### PR TITLE
fix: Fixes confirmation modal flickering bug

### LINKED ISSUE #11612: [Bug]: Confirmation for running action flickers through when running an action via cmd+enter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/5298848/156716756-b43ec012-efda-400a-82d1-8ed97f578cfd.mov

### Steps To Reproduce

1. Create a query
2. Mark it to require confirmation before running
3. Try to run the query by clicking on the run button in the editor. This pops the modal for confirmation.
4. Try to cmd+enter run the query from the editor. The modal flickers in and out and execution proceeds without confirmation.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by Irongade**
This PR fixes the flickering of the Modal confirmation when running an action via cmd+enter shortcut.

Fixes #11612 

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/modal-flickering-bug 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.82 **(0)** | 37.16 **(-0.01)** | 35.2 **(0)** | 56.16 **(0)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/RequestConfirmationModal.tsx [hunk 1]
```diff
@@ -44,7 +44,13 @@ class RequestConfirmationModal extends React.Component<Props> {
   };
 
   onKeyUp = (event: KeyboardEvent) => {
-    if (event.keyCode === Keys.ENTER) {
+    event.preventDefault();
+    // Sometimes calling the shortcut keys "Cmd + Enter" also triggers the onConfirm function below
+    // so We check if no multiple keys are being pressed currently before executing this block of code.
+    if (
+      !((event.metaKey || event.ctrlKey) && event.keyCode === Keys.ENTER) &&
```
Comment (AmanAgarwal041) [inline app/client/src/pages/Editor/RequestConfirmationModal.tsx:51]: Can this condition be changed to `!(event.metaKey || event.ctrlKey) && event.keyCode === Keys.ENTER` ?

Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/RequestConfirmationModal.tsx:51]: Instead of `(!((event.metaKey || event.ctrlKey) && event.keyCode === Keys.ENTER) && event.keyCode === Keys.ENTER)`

Comment (Irongade) [reply app/client/src/pages/Editor/RequestConfirmationModal.tsx:51]: No this will not work. The idea here is to catch when the user presses multiple keys e.g. CMD + ENTER.
`!((event.metaKey || event.ctrlKey) && event.keyCode === Keys.ENTER)`

Comment (Irongade) [reply app/client/src/pages/Editor/RequestConfirmationModal.tsx:51]: Thanks for this Aman! A great catch!
