### PR TITLE
fix: remove parent list widget from child widget level data

### LINKED ISSUE #20793: [Bug]: Remove parent list widget from level_ data to prevent cyclic dependency
https://user-images.githubusercontent.com/31691737/220094073-2c873e17-c0f0-49d1-8d3e-6588700e4de5.mov

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Avoid cyclic dependency in child widget when using level data to reference Parent List widget

Fixes #20793 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts [hunk 1]
```diff
@@ -904,7 +910,7 @@ class MetaWidgetGenerator {
           currentItem: currentViewData?.[0],
           // Uses any one of the row's container present on the List widget to
           // get the object of current row for autocomplete
-          currentView: `{{${metaContainerName}.data}}`,
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:907]: Doesn't this just removes it for autocomplete? I can still reference it right?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ServerSide_spec.js [hunk 2]
```diff
@@ -176,7 +176,7 @@ describe("List widget v2 - meta hydration tests", () => {
     cy.get(commonlocators.listPaginateNextButton).click({
       force: true,
     });
-    cy.wait(2000);
+    cy.wait(4000);
```
Comment (ashit-rath) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ServerSide_spec.js:179]: Why are we increasing the wait time here?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicChildWidgetInteraction_spec.js [hunk 3]
```diff
@@ -93,7 +93,7 @@ describe("List widget v2 - Basic Child Widget Interaction", () => {
 
     cy.PublishtheApp();
 
-    cy.wait(3000);
+    cy.wait(4000);
```
Comment (ashit-rath) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicChildWidgetInteraction_spec.js:96]: Maybe we should find a better we to identify the visual cue that we should be waiting for and then have those in place rather than waiting for longer time. This still does not guarantees non-flakyness

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts (hunk 1 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:907]: Yeah, that's a way to prevent users from adding it. We can out rightly remove the List widget from level data. It is possible that a sibling widget would like to access the list widget data using level data

Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:907]: or would you suggest a way to achieve this

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ClientSide_spec.js [hunk 4]
```diff
@@ -122,7 +132,30 @@ describe("List widget v2 - meta hydration tests", () => {
     cy.get(commonlocators.listPaginatePrevButton).click({
       force: true,
     });
-    cy.wait(3000);
+    cy.wait(300);
+    cy.waitUntil(() =>
```
Comment (ashit-rath) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ClientSide_spec.js:136]: Good job!

**Review by ashit-rath — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- No breakage of app or weird behavior on cyclic dependency

**Review by ashit-rath — APPROVED** [review]
