### PR TITLE
Resize canvas on delete widget

### LINKED ISSUE #1919: [Bug] Deleting a widget does not reset the canvas height
## Description
If the widget is at the bottom of the canvas, with a lot of empty space above it; When we delete this widget, the canvas height should reset, like it does when we drag and drop a widget when the canvas has empty space below the dropped widget.

### Steps to reproduce the behaviour:
1. Add a widget at the bottom of the canvas
2. Extend the canvas by dragging the widget further down, until the canvas increases in height to make the scrollbar appear.
3. Delete the widget.
4. The canvas height is still enough to have it scroll despite it having no widgets at the bottom.

### Important Details
 - Version: All
 - OS: All
 - Browser All

### PR DESCRIPTION
**Pull request by ofpiyush**
## Description
- Recalculate canvas rows on delete

Fixes #1919

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Added automated test.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ofpiyush** [comment]
@riodeuno this is ready for review now. Arpit is working on getting codefactor sorted

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 1]
```diff
@@ -402,11 +427,14 @@ export function* deleteSaga(deleteAction: ReduxAction<WidgetDelete>) {
...
       yield call(clearEvalPropertyCacheOfWidget, widgetName);
 
-      const finalWidgets = _.omit(
+      const finalWidgets: CanvasWidgetsReduxState = _.omit(
         widgets,
         otherWidgetsToDelete.map(widgets => widgets.widgetId),
       );
 
+      // Note: mutates finalWidgets
+      resizeCanvasToLowestWidget(finalWidgets, parentId);
```
Comment (riodeuno) [inline app/client/src/sagas/WidgetOperationSagas.tsx:436]: If this mutates, let's keep the contents here. I'm worried that another contributor might use this without knowing that this doesn't return anything.

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — DISMISSED** [review]

**Review by riodeuno — APPROVED** [review]
