### PR TITLE
Fix: Cypress tests for import application

### LINKED ISSUE #6769: [Bug] The cypress test for import application starts failing every time a new release is tagged.
## Description
We need to export a fresh app on the fly to used in `OrgImportApplication_spec.js` and test the import feature.

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
Improved `OrgImportApplication_spec.js` to export an app and test the import feature on the fly. Earlier it had a dependency on an application file from fixtures.

Fixes #6769 

## Type of change
- Fixes tests

## How Has This Been Tested?
- cypress tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by NandanAnantharamu — APPROVED** [review]
LGTM

File: app/client/src/pages/Applications/ApplicationCard.tsx [hunk 1]
```diff
@@ -356,16 +356,19 @@ export function ApplicationCard(props: ApplicationCardProps) {
...
-    link.target = "_blank";
     link.id = id;
     document.body.appendChild(link);
-    link.click();
+    // will fetch the file manually during cypress test run.
+    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+    // @ts-ignore
+    if (!window.Cypress) {
+      link.click();
+    }
```
Comment (rishabhsaxena) [inline app/client/src/pages/Applications/ApplicationCard.tsx:366]: nitpick: I guess we do without handling this case, the only issue would be that we fetch the file twice?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ExportApplication_spec.js [hunk 2]
```diff
@@ -28,6 +27,17 @@ describe("Export application as a JSON file", function() {
...
+    cy.get(`a[id=t--export-app-link]`).then((anchor) => {
+      const url = anchor.prop("href");
+      cy.request(url).then(({ headers }) => {
+        expect(headers).to.have.property("content-type", "application/json");
+        expect(headers).to.have.property(
+          "content-disposition",
+          `attachment; filename*=UTF-8''${appname}.json`,
+        );
+      });
+    });
```
Comment (rishabhsaxena) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ExportApplication_spec.js:40]: nitpick: We're also verifying this in the import flow, so we could omit it from here?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/OrgImportApplication_spec.js [hunk 3]
```diff
@@ -1,37 +1,68 @@
...
+    // eslint-disable-next-line cypress/no-unnecessary-waiting
+    cy.wait(2000);
+
+    cy.get(homePage.applicationCard)
+      .first()
+      .trigger("mouseover");
+    cy.get(homePage.appMoreIcon)
+      .first()
+      .click({ force: true });
+    cy.get(homePage.exportAppFromMenu).click({ force: true });
```
Comment (rishabhsaxena) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/OrgImportApplication_spec.js:26]: QQ: Does intercepting the get req on clicking a link not work here?

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/pages/Applications/ApplicationCard.tsx (hunk 1 above)
Comment (pranavkanade) [reply app/client/src/pages/Applications/ApplicationCard.tsx:366]: If I remove this, it might create problem on CI (trying to open a window).

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/OrgImportApplication_spec.js (hunk 3 above)
Comment (pranavkanade) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/OrgImportApplication_spec.js:26]: The problem here is  `"content-disposition"`.  It's not a straightforward axios GET request.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ExportApplication_spec.js (hunk 2 above)
Comment (pranavkanade) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ExportApplication_spec.js:40]: This is important actually. Rather I'd remove this check from `import` flow, although kept it there just for sanity check.

File: app/client/src/pages/Applications/ApplicationCard.tsx (hunk 1 above)
Comment (rishabhsaxena) [reply app/client/src/pages/Applications/ApplicationCard.tsx:366]: Got it, in that case may be we can construct a URL and fetch the contents directly, instead of clicking on the link in the test case? Another option might be to stub the function

**Review by rishabhsaxena — APPROVED** [review]

**Comment by pranavkanade** [comment]
Unrelated test case is failing -
https://github.com/appsmithorg/appsmith/issues/6589
