### PR TITLE
fix: Ensure Select Column Displays Data When Options Are Not Set

### LINKED ISSUE #35807: [Bug]: Data in a column of a table is coming up as empty, though data exists in the column
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In an existing application, [Regression app as well as Entry Criteria app on internal], the data in particular column/s in a table is coming up as empty

### Steps To Reproduce

1. Go to the [Entry Criteria app](https://internal.appsmith.com/app/qa-entry-criteria/homepage-6572bee19316452956030137?branch=master)
2. Choose an existing feature from the dropdown and go to the  Feature Impact tab.
3. Note that the Impact column is showing up empty, though there is data in the column
4. Try also with the [Regression app tagging calendar](https://internal.appsmith.com/app/appsmith-regression-app/tagging-calendar-660133674168a32134c426ec)
5. Note that the Tagging column is empty, though there is data in that column

### Public Sample App

_No response_

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/1720babd-5bff-4bf0-b406-c3fd9a6e80b2

### Version

Cloud

### PR DESCRIPTION
**Pull request by jacquesikot**
## Description
**Problem**
When using a table widget, changing a column to the "Select" type causes the data in that column to disappear unless the options property is explicitly set. This creates a poor user experience, as it appears that the data has been lost or the widget is malfunctioning.

**Solution**
We have implemented a fallback mechanism to ensure a smoother user experience. If no options are set in the property pane, the label inside the select cell will now default to displaying the existing value. This ensures that the data remains visible, even in the absence of predefined options.

Fixes #35807

## Automation

/ok-to-test tags="@tag.Widget, @tag.Select, @tag.Binding, @tag.Table, @tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10513374411>
> Commit: 1e89468e8345f2fc351c100428dca76a7a455dbc
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10513374411&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Widget, @tag.Select, @tag.Binding, @tag.Table, @tag.Sanity`
> Spec:
> <hr>Thu, 22 Aug 2024 19:43:53 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Enhanced the select column in the table widget to return a default value when no options are available.

- **Bug Fixes**
  - Improved robustness of the select cell component to prevent errors when the options array is empty.

- **Tests**
  - Updated and reorganized test cases for the select column to improve clarity and specificity.
  - Introduced a new test case to validate default value behavior when no options are provided.

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Select1_spec.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ describe(
       _.table.AddSampleTableData();
     });
 
-    it("1. should check that select column is available in the column dropdown options", () => {
+    it.only("1. should check that select column is available in the column dropdown options", () => {
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Select1_spec.ts:19]: Please remove only as it will only run this test case.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Select1_spec.ts [hunk 2]
```diff
@@ -31,7 +31,14 @@ describe(
       cy.get(".t--property-pane-section-collapse-events").should("exist");
     });
 
-    it("2. should check that options given in the property pane is appearing on the table", () => {
+    it.only("2. should check that select column returns value if no option is provided", () => {
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Select1_spec.ts:34]: Same comment as previous for only.

**Review by sagar-qa007 — CHANGES_REQUESTED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Select1_spec.ts (hunk 1 above)
Comment (jacquesikot) [reply app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Select1_spec.ts:19]: My bad, fixing now

**Review by rahulbarwal — APPROVED** [review]

**Comment by btsgh** [comment]
1. Imported the Regression application and checked for the Tagging calendar issue mentioned in the original bug. Works fine for column type set as Select.
2. Changed the column types from Select to Plain Text and viceversa and saw that data is retained
3. Created a new application, added a crud page, and changed the column type from Plain Text to Select for a particular column. Works fine. 
4. Moved it back to Plain Text, works fine. 
5. Deployed the apps and checked data in deploy mode. Works fine. 
6. Forked Regression app to another workspace and tested that the column data shows up fine for column type  set as Select

**Review by sagar-qa007 — DISMISSED** [review]

**Comment by sagar-qa007** [comment]
@jacquesikot Please check test case failure.

**Review by rahulbarwal — APPROVED** [review]
