### PR TITLE
fix: updated condition select widget

### LINKED ISSUE #8959: [Bug]: Cannot read properties of undefined (reading 'type') error occurs when the user groups widget as container and pressing cmd+A
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user groups few widgets into container and pasting the last copied widget to the canvas and deleting the last pasted widget and pressing cmd+A the following error is displayed both in application and console log

https://loom.com/share/5a146318bb0644968d66b4021eabffe9

### Steps To Reproduce

1.Launch Appsmith app in release environment 
2.Drag and drop container widget 
3.Copy the container widget 
4.Place any of the widget in the container widget 
5. Place any other widget next to container 
6. Draw and select the widget which is next to container and release the mouse inside the container inorder to Group 
7. Click on Group icon 
8. Now paste the copied container widget on the canvas - which is copied at step 3
9. Delete the copied widget 
10. Press Cmd+A and observe

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> fixed cannot read properties of undefined (reading 'type') error occurs when the user groups widget as container and pressing cmd+A 

Fixes #8959

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: bug/fixed-widget-selection 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.63 **(0)** | 36.35 **(-0.01)** | 33.09 **(0)** | 55.15 **(-0.01)**
 :red_circle: | app/client/src/sagas/WidgetSelectionSagas.ts | 90.6 **(-0.68)** | 88.42 **(0.25)** | 100 **(0)** | 89.84 **(-0.79)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**</details>

### CODE REVIEW

File: app/client/src/sagas/WidgetSelectionSagas.ts [hunk 1]
```diff
@@ -133,7 +133,7 @@ function* getAllSelectableChildren() {
   const canvasId: string = yield call(getLastSelectedCanvas);
   let allChildren: string[] = [];
   const selectGrandChildren: boolean = lastSelectedWidget
-    ? widgetLastSelected.type === WidgetTypes.LIST_WIDGET
+    ? widgetLastSelected && widgetLastSelected.type === WidgetTypes.LIST_WIDGET
```
Comment (jsartisan) [inline app/client/src/sagas/WidgetSelectionSagas.ts:136]: It's okay for now. But For future, can you simply use `get` from lodash like
`get(widgetLastSelected, 'type')`

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Verified this fix and it is working as expected now
