### PR TITLE
fix: removing unnecessary status api call

### LINKED ISSUE #31228: [Bug]: Duplicate /status api call when git modal is opened
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When git modal is opened, git status api is called twice

### Steps To Reproduce

1. Open git modal
2. Open network debugger and see the issue

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

All

### PR DESCRIPTION
**Pull request by brayn003**
## Description
Removing duplicate status API on opening modal

#### PR fixes following issue(s)

Fixes #31228

## Automation

/ok-to-test tags="@tag.Git"

## Summary by CodeRabbit

- **Refactor**
    - Improved the initialization process of Git status during deployment and merge operations for enhanced performance.
    - Optimized logging and code flow in the `getStatus` method for better monitoring and troubleshooting.
    - Introduced elapsed time logging for various operations within the method.

> [!IMPORTANT]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8328565497>
> Commit: `b8138d55279aaa943e8d747286663c0d5c71d705`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8328565497&attempt=2" target="_blank">Click here!</a>
> All cypress tests have passed 🎉🎉🎉

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 1]
```diff
@@ -1878,100 +1878,126 @@ private Mono<GitStatusDTO> getStatus(
...
+                    log.debug("saveApplicationToLocalRepo took: {}", tuple.getT1());
+                    return gitExecutor
+                            .getStatus(tuple.getT2().getT1(), finalBranchName)
+                            .elapsed()
+                            .flatMap(tuple2 -> {
+                                log.debug("git status took: {}", tuple2.getT1());
+                                // Remove any files which are copied by hard resetting the repo
+                                try {
+                                    // TODO: Why are we doing reset to last commit always???
+                                    // TODO: We can get rid of that - Anagh
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1981]: Is this comment required?

Comment (sondermanish) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1981]: Nope, not anymore

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 2]
```diff
@@ -2010,10 +2036,7 @@ private Mono<GitStatusDTO> getStatus(
                     }
                     return sendUnitExecutionTimeAnalyticsEvent(flowName, elapsedTime, currentUser, app)
                             .thenReturn(gitStatusDTO);
-                })
-        // .subscribe(sink::success, sink::error, null, sink.currentContext())
-        ;
-        // });
+                });
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2039]: Why are we removing this? The timeout can cause the API fail and for larger apps this can be come a problem.

Comment (sondermanish) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2039]: this was already a commented out code, I removed the commented code.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 3]
```diff
@@ -1878,100 +1878,126 @@ private Mono<GitStatusDTO> getStatus(
...
+                .switchIfEmpty(Mono.error(new AppsmithException(AppsmithError.GIT_GENERIC_ERROR)))
                 .cache();
 
         /*
            1. Copy resources from DB to local repo
            2. Fetch the current status from local repo
         */
-        Mono<GitStatusDTO> statusMono = getGitApplicationMetadata(defaultApplicationId)
-                .flatMap(gitApplicationMetadata -> {
+        Mono<GitStatusDTO> statusMono = Mono.zip(getGitApplicationMetadata(defaultApplicationId), branchedAppMono)
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1898]: QQ, is this going to be the first DB call in any of the flows? Asking because of the transaction creation issue when trying to start two of them in parallel at root level.

Comment (sondermanish) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1898]: This would mostly be the first call where ever we would require to interact with the git remote (which is nearly most of the APIs). otherwise the branched app itself is adequate for the job.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 4]
```diff
@@ -1994,11 +2020,11 @@ private Mono<GitStatusDTO> getStatus(
                 .name(AnalyticsEvents.GIT_STATUS.getEventName())
                 .tap(Micrometer.observation(observationRegistry));
 
-        return // Mono.create(sink -> {
-        Mono.zip(statusMono, sessionUserService.getCurrentUser(), branchedAppMono)
+        return Mono.zip(statusMono, sessionUserService.getCurrentUser(), branchedAppMono)
                 .elapsed()
                 .flatMap(objects -> {
                     Long elapsedTime = objects.getT1();
+                    log.debug("Multi mono took: {}", elapsedTime);
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2027]: Why are we trying to log timing in logs. This is not meant to reach prod, please use metrics instead.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 3 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1898]: Sorry, I didn't understand that response. If that is the case should we not remove the zip?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 5]
```diff
@@ -1878,99 +1878,110 @@ private Mono<GitStatusDTO> getStatus(
         if (StringUtils.isEmptyOrNull(branchName)) {
             return Mono.error(new AppsmithException(AppsmithError.INVALID_PARAMETER, FieldName.BRANCH_NAME));
         }
+
         final String finalBranchName = branchName.replaceFirst("origin/", "");
         Mono<Application> branchedAppMono = applicationService
                 .findByBranchNameAndDefaultApplicationId(
                         finalBranchName, defaultApplicationId, applicationPermission.getEditPermission())
+                .onErrorResume(error -> {
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1886]: Why are we adding a handling that will make users get to an unexpected state?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 6]
```diff
@@ -1878,99 +1878,110 @@ private Mono<GitStatusDTO> getStatus(
...
-                            }
-                        }))
+                .elapsed()
+                .flatMap(tuple -> {
+                    log.debug("saveApplicationToLocalRepo took: {}", tuple.getT1());
+                    return gitExecutor
+                            .getStatus(tuple.getT2().getT1(), finalBranchName)
+                            .elapsed()
+                            .flatMap(tuple2 -> {
+                                log.debug("git status took: {}", tuple2.getT1());
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1967]: There still seem to be log lines for timing sprinkled all over.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 5 above)
Comment (sondermanish) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1885]: this snippet was always there
