### PR TITLE
fix: add migration for removed table default selected row

### LINKED ISSUE #7258: [Bug] Table widget: Revert default selected row migration
## Description

We have to undo the migration from the table widget such that the default selected row for the older tables remain as it is and for the new table first drag and drop should have the 0th row default selected

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> Add migration for removed default selected row in the table.

Fixes #7258

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: bug/revert-table-row-migration 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.29 **(0.02)** | 36.34 **(0.02)** | 33.45 **(0.02)** | 54.83 **(0.02)**
 :green_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 75.89 **(0.3)** | 66.91 **(0.24)** | 71.72 **(0.59)** | 75 **(0.33)**</details>

### CODE REVIEW

**Comment by marks0351** [comment]
@techbhavin we need to write a reverse migration as well for this. to revert the table data back to its previous state.

File: app/client/src/constants/WidgetConstants.tsx [hunk 1]
```diff
@@ -106,7 +106,7 @@ export const layoutConfigurations: LayoutConfigurations = {
   FLUID: { minWidth: -1, maxWidth: -1 },
 };
 
-export const LATEST_PAGE_VERSION = 36;
```
Comment (marks0351) [inline app/client/src/constants/WidgetConstants.tsx:109]: you should not decrease versions. instead write a new migration to revert the old migration.

**Review by marks0351 — CHANGES_REQUESTED** [review]
@techbhavin we need to write a reverse migration as well for this. to revert the table data back to its previous state.

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 2]
```diff
@@ -839,12 +839,45 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
...
   }
 
   return currentDSL;
 };
 
+export const revertTableDefaultSelectedRow = (
+  currentDSL: ContainerWidgetProps<WidgetProps>,
+) => {
+  if (currentDSL.type === WidgetTypes.TABLE_WIDGET) {
+    currentDSL.defaultSelectedRow = undefined;
```
Comment (marks0351) [inline app/client/src/utils/WidgetPropsUtils.tsx:857]: there should be an additional check to change only "0" to undefined.

also @somangshu this will break for users who intentionally have set default selected row as 0. they will not have default selected row.

**Review by marks0351 — CHANGES_REQUESTED** [review]

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 3]
```diff
@@ -839,12 +839,67 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
 
   if (currentDSL.version === 35) {
     currentDSL = migrateInputValidation(currentDSL);
+    currentDSL.version = 36;
+  }
+
+  if (currentDSL.version === 36) {
+    currentDSL = migrateTableVersion(currentDSL);
```
Comment (marks0351) [inline app/client/src/utils/WidgetPropsUtils.tsx:846]: replace migrateTableDefaultSelectedRow with migrateTableVersion. and add only one new migration(reverse migration). mention comments in migrateTableVersion that this is done to stop reverse migrations for apps that did not use migrateTableDefaultSelectedRow to migrate.

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 4]
```diff
@@ -839,12 +839,67 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
...
+  }
+  if (currentDSL.children && currentDSL.children.length) {
+    currentDSL.children = currentDSL.children.map((child) =>
+      migrateTableVersion(child),
+    );
+  }
+  return currentDSL;
+};
+
+export const migrateTableDefaultSelectedRow = (
```
Comment (marks0351) [inline app/client/src/utils/WidgetPropsUtils.tsx:889]: remove this migration but add comments in migrateTableVersion mentioning why this is done.

**Review by marks0351 — CHANGES_REQUESTED** [review]

**Review by marks0351 — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@marks0351 Migration has been tested on the deploy preview and working fine.
