### PR TITLE
fix: Preserve entity explorer state on page refresh

### LINKED ISSUE #11015: [Task]: New entity explorer bug fixes and improvements

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

This PR mainly includes the feature of preserving the state of entity explorer open items, which covers PAGES, WIDGETS, QUERIES/JS and DATASOURCES main entities only. Also, includes following fixes.

* Fixed flickering issue of widget switcher
* Added 'Add <Entity>' button below all sections of entity explorer
* Added new empty state of entity explorer sections
* Changed Query/JS tooltip text

Fixes #11015

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested locally for the UI fixes

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: bug-fix/11015-new-entity-explorer-fixes-and-improvements 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.87 **(0.05)** | 37.23 **(0.07)** | 35.22 **(0.01)** | 56.18 **(0.04)**
 :green_circle: | app/client/src/ce/constants/messages.ts | 77.11 **(0.21)** | 100 **(0)** | 32.09 **(0.62)** | 82.28 **(0.18)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Datasources.tsx | 90.24 **(-1.87)** | 57.14 **(-5.36)** | 42.86 **(-7.14)** | 89.47 **(-1.96)**
 :sparkles: :new: | **app/client/src/pages/Editor/Explorer/common.tsx** | **90.91** | **100** | **0** | **90.91**
 :green_circle: | app/client/src/pages/Editor/Explorer/helpers.tsx | 84.91 **(8.44)** | 52.44 **(2.44)** | 66.67 **(16.67)** | 82.61 **(9.28)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Entity/Placeholder.tsx | 60 **(-40)** | 100 **(0)** | 0 **(-100)** | 60 **(-40)**
 :green_circle: | app/client/src/pages/Editor/Explorer/Entity/index.tsx | 91.76 **(1.17)** | 85.71 **(2.85)** | 84.21 **(0)** | 91.36 **(1.24)**
 :green_circle: | app/client/src/pages/Editor/Explorer/Files/index.tsx | 76.32 **(1.32)** | 33.33 **(16.66)** | 40 **(-10)** | 80.56 **(0.56)**
 :green_circle: | app/client/src/pages/Editor/Explorer/Pages/index.tsx | 81.67 **(1.31)** | 66.67 **(4.17)** | 42.86 **(4.4)** | 81.67 **(1.31)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Widgets/WidgetGroup.tsx | 94.12 **(-5.88)** | 74.65 **(0.65)** | 100 **(0)** | 93.94 **(-6.06)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/Explorer/Widgets/WidgetGroup.tsx [hunk 1]
```diff
@@ -18,32 +27,43 @@ type ExplorerWidgetGroupProps = {
...
   const widgets = useSelector(selectWidgetsForCurrentPage);
   const guidedTour = useSelector(inGuidedTour);
-
-  const childNode = (
-    <EntityPlaceholder step={props.step}>
-      Click the <strong>+</strong> icon above to add widgets
-    </EntityPlaceholder>
-  );
+  let isWidgetsOpen = getExplorerStatus(applicationId, "widgets");
+  if (isWidgetsOpen === null) {
```
Comment (arunvjn) [inline app/client/src/pages/Editor/Explorer/Widgets/WidgetGroup.tsx:35]: Minor: 
```
if(isWidgetsOpen === null || guidedTour) {
   isWidgetsOpen = guidedTour || widgets?.children?.length === 0;
   saveExplorerStatus(applicationId, "widgets", isWidgetsOpen);
}
```

We can remove else if

**Review by arunvjn — APPROVED** [review]

**Review by arunvjn — APPROVED** [review]

**Review by arunvjn — APPROVED** [review]
