### PR TITLE
fix: migration for encryption

### LINKED ISSUE #24267: [Bug] Decryption failure causing instance initiation failure in migration stage. Unable to invoke Cipher due to bad padding
After the nightly image update on appsmith-ee  v1.9.20.5-SNAPSHOT both the nightly ee test instances are down due to the encryption keys error. This happened while applying migrations after the update.

`appsmithith-ee-fat-nightly-https | backend stdout | Caused by: io.mongock.api.exception.MongockException: Error in method[Migration109TransferToDatasourceStorage.executeMigration] : Unable to invoke Cipher due to bad padding`

### PR DESCRIPTION
**Pull request by tkAppsmith**
#### PR fixes following issue(s)
Fixes #24267
#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration013UnsetEncryptionVersion2Fields.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
+package com.appsmith.server.migrations.db.ce;
+
+import com.appsmith.external.models.Datasource;
+import com.appsmith.external.models.QAuthenticationDTO;
+import com.appsmith.external.models.QDatasource;
+import com.appsmith.external.models.QDatasourceConfiguration;
+import com.appsmith.server.constants.FieldName;
+import com.appsmith.server.migrations.utils.CompatibilityUtils;
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration013UnsetEncryptionVersion2Fields.java:8]: Nit: Some of these imports seem unused now

**Review by nidhi-nair — APPROVED** [review]

**Comment by sondermanish** [comment]
Ci test isn't required for migration, skipping these tests

**Comment by nidhi-nair** [comment]
Force merging because ok-to-test is irrelevant here
