### PR TITLE
fix: Using an html tag within a Text widget to access a web page, without the https:// appended causes application to crash

### LINKED ISSUE #18204: [Bug]: Using an html tag within a Text widget to access a web page, without the https:// appended causes application to crash
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I use an html tag within a Text widget and try to access google web page using only www.google.co.in, ... application crashes

If I use with https:// appended at the start, it works fine

Expected behavior - even without the https:// appended, it should work. 

### Steps To Reproduce

1. Drag and drop a text widget.
2. In the property pane, for the text to be displayed, use an html tag within a Text widget and try to access google web page using only www.google.co.in
3. Click on Google in the text widget.  The application crashes.  
4. Note that the url that the application tries to access is - 
https://release.app.appsmith.com/app/release-nov-16/textwidget-6374e05855c68b4cc232c47b/www.google.co.in

Expected behavior: Application should not crash. The url that the application tries to access should be modified to the right one. Https:// should be automatically appended to the url.
Note: If we directly enter the link like this - www.google.co.in - in the text widget, it works fine.

### Public Sample App

_No response_

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/z4bOHTvbS1c8xM6d

### Version

Production

### PR DESCRIPTION
**Pull request by jsartisan**
## Description
On using anchor with href without `https` or `http`, It creates invalid URL which leads to 404 page. This PR fixes that invalid URL.

Fixes #18204 

## Type of change

- Bug fix

## How Has This Been Tested?
- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/TextWidget/component/filters/LinkFilter.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    if (name === "href") {
+      return addHttpIfMissing(value);
+    }
+
+    return value;
+  }
+
+  node(name: string, node: HTMLElement): HTMLElement {
+    if (name === "a") {
+      node.setAttribute("target", "_blank");
```
Comment (keyurparalkar) [inline app/client/src/widgets/TextWidget/component/filters/LinkFilter.ts:15]: Won't this line always open the link in new tab? Since we are setting `target='_blank'`. Should this be dependent on user?

File: app/client/src/widgets/TextWidget/component/helpers.tsx [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+ * @returns
+ */
+export const addHttpIfMissing = (url: string) => {
+  if (!url) {
+    return url;
+  }
+  if (url.indexOf("http") === 0) {
+    return url;
+  }
+  return `http://${url}`;
```
Comment (keyurparalkar) [inline app/client/src/widgets/TextWidget/component/helpers.tsx:14]: Why are we returning `http` instead of `https`?

File: app/client/src/widgets/TextWidget/component/helpers.tsx [hunk 3]
```diff
@@ -0,0 +1,15 @@
+/**
+ * add http if missing
+ *
+ * @param url
+ * @returns
+ */
+export const addHttpIfMissing = (url: string) => {
+  if (!url) {
+    return url;
```
Comment (keyurparalkar) [inline app/client/src/widgets/TextWidget/component/helpers.tsx:9]: @jsartisan does this `if block` returns string if it's not an URL?

File: app/client/src/widgets/TextWidget/component/filters/LinkFilter.ts (hunk 1 above)
Comment (jsartisan) [reply app/client/src/widgets/TextWidget/component/filters/LinkFilter.ts]: Right. Removed the target _blank.

File: app/client/src/widgets/TextWidget/component/helpers.tsx (hunk 3 above)
Comment (jsartisan) [reply app/client/src/widgets/TextWidget/component/helpers.tsx:9]: If the URL is undefined, null, or false, it will just return whatever it was. So now we don't have to do `return null` or `return false` etc.

File: app/client/src/widgets/TextWidget/component/helpers.tsx (hunk 2 above)
Comment (jsartisan) [reply app/client/src/widgets/TextWidget/component/helpers.tsx:14]: The main reason is some sites may not have HTTPS and when they have HTTPS, they always put a redirect from HTTP to HTTPS. We can't know if they have HTTP or HTTPS, so we can just put HTTP for the unknown.

File: app/client/src/widgets/TextWidget/component/filters/LinkFilter.ts (hunk 1 above)
Comment (keyurparalkar) [reply app/client/src/widgets/TextWidget/component/filters/LinkFilter.ts]: Have we considered scenarios apart from `anchor` tag? like tags mentioned in this [link](https://www.w3schools.com/tags/att_href.asp#:~:text=For%20and%20%3Carea,relative%20URLs%20on%20a%20page.). @jsartisan are there any use cases that you found were user might be referring to a file like the `link`tag in the above URL.

**Review by keyurparalkar — APPROVED** [review]
