### PR TITLE
fix: Google sheets Bulk insert of empty array returns an error

### LINKED ISSUE #8924: [Bug]: Google sheets Bulk insert of empty array returns an error
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When executing a Google sheets Bulk insert rows query, an error is returned if the data array is empty. This is highly annoying as it requires me to effectively run the script that generates the dataset in the submit button and disable the button if the dataset is empty. Not DRY and violates the principle of least surprise too I'd say.

It would be much more natural if an empty array was just a "noop". 

### Steps To Reproduce

1. Create a Google sheets query
2. Set the Method to Bulk insert rows and add the other standard query fields
3. Set the Row object to `[]`
4. Run the query

The result is the following response:
```
[test_bulk_insert]
Execution failed with status 5000
Expected an array of row objects
```

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by leotom2000**
## Description

> When executing a Google sheets Bulk insert rows query, an error is returned if the data array is empty.

Fixes #8924

## Type of change
- Bug fix (non-breaking change which fixes an issue)   

 
## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+    }
+
+    /**
+     * To Test if it passes the Non-empty Mono criteria,
+     * down the line the code may fail which is not the scope of testing
+     * that means, no code changes are done after empty Mono handling condition
+     * for which this test is intended to run.
+     */
+    @Test
+    public void testBulkAppendHandleNonEmptyMonoExecutePrerequisites() {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java:50]: We can get rid of this test. Here we seem to be testing for assertion error, which is so generic in nature that every failure would cause this test to pass. The other tests that test for behaviour automatically ake care of this scenario.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+
+        return methodConfig;
+    }
+
+    /**
+     * DatasourceConfiguration object need for creating OAuth
+     * @return
+     */
+    private DatasourceConfiguration createDatasourceConfiguration() {
+        DBAuth authDTO = new DBAuth();
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java:106]: Please use the correct type here, since this is specifically meant for OAuth2

**Review by nidhi-nair — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java (hunk 1 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java:50]: removed

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java (hunk 2 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java:106]: fixed this, by removing DBAuth related items

**Review by nidhi-nair — APPROVED** [review]
