### PR TITLE
fix: Add sheetjs package for parsing xls/xlsx file. Remove exceljs

### LINKED ISSUE #23405: [Task]: Use SheetJS for parsing xls/xlsx files in DocumentViewer widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The current package, exceljs, supports only xlsx files. We need to support xls files in filepicker widget. Thus creating this issue to remove exceljs from existing widgets and replace it with SheetJS/XLSX package which supports both xls/xlsx files. Thus, only one package will be used for parsing excel files across the app.

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #23405

Test Plan:

Steps to import an excel file into document viewer:
1. Import a file using file picker widget in base64 format.
2. Bind filepicker.files[0].data to document viewer data.

Test cases to cover
1. Import an .xls file into document viewer and it should work.
2. Import an .xlsx file into document viewer and it should work
3. Import an .xlsx file, verify it renders fine. Changing the file data to an .xls file. Verify it renders fine without having the need to use another document viewer widget

### CODE REVIEW

File: app/client/src/widgets/DocumentViewerWidget/component/index.tsx [hunk 1]
```diff
@@ -60,6 +60,7 @@ const getBlob = (docUrl: string) => {
     const blob = new Blob([uInt8Array], { type: mimeType });
     return blob;
   } catch (error) {
+    console.log("***", "error parsing blob", error);
     return;
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/DocumentViewerWidget/component/index.tsx:64]: I will remove this console log. It isn't required

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 2]
```diff
@@ -69,87 +69,90 @@ const chars = [
...
-        workbook.current.eachSheet((sheet, id) => {
-          newSheets.push({ name: sheet.name, id });
-        });
-        setSheets(newSheets);
-        // get 1st sheet data
-        getSheetData(1);
+      const workbook = XLSX.read(buffer, { type: "array" });
+
+      const sheetNames: string[] = [];
+      workbook.SheetNames.map((name, index) => {
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:90]: Done

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 3]
```diff
@@ -69,87 +69,90 @@ const chars = [
...
-  id: number;
-};
-
 export default function XlsxViewer(props: { blob?: Blob }) {
-  const [sheets, setSheets] = useState([] as sheetsDataType[]);
+  const [sheetNames, setSheetNames] = useState([] as string[]);
   const [tableData, setTableData] = useState([]);
   const [headerData, setHeaderData] = useState([] as Column[]);
-  const workbook = useRef(new Excel.Workbook());
+  const jsonData: any[] = [];
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:84]: Done. Thanks for pointing it out.

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 4]
```diff
@@ -69,87 +69,90 @@ const chars = [
...
 
-  // when user click on another sheet, re-generate data
+  // // when user click on another sheet, re-generate data
   const updateSheet = useCallback(
-    (sheetId) => () => {
-      getSheetData(sheetId);
+    (sheetIndex) => () => {
+      getSheetData(sheetIndex);
     },
     [],
```
Comment (rajatagrawal) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:157]: Is dependency array required here as well @vsvamsi1 ?

Comment (rajatagrawal) [reply app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:157]: Had an offline discussion with @vsvamsi1 . This is not required now.

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 5]
```diff
@@ -69,87 +69,90 @@ const chars = [
...
+
+  // get provided sheet data, read all row and columns
+  const getSheetData = useCallback((sheetIndex: number) => {
+    // collect all row data
+    const body = parseTableBody(jsonData[sheetIndex]);
+    const headers = parseTableHeaders(jsonData[sheetIndex]);
+
+    setTableData(body);
+    setHeaderData(headers);
   }, []);
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:150]: Since this is a state variable now, adding it to dependency array isn't required

File: app/client/package.json [hunk 6]
```diff
@@ -309,6 +308,7 @@
     "ts-jest-mock-import-meta": "^0.12.0",
     "ts-loader": "^9.4.1",
     "webpack-merge": "^5.8.0",
-    "workbox-webpack-plugin": "^6.5.3"
+    "workbox-webpack-plugin": "^6.5.3",
+    "xlsx": "https://cdn.sheetjs.com/xlsx-0.19.3/xlsx-0.19.3.tgz"
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/package.json:313]: Had an offline discussion with @vsvamsi1 . We can keep as it is for now. If the CI build fails or the package owners decide to stop supporting the CDN server, we can store the library using vendoring in our codebase.

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 7]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
   }
   return chars[index % 26];
 };
 
-type sheetsDataType = {
-  name: string;
-  id: number;
-};
+interface DocumentViewerState {
+  jsonData: any[];
```
Comment (sbalaji1192) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:80]: can we not use any type?

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 8]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
 
-  // get provided sheet data, read all row and columns
-  const getSheetData = useCallback((sheetId: number) => {
-    const worksheet = workbook.current.getWorksheet(sheetId);
-    // collect all row data
+  async function parseBlob(blob: Blob) {
+    const buffer = await blob.arrayBuffer();
+    const workbook = XLSX.read(buffer, { type: "array" });
+    const jsonData = convertWorkbookDataToJSON(workbook);
+    return jsonData;
```
Comment (sbalaji1192) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:135]: nit: no need to create a new variable

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 9]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
       <div>
-        {sheets.map((sheet) => (
-          <button key={sheet.id} onClick={updateSheet(sheet.id)}>
-            {sheet.name}
+        {state.sheetNames.map((name, index) => (
+          <button
+            key={index}
+            onClick={() => {
+              // state.sheetIndex = index
+              console.log("***", "clicking on index ", index);
```
Comment (sbalaji1192) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:216]: Please remove this console log

Comment (sbalaji1192) [reply app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:216]: remove commented lines as well

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 10]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
-        workbook.current.eachSheet((sheet, id) => {
-          newSheets.push({ name: sheet.name, id });
+    if (!props.blob) {
+      // Todo : figure out whot to do
+      resetStates();
+      setState(Object.assign({}, state)); // state gets reset above
+    } else {
+      parseBlob(props.blob)
+        .then((jsonData: { sheetsData: any; sheetNames: string[] }) => {
+          state.jsonData = jsonData.sheetsData;
```
Comment (sbalaji1192) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:108]: we should not update the state here. should create a new state

**Review by sbalaji1192 — COMMENTED** [review]
Can you also remove `any ` and use `unknown` whereever possible?

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 11]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
-  const workbook = useRef(new Excel.Workbook());
+  const defaultTableData: Record<number, []> = { "-1": [] };
+  const [sheetIndex, setSheetIndex] = useState<number>(-1);
+  const [state, setState] = useState<DocumentViewerState>({
+    jsonData: [],
+    sheetNames: [],
+    currentTableData: [],
+    currentTableHeaders: [],
+    tableData: Object.assign({}, defaultTableData),
+    headerData: Object.assign({}, defaultTableData),
```
Comment (vsvamsi1) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:97]: Can you use the spread operator?

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 12]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
+
+          state.jsonData.forEach((data, index) => {
+            state.tableData[index] = parseTableBody(data);
+            state.headerData[index] = parseTableHeaders(data);
+          });
+
+          if (jsonData.sheetsData.length > 0) {
+            state.currentTableData = state.tableData[localSheetIndex];
+            state.currentTableHeaders = state.headerData[localSheetIndex];
+          }
```
Comment (vsvamsi1) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:120]:
```
const stateCopy = {...state}
stateCopy.jsonData

```

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 13]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
+  };
+
+  const resetStates = () => {
+    state.jsonData = [];
+    state.currentTableData = [];
+    state.currentTableHeaders = [];
+    state.sheetNames = [];
+    state.tableData = Object.assign({}, defaultTableData);
+    state.headerData = Object.assign({}, defaultTableData);
+    setSheetIndex(-1);
```
Comment (vsvamsi1) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:162]: resetStates
```
setState(copy)
```

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 14]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
+          if (jsonData.sheetsData.length > 0) {
+            state.currentTableData = state.tableData[localSheetIndex];
+            state.currentTableHeaders = state.headerData[localSheetIndex];
+          }
+          setState(Object.assign({}, state));
+          setSheetIndex(localSheetIndex);
+        })
+        .catch(() => {
+          resetStates();
+          setState(Object.assign({}, state));
```
Comment (vsvamsi1) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:126]: can you move this line   to  resetState       setState(Object.assign({}, state));

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx [hunk 15]
```diff
@@ -69,100 +69,156 @@ const chars = [
...
+
+    workbook.SheetNames.forEach((name, index) => {
+      sheetNames.push(name);
+
+      const result = XLSX.utils.sheet_to_json(
+        workbook.Sheets[workbook.SheetNames[index]],
+        { header: 1 },
+      );
+      sheetsData.push(result);
+    });
```
Comment (vsvamsi1) [inline app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx:150]: const sheedNames =  workbook.SheetNames.map((name,index) => name)
const sheedData=  workbook.SheetNames.map((name,index) => XLSX.utils.sheet_to_json(
        workbook.Sheets[workbook.SheetNames[index]],
        { header: 1 },
      );)

**Review by vsvamsi1 — APPROVED** [review]

**Review by vsvamsi1 — DISMISSED** [review]

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx (hunk 10 above)
Comment (rajatagrawal) [reply app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx]: Done

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx (hunk 9 above)
Comment (rajatagrawal) [reply app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx]: Done

File: app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx (hunk 7 above)
Comment (rajatagrawal) [reply app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx]: this variable is removed

**Review by vsvamsi1 — APPROVED** [review]
