### PR TITLE
fix: safeguarding selected widgets saga

### LINKED ISSUE #7119: [Bug] TypeError: Cannot read property 'type' of undefined
Sentry Issue: [APPSMITH-122](https://sentry.io/organizations/appsmith/issues/2588392908/?referrer=github_integration)

```
TypeError: Cannot read property 'type' of undefined
  at call (sagas/SnipingModeSagas.ts:44:26)
  at apply (components/editorComponents/SnipeableComponent.tsx:59:7)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
added a check if selected widget even exists

Fixes #7119 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
This is extremely rare case, couldn't find a way to reproduce and test.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/sniping-mode-saga-safeguarding 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.01 **(0)** | 36.88 **(0)** | 33.94 **(-0.01)** | 55.56 **(0)**
 :red_circle: | app/client/src/constants/messages.ts | 70.88 **(-0.03)** | 100 **(0)** | 12.16 **(-0.08)** | 78.55 **(-0.29)**
 :red_circle: | app/client/src/sagas/SnipingModeSagas.ts | 17.54 **(0.27)** | 3.45 **(-0.55)** | 40 **(0)** | 18.18 **(0.26)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**</details>

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

File: app/client/src/sagas/SnipingModeSagas.ts [hunk 1]
```diff
@@ -37,6 +41,14 @@ export function* bindDataToWidgetSaga(
     action.payload.widgetId
   ];
 
+  if (!selectedWidget || !selectedWidget.type) {
+    Toaster.show({
```
Comment (rishabhsaxena) [inline app/client/src/sagas/SnipingModeSagas.ts:45]: nit: just curious when this can happen, should we add a comment here in case we have a specific scenario?

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/sagas/SnipingModeSagas.ts (hunk 1 above)
Comment (pranavkanade) [reply app/client/src/sagas/SnipingModeSagas.ts:45]: Not really. Don't have a clue why this happened. Looking at the logs I thought it's inner widget of a list, but no luck.

Comment (pranavkanade) [reply app/client/src/sagas/SnipingModeSagas.ts:45]: according to this - https://sentry.io/organizations/appsmith/issues/2588392908/events/64d2e826799f4592b3083f70255c7cde/events/?project=1546547
It was only seen twice.

**Review by rishabhsaxena — APPROVED** [review]

**Review by sbalaji1192 — APPROVED** [review]
