### PR TITLE
Bug/api editor datasources

### LINKED ISSUE #4768: [Bug] Api path does not get displayed on opening the property pane
## Description
The path of the api goes missing randomly when switching between APIs or editing APIs 

### Steps to reproduce the behaviour:
https://user-images.githubusercontent.com/12022471/119972374-bfaf3c00-bfcf-11eb-8944-23ae28ce3974.mov

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fixed API bug when the a saved datasource with a trailing / is used to build its URL

Fixes #4768 

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: bug/api_editor_datasources 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.64 **(0.04)** | 32.71 **(0.06)** | 29.78 **(0.02)** | 52.16 **(0.05)**
 :green_circle: | app/client/src/sagas/ApiPaneSagas.ts | 15.28 **(0.87)** | 1.87 **(0.23)** | 7.41 **(0.27)** | 17.2 **(1.12)**
 :red_circle: | app/client/src/utils/ApiPaneUtils.tsx | 100 **(0)** | 78.95 **(-21.05)** | 100 **(0)** | 100 **(0)**</details>

### CODE REVIEW

File: app/client/src/sagas/ApiPaneSagas.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ function* syncApiParamsSaga(
   let value = actionPayload.payload;
   // Regular expression to find the query params group
   const padQueryParams = { key: "", value: "" };
-  const queryParamsRegEx = /(\/[\s\S]*?)(\?(?![^{]*})[\s\S]*)?$/;
+  const queryParamsRegEx = /([\s\S]*?)(\?(?![^{]*})[\s\S]*)?$/;
```
Comment (hetunandu) [inline app/client/src/sagas/ApiPaneSagas.ts:82]: Let's extract the function and add a unit test for this parsing logic. Add the test case for the recent failure as well

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Review by hetunandu — APPROVED** [review]
