### PR TITLE
fix: add a warning icon and tooltip to indicate empty datasources

### LINKED ISSUE #30522: If users skip the step to connect with data, make it obvious for them they don't have a datasource connected while exploring the app
**Problem:**
Some users skip the datasource connection step and start creating entities without understanding that without having an active datasource, they can't create queries, bind widgets, etc. 

**Solution description:**
[Design](https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=5303-19812&mode=design&t=OLCr3zUrDlpzVv9O-0)
- If users skip the datasource connection in the start from data path and/or start from scratch and/or have an invalid datasource, we change the Data icon to a different one (with a visual hint that something needs to be configured). 
- On hover, a tooltip appear "Connect a valid datasource to enable functionality in this app."

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Indicate the warning icon and display tooltip on hover of the sidebar datasource icon if no datasource is created in the current workspace, to nudge the users to create one.

Notion doc : https://www.notion.so/appsmith/Nudge-for-users-to-connect-their-own-datasource-c62b5194bae84383b6301e4fe2e3ad80#d9a140a4bbda4ed18ac95136990aa3e6
Figma : https://www.figma.com/design/kbU9xPv44neCfv1FFo9Ndu/User-Activation?node-id=5303-26410&t=skXEhNbpopbw1gYs-0

Fixes #30522 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9203050102>
> Commit: 6bb71c44143775df8ed98263b554b820dd5de71b
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9203050102&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

### CODE REVIEW

File: app/client/src/pages/Editor/IDE/Sidebar/SidebarComponent.tsx [hunk 1]
```diff
@@ -23,6 +26,24 @@ interface SidebarComponentProps {
...
+  const getConditionalIconAndTooltip = (
+    type?: SideButtonType,
+    conditionTooltip?: string,
+  ) => {
+    switch (type) {
+      case SideButtonType.DATSOURCE:
+        if (datasources.length === 0)
+          return {
+            conditionIcon: "warning",
+            conditionIconColor: "#FFE283",
```
Comment (sneha122) [inline app/client/src/pages/Editor/IDE/Sidebar/SidebarComponent.tsx:39]: @AmanAgarwal041 Out of curiosity, why are we defining color as a prop here? Why can't we simply add this color in the css for conditionIcon?

File: app/client/src/pages/Editor/IDE/Sidebar/SidebarComponent.tsx [hunk 2]
```diff
@@ -53,6 +78,10 @@ function SidebarComponent(props: SidebarComponentProps) {
             }}
             selected={appState === b.state}
             tooltip={b.title}
+            {...getConditionalIconAndTooltip(
```
Comment (sneha122) [inline app/client/src/pages/Editor/IDE/Sidebar/SidebarComponent.tsx:81]: @AmanAgarwal041 Is this needed here? Because bottom buttons do not have datasource at all

File: app/client/src/pages/Editor/IDE/Sidebar/SidebarButton.test.tsx [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+  onClick: () => {},
+  selected: false,
+  title: TopButtons[1].title,
+  conditionIcon: "warning",
+  conditionIconColor: "#FFE283",
+  tooltip: TopButtons[1].conditionTooltip,
+};
+
+describe("SidebarButton", () => {
+  it("is rendered", () => {
```
Comment (sneha122) [inline app/client/src/pages/Editor/IDE/Sidebar/SidebarButton.test.tsx:18]: Can we please update this test description? It is a bit unclear what this test case is asserting

Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/IDE/Sidebar/SidebarButton.test.tsx]: Updated the test description

File: app/client/src/pages/Editor/IDE/Sidebar/SidebarComponent.tsx (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/IDE/Sidebar/SidebarComponent.tsx]: Removed color from props and used css to update it

File: app/client/src/pages/Editor/IDE/Sidebar/SidebarComponent.tsx (hunk 2 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/IDE/Sidebar/SidebarComponent.tsx]: It was to maintain consistency. But removed it for now, as it is not needed.

**Review by sneha122 — APPROVED** [review]
