### PR TITLE
Fix for 502 errors from the server

### LINKED ISSUE #1947: [Bug] Improve messaging when server is not running
## Description

When the Appsmith server is not running, the toast message shown to the user on the frontend is `n is not defined`. This is a bad experience because the user doesn't know what is happening and what to expect from the application. 

This is also blocking our AWS AMI Marketplace approval because the reviewers think that the application has not booted correctly.

Instead of a cryptic error message like this, is it possible to show a more informative message saying: 

_The Appsmith server is not responding right now. If you just setup Appsmith, please try refreshing this page after some time._

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Start the wildcard-nginx docker image with a non-running Java server endpoint (eg. http://localhost:8080)
2. Open the URL dev.appsmith.com
4. See error `n is undefined`

### Important Details
 - Version: All
 - OS: All
 - Browser: All

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
When server is not reachable, it will send a 502 response. We were not handling this gracefully. This PR will look for those errors and redirect the user to an appropriate route.

Fixes #1947 

This is also refactors old editor/viewer only error screens and uses the same error state to handle crashes on the whole app router level

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jsartisan — DISMISSED** [review]

File: app/client/src/api/Api.tsx [hunk 1]
```diff
@@ -68,6 +68,14 @@ axiosInstance.interceptors.response.use(
         message: SERVER_API_TIMEOUT_ERROR,
       });
     }
+    if (error.response.status === 502) {
```
Comment (jsartisan) [inline app/client/src/api/Api.tsx:71]: Is possible to store the status code in some constants file?
