### PR TITLE
fix: reduced the call for fetchPublishedPage action to single

### LINKED ISSUE #14141: [Bug]: Apps show error - `The action ... has failed` on page load
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Multiple appsmith users have complained that they are seeing the error: `The action ... has failed` on page load.

We started seeing the error after the release of v1.7

### Steps To Reproduce

Internal conversation - https://theappsmith.slack.com/archives/CGBPVEJ5C/p1653633651705329

This case is intermittently observed on apps before v1.7

### Public Sample App

_No response_

### Version

v1.7

### Test Plan

Cypress

- [ ] [[Test Case] : Execute actions should get called once for every page change](https://github.com/appsmithorg/TestSmith/issues/1740)

Jest

- [ ] [[Test Case] : Testing Init Saga for execution of multiple action calls in a specified sequence](https://github.com/appsmithorg/TestSmith/issues/1739)

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
### Problems 
1. There were multiple calls for `fetchPage` /`fetchPublishedPage` action which was disturbing the sequence of data tree evaluations and clearing cache resulting in the error message of `action failing`. Making it a single call restricts the cache from being cleared before the evaluations as the call was non blocking.

```
 case EVAL_WORKER_ACTIONS.CLEAR_CACHE: {
        dataTreeEvaluator = undefined;
        return true;
      }   
```

2. `failFastApiCalls` logic inside `initSagas` had an issue that resulted in scenarios where It was not actually waiting for all the success actions to complete. This resulted in an early executePageLoadActions trigger and hence the error `The action ... has failed`

### Solutions 

1. We have fixed `failFastApiCalls` to wait for all success actions to complete.
2. We have added `fetchAllPageEntityCompletion` which triggers evaluation instead of `fetchPageSuccess` or `fetchPublishedPageSuccess`. 
This is to make sure, we trigger evaluation only after actually `fetchPageSuccess`  & `fetchPublishedPageSuccess`. 

Fixes #14141 
Fixes https://github.com/appsmithorg/appsmith/issues/14252

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### Test Plan

Cypress

- [ ] [[Test Case] : Execute actions should get called once for every page change](https://github.com/appsmithorg/TestSmith/issues/1740)

Jest

- [ ] [[Test Case] : Testing Init Saga for execution of multiple action calls in a specified sequence](https://github.com/appsmithorg/TestSmith/issues/1739)

Will be added separately.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/14141-action-failed 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.72 **(0.01)** | 38.67 **(0)** | 36.23 **(0)** | 56.97 **(0.01)**
 :green_circle: | app/client/src/sagas/InitSagas.ts | 50.56 **(1.9)** | 36.67 **(2.82)** | 58.33 **(0)** | 53.95 **(2.38)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

File: app/client/src/sagas/InitSagas.ts [hunk 1]
```diff
@@ -430,22 +430,23 @@ export function* initializeAppViewerSaga(
     [
       fetchActionsForView({ applicationId }),
       fetchJSCollectionsForView({ applicationId }),
-      fetchPublishedPage(toLoadPageId, true, true),
+      fetchPublishedPage(toLoadPageId, true),
```
Comment (ohansFavour) [inline app/client/src/sagas/InitSagas.ts:433]: This should be `fetchPublishedPage(toLoadPageId, true, true)`.  This is the firstLoad and we don't want to execute pageLoadActions [here](https://github.com/appsmithorg/appsmith/blob/3da4ad55fb71789a1f126edb6d9d7e3ac89c36b2/app/client/src/sagas/PageSagas.tsx#L326). We wait till all actions and jsactions are fetched first before doing this in line 456

**Review by ohansFavour — DISMISSED** [review]

**Comment by ohansFavour** [comment]
Is there a way to automate tests here?

File: app/client/src/pages/AppViewer/AppViewerPageContainer.tsx [hunk 2]
```diff
@@ -36,19 +35,13 @@ const Section = styled.section<{
...
   const isFetchingPage = useSelector(getIsFetchingPage);
   const currentApplication = useSelector(getCurrentApplication);
   const { match } = props;
-  const { pageId } = match.params;
   const { applicationSlug, pageSlug } = useSelector(selectURLSlugs);
 
-  useEffect(() => {
-    pageId && dispatch(fetchPublishedPage(pageId, true));
-  }, [pageId, location.pathname]);
-
```
Comment (Rishabh-Rathod) [inline app/client/src/pages/AppViewer/AppViewerPageContainer.tsx:51]: As this code has been there for quite a long time.
Before Pawan's changes, the same logic was there in the class component. Let's not remove it, until we understand why was it added. 

Screenshot 2022-06-01 at 12 20 54 AM

@riodeuno Could you help here to understand if this is re-redundant now after current initSagas calling `fetchPage`.

Comment (riodeuno) [reply app/client/src/pages/AppViewer/AppViewerPageContainer.tsx:51]: @Rishabh-Rathod This does seem to be redundant now. The reason this was added was:
1. We did not have initSagas at the time.
2. When navigating to the view URL, we would make sure that the `pageId` actually exists and the `pageId` has changed before fetching the page.

Please note that, this is probably the earliest (literally) code related to the app view and quite a lot has changed since then. So, taking account of the application's current workflow, we can safely remove this code.

Having said that I appreciate the consideration for [Chesterton's fence](https://en.wiktionary.org/wiki/Chesterton%27s_fence)

File: app/client/src/sagas/InitSagas.ts (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/src/sagas/InitSagas.ts:433]: Then should we remove the `ReduxActionTypes.FETCH_PUBLISHED_PAGE_SUCCESS` on line number 440 also because same action is getting called at 456 ?

Comment (ohansFavour) [reply app/client/src/sagas/InitSagas.ts:433]: Yes, we should remove it there.

File: app/client/src/pages/AppViewer/AppViewerPageContainer.tsx (hunk 2 above)
Comment (Rishabh-Rathod) [reply app/client/src/pages/AppViewer/AppViewerPageContainer.tsx:51]: Thanks, Abhinav. @AmanAgarwal041 as we have better clarity about it now. We could remove it and test all functionality to remain the same. 
Mainly for cases, where
1. Page switch happens using `navigateTo`
2. Page switch happens using Top NavBar

File: app/client/src/sagas/InitSagas.ts (hunk 1 above)
Comment (Rishabh-Rathod) [reply app/client/src/sagas/InitSagas.ts]: removed older implementation of `firstLoad`.

File: app/client/src/sagas/InitSagas.ts [hunk 3]
```diff
@@ -450,35 +450,8 @@ export function* initializeAppViewerSaga(
...
-            resultOfFetchPage,
-            "failure.payload.error.code",
-            ERROR_CODES.SERVER_ERROR,
-          ),
-        },
-      });
-      return;
-    }
-  }
+  yield put(executePageLoadActions());
```
Comment (arunvjn) [inline app/client/src/sagas/InitSagas.ts:454]: @AmanAgarwal041  We need to call `executePageLoadActions` after evaluation (triggered by page_success) is complete. I doubt if this guarantees that.

Comment (Rishabh-Rathod) [reply app/client/src/sagas/InitSagas.ts:454]: @arunvjn 
Above `fetchPublishedPageSuccess().type,` waits for page_success and only when all below mentioned action are completed,
```
ReduxActionTypes.FETCH_ACTIONS_VIEW_MODE_SUCCESS,
      ReduxActionTypes.FETCH_JS_ACTIONS_VIEW_MODE_SUCCESS,
      ReduxActionTypes.FETCH_APP_THEMES_SUCCESS,
      ReduxActionTypes.FETCH_SELECTED_APP_THEME_SUCCESS,
      fetchPublishedPageSuccess().type,
```
then we move to next line where we trigger `executePageLoadActions`.

Comment (arunvjn) [reply app/client/src/sagas/InitSagas.ts:454]: page_success  -> evaluations  -> executePageLoadActions should be the flow. 

With the above code it becomes, 
                              
page_success -> ( evaluations & executePageLoadActions running in parallel )

Comment (Rishabh-Rathod) [reply app/client/src/sagas/InitSagas.ts:454]: In that case, shouldn’t  `executePageLoadActions` completion trigger evaluations?

Comment (arunvjn) [reply app/client/src/sagas/InitSagas.ts:454]: ```executePageLoadActions``` are API calls (POST /execute) or some JS function. If we take the case of an API,  EXECUTE_PLUGIN_ACTION will trigger evaluations.

Comment (Rishabh-Rathod) [reply app/client/src/sagas/InitSagas.ts:454]: @arunvjn you are correct, executePageLoadActions should run `postEval`. Thanks for pointing that out.

File: app/client/src/sagas/InitSagas.ts [hunk 4]
```diff
@@ -99,15 +101,17 @@ export function* failFastApiCalls(
...
+
   const successEffects = [];
   for (const successAction of successActions) {
-    successEffects.push(take(successAction));
+    successEffects.push(successAction);
   }
-  yield all(triggerEffects);
   const effectRaceResult = yield race({
-    success: all(successEffects),
+    success: all(successEffects.map((successAction) => take(successAction))),
```
Comment (arunvjn) [inline app/client/src/sagas/InitSagas.ts:114]: These lines can be combined

File: app/client/src/sagas/PageSagas.tsx [hunk 5]
```diff
@@ -986,16 +1006,29 @@ export function* generateTemplatePageSaga(
...
+        [
+          fetchActionsForPageError().type,
+          fetchJSCollectionsForPageError().type,
+        ],
       );
-      // TODO : Add this to onSuccess (Redux Action)
-      yield put(fetchActionsForPage(pageId, [executePageLoadActions()]));
-      // TODO : Add it to onSuccessCallback
+
+      if (afterActionsFetch) {
```
Comment (Rishabh-Rathod) [inline app/client/src/sagas/PageSagas.tsx:1028]: handle error case and return `!afterActionsFetch`

File: app/client/src/sagas/InitSagas.ts [hunk 6]
```diff
@@ -99,15 +101,17 @@ export function* failFastApiCalls(
 ) {
   const triggerEffects = [];
   for (const triggerAction of triggerActions) {
-    triggerEffects.push(put(triggerAction));
+    triggerEffects.push(triggerAction);
```
Comment (Rishabh-Rathod) [inline app/client/src/sagas/InitSagas.ts:104]: No need for creating `triggerEffects` and `successEffects`

File: app/client/src/pages/AppViewer/AppViewerPageContainer.tsx (hunk 2 above)
Comment (Rishabh-Rathod) [inline app/client/src/pages/AppViewer/AppViewerPageContainer.tsx:51]: Move code to AppViewer/index.ts and replicate editor logic

File: app/client/src/sagas/InitSagas.ts (hunk 6 above)
Comment (Rishabh-Rathod) [reply app/client/src/sagas/InitSagas.ts:104]: removed it

File: app/client/src/sagas/InitSagas.ts (hunk 4 above)
Comment (Rishabh-Rathod) [reply app/client/src/sagas/InitSagas.ts:114]: fixed it

File: app/client/src/pages/AppViewer/AppViewerPageContainer.tsx (hunk 2 above)
Comment (Rishabh-Rathod) [reply app/client/src/pages/AppViewer/AppViewerPageContainer.tsx:51]: created a separate PR https://github.com/appsmithorg/appsmith/pull/14294 for that.

**Review by arunvjn — DISMISSED** [review]

**Review by arunvjn — APPROVED** [review]
