### PR TITLE
fix: Error deleting application when soft-deleted entities are present in the application

### LINKED ISSUE #18181: [Bug]: Error deleting applications when soft-deleted JSObjects present
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Deleting the application throws a 500 error if there are soft-deleted JSObjects present. This happens when apps are exported from older versions of Appsmith and imported to new versions and if there are soft-deleted JSObjects present in the exported JSON.

### Steps To Reproduce

1. Export an app from an older version of Appsmith (<=v1.8.3) (App should have a soft-deleted JSObject present)
2. Import to the latest version of Appsmith (v1.8.8)
3. Try deleting the app.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

v1.8.8

### PR DESCRIPTION
**Pull request by vishnu-gp**
## Description

Deleting the application throws a 500 error if there are soft-deleted JSObjects present. This happens when apps are exported from older versions of Appsmith and imported to new versions and if there are soft-deleted JSObjects present in the exported JSON.

Fixes #18181 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java [hunk 1]
```diff
@@ -146,7 +146,10 @@ public Flux<T> findAll(Example example) {
     public Mono<T> archive(T entity) {
         Assert.notNull(entity, "The given entity must not be null!");
         Assert.notNull(entity.getId(), "The given entity's id must not be null!");
-        Assert.isTrue(!entity.isDeleted(), "The given entity is already deleted");
+        // Entity is already deleted
+        if (entity.isDeleted()) {
+            return Mono.empty();
+        }
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java:152]: Can you please add a TC for this, if possible ?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java [hunk 2]
```diff
@@ -146,7 +146,10 @@ public Flux<T> findAll(Example example) {
     public Mono<T> archive(T entity) {
         Assert.notNull(entity, "The given entity must not be null!");
         Assert.notNull(entity.getId(), "The given entity's id must not be null!");
-        Assert.isTrue(!entity.isDeleted(), "The given entity is already deleted");
+        // Entity is already deleted
+        if (entity.isDeleted()) {
```
[the remark this answers is not in the document]
Comment (vishnu-gp) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java:150]: > Can you please include a check for `deletedAt` field as well in the same `if` condition ?

@sumitsum I think `isDeleted()` method checks for both fields.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java [hunk 3]
```diff
@@ -146,7 +146,10 @@ public Flux<T> findAll(Example example) {
...
+            return Mono.empty();
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java:151]: Can we return the given entity as is, instead of empty Mono please? It'll be useful for further `.map` or `.flatMap` transformations.

```suggestion
            return Mono.just(entity);
```

Comment (vishnu-gp) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java]: @sharat87 done

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java (hunk 1 above)
Comment (vishnu-gp) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java:152]: > Can you please add a TC for this, if possible ?

@sumitsum As discussed, this will be handled in https://github.com/appsmithorg/appsmith/issues/18201

**Review by sumitsum — APPROVED** [review]
