### PR TITLE
fix: adds a new rule to show selectedRow in autocomplete's best match 

### LINKED ISSUE #12790: [Bug]-[2000]:Autocomplete selectedRow columns don't show in best match
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The best match feature of the autocomplete doesn't factor in the selectedRow of the table widget

### Steps To Reproduce

1. Drag a table
2. Drag a text widget
3. Enter {{Table1.}}
4. See that best match does not show the selectedRow and cols

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #14990: [Bug]: Copied widgets don't show up in Autocompletion hints in propertypane of original widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you create a copy of a widget, in the propertypane of the original widget, the copied widget doesn't show up in autocompletion Hints

### Steps To Reproduce

1. Drag Button (Button1)
2. Copy and paste Button (Button1Copy gets created)
3. In Button1, type {{}}
4. See that Button1Copy never shows up

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Refactored sorting logic for autocomplete.

### Type of change
Enhancement

### Test plan
- [x] https://github.com/appsmithorg/TestSmith/issues/1994
- [x] https://github.com/appsmithorg/TestSmith/issues/1995

## How Has This Been Tested?
- Manual
- Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by arunvjn** [comment]
@Rishabh-Rathod Can you check out the DP ?

File: app/client/src/utils/autocomplete/AutocompleteSortRules.ts [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+}
+
+/**
+ * Set's threshold value for completions like setInterval, clearInterval etc.
+ * Max score - 10^4
+ * Min score - 0
+ */
+class DataTreeFunctionRule implements AutocompleteRule {
+  static threshold = 1 << RuleWeight.DataTreeFunction;
+  computeScore(completion: Completion): number {
```
Comment (Rishabh-Rathod) [inline app/client/src/utils/autocomplete/AutocompleteSortRules.ts:118]: Can you help me understand how the max score here is 10^4.
1. `RuleWeight.DataTreeFunction` value according to above seems to be 3.
2. `threshold` value for 1 << 4 will be 16 which is 2^4.
Do you meant to write  `2^4` here?

File: app/client/src/utils/autocomplete/AutocompleteSortRules.ts [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+  }
+}
+
+/**
+ * Set's threshold value for completions like _, moment() etc.
+ * Max score - 10^2
+ * Min score - 0
+ */
+class JSLibraryRule implements AutocompleteRule {
+  static threshold = 1 << 3;
```
Comment (Rishabh-Rathod) [inline app/client/src/utils/autocomplete/AutocompleteSortRules.ts:102]: `static threshold = 1 << 3;` can we maintain the threshold in `RuleWeight` instead of hardcoding here?

File: app/client/src/utils/autocomplete/TernServer.ts [hunk 3]
```diff
@@ -222,10 +240,16 @@ class TernServer {
       completions.push(codeMirrorCompletion);
     }
 
-    completions = this.sortAndFilterCompletions(
+    const shouldComputeBestMatch =
+      this.fieldEntityInformation.entityType !== "JSACTION";
```
Comment (Rishabh-Rathod) [inline app/client/src/utils/autocomplete/TernServer.ts:244]: Can we please use ENTITY_TYPE.JSACTION here instead of hardcoded string.

**Review by Rishabh-Rathod — APPROVED** [review]
Code LGTM.

Few nit picks mentioned in below comments.

File: app/client/src/utils/autocomplete/AutocompleteSortRules.ts (hunk 1 above)
Comment (arunvjn) [reply app/client/src/utils/autocomplete/AutocompleteSortRules.ts]: Yes, I was using 10 as base when I wrote the comments for these rules. Missed to update the comments when I changed the base.

File: app/client/src/components/editorComponents/CodeEditor/index.tsx [hunk 4]
```diff
@@ -641,8 +644,16 @@ class CodeEditor extends Component<Props, State> {
...
+        if (isWidgetEntity(entity)) {
+          const isTriggerPath =
+            entity.dynamicTriggerPathList &&
+            entity.dynamicTriggerPathList
+              .map((path) => path.key)
+              .includes(propertyPath);
           entityInformation.entityId = entity.widgetId;
+          if (isTriggerPath)
+            entityInformation.expectedType = AutocompleteDataType.FUNCTION;
+        }
```
[the remark this answers is not in the document]
Comment (arunvjn) [reply app/client/src/components/editorComponents/CodeEditor/index.tsx]: Changed

**Comment by ramsaptami** [comment]
@Aishwarya-U-R DP has been tested and verified, only Cypress tests need a check from you :)

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Autcomplete-bugs.spec.js [hunk 5]
```diff
@@ -0,0 +1,81 @@
+const explorer = require("../../../../locators/explorerlocators.json");
+const dynamicInputLocators = require("../../../../locators/DynamicInput.json");
+
+describe("Autocomplete bug fixes", function() {
+  const modifierKey = Cypress.platform === "darwin" ? "meta" : "ctrl";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Autcomplete-bugs.spec.js:5]: 1. Consider writing test scripts in ts spec file - which is lot better in maintenance
2. Index the test cases for easier debugging in CI - like `it("1. Bug #bugId test case title goes here",() =>{`
3. I see the complete spec in this case is against bug, so this can be named after bug id & added to BugTests folder under ClientSideTests.

**Review by Aishwarya-U-R — CHANGES_REQUESTED** [review]
Please update to ts cypress test spec!

**Review by Aishwarya-U-R — APPROVED** [review]
Approving Cypress tests!
