### PR TITLE
fix: Fixes related to git profile

### LINKED ISSUE #9890: [Bug]: Connect application to git and commit application breaks when the git profile is not configured

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> This PR fixes a git profile related issues for scenarios like:

- Default git profile is null and useGlobalProfile flag is set
- Author name is empty for local git profile and useLocalGitProfile is set 

Fixes #9890

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Manual test
> JUnit TC

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitConnectDTO.java [hunk 1]
```diff
@@ -11,6 +11,4 @@
     String remoteUrl;
 
     GitProfile gitProfile;
-
-    String defaultApplicationId;
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitConnectDTO.java:15]: Removed this as we are not using this field anymore

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 2]
```diff
@@ -317,10 +332,14 @@ private String getReason() {
                                 .getCurrentUser()
                                 .flatMap(user -> {
                                     GitProfile gitProfile = new GitProfile();
-                                    gitProfile.setAuthorName(StringUtils.isEmptyOrNull(user.getName()) ? user.getUsername() : user.getName());
+                                    gitProfile.setAuthorName(StringUtils.isEmptyOrNull(user.getName()) ? user.getUsername().split("@")[0] : user.getName());
                                     gitProfile.setAuthorEmail(user.getEmail());
                                     Map<String, GitProfile> updateProfiles = userData.getGitProfiles();
-                                    updateProfiles.put(DEFAULT, gitProfile);
+                                    if (CollectionUtils.isNullOrEmpty(updateProfiles)) {
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:338]: Earlier this was throwing NPE as updateProfiles can be null for the user who have never used the git feature and never landed on git connect tab.

**Review by AnaghHegde — APPROVED** [review]
