### PR TITLE
fix: Firefox input widget text selection

### LINKED ISSUE #6723: [Bug] Number input field can't be selected on Firefox
## Description

The number in an input field set to Number DataType cannot be selected. _This happens for me on the Appsmith release server, using FireFox_. In Chrome the widget works as expected.

### Steps to reproduce the behaviour:

1. Create a new app
2. Add an input widget to the page
3. Set the DataType to Number
4. Double click on the "0" in the field to select it. It won't be selected
5. Drag across the "0" to select it. It won't be selected

### Important Details

This issue only happens in edit mode, in deployed mode the input works.

- Version: https://release.app.appsmith.com
- OS: Linux Mint 19
- Browser FireFox 89.0.2
- Environment: release (I guess)

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

Fixes #6723 

Cause - This is a very old issue that yet to be resolved by Mozilla
https://bugzilla.mozilla.org/show_bug.cgi?id=800050
https://bugzilla.mozilla.org/show_bug.cgi?id=1189486

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/6723-firefox-input-selection 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.85 **(-0.01)** | 36.79 **(-0.02)** | 33.55 **(-0.02)** | 55.44 **(-0.01)**
 :red_circle: | app/client/src/utils/helpers.tsx | 66.11 **(-1.67)** | 37.89 **(-3.16)** | 45.16 **(-3.23)** | 63.19 **(-1.39)**
 :red_circle: | app/client/src/widgets/InputWidget.tsx | 53.92 **(-0.54)** | 22.86 **(0)** | 59.09 **(0)** | 55.67 **(-0.58)**</details>

### CODE REVIEW

File: app/client/src/widgets/InputWidget.tsx [hunk 1]
```diff
@@ -492,6 +492,18 @@ class InputWidget extends BaseWidget<InputWidgetProps, WidgetState> {
...
+     * 1. In Firefox, draggable="true" property on the parent element
+     *    or <input /> itself, interferes with some <input /> element's events
+     *    Bug Ref - https://bugzilla.mozilla.org/show_bug.cgi?id=800050
+     *              https://bugzilla.mozilla.org/show_bug.cgi?id=1189486
+     *
+     *  Eg - input with draggable="true", double clicking the text; won't highlight the text
+     *
+     * 2. Dragging across the text (for text selection) in input won't cause the widget to drag.
+     */
+    super.updateWidgetProperty("dragDisabled", focusState);
```
Comment (marks0351) [inline app/client/src/widgets/InputWidget.tsx:506]: i think this calls an api to update DSL. doesn't seem like a good way to solve this issue.

**Review by marks0351 — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/InputWidget.tsx (hunk 1 above)
Comment (ashit-rath) [reply app/client/src/widgets/InputWidget.tsx:506]: So should I be using `updateWidgetMetaProperty` here? that would just update the local state
```
this.props.updateWidgetMetaProperty("dragDisabled", focusState);
```

**Review by marks0351 — APPROVED** [review]

**Comment by vivekverma2312** [comment]
Working fine on deploy preview.
