### PR TITLE
fix: fix execution of REST API query when dynamic binding is present in the URL

### LINKED ISSUE #24218: [Bug]: CRITICAL - DEFAULT_REST_DATASOURCE broken when creating new api query in version 1.9.21 + heading slash / sign incorrectly removed from query url
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating or editing an api query will result in a broken configuration where the query's metadata.json lacks a dataSourceConfiguration as below:

```
{
  "pluginType": "API",
  "pluginId": "restapi-plugin",
  "unpublishedAction": {
    "name": "cancelBeat",
    "datasource": {
      "name": "DEFAULT_REST_DATASOURCE",
      "pluginId": "restapi-plugin",
      "datasourceConfiguration": {
        "url": ""
      },
      "invalids": [],
      "messages": [],
      "isAutoGenerated": false,
      "deleted": false,
      "policies": [],
      "userPermissions": []
    },
   ...
```

I also noticed that the first '/' sign in the query's url seems to be removed, resulting in a broken api url.
For example, when using the query editor to create the query updatePaidAdBeat (above) and giving the endpoint url 

`{{appsmith.store.api_url}}/bo/v2/campaign/{{this.params.campaign_id}}/beat/{{this.params.beat_id}}/cancel`

will result in appsmith saving the following metadata.json to git:

```

    "actionConfiguration": {
      "timeoutInMillisecond": 10000,
      "paginationType": "NONE",
      "path": "{{appsmith.store.beatly_api}}bo/v2/campaign/{{this.params.campaign_id}}/beat/paidad/{{this.params.beat_id}}/update",

```

Notice the missing / in the path url...

Needless to say, this renders the api query editor unusable and breaks existing api queries as soon as editing one...

### Steps To Reproduce

See description.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

1.9.21

Front logo [Front conversations](https://app.frontapp.com/open/top_bwyoc)

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Earlier the client would by default set a URL in REST API query config in `datasource.url` path if it could not parse the URL properly. This made sure that `datasource.url` path was non-empty as long as user entered some value in the URL input box on the REST API query config page. However, this was changed recently to fix an issue related to showing the evaluated value of dynamic binding on the client. As per the current logic, the default path for the URL has been updated to `actionConfiguration.path`. Hence, for newer REST API queries where `datasource.url` is emtpy, a validation error shows up.  This PR includes changes to stop the empty URL validation check for embedded datasources on REST API datasource URL as it can be empty now for embedded datasource. 
- [Ref](https://theappsmith.slack.com/archives/C040LHZN03V/p1686478370473659?thread_ts=1686300736.679729&cid=C040LHZN03V)

#### PR fixes following issue(s)
Fixes #24218
  - Another fix required on client side for a different issue (Ade is working on it)

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
- [x] Cypress
- [x] JUnit
- [x] Manual

#### Test Plan
1. Write the following in JS Object
export default {
	myVar1: [],
	myVar2: {},
	myFun1 () {
		
		{{storeValue('api_url',"https://postman-echo.com/get")}}
		//	write code here
		//	this.myVar1 = [1,2,3]
	}
} 
Run it.
Create a new api and invoke GET - {{appsmith.store.api_url}}

2. Tried with following different APIs
	https://api.publicapis.org/entries
	https://official-joke-api.appspot.com/random_joke
        https://api.zippopotam.us/us/33162

3. Tried binding the storeValue api url in an input and text widget: e.g. {{storeValue('api_url',Text2.text)}} and then running API using that stored value. 

>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+      {
+        paste: true,
+        completeReplace: true,
+        toRun: false,
+        shouldCreateNewJSObj: true,
+        prettify: true,
+      },
+    );
+
+    agHelper.AssertAutoSave();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:26]: `CreateJSObject` already does AutoSave check. So this is not needed.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+describe("Test API execution with dynamic binding in URL", () => {
+  /* Create a JS Object and set TED API URL in an Appsmith store variable. */
+  it("1. Set URL in Appsmith store variable", () => {
+    jsEditor.CreateJSObject(
+      `export default {
+        myVar1: [],
+        myVar2: {},
+        myFun1 () {
+          storeValue("api_url", "http://host.docker.internal:5001/v1/dynamicrecords/getstudents");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:12]: Do not hardcode in spec. Create a variable in dataources.json & refer it here.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:12]: Please use `mockApiUrl` from dataSources.json

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+        prettify: true,
+      },
+    );
+
+    agHelper.AssertAutoSave();
+    jsEditor.RunJSObj();
+  });
+
+  /* Create an API with dynamic binding as URL and run it. */
+  it("2. Execute API", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:31]: Can be combined into single it block. 2 cases here not required.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts [hunk 4]
```diff
@@ -0,0 +1,40 @@
+import { agHelper, jsEditor } from "../../../../support/Objects/ObjectsCore";
+import * as _ from "../../../../support/Objects/ObjectsCore";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:2]: `import * as _ `is not needed, since needed objects can be imported via above statement itself from ObjectsCore.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+
+describe("Test API execution with dynamic binding in URL", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:4]: Add the `Bug Id to describe description - Bug #24218 `, so we know script already exits if someone search's for it in future & does not duplicate the effort.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java [hunk 6]
```diff
@@ -25,7 +26,19 @@ public Set<String> validateDatasource(DatasourceConfiguration datasourceConfigur
         Set<String> invalids = new HashSet<>();
 
         if (StringUtils.isEmpty(datasourceConfiguration.getUrl())) {
-            invalids.add("Missing URL.");
+            if (isEmbeddedDatasource) {
+                /**
+                 * Deliberately skipping adding any invalidity message here because based on the current parsing logic the
+                 * client can skip adding a URL to embedded datasource and instead add the entire URL to
+                 * `actionConfiguration.path`.
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java:33]: Should we add validation to either of these paths in that case?

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java:33]: Hi @nidhi-nair, we have added form validation on the REST API datasource at the moment to make sure that the datasource cannot be saved until a non empty URL is added. Hence, IMO, we should still keep this check because having an empty URL for non-embedded datasource is still not expected.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts (hunk 1 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:26]: Done.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts (hunk 3 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:31]: Done.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts (hunk 5 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:4]: Done.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts (hunk 4 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:2]: Done.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts (hunk 2 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:12]: Done.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java (hunk 6 above)
Comment (nidhi-nair) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java:33]: Hey I meant that the check should be added for both, either the url field is non-empty, or the resultant of url and path is non-empty.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts [hunk 7]
```diff
@@ -0,0 +1,39 @@
+const datasourceFormData = require("../../../../fixtures/datasources.json");
+
+import { agHelper, jsEditor } from "../../../../support/Objects/ObjectsCore";
+import { apiPage } from "../../../../support/Objects/ObjectsCore";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts:4]: nit: Can be same import.

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good!

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java (hunk 6 above)
Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java:33]: Hi @nidhi-nair two points here regarding why checking for datasource url + action config url seems redundant: 
(1) In case of embedded datasource i.e. when REST API does not have explicit datsource, datasource validation is only done at the time of execute action. At this point if the final URL is empty / null then we already have logic to return error. 
(2) We have added form validation on the client to make sure that a user cannot click on the run button without entering a non empty URL in REST API query.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts (hunk 7 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts]: Done.

**Review by nidhi-nair — APPROVED** [review]
