### PR TITLE
Fix #5319: Break word when text widget content is long

### LINKED ISSUE #5319: [Bug]Specific to windows->In text widget ->for enable scroll-> even when its enabled or disabled when the text is too big the scroll is displayed
## Description

[What happened]Specific to windows->In text widget ->for enable scroll-> even when its enabled or disabled when the text is too big the scroll is displayed

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to widgets
2. Drag and drop the text widget 
3. In the text add the Paragraph
4. Don't enable the scroll
5. Verify the display

Expected Output : The vertical scroll should be displayed be display when the user enable the Scroll bar and when it is disabled the scroll bar should not be displayed

https://drive.google.com/file/d/1N_pt01MPibfgVelrDJMgIcwLulu_595p/view

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment [production]

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description
Added word-break as mentioned in the issue

Fixes #5319 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/text-widget-break-word 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.9 **(-0.01)** | 36.76 **(-0.01)** | 33.62 **(0)** | 55.45 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

File: app/client/src/components/designSystems/blueprint/TextComponent.tsx [hunk 1]
```diff
@@ -48,6 +48,7 @@ export const StyledText = styled(Text)<{
   font-weight: ${(props) =>
     props?.fontStyle?.includes(FontStyleTypes.BOLD) ? "bold" : "normal"};
   font-size: ${(props) => props?.fontSize && TEXT_SIZES[props?.fontSize]};
+  word-break: break-word;
```
Comment (somangshu) [inline app/client/src/components/designSystems/blueprint/TextComponent.tsx:51]: This might have a cascading effect on all component using the text component. @riodeuno can you help us understand if this looks ok.

Comment (riodeuno) [reply app/client/src/components/designSystems/blueprint/TextComponent.tsx:51]: According to the codebase, the only place these styles are being used is the TextWidget. So, we should be fine as long as we thoroughly test the text widget.

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by somangshu** [comment]
@vivekverma2312 will need you sign-off to merge this change

**Comment by vivekverma2312** [comment]
@sbalaji1192 Calendar on table filter is getting closed every time I try to change the month/year.
https://www.loom.com/share/f4767d85e2294f5db2a22b07248cbfe4

**Comment by somangshu** [comment]
Re-ran all tests because of faliures

**Comment by vivekverma2312** [comment]
@sbalaji1192 Above deploy preview is tested and working fine.

**Comment by somangshu** [comment]
@sbalaji1192 we have some related fixes in the release, Can we merge to fix the failing tests

**Review by somangshu — APPROVED** [review]

**Review by somangshu — APPROVED** [review]
