### PR TITLE
fix: 11468 select widget performance on a large data set.

### LINKED ISSUE #11468: [Bug]: The time delay of the content displayed in the drop-down box is too long
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Release v1.6.0~v1.6.12
When there are more than 1000 records in the drop-down box, the display delay time is very long, more than 5 seconds. It is hoped that this function module can be improved and the use efficiency can be improved.

Same with #11252

### Steps To Reproduce

image

### Environment

Release

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by prsidhu**
## Description

- Improvements in initial render time of Select Widget on large data set.
- The original complaint was that in case of large data set, the widget takes up to 5 seconds to render.

Updates -
1. Biggest improvement gained by manually controlling the visibility of the menu list through a state variable. Prevents rendering of each item (total = 1000) on every parent re-render (even when the menu is hidden).
2. Cutting down unnecessary re-renders through memoization of child components and additional checks before calling setState.
3. Initial render is now down to ~100ms once the options are available from the api call.
4. Case - Opening the options menu for the first time. This was taking about 1.5s for a 1000 option list, mainly because of cascading updates and expensive style calculations in blueprint Text component. The only way to fix this was to create a custom MenuItem component. The rendering time is now down to ~700ms.

Screen Shot 2022-03-07 at 12 54 24 PM

Fixes #11468

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

1. Add a Select Widget to a page. 
5. Fetch options through an api call. Use the following api to get a 1000 item list - ```https://demo7762119.mockable.io/dropdown```.
6. Set default value to the first item [0].
7. Re-load the page and observe that the widget renders in under 100ms after the options are available from the api call. Use React profiler or performance dev tools to observe render times.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix-11468_dropdown_performance 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.69 **(-0.03)** | 37.07 **(-0.04)** | 35.29 **(0)** | 55.95 **(-0.02)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :green_circle: | app/client/src/utils/helpers.tsx | 67.58 **(0.6)** | 35.86 **(1.5)** | 53.45 **(2.57)** | 65.48 **(0.68)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :sparkles: :new: | **app/client/src/widgets/SelectWidget/component/SelectButton.tsx** | **100** | **50** | **100** | **100**
 :green_circle: | app/client/src/widgets/SelectWidget/component/index.styled.tsx | 48.48 **(1.6)** | 25.81 **(2.48)** | 0 **(0)** | 51.61 **(1.61)**
 :red_circle: | app/client/src/widgets/SelectWidget/component/index.tsx | 14.52 **(-7.22)** | 0 **(0)** | 4.55 **(-1.01)** | 15.04 **(-6.14)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@prsidhu please link the issue to the PR, gets easier to track

**Comment by somangshu** [comment]
@SatishGandham @riodeuno can we accelerate the review here? are we waiting on something?

@prsidhu can you clear the conflicts

**Comment by riodeuno** [comment]
@prsidhu Is it possible to virtualise the renders so that we can bring down the 700ms number?

File: app/client/src/widgets/SelectWidget/component/index.tsx [hunk 1]
```diff
@@ -269,4 +335,4 @@ export interface SelectComponentProps extends ComponentProps {
   filterText?: string;
 }
 
-export default SelectComponent;
+export default React.memo(SelectComponent);
```
Comment (riodeuno) [inline app/client/src/widgets/SelectWidget/component/index.tsx:338]: I was wondering if we can leverage the second argument to `React.memo` to get performance gains?

**Review by riodeuno — COMMENTED** [review]
A few queries. The rest looks good. @prsidhu Thanks for working on this, we will see much-needed performance improvements in this component.

**Comment by prsidhu** [comment]
@riodeuno Virtualizing list render has yielded great improvement. Thanks for the suggestion. Will update the PR after ironing our a few kinks

**Comment by prsidhu** [comment]
@riodeuno @SatishGandham Render performance on first click has improved to ~100ms through virtualisation. 

Due to large number of changes, I will merge in the release after these updates are approved.
Screen Shot 2022-03-17 at 10 21 47 AM

**Comment by riodeuno** [comment]
@prsidhu This is awesome! Going from 5000ms to 100ms is an extremely huge boost. 
Could you also reply to my comments in the previous review?

File: app/client/src/widgets/SelectWidget/component/index.tsx [hunk 2]
```diff
@@ -39,7 +40,55 @@ const DEBOUNCE_TIMEOUT = 800;
...
+
+function SelectButton(props: SelectButtonProps) {
+  const {
+    disabled,
+    displayText,
+    handleCancelClick,
+    togglePopoverVisibility,
+    value,
+  } = props;
+  return useMemo(
```
[the remark this answers is not in the document]
Comment (prsidhu) [reply app/client/src/widgets/SelectWidget/component/index.tsx]: updated. switched React.memo

File: app/client/src/components/ads/Icon.tsx [hunk 3]
```diff
@@ -420,4 +420,4 @@ const Icon = forwardRef(
 
 Icon.displayName = "Icon";
 
-export default Icon;
+export default React.memo(Icon);
```
[the remark this answers is not in the document]
Comment (prsidhu) [reply app/client/src/components/ads/Icon.tsx:423]: @riodeuno Without passing the equality function, memo does a shallow comparison of all the props which seems to suffice the use case. It has already helped trim down some re-renders.

**Review by riodeuno — DISMISSED** [review]
Looks good to me.

**Comment by riodeuno** [comment]
@prsidhu Please merge with the latest release to resolve conflicts. We can then comment with ok-to-test to run CI workflows.

File: app/client/src/widgets/SelectWidget/component/SelectButton.tsx [hunk 4]
```diff
@@ -0,0 +1,66 @@
+import React, { memo } from "react";
+import Icon, { IconSize } from "components/ads/Icon";
+import { Button } from "@blueprintjs/core";
+import { Colors } from "constants/Colors";
+import { isNil } from "lodash";
+
+import { isString } from "../../../utils/helpers";
+import { StyledDiv } from "./index.styled";
+
+export const isEmptyOrNill = (value: any) => {
```
Comment (SatishGandham) [inline app/client/src/widgets/SelectWidget/component/SelectButton.tsx:10]: Shouldn't this be in utils?

**Review by SatishGandham — CHANGES_REQUESTED** [review]
Scrollbar position is off compared to release.
Please check.

**Comment by prsidhu** [comment]
@SatishGandham addressed your suggestions.

File: app/client/cypress/support/Objects/CommonLocators.ts [hunk 5]
```diff
@@ -1,57 +1,90 @@
...
+    "']/parent::div[contains(@class, 't--entity-name editing')]/input";
+  _jsToggle = (controlToToggle: string) =>
+    ".t--property-control-" + controlToToggle + " .t--js-toggle";
+  _spanButton = (btnVisibleText: string) =>
+    "//span[text()='" + btnVisibleText + "']/parent::button";
+  _selectPropDropdown = (ddName: string) =>
+    "//div[contains(@class, 't--property-control-" + ddName + "')]//button";
+  _dropDownValue = (ddOption: string) =>
+    ".single-select:contains('" + ddOption + "')";
+  _selectOptionValue = (ddOption: string) =>
```
Comment (prsidhu) [inline app/client/cypress/support/Objects/CommonLocators.ts:63]: @SatishGandham this is the only addition to this file. _selectOptionValue

File: app/client/cypress/support/Pages/AggregateHelper.ts [hunk 6]
```diff
@@ -1,395 +1,424 @@
...
+      .click();
+    cy.get(locator._dropDownValue(ddOption)).click();
+  }
+
+  public SelectDropDown(endp: string, ddOption: string) {
+    cy.xpath(locator._selectWidgetDropdown(endp))
+      .first()
+      .scrollIntoView()
+      .click();
+    cy.get(locator._selectOptionValue(ddOption)).click({ force: true });
```
Comment (prsidhu) [inline app/client/cypress/support/Pages/AggregateHelper.ts:238]: @SatishGandham That locator is used here (replacing _dropDownValue())

**Review by SatishGandham — DISMISSED** [review]

File: app/client/src/widgets/SelectWidget/component/index.tsx [hunk 7]
```diff
@@ -60,20 +63,156 @@ class SelectComponent extends React.Component<
...
+    );
+    return (
+      <FixedSizeList
+        className="menu-virtual-list"
+        height={300}
+        initialScrollOffset={scrollOffset}
+        itemCount={items.length}
+        itemSize={ITEM_SIZE}
+        ref={this.listRef}
+        style={{ height: "auto", maxHeight: 300 }}
```
Comment (SatishGandham) [inline app/client/src/widgets/SelectWidget/component/index.tsx:210]: 1. Check what happens if the select is put in a small container, we may need min-height.
2. This will render whenever parent renders because style is a new object every-time. Since this static, move it out of the component

**Review by SatishGandham — CHANGES_REQUESTED** [review]

**Review by SatishGandham — DISMISSED** [review]

File: app/client/src/widgets/SelectWidget/component/index.tsx (hunk 7 above)
Comment (riodeuno) [reply app/client/src/widgets/SelectWidget/component/index.tsx:210]: We should also make this into an object -- as its properties have static values -- outside the component. as otherwise, there will be new references every time we render this component.

**Review by riodeuno — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@prsidhu Tested select widget and working fine.
