### PR TITLE
fix: Added support for self signed certificate during OAuth2 flows

### LINKED ISSUE #14275: [Bug]-[3520]:[OAuth2] Option required for self-signed certificates to be considered for Authorization call as well as final API Call
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In our evaluation, we have a containerized cluster of appsmith, a simple, but non trivial API based application, and a standards based simple OAuth 2.0 identity service (just in or out. No RBAC at this point). Each application runs in it's own container, and separate containers run to provide MongoDB and Redis to appsmith also, respectively. All of the appsmith functionality works, and we can't seem to see any functional issues with application design, etc.

All of the containerized applications are front-ended by an NGINX Proxy manager for ingress, and the IP address of the host VM (the platform running the complete docker instance) is mapped to the 3 applications (appsmith, IDServer and API) in their /etc/hosts file. **A self-signed certificate ensures that the whole experience performs over https** (this will become important later).
So far, this is all good and the network "wiring" seems to work

Now, here's the problem:
In the API, we have a number of endpoints, some we have protected with the identity server and some we have left unprotected (i.e. unauthenticated API). The unprotected API endpoint integrate and work with no issue whatsoever in appsmith.

We are using the "authorization code" flow, and after setting up the API integrations and supplying all the appropriate URL connections and callbacks, the "Save and Authorize" button DOES call out to the OAuth2 provider, and prompt for a login there. We have also attached the self-signed cert each API endpoint as specified at the end of the OAuth2 API configuration screen. Moreover, the OAuth2 provider also seems to correctly redirect back to the stated endpoint in appsmith.
However, whenever we try to test the API via a query on a page, we get the same error all the time:

**"Invalid authentication credentials. Please check datasource configuration."**

Additionally an error condition was spotted on returning to the API screen when "**Save & Authorize**" is hit, This is visible in the query param `&response_status=appsmith_error&`  in the URL after redirection.

According to the logs below generated by the "**Save & Authorize**" event, two different types of errors were seen at different times:

log from earlier version:

```
2022-05-10T15:28:57.878674482Z backend stdout | org.springframework.web.reactive.function.client.WebClientRequestException: Failed to resolve 'ingress.local' after 2 queries ; nested exception is java.net.UnknownHostException: Failed to resolve 'ingress.local' after 2 queries
2022-05-10T15:28:57.878676523Z backend stdout | at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
2022-05-10T15:28:57.878678396Z backend stdout | Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
2022-05-10T15:28:57.878680111Z backend stdout | Error has been observed at the following site(s):
2022-05-10T15:28:57.878681744Z backend stdout | *__checkpoint ⇢ Request to POST null [DefaultWebClient]
2022-05-10T15:28:57.878683862Z backend stdout | Original Stack Trace:
2022-05-10T15:28:57.878685503Z backend stdout | at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
2022-05-10T15:28:57.878696951Z backend stdout | at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
2022-05-10T15:28:57.878702794Z backend stdout | at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
2022-05-10T15:28:57.878704736Z backend stdout | at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
2022-05-10T15:28:57.878706524Z backend stdout | at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2022-05-10T15:28:57.878708223Z backend stdout | at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2022-05-10T15:28:57.878709919Z backend stdout | at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2022-05-10T15:28:57.878711596Z backend stdout | at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
2022-05-10T15:28:57.878713348Z backend stdout | at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
2022-05-10T15:28:57.878715068Z backend stdout | at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
2022-05-10T15:28:57.878717452Z backend stdout | at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
2022-05-10T15:28:57.878719268Z backend stdout | at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
2022-05-10T15:28:57.878720994Z backend stdout | at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
2022-05-10T15:28:57.878722692Z backend stdout | at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
2022-05-10T15:28:57.878724397Z backend stdout | at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
2022-05-10T15:28:57.878728208Z backend stdout | at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
2022-05-10T15:28:57.878729970Z backend stdout | at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
2022-05-10T15:28:57.878731715Z backend stdout | at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
2022-05-10T15:28:57.878733412Z backend stdout | at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
2022-05-10T15:28:57.878735118Z backend stdout | at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
2022-05-10T15:28:57.878736849Z backend stdout | at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:304)
2022-05-10T15:28:57.878738614Z backend stdout | at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
2022-05-10T15:28:57.878740342Z backend stdout | at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:154)
2022-05-10T15:28:57.878742098Z backend stdout | at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:477)
2022-05-10T15:28:57.878745768Z backend stdout | at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:401)
2022-05-10T15:28:57.878747614Z backend stdout | at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
2022-05-10T15:28:57.878749331Z backend stdout | at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
2022-05-10T15:28:57.878751030Z backend stdout | at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:536)
2022-05-10T15:28:57.878753047Z backend stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
2022-05-10T15:28:57.878754792Z backend stdout | at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
2022-05-10T15:28:57.878781887Z backend stdout | at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
2022-05-10T15:28:57.878786663Z backend stdout | at reactor.core.publisher.Operators.error(Operators.java:198)
2022-05-10T15:28:57.878788482Z backend stdout | at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
2022-05-10T15:28:57.878790183Z backend stdout | at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
2022-05-10T15:28:57.878791869Z backend stdout | at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
2022-05-10T15:28:57.878793581Z backend stdout | at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:517)
2022-05-10T15:28:57.878795287Z backend stdout | at reactor.netty.transport.TransportConnector.lambda$doResolveAndConnect$11(TransportConnector.java:324)
2022-05-10T15:28:57.878797059Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
2022-05-10T15:28:57.878798754Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
2022-05-10T15:28:57.878800440Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
2022-05-10T15:28:57.878802263Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
2022-05-10T15:28:57.878803927Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
2022-05-10T15:28:57.878805613Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
2022-05-10T15:28:57.878807305Z backend stdout | at io.netty.resolver.InetSocketAddressResolver$2.operationComplete(InetSocketAddressResolver.java:86)
2022-05-10T15:28:57.878809021Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
2022-05-10T15:28:57.878810759Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
2022-05-10T15:28:57.878815196Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
2022-05-10T15:28:57.878817061Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
2022-05-10T15:28:57.878819393Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
2022-05-10T15:28:57.878821157Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
2022-05-10T15:28:57.878822851Z backend stdout | at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
2022-05-10T15:28:57.878824537Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1055)
2022-05-10T15:28:57.878826226Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
2022-05-10T15:28:57.878827979Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
2022-05-10T15:28:57.878829667Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:605)
2022-05-10T15:28:57.878831327Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:66)
2022-05-10T15:28:57.878833020Z backend stdout | at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:462)
2022-05-10T15:28:57.878834717Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
2022-05-10T15:28:57.878836394Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
2022-05-10T15:28:57.878838108Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
2022-05-10T15:28:57.878839836Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
2022-05-10T15:28:57.878841575Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
2022-05-10T15:28:57.878843283Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
2022-05-10T15:28:57.878844985Z backend stdout | at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
2022-05-10T15:28:57.878846794Z backend stdout | at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:200)
2022-05-10T15:28:57.878848483Z backend stdout | at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:192)
2022-05-10T15:28:57.878850182Z backend stdout | at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1301)
2022-05-10T15:28:57.878851888Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-05-10T15:28:57.878853743Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-05-10T15:28:57.878857520Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-05-10T15:28:57.878859672Z backend stdout | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2022-05-10T15:28:57.878861622Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-05-10T15:28:57.878863355Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-05-10T15:28:57.878865085Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-05-10T15:28:57.878866812Z backend stdout | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2022-05-10T15:28:57.878868519Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-05-10T15:28:57.878870235Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-05-10T15:28:57.878872010Z backend stdout | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2022-05-10T15:28:57.878873734Z backend stdout | at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:618)
2022-05-10T15:28:57.878875433Z backend stdout | at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:653)
2022-05-10T15:28:57.878877121Z backend stdout | at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:56)
2022-05-10T15:28:57.878878845Z backend stdout | at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:492)
2022-05-10T15:28:57.878880573Z backend stdout | at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
2022-05-10T15:28:57.878882313Z backend stdout | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2022-05-10T15:28:57.878884009Z backend stdout | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
2022-05-10T15:28:57.878885917Z backend stdout | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
2022-05-10T15:28:57.878887625Z backend stdout | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2022-05-10T15:28:57.878889338Z backend stdout | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-05-10T15:28:57.878891034Z backend stdout | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-05-10T15:28:57.878894269Z backend stdout | at java.base/java.lang.Thread.run(Thread.java:829)
2022-05-10T15:28:57.878896001Z backend stdout | Caused by: java.net.UnknownHostException: Failed to resolve 'ingress.local' after 2 queries
2022-05-10T15:28:57.878897720Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
2022-05-10T15:28:57.878901164Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
2022-05-10T15:28:57.878902964Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
2022-05-10T15:28:57.878904649Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:605)
2022-05-10T15:28:57.878906346Z backend stdout | at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:66)
2022-05-10T15:28:57.878908041Z backend stdout | at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:462)
2022-05-10T15:28:57.878909735Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
2022-05-10T15:28:57.878911410Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
2022-05-10T15:28:57.878913128Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
2022-05-10T15:28:57.878915166Z backend stdout | at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
2022-05-10T15:28:57.878917106Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
2022-05-10T15:28:57.878918800Z backend stdout | at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
2022-05-10T15:28:57.878920535Z backend stdout | at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
2022-05-10T15:28:57.878922229Z backend stdout | at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:200)
2022-05-10T15:28:57.878924722Z backend stdout | at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:192)
2022-05-10T15:28:57.878926688Z backend stdout | at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1301)
2022-05-10T15:28:57.878928414Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-05-10T15:28:57.878930142Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-05-10T15:28:57.878932246Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-05-10T15:28:57.878934143Z backend stdout | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
2022-05-10T15:28:57.878935855Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-05-10T15:28:57.878939273Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-05-10T15:28:57.878941093Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-05-10T15:28:57.878942834Z backend stdout | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2022-05-10T15:28:57.878944538Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-05-10T15:28:57.878946270Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-05-10T15:28:57.878948043Z backend stdout | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2022-05-10T15:28:57.878949715Z backend stdout | at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:618)
2022-05-10T15:28:57.878951413Z backend stdout | at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:653)
2022-05-10T15:28:57.878953094Z backend stdout | at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:56)
2022-05-10T15:28:57.878954807Z backend stdout | at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:492)
2022-05-10T15:28:57.878956755Z backend stdout | at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
2022-05-10T15:28:57.878958489Z backend stdout | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2022-05-10T15:28:57.878960191Z backend stdout | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
2022-05-10T15:28:57.878961965Z backend stdout | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
2022-05-10T15:28:57.878963634Z backend stdout | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2022-05-10T15:28:57.878965335Z backend stdout | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-05-10T15:28:57.878967004Z backend stdout | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-05-10T15:28:57.878968695Z backend stdout | at java.base/java.lang.Thread.run(Thread.java:829)
```

Log from later version:

```
2022-06-02T14:57:17.880085285Z backend stdout | org.springframework.web.reactive.function.client.WebClientRequestException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2022-06-02T14:57:17.880087566Z backend stdout | at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
2022-06-02T14:57:17.880089457Z backend stdout | Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
2022-06-02T14:57:17.880091191Z backend stdout | Error has been observed at the following site(s):
2022-06-02T14:57:17.880092832Z backend stdout | *__checkpoint ⇢ Request to POST null [DefaultWebClient]
2022-06-02T14:57:17.880094948Z backend stdout | Original Stack Trace:
2022-06-02T14:57:17.880096603Z backend stdout | at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
2022-06-02T14:57:17.880098494Z backend stdout | at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
2022-06-02T14:57:17.880100246Z backend stdout | at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
2022-06-02T14:57:17.880101976Z backend stdout | at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
2022-06-02T14:57:17.880103755Z backend stdout | at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2022-06-02T14:57:17.880105450Z backend stdout | at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2022-06-02T14:57:17.880107181Z backend stdout | at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
2022-06-02T14:57:17.880108867Z backend stdout | at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
2022-06-02T14:57:17.880113501Z backend stdout | at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
2022-06-02T14:57:17.880115906Z backend stdout | at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
2022-06-02T14:57:17.880117742Z backend stdout | at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
2022-06-02T14:57:17.880119520Z backend stdout | at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
2022-06-02T14:57:17.880121283Z backend stdout | at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
2022-06-02T14:57:17.880122992Z backend stdout | at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
2022-06-02T14:57:17.880124743Z backend stdout | at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
2022-06-02T14:57:17.880126465Z backend stdout | at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
2022-06-02T14:57:17.880128173Z backend stdout | at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
2022-06-02T14:57:17.880129953Z backend stdout | at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
2022-06-02T14:57:17.880131656Z backend stdout | at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
2022-06-02T14:57:17.880133392Z backend stdout | at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
2022-06-02T14:57:17.880135138Z backend stdout | at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:304)
2022-06-02T14:57:17.880136910Z backend stdout | at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
2022-06-02T14:57:17.880138627Z backend stdout | at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onUncaughtException(DefaultPooledConnectionProvider.java:200)
2022-06-02T14:57:17.880140451Z backend stdout | at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onUncaughtException(DefaultPooledConnectionProvider.java:449)
2022-06-02T14:57:17.880142238Z backend stdout | at reactor.netty.channel.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:129)
2022-06-02T14:57:17.880144040Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
2022-06-02T14:57:17.880145969Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
2022-06-02T14:57:17.880147736Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
2022-06-02T14:57:17.880149499Z backend stdout | at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:424)
2022-06-02T14:57:17.880153034Z backend stdout | at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
2022-06-02T14:57:17.880164121Z backend stdout | at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:145)
2022-06-02T14:57:17.880165965Z backend stdout | at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
2022-06-02T14:57:17.880167675Z backend stdout | at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:231)
2022-06-02T14:57:17.880169495Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
2022-06-02T14:57:17.880171236Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
2022-06-02T14:57:17.880172993Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
2022-06-02T14:57:17.880174744Z backend stdout | at reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:834)
2022-06-02T14:57:17.880176439Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
2022-06-02T14:57:17.880178178Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
2022-06-02T14:57:17.880179940Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
2022-06-02T14:57:17.880181681Z backend stdout | at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1258)
2022-06-02T14:57:17.880183433Z backend stdout | at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1239)
2022-06-02T14:57:17.880185138Z backend stdout | at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
2022-06-02T14:57:17.880187186Z backend stdout | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
2022-06-02T14:57:17.880192255Z backend stdout | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
2022-06-02T14:57:17.880194083Z backend stdout | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
2022-06-02T14:57:17.880195823Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-06-02T14:57:17.880197557Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-06-02T14:57:17.880199283Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-06-02T14:57:17.880204810Z backend stdout | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2022-06-02T14:57:17.880206733Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-06-02T14:57:17.880208467Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-06-02T14:57:17.880210193Z backend stdout | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2022-06-02T14:57:17.880211920Z backend stdout | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
2022-06-02T14:57:17.880213692Z backend stdout | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
2022-06-02T14:57:17.880215407Z backend stdout | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
2022-06-02T14:57:17.880217083Z backend stdout | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2022-06-02T14:57:17.880218900Z backend stdout | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-06-02T14:57:17.880220614Z backend stdout | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-06-02T14:57:17.880222336Z backend stdout | at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-02T14:57:17.880224269Z backend stdout | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2022-06-02T14:57:17.880226155Z backend stdout | at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
2022-06-02T14:57:17.880227839Z backend stdout | at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
2022-06-02T14:57:17.880229515Z backend stdout | at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
2022-06-02T14:57:17.880231193Z backend stdout | at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
2022-06-02T14:57:17.880232922Z backend stdout | at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
2022-06-02T14:57:17.880234660Z backend stdout | at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
2022-06-02T14:57:17.880236396Z backend stdout | at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
2022-06-02T14:57:17.880238129Z backend stdout | at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
2022-06-02T14:57:17.880239785Z backend stdout | at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
2022-06-02T14:57:17.880241450Z backend stdout | at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
2022-06-02T14:57:17.880244807Z backend stdout | at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
2022-06-02T14:57:17.880246663Z backend stdout | at java.base/java.security.AccessController.doPrivileged(Native Method)
2022-06-02T14:57:17.880248392Z backend stdout | at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
2022-06-02T14:57:17.880250113Z backend stdout | at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1547)
2022-06-02T14:57:17.880251799Z backend stdout | at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1393)
2022-06-02T14:57:17.880253483Z backend stdout | at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
2022-06-02T14:57:17.880255169Z backend stdout | at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
2022-06-02T14:57:17.880256855Z backend stdout | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
2022-06-02T14:57:17.880258615Z backend stdout | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
2022-06-02T14:57:17.880260491Z backend stdout | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
2022-06-02T14:57:17.880262274Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-06-02T14:57:17.880264001Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-06-02T14:57:17.880265708Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2022-06-02T14:57:17.880267421Z backend stdout | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2022-06-02T14:57:17.880269133Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2022-06-02T14:57:17.880270835Z backend stdout | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2022-06-02T14:57:17.880272558Z backend stdout | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2022-06-02T14:57:17.880274265Z backend stdout | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
2022-06-02T14:57:17.880276026Z backend stdout | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
2022-06-02T14:57:17.880277729Z backend stdout | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
2022-06-02T14:57:17.880279406Z backend stdout | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2022-06-02T14:57:17.880281122Z backend stdout | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-06-02T14:57:17.880284416Z backend stdout | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-06-02T14:57:17.880286207Z backend stdout | at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-02T14:57:17.880287899Z backend stdout | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2022-06-02T14:57:17.880289717Z backend stdout | at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
2022-06-02T14:57:17.880291734Z backend stdout | at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
2022-06-02T14:57:17.880293456Z backend stdout | at java.base/sun.security.validator.Validator.validate(Validator.java:264)
2022-06-02T14:57:17.880295113Z backend stdout | at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
2022-06-02T14:57:17.880296806Z backend stdout | at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
2022-06-02T14:57:17.880298494Z backend stdout | at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
2022-06-02T14:57:17.880300210Z backend stdout | at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
2022-06-02T14:57:17.880301953Z backend stdout | ... 29 common frames omitted
2022-06-02T14:57:17.880303576Z backend stdout | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2022-06-02T14:57:17.880305364Z backend stdout | at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
2022-06-02T14:57:17.880307067Z backend stdout | at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
2022-06-02T14:57:17.880308841Z backend stdout | at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
2022-06-02T14:57:17.880310527Z backend stdout | at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
2022-06-02T14:57:17.880312230Z backend stdout | ... 35 common frames omitted
```

### Steps To Reproduce

1. Prepare appsmith environment to launch from and communicate with internal API services protected by internal OAuth2.0 service provider implementation, from docker/portainer/vagrant/virtualbox setup. Virtual Machine is Ubuntu Server 21.04
2. Prepare self signed wildcard key/cert for `*.ingress.local` and use it for **ALL** deployed appliances, varying the first member of the domain to differentiate the service, i.e. `ap.ingress.local` for appsmith, `mox.ingress.local` and `mox2.ingress.local` for the APIs and `fief.ingress.local` and `oa2.ingress.local` for the Oauth2 service providers
3. Complete an Authenticated API setup in appsmith, using the Oauth2 option, and the 'Authorization Code' flow, ensuring that a copy of the `*.ingress.local` cert is uploaded in the **advanced** section of the setup

### Public Sample App

_No response_

### Version

1.7.0 and previously 1.6.25

### PR DESCRIPTION
**Pull request by nidhi-nair**
This PR only includes the server side changes. I'm not sure how we're meant to use switches in datasources.

Fixes #14275 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Unable to write JUnit test case for self-signed certs, have tested the flow manually
- We will need to create Cypress tests when the client side changes come in

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 1]
```diff
@@ -164,7 +167,15 @@ public Mono<String> getAccessTokenForGenericOAuth2(AuthorizationCodeCallbackDTO
                 .flatMap(datasourceService::getById)
                 .flatMap(datasource -> {
                     OAuth2 oAuth2 = (OAuth2) datasource.getDatasourceConfiguration().getAuthentication();
-                    WebClient.Builder builder = WebClient.builder().baseUrl(oAuth2.getAccessTokenUrl());
+                    final HttpClient httpClient = HttpClient.create();
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:170]: These few lines to create http client and check for self signed cert seems to be duplicated in Authorisation code and client credentials code section as well. Can we instead create a utility method somewhere like `getHttpClient` and then use that to prevent code duplication ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSLHelper.java [hunk 2]
```diff
@@ -50,4 +55,26 @@ public static TrustManagerFactory getSslTrustManagerFactory(UploadedFile certifi
 
         return trustManagerFactory;
     }
+
+    public static Consumer<? super SslProvider.SslContextSpec> sslCheckForHttpClient(DatasourceConfiguration datasourceConfiguration) {
```
[the remark this answers is not in the document]
Comment (nidhi-nair) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSLHelper.java:59]: That's actually the expected type for the lambda where this is used. I'm guessing the spec ends up being the vessel to hold other mutable configs. I've just retained the same type. :)

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 1 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:170]: I've collected some of the logic for this into `ApiConnection`, which is a super type for these and all other types that we'll want to use for REST. I've left out the WebClient optimization though, because that will be coming in with one of Shri's [PR](https://github.com/appsmithorg/appsmith/pull/14427) which is WIP.

Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:170]: Can we use the `getSecuredHttpClient` method here as well ?

Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:170]: We'll be picking up this refactor after the conflicting PRs are merged in. Tracking this change [here](https://github.com/appsmithorg/appsmith/issues/15257).

**Review by sumitsum — APPROVED** [review]

**Review by Aishwarya-U-R — DISMISSED** [review]
Approving cypress changes!
