### PR TITLE
fix: flaky mongo spec test

### LINKED ISSUE #35149: [Task]: Fix flakiness of cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts
### SubTasks

Tested flakiness on this PR https://github.com/appsmithorg/appsmith/pull/33856

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
RCA:
The test started acting flaky because of the ted mongo db had new entries which changed the index value of the record that we were trying to verify. 

Solution:
We get the index value of the record by finding the record entry in a column and the traversing back to parent and getting index of the row item. This returned index is then used to match the record instead of just passing `0` which will still work if the new entries are made in the db.

Fixes #35149  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10789425505>
> Commit: dc720a1f47903776d5972a47d35bbb922e0653c3
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10789425505&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Tue, 10 Sep 2024 09:51:00 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced CRUD validation tests for MongoDB, improving dropdown selection and table data validation.
	- Introduced a new method for more precise targeting of table column data based on column index and text content.

- **Bug Fixes**
	- Improved reliability of tests by dynamically locating data rows instead of using hardcoded values.

- **Chores**
	- Updated the limited tests to reflect a shift in focus from client-side to server-side functionality.

### CODE REVIEW

**Review by sagar-qa007 — APPROVED** [review]

File: app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts [hunk 1]
```diff
@@ -103,30 +107,68 @@ describe(
...
+            expect($cellData).to.eq(col2Text);
+          });
+        table
+          .ReadTableRowColumnData(rowIndex, 6, "v2", 200)
+          .then(($cellData) => {
+            expect($cellData).to.eq(col3Text);
+          });
+
+        //Validating loaded JSON form
+        cy.xpath(locators._buttonByText("Update")).then((selector) => {
```
Comment (mohanarpit) [inline app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts:135]: @sagar-qa007 @AmanAgarwal041 Is using an xpath a best practice in Cypress? Or do we have no other alternatives that could have been used here? 

I'm asking this because the package `cypress-xpath` has been deprecated a year ago. Additionally, Cypress recommends using more specific ids to select elements rather than xpath.

Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts:135]: @mohanarpit Yeah we should ideally remove that and go for the css selectors. It was already there, but we can definitely update this.
cc @sagar-qa007

Comment (sagar-qa007) [reply app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts:135]: Yes agree and noted. @mohanarpit 

@AmanAgarwal041 It has present multiple places, can we update on that specs too? It will be good optimisation.

Comment (mohanarpit) [reply app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts:135]: @AmanAgarwal041 Is there a CSS selector already available for this validation today? If yes, can we change it right now? If not, then we'll leave it for the time being.

Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts:135]: @mohanarpit I am not really sure we have something like that, because we have a repetitive block in around 8 files. @sagar-qa007 Can we add a task to update this block at every place ?
List of files : 

1. app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts
2. app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts
3. app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MySQL1_Spec.ts
4. app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MySQL2_Spec.ts
5. app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Postgres1_Spec.ts
6. app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Postgres2_Spec.ts
7. app/client/cypress/e2e/Regression/ServerSide/QueryPane/Mongo1_spec.ts
8. app/client/cypress/e2e/Sanity/Datasources/MsSQL_Basic_Spec.ts
