### PR TITLE
Fix triggering of onChange when value is the same

### LINKED ISSUE #710: [BUG] Dropdown onOptionChange is triggering on selecting the same option.
## Description
Dropdown `onOptionChange` event is getting triggered on selecting the same option.

### Steps to reproduce the behaviour:
1. Add `showMessage()` to dropdown's `onOptionChange`.
2. Select any dropdown option and the message should appear.
3. Select the selected dropdown option again and the message will again appear.

[Video In Action](https://drive.google.com/file/d/18RGp31D5OKN6PMUpkMNqIFE-JbHJfzpX/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

### PR DESCRIPTION
**Pull request by wasabigeek**
Fixes #710

### CODE REVIEW

File: app/client/src/widgets/DropdownWidget.tsx [hunk 1]
```diff
@@ -136,7 +136,11 @@ class DropdownWidget extends BaseWidget<DropdownWidgetProps, WidgetState> {
   }
 
   onOptionSelected = (selectedOption: DropdownOption) => {
+    let isChanged = true;
     if (this.props.selectionType === "SINGLE_SELECT") {
+      if (this.props.selectedOption.value == selectedOption.value) {
+        isChanged = false;
+      }
       this.updateWidgetMetaProperty(
```
Comment (hetunandu) [inline app/client/src/widgets/DropdownWidget.tsx:144]: We should also avoid updates when the values are the same

**Review by hetunandu — CHANGES_REQUESTED** [review]
Minor change needed

**Review by hetunandu — APPROVED** [review]

**Comment by hetunandu** [comment]
Hey @wasabigeek ! This was a great PR. Thanks a lot for contributing 😄
