### PR TITLE
fix: Add collapse icon for bottom bar

### LINKED ISSUE #16855: [Feature]: Need a minimize/collapse icon for the debugger on the query editor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, there's a close/collapse icon present on the debugger for the canvas and JS editor but there's no such icon present on the query editor. This needs to be added and the experience needs to be made consistent across the platform

### Why should this be worked on?

**On the cavnas**
image

**On the JS editor**
image

**On the query editor**
image

### PR DESCRIPTION
**Pull request by eco-monk**
Fixes #16855

## Description

Cypress:
- Added EntityBottomBar_spec.ts.
- Created an object registry for commonly used methods in debugger.
- Cleaned up debugger locators

---

Functional:

Add collapse icon for bottom bar in query and api pages.
Open collapsed bottom bar on header click.

- Added `containerRef` and `expandedHeight` props to bottom bar component.
This was being checked internally to enable the collapse icon.
- Also fixed alignment for result and status text.
- Changed collapse icon to arrow down in debugger, to keep things consistent.
- Made Debugger/API/Query/Js bottom panes similar in height
- Removed unwanted padding in api response view. (helps remove nested scroll bars)

---

API:
image
image

Query:
image
image

Debugger:
image
image

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hetunandu — DISMISSED** [review]

**Review by hetunandu — APPROVED** [review]

**Comment by eco-monk** [comment]
Not to be merged yet.
Awaiting comments from @Aishwarya-U-R for cypress clean-ups.

File: app/client/src/components/ads/Tabs.tsx [hunk 1]
```diff
@@ -119,13 +119,6 @@ const TabsWrapper = styled.div<{
         font-weight: normal;
       `}
   }
-
```
Comment (albinAppsmith) [inline app/client/src/components/ads/Tabs.tsx:122]: These changes needs to be validated all places where tabs component is being used. Is that accommodated in QA?

Comment (albinAppsmith) [reply app/client/src/components/ads/Tabs.tsx:122]: https://docs.google.com/spreadsheets/d/1np7jQdiQa0nyryOBnNa927NkGDplG9M2gb7qnoZIIyM/edit#gid=1633263761

Refer this sheet for current usage

Comment (eco-monk) [reply app/client/src/components/ads/Tabs.tsx:122]: Some details.

I've tried to keep the changes very specific to:
- Tabs that have a `responseViewer` (margin and padding removed)
- Tabs that have a collapsable icon (expand on header click)

Both of which drills down to the `EntityBottomTabs` component. Which is the bottom pane of API/Query/Js pages.

Comment (eco-monk) [reply app/client/src/components/ads/Tabs.tsx:122]: cc: @Richarex

File: app/client/cypress/support/Pages/DataSources.ts [hunk 2]
```diff
@@ -659,4 +679,23 @@ export class DataSources {
...
+
+  openResponseTab() {
+    this.agHelper.GetNClick(this.locator._responseTab);
+  }
+
+  closeBottomPane() {
+    this.agHelper.GetNClick(this.locator._bottomPaneCollapseIcon);
+  }
+
+  isBottomPaneOpen() {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:691]: This method name can be - AssertBottomPaneOpen() - because now it gives feeling of validation of yes or no type..

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.ts [hunk 3]
```diff
@@ -1,11 +1,10 @@
 const commonlocators = require("../../../../locators/commonlocators.json");
-const debuggerLocators = require("../../../../locators/Debugger.json");
 import { ObjectsRegistry } from "../../../../support/Objects/Registry";
 
 const {
   AggregateHelper: agHelper,
   ApiPage: apiPage,
-  CommonLocators: locator,
+  Debugger: _debugger,
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.ts:7]: nit: Debugger : debugger - since "underscore" is for a ts modal locator indicator..

File: app/client/cypress/support/Pages/DataSources.ts [hunk 4]
```diff
@@ -216,6 +219,14 @@ export class DataSources {
     cy.get(this._newDatabases).should("be.visible");
   }
 
+  createMockDB(dbName: "Users" | "Movies"): Cypress.Chainable<string> {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:222]: nit: Method names are Pascal case :)

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.ts (hunk 3 above)
Comment (eco-monk) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.ts:7]: `debugger` is a JS keyword, hence added the _.
Will rename to `debuggerHelper` instead.

**Comment by eco-monk** [comment]
We'll be holding this PR for now.
`TabsComponent` changes will be pushed through the `design-system`.

We can proceed after that.
cc: @Richarex @ginilpg @albinAppsmith

**Review by tanvibhakta — APPROVED** [review]

**Review by akash-codemonk — APPROVED** [review]

**Comment by ramsaptami** [comment]
LGTM, please go ahead and merge this to release
cc: @eco-monk

**Comment by eco-monk** [comment]
Thanks @ramsaptami.
Waiting on CI now, will merge once it's done.
