### PR TITLE
fix: rich text editor cursor fix

### LINKED ISSUE #7231: [Bug] Cursor shifts position while typing in Rich Text Editor Widget
## Description

https://user-images.githubusercontent.com/23132741/132465865-a22c1651-e32d-4156-92ea-578a858d0455.mov

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to https://app.appsmith.com/applications/6131b0ce987e5a1cc9ff72f3/pages/61326208987e5a1cc9ff74f0
2. Click on new Post
3. Try to type inside Rich Text Editor Widget
3. See error

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Fix cursur position in RTE widget when using markdown

Fixes #7231

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/Rich-text-editor-cursor-position 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.08 **(0)** | 36.51 **(-0.01)** | 34.48 **(0)** | 55.61 **(0)**
 :red_circle: | app/client/src/widgets/RichTextEditorWidget/widget/index.tsx | 65 **(-7.22)** | 15.38 **(-6.84)** | 58.33 **(0)** | 65.79 **(-7.74)**</details>

### CODE REVIEW

**Comment by vicky-primathon** [comment]
@Tooluloope, this fix does not solves the issue.

https://www.loom.com/share/30ed16be9d74410babf4e7ef89582757

**Comment by Tooluloope** [comment]
@vicky-primathon Could you check it now?

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx [hunk 1]
```diff
@@ -26,112 +25,59 @@ export interface RichtextEditorComponentProps {
...
+        onEditorChange={(newValue) => {
+          if (newValue === value) return;
+          setValue(newValue);
+        }}
+        onInit={(evt, editor) => {
+          editorRef.current = editor;
+        }}
+        tinymceScriptSrc="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.10.1/tinymce.min.js"
+        toolbar={props.isToolbarHidden ? false : toolbarConfig}
+        value={value}
```
Comment (vicky-primathon) [inline app/client/src/widgets/RichTextEditorWidget/component/index.tsx:79]: @Tooluloope earlier we were setting value of tinymce editor as HTML content. In current PR input type Markdown has stopped working. Not sure it is exactly the issue for Mardown is due to same reason.

Comment (Tooluloope) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:79]: Could you check if markdown was previously working on release?

Comment (vicky-primathon) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:79]: Screenshot 2021-12-24 at 2 43 15 PM

**Review by vicky-primathon — APPROVED** [review]
LGTM

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Verified this PR and working fine now.

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx [hunk 2]
```diff
@@ -26,112 +25,67 @@ export interface RichtextEditorComponentProps {
...
-    if (editorInstance !== null) {
-      editorInstance.mode.set(
-        props.isDisabled === true ? "readonly" : "design",
-      );
-    }
-  }, [props.isDisabled, editorInstance, isEditorInitialised]);
+    if (!value) return;
+    // Prevent calling onTextChange when initialized
+    if (!isInit.current) return;
+    const timeOutId = setTimeout(() => props.onValueChange(value), 1000);
```
[the remark this answers is not in the document]
Comment (Rishabh-Rathod) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:45]: Yes, but that will cause problems in the evaluation as the values are not getting sent to workers for that long. 

Issues like https://github.com/appsmithorg/appsmith/issues/14045#issuecomment-1135739897

[the remark this answers is not in the document]
Comment (Rishabh-Rathod) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:45]: Also, I would like to understand why we want to avoid firing `onValueChange` ?

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx [hunk 3]
```diff
@@ -26,112 +25,67 @@ export interface RichtextEditorComponentProps {
...
 export function RichtextEditorComponent(props: RichtextEditorComponentProps) {
-  const status = useScript(
-    "https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.7.0/tinymce.min.js",
-  );
-
-  const [isEditorInitialised, setIsEditorInitialised] = useState(false);
-  const [editorInstance, setEditorInstance] = useState(null as any);
+  const [value, setValue] = React.useState<string>(props.defaultText as string);
+  const editorRef = useRef<any>(null);
+  const isInit = useRef<boolean>(false);
```
Comment (Rishabh-Rathod) [inline app/client/src/widgets/RichTextEditorWidget/component/index.tsx:36]: The local state in component seems to be introduced here.

**Review by Rajamudadolarkuning — COMMENTED** [review]
> > # ~~~~~~~~~~~~
