### PR TITLE
Welcome tour GIF and Close button fixes

### LINKED ISSUE #6153: [Task] Onboarding flow | Wrong gif on welcome tour window.
## Change the gif on welcome tour.
- Present GIF of "New Query" needs to be updated to match the current Orange buttons.

Screenshot 2021-07-26 at 9 48 54 PM

### LINKED ISSUE #6154: Onboarding Flow | The "Great job" card doesn't let user try the new app.
## Description

The "Great job" card overrides the new launched app.  It should either have an END tour button or should transition to left or button after 5 seconds for the user to open it when they want to see next steps. This will let user try out the app they just created. 

Screenshot 2021-07-26 at 9 59 42 PM

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

PR contains fixes features related to welcome tour popup

Fixes #6154 
Fixes #6153 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Verified in local whether GIF is changed or not in new query tour section.
- Verified close button not showing in any other pages than final page.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/new-query-gif-changed 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.73 **(-0.01)** | 33.5 **(-0.02)** | 29.4 **(-0.06)** | 52.39 **(-0.01)**
 :sparkles: :new: | **app/client/src/components/designSystems/blueprint/CloseButton.tsx** | **55.56** | **100** | **0** | **55.56**
 :red_circle: | app/client/src/components/editorComponents/Onboarding/Helper.tsx | 67.9 **(-3.31)** | 36.04 **(-0.15)** | 21.74 **(-9.51)** | 65.33 **(-4.02)**
 :green_circle: | app/client/src/constants/messages.ts | 69.1 **(-0.01)** | 100 **(0)** | 6.67 **(-0.02)** | 76.13 **(0.07)**
 :red_circle: | app/client/src/utils/helpers.tsx | 53.05 **(-1.83)** | 26.03 **(-4.11)** | 21.43 **(-3.57)** | 46.51 **(-1.55)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

File: app/client/src/components/editorComponents/Onboarding/Helper.tsx [hunk 1]
```diff
@@ -183,6 +189,19 @@ const SubStepContainer = styled.div`
...
+  left: 0;
+  z-index: 8;
+  padding: 12px 8px;
+  background-color: #df613c;
+  color: #fff;
+  font-weight: 500;
+  cursor: pointer;
+  writing-mode: vertical-rl;
+  text-orientation: mixed;
+`;
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/Onboarding/Helper.tsx:204]: nitpick:
we could use theme variables here:
- `props.theme.colors` for colors
- `getTypographyByKey` for fonts
- `props.theme.spaces` for padding

For z-index, we should use `layers` from `constants/Layers`

**Review by rishabhsaxena — DISMISSED** [review]

**Comment by rishabhsaxena** [comment]
Think the run button is also in the prev theme color, should update that as well.

File: app/client/src/components/editorComponents/Onboarding/Helper.tsx (hunk 1 above)
Comment (albinAppsmith) [reply app/client/src/components/editorComponents/Onboarding/Helper.tsx:204]: Thank you Rishabh for pointing out will take care of these

**Review by rishabhsaxena — DISMISSED** [review]

**Review by rishabhsaxena — APPROVED** [review]
