### PR TITLE
fix default override same value

### LINKED ISSUE #3443: [Bug] Bound input widgets don't update their value if edited, when the resulting value has not changed
This issue is best demonstrated with a video:

https://user-images.githubusercontent.com/120119/110352149-92e82a00-805b-11eb-9c42-b4d89e07e898.mov

In words,

1. Drop a table and an input widget.
2. Bind the input widget's default value to `{{Table1.selectedRow.email}}` (assuming `email` is a valid column in the table, and at least two rows have the **same** value for `email`.
3. Now select a row with the duplicated email.
4. Edit the text inside the input widget.
5. Now select a row with a different email. Notice that the email is updated in the input widget.
6. Now select the email from point 3 again.
7. Edit the text inside the input widget, like point 4 again.
8. Now select a row with the *same* email. Notice that the email is **not** updated in the input widget.

The inconsistency in behavior in points 5 and 8 is unexpected.

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Default value overrides happen by tracking value changes of their paths. Post our subtree optimisations, this can be improved by always updating the version of the default value property if it gets evaluated. That way, we make sure that the values are overridden any time the default property value changes

Fixes #3443

### CODE REVIEW

**Review by trishaanand — APPROVED** [review]

**Comment by trishaanand** [comment]
Approved for the cypress tests to run.

File: app/client/src/workers/DataTreeEvaluator.ts [hunk 1]
```diff
@@ -345,6 +345,7 @@ export default class DataTreeEvaluator {
   ): DataTree {
     const tree = _.cloneDeep(oldUnevalTree);
     try {
+      debugger;
```
Comment (hetunandu) [inline app/client/src/workers/DataTreeEvaluator.ts:348]: Remove

Comment (hetunandu) [reply app/client/src/workers/DataTreeEvaluator.ts:348]:
```suggestion

```

**Comment by trishaanand** [comment]
Approving for running cypress tests.

**Review by trishaanand — APPROVED** [review]

File: app/client/src/workers/DataTreeEvaluator.ts [hunk 2]
```diff
@@ -615,7 +622,7 @@ export default class DataTreeEvaluator {
       return unEvalPropertyValue;
     } else {
       const parsedCache = this.getParsedValueCache(propertyPath);
-      if (!equal(parsedCache.value, parsed)) {
+      if (!equal(parsedCache.value, parsed) || isDefaultProperty) {
```
Comment (trishaanand) [inline app/client/src/workers/DataTreeEvaluator.ts:625]:
```suggestion
      // In case this is a default property, always set the cache even in the value remains the same so that the version 
      // in cache gets updated and the property dependent on default property updates accordingly.
      if (!equal(parsedCache.value, parsed) || isDefaultProperty) {
```

**Review by trishaanand — DISMISSED** [review]

File: app/client/src/workers/DataTreeEvaluator.ts [hunk 3]
```diff
@@ -615,7 +622,9 @@ export default class DataTreeEvaluator {
       return unEvalPropertyValue;
     } else {
       const parsedCache = this.getParsedValueCache(propertyPath);
-      if (!equal(parsedCache.value, parsed)) {
+      // In case this is a default property, always set the cache even in the value remains the same so that the version
```
Comment (hetunandu) [inline app/client/src/workers/DataTreeEvaluator.ts:625]:
```suggestion
      // In case this is a default property, always set the cache even in the value remains the same so that the version
```

**Review by Nikhil-Nandagopal — APPROVED** [review]
