### PR TITLE
fix: exported datasource only sensitive fields set as null

### LINKED ISSUE #20545: [Bug]: Datasource Reconnect Modal for Authenticated Datasource, all setting values are lost on export/import
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When exporting and importing an app that uses an Authenticated API datasource, the reconnect modal appears but all fields are blank. There are several unencrypted fields that should be retained, like the URL, content-type or accept headers, etc.  

### Steps To Reproduce

A user in Discord is facing this issue:
https://discord.com/channels/725602949748752515/725609493974614076/1073222215182581781

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Appsmith v1.9.7-SNAPSHOT

### PR DESCRIPTION
**Pull request by NilanshBansal**
Ref: https://www.notion.so/Datasource-Configuration-on-Exporting-App-924d18f1b0ec4451a482bc41d7271721

#### PR fixes following issue(s)
Fixes #20545 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sumitsum — DISMISSED** [review]

**Review by AnaghHegde — CHANGES_REQUESTED** [review]
Please verify the behaviour on git with multiple instances

File: app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/export/DatasourceExportableServiceCEImpl.java [hunk 1]
```diff
@@ -99,6 +99,13 @@ public Mono<List<Datasource>> getExportableEntities(
         });
     }
 
+    private void resetSensitiveFields(DatasourceStorage datasourceStorage) {
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/export/DatasourceExportableServiceCEImpl.java:102]: Can you change the name remove instead of reset?

**Review by AnaghHegde — CHANGES_REQUESTED** [review]
Minor nit, rest looks good.

**Review by AnaghHegde — APPROVED** [review]
