### PR TITLE
fix: failing cypress tests and cyclic dependency issue

### LINKED ISSUE #14281: [Task]: Create and execute test plan for Jest and Cypress tests
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Verify test plan with QA (@prapullac)
- Make sure QA's test plan also has automated coverage

### PR DESCRIPTION
**Pull request by Irongade**
This PR fixes various failing cypress tests for the google sheets UQI and also fixes a cyclic dependency oversight problem.

Fixes #14281

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Cypress tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/workers/evaluationUtils.ts [hunk 1]
```diff
@@ -209,12 +209,12 @@ export const translateDiffEventToDataTreeDiffEvent = (
         if (isTrueObject(difference.lhs)) {
           Object.keys(difference.lhs).forEach((diffKey) => {
             const path = `${propertyPath}.${diffKey}`;
-            return {
+            (result as DataTreeDiff[]).push({
```
Comment (ohansFavour) [inline app/client/src/workers/evaluationUtils.ts:212]: Verified ✅
