### PR TITLE
fix: edit datasource for External saas plugins

### LINKED ISSUE #38472: [Task]: Test for Import Export and Git Flows
### SubTasks

Test for Import Export and Git Flows for the datasource created using externalSaas plugin

### LINKED ISSUE #38649: [Bug]: Edit datasource is not working for Integrations
### Is there an existing issue for this?

- [X] I have searched the existing issues

List of Test Party Issues:
- [x] No redirect to editor after connecting with zendesk
- [x] Weird text in datasource review page. It should be: Authentication type: OAuth
- [x] Handling loading for datasources
- [x] Use pluginName instead of a regex to create paragon integration in code base
- [x] Edit datasource is not working, it should take to paragon auth page on edit
- [x] On connecting datasource through onboarding flow, it doesn’t gets redirected to application page
- [x] We should display subdomain in the datasource review page for zendesk - Add provider data key in auth object

### Description

After creating Integrations like zendesk, when we try to edit the datasource, it renders a wrong form and on clicking on save datasource, it redirects to a error auth page.
Since, the authorization of these types of datasources is differently, hence we need to fix that.

### Steps To Reproduce

1. Create zendesk datasource.
2. Click on Edit 
3. Click on save datasource cta.

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Self hosted

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
In External Saas Plugin, there were couple of issues which are solved by this PR:
- Edit datasource not working
- After successful auth from on boarding flow, it wasn't redirecting to the application
- Import/Export was not working
- Restructured the view mode datasource information renderer
- Is creating flag handled on the datasource listing page

Fixes #38649
Fixes #38472

_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource, @tag.ImportExport, @tag.Workspace"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12827204806>
> Commit: 5685b006eaed9805484b5003e6d49cb372d72945
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12827204806&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource, @tag.ImportExport, @tag.Workspace`
> Spec:
> <hr>Fri, 17 Jan 2025 11:24:01 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Added a new "Connect Datasource" button for external SaaS datasources.
  - Introduced enhanced datasource form rendering with more flexible configuration.
  - Added support for provider-specific data in external SaaS authentication.
  - Introduced a new `ExternalSaasConnection` component for managing external connections.

- **Improvements**
  - Updated datasource connection and loading state management.
  - Refined UI styling for overlays, popovers, and menu items.
  - Enhanced plugin and datasource interface with additional properties.
  - Improved sorting and filtering of displayed plugins.

- **Bug Fixes**
  - Improved error handling in datasource form rendering.
  - Added loading state indicators for the datasource creation process.

### CODE REVIEW

File: app/client/src/entities/Datasource/index.ts [hunk 1]
```diff
@@ -211,6 +211,7 @@ export interface ExternalSaasDSAuthentication extends DatasourceAuthentication {
   integrationId: string;
```
Comment (NilanshBansal) [inline app/client/src/entities/Datasource/index.ts:211]: Is it okay to have the `ExternalSaasDSAuthentication` in CE codebase when the plugin implementation is EE only?
@AmanAgarwal041 @sneha122

File: app/client/src/constants/AppsmithActionConstants/formConfig/ApiDatasourceFormsButtonConfig.ts [hunk 2]
```diff
@@ -4,5 +4,5 @@ export default {
   SAAS: ["CANCEL", "SAVE_AND_AUTHORIZE"],
   REMOTE: ["CANCEL", "SAVE"],
   AI: ["TEST", "CANCEL", "SAVE"],
-  EXTERNAL_SAAS: ["CANCEL", "SAVE_AND_AUTHORIZE"],
+  EXTERNAL_SAAS: ["CANCEL", "CONNECT_DATASOURCE"],
```
Comment (NilanshBansal) [inline app/client/src/constants/AppsmithActionConstants/formConfig/ApiDatasourceFormsButtonConfig.ts:7]: @AmanAgarwal041 Please check if defining this in CE is alright?

File: app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx [hunk 3]
```diff
@@ -69,6 +70,10 @@ class DatasourceDBEditor extends JSONtoForm<Props> {
       return null;
     }
 
+    if (this.props.pluginType === PluginType.EXTERNAL_SAAS) {
+      return <ExternalSaasConnection />;
```
Comment (NilanshBansal) [inline app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx:74]: @AmanAgarwal041 Do we need this in CE?

File: app/client/src/pages/Editor/DataSourceEditor/ExternalSaasConnection.tsx [hunk 4]
```diff
@@ -0,0 +1,57 @@
+import { Flex, Text } from "@appsmith/ads";
```
Comment (NilanshBansal) [inline app/client/src/pages/Editor/DataSourceEditor/ExternalSaasConnection.tsx:1]: @AmanAgarwal041 Please check if this needs to be present only in EE.
cc: @sneha122

File: app/client/src/pages/Editor/IntegrationEditor/APIOrSaasPlugins.tsx [hunk 5]
```diff
@@ -291,9 +299,12 @@ const mapStateToProps = (
         p.type === PluginType.EXTERNAL_SAAS,
```
Comment (NilanshBansal) [inline app/client/src/pages/Editor/IntegrationEditor/APIOrSaasPlugins.tsx:299]: Do we need this check in CE codebase? Is it possible to override using EE?

File: app/client/src/pages/common/datasourceAuth/index.tsx [hunk 6]
```diff
@@ -333,7 +336,7 @@ function DatasourceAuth({
         updateDatasource(
           getSanitizedFormData(),
           currentEnvironment,
-          pluginType
+          pluginType && pluginType !== PluginType.EXTERNAL_SAAS
```
Comment (NilanshBansal) [inline app/client/src/pages/common/datasourceAuth/index.tsx:339]: Same with this check.

File: app/client/src/pages/common/datasourceAuth/index.tsx [hunk 7]
```diff
@@ -438,6 +441,18 @@ function DatasourceAuth({
           {createMessage(SAVE_AND_AUTHORIZE_BUTTON_TEXT)}
         </Button>
       ),
+      [DatasourceButtonType.CONNECT_DATASOURCE]: (
```
Comment (NilanshBansal) [inline app/client/src/pages/common/datasourceAuth/index.tsx:444]: @AmanAgarwal041 please check this as well if it needs to be EE only

File: app/client/src/entities/Datasource/index.ts (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/src/entities/Datasource/index.ts:211]: This component renders null in CE.

File: app/client/src/constants/AppsmithActionConstants/formConfig/ApiDatasourceFormsButtonConfig.ts (hunk 2 above)
Comment (AmanAgarwal041) [reply app/client/src/constants/AppsmithActionConstants/formConfig/ApiDatasourceFormsButtonConfig.ts:7]: Its a configuration so we can keep it in CE and doesn't expose any implementation.

File: app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx (hunk 3 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx:74]: On CE, it won't return anything just return null. And on CE we won't have any EXTERNAL_SAAS plugin from the backend. As it is not required to split this file in CE and EE. We can keep this logic here in CE.

File: app/client/src/pages/Editor/DataSourceEditor/ExternalSaasConnection.tsx (hunk 4 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/DataSourceEditor/ExternalSaasConnection.tsx]: Moved to EE.

File: app/client/src/pages/Editor/IntegrationEditor/APIOrSaasPlugins.tsx (hunk 5 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/IntegrationEditor/APIOrSaasPlugins.tsx:299]: A lot of implementation would be repeated for just one condition, so it is ok to keep in the CE.

File: app/client/src/pages/common/datasourceAuth/index.tsx (hunk 6 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/common/datasourceAuth/index.tsx:339]: Its just a condition to avoid passing extra params for EXTERNAL_SAAS plugin.

File: app/client/src/pages/common/datasourceAuth/index.tsx (hunk 7 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/common/datasourceAuth/index.tsx:444]: Its a config button, which is just a text change for the edit datasource button for EXTERNAL_SAAS plugin. There is no need for it to be moved to EE.

**Review by sneha122 — APPROVED** [review]
