### PR TITLE
Autoscroll to invited organisation

### LINKED ISSUE #2359: [Enhancement ] Auto scroll to invited organization when invited
Steps to reproduce:
1) Add a Organisation
2) Share an Invite to user
3) Login  to mail 
4) Click on "Go to Appsmith"
5) User is lead to Sign Up / Login page 
6) User is lead to home page

Expectation:
As we lead the user to homepage we can lead the user to respective Organisation that was shared with the user

### PR DESCRIPTION
**Pull request by abhvsn**
Fixes #2359 
> if no issue exists, please create an issue and ask the maintainers about this first

## How Has This Been Tested?

> JUnit TCs
> Manual 

1. Sharing organisation to the existing user
2. Sharing organisation to new user

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java [hunk 1]
```diff
@@ -30,11 +30,7 @@
 import reactor.core.publisher.Mono;
 import reactor.test.StepVerifier;
 
-import java.util.ArrayList;
-import java.util.Arrays;
-import java.util.HashSet;
-import java.util.List;
-import java.util.Set;
+import java.util.*;
```
Comment (sharat87) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java:33]: Star imports are considered dangerous since they import much more than what we actually want and they do it implicitly. Please configure your IntelliJ so that it doesn't automatically do star imports. Here's a screenshot on how to do it:

Screenshot 2021-04-09 at 15 01 16

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java [hunk 2]
```diff
@@ -86,6 +86,10 @@
     // We default the origin header to the production deployment of the client's URL
     private static final String DEFAULT_ORIGIN_HEADER = "https://app.appsmith.com";
 
+    public enum typeOfEmail {welcome, passwordReset, inviteExistingUserToOrg, inviteNewUserToOrg}
+
+    ;
+
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java:92]: Looks like this is unused. Can we remove it?

**Comment by abhvsn** [comment]
Refactored code pushed as per above suggestion : 

1. Unused typeOfEmail removed
2. import java.util.* removed with specified imports required (Also modified the intelliJ setting on local machine)

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java (hunk 2 above)
Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java]: Refactored code pushed.

**Comment by abhvsn** [comment]
@sharat87 Please review the changes.

**Review by sharat87 — APPROVED** [review]
