### PR TITLE
fix: Enhance sort icon layout in Table

### LINKED ISSUE #6905: [Enhancement] Improve table widget header on toggle
1. The sort icons have very low contrast.
Screenshot 2021-08-26 at 5 30 51 PM

2. The ascending arrow touches the bottom border of the header cell.
Screenshot 2021-08-26 at 5 33 29 PM

3.  On cycling through the sort order by clicking the table header, the icon pushes the header text to the right and after the icon goes away after couple of clicks, the text comes back to the original position. Basically the header texts fidgets back and forth on click; the icon should ideally be on the right side rather than the left.

### PR DESCRIPTION
**Pull request by Cool-Runningz**
## Description

This PR address the shifting layout display issue that would occur when clicking through the sorting options within the Table header. It also addresses the low contrast icon color for better accessibility.

Fixes #6905 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- This has been tested manually by adding a Table widget and sorting within the Table header(s).

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/TableWidget/component/TableUtilities.tsx [hunk 1]
```diff
@@ -536,7 +536,9 @@ export function TableHeaderCell(props: {
             <DescendingIcon height={16} width={16} />
           )}
         </SortIconWrapper>
-      ) : null}
+      ) : (
```
Comment (somangshu) [inline app/client/src/widgets/TableWidget/component/TableUtilities.tsx:539]: Moving the text like this is not the right way to go, We should rather place it on the right end of the cell.

File: app/client/src/widgets/TableWidget/component/TableUtilities.tsx [hunk 2]
```diff
@@ -496,7 +496,7 @@ const DescendingIcon = styled(ControlIcons.SORT_CONTROL as AnyStyledComponent)`
   cursor: pointer;
   && svg {
     path {
-      fill: ${(props) => props.theme.colors.secondary};
+      fill: ${Colors.OXFORD_BLUE};
```
Comment (somangshu) [inline app/client/src/widgets/TableWidget/component/TableUtilities.tsx:499]: Use `LIGHT_GREYISH_BLUE` instead, the same for the above

**Review by somangshu — APPROVED** [review]
Some changes requested in the comments 👇 

Approving to run the workflow

**Comment by Cool-Runningz** [comment]
@somangshu I have addressed the comments and this PR is ready for another review at your earliest convenience. Thanks!

File: app/client/src/widgets/TableWidget/component/TableUtilities.tsx [hunk 3]
```diff
@@ -528,6 +528,12 @@ export function TableHeaderCell(props: {
...
       onClick={handleSortColumn}
     >
+      <DraggableHeaderWrapper
+        className={!props.isHidden ? `draggable-header` : "hidden-header"}
+        horizontalAlignment={column.columnProperties.horizontalAlignment}
+      >
+        {props.columnName}
+      </DraggableHeaderWrapper>
       {props.isAscOrder !== undefined ? (
         <SortIconWrapper>
```
Comment (somangshu) [inline app/client/src/widgets/TableWidget/component/TableUtilities.tsx:538]: I see another challenge stemming from this, The icon alignment is not Appropriate because of this, Check this out, The header is hidden right now, And the header row height is more that before! 
Screenshot 2021-10-06 at 11 42 11 AM

Simply removing this style resolves the challenge, Lets clean the code here, Replace this with a simple `div`

**Review by somangshu — CHANGES_REQUESTED** [review]
One small change, The rest looks good to me.

**Comment by Cool-Runningz** [comment]
@somangshu I have addressed the changes you requested so this is ready for another review whenever you get the chance.

**Comment by Cool-Runningz** [comment]
@somangshu Thank you for that information. I have updated my branch with the latest from the `release` branch so this should be ready for another review/pass through the tests.

**Comment by Cool-Runningz** [comment]
@somangshu I noticed that the build had failed again so I pulled in the latest changes from the `release` branch so hopefully it will actually work this time and can get moved along. Thank you for your help throughout this.

**Comment by Cool-Runningz** [comment]
@somangshu Sorry to keep bugging you about this but do you have any idea as to why the tests keep failing? I didn't think my changes were that destructive but for some reason the tests don't pass 😞

**Comment by somangshu** [comment]
@Cool-Runningz please dont worry about that, Happy to help 🙂 

We are currently facing some issues on the PRs from external contributors, Our team is looking into this. Since your code is already approved, This will be counted in the hacktoberfest, We have created [an app](https://app.appsmith.com/applications/61628980ea18372f051057a6/pages/61628980ea18372f051057aa) for our contributor to submit these entries, Kindly do so, And it will considered by out team.

Meanwhile Ill look into what needs to be done here.

**Comment by somangshu** [comment]
Merging this as its working fine here
