### PR TITLE
fix: adding missing `fetch` api with `status` call

### LINKED ISSUE #28462: [Bug]: /remote/fetch api is not getting called
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`/fetch/remote` API is not getting called along with `/status`.
Expected behaviour is first `/fetch/remote` gets called and then `/status`.

### Steps To Reproduce

1. Open a git connected application
2. Open network inspector
3. Observation - only /status API is called not /fetch/remote

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by brayn003**
## Description
Does `fetch/remote` first and then `/status` on canvas load

#### PR fixes following issue(s)
Fixes #28462 

#### Media

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/sagas/GitSyncSagas.ts [hunk 1]
```diff
@@ -159,7 +165,12 @@ function* commitToGitRepoSaga(
           payload: curApplication,
         });
       }
-      yield put(fetchGitStatusInit());
+      if (isGitStatusLiteEnabled) {
+        yield put(fetchGitRemoteStatusInit());
```
Comment (sneha122) [inline app/client/src/sagas/GitSyncSagas.ts:169]: @brayn003 Since this piece of code is repeated like 3 times, is it possible to extract it in common util function?

Comment (brayn003) [reply app/client/src/sagas/GitSyncSagas.ts:169]: I thought so but it is not an easy feat, because the condition comes from a selector and these are two independent actions here.
The piece of code is used both in sagas and components. It uses 'select', 'put' in sagas and 'useDispatch', 'useSelector' in components. Even if I try to put it in a common function it will look hacky. So, avoiding it as it will be removed later.

**Review by sneha122 — APPROVED** [review]

**Review by sneha122 — APPROVED** [review]
