### PR TITLE
Fixed data validation issue

### LINKED ISSUE #2263: TypeError: Cannot read property 'Label' of null
Sentry Issue: [APPSMITH-EQ](https://sentry.io/organizations/appsmith/issues/2099092327/?referrer=github_integration)

```
TypeError: Cannot read property 'Label' of null
  at transformData (widgets/TableWidget.tsx:224:21)
  at getPageView (widgets/TableWidget.tsx:513:34)
  at getCanvasView (widgets/BaseWidget.tsx:249:26)
  at getWidgetView (widgets/BaseWidget.tsx:216:24)
  at render (widgets/BaseWidget.tsx:163:17)
...
(35 additional frame(s) were not displayed)
```

### LINKED ISSUE #2264: TypeError: Cannot read property 'total' of null
Sentry Issue: [APPSMITH-EP](https://sentry.io/organizations/appsmith/issues/2099091551/?referrer=github_integration)

```
TypeError: Cannot read property 'total' of null
  at None (components/designSystems/appsmith/TableUtilities.tsx:841:9)
  at Array.sort (<anonymous>)
  at sortTableFunction (components/designSystems/appsmith/TableUtilities.tsx:838:20)
  at filterTableData (widgets/TableWidget.tsx:311:25)
  at componentDidUpdate (widgets/TableWidget.tsx:397:38)
...
(35 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Fixed issues due to improper table input data by modifying table data validations.

Fixes #2263  
Fixes #2264 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/designSystems/appsmith/TableUtilities.tsx [hunk 1]
```diff
@@ -838,6 +838,8 @@ export function sortTableFunction(
   return tableData.sort(
     (a: { [key: string]: any }, b: { [key: string]: any }) => {
       if (
+        a !== null &&
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/TableUtilities.tsx:841]: Would we have other values for `a`? For example, can `a` and `b` be undefined? If so, we should use a check for `undefined` and also if `a` and `b` are objects?

File: app/client/src/workers/evaluation.worker.ts [hunk 2]
```diff
@@ -1334,6 +1334,7 @@ const VALIDATORS: Record<ValidationType, Validator> = {
     const isValidTableData = every(parsed, datum => {
       return (
         isObject(datum) &&
```
Comment (riodeuno) [inline app/client/src/workers/evaluation.worker.ts:1336]: Would `isPlainObject` work in this scenario? 
https://lodash.com/docs/4.17.15#isPlainObject

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]
