### PR TITLE
fix: MsSQL count breaks app

### LINKED ISSUE #24556: [Bug]: MSSQL Count query breaks application
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Video : https://vdqm24wed6.vmaker.com/record/EAF4tKnxpg8bC1IE

### Description
- When executing a count query for MSSQL the application breaks.

### Steps To Reproduce

1. Connect to a MSSQL datasource.
2. Create a new SELECT query.
3. Write a query to get the total records count. ( SELECT COUNT(*) FROM <table-name> )
4. Click `Run` to execute the query.
5. App breaks.

## Workaround
Provide a column name using the `as` keyword e.g. `select @@version as version`.

### Public Sample App

_No response_

### Environment

Release

### Issue video log

https://vdqm24wed6.vmaker.com/record/EAF4tKnxpg8bC1IE

### Version

Cloud / Self - Hosted 1.9.22

### PR DESCRIPTION
**Pull request by Irongade**
Whenever a count query is run on an MsSQL Query, the returned data is this `{"": 10}`, which breaks the app because, the Table component cannot render table data cells for empty strings as Headers.

Fixes #24556 

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/pages/Editor/QueryEditor/Table.tsx [hunk 1]
```diff
@@ -210,28 +210,20 @@ function Table(props: TableProps) {
   const tableBodyRef = React.useRef<HTMLElement>();
 
   const data = React.useMemo(() => {
-    const emptyString = "";
     /* Check for length greater than 0 of rows returned from the query for mappings keys */
     if (!!props.data && isArray(props.data) && props.data.length > 0) {
-      const keys = Object.keys(props.data[0]);
-      keys.forEach((key) => {
-        if (key === emptyString) {
```
Comment (AmanAgarwal041) [inline app/client/src/pages/Editor/QueryEditor/Table.tsx:218]: Why was this logic not fulfilling the purpose ?

Comment (Irongade) [reply app/client/src/pages/Editor/QueryEditor/Table.tsx:218]: For two reasons

1. When the props.data object is returned, the object is immutable i.e. if you did an Object.defineProperty on the object, the configurable field is set to false. Hence you cannot do a delete operation on that key. More info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty), which way why the app was breaking.
2. We don't actually need that logic, since we can simply replace the string at the point the columns are being created. It is essentially doing the same thing.

**Review by AmanAgarwal041 — APPROVED** [review]
