### PR TITLE
fix: 6842 added property firstDayOfWeek

### LINKED ISSUE #6842: [Feature] Change first day of the week on the date-picker widget
## Summary

We should be able to change the first day of the week on the date picker widget.

## Motivation

As requested by a user on [discord](https://discord.com/channels/725602949748752515/725609493974614076/879784273882800170).

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Added a new property for First Day of week.  

Fixes #6842 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/firstdayofweek-datepicker-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.04 **(-0.01)** | 36.48 **(-0.01)** | 34.45 **(0)** | 55.57 **(-0.01)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/widgets/DatePickerWidget2/component/index.tsx | 27.78 **(0)** | 2.99 **(-0.09)** | 6.25 **(0)** | 27.14 **(0)**
 :red_circle: | app/client/src/widgets/DatePickerWidget2/widget/index.tsx | 76.67 **(-7.95)** | 0 **(0)** | 66.67 **(-8.33)** | 78.57 **(-8.93)**</details>

### CODE REVIEW

File: app/client/src/widgets/DatePickerWidget2/component/index.tsx [hunk 1]
```diff
@@ -156,6 +156,9 @@ class DatePickerComponent extends React.Component<
             <DateInput
               className={this.props.isLoading ? "bp3-skeleton" : ""}
               closeOnSelection={this.props.closeOnSelection}
+              dayPickerProps={{
```
Comment (SatishGandham) [inline app/client/src/widgets/DatePickerWidget2/component/index.tsx:159]: Are we expecting more props here, why not firstDayOfWeek instead of dayPickerProps?

Comment (vibhandikyash) [reply app/client/src/widgets/DatePickerWidget2/component/index.tsx:159]: No, we are not expecting more props support right now, firstDayOfWeek is not supported directly.
As per blueprint, this is supported into dayPickerProps.

**Review by SatishGandham — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@vibhandikyash Few observations while testing the Deploy Preview
1. No default value for `First Day Of Week` property, it only populates on clicking on the calendar
2. Changing value show the field in red colour but no error is displayed
3. No limit is set for the property
4. Calendar pop up UI breaks on entering the value above 6

https://www.loom.com/share/2861f7625ba24ee7ae8edb85f952bb1b

**Comment by YogeshJayaseelan** [comment]
@vibhandikyash Tested this PR and please find the status below,

Issue 1 - Fixed
Issue 2 - Fixed
Issue 3 - Fixed
Issue 4 - Fixed

New Enhancement

Issue 5 - Enhancement - Instead of values 0-6 we can pass values in String (Sunday, Monday, Tuesday, etc) which will be more helpful

**Comment by techbhavin** [comment]
@YogeshJayaseelan  
For issue 5 => For now we do not support this. we made the change of all functionality. 

@somangshu  plz let us know can we do this?

**Comment by somangshu** [comment]
@techbhavin Ill agree with you, Given that this is set by the developer we can consider that they are aware of the concept, I dont see much of a value add. However, we need to clearly show this in the tooltip helper of the property to denote the index, ex 0 for sunday and so on and so forth.

Regardless of the of the critically, To implement this we could create a mapping of the index and String. (I still feel this is an overdo, even from the user point of view)

**Comment by techbhavin** [comment]
@somangshu  can we add a drop-down instead of Textbox for select First day of week ?

**Comment by somangshu** [comment]
@techbhavin What if somebody wants to use an expression to set this dynamically. I suggest not spending much time to improve this. Rather focus on validation, helper text, test coverage for the fix. 

We can have the dropdown, Given that its not going to take much time to implement, test and resolve more issues. Maybe create another enhancement for the future!
cc @YogeshJayaseelan

**Review by SatishGandham — APPROVED** [review]
