### PR TITLE
fix: Hiding the add new button in new workspace created if user has app viewer access

### LINKED ISSUE #9041: [Bug]: User with 'App viewer' rights can see New button to create applications
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When User A creates a new organization with no applications in it and shares that organization with User B with only "app viewer" permission. User B is displayed with _NEW_ button to create application. Upon clicking that an Error is displayed.
image

**Expected behavior:** User B must not be displayed with "New" button if the user has App Viewer permission

### Steps To Reproduce

1. Login with User A create a new Organization with no applications in it.
2. Share this Organization with User B with _App viewer_ permission only. 
3. Login with User B and verify the organization. 

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

> Hiding the add new button in new workspace created if user has app viewer access

Fixes #9041 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Logged in with User A and created a new workspace with no applications in it.
- Shared this Organization with User B with App viewer permission only.
- Logged in with User B and verify the workspace doesn't show any add new button inside or next to the share button.

image
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by berzerkeer — DISMISSED** [review]

File: app/client/src/pages/Applications/index.tsx [hunk 1]
```diff
@@ -911,34 +911,39 @@ function ApplicationsSection(props: any) {
...
+                          ) {
+                            createNewApplication(
+                              getNextEntityName(
+                                "Untitled application ",
+                                applications.map((el: any) => el.name),
+                              ),
+                              workspace.id,
+                            );
+                          }
+                        }}
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Applications/index.tsx:941]: This should be a function.

File: app/client/src/pages/Applications/index.tsx [hunk 2]
```diff
@@ -911,34 +911,39 @@ function ApplicationsSection(props: any) {
...
-                              "Untitled application ",
-                              applications.map((el: any) => el.name),
-                            ),
-                            workspace.id,
-                          );
+                  {isPermitted(
+                    workspace.userPermissions,
+                    PERMISSION_TYPE.CREATE_APPLICATION,
+                  ) &&
+                    !isMobile && (
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Applications/index.tsx:918]: Extract this condition to a variable.

File: app/client/src/pages/Applications/index.tsx [hunk 3]
```diff
@@ -911,34 +911,39 @@ function ApplicationsSection(props: any) {
                   <NoAppsFoundIcon />
                   <span>There’s nothing inside this workspace</span>
                   {/* below component is duplicate. This is because of cypress test were failing */}
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Applications/index.tsx:913]: Could you share the background for this?

**Review by IAmAnubhavSaini — CHANGES_REQUESTED** [review]

**Review by berzerkeer — APPROVED** [review]

File: app/client/src/pages/Applications/index.tsx [hunk 4]
```diff
@@ -661,6 +661,27 @@ function ApplicationsSection(props: any) {
...
+        const hasCreateNewApplicationPermission =
+          isPermitted(
+            workspace.userPermissions,
+            PERMISSION_TYPE.CREATE_APPLICATION,
+          ) && !isMobile;
+
+        const onClickAddNewButton = (workspaceId: string) => {
+          if (
+            Object.entries(creatingApplicationMap).length === 0 ||
+            (creatingApplicationMap && !creatingApplicationMap[workspaceId])
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Applications/index.tsx:673]: We are showing button only when `hasCreateNewApplicationPermission` is true. Is there any reason for button to be shown but not work?

If not, then you should integrate the if condition in show button logic somehow, right?

**Review by IAmAnubhavSaini — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Applications/index.tsx (hunk 4 above)
Comment (ankitakinger) [reply app/client/src/pages/Applications/index.tsx:673]: I think the if condition should be checked only when the button is clicked. The main aim of this issue was to hide the button if the user doesn't have access for creating new apps. I have just added the condition for that. This permission check condition was added at one place but was missed at the other one, which I have added in this PR.

Comment (IAmAnubhavSaini) [reply app/client/src/pages/Applications/index.tsx:673]: There are `shouldShow` and `shouldAllowCreate` conditions. If you are showing button then you should allow for clicking it too. The click check can be merged with show check. Please elaborate why this is not desirable?

Comment (ankitakinger) [reply app/client/src/pages/Applications/index.tsx:673]: This if condition is basically needed to check if the button is in loading state i.e. if this button is already clicked once then we should not allow another click till the first request is complete.
image

Comment (IAmAnubhavSaini) [reply app/client/src/pages/Applications/index.tsx:673]: All right, then name the condition appropriately.
