### PR TITLE
fix: mongo uri spec flakiness

### LINKED ISSUE #35148: [Task]: Fix flakiness of cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts
### SubTasks

Test flakiness on this PR https://github.com/appsmithorg/appsmith/pull/33856 which has only shell script change

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
There were two things that were making this spec file act flaky:
- The delete query wasn't working as the id was being converted to `ObjectId('id')` but since the id was expected to be int, it was failing. So converting the default delete query generated from crud operation to `{ _id: {{data_table.triggeredRow._id}}}` actually started passing the whole of test.
- Second thing was, since the spec was updating some records and verifying, running it multiple times was causing the failures in the next runs, Hence instead of using the default data table from the ted suite, the data is being dumped to a new collection that is dynamically generated in the spec using the new fixture that is added in the pr. Hence, after this change the spec started passing in every multiple runs.

Fixes #35148
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10891454490>
> Commit: 3aef2d2fec56c6ff0efcc575444c04d805e561a0
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10891454490&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Mon, 16 Sep 2024 21:03:05 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Added a comprehensive dataset for MongoDB-related merchandise, improving product management and display features.

- **Bug Fixes**
	- Updated test case logic to focus on deletion operations and enhance validation processes.
	- Removed redundant assertions for table data verification to improve test clarity.

- **Chores**
	- Streamlined validation of loaded table data for clearer test output, consolidating multiple assertions into a single verification method.

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts [hunk 1]
```diff
@@ -141,14 +148,15 @@ describe(
...
+      assertHelper.AssertNetworkExecutionSuccess("@postExecute");
       assertHelper.AssertNetworkStatus("@postExecute", 200);
-      assertHelper.AssertNetworkStatus("@postExecute", 200);
-      table.ReadTableRowColumnData(0, 6, "v2", 200).then(($cellData) => {
-        expect($cellData).to.eq("Coffee Mug");
-      });
-      table.ReadTableRowColumnData(1, 6, "v2", 200).then(($cellData) => {
-        expect($cellData).to.eq("Track Jacket");
-      });
+      // This is just verifying the table data
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts:153]: Please remove this commented lines if not needed.

File: app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts [hunk 2]
```diff
@@ -22,6 +22,10 @@ describe(
   () => {
     let dsName: any;
 
+    beforeEach(() => {
+      agHelper.CypressReload();
```
Comment (mohanarpit) [inline app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts:26]: @AmanAgarwal041 Why are we refreshing the page before each test run? Is this really required?

Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts:26]: @mohanarpit The issue is solve in one test run, but the issue is when it is run multiple times, somehow the column positions are changing is what I have guessed. I found out that this could be due to some caching issues, for which one of the solution was `CypressReload` which I tried out. 
The issue can be seen from these logs : https://github.com/appsmithorg/appsmith/actions/runs/10874426954/job/30171875222#step:25:1893
In the first run, it actually validates in the 6th column but somehow it gets changed to 7th column. I am still trying to debug why this is happening

**Review by sagar-qa007 — APPROVED** [review]
