### PR TITLE
fix: update UI for members page

### LINKED ISSUE #15697: [Bug]: Issues related to new architecture change in RBAC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [ ] When the Pathvi3@appsmith.com the home page goes for an infinite loading 
- [x] When the user login and clicks on any old app the editor crashes-->**Closed**
- [x] When the user open git connected app the server crashes->**Closed**
```
backend stdout | [2022-08-04 07:14:53,774] userEmail=c1@appsmith.com, sessionId=50a10473-8529-48f3-a5fe-4d53f99a74c8, thread=nioEventLoopGroup-3-2, requestId=7f4d1533-f7ce-4035-af9e-88c2b3410925 -
backend stdout | java.lang.NullPointerException: null
backend stdout | 	at com.appsmith.server.helpers.GitFileUtils.createApplicationReference(GitFileUtils.java:142)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout | 	*__checkpoint ⇢ Handler com.appsmith.server.controllers.GitController#getStatus(String, String) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout | 		at com.appsmith.server.helpers.GitFileUtils.createApplicationReference(GitFileUtils.java:142)
backend stdout | 		at com.appsmith.server.helpers.GitFileUtils.saveApplicationToLocalRepo(GitFileUtils.java:88)
backend stdout | 		at com.appsmith.server.services.ce.GitServiceCEImpl.lambda$getStatus$122(GitServiceCEImpl.java:1551)
```
- [x] The text **Organization** should be changed to **workspace** in the roles dropdown->**Closed**
- [x] The Look and feel of the Members page user Role dropdown should expand to show the complete role name
- [ ] there is now the possibility of searching in members page so when there is no available results show the error message->**need to be fixed** 

### Steps To Reproduce

1. Open the url https://rbac-release.appsmith.com
2. Login with your email id
3. In the home page
4. Click on any app

### Public Sample App

_No response_

### Version

https://rbac-release.appsmith.com/

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

> Updated the UI for members page.

Fixes #15697 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested the UI for desktop and mobile

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/pages/workspace/Members.tsx [hunk 1]
```diff
@@ -49,10 +49,50 @@ const MembersWrapper = styled.div<{
...
+    margin-top: 12px;
+    thead {
+      tr {
+        border-bottom: 1px solid #E8E8E8;
+        th {
+          font-size: 14px;
+          font-weight: 500;
+          line-height: 1.5;
+          color: var(--appsmith-color-black-700);
+          padding: 5px 20px;
```
Comment (albinAppsmith) [inline app/client/src/pages/workspace/Members.tsx:61]: multiples of 4 possible?

**Review by albinAppsmith — APPROVED** [review]
