### PR TITLE
chore: fix wds select widget bugs + refactor

### LINKED ISSUE #38197: Select Widget Bugs
- [ ]  Default selected value doesn’t work
- [ ]  Merge combo box into select with a new property
- [ ]  Default selected value for combo box is missing
- [ ]  Crashes when it’s given bad data
- [ ]  Missing dropdown to do mapping

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #38197 

/ok-to-test tags="@tag.Anvil"

## Summary by CodeRabbit

- **New Features**
  - Enhanced styling for select input components, improving visual consistency.
  - Introduced new validation functions for widget properties, ensuring better data integrity.
  - Added properties for improved configuration of select widgets, including dynamic data binding.
  - New utility functions for handling options in select widgets, enhancing functionality.
  - Introduced a constant for sample data to facilitate testing and development.

- **Bug Fixes**
  - Resolved issues with widget rendering and responsiveness to property changes.

- **Refactor**
  - Streamlined widget implementation by leveraging inherited functionalities and simplifying methods.
  - Updated methods to improve handling of derived properties and options.
  - Removed obsolete configuration files and validation functions to clean up the codebase.

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12480977859>
> Commit: d669e05ed5b7ce07a54259b7e301eb65341c1b02
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12480977859&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Anvil`
> Spec:
> <hr>Tue, 24 Dec 2024 11:43:59 UTC

### CODE REVIEW

File: app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/config/propertyPaneConfig/validations/valueKeyValidation.ts [hunk 1]
```diff
@@ -0,0 +1,122 @@
+import type { LoDashStatic } from "lodash";
+import type { WDSSelectWidgetProps } from "../../../widget/types";
+
+/**
+ * Validation rules:
+ * 1. Can be a string (representing a key in sourceData)
+ * 2. Can be an Array of string, number, boolean (for direct option values)
```
Comment (KelvinOm) [inline app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/config/propertyPaneConfig/validations/valueKeyValidation.ts:7]: I don't quite understand why we need to check that the key can be an array. Could you please clarify this?

File: app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/widget/derived.js [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+    } else if (_.isArray(props.optionValue)) {
+      values = processOptionArray(props.optionValue, sourceData);
+    }
+
+    return sourceData.map((d, i) => ({
+      label: labels[i],
+      value: values[i],
+    }));
+  },
+  //
```
Comment (KelvinOm) [inline app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/widget/derived.js:59]: // — all this comments should be deleted.

File: app/client/src/modules/ui-builder/ui/wds/WDSComboBoxWidget/widget/index.tsx [hunk 3]
```diff
@@ -1,187 +1,68 @@
...
+    const { labelTooltip, placeholderText, selectedOptionValue, ...rest } =
+      this.props;
     const validation = validateInput(this.props);
+    const options = (isArray(this.props.options) ? this.props.options : []) as {
+      value: string;
+      label: string;
+    }[];
+    // This is key is used to force re-render of the widget when the options change.
+    // Why force re-render on   options change?
+    // Sometimes when the user is changing options, the select throws an error ( related to react-aria code ) saying "cannot change id of item".
```
[the remark this answers is not in the document]
Comment (jsartisan) [reply app/client/src/modules/ui-builder/ui/wds/WDSComboBoxWidget/widget/index.tsx:44]: Ok sometimes seems wrong word here but the issue is that id's should not change while re-rendering and when we were changing the values from property panes, ids were changing and react-aria was throwing an error.

File: app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/config/propertyPaneConfig/validations/valueKeyValidation.ts (hunk 1 above)
Comment (jsartisan) [reply app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/config/propertyPaneConfig/validations/valueKeyValidation.ts:7]: I took this logic from the fixed layout component. the value comes as an array if we use evaluations inside the property like `{{item.name}}` and it just takes first value if they are all same. I know it's confusing and I talked to rahul about it that why we even need it. We might not even need it. I'll talk to vadim and carina after holidays about this because this feature of supporting `{{item.name}}` makes no sense to me. Not sure what usecases it solves.

File: app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/widget/derived.js (hunk 2 above)
Comment (jsartisan) [reply app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/widget/derived.js:59]: Yea right, with the new utility ( `parseDerivedProperties`) , we can remove these.

File: app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/config/propertyPaneConfig/validations/valueKeyValidation.ts (hunk 1 above)
Comment (KelvinOm) [reply app/client/src/modules/ui-builder/ui/wds/WDSSelectWidget/config/propertyPaneConfig/validations/valueKeyValidation.ts:7]: At first I thought it was to make dependent fields, but it doesn't work at all the way I expected. Please discuss this.

**Review by KelvinOm — APPROVED** [review]
