### PR TITLE
fix: Display for action response for imported app with SQL datasource

### LINKED ISSUE #6228: [Bug]The query output is displayed as json instead of table on importing a application
## Description: when we import and export any application which contains a datasource and rerun the query in the imported application, the query output is showing as JSON instead of a table 

[What happened]

### Steps to reproduce the behaviour:

1.Export the application which is connected to SQL datasource
2.Now import it in a new org
3.Run the select Query
4.Verify the display under response tab

image

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [chrome]
- Environment [release]

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> This PR fixes the action response display issue for the imported application, when we run the action from SQL datasource instead of tabluar format we used to see the response in JSON format. 

Fixes #6228

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> JUnit TC update
> Manual test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java [hunk 1]
```diff
@@ -723,10 +723,13 @@ private String sanitizeDatasourceInActionDTO(ActionDTO actionDTO, Map<String, St
                 //Mapping ds name in id field
                 ds.setId(datasourceMap.get(ds.getId()));
                 ds.setOrganizationId(null);
-                ds.setPluginId(null);
+                if (ds.getPluginId() != null) {
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:726]: Earlier this data was not present while exporting the application. Now with the pluginId in the nested datasource within ActionDTO FE can detect the correct plugin and display the correct format for select query

**Review by nayan-rafiq — APPROVED** [review]
LGTM
