### PR TITLE
Fix: TypeError: e.widgetName is undefined and TypeError: Cannot read property 'toUpperCase' of undefined

### LINKED ISSUE #3672: TypeError: Cannot read property 'toUpperCase' of undefined
Sentry Issue: [APPSMITH-MG](https://sentry.io/organizations/appsmith/issues/2281274062/?referrer=github_integration)

```
TypeError: Cannot read property 'toUpperCase' of undefined
  at None (components/editorComponents/LightningMenu/helpers.tsx:197:27)
  at Array.sort (<anonymous>)
  at getLightningMenuOptions (components/editorComponents/LightningMenu/helpers.tsx:196:23)
  at lightningMenuOptions (components/editorComponents/LightningMenu/index.tsx:27:19)
  at c (components/editorComponents/LightningMenu/index.tsx:87:13)
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jsartisan**
toUpperCase() on undefined was failing. Using lodash instead of native string functions.

Fixes #3672 #3673 

## Type of change

- Bug fix

## How Has This Been Tested?

- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]

File: app/client/src/components/editorComponents/LightningMenu/helpers.tsx [hunk 1]
```diff
@@ -194,7 +195,9 @@ export const getLightningMenuOptions = (
   ];
   if (widgets.length > 0) {
     widgets = widgets.sort((a: WidgetProps, b: WidgetProps) => {
-      return a.widgetName.toUpperCase() > b.widgetName.toUpperCase() ? 1 : -1;
+      return toUpper(get(a, "widgetName")) > toUpper(get(b, "widgetName"))
```
Comment (mohanarpit) [inline app/client/src/components/editorComponents/LightningMenu/helpers.tsx:198]: Do we know why the `widgetName` was undefined here? Shouldn't the `widgetName` always be present?

Comment (jsartisan) [reply app/client/src/components/editorComponents/LightningMenu/helpers.tsx:198]: I couldn't find the exact root cause of it. Will try again with checking smartlook. I think nidhi, hetu had this sentry issue. Will ask them about this.

**Review by mohanarpit — APPROVED** [review]
