### PR TITLE
fix: introduce new regexp for remote url validation

### LINKED ISSUE #11996: [Bug]: missing frontend validation for remote URL in git connect flow
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you enter `g@` in the remote URL, FE code accepts that as proper ssh url for git repo.

### Steps To Reproduce

1. Create a new app.
2. Click git connect in bottom bar
3. Insert `g@` in the remote URL bar
4. Notice that the greyed out Connect button becomes active and user can click it.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

As of today we accept almost anything in git connect modal for remote URL. The URL should be ssh/git one. This PR fixes it. 

New RE is: `/^((git|ssh)|(git@[\w\.]+))(:(\/\/)?)([\w\.@\:\/\-~]+)(\.git)$/`

Screenshot 2022-03-21 at 12 10 43 PM

Screenshot 2022-03-21 at 12 05 41 PM

Fixes #11996 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually.

## Examples of validation (post-fix):

Screenshot 2022-03-21 at 12 07 39 PM
Screenshot 2022-03-21 at 12 07 25 PM
Screenshot 2022-03-21 at 12 07 02 PM
Screenshot 2022-03-21 at 12 07 16 PM

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: 11996-fix-git-remote-url-validation 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.25 **(0.01)** | 37.69 **(0.02)** | 35.93 **(0.02)** | 56.48 **(0.01)**
 :green_circle: | app/client/src/pages/Editor/gitSync/utils.ts | 100 **(50)** | 100 **(100)** | 100 **(100)** | 100 **(66.67)**</details>

### CODE REVIEW

**Review by ankitakinger — APPROVED** [review]
LGTM

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Connection_spec.js [hunk 1]
```diff
@@ -216,12 +216,7 @@ describe("Git sync modal: connect tab", function() {
       .click({ force: true })
       .type(`{selectAll}${invalidURLDetectedOnTheBackend}`);
     cy.get(gitSyncLocators.connectSubmitBtn).scrollIntoView();
-    cy.get(gitSyncLocators.connectSubmitBtn).click();
-    cy.wait("@connectGitRepo").then((interception) => {
```
Comment (ankitakinger) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Connection_spec.js:220]: why have we removed the test for Submit button click?

Comment (IAmAnubhavSaini) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Connection_spec.js:220]: Because it won't accept wrong input anymore. If you cannot add wrong input anymore, you won't be able to click the submit button to check backend response.

Comment (ankitakinger) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Connection_spec.js:220]: can we then add a check for error message which will be seen below the field?

Comment (IAmAnubhavSaini) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Connection_spec.js:220]: https://github.com/appsmithorg/appsmith/blob/4fa46fd99aca9bbedad7e1510e7d1bfcb15a73c7/app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Connection_spec.js#L52-L54

**Review by ankitakinger — APPROVED** [review]
LGTM
