### PR TITLE
fix: Added support for bracket notation autocomplete

### LINKED ISSUE #21473: [Feature]-[756]:Automatically switch to bracket notation when an autocomplete result contains blank space
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to select an autocomplete result for an object key containing a blank space, automatically switch to bracket notation to avoid unexpected identifier errors on . notation

### Steps To Reproduce

1. Create an API that returns data with keys containing a space (eg: "first name")
2. Try binding this key on the property pane (eg: `{{API.data.first name}}`)
3. Notice binding failure due to Unexpected Identifier error 

Expectation: Automatically convert this to bracket notation to avoid this error. eg: `API.data["first name"]`

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Adds support for bracket notation in autocomplete results
- Change AST parsing in JSObjects to support property access using bracket notation
- Change `flattenDef` logic to add bracket notation when dot notation is invalid. Eg. when the property is separated by space or has an invalid character.
- Added `hint` callback to all the generated hints to convert invalid dot notation autocompletion to a valid bracket notation

#### PR fixes following issue(s)
Fixes #21473 
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts [hunk 1]
```diff
@@ -129,10 +133,10 @@ export const commandsHelper: HintHelper = (editor, data: DataTree) => {
               } catch (e) {
                 log.debug(e, "Error logging slash command");
               }
-            });
-            CodeMirror.on(hints, "select", (selected: CommandsCompletion) => {
-              currentSelection = selected;
-            });
+              CodeMirror.off(hints, "pick", handlePick);
+            }
+            CodeMirror.on(hints, "pick", handleSelection);
```
Comment (Druthi) [inline app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts:138]: should this be `handlePick`?

File: app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts [hunk 2]
```diff
@@ -129,10 +133,10 @@ export const commandsHelper: HintHelper = (editor, data: DataTree) => {
...
+            CodeMirror.on(hints, "select", handlePick);
```
Comment (Druthi) [inline app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts:139]: And this be `handleSelection`?

Comment (arunvjn) [reply app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts]: Done

File: app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts (hunk 1 above)
Comment (arunvjn) [reply app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts]: Done

File: app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts [hunk 3]
```diff
@@ -81,8 +81,6 @@ export const dataTreeTypeDefCreator = (
           extraDefsToDefine,
         );
         jsPropertiesDef[funcName] = funcTypeDef;
-        // To also show funcName.data in autocompletion hint, we explictly add it here
-        jsPropertiesDef[`${funcName}.data`] = funcTypeDef.data;
```
Comment (Rishabh-Rathod) [inline app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts:85]: How would the `funcName.data` work after this change?

Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts:85]: Does the below logic inside `flattenDef` would take care of it? 
```
Object.entries(value).forEach(([subKey, subValue]) => {
      if (subKey.startsWith("!")) return;
      const childKeyIsValid = isValidVariableName(subKey);
      const childCompletion = !childKeyIsValid
        ? `${parentCompletion}["${subKey}"]`
        : `${parentCompletion}.${subKey}`;
      flattenedDef[childCompletion] = subValue;
```

File: app/client/src/workers/Evaluation/JSObject/index.ts [hunk 4]
```diff
@@ -160,8 +160,16 @@ export function saveResolvedFunctionsAndJSUpdates(
...
+              // key as "\"prop1\"" or "\'prop1\'". We need to remove the extra quotes.
+              const isStringRepresentation =
+                parsedElement.key.startsWith("'") ||
+                parsedElement.key.startsWith('"');
+              const parsedKey = isStringRepresentation
+                ? parsedElement.key.slice(1, -1)
+                : parsedElement.key;
               variables.push({
-                name: parsedElement.key,
+                name: parsedKey,
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/Evaluation/JSObject/index.ts:172]: What about the case when key only startsWith `"` and doesns't end with `"`

Comment (arunvjn) [reply app/client/src/workers/Evaluation/JSObject/index.ts:172]: AST parsing would fail in that case since the JS Object would be invalid

File: app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts (hunk 3 above)
Comment (arunvjn) [reply app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts]: Reverted

File: app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts [hunk 5]
```diff
@@ -101,7 +101,11 @@ export const commandsHelper: HintHelper = (editor, data: DataTree) => {
               to: editor.getCursor(),
               selectedHint: 1,
             };
-            CodeMirror.on(hints, "pick", (selected: CommandsCompletion) => {
+            function handleSelection(selected: CommandsCompletion) {
+              currentSelection = selected;
+              CodeMirror.off(hints, "pick", handleSelection);
```
[the remark this answers is not in the document]
Comment (arunvjn) [reply app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts]: Fixed

**Review by Druthi — APPROVED** [review]

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

**Review by Parthvi12 — APPROVED** [review]

**Comment by Parthvi12** [comment]
Cypress test LGTM.

**Comment by shwetha-ramesh** [comment]
@arunvjn Tested this [DP](https://ce-24493.dp.appsmith.com)https://ce-24493.dp.appsmith.com/. Working as expected. Moving to Done
image
