### PR TITLE
fix: add datatype check for date field validity jsonform

### LINKED ISSUE #24675: trim() is not a function when default date is blank. TypeError: t.trim is not a function
Sentry Issue: [APPSMITH-6J9](https://appsmith.sentry.io/issues/4224005846/?referrer=github_integration)

```
TypeError: t.trim is not a function
  at isValid (widgets/JSONFormWidget/fields/DateField.tsx:99:44)
  at DateField (widgets/JSONFormWidget/fields/DateField.tsx:126:24)
  at apply (widgets/JSONFormWidget/component/Field.tsx:64:9)
...
(17 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description
This PR adds a check to the date field's value. Along with the existing checks we also check if the value is of type string.

This change solves the issue mentioned below that occurs whenever the defaultValue for the date field in the property pane is an array of string.

#### PR fixes following issue(s)
Fixes #24675

- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?

- [x] Manual
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/widgets/JSONFormWidget/fields/DateField.tsx [hunk 1]
```diff
@@ -96,7 +96,8 @@ export const isValidType = (value: string) =>
   );
 
 const isValid = (schemaItem: DateFieldProps["schemaItem"], value?: string) =>
```
Comment (ashit-rath) [inline app/client/src/widgets/JSONFormWidget/fields/DateField.tsx:98]: Could you also make `value?: unknown`? since we are expecting something other than the string as well?

**Comment by chandannkumar** [comment]
@keyurparalkar Observation:
- Unable to select any date when binding is done on Default date
 https://www.loom.com/share/df47bd1df14b457ba37dc827a8573ab8?sid=256445e6-d89f-4c54-86e4-b3810df0f207

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested the fix of error
- Tested the fix of app break
