### PR TITLE
fix: Maintain focus on editor when Escape is pressed with autocomplete menu open

### LINKED ISSUE #21999: [Bug]-[2640]:Pressing ESC when an autocomplete is open should only close the autocomplete menu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The JS object pane should support basic keyboard shortcuts that help developers write code faster and more effectively

Pressing ESC when an autocomplete is open should only close the autocomplete menu. Right now, the user loses focus from the entire editor forcing me to use the mouse and regain my cursor position.

### Steps To Reproduce

Open the JS editor and perform any/all of the actions defined above to see behavior.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

1.6.6

### PR DESCRIPTION
**Pull request by rimildeyjsr**
## Description

When typing content in the editor, the autocomplete menu pops up to suggest possible matches. If we press escape, the autocomplete menu closes but the editor loses focus, and users have to click again to regain focus and type.

This PR fixes this issue and removes this defect.

Fixes #21999 

Screen recording - https://www.loom.com/share/697f689f85b7426d88032f6487a9f7d9

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer-reviewed by QA
- [x] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reviewing all Cypress test

### CODE REVIEW

**Review by ApekshaBhosale — APPROVED** [review]

**Comment by rimildeyjsr** [comment]
Note for QA - test in different browsers/platforms/incognito

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/MaintainContext&Focus_spec.js [hunk 1]
```diff
@@ -191,4 +193,13 @@ describe("MaintainContext&Focus", function () {
     agHelper.GetNClick(dataSources._queryResponse("SETTINGS"));
     cy.xpath(queryLocators.queryTimeout).should("be.focused");
   });
+
+  it("11. Maintain focus of code editor when Escape is pressed with autcomplete open", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/MaintainContext&Focus_spec.js:197]: Please add bug id to the `it` title - so someone referring in the future will also know the script exists for the associated bug.

`it("11. Bug 21999 - Maintain focus of code editor when Escape is pressed with autcomplete open", () => {`

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/MaintainContext&Focus_spec.js:197]: Otherwise test looks good.

Comment (rimildeyjsr) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/MaintainContext&Focus_spec.js:197]: fixed

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good!

**Comment by ramsaptami** [comment]
Tested on Chrome (w/ incognito), Canary & Firefox on property pane, editor and query pages - LGTM

**Review by ravikp7 — APPROVED** [review]
