### PR TITLE
fix: rest api response box is unreachable via scroll

### LINKED ISSUE #29534: [Bug]: Bottom of the REST API response is not reachable with scroll
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

coming from [here](https://www.notion.so/appsmith/Issues-in-developing-Raven-and-more-ce55b055ac93494f96ae36cd009d3bfd?pvs=4#09b1364caf8c40ed9c29d41d01a53453)
Say you have a long response to your REST API query, such that it is not completely visible in the current viewport. Scrolling through bottoms out before reaching the actual bottom of the response, and it only possible to reach this place with the "down" strokes on the keyboard.

### Steps To Reproduce

1. create a blank API with URL `https://httpbun.com/any'
2. make sure the height of the response window is short, so that you can't see the entire response
3. try to reach the bottom of the response via scrolling, and see that some part of the response is actually still not shown even when the scroll has reached the bottom.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by vaibhavchobisa**
## Description
Scrollbar of API response is escaping the viewport. This PR fixes the issue.

#### Media
Screenshot 2023-12-24 at 3 20 21 PM

Fixes #29534  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

## Summary by CodeRabbit

- **Style**
	- Improved the visual layout and padding of the `TabPanelWrapper` component for better readability and user interface experience.
	- Updated the layout or styling of the `DebuggerLogs` component to enhance the user interface.

### CODE REVIEW

**Comment by rohan-arthur** [comment]
@vaibhavchobisa looks like the issue is still there. You can sign up with a new user and test here: https://ce-29830.dp.appsmith.com/

https://github.com/appsmithorg/appsmith/assets/94514895/47a0a195-6709-4945-ab1c-5a234792cfc0

**Comment by vaibhavchobisa** [comment]
Hey @rohan-arthur 
This issue is resolved on my end. I think the re-deploy was completed after you tested on the old DP.
Could you please re-test and verify?

**Comment by rohan-arthur** [comment]
tested ok on incognito.
@sneha122 would you please review?

File: app/client/src/components/editorComponents/EntityBottomTabs.tsx [hunk 1]
```diff
@@ -13,6 +13,12 @@ const TabPanelWrapper = styled(TabPanel)`
   &.ads-v2-tabs__panel {
     overflow: auto;
   }
+  & .t--code-editor-wrapper.codeWrapper {
+    overflow-y: scroll;
```
Comment (sneha122) [inline app/client/src/components/editorComponents/EntityBottomTabs.tsx:17]: @vaibhavchobisa Why is this overflow-y necessary? It seems to be adding another scroll bar in the UI, other than the one we already have for code editor

File: app/client/src/components/editorComponents/EntityBottomTabs.tsx [hunk 2]
```diff
@@ -13,6 +13,12 @@ const TabPanelWrapper = styled(TabPanel)`
...
+    & .CodeMirror-scroll {
+      padding-bottom: 0;
```
Comment (sneha122) [inline app/client/src/components/editorComponents/EntityBottomTabs.tsx:19]: The root cause of the issue is that the div with class CodeMirror-scroll does not have its height configured correctly, its height is overflowing over the footer and hence some of the content gets hidden behind the footer, can you please check where this height is coming from and fix the issue from root cause?

Comment (sneha122) [reply app/client/src/components/editorComponents/EntityBottomTabs.tsx:19]: Screenshot 2023-12-26 at 5 14 26 PM

Comment (vaibhavchobisa) [reply app/client/src/components/editorComponents/EntityBottomTabs.tsx]: Thank you for the feedback @sneha122. 
Div with the class "t--code-editor-wrapper codeWrapper" is the one that is causing the overflow beyond the screen. I have provided it with the height of "100% - 40px" which takes both the footer size and the little padding above it into account.
I have also replaced the bottom padding with box-sizing: border-box; so that the bottom padding of 50px stays.

It seems to be working fine now, please re-review and let me know, thanks!

**Comment by vaibhavchobisa** [comment]
Hi @sneha122 
Can you please review the changes in the PR?

File: app/client/src/components/editorComponents/EntityBottomTabs.tsx [hunk 3]
```diff
@@ -5,14 +5,20 @@ import AnalyticsUtil from "utils/AnalyticsUtil";
...
 const TabPanelWrapper = styled(TabPanel)`
   margin-top: 0;
   height: calc(100% - ${LIST_HEADER_HEIGHT});
   &.ads-v2-tabs__panel {
     overflow: auto;
   }
+  & .t--code-editor-wrapper.codeWrapper {
+    height: calc(100% - ${FOOTER_MARGIN});
+    & .CodeMirror-scroll {
+      box-sizing: border-box;
```
Comment (sneha122) [inline app/client/src/components/editorComponents/EntityBottomTabs.tsx:19]: Is the box sizing necessary if we have already fixed the issue by adjusting height?

Comment (sneha122) [reply app/client/src/components/editorComponents/EntityBottomTabs.tsx:19]: @vaibhavchobisa

Comment (vaibhavchobisa) [reply app/client/src/components/editorComponents/EntityBottomTabs.tsx:19]: Yes @sneha122. That's because the div has a bottom padding of 50px, which would make the scroll overflow since its box-sizing property is set to content-box. Therefore I have changed it to border-box.

Comment (vaibhavchobisa) [reply app/client/src/components/editorComponents/EntityBottomTabs.tsx:19]: @sneha122 we can either choose to make it border-box or remove the bottom padding of 50px. I went with the former as some bottom padding would make for a better UI.

Comment (sneha122) [reply app/client/src/components/editorComponents/EntityBottomTabs.tsx:19]: Got it makes sense

**Review by sneha122 — APPROVED** [review]

**Comment by sneha122** [comment]
This PR is active

**Comment by vaibhavchobisa** [comment]
Hey @rohan-arthur @sneha122 
Will this PR merge? Is there any merge blocker that I can help with, would love to help!

**Comment by vaibhavchobisa** [comment]
@sneha122 Done. Thanks!

**Review by hetunandu — APPROVED** [review]
