### PR TITLE
fix: remove unnecessary re-renders on JS Object context menu in explorer

### LINKED ISSUE #14700: [Bug]-[48000]:Wasted renders of JSCollectionEntityContextMenu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JSCollectionEntityContextMenu is rendering 10k to 15k times for every action on Aforce app. I don't see why that needs to run so many times. I believe it to be a problem with the hook `useNewJSCollectionName();`

### Steps To Reproduce

Take a react profile while editing the table data property[Just add a space] on community issues page. You will see it render 15k times.

Or

Just put console.count in `JSCollectionEntityContextMenu` component function

### Public Sample App

_No response_

### Version

Both / Latest

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fixes an inline selector used in jsCollectionContextMenu to remove unnecessary re-renders.

Fixes #14700 

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- Perf fix

## How Has This Been Tested?
- Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/pages/Editor/Explorer/JSActions/JSActionContextMenu.tsx [hunk 1]
```diff
@@ -34,8 +34,8 @@ type EntityContextMenuProps = {
 export function JSCollectionEntityContextMenu(props: EntityContextMenuProps) {
   const nextEntityName = useNewJSCollectionName();
```
Comment (SatishGandham) [inline app/client/src/pages/Editor/Explorer/JSActions/JSActionContextMenu.tsx:35]: We should not be using a selector to get the data if it not used for display purposes.
Let the function that needs it access the store directly and get the new name.

If you think it is out of scope for this issue, please create an issue.

You can check similar change done by @aswathkk  here
https://github.com/appsmithorg/appsmith/pull/14581/files#diff-d5c64b5bfe5aad11ddfb4fa2dbb869f688d6f60d38c605218e0a678d87de09c9L10

**Review by SatishGandham — CHANGES_REQUESTED** [review]

**Comment by SatishGandham** [comment]
This PR saves about 600-800ms on table row click on Aforce app in edit mode. Screenshots and profiles available [here](https://theappsmith.slack.com/archives/C024GUDM0LT/p1656584195605779)

**Review by SatishGandham — DISMISSED** [review]
LGTM

**Review by SatishGandham — APPROVED** [review]
