### PR TITLE
fix: App crashes when a modal has a filepicker?

### LINKED ISSUE #10283: [Bug] App crashes when a modal has a filepicker?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
Reported by A-Cityzen#3550 on discord.

The user added a filepicker - which calls a multipart POST api - into a modal. The modal crashes the application on `showModal`
Logs from the crash:

Screenshot 2022-01-10 at 5 41 49 PM
.

### Steps To Reproduce

Not clear at the moment. We can attempt to do the following

- Create a multipart POST API
- Create a modal
- Add a file picker into the modal, and configure it to call the multipart POST API.
- We can further try selecting a video/PDF/Excel to try and recreate this issue.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #10283

## Type of change

- Bug fix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/http-issue-with-filepicker 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.07 **(0)** | 36.59 **(0)** | 34.54 **(0)** | 55.56 **(-0.01)**
 :red_circle: | app/client/src/widgets/CameraWidget/component/index.tsx | 10.53 **(-0.03)** | 14.72 **(0)** | 0 **(0)** | 12.41 **(-0.04)**
 :red_circle: | app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx | 32.41 **(-0.92)** | 0 **(0)** | 20.69 **(0)** | 33.33 **(-1.01)**</details>

### CODE REVIEW

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 1]
```diff
@@ -323,14 +323,17 @@ class FilePickerWidget extends BaseWidget<
       .use(Url, { companionUrl: "https://companion.uppy.io" })
       .use(OneDrive, {
         companionUrl: "https://companion.uppy.io/",
-      })
-      .use(Webcam, {
+      });
+
+    if (location.protocol === "https:") {
```
Comment (somangshu) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:328]: @jsartisan would this change not load the url with `http`, how will the user identify this?

**Review by somangshu — APPROVED** [review]
Change LGTM

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 2]
```diff
@@ -451,7 +454,9 @@ class FilePickerWidget extends BaseWidget<
   componentDidMount() {
     super.componentDidMount();
 
-    this.initializeUppyEventListeners();
+    try {
+      this.initializeUppyEventListeners();
+    } catch (e) {}
```
Comment (sharat87) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:459]: Can we log the error here just in case?

File: app/client/src/widgets/CameraWidget/component/index.tsx [hunk 3]
```diff
@@ -891,12 +891,14 @@ function CameraComponent(props: CameraComponentProps) {
...
-        setError(err.message);
-      });
+    try {
+      navigator.mediaDevices
+        .enumerateDevices()
+        .then(handleDeviceInputs)
+        .catch((err) => {
+          setError(err.message);
+        });
+    } catch (e) {}
```
Comment (sharat87) [inline app/client/src/widgets/CameraWidget/component/index.tsx:901]: Can we log the error here as well?

**Review by sharat87 — CHANGES_REQUESTED** [review]

**Review by sharat87 — APPROVED** [review]
