### PR TITLE
fix: {{appsmith.user.email}} is not available on page load

### LINKED ISSUE #20275: [Bug]: {{appsmith.user.email}} is not available on page load
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The appsmith.user.email value is not populated in queries that run on page load

### Steps To Reproduce

1. create a query
2. bind it to appsmith.user.email
3. mark it to run on page load
4. check the network console and see that it's value is not passed to the query

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Druthi**
## Description
Fix for a bug where {{appsmith.user.email}} is not available on page load.

Fixes #20275 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- [ ] Google sheet - get the data by {{appsmith.user.email}} in table, verify the On page load for the table
- [ ] Mongo - Retrieve data with customer_email : {{appsmith.user.email}}  Verify the on page load
- [ ] PostgreSQL - Retrieve data with email : {{appsmith.user.email}}  Verify the on page load
`SELECT * FROM public."users" where email = '{{appsmith.user.email}}';`
- [x] Verify JSobject function for stored and User values >> On page load

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/entities/Engine/AppEditorEngine.ts [hunk 1]
```diff
@@ -132,6 +135,7 @@ export default class AppEditorEngine extends AppEngine {
         `Unable to fetch actions for the application: ${applicationId}`,
       );
 
+    yield call(waitForFetchUserSuccess);
```
Comment (eco-monk) [inline app/client/src/entities/Engine/AppEditorEngine.ts:138]: Will need the same in AppViewerEngine.

**Review by eco-monk — COMMENTED** [review]
We will need the same change in AppViewerEngine.

**Comment by eco-monk** [comment]
Adding @sbalaji1192 since he recently worked on analytics as well.

**Review by sbalaji1192 — APPROVED** [review]
checked out the usage pulse related code. looks good!

File: app/client/src/entities/Engine/AppEditorEngine.ts (hunk 1 above)
Comment (arunvjn) [inline app/client/src/entities/Engine/AppEditorEngine.ts:138]: You will have to add this line in app/client/src/entities/Engine/AppViewerEngine.ts as well

**Review by arunvjn — DISMISSED** [review]

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug20275_Spec.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+      toRun: false,
+      shouldCreateNewJSObj: true,
+      prettify: false,
+    });
+
+    jsEditor.EnableDisableAsyncFuncSettings("myFun1", true, false);
+
+    deployMode.DeployApp();
+
+    agHelper.ValidateToastMessage(Cypress.env("USERNAME"));
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug20275_Spec.js:27]: Can we add a another validation for normal text displaying `{{appsmith.user.email}}` also please?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug20275_Spec.js [hunk 3]
```diff
@@ -0,0 +1,41 @@
+import { ObjectsRegistry } from "../../../../support/Objects/Registry";
+import { WIDGET } from "../../../../locators/WidgetLocators";
+
+const jsEditor = ObjectsRegistry.JSEditor,
+  agHelper = ObjectsRegistry.AggregateHelper,
+  deployMode = ObjectsRegistry.DeployMode,
+  locator = ObjectsRegistry.CommonLocators,
+  ee = ObjectsRegistry.EntityExplorer,
+  propPane = ObjectsRegistry.PropertyPane;
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug20275_Spec.js:9]: Nit: Use import from ObjectsCore instead of Registry so spec level objects are not needed to be declared.

`import * as _ from "../../../../support/Objects/ObjectsCore";
`Usage: `_.jsEditor.CreateJSObject(JS_OBJECT_BODY, {`
`_.ee.DragDropWidgetNVerify(WIDGET.TEXT, 200, 600);
`

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good!

**Review by arunvjn — APPROVED** [review]
