### PR TITLE
fix: File picker disabled state

### LINKED ISSUE #5761: [Bug] [Release-Frozen] Able to upload file after disabling the File Picker widget
### Steps to reproduce the behaviour:

1. Drag and drop File picker widget
2. Toggle the disable property
3. Observe that upload is functional after disabling also

https://www.loom.com/share/8678428d78e94da1ba82a50b8dc46507

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: Release frozen

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Fix File picker disabled state

Fixes #5761 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/FilePicker-working-after-being-disabled 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.91 **(-0.01)** | 33.48 **(-0.02)** | 30.05 **(-0.01)** | 52.58 **(-0.01)**
 :red_circle: | app/client/src/components/designSystems/appsmith/FilePickerComponent.tsx | 52.38 **(-2.62)** | 0 **(0)** | 20 **(0)** | 50 **(-2.63)**
 :red_circle: | app/client/src/utils/helpers.tsx | 53.46 **(-1.89)** | 26.03 **(-4.11)** | 22.22 **(-3.71)** | 47.2 **(-1.6)**</details>

### CODE REVIEW

File: app/client/src/components/designSystems/blueprint/ButtonComponent.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ const AccentColorMap: Record<ButtonStyleName, string> = {
 };
 
 const ButtonWrapper = styled((props: ButtonStyleProps & IButtonProps) => (
-  <Button {..._.omit(props, ["accent", "filled", "disabled"])} />
```
Comment (somangshu) [inline app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:54]: We are changing the core component here, What are the implications of this. 

@riodeuno does this look fine to you? Please let us know.

Comment (Tooluloope) [reply app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:54]: It was actually changed here, 
https://github.com/appsmithorg/appsmith/pull/4744/files#diff-ca7efadeb621ea38f3dd4c5a353d05be64e7079ea342b5b37c581dd27bb660ee

This change was what introduced the file picker bug.

Although, I've opened an issue for fixing all disabled widgets on Mozilla 
https://github.com/appsmithorg/appsmith/issues/5944

Comment (somangshu) [reply app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:54]: Thanks for triaging this, We need to understand a better solution here. 

@marks0351 this changed was made to resolve button widget drag on Firefox in the disabled state. Need your inputs here. 

@vivekverma2312 can we test these situation here across browsers.

Comment (riodeuno) [reply app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:54]: @somangshu @Tooluloope This change seems to effect the props which are passed to the core HTML button. We omit them to avoid getting errors in the browsers console regarding this. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

Removing this, will allow `disabled` to be passed to the button element, which will be handled by the browser. It is possible, that this is what is needed to fix the issue. @marks0351 please weigh in on @somangshu 's comment.

Comment (marks0351) [reply app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:54]: @Tooluloope @somangshu @riodeuno 
I agree that we need to omit disabled coz of the Firefox issue.
we can simply move the logic to disable click based events by ignoring them when click happens onto the parent like how Button widget is doing.
or
We stop click events from propagating outside of button components when its disabled.
also when I tried doing this there was event ordering issue. since the parent widget clicks are registered first those click handlers will fire first, so we need a custom onClick property for the button component(onButtonClick) which only fires when it is not disabled and stops click propagation when it is disabled.

File: app/client/src/components/designSystems/appsmith/FilePickerComponent.tsx [hunk 2]
```diff
@@ -17,6 +17,9 @@ class FilePickerComponent extends React.Component<
   }
 
   openModal = () => {
+    if (this.props.isDisabled) {
+      return;
+    }
     this.props.uppy.getPlugin("Dashboard").openModal();
```
Comment (marks0351) [inline app/client/src/components/designSystems/appsmith/FilePickerComponent.tsx:23]:
```suggestion
    if (!this.props.isDisabled) {
     this.props.uppy.getPlugin("Dashboard").openModal();
    }
    
```
not much of a comment. this just looks cleaner to me.

**Review by marks0351 — APPROVED** [review]

File: app/client/src/components/designSystems/appsmith/FilePickerComponent.tsx (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/components/designSystems/appsmith/FilePickerComponent.tsx]: Thanks @marks0351

**Review by marks0351 — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified the fix and now by disabling the file picker user will not be able to upload files. working as expected
