### PR TITLE
fix: fix MySQL SSH tunnel default port value

### LINKED ISSUE #27604: [Bug]: MySQL ssh tunnel datasource config fails if port value is not provided
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- MySQL SSH tunnel datasource config is supposed to assume a default value for SSH port when not provided explicitly. Currently it fails with null pointer exception. 

### Steps To Reproduce

1. Create MySQL SSH tunnel datasource config and leave SSH port value empty.
2. Click on `Test` button.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

cloud, self hosted

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- If the user provides no value for port number field in the datasource config form, then the API server should assume default value. This PR fixes this functionality.

#### PR fixes following issue(s)
Fixes #27604 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit
>
>

### How to test
- Please check out the video provided in the description [here](https://github.com/appsmithorg/appsmith/pull/26632). Use the same config for datasource as shown in the video, but leave the port number fields empty. Please reach out to @sumitsum for key file. 

#### Test Plan
https://github.com/appsmithorg/TestSmith/issues/2527
>
>
#### Issues raised during DP testing
https://github.com/appsmithorg/appsmith/pull/27612#issuecomment-1736788753
>
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [x] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java [hunk 1]
```diff
@@ -118,6 +119,16 @@ public static boolean isSSHEnabled(
...
     }
 
+    public static int getSSHPortFromConfigOrDefault(DatasourceConfiguration datasourceConfiguration) {
+        return toIntExact(defaultIfNull(datasourceConfiguration.getSshProxy().getPort(), DEFAULT_SSH_PORT));
+    }
+
+    public static int getDBPortFromConfigOrDefault(
+            DatasourceConfiguration datasourceConfiguration, Long defaultDBPort) {
+        return toIntExact(
+                defaultIfNull(datasourceConfiguration.getEndpoints().get(0).getPort(), defaultDBPort));
```
Comment (sneha122) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java:129]: @sumitsum When we save a datasource with blank hostname and port, the datasourceConfiguration.endpoints is [], in that case of we do get(0) on empty array will it throw any error? or would it default to defaultDBPort? or should we handle this case as well?

File: app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/SSHUtilsTest.java [hunk 2]
```diff
@@ -91,8 +97,24 @@ public void testGetConnectionContext_whenSSHIsDisabled() {
         properties.add(new Property("Connection method", "Standard"));
         datasourceConfiguration.setProperties(properties);
 
-        ConnectionContext connectionContext = getConnectionContext(datasourceConfiguration, 1, Object.class);
+        ConnectionContext connectionContext = getConnectionContext(datasourceConfiguration, 1, null, Object.class);
         assertTrue(connectionContext.getConnection() == null, connectionContext.toString());
```
Comment (sneha122) [inline app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/SSHUtilsTest.java:101]: Will this test not fail? because defaultPort passed is null and the datasourceConfig also does not have port specified, so it will throw the DS_MISSING_PORT_ERROR_MSG  exception right?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java (hunk 1 above)
Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java:129]: Hi @sneha122 this use case is already handled as part of `validateDatasource` method i.e. the execution will not reach this point if the validation has failed beforehand.

File: app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/SSHUtilsTest.java (hunk 2 above)
Comment (sumitsum) [reply app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/SSHUtilsTest.java:101]: Hi @sneha122 this test case tests for the case when SSH is disabled, in which case it will not do anything and just return from the function.

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/SSHUtilsTest.java:101]:
```
 /* Return empty ConnectionContext if SSH tunnel is not enabled */
        if (!isSSHEnabled(datasourceConfiguration, connectionMethodPropertiesIndex)) {
            return new ConnectionContext<C>(null, null);
        }
```

**Review by sneha122 — APPROVED** [review]

**Comment by btsgh** [comment]
@sumitsum 

1. On choosing SSH tunnel, I enter all the required details for SSH and SQL db. Test and Save config. Create queries.
2. Now get to Edit DS screen, and choose Standard, instead of SSH tunnel, and test and save config. Create queries, work with these 
3. Come back to Edit DS screen, click on SSH Tunnel. Note that all the old values we had entered for this setting are retained, including the host address and the pem key file. 

Should these values be retained? They should be discarded and user should be made to reenter, as the config was saved earlier by choosing Standard.

**Comment by sumitsum** [comment]
> @sumitsum
> 
> 1. On choosing SSH tunnel, I enter all the required details for SSH and SQL db. Test and Save config. Create queries.
> 2. Now get to Edit DS screen, and choose Standard, instead of SSH tunnel, and test and save config. Create queries, work with these
> 3. Come back to Edit DS screen, click on SSH Tunnel. Note that all the old values we had entered for this setting are retained, including the host address and the pem key file.
> 
> Should these values be retained? They should be discarded and user should be made to reenter, as the config was saved earlier by choosing Standard.
> 
>  Screen.Recording.2023-09-27.at.12.02.53.PM.mov

Hi @btsgh, the issue that you have mentioned is by design. It is a deeper issue related to how the config forms work at the moment and will require a separate discussion.

**Comment by btsgh** [comment]
Rest of the areas look fine. Good to go! @sumitsum

**Comment by btsgh** [comment]
Rest of the areas look fine. Good to go! @sumitsum
