### PR TITLE
fix: Table reverts column positions on sorting if columns returned differ

### LINKED ISSUE #13979: [Bug]-[4869]:Table (v1) reverts column positions on sorting if columns returned differ
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/169489128-6413dfea-6fdf-4b70-bcf0-00901f8656f7.mov

### Steps To Reproduce

1. Connect Table to a datasource which does not return values for some columns (eg used: Mongo TED)
2. Drag drop columns from within table properties to reorder the columns
3. Deploy & Observe: Dragged column remains in its position
4. Now try to sort it
5. **Observe : The repositioned columns reverts to its old position**
6. **Expected: New positions of the table columns should remain after any action taken by user**

### Public Sample App

_No response_

### Version

Prod/Release v1.6.26

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

- Table V2 will now maintain the original order of the columns even if some of the columns returned change
- The new columns will show up at the end

Fixes #13979 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_Column_Order_spec.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+const dsl = require("../../../../../fixtures/tableV2ColumnOrderDsl.json");
+const widgetsPage = require("../../../../../locators/Widgets.json");
+
+describe("Table Widget V2 column order maintained on column change validation", function() {
+  before(() => {
+    cy.addDsl(dsl);
+  });
+
+  it("Table widget V2 column order should be same and new column should be at the end", function() {
+    cy.get(commonlocators.switchWidgetActive).click({ force: true });
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_Column_Order_spec.js:11]: Please rearrange column and turn off the switch to check the expected columnOrder

Comment (sbalaji1192) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_Column_Order_spec.js:18]: Please add one more assertion

**Review by sbalaji1192 — APPROVED** [review]
