### PR TITLE
Fix authentication issue while creating mockdata

### LINKED ISSUE #5924: [Bug] When the same mock DB is added twice it shows an error.
## Description

[What happened]
 Currently trying to add the mock twice throws an error. 

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to datasource page
2. Try adding the same mock data twice

### Important Details

- Version: [Cloud 
- OS: [Windows]
- Browser [Chrome]
- Environment [production]
image

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> When creating mockdata set twice, authentication was failing due to double encryption on password. 
Fixes #5924

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sharat87** [comment]
@AnaghHegde, can we add a test so this doesn't regress and magically show up later? A test that creates two mock datasources and ensure that the password in these datasources is correct should do. What say?

**Comment by AnaghHegde** [comment]
Ready for review :)

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java [hunk 1]
```diff
@@ -174,10 +174,16 @@ private DatasourceConfiguration getPostgresDataSourceConfiguration(String name,
...
+        String password = null;
+        if( datasource.getDatasourceConfiguration().getAuthentication() instanceof DBAuth) {
+            password = ((DBAuth) datasource.getDatasourceConfiguration().getAuthentication()).getPassword();
+        }
+        final String finalPassword = password;
         return datasourceService.create(datasource)
                 .onErrorResume(DuplicateKeyException.class, error -> {
                     if (error.getMessage() != null
                             && error.getMessage().contains("organization_datasource_deleted_compound_index")) {
+                        ((DBAuth) datasource.getDatasourceConfiguration().getAuthentication()).setPassword(finalPassword);
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java:186]: Can we do the `instanceof` check here as well? Just like on line 178?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java [hunk 2]
```diff
@@ -174,10 +174,17 @@ private DatasourceConfiguration getPostgresDataSourceConfiguration(String name,
...
+        }
+        final String finalPassword = password;
         return datasourceService.create(datasource)
                 .onErrorResume(DuplicateKeyException.class, error -> {
                     if (error.getMessage() != null
-                            && error.getMessage().contains("organization_datasource_deleted_compound_index")) {
+                            && error.getMessage().contains("organization_datasource_deleted_compound_index")
+                            && datasource.getDatasourceConfiguration().getAuthentication() instanceof DBAuth) {
+                        ((DBAuth) datasource.getDatasourceConfiguration().getAuthentication()).setPassword(finalPassword);
                         return createSuffixedDatasource(datasource, name, 1 + suffix);
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java:188]: If I understand correctly, if the auth for the datasource is _not_ `DBAuth`, then we don't create a suffixed datasource at all? Do we not want to create a suffixed datasource even if the auth isn't a `DBAuth`? Something like:

```suggestion
                            && error.getMessage().contains("organization_datasource_deleted_compound_index") {
                        if (datasource.getDatasourceConfiguration().getAuthentication() instanceof DBAuth) {
                            ((DBAuth) datasource.getDatasourceConfiguration().getAuthentication()).setPassword(finalPassword);
                        }
                        return createSuffixedDatasource(datasource, name, 1 + suffix);
```

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java:188]: No, we dont want create a datasource if the type is not `dbAuth`. Since the mock datasource is of db type. The current implementation supports only the DB type datasource creation.

Comment (sharat87) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java:188]: I see. So, if we need mock datasources that are not of DB type, we'll need code changes then. Alright, approving.

**Review by sharat87 — APPROVED** [review]
Looks good to be merged. Please squash merge once the CI is finished. Thanks!
