### PR TITLE
fix: invite user and password reset email not being sent via config page setup

### LINKED ISSUE #13976: [Bug]: Unable to send Forget Password and Invite mail even after configuaration of email service
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

#4368 Is similar to My issue but in that they may have not config the Email service but i had config it correctly but not able to send the Invite mail and Forget password mail. It says it is sent but i did not receive any in inbox

### Steps To Reproduce

1. Create an application 
2. Config the email service
3. Signout and try to send the forget password mail

### Public Sample App

_No response_

### Version

Hosted on Cloud AWS

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

> Invite user and password reset emails not being sent via config page setup

Fixes #13976 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested if the values being passed to the API while toggling is correct.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IAmAnubhavSaini** [comment]
@ankitakinger how does this affect https://github.com/appsmithorg/appsmith/pull/11703 

I am trying to understand why it was introduced and now being removed. Could you provide some description on how this change helps with "Invite user and password reset emails not being sent via config page setup".

**Comment by ankitakinger** [comment]
> @ankitakinger how does this affect #11703
> 
> I am trying to understand why it was introduced and now being removed. Could you provide some description on how this change helps with "Invite user and password reset emails not being sent via config page setup".

This introduced a bug elsewhere. So this is a better fix right now to tackle both scenarios - the earlier one and the current one.

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx [hunk 1]
```diff
@@ -64,7 +71,11 @@ export function ToggleComponent({ setting }: SettingComponentProps) {
     <StyledFieldToggleGroup>
       <FormGroup setting={setting}>
         <Field
-          component={FieldToggleWithToggleText(setting.toggleText, setting.id)}
+          component={FieldToggleWithToggleText(
+            setting.toggleText,
+            setting.id,
+            setting.name?.toLowerCase().includes("enable") ? false : true,
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/FormGroup/Toggle.tsx:77]: `setting.name?.toLowerCase().includes("enable")` is a boolean value. Could use `!setting.name?.toLowerCase().includes("enable")`.

File: app/client/src/pages/Settings/SettingsForm.tsx [hunk 2]
```diff
@@ -132,14 +132,20 @@ export function SettingsForm(
...
       if (setting && setting.controlType == SettingTypes.TOGGLE) {
-        props.settingsConfig[settingName] =
-          props.settingsConfig[settingName].toString() == "true";
+        if (settingName.toLowerCase().includes("enable")) {
+          props.settingsConfig[settingName] =
+            props.settingsConfig[settingName].toString() == "" ||
+            props.settingsConfig[settingName].toString() == "true";
+        } else {
+          props.settingsConfig[settingName] =
+            props.settingsConfig[settingName].toString() == "true";
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/SettingsForm.tsx:141]: `props.settingsConfig[settingName].toString()` can be put in a variable as it is being evaluated multiple times. Above too.

Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/SettingsForm.tsx:141]: Can we use `===` instead of `==`?

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx [hunk 3]
```diff
@@ -30,8 +31,10 @@ function FieldToggleWithToggleText(
     },
   ) {
     function onToggle(value?: boolean) {
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/FormGroup/Toggle.tsx:33]: Is there any place where `value` is not boolean? In ads/Toggle, we have `value: boolean`.

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx [hunk 4]
```diff
@@ -30,8 +31,10 @@ function FieldToggleWithToggleText(
...
-      componentProps.input.onChange && componentProps.input.onChange(!value);
-      componentProps.input.onBlur && componentProps.input.onBlur(!value);
+      componentProps.input.onChange &&
+        componentProps.input.onChange(isDisableProperty ? !value : value);
+      componentProps.input.onBlur &&
+        componentProps.input.onBlur(isDisableProperty ? !value : value);
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/FormGroup/Toggle.tsx:37]: `isDisableProperty ? !value : value` can be assigned to a variable.

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx [hunk 5]
```diff
@@ -22,6 +22,7 @@ const ToggleStatus = styled.span`
 function FieldToggleWithToggleText(
   toggleText?: (value: boolean) => string,
   id?: string,
+  isDisableProperty?: boolean,
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/FormGroup/Toggle.tsx:25]: This should be renamed. `isPropertyDisabled` or `isDisabledProperty` or `shouldDisableProperty`.

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx [hunk 6]
```diff
@@ -41,12 +44,16 @@ function FieldToggleWithToggleText(
...
+              ? !componentProps.input.value
+              : componentProps.input.value
+          }
         />
         <ToggleStatus>
           {typeof toggleText == "function"
-            ? createMessage(() => toggleText(!componentProps.input.value))
-            : !componentProps.input.value
+            ? createMessage(() => toggleText(componentProps.input.value))
+            : componentProps.input.value
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/FormGroup/Toggle.tsx:56]: `componentProps.input.value` can be put in to a variable. Above too.

File: app/client/src/pages/Settings/config/email.ts [hunk 7]
```diff
@@ -101,7 +101,7 @@ export const config: AdminConfigType = {
       controlSubType: SettingSubtype.PASSWORD,
       label: "SMTP Password",
       isVisible: (values: Record<string, any>) => {
-        return values && !values["APPSMITH_MAIL_SMTP_TLS_ENABLED"];
+        return values && values["APPSMITH_MAIL_SMTP_TLS_ENABLED"];
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/config/email.ts:104]: Can `values` be falsy?

File: app/client/src/pages/Settings/SettingsForm.tsx [hunk 8]
```diff
@@ -132,14 +132,20 @@ export function SettingsForm(
...
+        }
       }
     });
     props.initialize(props.settingsConfig);
   };
 
-  useEffect(onClear, []);
+  useEffect(onClear, [subCategory]);
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/SettingsForm.tsx:148]: Are we sure that we want to fire onClear every time `subCategory` is updated?

**Review by IAmAnubhavSaini — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Settings/SettingsForm.tsx (hunk 8 above)
Comment (ankitakinger) [reply app/client/src/pages/Settings/SettingsForm.tsx:148]: yes

File: app/client/src/pages/Settings/config/email.ts (hunk 7 above)
Comment (ankitakinger) [reply app/client/src/pages/Settings/config/email.ts:104]: Have handled it in SettingsForm.tsx

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx (hunk 5 above)
Comment (ankitakinger) [reply app/client/src/pages/Settings/FormGroup/Toggle.tsx]: done

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx (hunk 3 above)
Comment (ankitakinger) [reply app/client/src/pages/Settings/FormGroup/Toggle.tsx:35]: I'm not sure on this. Will have to check separately.

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx (hunk 4 above)
Comment (ankitakinger) [reply app/client/src/pages/Settings/FormGroup/Toggle.tsx]: done

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx (hunk 6 above)
Comment (ankitakinger) [reply app/client/src/pages/Settings/FormGroup/Toggle.tsx]: done

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx (hunk 1 above)
Comment (ankitakinger) [reply app/client/src/pages/Settings/FormGroup/Toggle.tsx]: done

File: app/client/src/pages/Settings/SettingsForm.tsx (hunk 2 above)
Comment (ankitakinger) [reply app/client/src/pages/Settings/SettingsForm.tsx]: done

Comment (ankitakinger) [reply app/client/src/pages/Settings/SettingsForm.tsx]: done

**Review by IAmAnubhavSaini — APPROVED** [review]

**Comment by stevenleeg** [comment]
Was there ever a resolution to this one? I'm also experiencing the same issue on a fresh install of appsmith.
