### PR TITLE
fix: Modify Form Control Inputs for various Datasource Actions

### LINKED ISSUE #15365: [Bug]: Width of code mirror components in mongo forms is too small
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Thread for reference](https://theappsmith.slack.com/archives/CPG2ZTXEY/p1658155798267189)

### Steps To Reproduce

1. Create a new mongo form
2. Select Insert command and see the width of the documents field.
3. Compare this with the input available for Raw command.

### Public Sample App

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by Irongade**
Different form inputs across various datasources have very small text areas, This presents an uncomfortable User experience for users of appsmith. This PR makes those form inputs bigger.

The documentation of the form control inputs that needed this change can be found in this [Notion Doc](https://appsmith.notion.site/The-problem-with-Form-Input-Widths-ba295cd8205b4809b7e8e97d75f3cc07)

Fixes #15365 

- Bug fix (non-breaking change which fixes an issue)

Visual Tests needed.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by nidhi-nair — APPROVED** [review]

**Review by mohanarpit — APPROVED** [review]

**Review by nidhi-nair — APPROVED** [review]

**Comment by Aishwarya-U-R** [comment]
Cypress looks fine! @prapullac - please proceed.

File: app/client/src/sagas/QueryPaneSagas.ts [hunk 1]
```diff
@@ -213,12 +213,13 @@ function* handleQueryCreatedSaga(actionPayload: ReduxAction<QueryAction>) {
...
-    !!actionConfiguration.formData?.body ||
-    isEmpty(queryTemplate)
-  );
+  // Do not show template view if the query has body(code) or if there are no templates or if the plugin is MongoDB
+  const showTemplate =
+    !(
+      !!actionConfiguration.body ||
+      !!actionConfiguration.formData?.body ||
+      isEmpty(queryTemplate)
+    ) && !(actionPayload.payload?.pluginName === PluginName.MONGO);
```
Comment (nidhi-nair) [inline app/client/src/sagas/QueryPaneSagas.ts:222]: @Irongade Why are we adding this condition for Mongo plugin?

Comment (Irongade) [reply app/client/src/sagas/QueryPaneSagas.ts:222]: > @Irongade Why are we adding this condition for Mongo plugin?

this is because Mongo is the only plugin that was utilizing the showTemplate parameter without actually using it.

Comment (mohanarpit) [reply app/client/src/sagas/QueryPaneSagas.ts:222]: @Irongade Is there a cleaner solution here that doesn't involve us having a special if-else condition like this in code?

Comment (Irongade) [reply app/client/src/sagas/QueryPaneSagas.ts:222]: Yes, I will fix this via a separate PR, this PR got auto squash-merged before I could correct it here.
