### PR TITLE
fix: CURL empty command error msg fix

### LINKED ISSUE #12008: [Bug]-[250]:cURL command - On empty box the user is displayed with inappropriate error message
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Import is clicked on an empty box of cURL inappropriate error message is displayed to the user stating  "Enter a valid  parameter cURLcode "

Expectation : 
Since the user has not added any cURL code we can let the user know by stating error as "Please add the cURL code"

### Steps To Reproduce

1) Navigate to cURL  
2) click on import option 
and observe the error message 

Note : Ensure the cURL code is empty 

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by PiyushPushkar02**
## Description

- Changed the error message returned in case of empty input from the user for CURL import

Fixes #12008 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by PiyushPushkar02** [comment]
> Hi @PiyushPushkar02 , can you please add a JUnit TC for this in `CurImporterServiceTests.java` if possible ?

Done @sumitsum

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java [hunk 1]
```diff
@@ -81,7 +81,7 @@ public Mono<ActionDTO> importAction(Object input, String pageId, String name, St
 
         try {
             if (input == null) {
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java:83]: Hi Piyush, can you please update this if condition to `StringUtils.isBlank(input)` - this will check for two input being null and input being empty string as well. Also, when using the function please use it like `isBlank(...)` instead of `StringUtils.isBlank(...)` (by using appropriate import statement).

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java [hunk 2]
```diff
@@ -180,6 +180,28 @@ public void testImportAction_EmptyLex() {
                 .verify();
     }
 
+    @Test
+    @WithUserDetails(value = "api_user")
+    public void testImportAction_NullLex() {
```
Comment (sumitsum) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java:185]: Can you please update the test case name to be more verbose and direct e.g. something along the lines of  `testImportActionErrorOnNullInput`. Also, can you please add another test case to test empty string input. ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java (hunk 1 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java:83]: Here the input is not a string Object. Its an object of the Java Parent Object class.

Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java:83]: Hi @PiyushPushkar02 , APMU, in the very next line the input object is being cast as a string : `action = curlToAction((String) input, name);` - i.e. the object is actually intended to be a string object. Could we do this type cast early and check for empty string as well ?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java [hunk 3]
```diff
@@ -176,7 +176,29 @@ public void testImportAction_EmptyLex() {
         StepVerifier
                 .create(action)
                 .expectErrorMatches(throwable -> throwable instanceof AppsmithException &&
-                        throwable.getMessage().equals(AppsmithError.INVALID_CURL_COMMAND.getMessage()))
+                        throwable.getMessage().equals(AppsmithError.EMPTY_CURL_INPUT_STATEMENT.getMessage()))
```
Comment (sumitsum) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java:179]: Hi Piyush, it seems like this test is named as `emptyLex` but the input string passed is not actually empty - it contains a single quote - so I am not sure if it is indeed testing for empty string case - can you please check this ? If required, please add a new test case for empty input string case.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java [hunk 4]
```diff
@@ -80,8 +80,8 @@ public Mono<ActionDTO> importAction(Object input, String pageId, String name, St
         ActionDTO action;
 
         try {
-            if (input == null) {
-                throw new AppsmithException(AppsmithError.INVALID_PARAMETER, FieldName.CURL_CODE);
+            if (StringUtils.isBlank((String) input)) {
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java:83]: Hi Piyush, as mentioned earlier, if possible, can you please write it as `isBlank(...)` and add import statement like `import ...StringUtils.isBlank`

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java (hunk 3 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java:179]: As suggested @sumitsum I have checked the mentioned method. It seems to be checking for invalid input rather than empty input. I have added a test case for empty input and also changed the name for above mentioned to to InvalidInput.

**Review by sumitsum — APPROVED** [review]
