### PR TITLE
chore: fix form widgets bugs

### LINKED ISSUE #38200: New line characters do not work in Paragraph widget

### LINKED ISSUE #38201: Large text in read only mode never ends and full age scrolls in Inputs

### LINKED ISSUE #38409: Fix the disable state of input like components

### LINKED ISSUE #38410: Fix the multi-line description of the widgets.

### PR DESCRIPTION
**Pull request by jsartisan**
/ok-to-test tags="@tag.Anvil"

Fixes #38200
Fixes #38201
Fixes #38409
Fixes #38410

## Summary by CodeRabbit

Based on the comprehensive summary, here are the updated release notes:

- **New Features**
    - Enhanced calendar functionality with month and year dropdown selection.
    - Improved input and select component styling.
    - Added text wrapping and line clamping for field labels.

- **Bug Fixes**
    - Refined input validation and error handling across multiple widgets.
    - Updated text property handling for various input widgets.

- **Documentation**
    - Updated autocomplete configuration for input widgets.

- **Chores**
    - Temporarily disabled several Cypress test suites for Anvil widgets.
    - Standardized text property naming across input-related components.

- **Style**
    - Improved CSS styling for input groups, dropdowns, and calendar components.
    - Enhanced text rendering and whitespace handling.

These release notes capture the key changes across the design system and widget components, focusing on user-facing improvements and internal refinements.

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12650457693>
> Commit: c41781c32b9fd186b718338556af9a53221eaca7
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12650457693&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Anvil`
> Spec:
> <hr>Tue, 07 Jan 2025 11:41:09 UTC

### CODE REVIEW

**Comment by jsartisan** [comment]
/ci-test-limit-count run_count=1 update_snapshot=true specs_to_run=cypress/e2e/Regression/ClientSide/Anvil/Widgets/*

**Comment by jsartisan** [comment]
/ci-test-limit-count run_count=1 update_snapshot=true specs_to_run=cypress/e2e/Regression/ClientSide/Anvil/Widgets/*

File: app/client/packages/design-system/widgets/src/components/Calendar/src/CalendarMonthDropdown.tsx [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+    if (state.minValue && date.compare(state.minValue) < 0) {
+      continue;
+    }
+
+    if (state.maxValue && date.compare(state.maxValue) > 0) {
+      continue;
+    }
+
+    months.push(formatter.format(date.toDate(state.timeZone)));
+  }
```
Comment (znamenskii-ilia) [inline app/client/packages/design-system/widgets/src/components/Calendar/src/CalendarMonthDropdown.tsx:33]: What do you think about extracting this code into a function?

File: app/client/packages/design-system/widgets/src/components/Calendar/src/CalendarYearDropdown.tsx [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+  });
+
+  for (let i = -20; i <= 20; i++) {
+    const date = state.focusedDate.add({ years: i });
+
+    years.push({
+      value: date,
+      formatted: formatter.format(date.toDate(state.timeZone)),
+    });
+  }
```
Comment (znamenskii-ilia) [inline app/client/packages/design-system/widgets/src/components/Calendar/src/CalendarYearDropdown.tsx:22]: What do you think about extracting this code into a function?

File: app/client/packages/design-system/widgets/src/components/Calendar/src/CalendarYearDropdown.tsx [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+export function CalendarYearDropdown({ state }: { state: CalendarState }) {
+  const years: { value: CalendarState["focusedDate"]; formatted: string }[] =
+    [];
+  const formatter = useDateFormatter({
+    year: "numeric",
+    timeZone: state.timeZone,
+  });
+
+  for (let i = -20; i <= 20; i++) {
```
Comment (znamenskii-ilia) [inline app/client/packages/design-system/widgets/src/components/Calendar/src/CalendarYearDropdown.tsx:15]: What is 20? Could you extract into a constant?

**Review by znamenskii-ilia — APPROVED** [review]
