### PR TITLE
Remove unsafe functions from eval

### LINKED ISSUE #1816: [Bug] Adding JS snippet without a defined API leads to infinite errors
### Steps to reproduce the behaviour:
1. Drag a table
2. drag a button
3. paste the code snippet in the button
```
{{function() { 
    let x = 0;
    for(var i = 0;i < Table1.tableData.length; i++) { 
    x += 100;
    setTimeout(() => {
            Stripe_customer.run(() => {

                    if(!!Stripe_customer.data.data[0]) {
                        storeValue(Stripe_customer.data.data[0].customer, {count: Stripe_customer.data.data.length, total: Stripe_customer.data.data.reduce((total, obj) => obj.amount+total, 0)} );
                    }
                },
                undefined, 
                Table1.tableData[i]
            );
    }, x);
    } 
}()
}}
```
4. See the errors in the console

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Certain functions defer execution to later that happen after our eval context. This is not safe and should not be allowed to reference

Fixes #1816

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/utils/DynamicBindingUtils.ts [hunk 1]
```diff
@@ -232,3 +232,5 @@ export const isPathADynamicProperty = (
   }
   return false;
 };
+
+export const unsafeFunctionForEval = ["setTimeout", "fetch"];
```
Comment (hetunandu) [inline app/client/src/utils/DynamicBindingUtils.ts:236]:
```suggestion
export const unsafeFunctionForEval = ["setTimeout", "fetch", "setInterval", "Promise"];
```

**Comment by ofpiyush** [comment]
Not exhaustive

Network:
https://developer.mozilla.org/en-US/docs/Web/API/Websocket
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API

File: app/client/src/utils/DynamicBindingUtils.ts (hunk 1 above)
Comment (rishabhsaxena) [inline app/client/src/utils/DynamicBindingUtils.ts:236]:
```suggestion
export const unsafeFunctionForEval = ["setTimeout", "fetch", "requestAnimationFrame", "setImmediate"];
```
could add these too

**Comment by ofpiyush** [comment]
On second thoughts, why did we not go down the whitelist path?

**Comment by hetunandu** [comment]
We have a limited set of functionality anyways. Easier to just blacklist I guess
https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope

File: app/client/src/utils/DynamicBindingUtils.ts (hunk 1 above)
Comment (hetunandu) [reply app/client/src/utils/DynamicBindingUtils.ts]: Both are not available inside a worker today
https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope

**Review by riodeuno — APPROVED** [review]
