### PR TITLE
Fix-Selected file deletion not working in File Picker widget

### LINKED ISSUE #3836: [Bug] Filepicker widget: does not clear selected files
## Description
After removing the file from the uploaded list, it still remains internally at the original index so multiple calls using `filepicker.files[0].data` uploads the same file even though we remove a file and add a new file in the widget.

### Steps to reproduce the behaviour:

1. Select a file in filepicker
2. Create an S3 create query which uploads the first file selected using `FilePicker1.files[0].data`
3. Click on the filepicker to execute the create query
4. Remove the file from the filepicker's list and add another file
5. FilePicker shows 2 files selected, when it should only have one <--- Bug 1
6. Click on the filepicker to execute the create query
7. The query succeeds but uploads the same file which was deleted earlier. <--- Bug 2

### Important Details
 Release 1.4.6

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Selected file deletion not working in File Picker widget

Fixes #3836 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress test to check deletion selected file in file picker works as expected

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/FilepickerWidget.tsx [hunk 1]
```diff
@@ -326,14 +326,13 @@ class FilePickerWidget extends BaseWidget<
             return file.id !== dslFile.id;
           })
         : [];
-      this.props.updateWidgetMetaProperty("files", updatedFiles);
+      this.props.updateWidgetMetaProperty("selectedFiles", updatedFiles);
```
Comment (riodeuno) [inline app/client/src/widgets/FilepickerWidget.tsx:329]: Please verify if `Filepicker1.files` binding work after this update?
https://docs.appsmith.com/widget-reference/filepicker#properties

Comment (vicky-primathon) [reply app/client/src/widgets/FilepickerWidget.tsx:329]: @riodeuno  Filepicker1.files binding is working after this update as files property is derived from selectedFiles property

**Review by riodeuno — APPROVED** [review]

**Review by marks0351 — APPROVED** [review]
