### PR TITLE
fix: move canvas starter datasource prompt from entity explorer to sidebar button

### LINKED ISSUE #29484: Bug: incorrect placement of `Bring your data` popup
When I import a building block, we show user a `Bring your data popup`. 
With new IA desgin changes, now the data has a new home in left side nav. We should update position of the popup to match that. 

[Notion card](https://www.notion.so/appsmith/Bring-in-data-modal-pops-up-in-the-wrong-place-after-the-new-sidebar-update-ecfe985e89944caeb618ea1a19398342?pvs=4)

### PR DESCRIPTION
**Pull request by jacquesikot**
## Description
In this fix, we've moved the canvas starter datasource prompt into the newly introduced left side bar for data. This enhancement not only ensures a more intuitive user experience but also establishes a clear and cohesive relationship with the data button, streamlining the workflow for a more efficient and user-friendly interface.

Notion  - https://www.notion.so/appsmith/Bring-in-data-modal-pops-up-in-the-wrong-place-after-the-new-sidebar-update-ecfe985e89944caeb618ea1a19398342?pvs=4

#### PR fixes following issue(s)
Fixes #29484 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
- 
## Testing

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Style**
  - Improved the visual layout of popover components for better user interface alignment.

- **Refactor**
  - Streamlined the user interface by removing the `DatasourceStarterLayoutPrompt` from the `EntityExplorer` component.
  - Enhanced the `SidebarButton` component to conditionally render the `DatasourceStarterLayoutPrompt` based on context, ensuring a more dynamic and responsive user experience.

### CODE REVIEW

File: app/client/src/pages/Editor/IDE/Sidebar/SidebarButton.tsx [hunk 1]
```diff
@@ -39,9 +40,14 @@ const IconContainer = styled.div<{ selected: boolean }>`
   }
 `;
 
+const DATASOURCE_BUTTON_TITLE = "Data";
```
Comment (rahulbarwal) [inline app/client/src/pages/Editor/IDE/Sidebar/SidebarButton.tsx:43]: How did we come up with this? 
If possible move this to some constant fie please.

**Review by rahulbarwal — CHANGES_REQUESTED** [review]
Functionality wise looks good. Please address previous comment.

**Review by rahulbarwal — APPROVED** [review]

File: app/client/src/pages/Editor/IDE/Sidebar/SidebarButton.tsx (hunk 1 above)
Comment (rahulbarwal) [reply app/client/src/pages/Editor/IDE/Sidebar/SidebarButton.tsx:43]: @jacquesikot 

Actually there is a constant already defined here: https://github.com/appsmithorg/appsmith/blob/32838e56c133414a6eff90f6b438bd04b40677c8/app/client/src/entities/IDE/constants.ts#L23

Please check it out.

**Review by rahulbarwal — CHANGES_REQUESTED** [review]

File: app/client/src/entities/IDE/constants.ts [hunk 2]
```diff
@@ -5,6 +5,16 @@ export enum EditorState {
   LIBRARIES = "LIBRARIES",
 }
 
+export enum SidebarTopButtonTitles {
```
Comment (rahulbarwal) [inline app/client/src/entities/IDE/constants.ts:8]:
```suggestion
export const SidebarTopButtonTitles = {
```

Lets keep both top and bottom export types same, and I think const is a more readable choice.

**Review by rahulbarwal — APPROVED** [review]
Looks good thanks.
