### PR TITLE
fix: Set comment authors email address as reply to field in comment notification email

### LINKED ISSUE #11016: [Bug]: The from email id is displayed wrong in the commenting emails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The wrong email id is displayed when user 1 tag user 2 and add a comment in the comment section
image

### Steps To Reproduce

1. Go to commenting feature
2. Tag Raksha@appsmith.com and add a new comment
3. Now when the user Raksha receives a email the receiver email is displayed as "hello@appsmith.com" instead of user email id

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description

When someone adds a comment to a thread, we send a email notification to the subscribers of that thread. The email has resply-to set to appsmith email address. If someone replies to that email, it's sent to an appsmith email address. This PR sets comment author's email address in the reply-to field so that replying to that email will be sent to the authors inbox.
Fixes #11016

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Unit tests
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java [hunk 1]
```diff
@@ -37,11 +38,11 @@ public EmailSender(JavaMailSender javaMailSender, EmailConfig emailConfig) {
         REPLY_TO = makeReplyTo();
     }
 
-    public Mono<Boolean> sendMail(String to, String subject, String text) {
-        return sendMail(to, subject, text, null);
+    public Mono<Boolean> sendMail(String to, String subject, String text, Map<String, ? extends Object> params) {
+        return sendMail(to, subject, text, params, null);
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java:42]: Looks like this signature is not used anywhere. Can we remove it, if it's unused code?

**Review by sharat87 — COMMENTED** [review]
Minor refactor, otherwise looks good to be merged.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java (hunk 1 above)
Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java:42]: No, the method with no replyTo is used in a lot of places. The one with replyTo is used in only the comment notification emails.

Comment (sharat87) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java:42]: Oh but the signature of this method is changing in this PR right? So then all those usages also should be updated otherwise we'll have a compilation error no?

Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java:42]: Understood. Let me explain the changes here: 
Earlier we had these two methods: 
1. `public Mono<Boolean> sendMail(String to, String subject, String text)` 
2. `public Mono<Boolean> sendMail(String to, String subject, String text, Map<String, ? extends Object> params)` 

The first method was used no where. It also called the second method with last param as null. I've removed the first method and added another one like the following:
3. `public Mono<Boolean> sendMail(String to, String subject, String text, Map<String, ? extends Object> params, String replyTo)` 

The second method now calls the new one with last param as null. The actual change is not reflected by the diff.

**Review by sharat87 — APPROVED** [review]
