### PR TITLE
fix: updated the max connection pool size and datasourceDestroy method

### LINKED ISSUE #34028: [Bug]: [aforce] Memory leak issue in Appsmith's database integration causing website downtime.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[slack link](https://theappsmith.slack.com/archives/C0341RERY4R/p1716955225250479)

### Steps To Reproduce

no clear reproduction steps

### Public Sample App

_No response_

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

_No response_

### Version

Self hosted

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description
- This PR updates the max connection pool size for MySQL datasource from 5 to 20 as from the logs we found out that the maximum connections are always getting used. 
- This PR also updates the datasourceDestroy method for MySQL plugin to ensure the graceful shutdown of thread takes places and ensures the connection is closed as opposed to immediate termination of the thread earlier which does not ensure closure of existing connection.

SCR-20241001-lbq-2

Fixes #34028  

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11129233985>
> Commit: 04617ce742961952b863cedaff60060bd46c02b0
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11129233985&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Tue, 01 Oct 2024 16:44:48 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Increased the maximum connection pool size for MySQL from 5 to 20, allowing for more concurrent database connections.
  
- **Bug Fixes**
	- Improved the termination process of the SSH tunnel thread for better handling during datasource destruction.

### CODE REVIEW

File: app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java [hunk 1]
```diff
@@ -692,12 +692,11 @@ public void datasourceDestroy(ConnectionContext<ConnectionPool> connectionContex
                                  */
                                 sshTunnelContext.getServerSocket().close();
                                 sshTunnelContext.getSshClient().disconnect();
-                                sshTunnelContext.getThread().stop();
+                                sshTunnelContext.getThread().interrupt(); // Gracefully interrupt the thread
```
Comment (sneha122) [inline app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java:695]: @NilanshBansal Will this have any impact on query execution or so?

File: app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/utils/MySqlDatasourceUtils.java [hunk 2]
```diff
@@ -38,7 +38,7 @@
 
 public class MySqlDatasourceUtils {
 
-    public static int MAX_CONNECTION_POOL_SIZE = 5;
+    public static int MAX_CONNECTION_POOL_SIZE = 20;
```
Comment (sneha122) [inline app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/utils/MySqlDatasourceUtils.java:41]: I feel even after increasing the max connection pool size to 20, it may occupy all connections, can we please check by executing page load query to see how many connections are created in DB?

**Comment by sneha122** [comment]
@NilanshBansal Are there any test cases that I need to test on DP?

**Comment by NilanshBansal** [comment]
@sneha122 @manish535 please check the performance of the same application when imported in appsmith production VS the DP (containing these changes). It is very evident that the above change fixes the problem at hand and improves the performance of the application thereby ensuring early release of memory.
App Json imported: https://drive.google.com/file/d/16dy2_9I9T11wb3ZIUBgxvaxSn0V8yapT/view?usp=sharing
Maria DB Creds can be found in Servers & Credentials notion doc.
Appsmith Prod App: https://app.appsmith.com/app/memory-leak-a-force-issue/page2-66fbf8e2762fac387e09b19b
DP App: https://ce-36631.dp.appsmith.com/app/memory-leak-a-force-issue/page2-66fbf1f4370ad96d89adeddb

https://github.com/user-attachments/assets/b4edfb71-c4b3-4024-920a-238ef33dc29a

File: app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/utils/MySqlDatasourceUtils.java (hunk 2 above)
Comment (NilanshBansal) [reply app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/utils/MySqlDatasourceUtils.java:41]: @sneha122 20 is fairly small size of connection pool. It can go upto 150 connections usually.
The recommended value for small-sized applications with less traffic usually 10-20 is preferred, for medium 20-50.
I have also tested this out on DP [here](https://github.com/appsmithorg/appsmith/pull/36631#issuecomment-2385922669). There is a huge difference in the performance that we can observe.

**Comment by sondermanish** [comment]
The PR looks good to go! waiting for the Cypress to pass

**Comment by NilanshBansal** [comment]
The failing test is unrelated to the changes in this PR, it is also failing in an empty commit PR. Ref: https://github.com/appsmithorg/appsmith/pull/36637
image

Hence updating the Tag to let the cypress pass
