### PR TITLE
Prevent Entire Editor Header from re rendering

### LINKED ISSUE #5115: [Perf] EditorHeader rerenders on codeEditor keyPress
## Description
EditorHeader re-renders on every codeEditor keyPress

### Steps to reproduce the behaviour:

- Start the react profiler
- Open Any PropertyPane
- Change any propertyControl

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

Separated Save Indicator to a different file to prevent entire Editor Header rerender.

Fixes #5115

## Type of change

performance change

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: editorheader-rerendering 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.74 **(0)** | 33.44 **(-0.02)** | 29.37 **(0)** | 52.4 **(0)**
 :green_circle: | app/client/src/constants/messages.ts | 69.22 **(0.13)** | 100 **(0)** | 7.02 **(0.38)** | 76.28 **(0.08)**
 :red_circle: | app/client/src/pages/Editor/EditorHeader.tsx | 89.9 **(0.07)** | 55.81 **(-1.05)** | 72 **(-3)** | 89.47 **(0.18)**
 :sparkles: :new: | **app/client/src/pages/Editor/EditorSaveIndicator.tsx** | **85.19** | **50** | **66.67** | **84**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/EditorSaveIndicator.tsx [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+  const lastUpdatedTime = useSelector(
+    (state: AppState) => state.ui.editor.lastUpdatedTime,
+  );
+  const isSaving = useSelector(getIsPageSaving);
+  const pageSaveError = useSelector(getPageSavingError);
+
+  const findLastUpdatedTimeMessage = () => {
+    setLastUpdatedTimeMessage(
+      lastUpdatedTime
+        ? `Saved ${moment(lastUpdatedTime * 1000).fromNow()}`
```
Comment (mohanarpit) [inline app/client/src/pages/Editor/EditorSaveIndicator.tsx:36]: Nit: When refactoring, if you notice any raw strings, please move them to `messages.ts`. Will ensure that we have a single place from where we can edit all the text and also help in future i18n.

Comment (rahulramesha) [reply app/client/src/pages/Editor/EditorSaveIndicator.tsx:36]: Didn't know we were doing that, will refactor.

**Review by hetunandu — APPROVED** [review]
Good one

**Review by SatishGandham — APPROVED** [review]
