### PR TITLE
fix: publishing an app removes page permissions 

### LINKED ISSUE #18819: [Bug]: Deploy the app come back to edit mode try to add a widget the No access error is displayed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Deploy the app come back to edit mode try to add a widget the No access error is displayed https://www.loom.com/share/b6be1cc5e738448b90f20daf29bd347d

### Steps To Reproduce

1. create a crud app
2. now go to admin setting
3. give crud access
4. And give execute access from datasource tab
5. now assign this to user 1
6. Login as user 1
7. go to edit mode of the app
8. deploy the app
9. come back to edit mode and add a new widget 
10. The no access toast is displayed

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

localhost

### PR DESCRIPTION
**Pull request by berzerkeer**
## Description

Publish an application replaces the page data in redux store with the newly fetched data which won't have permissions. So replace only the key which are present in the data.

Fixes #18819 

Media
[Loom video](https://www.loom.com/share/40df104425a140f9ab386a94a15293fd)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### CODE REVIEW

File: app/client/src/sagas/ApplicationSagas.tsx [hunk 1]
```diff
@@ -227,6 +228,13 @@ export function* fetchAppAndPagesSaga(
     );
     const isValidResponse: boolean = yield call(validateResponse, response);
     if (isValidResponse) {
+      const prevPagesState: Page[] = yield select(
+        (state: AppState) => state.entities.pageList.pages,
```
Comment (ankitakinger) [inline app/client/src/sagas/ApplicationSagas.tsx:232]: I think we have a selector for this `getPageList`. Any reason we are not using that?

Comment (berzerkeer) [reply app/client/src/sagas/ApplicationSagas.tsx:232]: I think the `.tsx` file extension might've confused you, it would confuse me as well for sure. This is a sagas file though, so we can't use it inside sagas, `useSelector` is a hook, that can be only used inside a react function/component.

Comment (ankitakinger) [reply app/client/src/sagas/ApplicationSagas.tsx:232]: We have used selectors in sagas as well. Refer `SuperUserSagas` file for the same.

Comment (berzerkeer) [reply app/client/src/sagas/ApplicationSagas.tsx:232]: Ahh so the code reuse, not the `useSelector` hook. got it, i will change.

**Review by ankitakinger — APPROVED** [review]
