### PR TITLE
fix: Enable atomic pushes in git using an environment configuration

### LINKED ISSUE #33054: [Bug] Make git push atomicity configurable at instance level
Bitbucket data center requires atomicity during git push but this is not compatible with Azure. We need users to be able to set this up themselves. This flag should be off by default.

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description
Since on-prem Bitbucket needs atomic git pushes to be used for operations from Appsmith, this PR introduces the property as a tenant level configuration that is turned off by default. Users can turn this on to allow git operations to succeed on Bitbucket again.

Fixes #33054

## Automation

/ok-to-test tags="@tag.Git"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9072140454>
> Commit: e1d4325ad751f6b6152c8289d1eb68ed29a5d768
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9072140454&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

### CODE REVIEW

File: app/client/src/ce/pages/AdminSettings/config/general.tsx [hunk 1]
```diff
@@ -115,10 +115,17 @@ export const APPSMITH_USER_SESSION_TIMEOUT_SETTING: Setting = {
   subText:
     "* Default duration is 30 days. To change, enter the new duration in DD:HH:MM format",
   helpText:
-    "Users' session will automatically end if there's no activity for the specified duration, requiring them to log in again for security. The duration can be set between 1 minute and 30 days.",
-  isFeatureEnabled: false,
-  isEnterprise: true,
-  isDisabled: () => true,
```
Comment (ankitakinger) [inline app/client/src/ce/pages/AdminSettings/config/general.tsx:121]: why have we removed these properties here?

File: app/client/src/ce/pages/AdminSettings/config/general.tsx [hunk 2]
```diff
@@ -115,10 +115,17 @@ export const APPSMITH_USER_SESSION_TIMEOUT_SETTING: Setting = {
...
+
+export const APPSMITH_IS_ATOMIC_PUSH_ALLOWED: Setting = {
+  id: "isAtomicPushAllowed",
+  name: "isAtomicPushAllowed",
+  category: SettingCategories.GENERAL,
+  controlType: SettingTypes.CHECKBOX,
+  label: "Allow atomic pushes",
+  text:
+    "Git operations on this tenant should attempt to perform pushes atomically"
 };
```
Comment (ankitakinger) [inline app/client/src/ce/pages/AdminSettings/config/general.tsx:129]: Is this setting a BE/EE feature?

File: app/client/src/ce/pages/AdminSettings/config/general.tsx (hunk 1 above)
Comment (nidhi-nair) [reply app/client/src/ce/pages/AdminSettings/config/general.tsx:121]: Mb, I was trying to understand how they work. :) Thanks for the catch

File: app/client/src/ce/pages/AdminSettings/config/general.tsx (hunk 2 above)
Comment (nidhi-nair) [reply app/client/src/ce/pages/AdminSettings/config/general.tsx:129]: It's applicable to CE as well

File: app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration055AddIsAtomicPushAllowedEnvVarToTenantConfiguration.java [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+    @Execution
+    public void executeMigration() throws IOException {
+        Query tenantQuery = new Query();
+        tenantQuery.addCriteria(where(Tenant.Fields.slug).is("default"));
+        Tenant defaultTenant = mongoTemplate.findOne(tenantQuery, Tenant.class);
+
+        boolean isAtomicPushAllowed = false;
+
+        TenantConfiguration defaultTenantConfiguration = new TenantConfiguration();
+        assert defaultTenant != null : "Default tenant not found";
```
Comment (sondermanish) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration055AddIsAtomicPushAllowedEnvVarToTenantConfiguration.java:38]: suggestion by rabbit makes sense!

Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration055AddIsAtomicPushAllowedEnvVarToTenantConfiguration.java]: Yes it does :)

**Review by ankitakinger — APPROVED** [review]
FE changes look good to me
