### PR TITLE
fix: calculate fluid tokens based on provider width

### LINKED ISSUE #29177: Сalculate fluid tokens based on provider width

### PR DESCRIPTION
**Pull request by KelvinOm**
## Description

- I added `--provider-width` CSS variable to the provider, which we get with the help of [ResizeObserver hook](https://github.com/jaredLunde/react-hook/tree/master/packages/resize-observer), the variable is calculated through [debounces](https://github.com/jaredLunde/react-hook/tree/master/packages/debounce) every 100 ms.
- Styles for typography are now calculated only through CSS
- Split useFluidTokens hook into several, now there are separate hook for sizing, spacing and typography
- Create a separate folder for hooks in the theme package

#### PR fixes following issue(s)
Fixes #29177 

#### Media
https://github.com/appsmithorg/appsmith/assets/11555074/7778c5a0-9ed9-4f9c-a2b6-787784ed3e1f

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

## Summary by CodeRabbit

- **New Features**
  - Introduced fluid sizing, spacing, and typography hooks for responsive design adjustments.
  - Added global font stack utility for consistent typography across platforms.
  - Enhanced theming capabilities with new hooks and utilities.

- **Improvements**
  - Updated `ThemeProvider` to support new styling hooks and responsive design features.
  - Refined typography utilities for dynamic class name generation based on design tokens.

- **Documentation**
  - Added comments to clarify the use of `className` and `style` properties in `ThemeProviderProps`.

- **Refactor**
  - Streamlined token access with updated `TokensAccessor` class.
  - Consolidated typography and font metric types for better type safety and clarity.

- **Bug Fixes**
  - Fixed modal handling in `ComplexForm` component with improved state management and accessibility.

- **Breaking Changes**
  - Removed exports of deprecated typography module and fluid token module.
  - Changed public interface for theming hooks, which may affect existing consumers.

### CODE REVIEW

File: app/client/packages/design-system/theming/src/hooks/src/useCssTokens.tsx [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+  useEffect(() => {
+    setProviderClassName(css`
+      ${cssRule(restTokens)};
+    `);
+  }, [restTokens]);
+
+  useEffect(() => {
+    if (width != null) {
+      setWidthClassName(css`
+        --provider-width: ${width}px;
```
Comment (KelvinOm) [inline app/client/packages/design-system/theming/src/hooks/src/useCssTokens.tsx:83]: @jsartisan If you are interested, then here you can change the values to `vw` or `cqw` and test the performance from your side. This is the only variable that changed on the fly now.

File: app/client/packages/design-system/theming/src/hooks/src/useFluidTypography.tsx [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+    },
+    minVw,
+    maxVw,
+  );
+
+  const styles = scales.reduce(
+    (metrics: TypographyVariantMetric[], currentValue) => {
+      const { maxSize, minSize, r, v } = currentValue;
+      const minTypographyStyle = createStyleObject({
+        fontSize: minSize,
```
Comment (KelvinOm) [inline app/client/packages/design-system/theming/src/hooks/src/useFluidTypography.tsx:53]: @ichik  Before, we used `capHeight` and calculated everything differently, I hope it's okay to use fontSize for calculation. Also, because of this, I had to change defaultTokens.

Comment (ichik) [reply app/client/packages/design-system/theming/src/hooks/src/useFluidTypography.tsx:53]: I thought we were going with our own implementation of capSize? Would be nice to add coefficients dictionary for supported typefaces then, since font-size is not font-family agnostic.

**Review by ichik — APPROVED** [review]

File: app/client/packages/design-system/theming/src/hooks/src/useFluidTypography.tsx (hunk 2 above)
Comment (KelvinOm) [reply app/client/packages/design-system/theming/src/hooks/src/useFluidTypography.tsx:53]: We still use capsize here, we request new data for each font-family. `createStyleObject` is a function of capsize. We pass the min, max font values plus font-family and function returns all the necessary styles, including compensators coefficients.

Comment (ichik) [reply app/client/packages/design-system/theming/src/hooks/src/useFluidTypography.tsx:53]: Cropping still happens, yes, but we're setting different font families to different sizes if we're using font-size.

File: app/client/packages/design-system/theming/src/token/src/types.ts [hunk 3]
```diff
@@ -39,3 +38,76 @@ export interface TokenSource {
...
+export const TYPOGRAPHY_VARIANTS = {
+  footnote: "footnote",
+  body: "body",
+  caption: "caption",
+  subtitle: "subtitle",
+  title: "title",
+  heading: "heading",
+} as const;
+
+export const TYPOGRAPHY_FONT_WEIGHTS = {
```
Comment (jsartisan) [inline app/client/packages/design-system/theming/src/token/src/types.ts:82]: should we store constants in types files? 🤔

**Review by jsartisan — APPROVED** [review]

File: app/client/packages/design-system/theming/src/token/src/types.ts (hunk 3 above)
Comment (KelvinOm) [reply app/client/packages/design-system/theming/src/token/src/types.ts:82]: Maybe then it's better to name the file `models`? Then it will make more sense. Anyway, let it be as it is for now, I see quite a lot of small improvements in this package that I want to make, but it's not critical, as it seems to me.
