### PR TITLE
fix: SMTP datasource should work without username and password

### LINKED ISSUE #37271: [Bug]: SMTP datasource should work without username and password
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When configuring SMTP datasource without username and password, always throws error `Invalid authentication credentials. Please check datasource configuration.`

Ideally we should be able to configure SMTP datasource without username and password too.
More specifically we need to remove the manual validations added on SMTP code base as it is possible to configure smtp service without password as well
Screenshot 2024-11-07 at 11 37 57 AM

### Steps To Reproduce

1. Use any email service for configuring SMTP datasource without setting up username and password
2. Create SMTP datasource with host port, keeping username and password blank
3. Test the configuration

### Public Sample App

_No response_

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

_No response_

### Version

v1.47

### PR DESCRIPTION
**Pull request by shanid544**
### Bug Description
Issue: When configuring an SMTP datasource without a username and password, the system throws an error: “Invalid authentication credentials. Please check datasource configuration.”
Expected Behavior: The system should allow SMTP datasource configuration without requiring authentication credentials, as it is possible to connect to some SMTP servers without a username or password.
**Steps To Reproduce**
Use any email service for configuring SMTP datasource without setting up username and password
Create SMTP datasource with host port, keeping username and password blank
Test the configuration

**Root Cause**
Manual validation in the codebase was enforcing that both username and password fields are mandatory for SMTP configuration. This validation prevented the successful configuration of SMTP services that do not require authentication.

**Solution Details**
_To fix this, the following changes were implemented:
Updated Validation Method (validateDatasource)_
Before: Enforced mandatory username and password validation.
After: Removed the strict validation check for authentication fields, allowing for configurations without credentials.

```
if (authentication == null || !StringUtils.hasText(authentication.getUsername()) || !StringUtils.hasText(authentication.getPassword())) {
    invalids.add(new AppsmithPluginException(AppsmithPluginError.PLUGIN_AUTHENTICATION_ERROR).getMessage());
}

```
_Modified the SMTP Session Creation (datasourceCreate)_
Before: Always initialized the SMTP session with authentication, assuming credentials were required.
After: Updated the session creation to support both authenticated and unauthenticated configurations.

```
Properties prop = new Properties();
prop.put("mail.smtp.auth", "false"); // Default to no authentication

if (authentication != null && StringUtils.hasText(authentication.getUsername()) && StringUtils.hasText(authentication.getPassword())) {
    prop.put("mail.smtp.auth", "true");
    session = Session.getInstance(prop, new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(username, password);
        }
    });
} else {
    session = Session.getInstance(prop);
}
```

_Enhanced Testing for Authentication Scenarios (testDatasource)_
Before: Errors were logged if authentication failed, even for servers where authentication wasn’t required.
After: Introduced a flag to detect if authentication was required based on the session configuration, and adjusted error handling accordingly.

```
boolean isAuthRequired = "true".equals(connection.getProperty("mail.smtp.auth"));
if (isAuthRequired && transport != null) {
    try {
        transport.connect();
    } catch (AuthenticationFailedException e) {
        invalids.add(SMTPErrorMessages.DS_AUTHENTICATION_FAILED_ERROR_MSG);
    }
}

```
**Testing and Verification**
**Unit Tests**
Without Authentication:
_Updated testNullAuthentication test case to ensure no errors are returned when authentication is absent._

```
@Test
public void testNullAuthentication() {
    DatasourceConfiguration invalidDatasourceConfiguration = createDatasourceConfiguration();
    invalidDatasourceConfiguration.setAuthentication(null);
    assertEquals(0, pluginExecutor.validateDatasource(invalidDatasourceConfiguration).size());
}
```

Fixes #37271

## Automation

/ok-to-test tags=""
updated testNullAuthentication() from SmtpPluginTest class

## Summary by CodeRabbit

- **New Features**
	- Enhanced SMTP plugin now supports conditional authentication during session creation.
	- Improved error handling for authentication failures, providing clearer validation results.
	- Added support for testing SMTP connections without authentication.

- **Bug Fixes**
	- Streamlined validation logic for datasource configurations, particularly for authentication scenarios.

- **Documentation**
	- Updated test methods to clarify expected error messages for invalid configurations.

### CODE REVIEW

File: app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java [hunk 1]
```diff
@@ -264,6 +273,10 @@ public Mono<DatasourceTestResult> testDatasource(Session connection) {
             log.debug(Thread.currentThread().getName() + ": testDatasource() called for SMTP plugin.");
             return Mono.fromCallable(() -> {
                         Set<String> invalids = new HashSet<>();
+
+                        boolean isAuthRequired = connection.getProperty("mail.smtp.auth") != null
```
Comment (sneha122) [inline app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java:277]: @shanid544 validateDatasource method has not been updated, it will still throw error when username and password is empty, please check that once

File: app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java [hunk 2]
```diff
@@ -273,7 +286,9 @@ public Mono<DatasourceTestResult> testDatasource(Session connection) {
                         } catch (NoSuchProviderException e) {
                             invalids.add(SMTPErrorMessages.DS_NO_SUCH_PROVIDER_ERROR_MSG);
                         } catch (AuthenticationFailedException e) {
-                            invalids.add(SMTPErrorMessages.DS_AUTHENTICATION_FAILED_ERROR_MSG);
+                            if (isAuthRequired) {
```
Comment (sneha122) [inline app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java:289]: @shanid544 Can you please explain why this isAuthRequired check is required here? In case of no username and password this exception would never occur right? So why this specific condition?

File: app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java (hunk 1 above)
Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java:277]: Sorry, I reverted by mistake, for testing the negative testing, will update

File: app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java [hunk 3]
```diff
@@ -131,12 +131,10 @@ public void testInvalidPort() {
...
     public void testNullAuthentication() {
-        DatasourceConfiguration invalidDatasourceConfiguration = createDatasourceConfiguration();
-        invalidDatasourceConfiguration.setAuthentication(null);
+        DatasourceConfiguration noAuthDatasourceConfiguration = createDatasourceConfiguration();
+        noAuthDatasourceConfiguration.setAuthentication(null);
 
-        assertEquals(
-                Set.of(new AppsmithPluginException(AppsmithPluginError.PLUGIN_AUTHENTICATION_ERROR).getMessage()),
-                pluginExecutor.validateDatasource(invalidDatasourceConfiguration));
+        assertEquals(0, pluginExecutor.validateDatasource(noAuthDatasourceConfiguration).size());
```
Comment (sneha122) [inline app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:137]: In this test case file, we are creating docker container for intergration testing, can you check if we can configure this without username and password and see if we can write test case for it? This way we would have tested the smtp without credentials end to end

File: app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java (hunk 2 above)
Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java:289]: When we call
```
transport.connect();

```
in case of username and password null it will throw AuthenticationFailedException. 


from Jakarta.Service.connect()

```
  if (!connected) {
                if (authEx != null) {
                    throw authEx;
                } else if (user == null) {
                    throw new AuthenticationFailedException("failed to connect, no user name specified?");
                } else if (password == null) {
                    throw new AuthenticationFailedException("failed to connect, no password specified?");
                } else {
                    throw new AuthenticationFailedException("failed to connect");
                }

```

Comment (sneha122) [reply app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java:289]: If we create session `session = Session.getInstance(prop, null);` with null authentication like this, will it still throw an error?

File: app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java (hunk 3 above)
Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:137]: will add one more test case for that

Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:137]: @sneha122 shall I update PR?

File: app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java (hunk 2 above)
Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java:289]: @sneha122 It is throwing error.

**Comment by shanid544** [comment]
@sneha122 Please review the changes

File: app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java [hunk 4]
```diff
@@ -131,12 +129,38 @@ public void testInvalidPort() {
...
-        DatasourceConfiguration invalidDatasourceConfiguration = createDatasourceConfiguration();
-        invalidDatasourceConfiguration.setAuthentication(null);
+        DatasourceConfiguration noAuthDatasourceConfiguration = createDatasourceConfiguration();
+        noAuthDatasourceConfiguration.setAuthentication(null);
+
+        assertEquals(0, pluginExecutor.validateDatasource(noAuthDatasourceConfiguration).size());
+    }
+
+    @Test
+    public void testConnectionWithoutAuth() {
```
Comment (sneha122) [inline app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]: @shanid544 We need to write test case in a way where we call the datasourceCreate or testDatasource method defined in our plugin interface. The test case you have written is purely connecting to SMTP through Session object. Please check this test case for reference https://github.com/appsmithorg/appsmith/blob/38c2859e929c9661d314f3d6be6edeed3cf724c5/app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java#L143

Here we have created datasourceConfig with username and password and then called out datasourceCreate method, we need to do the same but without username and password

Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]: Ok, got it, will update

Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]: ` @Test
    public void testNullAuthentication() {
        DatasourceConfiguration noAuthDatasourceConfiguration = createDatasourceConfiguration();
        noAuthDatasourceConfiguration.setAuthentication(null);
        final Mono<DatasourceTestResult> testDatasourceMono = pluginExecutor.testDatasource(noAuthDatasourceConfiguration);

        StepVerifier.create(testDatasourceMono)
            .assertNext(datasourceTestResult -> {
                assertNotNull(datasourceTestResult);
                assertTrue(datasourceTestResult.isSuccess());
                assertTrue(datasourceTestResult.getInvalids().isEmpty());
            })
            .verifyComplete();
        assertTrue(pluginExecutor.validateDatasource(noAuthDatasourceConfiguration).isEmpty());
    }`

@sneha122 Shall I add this?

Should i remove direct  SMTP Session test

Comment (sneha122) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]: This might not work because it would be using smtp container that is set with username and password, we may have to change the host and port in datasourceConfig

Comment (sneha122) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]: Yes we should not have direct SMTP session test

Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]:
```
@Test
    public void testNullAuthentication() {
        updateToSmtpWithoutAuth();
        DatasourceConfiguration noAuthDatasourceConfiguration = createDatasourceConfiguration();
        noAuthDatasourceConfiguration.setAuthentication(null);
        final Mono<DatasourceTestResult> testDatasourceMono = pluginExecutor.testDatasource(noAuthDatasourceConfiguration);

        StepVerifier.create(testDatasourceMono)
            .assertNext(datasourceTestResult -> {
                assertNotNull(datasourceTestResult);
                assertTrue(datasourceTestResult.isSuccess());
                assertTrue(datasourceTestResult.getInvalids().isEmpty());
            })
            .verifyComplete();
        assertTrue(pluginExecutor.validateDatasource(noAuthDatasourceConfiguration).isEmpty());
        updateToSmtpWithAuth();
    }

    private void updateToSmtpWithAuth() {
        host = smtp.getContainerIpAddress();
        port = Long.valueOf(smtp.getFirstMappedPort());
    }

    private void updateToSmtpWithoutAuth() {
        host = smtpWithoutAuth.getContainerIpAddress();
        port = Long.valueOf(smtpWithoutAuth.getFirstMappedPort());
    }
```

@sneha122 updated the host and port, and reverted to the old host and port

Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]:
```
@Test
    public void testConnectionWithoutAuth() {
        configureSmtpConnection(false); 
        DatasourceConfiguration noAuthDatasourceConfiguration = createDatasourceConfiguration();
        noAuthDatasourceConfiguration.setAuthentication(null); // No authentication

        Mono<DatasourceTestResult> testDatasourceMono = pluginExecutor.testDatasource(noAuthDatasourceConfiguration);

        StepVerifier.create(testDatasourceMono)
            .assertNext(datasourceTestResult -> {
                assertNotNull(datasourceTestResult);
                assertTrue(datasourceTestResult.isSuccess());
                assertTrue(datasourceTestResult.getInvalids().isEmpty());
            })
            .verifyComplete();
        configureSmtpConnection(true);
    }
````

 ```
@BeforeAll
    public static void setup() {
        //Initialize SMTP connection with default configuration (can be changed per test)
        configureSmtpConnection(true); //Default withAuth (true)
    }
    
    private static void configureSmtpConnection(boolean withAuth) {
        if (withAuth) {
            host = smtp.getContainerIpAddress();
            port = Long.valueOf(smtp.getFirstMappedPort());
        } else {
            host = smtpWithoutAuth.getContainerIpAddress();
            port = Long.valueOf(smtpWithoutAuth.getFirstMappedPort());
        }
        System.out.println("SMTP Host: " + host + ", Port: " + port);
    }
```
@sneha122 I have updated host & port in this way, and revertted after the test.

Comment (sneha122) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]: Sounds good! Does the test pass in that case?

Comment (sneha122) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]: Instead you can also pass the container object itself, so we don't have to keep a boolean, we can simply take host and port from the container which is passed

Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:139]: > Sounds good! Does the test pass in that case?

yes

Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:135]: @sneha122 Please review the changes

File: app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java [hunk 5]
```diff
@@ -28,17 +27,10 @@
 import reactor.core.publisher.Mono;
 import reactor.test.StepVerifier;
 
-import java.util.ArrayList;
-import java.util.Arrays;
-import java.util.HashMap;
-import java.util.List;
-import java.util.Map;
-import java.util.Set;
+import java.util.*;
```
Comment (sneha122) [inline app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:30]: @shanid544 Can we please keep the imports as is and not make it wildcard imports like java.util.*

File: app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java [hunk 6]
```diff
@@ -28,17 +27,10 @@
...
 import java.util.stream.Collectors;
 
-import static org.junit.jupiter.api.Assertions.assertEquals;
-import static org.junit.jupiter.api.Assertions.assertNotNull;
-import static org.junit.jupiter.api.Assertions.assertTrue;
+import static org.junit.jupiter.api.Assertions.*;
```
Comment (sneha122) [inline app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:33]: Same here, let's keep the imports as is

File: app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java (hunk 4 above)
Comment (shanid544) [reply app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java:143]: @sneha122 made changes on imports

**Comment by sneha122** [comment]
Thank you @shanid544 PR looks good to me, ill create shadow PR and run test cases on it

**Comment by shanid544** [comment]
@sneha122 Could you please approve this.

**Review by sneha122 — DISMISSED** [review]

**Comment by shanid544** [comment]
@sneha122 2 check are pending, those should automatically trigger ryt?

**Comment by sneha122** [comment]
Created shadow Pr here for monitoring tests: https://github.com/appsmithorg/appsmith/pull/37393

**Comment by shanid544** [comment]
> @shanid544 Can you please run this command on server `mvn spotless:apply`? There are some formatting issues which will be fixed by this command

@sneha122 Ran, should I commit that changes as well?

**Comment by sneha122** [comment]
> > @shanid544 Can you please run this command on server `mvn spotless:apply`? There are some formatting issues which will be fixed by this command
> 
> @sneha122 Ran, should I commit that changes as well?

yes please

**Comment by shanid544** [comment]
@sneha122  Formatted

**Comment by sneha122** [comment]
Thanks @shanid544 Once all tests are completed, will merge the PR

**Review by sneha122 — APPROVED** [review]
