### PR TITLE
Fixed upload logo payload limit and added delete logo API

### LINKED ISSUE #1489: [Feature] API: Remove logo for org
## Summary
Need an api which deletes the logo of an org.

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description
* Fixed upload logo for organization to allow files greater than 4kb
* Set approximate limit of upload files to 250kb
* Added delete logo API

Fixes #1489

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?
- JUnit tests for uploadLogo and deleteLogo
- Locally tested APIs

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nidhi-nair** [comment]
These changes will need an update in the Postman docs. Also, please review this code critically so I learn the standard, I've tried to look at neighbouring code for hints but even that has evolved over time to have multiple versions.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/OrganizationController.java [hunk 1]
```diff
@@ -61,10 +66,19 @@ public OrganizationController(OrganizationService organizationService, UserOrgan
 
     @PostMapping("/{organizationId}/logo")
     public Mono<ResponseDTO<Organization>> uploadLogo(@PathVariable String organizationId,
-                                                      @RequestPart("file") Mono<Part> fileMono) {
-        return fileMono
+                                                      @RequestPart("file") Mono<Part> fileMono,
+                                                      @RequestHeader("Content-Length") long contentLength) {
+        return contentLength > 251 * 1024 ?
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/OrganizationController.java:71]: Please move this magic number to a constant. Makes it easy for us to modify it in the future. Also, please add a comment about whether this is bytes, kb, mb etc.

Comment (mohanarpit) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/OrganizationController.java:71]: Also, is it possible for us to move this check to the service level function? Makes it easy for us to write a test case for it.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java [hunk 2]
```diff
@@ -69,6 +68,7 @@
     INVALID_CURL_METHOD(400, 4032, "Invalid method in cURL command: {0}.", AppsmithErrorAction.DEFAULT),
     OAUTH_NOT_AVAILABLE(500, 5006, "Login with {0} is not supported.", AppsmithErrorAction.LOG_EXTERNALLY),
     MARKETPLACE_NOT_CONFIGURED(500, 5007, "Marketplace is not configured.", AppsmithErrorAction.DEFAULT),
+    PAYLOAD_TOO_LARGE(413, 4028, "Unable to process the request entity.", AppsmithErrorAction.DEFAULT)
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java:71]:
```suggestion
    PAYLOAD_TOO_LARGE(413, 4028, "The request payload is too large. Max allowed size for request payload is {0} KB", AppsmithErrorAction.DEFAULT)
```

Comment (mohanarpit) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java:71]: The variable `{0}` will then need to be passed when we raise the exception in our functions.

**Comment by mohanarpit** [comment]
@nidhi-nair Please feel free to update the Postman files as you see fit in order to add/modify existing APIs

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java [hunk 3]
```diff
@@ -990,6 +990,69 @@ public void uploadOrganizationLogo() throws IOException {
                 .verifyComplete();
     }
 
+    @Test
+    @WithUserDetails(value = "api_user")
+    public void uploadOrganizationLogo_nullFilePart() throws IOException {
+        final String organizationId = organizationRepository
+                .findByName("Spring Test Organization")
+                .blockOptional(Duration.ofSeconds(3))
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java:998]: Any particular reason that we are blocking here for 3 seconds?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java [hunk 4]
```diff
@@ -990,6 +990,69 @@ public void uploadOrganizationLogo() throws IOException {
...
+                .map(Organization::getId)
+                .orElse(null);
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java:1000]: Why would we hit this case? Shouldn't the test organization "Spring Test Organization" always exist?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java [hunk 5]
```diff
@@ -990,6 +990,69 @@ public void uploadOrganizationLogo() throws IOException {
...
+
+        assertThat(organizationId).isNotNull();
+
+        final Mono<Organization> resultMono = organizationService.uploadLogo(organizationId, null);
+
+        StepVerifier.create(resultMono)
+                .expectError(AppsmithException.class);
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java:1007]: Please take a look at how exceptions are asserted in other tests as well. We should not just assert the exception class, but also the type of exception & message being returned. In the past, we've seen issues where `AppsmithException` was returned but it was from a different part of the code base and not the message that we expected to see.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java (hunk 3 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java:998]: So this is one of two ways I've seen the tests being configured. The other was to have multiple step verifiers to allow for ordering monos sequentially. I'm guessing step verifiers are the way to go?

Comment (mohanarpit) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java:998]: Aah ... I see now why the `block()` function was used. This was done to keep the test code more readable. If we don't use `block()`, then the return will be `Mono<String>` which then needs to be piped into the next function which uses it's value. The 3 secs duration is the max time that this step will take. After that it'll error out. 

Let's keep the code as is then. Instead, can you add a comment explaining this in the function itself? So that we aren't asking ourselves this same question in 6 months from now?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java (hunk 4 above)
Comment (mohanarpit) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java:1000]: Here as well. The `orElse` is just a protection against a timeout in the `block()` function. Keep this as is.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java [hunk 6]
```diff
@@ -340,16 +347,38 @@ public OrganizationServiceImpl(Scheduler scheduler,
...
+                            .flatMap(analyticsService::sendCreateEvent)
                             .flatMap(asset -> {
                                 organization.setLogoAssetId(asset.getId());
                                 return repository.save(organization);
                             })
                             .flatMap(savedOrganization ->
-                                prevAssetId != null
-                                        ? assetRepository.deleteById(prevAssetId).thenReturn(savedOrganization)
-                                        : Mono.just(savedOrganization)
+                                    prevAssetId != null
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java:356]: Here as well. Can we add braces to make this more readable? As a thumb rule, ternary operators are great for one-liners, but in this case, I'd much rather prefer an if-block. Makes the code a lot more readable & scannable.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java [hunk 7]
```diff
@@ -340,16 +347,38 @@ public OrganizationServiceImpl(Scheduler scheduler,
 
                     return assetRepository
                             .save(new Asset(filePart.headers().getContentType(), data))
+                            .flatMap(analyticsService::sendCreateEvent)
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java:350]: Can we move the call to the analytics service to the end of this stream? We should send analytics when the entire processing is complete.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java [hunk 8]
```diff
@@ -340,16 +347,38 @@ public OrganizationServiceImpl(Scheduler scheduler,
...
     }
 
+    @Override
+    public Mono<Organization> deleteLogo(String organizationId) {
+        return repository
+                .findById(organizationId, MANAGE_ORGANIZATIONS)
+                .switchIfEmpty(Mono.error(new AppsmithException(AppsmithError.NO_RESOURCE_FOUND, FieldName.ORGANIZATION, organizationId)))
+                .flatMap(organization -> {
+                    final String prevAssetId = organization.getLogoAssetId();
+                    if(prevAssetId == null)
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java:373]: Nitpick: Here as well. Please use braces for if conditions.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Constraint.java [hunk 9]
```diff
@@ -0,0 +1,6 @@
+package com.appsmith.server.constants;
+
+public class Constraint {
+    public static final int ORGANIZATION_LOGO_CHUNKS = 63;
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Constraint.java:4]: To my understanding this number is calculated from by (fileSize / 4) right? If yes, then please remove it from the constants and actually calculate & use it in code. This is because, in the future, when we wish to modify the max file size, developers don't have to worry about modifying 2 constants. They only need to modify a single constant and everything is derived from there.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Constraint.java [hunk 10]
```diff
@@ -0,0 +1,6 @@
...
+    public static final int ORGANIZATION_LOGO_SIZE = 250;
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Constraint.java:5]:
```suggestion
    public static final int ORGANIZATION_LOGO_SIZE_KB = 250;
```

Adding the units in the constant makes it super clear what we are talking about.

**Review by mohanarpit — APPROVED** [review]
