### PR TITLE
fix: Fix chart dataset crash

### LINKED ISSUE #26325: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Sentry Issue: [APPSMITH-6SE](https://appsmith.sentry.io/issues/4382323470/?referrer=github_integration)

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
  at forEach (widgets/ChartWidget/component/EChartsDatasetBuilder.ts:26:42)
  at Array.forEach (<anonymous>)
  at <object>.value (widgets/ChartWidget/component/EChartsDatasetBuilder.ts:22:32)
  at _this.getEChartsOptions (widgets/ChartWidget/component/index.tsx:136:34)
  at _this.renderECharts (widgets/ChartWidget/component/index.tsx:195:35)
...
(15 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #26325

### CODE REVIEW

File: app/client/src/workers/Evaluation/validations.ts [hunk 1]
```diff
@@ -50,6 +51,20 @@ function getPropertyEntry(
   }
 }
 
+function captureChartSentryMessage(value: unknown, propertyPath: string) {
```
Comment (sbalaji1192) [inline app/client/src/workers/Evaluation/validations.ts:54]: We should not keep this code here. validations.ts should only house the generic validations related functions. please find a better point in the control flow for this

File: app/client/src/widgets/ChartWidget/widget/index.tsx [hunk 2]
```diff
@@ -31,6 +33,25 @@ export const emptyChartData = (props: ChartWidgetProps) => {
     }
   } else {
     for (const seriesID in props.chartData) {
+      try {
+        props.chartData[seriesID].data.length;
```
Comment (sbalaji1192) [inline app/client/src/widgets/ChartWidget/widget/index.tsx:37]: use an if condition instead of try catch block.

File: app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.ts [hunk 3]
```diff
@@ -25,14 +26,29 @@ export class EChartsDatasetBuilder {
...
-        if (!categories[categoryName]) {
-          categories[categoryName] = {};
+          if (!categories[categoryName]) {
+            categories[categoryName] = {};
+          }
+          categories[categoryName][seriesID] = value;
+        }
+      } catch (error) {
+        const message =
+          "Chart Dataset Error\n" +
```
Comment (sbalaji1192) [inline app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.ts:41]: use template literal instead of concatenation.

**Review by sbalaji1192 — APPROVED** [review]
