### PR TITLE
fix: Makes use of mobile positioning properties in Table Widget

### LINKED ISSUE #22907: [Bug][Table] Increasing the height of table in mobile viewport creates a blank space at bottom (with no cell borders)
Image

### LINKED ISSUE #22911: [Bug] the Table widgets pageSize property cannot be updated in mobile viewport
https://www.loom.com/share/64a52913d2254122af468b2a5f58ff11

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Table widget's pageSize property was not taking account of mobile position properties (`mobileTopRow` and `mobileBottomRow`) in Auto Layout mode. This caused the issues mentioned in this PR.
Since this is a derived property, properties such as `isMobile` and `appPositioningType` were not directly available. So, we added these into the DataTree as well.

#### PR fixes following issue(s)
Fixes #22907
Fixes #22911

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by keyurparalkar — COMMENTED** [review]
@aswathkk Can you please add cypress test for the issue?

@sbalaji1192 can you provide a final review on this? The changes LGTM!

File: app/client/src/sagas/selectors.tsx [hunk 1]
```diff
@@ -48,6 +48,9 @@ export const getCanvasAndMetaWidgets = createSelector(
 
 export const getWidgetsMeta = (state: AppState) => state.entities.meta;
 
+export const getIsMobileBreakPoint = (state: AppState) =>
```
Comment (sbalaji1192) [inline app/client/src/sagas/selectors.tsx:51]: Why are we calling the selector breakPoint when the state just calls it isMobile

File: app/client/src/entities/DataTree/dataTreeFactory.ts [hunk 2]
```diff
@@ -141,8 +144,13 @@ export class DataTreeFactory {
       );
 
       dataTree[widget.widgetName] = unEvalEntity;
+      if (widgets[MAIN_CONTAINER_WIDGET_ID].positioning === "vertical") {
```
Comment (sbalaji1192) [inline app/client/src/entities/DataTree/dataTreeFactory.ts:147]: nit: Can we create constants for these values?

**Review by sbalaji1192 — APPROVED** [review]
@aswathkk Just had two minor callouts. Since we're adding properties to the data tree , could you ask someone from fe coders to review this once?

File: app/client/src/sagas/selectors.tsx (hunk 1 above)
Comment (aswathkk) [reply app/client/src/sagas/selectors.tsx:51]: This selector checks whether the app is in mobile break point or not.
In the future, we might be having multiple breakpoints.

File: app/client/src/entities/DataTree/dataTreeFactory.ts [hunk 3]
```diff
@@ -141,8 +146,16 @@ export class DataTreeFactory {
       );
 
       dataTree[widget.widgetName] = unEvalEntity;
+      if (
+        widgets[MAIN_CONTAINER_WIDGET_ID].positioning === Positioning.Vertical
+      ) {
+        dataTree[widget.widgetName].appPositioningType =
+          AppPositioningTypes.AUTO;
+      }
+      dataTree[widget.widgetName].isMobile = isMobile;
```
Comment (Rishabh-Rathod) [inline app/client/src/entities/DataTree/dataTreeFactory.ts:155]: @aswathkk  Instead of adding the `isMobile` property to each widget, it would be better to add it in `appsmith.isMobile` and then later read the dataTree value and pass it to each widget.

**Review by sbalaji1192 — DISMISSED** [review]
Table-related changes look good to me.

File: app/client/src/entities/DataTree/dataTreeFactory.ts (hunk 3 above)
Comment (aswathkk) [reply app/client/src/entities/DataTree/dataTreeFactory.ts:155]: @Rishabh-Rathod How to do read the dataTree value and pass it to each widget?
Where to do that?

**Review by sbalaji1192 — APPROVED** [review]
