### PR TITLE
Fix long app names not visible

### LINKED ISSUE #720: [BUG] App name isn't completely visible when it's long
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate :
1. From the homepage, create an app named 'gnerwihnireongionihgnerwihnireongionihgnerwihnireongionihgnerwihnireongionihgnerwihnireongionihgnerwihnireongionih1' under an organization

issue: App name with long names isn't completely visible

Attachment - https://drive.google.com/drive/folders/1Z4Xe_Up8As0p1lrmb6K7zpND6YaWN0TT?usp=sharing

### PR DESCRIPTION
**Pull request by jsartisan**
Description:
Adding an ellipsis by CSS for the text longer than 3 lines and adding popover that will show the full name on hover.

Fixes #720

### CODE REVIEW

File: app/client/src/pages/Applications/ApplicationCard.tsx [hunk 1]
```diff
@@ -509,12 +521,25 @@ export const ApplicationCard = (props: ApplicationCardProps) => {
...
-          </Text>
+          {isEllipsisActive(appNameWrapperRef?.current) ? (
+            <TooltipComponent
+              maxWidth={400}
+              position={Position.BOTTOM}
+              content={props.application.name}
+            >
+              <Text type={TextType.H3} cypressSelector="t--app-card-name">
+                {props.application.name}
+              </Text>
```
Comment (hetunandu) [inline app/client/src/pages/Applications/ApplicationCard.tsx:536]: Can we make sure this part is not duplicated

File: app/client/src/utils/helpers.tsx [hunk 2]
```diff
@@ -136,3 +136,16 @@ export const trimTrailingSlash = (path: string) => {
   const trailingUrlRegex = /\/+$/;
   return path.replace(trailingUrlRegex, "");
 };
+
+/**
+ * checks if ellipsis is active on the DOM element
+ *
+ * @param element
+ */
+export const isEllipsisActive = (element: HTMLElement | null) => {
```
Comment (hetunandu) [inline app/client/src/utils/helpers.tsx:145]: This needs some comments to explain why this works

File: app/client/src/pages/Applications/ApplicationCard.tsx [hunk 3]
```diff
@@ -509,12 +521,25 @@ export const ApplicationCard = (props: ApplicationCardProps) => {
...
           isFetching={isFetchingApplications}
           className={isFetchingApplications ? Classes.SKELETON : ""}
         >
-          <Text type={TextType.H3} cypressSelector="t--app-card-name">
-            {props.application.name}
-          </Text>
+          {isEllipsisActive(appNameWrapperRef?.current) ? (
+            <TooltipComponent
+              maxWidth={400}
+              position={Position.BOTTOM}
```
Comment (hetunandu) [inline app/client/src/pages/Applications/ApplicationCard.tsx:531]: position should be auto

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Review by hetunandu — APPROVED** [review]
