### PR TITLE
fix: Fix for import curl when app is connected to git

### LINKED ISSUE #10354: [Bug] Curl import fails with resource not found error when the application is connected to git

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> As the branch name param was not taken into consideration when importing the curl for the application connected to git, while saving the action branchName was not getting saved which resulted in resource not found error. This PR introduces the branchName param for `create method` in `RestAPIImportControllerCE` which saves the action with branchName so that action can be identified by `defaultActionId` and `branchName`. 

Fixes #10354

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> JUnit TC
> Manual Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java [hunk 1]
```diff
@@ -69,20 +80,27 @@ public CurlImporterServiceCEImpl(PluginService pluginService,
...
                     final Plugin plugin = tuple.getT2();
+                    final NewPage newPage = tuple.getT3();
+
                     final Datasource datasource = action1.getDatasource();
                     final DatasourceConfiguration datasourceConfiguration = datasource.getDatasourceConfiguration();
                     datasource.setName(datasourceConfiguration.getUrl());
                     datasource.setPluginId(plugin.getId());
                     datasource.setOrganizationId(orgId);
+                    // Set git related resource IDs
+                    action1.setDefaultResources(newPage.getDefaultResources());
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java:99]: This was missing earlier which includes the `branchName` param from the parent page

**Review by AnaghHegde — APPROVED** [review]
