### PR TITLE
fix: Firestore Invalid DS Test Success

### LINKED ISSUE #21373: [Bug]: Firestore: If the user enters a wrong credentials, the test still pass
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user enters a wrong credentials in database URL or Project ID, the test still pass. 
Please note - The query doesn't run which is fine.

### Steps To Reproduce

1. Create and test a firestore datasource
2. edit the same - say - Edit database URL or Project ID field.
3. Test it again
Observe - It shows datasource is valid

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/5afcad9d23d64a0eb3a13fd6aaa6ec84

### Version

1.9.12

### PR DESCRIPTION
**Pull request by PiyushPushkar02**
## Description

- The following PR fixes the issue where the firestore test data source was returning success even after providing an invalid project id.
- The PR address the invalid project id only not the db URL as it is fetched from the auth json If the URL is invalid in user provided entry. Also, the value is mutable at runtime from the firestore side.
-  For more detailed description of the following can be found in the notion doc here: https://www.notion.so/Firestore-c3f5c816a68a45b18395da74be97d666

Fixes #21373 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- JUnit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java [hunk 1]
```diff
@@ -902,13 +904,29 @@ public Mono<Firestore> datasourceCreate(DatasourceConfiguration datasourceConfig
                         try {
                             return FirebaseApp.getInstance(projectId);
                         } catch (IllegalStateException e) {
-                            return FirebaseApp.initializeApp(options, projectId);
+                            return FirebaseApp.initializeApp(options,projectId);
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java:907]: Nit: Can you please format the code in this PR according to standards? This changelog is not formatted correctly.

File: app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/exceptions/FirestoreErrorMessages.java [hunk 2]
```diff
@@ -67,6 +67,7 @@ private FirestoreErrorMessages() {
     public static final String DS_VALIDATION_FAILED_FOR_SERVICE_ACC_CREDENTIALS_ERROR_MSG = "Validation failed for field 'Service Account Credentials'. Please check the " +
             "value provided in the 'Service Account Credentials' field.";
 
+    public static final String DS_VALIDATION_FAILED_FOR_PROJECT_ID = "Invalid project id, no database found for given project id";
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/exceptions/FirestoreErrorMessages.java:70]: Please keep the sentence casing and grammar as per other error messages. Consistency is key to a polished product.

File: app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java [hunk 3]
```diff
@@ -919,9 +919,17 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
                         try {
                             connection.listCollections();
                         } catch (FirestoreException e){
-                            log.debug("Invalid datasource configuration : {}",e.getMessage());
+                            log.debug("Invalid datasource configuration : {}", e.getMessage());
+                            if(e.getMessage().contains("Metadata operations require admin authentication")){
+                                String metaDataAccessMissingMessage = "Unable to validate ProjectID, provided service " +
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java:924]: @PiyushPushkar02 just a general suggestion. Whenever we write an error message we should try to structure it so that (1) It is friendly / humane (2) It tells the user exaclty what th issue is (3) It tells the user what to do next. Since we don't have a platform wide convention on this, IMO, for now we should change the message to something along the following lines. Please mention if you think otherwise or if we could add / modify to improve upon it: 
```
Hi, it seems that the credentials provided here don't have the permission to gather metadata information. Please reach out to your database admin to understand more. 
```

Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java:924]: Can you please convert this message string in a `public static final String` macro and use the same in the test case as well ?

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java [hunk 4]
```diff
@@ -646,24 +650,48 @@ public void testTestDatasource_withCorrectCredentials_returnsWithoutInvalids() {
...
+                .verifyComplete();
+    }
+
+    @Test
+    public void testDatasource_withInvalidProjectId_WithMetaDataAccess() {
+
+        //This validates firestore connection and the ProjectId given by the user
+        FirestorePlugin.FirestorePluginExecutor spyExecutor = Mockito.spy(pluginExecutor);
+
+        FirebaseOptions firebaseOptions = FirebaseOptions.builder()
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:678]: Instead of building the `Firestore` object explicitly here, could we instead create a new datasource config object with the required parameters and then `datasourceCreate` should build the Firestore object as part of its flow ? Reason being that if we build it explicitly here and then some code change happens as part of the datasource create flow then we wouldn't be able to verify the impact of that change on this PR since this PR creates the object on its own.

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java [hunk 5]
```diff
@@ -674,7 +674,8 @@ public void testDatasource_withInvalidProjectId_WithMetaDataAccess() {
 
         //This validates firestore connection and the ProjectId given by the user
         FirestorePlugin.FirestorePluginExecutor spyExecutor = Mockito.spy(pluginExecutor);
-
+        //We cannot use the datasource create flow here as the client authentication json in unknown. Hence, using the
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:677]: Minor: should it be `is unknown` instead of `in unknown` ?

**Review by sumitsum — APPROVED** [review]

File: app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/exceptions/FirestoreErrorMessages.java (hunk 2 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/exceptions/FirestoreErrorMessages.java]: done

File: app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java (hunk 1 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java]: done
