### PR TITLE
Fix-Show table columns in selectedRow autocomplete irrespective of table row selection

### LINKED ISSUE #1425: [Bug] Values inside the selected row do not show in the auto complete until the row is selected
### Steps to reproduce the behaviour:
1. Drag a table and a button
2. In the button enter the binding {{ Table1.selectedRow. }}
3. none of the table columns show in the auto complete

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Show table columns in selectedRow autocomplete irrespective of table row selection

Fixes #1425 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually tested

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/TableWidget.tsx [hunk 1]
```diff
@@ -361,7 +361,7 @@ class TableWidget extends BaseWidget<TableWidgetProps, WidgetState> {
       const columnKeys: string[] = getAllTableColumnKeys(this.props.tableData);
       const selectedRow: { [key: string]: any } = {};
       for (let i = 0; i < columnKeys.length; i++) {
-        selectedRow[columnKeys[i]] = undefined;
+        selectedRow[columnKeys[i]] = null;
```
Comment (riodeuno) [inline app/client/src/widgets/TableWidget.tsx:364]: Can we use `""` instead of `null` here? This is what we're using elsewhere.

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Review by riodeuno — APPROVED** [review]
