### PR TITLE
fix: Refactored common datatype handling logic to conform to new client side datatypes 

### LINKED ISSUE #7462: Datatypes in request payload is being changed
## Description

appsmith is changing the datatype of json payload before sending it to server. 

image

have a look at ```"phone_number": {{phone_number.text}},``` in the above screenshot. evaluated value says it will be sent as string. but when actual operation happens it converts it to numbers. I have also tried ```"phone_number": "{{phone_number.text}}",```. I have also tried ```"phone_number": {{`"${phone_number.text}"`}},```

the API which I am calling is facebook's so I don't have control over their code or server. 

#### My Take on this
It should take textbox as string by default. if a developer/user wants to send a value as Number then he/she can always convert it before sending. 

### Steps to reproduce the behavior:

Add steps to reproduce this behavior, include console / network logs & screenshots

1. take a Input box in canvas
2. take the value of that input box and send to an API in body as JSON
3. Input numbers in input box
4. Send the request and see what is sending to the server

### Expected behavior
Appsmith should send what is being shown in the evaluated value tooltip.

### Actual behavior 
If a string has a digits in it then appsmith is changing that property's value to Number data type.

### Important Details

- Version: Cloud
- OS: Windows
- Browser: chrome
- Environment: production

### LINKED ISSUE #13620: [Bug]-[Infinity]:Query Fails When Prepared Statement Is Turned On and Value Contains Only Numbers and Commas
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When running a **query** with **Prepared Statement** turned **on**, in which one of the values contains only **numbers** and **commas** (and optionally, **one single dot**),  it returns the error: 

> Query preparation failed while inserting value: 12,23.4, for binding: {{Input3.text}}. Please check the query again.
> Error: Character , is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

**Notes**: 
- This happens for all queries (Select, Insert, etc.)
- The issue is reproducible for **PostgreSQL** and **MySQL** databases.

image
image

Sample app that reproduces the issue: https://app.appsmith.com/app/prepared-statement-with-comma/prepared-statement-with-comma-6273fdb75984be5f57847aad

### Steps To Reproduce

1. Create a **Select** or **Insert** query and bind it to an **Input** or **Text** widget.
2. Ensure **Prepared Statement** is turned **on**.
image
3. Enter a **value** that contains only **numbers** and **commas** (and optionally, **one single dot**) in the **widget**. E.g., `12,34` or `12,03,456,7.89`.
image
4. Run the **query**.
image

### Public Sample App

https://app.appsmith.com/app/prepared-statement-with-comma/prepared-statement-with-comma-6273fdb75984be5f57847aad

### Version

Appsmith v1.6.24-SNAPSHOT

### LINKED ISSUE #15578: [Bug]: No operator matches the given name and argument types (text = integer)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to pass a numeric value as a string to a text column in Postgres then I get an exception like below

Screenshot 2022-08-01 at 6 19 43 PM

The server treats the numeric value as an integer although the client sent it as a string. As Postgres is stringent at data type matching we encounter the above error. 

As a current workaround explicit type cast in the query is required.

Screenshot 2022-08-01 at 6 22 40 PM

### Steps To Reproduce

1. Create a table with a column having column-type text or varchar
2. Create an input widget with type text // Input1
3. Put some numeric value inside the input widget e.g. 838831
4. Turn on the prepared statement
5. Write an SQL like `SELECT * FROM your_table where your_text_column = {{Input1.text}} `
6. You will see an exception mentioned above

### Public Sample App

_No response_

### Version

Cloud / Self Hosted

### LINKED ISSUE #16994: [Task]: Refactor common data type handling logic w.r.t. the newer structure
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### LINKED ISSUE #17072: [Bug]-[Infinity]:Appsmith treats a string as a number when the string is a numeric value with leading zero(s)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This one comes from this [post](https://community.appsmith.com/t/adding-a-string-that-is-a-number-with-a-leading-zero/180)

User's complain:

https://community.appsmith.com/t/adding-a-string-that-is-a-number-with-a-leading-zero/180/12

### Steps To Reproduce

1. Let's have a table named x where col has some data "098765" of varchar type
2. Create a query like select * from x where col = {{"098765"}} 
3. Appsmith identifies "098765" as an integer and thus loses the leading zero

### Public Sample App

_No response_

### Version

Cloud / Self Hosted

### PR DESCRIPTION
**Pull request by subrata71**
## Description

This PR will essentially solve some long-pending data type issues across different plugins. Now all the plugins will be able to distinguish between 
- `{{null}} and {{"null"}}` //the former is the null object and the latter is the null as a string
- `{{098765}} and {{"098765"}}` //the former will be identified as a number and the latter will be identified as a string

Fixes #16994
Fixes #13620
Fixes #17072
Fixes #15578
Fixes #7462

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual
- JUnit Tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java [hunk 1]
```diff
@@ -23,17 +22,7 @@ public boolean test(String s) {
...
-            if (!trimmedInputBetweenBraces.isEmpty()) {
-                try {
-                    new ObjectMapper().readValue(trimmedValue, List.class);
-                    return true;
-                } catch (JsonProcessingException e) {
-                    return false;
-                }
-
-            }
+            return  (!trimmedInputBetweenBraces.isEmpty());
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java:25]: Could you please help me understand this change? Should we be considering empty arrays here?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/NullType.java [hunk 2]
```diff
@@ -12,6 +11,13 @@ public boolean test(String s) {
             return true;
         }
         final String trimmedValue = s.trim();
+        if (trimmedValue.startsWith("[") && trimmedValue.endsWith("]")) {
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/NullType.java:14]: Let's create specific null types for these?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java [hunk 3]
```diff
@@ -27,7 +27,7 @@ public class DataTypeServiceUtils {
             JsonObjectType is the preferred server-side data type when the client-side data type is of type OBJECT.
             Fallback server-side data type for client-side OBJECT type is String.
          */
-        defaultAppsmithTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType()));
+        defaultAppsmithTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType(), new BsonType()));
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java:30]: Should `BsonType` be a default? Would we want this to only apply for Mongo?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java [hunk 4]
```diff
@@ -196,17 +199,21 @@ public static DataType stringToKnownDataTypeConverter(String input) {
...
      * @return
      */
     public static String jsonSmartReplacementPlaceholderWithValue(String input,
                                                                   String replacement,
                                                                   DataType replacementDataType,
                                                                   List<Map.Entry<String, String>> insertedParams,
-                                                                  SmartSubstitutionInterface smartSubstitutionUtils) {
+                                                                  SmartSubstitutionInterface smartSubstitutionUtils,
+                                                                  Param param,
+                                                                  Object...args) {
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java:211]: I'm sorry I keep asking this over and over. Why are we using varargs here? It's a code smell and I know we've talked about this before, I forget your reason.

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Mostly shared code related comments.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java (hunk 4 above)
Comment (subrata71) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java:211]: I will remove this varargs. I forgot to refactor this. It's not required anymore at this.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java (hunk 3 above)
Comment (subrata71) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java:30]: I will move it to mongoplugin module.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java [hunk 5]
```diff
@@ -12,7 +12,7 @@ public class DataTypeServiceUtils {
     static  {
         defaultAppsmithTypes.put(ClientDataType.NULL, List.of(new NullType()));
 
-        defaultAppsmithTypes.put(ClientDataType.ARRAY, List.of(new ArrayType()));
+        defaultAppsmithTypes.put(ClientDataType.ARRAY, List.of(new NullArrayType(), new ArrayType()));
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java:15]: NullArrayType only applies to SQL plugins right?

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDataTypeTest.java [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+        pluginSpecificTypes.put(ClientDataType.ARRAY, List.of(new ArrayType()));
+
+        pluginSpecificTypes.put(ClientDataType.NUMBER, List.of(
+                new IntegerType(),
+                new LongType(),
+                new DoubleType(),
+                new BigDecimalType()
+        ));
+
+        pluginSpecificTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType(), new BsonType()));
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDataTypeTest.java:46]: QQ: Could you please explain the order of prioritization between JSON and BSON here? We should also add a comment so we don't ask this question again!

Comment (subrata71) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDataTypeTest.java:46]: I just followed the same order which was in `jsonSmartReplacementPlaceholderWithValue` method. Inspired by that type hierarchy.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java (hunk 5 above)
Comment (subrata71) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java:15]: This one I am not 100% certain about. There could be use cases for non-sql plugins too. I put it in the default datatypes collection though.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java (hunk 1 above)
Comment (subrata71) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java:25]: If the array is not empty only then it will be identified as an array data type. You see a (!) before that condition.

Comment (nidhi-nair) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java:25]: Can empty array types not be identified as this as well?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java (hunk 5 above)
Comment (nidhi-nair) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java:15]: I think we should. treat this on a case by case basis? Since this is a known problem for SQL, let's use it for those plugins only? The reason for this is that we're going to add a null kind of handling for other plugins as well and that might be undesirable.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java (hunk 1 above)
Comment (subrata71) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java:25]: No, empty will be identified as `NullArray`.

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDataTypeTest.java (hunk 6 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDataTypeTest.java:46]: It would be great if you can add a comment here about the possible logic for this as per your understanding. :)

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 7]
```diff
@@ -1106,5 +1106,45 @@ public void testAPIResponseEncodedInGzipFormat() {
                 })
                 .verifyComplete();
     }
+
+    @Test
+    public void testNumericStringHavingLeadingZeroWithPreparedStatement() {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:1111]: This seems to be an incorrect name for this plugin.

File: app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java [hunk 8]
```diff
@@ -5,6 +5,7 @@
 import com.amazonaws.services.s3.AmazonS3ClientBuilder;
 import com.amazonaws.services.s3.model.*;
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java:6]: Not your change, but could you please fix this?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java (hunk 1 above)
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java:25]: QQ: What does `[]` return with here?
