### PR TITLE
fix: curl import tries to guess the content-type from the body if content-type header is not specified

### LINKED ISSUE #7900: [Bug] when the header is not added to cURL command default must be empty
Steps to reproduce:
1) Add a cURL by removing a header 
2) Click on the import 
and observe

Observation:
It is observed that when the cURL is converted to API by default the header is considered as  "Form URL" even when the data sent is Json and retrieving of data is also not displayed properly. Even on changing the body selection, the data retrieving is. not appropriate 

Expectation:
When the header is not specified by the user we have to allow the user to specify and move the data body to align appropriately.
Possibly we can read the data imported to API and specify appropriate data section 

Video:
[LOOM DEMO](https://www.loom.com/share/534c91a990024889ae0b283975f7dc14)

### PR DESCRIPTION
**Pull request by mojtab23**
## Description

Before if the content-type was not specified and there was a body value, curl import (in the new datasource page) was treating the request as form-urlencoded, but now it tries to guess the content-type for the request.
it checks for `x-www-form-urlencoded` or `json` or sends it as raw without any content-type header.

Fixes #7900

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested manually
- Unit tests are fixed for it

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java [hunk 1]
```diff
@@ -311,33 +311,24 @@ public void testUrlEncodedData() throws AppsmithException {
         );
         assertMethod(action, HttpMethod.POST);
         assertUrl(action, "http://loc");
-        assertEmptyBody(action);
-        assertBodyFormData(
-                action,
-                new Property("", "all of this exactly, but url encoded ")
-        );
+        assertBody(action,"all of this exactly, but url encoded ");
```
Comment (leotom2000) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java:314]: Code formatting is expected, may be some automation tool can discover it later
Seems code formatting is not done, pls. do

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java [hunk 2]
```diff
@@ -311,33 +311,24 @@ public void testUrlEncodedData() throws AppsmithException {
...
                 "curl --data-urlencode 'spaced name=all of this exactly, but url encoded' http://loc"
         );
         assertMethod(action, HttpMethod.POST);
         assertUrl(action, "http://loc");
-        assertEmptyBody(action);
-        assertBodyFormData(
-                action,
-                new Property("spaced name", "all of this exactly, but url encoded")
-        );
+        assertBody(action,"spaced name=all of this exactly, but url encoded");
```
Comment (leotom2000) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java:322]: a space before and after = will be good, 
seems it is not going to affect the functionality
(in other similar places too )

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java [hunk 3]
```diff
@@ -311,33 +311,24 @@ public void testUrlEncodedData() throws AppsmithException {
...
                 "curl --data-urlencode 'awesome=details, all of this exactly, but url encoded' http://loc"
         );
         assertMethod(action, HttpMethod.POST);
         assertUrl(action, "http://loc");
-        assertEmptyBody(action);
-        assertBodyFormData(
-                action,
-                new Property("awesome", "details, all of this exactly, but url encoded")
-        );
+        assertBody(action,"awesome=details, all of this exactly, but url encoded");
```
Comment (leotom2000) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java:330]: space around equal,
leave it if affects the intended meaning

**Review by leotom2000 — COMMENTED** [review]
Few Code formatting issues, check for similar issues in other places too you modified

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java (hunk 1 above)
Comment (mojtab23) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java]: I fixed this in the new commit.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java (hunk 2 above)
Comment (mojtab23) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java]: I can't do this because it's related to the code and business logic (form-urlencoded). I think it's better to keep it like this.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java (hunk 3 above)
Comment (mojtab23) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java]: I can't do this because it's related to the code and business logic (form-urlencoded). I think it's better to keep it like this.

**Review by leotom2000 — APPROVED** [review]
