### PR TITLE
fix: plugins not loaded during onboarding issue fixed

### LINKED ISSUE #29784: [Bug]: Start with data onboarding -> Plugins not loaded
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I login with appsmith email domain, I see onboarding flow, When I click on start with data plugins are not getting loaded

https://theappsmith.slack.com/archives/C05P3ME9MBR/p1703035861780029

### Steps To Reproduce

1. Login with appsmith email domain
2. During onboarding flow, select start with data
3. Observe the error

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/ Self-Hosted - 1.9.53

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes issue of plugins not being seen on datasources page during onboarding: https://theappsmith.slack.com/archives/C05P3ME9MBR/p1703035861780029

**Root cause:**
The issue occurs because workspaceId is not present when we make an API call to fetch all plugins. WorkspaceId comes from an API `applications/new` and this API is called once we answer following onboarding questions
Screenshot 2023-12-21 at 3 49 24 PM

Now If the API call gets completed before we select start with data options, we get workspaceId and we are able to proceed ahead to fetch plugins, but if this API call is not completed by the time we select start with data, workspace id not available hence we dont see any plugins.

**Solution:**
To make sure that we do not face such issue and we always workspace Id available before we show 3 onboarding options, I have added a condition of workspace Id for loading the component which shows 3 options, this way 3 options will be shown only if workspace id is available, meaning only if above API call is complete.

#### PR fixes following issue(s)
Fixes #29784 
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
  - Conditional display of the 'Create New Apps' option based on workspace selection.

- **Refactor**
  - Enhanced `ApplicationProps` interface to include `currentWorkspaceId`.

- **Style**
  - Visual updates to the 'Applications' page when creating new applications.

### CODE REVIEW

File: app/client/src/ce/pages/Applications/index.tsx [hunk 1]
```diff
@@ -854,12 +856,16 @@ export class Applications<
...
+      // Workspace id condition is added to ensure that we have workspace id present before we show 3 options
+      // as workspace id is required to fetch plugins
+      !!this.props.currentWorkspaceId ? (
+        <CreateNewAppsOption
+          currentApplicationIdForCreateNewApp={
+            this.props.currentApplicationIdForCreateNewApp
+          }
+          onClickBack={this.props.resetCurrentApplicationIdForCreateNewApp}
+        />
+      ) : null
```
Comment (AmanAgarwal041) [inline app/client/src/ce/pages/Applications/index.tsx:868]: Shouldn't we show some kind of loader ? Why because seeing the video attached for the issue seems like it takes time to load the plugins and it would be better if the user sees the loader instead of blank screen.

Comment (sneha122) [reply app/client/src/ce/pages/Applications/index.tsx:868]: Yes yes we should have a loader for plugins, but I believe we have a separate issue for that in sprint backlog, so can we take that up separately?

**Comment by AmanAgarwal041** [comment]
@sneha122 Tested the PR for 2-3 new users to see the start with data flow, the plugins are available everytime. Is there any way to replicate the previous issue ?

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by sneha122** [comment]
> @sneha122 Tested the PR for 2-3 new users to see the start with data flow, the plugins are available everytime. Is there any way to replicate the previous issue ?

It used to happen when you would quickly fill the profiling questions and quickly click on start with data, this way the API which fetches workspace Id was not complete and we wouldn't have workspace Id to fetch plugins. Now you wont be able to replicate the issue, but you can try these steps as fast as you can and see if plugins load or not

**Comment by AmanAgarwal041** [comment]
> > @sneha122 Tested the PR for 2-3 new users to see the start with data flow, the plugins are available everytime. Is there any way to replicate the previous issue ?
> 
> It used to happen when you would quickly fill the profiling questions and quickly click on start with data, this way the API which fetches workspace Id was not complete and we wouldn't have workspace Id to fetch plugins. Now you wont be able to replicate the issue, but you can try these steps as fast as you can and see if plugins load or not

Works fine. Not able to reproduce the issue. Hence, Adding `skip-testPlan` label.
