### PR TITLE
fix: For git connected apps duplicate should use default branch resources

### LINKED ISSUE #13186: [Bug]: The duplicated application has a master branch details instead of default branch
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The duplicated application has a master branch details instead of default branch 

### Steps To Reproduce

1. Connect the application to the git
2. now create a new branch
3. From git hub change the default branch to the newly created branch b1
4. Now come back to the application sync the branch
5. now master branch will be removed as a default branch
6. Now go to the home page
7. duplicate the application
8. The duplicated application has the details of master branch instead of default branch

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> For git connected application user can update the default branch. When the user updated the default branch clone service should use the default branched application not the original(appsmith default) application.

Fixes #13186 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Junit Tests
- Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java [hunk 1]
```diff
@@ -659,6 +660,20 @@ private Mono<PageDTO> clonePageGivenApplicationId(String pageId, String applicat
     public Mono<Application> cloneApplication(String applicationId, String branchName) {
 
         Mono<Application> applicationMono = applicationService.findByBranchNameAndDefaultApplicationId(branchName, applicationId, MANAGE_APPLICATIONS)
+                .flatMap(application -> {
+                    // For git connected application user can update the default branch
+                    // In such cases we should fork the application from the new default branch
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java:665]: Typo : fork => clone

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java [hunk 2]
```diff
@@ -659,6 +660,20 @@ private Mono<PageDTO> clonePageGivenApplicationId(String pageId, String applicat
...
+                    if(StringUtils.isEmpty(branchName)
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java:666]: We have a expectation that client will always send the `branchName` in the request header if the app is connected to git. Any reason why we are checking if this is empty?

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java:666]: We should not fetch the default branch resource if the branchName is already present. Because that clearly means the client is requesting data for that branch resource. 
FYI, client does not send branchName at the movement.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java [hunk 3]
```diff
@@ -1760,6 +1760,64 @@ public void cloneApplication_withDeletedActionInActionCollection_deletedActionIs
...
+                    gitApplicationMetadata.setGitAuth(gitAuth);
+                    application1.setGitApplicationMetadata(gitApplicationMetadata);
+                    return applicationService.save(application1);
+                }).block();
+
+        // Add a branch to the git connected app
+        application = new Application();
+        application.setName("cloneGitConnectedApplication_withUpdatedDefaultBranch_sucess");
+        application.setOrganizationId(orgId);
+        Mono<Application> forkedApp = applicationPageService.createApplication(application)
```
Comment (abhvsn) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java:1789]: Should we rename this to clonedApp

**Review by abhvsn — APPROVED** [review]
LGTM
