### PR TITLE
fix: Add support for xls,json,tsv file types in file widget

### LINKED ISSUE #17946: [Feature]: Filepicker to support parsing xls, tsv, json along with csvs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Filepicker widget can automatically parse the following filetypes and convert them to arrays and objects

### Why should this be worked on?

Simplifies the workflows for users

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #17946

This PR adds support for parsing XLS,XLSX, TSV, JSON and CSV files in file widget v2.

#### Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

#### How Has This Been Tested?
- [x] Manual
- [x] Cypress
>

### Test Plan
https://github.com/appsmithorg/TestSmith/issues/2411

1. Import xls, xlsx, json, tsv, csv file.
2. Import a large file > 1 MB, > 5 MB to test the feature.
3. Import file types of text,binary and base64 to test existing functionality since the whole importing code has been refactored.

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### CODE REVIEW

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 1]
```diff
@@ -29,15 +29,11 @@ import FilePickerComponent from "../component";
...
-const CSV_ARRAY_LABEL = "Array (CSVs only)";
-const CSV_FILE_TYPE_REGEX = /.+(\/csv)$/;
-
-const ARRAY_CSV_HELPER_TEXT = `All non csv filetypes will have an empty value. \n Large files used in widgets directly might slow down the app.`;
+const CSV_ARRAY_LABEL = "Array of Objects (CSV, XLSX(X), JSON, TSV)";
 
-const isCSVFileType = (str: string) => CSV_FILE_TYPE_REGEX.test(str);
-
-type Result = string | Buffer | ArrayBuffer | null;
+const ARRAY_CSV_HELPER_TEXT = `All non CSV, XLS(X), JSON or TSV filetypes will have an empty value. \n Large files used in widgets directly might slow down the app. Read more`;
```
Comment (keyurparalkar) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:36]: Does the `Read more` keyword point to an actual link?

**Review by keyurparalkar — DISMISSED** [review]

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx (hunk 1 above)
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:36]: I have to remove Read More. It is not part of the scope as discussed with @dilippitchika . It will done as a separate task for all widgets together.

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+import log from "loglevel";
+import Excel from "exceljs";
+
+function parseFileData(
+  data: Blob,
+  type: FileDataTypes,
+  fileType: string,
+  extension: string,
+  dynamicTyping = false,
+): Promise<any> {
```
Comment (sbalaji1192) [inline app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts:12]: Can we use a definitive type here

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts [hunk 3]
```diff
@@ -0,0 +1,184 @@
...
+}
+
+function parseArrayTypeFile(
+  data: Blob,
+  filetype: string,
+  extension: string,
+  dynamicTyping = false,
+): Promise<any[]> {
+  return new Promise((resolve) => {
+    (async () => {
```
Comment (sbalaji1192) [inline app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts:66]: do we need IIFE here? we can make the promise body as async function

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+
+function parseCSVBlob(data: Blob, dynamicTyping = false): Promise<any[]> {
+  return new Promise((resolve) => {
+    const reader = new FileReader();
+    reader.onloadend = () => {
+      try {
+        const result = parseCSVString(reader.result as string, dynamicTyping);
+        resolve(result);
+      } catch (error) {
+        // TODO: show error alert here
```
Comment (sbalaji1192) [inline app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts:147]: remove if not needed

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 5]
```diff
@@ -678,53 +674,39 @@ class FilePickerWidget extends BaseWidget<
...
+            file.data,
+            this.props.fileDataType,
+            file.type || "",
+            file.extension,
+            this.props.dynamicTyping,
+          );
+        } else {
+          data = createBlobUrl(file.data, this.props.fileDataType);
+        }
+
```
Comment (sbalaji1192) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:698]: move the reading logic inside the promise

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts (hunk 4 above)
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts:147]: Resolved.

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx (hunk 1 above)
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:36]: Done

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx (hunk 5 above)
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:698]: Done

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts (hunk 3 above)
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts:66]: I read online. It is documented as an anti-pattern : https://simonjcarr.medium.com/using-async-inside-a-javascript-promise-f32957617d78 ? Couldn't find references of an async body in a promise in our codebase either.

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts (hunk 2 above)
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/FileParsing.ts:12]: Done

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:698]: Done

**Comment by rajatagrawal** [comment]
@somangshu @dilippitchika does this feature need to go part of What's new updates ?

**Comment by somangshu** [comment]
@rajatagrawal yes please

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 6]
```diff
@@ -29,15 +29,11 @@ import FilePickerComponent from "../component";
 import FileDataTypes from "../constants";
 import { DefaultAutocompleteDefinitions } from "widgets/WidgetUtils";
 import type { AutocompletionDefinitions } from "widgets/constants";
+import parseFileData from "./FileParsing";
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx]: Done

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 7]
```diff
@@ -678,42 +674,31 @@ class FilePickerWidget extends BaseWidget<
...
-      const fileReaderPromises = files.map((file, index) => {
+      const fileReaderPromises = files.map(async (file, index) => {
         return new Promise((resolve) => {
-          if (file.size < FILE_SIZE_LIMIT_FOR_BLOBS) {
-            const reader = new FileReader();
-            if (this.props.fileDataType === FileDataTypes.Base64) {
-              reader.readAsDataURL(file.data);
-            } else if (this.props.fileDataType === FileDataTypes.Binary) {
-              reader.readAsBinaryString(file.data);
+          const parseFile = async () => {
```
Comment (sbalaji1192) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:686]: can we just make this a iffe and move the entire body inside here?

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.ts [hunk 8]
```diff
@@ -0,0 +1,182 @@
...
+      workbook.SheetNames.forEach((sheetName) => {
+        const sheetData: ExcelSheetData = { name: "", data: [] };
+        try {
+          const data = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {
+            header: 1,
+          });
+          sheetData["name"] = sheetName;
+          sheetData["data"] = data;
+          sheetsData.push(sheetData);
+        } finally {
```
Comment (sbalaji1192) [inline app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.ts:126]: we don't need this finally here.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/Filepicker/FilePickerV2_CSV_spec.js [hunk 9]
```diff
@@ -33,15 +36,86 @@ describe("File picker widget v2", () => {
...
     cy.get(
       `.t--widget-tablewidgetv2 .tbody .td[data-rowindex=${1}][data-colindex=${3}] input`,
     ).should("not.be.checked");
+    cy.get(".uppy-Dashboard-Item-action--remove").click({ force: true });
+
+    // Test for XLSX file
+    cy.get(commonlocators.filePickerInput)
+      .first()
+      .attachFile("TestSpreadsheet.xlsx");
+    cy.wait(3000);
```
Comment (sbalaji1192) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/Filepicker/FilePickerV2_CSV_spec.js:53]: Can you just mention here and below that we're waiting for the file to get uploaded

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.test.tsx [hunk 10]
```diff
@@ -0,0 +1,210 @@
...
+          ["r2a", "r2b", "r2c"],
+          ["r3a", "r3b", "r3c"],
+        ],
+        name: "Sheet1",
+      },
+    ];
+    expect(result).toStrictEqual(expectedResult);
+  });
+
+  it.only("parses xls file correctly", async () => {
```
Comment (sbalaji1192) [inline app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.test.tsx:122]: remove only

Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.test.tsx:122]: Done. Thanks for pointing out.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/Filepicker/FilePickerV2_CSV_spec.js (hunk 9 above)
Comment (rajatagrawal) [reply app/client/cypress/e2e/Regression/ClientSide/Widgets/Filepicker/FilePickerV2_CSV_spec.js:53]: Done

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.ts (hunk 8 above)
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.ts:126]: The ts compiler throws a compilation error without a catch/finally block

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx (hunk 7 above)
Comment (rajatagrawal) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:686]: Done

**Comment by rajatagrawal** [comment]
@sbalaji1192 I have fixed the review feedback. You can review the changes. Thanks!

File: app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.ts (hunk 8 above)
Comment (sbalaji1192) [reply app/client/src/widgets/FilePickerWidgetV2/widget/FileParser.ts:126]: Let's use catch otherwise no purpose in using the try block.

**Review by sbalaji1192 — COMMENTED** [review]
Just had one comment

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Observations @rajatagrawal :
- Filepicker doesn't show it's file count on uploading csv,tsv & json files
https://www.loom.com/share/30cff6b76b77491ab02524f28a96b0ee

- Because of above issue, i can't see csv files are getting uploaded either (same works fine on prod)
 https://www.loom.com/share/7d1d0360494b4e29b470d04da7cec335

- Rename file type typo to XLS(X) as discussed

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Verified all callouts
- Tested existing Supported filetypes
- Tested newly added supported filetypes

**Comment by sbalaji1192** [comment]
@somangshu It's been marked as flaky and has been temporarily skipped. @vsvamsi1 has already opened a PR and running tests.
@rajatagrawal Can you rebase with latest release and run the tests again?
