### PR TITLE
fix: google sheets query getting executed even after changing sheet

### LINKED ISSUE #36747: [Bug]: Unauthorised Google Sheets data visible after app import
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- While importing an app, when I authorise a specific sheet for the Google Sheets datasource and go to the app, I am able to view data from a sheet that was not selected during the authorisation process.

### Steps To Reproduce

1. Import this app: [OldApp_DSTesting1.9.24 (1).json](https://github.com/user-attachments/files/17289810/OldApp_DSTesting1.9.24.1.json)
2. Authorise the Google sheet datasource & select any sheet.
3. Click on `Go to application`.
4. Now go to the page that runs a query form the above authorised datasource.

**Expected:** Data inside the selected sheet only should be visible upon binding the query with widgets.
**Actual:** We are able to see data from sheets that have not been selected.

### Public Sample App

_No response_

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/31e5e918-29d5-4d23-b99a-60c402d23e6b

### Version

Cloud

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes the issue with google sheets -> selected sheets option.  Following are the steps to reproduce the issue on cloud/release platform:

**Steps:**
1. Create a Google sheets datasource with selected sheets option
2. Select "spreadsheet1" from the file picker.
3. Create a query for this datasource and attach it to table widget
4. Now edit the datasource and change authorisation from "spreadsheet1" to "spreadsheet2"
5. Refresh the page and check the table data

This issue has been fixed, where we check if the correct spreadsheetId is present in authorisedSheetIds, if it's not throwing an exception so we don't execute the query.

Fixes #36747   
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11473463879>
> Commit: e0f725a6246ff849c8666d5a34e6cf016111cf0f
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11473463879&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Sanity`
> Spec:
> <hr>Wed, 23 Oct 2024 05:43:59 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new error message for missing spreadsheet URLs to enhance user guidance.
	- Updated method for retrieving authorized sheet IDs to include validation, improving error handling.

- **Bug Fixes**
	- Enhanced error handling for cases where the spreadsheet URL is invalid or missing.

- **Tests**
	- Added new test cases to validate the updated functionality for authorized sheet IDs, ensuring robust error handling and correct returns.

### CODE REVIEW

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/constants/ErrorMessages.java [hunk 1]
```diff
@@ -39,6 +39,9 @@ public class ErrorMessages extends BasePluginErrorMessages {
 
     public static final String MISSING_ROW_INDEX_ERROR_MSG = "Missing required field 'Row index'";
 
+    public static final String MISSING_SPREADSHEET_URL_SELECTED_SHEETS_ERROR_MSG =
+            "Missing required field 'Spreadsheet Url', Check if your datasource is authorised to use this spreadsheet or not";
```
Comment (NilanshBansal) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/constants/ErrorMessages.java:43]: Nit: Can we please update this message to `"Missing required field 'Spreadsheet Url'. Please check if your datasource is authorized to use this spreadsheet."`

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java [hunk 2]
```diff
@@ -33,9 +39,23 @@ public static Set<String> getUserAuthorizedSheetIds(DatasourceConfiguration data
                     .getProperties()
                     .get(USER_AUTHORIZED_SHEET_IDS_INDEX)
                     .getValue();
-            return new HashSet<String>(temp);
+            userAuthorisedSheetIds = new HashSet<String>(temp);
```
Comment (NilanshBansal) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java:42]: @sneha122 Can we create and assign the userAuthorisedSheetIds here only
`Set<String> userAuthorisedSheetIds = new HashSet<String>(temp);` as coderabbit also requested https://github.com/appsmithorg/appsmith/pull/37006/files#r1810342592

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java [hunk 3]
```diff
@@ -33,9 +39,23 @@ public static Set<String> getUserAuthorizedSheetIds(DatasourceConfiguration data
...
+
+            // This is added specifically for selected gsheets, so that whenever authorisation changes from one sheet to
```
Comment (NilanshBansal) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java:44]: @sneha122 please correct me if my understanding is not right here.
Since we are selectively throwing error here by comparing the selected sheet ID but the scope sent to google is still  `drive.file` scope which grants access to all sheets. Is there a way we can restrict the access using scope which is more secure way as the token also is restricted to access other sheets?

Comment (sneha122) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java:44]: @NilanshBansal You are partially correct here, drive.file scope grants access to all sheets selected so far and not all sheets from the drive and yes I agree restricting it via the token itself is more secure way but unfortunately drive.file allows us access to all sheets selected so far and to make the distinction of which sheet was selected for which datasource, we store the authorisedSheetIds

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/SheetsUtilTest.java [hunk 4]
```diff
@@ -47,7 +48,92 @@
         propList.add(prop2);
 
         dsConfig.setProperties(propList);
-        Set<String> result = SheetsUtil.getUserAuthorizedSheetIds(dsConfig);
+        Set<String> result = SheetsUtil.validateAndGetUserAuthorizedSheetIds(dsConfig, null);
         assertEquals(result.size(), 1);
```
[the remark this answers is not in the document]
Comment (sneha122) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/SheetsUtilTest.java:52]: Will make this change, thank you

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java (hunk 2 above)
Comment (NilanshBansal) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java:42]: @sneha122 can we create and initialize the `userAuthorisedSheetIds` here only as it is not used anywhere above.
`Set<String> userAuthorisedSheetIds = new HashSet<String>(temp);`
Also, please check [this](https://github.com/appsmithorg/appsmith/pull/37006/files#r1810342592) comment from coderabbit which also can be resolved with this change

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/SheetsUtilTest.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (NilanshBansal) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/SheetsUtilTest.java:52]: cc: @sneha122

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java (hunk 2 above)
Comment (sneha122) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java:42]: I will have to check how we are consuming the userAuthorisedSheetIds and if there are any further checks which expects null value and based on that will update the initialisation to empty set. Does that sound good?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java (hunk 3 above)
Comment (NilanshBansal) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java:44]: @sneha122 Thanks for the clarification. Resolving this comment!

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java [hunk 5]
```diff
@@ -17,8 +21,10 @@ public class SheetsUtil {
     private static final String FILE_SPECIFIC_DRIVE_SCOPE = "https://www.googleapis.com/auth/drive.file";
     private static final int USER_AUTHORIZED_SHEET_IDS_INDEX = 1;
 
-    public static Set<String> getUserAuthorizedSheetIds(DatasourceConfiguration datasourceConfiguration) {
+    public static Set<String> validateAndGetUserAuthorizedSheetIds(
+            DatasourceConfiguration datasourceConfiguration, MethodConfig methodConfig) {
         OAuth2 oAuth2 = (OAuth2) datasourceConfiguration.getAuthentication();
+        Set<String> userAuthorisedSheetIds = null;
```
[the remark this answers is not in the document]
Comment (sneha122) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java:27]: This is done intentionally to use the null check when this variable is getting consumed

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java (hunk 2 above)
Comment (sneha122) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java:42]: I have done this intentionally, setting this as null as this is being used https://github.com/appsmithorg/appsmith/blob/a8da0e1e7232403665defdcd528aa93070b04b99/app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java#L44. As discussed on call, will keep this implementation as is.

**Review by NilanshBansal — APPROVED** [review]

**Comment by rohan-arthur** [comment]
waiting to run the specific gsheets tests workflow to ensure no expensive breakages in later stages

**Comment by sneha122** [comment]
Triggered the workflow here: https://github.com/appsmithorg/appsmith/actions/runs/11482943399

**Comment by sneha122** [comment]
All google sheets test cases have passed in the workflow, we should be good to merge the PR
