### PR TITLE
fix: this.params shows error in IIFE

### LINKED ISSUE #6732: [Bug] this.params shows an error in IIFE
### Steps to reproduce the behaviour:

1. Create an API
2. Create a new parameter that has an IIFE which returns a value from `this.params`
`(function() { return this.params.name })()` (also test with arrow function)
3. TypeError: cannot read params of undefined
image

Note: When a param is passed @`Api.run({ name: "abcd" })`, it is successfully passed to the server.

### PR DESCRIPTION
**Pull request by ravikp7**
## Description
This fixes the issue where using `this.params` in an IIFE function in API query params showed error.

**How does this PR fix the issue?**
The PR adds an empty object as `params` in the global `this` context. So that `this.params` doesn't evaluate to `undefined`.

Fixes #6732

Media
Screenshot 2023-04-25 at 12 59 36 AM

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { agHelper, apiPage, locators } = _;
+
+describe("this.params in IIFE function in API editor", () => {
+  it("1. this.params should be available in IIFE function in API editor", () => {
+    apiPage.CreateApi("Api1", "GET");
+
+    _.agHelper.GetNClick(_.locators._paramsTab);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:9]: _.apiPage.SelectPaneTab("Params"); - to be used. Also remove the associated new locator created.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+    cy.get(locators._queryParamsKey(0)).then(($el) => {
+      agHelper.UpdateCodeInput($el, "page");
+    });
+
+    cy.get(locators._queryParamsValue(0)).then(($el) => {
+      agHelper.UpdateCodeInput(
+        $el,
+        "{{(function () { return this.params.key; })()}}",
+      );
+    });
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:19]: Check if _.apiPage.EnterParams() can be used here.

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:19]: If can be used, remove newly created locators.

File: app/client/src/workers/common/DataTreeEvaluator/index.ts [hunk 3]
```diff
@@ -942,9 +942,27 @@ export default class DataTreeEvaluator {
 
             const contextData: EvaluateContext = {};
             if (isAction(entity)) {
+              const evaluatedExecutionParams = this.getDynamicValue(
+                `{{${JSON.stringify(
+                  (entity.config.queryParameters &&
+                    entity.config.queryParameters[0]) ||
+                    {},
+                )}}}`,
```
Comment (arunvjn) [inline app/client/src/workers/common/DataTreeEvaluator/index.ts:950]: This is not the solution. You could put the same binding in API headers and replicate the issue

**Review by arunvjn — CHANGES_REQUESTED** [review]

**Review by Aishwarya-U-R — COMMENTED** [review]
The attached bug also talks about arrow function. Can we please include script for that also?

**Comment by ravikp7** [comment]
@Aishwarya-U-R The issue couldn't be replicated for arrow functions.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+    apiPage.EnterParams(
+      "page",
+      "{{(function () { return this.params.key; })()}}",
+      0,
+      false,
+    );
+
+    // the value is evaluated correctly only during execution
+    // in this case, we just want to ensure that this.params is an object and present
+    agHelper.VerifyEvaluatedValue("undefined", false);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:19]: Showing undefined is the bug too. I dint quite get the fix here.

Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:19]: The issue was `this.params` was being evaluated as `undefined` and hence accessing `this.params.something` raised an error `Cannot read properties of undefined`. The fix makes sure that `this.params` is a an empty object to suppress this error. We can't be sure of the exact value of `this.params` here on API editor page as `this.params` is contextual to the invocation, where the API is being called passing the params object.

In the test, we're making sure that the value of `this.params.key` gets evaluated without any errors, and the value will be undefined because `this.params` is an empty object here on this page.

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:19]: Ok, why cant we send some value to this API param & see if its evaluated - instead of undefined?

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:19]: Before fix also it was undefined & after fix also its undefined - makes it confusing.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts [hunk 5]
```diff
@@ -0,0 +1,22 @@
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { apiPage } = _;
+
+describe("this.params in IIFE function in API editor", () => {
+  it("1. this.params should be available in IIFE function in API editor", () => {
```
[the remark this answers is not in the document]
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:6]: @Aishwarya-U-R The spec file name itself mentions the bug id. Is it not enough?

[the remark this answers is not in the document]
Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:6]: File name doesn't show up in search results - in vscode. So a skim of all bug specs file names is needed, which can be visually daunting. Hence.

[the remark this answers is not in the document]
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug6732_Spec.ts:6]: added

File: app/client/src/workers/common/DataTreeEvaluator/index.ts [hunk 6]
```diff
@@ -942,9 +942,15 @@ export default class DataTreeEvaluator {
...
-                params: {},
+              // Add empty object for this.params to avoid undefined errors
+              contextData.globalContext = {
+                [THIS_DOT_PARAMS_KEY]: {},
               };
+
+              unEvalPropertyValue = unEvalPropertyValue.replace(
+                EXECUTION_PARAM_REFERENCE_REGEX,
+                THIS_DOT_PARAMS_KEY,
+              );
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/common/DataTreeEvaluator/index.ts:953]: As params is a valid entity name, the user code with JSObject named `params` might get impacted by the above logic, if in the API body, the user tries to call `params.myFun()` that would not work when API is executed. 

Also, I would suggest replacing it with a key that is already an invalid entity name like `$params` anything starting with `$` is an invalid entity name and hence safe to add to the global context.

Comment (ravikp7) [reply app/client/src/workers/common/DataTreeEvaluator/index.ts:953]: Excellent point. Updated.

Comment (Rishabh-Rathod) [inline app/client/src/workers/common/DataTreeEvaluator/index.ts:953]: Could we please write this logic in a separate helper method and write a jest test to validate for cases mentioned in the PR description here https://github.com/appsmithorg/appsmith/pull/10826

File: app/client/src/workers/common/DataTreeEvaluator/index.ts [hunk 7]
```diff
@@ -942,9 +942,15 @@ export default class DataTreeEvaluator {
 
             const contextData: EvaluateContext = {};
             if (isAction(entity)) {
-              contextData.thisContext = {
-                params: {},
+              // Add empty object for this.params to avoid undefined errors
+              contextData.globalContext = {
+                [THIS_DOT_PARAMS_KEY]: {},
               };
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/common/DataTreeEvaluator/index.ts:948]: As this was the only line in the code base where `thisContext` was used and now we remove it. 

I would suggest for following changes to be done 
1. Let's remove `thisContext` implementation from the codebase which means from `evaluate.ts` and `evaluate.test.ts` 
2. Let's modify the evaluation script to remove `THIS_CONTEXT` 

```js

export const EvaluationScripts: Record<EvaluationScriptType, string> = {
  [EvaluationScriptType.EXPRESSION]: `
  function $$closedFn () {
    const $$result = ${ScriptTemplate}
    return $$result
  }
  $$closedFn()
  `,
  [EvaluationScriptType.ANONYMOUS_FUNCTION]: `
  function $$closedFn (script) {
    const $$userFunction = script;
    const $$result = $$userFunction?.apply(THIS_CONTEXT, ARGUMENTS);
    return $$result
  }
  $$closedFn(${ScriptTemplate})
  `,
  [EvaluationScriptType.ASYNC_ANONYMOUS_FUNCTION]: `
  async function $$closedFn (script) {
    const $$userFunction = script;
    const $$result = $$userFunction?.apply(THIS_CONTEXT, ARGUMENTS);
    return await $$result;
  }
  $$closedFn(${ScriptTemplate})
  `,
  [EvaluationScriptType.TRIGGERS]: `
  async function $$closedFn () {
    const $$result = ${ScriptTemplate};
    return await $$result
  }
  $$closedFn()
  `,
  [EvaluationScriptType.OBJECT_PROPERTY]: `
  function $$closedFn () {
    const $$result = {${ScriptTemplate}}
    return $$result
  }
  $$closedFn()
  `,
};
```
3. Fix the jest test cases in `evaluate.test.ts`

Comment (ravikp7) [reply app/client/src/workers/common/DataTreeEvaluator/index.ts:948]: @Rishabh-Rathod I'm now wondering what was this being used for earlier.

File: app/client/src/workers/common/DataTreeEvaluator/index.ts (hunk 6 above)
Comment (ravikp7) [reply app/client/src/workers/common/DataTreeEvaluator/index.ts]: @Rishabh-Rathod Added

File: app/client/src/workers/common/DataTreeEvaluator/index.ts (hunk 7 above)
Comment (ravikp7) [reply app/client/src/workers/common/DataTreeEvaluator/index.ts:949]: We'll take care of this in the `this` refactor being done by Arun

**Review by Rishabh-Rathod — COMMENTED** [review]
Code LGTM.

**Review by Rishabh-Rathod — APPROVED** [review]

**Comment by ravikp7** [comment]
test comment

**Comment by ravikp7** [comment]
test sha=6ce6113

**Review by ohansFavour — COMMENTED** [review]
Looks good

**Review by arunvjn — APPROVED** [review]
