### PR TITLE
Fixed conversion of Unix timestamp in milliseconds

### LINKED ISSUE #2199: [Bug] Table's DateTime data type does not work
## Description

Appsmith sees DateTIme columns in MSFT SQL Server as int numbers. Even if I try to change the column's datatype in the table widget - it shows weird things (like "year 521234") or complains about invalid date

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add any `SELECT` data query that has a DateTime column in SQL Server
2. Run the query

### Important Details
 - Version: [Cloud]
 - Browser [chrome]

image

### PR DESCRIPTION
**Pull request by vicky-primathon**
Fixed conversation of Unix timestamp in milliseconds

Fixes #2199 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/TableWidget.tsx [hunk 1]
```diff
@@ -239,7 +239,7 @@ class TableWidget extends BaseWidget<TableWidgetProps, WidgetState> {
               let inputFormat;
               try {
                 const type = column.metaProperties.inputFormat;
-                if (type !== "EPOCH" && type !== "Milliseconds") {
+                if (type !== "Epoch" && type !== "Milliseconds") {
```
Comment (mohanarpit) [inline app/client/src/widgets/TableWidget.tsx:242]: This seems like an ideal PR to introduce Jest tests at a widget level. This doesn't require Cypress integration testing, but functional unit testing using Jest. 

Is that possible?

**Review by mohanarpit — APPROVED** [review]
