### PR TITLE
Fix: 404 error page shows server unavailable

### LINKED ISSUE #2192: [Bug] 404 Not Found error shows 500 error page
## Description

When the server returns a 404 Page Not Found error, the UI being shown to the user belongs to the 500 error page. 

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to an invalid link. Eg. https://app.appsmith.com/applications/5f9512190211101faeb4785d/pages/5f9512190211101faeb47851
2. Notice the error page says "Appsmith server not available", while the URL is a 404 error.

The error page should be the 404 error page.

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: MacOSX
 - Browser: All browsers

### PR DESCRIPTION
**Pull request by jsartisan**
The 404 page was showing "Server not unavailable"

## Description

Fixes #2192 

## Type of change

- Bug fix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/AppRouter.tsx [hunk 1]
```diff
@@ -72,14 +72,26 @@ class AppRouter extends React.Component<any, any> {
...
+
     // This is needed for the theme switch.
     changeAppBackground(currentTheme);
     return (
       <Router history={history}>
         <Suspense fallback={loadingIndicator}>
           <AppHeader />
           {safeCrash ? (
-            <ServerUnavailable />
+            <Switch>
```
Comment (mohanarpit) [inline app/client/src/AppRouter.tsx:83]: As part of this change, is it possible to keep the URL the same instead of redirecting to a `/404` URL? I'm asking this so that the user can simply try to refresh the page and access the content again instead of clicking on the button?

Comment (jsartisan) [reply app/client/src/AppRouter.tsx:83]: Yes, It should be fairly easy to do that but I wonder why we changed the URL in the first place.

Comment (jsartisan) [reply app/client/src/AppRouter.tsx:83]: Let me confirm this with Hetu. I think we did that because react-router expects a specific router to render a component.

File: app/client/src/AppRouter.tsx [hunk 2]
```diff
@@ -72,14 +72,26 @@ class AppRouter extends React.Component<any, any> {
...
+                exact
+                path={PAGE_NOT_FOUND_URL}
+                component={PageNotFound}
+              />
+              <SentryRoute
+                exact
+                path={SERVER_ERROR_URL}
+                component={ServerUnavailable}
+              />
+            </Switch>
```
Comment (hetunandu) [inline app/client/src/AppRouter.tsx:94]: You cannot switch based on routes here

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Comment by jsartisan** [comment]
@hetunandu now rendering the page based on error code.

**Comment by hetunandu** [comment]
Please also remove the two routes for 404 and 500 and make sure nothing else in the app tries to navigate to those routes

**Comment by jsartisan** [comment]
> Please also remove the two routes for 404 and 500 and make sure nothing else in the app tries to navigate to those routes

Done.

File: app/client/cypress/integration/Smoke_TestSuite/Pages/Pages_spec.js [hunk 3]
```diff
@@ -26,4 +26,11 @@ describe("Pages", function() {
       expect($x).contain(veryLongPageName);
     });
   });
+
+  it("Checks if 404 is showing correct route", () => {
+    cy.visit("/route-that-does-exit");
```
Comment (jsartisan) [inline app/client/cypress/integration/Smoke_TestSuite/Pages/Pages_spec.js:31]: This will be "route-that-does-not-exist" :P will update it in next commit.

File: app/client/src/utils/AppsmithUtils.tsx [hunk 4]
```diff
@@ -265,7 +263,6 @@ export const retryPromise = (
         setTimeout(() => {
           if (retriesLeft === 1) {
             reject(error);
-            history.replace(SERVER_ERROR_URL);
```
Comment (hetunandu) [inline app/client/src/utils/AppsmithUtils.tsx:268]: set the crash code from here.

File: app/client/src/AppRouter.tsx [hunk 5]
```diff
@@ -54,6 +55,22 @@ function changeAppBackground(currentTheme: any) {
   }
 }
 
+/**
+ * renders error page based on error code
+ *
+ * @param safeCrashCode
+ */
+const renderErrorPage = (safeCrashCode: number | string) => {
+  switch (safeCrashCode) {
```
Comment (hetunandu) [inline app/client/src/AppRouter.tsx:64]: Let us make a proper enum for this safeCrashCode and use that to keep this maintainable

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/constants/ApiConstants.tsx [hunk 6]
```diff
@@ -15,6 +15,13 @@ export enum API_STATUS_CODES {
   REQUEST_NOT_AUTHORISED = 401,
   RESOURCE_NOT_FOUND = 404,
   SERVER_ERROR = 502,
+  SERVER_UNAVAILABLE = 503,
+}
+
+export enum ERROR_CODES {
+  PAGE_NOT_FOUND = 404,
+  SERVER_ERROR = 502,
+  REQUEST_TIMEOUT = "ECONNABORTED",
```
Comment (hetunandu) [inline app/client/src/constants/ApiConstants.tsx:24]: Keeps it separate from API level codes
```suggestion
export enum ERROR_CODES {
  PAGE_NOT_FOUND = "PAGE_NOT_FOUND",
  SERVER_ERROR = "SERVER_ERROR",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
```

File: app/client/src/sagas/InitSagas.ts [hunk 7]
```diff
@@ -144,6 +163,13 @@ export function* initializeAppViewerSaga(
   if (resultOfPrimaryCalls.failure) {
     yield put({
       type: ReduxActionTypes.SAFE_CRASH_APPSMITH,
+      payload: {
+        code: get(
+          resultOfPrimaryCalls,
+          "failure.payload.error.code",
+          API_STATUS_CODES.SERVER_ERROR,
```
Comment (hetunandu) [inline app/client/src/sagas/InitSagas.ts:170]: Use the error code enum in this file

File: app/client/src/constants/ReduxActionConstants.tsx [hunk 8]
```diff
@@ -430,6 +430,7 @@ export interface ReduxActionWithPromise<T> extends ReduxAction<T> {
 export interface ReduxActionErrorPayload {
   message: string;
   source?: string;
+  code?: number | string;
```
Comment (hetunandu) [inline app/client/src/constants/ReduxActionConstants.tsx:433]: Use the error code here

File: app/client/src/api/Api.tsx [hunk 9]
```diff
@@ -67,6 +68,7 @@ axiosInstance.interceptors.response.use(
       return Promise.reject({
         ...error,
         message: SERVER_API_TIMEOUT_ERROR,
+        code: ERROR_CODES.REQUEST_TIMEOUT,
```
Comment (hetunandu) [inline app/client/src/api/Api.tsx:71]: Use the error code in all promise rejections here

**Review by hetunandu — CHANGES_REQUESTED** [review]
Please refactor properly

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Comment by jsartisan** [comment]
@hetunandu Since we were not rendering the routes in `AppRouter` on `safeCrash`, `history.push` was not working at all in the header on the error page since there were no routes to render. So in the header of the error page, on clicking the logo, I am flushing errors.

**Review by hetunandu — APPROVED** [review]
