### PR TITLE
fix: turned on learnability flags on by default

### LINKED ISSUE #33224: [Task]: Activation flags which are rolled out to 100% turn them to true by default
### SubTasks

https://theappsmith.slack.com/archives/C05P3ME9MBR/p1715050713382359

### PR DESCRIPTION
**Pull request by sneha122**
## Description
For the airgapped testing, we need to remove all the feature flags which are already rolled out to 100% of the users. As part of this task, we have 3 flags in activation/learnability initiatives:
1. rollout_js_enabled_one_click_binding_enabled
2. ab_learnability_ease_of_initial_use_enabled
3. ab_learnability_discoverability_collapse_all_except_data_enabled
4. rollout_remove_feature_walkthrough_enabled

As immediate measure, we are turning default values of these flags to be true, later on we can plan to completely remove the flags from the code.

Fixes #33224 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!CAUTION]
> 🔴 🔴 🔴 Some tests have failed.
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9059739090>
> Commit: e430215c66e067f36b8af04e04e344d6fe15e09e
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9059739090&attempt=3&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank"> Click here!</a>
> The following are new failures, please fix them before merging the PR: <ol>
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/Page_Load_Spec.js </ol>
> To know the list of identified flaky tests - <a href="https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master" target="_blank">Refer here</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: app/client/cypress/support/Objects/FeatureFlags.ts [hunk 1]
```diff
@@ -4,6 +4,8 @@ import produce from "immer";
 
 const defaultFlags = {
   release_side_by_side_ide_enabled: true,
+  ab_learnability_discoverability_collapse_all_except_data_enabled: false, // remove this flag from here when it's removed from code
```
Comment (AmanAgarwal041) [inline app/client/cypress/support/Objects/FeatureFlags.ts:7]: Shouldn't this value be true by default ?

Comment (sneha122) [reply app/client/cypress/support/Objects/FeatureFlags.ts:7]: Yes it should be true by default for normal functioning, but in cypress there are many tests cases which fail if we set this to true, because this flag will collapse all sections except data for table and json form widgets, hence hiding rest of the elements. So when we actually remove this flag from code base we will have to update those tests as well. For now I have simply set it as false, so that test cases continue to work as expected, hope this makes sense!

Comment (AmanAgarwal041) [reply app/client/cypress/support/Objects/FeatureFlags.ts:7]: This is immediately required for airgap testing. Not changing the test cases. Approving the PR.

**Review by AmanAgarwal041 — DISMISSED** [review]

File: app/client/cypress/support/Objects/FeatureFlags.ts (hunk 1 above)
Comment (sneha122) [reply app/client/cypress/support/Objects/FeatureFlags.ts:7]: Yes we are planning to remove these flags and fix test cases in next sprint, this PR is just to unblock the airgap testing as soon as we can

**Review by AmanAgarwal041 — APPROVED** [review]
