### PR TITLE
fix: Fixed test MongoDB datasource shows ok even if there is no database matching the name in the 'Default Database Name' input

### LINKED ISSUE #11214: [Bug]: Test MongoDB datasource shows ok even if there is no database matching the name in the 'Default Database Name' input
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Test MongoDB datasource shows ok even if there is no database matching the name in the 'Default Database Name' input.
as mentioned in item number 4 in this comment https://github.com/appsmithorg/appsmith/issues/5005#issuecomment-1002032009

### Steps To Reproduce

1. Fill a valid MongoDB datasource 
2. Enter the name of a database that doesn't exist in MongoDB in the _Default Database Name_ input.
3. Click the _Test_ datasource button and it shows Ok instead of showing an error that the default database name does not exist.

### Environment

Release

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by mojtab23**
## Description

Test MongoDB datasource shows ok even if there is no database matching the name in the 'Default Database Name' input.

Fixes #11214

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test case [`MongoPluginTest.testDatasourceFailWithInvalidDefaultDatabaseName()`](https://github.com/appsmithorg/appsmith/blob/979bd9b2d066f1ab028001fa8e91827569786698/app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java#L189)  is added
- Tested manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 1]
```diff
@@ -874,23 +873,37 @@ private boolean isHostStringConnectionURI(Endpoint endpoint) {
...
+                        tuple2.getT1().close();
+
+                        // this lambda checks if default database name is valid or not
+                        Document document = tuple2.getT2();
+                        List<Document> databases = document.getList("databases", Document.class);
+                        Optional<Document> defaultDB = databases.stream()
+                                .filter(d -> d.getString("name").trim().equals(defaultDatabaseName))
+                                .findFirst();
+
+                        log.debug("list databases:{}",document.toJson());
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:900]: Can we remove the logging here? We should only log things that will be required for debugging.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 2]
```diff
@@ -874,23 +873,37 @@ private boolean isHostStringConnectionURI(Endpoint endpoint) {
...
         @Override
         public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasourceConfiguration) {
-            final Consumer<Tuple2<MongoClient, Document>> closeClient = tuple -> tuple.getT1().close();
 
             Function<TimeoutException, Throwable> timeoutExceptionThrowableFunction = error -> new AppsmithPluginException(
                     AppsmithPluginError.PLUGIN_DATASOURCE_TIMEOUT_ERROR,
                     "Connection timed out. Please check if the datasource configuration fields have " +
                             "been filled correctly."
             );
+            final String defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:882]: Should we be using `datasourceConfiguration.authentication.databaseName` here instead of `datasourceConfigurations.connection.defaultDatabaseName`?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 3]
```diff
@@ -874,23 +873,37 @@ private boolean isHostStringConnectionURI(Endpoint endpoint) {
...
+                        Document document = tuple2.getT2();
+                        List<Document> databases = document.getList("databases", Document.class);
+                        Optional<Document> defaultDB = databases.stream()
+                                .filter(d -> d.getString("name").trim().equals(defaultDatabaseName))
+                                .findFirst();
+
+                        log.debug("list databases:{}",document.toJson());
+                        if (defaultDB.isEmpty()) {
+                            // value entered in default database name is invalid
+                            return Mono.just(new DatasourceTestResult("Default Database Name is invalid, no database found with this name."));
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:903]: Should we not be throwing an error at this point?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 4]
```diff
@@ -915,7 +927,13 @@ private boolean isHostStringConnectionURI(Endpoint endpoint) {
...
                                                         "Please provide the default database name."));
 
-                                    }).doOnSuccess(closeClient).then(Mono.just(new DatasourceTestResult()))
+                                    })
+                                    .flatMap(tuple2 -> {
+                                        Document document = tuple2.getT2();
+                                        log.debug("list collections:{}",document.toJson());
+                                        return Mono.just(tuple2.getT1());
+                                    })
+                                    .doOnSuccess(MongoClient::close).then(Mono.just(new DatasourceTestResult()))
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:936]: Will the doOnSuccess prevent the connection from closing if the default DB is empty?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 5]
```diff
@@ -904,8 +917,7 @@ private boolean isHostStringConnectionURI(Endpoint endpoint) {
                                 ((MongoCommandException) error).getErrorCodeName().equals("Unauthorized")) {
                             return datasourceCreate(datasourceConfiguration)
                                     .flatMap(mongoClient -> {
-                                        if (datasourceConfiguration.getConnection() != null && datasourceConfiguration.getConnection().getDefaultDatabaseName() != null) {
-                                            final String defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
+                                        if (datasourceConfiguration.getConnection() != null && defaultDatabaseName != null) {
                                             Publisher<Document> result = mongoClient.getDatabase(defaultDatabaseName).runCommand(new Document(
                                                     "listCollections", 1).append("nameOnly", TRUE));
                                             return Mono.zip(Mono.just(mongoClient), Mono.from(result));
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:923]: Instead of zipping the two, you can chain them right here, so you're only left with the connection at the end of this flatMap

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Needs a few changes to the flow, also need confirmation on the field being manipulated.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 1 above)
Comment (mojtab23) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:900]: Sure, I removed the logs.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 2 above)
Comment (mojtab23) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:882]: The problem we try to solve here is to make sure that the _default database name_ field in datasource configuration is valid.  `datasourceConfiguration.authentication.databaseName` is used by mongoDB to verify the credentials, it might be usable if we want to entirely change the process for _testing datasource_. but with this flow I used the correct `databaseName`.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 3 above)
Comment (mojtab23) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:903]: I've tested it manually and it's working as expected. what for replace do you have in mind?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 4 above)
Comment (mojtab23) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:936]: I'm not sure, its behavior will be the same as before. You are right, there is no guarantee to call the client.close() if there is an error.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 5 above)
Comment (mojtab23) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:923]: I'm not sure what to do here. can you help me?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 2 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:882]: Oh I see. In that case we should switch out the `admin` on L#885 with authentication database. I missed this in the previous change during review as well. This is my bad. :)

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 4 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:931]: Can we use a `.then` in that case? This will make sure that the closing happens regardless of the result of the previous flatMap

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 6]
```diff
@@ -904,8 +916,7 @@ private boolean isHostStringConnectionURI(Endpoint endpoint) {
                                 ((MongoCommandException) error).getErrorCodeName().equals("Unauthorized")) {
                             return datasourceCreate(datasourceConfiguration)
                                     .flatMap(mongoClient -> {
-                                        if (datasourceConfiguration.getConnection() != null && datasourceConfiguration.getConnection().getDefaultDatabaseName() != null) {
-                                            final String defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
+                                        if (datasourceConfiguration.getConnection() != null && defaultDatabaseName != null) {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:919]: If getConnection can return a null, we will already have failed at L#882 where you are initializing `defaultDatabaseName`

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 5 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:922]: How are we checking if result is valid here? That is, how do we know is `result` returned with an error?
