### PR TITLE
Fix default value reset issue

### LINKED ISSUE #2848: [Bug] The form gets reset to the wrong value post update
### Steps to reproduce the behavior:
1. Drag a table and bind it to a data set
2. Drag a form and bind the input in it to a column in a table
3. Create a query to update the data and fetch the new results
4. Bind it to the form button
5. Update a data set
6. The value in the form is reset to the wrong value

https://user-images.githubusercontent.com/3897254/106753851-3c4d9180-6652-11eb-9f95-91a28374a9b0.mov

### PR DESCRIPTION
**Pull request by hetunandu**
Fix default value reset issue

Fixes #2848

### CODE REVIEW

File: app/client/src/widgets/MetaHOC.tsx [hunk 1]
```diff
@@ -50,6 +50,25 @@ const withMeta = (WrappedWidget: typeof BaseWidget) => {
       const defaultProperties = WrappedWidget.getDefaultPropertiesMap();
       Object.keys(metaProperties).forEach((metaProperty) => {
         const defaultProperty = defaultProperties[metaProperty];
+        if (prevProps.widgetName === "Input1") {
```
Comment (mohanarpit) [inline app/client/src/widgets/MetaHOC.tsx:53]: This seems like a debug log here. Is this required in the final code?

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 2]
```diff
@@ -944,43 +943,7 @@ function* resetChildrenMetaSaga(action: ReduxAction<{ widgetId: string }>) {
...
-  }
-  const newEvaluatedDataTree = {
-    ...evaluatedDataTree,
-    ...updates,
-  };
-  yield put({
-    type: ReduxActionTypes.SET_EVALUATED_TREE,
-    payload: newEvaluatedDataTree,
-  });
+  // yield call(resetEvaluatedWidgetMetaProperties, childrenIds);
```
Comment (mohanarpit) [inline app/client/src/sagas/WidgetOperationSagas.tsx:946]: Can we remove all commented code?

**Review by Nikhil-Nandagopal — APPROVED** [review]

**Review by mohanarpit — APPROVED** [review]
