### PR TITLE
fix: adding new settings modal

### LINKED ISSUE #30319: CD: New modal for git settings
- Tab: General
- Tab: Branch

### PR DESCRIPTION
**Pull request by brayn003**
## Description
Separates git sync modal from git settings modal

#### PR fixes following issue(s)
Fixes #30319 

#### Type of change
- New feature (non-breaking change which adds functionality)
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Introduced the `GitSettingsModal` for enhanced Git configuration.
	- Added the ability to switch between General and Branch settings tabs within the Git settings modal.
	- Implemented new user permission checks for displaying Git user settings and danger zone sections.

- **Enhancements**
	- Streamlined the Git settings experience by removing unnecessary modals and components.

- **Refactor**
	- Improved action and selector naming for better clarity and maintainability.
	- Adjusted UI components to utilize new Redux state management for Git settings.

- **Style**
	- Updated padding for better visual spacing in Git user settings.

- **Tests**
	- Modified and removed tests to align with the updated component structure and functionality.

- **Bug Fixes**
	- Fixed navigation issues within the Git settings modal by refining action dispatches and state handling.

### CODE REVIEW

File: app/client/src/ce/constants/messages.ts [hunk 1]
```diff
@@ -1110,6 +1110,10 @@ export const UPDATE_DEFAULT_BRANCH_SUCCESS = (branchName: string) =>
   `Updated default branch ${!!branchName ? `to ${branchName}` : ""}`;
 export const CONTACT_ADMIN_FOR_GIT = () =>
   "Please contact your workspace admin to connect your app to a git repo";
+
+export const GENERAL = () => "General";
+export const SETTINGS = () => "Settings";
```
Comment (dipyamanbiswas07) [inline app/client/src/ce/constants/messages.ts:1115]: This already exists, can we reuse?

**Review by dipyamanbiswas07 — APPROVED** [review]
LGTM
