### PR TITLE
datepicker 2 migration 27 added, default response udpated

### LINKED ISSUE #4945: [Bug] Safari -By default Min and Max Date field are highlighted in red with Invalid date message when Datepicker widget is dragged and dropped
## Description
Release Frozen - Its is observed that by dragging and dropping datepicker widget the min and max field shows invalid and highlighted in red.

**Expected Result:**
Dragging and dropping Date-picker should not throw any error

**Actual Result:**
Dragging and Dropping Date Picker the min and max date field shows invalid and highlighted in red.

### Steps to reproduce the behaviour:
1.Launch Appmsith app in release frozen environment in Safari
2. Drag and Drop DatePicker widget and observe 

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
Screenshot 2021-06-07 at 9 45 33 AM

- Environment [Release Frozen]

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

>  add iso date formate for default min and max date and add migration script for change default min and max date for already exists component

Fixes #4945 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: bug/date-picker-iso-migration 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.81 **(-0.02)** | 35.78 **(-0.02)** | 32.41 **(-0.03)** | 54.39 **(-0.02)**
 :red_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 63.87 **(-1.43)** | 57.32 **(-1.32)** | 53.49 **(-2.46)** | 63.1 **(-1.48)**</details>

### CODE REVIEW

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 1]
```diff
@@ -785,12 +785,34 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
...
   }
 
   return currentDSL;
 };
 
+const migrateDatePickerMinMaxDate = (
+  currentDSL: ContainerWidgetProps<WidgetProps>,
+) => {
+  if (
+    currentDSL.type === WidgetTypes.DATE_PICKER_WIDGET2 &&
```
Comment (riodeuno) [inline app/client/src/utils/WidgetPropsUtils.tsx:803]: @techbhavin This does not go into the children. the first `currentDSL` here will be the `widgetId: "0"` entry, which will never be a datepicker widget. We need to add a recursion here for the `currentDSL.children`. Please check out the other migrations.

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 2]
```diff
@@ -785,12 +785,41 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
...
+      currentDSL.minDate = "1920-12-31T18:30:00.000Z";
+    }
+    if (currentDSL.maxDate === "2041-12-31 23:59") {
+      currentDSL.maxDate = "2121-12-31T18:29:00.000Z";
+    }
+  }
+  if (currentDSL.children && currentDSL.children.length) {
+    currentDSL.children.forEach(
+      (eachWidgetDSL: ContainerWidgetProps<WidgetProps>) => {
+        migrateDatePickerMinMaxDate(eachWidgetDSL);
```
Comment (riodeuno) [inline app/client/src/utils/WidgetPropsUtils.tsx:816]: Does this function mutate the DSL in the argument? If this is not mutating, but returning, then this won't work. We will need to use `map` instead of `forEach`

Comment (riodeuno) [inline app/client/src/utils/WidgetPropsUtils.tsx:816]: Does this function mutate the DSL in the argument? If this is not mutating, but returning, then this won't work. We will need to use `map` instead of `forEach`

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Comment by vivekverma2312** [comment]
@techbhavin Please rebuild the deploy preview after taking latest pull from release branch. Currently we are not able to open applications on safari due to issue #5480

**Review by somangshu — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@somangshu Verified this and working as expected

File: app/client/src/utils/WidgetPropsUtils.tsx (hunk 2 above)
Comment (riodeuno) [reply app/client/src/utils/WidgetPropsUtils.tsx:819]: I believe this function is mutating, as we have confirmed that this migration is working. So we have two options. We revert back to `forEach` as it is mutating, or continue using `map` and not assume that this function will always mutate the DSL.

``` 
currentDSL.children = currentDSL.children.map(
      (eachWidgetDSL: ContainerWidgetProps<WidgetProps>) => {
        return migrateDatePickerMinMaxDate(eachWidgetDSL);
      },
    );

**Review by riodeuno — APPROVED** [review]
