### PR TITLE
fix: Auto-suggestion is not working for progress widget while binding

### LINKED ISSUE #12647: [Bug]: Auto-suggestion is not working for progress widget while binding
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Observation 1: Auto-suggestion is not coming while binding
Observation 2: Now `Progress1.progress` is not functional. It has been changed to `Progress1.value`

https://watch.screencastify.com/v/MrAi0zeMMqfoMyj42Coo

### Steps To Reproduce

1. Drag and drop a Progress widget
2. Drag and drop a text widget
3. Try to bind the Progress widget with text widget
4. Observe that auto suggestion is not displayed

Observation 2:

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
Add a missing Cypress test case to demonstrate the auto suggestion

Fixes #12647 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/12647-progress-add-cypress-test 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.35 **(0)** | 37.8 **(0.01)** | 35.96 **(0)** | 56.57 **(0)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**</details>

### CODE REVIEW

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Progress_spec.js [hunk 1]
```diff
@@ -1,10 +1,13 @@
...
 
 describe("Progress Widget", function() {
-  it("Add a new Progress widget", function() {
+  it("Add a new Progress widget and text widget", function() {
     cy.get(explorer.addWidget).click();
     cy.dragAndDropToCanvas("progresswidget", { x: 300, y: 300 });
     cy.get(".t--widget-progresswidget").should("exist");
+    cy.dragAndDropToCanvas("textwidget", { x: 300, y: 500 });
+    cy.openPropertyPane("textwidget");
+    cy.updateCodeInput(".t--property-control-text", "");
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Progress_spec.js:10]: I don't think we need this line. its empty string by default

Comment (sbalaji1192) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Progress_spec.js:10]: oops. My bad. ignore the that comment .

**Review by sbalaji1192 — APPROVED** [review]
