### PR TITLE
fix: Support repo url conversion for all top level domains

### LINKED ISSUE #11644: [Bug]: Only .com and .org Git-Servers can be used
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I enter a valid ssh-git-url as new repository, which is not github.com or gitlab.org (e.g. git@git.something**.ch**:user/something/showcases/testrepo.git) the check will fail within the backend, due to the restriction in the regex here: https://github.com/appsmithorg/appsmith/blob/f610033240bea09c3db4dfb4dcbd29d517b6b1b5/app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java#L30

with error 

java.net.MalformedURLException: Error at index 0 in: "user"
	at java.base/java.net.URL.<init>(URL.java:679)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at com.appsmith.server.helpers.GitUtils.isRepoPrivate(GitUtils.java:61)
	at com.appsmith.server.services.ce.GitServiceCEImpl.connectApplicationToGit(GitServiceCEImpl.java:638)

My suggestion is to replace the regex with the following, which allows all possible toplevel-domains: 

`sshUrl.replaceFirst("(\\.[a-z]*):", "$1/");`

### Steps To Reproduce

1. Go to any application, hit "connect git"
2. Enter a git-url wich does not end with .com or .org (e.g. git@git.something**.ch**:user/something/showcases/testrepo.git)
3. Go to Backend-Logs and find error

### Environment

Production

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> We only support git urls ending with .com or .org at the movement. This PR adds support for all valid top level domains. 

Fixes #11644 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally
- JUnit tests

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java [hunk 1]
```diff
@@ -761,6 +761,52 @@ public void connectApplicationToGit_toggleAccessibilityToPublicForConnectedApp_c
...
+                .create(applicationMono)
+                .assertNext(application -> {
+                    GitApplicationMetadata gitApplicationMetadata1 = application.getGitApplicationMetadata();
+                    assertThat(gitApplicationMetadata1.getRemoteUrl()).isEqualTo(gitConnectDTO.getRemoteUrl());
+                    assertThat(gitApplicationMetadata1.getBranchName()).isEqualTo("defaultBranchName");
+                    assertThat(gitApplicationMetadata1.getGitAuth().getPrivateKey()).isNotNull();
+                    assertThat(gitApplicationMetadata1.getGitAuth().getPublicKey()).isNotNull();
+                    assertThat(gitApplicationMetadata1.getGitAuth().getGeneratedAt()).isNotNull();
+                    assertThat(gitApplicationMetadata1.getRepoName()).isEqualTo("testRepo");
+                    assertThat(gitApplicationMetadata1.getDefaultApplicationId()).isEqualTo(application.getId());
```
Comment (abhvsn) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java:805]: Instead of writing a testcase here can we have a seperate testcase just to test different extensions in `gitUtilsTests.java`

**Comment by abhvsn** [comment]
Minor comment but LGTM

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java (hunk 1 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java:805]: That would require adding tests for all the methods. I will take it up in a different PR just tests.

Comment (abhvsn) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java:805]: Can we atleast add the `browserSupportedUrl` check in this PR then? Also, any harm in doing the testcases for other methods as this will increase our test coverage and this change will anyway go in next release cycle?

Comment (AnaghHegde) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java:805]: I am not against adding tests, it is just that i felt to add all the tests for all the methods of GitUtil class in a different PR. 
The edge for converting url is already covered in the above added test.

Comment (abhvsn) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java:805]: Sorry but I'm unable to find the check for `browserSupportedRemoteUrl`. Also, we can implement the testcases just for this method right now and then in separate PR we can take care for others.

**Review by abhvsn — APPROVED** [review]
