### PR TITLE
Fix widget not having query data

### LINKED ISSUE #1366: [Bug]Add widget from from Query is not populating query data in table widget
Steps:

1.Create a query using postgres datasource.
2.Then execute a query , make sure you can see the query response.
3.Click on Add widget.

Expected:
Table widget to be populated with query response.

Actual:
Table widget is populated with default table data.

### PR DESCRIPTION
**Pull request by akash-codemonk**
Fixes #1366 
Initialising widget props  with the tableData prop seems to fix it for now

### CODE REVIEW

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 1]
```diff
@@ -1035,6 +1035,9 @@ function* addTableWidgetFromQuerySaga(action: ReduxAction<string>) {
       parentRowSpace: 1,
       parentColumnSpace: 1,
       isLoading: false,
+      props: {
+        tableData: `{{${queryName}.data}}`,
+      },
```
Comment (hetunandu) [inline app/client/src/sagas/WidgetOperationSagas.tsx:1040]:
```suggestion
      props: {
        tableData: `{{${queryName}.data}}`,
        dynamicBindings: {
          tableData: true
        }
      },
```
If you do this you will not have to call the `updateWidgetPropertyRequest` done the line

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Review by hetunandu — APPROVED** [review]
