### PR TITLE
fix: Change multiselect back to supporting numbers and boolean.

### LINKED ISSUE #7872: [Bug] MultiSelect Default Value return value is not string.
## Description

The expected structure of multi select values are `Array<{ "label": "string", "value": "string" }>` and if we do INT and FLOAT on the value part the widget automatically converts it to string.
The same is not being followed on Default value. For e.g. if I put INT or FLOAT on default value, it doesn't automatically converts to string.

Behaviour of data type across the widget should have same expected results. 

Screenshot 2021-09-27 at 9 02 43 PM

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

### PR DESCRIPTION
**Pull request by SatishGandham**
## Description

Revert the validations change which converts multiselect options values to strings and path the filtering function to handle numbers and boolean

Fixes #7872, #7604

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/multiselect-default-values 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.82 **(-0.01)** | 36.96 **(-0.01)** | 33.8 **(-0.01)** | 55.43 **(-0.01)**
 :red_circle: | app/client/src/workers/validations.ts | 73.91 **(-1.09)** | 67.72 **(-0.3)** | 62.5 **(-3.13)** | 76.19 **(-0.84)**</details>

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]

File: app/client/src/workers/validations.ts [hunk 1]
```diff
@@ -119,7 +117,7 @@ function validateArray(
     config.params?.children?.type === ValidationTypes.OBJECT &&
     (config.params.children.params?.allowedKeys || []).length > 0
   ) {
-    const allowedKeysConfigArray =
+    const allowedKeysCofigArray =
```
Comment (Tooluloope) [inline app/client/src/workers/validations.ts:120]: This was incorrectly Spelt, that's why I changed it. `allowedKeysConfigArray` instead of `allowedKeysCofigArray`

**Review by Tooluloope — DISMISSED** [review]

**Comment by SatishGandham** [comment]
@vivekverma2312 , Can you test this.

**Review by jsartisan — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@SatishGandham Please find the list of issues
1. In Expected structure , value is still showing as only string
Screenshot 2021-09-28 at 4 50 32 PM
2. Passing value in Default value is not working when Expected value and example mention both value and array of value
Screenshot 2021-09-28 at 5 01 16 PM

**Comment by vivekverma2312** [comment]
3. Default value is not working with curly braces
Screenshot 2021-09-28 at 6 00 26 PM

**Comment by SatishGandham** [comment]
1. Changing this might have impact on other things, since its only cosmetic, we will take care of it later.
2. Removed the string option from suggestion to discourage users from using it.
3. Working on it.

@somangshu , if you want to merge this please go ahead. We will take 3 as a separate issue.

**Review by rahulramesha — APPROVED** [review]
Approving for tests

**Comment by somangshu** [comment]
@SatishGandham would any map on inside the curly brace work? In that case we could take up the issue later.

**Comment by SatishGandham** [comment]
> @SatishGandham would any map on inside the curly brace work? In that case we could take up the issue later.

They will. Only single values don't.
