### PR TITLE
fix: Handle clone errors in async executions

### LINKED ISSUE #19982: [Bug]: JS Function execution never ends when a higher-order js function is called
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Calling a higher-order JS Function (that returns a function) from within another JS function, causes a clone error that prevents JS Execution from getting completed.

### Steps To Reproduce

1. Create JS Object below 

```
export default {
	myVar1: [],
	myVar2: {},
	myFun1: () => {
		//write code here
		return (name)=>name;
	},
	myFun2: async () => {
		//use async-await or promises
		return this.myFun1()("favour")
	}
}
```
2. Run myFun2, and observe that execution never completes

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

Fixes #19982 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
WIP

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [x] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [x] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/workers/Evaluation/JSObject/JSProxy.ts [hunk 1]
```diff
@@ -96,18 +104,37 @@ export class JSProxy {
...
       });
     }
   }
 
+  private getSanitizedData(dataStore: Record<string, unknown>) {
+    const errors: Record<string, unknown> = {};
+    const data: Record<string, unknown> = {};
+    for (const funcName of Object.keys(dataStore)) {
+      try {
+        self.structuredClone(dataStore[funcName]);
```
Comment (arunvjn) [inline app/client/src/workers/Evaluation/JSObject/JSProxy.ts:126]: This can be referenced as structuredClone instead of `self.structuredClone` and we can avoid the custom type declaration.

**Review by arunvjn — APPROVED** [review]

File: app/client/src/workers/Evaluation/JSObject/JSProxy.ts (hunk 1 above)
Comment (ohansFavour) [reply app/client/src/workers/Evaluation/JSObject/JSProxy.ts:126]: Without the declaration, I was running into a compilation error. I will check for other ways to prevent this.

**Comment by ramsaptami** [comment]
lgtm

**Review by arunvjn — APPROVED** [review]
