### PR TITLE
fix: move git file operations to elastic schedulers

### LINKED ISSUE #13824: [Task]: Use async calls for file operations in FileUtils class like deleteDirectory, saveFile etc

### PR DESCRIPTION
**Pull request by AnaghHegde**
Fixes #13824 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 1]
```diff
@@ -160,15 +167,40 @@ public Mono<Path> saveApplicationToGitRepo(Path baseRepoSuffix,
...
+                        Mono<List<Boolean>> actionCollectionList = Flux.fromStream(Files.walk(baseRepo.resolve(ACTION_COLLECTION_DIRECTORY)))
+                                .map(Path::toFile)
+                                .map(File::delete)
+                                .collectList();
+                        return Mono.zip(pageList, actionList, actionCollectionList)
+                                .flatMap(objects -> Mono.zip(Mono.just(baseRepo), Mono.just(gson), Mono.just(validFileNames)));
+
                     } catch (IOException e) {
                         log.debug("Unable to delete directory for path {} with message {}", pageDirectory, e.getMessage());
+                        //return Mono.error(new IOException("Unable to delete directory for path {} with message {}"));
```
Comment (abhvsn) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:192]: Do we want to continue even if the delete operation failed for some reason? Asking this because this may result in resource being deleted in DB but still present in file system. IMO we should throw the exception as earlier

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 2]
```diff
@@ -160,15 +167,40 @@ public Mono<Path> saveApplicationToGitRepo(Path baseRepoSuffix,
...
                     }
+                    return Mono.zip(Mono.just(baseRepo), Mono.just(gson), Mono.just(validFileNames));
+                })
+                .flatMap(objects -> {
+                    Path baseRepo = objects.getT1();
+                    Path pageDirectory = baseRepo.resolve(PAGE_DIRECTORY);
+                    Gson gson = objects.getT2();
+                    Set<String> validFileNames = objects.getT3();
                     // Save pages
+                    processStop.stopAndLogTimeInMillis();
```
Comment (abhvsn) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:202]: Please remove this as it will stop the stopwatch and will result in incorrect result, as the intention was to log complete time for the `saveApplicationToGitRepo`

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 3]
```diff
@@ -89,7 +89,7 @@
 /**
  * Git APIs are slow today because these needs to communicate with remote repo and/or serialise and de-serialise the
  * application. This process takes time and the client may cancel the request. This leads to the flow getting stopped
- * midway producing corrupted states.
+ * midwa`y producing corrupted states.
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:92]: typo

**Review by abhvsn — CHANGES_REQUESTED** [review]

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 4]
```diff
@@ -160,15 +167,40 @@ public Mono<Path> saveApplicationToGitRepo(Path baseRepoSuffix,
                     saveFile(applicationGitReference.getTheme(), baseRepo.resolve(CommonConstants.THEME + CommonConstants.JSON_EXTENSION), gson);
 
                     Path pageDirectory = baseRepo.resolve(PAGE_DIRECTORY);
+
                     try {
                         // Remove relevant directories to avoid any stale files
-                        FileUtils.deleteDirectory(pageDirectory.toFile());
-                        FileUtils.deleteDirectory(baseRepo.resolve(ACTION_DIRECTORY).toFile());
-                        FileUtils.deleteDirectory(baseRepo.resolve(ACTION_COLLECTION_DIRECTORY).toFile());
+                        Mono<List<Boolean>> pageList = Flux.fromStream(Files.walk(pageDirectory)
```
[the remark this answers is not in the document]
Comment (AnaghHegde) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:173]: I don't see any reason on why we should create a local variable. It is not used in any other places, except the delete option.

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java (hunk 1 above)
Comment (AnaghHegde) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:192]: There was no error thrown before. It was not at all present. I have added this to test few things.

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 5]
```diff
@@ -224,7 +249,8 @@ public Mono<Path> saveApplicationToGitRepo(Path baseRepoSuffix,
                     }
                     processStopwatch.stopAndLogTimeInMillis();
                     return Mono.just(baseRepo);
-                });
+                })
+                .subscribeOn(scheduler);
```
Comment (abhvsn) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:253]: Hey, we have converted the blocking calls to reactive streams, is this still required?

Comment (AnaghHegde) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:253]: Not really. The save and read file operations are still blocking. Thats the reason why i wanted it to execute on a separate thread.

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java (hunk 1 above)
Comment (abhvsn) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java]: This may happen when we don't have permission to perform the file ops. If you think this will not happen then we can keep this in logs for now

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java (hunk 5 above)
Comment (abhvsn) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:253]: Should we convert these to async calls then

Comment (AnaghHegde) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:253]: I would prefer using the elastic schedule as it is used even for action execution and jgit apis.

**Review by abhvsn — DISMISSED** [review]

**Review by vishnu-gp — APPROVED** [review]

**Comment by AnaghHegde** [comment]
@allcontributors add @AnaghHegde as a contributor for code, bug
