### PR TITLE
Fix cyclical dependency issue when Api returns an error

### LINKED ISSUE #4775: [Bug] Cyclical dependency when Api returns an error
## Description
Seeing a cyclical dependency sometimes when API is returned an error

### Steps to reproduce the behaviour:

1. Create an API (Api1) with mock API users
2. Have a widget bound to the `{{Api1.data.users}}`
2. Run the API to get the data
3. remove /users
4. Run the API to get an error
5. Error: Cyclical dependency created in Api1.data node

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Translating edit differences had an issue where static changes were processed as NOOP when the data type changed from an object to some other type and vice versa. This caused a cyclic dependency for nodes when a nested dependency path was deleted and newly added paths were not processed. Fixed this by translating those events correctly

Fixes #4775 

## Type of change
- Bugfix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Follow the steps in the issue. When the API is returning a string error, it should not result in a cyclical dependency. When you fix the API again to make it return an object, it should populate the table again

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/cyclical-api-error 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/workers/DataTreeEvaluator.ts | 88.68 **(0.07)** | 79.27 **(0)** | 87.32 **(0)** | 88.86 **(0.07)**
 :red_circle: | app/client/src/workers/evaluationUtils.ts | 86.96 **(-2.67)** | 71.77 **(-4.12)** | 87.23 **(-3.68)** | 86.24 **(-3.13)**</details>

### CODE REVIEW

File: app/client/src/workers/evaluationUtils.ts [hunk 1]
```diff
@@ -88,8 +88,9 @@ export function getEntityNameAndPropertyPath(
 
 export const translateDiffEventToDataTreeDiffEvent = (
   difference: Diff<any, any>,
-): DataTreeDiff => {
-  const result: DataTreeDiff = {
+): DataTreeDiff | DataTreeDiff[] => {
+  debugger;
```
Comment (trishaanand) [inline app/client/src/workers/evaluationUtils.ts:92]:
```suggestion
```

**Review by trishaanand — APPROVED** [review]

**Review by trishaanand — DISMISSED** [review]

**Review by trishaanand — APPROVED** [review]
