### PR TITLE
fix: advanced filetype validation

### LINKED ISSUE #22592: [Feature]: Advanced file type validation is required on profile image upload
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There is a basic client side validation exists for validating the file extension. But Users can alter the file extension to image and upload it as their profile image. 

### Why should this be worked on?

The application allows the attacker to upload or transfer files of dangerous types that can be automatically processed within the product's environment.During the assessment, it was observed that application allows to upload the php and js based files to the application which is restricted to upload the file.By changing the extension it is possible to upload the malicious file.

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description

> This PR adds a second layer validation to the basic mime type validation that's in place which checks the file extension.
> If the `ImageIO.read()` library returns null for .png/.jpeg type files, it indicates a corrupted file upload, hence it returns VALIDATION_FAILURE.

Fixes #22592 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- JUnit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AssetServiceCEImpl.java [hunk 1]
```diff
@@ -46,11 +46,32 @@ public class AssetServiceCEImpl implements AssetServiceCE {
...
     @Override
     public Mono<Asset> getById(String id) {
         return repository.findById(id);
     }
 
+    private Boolean checkImageTypeValidation(DataBuffer dataBuffer, MediaType contentType) throws IOException {
+        BufferedImage bufferedImage = ImageIO.read(dataBuffer.asInputStream());
+        if (bufferedImage == null) {
+            /*
+                This is true for SVG and ICO images.
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AssetServiceCEImpl.java:63]: So, if I rename a JSON file to `.ico` and then upload, will it succeed? Then the vulnerability is still there, no?

Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AssetServiceCEImpl.java:63]: @sharat87 Yes, that's still a vulnerability. It's masked in the profile pic upload section since the client only allows for png/jpeg type file uploads. 
For svg/ico type files, since we cannot read the bytes, we are not able to know by reading the file content. It still has to rely on basic mime type checking (based on file extension)

Comment (sharat87) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AssetServiceCEImpl.java:63]: Got it. But let's create an issue to solve for svg/ico files as well please.

**Review by sharat87 — COMMENTED** [review]
I see that this PR is linked to #22592, but if I understand this right, that's not what we're solving here.

What we're solving here for, is ensuring that the uploaded PNG image, is indeed a valid PNG image. This is a good addition.

What the linked issue is talking about, is being able to upload any arbitrary file type, by mimicking the content-type. Here's an example of how I can upload a PHP file as my profile image:

Login with httpie:
Screenshot 2023-05-01 at 5 31 32 PM

Upload:
Screenshot 2023-05-01 at 5 31 44 PM

Confirm that it's uploaded:
Screenshot 2023-05-01 at 5 31 57 PM

Problem is, we are completely ignoring the file extension, and only checking the uploaded content type, which can be spoofed just as easily as the file type.

I think this is what linked issue is talking about. Correct me if I'm missing something though. 🤔

**Review by sharat87 — DISMISSED** [review]
Approving since the PoC above uses ICO content type, which isn't resolved in this PR, and which isn't allowed by the Appsmith client. Doesn't mean it's not a problem, just not solved in this PR. We should solve it separately.

**Comment by NilanshBansal** [comment]
CC: @Richarex can you pls test the dp for backend changes and share the results

**Comment by Richarex** [comment]
> CC: @Richarex can you pls test the dp for backend changes and share the results

Sure, will start testing it.

**Comment by Richarex** [comment]
@NilanshBansal 
Tested it on DP url, working as expected. 2level of validation is applied for invalid file UI & backend level error are getting displayed. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/6Dl3BagOBrDIdKP7

File: app/client/src/ce/sagas/userSagas.tsx [hunk 2]
```diff
@@ -476,11 +478,25 @@ export function* updatePhoto(
...
     //@ts-expect-error: response is of type unknown
     const photoId = response.data?.profilePhotoAssetId; //get updated photo id of iploaded image
     if (action.payload.callback) action.payload.callback(photoId);
   } catch (error) {
     log.error(error);
+
+    const payload: ErrorActionPayload = {
+      show: true,
+      error: {
+        message: (error as any).message ?? USER_PROFILE_PICTURE_UPLOAD_FAILED(),
```
Comment (akash-codemonk) [inline app/client/src/ce/sagas/userSagas.tsx:493]: `createMessage(USER_PROFILE_PICTURE_UPLOAD_FAILED)`

**Review by akash-codemonk — DISMISSED** [review]

**Review by eco-monk — APPROVED** [review]
