### PR TITLE
fix: Show recent errors first in the debugger error tab

### LINKED ISSUE #6715: [Bug]Clicking on the debug from the evaluated pane should open the error tab and scroll to the particular error when there are multiple errors
## Description

[What happened]Clicking on the debug from the evaluated pane should open the error tab and scroll to the particular error when there are multiple errors 

### Steps to reproduce the behaviour:

1. Go to canvas
2. drag and drop the map widget
3. open the property pane
3. make some error
4. now drag and drop the input box
5. open the property pane made some error
6. hover on the error and click on debug button from the evaluated tab 
7. verify the functionality

The user should navigate to the correct error when there are multiple errors in the debbuger

[LOOM DEMO](https://www.loom.com/share/6f012a45a5324d039a86a03bc83b0e28)
### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [ chrome]
- Environment [prelease]

### PR DESCRIPTION
**Pull request by akash-codemonk**
Shows recent errors first in the debugger error tab.

## Description

Fixes #6715 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

cypress test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/recent-error 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.87 **(-0.01)** | 36.87 **(-0.01)** | 34.23 **(0)** | 55.39 **(-0.01)**
 :red_circle: | app/client/src/reducers/uiReducers/debuggerReducer.ts | 43.75 **(-2.92)** | 0 **(0)** | 14.29 **(0)** | 46.67 **(-3.33)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

File: app/client/src/reducers/uiReducers/debuggerReducer.ts [hunk 1]
```diff
@@ -42,13 +42,23 @@ const debuggerReducer = createReducer(initialState, {
...
 
+    if (state.isOpen) {
+      return {
+        ...state,
+        errors: {
+          ...state.errors,
+          [action.payload.id]: action.payload,
+        },
+      };
+    }
```
Comment (rishabhsaxena) [inline app/client/src/reducers/uiReducers/debuggerReducer.ts:53]: should we move the latest error to the top even when the error tab is open?

**Review by rishabhsaxena — APPROVED** [review]
LGTM

**Review by rishabhsaxena — APPROVED** [review]
