### PR TITLE
fix: Action toolbar menu state

### LINKED ISSUE #38123: [Bug]: Action Redesign: Post clicking Delete, the pop-up does not disappear.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the queries page, if we click Delete query on the kebab menu, though the query gets deleted, the pop up menu does not go away

### Steps To Reproduce

1. Create a new application
2. Create a new datasource and create a couple of queries from the datasource
3. Click on the kebab menu in the tool bar of the query pane and click Delete
4. Note that though the query gets deleted, the popup menu remains open

https://jam.dev/c/b44c1f45-1094-488e-81c9-c895ae554a0f

### Public Sample App

_No response_

### Environment

Release

### Severity

Medium (Frustrating UX)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

- Refactors the menu toggle of the Plugin Action Toolbar to be in a different component
- Adds a key to the PluginToolbarContextMenu
- Refactor the run function for AI Plugin types (unrelated change)

Fixes #38123

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13128988723>
> Commit: ead4fac15c14a5e00a5f5103733bf8a128312a4a
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13128988723&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Tue, 04 Feb 2025 06:15:19 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new context menu for plugin actions, providing a smoother and more intuitive interaction experience.
	- Updated the plugin action toolbar to integrate with the context menu, enhancing accessibility and usability.

- **Refactor**
	- Streamlined the execution of plugin actions for a more dynamic and reliable behavior.

### CODE REVIEW

**Review by ankitakinger — DISMISSED** [review]

File: app/client/src/PluginActionEditor/components/PluginActionContextMenu/styles.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+import styled from "styled-components";
+import { MenuContent as ADSMenuContent } from "@appsmith/ads";
+
+export const MenuContent = styled(ADSMenuContent)`
+  z-index: 100;
```
Comment (KelvinOm) [inline app/client/src/PluginActionEditor/components/PluginActionContextMenu/styles.ts:5]: Why do we need this? As far as I understand, the menu should have a z-index by default to overlap  elements. cc @albinAppsmith

File: app/client/src/PluginActionEditor/components/PluginActionToolbar.tsx [hunk 2]
```diff
@@ -1,42 +1,36 @@
...
   useAnalyticsOnRunClick,
 } from "../hooks";
-import { useToggle } from "@mantine/hooks";
 import { useSelector } from "react-redux";
 import { isActionRunning } from "../store";
 import PluginActionSettings from "./PluginActionSettings";
+import { PluginActionContextMenu } from "./PluginActionContextMenu";
 
 interface PluginActionToolbarProps {
+  key: string;
```
[the remark this answers is not in the document]
Comment (hetunandu) [reply app/client/src/PluginActionEditor/components/PluginActionToolbar.tsx]: Removed

File: app/client/src/PluginActionEditor/components/PluginActionContextMenu/styles.ts (hunk 1 above)
Comment (hetunandu) [reply app/client/src/PluginActionEditor/components/PluginActionContextMenu/styles.ts]: Removed

**Review by ankitakinger — APPROVED** [review]
