### PR TITLE
fix: Redis running on 64k pagesize

### LINKED ISSUE #11773: [Bug]: Deploying on CentOS 8, with ARM64 fails to start Redis
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When installing Appsmith using the docker-compose method, and starting it, we see the following in the output, repeated over and over again.

```
appsmith  | 2022-03-10 13:06:40,670 INFO spawned: 'redis' with pid 400
appsmith  | 2022-03-10 13:06:40,678 INFO success: redis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
appsmith  | redis stdout | <jemalloc>: Unsupported system page size
appsmith  | redis stdout | 
appsmith  | redis stdout | <jemalloc>: Unsupported system page size
appsmith  | redis stdout | 
appsmith  | 2022-03-10 13:06:41,123 INFO exited: redis (terminated by SIGSEGV (core dumped); not expected)
```

Because of this, the server never comes up.

Server information:

```
[centos@ip-172-31-25-105 appsmith]$ uname -a
Linux ip-172-31-25-105.ap-south-1.compute.internal 4.18.0-240.10.1.el8_3.aarch64 #1 SMP Mon Jan 18 16:34:39 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

[centos@ip-172-31-25-105 appsmith]$ hostnamectl
   Static hostname: ip-172-31-25-105.ap-south-1.compute.internal
         Icon name: computer
        Machine ID: cecfd58c6d4d61edfb8f1b3a7341f92b
           Boot ID: 5931b68b24314ea1b7f8c07681a5d326
  Operating System: CentOS Linux 8
       CPE OS Name: cpe:/o:centos:centos:8
            Kernel: Linux 4.18.0-240.10.1.el8_3.aarch64
      Architecture: arm64

[centos@ip-172-31-25-105 appsmith]$ cat /etc/centos-release
CentOS Linux release 8.5.2111

[centos@ip-172-31-25-105 appsmith]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

[centos@ip-172-31-25-105 appsmith]$ getconf PAGE_SIZE
65536
```

### Steps To Reproduce

Create an instance with this AMI: https://ap-south-1.console.aws.amazon.com/ec2/v2/home?region=ap-south-1#ImageDetails:imageId=ami-081375038454ad4d5, with 2 processors, 4GB memory, and 20GB disk.

Then, run the following commands to setup Docker and `docker-compose`, and then get the default `docker-compose.yml` file and start Appsmith.

```
sudo sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
sudo yum update -y
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce docker-ce-cli containerd.io
sudo systemctl start docker
sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-aarch64" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
curl -L https://bit.ly/32jBNin -o docker-compose.yml
sudo /usr/local/bin/docker-compose up -d
sudo /usr/local/bin/docker-compose logs -f appsmith
```

### Public Sample App

_No response_

### Version

SelfHosted

### PR DESCRIPTION
**Pull request by geekup-legodevops**
## Description
- This is a workaround to run Redis on many platforms with different memory pagesize (4k, 32k, 64k)
## Type of change
- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
## How Has This Been Tested?
- Build new image and running on CentOS arm64 with Pagesize 64k
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: deploy/docker/entrypoint.sh [hunk 1]
```diff
@@ -172,13 +172,32 @@ configure_supervisord() {
   fi
 }
 
+# This is a workaround to get Redis working on diffent memory pagesize
+# https://github.com/appsmithorg/appsmith/issues/11773
+check_redis_compatible_page_size() {
+  if [ $(getconf PAGE_SIZE) -gt 4096 ]; then
+    echo "Compile Redis stable with page size of $(getconf PAGE_SIZE)"
```
Comment (sharat87) [inline deploy/docker/entrypoint.sh:179]:
```suggestion
  local page_size
  page_size="$(getconf PAGE_SIZE)"
  if [[ $page_size -gt 4096 ]]; then
    echo "Compile Redis stable with page size of $page_size"
```

File: deploy/docker/entrypoint.sh [hunk 2]
```diff
@@ -172,13 +172,32 @@ configure_supervisord() {
...
+    echo "Downloading Redis source..."
+    curl https://download.redis.io/redis-stable.tar.gz -L | tar xvz
+    cd redis-stable/
+    echo "Compiling Redis from source..."
+    make && make install
+    echo "Cleaning up Redis source..."
+    cd ..
+    rm -rf redis-stable/
+  else
+    echo "Redis is compatible with page size of $(getconf PAGE_SIZE)"
```
Comment (sharat87) [inline deploy/docker/entrypoint.sh:189]:
```suggestion
    echo "Redis is compatible with page size of $page_size"
```

**Review by sharat87 — CHANGES_REQUESTED** [review]

**Review by sharat87 — DISMISSED** [review]
