### PR TITLE
fix: added support for both openssh and rsa private keys

### LINKED ISSUE #39015: [Bug]: [A-force] Postgres SSH Tunnelling does not work
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

The cloud user is not able to connect to their PostgreSQL database via SSH tunnel, getting the error Failed to create SSH connection. and Test failed, couldn't establish a connection. However, they are able to successfully connect using the Dbeaver tool with an SSH tunnel.
Link: https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=3785
Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1737548296333299
Image

### Steps To Reproduce

1. Create a new postgres datasource
2. Add the SSH tunnelling config
3. Upload the private key 
4. Click on Test Datasource, it fails

### Public Sample App

_No response_

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

_No response_

### Version

Appsmith Cloud v1.59

### PR DESCRIPTION
**Pull request by NilanshBansal**
Fixes #39015 

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13160498931>
> Commit: 0c06208089c6e3498f5fca0b7ee861b7797e5cef
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13160498931&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Wed, 05 Feb 2025 15:56:40 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced secure connection setup by automatically detecting and supporting multiple SSH key formats, ensuring more reliable authentication during tunnel creation.
	- Improved error messaging for invalid SSH key formats and parsing issues.

- **Tests**
	- Added new tests to validate the parsing of OpenSSH, PKCS#8 PEM, and RSA PEM key formats, improving test coverage for SSH key handling functionality.

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java [hunk 1]
```diff
@@ -65,8 +69,22 @@ public static SSHTunnelContext createSSHTunnel(
...
+            keyFile = openSSHKeyFile;
+        } else {
+            // PEM (PKCS#8) format
+            PKCS8KeyFile pkcs8KeyFile = new PKCS8KeyFile();
+            pkcs8KeyFile.init(new StringReader(keyContent));
+            keyFile = pkcs8KeyFile;
+        }
+
+        // Authenticate using the detected key format
         client.auth(sshUsername, new AuthPublickey(keyFile));
```
[the remark this answers is not in the document]
Comment (NilanshBansal) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java]: Done

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java [hunk 2]
```diff
@@ -65,9 +71,38 @@ public static SSHTunnelContext createSSHTunnel(
...
+                keyFile = openSSHKeyFile;
+            } else if (keyContent.contains("BEGIN PRIVATE KEY") || keyContent.contains("BEGIN RSA PRIVATE KEY")) {
+                // Handle PEM (PKCS#8) and RSA PEM formats
+                PKCS8KeyFile pkcs8KeyFile = new PKCS8KeyFile();
+                pkcs8KeyFile.init(reader);
+                keyFile = pkcs8KeyFile;
+            } else {
+                throw new AppsmithPluginException(
+                        AppsmithPluginError.PLUGIN_DATASOURCE_ARGUMENT_ERROR,
+                        "Invalid SSH key format. Only OpenSSH and PEM (PKCS#8) formats are supported.");
```
Comment (sneha122) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java:93]: @NilanshBansal Let's add this message in appropriate constants file?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java [hunk 3]
```diff
@@ -65,9 +71,38 @@ public static SSHTunnelContext createSSHTunnel(
 
         client.connect(sshHost, sshPort);
         Reader targetReader = new InputStreamReader(new ByteArrayInputStream(key.getDecodedContent()));
-        PKCS8KeyFile keyFile = new PKCS8KeyFile();
-        keyFile.init(targetReader);
-        client.auth(sshUsername, new AuthPublickey(keyFile));
+        KeyProvider keyFile;
+        String keyContent = null;
+        try (Reader reader = new StringReader(new String(key.getDecodedContent(), StandardCharsets.UTF_8))) {
```
Comment (sneha122) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java:76]: There is no catch here, we should add that for better error handling

**Review by sneha122 — APPROVED** [review]
