### PR TITLE
fix: Some .jpg images don't load in the Image Widget

### LINKED ISSUE #11206: [Bug]: some .jpg images don't load in the Image Widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to display a .jpg image in the image widget when being loaded from a URL, it doesn't display the output, and continues to display the default image. Some examples are:

http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg
https://www.simplyrecipes.com/thmb/nAuodqCn_xVyOfRCuqIwQ-j1izo=/2000x1333/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2007__05__mango-chutney-horiz-a-2000-2b99607680ef4c0fb0dcd470d158982d.jpg

### Steps To Reproduce

1. Add an image widget to the application
2. Enter any of the above URLs

The image doesn't load when it should

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
When I try to display a .jpg image in the image widget when being loaded from a URL, it doesn't display the output, and continues to display the default image. Some examples are:

http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg
https://www.simplyrecipes.com/thmb/nAuodqCn_xVyOfRCuqIwQ-j1izo=/2000x1333/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2007__05__mango-chutney-horiz-a-2000-2b99607680ef4c0fb0dcd470d158982d.jpg

Fixes #11206 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/11206-image-jpg-not-load 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.77 **(-0.01)** | 37.09 **(-0.01)** | 35.82 **(0)** | 56.13 **(0)**
 :red_circle: | app/client/src/ce/constants/messages.ts | 76.98 **(-0.02)** | 100 **(0)** | 31.75 **(-0.05)** | 81.94 **(0.02)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :green_circle: | app/client/src/widgets/ImageWidget/component/index.tsx | 14.63 **(0.34)** | 14.12 **(0.79)** | 8.33 **(0)** | 16.19 **(1.19)**</details>

### CODE REVIEW

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected
1. Proper error message on url issues instead of displaying default image
2. 2nd url image is able to view on image widget

File: app/client/src/widgets/ImageWidget/component/index.tsx [hunk 1]
```diff
@@ -119,6 +126,14 @@ class ImageComponent extends React.Component<
       cursor = isZoomingIn ? "zoom-in" : "zoom-out";
     }
     if (this.props.onClick) cursor = "pointer";
+
+    if (imageUrl && imageError)
+      return (
+        <ErrorContainer data-testid="error-container">
+          Image load error
```
Comment (mohanarpit) [inline app/client/src/widgets/ImageWidget/component/index.tsx:133]: Nit pick: Can we please improve this error message? Also, is it possible to move this to `messages.ts` and use `createMessage` function here?

```suggestion
          Unable to display the image
```

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Image_spec.js [hunk 2]
```diff
@@ -65,6 +65,22 @@ describe("Image Widget Functionality", function() {
...
     cy.get(publish.imageWidget).should("be.visible");
   });
+
+  it("In case of an image loading error, show off error message", () => {
+    cy.get(publish.backToEditor).click();
+    cy.openPropertyPane("imagewidget");
+    // Invalid image url
+    const invalidImageUrl = "https://www.example.com/does-not-exist.jpg";
+    cy.testCodeMirror(invalidImageUrl);
+    cy.wait(5000);
```
Comment (mohanarpit) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Image_spec.js:75]: Quick question: Why are we waiting for 5 secs here? Can we reduce the wait time or in the best case eliminate it?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Image_spec.js [hunk 3]
```diff
@@ -65,6 +65,22 @@ describe("Image Widget Functionality", function() {
     cy.PublishtheApp();
     cy.get(publish.imageWidget).should("be.visible");
   });
+
+  it("In case of an image loading error, show off the error message", () => {
```
Comment (somangshu) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Image_spec.js:69]: @sbalaji1192 @wmdev0808 I am trying to understand if in any way it was possible to identify the failed case https://github.com/appsmithorg/appsmith/issues/11494.

Is there anything we can learn here?

Comment (sbalaji1192) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Image_spec.js:69]: @somangshu It's a case we could have identified in the QA and written a case here to cover it. I don't think we could have identified in the CR stage since we not have declared any new state, we are using the existing state.

Comment (somangshu) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Image_spec.js:69]: @vivekverma2312 @shwetha-ramesh @YogeshJayaseelan please take note of this, What could have been done to find this important issue that cause so much friction for our users?

cc @dilippitchika
