### PR TITLE
fix: Added Button Container for the firefox drag issue

### LINKED ISSUE #10655: [Bug]: Button drag issue in firefox
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Button is not draggable if drag starts from empty area in button. If I start dragging from the text, button is draggable. Happens in Firefox 91.5.

This doesn't happen in chromium, button can be dragged from any area.

https://user-images.githubusercontent.com/1573771/151161388-e69fe29c-8f59-4c0f-9c6a-f0ffb59772d1.mp4

### Steps To Reproduce

1. open firefox
2. drag drop a button
3. increase size of the button
4. drag from empty space, it is not draggable. (bug)
5. drag from text, it is draggable.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by yaldram**
## Description

- Unfortunately firefox browser has an open issue with regards to button drag - https://bugzilla.mozilla.org/show_bug.cgi?id=568313.
- Solution was inspired by - https://stackoverflow.com/a/43888410.

Fixes #10655 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested Manually on the canvas.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/firefox-button-drag-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.89 **(0.01)** | 37.25 **(0)** | 35.23 **(-0.01)** | 56.2 **(0.01)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :green_circle: | app/client/src/widgets/ButtonGroupWidget/component/index.tsx | 23.96 **(0.63)** | 11.2 **(0.51)** | 4.17 **(-0.59)** | 25.58 **(0.58)**
 :sparkles: :new: | **app/client/src/widgets/ButtonWidget/component/DragContainer.tsx** | **90.91** | **66.67** | **100** | **90**
 :red_circle: | app/client/src/widgets/ButtonWidget/component/index.tsx | 51.58 **(-0.5)** | 30 **(-1)** | 45.45 **(-2.38)** | 51.19 **(0)**
 :sparkles: :new: | **app/client/src/widgets/ButtonWidget/component/utils.tsx** | **100** | **50** | **100** | **100**
 :red_circle: | app/client/src/widgets/IconButtonWidget/component/index.tsx | 23.81 **(-5.6)** | 5.88 **(-1.26)** | 0 **(0)** | 37.04 **(-4.63)**
 :red_circle: | app/client/src/widgets/MenuButtonWidget/component/index.tsx | 25.42 **(0.83)** | 11.76 **(-2.13)** | 0 **(0)** | 30.61 **(0.61)**</details>

### CODE REVIEW

**Comment by yaldram** [comment]
Thanks @sbalaji1192 for the insights, following our conversations I have - 
- not used state inside my component keeping it pure.
- used `renderMode` prop to check if we are in renderMode and add necessary styles.

**Comment by yaldram** [comment]
@sbalaji1192 I have refactored the code, I have also handled the drag issue for `IconButtonWidget`, there were some additional conditions for `IconButtonWidget` which are not in common with the `ButtonWidget` & `ButtonGroupWidget` therefore at this point in time I have handled the drag for `IconButtonWidget` in its own file. Thanks

File: app/client/src/widgets/ButtonGroupWidget/component/index.tsx [hunk 1]
```diff
@@ -119,25 +125,28 @@ interface ButtonStyleProps {
...
 
 const StyledButton = styled.button<ThemeProp & ButtonStyleProps>`
   flex: 1 1 auto;
   display: flex;
-  cursor: pointer;
   justify-content: stretch;
   align-items: center;
   padding: 0px 10px;
 
+  // use the css at the top and not inside a function
```
Comment (sbalaji1192) [inline app/client/src/widgets/ButtonGroupWidget/component/index.tsx:137]: not able to understand the comment.

File: app/client/src/widgets/ButtonWidget/component/DragContainer.tsx [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+
+  We found a solution here - https://stackoverflow.com/a/43888410
+*/
+
+/*
+  We are adding a wrapper in Canvas mode to the Button and once
+  we deploy it we remove the wrapper altogether.
+  Because we are adding a wrapper we also need to duplicate any 
+  :hover, :active & :focus styles and pass onClick to the wrapper.
+*/
```
Comment (sbalaji1192) [inline app/client/src/widgets/ButtonWidget/component/DragContainer.tsx:19]: Please add the line we discussed why we're adding this wrapper for all browsers when the issue is only in firefox.

Comment (yaldram) [reply app/client/src/widgets/ButtonWidget/component/DragContainer.tsx:19]: Sure will add - `we could have checked for firefox browser using window.navigator but we wanted our function to be pure.`

File: app/client/src/widgets/ButtonGroupWidget/component/index.tsx (hunk 1 above)
Comment (yaldram) [reply app/client/src/widgets/ButtonGroupWidget/component/index.tsx:137]: Here because we are using `css` function from styled components calling it in a nested function won't work example - 
```js
const hoverStyles = css ``

const Button = styled.button`
// won't work
  ${() => {
    &:hover, &:active {
      ${hoverStyles}
    }
  }}

// will work
 &:hover, &:active {
      ${hoverStyles}
    }
`
```

File: app/client/src/widgets/ButtonWidget/component/DragContainer.tsx (hunk 2 above)
Comment (sbalaji1192) [reply app/client/src/widgets/ButtonWidget/component/DragContainer.tsx:19]: widget to be pure. And also `similiar experience in all browser.`

File: app/client/src/widgets/ButtonGroupWidget/component/index.tsx (hunk 1 above)
Comment (sbalaji1192) [reply app/client/src/widgets/ButtonGroupWidget/component/index.tsx:137]: Could you mention that same on the comment?

File: app/client/src/widgets/ButtonGroupWidget/component/index.tsx [hunk 3]
```diff
@@ -429,7 +443,7 @@ class ButtonGroupComponent extends React.Component<ButtonGroupComponentProps> {
                   content={
                     <PopoverContent
                       menuItems={menuItems || {}}
-                      onItemClicked={this.onButtonClick}
+                      onItemClicked={() => () => this.onButtonClick()}
```
Comment (sbalaji1192) [inline app/client/src/widgets/ButtonGroupWidget/component/index.tsx:446]: Why we are wrapping inside a function ?

Comment (yaldram) [reply app/client/src/widgets/ButtonGroupWidget/component/index.tsx:446]: Hey actually this prop `onItemClicked` accepts a curried function.

Comment (sbalaji1192) [reply app/client/src/widgets/ButtonGroupWidget/component/index.tsx:446]: onItemClicked={() => this.onButtonClick} should suffice.

**Review by sbalaji1192 — APPROVED** [review]

File: app/client/src/widgets/ButtonGroupWidget/component/index.tsx (hunk 3 above)
Comment (yaldram) [reply app/client/src/widgets/ButtonGroupWidget/component/index.tsx:446]: Thanks for pointing it out, I have made the necessary changes.
