### PR TITLE
fix: auto toggle js to normal on click of connect data in table widget

### LINKED ISSUE #25393: [Task]:  Switch to normal mode on click of "connect data" in table widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

If the data value is in JS mode with no bindings then on click of "Connect data" in table widget it should switch to normal mode from JS mode.

### PR DESCRIPTION
**Pull request by berzerkeer**
## Description
- When we click on connect data on table widget, if the prop pane data field is in JS mode and no binding value has been set , it should switch to normal mode automatically.

#### PR fixes following issue(s)
Fixes #25393 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)

>
>
>
- [s] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by rahulramesha — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx [hunk 1]
```diff
@@ -746,6 +749,15 @@ const PropertyControl = memo((props: Props) => {
       };
     }
 
+    if (
+      connectDataClicked &&
+      propertyName === "tableData" &&
```
[the remark this answers is not in the document]
Comment (berzerkeer) [reply app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:754]: I don't get it, will DM you in slack. 😅

File: app/client/src/widgets/TableWidgetV2/widget/propertyConfig/contentConfig.ts [hunk 2]
```diff
@@ -47,6 +47,16 @@ export default [
...
         },
         evaluationSubstitutionType: EvaluationSubstitutionType.SMART_SUBSTITUTE,
+        switchToNormalMode: (
+          triggerFlag: boolean,
+          propertyName: string,
+          isDynamic: boolean,
+          isToggleDisabled: boolean,
+        ) =>
+          triggerFlag &&
+          propertyName === "tableData" &&
```
Comment (rahulramesha) [inline app/client/src/widgets/TableWidgetV2/widget/propertyConfig/contentConfig.ts:57]: no need for propertyName check here

File: app/client/src/widgets/TableWidgetV2/widget/propertyConfig/contentConfig.ts [hunk 3]
```diff
@@ -47,6 +47,16 @@ export default [
           },
         },
         evaluationSubstitutionType: EvaluationSubstitutionType.SMART_SUBSTITUTE,
+        switchToNormalMode: (
```
Comment (rahulramesha) [inline app/client/src/widgets/TableWidgetV2/widget/propertyConfig/contentConfig.ts:50]: could you change the name to something like, `shouldSwitchToNormalMode`

File: app/client/src/constants/PropertyControlConstants.tsx [hunk 4]
```diff
@@ -98,6 +98,13 @@ export type PropertyPaneControlConfig = {
   isPanelProperty?: boolean;
   // Numeric Input Control
   min?: number;
+  // Switch mode ( JS -> Text )
+  switchToNormalMode?: (
+    triggerFlag: boolean,
```
Comment (rahulramesha) [inline app/client/src/constants/PropertyControlConstants.tsx:103]: Could you move the trigger flag as the last argument and make it optional? So that in the future it can be used without the last argument..

**Review by rahulramesha — CHANGES_REQUESTED** [review]

**Review by rahulramesha — DISMISSED** [review]

**Review by rahulramesha — APPROVED** [review]

**Comment by laveena-en** [comment]
Verified, PR looks good to me!
