### PR TITLE
fix: show errors from git status

### LINKED ISSUE #12274: [Bug]: The error CTA should be added when new SSH key is generated and not added in git
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The error CTA should be added when new SSH key is generated and not added in git

### Steps To Reproduce

1. Go to App which is connected to git 
2. Now Under git connect tab click on Meat ball icon 
3. Generate a new SSH Key 
4. Now do a change in the app before coping the new ssh key in the git repo 
5. try to commit and push 
6. The commit and push button is disabled but the error cta is not displayed

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

We are not showing a few errors from git status API.

Fixes #12274 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: 12274-fix-show-error-notification-on-ssh-regeneration 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.18 **(0)** | 37.67 **(-0.02)** | 35.67 **(0.01)** | 56.42 **(-0.01)**
 :green_circle: | app/client/src/ce/constants/messages.ts | 77.13 **(0.06)** | 100 **(0)** | 32.2 **(0.19)** | 82.02 **(0.15)**
 :red_circle: | app/client/src/sagas/GitSyncSagas.ts | 9.15 **(-1.01)** | 0.24 **(-0.02)** | 4.35 **(0)** | 11.46 **(-1.29)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**</details>

### CODE REVIEW

File: app/client/src/sagas/GitSyncSagas.ts [hunk 1]
```diff
@@ -432,10 +433,18 @@ function* fetchGitStatusSaga() {
       yield put(fetchGitStatusSuccess(response?.data));
     }
   } catch (error) {
+    const payload = { error, show: true };
+    if (error?.message?.includes("Auth fail")) {
+      payload.error = new Error(ERROR_GIT_AUTH_FAIL());
```
Comment (mohanarpit) [inline app/client/src/sagas/GitSyncSagas.ts:438]: Can we use `createMessage(ERROR_GIT_AUTH_FAIL)`  instead? The `createMessage` function has been created to deal with i18n in the future. This way, the same message can be shown in different languages based on the user setting.

**Review by haojin111 — APPROVED** [review]
