### PR TITLE
fix: remove redundant eval trigger

### LINKED ISSUE #36237: [Bug]: Eval getting triggered twice on page switch in deployed mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Recently we merged an improvement for consolidated view API's Action part, where we say that published actions will be fetched based on pageId instead of app Id. This way whenever we switch between pages, we call the consolidated api again to fetch actions belonging to the new page. This has caused an issue in the evaluations as mentioned here https://theappsmith.slack.com/archives/C024GUDM0LT/p1725943060293719?thread_ts=1725864964.488269&cid=C024GUDM0LT

### Steps To Reproduce

1. Create app and publish it
2. In deployed mode, switch between different pages

### Public Sample App

_No response_

### Environment

Release

### Severity

Medium (Frustrating UX)

### Issue video log

_No response_

### Version

NA

### PR DESCRIPTION
**Pull request by rishabhrathod01**
## Description

We removed the fetchPublishedPage action from the page switch flow in App Viewer as the consolidated API now loads the migratedDSL.  
- PageSaga code was refactored to make sure the `postFetchPublishedPage` logic is common for both the init and switch page to ease maintenance. 

Fixes #36237 

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11132731783>
> Commit: 026ef4e704ce878be75446d470eef1af842aff39
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11132731783&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Tue, 01 Oct 2024 21:32:17 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced handling of page fetching with the addition of new action types for managing published page resources.
	- Introduced new functions to streamline canvas layout updates and post-fetch processes.

- **Bug Fixes**
	- Resolved issues related to fetching published page resources and improved error handling.

- **Refactor**
	- Simplified the logic in the `PageSagas` for better organization and reduced code duplication.
	- Improved the control flow in the `AppViewer` component for fetching page resources.

- **Tests**
	- Updated tests to reflect changes in action payload structures and new action types.

### CODE REVIEW

**Comment by rishabhrathod01** [comment]
Running only git tag as all tags have failures related to git. 

image

File: app/client/src/ce/sagas/PageSagas.tsx [hunk 1]
```diff
@@ -420,8 +420,11 @@ export function* fetchPublishedPageResourcesSaga(
       );
 
       // NOTE: fetchActionsForView is used here to update publishedActions in redux store and not to fetch actions again
-      yield put(fetchActionsForView({ applicationId, publishedActions }));
+      yield put(fetchActionsForView({ applicationId: "", publishedActions }));
```
Comment (sneha122) [inline app/client/src/ce/sagas/PageSagas.tsx:423]: Do we not want to send applicationId here? I know earlier also it was being sent as empty butt want to confirm why we changed this?

Comment (rishabhrathod01) [reply app/client/src/ce/sagas/PageSagas.tsx:423]: - The `AppViewer/index.tsx` component does not have `applicationId` but instead has the `baseApplicationId` and sending it here might cause unknown issues similar to what happened when I sent the `basePageId` instead of `pageId` to the updateCurrentPage as the fetchPublishedPageResourcesSaga has `basePageId` property named as `pageId`. 

- I do not want to include the change of fetching the `applicationId` in the component and sending it to the saga with this change.

Comment (sneha122) [reply app/client/src/ce/sagas/PageSagas.tsx:423]: Makes sense, I think ideally consolidated API would fetch in all the actions data anyways and sending applicationId using another API is just a fallback. We can visit this again whenever we come to this fallback situation

**Review by sneha122 — APPROVED** [review]
