### PR TITLE
feat: [Context Switching]: Change focus target and fix cursor position

### LINKED ISSUE #17598: [Task]: Maintain cursor position when changing context
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Need to update code editor to allow for storing and restoring of cursor position when the input gets back in focus

### LINKED ISSUE #17670: [Bug]: Context switching is hampering the copy paste experience of the widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two issues here:
1. Due to context switching the cursor is not retaining its initital position
2. This is breaking the copy paste experience of the widget

### Steps To Reproduce

1. Edit any property (say label ) of any widget (say text widget)
2. Click on the canvas to remove the focus from the property pane
3. Click on the edit widget again . You'll see the Cursor position is retained (position is wrong though)
4. Try copy and paste of the widget(Since the focus is on the input text box, Widget copy is not happening)
5. 
 https://www.loom.com/share/ed2108a3869d49f19c6245f28e5399f6

### Public Sample App

_No response_

### Version

Release

### LINKED ISSUE #18011: [Bug]: Context Switching does not work on API pane url
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/12022471/199161605-34cc2803-adc0-4a56-9898-5d4d3e88b5e2.mov

### Steps To Reproduce

1. Navigate to API
2. Focus on the URL field
3. Navigate out of the API to any part of the app
4. Navigate back to the API

expected to have the focus and cursor be on the URL field

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #18013: [Bug]: Context Switching Scrolling issues in property pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Scroll top not working
https://www.loom.com/share/f3501752a6334aed8544bb18a1ab3f14

- Flickering issues due to auto scroll.
https://www.loom.com/share/7f1bffb7896a4ec992652df2509435fb
- Not focusing on correct property .
 https://www.loom.com/share/6cf64700098044a3a525a3d9b02f06e8

### Steps To Reproduce

Context Switching in property pane acts weirdly

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #18015: [Bug]: Need to limit Auto scroll to widgets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are scrolling whenever a new widget is selected. Instead we should only do so when the widget is significantly out of the view port center

### Steps To Reproduce

1. Click on a widget
2. Click on another widget near it

https://user-images.githubusercontent.com/12022471/199164535-e7f009cc-f7a0-4d84-a3c6-1b98fca7a14b.mov

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #18016: [Bug]: [Context Switching] Default focus not being set for new entities
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating new action entities, we are not resetting the focus states to their defaults

### Steps To Reproduce

https://user-images.githubusercontent.com/12022471/199164987-9fe9a211-c10e-4fbc-83cb-661ab4e7d2bf.mov

https://user-images.githubusercontent.com/12022471/199164991-0750f1c8-cc05-4396-b521-384d4ecb42e6.mov

https://user-images.githubusercontent.com/12022471/199165001-e8208af2-15b7-4c1d-82f7-5257138876ac.mov

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Focus on the code editor container and only focus on editor when enter is clicked when the editor is on property pane

Fixes #17598
Fixes #17670
Fixes #18015
Fixes #18016
Fixes #18011
Fixes #18013 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual
- Cypress

### Issues raised during DP testing
- [x] #18015
- [x] #18016
- [x] #18011
- [x] #18013

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/editorComponents/CodeEditor/index.tsx [hunk 1]
```diff
@@ -343,9 +349,14 @@ class CodeEditor extends Component<Props, State> {
 
         this.lintCode(editor);
 
-        if (this.props.editorIsFocused && shouldFocusOnPropertyControl()) {
-          editor.focus();
-        }
+        setTimeout(() => {
```
Comment (rahulramesha) [inline app/client/src/components/editorComponents/CodeEditor/index.tsx:352]: Do we need a setTimeout? I remember it working without it. Which scenario was this required for?

File: app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx [hunk 2]
```diff
@@ -117,13 +117,15 @@ const PropertyControl = memo((props: Props) => {
...
+      // We can get a code editor element as well, which will take time to load
+      // for that we setTimeout to 200 ms
       setTimeout(() => {
         const focusableElement = getPropertyControlFocusElement(
           controlRef.current,
         );
         focusableElement?.scrollIntoView({ block: "center" });
         focusableElement?.focus();
-      }, 0);
+      }, 500);
```
Comment (rahulramesha) [inline app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:128]: Not sure the 500ms delay is required either. Noticing a lag when opening new widget to it focusing on the property control because of this. I remember it working without delay before

File: app/client/src/utils/helpers.tsx [hunk 3]
```diff
@@ -234,7 +234,7 @@ export const quickScrollToWidget = (widgetId?: string) => {
     if (el) {
       el.scrollIntoView({ block: "center" });
     }
-  }, 0);
+  }, 200);
```
Comment (rahulramesha) [inline app/client/src/utils/helpers.tsx:237]: Was this failing in some scenario without the timeout value?

File: app/client/src/components/editorComponents/CodeEditor/index.tsx (hunk 1 above)
Comment (hetunandu) [reply app/client/src/components/editorComponents/CodeEditor/index.tsx:352]: We added a set timeout here to delay the focus. I noticed in JS editor, the props were updating in a staggered manner which was causing the focus to not happen reliably. Adding this makes it work always.

File: app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx (hunk 2 above)
Comment (hetunandu) [reply app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:128]: We need this to work when moving from action pane to canvas. The lazy code editor or the code editor do not render properly but the focus is set. Because of this race, the focus is then reset to the body. Adding this solved the issue. I experimented with 200 but that was not working all the time, hence 500.

File: app/client/src/utils/helpers.tsx (hunk 3 above)
Comment (hetunandu) [reply app/client/src/utils/helpers.tsx:237]: Same problem with focus being set on widget before it renders and resetting it in the process.

**Comment by kamakshibhat-appsmith** [comment]
Checked the DP to verify [#17670 ](https://github.com/appsmithorg/appsmith/issues/17670) , working fine.

**Comment by Richarex** [comment]
[#17598 ](url) This is working fine verified it on the DP url:- https://appsmith-f733zntcz-get-appsmith.vercel.app/applications

File: app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx (hunk 2 above)
Comment (rahulramesha) [reply app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:128]: Yes, i think this can be solved by focusing on the control, which wraps both lazyCodeEditor and the CodeEditor instead. I cant seem to get over the lag which makes the propertyPane jump around after 500ms.

**Comment by Richarex** [comment]
Verified the fixes for #17598, #17670, #18011, #18015 & #18016 on this DP url:- https://appsmith-bhr12cc9o-get-appsmith.vercel.app/applications and they are working fine.

**Review by Richarex — APPROVED** [review]
Verified the changes, QA approved.

**Review by yaldram — APPROVED** [review]
