### PR TITLE
Fix issue where creating a new application twice does not work

### LINKED ISSUE #1712: [Bug] Create app is not working
### Steps to reproduce the behaviour:
1. Login to an existing account
2. Click create new app
3. Go back to the applications page 
4. Click create app
5. Nothing happens

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
Fix issue where creating a new application twice does not work

Fixes #1712 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/pages/Applications/index.tsx [hunk 1]
```diff
@@ -631,8 +631,11 @@ const ApplicationsSection = (props: any) => {
                   <PaddingWrapper>
                     <ApplicationAddCardWrapper
                       onClick={() => {
+                        console.log({ creatingApplicationMap });
```
Comment (mohanarpit) [inline app/client/src/pages/Applications/index.tsx:634]: Can we remove this console.log?

**Review by mohanarpit — APPROVED** [review]
