### PR TITLE
fix: checkbox group feedback

### LINKED ISSUE #6783: Checkbox group widget - Feedback
1. The design of the checkbox doesn't match the Figma designs. 
Screen Shot 2021-08-21 at 12 39 12 AM
2. The checkbox group isn't centered when there's just one option
Screen Shot 2021-08-21 at 12 54 49 AM
3. The inline option should be the default selected

----------
_Originally posted by @areyabhishek in https://github.com/appsmithorg/appsmith/issues/6199#issuecomment-902913602_

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- Add default border for a checkbox icon and color for a label
- Align the option to the center if its options count is one or inline
- Set isInline to true by default in widget config

Fixes #6783 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/6783-checkboxgroup-feedback 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.14 **(-0.01)** | 37.1 **(0.01)** | 33.97 **(-0.01)** | 55.65 **(-0.01)**
 :green_circle: | app/client/src/utils/DSLMigrations.ts | 73.89 **(0.15)** | 65.04 **(-0.05)** | 70.21 **(0)** | 73.71 **(0.16)**
 :sparkles: :new: | **app/client/src/utils/migrations/CheckboxGroupWidget.ts** | **72.73** | **66.67** | **100** | **70**
 :red_circle: | app/client/src/widgets/CheckboxGroupWidget/component/index.tsx | 25.71 **(-20.96)** | 13.33 **(0)** | 0 **(0)** | 33.33 **(-20.52)**</details>

### CODE REVIEW

File: app/client/src/mockResponses/WidgetConfigResponse.tsx [hunk 1]
```diff
@@ -1306,15 +1306,16 @@ const WidgetConfigResponse: WidgetConfigReducerState = {
...
+      rows: 1 * GRID_DENSITY_MIGRATION_V1,
+      columns: 4 * GRID_DENSITY_MIGRATION_V1,
       options: [
         { label: "Apple", value: "apple" },
         { label: "Orange", value: "orange" },
         { label: "Lemon", value: "lemon" },
       ],
       defaultSelectedValues: "apple",
       isDisabled: false,
+      isInline: true,
```
Comment (somangshu) [inline app/client/src/mockResponses/WidgetConfigResponse.tsx:1318]: Old apps need migration for this, The new widgets have inline true by default

File: app/client/src/mockResponses/WidgetConfigResponse.tsx [hunk 2]
```diff
@@ -1306,15 +1306,16 @@ const WidgetConfigResponse: WidgetConfigReducerState = {
       version: 1,
     },
     [WidgetTypes.CHECKBOX_GROUP_WIDGET]: {
-      rows: 2 * GRID_DENSITY_MIGRATION_V1,
-      columns: 1.5 * GRID_DENSITY_MIGRATION_V1,
+      rows: 1 * GRID_DENSITY_MIGRATION_V1,
```
Comment (somangshu) [inline app/client/src/mockResponses/WidgetConfigResponse.tsx:1309]: We did not need to change this, Only inline needs to be enabled and the default size should not show scroll. 

If there is a problem in writing migration for this, please revert to old value

**Review by somangshu — CHANGES_REQUESTED** [review]
Everything looks good apart from the inline prop being true by default. Requested changes as above

File: app/client/src/mockResponses/WidgetConfigResponse.tsx (hunk 2 above)
Comment (somangshu) [reply app/client/src/mockResponses/WidgetConfigResponse.tsx:1309]: My bad, Since this cant be migrated, the widget from old apps will only have `inline` true and the widget boundaries / size will remain as it is, For the new widget the above change made by @wmdev0808 will work 👍

**Review by marks0351 — DISMISSED** [review]

**Comment by marks0351** [comment]
@wmdev0808 the default checkbox group when dragged and dropped doesn't look good. pls check.

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 3]
```diff
@@ -832,6 +833,11 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
     currentDSL.version = LATEST_PAGE_VERSION;
```
Comment (marks0351) [inline app/client/src/utils/WidgetPropsUtils.tsx:833]: pls change this to 34

**Review by marks0351 — CHANGES_REQUESTED** [review]

**Comment by marks0351** [comment]
@wmdev0808 @somangshu when I drop a new checkbox group i see two entries, the third one is hidden coz of space constraint. pls check if that is acceptable.

**Comment by somangshu** [comment]
@marks0351 on first D&D I see it like this 👇 

Screenshot 2021-09-06 at 11 16 45 AM

Can you please share what issue you are seeing?

**Comment by marks0351** [comment]
cbgrp
this is how it looks for me. when i decrease zoom percentage to 90% i can see all three options.

**Comment by somangshu** [comment]
@wmdev0808 can you look into this, See if we can reproduce it

**Comment by somangshu** [comment]
@vivekverma2312 @YogeshJayaseelan can you guys help us verify the problem here

**Comment by wmdev0808** [comment]
> @wmdev0808 can you look into this, See if we can reproduce it

Hi @somangshu , I've confirmed with @marks0351 and then made appropriate changes on this PR

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 4]
```diff
@@ -842,6 +843,11 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
...
```
Comment (marks0351) [inline app/client/src/utils/WidgetPropsUtils.tsx:843]:
```suggestion
    currentDSL.version = 36;
```

Comment (marks0351) [inline app/client/src/utils/WidgetPropsUtils.tsx:843]:
```suggestion
    currentDSL.version = 36;
```

**Review by marks0351 — CHANGES_REQUESTED** [review]

**Review by marks0351 — DISMISSED** [review]

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Verified this PR. Now By default the inline option is enabled and for the D&D the widget looks like below,

Screenshot 2021-09-13 at 4 08 37 PM

and the option is center alined when only one option is available

**Review by marks0351 — APPROVED** [review]

**Comment by somangshu** [comment]
@wmdev0808 please merge the latest release here

**Review by somangshu — DISMISSED** [review]

File: app/client/src/utils/DSLMigrations.ts [hunk 5]
```diff
@@ -917,6 +918,11 @@ export const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
...
   }
 
+  if (currentDSL.version === 38) {
+    currentDSL = migrateResizableModalWidgetProperties(currentDSL);
+    currentDSL.version = 39;
+  }
+
   if (currentDSL.version === 38) {
     currentDSL = migrateCheckboxGroupWidgetInlineProperty(currentDSL);
     currentDSL.version = LATEST_PAGE_VERSION;
```
Comment (somangshu) [inline app/client/src/utils/DSLMigrations.ts:928]: @marks0351 this should update to 38? Can you please check

Comment (marks0351) [reply app/client/src/utils/DSLMigrations.ts:928]: this looks fine.

File: app/client/src/widgets/CheckboxGroupWidget/component/index.tsx [hunk 6]
```diff
@@ -1,29 +1,32 @@
...
+import { Checkbox } from "@blueprintjs/core";
 
 import { ComponentProps } from "widgets/BaseComponent";
 import { ThemeProp } from "components/ads/common";
 import { generateReactKey } from "utils/generators";
 
 // TODO(abstraction-issue): this needs to be a common import from somewhere in the platform
 // Alternatively, they need to be replicated.
-import { StyledCheckbox } from "widgets/CheckboxWidget/component";
+// import { StyledCheckbox } from "widgets/CheckboxWidget/component";
```
Comment (marks0351) [inline app/client/src/widgets/CheckboxGroupWidget/component/index.tsx:11]: remove unwanted comments

**Review by marks0351 — CHANGES_REQUESTED** [review]

File: app/client/src/utils/migrations/CheckboxGroupWidget.ts [hunk 7]
```diff
@@ -0,0 +1,18 @@
+import { WidgetProps } from "widgets/BaseWidget";
+import { DSLWidget } from "widgets/constants";
+
+export const migrateCheckboxGroupWidgetInlineProperty = (
+  currentDSL: DSLWidget,
+) => {
+  currentDSL.children = currentDSL.children?.map((child: WidgetProps) => {
+    if (child.type === "CHECKBOX_GROUP_WIDGET") {
+      if (!("isInline" in child)) {
+        child.isInline = true;
```
Comment (marks0351) [inline app/client/src/utils/migrations/CheckboxGroupWidget.ts:10]: pls update widget version which wud make it easy to reverse migrate.

**Review by marks0351 — CHANGES_REQUESTED** [review]

**Review by marks0351 — APPROVED** [review]

**Comment by wmdev0808** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1418332469

File: app/client/src/utils/DSLMigrations.ts [hunk 8]
```diff
@@ -972,10 +973,16 @@ export const transformDSL = (
   }
 
   if (currentDSL.version === 43) {
+    currentDSL = migrateCheckboxGroupWidgetInlineProperty(currentDSL);
     currentDSL = mapAllowHorizontalScrollMigration(currentDSL);
     currentDSL.version = LATEST_PAGE_VERSION;
```
Comment (marks0351) [inline app/client/src/utils/DSLMigrations.ts:978]: pls change this to 44.

**Review by marks0351 — CHANGES_REQUESTED** [review]

**Comment by marks0351** [comment]
@wmdev0808 pls resolve conflicts.

File: app/client/src/utils/DSLMigrations.ts (hunk 8 above)
Comment (marks0351) [reply app/client/src/utils/DSLMigrations.ts:983]: @wmdev0808 pls fix this.

**Review by marks0351 — APPROVED** [review]

**Comment by somangshu** [comment]
@wmdev0808 related tests failing here, Please check

**Review by marks0351 — DISMISSED** [review]

**Comment by shwetha-ramesh** [comment]
@wmdev0808 tested this on DP
Feedback 2 & 3 are working as expected.

However Feedback 1 - **"The design of the checkbox doesn't match the Figma designs."**
1) The document shows a darker grey border for a checkbox icon whereas in DP the checkbox icon is a lighter version.
2) Also on Windows OS the drag and drop of a checkbox group only two options are showed and for the third option user needs to scroll (as observed in the video)
image

https://loom.com/share/736088d07eb043bab72c34c982421db5

For a better comparison I have attached the screenshot on all three platforms notice at the moment.
image

**Comment by wmdev0808** [comment]
> 2\. Also on Windows OS the drag and drop of a checkbox group only two options are showed and for the third option user needs to scroll (as observed in the video)

@shwetha-ramesh , I noticed you found this issue on Fluid mode.
In that mode, all the widgets' sizes are decreased, that's why having scrollbar is normal behavior.
I think you can ignore this.

**Review by marks0351 — DISMISSED** [review]

**Comment by shwetha-ramesh** [comment]
@wmdev0808 retested this PR. 
There is still a mismatch of color from [figma](https://www.figma.com/file/u0IE1Vqr2MKcQcQKCpHO4O/Checkbox-Group-Widget?node-id=2%3A3) to DP. As seen in below image in DP the checkbox has a light grey outline inside which is not noticed in figma.

image

**Review by marks0351 — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@wmdev0808 working as expected. Moving to DONE.

**Review by somangshu — APPROVED** [review]
