### PR TITLE
fix: prevent click event on disabled next page button of table widget

### LINKED ISSUE #22477: [Bug]: Disable clicking on Next page button when Table record reached to last page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Table widget, when pagination reach to it's last page the icon seems disabled but we can still Click on it and see rendering of data.

### Steps To Reproduce

1. Drag & drop a Table widget
2. Run a server side pagination query `SELECT * FROM users ORDER BY id LIMIT {{Table2.pageSize}} offset {{Table2.pageOffset}}`
3. Enable server side pagination and configure onPageChange & Total records
4. Reach to last page of the table records
5. Observe that Next page button is disabled but clickable

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/bad8d690647c4583b7e82d6092a1ccbe

### Version

Cloud / Production

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description
This PR fixes the issue mentioned below by preventing the click event when the next page button is disabled and when it is table's last page.

#### PR fixes following issue(s)
Fixes #22477

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?

- [x] Manual
- [ ] Jest
- [ ] Cypress
    - should check whether the next page button is disabled and not clickable when last page is reached

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js [hunk 1]
```diff
@@ -35,4 +36,17 @@ describe("Test Create Api and Bind to Table widget V2", function () {
       .first()
       .should("contain", "2");
   });
+
+  it("2. should check whether the next page button is disabled and not clickable when last page is reached", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js:40]: Mention `Bug # 22477` id in `it` description

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js [hunk 2]
```diff
@@ -35,4 +36,17 @@ describe("Test Create Api and Bind to Table widget V2", function () {
...
+    /**
+     * Flow:
+     * Update total records count to 20
+     * Click next page
+     */
+
+    propPane.UpdatePropertyFieldValue("Total Records", "20");
+    agHelper.GetNClick(table._nextPage("v2"));
+
+    agHelper.AssertElementAbsence(commonlocators._toastMsg);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js:50]: What is toast absence? Can we check if nextPage button is disabled - bug specific validation?

Comment (keyurparalkar) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js:50]: @Aishwarya-U-R I have added toast absence because we also need to check that no click event should happen when the button is disabled. This was happening earlier so this PR fixes this issue. Also, I have added asseration for disabled state of the button

FYI: toast appears when the next page is clicked.

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js [hunk 3]
```diff
@@ -35,4 +36,18 @@ describe("Test Create Api and Bind to Table widget V2", function () {
...
+    /**
+     * Flow:
+     * Update total records count to 20
+     * Click next page
+     */
+
+    propPane.UpdatePropertyFieldValue("Total Records", "20");
+    agHelper.GetNClick(table._nextPage("v2"));
+
+    agHelper.GetElement(table._nextPage("v2")).should("have.attr", "disabled");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js:50]: Use `agHelper.AssertElementEnabledDisabled`

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js (hunk 2 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js:51]: It always comes when moving to next page? Where is toast set?

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js [hunk 4]
```diff
@@ -14,10 +15,10 @@ describe("Test Create Api and Bind to Table widget V2", function () {
   });
   it("1. Create an API and Execute the API and bind with Table", function () {
     apiPage.CreateAndFillApi(
-      this.dataSet.paginationUrl + this.dataSet.paginationParam,
+      "http://localhost:5001/v1/" + this.dataSet.paginationParam,
     );
     agHelper.VerifyEvaluatedValue(
-      this.dataSet.paginationUrl + "mock-api?records=20&page=1&size=10",
+      "http://localhost:5001/v1/" + "mock-api?records=20&page=1&size=10",
     );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js:22]: No hard coding of urls.. Why is this changed?

Comment (keyurparalkar) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js]: Apologies I reverted this code. I used it to test the spec file locally.

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js (hunk 2 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js:51]: Ok is from DSL. That is the issue with DSL's. We do not know whats present & whats not. Please prefer using dragDrop from next case.

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes.

**Comment by laveena-en** [comment]
Verified. PR look good to me!

**Review by sbalaji1192 — APPROVED** [review]
