### PR TITLE
fix: trigger instance re-registration if not already registered

### LINKED ISSUE #28952: [Task]: Update instance registration check and re- registration flow
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

- A [use case](https://theappsmith.slack.com/archives/C040LHZN03V/p1700206435426579) surfaced recently wherein a user's instance failed to register itself with the remote cloud service. Although we do not know the root cause for why a registration would fail or if the user's instance was marked with `true` or `false` for the `appsmith_registered` config document, it may be useful to update the flows where registration is required to attempt a re-registration if the previous attempt failed: 
  - Attempt to get Appsmith token immediately post registration to check if registration succeeded. 
    - Mark `appsmith_registered` value `true` or `false` based on whether the Appsmith token could be fetched. 
  - In case of flows where Appsmith token is required, first check if the `appsmith_registered` value is `true` or `false`. If it is `false`, then re-trigger the registration flow first e.g. Google sheets authorization
    -  if Appsmith token could not be fetched then show proper error on the client.

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description

Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1700206435426579
## Background 
At the start of the new appsmith server, we register the instanceId with cloud services by invoking the cloud services api. For some of the instances, if this register api call didn't go through, the cloud services db will not have the instanceId.

While connecting to GSheets, we do a check if the request is coming from a valid registered instance, and if it is not present this api fails.

The appsmith mongo database config collection, keeps a record of whether this instance was registered or not. 
In some scenarios, the appsmith_registered field shows that the instance is registered but it is not as instanceId is missing in CS, i.e. the appsmith server has the info that the instance is registered with CS but the CS db has not registered the instance.

> This PR triggers the re-registration flow to the cloud services if the instance is not registered. 
> When calling the google sheets API to cloud services, if the response received is 403 FORBIDDEN, it indicates the instance is not registered, in which scenario we retrigger the registeration flow and call the CS again.

#### PR fixes following issue(s)
Fixes #28952 

https://drive.google.com/file/d/1cVluIAQlzxwb7A2bgBBMJ0I4awSV6fKp/view?usp=sharing
#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Automation

/ok-to-test tags=""

### :mag: Cypress test results

> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt the CI result for your PR.

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 1]
```diff
@@ -422,19 +427,55 @@ public Mono<String> getAppsmithToken(
...
+                                        Mono<? extends Config> registerInstanceMono =
+                                                instanceConfigHelper.registerInstance();
+                                        return registerInstanceMono
+                                                .flatMap(config -> clientResponseMono.flatMap(res -> {
+                                                    if (res.statusCode().is2xxSuccessful()) {
+                                                        // After re-registering the instance, the appsmith token request
+                                                        // is successful
+                                                        return res.bodyToMono(Map.class);
+                                                    } else {
+                                                        // After re-registering the instance, the appsmith token request
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:452]: @NilanshBansal In registerInstanceMono, if response status code is not 200, does that not mean registration failed? Instead from your comment it seems like registration was successful but appsmith token request failed, I dont quite understand this, can you please explain the flow once?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 2]
```diff
@@ -422,19 +427,55 @@ public Mono<String> getAppsmithToken(
...
+                    return clientResponseMono
                             .flatMap(response -> {
                                 if (response.statusCode().is2xxSuccessful()) {
                                     return response.bodyToMono(Map.class);
                                 } else {
-                                    log.debug("Unable to retrieve appsmith token with error {}", response.statusCode());
-                                    return Mono.error(new AppsmithException(
-                                            AppsmithError.AUTHENTICATION_FAILURE,
-                                            "Unable to retrieve appsmith token with error " + response.statusCode()));
+                                    if (response.statusCode().equals(HttpStatus.FORBIDDEN)) {
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:441]: @NilanshBansal Can we check if there is any other case where cloud services throws 403 forbidden, other than instance registration failure?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 3]
```diff
@@ -422,19 +427,55 @@ public Mono<String> getAppsmithToken(
...
+                                        // Instance is not registered with CS, hence re-registering it
+                                        Mono<? extends Config> registerInstanceMono =
+                                                instanceConfigHelper.registerInstance();
+                                        return registerInstanceMono
+                                                .flatMap(config -> clientResponseMono.flatMap(res -> {
+                                                    if (res.statusCode().is2xxSuccessful()) {
+                                                        // After re-registering the instance, the appsmith token request
+                                                        // is successful
+                                                        return res.bodyToMono(Map.class);
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:450]: @NilanshBansal After the registration is successful, do we not want to fetch appsmith token again? Or is that something user will have to do by running query again?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 4]
```diff
@@ -422,19 +427,55 @@ public Mono<String> getAppsmithToken(
...
                                 if (response.statusCode().is2xxSuccessful()) {
                                     return response.bodyToMono(Map.class);
                                 } else {
-                                    log.debug("Unable to retrieve appsmith token with error {}", response.statusCode());
-                                    return Mono.error(new AppsmithException(
-                                            AppsmithError.AUTHENTICATION_FAILURE,
-                                            "Unable to retrieve appsmith token with error " + response.statusCode()));
+                                    if (response.statusCode().equals(HttpStatus.FORBIDDEN)) {
+                                        // Instance is not registered with CS, hence re-registering it
+                                        Mono<? extends Config> registerInstanceMono =
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:443]: @NilanshBansal Should we add junit test cases to mock this call to cloud services and assert this flow?

**Comment by sneha122** [comment]
@NilanshBansal Can you please provide steps on how I can test this flow?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 2 above)
Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:441]: Yes, @sneha122 this has been verified from cloud services. Another [PR](https://github.com/appsmithorg/cloud-services/pull/1596) changing one of the error codes regarding this was raised and merged.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 4 above)
Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:443]: It's not required @sneha122, since this a extra step we are doing to register the instance. This occurs for only 1% of the cases where instance registration fails at step 1. 
Also, writing JUnit will not solve the purpose as we need to mock the cloud services API call in the test case which would not validate the instance registration from cloud services db.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 3 above)
Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:450]: Yes, after the registration we are fetching the appsmith token again from cloud services. 
The `clientResponseMono` contains the appsmith token request to cloud services. 

For the user, they will just be making 1 API call to google sheets, internally we will register the instance to cloud services if not registered and then carry on the token request flow as intended.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 1 above)
Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:452]: If instance registration fails, the error will be handled in `onErrorResume()` on line 463 where I have handled the logic for instance registration failure.

**Comment by NilanshBansal** [comment]
> @NilanshBansal Can you please provide steps on how I can test this flow?


@sneha122 this flow involves deleting the entry for instance registration from the cloud services database. 
Hence, testing this on dp will be a bit difficult. 

I will be adding a screen recording from my local setup along with the directions for the same

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 3 above)
Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:450]: Got it makes sense, thanks a lot!!

**Review by sneha122 — APPROVED** [review]

**Comment by NilanshBansal** [comment]
Screen Recording for the instance re-registration flow.
https://drive.google.com/file/d/1cVluIAQlzxwb7A2bgBBMJ0I4awSV6fKp/view?usp=sharing

cc: @sneha122 @rohan-arthur
