### PR TITLE
Fix success message for single user invite and multiple user invite

### LINKED ISSUE #3542: [Bug] Invite success text is always plural even when only 1 user is invited
The invite text says: "Users have been invited." when I invited only one user. It should say, 'The user has been invited successfully' for one email and 'Users have been invited' for multiple emails.

Screen Shot 2021-03-14 at 2 02 18 AM

### PR DESCRIPTION
**Pull request by kaushik94**
## Description
The invite text says: "Users have been invited." when I invited only one user. It should say, 'The user has been invited successfully' for one email and 'Users have been invited' for multiple emails.

Fixes #3542 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test 1: invited a single user, used cypress to check if the error message is correct.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js [hunk 1]
```diff
@@ -19,6 +19,16 @@ describe("Create new org and share with a user", function() {
         Cypress.env("TESTUSERNAME1"),
         homePage.viewerRole,
       );
+      // check that the success message is correct
+      cy.checkSuccessMessageForOneUserInvite(
```
Comment (rishabhsaxena) [inline app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js:23]: NIT: Maybe we could keep the logic here itself instead of a separate cypress command since it would be relevant just for the `invite user modal`?

File: app/client/src/pages/organization/OrgInviteUsersForm.tsx [hunk 2]
```diff
@@ -220,6 +221,10 @@ const OrgInviteUsersForm = (props: any) => {
     isLoading,
   } = props;
 
+  // set state for checking number of users invited
+  const [numberOfUsersInvited, updateNumberOfUsersInvited] = useState(0);
+
+  console.log("INVITING USERS:", allUsers, props);
```
Comment (rishabhsaxena) [inline app/client/src/pages/organization/OrgInviteUsersForm.tsx:227]: Not sure if the log is still needed

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js [hunk 3]
```diff
@@ -19,6 +19,14 @@ describe("Create new org and share with a user", function() {
         Cypress.env("TESTUSERNAME1"),
         homePage.viewerRole,
       );
+      // check that the success message is correct
+      const successMessage = "The user has been invited successfully";
+      cy.contains(message);
```
Comment (rishabhsaxena) [inline app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js:24]: Looks like a typo, should it be `successMessage ` instead?

File: app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js [hunk 4]
```diff
@@ -19,6 +19,14 @@ describe("Create new org and share with a user", function() {
...
+      cy.get(homePage.manageUsers).click({ force: true });
+      cy.xpath(homePage.appHome)
+        .first()
+        .should("be.visible")
+        .click();
```
Comment (rishabhsaxena) [inline app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js:29]: Any reason for moving these lines of code from the `commands.js` file?

Comment (kaushik94) [reply app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js:29]: I think that before taking any action like "click", we should check if the error message is correctly shown. On clicking manage users, the message might not be visible.

Comment (rishabhsaxena) [reply app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js:29]: Ok yeah, missed that. Think we can add the assertion as part of the `inviteUserForOrg` command as well. Since it doesn't add a lot of overhead to the test. Otherwise we could have refactored the command to do just one flow.

Comment (kaushik94) [reply app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js:29]: In the future, I might add a test for multiple user invite as well therefore I added it here. Do you think it makes sense?

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js (hunk 4 above)
Comment (rishabhsaxena) [reply app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js:29]: Yeah, this looks good, I wasn't sure if it affects other tests.
