### PR TITLE
fix: entity explorer issue with datasources is fixed

### LINKED ISSUE #26716: [Bug]: Selected datasource does not get highlighted correctly in entity explorer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I select a datasource on the left side, that does not get highlighted, though its details get populated on the right pane
https://drive.google.com/file/d/1Aldi9Labr-D8gesI0zW7_H__qx7eu3Fn/view?usp=sharing

### Steps To Reproduce

1. Create a couple of postgres, mysql datasources
2. Try navigating through them

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/ Self-Hosted - 1.9.32

### PR DESCRIPTION
**Pull request by sneha122**
## Description
This PR fixes issue with datasource not getting highlighted in entity explorer:

Suppose we have 3 datasources in our applications: Users, Movies, and one Postgres or MySQL datasource. Once we create these datasources, we can see them getting populated in entity explorer -> datasource section.

So there were two issues here:
- If I select Users, I am able to see the Users datasource info on the right pane but its not active in the entity explorer, Similarly If I switch to movies, right pane gets updated with movies info but in the entity explorer, we cannot see movies getting highlighted as thats the active selection
- If I am on Users datasource review page, I reload the page, now I can see active selection of Users being highlighted in the entity explorer, but now if we switch to Movies, right pane gets updated but in entity explorer Users is highlighted, which is incorrect

This issue occurred because we have used useMemo for `datasourceElements`, two dependency passed are appWideDS and pageId, whenever we switch between datasources, `activeDatasourceId` gets updated but since we have cached the whole datasource listing component without the dependency of `activeDatasourceId`, it does not recompute and shows the same state as before.

To fix the issue, `activeDatasourceId` needs to be passed in the dependency array. After adding this new dependency, another issue occurred with respect to entity explorer, The order of suggested datasources would change in entity explorer, This PR addresses that issue as well.
#### PR fixes following issue(s)
Fixes #26716 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [x] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+      cy.get("[data-testid='t--entity-item-Movies']").should(
+        "have.class",
+        "active",
+      );
+
+      // Switch to custom DS
+      entityExplorer.SelectEntityByName(dsName, "Datasources");
+      agHelper.Sleep(200);
+      const testId = "t--entity-item-" + dsName;
+      cy.get(`[data-testid='${testId}']`).should("have.class", "active");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts:36]: No direct locator in specs.

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+  agHelper,
+  dataSources,
+  entityExplorer,
+} from "../../../../support/Objects/ObjectsCore";
+let dsName;
+
+describe("Bug 26726: Datasource selected from entity explorer should be correctly highlighted", function () {
+  it("1. Create users and movies mock datasources and switch between them through entity explorer, check the active state", function () {
+    dataSources.CreateMockDB("Users");
+    dataSources.CreateMockDB("Movies");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts:11]: Can this be tested only with mock db's? If so - please exclude this spec for Airgap run.

Comment (sneha122) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts:11]: Can you please give an example of excluding this for Airgap? Also why do we need to exclude this from airgap?

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts (hunk 1 above)
Comment (sneha122) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts:36]: You mean adding this check in Aggregate helper instead?

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts (hunk 2 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts:11]: Add `excludeForAirgap` as first parameter to describe block.

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts (hunk 1 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts:36]: No, I meant no direct locator `[data-testid='${testId}']` in spec.

**Review by Irongade — DISMISSED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts (hunk 1 above)
Comment (sneha122) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts]: Made the changes please check

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts (hunk 2 above)
Comment (sneha122) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts]: Resolved this as well. Please check

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts]: Also why do we need to exclude this from airgap? - `We need to exclude them in Airgap instances because mock ds are not present as they need internet access to connect to Mock ds's.`

File: app/client/cypress/support/Pages/AggregateHelper.ts [hunk 3]
```diff
@@ -1639,6 +1639,10 @@ export class AggregateHelper extends ReusableHelper {
       });
   }
 
+  public AssertClassExists(selector: string, className: string) {
+    cy.get(selector).should("have.class", className);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/AggregateHelper.ts:1643]: nit: Use `agHelper.GetElement` instead of cy.get - so it can work with both css & xpath locators.

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts [hunk 4]
```diff
@@ -0,0 +1,50 @@
+import {
+  agHelper,
+  dataSources,
+  entityExplorer,
+} from "../../../../support/Objects/ObjectsCore";
+let dsName;
+
+describe(
+  "excludeForAirgap",
+  "Bug 26726: Datasource selected from entity explorer should be correctly highlighted",
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts:10]: Bug id is 26726 or `26716`?

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes.

**Review by Aishwarya-U-R — DISMISSED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]

**Review by Irongade — APPROVED** [review]
