### PR TITLE
fix: Improving form widget keyboard accessibility

### LINKED ISSUE #7757: [Feature] Improving form widget keyboard accessibility
## Summary

In a regular HTML form, a user can choose to set different tab indices for different inputs irrespective of their position. This gives users control over how the cursor moves between elements in a form.

## Motivation
Improves keyboard accessibility in forms on Appsmith.

## Additional Context
Screen Shot 2021-09-23 at 11 35 48

### PR DESCRIPTION
**Pull request by jsartisan**
This PR allows tabbing between widgets according to their position. 
Also, it allows trapping focus in the modal widget

https://user-images.githubusercontent.com/6636360/210065731-403d68f7-8f82-4780-8c3d-5055056c139d.mov

Fixes #7757

## Type of change
- Enhancement

## How Has This Been Tested?
- Manually

### CODE REVIEW

**Comment by laveena-en** [comment]
@jsartisan Noticing some inconsistencies here:
https://ivp6ez0ljb.vmaker.com/record/NBKvsfEoEP4d4H5Z
In addition, there doesn't seem to be a focus state on Tabs widget as well

**Comment by laveena-en** [comment]
@jsartisan Also, focus is seen on the widgets when they are set to `visible: OFF` in edit mode https://ivp6ez0ljb.vmaker.com/record/mxq4U04O70GJe7yi

**Comment by laveena-en** [comment]
Tested and verified the fixes, keyboard accessibility between widgets and wrapping within modals.

File: app/client/src/components/designSystems/appsmith/PositionedContainer.tsx [hunk 1]
```diff
@@ -163,7 +168,9 @@ export function PositionedContainer(props: PositionedContainerProps) {
   return (
     <PositionedWidget
       className={containerClassName}
+      data-hidden={props.visible === false || undefined}
```
Comment (ashit-rath) [inline app/client/src/components/designSystems/appsmith/PositionedContainer.tsx:171]: `!props.visible || undefined`

File: app/client/src/utils/hooks/useWidgetFocus/handleTab.ts [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+      nextTabbableDescendant = getNextTabbableDescendantForJSONForm(
+        currentWidget,
+        shiftKey,
+      );
+      break;
+    default:
+      const tabbable = getTabbableDescendants(currentNode, shiftKey);
+
+      nextTabbableDescendant = getNextTabbableDescendant(tabbable, shiftKey);
+  }
```
Comment (ashit-rath) [inline app/client/src/utils/hooks/useWidgetFocus/handleTab.ts:35]: Any advantage of using a switch case instead of `if-else`?

File: app/client/src/utils/hooks/useWidgetFocus/handleTab.ts [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+  const currentWidget = currentNode.closest(WIDGET_SELECTOR) as HTMLElement;
+
+  switch (true) {
+    // when the current node is a widget, we want to do tabbing in regular way
+    // the elements will be in proper order in dom for thes widgets
+    case currentWidget && currentWidget.matches(JSONFORM_WIDGET):
+    case currentWidget && currentWidget.matches(CHECKBOXGROUP_WIDGET):
+    case currentWidget && currentWidget.matches(SWITCHGROUP_WIDGET):
+    case currentWidget && currentWidget.matches(BUTTONGROUP_WIDGET):
+      nextTabbableDescendant = getNextTabbableDescendantForJSONForm(
```
Comment (ashit-rath) [inline app/client/src/utils/hooks/useWidgetFocus/handleTab.ts:26]: Why `getNextTabbableDescendantForJSONForm` when the currentWidget can be checkboxgroup, switchgroup etc?

File: app/client/src/utils/hooks/useWidgetFocus/tabbable.ts [hunk 4]
```diff
@@ -0,0 +1,325 @@
...
+      return sortedTabbableDescendants;
+    }
+
+    // this case means the focus on the main container canvas
+    if (currentNode.matches(CANVAS_WIDGET)) {
+      const tabbableDescendants = Array.from(
+        currentNode.querySelectorAll(WIDGET_SELECTOR),
+      ) as HTMLElement[];
+
+      const domRect = currentNode.getBoundingClientRect();
```
Comment (ashit-rath) [inline app/client/src/utils/hooks/useWidgetFocus/tabbable.ts:61]: We are calling functions like `getBoundingClientRect`. 
These may cause layout thrashing with continuous tabbing. I would recommend to run few performance profile to check if this is happening.

File: app/client/src/utils/hooks/useWidgetFocus/tabbable.ts [hunk 5]
```diff
@@ -0,0 +1,325 @@
...
+    if (isTabbingBackward) {
+      if (element.topDiff === 0) {
+        return element.leftDiff < 0;
+      }
+
+      if (element.topDiff < 0) {
+        return true;
+      }
+
+      return false;
```
Comment (ashit-rath) [inline app/client/src/utils/hooks/useWidgetFocus/tabbable.ts:273]: Can we convert this whole thing into
```
      if (element.topDiff === 0) {
        return element.leftDiff < 0;
      }

      return element.topDiff < 0
```

File: app/client/src/utils/hooks/useWidgetFocus/tabbable.ts [hunk 6]
```diff
@@ -0,0 +1,325 @@
...
+ *
+ * @param node
+ * @returns
+ */
+export function getFocussableElementOfWidget(node: HTMLElement) {
+  if (node.matches(FOCUS_SELECTOR)) {
+    return node;
+  }
+
+  const focussableElement = node.querySelector(FOCUS_SELECTOR) as HTMLElement;
```
Comment (ashit-rath) [inline app/client/src/utils/hooks/useWidgetFocus/tabbable.ts:171]: direct return `node.querySelector ...`

File: app/client/src/utils/hooks/useWidgetFocus/useWidgetFocus.tsx [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+  const ref = useRef<HTMLElement | null>();
+
+  // This is a callback that will be called when the ref is set
+  const setRef = useCallback((node: HTMLElement | null) => {
+    if (node === null) return;
+
+    if (ref.current === node) return;
+
+    ref.current = node;
+  }, []);
```
Comment (ashit-rath) [inline app/client/src/utils/hooks/useWidgetFocus/useWidgetFocus.tsx:16]: Can't we just return the `ref` and use that? It does the same thing that we are doing in the `setRef`

File: app/client/src/utils/hooks/useWidgetFocus/useWidgetFocus.tsx [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+      ref.current.addEventListener("click", (event: any) => {
+        const target = event.target as HTMLElement;
+        if (target.matches(CANVAS_WIDGET)) {
+          target.focus();
+        }
+      });
+    }
+
+    return () => {
+      ref?.current && ref.current.removeEventListener("keydown", handleKeyDown);
```
Comment (ashit-rath) [inline app/client/src/utils/hooks/useWidgetFocus/useWidgetFocus.tsx:38]: We should remove the `click` event as well

File: app/client/src/utils/hooks/useWidgetFocus/useWidgetFocus.tsx [hunk 9]
```diff
@@ -0,0 +1,45 @@
...
+    if (!ref.current) return;
+
+    const handleKeyDown = (event: KeyboardEvent) => {
+      if (event.key === "Tab") handleTab(event);
+    };
+
+    ref.current.addEventListener("keydown", handleKeyDown);
+
+    // focus the current element on click inside the widget
+    if (ref.current) {
```
Comment (ashit-rath) [inline app/client/src/utils/hooks/useWidgetFocus/useWidgetFocus.tsx:28]: Do we need to check again for the existence of `ref.current`?

File: app/client/src/widgets/BaseWidget.tsx [hunk 10]
```diff
@@ -351,6 +352,9 @@ abstract class BaseWidget<
         resizeDisabled={this.props.resizeDisabled}
         selected={this.props.selected}
         topRow={this.props.topRow}
+        visible={
+          this.props.isVisible === undefined ? true : this.props.isVisible
```
Comment (ashit-rath) [inline app/client/src/widgets/BaseWidget.tsx:356]: `this.props.isVisible ?? true`.
Though I believe `isVisible` cannot be `undefined`. Check `withWidgetProps` where we are setting the `isVisible` property.

File: app/client/src/widgets/BaseWidget.tsx [hunk 11]
```diff
@@ -342,6 +342,7 @@ abstract class BaseWidget<
       <PositionedContainer
         componentHeight={componentHeight}
         componentWidth={componentWidth}
+        disabled={this.props.isDisabled}
```
Comment (ashit-rath) [inline app/client/src/widgets/BaseWidget.tsx:345]: Let's stick to the convention and rename `disabled` -> `isDisabled`

File: app/client/src/widgets/BaseWidget.tsx (hunk 10 above)
Comment (ashit-rath) [reply app/client/src/widgets/BaseWidget.tsx:356]: Let's stick to the convention and rename `visible` -> `isVisible`

File: app/client/src/widgets/CheckboxGroupWidget/component/index.tsx [hunk 12]
```diff
@@ -48,7 +47,7 @@ const InputContainer = styled.div<ThemeProp & InputContainerProps>`
   width: 100%;
   flex-grow: 1;
   height: 100%;
-  
+
```
Comment (ashit-rath) [inline app/client/src/widgets/CheckboxGroupWidget/component/index.tsx:50]: Can we remove the new line?

File: app/client/src/widgets/CheckboxGroupWidget/component/index.tsx [hunk 13]
```diff
@@ -236,15 +236,15 @@ function CheckboxGroupComponent(props: CheckboxGroupComponentProps) {
...
+          [...options].map((option: OptionProps, index: number) => (
             <StyledCheckbox
               accentColor={accentColor}
               borderRadius={borderRadius}
               checked={(selectedValues || []).includes(option.value)}
               disabled={isDisabled}
               hasError={!isValid}
               inline={isInline}
-              key={generateReactKey()}
+              key={`${widgetId}-checkbox-${index}`}
```
Comment (ashit-rath) [inline app/client/src/widgets/CheckboxGroupWidget/component/index.tsx:247]: Is this change relevant to this PR?

File: app/client/src/widgets/ContainerWidget/component/index.tsx [hunk 14]
```diff
@@ -75,9 +75,10 @@ function ContainerComponentWrapper(props: ContainerComponentProps) {
         props.shouldScrollContents ? getCanvasClassName() : ""
       } ${generateClassName(props.widgetId)}`}
       containerStyle={containerStyle}
+      ref={containerRef}
       // Before you remove: generateClassName is used for bounding the resizables within this canvas
```
Comment (ashit-rath) [inline app/client/src/widgets/ContainerWidget/component/index.tsx:79]: Can we move this comment to the right place?

File: app/client/src/widgets/ModalWidget/component/index.tsx [hunk 15]
```diff
@@ -171,6 +171,9 @@ export default function ModalComponent(props: ModalComponentProps) {
     setTimeout(() => {
       setModalPosition("unset");
     }, 100);
+
+    modalContentRef.current?.focus();
```
Comment (ashit-rath) [inline app/client/src/widgets/ModalWidget/component/index.tsx:175]: Are we suppose to call this on mount of the component?

**Review by ashit-rath — APPROVED** [review]
