### PR TITLE
fix: show pull button when behind X commits | git

### LINKED ISSUE #15331: [Feature]: Show pull button on Deploy tab, when there are no changes to commit, but local is ahead of remote repo
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Screenshot 2022-07-20 at 11 55 30 AM

### Why should this be worked on?

Even though pull functionality exists in bottom bar, we should show pull button here too. gitV2.

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

- Show pull button when current local branch is X commits behind remote branch.
- Refactor GitChangeList component to remove prop.

Fixes #15331

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually, this requires extra commits on remote repo which cannot be done as of today.

## After fix / solution

Screenshot 2022-10-08 at 4 08 57 PM

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IAmAnubhavSaini** [comment]
Failing tests

Screenshot 2022-10-09 at 12 21 19 PM
Screenshot 2022-10-09 at 12 20 59 PM

**Comment by IAmAnubhavSaini** [comment]
Only one (flaky) test failing.

Screenshot 2022-10-10 at 12 19 48 PM

**Comment by RakshaKShetty** [comment]
@Debsourabh, @IAmAnubhavSaini the modal look clumsy when all 3 buttons are displayed together as in the screenshot
image
Else the pull changes button will be displayed when the commits are behind and the user can pull the changes

File: app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx [hunk 1]
```diff
@@ -77,6 +77,7 @@ import { Variant } from "components/ads";
 import DiscardChangesWarning from "../components/DiscardChangesWarning";
 import { changeInfoSinceLastCommit } from "../utils";
 import { ScrollIndicator } from "design-system";
+import { GitStatusData } from "reducers/uiReducers/gitSyncReducer";
```
Comment (berzerkeer) [inline app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx:80]: @IAmAnubhavSaini since we split the reducers , I think we should import it like `@appsmith/reducers/uiReducers/gitSyncReducer`. What you have works fine, but I think this will lead to import being inconsistent. 

cc: @ankitakinger  correct me if I am wrong.

Comment (ankitakinger) [reply app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx:80]: @berzerkeer this import statement is correct because we have only split the following files in reducers:
image


Since `gitSyncReducer` is not split, the import here is correct.

Comment (berzerkeer) [reply app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx:80]: Got it thank you.

**Comment by IAmAnubhavSaini** [comment]
Failing test

Screenshot 2022-10-14 at 10 23 39 AM

**Comment by RakshaKShetty** [comment]
@IAmAnubhavSaini The pull changes button is now displayed when we are x commits behind. Its working as expected

**Review by mohanarpit — APPROVED** [review]
