### PR TITLE
Parameter missing for email template replace

### LINKED ISSUE #1306: [Bug] Email Button doesn't work
## Description

In the role updated email, the goto appsmith button is not clickable

### Steps to reproduce the behaviour:
1. Invite someone to an org
2. Update their role
3. Check their email
4. The email informs them about the role update but the go to appsmith CTA is broken

### PR DESCRIPTION
**Pull request by shinnlok**
## Description

Fixes #1306

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Invite user to organization
- Update role
- Click on link in email

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/OrganizationController.java [hunk 1]
```diff
@@ -51,8 +52,10 @@ public OrganizationController(OrganizationService organizationService, UserOrgan
     }
 
     @PutMapping("/{orgId}/role")
-    public Mono<ResponseDTO<UserRole>> updateRoleForMember(@RequestBody UserRole updatedUserRole, @PathVariable String orgId) {
-        return userOrganizationService.updateRoleForMember(orgId, updatedUserRole)
+    public Mono<ResponseDTO<UserRole>> updateRoleForMember(@RequestBody UserRole updatedUserRole,
+                                                           @PathVariable String orgId,
+                                                           @RequestHeader("Origin") String originHeader) {
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/OrganizationController.java:57]:
```suggestion
                                                           @RequestHeader(name = "Origin", required = false) String originHeader) {
```

**Review by trishaanand — APPROVED** [review]
