### PR TITLE
fix: Allow Multiselect DefaultValue to accept numbers

### LINKED ISSUE #11714: [Bug]: Multi select dropdown does not pre populate single values .
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I  have  a multi  dropdown  list with some integer values . I am able to select and save single as well as multi values . But while am trying to pre populate these values from my  db query , the single value is not prepopulating to the list.

Screenshot (26)

### Steps To Reproduce

1. Create a page  with multiselect dropdown widget  and set values into it.
2. Select single value from the dropdown and save to  database.
3. Create  a modal for  edit  these values  and set default values from the database query.

### Environment

Production

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description
Allow number to be passed as default Value in Multiselect

Fixes #11714

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/multiselect-prepopulate-value-with-number 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.77 **(0.01)** | 37.22 **(0.02)** | 35.36 **(0)** | 56.02 **(0)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :green_circle: | app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx | 80.46 **(0.46)** | 56.67 **(6.67)** | 70.59 **(0)** | 80.49 **(0.49)**</details>

### CODE REVIEW

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 1]
```diff
@@ -22,8 +22,8 @@ export function defaultOptionValueValidation(
   props: MultiSelectWidgetProps,
   _: any,
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:23]: Instead of `any` here try using `LoDashStatic`. This would help remove any `as string` or `as []` type assertion which we should try to avoid as much as possible.

After making this change please do go through the whole validation function and see if all the `as` assertions can be removed.

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 2]
```diff
@@ -67,11 +67,10 @@ export function defaultOptionValueValidation(
     }
   }
 
-  if (_.isString(value) && (value as string).trim() === "") {
-    isValid = true;
-    parsed = [];
-    message = "";
-  } else if (Array.isArray(value)) {
+  /*
+   * When value is "['green', 'red']", "[{label: 'green', value: 'green'}]" and "green, red"
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:71]: This block won't deal with strings, right? If not, can we update the comment?

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 3]
```diff
@@ -107,6 +106,35 @@ export function defaultOptionValueValidation(
...
+  }
+
+  /*
+   * When value is an empty string
+   */
+  if (_.isString(value) && (value as string).trim() === "") {
+    isValid = true;
+    parsed = [];
+    message = "";
+  } else if (_.isNumber(value)) {
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:124]: Can we add a comment in[ line 52 ](https://github.com/appsmithorg/appsmith/pull/12138/files#diff-c321b0cc1a03b818cf65267b761ad882f25a18957c398e7671f7a61434f3a9dcR52)stating that when we get a number as a value like `"100"`, it's a valid JSON and gets parsed to a number whereas `"test"` is not a valid JSON and we treat it as a CSV?

I feel like this particular value is an edge case and I think we should explicitly mention that.

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 4]
```diff
@@ -107,6 +106,35 @@ export function defaultOptionValueValidation(
...
+    /*
+     * When value is a number
+     */
+    isValid = true;
+    parsed = [value];
+    message = "";
+  } else if (_.isString(value)) {
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:131]: We are checking `_.isString` at 2 places can we combine both into one?

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.test.tsx [hunk 5]
```diff
@@ -26,6 +26,18 @@ describe("defaultOptionValueValidation - ", () => {
     });
   });
 
+  it("should get tested with a number", () => {
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.test.tsx:29]: Can we add test cases for singular values like `"100"` and `"test"` if not present?

**Review by ashit-rath — COMMENTED** [review]
Looks good Tolu!
Wanted to know have we made sure that this takes care of all the cases for default value we were discussing the other day?

**Comment by ashit-rath** [comment]
@Tooluloope Can we make the title more descriptive? Would help with the release notes
Also, could you also make sure the checklist in the PR description is also marked correctly?

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:71]: it actually does, 

```
"['green', 'red']", "[{label: 'green', value: 'green'}]" and "green, red" 
is converted to

['green', 'red'] , [{label: 'green', value: 'green'}] , ['green', 'red']

```

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx (hunk 3 above)
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:124]: Should we parse "100" to a number or leave it as a string?

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 6]
```diff
@@ -67,51 +71,64 @@ export function defaultOptionValueValidation(
...
        */
-      if (hasUniqueValues(value.map((val) => val.value) as [])) {
+      if (hasUniqueValues(value.map((val) => val.value))) {
         isValid = true;
         parsed = value;
-        message = "";
       } else {
-        isValid = false;
         parsed = [];
         message = "path:value must be unique. Duplicate values found";
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:98]: The message here is a bit different from the one in line 87. Can we move this message to a constant like 

```js
const UNIQUENESS_MESSAGE = "..."
```
Also, can we do the same thing for the messages in line 105 and line 134?
 Putting it in constant makes it DRY and less prone to inconsistency.

Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:98]: The reason behind this is that The first one is an array of strings, while the other is an array of objects hence the use of `path`.

Also for consistency, `path: value` is also used in Radio Widget.

Comment (ashit-rath) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:101]: Got it!

**Review by ashit-rath — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Tested this PR and it is working as expected
