### PR TITLE
fix: comment pins related issues

### LINKED ISSUE #5100: z-index issues related to comments

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
- [x] latest pin should be on top: this is the render order issue. Reused the sorting mech employed for listing the comment cards on left sidebar
- [x] unpublished pin z - index problem
- [x] pin cutoff problem at the top of canvas

Fixes #5100 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
* manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/collab-z-index-issues 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.12 **(0.11)** | 37.03 **(0.15)** | 34.04 **(0.09)** | 55.67 **(0.11)**
 :sparkles: :new: | **app/client/src/comments/AppComments/AppCommentThreads.tsx** | **65.79** | **31.25** | **40** | **64.86**
 :sparkles: :new: | **app/client/src/comments/AppComments/AppCommentsPlaceholder.tsx** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/src/comments/CommentThread/connectedCommentThread.tsx** | **75** | **100** | **0** | **75**
 :green_circle: | app/client/src/comments/inlineComments/Comments.tsx | 97.37 **(0.15)** | 90 **(0)** | 100 **(0)** | 100 **(0)**
 :green_circle: | app/client/src/pages/Editor/MainContainerLayoutControl.tsx | 86.21 **(0.5)** | 50 **(0)** | 57.14 **(7.14)** | 86.21 **(0.5)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 76.85 **(29.63)** | 52.17 **(40.58)** | 69.23 **(26.92)** | 82.89 **(40.78)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**</details>

### CODE REVIEW

File: app/client/src/comments/inlineComments/InlineCommentPin.tsx [hunk 1]
```diff
@@ -224,7 +224,8 @@ function InlineCommentPin(props: Props) {
   };
 
   if (!commentThread) return null;
-
+  // eslint-disable-next-line no-console
+  console.log({ seq: commentThread.sequenceId, id: commentThreadId });
```
Comment (rishabhsaxena) [inline app/client/src/comments/inlineComments/InlineCommentPin.tsx:228]: idle logs

Comment (rishabhsaxena) [inline app/client/src/comments/inlineComments/InlineCommentPin.tsx:228]: idle log

File: app/client/src/comments/inlineComments/Comments.tsx [hunk 2]
```diff
@@ -64,19 +65,26 @@ export const useSelectCommentThreadUsingQuery = () => {
...
+  const commentThreadIds = useSortedCommentThreadIds(
+    applicationId,
+  ).filter((id) => (commentThreadIdsByRef as string[]).includes(id));
   const unpublishedCommentThread = useSelector(
     unpublishedCommentThreadSelector(refId),
   );
   const commentThreadIdInUrl = useSelectCommentThreadUsingQuery();
-
+  // eslint-disable-next-line no-console
+  console.log({
```
Comment (rishabhsaxena) [inline app/client/src/comments/inlineComments/Comments.tsx:80]: idle log

File: app/client/src/comments/inlineComments/Comments.tsx [hunk 3]
```diff
@@ -64,19 +65,26 @@ export const useSelectCommentThreadUsingQuery = () => {
...
+    commentsThreadIds:
+      Array.isArray(commentThreadIds) && commentThreadIds.reverse(),
+  });
   return (
     <>
-      {Array.isArray(commentsThreadIds) &&
-        commentsThreadIds.map((commentsThreadId: any) => (
+      {Array.isArray(commentThreadIds) &&
+        commentThreadIds.map((commentsThreadId: any) => (
```
Comment (rishabhsaxena) [inline app/client/src/comments/inlineComments/Comments.tsx:87]: I guess would need to loop in reverse here, after we remove the log since that might be mutating the array

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/comments/inlineComments/Comments.tsx (hunk 3 above)
Comment (rishabhsaxena) [reply app/client/src/comments/inlineComments/Comments.tsx:87]: I think we would need to slice it to avoid mutating the original array

Comment (pranavkanade) [reply app/client/src/comments/inlineComments/Comments.tsx]: fixed

File: app/client/src/comments/inlineComments/Comments.tsx [hunk 4]
```diff
@@ -64,25 +65,30 @@ export const useSelectCommentThreadUsingQuery = () => {
...
-        commentsThreadIds.map((commentsThreadId: any) => (
-          <MemoisedInlinePageCommentPin
-            commentThreadId={commentsThreadId}
-            focused={commentThreadIdInUrl === commentsThreadId}
-            key={commentsThreadId}
-          />
-        ))}
+      {Array.isArray(commentThreadIds) &&
+        commentThreadIds
+          .reverse()
```
Comment (rishabhsaxena) [inline app/client/src/comments/inlineComments/Comments.tsx:84]: think should slice this to avoid mutation?

File: app/client/src/comments/inlineComments/Comments.tsx [hunk 5]
```diff
@@ -64,25 +65,30 @@ export const useSelectCommentThreadUsingQuery = () => {
...
 function Comments({ refId }: { refId: string }) {
-  const applicationId = useSelector(getCurrentApplicationId);
-  const commentsThreadIds = useSelector(
+  const applicationId = useSelector(getCurrentApplicationId) as string;
+  const commentThreadIdsByRef = useSelector(
     refCommentThreadsSelector(refId, applicationId),
   );
+  const commentThreadIds = useSortedCommentThreadIds(
+    applicationId,
+  ).filter((id) => (commentThreadIdsByRef as string[]).includes(id));
```
Comment (rishabhsaxena) [inline app/client/src/comments/inlineComments/Comments.tsx:74]: nit: would it be possible to just sort the `commentThreadIdsByRef` instead of the app comments and then filtering it? we could pass `commentThreadIdsByRef` to  `getSortedAndFilteredAppCommentThreadIds` instead of `appCommentIds`

**Review by rishabhsaxena — DISMISSED** [review]

File: app/client/src/comments/inlineComments/Comments.tsx (hunk 5 above)
Comment (pranavkanade) [reply app/client/src/comments/inlineComments/Comments.tsx]: Nice catch, pushed a fix

File: app/client/src/comments/AppComments/AppCommentThreads.tsx [hunk 6]
```diff
@@ -30,38 +30,49 @@ const Container = styled.div`
...
-function AppCommentThreads() {
-  const dispatch = useDispatch();
-  const commentThreadIdFromUrl = useSelectCommentThreadUsingQuery();
-  const applicationId = useSelector(getCurrentApplicationId) as string;
-  const appCommentThreadsByRefMap = useSelector(
-    applicationCommentsSelector(applicationId),
-  );
-  const appCommentThreadIds = getAppCommentThreads(appCommentThreadsByRefMap);
+export const useSortedCommentThreadIds = (
+  applicationId: string,
```
Comment (rishabhsaxena) [inline app/client/src/comments/AppComments/AppCommentThreads.tsx:34]: `applicationId` not needed anymore?

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/comments/AppComments/AppCommentThreads.tsx (hunk 6 above)
Comment (pranavkanade) [reply app/client/src/comments/AppComments/AppCommentThreads.tsx]: refactored

**Review by rishabhsaxena — APPROVED** [review]

**Review by rishabhsaxena — APPROVED** [review]
