### PR TITLE
fix: QA callouts for list v2

### LINKED ISSUE #19941: TAsk: QA Callout-2
https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

1. Issue with Pasting a copied List when the mouse pointer is in the second list item  https://www.loom.com/share/291b928a8b564cd6802e35968b5173be
2. Canvas crashes when we click on nested list Item in both Client side and Server Side pagination https://www.loom.com/share/64e36ec5d1b24f8cab45d68b218db222

https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0

Fixes #19941

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 1]
```diff
@@ -736,6 +751,21 @@ class ListWidget extends BaseWidget<
     this.props.updateWidgetMetaProperty("selectedItemKey", null);
   };
 
+  /**
+   * Clearing selected Items and triggered items when the list widget is mounted
+   * because the MetaWidgetGenerator also clears all cached data when mounted or re-mounted
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:756]: Which part are you referring to where the cache is cleared in MetaWidgetGenerator?

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 2]
```diff
@@ -736,6 +751,21 @@ class ListWidget extends BaseWidget<
     this.props.updateWidgetMetaProperty("selectedItemKey", null);
   };
 
+  /**
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:754]: Move this comment to the place this is called i.e in `componentDidMount`

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx (hunk 1 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:756]: The `rowCacheData`. 
When we unmount the List Widget, the data in `rowCacheData` is lost and on-mount; since `SelectItemKey` is a meta property, the value is mounted with the List widget. 

So if the List widget is mounted on a page that doesn't have the `SelectItemKey`, there's no how we can grab the data since it is ServerSide Paginated.

This kind of case happens when you select a row or trigger a row and navigate away from the canvas to the query page.

Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:762]: rowCacheData is not cleared when the Listwidget in umounted. We used to do that but I had to remove that logic because of nested list.
When the outer list widget changes page, the inner list in the prev page is unmounted and was removing all the cache data.
When we go back to the prev page, no cache for inner list and new ids were generated thus leading to meta props being lost.


Now with this logic when you switch pages, the inner list will mount/unmount and that would cause a reset.

**Review by ashit-rath — APPROVED** [review]
