### PR TITLE
fix: UQI UI alignment fixes

### LINKED ISSUE #15022: [Bug]: Fix UI alignment of form controls for SImplified crud queries
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The current UI of new form controls in UQI is out of sync. Needs to be updated.

### Steps To Reproduce

1. Create new gsheets form
2. The UI is misaligned 

image

### Public Sample App

_No response_

### Version

cloud - release

### PR DESCRIPTION
**Pull request by ayushpahwa**
## Description

Minor changes to bring UQI components in sync with design system and fix alignment issues

Fixes #15022 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/formControls/DynamicTextFieldControl.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ import { actionPathFromName } from "components/formControls/utils";
 import { EvaluationSubstitutionType } from "entities/DataTree/dataTreeFactory";
 
 const Wrapper = styled.div`
-  width: 75%;
+  width: 872px;
```
Comment (albinAppsmith) [inline app/client/src/components/formControls/DynamicTextFieldControl.tsx:27]: nit: Can we use dynamic width for wrappers?

**Review by albinAppsmith — APPROVED** [review]

File: app/client/src/components/formControls/DynamicTextFieldControl.tsx (hunk 1 above)
Comment (ayushpahwa) [reply app/client/src/components/formControls/DynamicTextFieldControl.tsx:27]: Hey Albin, this can't be done since the entity sector component is going out of sync with the rest of the components
