### PR TITLE
Fix: Update debugger placeholder text for non-mac

### LINKED ISSUE #5106: [Bug] Toggle debugger hotkey issues
## Description

- [x] Show text based on OS (cmd or ctrl), currently it shows `cmd` even for ubuntu
- [x] Update text to indicate it can be used to toggle (show or hide) the debugger
- [x] Verify / fix if the hotkey works on windows and linux (ubuntu)

### PR DESCRIPTION
**Pull request by akash-codemonk**
Fixes #5106

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/toggle-debugger 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.54 **(0)** | 33.55 **(-0.01)** | 29.38 **(0)** | 52.17 **(0)**
 :red_circle: | app/client/src/components/editorComponents/Debugger/helpers.tsx | 77.05 **(-0.92)** | 72.73 **(-7.27)** | 33.33 **(0)** | 78.43 **(-1.16)**</details>

### CODE REVIEW

File: app/client/src/constants/messages.ts [hunk 1]
```diff
@@ -338,7 +338,7 @@ export const BACK = () => "BACK";
 // Debugger
 export const CLICK_ON = () => "🙌 Click on ";
 export const PRESS = () => "🎉 Press ";
-export const OPEN_THE_DEBUGGER = () => " to open the debugger";
+export const OPEN_THE_DEBUGGER = () => " to show/hide the debugger";
```
Comment (rishabhsaxena) [inline app/client/src/constants/messages.ts:341]: nitpick:
```suggestion
export const OPEN_THE_DEBUGGER = () => " to show / hide the debugger";
```

**Review by rishabhsaxena — DISMISSED** [review]
nitpick

**Review by rishabhsaxena — APPROVED** [review]
