### PR TITLE
fix: Allow serializing child widget if it is a substring of the conta…

### LINKED ISSUE #35224: [Bug]: widgets not being committed to Git when child of a container has a name that is part of the parent name
[Slack Thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1721823202896379?thread_ts=1721823202.896379&cid=C0341RERY4R)

### PR DESCRIPTION
**Pull request by nidhi-nair**
…iner

## Description

Fixes #35224

## Automation

/ok-to-test tags="@tag.Git"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10177962011>
> Commit: 2c3878c285f6c34fa0f9e04c29fa6c022d8e6086
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10177962011&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Git`
> Spec:
> <hr>Wed, 31 Jul 2024 10:09:14 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Introduced a new method to generate the correct path for canvas widgets, enhancing the handling and organization of widget files.
  
- **Bug Fixes**
  - Improved the handling of widget names in file paths to ensure only the trailing instance is removed, enhancing path integrity and preventing unintended modifications.
  
- **Tests**
  - Added a new test case to validate the path generation for canvas widgets, expanding coverage and ensuring functionality.

### CODE REVIEW

**Review by sondermanish — APPROVED** [review]

File: app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsCEImpl.java [hunk 1]
```diff
@@ -266,7 +266,7 @@ protected Set<String> updateEntitiesInRepo(ApplicationGitReference applicationGi
                     if (!DSLTransformerHelper.hasChildren(jsonObject)
                             && !DSLTransformerHelper.isTabsWidget(jsonObject)) {
                         // Save the widget as a directory or Save the widget as a file
-                        childPath = childPath.replace(widgetName, CommonConstants.EMPTY_STRING);
+                        childPath = childPath.replaceAll(widgetName + "$", CommonConstants.EMPTY_STRING);
```
Comment (sondermanish) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsCEImpl.java:269]: please provide an example of this in the comments.
