### PR TITLE
fix: Hide generate page button in integration home screen for onboarding

### LINKED ISSUE #7405: [Bug] Widgets overlap when generate page and signposting feature is used during user on-boarding walkthrough
## Description
If during user onboarding, signposting option is clicked and custom DB is selected for generating a page then clicking on page generate and then on resuming onboarding tutorial observe super standup widget overlap with existing generate page template widgets.

### Steps to reproduce the behaviour:
1. Go to welcome tutorial on the home page and start the tutorial
2. On the first page of the tutorial, click on Create a Query on the Entity Explorer and generate a page from either a sample DB or by adding your own datasource
3. Now resume the tutorial and go through with creating a new query and click through on the tutorial - observe that the super standup widget template is generated over the generate page template. Deploying the app, deploys all widgets.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[LOOM DEMO](https://www.loom.com/share/140beaaed9f1475890034a070983659a)

### PR DESCRIPTION
**Pull request by akash-codemonk**
Hide generate page button in integration home screen for onboarding

Related to https://github.com/appsmithorg/appsmith/issues/7405#issuecomment-920598211
Fixes #7405 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/onboarding-generate-page 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx | 57.33 **(1.17)** | 51.85 **(0)** | 0 **(0)** | 57.33 **(1.17)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx [hunk 1]
```diff
@@ -239,21 +241,23 @@ function DatasourceCard(props: DatasourceCardProps) {
...
-            >
-              <GenerateTemplateButton
-                category={Category.tertiary}
-                className="t--generate-template"
-                disabled={!supportTemplateGeneration}
-                onClick={routeToGeneratePage}
-                text="GENERATE NEW PAGE"
-              />
-            </TooltipComponent>
+            <Boxed step={OnboardingStep.FINISH}>
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx:244]: should we add a `alwaysHidden` flag instead, since it should always be hidden?

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx (hunk 1 above)
Comment (akash-codemonk) [reply app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx:244]: `step={OnboardingStep.FINISH}` will hide it until onboarding is finished. We go to OnboardingStep.FINISH step after deploy.

**Review by rishabhsaxena — APPROVED** [review]

**Review by rishabhsaxena — APPROVED** [review]
