### PR TITLE
fix: update def on focus

### LINKED ISSUE #14749: [Bug]: Lot of deviation in time taken to setup autocomplete
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`startAutoComplete`  took 3600ms in one profile and 2400ms in other profile. That is 50% deviation, while the rest of the code has around 2.5% deviation.

It would help with performance monitoring and performance in general if this deviation can be reduced.
Profiles can be found in the slack thread.

https://theappsmith.slack.com/archives/C024GUDM0LT/p1655467501490139

### Steps To Reproduce

Check the profiles on slack thread attached.

### Public Sample App

_No response_

### Version

Both / Latest

### LINKED ISSUE #16206: [Task]: update autocomplete defs on code editor focus
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Currently, autocomplete customDataTree defs are updated when the code editor gets mounted on the tree. As a result, when two code editor with different customDataTree is present on the property pane, the second code editor's defs overwrites the previous one. So we need to update the defs only when code editor gets focused.

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

It was noticed that the TernServer's `deleteDefs` and `addDefs` method are expensive which were internally ran when `TernServer.updateDef` API was called.
- Earlier we were running `TernServer.updateDef` for each codeEditor onMount which was expensive and not required. Now, it is changed to be done only when the editor is focused.
    - Avoiding to run `TernServer.updateDef`  for each codeEditor instance.
- In case when editor with the same customDataTreeDef's requirement is opened in that case we do a deep comparison of previous `customDataTreeDef` and only if different then trigger `TernServer.updateDef`
 

Fixes #16206 
Fixes #14749

## Type of change

- Enhancement to support `editedValue` feature in autocomplete added [here](https://github.com/appsmithorg/appsmith/pull/15954)
- Performance Improvement 

## How Has This Been Tested?

- [ ] Check performance impact

Future test 
- [ ] Once Table Widget `evaluatedValue` [feature](https://github.com/appsmithorg/appsmith/pull/15954/files) is added autocompletion test for property supporting `evaluatedValue` and property which doesn’t to make sure customDataTreeDef updates

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rishabh-Rathod — COMMENTED** [review]
Self-review done.

File: app/client/src/utils/autocomplete/customDefUtils.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+  AdditionalDynamicDataTree,
+  customTreeTypeDefCreator,
+} from "./customTreeTypeDefCreator";
+import TernServer from "./TernServer";
+
+let lastCustomDataDef: AdditionalDynamicDataTree | undefined;
+
+export const updateCustomDef = (customData?: AdditionalDynamicDataTree) => {
+  if (customData && !isEmpty(customData)) {
+    const customDataDef = customTreeTypeDefCreator(customData);
```
Comment (arunvjn) [inline app/client/src/utils/autocomplete/customDefUtils.ts:14]: Can we cache last customData ? We can compare customData and lastCustomData. Avoids customTreeTypeDef calculation

File: app/client/src/utils/autocomplete/customDefUtils.ts [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+      debug(
+        "Tern: updateDef for customDataTree took",
+        (performance.now() - start).toFixed(),
+        "ms",
+      );
+
+      lastCustomDataDef = customDataDef;
+    }
+  } else if (lastCustomDataDef) {
```
Comment (arunvjn) [inline app/client/src/utils/autocomplete/customDefUtils.ts:28]: Can you explain what happens here ? If the lastCustomData and the newCustomData are the same, will it not simply remove the definitions from Tern ?

Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/customDefUtils.ts:28]: When `customData` is not sent or is empty in those cases we need to `removeDef`.

As `removeDef` also is expensive call we try to only do it once to actually remove customDataDef. 

Once we run removeDef
- lastCustomDataDef becomes `undefined` and hence we have a check that only if `lastCustomDataDef` was defined then run removeDef.

Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/customDefUtils.ts:28]: > it will remove the definitions right ?

No, it will do nothing. 
it will go inside 1st if the case where customData if defined then it will generate customDataDef and deep compare with previous customDataDef as they are same it will not go inside this condition`if (!equal(lastCustomDataDef, customDataDef)) {`

Comment (arunvjn) [reply app/client/src/utils/autocomplete/customDefUtils.ts:28]: My bad. Read it wrong!

**Review by arunvjn — APPROVED** [review]
Looks good!

**Review by arunvjn — APPROVED** [review]

**Review by arunvjn — APPROVED** [review]

File: app/client/src/utils/autocomplete/customDefUtils.ts [hunk 3]
```diff
@@ -0,0 +1,38 @@
+import equal from "fast-deep-equal/es6";
+import { isEmpty } from "lodash";
+import { debug } from "loglevel";
+import {
+  AdditionalDynamicDataTree,
+  customTreeTypeDefCreator,
+} from "./customTreeTypeDefCreator";
+import TernServer from "./TernServer";
+
+let lastCustomDataDef: AdditionalDynamicDataTree | undefined;
```
[the remark this answers is not in the document]
Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/customDefUtils.ts]: done

**Review by sbalaji1192 — APPROVED** [review]
