### PR TITLE
fix: Preserve query execution data on name refactor

### LINKED ISSUE #28985: [Bug]: Execution result is lost when a query is renamed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Last execution results of a query gets lost when it is renamed.

### Steps To Reproduce

1. Drag & drop a table widget
2. Create a rest API
3. Bind the API to the table widget and ensure that the table renders data
4. Rename the API

Observe that the table is empty

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Code changes to preserve execution data when a Query/JS Object is renamed.
>
#### PR fixes following issue(s)
Fixes #28985
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
#### How Has This Been Tested?
- [x] Manual
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/workers/Evaluation/dataStore/index.ts [hunk 1]
```diff
@@ -11,6 +11,10 @@ export default class DataStore {
     set(DataStore.store, fullPath, value);
   }
 
+  static unSetActionData(fullPath: string) {
```
Comment (ohansFavour) [inline app/client/src/workers/Evaluation/dataStore/index.ts:14]: This method is already implemented in `deleteActionData`

**Review by ohansFavour — DISMISSED** [review]

**Review by ohansFavour — APPROVED** [review]
