### PR TITLE
fix: Form message component link issue

### LINKED ISSUE #18086: [Bug]: submitting password reset fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On a self-hosted instance, when a user tries to reset their password an email is sent and the link in the email navigates to a password reset page. When submitting a new password an `Internal server error` message appears. 

### Steps To Reproduce

1. go to `<host>/user/forgotPassword`
2. type in registered email and click reset
3. click on Reset Password link in email 
4. on reset password page (`<host>/user/resetPassword?token=<token>`), type in new password and click Reset 
5. password reset fails

backend.log stack:
`
[2022-11-03 15:58:04,196]  - Error clearing user sessions
org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding 
serialization for DefaultDeserializer?; nested exception is java.io.StreamCorruptedException: invalid stream header: 61707073
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:84)
        at org.springframework.data.redis.serializer.DefaultRedisElementReader.read(DefaultRedisElementReader.java:49)
        at org.springframework.data.redis.serializer.RedisSerializationContext$SerializationPair.read(RedisSerializationContext.java:272)
        at org.springframework.data.redis.core.DefaultReactiveHashOperations.readHashValue(DefaultReactiveHashOperations.java:353)
        at org.springframework.data.redis.core.DefaultReactiveHashOperations.deserializeHashEntry(DefaultReactiveHashOperations.java:357)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:543)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:984)
        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
        at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onNext(RedisPublisher.java:886)
        at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:291)
        at io.lettuce.core.output.StreamingOutput$Subscriber.onNext(StreamingOutput.java:64)
        at io.lettuce.core.output.KeyValueListOutput.set(KeyValueListOutput.java:72)
        at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:810)
        at io.lettuce.core.protocol.RedisStateMachine.handleBytes(RedisStateMachine.java:572)
        at io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:206)
        at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:334)
        at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:295)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:841)
        at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:792)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:766)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:658)
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.StreamCorruptedException: invalid stream header: 61707073
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:78)
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:36)
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:82)
        ... 39 common frames omitted
Caused by: java.io.StreamCorruptedException: invalid stream header: 61707073
        at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:935)
        at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:374)
        at org.springframework.core.ConfigurableObjectInputStream.<init>(ConfigurableObjectInputStream.java:65)
        at org.springframework.core.ConfigurableObjectInputStream.<init>(ConfigurableObjectInputStream.java:51)
        at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:70)
        at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:73)
        ... 41 common frames omitted`

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Self Hosted 1.8.6

Front logo [Front conversations](https://app.frontapp.com/open/top_5v6oc)

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

While resetting the password, the link which shared over mail was showing 'oops something went wrong' screen (shown below).

Screenshot 2022-11-18 at 9 49 23 AM

This issue is fixed and now it will show appropriate message and link. This happened during design system migration.

Fixes #18086

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested in local by taking the token link from prod password reset mail

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/pages/UserAuth/ForgotPassword.tsx [hunk 1]
```diff
@@ -109,6 +109,7 @@ export const ForgotPassword = withTheme(
                 },
               ]}
               intent="warning"
+              linkAs={Link}
```
Comment (hetunandu) [inline app/client/src/pages/UserAuth/ForgotPassword.tsx:112]: Instead of passing the component and it's props separately, lets just pass the whole component with the props assigned from here.

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/pages/UserAuth/ForgotPassword.tsx (hunk 1 above)
Comment (albinAppsmith) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:112]: Screenshot 2022-11-18 at 10 09 07 AM
This is the code from design system component. Do you think this way it won't scale?

Comment (hetunandu) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:112]: Yes. Seeing this, I feel there is too much logic on this component and will make it inflexible. Everything inside "StyledAction" should be just a prop passed down and rendered

Comment (albinAppsmith) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:112]: Yeah, but now if I need to change this I need to touch all places the component being used... To summarise do you still want me to accept the link as a whole component with props?

Comment (hetunandu) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:112]: Still yes. The change seems big now, but it will add a lot of flexibility for future design changes

**Review by hetunandu — DISMISSED** [review]

**Comment by shadabbuchh** [comment]
Tested this PR.
Now after clicking the `Reset Password` link the user is directed to the appropriate page without any errors and is able to reset the password.
https://www.loom.com/share/8f60d7aa29364c58a61d8618ff1f46ec
