### PR TITLE
fix: Firestore where condition issue

### LINKED ISSUE #6060: [Bug]In Firestore for "Get Documents in Collection" method the "where condition" doesn't work for Number, Null, Boolean, Array of Numbers, Geolocation
## Description In Firestore for "Get Documents in Collection" method the "where condition" doesn't work for Number, Null, Boolean, Array of Numbers, Geolocation
[What happened]

https://loom.com/share/0665bef56ad14ceb9a3b00bbeaf8594a

### Steps to reproduce the behaviour:
1.Add the new data source Firestore
2.Select method  as "get documents in collection"
3.Add document/collection path
4. under where the condition 
5. add the path and the value should be a "number" data type 
6. then the output will be displayed as empty array
image

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [ safari]
- Environment [release frozen]

### PR DESCRIPTION
**Pull request by leotom2000**
## Description
Firestore Unit test for testing Array

Fixes #6060

## Type of change

- Added Unit Test

## How Has This Been Tested?

Added Unit test

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java [hunk 1]
```diff
@@ -36,11 +36,7 @@
 import java.sql.Timestamp;
 import java.text.ParseException;
 import java.text.SimpleDateFormat;
-import java.util.ArrayList;
-import java.util.Collections;
-import java.util.HashMap;
-import java.util.List;
-import java.util.Map;
+import java.util.*;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:39]: Please replace it with specific classes that need to be imported. In general we don't want to use wild card import statements because of the following: https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java [hunk 2]
```diff
@@ -977,6 +981,140 @@ public void testTimeStampWhereConditional() {
                 .verifyComplete();
     }
 
+    @Test
+    public void testArrayContainsNumberWhereConditional() {
+        Map<String, Object> configMap = new HashMap<>();
+        setValueSafelyInFormData(configMap, COMMAND, "GET_DOCUMENT");
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:987]: where condition is only evaluated when command is `GET_COLLECTION`. IMO, this test case does ignores the where condition completely. Can you please update the command to `GET_COLLECTION` ?

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java [hunk 3]
```diff
@@ -977,6 +981,140 @@ public void testTimeStampWhereConditional() {
...
+        actionConfiguration.setFormData(configMap);
+
+        List params = new ArrayList();
+        Param param = new Param();
+        param.setKey("Input1.text");
+        param.setValue("phone_numbers");
+        params.add(param);
+        param = new Param();
+        param.setKey("Input2.text");
+        param.setValue("[333]");
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:1012]: The parameter here should be non-arrray i.e. it should be "333" instead of `[333]`. Ref: https://firebase.google.com/docs/firestore/query-data/queries#array_membership

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java [hunk 4]
```diff
@@ -977,6 +981,140 @@ public void testTimeStampWhereConditional() {
...
+                .assertNext(result -> {
+                    assertTrue(result.getIsExecutionSuccess());
+                    List<Map<String, Object>> results = (List) ((HashMap) result.getBody()).get("kids");
+                    assertEquals(4, results.size());
+                })
+                .verifyComplete();
+    }
+
+    @Test
+    public void testArrayContainsWhereConditional() {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:1030]: Same comments as above.

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java [hunk 5]
```diff
@@ -977,6 +981,140 @@ public void testTimeStampWhereConditional() {
...
+                    List<Map<String, Object>> results = (List) ((HashMap) result.getBody()).get("kids");
+                    assertEquals(4, results.size());
+                })
+                .verifyComplete();
+    }
+
+    @Test
+    public void testArrayContainsAnyWhereConditional() {
+        Map<String, Object> configMap = new HashMap<>();
+        setValueSafelyInFormData(configMap, COMMAND, "GET_DOCUMENT");
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:1077]: Same as above - command should be `GET_COLLECTION`.

File: app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java [hunk 6]
```diff
@@ -989,6 +989,9 @@ private static HikariDataSource createConnectionPool(DatasourceConfiguration dat
             urlBuilder.append(authentication.getDatabaseName());
         }
 
+        //JDBC override parameter for resolving Cast Errors on PostgreSQL
```
Comment (sumitsum) [inline app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java:992]: This change should not be here.

File: app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java [hunk 7]
```diff
@@ -1300,6 +1300,50 @@ public void testPreparedStatementWithExplicitTypeCasting() {
 
     }
 
+    @Test
```
Comment (sumitsum) [inline app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java:1303]: This change should not be here.

**Review by sumitsum — CHANGES_REQUESTED** [review]

**Comment by sumitsum** [comment]
@leotom2000 can you please edit `getCollection.json` file to add ARRAY_CONTAINS and ARRAY_CONTAINS_ANY operators ?

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java (hunk 1 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:39]: Resolved, updated the IDE settings too

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java (hunk 3 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:1012]: resolved

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java (hunk 2 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:987]: Updated to GET_COLLECTION

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java (hunk 5 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:1077]: Updated to GET_COLLECTION

File: app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java (hunk 6 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java:992]: Seems that was from another PR,
will check it is not carried over in the next update

File: app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java (hunk 7 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java:1303]: Seems that was from another PR,
will check it is not carried over in the next update

File: app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java (hunk 6 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java]: > @leotom2000 can you please edit `getCollection.json` file to add ARRAY_CONTAINS and ARRAY_CONTAINS_ANY operators to the query config page ?

Added the changes

File: app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json [hunk 8]
```diff
@@ -86,8 +86,12 @@
           "value": "IN"
         },
         {
-          "label": "not in",
-          "value": "NOT_IN"
```
Comment (leotom2000) [inline app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json:90]: NOT_IN not supported in backend, it is there in front end.
is it okay that we add it back when the backend is ready ?

File: app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/utils/WhereConditionUtils.java [hunk 9]
```diff
@@ -99,23 +102,9 @@ public static Query applyWhereConditional(Query query, String strPath, String op
...
             case ARRAY_CONTAINS_ANY:
-                try {
-                    return query.whereArrayContainsAny(fieldPath, parseList((String) value));
-                } catch (IOException e) {
-                    throw new AppsmithPluginException(
-                            AppsmithPluginError.PLUGIN_EXECUTE_ARGUMENT_ERROR,
-                            "Unable to parse condition value as a JSON list."
-                    );
-                }
+                return query.whereArrayContainsAny(fieldPath, Arrays.asList(value.toString().split(",")) );
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/utils/WhereConditionUtils.java:105]: Please restore the earlier code version where `parseList` method is used, since we assume the user to provide input like `["abc", "def", 123]` because we have used similar format elsewhere in Firestore plugin query config.

File: app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json [hunk 10]
```diff
@@ -86,8 +86,12 @@
...
+          "label": "Contains",
+          "value": "ARRAY_CONTAINS"
+        },
+        {
+          "label": "Any",
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json:93]: Please rename to `Contains Any`

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java [hunk 11]
```diff
@@ -977,6 +987,137 @@ public void testTimeStampWhereConditional() {
...
+                    assertTrue(result.getIsExecutionSuccess());
+                    List<Map<String, Object>> results = (List) result.getBody();
+                    assertEquals(1, results.size());
+                })
+                .verifyComplete();
+    }
+
+
+    @Test
+    public void testArrayContainsAnyWhereConditional() {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:1079]: Please update the TC as per the suggested changes above.

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json (hunk 10 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json:93]: Updated, this is word Wrapping in the UI dropdown, 
so we need to update the Width in the front end

File: app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java (hunk 11 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java:1079]: Updated

File: app/client/src/components/formControls/WhereClauseControl.tsx [hunk 12]
```diff
@@ -11,7 +11,7 @@ import { WhereClauseSubComponent } from "./utils";
 import Tooltip from "components/ads/Tooltip";
 
 //Dropdwidth and Icon have fixed widths
-const DropdownWidth = 100; //pixel value
```
Comment (sumitsum) [inline app/client/src/components/formControls/WhereClauseControl.tsx:14]: Can you please remove this change ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

**Review by sumitsum — APPROVED** [review]
