### PR TITLE
fix: In Table widget for button/icon/menu type when Button Color is selected as Theme color and we toggle JS {{or}}}} is displayed

### LINKED ISSUE #13931: [Bug]: In Table widget for button/icon/menu type when Button Color is selected as Theme color and we toggle JS {{or}}}} is displayed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[LOOM DEMO](https://www.loom.com/share/cc3fad73b9604647aa810a78f4bd42b2)

### Steps To Reproduce

1. Drag and drop a table widget
2. Change the column type to icon
3. Scroll to Button color property
4. Select the Theme color
5. Now click on JS
6. Observe {{or}}}} is displayed

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #14305: [Bug]: Theme font is applied to appsmith when navigating from deploy mode back to edit mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i apply a new theme font and deploy it, then come back to the edit mode of the app using the edit button in deployed mode. 

I can see the same font is applied to appsmith as well.

### Steps To Reproduce

1. Select a new font in app's theme
2. Deploy the app
3. In the deployed app click on edit app again and come back to the edit mode
4. Now the theme font will also be visible in appsmith for property pane, IDE and other places
Screenshot 2022-06-06 at 2 38 09 PM

### Public Sample App

_No response_

### Version

Production/Cloud

### PR DESCRIPTION
**Pull request by jsartisan**
## Description
Fixes a bug where on changing color to theme color with the color picker in primary column and switching to js mode, {{or}} was observed in table widget.

Fixes #13931
Fixes #14305 

## Type of change
- Bug fixate

## How Has This Been Tested?
- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/propertyControls/PrimaryColumnColorPickerControl.tsx [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+
+class PrimaryColumnsColorPickerControl extends BaseControl<
+  PrimaryColumnColorPickerControlProps
+> {
+  handleChangeColor = (color: string) => {
+    const { jsSnippets, stringSegments } = getDynamicBindings(color);
+
+    const js = combineDynamicBindings(jsSnippets, stringSegments);
+    const computedValue = `{{${this.props.widgetProperties.widgetName}.sanitizedTableData.map((currentRow) => ( ${js}))}}`;
+    const computedColor = isDynamicValue(color) ? computedValue : color;
```
Comment (sbalaji1192) [inline app/client/src/components/propertyControls/PrimaryColumnColorPickerControl.tsx:18]: do this check before computing `computedValue`, `js` and `jsSnippets`

File: app/client/src/components/propertyControls/PrimaryColumnColorPickerControl.tsx [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+    this.updateProperty(this.props.propertyName, computedColor);
+  };
+
+  render() {
+    const computedEvaluatedValue = Array.isArray(this.props.evaluatedValue)
```
Comment (sbalaji1192) [inline app/client/src/components/propertyControls/PrimaryColumnColorPickerControl.tsx:24]: this could be an issue in the column section. Users could return different colors based on the  the cell value.

Comment (jsartisan) [reply app/client/src/components/propertyControls/PrimaryColumnColorPickerControl.tsx:24]: Yea right but in that case, the user will have already toggled the js option. 🤔

Comment (sbalaji1192) [reply app/client/src/components/propertyControls/PrimaryColumnColorPickerControl.tsx:24]: Just to confirm, are we resetting the js expression when user toggles back to color picker control?

Comment (jsartisan) [reply app/client/src/components/propertyControls/PrimaryColumnColorPickerControl.tsx:27]: I didn't add any code to do that but it seems values are getting cleared when toggling back to color picker control from js mode.

Comment (sbalaji1192) [reply app/client/src/components/propertyControls/PrimaryColumnColorPickerControl.tsx:27]: then this should be fine. Ignore this comment.

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
@jsartisan
 **Observation**: The {{or}}}} can still be seen for Button and Icon Button type color field when we do click on Reset value(theme deviation icon) and enable JS option.
 refer video
https://www.loom.com/share/924142989e754c20a3832141f2184fb1

**Comment by jsartisan** [comment]
@chandannkumar Hey, we have created a different issue for the reset button bug in the table and JSON form.

**Comment by chandannkumar** [comment]
Tested this PR and working as expected.
Fixes #13931
Fixes #14305
