### PR TITLE
fix: hide skip button if the application object is not present in the onboarding screen

### LINKED ISSUE #32380: [Bug]: hide the  skip this step, I ll do it later button when application object is not available
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is related to the conversation regarding the closure of the issue https://github.com/appsmithorg/appsmith/issues/32310
It is better to not show the button if the application object is not available rather show the button and not do anything.
Linked thread : https://theappsmith.slack.com/archives/C0134BAVDB4/p1712125023745899

### Steps To Reproduce

1. Add a latency to the network
2. Register a new user
3. Once the start with the data screen appears
4. Click on the  `Skip this step, I ll do it later` button before the network call to get the applications in the workspace finishes
5. Observe nothing happens

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Issue video log

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Removing `Skip this step, I ll do it later` button if the application object is not present. 
As earlier the skip button was rendering but there was a check in the onClick handler that if the application object is not present then do nothing, which does not make sense. There should be no if block without else block.
Link to the conversation thread : https://theappsmith.slack.com/archives/C0134BAVDB4/p1712125023745899

Fixes #32380 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.ImportExport, @tag.Workspace, @tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9405536613>
> Commit: c913d05e889eaea1d5562818b5bca257f959c55c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9405536613&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Added unit tests for the `CreateNewAppsOption` component to ensure proper rendering based on application states.
- **Bug Fixes**
	- Enhanced the `onClickSkipButton` function to prevent errors by ensuring the `application` object is not null.

### CODE REVIEW

File: app/client/src/ce/pages/Applications/CreateNewAppsOption.tsx [hunk 1]
```diff
@@ -140,25 +140,24 @@ const CreateNewAppsOption = ({
...
-          pageId: page.id,
-        })),
-      );
-      history.push(
-        builderURL({
-          pageId: application.pages[0].id,
-        }),
-      );
-    }
+    const applicationObject = application!;
```
Comment (rishabhrathod01) [inline app/client/src/ce/pages/Applications/CreateNewAppsOption.tsx:143]: Is this a valid JS to have `!` at the end of the variable name?

Comment (AmanAgarwal041) [reply app/client/src/ce/pages/Applications/CreateNewAppsOption.tsx:143]: It's a typescript convention  : https://www.geeksforgeeks.org/typescript-non-null-assertion-operator-postfix-type/

Comment (rishabhrathod01) [reply app/client/src/ce/pages/Applications/CreateNewAppsOption.tsx:143]: @AmanAgarwal041 got it. This will tell the typescript server that the application is defined but how are we sure about that? Shouldn't we instead use null coalescing here?

Comment (AmanAgarwal041) [reply app/client/src/ce/pages/Applications/CreateNewAppsOption.tsx:143]: The button is rendering only when the application object is available, so this function will be called only when the application object is present so null coalescing isn't required here. https://github.com/appsmithorg/appsmith/pull/34048/files#diff-b47d5cc31b2d89681b20e56253bdcd041a50b7eb564a01f5960a0aad599b25a0R216-R225

Comment (rishabhrathod01) [reply app/client/src/ce/pages/Applications/CreateNewAppsOption.tsx:143]: Got it. My bad i missed the JSX part of the code.

**Review by rishabhrathod01 — APPROVED** [review]
LGTM
