### PR TITLE
Fix: Tabs Widget

### LINKED ISSUE #1523: [Bug] Drag and drop not working inside Tab widget
### Steps to reproduce the behaviour:
1. Create a new app
2. drag a tab widget
3. try to drag an input inside it
4. The invalid bounds error shows while dragging even when there is space to drop

### LINKED ISSUE #1524: [Bug] Copy Pasting a widget from tab1 to tab2 does not work
### Steps to reproduce the behaviour:
1. Drag a tab
2. Drag a widget into tab 1
3. copy the widget in tab1 and navigate to tab2
4. Paste the widget in tab2
5. The widget gets pasted in tab1 instead

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
Fixes issue where placing widgets into the first tab of a tabs widget was disallowed.
Solution: Deprecate use of `tabId`, instead use the tab's `widgetId` as a reference.

Fixes #1524
Fixes #1523 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
All scenarios related to Tabs widget were manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 1]
```diff
@@ -149,20 +160,15 @@ function* generateChildWidgets(
...
     widgets = yield call(
       executeWidgetBlueprintOperations,
-      widget.blueprint.operations,
+      blueprint.operations,
       widgets,
       widget.widgetId,
     );
   }
   widget.parentId = parent.widgetId;
-  delete widget.blueprint;
```
Comment (hetunandu) [inline app/client/src/sagas/WidgetOperationSagas.tsx:165]: Why do we need to keep the blueprint? This causes other errors in evaluation and also increases the overall size of the dsl

File: app/client/src/components/propertyControls/TabControl.tsx [hunk 2]
```diff
@@ -169,11 +170,14 @@ class TabControl extends BaseControl<ControlProps> {
       "Tab ",
       tabs.map(tab => tab.label),
     );
-    tabs.push({
-      id: newTabId,
-      label: newTabLabel,
-      widgetId: generateReactKey(),
+    tabs = produce(tabs, draft => {
```
Comment (hetunandu) [inline app/client/src/components/propertyControls/TabControl.tsx:173]: Wondering if simple `concat` would be better here instead of produce. We anyways stringify the output so this is only to protect the "propertyValue" from mutating

File: app/client/src/sagas/WidgetOperationSagas.tsx (hunk 1 above)
Comment (riodeuno) [reply app/client/src/sagas/WidgetOperationSagas.tsx:165]: I agree.
`blueprint` no longer appears in the widget props. The previous changes here are towards that. The spread of the widgetConfigResponse excludes `blueprint`.

Comment (hetunandu) [reply app/client/src/sagas/WidgetOperationSagas.tsx:165]: Got it. You exclude it in the spread itself. Nice

**Review by hetunandu — APPROVED** [review]
