### PR TITLE
Fix: Maps widget crash on wrong initial location datatype

### LINKED ISSUE #1430: [Bug] Maps : Initial location does not get stored in the Property pane
Steps to reproduce:
1) Add an MAP widget 
2) Add a Initial Location 
and  observe 

Observation:
1) the map does not navigate to desired location on edit mode however on deploy mode the map is navigated to initial location

### LINKED ISSUE #1431: [Bug] Maps : On Copy paste of the widget the map is navigated to initial location
Steps to reproduce:
1) Add a Map widget
2) Add initial location 
and observe that the map is not navigated to initial location
3) Copy the widget 
4) Paste the widget 
and observe

Observation:
It is observed that Copied map widget is at initial location. 

Expectation:
both the parent and child widget should have similar behaviour

### LINKED ISSUE #1506: [Bug]MAPS:  unable navigate to  marked location after deployment when my initial location and default marker are two different location
Steps to reproduce:
1) Add a Map widget
2) Click on Property pane of the widget
3) Set the Initial location 
4) Set the Default marker 
5) Now deploy
6)Try to move the map  
and observe 

Observation:
It is observed that the user is unable to navigate to location other then the Initial location. Trying to reduce/ increase the size of the map user is only navigated in and around  initial location

### PR DESCRIPTION
**Pull request by ofpiyush**
## Description
- Initial location title now shows up on reopening the widget.
- Fix for that also fixes the crash in map widget. (#1506)
- Added a workaround for a race condition on declaring and using `window.google` (#1808)

Fixes #1430 
Fixes #1431
Fixes #1506 

Temporary hotfix for #1808 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually verified
- Added automated tests.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/propertyControls/LocationSearchControl.tsx [hunk 1]
```diff
@@ -29,61 +26,47 @@ interface StandaloneSearchBoxProps {
...
+    this.setState({ title: title });
+  };
+
+  onSearchBoxMounted = (ref: SearchBox) => {
+    this.searchBox = ref;
   };
+
   render() {
+    // Todo: figure out why there's a race here.
+    if (!window.google) return null;
```
Comment (ofpiyush) [inline app/client/src/components/propertyControls/LocationSearchControl.tsx:55]: Switch to `useScript`

**Comment by ofpiyush** [comment]
@riodeuno 
I realised that `useScript` will need me to make the entire component functional.

Is it possible to merge with the stopgap solution of `window.google` and come back to the functional component with a new PR?

There's 2 reasons behind this:
1. This PR fixes a crash scenario, which will keep getting delayed.
1. This PR is growing and accumulating more and more issues around it, I feel way more comfortable with small continuous changes.

**Review by riodeuno — APPROVED** [review]
