### PR TITLE
fix: send additional data to analytics for cloud hosted instance

### LINKED ISSUE #21857: [Task]: Send additional properties to analytics for cloud hosted instance
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Additional Information present here:
https://www.notion.so/appsmith/Tracking-Plan-83016de1083e486b85b96d64f9a82500#56d3580cb9934e34a4366a626bf258b8

Slack thread:
https://theappsmith.slack.com/archives/C02K2MZERSL/p1679314558219809?thread_ts=1677147977.937969&cid=C02K2MZERSL

### PR DESCRIPTION
**Pull request by nsarupr**
## Description

> Send additional data required for cloud hosted instance.

Fixes #21857

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (housekeeping or task changes that don't impact user perception)

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by vishnu-gp — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/FieldNameCE.java [hunk 1]
```diff
@@ -163,5 +164,6 @@ public class FieldNameCE {
     public static final String ANONYMOUS_USER_ID = "anonymousUserId";
     public static final String VIEW_MODE = "viewMode";
     public static final String USER_EMAILS = "userEmails";
+    public static final String NUMBER_OF_INVITED_USERS = "numberOfUsersInvited";
```
Comment (vishnu-gp) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/FieldNameCE.java:167]: @nsarupr Can we update the variable name to exactly match the string or the other way?

**Review by vishnu-gp — COMMENTED** [review]
@nsarupr Minor nit. Otherwise LGTM

**Review by vishnu-gp — APPROVED** [review]

**Review by AnaghHegde — APPROVED** [review]
