### PR TITLE
fix: parsing of nested parentheses in TableComputeValue expressions

### LINKED ISSUE #40265: [Bug]: Computed Value Field in Table Widget Removes Closing Parenthesis on Blur (v1.67)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Description:
When editing the Computed Value field of a column in the Table widget, some closing round bracket ) added at the end of specific expressions is automatically removed when the field loses focus. This results in broken expressions and incorrect widget behavior. The issue has been observed on Appsmith Cloud.

User Impact:
Users are unable to write valid expressions ending with a closing parenthesis, which leads to broken data bindings and possibly runtime errors in their apps.

### Steps To Reproduce

1. Create a new app and add a Table widget with Data
2. Create a JS object with any function inside it
3. Click on the **Table** widget and edit any column property
4. In the Computed value field, add this `{{JSObject1.someFunction(currentRow["id"] || 0)}}`
5. Note that when you leave the input, the last bracket ")" is removed and causes a broken experience

### Public Sample App

_No response_

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

_No response_

### Version

Cloud - 1.67

### PR DESCRIPTION
**Pull request by jacquesikot**
## Problem
The table compute value parser was unable to handle expressions with nested parentheses, causing incorrect extraction of computation expressions when functions with multiple parameters or nested function calls were used. This caused issues when users tried to use more complex expressions like `JSObject1.somefunction(currentRow["id"] || 0)`.

## Solution
Implemented a proper nested parentheses tracking algorithm that counts opening and closing parentheses to find the correct end of the computation expression, rather than simply looking for the first closing parenthesis sequence.

## Why This Approach
This solution is robust because it:
1. Properly handles any level of nested parentheses in function calls
2. Maintains backward compatibility with existing simple expressions
3. Provides a more accurate way to extract the computation expression

## Testing
- Added a new test case with nested parentheses: `JSObject1.somefunction(currentRow["id"] || 0)`
- Ensured existing test cases still pass
- Manually verified with complex expressions containing multiple nested parentheses

This fix enables users to write more complex table computations involving function calls with multiple parameters and conditions.

Fixes #40265 

## Automation

/ok-to-test tags="@tag.Table, @tag.Widget, @tag.Binding, @tag.Sanity, @tag.PropertyPane"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/14610729968>
> Commit: abbbaebfe5cf723109bee517e5f6f0cebf96a74a
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=14610729968&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Table, @tag.Widget, @tag.Binding, @tag.Sanity, @tag.PropertyPane`
> Spec:
> <hr>Wed, 23 Apr 2025 07:45:26 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved handling of computed values in table controls to correctly process nested parentheses and avoid errors from malformed expressions.

- **Tests**
  - Added test cases for complex computed expressions with nested parentheses, logical operators, and malformed inputs to ensure robustness.

### CODE REVIEW

**Review by vivek-appsmith — APPROVED** [review]

File: app/client/src/components/propertyControls/TableComputeValue.tsx [hunk 1]
```diff
@@ -161,25 +161,86 @@ class ComputeTablePropertyControlV2 extends BaseControl<ComputeTablePropertyCont
...
     return JSToString(computationExpression);
   };
 
+  /**
+   * Check if the computed value string looks structurally valid
+   * This helps catch obviously malformed expressions early
+   */
+  private static isLikelyValidComputedValue(value: string): boolean {
+    // Check for basic structural elements that should be present
+    const hasOpeningStructure = value.includes("(() => {");
```
Comment (AmanAgarwal041) [inline app/client/src/components/propertyControls/TableComputeValue.tsx:203]: Can the opening structure be :
`(
() =>
{` i.e. with new line chars instead of spaces or `(() =>{` ? @jacquesikot

Comment (jacquesikot) [reply app/client/src/components/propertyControls/TableComputeValue.tsx:203]: Thanks for this Aman, but the function in question here is defined by us in the code (hard coded) so this is not factor to change by the user
