### PR TITLE
fix: Fix npe while importing application when JSObject contains only variables and no action

### LINKED ISSUE #10002: NullPointerException
Sentry Issue: [APPSMITH-1GF](https://sentry.io/organizations/appsmith/issues/2882958981/?referrer=github_integration)

```
NullPointerException: None
    at com.appsmith.server.services.ce.ActionCollectionServiceCEImpl.lambda$getActionCollectionsForViewMode$10(ActionCollectionServiceCEImpl.java:215)
```

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> When the JSObject only contains the variables with no action reference we were getting npe as `actionCollectionDTO.getDefaultToBranchedActionIdsMap()` was null. Also as the imported application is ina bad state with no defaultResource ids set this was throwing the exception while fetching the `actionCollection` as well

Fixes #10002

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> JUnit TC
> Manual Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/DefaultResourcesUtils.java [hunk 1]
```diff
@@ -78,10 +78,12 @@
             collectionDTO.setDefaultResources(defaultResources);
 
             Map<String, String> updatedActionIds = new HashMap<>();
-            collectionDTO.getDefaultToBranchedActionIdsMap()
-                    .values()
-                    .forEach(val -> updatedActionIds.put(val, val));
-            collectionDTO.setDefaultToBranchedActionIdsMap(updatedActionIds);
+            if (!CollectionUtils.isNullOrEmpty(collectionDTO.getDefaultToBranchedActionIdsMap())) {
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/DefaultResourcesUtils.java:81]: Earlier this check was not present which was causing the issue which we are trying to solve here

**Review by nayan-rafiq — APPROVED** [review]
LGTM

**Review by AnaghHegde — APPROVED** [review]
