### PR TITLE
fix: Widget Context Switching

### LINKED ISSUE #29695: [Task]: Widget List Context Switching issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Case 1: Sidebar Navigation

- Have a widget selected
- Go to another state like libraries or data
- Go back to editor
- Widget is not selected and editor is ui add state

Case 2: Page Switch

- Have a widget selected
- Go to another page
- come back to the older page
- Widget is not selected and editor is in ui add state

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Fixes context switching issues related to Widget List ensuring it also works for current prod

#### PR fixes following issue(s)
Fixes #29695

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
  - Added a search functionality to the app.
  - Integrated a search bar at the top of the `Hero` component and a `Search` component to the `App` component.
  - Included styles for the search bar in the application.

### CODE REVIEW

File: app/client/src/components/editorComponents/CloseEditor.tsx [hunk 1]
```diff
@@ -52,7 +52,7 @@ function CloseEditor() {
     // else go back to BUILDER_PAGE
     const redirectURL = isGeneratePageInitiator
       ? generateTemplateFormURL({ pageId })
-      : builderURL({ pageId });
+      : widgetListURL({ pageId });
```
Comment (hetunandu) [inline app/client/src/components/editorComponents/CloseEditor.tsx:55]: We are going to widget list url because that will select the last selected widget.

File: app/client/src/navigation/FocusEntity.ts [hunk 2]
```diff
@@ -39,11 +39,12 @@ export enum FocusEntity {
   LIBRARY = "LIBRARY",
   SETTINGS = "SETTINGS",
   WIDGET_LIST = "WIDGET_LIST",
+  EDITOR = "EDITOR",
   QUERY_ADD = "QUERY_ADD",
 }
 
 export const FocusStoreHierarchy: Partial<Record<FocusEntity, FocusEntity>> = {
-  [FocusEntity.PROPERTY_PANE]: FocusEntity.CANVAS,
+  [FocusEntity.PROPERTY_PANE]: FocusEntity.WIDGET_LIST,
```
Comment (hetunandu) [inline app/client/src/navigation/FocusEntity.ts:47]: Removing CANVAS as point of focus cause now that is basically just the add state of UI

File: app/client/src/navigation/FocusSetters.ts [hunk 3]
```diff
@@ -80,3 +71,21 @@ export function setSelectedJSObject(id: string | undefined) {
     );
   }
 }
+
+export function setSelectedSegment(tab?: EditorEntityTab) {
```
Comment (hetunandu) [inline app/client/src/navigation/FocusSetters.ts:75]: We will set it to the list urls so that they can automatically select the last selected item

File: app/client/src/navigation/FocusSelectors.ts [hunk 4]
```diff
@@ -107,3 +108,26 @@ export const getSelectedJSObjectId = (path: string): string | undefined => {
   if (!match) return undefined;
   return match.params.collectionId;
 };
+
+export const getSelectedSegment = (path: string): string | undefined => {
```
Comment (hetunandu) [inline app/client/src/navigation/FocusSelectors.ts:112]: We will store the last selected segment to take them to the correct selected segment when coming back

File: app/client/src/pages/Editor/Explorer/Pages/index.tsx [hunk 5]
```diff
@@ -72,9 +72,12 @@ function Pages() {
 
   const switchPage = useCallback(
     (page: Page) => {
-      const navigateToUrl = builderURL({
-        pageId: page.pageId,
-      });
+      const navigateToUrl =
+        currentPageId === page.pageId
```
Comment (hetunandu) [inline app/client/src/pages/Editor/Explorer/Pages/index.tsx:76]: If the page is already selected, clicking on it ( a hack in today's IDE to go back to canvas) we will redirect to the widget list url instead to select the last selected widget

File: app/client/src/pages/Editor/IDE/PagesPane/JS_Section.tsx [hunk 6]
```diff
@@ -66,24 +70,31 @@ const JSSection = () => {
...
-                  parentEntityId={pageId}
-                  searchKeyword={""}
-                  step={2}
-                  type={JSobject.type as PluginType}
-                />
-              </Flex>
-            );
-          })}
-      </Flex>
+      <FilesContextProvider
```
Comment (hetunandu) [inline app/client/src/pages/Editor/IDE/PagesPane/JS_Section.tsx:73]: Added because JS was crashing. Now Context menus in Explorer need a Provider

File: app/client/src/pages/Editor/IDE/PagesPane/ListWidgets.tsx [hunk 7]
```diff
@@ -32,8 +36,12 @@ const ListWidgets = () => {
   }, [widgets?.children]);
 
   const addButtonClickHandler = useCallback(() => {
-    dispatch(selectWidgetInitAction(SelectionRequestType.Empty));
-  }, [pageId]);
+    if (selectedWidgets.length) {
+      dispatch(selectWidgetInitAction(SelectionRequestType.Empty));
+    } else {
+      history.push(builderURL({ pageId }));
```
Comment (hetunandu) [inline app/client/src/pages/Editor/IDE/PagesPane/ListWidgets.tsx:42]: Edge case where no widgets exist

File: app/client/src/navigation/FocusSelectors.ts [hunk 8]
```diff
@@ -107,3 +108,26 @@ export const getSelectedJSObjectId = (path: string): string | undefined => {
...
+  const match = matchPath<{ entity: string }>(path, {
+    path: [
+      BUILDER_PATH_DEPRECATED + "/:entity",
```
Comment (albinAppsmith) [inline app/client/src/navigation/FocusSelectors.ts:115]: we don't need add paths here? In add paths also the selected entity should be the same right?

Comment (albinAppsmith) [reply app/client/src/navigation/FocusSelectors.ts:115]: Also, will curl import make issue here?

Comment (hetunandu) [reply app/client/src/navigation/FocusSelectors.ts:100]: Does not matter if it is an add path or not, since it looks only for "entity" , the selected entity will be captured. We will not be storing context states for curl

**Review by albinAppsmith — APPROVED** [review]
