### PR TITLE
Fix editor container fails to run with vanilla config

### LINKED ISSUE #4635: [Bug] Appsmith editor container refers to hard-coded paths for SSL certs, making the container fail to run when there's no file system available
<p>Got this message from Johann on Discord. He is unable to install Appsmith on GCP. I also couldn't find any documentation around this. His message below</p>
<p>I tried deploying the appsmith editor image first and I got "cannot load certificate "/etc/certificate/dev.appsmith.com.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/certificate/dev.appsmith.com.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)"</p>
<p><br />Some context on how I am going about it, I have pushed everything to GCP container registry, and then am using terraform to create cloudrun applications<br /><br /><br /></p>

### PR DESCRIPTION
**Pull request by sharat87**
Fixes #4635.

After this is fixed, the appsmith-editor container will be able to be run with a command like the following:

```sh
docker run -p 80:80 -p 443443 -e APPSMITH_SERVER_PROXY_PASS='http://host.docker.internal:8080' appsmith/appsmith-editor
```

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/editor-container-vanilla 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.66 **(-0.01)** | 33.66 **(-0.01)** | 29.53 **(0)** | 52.32 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.59 **(-0.24)** | 39.41 **(-0.84)** | 36.21 **(0)** | 54.77 **(-0.27)**</details>

### CODE REVIEW

**Comment by sharat87** [comment]
@mohanarpit @riodeuno, I'm marking you guys are reviewers for this. I'm a bit concerned that the newer Docker images built with this new `Dockerfile`, won't break existing self-hosted installations. While I've gone and done my review to ensure that won't be the case, I'd love it if you guys do so as well. Thanks! 😄

**Comment by ioloc** [comment]
Any idea when this merge will go through ? 😄

**Comment by sharat87** [comment]
Hey @mohanarpit @riodeuno, can I borrow your eyes for a few minutes on this PR please? It most likely won't make your eyes bleed I promise ✋

**Comment by riodeuno** [comment]
@sharat87 To me, it looks like the existing setup scenario has been handled.  Looks good to me.

File: app/client/docker/start-nginx.sh [hunk 1]
```diff
@@ -1,7 +1,36 @@
...
-cat /nginx-root.conf.template | envsubst "$(printf '$%s,' $(env | grep -Eo '^APPSMITH_[A-Z0-9_]+'))" | sed -e 's|\${\(APPSMITH_[A-Z0-9_]*\)}||g' > /etc/nginx/nginx.conf
+set -o errexit
+set -o xtrace
+
+if [ -z "$APPSMITH_SERVER_PROXY_PASS" ]; then
+  echo "Missing APPSMITH_SERVER_PROXY_PASS env variable. Please point it to where server is avilable." >&2
+  exit 1
+fi
+
+cp /nginx-root.conf.template /etc/nginx/nginx.conf
```
Comment (riodeuno) [inline app/client/docker/start-nginx.sh:13]: Do we not need to substitute anything during startup? I checked the template, doesn't seem like anything comes from the env. Please confirm.

I am confused because we used to substitute earlier.

**Review by mohanarpit — APPROVED** [review]

File: app/client/docker/start-nginx.sh (hunk 1 above)
Comment (sharat87) [reply app/client/docker/start-nginx.sh:13]: I think the substitution happens later in this case. You are right, the substitution happens earlier, in the case of building/running the normal Docker image. But in this script, I think we bypass that and do the substitution a bit later.

**Comment by ioloc** [comment]
Thanks, guys! Saves me editing it every update :D
