### PR TITLE
Fix/additional date formats

### LINKED ISSUE #2304: [Feature] New Date picker needs more default date options
The date picker only has 5 different date formats, we need more that users in the US use.
Screen Shot 2020-12-21 at 4 32 45 PM

Tasks:
1. Identify and include more date options
2. Give examples of date options so that the user understands what the date type is like
3. Ensure date types in table widget, and date picker widget are consistent.

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Ensure date types in table widget, and date picker widget are consistent.
Changed date format dropdown to include example date and date format in each option.

Fixes #2304 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by riodeuno** [comment]
Jest tests are failing. Leading to a failed build.

File: app/client/src/widgets/DatePickerWidget2.tsx [hunk 1]
```diff
@@ -37,23 +38,28 @@ class DatePickerWidget extends BaseWidget<DatePickerWidget2Props, WidgetState> {
...
-                label: "DD/MM/YYYY",
+                label: moment().format("DD/MM/YYYY"),
+                subText: "DD/MM/YYYY",
                 value: "DD/MM/YYYY",
               },
               {
-                label: "DD/MM/YYYY HH:mm",
+                label: moment().format("DD/MM/YYYY HH:mm"),
+                subText: "DD/MM/YYYY HH:mm",
                 value: "DD/MM/YYYY HH:mm",
```
Comment (riodeuno) [inline app/client/src/widgets/DatePickerWidget2.tsx:63]: These are the same list of formats as before. 
We need more formats in this list.

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/DatePickerWidget2.tsx [hunk 2]
```diff
@@ -37,23 +38,28 @@ class DatePickerWidget extends BaseWidget<DatePickerWidget2Props, WidgetState> {
             isJSConvertible: true,
             options: [
               {
```
Comment (riodeuno) [inline app/client/src/widgets/DatePickerWidget2.tsx:40]: The control hasn't been updated to show the subText. Please update the control as well.

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Comment by riodeuno** [comment]
Additional formats:
- moment().format("LLL") "March 12, 2021 1:52 PM"
- moment().format("LL") "March 12, 2021"
- moment().format("D MMMM, YYYY") "12 March, 2021"
- moment().format("H:mm A D MMMM, YYYY") "1:52 PM 12 March, 2021"
- moment().format("MM-DD-YYYY") "03-12-2021"
- moment().format("DD-MM-YYYY") "12-03-2021"
- moment().format("MM/DD/YYYY") "03/12/2021"
- moment().format("DD/MM/YYYY") "12/03/2021"
- moment().format("DD/MM/YY") "12/03/21"
- moment().format("MM/DD/YY") "12/03/21"

File: app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts [hunk 3]
```diff
@@ -273,24 +321,60 @@ export default [
...
+                    {
+                      label: "LLL",
+                      value: "LLL",
+                    },
+                    {
+                      label: "LL",
+                      value: "LL",
                     },
                     {
-                      label: "YYYY-MM-DD hh:mm:ss",
```
Comment (riodeuno) [inline app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts:280]: Let's not remove any existing ones.

**Comment by riodeuno** [comment]
@vicky-primathon Let's rename the `YYYY-MM-DDTHH:mm:ss.sssZ` label to `ISO8601` and right align all the labels.

File: app/client/src/widgets/DatePickerWidget2.tsx [hunk 4]
```diff
@@ -37,25 +38,95 @@ class DatePickerWidget extends BaseWidget<DatePickerWidget2Props, WidgetState> {
...
-                label: "YYYY-MM-DDTHH:mm:ss.sssZ",
+                label: moment().format("YYYY-MM-DDTHH:mm:ss.sssZ"),
+                subText: "ISO 8601",
                 value: "YYYY-MM-DDTHH:mm:ss.sssZ",
               },
               {
-                label: "DD/MM/YYYY",
+                label: moment().format("YYYY-MM-DDTHH:mm:ss.sssZ"),
+                subText: "YYYY-MM-DDTHH:mm:ss.sssZ",
```
Comment (riodeuno) [inline app/client/src/widgets/DatePickerWidget2.tsx:57]: This seems to be a duplicate. Please remove this.

File: app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts [hunk 5]
```diff
@@ -229,6 +229,14 @@ export default [
                       label: "YYYY-MM-DD",
                       value: "YYYY-MM-DD",
                     },
+                    {
+                      label: "YYYY-MM-DD HH:mm",
+                      value: "YYYY-MM-DD HH:mm",
+                    },
+                    {
+                      label: "YYYY-MM-DDTHH:mm:ss.sssZ",
+                      value: "YYYY-MM-DDTHH:mm:ss.sssZ",
```
Comment (riodeuno) [inline app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts:238]: Let's rename this to ISO8601

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_spec.js [hunk 6]
```diff
@@ -47,15 +47,18 @@ describe("DatePicker Widget Property pane tests with js bindings", function() {
     cy.openPropertyPane("datepickerwidget2");
     cy.selectDateFormat("YYYY-MM-DD");
     cy.assertDateFormat();
-    cy.selectDateFormat("YYYY-MM-DD HH:mm");
+    cy.selectDateFormat("DD-MM-YYYY");
     cy.assertDateFormat();
-    cy.selectDateFormat("YYYY-MM-DDTHH:mm:ss.sssZ");
+    // cy.selectDateFormat("YYYY-MM-DD HH:mm");
```
Comment (riodeuno) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_spec.js:52]: Let's figure out if we can keep these lines.

**Review by riodeuno — APPROVED** [review]
