### PR TITLE
fix: don't run onClick event handler when button is disabled

### LINKED ISSUE #12144: [Bug]: Disable run button in query editor page after having run the query once.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the run button has been clicked once, the button shows disabled state, but it is still clickable. As a result, we can click as many times as we want on the Run button, and have different execute requests sent for each one. We should disable the button till we come back with a response.

### Steps To Reproduce

https://user-images.githubusercontent.com/5298848/159477726-085890b8-8197-4299-a3e7-a19f54323bbc.mov

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rimildeyjsr**
## Description

When the "Run" button is clicked - it gets the disabled styles indicating a user should not be able to perform clicks while a particular query is running. But this does not prevent the operations to be performed repeatedly by clicking the button in the loading state.

This PR fixes this issue by checking if the button is not in a loading state, and only then allowing the onclick handler to be executed.

Fixes #12144

**Screenshots:**

**Before:**
https://user-images.githubusercontent.com/10229595/160589310-39e86f64-804c-4f01-9ed7-8779afb2e1d8.mov

**After fixing the issue:**
https://user-images.githubusercontent.com/10229595/160589949-12bc5c77-5898-4c9f-b269-5a2723e3012f.mov

**After fixing the issue for canvas**
https://user-images.githubusercontent.com/10229595/161064807-dc0d6f84-c99b-48b3-9043-8d47be1b62d4.mov

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Created a new API (https://swapi.dev/api/people/1) and hit the Run button. Watch the XHR/Fetch requests in the network tab of the developer tools. You will see one request going and the button in the loading state. While the button is in the loading state, click the button multiple times - there should not be additional requests being sent while the button is in the loading state.
- Checked using the same steps by connecting a Firebase data source and running a "get document" query

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/disable-onclick-in-disabled-button 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.43 **(0.01)** | 37.81 **(0)** | 36.07 **(0.05)** | 56.65 **(0.01)**
 :green_circle: | app/client/src/components/ads/Button.tsx | 92.36 **(1.39)** | 82.76 **(3.63)** | 97.78 **(2.22)** | 92.96 **(1.41)**
 :green_circle: | app/client/src/components/ads/Spinner.tsx | 100 **(33.33)** | 100 **(0)** | 100 **(100)** | 100 **(33.33)**
 :red_circle: | app/client/src/widgets/ButtonWidget/component/DragContainer.tsx | 58.82 **(-7.85)** | 42.86 **(-7.14)** | 66.67 **(0)** | 64.29 **(-4.94)**
 :red_circle: | app/client/src/widgets/ButtonWidget/component/index.tsx | 47.62 **(-2.38)** | 27.88 **(-2.33)** | 43.48 **(-1.97)** | 48.89 **(-1.68)**</details>

### CODE REVIEW

**Review by eco-monk — COMMENTED** [review]
LGTM.
@rimildeyjsr, Can we consider fixing this for the button widget too?
It's not described in the issue.
But when you drag and drop a button in the canvas. The issue happens.

https://www.loom.com/share/bc425773cefc4e429bdee7c85bf7bfb3

File: app/client/src/widgets/ButtonWidget/component/index.tsx [hunk 1]
```diff
@@ -408,12 +412,17 @@ function BtnWrapper(
...
+    isLoading: boolean;
     onClick?: (event: React.MouseEvent<HTMLElement>) => void;
   } & RecaptchaProps,
 ) {
-  if (!props.googleRecaptchaKey)
-    return <div onClick={props.onClick}>{props.children}</div>;
-  else {
+  if (!props.googleRecaptchaKey) {
+    return (
+      <div onClick={props.isLoading ? undefined : props.onClick}>
```
Comment (eco-monk) [inline app/client/src/widgets/ButtonWidget/component/index.tsx:421]: Is it okay to set callbacks as undefined?
If not, we can wrap around with a function (similar to the ads changes). So the callback is never undefined.

```
(e: React.MouseEvent<HTMLElement>) =>
        props.onClick && !props.isLoading && props.onClick(e)
      }
```

**Review by eco-monk — APPROVED** [review]

**Review by eco-monk — DISMISSED** [review]

**Review by eco-monk — DISMISSED** [review]

**Review by eco-monk — APPROVED** [review]

**Review by eco-monk — APPROVED** [review]

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM
