### PR TITLE
fix: Remove sentry logging of clone errors 

### LINKED ISSUE #2654: [Bug] Error: DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function(e){var ...
Sentry Issue: [APPSMITH-GQ](https://sentry.io/organizations/appsmith/issues/2168651302/?referrer=github_integration)

```
Error: DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function(e){var n=e%10;return e+(1===se(e%100/10)?"th":1===n?"st":2===n?"nd":3===n?"rd":"th")} could not be cloned.
  at None (/static/js/evaluation.worker.2f72bca4.worker.js:2:166009)
```

### PR DESCRIPTION
**Pull request by rimildeyjsr**
## Description

Sending unserializable data between threads causes a DataClone error. This occurs when a user tries to return a Function, a Promise, or any [unclonable data type](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#things_that_dont_work_with_structured_clone) from a JS function.

The proposed solution is to create a lint error that prevents users from returning unclonable data types. This will take some time, so in the meanwhile, we are disabling sending logging this error to sentry. Once we have worked on this solution, we will enable sentry again.

Fixes #2654 - temporary fix till we come up with a more definitive solution

Media
- not needed

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/sagas/PostEvaluationSagas.ts [hunk 1]
```diff
@@ -286,11 +286,18 @@ export function* evalErrorHandler(
...
+         * This code is being commented out to prevent these errors from going to Sentry
+         * till we come up with a more definitive solution to prevent this error
+         * Proposed solution - adding lint errors to editor to prevent these from happening
+         * */
+
+        // Sentry.captureException(new Error(error.message), {
+        //   extra: {
+        //     request: error.context,
+        //   },
+        // });
```
Comment (arunvjn) [inline app/client/src/sagas/PostEvaluationSagas.ts:300]: You need to log this error on debugger. That way users could reach out to support with this message.

**Review by arunvjn — APPROVED** [review]
