### PR TITLE
fix: properly lint triggerfields

### LINKED ISSUE #9438: [Bug]: Datasources and JS Objects are not recognized in widget binding for an old app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Datasources and JS objects are not recognized by this old [app](https://release.app.appsmith.com/applications/612332edfe755a38b6e6a9c2/pages/614c3e3f014ef61ca5f03449/edit) that's about 2 months old.

https://release.app.appsmith.com/applications/612332edfe755a38b6e6a9c2/pages/614c3e3f014ef61ca5f03449/edit

- Datasources and JS objects are picked up linter as undefined but don't appear in debugger
- Only `mongoQuery` shows up for `uncaught reference error`

[LOOM DEMO](https://www.loom.com/share/5bd34b50bd4d4d7783035860ba61e3aa)

### Steps To Reproduce

1. Navigate to link above and observe widget bindings on the page and the errors present in the debugger and console.

### Environment

Release

### Version

Cloud

### LINKED ISSUE #9676: [Bug]: Linting errors are showing incorrectly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Linting errors are showing for users even when their queries are defined

### Steps To Reproduce

1. Go to https://app.appsmith.com/applications/6139b6c7dd7786286ddd4f04/pages/6139b6c7dd7786286ddd4f0c/edit?branch=master
2. Click the table
3. Open the config for the delete column
4. convert the onClick to js
5. See the Delete_Integration query is in an error state

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

This PR fixes the linting error which occurs when creating the first  tree

Fixes #9676
Fixes #9438

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

File: app/client/src/workers/DataTreeEvaluator.ts [hunk 1]
```diff
@@ -1571,14 +1575,18 @@ export default class DataTreeEvaluator {
...
+    entity: DataTreeEntity,
+    currentTree: DataTree,
+  ) {
     const { jsSnippets } = getDynamicBindings(userScript, entity);
     const script = getScriptToEval(
       jsSnippets[0],
       EvaluationScriptType.TRIGGERS,
     );
     const GLOBAL_DATA = createGlobalData(
-      this.evalTree,
```
Comment (ohansFavour) [inline app/client/src/workers/DataTreeEvaluator.ts:1581]: During the creation of the first tree, `this.evalTree` is an empty object.

**Review by hetunandu — APPROVED** [review]
