### PR TITLE
fix: fork template tracking

### LINKED ISSUE #18416: [Task]: analytics event for fork template not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

It seems that the analytics event `fork_APPLICATIONTEMPLATE` is not being triggered with the new user flow. we need to have this event trigger whenever a user forks a template from either the templates page, or the templates modal.

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description
The mixpanel analytics event `fork_APPLICATIONTEMPLATE` was not being tracked when the user forks a template from the Add Page option, but the same event was getting tracked when the user clicks on the `Templates` tab and then forks it.
Due to this, the mixpanel metrics were affected.

Fixes #18416 

## Resolution
Added code for populating the `fork_APPLICATIONTEMPLATE` event in the following API:

- [/api/v1/app-templates/62ffa415e8e73110ce254b4c/merge/6389a2b59956db2c13d0d5ed/635b9f516278c10e2bf9c4cd](https://app.appsmith.com/api/v1/app-templates/62ffa415e8e73110ce254b4c/merge/6389a2b59956db2c13d0d5ed/635b9f516278c10e2bf9c4cd) (POST)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

https://user-images.githubusercontent.com/25542733/205931589-bcb47438-6300-4dbc-80be-31fc76aa1e49.mov

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java [hunk 1]
```diff
@@ -284,9 +284,25 @@ public Mono<ApplicationImportDTO> mergeTemplateWithApplication(String templateId
...
+                    );
+
+                    final Map<String, Object> data = Map.of(
+                            FieldName.APPLICATION_ID, application.getId(),
+                            FieldName.WORKSPACE_ID, application.getWorkspaceId(),
+                            FieldName.TEMPLATE_APPLICATION_NAME, application.getName(),
+                            FieldName.EVENT_DATA, eventData
+                    );
+
+                    return analyticsService.sendObjectEvent(AnalyticsEvents.FORK, applicationTemplate, data)
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java:304]: Should we create a separate event to differentiate between normal app forks and template forking into an existing app?

Comment (vishnu-gp) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java:304]: @AnaghHegde I think here the Analytics event is FORK but the resource is template, normal app fork event and this will have different tag names when sent to Segment.

If you meant different events for forking templates from the template page and from within the application page here, We had this conversation already and I think the product team want the same event in both places.

Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java:304]: @AnaghHegde As per discussion with @kocharrahul7, we need the same `fork_APPLICATIONTEMPLATE` event to be tracked in both the scenarios above.
