### PR TITLE
fix: doc viewer and xlsx fixes (#19427)

### LINKED ISSUE #19427: [Bug]: Base64 of .docx and/or .xlsx not working with Document Viewer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I put a data URL of a docx or xlsx file as source for the document viewer, the document is not shown. "Oops, Something went wrong." is shown instead.

### Steps To Reproduce

1. Create a xlsx (or docx) file or use the attached test files.
2. Encode the file as base64.
3. Set under "Document link" of a Document Viewer the following: data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,_your base64_
[test.docx](https://github.com/appsmithorg/appsmith/files/10331112/test.docx)
[test.xlsx](https://github.com/appsmithorg/appsmith/files/10331113/test.xlsx)

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Self Hosted - 1.8.15

Front logo [Front conversations](https://app.frontapp.com/open/top_6z9xo)

### PR DESCRIPTION
**Pull request by vsvamsi1**
## Description
Updated versions of mammoth  and execljs to browser versions. Earlier versions used were compatible in a node js environment and expected certain base libraries which were missing in the browser env. Hence caused errors which prevented the app from loading the base encoded versions.

Fixes #19427 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/DocumentViewerWidget/component/DocViewer.tsx [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import React, { useEffect, useState } from "react";
-import mammoth from "mammoth";
+// eslint-disable-next-line @typescript-eslint/ban-ts-comment
+// @ts-ignore: Types are not available
```
Comment (ashit-rath) [inline app/client/src/widgets/DocumentViewerWidget/component/DocViewer.tsx:3]: Instead of doing this, declare a module in `typings` folder and remove these.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Others/DocumentViewer_spec/DocumentViewer_Spec.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
+import { ObjectsRegistry } from "../../../../../../support/Objects/Registry";
```
Comment (ashit-rath) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Others/DocumentViewer_spec/DocumentViewer_Spec.ts:1]: Why this file (`DocumentView_Spec.ts`) under `Widgets/Others/DocumentViewer_spec/` and not
`Widgets/DocumentViewer/`?

File: app/client/src/widgets/DocumentViewerWidget/component/DocViewer.tsx [hunk 3]
```diff
@@ -24,7 +26,7 @@ export default function DocViewer(props: { blob?: Blob }) {
             { arrayBuffer: buffer },
             { includeEmbeddedStyleMap: true, includeDefaultStyleMap: true },
           )
-          .then((result) => {
+          .then((result: any) => {
```
Comment (ashit-rath) [inline app/client/src/widgets/DocumentViewerWidget/component/DocViewer.tsx:29]: use `unknown` instead of `any` here.

**Comment by ashit-rath** [comment]
@vsvamsi1 Fix the PR description to link the issue correctly.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Others/DocumentViewer_spec/DocumentViewer_Spec.ts (hunk 2 above)
Comment (vsvamsi1) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Others/DocumentViewer_spec/DocumentViewer_Spec.ts:1]: Hi @ashit-rath It was earlier within the "Others location", thats why i continued to use the same place. Should we moved it to the widgets folder?

Comment (ashit-rath) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Others/DocumentViewer_spec/DocumentViewer_Spec.ts:1]: Yes please

File: app/client/src/widgets/DocumentViewerWidget/component/DocViewer.tsx (hunk 3 above)
Comment (vsvamsi1) [reply app/client/src/widgets/DocumentViewerWidget/component/DocViewer.tsx:29]: Sure if i have updated the type to be more tighter to a string because i expect the result to resolve to a string.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/DocumentViewer/DocumentViewer_spec.ts [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+    deployMode.NavigateBacktoEditor();
+  });
+  it("7. Should show an empty xlsx document when a malformed input is provided", () => {
+    ee.SelectEntityByName("DocumentViewer1", "Widgets");
+    // previously the document contains the number "456"
+    const someGarbageString = "fdfdfdf";
+    propPane.UpdatePropertyFieldValue("Document Link", someGarbageString);
+    deployMode.DeployApp();
+    // now the doc should not contain "456" after a malformed input is provided
+    cy.get(locator._widgetInDeployed("documentviewerwidget")).should(
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/DocumentViewer/DocumentViewer_spec.ts:74]: test case description says that it should show an empty xlsx document. Can we add one more assertion to check whether its showing an empty document and not an errored-out state?

**Review by sbalaji1192 — APPROVED** [review]

**Review by ashit-rath — APPROVED** [review]

**Review by sbalaji1192 — DISMISSED** [review]

**Review by sbalaji1192 — APPROVED** [review]

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM

**Review by ashit-rath — DISMISSED** [review]
