### PR TITLE
fix: Property pane components re-render

### LINKED ISSUE #6417: [Perf] Further Optimisations of PropertyPane Connections
PropertyPane Connections were optimised to an extent as part of the editing optimisations. But this can be further optimised with optimising other selectors and moving code to fetch link on click instead of updating every time.

### LINKED ISSUE #14580: [Task]: Some Property pane components re-renders when they are not supposed to be
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The following components are re-rendering when we make a small change to any property in the property pane
- PropertyPaneSidebar
- PropertyPaneView
- ProeprtyPaneConnections
- CodeEditor

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

The following components were re-rendering when any property changes
- PropertyPaneSidebar
- PropertyPaneView
- ProeprtyPaneConnections

After inspection, I found that it was due to the selectors they were using. Modified the selector code to fix the re-rendering issue.

Fixes #14580 
Fixes #6417

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by rahulramesha — COMMENTED** [review]
@aswathkk As discussed please verify changes with respect to `() => true` for selectors.

File: app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts [hunk 1]
```diff
@@ -102,7 +104,19 @@ export const useSelectedEntity = () => {
 };
 
 export const useEntityLink = () => {
-  const dataTree = useSelector(getDataTree);
+  const dataTree = useSelector(getDataTree, (left, right) => {
```
Comment (SatishGandham) [inline app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts:107]: This is not the right solve for this.
We should not use use selector at all. We don't need the dataTree until the user click the link and its not used to render any element, so use can access the store directly in the returned function.

File: app/client/src/pages/Editor/Explorer/Widgets/useNavigateToWidget.ts [hunk 2]
```diff
@@ -10,12 +10,20 @@ import { navigateToCanvas } from "./utils";
...
+import equal from "fast-deep-equal/es6";
+import { mapValues } from "lodash";
 
 const WidgetTypes = WidgetFactory.widgetTypes;
 
 export const useNavigateToWidget = () => {
   const params = useParams<ExplorerURLParams>();
-  const allWidgets = useSelector(getCurrentPageWidgets);
+
+  const allWidgets = useSelector(getCurrentPageWidgets, (left, right) => {
```
Comment (SatishGandham) [inline app/client/src/pages/Editor/Explorer/Widgets/useNavigateToWidget.ts:21]: Same as previous comment.

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx [hunk 3]
```diff
@@ -191,8 +191,11 @@ const doConnectionsHaveErrors = (
 };
 
 const useDependencyList = (name: string) => {
-  const dataTree = useSelector(getDataTree);
-  const deps = useSelector((state: AppState) => state.evaluations.dependencies);
+  const dataTree = useSelector(getDataTree, () => true);
```
Comment (SatishGandham) [inline app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx:194]: Will this work when the dependencies change? 

For example, on text widget I change the value to {{Input1.text}}, will the dependency list be updated?

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx [hunk 4]
```diff
@@ -46,7 +48,13 @@ function PropertyPaneView(
 ) {
   const dispatch = useDispatch();
   const { ...panel } = props;
-  const widgetProperties: any = useSelector(getWidgetPropsForPropertyPane);
+  const widgetProperties = useSelector(
+    getWidgetPropsForPropertyPane,
+    (left, right) => {
```
Comment (SatishGandham) [inline app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx:53]: 1. Use prev and next instead of left right. This is the convention followed in react and in Appsmith.
2. Can you explain what you are doing here.

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx (hunk 3 above)
Comment (aswathkk) [reply app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx:194]: @SatishGandham @rahulramesha This doesn't work when the dependency changes.

I will explore the right solution and update this.

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx (hunk 4 above)
Comment (aswathkk) [reply app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx:53]: 1. okay. I will follow the convention.
2. getWidgetPropsForPropertyPane is returning some data that is not being used in this component. So, this one renders whenever some unwanted data changes. To resolve this, I pass a comparator function to `useSelector` which checks the equality between only the properties that are being used in the component.

Comment (SatishGandham) [reply app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx:53]: In that case, please write a selector that give it only the information it needs.

File: app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts (hunk 1 above)
Comment (aswathkk) [reply app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts:107]: Correct.
This was also pointed out by @rahulramesha 
I will use a different approach.

File: app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts [hunk 5]
```diff
@@ -102,46 +103,43 @@ export const useSelectedEntity = () => {
...
-      } else if (isJSAction(entity)) {
-        history.push(
-          jsCollectionIdURL({
-            applicationSlug,
-            pageSlug,
-            pageId,
-            collectionId: entity.actionId,
-          }),
+  const navigateToEntity = useCallback((name) => {
+    const dataTree = getDataTree(store.getState());
```
Comment (SatishGandham) [inline app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts:113]: @aswathkk , To maintain existing logic, you need the dataTree at the time the link was clicked. 

For this to work,  subsequent updates to datatree shouldn't change the existing links.

Comment (aswathkk) [reply app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts:113]: @SatishGandham I didn't get you.
According to previous logic, an update to dataTree will also update navigateToEntity function. Check the dependency list of useCallback in the previous case.
Is that something else you were talking about?

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx [hunk 6]
```diff
@@ -190,9 +193,16 @@ const doConnectionsHaveErrors = (
...
+);
+
 const useDependencyList = (name: string) => {
-  const dataTree = useSelector(getDataTree);
-  const deps = useSelector((state: AppState) => state.evaluations.dependencies);
+  const dataTree = useSelector(getDataTreeWithOnlyId, equal);
+  const inverseDependencyMap = useSelector(
+    (state: AppState) => state.evaluations.dependencies.inverseDependencyMap,
+    equal,
+  );
```
Comment (SatishGandham) [inline app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx:205]: We don't need deep equal at L204. It changes only when it actually changes.
Please verify.

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx [hunk 7]
```diff
@@ -190,9 +193,16 @@ const doConnectionsHaveErrors = (
...
 };
 
+const getDataTreeWithOnlyId = createSelector(getDataTree, (tree) =>
+  mapValues(pick(tree, ["ENTITY_TYPE", "widgetId", "actionId"])),
+);
+
 const useDependencyList = (name: string) => {
-  const dataTree = useSelector(getDataTree);
-  const deps = useSelector((state: AppState) => state.evaluations.dependencies);
+  const dataTree = useSelector(getDataTreeWithOnlyId, equal);
```
Comment (SatishGandham) [inline app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx:201]: Shouldn't this be getDataTreeWithOnlyIds

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx [hunk 8]
```diff
@@ -39,14 +42,35 @@ export const excludeList: WidgetType[] = [
...
+  type: string;
+  widgetId: string;
+  widgetName: string;
+  displayName: string;
+};
+
+const getWidgetPropsForPropertyPaneView = createSelector(
+  getWidgetPropsForPropertyPane,
+  (props) =>
+    pick(props, [
```
Comment (SatishGandham) [inline app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx:55]: Check the time taken by pick in the chrome profiler.

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx [hunk 9]
```diff
@@ -39,14 +42,35 @@ export const excludeList: WidgetType[] = [
...
 ];
 
+type WidgetPropertiesForPropertyPaneView = {
+  type: string;
+  widgetId: string;
+  widgetName: string;
+  displayName: string;
+};
+
+const getWidgetPropsForPropertyPaneView = createSelector(
```
Comment (SatishGandham) [inline app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx:52]: See if moving the selector to selectors folder, or a separate file in the same folder makes sense.

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx (hunk 7 above)
Comment (aswathkk) [reply app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx:201]: Yeah. 💯  I will make the change.

File: app/client/src/components/editorComponents/PropertyPaneSidebar.tsx [hunk 10]
```diff
@@ -61,13 +59,6 @@ export const PropertyPaneSidebar = memo((props: Props) => {
   const keepThemeWhileDragging =
     prevSelectedWidgetId.current === undefined && shouldNotRenderPane;
 
-  const selectedWidgets = useMemo(
```
Comment (rahulramesha) [inline app/client/src/components/editorComponents/PropertyPaneSidebar.tsx:64]: Was thinking about this and remembered why `selectedWidgets` was accessed from `canvasWidgets`.
This was to make sure that the `selected widgetIds` still exists in `canvasWidgets`. This was a mechanism to verify if the selected widgets had not been cut or deleted or the user had selected widgets from previous pages.

To fix this you could create a `selector` that had access to `canvasWidgets`, from there you could filter out the `widgetIds` that did not exist in `canvasWidgets`. You could use such selector here with an `equal` check.

**Review by rahulramesha — CHANGES_REQUESTED** [review]

File: app/client/src/selectors/propertyPaneSelectors.tsx [hunk 11]
```diff
@@ -56,6 +57,35 @@ export const getWidgetPropsForPropertyPane = createSelector(
...
+      "widgetName",
+      "displayName",
+    ]) as WidgetPropertiesForPropertyPaneView,
+);
+
+export const selectedWidgetsPresentInCanvas = createSelector(
+  getWidgets,
+  getSelectedWidgets,
+  // Make sure the widgets in selectedWidgets still exists in the canvasWidgets
+  (canvasWidgets, selectedWidgets) => {
```
Comment (SatishGandham) [inline app/client/src/selectors/propertyPaneSelectors.tsx:82]: How about iterating over selected widgets and pop the array if its not on the canavs?
We won't need compact.

**Review by SatishGandham — CHANGES_REQUESTED** [review]
Looks good except for few minor clarification and may be changes.

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx (hunk 6 above)
Comment (aswathkk) [reply app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx:205]: Yes. Reference changes.

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx [hunk 12]
```diff
@@ -46,7 +47,10 @@ function PropertyPaneView(
 ) {
   const dispatch = useDispatch();
   const { ...panel } = props;
-  const widgetProperties: any = useSelector(getWidgetPropsForPropertyPane);
+  const widgetProperties = useSelector(
+    getWidgetPropsForPropertyPaneView,
```
[the remark this answers is not in the document]
Comment (aswathkk) [reply app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx:51]: It is hardcoded to 4 keys ["type", "widgetId", "widgetName", "displayName"]

File: app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx (hunk 6 above)
Comment (aswathkk) [reply app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx:205]: I tested it by replacing `equal` function with a custom function and found that reference changes (using `===` operator)

**Review by SatishGandham — DISMISSED** [review]
