### PR TITLE
fix: increase scrolling threshold to fix weird scrolling behaviour

### LINKED ISSUE #25146: [Bug]: Issues with centring of the widget in Edit mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Issue with JSON form - When there are multiple fields in JSON form , and your click on the first one to add some details , the widget starts centring and the current input field goes out of view
2. Issues with dropdown (for select widgets, phone etc)
3. Issue with Modal, on clicking the child widget inside the modal, the main canvas starts scrolling

### Steps To Reproduce

https://www.loom.com/share/17b287ca5e794602bb47c51c930fe7d8

Link to app-->
[Untitled application 97 (2).json.zip](https://github.com/appsmithorg/appsmith/files/11965214/Untitled.application.97.2.json.zip)

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/Self-hosted

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Widget scrolling was introduced in the context switching project to ensure that a selected widget is never out of view. This went through some changes and it seems like when widgets on edges increase height on interaction (select widget) or if the widget is longer than the current view, the scrolling behaviour did not make sense. 

To fix this problem, we have increased the threshold of scrolling, and will only scroll when less than 5% of the widget is visible on screen. Anything more and it will not scroll the page

#### PR fixes following issue(s)
Fixes #25146

#### Media

https://github.com/appsmithorg/appsmith/assets/12022471/2cc251a3-01c9-44d8-9b6e-536e727250ec

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/utils/helpers.tsx [hunk 1]
```diff
@@ -233,7 +233,7 @@ export const quickScrollToWidget = (
     const el = document.getElementById(widgetId);
     const canvas = document.getElementById("canvas-viewport");
 
-    if (el && canvas && !isElementVisibleInContainer(el, canvas)) {
+    if (el && canvas && !isElementVisibleInContainer(el, canvas, 5)) {
```
Comment (akash-codemonk) [inline app/client/src/utils/helpers.tsx:236]: If we have just the bottom part of the widget visible more than 5%, but most of the top part isn't, will it scroll?
For e.g a table widget with just the bottom 5% visible and rest of it is at the top outside the viewport, and we select widget from the explorer.

**Review by akash-codemonk — APPROVED** [review]

File: app/client/src/utils/helpers.tsx (hunk 1 above)
Comment (hetunandu) [reply app/client/src/utils/helpers.tsx:236]: It will not. The widget name and borders will show up in orange though so that should be good enough to guide the user

**Comment by kamakshibhat-appsmith** [comment]
Looks Good @hetunandu
