### PR TITLE
fix: Corrected usage of old soft deleted filter in BaseAppsmithRepository

### LINKED ISSUE #18161: [Task]: Check usage of deleted param for soft delete action in the entire codebase
### Is there an existing issue for this?

- [X] I have searched the existing issues

Recently we found there were issues happening because of the deprecated `deleted` param in entities for soft-delete operation. In the latest version, we only use `deletedAt` field for soft-delete. This task is to verify we are only using `deletedAt` in all places in the code and `delete` field is not creating issues across.

### SubTasks
- Verify on FE
- Verify on BE

### PR DESCRIPTION
**Pull request by vishnu-gp**
## Description

Recently we found there were issues happening because of the deprecated `deleted` param in entities for soft-delete operation. In the latest version, we only use `deletedAt` field for soft-delete. This PR correct the usage of old `deleted` field only filter and adds the current field to the filter.

Fixes #18161

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- JUnit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java [hunk 1]
```diff
@@ -217,6 +222,42 @@ public void testCreateActionCollection() {
...
+        actionCollectionDTO.setPageId(pageId);
+        actionCollectionDTO.setPluginId(datasource.getPluginId());
+        actionCollectionDTO.setPluginType(PluginType.JS);
+        actionCollectionDTO.setDeletedAt(Instant.now());
+        layoutCollectionService.createCollection(actionCollectionDTO).block();
+        ActionCollection createdActionCollection = actionCollectionRepository.findByApplicationId(createdApplication.getId(), READ_ACTIONS, null).blockFirst();
+        createdActionCollection.setDeletedAt(Instant.now());
+        actionCollectionRepository.save(createdActionCollection).block();
+
+        StepVerifier.create(actionCollectionRepository.findByApplicationId(createdApplication.getId(), READ_ACTIONS, null))
```
Comment (sumitsum) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java:256]: Sorry, I could be understanding this wrong, but shouldn't we be checking here if `findByApplicationId` has not returned anything ?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java [hunk 2]
```diff
@@ -95,9 +95,17 @@ public static final String fieldName(Path path) {
...
+                new Criteria().orOperator(
+                        where(FieldName.DELETED).exists(false),
+                        where(FieldName.DELETED).is(false)
+                ),
+                //New check for deleted
+                new Criteria().orOperator(
+                        where(FieldName.DELETED_AT).exists(false),
+                        where(FieldName.DELETED_AT).is(null)
+                )
         );
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java:109]: @vishnu-gp as we have deprecated the use of deleted flag does it make sense to completely remove the dependency and only use deletedAt field instead?

Comment (vishnu-gp) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java:109]: @abhvsn Did you mean removing the filter from here or removing the entire deprecated field from all entities? The current setup is even if this field is deprecated we default it to false and on deletes update this field as well in addition to deletedAt. I would like to start a thread and hear everyone's opinion on this before making that change. You can see similar filters in `BaseRepositoryImpl` as well.

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java:109]: Fair enough, I will vote for completely removing the dependency on deleted flag, rational being we are deprecationg that field but still using in some places which creates confusion 😕.
I am treating this as a tech debt and we should get rid of this, earlier the better!

Comment (vishnu-gp) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java:109]: @abhvsn Let's track this here https://github.com/appsmithorg/appsmith/issues/18248 and move forward with PR for the time being.
