### PR TITLE
fix: Correct x and y values returned for Sankey (custom fusion chart) when onDataPointClick is triggered

### LINKED ISSUE #26026: [Bug]: selectedDataPoint does not contain x and y values for Sankey custom fusion chart
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`selectedDataPoint` does not contain the `x` and `y` coordinate when clicked on a datapoint present on the sankey custom fusion chart. 

Front - user: https://app.frontapp.com/inboxes/teams/folders/15690316/archived/84143541516

### Steps To Reproduce

1. Dnd chart widget
2. Switch to custom charts
3. Add the following chart config:
```
{
  "type": "sankey",
  "dataSource": {
    "nodes": [
      {
        "label": "Netherlands"
      },
      {
        "label": "Canada"
      },
      {
        "label": "Belgium"
      },
      {
        "label": "Italy"
      },
      {
        "label": "Mexico"
      },
      {
        "label": "Russia"
      },
      {
        "label": "Spain"
      },
      {
        "label": "South Korea"
      },
      {
        "label": "Germany"
      },
      {
        "label": "China"
      },
      {
        "label": "European Union"
      },
      {
        "label": "Japan"
      },
      {
        "label": "United Kingdom"
      },
      {
        "label": "United States"
      },
      {
        "label": "France"
      },
      {
        "label": "Hong Kong"
      },
      {
        "label": "Switzerland"
      },
      {
        "label": "Austria"
      },
      {
        "label": "Sweden"
      }
    ],
    "links": [
      {
        "from": "Netherlands",
        "to": "European Union",
        "value": 798744
      },
      {
        "from": "Germany",
        "to": "European Union",
        "value": 1468990
      },
      {
        "from": "European Union",
        "to": "France",
        "value": 745931
      },
      {
        "from": "European Union",
        "to": "United States",
        "value": 660541
      },
      {
        "from": "Canada",
        "to": "United States",
        "value": 594546
      },
      {
        "from": "Belgium",
        "to": "European Union",
        "value": 628796
      },
      {
        "from": "China",
        "to": "Hong Kong",
        "value": 400571
      },
      {
        "from": "China",
        "to": "United States",
        "value": 526454
      },
      {
        "from": "European Union",
        "to": "United Kingdom",
        "value": 520318
      },
      {
        "from": "China",
        "to": "European Union",
        "value": 560536
      },
      {
        "from": "Italy",
        "to": "European Union",
        "value": 539556
      },
      {
        "from": "Mexico",
        "to": "United States",
        "value": 492715
      },
      {
        "from": "Russia",
        "to": "European Union",
        "value": 385778
      },
      {
        "from": "Spain",
        "to": "European Union",
        "value": 365191
      },
      {
        "from": "China",
        "to": "Japan",
        "value": 312062
      },
      {
        "from": "European Union",
        "to": "Switzerland",
        "value": 328609
      },
      {
        "from": "South Korea",
        "to": "China",
        "value": 229073
      },
      {
        "from": "European Union",
        "to": "Austria",
        "value": 244913
      },
      {
        "from": "Japan",
        "to": "United States",
        "value": 206091
      },
      {
        "from": "European Union",
        "to": "Sweden",
        "value": 204849
      },
      {
        "from": "Germany",
        "to": "United States",
        "value": 184287
      }
    ],
    "chart": {
      "caption": "Immigrant Flow for Last Month (In Millions)",
      "legendPosition": "bottom",
      "linkcolor": "blend",
      "theme": "fusion"
    }
  }
}
```
4. Configure `onDataPointClick` event of chart widget.
5. Dnd text widget and map it's text property to the following: `{{Chart1.selectedDataPoint}}`.
6. Observe that on click of data point on chart, the x and y values does not appear in the`selectedDataPoint` object.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
We are adding `rawEventData` property to `onDataPointClick` for the chart widget. Also, when `x` and `y` are not available, we make them `-1`.

#### PR fixes following issue(s)
Fixes #26026

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Jest

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/widgets/ChartWidget/constants.ts [hunk 1]
```diff
@@ -32,6 +32,7 @@ export interface ChartSelectedDataPoint {
   x: any;
   y: any;
   seriesTitle: string;
+  rawEventData: unknown[];
```
Comment (rajatagrawal) [inline app/client/src/widgets/ChartWidget/constants.ts:35]: Would you like to consider the type to be just unknown instead of unknown[], since it may not always be an array if a new library in future doesn't return an array ?

File: app/client/src/widgets/ChartWidget/component/index.tsx [hunk 2]
```diff
@@ -306,10 +307,12 @@ class ChartComponent extends React.Component<
...
           const data = evt.data;
           const seriesTitle = get(data, "datasetName", "");
+          // pass -1 when x and y are not present
           this.props.onDataPointClick({
-            x: data.categoryLabel,
-            y: data.dataValue,
+            x: data.categoryLabel ?? -1,
+            y: data.dataValue ?? -1,
             seriesTitle,
+            rawEventData: data,
```
Comment (rajatagrawal) [inline app/client/src/widgets/ChartWidget/component/index.tsx:315]: I think that we want to pass rawEventData only for custom fusion chart. For basic chart, we don't want to pass this value to the users. [Relevant Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1691396411061089?thread_ts=1691135335.087569&cid=C0341RERY4R)

File: app/client/src/widgets/ChartWidget/component/index.test.tsx [hunk 3]
```diff
@@ -159,4 +159,25 @@ describe("Chart Widget", () => {
...
+      point;
+      mockCallback(point);
+    };
+
+    render(<ChartComponent {...props} />);
+
+    const el = await screen.findByText("1000");
+
+    userEvent.click(el);
+    expect(mockCallback.mock.results?.[0].value).toHaveProperty("rawEventData");
```
Comment (rajatagrawal) [inline app/client/src/widgets/ChartWidget/component/index.test.tsx:181]: Can we have an assertion like 

```
expect(mockCallback.mock.results?.[0].value.rawEventData).toEq({//raw event value goes here})
```

File: app/client/src/widgets/ChartWidget/component/index.tsx [hunk 4]
```diff
@@ -154,9 +154,10 @@ class ChartComponent extends React.Component<
         : "null";
 
     this.props.onDataPointClick({
-      x: x,
-      y: y,
+      x: x ?? -1,
```
Comment (rajatagrawal) [inline app/client/src/widgets/ChartWidget/component/index.tsx:157]: We can consider moving the logic for parsing event data into chartSelectedPoint params into a separate function. With that we would be also able to test that x and y are -1 if relevant values are not present in event data.

A wrapper unit test that tests that mockCallbackfunction gets called with a set of correct chartSelectedPoint params would validate that the helper function created above is getting called.

File: app/client/src/widgets/ChartWidget/component/index.test.tsx (hunk 3 above)
Comment (rajatagrawal) [reply app/client/src/widgets/ChartWidget/component/index.test.tsx:181]: This way we can also test a set of possible values inside rawEventData.

**Review by rajatagrawal — CHANGES_REQUESTED** [review]

**Comment by rajatagrawal** [comment]
I think that we would also need a documentation update for this ticket. cc : @dilippitchika

File: app/client/src/widgets/ChartWidget/component/index.test.tsx (hunk 3 above)
Comment (dhruvikn) [reply app/client/src/widgets/ChartWidget/component/index.test.tsx:181]: As discussed in our call, we are not writing a unit test for this, rather a cypress to test onDataPointClick functionality.

File: app/client/src/widgets/ChartWidget/component/index.tsx (hunk 4 above)
Comment (dhruvikn) [reply app/client/src/widgets/ChartWidget/component/index.tsx:157]: Have moved this logic to a separate `parseOnDataPointClickParams` function.

**Review by rajatagrawal — APPROVED** [review]
