### PR TITLE
Fix incorrect bodyFormData values being sent

### LINKED ISSUE #1661: [Bug] [Rest API] Incorrect UI displayed after switching content type
When content type is switched to a previously used content type, even though the UI displays the cached data, the action is not updated giving the user a false sense of data preservation. When executed, the server sends a request with empty body because of this. 

### Steps to reproduce the behaviour:

1. Create an action. Set the content type to application/x-www-form-urlencoded
2. Enter some key-values in the body
3. Switch the content type to application/json
4. Enter some json here.
5. Switch back to application/x-www-form-urlencoded.
6. Hit Run.
Check the Request Tab to see that body does not get set in the API
7. Add 3 keys and 3 values quickly
8. Refresh the API
9. Only a few keys or values get saved

### PR DESCRIPTION
**Pull request by akash-codemonk**
Fixes #1661

### CODE REVIEW

File: app/client/src/transformers/RestActionTransformer.ts [hunk 1]
```diff
@@ -50,7 +50,6 @@ export const transformRestAction = (data: any): any => {
       contentType !== POST_BODY_FORMAT_OPTIONS[1].value &&
       contentType !== POST_BODY_FORMAT_OPTIONS[2].value
     ) {
-      action.actionConfiguration.bodyFormData = undefined;
```
Comment (Nikhil-Nandagopal) [inline app/client/src/transformers/RestActionTransformer.ts:53]: @akash-codemonk please test out all scenarios correctly. In this case, I am now seeing if I switch to application/json, it has data locally but after refreshing its empty so the data did not get saved.

Comment (akash-codemonk) [reply app/client/src/transformers/RestActionTransformer.ts:53]: This was happening before this change as well. Pushed a fix for the same.

**Review by Nikhil-Nandagopal — APPROVED** [review]
