### PR TITLE
fix: added fuzzy search logic for datasource home

### LINKED ISSUE #38983: Use a fuzzy match search instead of exact match

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Earlier when we were searching `sk` , snowflake was not returned in the searched datasources. Hence after this pr instead of exacting matching a fuzzy search logic is applied which helps us in searching for snowflake datasource even if we add `sk` in the search input. 

Steps to test: 
- Go to application
- Go to Add new datasources page
- Add `sk` in the search input, snowflake should be  present in the UI.

Fixes #38983
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13172714737>
> Commit: ca099a3e1eca8c8a5953d508f9833d00fd94d7b1
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13172714737&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Thu, 06 Feb 2025 06:58:30 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Enhanced search filtering now delivers alphabetically sorted and more accurate results when browsing plugins and datasources.
  - Added a new prop for mock datasources to improve the functionality of the Empty Searched Plugins component.

- **Refactor**
  - Streamlined and centralized the search filtering process across integration pages for a more consistent and scalable user experience.

### CODE REVIEW

**Comment by NilanshBansal** [comment]
@rahulbarwal can you please review this PR

**Comment by rahulbarwal** [comment]
I am sorry I don't have context on this issue. @AmanAgarwal041, would it be possible for you to add some more details in the description about what the problem was, what's the new solution and how exactly to test this. I would like to test this on the DP first.

**Comment by AmanAgarwal041** [comment]
> I am sorry I don't have context on this issue. @AmanAgarwal041, would it be possible for you to add some more details in the description about what the problem was, what's the new solution and how exactly to test this. I would like to test this on the DP first.

Updated the description and added steps to test as well.

**Review by rahulbarwal — COMMENTED** [review]
Overall I agree with the changes in the sense that it will accomplish your goal. But we already are using fuse.js in our repo that will be a better replacement than our own native implementation which is susceptible to edge cases failure. 

https://github.com/appsmithorg/appsmith/blob/release/app/client/src/selectors/templatesSelectors.tsx#L157

**Comment by rahulbarwal** [comment]
@AmanAgarwal041 On the DP when I search for `sl`, the result `MySQL` is not coming up.

image

**Comment by AmanAgarwal041** [comment]
> @AmanAgarwal041 On the DP when I search for `sl`, the result `MySQL` is not coming up.
> 
> image

@rahulbarwal Fixed the threshhold for the search

File: app/client/src/pages/Editor/IntegrationEditor/util.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+import Fuse from "fuse.js";
+
+const searchConfig = {
+  keys: ["name"],
+  shouldSort: true,
+  threshold: 0.6,
+  location: 0,
+  distance: 100,
```
Comment (rahulbarwal) [inline app/client/src/pages/Editor/IntegrationEditor/util.ts:8]: Nit: 100 distance seems too much for datasources name search, as we have limited options to search from. 

See if reducing this make sense.

**Review by rahulbarwal — APPROVED** [review]
