### PR TITLE
fix: Properly save JSON to clipboard

### LINKED ISSUE #9390: [Bug]: Copy button in evaluated popup is not saving JSON correctly in clipboard
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on the copy button in the evaluated button, the object that is saved to the clipboard contains `[object]` instead of the actual object string.  was hoping JSON will get saved in the clipboard.

### Steps To Reproduce

1. Drop a table widget.
2. Focus on the table data in the property pane.
3. Click on the copy button on the evaluated popup
4. Notice the JSON that is saved in the clipboard is not valid

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

Fixes #9390 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/correctly-copy-json-objects-in-evaluated-pane 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.09 **(-0.01)** | 37.05 **(-0.02)** | 33.86 **(0)** | 55.58 **(-0.01)**
 :red_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 65.35 **(-0.52)** | 56.1 **(-1.4)** | 38.89 **(0)** | 65.77 **(-0.59)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**</details>

### CODE REVIEW

File: app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx [hunk 1]
```diff
@@ -163,7 +163,11 @@ function CollapseToggle(props: { isOpen: boolean }) {
 }
 
 function copyContent(content: any) {
-  copy(content);
+  const stringifiedContent = _.isString(content)
+    ? content
+    : JSON.stringify(content);
```
Comment (hetunandu) [inline app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx:168]:
```suggestion
    : JSON.stringify(content, null, 2);
```

**Review by hetunandu — APPROVED** [review]
