### PR TITLE
fix: Race condition in JS object mutation

### LINKED ISSUE #27978: [Bug]: JS object properties not set
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since 1-2 days ago (release v1.9.38 or v1.9.39? in the AppSmith-hosted SaaS), we are facing a issues with setting properties in JS objects.

The following code snippet of a JS object, `JSObject`, illustrates the issues.
```
export default {
  data: [],

  async getData() {
    await APIQuery.run()
    return APIQuery.data
  },

  async myFun1() {
    this.data = await this.getData()
    console.log(this.data) // prints "[]", this.data is not set
  },
  async myFun2() {
    const data = await this.getData()
    this.data = data
    console.log(this.data) // prints result of this.getData(), this.data is properly set
    // however, setting a UI element (table) to {{ JSObject.data }} does not populate the table
  },
  async myFun3() {
    await APIQuery.run()
    const data = APIQuery.data
    this.data = data
    // this properly populates the table when setting a UI element (table) to {{ JSObject.data }}
  },
}
```

Previously, `myFun1()` has worked as expected for us - the table UI element has been populated with the results of `getData()` (the query). But since a few days ago, only `myFun3()` will work in this way.

### Steps To Reproduce

1. Create an API query to an API returning a JSON array and name it `APIQuery`.
2. Create a JS object named `JSObject`, containing the code snippet in the description.
3. Create a table and a button in the UI.
4. Set the button `onClick` property of the button to `{{ await myFun1() }}`.
5. Set the `Table data` property of the table to `{{ JSObject.data }}`.
6. Click the button.
7. The table is not populated.
8. Return to step 4, first replace `myFun1` with `myFun2` and continue to step 7, then replace it with `myFun3` and to the same. Only `myFun3` populates the table.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

v1.9.40-SNAPSHOT

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fixes race condition in JS Object mutation where evaluation overrides the variables state. 

Root Cause:
Execution context is shared between every evaluation request and trigger execution request. A trigger execution request could be paused when an asynchronous task is awaited. In the mean time, worker might pick up the task to perform and evaluation. Evaluation would end up replacing the entities in the execution context, there by resetting the actions performed by the trigger execution before it was paused. 

What the fix does?
We are now caching the JS object for reuse which means that every execution/evaluation request reuses the same JS Object as long the JS Object isn't modified by a user action.

#### PR fixes following issue(s)
Fixes #27978 
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
#### How Has This Been Tested?
- [x] Manual
- [x] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [x] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [x] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/ce/actions/evaluationActions.ts [hunk 1]
```diff
@@ -66,8 +66,6 @@ export const EVALUATE_REDUX_ACTIONS = [
   ReduxActionTypes.MOVE_ACTION_SUCCESS,
   ReduxActionTypes.RUN_ACTION_SUCCESS,
   ReduxActionErrorTypes.RUN_ACTION_ERROR,
-  ReduxActionTypes.EXECUTE_PLUGIN_ACTION_SUCCESS,
-  ReduxActionErrorTypes.EXECUTE_PLUGIN_ACTION_ERROR,
```
Comment (Rishabh-Rathod) [inline app/client/src/ce/actions/evaluationActions.ts:70]: This change was done to avoid evaluation when API or Query is executed from main thread, as we already trigger evaluation in worker inside Action run. 
cc: @ohansFavour

**Review by Rishabh-Rathod — APPROVED** [review]
Changes LGTM.

**Comment by ramsaptami** [comment]
LGTM @arunvjn
