### PR TITLE
Location Search Control Crash

### LINKED ISSUE #3196: [Bug] TypeError: Cannot read property 'geometry' of undefined
Sentry Issue: [APPSMITH-JM](https://sentry.io/organizations/appsmith/issues/2235021066/?referrer=github_integration)

```
TypeError: Cannot read property 'geometry' of undefined
  at onPlacesChanged (components/propertyControls/LocationSearchControl.tsx:38:32)
  at Dv.onPlacesChanged (components/propertyControls/LocationSearchControl.tsx:86:19)
  at gf.Dj (/maps/api/js:240:414)
  at Object._.K.trigger (/maps/api/js:237:385)
  at mf (/maps/api/js:111:322)
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
Fix issue when searching for certain places does not return a list from the location search control

Fixes #3196 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

By generating this crash manually.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/propertyControls/LocationSearchControl.tsx [hunk 1]
```diff
@@ -34,13 +35,22 @@ class LocationSearchControl extends BaseControl<ControlProps> {
...
-    const location = places[0].geometry.location;
-    const title = places[0].formatted_address;
-    const lat = location.lat();
-    const long = location.lng();
-    const value = { lat, long, title };
-    this.updateProperty(this.props.propertyName, value);
+    try {
+      // For some places, the length is zero
+      const places = this.searchBox.getPlaces();
+      const location = places[0].geometry.location;
```
Comment (Nikhil-Nandagopal) [inline app/client/src/components/propertyControls/LocationSearchControl.tsx:41]: Shouldn't we have a check for places here instead of this?

Comment (riodeuno) [reply app/client/src/components/propertyControls/LocationSearchControl.tsx:41]: There is no other choice but to bail out here if places[0].geometry.location isn't available.
This whole function does one task. Which is why having a try catch will serve the same purpose as having a check for places. Also, in successful cases, adding another if else condition will cause an unnecessary code path to execute.

**Review by Nikhil-Nandagopal — APPROVED** [review]
