### PR TITLE
fix: Fix mismatch between errors in debugger and evaluated value popup

### LINKED ISSUE #7751: [Bug] Mismatch in error message for unique values in select widget in evaluated value popup and debugger
## Description

select

Fix is to show the first error message in debugger in the eval popup.

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Show the first error message in the debugger in the eval popup. 
Also update error message for the same.

Fixes #7751 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/mismatch-in-errors 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.81 **(-0.01)** | 36.94 **(-0.02)** | 33.81 **(0.01)** | 55.43 **(0)**
 :red_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 65.08 **(-0.27)** | 56.25 **(0)** | 36.11 **(0)** | 65.45 **(-0.32)**
 :red_circle: | app/client/src/sagas/EvaluationsSaga.ts | 23.9 **(-0.12)** | 5.62 **(-0.26)** | 12.5 **(-0.54)** | 26.86 **(-0.15)**
 :red_circle: | app/client/src/workers/DataTreeEvaluator.ts | 83.7 **(-0.31)** | 62.81 **(-2.15)** | 82.05 **(-1.07)** | 83.13 **(-0.34)**
 :red_circle: | app/client/src/workers/evaluationUtils.ts | 73.84 **(-0.53)** | 58.87 **(-2.61)** | 74.42 **(-1.77)** | 71.91 **(-0.62)**
 :green_circle: | app/client/src/workers/validations.ts | 74.07 **(0.16)** | 67.76 **(0.04)** | 64.71 **(2.21)** | 76.35 **(0.16)**</details>

### CODE REVIEW

**Review by rishabhsaxena — APPROVED** [review]
LGTM

File: app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx [hunk 1]
```diff
@@ -385,11 +375,7 @@ function PopoverContent(props: PopoverContentProps) {
     >
       {hasError && error && (
         <ErrorText>
-          <span className="t--evaluatedPopup-error">
-            {error.errorType === PropertyEvaluationErrorType.VALIDATION
-              ? `This value does not evaluate to type "${expected?.type}".`
-              : error.errorMessage}
-          </span>
+          <span className="t--evaluatedPopup-error">{error.errorMessage}</span>
```
Comment (hetunandu) [inline app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx:378]: Not all errors have error message i guess. Can we do a QA before merging?

**Review by ramsaptami — APPROVED** [review]
tested ok on deploy preview

File: app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx (hunk 1 above)
Comment (akash-codemonk) [reply app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx:378]: You mean errorMessage might be an empty string`""` right .

Comment (hetunandu) [reply app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx:378]: Yea

Comment (Tooluloope) [reply app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx]: I think `error.errorMessage` is a concatenation of error messages, So if multiple errors are found, they'd be joined together and could be so long, Might be a bad UX

Comment (Tooluloope) [reply app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx]: Something like this looks hard to understand
Screenshot 2021-09-23 at 12 54 34

Comment (akash-codemonk) [reply app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx]: Ok so I think a good fix for this would be to not join multiple error messages in [validations](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/workers/validations.ts#L74), instead we can just show the first error message. Also joining is not that readable in the debugger as well. 
So I will just show the first error message that exists.

Comment (hetunandu) [reply app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx]: Validations should return an array of error messages and all should show up in the debugger

**Review by hetunandu — DISMISSED** [review]

**Review by hetunandu — APPROVED** [review]
