### PR TITLE
fix: datasource form footer ui fix

### LINKED ISSUE #33826: [Bug]: UI consistency is missing in the Edit datasource page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I traverse between different datasources in the Edit mode, the bottom division ui is not consistent across all datasources

### Steps To Reproduce

1. Create many datasources in an application
2. Go the edit option of each datasource and observe the ui consistency in the bottom section where the test / save / cancel buttons are present. 

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

https://jam.dev/c/9ced90bc-e23c-426a-8075-352b3940ca87

### Version

Cloud

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Datasource form footer height was defined to be `68px` but the height was shrinking to limited space. Adding `flex-shrink: 0` doesn't shrink the footer's height where the datasource auth buttons are present.
Screenshot 2024-06-04 at 2 22 09 PM

Fixes #33826 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9368964611>
> Commit: 6c3de7685a79e2540b64424e71cb728147ec64e9
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9368964611&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **Style**
  - Updated the `SaveButtonContainer` to include `flex-shrink: 0;` for improved layout behavior.

### CODE REVIEW

**Comment by rohan-arthur** [comment]
@AmanAgarwal041 is this a common fix for all datasources?

**Comment by AmanAgarwal041** [comment]
> @AmanAgarwal041 is this a common fix for all datasources?

Yes @rohan-arthur

**Comment by AmanAgarwal041** [comment]
> /build-deploy-preview skip-tests=true

It is already there : https://github.com/appsmithorg/appsmith/pull/33957#issuecomment-2147030999

File: app/client/src/pages/common/datasourceAuth/index.tsx [hunk 1]
```diff
@@ -121,6 +121,7 @@ const SaveButtonContainer = styled.div<{
   border-color: var(--ads-v2-color-border);
   align-items: center;
   height: 68px;
+  flex-shrink: ${(props) => (props.isInsideReconnectModal ? "unset" : "0")};
```
Comment (sneha122) [inline app/client/src/pages/common/datasourceAuth/index.tsx:124]: Why are we adding this check for isInsideReconnectModal? I checked by importing an app and there also the buttons at the bottom fluctuate when we switch between datasources

Comment (sneha122) [inline app/client/src/pages/common/datasourceAuth/index.tsx:124]: Why are we adding this check for isInsideReconnectModal? I checked by importing an app and there also the buttons at the bottom fluctuate when we switch between datasources

Comment (AmanAgarwal041) [reply app/client/src/pages/common/datasourceAuth/index.tsx:124]: The issue was raised for the datasource form. The reconnect modal already has limited space and adding this css will limit more space for the form, so I haven't addressed the design changes for reconnect model. This might also require design suggestions. Do you think we should delay this papercut for the particular thing ?

Comment (sneha122) [reply app/client/src/pages/common/datasourceAuth/index.tsx:124]: Sounds good to me! Can you please create separate issue to track that?

**Comment by AmanAgarwal041** [comment]
Similar Ui inconsistency for reconnect modal : https://github.com/appsmithorg/appsmith/issues/33970

File: app/client/src/pages/common/datasourceAuth/index.tsx (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/common/datasourceAuth/index.tsx:124]: Reconnect modal ui inconsistency : https://github.com/appsmithorg/appsmith/issues/33970
