### PR TITLE
fix: Update copy and flag for all toggle buttons on Admin settings page

### LINKED ISSUE #11702: [Bug]: Toggle buttons on Admin settings page has incorrect copies and flag
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I go to the form login authentication config setup page, the toggle is by default turned off and the text reads disabled. It should by default by on and text should be read enabled.
There is a similar issue on all toggles under the Admin settings pages

### Steps To Reproduce

1. Go to the Admin Settings page.
2. Click on the Authentication tab.
3. Click on the Form login edit button.
4. Notice the toggle copy and flag.

### Environment

Production

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

> Updated the copy and flags for all toggle buttons on the Admin settings page so it is easy to understand on the UI.

Fixes #11702 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Go to the Admin Settings page
- Click on the Authentication tab.
- Click edit for Form Login authentication method.
- Check the default toggle value for Form login should be Enabled and the flag should be on.
- On clicking the toggle and saving the changes, the form login should turn off (provided some other authentication method is enabled).

[LOOM DEMO](https://www.loom.com/share/cdead02a72fb44979829b1fadce2f96a)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: hotfix/toggle-buttons 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.91 **(0)** | 37.28 **(0.01)** | 35.3 **(0)** | 56.24 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

File: app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx [hunk 1]
```diff
@@ -40,9 +40,9 @@ const Form_Auth: AdminConfigType = {
       label: "Form Login Option",
       toggleText: (value: boolean) => {
         if (value) {
-          return "Disabled";
+          return "Enabled";
         } else {
-          return " Enabled";
+          return " Disabled";
         }
       },
```
Comment (IAmAnubhavSaini) [inline app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx:47]: This can be one lined: `toggleText: (value: boolean) => value ? "Enabled" : "Disabled",`

File: app/client/src/pages/Settings/FormGroup/Toggle.tsx [hunk 2]
```diff
@@ -26,16 +26,19 @@ function FieldToggleWithToggleText(toggleText?: (value: boolean) => string) {
     },
   ) {
     function onToggle(value?: boolean) {
-      ComponentProps.input.onChange && ComponentProps.input.onChange(value);
-      ComponentProps.input.onBlur && ComponentProps.input.onBlur(value);
+      ComponentProps.input.onChange && ComponentProps.input.onChange(!value);
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/FormGroup/Toggle.tsx:29]: Why is param name starting with a capital letter?

File: app/client/src/pages/Settings/config/general.ts [hunk 3]
```diff
@@ -66,7 +66,7 @@ export const config: AdminConfigType = {
         if (value) {
           return "Don't share any data";
         } else {
-          return "Share Anonymous Telemetry";
+          return " Share Anonymous Telemetry";
```
Comment (IAmAnubhavSaini) [inline app/client/src/pages/Settings/config/general.ts:69]: A space? This should be handled in UI via CSS.

**Review by IAmAnubhavSaini — CHANGES_REQUESTED** [review]

**Review by IAmAnubhavSaini — APPROVED** [review]

**Review by albinAppsmith — APPROVED** [review]

**Comment by ankitakinger** [comment]
@RakshaKShetty could you please test the deploy preview for this and give confirmation?

**Comment by RakshaKShetty** [comment]
Seems good can be merged
