### PR TITLE
Wait for server to start before Cypress tests

### LINKED ISSUE #5845: [Bug] All Cypress tests fails randomly in CI
## Description

All Cypress tests fails randomly in CI. This would happen if setup-tests.sh is run before server is started

### Steps to reproduce the behavior:

Run tests via ci/client-test.yml

### PR DESCRIPTION
**Pull request by yatinappsmith**
## Description
This PR checks if the server has started before proceeding to cypress tests

Fixes #5845

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

I have tested the new workflow in my local fork.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

File: app/client/cypress/setup-test.sh [hunk 1]
```diff
@@ -41,6 +41,22 @@ sleep 30
...
+
+while [  "$retry_count" -le "3"  -a  "$status_code" -eq "502"  ]; do
+	echo "Hit 502.Server not started retrying..."
+	retry_count=$((1 + $retry_count))
+	sleep 30
+	status_code=$(curl -o /dev/null -s -w "%{http_code}\n" https://dev.appsmith.com/api/v1/users)
+done
+
+if [ "$status_code" -eq "502" ]; then
+  echo "Hit 502"
```
Comment (mohanarpit) [inline app/client/cypress/setup-test.sh:57]: Can we exit the shell script here? If by now the server hasn't started, all the client tests will fail anyway. No point executing further.

Comment (yatinappsmith) [reply app/client/cypress/setup-test.sh]: Added an exit if unable to connect to server.

**Review by mohanarpit — APPROVED** [review]
