### PR TITLE
fix: fix refresh token flow in REST API OAuth

### LINKED ISSUE #10493: [Bug]: Refresh token is not being processed correctly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A user is reporting that the refresh token is not being processed correctly and therefore they must re-authorize the application on a daily basis.  The application (Infusionsoft Max Classic) doesn't use the offline_access method of OAuth2, so needs some investigation.  

### Steps To Reproduce

Need to get on a call with the user to investigate this issue.

### Environment

Production

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- This PR adds the following config to REST API datasource when OAuth2.0 authentication is selected:
  - config to add client credentials on either header or body during refresh token flow.
  - if scope needs to be sent on refresh token flow.
- The configurations above are required because various OAuth servers behave differently and prefer different configurations. 
- This PR also includes minor refactor to improve code debuggability (no change in code logic)
-  Client side changes to add config on the REST API datasource page.

Fixes #10493 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix_refresh_token_10493 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.02 **(-0.01)** | 36.35 **(-0.02)** | 34.71 **(0)** | 55.4 **(-0.01)**
 :red_circle: | app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx | 25 **(-0.98)** | 14.08 **(-1.3)** | 2.7 **(-0.08)** | 27.66 **(-1.23)**</details>

### CODE REVIEW

**Comment by nidhi-nair** [comment]
LGTM, would recommend that the client adds these into a separate "Advanced" section since these settings won't usually be helpful for providers that follow the spec.

**Review by nidhi-nair — APPROVED** [review]

File: app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx [hunk 1]
```diff
@@ -620,6 +634,9 @@ class DatasourceRestAPIEditor extends React.Component<Props> {
           )}
         </FormInputContainer>
         {content}
+        <Collapsible defaultIsOpen title="Advanced Settings">
```
Comment (nidhi-nair) [inline app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx:637]: Can we keep this settings closed by default? We should design for least friction for the 80% user base

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java [hunk 2]
```diff
@@ -174,7 +191,8 @@
             body.with(Authentication.RESOURCE, oAuth2.getResource());
         }
         // Optionally add scope, if applicable
-        if (!CollectionUtils.isEmpty(oAuth2.getScope())) {
+        if (!CollectionUtils.isEmpty(oAuth2.getScope())
+                && (Boolean.TRUE.equals(oAuth2.getSendScopeWithRefreshToken()) || oAuth2.getSendScopeWithRefreshToken() == null)) {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java:195]: I'm not sure if these settings make sense for client credentials, since we don't really use the refresh token grant type in this flow. In client credentials grant type, the original request is sent again to get new the new access token. @sumitsum

Comment (sumitsum) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java]: @nidhi-nair thanks for catching this :) . I totally didn't know about it.

Comment (nidhi-nair) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java]: We should also make the advanced settings appear only for Authorization code grant type on the UI. I believe it appears for all OAuth2 types right now.

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Needs a few UI changes

**Review by nidhi-nair — APPROVED** [review]

**Review by nidhi-nair — APPROVED** [review]

**Review by Irongade — APPROVED** [review]
