### PR TITLE
fix: v.1.9.5 Map Widget can't choose color on Markers and Unresponsive on updating (by requerying)

### LINKED ISSUE #20271: [Bug]: v.1.9.5 Map Widget can't choose color on Markers and Unresponsive on updating (by requerying)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2023-02-01 at 00 13 35
Before 1.9.5, i have a database of places with categories that linked to Map Widget and show colors based on the categories.

e.g. Category A showed by Red Marker
Category B showed by Green marker
etc.

Screenshot 2023-01-30 at 15 43 25
Now on 1.9.5 revamp on using latest maps library, the color won't change based on it. And also when filtering the places based on their region/category (by re-quering), the webapp becomes unresponsive. And sometimes the filtered places didn't update properly.

### Steps To Reproduce

Video attached below:

Left Side: Self Hosted 1.9.4 (the expected function)

Right Side: Cloud 1.9.5
- Marker colors ignored
- Appsmith become slow when querying filter
- Maps showing unexpected, wrong, filtered places. (Expected result is shown on the left side)

### Public Sample App

_No response_

### Issue video log

https://youtu.be/8vEL_00KgNs

### Version

Cloud - 1.9.5

Front logo [Front conversations](https://app.frontapp.com/open/top_753ik)

### PR DESCRIPTION
**Pull request by jsartisan**
## Description
When we worked on replacing the underlying library of google map component, we accidently replaced the custom icon with the one provided by google due to which color functionality got lost. This PR fixes this and also tracks for changes in position or color in the marker values.

Fixes #20271 

## Type of change
- Bug fix 

## How Has This Been Tested?
- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/MapWidget/component/Markers.tsx [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+          onClick={() => {
+            if (clickedMarkerCentered) {
+              updateCenter(marker.lat, marker.long);
+            }
+
+            selectMarker(marker.lat, marker.long, marker.title);
+          }}
+          onDragEnd={(e) => {
+            updateMarker(
+              Number(e.latLng?.lat()),
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Markers.tsx:53]: If latLng is undefined then we will be passing `NaN` to updateMarker

File: app/client/src/widgets/MapWidget/component/Marker.tsx [hunk 2]
```diff
@@ -6,23 +6,48 @@ type MarkerProps = google.maps.MarkerOptions & {
   map?: google.maps.Map;
   markerClusterer?: MarkerClusterer;
   onDragEnd?: (e: google.maps.MapMouseEvent) => void;
+  color?: string;
+};
+
+const MARKER_ICON = {
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Marker.tsx:12]: Let us move this to Widget's constant

File: app/client/src/widgets/MapWidget/component/Marker.tsx [hunk 3]
```diff
@@ -6,23 +6,48 @@ type MarkerProps = google.maps.MarkerOptions & {
...
+    onClick,
+    onDragEnd,
+    position,
+    ...rest
+  } = options;
   const [marker, setMarker] = useState<google.maps.Marker>();
 
+  const icon = {
+    ...MARKER_ICON,
+    anchor: new google.maps.Point(12, 24),
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Marker.tsx:33]: Why are creating a `Point` with 12, 14 coordinates? Is there a rationale behind it?

File: app/client/src/widgets/MapWidget/component/Map.tsx [hunk 4]
```diff
@@ -119,7 +124,10 @@ const Map = (props: MapProps) => {
         id="map"
         ref={mapRef}
       />
-      <Clusterer
+      <MarkerOrCluster
+        key={`markers-${allowClustering ? "cluster" : "markers"}-${
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Map.tsx:128]: This will lead to multiple markers having the same key. Can we make this key unique?

File: app/client/src/widgets/MapWidget/component/Marker.tsx [hunk 5]
```diff
@@ -6,23 +6,48 @@ type MarkerProps = google.maps.MarkerOptions & {
...
+    fillColor: color || "#ea4335",
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Marker.tsx:34]: Move these default values to a constant file like `#ea4335` anchor

File: app/client/src/widgets/MapWidget/component/Map.tsx (hunk 4 above)
Comment (jsartisan) [reply app/client/src/widgets/MapWidget/component/Map.tsx:128]: Actually its `Markers` or `Clusterer`. Renamed it.

File: app/client/src/widgets/MapWidget/component/Marker.tsx (hunk 5 above)
Comment (jsartisan) [reply app/client/src/widgets/MapWidget/component/Marker.tsx:34]: Done.

File: app/client/src/widgets/MapWidget/component/Marker.tsx (hunk 3 above)
Comment (jsartisan) [reply app/client/src/widgets/MapWidget/component/Marker.tsx:33]: Not sure about this. It added it because it was added in old code too for custom icon. I think its used to move the icon up little bit.

File: app/client/src/widgets/MapWidget/component/Marker.tsx (hunk 2 above)
Comment (jsartisan) [reply app/client/src/widgets/MapWidget/component/Marker.tsx:12]: done.

File: app/client/src/widgets/MapWidget/component/Markers.tsx (hunk 1 above)
Comment (jsartisan) [reply app/client/src/widgets/MapWidget/component/Markers.tsx]: added a check.

File: app/client/src/widgets/MapWidget/component/Map.tsx (hunk 4 above)
Comment (keyurparalkar) [reply app/client/src/widgets/MapWidget/component/Map.tsx:128]: We need to make the key Unique key={`markers-${allowClustering ? "cluster" : "markers"}-${`markers?.length}

File: app/client/src/widgets/MapWidget/component/Markers.tsx [hunk 6]
```diff
@@ -49,11 +49,13 @@ const Markers: React.FC<MarkersProps> = (props) => {
...
           }}
           onDragEnd={(e) => {
-            updateMarker(
-              Number(e.latLng?.lat()),
-              Number(e.latLng?.lng()),
-              index,
-            );
+            if (e.latLng && e.latLng.lat() && e.latLng.lng()) {
+              updateMarker(
+                Number(e.latLng?.lat()),
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Markers.tsx:54]: Then we don't need `?`

Comment (jsartisan) [reply app/client/src/widgets/MapWidget/component/Markers.tsx]: removed it.

**Review by keyurparalkar — APPROVED** [review]

**Review by keyurparalkar — APPROVED** [review]
