### PR TITLE
fix: fix git sync related bugs for Custom JS Lib feature

### LINKED ISSUE #19038: [Bug]: [CustomJSLib] Fix git sync related bugs on the server side
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

At the moment the following seems to work / fail:
- works:
Export, Import, Fork, Clone, Git Import on same instance, Git pull, Git merge
- fails:
  - Export also exports js lib meta data for published state separately causing duplication (but does not seem to cause issue with import)
  - Git Export does not export js lib meta data
  - Git Import fails to install js lib (although overall import succeeds) when importing across instance (because export fails to export meta data)
  - Git diff does not show status explicitly

### Steps To Reproduce

.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

self hosted

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Fix git import / export / status related bugs. Please check out this issue for more details : https://github.com/appsmithorg/appsmith/issues/19038
- Remove feature flag usage from the server side, since it was interfering with the JUnit TCs. Please note that the overall feature is still under feature flag since the client side also uses the same feature flag. 

Fixes #19038

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- JUnit TC

Test plan is the same as the one present for https://github.com/appsmithorg/appsmith/pull/17895

Issues raised during QA
- [ ] https://github.com/appsmithorg/appsmith/pull/19352#issuecomment-1373626895

### Dev activity
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 1]
```diff
@@ -554,6 +574,19 @@ private ApplicationGitReference fetchApplicationReference(Path baseRepoPath, Gso
...
+        Path jsLibDirectory = baseRepoPath.resolve(JS_LIB_DIRECTORY);
+        File directory = jsLibDirectory.toFile();
+        if (directory.isDirectory()) {
+            // Loop through all the directories and nested directories inside the pages directory to extract
+            // pages, actions and actionCollections from the JSON files
+            for (File jsLib : directory.listFiles()) {
+                jsLibrariesMap.put(jsLib.getName(), readFile(jsLib.toPath(), gson));
+            }
+        }
+        applicationGitReference.setJsLibraries(jsLibrariesMap);
```
Comment (AnaghHegde) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:588]: Can we use the existing readFile method to get this information?

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 2]
```diff
@@ -554,6 +574,19 @@ private ApplicationGitReference fetchApplicationReference(Path baseRepoPath, Gso
             default:
         }
         applicationGitReference.setMetadata(metadata);
+
+        Map<String, Object> jsLibrariesMap = new HashMap<>();
+        Path jsLibDirectory = baseRepoPath.resolve(JS_LIB_DIRECTORY);
+        File directory = jsLibDirectory.toFile();
+        if (directory.isDirectory()) {
+            // Loop through all the directories and nested directories inside the pages directory to extract
+            // pages, actions and actionCollections from the JSON files
```
Comment (AnaghHegde) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:583]: Could you please help me understand this comment? Why do we need to loop through all the resources?

**Review by AnaghHegde — CHANGES_REQUESTED** [review]
All the changes done to ImportExportServiceV2 needs to copied to ImportExportService. The export and import by file is still using the same service. I am afraid we don't have any other way till we finish this up. Apologies for the inconvenience.

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java (hunk 2 above)
Comment (sumitsum) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java]: @AnaghHegde sorry, this comment got copied over from another place. This comment would not apply here. Removed it now.

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java (hunk 1 above)
Comment (sumitsum) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:580]: Done.

**Review by AnaghHegde — DISMISSED** [review]

**Comment by ramsaptami** [comment]
- [ ] Commit message does not show up for a branch
https://www.loom.com/share/23b2dead86f24fc895543dec6080c38a

- [ ]

**Comment by AnaghHegde** [comment]
@ramsaptami I don't see the git discard scenario covered in the test plan. Can we ensure that git discard is also handled correctly?

**Comment by ramsaptami** [comment]
@AnaghHegde Yep, will add those in. Thanks for reviewing!

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/GitStatusDTO.java [hunk 3]
```diff
@@ -25,22 +25,25 @@ public class GitStatusDTO {
...
 
-        // # of modified JSObjects
-        Long modifiedJSObjects;
+        // number of modified actions
+        int modifiedQueries;
 
-        // # of modified JSObjects
-        Long modifiedDatasources;
+        // number of modified JSObjects
+        int modifiedJSObjects;
```
Comment (sidhantgoel) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/GitStatusDTO.java:38]: QQ: Why we are modifying the data type?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java [hunk 4]
```diff
@@ -21,6 +21,7 @@
 import com.appsmith.server.domains.ActionCollection;
```
Comment (sidhantgoel) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java:21]: You need to apply this change to ImportExportApplicationCEImpl.java as well, this file is used for git and the other one for normal import/export. Soon both will use  V2.

**Review by sidhantgoel — CHANGES_REQUESTED** [review]
Looks good, 1 question, 1 change request

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/GitStatusDTO.java (hunk 3 above)
Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/GitStatusDTO.java:38]: @sidhantgoel the initial data type was `Long`, however IMO, we don't expect the number of changes to be so many that we actually need the `Long` data type. Please let me know if you think otherwise.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java (hunk 4 above)
Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java:21]: @sidhantgoel this change has already been done in `ImportExportApplicationCEImpl.java` - the current PR is changes specific to `Git`.

**Review by sidhantgoel — APPROVED** [review]

**Review by abhvsn — APPROVED** [review]
