### PR TITLE
fix: revoke access and limit reached modal updates

### LINKED ISSUE #11750: [Task]: rest of the git sync polishing tasks
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Figure out scenarios in which error message come up, and 
- [ ] (try to) remove two error messages on git merge tab
- [x] Update design of disconnection, move error down below, remove breadcrumbs etc 
- [x] Improve repo disconnection messaging ( this has been deprioritised )
- [x] Error toast when remote branches are clicked ( will be resolved via #11757 )
- [x] Hover state for modal elements
- [x] Error should point towards field that needs fixing. ( this requires a design change to form elements overall )
- [ ] Add git error in a notification banner on connection tab

Refer:

Two error messages on git merge
Two error messages on git merge

Improve repo disconnection messaging

The following has been deprioritised because it is hard for user to find it

Error toast when remote branches are clicked

Errors should point towards field that can be fixed to correct
(This will be taken up in a separate effort to bring form errors closer to form field.)

These tasks are taken from #11558

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
## Description

Resolves rest of git polishing issues

Fixes #11750 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: 11750-fix-rest-git-sync-polishing-issues 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.65 **(0)** | 36.91 **(0)** | 34.95 **(-0.01)** | 55.96 **(0)**
 :red_circle: | app/client/src/ce/constants/messages.ts | 76.75 **(-0.05)** | 100 **(0)** | 30.99 **(-0.13)** | 81.49 **(0.06)**</details>

### CODE REVIEW

**Review by haojin111 — APPROVED** [review]

**Review by haojin111 — APPROVED** [review]

File: app/client/src/pages/Editor/gitSync/RepoLimitExceededErrorModal.tsx [hunk 1]
```diff
@@ -162,7 +165,7 @@ function RepoLimitExceededErrorModal() {
           </Text>
           <Text
             color={Colors.BLACK}
-            style={{ marginTop: theme.spaces[3] }}
+            style={{ marginTop: theme.spaces[3], width: "410px" }}
```
Comment (ankitakinger) [inline app/client/src/pages/Editor/gitSync/RepoLimitExceededErrorModal.tsx:168]: any reason we are using inline styles instead of assigning styles with classname?

Comment (IAmAnubhavSaini) [reply app/client/src/pages/Editor/gitSync/RepoLimitExceededErrorModal.tsx:168]: I know this is bad, but I am going with existing code as of right now. I will attempt refactoring soon.
