### PR TITLE
fix: API Url Whitespace Bug Fix

### LINKED ISSUE #21629: [Bug]: REST/ GraphQL: If there is a space before the API, it throws an error unlike postman where spaces before API/ URI is allowed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

graphQL/ Rest API -  If there is a space before the API, it throws an error unlike postman where spaces before API/ URI is allowed.

### Steps To Reproduce

1. Click on query to add a new balnk REST/ GraphQL API
2. Say the API is - https://countries.trevorblades.com
3. Query is - query CountryFilterInput{
    countries{
        code
        name
        capital
        continent{
            code
            name
        }
		}
}

4. Give a space before the API
Observe - The error message is - Illegal character in scheme name at index 0:  https://countries.trevorblades.com

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/gUA53Sv4EnHPtHYq

### Version

1.9.12

### PR DESCRIPTION
**Pull request by PiyushPushkar02**
## Description

- Added trim method to remove the whitespace from the URL while creating the request URL.
- Notion doc for the issue and fix: https://www.notion.so/appsmith/API-GraphQL-URL-With-Whitespaces-449a8fa4f3fa49e490b4b4b0fe5a16d1

Fixes #21629 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- JUnit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/InitUtils.java [hunk 1]
```diff
@@ -13,7 +13,7 @@ public class InitUtils {
     public String initializeRequestUrl(ActionConfiguration actionConfiguration,
                                             DatasourceConfiguration datasourceConfiguration ) {
         String path = (actionConfiguration.getPath() == null) ? "" : actionConfiguration.getPath();
-        return datasourceConfiguration.getUrl() + path;
+        return datasourceConfiguration.getUrl().trim() + path;
```
Comment (sumitsum) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/InitUtils.java:16]: As requested by Arpit as well, please add a JUnit TC for this. Otherwise LGTM.

Comment (PiyushPushkar02) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/InitUtils.java:16]: Added the JUnit test case for this

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 2]
```diff
@@ -135,6 +135,39 @@ public void testValidJsonApiExecution() {
                 .verifyComplete();
     }
 
+    @Test
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:138]: @PiyushPushkar02 can you please add a test for GraphQL plugin as well ?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 3]
```diff
@@ -135,6 +135,39 @@ public void testValidJsonApiExecution() {
...
+        Mono<ActionExecutionResult> resultMono = pluginExecutor.executeParameterized(null, new ExecuteActionDTO(), dsConfig, actionConfig);
+        StepVerifier.create(resultMono)
+                .assertNext(result -> {
+                    assertTrue(result.getIsExecutionSuccess());
+                    assertNotNull(result.getBody());
+                    JsonNode data = ((ObjectNode) result.getBody()).get("data");
+                    assertEquals(requestBody, data.toString());
+                    final ActionExecutionRequest request = result.getRequest();
+                    assertEquals("https://postman-echo.com/post", request.getUrl());
+                    assertEquals(HttpMethod.POST, request.getHttpMethod());
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:160]: Should we remove all the following asserts since they are not related to the feature we are testing ? This should improve the readability of the test case.

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 4]
```diff
@@ -135,6 +135,39 @@ public void testValidJsonApiExecution() {
                 .verifyComplete();
     }
 
+    @Test
+    public void testValidApiExecutionWithWhitespacesInUrl() {
+        DatasourceConfiguration dsConfig = new DatasourceConfiguration();
+        //added whitespaces in url to validate successful execution of the same
+        dsConfig.setUrl("    https://postman-echo.com/post");
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:142]: Can you please add spaces in the end as well, so that it covers both the situations - spaces at the start and the tail.

**Review by sumitsum — APPROVED** [review]
