### PR TITLE
fix: git connected app, user gets redirected to the default branch on closing add pane

### LINKED ISSUE #31478: [Bug]: On closing the `Create a query/API` flow in a git connected app, user gets redirected to the default branch
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we click on the `x` button next to the `Create a query/API` in the entity pane, we get redirected to the default branch. This leads to a frustrating UX.

### Steps To Reproduce

1. Go to a git connected app.
2. Create a new branch.
3. In the new branch go to the `Queries` tab & click `New Query/API`.
4. Now click on the `x` button next to it.

**Expected:** The options to create new queries should disappear.
**Actual:** The user is redirected to the `Queries` tab of the default branch 

### Public Sample App

_No response_

### Environment

Production

### Severity

High (Blocker to building)

### Issue video log

https://www.loom.com/share/db7ca585becf41b9b268545fb5c36e1e

### Version

Cloud

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

When user tries to close the add pane, user gets redirected to the default branch in git connected apps.

Fixes #31478

## Automation

/ok-to-test tags="@tag.IDE, @tag.Git"

### :mag: Cypress test results

> [!CAUTION]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8261408748>
> Commit: `ff06b5d9655128e22b6fc3ec7a30e027d425b578`
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8261408748&attempt=3&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank"> Click here!</a>
> The following are new failures, please fix them before merging the PR: <ol>
> <li>cypress/e2e/Regression/ClientSide/BugTests/GitBugs_Spec.ts
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/API_Pane_spec.js
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/CopyQuery_RenameDatasource_spec.js
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/Hide_Page_spec.js
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/Page_Load_Spec.js
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/Pages_spec.js
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/Query_Datasource_spec.js </ol>
> To know the list of identified flaky tests - <a href="https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master" target="_blank">Refer here</a>

## Summary by CodeRabbit

- **New Features**
	- Enhanced JavaScript and Query addition functionality in the IDE editor pane for improved usability.

- **Refactor**
	- Improved navigation handling in both JavaScript and Query addition components for a more streamlined user experience.
- **Documentation**
	- Added `jsCollectionListURL` import and `FocusEntityInfo` type import. Introduced `getJSUrl` function for URL generation based on `FocusEntityInfo` parameters.

### CODE REVIEW

File: app/client/src/ce/pages/Editor/IDE/EditorPane/JS/hooks.ts [hunk 1]
```diff
@@ -18,15 +18,21 @@ import { ADD_PATH } from "@appsmith/constants/routes/appRoutes";
...
 export const useJSAdd = () => {
   const pageId = useSelector(getCurrentPageId);
   const dispatch = useDispatch();
+  const currentEntityInfo = identifyEntityFromPath(location.pathname);
   const { segmentMode } = useCurrentEditorState();
 
   return useCallback(() => {
     if (segmentMode === EditorEntityTabState.Add) {
       // since js don't have a add mode in CE
+      const url = getJSUrl(currentEntityInfo, false);
```
Comment (hetunandu) [inline app/client/src/ce/pages/Editor/IDE/EditorPane/JS/hooks.ts:34]: `currentEntityInfo` not used in the dependency list of this hook

File: app/client/src/ce/pages/Editor/IDE/EditorPane/Query/hooks.ts [hunk 2]
```diff
@@ -51,9 +51,9 @@ export const useQueryAdd = () => {
     let url = "";
     if (segmentMode === EditorEntityTabState.Add) {
       // Already in add mode, back to the previous active item
-      url = location.pathname.replace(`${ADD_PATH}`, "");
+      url = getQueryUrl(currentEntityInfo, false);
```
Comment (hetunandu) [inline app/client/src/ce/pages/Editor/IDE/EditorPane/Query/hooks.ts:54]: `currentEntityInfo` not added in the hook's dependency list

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Review by hetunandu — DISMISSED** [review]

**Review by hetunandu — APPROVED** [review]
