### PR TITLE
fix: Added Gsheet Auth Failure Analytic Event

### LINKED ISSUE #18980: [Feature]: Enable analytics events for authorisation of google sheet datasource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Enable analytics events for authorisation of google sheet datasource.

### Why should this be worked on?

This will help us to know the percentage of cases where google sheet authorisation has succeeded and improving upon that number.

https://www.notion.so/appsmith/Improve-GSheets-Conversions-e387633d9dbb4e37bd7c203bd9044b9f

### PR DESCRIPTION
**Pull request by sneha122**
## Description

Added analytic event for google sheet authorization failure. This will help us in understanding percentage of use cases where users are not authorizing their google sheet datasource

> Add a TL;DR when description is extra long (helps content team)

Fixes #18980 

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

- Manual
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/pages/common/datasourceAuth/index.tsx [hunk 1]
```diff
@@ -126,6 +127,9 @@ function DatasourceAuth({
 
   const { id: datasourceId, isDeleting } = datasource;
   const applicationId = useSelector(getCurrentApplicationId);
+  const pluginName = useSelector((state: AppState) =>
+    getPluginNameFromId(state, datasource?.pluginId),
```
Comment (ChandanBalajiBP) [inline app/client/src/pages/common/datasourceAuth/index.tsx:131]: Can you get pluginId from the above destructuring.(from line 128)

File: app/client/src/utils/AnalyticsUtil.tsx [hunk 2]
```diff
@@ -239,6 +239,7 @@ export type EventName =
   | "DEFAULT_CONFIGURATION_CHECKBOX_TOGGLED"
   | "CONNECT_BUTTON_ON_GIT_SYNC_MODAL_CLICK"
   | "DATASOURCE_AUTH_COMPLETE"
+  | "update_DATASOURCE"
```
Comment (ChandanBalajiBP) [inline app/client/src/utils/AnalyticsUtil.tsx:242]: Can you rename this to UPDATE_DATASOURCE and move it near line ~90? There are similar events around there.

Comment (sneha122) [reply app/client/src/utils/AnalyticsUtil.tsx:242]: @ChandanBalajiBP I have named the event as update_DATASOURCE because the backend event that we have added in case of successful authorization also has the same name and hence here also I have named the event like that. @vaibh1297 should I change the event name as per above comment and do we wanna keep it like backend event name only?

File: app/client/src/pages/common/datasourceAuth/index.tsx (hunk 1 above)
Comment (sneha122) [reply app/client/src/pages/common/datasourceAuth/index.tsx]: Resolved please check @ChandanBalajiBP

File: app/client/src/utils/AnalyticsUtil.tsx (hunk 2 above)
Comment (vaibh1297) [reply app/client/src/utils/AnalyticsUtil.tsx]: @ChandanBalajiBP on server side we send these type of events to analytics service with name = "update_DATASOURCE" only. Why is this change required ?

Comment (ChandanBalajiBP) [reply app/client/src/utils/AnalyticsUtil.tsx]: @vaibh1297 in the client side we maintain the other way round, it's only capital letters. 
@sneha122 can you discuss this with the team/Rohan? if they are fine with this, PR can be merged. (Just add a comment on your discussion here)

Comment (sneha122) [reply app/client/src/utils/AnalyticsUtil.tsx]: yes will do that

Comment (sneha122) [reply app/client/src/utils/AnalyticsUtil.tsx]: @ChandanBalajiBP Discussed with Rohan and updated the event name as per your comment, please check the changes

**Review by ChandanBalajiBP — APPROVED** [review]
