### PR TITLE
Fixes failure due to extra spaces in authorization url in OAuth2 datasource

### LINKED ISSUE #4807: IllegalArgumentException: Illegal character in scheme name at index 0: Authorization URL with spaces around it fails
Sentry Issue: [APPSMITH-V9](https://sentry.io/organizations/appsmith/issues/2423248271/?referrer=github_integration)

```
URISyntaxException: Illegal character in scheme name at index 0: %20https://accounts.google.com/o/oauth2/v2/auth?client_id=898800068064-c8jtgtun9tnqtqqfj47o6erqj8bprgr3.apps.googleusercontent.com&response_type=code&redirect_uri=https://app.appsmith.com/api/v1/datasources/authorize&state=604f1511c046f668d7bcc096,604f1537c046f668d7bcc098,https://app.appsmith.com&scope=https://www.googleapis.com/auth/spreadsheets&prompt=consent&access_type=offline
    at com.appsmith.server.controllers.DatasourceController.lambda$getTokenRequestUrl$2(DatasourceController.java:66)
...
(103 additional frame(s) were not displayed)

IllegalArgumentException: Illegal character in scheme name at index 0: %20https://accounts.google.com/o/oauth2/v2/auth?client_id=898800068064-c8jtgtun9tnqtqqfj47o6erqj8bprgr3.apps.googleusercontent.com&response_type=code&redirect_uri=https://app.appsmith.com/api/v1/datasources/authorize&state=604f1511c046f668d7bcc096,604f1537c046f668d7bcc098,https://app.appsmith.com&scope=https://www.googleapis.com/auth/spreadsheets&prompt=consent&access_type=offline
    at com.appsmith.server.controllers.DatasourceController.lambda$getTokenRequestUrl$2(DatasourceController.java:66)
...
(98 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by nidhi-nair**
Validation rule for URL

Fixes #4807

### CODE REVIEW

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DatasourceValidator.java [hunk 1]
```diff
@@ -6,9 +6,18 @@
...
 import java.util.Set;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
 
 public class DatasourceValidator {
 
+    private static final String URL_REGEX =
+            "^(https?://" +
+                    "(%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@&=+$,A-Za-z0-9])+)" +
+                    "([).!';/?:,][[:blank:]])?$";
```
Comment (sharat87) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DatasourceValidator.java:17]: What is the last group for? Doesn't look like it's needed, and I can't find the `[[:blank:]]` syntax on the [Pattern class either](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html)?

```suggestion
            "^https?://" +
                    "(%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@&=+$,A-Za-z0-9])+$"
```

This seems to work just as well no?

**Review by sharat87 — DISMISSED** [review]

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DatasourceValidator.java [hunk 2]
```diff
@@ -6,9 +6,17 @@
...
 import java.util.HashSet;
 import java.util.Set;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
 
 public class DatasourceValidator {
 
+    private static final String URL_REGEX =
+            "^https?://" +
+                    "(%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@&=+$,A-Za-z0-9])+$"
```
Comment (sharat87) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DatasourceValidator.java:16]: Sorry, my bad :)

```suggestion
                    "(%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@&=+$,A-Za-z0-9])+$";
```

**Review by sharat87 — APPROVED** [review]
