### PR TITLE
fix: isRequired validation property for table select column

### LINKED ISSUE #30091: [Feature]: Support Validation Section and Required Toggle for Select Column Type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The validation section and required toggle are not available for Select column types.
We only provide the Required toggle and the Validation section for Plain Text column types, but not for Select column types. 

### Why should this be worked on?

A user who uses the editable table with a Select column type may want to make this field required.

[Front thread](https://app.frontapp.com/open/cnv_17c1zn9o?key=D_DYOgA4TJ0FAMJncD9gtO48E5mJZGtm)

Front logo [Front conversations](https://app.frontapp.com/open/top_4e78y4)

### PR DESCRIPTION
**Pull request by jacquesikot**
## Description

**Problem**
The select column of the table widget does not have a validation property within its property pane to allow users add an isRequired validation to the table select column.

**Solution**
Added a Validation section to the table select column's property pane, which includes an isRequired toggle. When enabled, this feature will trigger a visual indication (error border colour) around the select widget if a required field is left unselected during "Add new row" or inline editing.

Fixes #30091 

## Automation

/ok-to-test tags="@tag.Widget, @tag.Table, @tag.Binding, @tag.Sanity, @tag.Select"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10957896180>
> Commit: d2597e6a26938f2b99f2f997fca7bc110e5c2091
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10957896180&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Widget, @tag.Table, @tag.Binding, @tag.Sanity, @tag.Select`
> Spec:
> <hr>Fri, 20 Sep 2024 12:23:29 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced end-to-end tests for Select column validation in Table widgets.
	- Enhanced validation logic to support Select column types in the Table widget.
	- Added visual feedback for required Select fields during row addition and inline editing.
	- Improved locator for single-select widget button control to enhance UI interaction.

- **Bug Fixes**
	- Improved error handling and visual representation for invalid editable Select cells.

- **Documentation**
	- Updated validation configuration to include Select column types for better usability.

- **Refactor**
	- Enhanced code clarity for styled components related to Select fields.
	- Modified method to improve versatility in handling table interactions.

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+            ]
+            `,
+      );
+
+      // Click the first cell in the step column
+      (cy as any).editTableSelectCell(0, 0);
+
+      // Exect the select to have an error color
+      _.agHelper
+        .GetElement(".bp3-button.select-button")
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts:111]: Please create a locator and use it. Please do check all the locators

**Review by sagar-qa007 — CHANGES_REQUESTED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts [hunk 2]
```diff
@@ -0,0 +1,120 @@
+import * as _ from "../../../../../../support/Objects/ObjectsCore";
```
Comment (rahulbarwal) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts:1]: Instead of importing `*` import and use specific objects that you want to use.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+                "task": "Bind the query using => fetch_users.data",
+                "status": "--",
+                "action": ""
+              }
+            ]
+            `,
+      );
+
+      // Click the first cell in the step column
+      (cy as any).editTableSelectCell(0, 0);
```
Comment (rahulbarwal) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts:112]: Don't we have a table counterpart helper method, instead of `cy`

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+        .contains("#1")
+        .click();
+
+      // Expect the save row option to be enabled
+      _.agHelper.GetElement(_.table._saveNewRow).should("be.enabled");
+
+      // Expect button to have a valid color
+      _.agHelper
+        .GetElement(commonlocators.singleSelectWidgetButtonControl)
+        .should("have.css", "border-color", "rgb(85, 61, 233)");
```
Comment (rahulbarwal) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts:77]: can we use some better way to check this? maybe a class?
If not able to, lets put this as a constant, so that if it updates it updates everywhere.

**Review by rahulbarwal — CHANGES_REQUESTED** [review]
Requesting minor changes. Overall looks good.

**Review by rahulbarwal — DISMISSED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+
+const TABLE_SELECT_WIDGET_ERROR_BORDER = "rgb(217, 25, 33)";
+const TABLE_SELECT_WIDGET_VALID_BORDER = "rgb(85, 61, 233)";
+
+describe(
+  "Table widget - Select column validation",
+  { tags: ["@tag.Widget", "@tag.Table", "@tag.Select"] },
+  () => {
+    before(() => {
+      cy.dragAndDropToCanvas("tablewidgetv2", { x: 350, y: 500 });
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts:20]: Can we use aghelper or some TS functions ?

**Review by sagar-qa007 — CHANGES_REQUESTED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts (hunk 5 above)
Comment (jacquesikot) [reply app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Table_select_validation_spec.ts]: Change made

**Review by sagar-qa007 — APPROVED** [review]
