### PR TITLE
Fix: Update chart from array to object

### LINKED ISSUE #3406: [Bug] Convert chartData to be in object structure
## Description
Array data with nested paths are not the best to manage dynamicBindingPathLists which when wrong will cause an error on the server. We should update the structure to be object based to better handle this

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add chart with two series, both with bindings
2. Delete the first series
3. Server returns 400 error first while client recreates the dynamicBindingPathList

### PR DESCRIPTION
**Pull request by jsartisan**
Previously we were using the array structure of chart data which causes issue during evaluations. Moving to object structure now

Fixes #3406 
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change
- Bug fix

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hetunandu — DISMISSED** [review]
Approving to see cypress test results

**Review by riodeuno — DISMISSED** [review]
Approving to have the tests run

File: app/client/src/components/designSystems/appsmith/ChartComponent.tsx [hunk 1]
```diff
@@ -142,21 +145,24 @@ class ChartComponent extends React.Component<ChartComponentProps> {
...
   };
 
-  getChartCategoriesMutliSeries = (chartData: ChartData[]) => {
+  getChartCategoriesMutliSeries = (chartData: AllChartData) => {
     const categories: string[] = [];
-    for (let index = 0; index < chartData.length; index++) {
-      const data: ChartDataPoint[] = chartData[index].data;
+
+    Object.keys(chartData).forEach((key: string) => {
+      const data: ChartDataPoint[] = get(chartData, `${key}`).data;
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/ChartComponent.tsx:152]: Can we pass `key` instead of `${key}` here? Also, we need a default as the third argument, since the value could be `undefined` which will throw an error.

File: app/client/src/components/propertyControls/ChartDataControl.tsx [hunk 2]
```diff
@@ -1,5 +1,5 @@
 import React from "react";
-import _ from "lodash";
+import _, { get, isString, set } from "lodash";
```
Comment (riodeuno) [inline app/client/src/components/propertyControls/ChartDataControl.tsx:2]: Since we're tree shaking `lodash` here can we remove the need for `_` import?

File: app/client/src/components/propertyControls/ChartDataControl.tsx [hunk 3]
```diff
@@ -176,95 +182,104 @@ function DataControlComponent(props: RenderComponentProps) {
...
+          index={firstKey}
           item={data}
           length={1}
           deleteOption={this.deleteOption}
           updateOption={this.updateOption}
-          isValid={validations[0].isValid}
-          validationMessage={validations[0].validationMessage}
-          evaluated={evaluatedValue[0]}
+          isValid={get(validations, `${firstKey}`).isValid}
+          validationMessage={get(validations, `${firstKey}`).validationMessage}
```
Comment (riodeuno) [inline app/client/src/components/propertyControls/ChartDataControl.tsx:260]: If the `get` results in `undefined` we will see crashes where it won't be able to find property `isValid` or `validationMessage` of `undefined`. can we handle this scenario?

File: app/client/src/mockResponses/WidgetConfigResponse.tsx [hunk 4]
```diff
@@ -373,8 +363,8 @@ const WidgetConfigResponse: WidgetConfigReducerState = {
       chartName: "Sales on working days",
       allowHorizontalScroll: false,
       version: 1,
-      chartData: [
-        {
+      chartData: {
+        [generateReactKey()]: {
```
Comment (riodeuno) [inline app/client/src/mockResponses/WidgetConfigResponse.tsx:367]: If we use random numbers as keys, what will happen when the user is using the `chartData` as a binding?
I was wondering if we should use a different property to store this value and use the `chartData` as an array as we did originally. Let's discuss this.

File: app/client/src/workers/validations.ts [hunk 5]
```diff
@@ -299,11 +304,12 @@ export const VALIDATORS: Record<VALIDATION_TYPES, Validator> = {
     props: WidgetProps,
     dataTree?: DataTree,
   ): ValidationResponse => {
-    const { isValid, parsed } = VALIDATORS[VALIDATION_TYPES.ARRAY](
+    const { isValid, parsed } = VALIDATORS[VALIDATION_TYPES.OBJECT](
```
Comment (hetunandu) [inline app/client/src/workers/validations.ts:307]: Lets remove this old chart data validation

Comment (jsartisan) [reply app/client/src/workers/validations.ts]: removed

**Review by hetunandu — APPROVED** [review]

**Review by marks0351 — APPROVED** [review]

**Review by hetunandu — APPROVED** [review]
