### PR TITLE
fix: 10527 Google Sheet crud generation header issue v2

### LINKED ISSUE #10527: [Bug]: CRUD generation is not allowed when GSheet has only headers present
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a Google Sheet document has only headers and no data under those headers then the sheet cannot be used for CRUD.

[LOOM DEMO](https://www.loom.com/share/721afb5780264c91b62dc8452e130365)

### Steps To Reproduce

1. Create a Google sheet with only headers and try to use this on the CRUD feature.
2. Generate Page button is not activated until data is present under those headers.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by leotom2000**
## Description
The CRUD operation cannot be performed when there are no rows in the google sheet even though headers are present.
A fix was made so that even if there are no data rows but headers are present, then the button to initiate crud operation is enabled and crud operation can be done. If no rows are found including headers, then button is not enabled.

Fixes #10527

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
**Manual Tests Done**
| Test Case | Actions | Result | Status |
| --- | -----------| --- | :---: |
| Created a new Sheet through application| Create CRUD interface |Button not enabled |  Pass |
| Above steps + Added headers in row 1| Create CRUD interface | Button enabled |  Pass |
| Above steps +  Moved headers to row 2| Create CRUD interface  | Button NOT enabled |  Pass |
| Above steps +  Changed 'table header Index' in app to 2| Create CRUD interface  | Button enabled |  Pass |
| Above steps +  Added rows to the sheet| Create CRUD interface  | Button enabled |  Pass |
| Manually created empty sheet and created datasource|  Create CRUD interface | Button not enabled |  Pass |
| Above step + Added another sheet Sheet2| Create CRUD interface | Button not enabled |  Pass |
| Above steps + Added header in Sheet1| Create CRUD interface  | Button enabled |  Pass |
| Above steps + Added row in Sheet1| Create CRUD interface  | Button enabled |  Pass |
| Above steps + Changed table header Index' in app to 2 | Create CRUD interface  | Button enabled ** |  Pass |
| Above steps + Selected the Sheet2  | Create CRUD interface  | Button not enabled |  Pass |
| Above steps + Added row in Sheet2 | Create CRUD interface  | Button enabled |  Pass |
| Above steps + Inserted 3 row above headers in Sheet2 | Create CRUD interface  | Button Not enabled |  Pass |
| Above steps + Changed 'table header Index' in app to 4  |Create CRUD interface | Button enabled |  Pass |
** - App created with data as headers

Unit Tests Added
|----|
|com.external.config.GetStructureMethodTest.testTransformResponse_missingJSON_throwsException()|
|com.external.config.GetStructureMethodTest.testTransformResponse_missingValues_returnsEmpty()|
|com.external.config.GetStructureMethodTest.testTransformResponse_singleRowJSON_returnsEmpty()|
|com.external.config.GetStructureMethodTest.testTransformResponse_emptyJSON_returnsEmpty()|
|com.external.config.GetStructureMethodTest.testTransformResponse_emptyStartingRows_toListOfObjects()|
|com.external.config.GetStructureMethodTest.testTransformResponse_emptyRows_returnsIndices()|
|com.external.config.GetStructureMethodTest.testTransformResponse_VerifyEndResult()|

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: Fix10527_GS_Crud_Generation_Header_Isssue_V2 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.88 **(0)** | 37.23 **(-0.01)** | 35.22 **(0)** | 56.19 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+        GetStructureMethod getStructureMethod = new GetStructureMethod(objectMapper);
+        JsonNode result = getStructureMethod.transformResponse(jsonNode, null);
+
+        Assert.assertNotNull(result);
+        Assert.assertTrue(result.isArray());
+        Assert.assertEquals(0, result.size());
+    }
+
+    @Test
+    public void testTransformResponse_emptyJSON_returnsEmpty() throws JsonProcessingException {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java:46]: This scenario should not return as empty for get structure. We expect to be able to show column headers only.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java [hunk 2]
```diff
@@ -130,6 +130,39 @@
                 );
     }
 
+    /**
+     * @param datasourceId
+     * @param pluginSpecifiedTemplates
+     * @param ignoreCache
+     * @return
+     */
+    public Mono<DatasourceStructure> getStructure(String datasourceId, List<Property> pluginSpecifiedTemplates, boolean ignoreCache) {
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java:139]: How are we using the pluginSpecifiedTemplates here?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+        JsonNode result = getStructureMethod.transformResponse(jsonNode, new MethodConfig(List.of()).toBuilder().tableHeaderIndex("1").build());
+
+        Assert.assertNotNull(result);
+        Assert.assertTrue(result.isArray());
+        Assert.assertEquals(3, result.size());
+        Assert.assertEquals(0, result.get(0).get(GoogleSheets.ROW_INDEX).asInt());
+    }
+
+    @Test
+    public void transformResponse() throws JsonProcessingException {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java:121]: Could you please show an example of how get structure is different from get? What format does this response look like?

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Needs some changes to remove redundancies.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetStructureMethod.java [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+            try {
+                tableHeaderIndex = Integer.parseInt(methodConfig.getTableHeaderIndex());
+                if (tableHeaderIndex <= 0) {
+                    tableHeaderIndex = 1;
+                }
+            } catch (NumberFormatException e) {
+                // Should have already been caught
+            }
+        }
+        if ("ROWS".equalsIgnoreCase(methodConfig.getQueryFormat())) {
```
[the remark this answers is not in the document]
Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetStructureMethod.java:88]: Updated to fetch max by 2 rows
and removed code to fetch range

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java (hunk 2 above)
Comment (leotom2000) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java:139]: This method is not in use, so removed

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java (hunk 3 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java:121]: Removed this test as it is repetitive

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java (hunk 1 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java:46]: Updated the method name, this method tests the transposeResponse() specific to getStructure in which functions like WHERE condition, Range consideration are ignored. Test for pulling data from sheets are not included.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+
+public class GetStructureMethodTest {
+
+    @Test
+    public void testTransformResponse_missingJSON_throwsException() {
+        ObjectMapper objectMapper = new ObjectMapper();
+
+        GetStructureMethod getStructureMethod = new GetStructureMethod(objectMapper);
+        try {
+            getStructureMethod.transformResponse(null, null);
```
[the remark this answers is not in the document]
Comment (nidhi-nair) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java]: Yes I understand the test case, but it should also include the failing scenario. What happens if a refactor of the method fails to throw an error in the current test? It would simply pass through all the code without reporting an error.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java (hunk 3 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java]: @leotom2000 Could you please also include an example of the end result of this request?

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
I think we need to change the format of the response for this request. Please provide an example so we can discus over it with more clarity.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java]: Yes got it, updated the test case

File: app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java (hunk 3 above)
Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java]: Added a new Unit Test to evaluate end result derived from the method (testTransformResponse_VerifyEndResult())

Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java]: Input : 
`{"valueRanges":[{"range":"Sheet1!A1:D1","majorDimension":"ROWS","values":[["Name","Actor","Music","Director"]]},{"range":"Sheet1!A3:D7","majorDimension":"ROWS","values":[["Bean","Sean","Dean","Mean"],["Cow","Dow","Sow","Bow"],["Luke","Make","Duke","Cake"]]}]}`


Output :
`[{"Name":"Bean","Actor":"Sean","Music":"Dean","Director":"Mean","rowIndex":"1"},{"Name":"Cow","Actor":"Dow","Music":"Sow","Director":"Bow","rowIndex":"2"},{"Name":"Luke","Actor":"Make","Music":"Duke","Director":"Cake","rowIndex":"3"}]`

Comment (leotom2000) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetStructureMethodTest.java]: Updated end result to process as one row

**Review by nidhi-nair — APPROVED** [review]
We'll be working on getStructure again in another PR. This one allows us to fix the generate CRUD bug in a non-breaking way. We'll introduce a few other defaults to be able to use getStructure with this same set of calls in the future.
