### PR TITLE
fix: Change js lib file name in git to avoid file name error in windows

### LINKED ISSUE #29655: Git not working due to unsupported file name
When an application is git connected and it has custom js library, it can not be imported to a windows file system.

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This PR stops writing custom js libs to a file with the same name as url. 

#### PR fixes following issue(s)
Fixes #29655

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved file naming for saved items to avoid conflicts and ensure consistency.
  - Enhanced application import to prevent duplication of JavaScript libraries, ensuring a cleaner and more reliable setup.
  - Updated file migration message for improved clarity and guidance.

### CODE REVIEW

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 1]
```diff
@@ -1108,4 +1110,13 @@ public Mono<Long> deleteIndexLockFile(Path path, int validTimeInSeconds) {
...
         }
     }
+
+    /**
+     * This method converts an URL string to a valid file name. The file name should not contain any character
+     * that's not allowed in any operating systems.
+     * @return String
+     */
+    public static String urlToFileName(String urlString) {
+        return urlString.replaceAll("[/:]", "_");
```
Comment (AnaghHegde) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:1120]: Can you help me understand what this function do and what pattern we decided for the name?

Comment (nayan-rafiq) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:1120]: @AnaghHegde Earlier, we were replacing the `/` character by `_` from the url string. Now, we're replacing the `:` character as well. This method removes these two characters from the url string and returns it.

Comment (AnaghHegde) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:1120]: What is the name format we have decided for the js objects?

File: app/server/appsmith-git/src/main/java/com/appsmith/git/constants/CommonConstants.java [hunk 2]
```diff
@@ -25,7 +25,7 @@ public class CommonConstants {
     public static final String DELIMITER_PATH = "/";
     public static final String EMPTY_STRING = "";
     public static final String FILE_MIGRATION_MESSAGE =
-            "Some of the changes above are due to an improved file structure designed to reduce merge conflicts. You can safely commit them to your repository.";
+            "Some of the changes above are due to an improved file structure. You can safely commit them to your repository.";
```
Comment (sondermanish) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/constants/CommonConstants.java:28]: Would this be the case for all such container messages? @infinitetrooper

**Review by AnaghHegde — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java [hunk 3]
```diff
@@ -539,7 +539,11 @@ private ApplicationJson getApplicationJsonFromGitReference(ApplicationGitReferen
 
         List<CustomJSLib> customJSLibList =
                 getApplicationResource(applicationReference.getJsLibraries(), CustomJSLib.class);
-        applicationJson.setCustomJSLibList(customJSLibList);
+
+        // remove the duplicate js libraries if there is any
```
Comment (sondermanish) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java:543]: QQ: Why would it be the case, are we adding any libraries while an export? Application contains the Uids in a set, so I'm assuming that the duplicates could only happen while exporting

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 4]
```diff
@@ -1108,4 +1113,30 @@ public Mono<Long> deleteIndexLockFile(Path path, int validTimeInSeconds) {
             return Mono.just(0L);
         }
     }
+
+    /**
+     * This method converts an URL string to a valid file name. The file name should not contain any character
```
Comment (sondermanish) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:1118]: let's update the description with what exactly we are doing over here?

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java [hunk 5]
```diff
@@ -1108,4 +1113,30 @@ public Mono<Long> deleteIndexLockFile(Path path, int validTimeInSeconds) {
...
+     * that's not allowed in any operating systems.
+     * @return String
+     */
+    public static String getJsLibFileName(String uidString) {
+        int firstUnderscoreIndex = uidString.indexOf('_'); // this finds the first occurrence of "_"
+        String prefix;
+        if (firstUnderscoreIndex != -1) {
```
Comment (sondermanish) [inline app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:1125]: QQ: the idea over here is that we are extracting the accessor from Uid string, right?

**Review by sondermanish — COMMENTED** [review]
added some nit comments, rest LGTM

File: app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java (hunk 5 above)
Comment (nayan-rafiq) [reply app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java:1125]: @sondermanish Yeah, you're right.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java (hunk 3 above)
Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java:543]: It shouldn't happen normally when you export from DB. Here we're constructing the ApplicationJson from file system. Consider a case: an application has two branches. In one branch, it has a js lib in new name format and got merged with a branch where the js lib is present in old name format. Then there might be chance of having two files in the file system for same js lib. This check is there to prevent this case.

**Review by sondermanish — APPROVED** [review]
LGTM

**Comment by sondermanish** [comment]
QQ: @nayan-rafiq What happens to the older files once we save the newer ones?
