### PR TITLE
Fix/multi select dropdown

### LINKED ISSUE #832: [Bug] Multi select Dropdown widget default value breaking
The multi select dropdown widget does not get selected value in view mode when set via bindings

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Validations removed for selectedOptionValueArr these ensures the default initialisation works.

Fixes #832 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Workflow is tested manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/DropdownWidget.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ class DropdownWidget extends BaseWidget<DropdownWidgetProps, WidgetState> {
       selectionType: VALIDATION_TYPES.TEXT,
       isRequired: VALIDATION_TYPES.BOOLEAN,
       // onOptionChange: VALIDATION_TYPES.ACTION_SELECTOR,
-      selectedOptionValueArr: VALIDATION_TYPES.ARRAY,
+      // selectedOptionValueArr: VALIDATION_TYPES.ARRAY,
```
Comment (Nikhil-Nandagopal) [inline app/client/src/widgets/DropdownWidget.tsx:27]: @vicky-primathon this does not work

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you review this

**Review by hetunandu — APPROVED** [review]
