### PR TITLE
fix: New user datasource test 404 issue fixed

### LINKED ISSUE #19426: [Bug]: [Cypress Test] On clicking test button for empty datasource, api /v1/datasources/test is returning 404 status code.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed in cypress tests , when on creating new datasource and clicking test button, the /api/v1/datasources/test returns 404 causing test to fail,
Screenshot 2023-01-02 at 4 20 44 PM

Screenshot 2023-01-02 at 4 32 40 PM

### Steps To Reproduce

1. Sign up as new user, create new datasource e.g. PostgreSQL
2. Click on Test button and observe

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by sneha122**
## Description
When a new user who signs up, creates datasource and tests it before saving it, then the test API is throwing 404 error. This PR fixes that issue 

Fixes #19426 

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug19426_spec.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { ObjectsRegistry } from "../../../../support/Objects/Registry";
+
+const dataSources = ObjectsRegistry.DataSources;
+
+describe("Testing empty datasource without saving should not throw 404", function() {
+  it("Bug 19426: Create empty S3 datasource, test it", function() {
+    dataSources.NavigateToDSCreateNew();
```
Comment (Parthvi12) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug19426_spec.ts:7]: @sneha122  Can we add test flow where we sign up as a new user and then create datasource as the bug was observed for the new user who creates datasource for the first time

Comment (sneha122) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug19426_spec.ts:7]: @Parthvi12 The bug was observed for new user sign up thats correct, but in case of existing user, it was there for S3 plugin with empty datasource, hence added case for that. Do you still want me to add it for new user sign up as well?

Comment (sneha122) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug19426_spec.ts:7]: For both the cases issue was same, and hence wrote the test for second case

Comment (Parthvi12) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug19426_spec.ts:7]: @sneha122 Alright then this should suffice.

**Comment by Parthvi12** [comment]
Cypress test LGTM.

**Review by hetunandu — APPROVED** [review]
