### PR TITLE
fix: Fix validation check that is blocking input from changing

### LINKED ISSUE #13919: [Bug]: [REGRESSION] Unable to configure Elasticsearch datasource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to add a new Elasticsearch datasource, I am not able to enter anything in the host url and port number. Here's the video with commentary:
[LOOM DEMO](https://www.loom.com/share/67327345256f4109b513b0c21c5f6902)

Tried a couple of other plugins and so far this seems to be affecting only elasticsearch

### Steps To Reproduce

1. open your app
2. add new datasource
3. select `elasticsearch`
4. try to enter host url or port number

Entry is blocked, the input fields don't reach to keystrokes

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Irongade**
Fixes validation regex checks blocking onChange function from firing in KeyValue array form input.

Fixes #13919

> if no issue exists, please create an issue and ask the maintainers about this first

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix-key-value-validation-check 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.65 **(0.01)** | 38.62 **(0.01)** | 35.97 **(0)** | 56.9 **(0.01)**
 :green_circle: | app/client/src/components/ads/TextInput.tsx | 79.84 **(0.61)** | 63.89 **(1.3)** | 87.5 **(0)** | 78.63 **(0.66)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Review by rashmi-rai — DISMISSED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]
Reviewed Cypress test, LGTM

File: app/client/src/components/ads/TextInput.tsx [hunk 1]
```diff
@@ -340,11 +340,7 @@ const TextInput = forwardRef(
...
           props.validator && setValidation(inputValueValidation);
 
-          return (
-            inputValueValidation.isValid &&
-            props.onChange &&
-            props.onChange(inputValue)
-          );
+          return props.onChange && props.onChange(inputValue);
         } else {
           return props.onChange && props.onChange(inputValue);
```
Comment (AmanAgarwal041) [inline app/client/src/components/ads/TextInput.tsx:345]: We can just move out the condition, as input value will eventually require a change.

File: app/client/src/components/formControls/KeyValueArrayControl.tsx [hunk 2]
```diff
@@ -78,10 +78,12 @@ function KeyValueRow(
...
         const regex = new RegExp(keyFieldProps?.validationRegex);
 
-        return regex.test(value) ? undefined : keyFieldProps.validationMessage;
+        return regex.test(value)
+          ? { isValid: true }
+          : keyFieldProps.validationMessage;
       }
 
-      return undefined;
+      return { isValid: true };
```
Comment (AmanAgarwal041) [inline app/client/src/components/formControls/KeyValueArrayControl.tsx:86]: Returning `undefined` would be a better option as it will indicate that `validationRegex` is not present.

**Review by rashmi-rai — APPROVED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]
Cypress tests LGTM
