### PR TITLE
Fixed handling of lists in dynamodb

### LINKED ISSUE #2812: [Bug] DynamoDB queries failing with serialization issue
image

### Steps to reproduce the behaviour:
1. Create a valid DynamoDB datasource
2. Run `ListTables` query to check if datasource functions properly
3. Run `DescribeTable` query with a TableName as shown to see the error
 
### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #2812 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Added JUnit test

### CODE REVIEW

File: app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java [hunk 1]
```diff
@@ -359,6 +360,16 @@ private static String getSetterMethodName(final String key) {
                 }
                 value = plainMap;
 
+            } else if (value instanceof List) {
```
Comment (trishaanand) [inline app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java:363]: Random question. Is it possible for dynamodb to in future return a List<Map<String, SdkPojo> ? Do we need to have a recursive solve for this?

**Comment by sharat87** [comment]
Looks good as a solution to the issue marked as critical. But as discussed earlier (and as pointed out by @trishaanand), we need to handle other nested data structure cases as well. That can be taken up as a separate PR so that the critical issue's fix can go ahead.

File: app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java (hunk 1 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java:363]: Yes, we do. I was planning on fixing that in a separate issue since this one is a blocker for docs right now @trishaanand

Comment (sharat87) [reply app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java:363]: Yes, a recursive solution is needed here. But we intend to take it up as a separate PR. This PR only aims to fix the critical issue (which, technically, should've wait for anything else). Does that sound okay?

**Review by sharat87 — APPROVED** [review]
