### PR TITLE
Multiselect Widget

### LINKED ISSUE #772: [BUG] All the selected values from the dropdown are not visible in the box
Attachment : https://drive.google.com/drive/folders/1SIlVTswfLx8QgeF8fNvX5uc2O5Kwlx2u?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. In the dropdown widget, Select 'Multi Select'
2. Have 7-8 values 
3. Now, from the dropdown, select all the values

Expected Result: User should be able to see all the selected values.
Actual Result: User is able to see Only 2-3 values.

### LINKED ISSUE #2733: [Bug] Dropdown widget's default is applied even if it's invalid
## Description

The vanilla dropdown widget has a few options, of which, one have the value `VEG`. Additionally, there's a default value field which is prefilled with `VEG`. Now if we change the options array to something else, something that does NOT contain the `VEG` option, that would mean the value in the default is no longer valid. Yet, when nothing is selected in the dropdown widget, `Dropdown1.selectedOptionValue` evaluates to `VEG`, which is very confusing.

When the value provided for default value is not among the options array, can we have the `.selectedOptionValue` evaluate to something falsy (like `null` or `""`)? This is useful because oftentimes, a button's disabled state is being toggled by the existence of a valid value in the `.selectedOptionValue`.

### Steps to reproduce the behaviour:

1. Add a dropdown widget to the canvas.
2. Drag a text widget to the canvas and set it's text to `{{Dropdown1.selectedOptionValue}}`.
3. Now change the `VEG` option value in the dropdown's properties' `Options` field to something else like `VEG1`.
4. The text widget still shows `VEG` although the dropdown widget's UI indicates that nothing has been selected.

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

### LINKED ISSUE #4230: [Bug] On Reseting the multi-select dropdown of a form widget the default value does not get selected
Steps to reproduce:
1) Drag a dropdown
2) Make it multi select
3) Select a default value 
4) Select 3 values
5) Reset the form
6) The dropdown get reset
and observe

Observation:
after reset the default value is not displayed to user  

Expectation:
Default value must be displayed to user 

https://user-images.githubusercontent.com/71753653/116655457-c2a31680-a9a8-11eb-8c59-b071c7deb36f.mov

### LINKED ISSUE #4629: [Bug] The disabled dropdown should show not-allowed cursor on hover of the widget
The dropdown in the disabled state should use `cursor: not-allowed`. Currently, a user can't tell if the the dropdown is disabled or not.

### LINKED ISSUE #4968: [Feature] Select should have a configurable placeholder
## Summary

As a user, when I want to use the `select` widget without a label, It's helpful to have a placeholder when no default value is present. This will inform end-user about the purpose of the fields

## Additional Context

Screenshot 2021-06-07 at 9 08 33 PM
Screenshot 2021-06-07 at 9 08 46 PM
Screenshot 2021-06-07 at 9 08 51 PM

### LINKED ISSUE #5022: [Bug] Default option becomes inactive when the user moves from single select to multi-select and vice versa
Steps to reproduce:
1) Add a select widget
2) Select "Selection Type" as a Single 
3) Add a "Default option"
4) now observe the widget the default option is displayed 
5) Click to open the property pane 
6) Select "Selection Type" as a Multiple 
and observe 

Observation :
we observe that the default option must be redefined and does not pull data that is already defined 

Expectation:
It is expected that the already defined data must be displayed to a user.

### LINKED ISSUE #5063: Migrations for the old widget

### LINKED ISSUE #5069: [Feature] Create multiselect widget

### LINKED ISSUE #5182: [Feature] Select all option in multi select
## Summary

A user wants a select all option in a multi select widget

### LINKED ISSUE #6007: [Bug] Select widget - disable functionality dosent work
## Description

The disable functionality in the select widget seems to be broken. On changing the toggle or adding a JS binding no change is observed

### Steps to reproduce the behaviour:

1. Drag & drop a select widget
2. Toggle disable prop
3. Observe that the widget does not disable

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Browser [chrome, safari]
- Environment [production,]

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

> This PR is a migration from the Old Select Widget which includes a Single select and MultiSelect to a Standalone MultiSelect Widget.
> Also, the Previous Select Widget is not mainly a single select Widget

Fixes #5069 
Fixes #5063
Fixes #2733 
Fixes #5022
Fixes #4968
Fixes #4629 
Fixes #772
Fixes #5182 
Fixes #4230 
Fixes #6007

## Type of change

- New feature
- Breaking change 
- This change requires a documentation update

## How Has This Been Tested?

> Migration Test
> Deploy Preview Test on Old Applications

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: feat/Multiselect-component 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.64 **(0.14)** | 33.66 **(0.15)** | 29.44 **(0.14)** | 52.29 **(0.16)**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.styled.tsx** | **92.31** | **100** | **0** | **100**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx** | **14.63** | **0** | **0** | **15.79**
 :green_circle: | app/client/src/components/designSystems/blueprint/DropdownComponent.tsx | 45.83 **(13.73)** | 26.67 **(4.03)** | 5.56 **(2.33)** | 45.65 **(13.6)**
 :green_circle: | app/client/src/components/designSystems/blueprint/ModalComponent.tsx | 33.33 **(2.3)** | 15.38 **(0)** | 0 **(0)** | 34.48 **(2.34)**
 :red_circle: | app/client/src/icons/WidgetIcons.tsx | 63.79 **(-0.5)** | 100 **(0)** | 25 **(-0.93)** | 63.79 **(-0.5)**
 :green_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 66.43 **(2.73)** | 58.8 **(1.51)** | 57.95 **(4.46)** | 65.74 **(2.81)**
 :red_circle: | app/client/src/utils/WidgetRegistry.tsx | 74.51 **(-0.24)** | 100 **(0)** | 23.53 **(-0.71)** | 74.51 **(-0.24)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.83 **(0.24)** | 40.25 **(0.84)** | 36.21 **(0)** | 55.04 **(0.27)**
 :green_circle: | app/client/src/utils/migrations/TableWidget.ts | 70.45 **(4.54)** | 61.67 **(6.67)** | 81.25 **(12.5)** | 73.95 **(5.04)**
 :green_circle: | app/client/src/widgets/DropdownWidget.tsx | 55.81 **(23.76)** | 0 **(0)** | 55.56 **(22.23)** | 60.53 **(27.65)**
 :sparkles: :new: | **app/client/src/widgets/MultiSelectWidget.tsx** | **55.56** | **0** | **50** | **57.14**
 :red_circle: | app/client/src/workers/validations.ts | 79.23 **(-3.49)** | 69.95 **(-0.79)** | 80 **(-3.33)** | 81.68 **(-2.12)**</details>

### CODE REVIEW

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+          </>
+        )}
+        dropdownStyle={{
+          zIndex: layer.portals,
+        }}
+        getPopupContainer={() =>
+          document.getElementsByClassName("appsmith_widget_0")[0] as HTMLElement
+        }
+        inputIcon={
+          <svg
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx:127]: Let's make this a separate component and use it here.

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+              />
+            ) : null}
+            {menu}
+          </>
+        )}
+        dropdownStyle={{
+          zIndex: layer.portals,
+        }}
+        getPopupContainer={() =>
+          document.getElementsByClassName("appsmith_widget_0")[0] as HTMLElement
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx:124]: Let's declare this function outside the component and use it here, so that it is not created on every component update.

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx [hunk 3]
```diff
@@ -0,0 +1,156 @@
...
+                  paddingBottom: "10px",
+                  marginLeft: "16px",
+                }}
+              />
+            ) : null}
+            {menu}
+          </>
+        )}
+        dropdownStyle={{
+          zIndex: layer.portals,
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx:121]: Let's make this a constant outside the component and use it as a static value, so that this object is not created on every update.

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+      <DropdownStyles />
+      <Select
+        animation="slide-up"
+        autoFocus
+        choiceTransitionName="rc-select-selection__choice-zoom"
+        className="rc-select"
+        disabled={disabled}
+        dropdownClassName="multi-select-dropdown"
+        dropdownRender={(menu) => (
+          <>
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx:104]: Let's useCallback for this function.

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+            {options.length ? (
+              <StyledCheckbox
+                alignIndicator="left"
+                checked={isSelectAll}
+                label="Select all"
+                onChange={handleSelectAll}
+                style={{
+                  paddingBottom: "10px",
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx:112]: Let's make this a constant outside the component so that it isn't recreated on every render.

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+    }
+    .${Classes.CONTROL} input:checked ~ .${Classes.CONTROL_INDICATOR} {
+      background: ${(props) => props.theme.colors.primaryOld};
+      color: ${(props) => props.theme.colors.textOnDarkBG};
+      border-color: ${(props) => props.theme.colors.primaryOld};
+    }
+  }
+`;
+
+const MultiSelectContainer = styled.div``;
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx/index.tsx:38]: Let's use this wrapper for the `index.css` styles.

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx [hunk 7]
```diff
@@ -62,6 +62,7 @@ export enum EventType {
   ON_CHECK_CHANGE = "ON_CHECK_CHANGE",
   ON_SWITCH_CHANGE = "ON_SWITCH_CHANGE",
   ON_SELECT = "ON_SELECT",
+  ON_MULTI_SELECT = "ON_MULTI_SELECT",
```
[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx:65]: I'll remove it in the meantime.
Once we have a request for this, I'd work on it.

**Comment by vivekverma2312** [comment]
@Tooluloope Please find some observations related to select and multiselect widgets. Testing is still in progress.
Observation:
1. "Either" should not be available in select widget now
Screenshot 2021-06-23 at 3 46 19 PM

2. No error when same label is repeated
Screenshot 2021-06-23 at 3 50 28 PM

3. Default data style in option is different for single and multi select. In case of select widget it is in form of array but for multi-select it like like radioButton widget
Screenshot 2021-06-23 at 3 52 58 PM
Screenshot 2021-06-23 at 3 52 46 PM

4. Hovering of mouse on multi-select dropdown do not change the cursor properly. Can we make this similar to prod.
https://www.loom.com/share/6a43b066cdf640238aaac6e6dde7147e

5. Search is allowed but not functional in case of multi-select.
https://www.loom.com/share/ec8b89ddc8054b559c6896b1b0e33534

6. When we remove default value and placeHolder from multi-select widget then it is showing as blank
Screenshot 2021-06-23 at 3 59 22 PM

**Comment by somangshu** [comment]
@vivekverma2312 please check all the linked issues, replicated/fixed for the multi-select, What you dont see in the single select should be created as a new issue and added to the `Dropdown widget` epic

**Comment by Tooluloope** [comment]
@somangshu @vivekverma2312 Should we allow the same Label.
The main issue is allowing the same value which would cause an evaluation error

**Comment by Tooluloope** [comment]
@vivekverma2312 All issues outlined have been resolved.
Do let me know if there are other issues. 

Thanks for spotting them.👍

**Comment by Tooluloope** [comment]
@vivekverma2312 Could you explain No.6

Didn't understand the issue.

**Comment by vivekverma2312** [comment]
> @vivekverma2312 Could you explain No.6
> 
> Didn't understand the issue.

Issue 6: In case of multi-select if we remove both default value and place holder then only drop-down icon is coming. In case of select widget if we remove default value then select along with drop-down icon is displayed.

**Comment by vivekverma2312** [comment]
@Tooluloope Few more observations:
7. Place holder is not coming in option field after user clear the default data
Screenshot 2021-06-24 at 11 34 53 AM


8. Default data is not showing in options for existing widgets

Screenshot 2021-06-24 at 12 11 57 PM

9. Select all is not coming in some cases
Screenshot 2021-06-24 at 12 11 57 PM

**Comment by Tooluloope** [comment]
@vivekverma2312, All issues have been fixed, except No 7. The JS Convertible Editor doesn't use Placeholders

**Comment by vivekverma2312** [comment]
@Tooluloope New observations:
10. Default Input place holder for multi select  should be changed from `Favorite Hokage` to may be `--Select-- `
Screenshot 2021-06-28 at 1 54 28 PM

11. #995 Is working fine for multi-select but it is not handled for select widget

**Comment by Tooluloope** [comment]
> @Tooluloope New observations:
> 
> 10. Default Input place holder for multi select  should be changed from `Favorite Hokage` to may be `--Select-- `
> 
> Screenshot 2021-06-28 at 1 54 28 PM
> 
> 
> 
> 11. #995 Is working fine for multi-select but it is not handled for select widget
> 
> 
> 
> 

@vivekverma2312 So, The Default Place holder is ```Select a Value```.
Favourite Hokage was a custom Placeholder.

For 11, A different PR is meant to be used to fix it.

**Comment by vivekverma2312** [comment]
@Tooluloope For issue 10
Please make the property name as `Placeholder`
and the default should be `select option(s)`

**Review by somangshu — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@Tooluloope  we have found few more issues 

12.Click on +Option throws error 'The value at the option is invalid' for both select and multi-select widget 

https://loom.com/share/e5f3fd1eeb554be88758c80631f3854c

13. Multi-select - The default value 'Forth' should be replaced with 'Fourth' and 'Six' to be 'Sixth'

Screenshot 2021-06-29 at 12 33 12 PM

14. Multi-select -When the user tries to add new label and value to the options fields the mouse insertion pointer points to placeholder field instead of options field and whatever user types the values are directly typed into placeholder filed. (This is also applicable for the Default value field)

https://www.loom.com/share/2964b249b87c486c8d777ccc0034d23d

**Comment by Tooluloope** [comment]
> 1. Fourth

All fixed, for No. 12, the Control type needs both input field filled, i.e. the Label and Value cannot be empty

**Comment by YogeshJayaseelan** [comment]
@Tooluloope - verified issue 13 and 14 they are working as expected now

**Comment by Tooluloope** [comment]
> @Tooluloope - verified issue 13 and 14 they are working as expected now

@YogeshJayaseelan do let me know if you require further clarification for No.12

File: app/client/src/utils/autocomplete/EntityDefinitions.ts [hunk 8]
```diff
@@ -112,6 +112,24 @@ export const entityDefinitions = {
...
   },
+  MULTI_SELECT_WIDGET: {
+    "!doc":
+      "MultiSelect is used to capture user input/s from a specified list of permitted inputs. A MultiSelect captures multiple choices from a list of options",
+    "!url": "https://docs.appsmith.com/widget-reference/dropdown",
+    isVisible: isVisible,
+    selectedOptionValues: {
+      "!type": "[string]",
+      "!doc": "The array of values selected in a multi select dropdown",
+      "!url": "https://docs.appsmith.com/widget-reference/dropdown",
```
[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/utils/autocomplete/EntityDefinitions.ts:123]: @somangshu, Do we need to separate the widgets also in the Docs  
https://docs.appsmith.com/widget-reference/dropdown

**Comment by vivekverma2312** [comment]
@Tooluloope #2733 was working before but now that is not working. Every-time we make any change in the value the option selected gets reset. Same behaviour for both select and multi-select.

**Comment by Tooluloope** [comment]
> @Tooluloope #2733 was working before but now that is not working. Every-time we make any change in the value the option selected gets reset. Same behaviour for both select and multi-select.

Could you make a loom video for me to understand the issue better

**Comment by vivekverma2312** [comment]
@Tooluloope Loom video for #2733 ->  https://www.loom.com/share/2283be0339e04744af8cf33e6ecf8d0e

I also checked that #4629 is working fine for multi-select but not for select widget
https://www.loom.com/share/f762dc7736554f48806f9ddae8535f5a

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx [hunk 9]
```diff
@@ -0,0 +1,532 @@
+import React, { useEffect, useState, useCallback } from "react";
+import Select, { SelectProps } from "rc-select";
+import { Checkbox, Classes } from "@blueprintjs/core";
+import styled, { keyframes } from "styled-components";
+import { Colors } from "constants/Colors";
+import { createGlobalStyle } from "constants/DefaultTheme";
+import { DefaultValueType } from "rc-select/lib/interface/generator";
+import { useRef } from "react";
+
+const inputIcon = (): JSX.Element => (
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx:10]: Let us organize this file. We can create a folder called `MultiSelectComponent` and move the styles to a file `MultiSelectStyles`, `InputIcon`, etc. It will make this file cleaner.

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx [hunk 10]
```diff
@@ -0,0 +1,532 @@
...
+  onChange,
+  options,
+  placeholder,
+  value,
+}: MultiSelectProps): JSX.Element {
+  const [isSelectAll, setIsSelectAll] = useState(false);
+  const _menu = useRef<HTMLElement | null>(null);
+
+  const getDropdownPosition = useCallback((node: HTMLElement | null) => {
+    if (Boolean(node?.closest(".bp3-modal-widget"))) {
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent.tsx:447]: Is this a blueprint class? If so, let us use `Classes` from `@blueprint/core` instead of `.bp3-modal-widget`

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 11]
```diff
@@ -785,12 +785,38 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
...
+    currentDSL.version = 26;
+  }
+
+  if (currentDSL.version === 26) {
+    currentDSL = migrateToNewMultiSelect(currentDSL);
+    currentDSL.version = LATEST_PAGE_VERSION;
+  }
+  if (currentDSL.version === LATEST_PAGE_VERSION) {
+    currentDSL = migrateToNewMultiSelect(currentDSL);
     currentDSL.version = LATEST_PAGE_VERSION;
```
Comment (riodeuno) [inline app/client/src/utils/WidgetPropsUtils.tsx:797]: Here we are not updating the DSL version, which will result in this migration running everytime the page loads.

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Comment by Tooluloope** [comment]
> @Tooluloope Loom video for #2733 ->
> 
> https://www.loom.com/share/2283be0339e04744af8cf33e6ecf8d0e
> 
> I also checked that #4629 is working fine for multi-select but not for select widget
> 
> https://www.loom.com/share/f762dc7736554f48806f9ddae8535f5a

@vivekverma2312 , Could you confirm the issues now?

File: app/client/src/components/designSystems/blueprint/DropdownComponent.tsx [hunk 12]
```diff
@@ -145,6 +145,7 @@ const DropdownContainer = styled.div`
 
 class DropDownComponent extends React.Component<DropDownComponentProps> {
   render() {
+    console.log(Classes.DIALOG, "NOOOOOOOODAL");
```
Comment (riodeuno) [inline app/client/src/components/designSystems/blueprint/DropdownComponent.tsx:148]: Missed cosole.log

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Comment by vivekverma2312** [comment]
@Tooluloope Issue #2733 and #4629 is fixed.

Able to see migration issue again: For old apps the noting is coming below Option property for both select and multiselect widget.
Screenshot 2021-07-01 at 3 39 55 PM

**Comment by Tooluloope** [comment]
> @Tooluloope Issue #2733 and #4629 is fixed.
> 
> 
> 
> Able to see migration issue again: For old apps the noting is coming below Option property for both select and multiselect widget.
> 
> Screenshot 2021-07-01 at 3 39 55 PM
> 
> 

Sorry didn't get that clearly

**Review by riodeuno — DISMISSED** [review]

**Review by somangshu — APPROVED** [review]
Running tests

**Review by somangshu — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Comment by vivekverma2312** [comment]
@Tooluloope Can you please remove the JS beside options property for both select and multi-select widget.

Screenshot 2021-07-12 at 5 47 46 PM
Screenshot 2021-07-12 at 5 42 20 PM

**Comment by Tooluloope** [comment]
> @Tooluloope Can you please remove the JS beside options property for both select and multi-select widget.
> 
> Screenshot 2021-07-12 at 5 47 46 PM
> 
> Screenshot 2021-07-12 at 5 42 20 PM

@vivekverma2312 Fixed

**Comment by vivekverma2312** [comment]
@Tooluloope Above issues are fixed. Please remove #4416 as this is not going in this PR.

**Comment by Tooluloope** [comment]
> @Tooluloope Above issues are fixed. Please remove #4416 as this is not going in this PR.

For some reasons, I can't, Its greyed out when I try to remove it

**Comment by mohanarpit** [comment]
> > @Tooluloope Above issues are fixed. Please remove #4416 as this is not going in this PR.
> 
> For some reasons, I can't, Its greyed out when I try to remove it

I've removed #4416 from this PR.

File: app/client/src/reducers/entityReducers/widgetConfigReducer.tsx [hunk 13]
```diff
@@ -30,6 +30,8 @@ import { SkeletonWidgetProps } from "../../widgets/SkeletonWidget";
 import { SwitchWidgetProps } from "widgets/SwitchWidget";
 import { ListWidgetProps } from "../../widgets/ListWidget/ListWidget";
 import { MultiSelectWidgetProps } from "widgets/MultiSelectWidget";
+import { DividerWidgetProps } from "../../widgets/DividerWidget";
```
Comment (riodeuno) [inline app/client/src/reducers/entityReducers/widgetConfigReducer.tsx:33]: We could import from absolute paths `widgets/DividerWidget`

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Dropdown_spec.js [hunk 14]
```diff
@@ -27,45 +26,12 @@ describe("Dropdown Widget Functionality", function() {
       .should("have.text", "Option 3");
   });
   it("Selects value with enter in default value", () => {
-    // cy.openPropertyPane("dropdownwidget");
     cy.testJsontext("defaultoption", "3\n");
     cy.get(formWidgetsPage.dropdownWidget)
       .find(widgetLocators.defaultSingleSelectValue)
       .should("have.text", "Option 3");
   });
-  it("Dropdown Widget Functionality", function() {
```
Comment (riodeuno) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Dropdown_spec.js:36]: @Tooluloope  There are multiple tests removed. I was wondering if they were added in another file?

File: app/client/src/widgets/DropdownWidget.tsx [hunk 15]
```diff
@@ -22,11 +22,11 @@ class DropdownWidget extends BaseWidget<DropdownWidgetProps, WidgetState> {
               "Allows users to select a single option. Values must be unique",
             propertyName: "options",
             label: "Options",
-            controlType: "OPTION_INPUT",
+            controlType: "INPUT_TEXT",
             placeholderText: 'Enter [{"label": "label1", "value": "value2"}]',
             isBindProperty: true,
             isTriggerProperty: false,
-            isJSConvertible: true,
+            isJSConvertible: false,
```
Comment (riodeuno) [inline app/client/src/widgets/DropdownWidget.tsx:29]: We could just remove it, if it isn't needed. But, this works as well.

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@Tooluloope I've added a couple of nit-picky comments. Please feel free to respond to them, or deal with them either in this PR or another PR.

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx [hunk 16]
```diff
@@ -0,0 +1,131 @@
...
+import Select, { SelectProps } from "rc-select";
+import { DefaultValueType } from "rc-select/lib/interface/generator";
+import {
+  DropdownStyles,
+  inputIcon,
+  MultiSelectContainer,
+  StyledCheckbox,
+} from "./index.styled";
+import {
+  CANVAS_CLASSNAME,
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx:11]: If we need the class name for a widget, we can use `generateClassName` from `src/utils/generators`

Comment (riodeuno) [reply app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx:11]: Using it this way, will break things if we decided to change the way `generateClassName` prefixes the widgetIds.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Dropdown_spec.js (hunk 14 above)
Comment (Tooluloope) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Dropdown_spec.js:36]: They were for the Dropdown widget.
The test just included switching selection types from single select to Multiselect which we are no longer doing, since they are now separate

File: app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx (hunk 16 above)
Comment (Tooluloope) [reply app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.tsx:11]: Would resolve this in the serverSide PR

**Review by riodeuno — DISMISSED** [review]

**Comment by Tooluloope** [comment]
Screenshot 2021-07-14 at 12 36 03
Screenshot 2021-07-14 at 12 45 29


Tests are passing on local

**Review by somangshu — APPROVED** [review]
Approving to run failing tests.

@YogeshJayaseelan please check the widget icon and give the final sign off to close this

**Comment by somangshu** [comment]
@Tooluloope related tests failing again, Please test locally as well

**Comment by Tooluloope** [comment]
> @Tooluloope related tests failing again, Please test locally as well

@somangshu both tests are passing
Screenshot 2021-07-16 at 10 45 28
Screenshot 2021-07-16 at 10 53 38

**Review by riodeuno — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

File: app/client/src/constants/Colors.tsx [hunk 17]
```diff
@@ -81,6 +81,6 @@ export const Colors: Record<string, string> = {
   OPAQ_BLUE: "rgba(106, 134, 206, 0.1)",
   RATE_ACTIVE: "#FFCB45",
   RATE_INACTIVE: "#F2F2F2",
+  SELECT_DISABLED: "#ced9e080",
```
Comment (somangshu) [inline app/client/src/constants/Colors.tsx:84]: Why are we not using the generic disable colour used everywhere else. Do we really need a new variable?

**Review by trishaanand — APPROVED** [review]

**Comment by trishaanand** [comment]
Approved for the tests to run. Not a real code review :)

File: app/client/src/constants/Colors.tsx (hunk 17 above)
Comment (Tooluloope) [reply app/client/src/constants/Colors.tsx:84]: It was overwritten when customizing the Select Component.

**Comment by somangshu** [comment]
@vivekverma2312 is there an update here, Have we tested all scenarios. 

@riodeuno can you provide a final review. We should be able to push this into the next release.

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 18]
```diff
@@ -791,16 +791,24 @@ const transformDSL = (currentDSL: ContainerWidgetProps<WidgetProps>) => {
...
+
   if (currentDSL.version === 27) {
     currentDSL = migrateFilterValueForDropDownWidget(currentDSL);
-    currentDSL.version = 27;
+    currentDSL.version = 28;
   }
 
   if (currentDSL.version === 27) {
+    currentDSL = migrateTablePrimaryColumnsComputedValue(currentDSL);
+    currentDSL.version = 28;
```
Comment (riodeuno) [inline app/client/src/utils/WidgetPropsUtils.tsx:804]: The version set above is 28. This migration will never run.

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/src/utils/WidgetPropsUtils.tsx (hunk 18 above)
Comment (Tooluloope) [reply app/client/src/utils/WidgetPropsUtils.tsx]: Fixed

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — DISMISSED** [review]

**Comment by somangshu** [comment]
@Tooluloope if this is complete please merge it ASAP to release

**Comment by Tooluloope** [comment]
> @Tooluloope if this is complete please merge it ASAP to release

Just merged @riodeuno Widget Validation Changes to this PR.
Quite a lot of conflicts 🥲🥲🥲

**Review by somangshu — APPROVED** [review]
Approving to run tests here. 

@riodeuno @vivekverma2312 @Tooluloope do we need another round of sanity testing here?

**Comment by vivekverma2312** [comment]
@Tooluloope Observed this issue around select and multi-select widget
Now we can have duplicate data
https://www.loom.com/share/93d52abd1df0424cb2ae083cc1d48a16

Multi-select-> 
https://www.loom.com/share/d3544cb50c2643c3927d865fb0adc9fe

**Comment by Tooluloope** [comment]
> @Tooluloope Observed this issue around select and multi-select widget
> Now we can have duplicate data
> 
> https://www.loom.com/share/93d52abd1df0424cb2ae083cc1d48a16
> 
> Multi-select->
> 
> https://www.loom.com/share/d3544cb50c2643c3927d865fb0adc9fe

I think it's related to the Widget Validation

**Review by somangshu — DISMISSED** [review]
Running tests again.

@vivekverma2312 please confirm with @riodeuno and create new issues as required.

**Review by riodeuno — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@Tooluloope @riodeuno Duplicate label issue is fixed but there is some issue on search. After every search the drop-down options are getting repeated. It is happening for both select and multi-select.
https://www.loom.com/share/9c7b30137d49455cbadd35e56b615826

**Comment by Tooluloope** [comment]
> @Tooluloope @riodeuno Duplicate label issue is fixed but there is some issue on search. After every search the drop-down options are getting repeated. It is happening for both select and multi-select.
> 
> https://www.loom.com/share/9c7b30137d49455cbadd35e56b615826

@riodeuno I think having both label and value unique is meant to be the ideal behavior?

**Comment by riodeuno** [comment]
@Tooluloope The uniqueness check is for the `JSON.stringify({"label": "something", "value": "something"})` 
So, one pair of label and value should be unique. We can have the same label in two different entries. Is this the issue?

**Comment by Tooluloope** [comment]
> @Tooluloope The uniqueness check is for the `JSON.stringify({"label": "something", "value": "something"})`
> So, one pair of label and value should be unique. We can have the same label in two different entries. Is this the issue?

Yeah, that's the issue
I think that's why this issue was closed https://github.com/appsmithorg/appsmith/issues/4966

**Review by riodeuno — DISMISSED** [review]

**Review by riodeuno — APPROVED** [review]

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
Re Ran all jobs > `Smoke_TestSuite/ClientSideTests/GenerateCRUD/GenerateCRUDPage_Spec.js` failed

**Comment by somangshu** [comment]
Force merging this into release, the above test is failing consistently.
