### PR TITLE
fix: Fixes Mongo connection pool minimum size to 0

### LINKED ISSUE #4142: Add retry limits for Mongo connection in the Mongo plugin

### PR DESCRIPTION
**Pull request by nidhi-nair**
The mongo plugin retries creating connections passively in the pool all the time right now because the pool is initialized with a setting to always have at least one connection open. This fix forces all datasources to allow 0 connections as well. This will allow incorrect datasource configurations to not keep attempting the connection. 

Also contains refactoring since the logic for URIs was crowding the `MongoPluginExecutor` class.

Do we also need to be checking for the duration of time that each connection is held on to even when idle?

Fixes #4142

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Unit tests for parameter additions
- Manually tested for connection recreation attempts

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 1]
```diff
@@ -140,7 +145,7 @@ public class MongoPlugin extends BasePlugin {
      *   - mongodb://user:pass@some-url:port,some-url:port,.../some-db...
      * - It has been grouped like this: (mongodb+srv://)(user):(pass)@(some-url)/(some-db...)?(params...)
      */
-    private static final String MONGO_URI_REGEX = "^(mongodb(?:\\+srv)?:\\/\\/)(?:(.+):(.+)@)?([^\\/\\?]+)\\/?([^\\?]+)?\\??(.+)?$";
+    private static final String MONGO_URI_REGEX = "^(mongodb(?:\\+srv)?://)(?:(.+):(.+)@)?([^/?]+)/?([^?]+)?\\??(.+)?$";
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:148]: Just asking for confirmation - have we checked if it is ok to remove the back slashes.

**Review by sumitsum — APPROVED** [review]

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 1 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:148]: Yes, the forward slash character does not need to be escaped at all, I've tested this with mongo uri string inputs as well. :)
