### PR TITLE
fix: ds initial values logic on app import

### LINKED ISSUE #29409: [Bug]: Import modal AI datasource throws internal server error on Test configuration
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on Test configuration while importing AI ds, I get an internal server error. This works fine when I connect from data flow inside the application 

### Steps To Reproduce

Screenshot 2023-12-07 at 9 57 15 AM

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ayushpahwa**
## Description
Today when we import any app, the initial values for our unconfigured datasources are dependant on the exported file from server which doesn't include all of the formconfig. This PR solves that issue and updates the server definition of the datasource with the new initial values. Also added a check to not make an API call if the initial value is correct.

#### PR fixes following issue(s)
Fixes #29409 

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
	- Enhanced comparison logic in the initialization of data sources to improve performance.
	- Updated form control utilities to allow excluding encrypted fields from initial configurations.

### CODE REVIEW

File: app/client/src/components/formControls/utils.ts [hunk 1]
```diff
@@ -352,6 +352,7 @@ export const switchViewType = (
 export const getConfigInitialValues = (
   config: Record<string, any>[],
   multipleViewTypesSupported = false,
+  includeEncryptedFields = true,
```
Comment (sneha122) [inline app/client/src/components/formControls/utils.ts:355]: @ayushpahwa Why do we need this param includeEncryptedFields?

File: app/client/src/components/formControls/utils.ts [hunk 2]
```diff
@@ -370,6 +371,12 @@ export const getConfigInitialValues = (
           },
         );
       } else {
+        if (
+          !includeEncryptedFields &&
+          (section.encrypted || section.dataType === "PASSWORD")
```
Comment (sneha122) [inline app/client/src/components/formControls/utils.ts:376]: Can we please avoid this magic string and define an enum instead?

**Comment by laveena-en** [comment]
@ayushpahwa On adding the credentials on the import modal, the authentication details aren't being shown within the app https://www.loom.com/share/6928f74c89db40bda899a40a415629df?sid=a40f4ce4-7599-4204-b1ea-5d12be04f1db

File: app/client/src/components/formControls/utils.ts (hunk 1 above)
Comment (ayushpahwa) [reply app/client/src/components/formControls/utils.ts:355]: This is done to avoid multiple update calls while getting initial values in the import modal. Server doesn't send values for password fields and hence the diff in application sagas was coming to be different. To avoid that, I have added this check. Updated in comments of the code also.

File: app/client/src/ce/sagas/ApplicationSagas.tsx [hunk 3]
```diff
@@ -963,20 +957,29 @@ export function* initializeDatasourceWithDefaultValues(datasource: Datasource) {
     const initialValues: unknown = yield call(
       getConfigInitialValues,
       formConfig,
+      false,
+      false,
```
[the remark this answers is not in the document]
Comment (ayushpahwa) [reply app/client/src/ce/sagas/ApplicationSagas.tsx:961]: Doesn't make sense to include limited scope variables here. The function definition will be sufficient

File: app/client/src/components/formControls/utils.ts (hunk 2 above)
Comment (ayushpahwa) [reply app/client/src/components/formControls/utils.ts:376]: Done

**Review by sneha122 — APPROVED** [review]
