### PR TITLE
fix: Tabs widget - full height when showTabs is false

### LINKED ISSUE #4747: [Bug] Additional grey spacing is displayed to user on making "Show Tabs" false
Steps to reproduce:
1) Add a tab widget
2) Open property pane
3) Scroll to "Show Tabs" option
4) Toggle to false
and observe 

Observation:
Ther is spacing around the tab 

Expectation:
The tab should cover the entire outer border of the widget

Video:
[LOOM DEMO](https://www.loom.com/share/ab60d5a82d0e4da0ab170daf6ee4156e)

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

Fixes #4747 

Screenshot 2021-08-30 at 10 37 51 AM

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/4747-tabs-widget-height 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55 **(0.01)** | 36.88 **(0)** | 33.87 **(0.01)** | 55.55 **(0.01)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TabsComponent.tsx | 100 **(0)** | 83.33 **(-1.96)** | 100 **(0)** | 100 **(0)**</details>

### CODE REVIEW

File: app/client/src/components/designSystems/appsmith/TabsComponent.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ const TabsContainerWrapper = styled.div<{
 `;
 
 const ChildrenWrapper = styled.div`
-  height: calc(100% - 40px);
```
Comment (jsartisan) [inline app/client/src/components/designSystems/appsmith/TabsComponent.tsx:45]: Do we know why we subtracted this 40px before?

**Review by jsartisan — APPROVED** [review]

File: app/client/src/components/designSystems/appsmith/TabsComponent.tsx (hunk 1 above)
Comment (ashit-rath) [reply app/client/src/components/designSystems/appsmith/TabsComponent.tsx:45]: Maybe to consider for the tab height as it's 40px, not 100% sure.

**Comment by vivekverma2312** [comment]
@ashit-rath It looks that placing any other widget on the tab widget changes position due to grid change. If I place any widget at bottom of tab then it's getting cropped.
https://www.loom.com/share/9fbc0b03f8494944b21ef4843d73c96e

**Comment by ashit-rath** [comment]
@vivekverma2312 Regarding the chart widget issue you mentioned, I think that is out of the scope of this issue as this is regarding the grey bar that we see. Can you maybe create a new issue stating that?

**Review by jsartisan — APPROVED** [review]

**Comment by somangshu** [comment]
@ashit-rath @jsartisan kindly dont push small issue like this to QA pipeline, As stated before, The reviewer can test the Deploy preview while looking at the code and then push to the done pipeline
