### PR TITLE
fix: Cannot read properties of undefined (reading 'matches')

### LINKED ISSUE #23880: TypeError: Cannot read properties of undefined (reading 'matches')
Sentry Issue: [APPSMITH-6DZ](https://appsmith.sentry.io/issues/4190897475/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'matches')
  at getNextTabbableDescendant (utils/hooks/useWidgetFocus/tabbable.ts:119:30)
  at handleTab (utils/hooks/useWidgetFocus/handleTab.ts:34:32)
  at handleKeyDown (utils/hooks/useWidgetFocus/useWidgetFocus.tsx:24:32)
```

### PR DESCRIPTION
**Pull request by jsartisan**
The tabbing logic was failing where there was no widget on canvas except modal widget.
Added a null check to fix it.

Fixes #23880

### CODE REVIEW

File: app/client/src/utils/hooks/useWidgetFocus/tabbable.ts [hunk 1]
```diff
@@ -115,6 +115,8 @@ export function getNextTabbableDescendant(
 ) {
   const nextTabbableDescendant = descendants[0];
 
+  if (!nextTabbableDescendant) return;
```
Comment (keyurparalkar) [inline app/client/src/utils/hooks/useWidgetFocus/tabbable.ts:118]: @jsartisan can you add a unit test for this function? so that it covers the issue that this PR solves

Comment (jsartisan) [reply app/client/src/utils/hooks/useWidgetFocus/tabbable.ts:118]: Added the test.

**Review by keyurparalkar — APPROVED** [review]
LGTM!
