### PR TITLE
fix: Widget name disappear as you hover over it

### LINKED ISSUE #32710: [Bug]: In split screen, selecting the widget name is hard because it looses focus
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While in Split screen mode, trying to select a Widget by hovering over the name is really hard because the name keeps on disappearing.

### Steps To Reproduce

1. Have widgets on screen
2. Navigate to query in split screen mode
3. Hover over the widget like Table Widget
4. If you go a bit slow to reach the name with the mouse, it will disappear before you reach it.

https://github.com/appsmithorg/appsmith/assets/12022471/a90b9fd3-791d-4def-86dd-4c1d259222aa

### Public Sample App

_No response_

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Moves the Focus widget action into its own hook, and calling it from the PositionContainer instead from the DraggableContainer. PositionContainer is the parent of Draggable and hence adds a larger target for the mouse focus of a widget.

Fixes #32710

## Automation

/ok-to-test tags="@tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8705394457>
> Commit: bc58f19c7247544117866d89f4f557372f8791ef
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8705394457&attempt=1" target="_blank">Click here!</a>

## Summary by CodeRabbit

- **New Features**
	- Enhanced widget interaction by implementing hover to focus functionality in the PositionedContainer.

- **Refactor**
	- Simplified the DraggableComponent by removing unused states and event handlers, focusing on widget selection improvements.

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]

File: app/client/src/utils/hooks/useHoverToFocusWidget.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    (state: AppState) => state.ui.widgetDragResize.isResizing,
+  );
+  // This state tells us whether a `DraggableComponent` is dragging
+  const isDragging = useSelector(
+    (state: AppState) => state.ui.widgetDragResize.isDragging,
+  );
+
+  const isResizingOrDragging = isResizing || isDragging;
+  // This state tells us whether space redistribution is in process
+  const isDistributingSpace = useSelector(getAnvilSpaceDistributionStatus);
```
Comment (marks0351) [inline app/client/src/utils/hooks/useHoverToFocusWidget.ts:30]: @hetunandu you can remove this check, this component is not used in Anvil anymore.

**Review by marks0351 — APPROVED** [review]
approving with a minor comment.
