### PR TITLE
fix: remove uploadedFileUrls property from FilePicker

### LINKED ISSUE #3802: [Task] Widget Properties cleanup
## Remove deprecated widget properties
- FilePicker - Uploaded File Url(s)

### PR DESCRIPTION
**Pull request by Tooluloope**
Fixes #3802
[Docs update](https://github.com/appsmithorg/appsmith/issues/3802)

## Type of change

- Cleanup (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/-filePicker-widget-property-cleanup 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.58 **(0.01)** | 32.5 **(0)** | 29.7 **(0)** | 52.09 **(0.01)**
 :green_circle: | app/client/src/widgets/FilepickerWidget.tsx | 37.21 **(1.65)** | 0 **(0)** | 15.38 **(0.57)** | 36.47 **(1.64)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@vihar some documentation changes are made here. Please check when you get the time.

**Review by somangshu — APPROVED** [review]
Looks good to me. Tested on deploy preview as well!

File: app/client/src/widgets/FilepickerWidget.tsx [hunk 1]
```diff
@@ -185,7 +171,7 @@ class FilePickerWidget extends BaseWidget<
         children: [
           {
             helpText:
-              "Triggers an action when the user selects a file. Upload files to a CDN here and store their urls in uploadedFileUrls",
+              "Triggers an action when the user selects a file. Upload files to a CDN here and store their urls in",
```
Comment (hetunandu) [inline app/client/src/widgets/FilepickerWidget.tsx:174]: This help text is incomplete

Comment (Tooluloope) [reply app/client/src/widgets/FilepickerWidget.tsx:174]: @hetunandu @somangshu  would this be okay `Triggers an action when the user selects a file. Upload files to a CDN and stores their URLs`

Comment (somangshu) [reply app/client/src/widgets/FilepickerWidget.tsx:174]: I see that this will be present under the `files` property now. So it should be:

`Triggers an action when the user selects a file. Upload files to a CDN and stores their URLs filepicker.files`

@hetunandu does that make sense?

Comment (hetunandu) [reply app/client/src/widgets/FilepickerWidget.tsx:174]: @somangshu Looks good

**Review by hetunandu — APPROVED** [review]
