### PR TITLE
fix: Action redesign/remove container query

### LINKED ISSUE #35901: [Bug]: Action redesign - UI issues with mongo plugin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. When we have multiple line in fields like Skip or sort, we are not able to scroll past the bottom boundary. (see video)
2. When we reduce the screen size, the code editor field is not responsive.
Screenshot 2024-08-27 at 2 13 07 PM

3. Limit dropdown overlaps with the bottom bar. (this is a regression as it works fine on prod)
Screenshot 2024-08-27 at 2 40 49 PM

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/
2. Add a mongo datasource & click on `New Query`

### Public Sample App

_No response_

### Environment

Release

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/616a34a4-7f7e-4bc7-98c4-5dfb636407d6

### Version

Cloud

### LINKED ISSUE #36000: [Task]: Update container query to grid - fix for scroll issue in UQI
Container query inside Section and Zone was causing issue for absolute positioned objects like code editor.

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

PR addresses below issues,
1. Query was not scrollable when code editor field dynamically increase height. This was caused by the container property in Section. Container will ignore absolute positioned elements dynamic heights.
2. Fixed code editor field min-width while resizing
3. Fixed ads select feild min-width while resizing.

Fixes #36000
Fixes #35901

## Automation

/ok-to-test tags="@tag.Sanity, @tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10631460963>
> Commit: 9d9fe7691113f36ecf4172972ae31a69c059a8f4
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10631460963&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Sanity, @tag.IDE`
> Spec:
> <hr>Fri, 30 Aug 2024 11:24:13 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for the dynamic text field control, improving visual consistency.
	- Introduced a flexible grid layout for better responsiveness across different screen sizes.

- **Bug Fixes**
	- Addressed layout issues with minimum width adjustments for dynamic text fields and advertisement selectors.

### CODE REVIEW

File: app/client/src/components/formControls/DynamicTextFieldControl.tsx [hunk 1]
```diff
@@ -65,7 +65,7 @@ class DynamicTextControl extends BaseControl<
 
     return (
       <Wrapper
-        className={`t--${configProperty}`}
+        className={`t--${configProperty} dynamic-text-feild-control`}
```
Comment (hetunandu) [inline app/client/src/components/formControls/DynamicTextFieldControl.tsx:68]:
```suggestion
        className={`t--${configProperty} dynamic-text-field-control`}
```

Spelling issue in "field"

**Review by hetunandu — APPROVED** [review]
