### PR TITLE
fix: MongoDB Invalid DB Name Error Msg

### LINKED ISSUE #12260: [Bug]-[280]:Any random database name tests OK for MongoDB database
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try create a MongoDB datasource with Use Mongo Connection String URI set to No by providing host address name and authentication details, even if I provide a random database name in the Authentication section and click on Test icon, the test passes with a success message.
It should give an error to the effect of Invalid Database Name. 

### Steps To Reproduce

1. Click on Add a New Datasource under Datasources
2. Select MongoDB Database
3. Set the parameters as below:
- Use Mongo Connection String URI - No
- Connection Mode - Read/Write
- Connection Type - Replica Set
- Host Address - <appropriate host address>
- Port - leave blank
- Default Database Name - leave blank
- Database Name - xyz (give any random db name)
- Authentication Type - SCRAM-SHA1
- Username.- give the appropriate user name for a valid db
- Password - give the appropriate password a valid db

Attached the link to the loom video showing the issue -
[LOOM DEMO](https://www.loom.com/share/b3d532ab8ab84e22b24bf304965b95ef)

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by PiyushPushkar02**
## Description

- This PR adds a check to throw a proper error if the default database name is empty and an invalid database name is provided in the authentication section for mongo db.
- Added JUnit test cases for the same. one for an invalid db name and one for a valid db name (Both with empty default db name)
- There is one more issue observed here which is not taken part in this ticket. When you try to save the mongo data source with the default database name and empty database name under auth section. Once you try to save the data source it will throw an internal server error. Created a ticket for the same: https://app.zenhub.com/workspaces/data-integration-pod-6322a759b3296d249ce5c4ed/issues/gh/appsmithorg/appsmith/21598

Fixes #12260 

## Type of change
- Bug Fix(non-breaking change which adds functionality)

## How Has This Been Tested?
- Manual
- JUnit TC added 

### **Checklist**:

- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [ ]  My changes generate no new warnings
- [x]  I have added tests that prove my fix is effective or that my feature works
- [x]  New and existing unit tests pass locally with my changes
- [ ]  PR is being merged under a feature flag

### **QA activity:**

- [ ]  Test plan has been approved by relevant developers
- [ ]  Test plan has been peer reviewed by QA
- [ ]  Cypress test cases have been added and approved by either SDET or manual QA
- [ ]  Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ]  Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 1]
```diff
@@ -790,7 +790,7 @@ public Set<String> validateDatasource(DatasourceConfiguration datasourceConfigur
                     }
 
                     if (!StringUtils.hasLength(authentication.getDatabaseName())) {
-                        invalids.add(MongoPluginErrorMessages.DS_MISSING_DEFAULT_DATABASE_NAME_ERROR_MSG);
+                        invalids.add(MongoPluginErrorMessages.DS_INVALID_USER_DATABASE_NAME);
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:793]: Can you please update the error name to `DS_INVALID_AUTH_DATABASE_NAME` ? as the concerned input field should ideally be named `Authentication Database`.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 2]
```diff
@@ -821,16 +821,31 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
...
+            } else databaseName = null;
+
             return datasourceCreate(datasourceConfiguration)
                     .flatMap(mongoClient -> {
                         final Publisher<String> result = mongoClient.listDatabaseNames();
                         final Mono<List<String>> documentMono = Flux.from(result).collectList().cache();
                         return documentMono.doFinally(ignored -> mongoClient.close()).then(documentMono);
                     })
                     .flatMap(names -> {
-                        if (defaultDatabaseName == null || defaultDatabaseName.isBlank()) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:831]: I think we want to keep this flow as this field is optional which means that even if the user chooses to keep it as empty it should be fine.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 3]
```diff
@@ -821,16 +821,31 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
                 defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
             } else defaultDatabaseName = null;
 
+            final String databaseName;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:824]: Should we rename it to `authDatabaseName` ? as ideally the input field is capturing authentication database name.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 4]
```diff
@@ -821,16 +821,31 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
...
+            if (datasourceConfiguration.getConnection() != null && datasourceConfiguration.getAuthentication() != null) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:825]: QQ: Why are we checking for `datasourceConfiguration.getConnection() != null` ?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 5]
```diff
@@ -821,16 +821,31 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
...
+                databaseName = ((DBAuth) datasourceConfiguration.getAuthentication()).getDatabaseName();
+            } else databaseName = null;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:827]: Shouldn't we add a check for authentication db being empty / null and throw an error ?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 3 above)
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:824]: Can we pull this and the `defaultDatabaseName` variable definition right next to their usage lines ?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 6]
```diff
@@ -821,16 +821,31 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
...
                         return documentMono.doFinally(ignored -> mongoClient.close()).then(documentMono);
                     })
                     .flatMap(names -> {
-                        if (defaultDatabaseName == null || defaultDatabaseName.isBlank()) {
+
+                        final Optional<String> userDB = names.stream()
+                                .filter(name -> name.equals(databaseName))
+                                .findFirst();
+
+                        if(defaultDatabaseName == null || defaultDatabaseName.isBlank()){
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:841]: QQ: Why are we checking for both `userDB` and `defaultDatabaseName` ?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/exceptions/MongoPluginErrorMessages.java [hunk 7]
```diff
@@ -56,6 +56,7 @@ private MongoPluginErrorMessages() {
             "check the URI once.";
 
     public static final String DS_MISSING_DEFAULT_DATABASE_NAME_ERROR_MSG = "Missing default database name.";
+    public static final String DS_INVALID_USER_DATABASE_NAME = "Database Name is invalid, no database found with this name.";
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/exceptions/MongoPluginErrorMessages.java:59]: As mentioned earlier, can we update the name to `DS_INVALID_AUTH_D...` and the message to `Authentication Database Name is...` ?

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java [hunk 8]
```diff
@@ -188,6 +188,36 @@ public void testDatasourceFailWithInvalidDefaultDatabaseName() {
...
+    public void testDatasourceFailWithEmptyDefaultDatabaseNameAndInvalidUserDBName() {
+        DatasourceConfiguration dsConfig = createDatasourceConfiguration();
+        dsConfig.getConnection().setDefaultDatabaseName("");
+        DBAuth dbAuth = new DBAuth();
+        dbAuth.setDatabaseName("abcd");
+        dsConfig.setAuthentication(dbAuth);
+        StepVerifier.create(pluginExecutor.testDatasource(dsConfig))
+                .assertNext(datasourceTestResult -> {
+                    assertNotNull(datasourceTestResult);
+                    assertFalse(datasourceTestResult.isSuccess());
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java:201]: Also, please check add check for exact error message received if any.

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java [hunk 9]
```diff
@@ -188,6 +188,36 @@ public void testDatasourceFailWithInvalidDefaultDatabaseName() {
...
+                })
+                .verifyComplete();
+    }
+
+    @Test
+    public void testDatasourceFailWithEmptyDefaultDatabaseNameAndValidUserDBName() {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java:207]: As mentioned earlier, the default database name is optional and hence if the field is left empty it should be fine. In which case, we should update this test to check for test datasource pass.

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java [hunk 10]
```diff
@@ -188,6 +188,36 @@ public void testDatasourceFailWithInvalidDefaultDatabaseName() {
...
+        DatasourceConfiguration dsConfig = createDatasourceConfiguration();
+        dsConfig.getConnection().setDefaultDatabaseName("");
+        DBAuth dbAuth = new DBAuth();
+        dbAuth.setDatabaseName("test");
+        dsConfig.setAuthentication(dbAuth);
+        StepVerifier.create(pluginExecutor.testDatasource(dsConfig))
+                .assertNext(datasourceTestResult -> {
+                    assertNotNull(datasourceTestResult);
+                    assertTrue(datasourceTestResult.isSuccess());
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java:216]: QQ: The test case name says `testDatasourceFail...` but we seem to be checking for `isSuccess=True`. Is this ok ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 4 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:825]: to handle the case when the db is configured with with no authentication. In that case the DBAuth object returned here will be null.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 11]
```diff
@@ -816,21 +816,40 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
...
                         final Publisher<String> result = mongoClient.listDatabaseNames();
                         final Mono<List<String>> documentMono = Flux.from(result).collectList().cache();
                         return documentMono.doFinally(ignored -> mongoClient.close()).then(documentMono);
                     })
                     .flatMap(names -> {
+
+                        final String defaultDatabaseName;
+                        if (datasourceConfiguration.getConnection() != null) {
+                            defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
+                        } else defaultDatabaseName = null;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:830]: Minor: can we please write the else block using curly braces ? 
if () {
// code
}
else {
// code
}

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 12]
```diff
@@ -816,21 +816,40 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
...
+
+                        final String authDatabaseName;
+                        if (datasourceConfiguration.getAuthentication() != null) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:833]: In the `if` condition should we also check for `!isBlank(datasourceconfiguration.getAuthentication().getDatabaseName())` ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 13]
```diff
@@ -827,10 +827,13 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
...
                             defaultDatabaseName = datasourceConfiguration.getConnection().getDefaultDatabaseName();
-                        } else defaultDatabaseName = null;
+                        } else {
+                            defaultDatabaseName = null;
+                        }
 
                         final String authDatabaseName;
-                        if (datasourceConfiguration.getAuthentication() != null) {
+                        if (datasourceConfiguration.getAuthentication() != null &&
+                                !((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName().isBlank()) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:836]: Should we replace the `.isBlank()` call with the function call `isBlank(....getDatabaseName())` reason being that in case the database name is `null` then `null.isBlank` will lead to NPE ?

Comment (sumitsum) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:836]: JFYI, I am referring to `StringUtils.isBlank` function here.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 14]
```diff
@@ -833,7 +834,7 @@ public Mono<DatasourceTestResult> testDatasource(DatasourceConfiguration datasou
 
                         final String authDatabaseName;
                         if (datasourceConfiguration.getAuthentication() != null &&
-                                isBlank(((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName())) {
+                                isEmpty(((DBAuth)datasourceConfiguration.getAuthentication()).getDatabaseName())) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:837]: QQ: Why did we choose to use `isEmpty` instead of `isBlank` ?

Comment (sumitsum) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:837]: Also, shouldn't it be `!isEmpty` ?

Comment (PiyushPushkar02) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java]: I have corrected the incorrect boolean check. Also, I have changed it to isBlank but it wouldn't have made a difference as they both do the same thing except isBlank also checks for whitespace. But that wouldn't have been a problem for us as the value is already trimmed. They belong to different classes isBlank comes from logging utils of apache and isEmpty comes from String utils.

Comment (sumitsum) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java]: Hi Piyush, sorry I couldn't find if we are trimming the value anywhere. Can you please share where I can find it ?

**Review by sumitsum — APPROVED** [review]
