### PR TITLE
fix: Handle widget selection on modal closure when url changes.

### LINKED ISSUE #31614: [Bug]: On invoking modal1 on the Vehicle maintenance app template, and then going to home page, missing page id error pops up
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Navigating to home page after invoking modal1 in the vehicle maintenance app template causes missing page id error to pop up

### Steps To Reproduce

1. Create a vehicle maintenance app template
2. Invoke modal1 from the widget pane
3. Navigate to home page
4. Note an error is thrown on the home page.

https://github.com/appsmithorg/appsmith/assets/101863839/b446b603-f0e1-4c79-a423-185f35e286e1

Screenshot 2024-03-08 at 10 47 55 AM

### Public Sample App

_No response_

### Environment

Production

### Severity

High (Blocker to building)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description

<ins>Root cause</ins>
In the case of `Vehicle maintenence app` the problem was when you had modal open and clicked on appsmith logo - it triggered evaluations, which in turn closed the modal -> and modal saga called select widget saga (to select the main container)

This PR adds a check in the widget selection saga to ensure that we dont run the selection logic if we are not on the editor url.

Fixes #31614
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Widget,@tag.Modal,@tag.MainContainer,@tag.Container"

### :mag: Cypress test results

> [!IMPORTANT]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8249215900>
> Commit: `f9aee9ac5e03c556782df6b8306ddc75261e2d10`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8249215900&attempt=2" target="_blank">Click here!</a>
> All cypress tests have passed 🎉🎉🎉

## Summary by CodeRabbit

- **Refactor**
	- Improved the selection process of widgets by checking if the user is on the editor page, enhancing the app usability and performance.
	- Added a condition to the selectWidgetSaga function to ensure actions are performed only when the current URL is on the editor page.

### CODE REVIEW

File: app/client/src/sagas/WidgetSelectionSagas.ts [hunk 1]
```diff
@@ -67,8 +68,10 @@ function* selectWidgetSaga(action: ReduxAction<WidgetSelectionRequestPayload>) {
       payload = [],
       selectionRequestType,
     } = action.payload;
-
-    if (payload.some(isInvalidSelectionRequest)) {
+    const isOnEditorURL = !!getAppViewerPageIdFromPath(
```
Comment (marks0351) [inline app/client/src/sagas/WidgetSelectionSagas.ts:71]: can you pls add comments explaining why we had to add this change.

**Review by marks0351 — CHANGES_REQUESTED** [review]

File: app/client/src/sagas/WidgetSelectionSagas.ts (hunk 1 above)
Comment (rahulbarwal) [reply app/client/src/sagas/WidgetSelectionSagas.ts:78]: Done.

**Review by marks0351 — APPROVED** [review]
