### PR TITLE
fix: add color picker to form component

### LINKED ISSUE #4418: [Bug] Color picker in form widget is not the same as in the container widget
## Description
There's a color picker in the container widget which shows color options. The color field in the form widget doesn't show the color options. Both of these should be the same.

Screen Shot 2021-05-11 at 4 06 00 AM
Screen Shot 2021-05-11 at 4 05 48 AM

### PR DESCRIPTION
**Pull request by Tooluloope**
Fixes #4418 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by somangshu — DISMISSED** [review]
Looks good to me

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_DragAndDropWidget_spec.js [hunk 1]
```diff
@@ -29,10 +30,13 @@ describe("Entity explorer Drag and Drop widgets testcases", function() {
...
      */
-    cy.testCodeMirror(this.data.colour);
+    cy.get(widgetsPage.backgroundcolorPicker)
+      .first()
+      .click({ force: true });
+    cy.xpath(widgetsPage.greenColor).click();
     cy.get(formWidgetsPage.formD)
       .should("have.css", "background-color")
-      .and("eq", this.data.rgbValue);
+      .and("eq", "rgb(3, 179, 101)");
```
Comment (somangshu) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_DragAndDropWidget_spec.js:39]: Why is this value hardcoded @Tooluloope

Comment (Tooluloope) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_DragAndDropWidget_spec.js:39]: Got the example from [here](https://github.com/appsmithorg/appsmith/blob/7df8581a5fa2b567c3ca10124a69373a36c45ca3/app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/LayoutWidgets/Container_spec.js#L31)

**Review by marks0351 — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]
