### PR TITLE
fix: JS option missing for Label Font Style in Input widget

### LINKED ISSUE #15542: [Bug]: JS option missing for Label Font Style in Input widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Label Font Style` property in the Input widget does not have a JS option like other widgets.

Screenshot 2022-07-29 at 4 16 57 PM

### Steps To Reproduce

1. D&D an input widget.
2. Go to the property pane.

**Expected:** JS option should be present for the `Label Font Style` property.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by sanjus-robotic-studio**
## Description

> Made changes to baseinputwidget label style - Emphasis Property
Fixes #15542 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

This has been tested locally on my Computer

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dilippitchika** [comment]
@aswathkk can you review this change? It's from our external contributor

File: app/client/src/widgets/BaseInputWidget/widget/index.tsx [hunk 1]
```diff
@@ -342,6 +342,7 @@ class BaseInputWidget<
                 value: "ITALIC",
               },
             ],
+            isJSConvertible: true,
             isBindProperty: false,
```
Comment (aswathkk) [inline app/client/src/widgets/BaseInputWidget/widget/index.tsx:346]: `isBindProperty` should be `true` so that bindings will be accepted by this field.

**Review by aswathkk — CHANGES_REQUESTED** [review]
Hi @sanjus-robotic-studio,

Thanks for contributing. We need to make the `isBindingProperty` `true` so that this field will accept binding.

File: app/client/src/widgets/BaseInputWidget/widget/index.tsx (hunk 1 above)
Comment (sanjus-robotic-studio) [reply app/client/src/widgets/BaseInputWidget/widget/index.tsx]: Hey @aswathkk  I have made the changes

**Comment by sanjus-robotic-studio** [comment]
@aswathkk I have made the changes

**Review by aswathkk — APPROVED** [review]
LGTM
