### PR TITLE
fix: remove unnecessary spaces from the active datasource page for consistent page scroll

### LINKED ISSUE #8592: [Bug]: Active Datasources page should be scrollable irrespective of the position of cursor [outside or inside]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create a few data sources and navigate to the Active Data sources page. Leave the mouse cursor as it is & try to scroll up or down to view the list of data sources. 
While the cursor is placed outside - the scrolling does not happen.
Now move the cursor to within the container & scroll & now scrolling happens OK.

### Steps To Reproduce
View this loom recording to notice the issue:

```markdown
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ffc9084d144b44e989d56815c6eab60b-00001.gif)](https://www.loom.com/share/ffc9084d144b44e989d56815c6eab60b)
```

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by danieldare**
## Description

Removes unnecessary spaces from the active data source page for consistent page scroll

Fixes #8592 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/active-datasources-page-scroll 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.11 **(-0.01)** | 36.61 **(0)** | 34.54 **(0)** | 55.64 **(0)**
 :red_circle: | app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx | 27.81 **(-0.38)** | 11.63 **(-0.27)** | 4.55 **(-0.21)** | 32.54 **(-0.26)**</details>

### CODE REVIEW

**Comment by rashmi-rai** [comment]
It breaks the UI of `Create New` tab.
Screenshot 2021-12-31 at 11 43 58 AM

File: app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx [hunk 1]
```diff
@@ -69,8 +69,7 @@ const MainTabsContainer = styled.div`
 const SectionGrid = styled.div`
   margin-top: 16px;
   display: grid;
-  grid-template-columns: 1fr 180px;
```
Comment (rashmi-rai) [inline app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx:72]: Screenshot 2021-12-31 at 11 43 58 AM

It breaks the UI of `Create New` tab

**Review by rashmi-rai — APPROVED** [review]
