### PR TITLE
fix: Input widget onSubmit gets triggered before evaluation

### LINKED ISSUE #7507: [Bug] onSubmit gets triggered before evaluation
## Description

A user reported that hitting enter in an input widget was submitting only part of the input

### Steps to reproduce the behavior:

1. Drag an input widget
2. configure onSubmit as
`{{navigateTo('Page 1',{name: Input1.text})}}`
3. Type text quickly and hit enter
4. only part of the text is present in the query param

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- A user reported that quickly hitting enter key in an input widget was submitting only part of the input
- Enforce to update text meta property before trigger the submit action

Fixes #7507 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/7507-input-widget-onSubmit-before-evaluation 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.88 **(0.01)** | 37.24 **(0.01)** | 35.22 **(0)** | 56.19 **(0)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

**Comment by sbalaji1192** [comment]
@wmdev0808
1. Let's add a detailed comment on why we're updating the text property on submit?
2. We need to write a cypress test for this. You have to verify that when enter key is pressed immediately after the text in the input, the action handlers are executed with the updated meta properties.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js [hunk 1]
```diff
@@ -107,6 +107,25 @@ describe("Input widget V2 - ", () => {
...
+    cy.selectShowMsg();
+    cy.addSuccessMessage("{{ Input1.text }}");
+    cy.get(widgetInput).clear();
+    cy.wait(300);
+    // Input text and hit enter key
+    cy.get(widgetInput).type("test{enter}");
+    // Assert if the toast message contains the whole value, test
+    cy.get(".Toastify__toast-body span").should("have.text", "test");
+  });
+
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js:128]: @wmdev0808 did you run this test case without your fix and see if this is catching the issue?

File: app/client/src/widgets/BaseInputWidget/widget/index.tsx [hunk 2]
```diff
@@ -334,7 +334,9 @@ class BaseInputWidget<
     const { isValid, onSubmit } = this.props;
     const isEnterKey = e.key === "Enter" || e.keyCode === 13;
     if (isEnterKey && typeof onSubmit === "string" && onSubmit && isValid) {
-      super.executeAction({
+      // In case users quickly type input text followed by hitting enter and using super.executeAction to trigger ON_SUBMIT action, they encounters an issue which they only get part of the input because the action is triggered before text meta property is updated.
```
Comment (sbalaji1192) [inline app/client/src/widgets/BaseInputWidget/widget/index.tsx:337]: 1. Use block comment.
2. Let's use the following comment
```
Originally super.executeAction was used to trigger the ON_SUBMIT action and updateMetaProperty to update the text. Since executeAction is not queued and updateMetaProperty is, the user would observe that the data tree only gets partially updated with text before the ON_SUBMIT would get triggered, if they type {enter} really fast after typing some input text. So we're using updateMetaProperty to trigger the ON_SUBMIT to let the data tree update before we actually execute the action. Since updateMetaProperty expects a meta property to be updated, we are redundantly updating the text here. But the main part is the action execution payload.
```
3. Let's move this to QA. Please sit with QA and explain the whole scenario.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js (hunk 1 above)
Comment (wmdev0808) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js:128]: Good point, I will fix, thank you

**Review by sbalaji1192 — APPROVED** [review]
@wmdev0808 Looks good. Please confirm that the cypress test case is catching the issue without your fix. Lets move this to QA.

**Comment by wmdev0808** [comment]
> @wmdev0808 Looks good. Please confirm that the cypress test case is catching the issue without your fix. Lets move this to QA.

Yes, I've already confirmed and moved to Needs QA pipeline

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Tested this PR and now clicking on submitting immediately shows the complete input text in the toast message and it is working as expected. 

@somangshu @sbalaji1192 @dilippitchika Apart from the original fix observed the following scenario - Clicking on Submit with empty input shows an empty toast message. Is an empty toast message is expected when there is no input text for onSubmit action?

https://www.loom.com/share/0d59e603c4754982a414e90778f19021

**Comment by dilippitchika** [comment]
Hey @YogeshJayaseelan yes, if the users want to prevent empty submissions they need to write some validation to prevent this. Can you check that as well, that if there's any validation and the criteria is not met then user should not be able to submit.

**Comment by YogeshJayaseelan** [comment]
@dilippitchika @wmdev0808 I wrote an validation condition which does not meet the criteria and still i could see empty toast message OnSubmit

https://www.loom.com/share/2d32f743646d465bb122d5001bd33f40

**Comment by sbalaji1192** [comment]
@YogeshJayaseelan You need to enable the `required` flag.

File: app/client/src/widgets/BaseInputWidget/widget/index.tsx [hunk 3]
```diff
@@ -334,7 +334,19 @@ class BaseInputWidget<
...
+       * Since executeAction is not queued and updateMetaProperty is,
+       * the user would observe that the data tree only gets partially updated with text
+       * before the ON_SUBMIT would get triggered,
+       * if they type {enter} really fast after typing some input text.
+       * So we're using updateMetaProperty to trigger the ON_SUBMIT to let the data tree update
+       * before we actually execute the action.
+       * Since updateMetaProperty expects a meta property to be updated,
+       * we are redundantly updating the text here. But the main part is the action execution payload.
+       */
+      this.props.updateWidgetMetaProperty("text", this.props.text, {
```
Comment (sbalaji1192) [inline app/client/src/widgets/BaseInputWidget/widget/index.tsx:349]: @wmdev0808 We have changed this property to `inputText` in inputWidgetV2 recently in a [PR](https://github.com/appsmithorg/appsmith/pull/11579). could also change here?

**Review by sbalaji1192 — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/BaseInputWidget/widget/index.tsx (hunk 3 above)
Comment (sbalaji1192) [reply app/client/src/widgets/BaseInputWidget/widget/index.tsx:349]: Please reach out to me before proceeding

**Comment by dilippitchika** [comment]
@YogeshJayaseelan there is a mistake in the condition, the spelling of length is wrong. I was able to check using this condition - {{Input1.text.length>12}} and we are not able to submit in that case, it's working as expected.

**Comment by YogeshJayaseelan** [comment]
> @YogeshJayaseelan there is a mistake in the condition, the spelling of length is wrong. I was able to check using this condition - {{Input1.text.length>12}} and we are not able to submit in that case, it's working as expected.

My Bad!!! Yeah after correcting spelling mistakes it is working as expected. Thanks

**Comment by somangshu** [comment]
@YogeshJayaseelan do we have your sign-off here? Is there anything else from the QA?

File: app/client/src/widgets/BaseInputWidget/widget/index.tsx (hunk 3 above)
Comment (sbalaji1192) [reply app/client/src/widgets/BaseInputWidget/widget/index.tsx:349]: @wmdev0808 As discussed, Please use isDirty instead of text here. We want to use a common property across the three inherited widget

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Tested this PR and it is working as expected
