### PR TITLE
fix: null check in Table widget

### LINKED ISSUE #8229: [Bug] Null check in removeSpecialCharacters in Table Widget
## Description
```
Cannot read properties of undefined (reading 'split')
    at removeSpecialChars (TableWidget.ts:171)
```

### Steps to reproduce the behaviour:

https://app.appsmith.com/applications/611cf172695af65b46d736c8/pages/611cf172695af65b46d736ca/edit

This error crashed the application

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #8229

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/Faulty-DSL-fix 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.78 **(0.02)** | 36.64 **(0.03)** | 33.47 **(0)** | 55.32 **(0.02)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**
 :green_circle: | app/client/src/utils/migrations/TableWidget.ts | 84.82 **(0.39)** | 75.76 **(-0.56)** | 92.59 **(0)** | 86.73 **(0.24)**</details>

### CODE REVIEW

File: app/client/src/utils/migrations/TableWidget.ts [hunk 1]
```diff
@@ -372,9 +372,18 @@ export const migrateTableSanitizeColumnKeys = (currentDSL: DSLWidget) => {
...
       const newPrimaryColumns: Record<string, ColumnProperties> = {};
       if (primaryColumnEntries.length) {
-        for (const [key, value] of primaryColumnEntries) {
+        // eslint-disable-next-line prefer-const
+        for (let [key, value] of primaryColumnEntries) {
           const sanitizedKey = removeSpecialChars(key, 200);
-          const id = removeSpecialChars(value.id, 200);
+          let id = "";
+          if (value.id) {
+            id = removeSpecialChars(value.id, 200);
```
Comment (Tooluloope) [inline app/client/src/utils/migrations/TableWidget.ts:380]: @riodeuno Could you help look at this, I'm trying to bring the Column property one level up

File: app/client/src/utils/migrations/TableWidget.ts [hunk 2]
```diff
@@ -372,9 +372,18 @@ export const migrateTableSanitizeColumnKeys = (currentDSL: DSLWidget) => {
 
       const newPrimaryColumns: Record<string, ColumnProperties> = {};
       if (primaryColumnEntries.length) {
-        for (const [key, value] of primaryColumnEntries) {
+        // eslint-disable-next-line prefer-const
+        for (let [key, value] of primaryColumnEntries) {
```
Comment (riodeuno) [inline app/client/src/utils/migrations/TableWidget.ts:376]: Let's not manipulate the `key` and `value` in this iteration and use other variables for this.

File: app/client/src/utils/migrations/TableWidget.ts [hunk 3]
```diff
@@ -372,9 +372,18 @@ export const migrateTableSanitizeColumnKeys = (currentDSL: DSLWidget) => {
...
           const sanitizedKey = removeSpecialChars(key, 200);
-          const id = removeSpecialChars(value.id, 200);
+          let id = "";
+          if (value.id) {
+            id = removeSpecialChars(value.id, 200);
+          } else if (Object.keys(value)) {
+            const onlyKey = Object.keys(value)[0] as keyof ColumnProperties;
```
Comment (riodeuno) [inline app/client/src/utils/migrations/TableWidget.ts:382]: Here I believe we're assuming that there is only one key, can we verify this, before using the nested object. Also, we can do some basic checks. For example, id, type, etc should be available in the column properties, otherwise, even if we migrate it wouldn't work.

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/src/utils/migrations/TableWidget.ts (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/utils/migrations/TableWidget.ts:376]: @riodeuno What do you mean here?
I think `value` is where the faulty object lies.

Comment (riodeuno) [reply app/client/src/utils/migrations/TableWidget.ts:376]: @Tooluloope This was just a code comment from a readability standpoint. Since, we're in control of the whole migration, we can assign a different variable here. I just wanted to avoid the `//eslint-disable-next-line prefer-const`. Updating the `value` or `key` here, would make this function difficult to read and maintain.

**Review by riodeuno — APPROVED** [review]
@Tooluloope Looks good to me! Let's try to reproduce the issue, and make sure that this fixes it.

**Comment by vivekverma2312** [comment]
@Tooluloope I tried importing the application and it's not throwing error on deploy preview.
