### PR TITLE
fix: Handling the empty object set for where clause value in new google sheets action

### LINKED ISSUE #8001: [Bug] Google sheet is broken
Unable to execute any query as it ends up displaying  an error

### PR DESCRIPTION
**Pull request by trishaanand**
Fixes #8001

### CODE REVIEW

**Review by mohanarpit — APPROVED** [review]

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java [hunk 1]
```diff
@@ -89,8 +91,15 @@ public MethodConfig(List<Property> propertyList) {
                         this.rowObjects = propertyValue;
                         break;
                     case "where":
-                        if (property.getValue() != null && !((List<Object>) property.getValue()).isEmpty()) {
-                            this.whereConditions = Condition.generateFromConfiguration((List<Object>) property.getValue());
+                        if (value != null) {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java:94]: Just to be sure can you add an instanceof check here as well? Not sure how far the UI issue goes at this point

**Review by nidhi-nair — APPROVED** [review]
