### PR TITLE
fix: Widget suggestion for firestore datasource

### LINKED ISSUE #7371: [Bug] Suggested Widget does not show widget suggestion for firestore datasource
## Description

Suggested Widget - FireStore Datasource does not show Table, Chart and Dropdown

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to Datasource
2. Click on add datasource and choose firestore and run any query
3. See the suggested Widget pane
4. Table, Chart and DropDown are missing

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> Suggested Widget for FireStore Datasource does not show Table, Chart and Dropdown

Fixes #7371 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Unit tests
- Local 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/WidgetSuggestionHelper.java [hunk 1]
```diff
@@ -5,136 +5,152 @@
...
+        //TODO - check other data types
+        if (array.isArray()) {
+            int length = array.size();
+            JsonNode node = array.get(0);
+            JsonNodeType nodeType = node.getNodeType();
+
+            DataFields dataFields = collectFieldsFromData(node.fields());
+
+            if (JsonNodeType.STRING.equals(nodeType)) {
+                return getWidgetsForTypeString(dataFields.fields, length);
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/WidgetSuggestionHelper.java:58]: Please use getter & setter fields. Referencing fields directly like this is an anti-pattern in Java.

**Review by mohanarpit — APPROVED** [review]

**Review by mohanarpit — APPROVED** [review]
