### PR TITLE
[Fix] Small UI improvements to suggested widgets section

### LINKED ISSUE #6189: [Enhancement] Minor UI improvement in suggested widgets panel
## Summary

- [x] Kill subtitles and make the chevrons better in the query editor
- [x] Add animations to show the right pane in the query editor
- [x] Optimise the whitespace in the relationships section

Will create new issue for this
~Make consistent icons for APIs vs Datasources~
~Documentation needs a better place and UI even for API~

https://www.figma.com/file/BqKAb0SFlbRpiEFxtXWyHp/?node-id=1552%3A4790

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
To add minor improvements to suggested widget panel, as listed in the issue.

Fixes #6189 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/minor-ux-changes-suggested-widgets 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 51.85 **(0.01)** | 33.67 **(0)** | 29.76 **(0)** | 52.48 **(0)**
 :green_circle: | app/client/src/components/editorComponents/ActionRightPane/index.tsx | 34.48 **(0.76)** | 25 **(0)** | 0 **(0)** | 37.5 **(0.79)**</details>

### CODE REVIEW

File: app/client/src/components/editorComponents/ActionRightPane/index.tsx [hunk 1]
```diff
@@ -30,13 +30,17 @@ import {
...
 } from "api/ActionAPI";
+import { Colors } from "constants/Colors";
 
 const SideBar = styled.div`
   padding: ${(props) => props.theme.spaces[0]}px
     ${(props) => props.theme.spaces[3]}px ${(props) => props.theme.spaces[4]}px;
   overflow: auto;
   height: 100%;
   width: 100%;
+  //transition: 0.2s ease-in;
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/ActionRightPane/index.tsx:41]: nitpick: I guess we could remove this comment

**Review by rishabhsaxena — DISMISSED** [review]

**Review by rishabhsaxena — APPROVED** [review]

**Comment by pranavkanade** [comment]
Merging this PR fails only for - `Smoke_TestSuite/ServerSideTests/QueryPane/AddWidgetTableAndBind_spec.js`
