### PR TITLE
fix: Import from file fails when workspace has a git connected app wi…

### LINKED ISSUE #28122: [Bug]: Importing an app that was initially exported from a git connected app(having atleast one child branch) throws error when added in the same workspace
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Importing an app that was initially exported from a git connected app(having atleast one child branch) throws error when added in the same workspace

### Steps To Reproduce

1. Git connect an application
2. Make sure to create a CHILD branch(This is important)
3. Export the app
4. Now import the app into the same workspace

Error is thrown

https://www.loom.com/share/5d31f58574f5422ba078e4153e39bf8c

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/Selfhosted

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
Fixes the bug when import app from file fails when target workspace has existing app with same name and multiple branches.

#### PR fixes following issue(s)
Fixes #28122

#### Media
https://www.loom.com/share/5d31f58574f5422ba078e4153e39bf8c

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java [hunk 1]
```diff
@@ -56,6 +56,11 @@ public Flux<Tuple2<String, Set<String>>> getPossibleReferencesFromDynamicBinding
         if (bindingValues == null || bindingValues.isEmpty()) {
             return Flux.empty();
         }
+
+        if (bindingValues.contains(null)) {
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java:60]: Can you please help me in understanding, what this condition is? I don't understand how this affects import flow

Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java:60]: My bad. It was an unrelated change that I was doing while debugging an issue. It got added accidentally. I'll remove this.

**Review by AnaghHegde — APPROVED** [review]
