### PR TITLE
chore: git tag - fixing contracts for pretag

### LINKED ISSUE #38808: [Task] Git Tagging - View last commit

### PR DESCRIPTION
**Pull request by brayn003**
## Description
- Updates api contracts for pretag validation in release tab

Fixes #38808

## Automation

/ok-to-test tags="@tag.Git"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13821575387>
> Commit: 751c6ee4f6e102c50de8e7402d947b63f5b6be06
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13821575387&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Git`
> Spec:
> <hr>Wed, 12 Mar 2025 22:04:53 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Introduced a new `TabRelease` component for managing pre-tagging functionality.
  - Added a custom hook `usePretag` for improved data management related to pre-tagging.
  - Implemented a new `useReleaseTag` hook for handling release tag creation.
  - Enhanced `OpsModalView` to conditionally render tagging capabilities based on artifact definition.
  - Added a new `isGitTaggingEnabled` function to determine if tagging is applicable based on artifact type.
  - Introduced loading states and improved commit information display in `LatestCommitInfoView`.

- **Bug Fixes**
  - Updated components to utilize the new pre-tagging data structure, ensuring accurate information is displayed.
  - Improved display logic in `LatestCommitInfoView` for commit messages and author information.

- **Refactor**
  - Removed outdated commit-related actions and state management, transitioning to pre-tagging actions and state.
  - Modified selectors to focus on pre-tagging data instead of the latest commit state.
  - Renamed and restructured components for clarity and consistency in handling pre-tagging and release tagging.

- **Style**
  - Updated the `TAB_RELEASE` property for improved display consistency.
  - Added new constants for loading and no commit messages to enhance user feedback.

### CODE REVIEW

File: app/client/src/git/components/OpsModal/TabRelease/TabReleaseView.tsx [hunk 1]
```diff
@@ -21,13 +22,42 @@ const StyledModalFooter = styled(ModalFooter)`
...
+  useEffect(
+    function fetchPretagOnInitEffect() {
+      fetchPretag();
+    },
+    [fetchPretag],
+  );
+
+  const handleClickOnRelease = useCallback(() => {
+    createReleaseTag({
+      tag: releaseVersion ?? "",
```
Comment (ashit-rath) [inline app/client/src/git/components/OpsModal/TabRelease/TabReleaseView.tsx:56]: Should we check for the presence of `releaseVersion` and then only dispatch this action?

Comment (brayn003) [reply app/client/src/git/components/OpsModal/TabRelease/TabReleaseView.tsx:56]: But that would silently fail without an error :(
Will be hard to debug

Comment (ashit-rath) [reply app/client/src/git/components/OpsModal/TabRelease/TabReleaseView.tsx:56]: We can throw an error but would making this call with empty releaseVersion would also throw an error then we are fine but throwing error early would be pre-emptive

**Review by ashit-rath — APPROVED** [review]
