### PR TITLE
fix: Reset templates filter for templates modal

### LINKED ISSUE #17276: [Bug]: Filters for templates are not resetting on re-opening app or opening new app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On selecting filters for templates from left pane they remain selected, even when we open some different app. Ideally we should reset it.

### Steps To Reproduce

1. Click on Start from templates card
2. Select any filter from left pane
3. Close the modal
4. Go back to Applications page
5. Open any other app, and click on start from template
6. Observe filters selected from the previous app are showing
This is also observed when we switch to Templates Tab

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description

* Currently we do not reset the template filters when we close template modal and open it again in `add page from template flow`
   This becomes confusing for some users.

* Also increases test coverage of templates filtering

#### PR fixes following issue(s)
Fixes #17276

#### Media

https://github.com/appsmithorg/appsmith/assets/6761673/3c94e21b-e8a9-4c6b-bc81-e677269bb5ea

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
#### How Has This Been Tested?
- [x] Cypress
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import * as _ from "../../../../../support/Objects/ObjectsCore";
+const NAME_FILTER = "order";
+
+describe("Templates modal filtering", () => {
+  it("1. should not retain filters when trying to add a page from template(multiple attempts)", () => {
+    _.entityExplorer.AddNewPage("Add page from template");
+    cy.get(_.templates.locators.templateDialogBox).should("be.visible");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:7]: USe `agHelper.AssrtElementVisible`

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+    cy.get(_.templates.locators._resultsHeader).then(($header) => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:9]: USe `agHelper.GetElemnt`. No direct cy.get or cy.xpath in specs.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+      _.templates.filterTemplatesByName(NAME_FILTER);
+      cy.get(_.templates.locators._resultsHeader).should(
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:11]: Use `agHelper.GetNAssertElementText`

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+        "not.have.text",
+        $header.text(),
+      );
+      _.templates.closeTemplateDialogBox();
+
+      _.entityExplorer.AddNewPage("Add page from template");
+      cy.get(_.templates.locators.templateDialogBox).should("be.visible");
+      cy.get(_.templates.locators._resultsHeader).should(
+        "have.text",
+        $header.text(),
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:21]: Sam as above.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+    _.entityExplorer.AddNewPage("Add page from template");
+    cy.get(_.templates.locators.templateDialogBox).should("be.visible");
+
+    cy.get(_.templates.locators._resultsHeader).then(($header) => {
+      _.templates.filterTemplatesByName(NAME_FILTER);
+      cy.get(_.templates.locators._resultsHeader).should(
+        "not.have.text",
+        $header.text(),
+      );
+      _.templates.closeTemplateDialogBox();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:15]: TS helper method names are CamelCase - `CloseTemplateDialogBox`

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts [hunk 6]
```diff
@@ -0,0 +1,48 @@
+import * as _ from "../../../../../support/Objects/ObjectsCore";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:1]: Correct the above comments in this spec also.

**Review by Aishwarya-U-R — CHANGES_REQUESTED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts (hunk 2 above)
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts]: Done.

**Review by akash-codemonk — APPROVED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 7]
```diff
@@ -0,0 +1,25 @@
+import * as _ from "../../../../../support/Objects/ObjectsCore";
+const NAME_FILTER = "order";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:2]: Can this variable go inside describe? Global scope necessarily not needed.

File: app/client/cypress/support/Pages/Templates.ts [hunk 8]
```diff
@@ -1,13 +1,57 @@
...
+
+  AssertResultsHeaderText(
+    text: string,
+    textPresence: "have.text" | "contain.text" | "not.have.text" = "have.text",
+  ) {
+    ObjectsRegistry.AggregateHelper.GetNAssertElementText(
+      this.locators._resultsHeader,
+      text,
+      textPresence,
+    );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/Templates.ts:55]: How many times do you think we will be using these methods? Are they really needed? instead can we use the helpers directly?
This is one more level - which is not needed.

File: app/client/cypress/support/Pages/Templates.ts [hunk 9]
```diff
@@ -1,13 +1,57 @@
...
+      .get("input[type='checkbox']")
+      .check(valuesToBeChecked, { force: true });
+  }
+
+  VisitFirstTemplate() {
+    return cy.get(this.locators._templateCard).first().click();
+  }
+
+  GobackFromTemplateDetailedView() {
+    return cy.get(this.locators._templateViewGoBack).click();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/Templates.ts:40]: No direct cy.get or cy.xpath in specs/helpers. Use `agHelper.GetElement` only,

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts [hunk 10]
```diff
@@ -0,0 +1,58 @@
...
+
+describe("Templates page filtering", () => {
+  before(() => {
+    _.homePage.NavigateToHome();
+    _.homePage.SwitchToTemplatesTab();
+  });
+  beforeEach(() =>
+    _.agHelper.AssertElementVisible(_.templates.locators._templateCard),
+  );
+  afterEach(() => cy.reload());
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:14]: Use `agHelper.Refresh()`

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 11]
```diff
@@ -0,0 +1,25 @@
...
+  it("1. should not retain filters when trying to add a page from template(multiple attempts)", () => {
+    _.entityExplorer.AddNewPage("Add page from template");
+    _.agHelper.AssertElementVisible(_.templates.locators.templateDialogBox);
+
+    _.agHelper
+      .GetText(_.templates.locators._resultsHeader)
+      .then((headerText) => {
+        _.templates.FilterTemplatesByName(NAME_FILTER);
+        if (typeof headerText === "string") {
+          _.templates.AssertResultsHeaderText(headerText, "not.have.text");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:14]: Can you explain this condition a bit. 
We are searching with 'order'. Then expecting header to not have text? Which element is this _resultsHeader in UI please?

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts (hunk 7 above)
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts]: Done.

File: app/client/cypress/support/Pages/Templates.ts (hunk 8 above)
Comment (rahulbarwal) [reply app/client/cypress/support/Pages/Templates.ts]: Kept only those methods which have more than one usage.
I was thinking of future problems, but yeah why solve a problem which we have not faced yet.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts (hunk 10 above)
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts]: Done.

File: app/client/cypress/support/Pages/Templates.ts (hunk 9 above)
Comment (rahulbarwal) [reply app/client/cypress/support/Pages/Templates.ts]: Done.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts (hunk 11 above)
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:14]: Before we type header will have something like: "Showing 20 templates"
After we type into the search input, if filtering is successful the number of templates should be less and header would have changed to something like "Showing 5 templates"

This check basically means that filtering via search input indeed is functional.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:14]: Oh I see that now!

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 12]
```diff
@@ -0,0 +1,25 @@
+import * as _ from "../../../../../support/Objects/ObjectsCore";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:1]: Also please import only needed objects from ObjectsCore:
```
import {
  agHelper,
  entityExplorer
} from "../../../../support/Objects/ObjectsCore";
```

I'm seeing only entityExplorer & agHelper are needed in specs. So why to import 100% of objects.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts [hunk 13]
```diff
@@ -0,0 +1,62 @@
...
+
+  it("2. should filter templates by functions", () => {
+    _.agHelper
+      .GetText(_.templates.locators._resultsHeader, "text")
+      .then((headerText) => {
+        _.agHelper
+          .GetElement("input[type='checkbox']")
+          .check(FUNCTIONS_FILTER, {
+            force: true,
+          });
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:37]: Can we use` agHelper.CheckUncheck` here?

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts [hunk 14]
```diff
@@ -0,0 +1,62 @@
...
+    _.templates.FilterTemplatesByName(NAME_FILTER);
+    _.agHelper.Sleep();
+    _.agHelper
+      .GetText(_.templates.locators._resultsHeader, "text")
+      .then((headerText) => {
+        _.agHelper.GetNClick(_.templates.locators._templateCard);
+        _.agHelper.GetNClick(_.templates.locators._templateViewGoBack);
+        _.agHelper
+          .GetText(_.templates.locators._templatesSearchInput, "val")
+          .should("equal", NAME_FILTER);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:56]: Use `agHelper.AssertText` here

File: app/client/cypress/support/Pages/Templates.ts (hunk 8 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/Templates.ts]: Yeah if method is needed more than once, we can definitely have them created. Else lets prefer to use the helpers to solve the case.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 15]
```diff
@@ -0,0 +1,25 @@
...
+        _.agHelper.GetNClick(_.templates.locators.templateDialogCloseButton);
+
+        _.entityExplorer.AddNewPage("Add page from template");
+        _.agHelper.AssertElementVisible(_.templates.locators.templateDialogBox);
+        if (typeof headerText === "string") {
+          _.templates.AssertResultsHeaderText(headerText, "have.text");
+        }
+      });
+  });
+});
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:25]: And hey, do you think we will add more cases to this spec? Can we please combine the below spec also into this - `TemplatesFiltering_Spec.ts`? Totally 5 `it` blocks in a spec is still fine.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts (hunk 12 above)
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts]: Done in both files.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts (hunk 14 above)
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts]: Done.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts (hunk 15 above)
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:27]: There are 2 reasons for keeping these separate:
1. Process to reach these is different, for one we go to templates tab, for this one we go inside any app and then go to `add a page from template`
2. yes, we expect that test cases in this might increase in nearby future.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts [hunk 16]
```diff
@@ -0,0 +1,27 @@
+import {
+  agHelper,
+  entityExplorer,
+  templates,
+} from "../../../../../support/Objects/ObjectsCore";
+
+describe("Templates modal filtering", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts:7]: Also better to add Bug id to describe - so anyone searching in future will know a test case exists for this & dont duplicate.
`describe("Bug 17276 - Templates modal filtering", () => {`

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good!

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts (hunk 16 above)
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts]: Makes sense added. 

Thanks @Aishwarya-U-R  for a thorough review 🙂. I'll make lesser mistakes because of you.

**Comment by shwetha-ramesh** [comment]
@rahulbarwal Tested this [DP](https://appsmith-m818t6doy-get-appsmith.vercel.app/) and found this [issue](https://www.loom.com/share/7d77ae5a742e4b4092021fbe417b4dda)

**Comment by rahulbarwal** [comment]
Thanks @shwetha-ramesh for bringing this to attention. 
Upon debugging this we found a bug in design system, and raised a ticket for this: https://github.com/appsmithorg/design-system/issues/501

We will continue on this once that is resolved.

**Comment by rahulbarwal** [comment]
Hey @shwetha-ramesh , 
>Tested this [DP](https://appsmith-m818t6doy-get-appsmith.vercel.app/) and found this [issue](https://www.loom.com/share/7d77ae5a742e4b4092021fbe417b4dda)

This issue has been fixed. Please test this on [DP URL](https://appsmith-bx0fm6izf-get-appsmith.vercel.app)

**Comment by shwetha-ramesh** [comment]
@rahulbarwal Re-tested this ticket along with the issue reported. Working as expected. 
QA Done

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts [hunk 17]
```diff
@@ -0,0 +1,69 @@
+import {
+  homePage,
+  agHelper,
+  templates,
+} from "../../../../../support/Objects/ObjectsCore";
+
+describe("excludeForAirgap", "Templates page filtering", () => {
```
[the remark this answers is not in the document]
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:7]: Nope, with this PR I am increasing the test coverage to templates pages.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts [hunk 18]
```diff
@@ -0,0 +1,69 @@
...
+      });
+  });
+
+  it("2. should filter templates by functions", () => {
+    agHelper
+      .GetText(templates.locators._resultsHeader, "text")
+      .then((headerText) => {
+        agHelper.GetElement("input[type='checkbox']").check(FUNCTIONS_FILTER, {
+          force: true,
+        });
```
[the remark this answers is not in the document]
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:42]: `FUNCTIONS_FILTER` is an array here, I am selecting multiple check boxes at once. Dont think `CheckUncheck` can be used.

[the remark this answers is not in the document]
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:42]: Ok, `CheckUncheck` can still be called individually which will also check the checked state after checked.
Leaving it to your call now. But if this is flaky - we may need to fix it.

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts [hunk 19]
```diff
@@ -0,0 +1,69 @@
...
+  it("1. should filter templates by name", () => {
+    agHelper
+      .GetText(templates.locators._resultsHeader, "text")
+      .then((headerText) => {
+        templates.FilterTemplatesByName(NAME_FILTER);
+        // here we check if header changes, if it does we can assume
+        // list has been filtered
+        if (typeof headerText === "string") {
+          templates.AssertResultsHeaderText(headerText, "not.have.text");
+        }
```
[the remark this answers is not in the document]
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:32]: I am testing filtering with this spec here. Consider this scenario:
1. We have 20 templates and header text says "Showing 20 templates"
2. I filter it using name or by checking the "Functions" 
3. resultant header text would be "Showing n templates" where n<20(if filter is successfull)
4. we can not assume what this n would turn out to be. And as the templates team keeps on adding new templates, these numbers would fluctuate more.

Only workaround this would be to use a fixture so that we can dictate the headers and filters. 
What do you think would be better to have this via fixtures OR via templates(& cloud services network call) communication?

[the remark this answers is not in the document]
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts:32]: Ok, ah I see... According to me - the valid test for filtering would be to check if each of the filtered template has the filtered category against it. Headers - I'm all skeptical about test validation :)

File: app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts (hunk 18 above)
[the remark this answers is not in the document]
Comment (rahulbarwal) [reply app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts]: We don't want that 😛. 
The checkboxes are dynamic in this page and did not have name attribute. Added that and used `CheckUncheck`

**Comment by rahulbarwal** [comment]
@Aishwarya-U-R 
Updated the spec to address concerns raised above. Used fixtures where possible. Please take a look.

File: app/client/cypress/fixtures/Templates/AllowPageImportTemplates.json [hunk 20]
```diff
@@ -118,7 +118,7 @@
         "SWITCH_WIDGET",
         "TABS_WIDGET"
       ],
-      "functions": [],
+      "functions": ["Customer Support"],
```
Comment (Aishwarya-U-R) [inline app/client/cypress/fixtures/Templates/AllowPageImportTemplates.json:121]: I dint get why this is added!

File: app/client/cypress/support/Pages/Templates.ts [hunk 21]
```diff
@@ -8,27 +8,70 @@ export class Templates {
...
+      this.agHelper.GetNClick(this.locators._templatesTab);
+      this.agHelper.AssertElementVisible(
+        this.locators._requestForTemplateBtn,
+        0,
+        30000,
+      ); //giving more time here for templates page to fully load, since there is no intercept validation for same
+    });
+  }
+
+  refreshTemplatesPage(
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/Templates.ts:55]: `RefreshTemplatesPage` - method name.

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes.

File: app/client/cypress/support/Pages/Templates.ts (hunk 21 above)
Comment (rahulbarwal) [reply app/client/cypress/support/Pages/Templates.ts]: Done. 👍

**Review by abm17 — APPROVED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]
