### PR TITLE
fix: not able to delete No action card

### LINKED ISSUE #23345: TypeError: Cannot read properties of undefined (reading 'label')
Sentry Issue: [APPSMITH-6AW](https://appsmith.sentry.io/issues/4167900366/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'label')
  at getActionTypeLabel (components/editorComponents/ActionCreator/viewComponents/ActionBlockTree/utils.tsx:228:41)
  at onChange (components/editorComponents/ActionCreator/index.tsx:183:23)
  at handleChange (components/editorComponents/ActionCreator/viewComponents/Action/index.tsx:32:7)
  at <object>.{children#2}.onClick (components/editorComponents/ActionCreator/viewComponents/Action/ActionSelector.tsx:158:13)
...
(15 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ravikp7**
## Description
This Pr fixes an issue when user was not able to delete a `No action` card from the action selector.

#### PR fixes following issue(s)
fixes #23345 #22596 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]

**Comment by Aishwarya-U-R** [comment]
@ravikp7 - Merge latest release & trigger new oktotest. Cancelling the re-run since its past 12 hours from initial attempt.

File: app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import { WIDGET } from "../../../../locators/WidgetLocators";
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { agHelper, entityExplorer, propPane } = _;
+
+describe("Delete No Action card without any error", () => {
+  it("Bug 23345", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts:7]: Add Index to `it` block

File: app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts [hunk 2]
```diff
@@ -0,0 +1,18 @@
+import { WIDGET } from "../../../../locators/WidgetLocators";
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { agHelper, entityExplorer, propPane } = _;
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts:4]: Dont declare objects again in local spec file. Use it from ObjectsCore directly. This simply increases the readable code/length of spec file.

File: app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts (hunk 1 above)
Comment (ravikp7) [reply app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts]: done

File: app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts [hunk 3]
```diff
@@ -0,0 +1,20 @@
+import { WIDGET } from "../../../../locators/WidgetLocators";
+import {
+  agHelper,
+  entityExplorer,
+  propPane,
+} from "../../../../support/Objects/ObjectsCore";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts:6]: No, it should be `import * as _ from "../../../../support/Objects/ObjectsCore";`
And usage wil be like     `_.entityExplorer.DragDropWidgetNVerify(WIDGET.BUTTON, 200, 200);`

Comment (ravikp7) [reply app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts:6]: @Aishwarya-U-R I don't see a point in doing `_.` everywhere. I think it's better to just totally get rid of `_`. In fact, it's bad that we're importing the whole `ObjectsCore` as `_` even when we're not using all of its properties. Destructuring while importing is a better choice here as we import only the properties we want to use.

Let me know your thoughts on this.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts:6]: We introduced ObjectsCore since all specs were creating their own objects multiple time - which means multiple objects getting created. If you see ObjectsCore - it is basically creating the objects once & the once created objects are being used in any number of specs its called.
With this statement - if anyone wants to use deployHelper in same spec, I can envision them to add an extra entry into this import - which is essentially why we had 'one import use any helper' concept with ObjectsCore.
Even with this statement - you are again using the ObjectsCore consts which is better used with `_. agHelper` which will help remove this import line at top of spec completely.

Comment (ravikp7) [reply app/client/cypress/e2e/Regression/ClientSide/ActionExecution/Bug23345_spec.ts]: Understood. Done
