### PR TITLE
fix: Improved error message for google sheet insert/update empty body

### LINKED ISSUE #17343: [Feature]: gsheets improve error for empty insert/update
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. create a valid gsheets datasource
2. select operation as `Insert One` and entity as `Sheet Rows`
3. don't enter anything else, and run the query

Error is shown as: `argument "content" is null`
This error is not clear, and does not help the user to understand what they need to fix.

A better error would be something that points to the fields that are offered by the query form, in this case it is called `Row Object`, so the message could be something like `Row Object cannot be empty`  

Alternatively, there is another error that is shown in case I enter empty brackets `{}` in the row object: `Expected a row object.` This error is also an improvement over the current one.

### Why should this be worked on?

Google Sheets datasource is frequently the first datasource used by new users because of less friction to set up some backend data. The problem above described above represents initial friction that the user faces when creating their app.

### PR DESCRIPTION
**Pull request by vaibh1297**
## Description

> Improved error message for google sheet insert/update empty body

Fixes #17343

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java [hunk 1]
```diff
@@ -68,6 +68,9 @@ public boolean validateExecutionMethodRequest(MethodConfig methodConfig) {
         JsonNode bodyNode;
         try {
             bodyNode = this.objectMapper.readTree(methodConfig.getRowObjects());
+        } catch (IllegalArgumentException e) {
+            throw new AppsmithPluginException(AppsmithPluginError.PLUGIN_ERROR,
+                    "Row Object cannot be empty");
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:73]: Minor: Please follow sentence casing for all user-facing error messages. In this case, it would be: "Row object cannot be empty".

Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java]: done

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java [hunk 2]
```diff
@@ -68,6 +68,9 @@ public boolean validateExecutionMethodRequest(MethodConfig methodConfig) {
         JsonNode bodyNode;
         try {
             bodyNode = this.objectMapper.readTree(methodConfig.getRowObjects());
+        } catch (IllegalArgumentException e) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:71]: QQ: Could `IllegalArgumentException` indicate other things apart from the row object being empty ? e.g. if the object format is not correct i.e. `readTree` fails to parse the non-empty row object ?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java [hunk 3]
```diff
@@ -237,10 +240,16 @@ public JsonNode transformExecutionResponse(JsonNode response, MethodConfig metho
...
 
-        if (body.isArray() || body.isEmpty()) {
+        if (body.isArray()) {
             throw new AppsmithPluginException(AppsmithPluginError.PLUGIN_ERROR,
                     "Expected a row object.");
         }
+
+        if (body.isEmpty()) {
+            throw new AppsmithPluginException(AppsmithPluginError.PLUGIN_ERROR,
+                    "Row object cannot be empty.");
```
Comment (sumitsum) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:250]: Can you please update the message to `Row object cannot be emtpy. Please edit the <xyz> field in the GSheet query form to provide row object.`

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsBulkAppendMethod.java [hunk 4]
```diff
@@ -64,6 +64,9 @@ public boolean validateExecutionMethodRequest(MethodConfig methodConfig) {
         JsonNode bodyNode;
         try {
             bodyNode = this.objectMapper.readTree(methodConfig.getRowObjects());
+        } catch (IllegalArgumentException e) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsBulkAppendMethod.java:67]: QQ: Could IllegalArgumentException indicate other things apart from the row object being empty ? e.g. if the object format is not correct i.e. readTree fails to parse the non-empty row object ?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java [hunk 5]
```diff
@@ -216,6 +219,17 @@ public JsonNode transformExecutionResponse(JsonNode response, MethodConfig metho
     }
 
     private RowObject getRowObjectFromBody(JsonNode body) {
+
```
Comment (sumitsum) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:222]: Please add JUnit TC if possible.

Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:227]: Adding unit test for this might not be possible, since this includes authorisation into someone's google account and performing insert/update operation on google sheet.
Do we have any google account on which this can be done ?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 2 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:72]: done

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsBulkAppendMethod.java (hunk 4 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsBulkAppendMethod.java:68]: done

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 3 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:255]: what is this <xyz> field ?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java [hunk 6]
```diff
@@ -237,10 +245,16 @@ public JsonNode transformExecutionResponse(JsonNode response, MethodConfig metho
 
     private RowObject getRowObjectFromBody(JsonNode body) {
 
-        if (body.isArray() || body.isEmpty()) {
+        if (body.isArray()) {
             throw new AppsmithPluginException(AppsmithPluginError.PLUGIN_ERROR,
                     "Expected a row object.");
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:250]: Please consider moving all these messages to a single file for Google Sheets. While we do this, please also think about how best to organize the hierarchy of these messages. @subrata71 will be working on creating a framework for error reporting soon and this insight might come in handy.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java [hunk 7]
```diff
@@ -68,6 +69,13 @@ public boolean validateExecutionMethodRequest(MethodConfig methodConfig) {
         JsonNode bodyNode;
         try {
             bodyNode = this.objectMapper.readTree(methodConfig.getRowObjects());
+        } catch (IllegalArgumentException e) {
+            if (!StringUtils.hasLength(methodConfig.getRowObjects())) {
+                throw new AppsmithPluginException(AppsmithPluginError.PLUGIN_ERROR,
+                        "Row object cannot be empty.");
+            } else {
+                throw e;
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:77]: Is it neccesary for us to throw raw exception here? How does this raw exception show up for users in the UI? What error do they see? Do we need to wrap this in `AppsmithPluginException`?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 3 above)
Comment (mohanarpit) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:255]: `<xyz>` field == The field that is nul/empty. This error message will help users understand & resolve their error message on their own with greater ease.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 7 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:77]: I think this will make error message more readable. 
throw new AppsmithPluginException(AppsmithPluginError.PLUGIN_ERROR,e.getMessage());

Comment (mohanarpit) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:77]: Sure. Please go ahead & make that change.

Minor nit: Since we are throwing an exception in the if-clause, we don't really need an else-clause.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 3 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:255]: Field name is "Row object" only.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java (hunk 5 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:227]: @mohanarpit do we have any google account for this ?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 6 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:250]: @nidhi-nair can this be picked up in a separate issue ?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java (hunk 5 above)
Comment (mohanarpit) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:226]: No. We don't have a google account that we test against. I'd highly recommend testing against a valid Google account. Is there a possibility to mock the API and return mock responses?

Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:226]: Have already tested it with my appsmith google account, but adding unit test is not possible.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 7 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java]: done

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java (hunk 5 above)
Comment (mohanarpit) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:226]: @vaibh1297 Can I ask why adding a unit test is not possible? Is it because we cannot mock the function response? Or is there some other reason?

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 6 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java:249]: Perhaps we can move the strings away in this PR and organize them in a separate PR? I think it's usually easier to retain context, and push such things in one go. But I'll leave the decision up to you, I'm okay either way. :)

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java (hunk 5 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:226]: Should I add unit test for a valid google account (actual api call) or just mock the api call ?

Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:226]: Okay, let me try this.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 6 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java]: done, please review @nidhi-nair

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java (hunk 5 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java:227]: Have added unit test for RowAppendMethod, let me know if it looks good ? Will add for remaining three cases as well.

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 6 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java]: @nidhi-nair

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java (hunk 3 above)
Comment (sumitsum) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java]: @vaibh1297 In the comment template `<xyz>` is a placeholder i.e. it should be replaced with the name of the field. The reason that I didn't name the actual field and kept it as `<xyz>` is so that we could apply the same template to any other comment as well - which may be related to a different field.

Comment (vaibh1297) [reply app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java]: done

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/constants/ErrorMessages.java [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+
+    public static final String EMPTY_ROW_OBJECT_MESSAGE = "Row Object cannot be empty. Please edit the Row Object field in the Google Sheet query form.";
+
+    public static final String EMPTY_ROW_ARRAY_OBJECT_MESSAGE = "Row Object(s) cannot be empty. Please edit the Row Object(s) field in the Google Sheet query form.";
+
+    public static final String EMPTY_UPDATE_ROW_OBJECT_MESSAGE = "Update Row Object cannot be empty. Please edit the Update Row Object field in the Google Sheet query form.";
+
+    public static final String EMPTY_UPDATE_ROW_OBJECTS_MESSAGE = "Update Row Object(s) cannot be empty. Please edit the Update Row Object(s) field in the Google Sheet query form.";
+
+    public static final String EXPECTED_ROW_OBJECT_MESSAGE = "Expected a row object. Please edit the Row Object field in the Google Sheet query form.";
```
Comment (sumitsum) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/constants/ErrorMessages.java:13]: Nitpick: please capitalize the  first letters in`row object` field since the same format has been used in all messages before this. 
Also, please check the same for all the other messages.

**Review by sumitsum — APPROVED** [review]
