### PR TITLE
return url on file create and fix image/video file upload issues with amazons3 plugin

### LINKED ISSUE #2985: [Feature] S3 plugin: return signed url when file is uploaded
## Summary
1. Return signed url when file is uploaded.

## Motivation
Requested in office hour session.

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
1. Return url on file create. 
2. Fix image/video upload. 

Fixes #2985 #3011

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?
- Unit TCs.
- Manual testing.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java [hunk 1]
```diff
@@ -164,40 +171,85 @@ public AmazonS3Plugin(PluginWrapper wrapper) {
...
-                                   String body)
-                                   throws InterruptedException {
-            InputStream inputStream = new ByteArrayInputStream(body.getBytes());
+                                   String body,
+                                   Boolean usingFilepicker,
+                                   int durationInMillis)
+                throws InterruptedException, AppsmithPluginException {
+
+            byte[] payload = null;
+            if(usingFilepicker == true) {
```
Comment (trishaanand) [inline app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java:186]: The following ensures that the null value of usingFilepicker also gets caught.
```suggestion
            if(Boolean.TRUE.equals(usingFilepicker)) {
```

File: app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java [hunk 2]
```diff
@@ -164,40 +171,85 @@ public AmazonS3Plugin(PluginWrapper wrapper) {
...
          */
-        boolean uploadFileFromBody(AmazonS3 connection,
+        String uploadFileFromBody(AmazonS3 connection,
                                    String bucketName,
                                    String path,
-                                   String body)
-                                   throws InterruptedException {
-            InputStream inputStream = new ByteArrayInputStream(body.getBytes());
+                                   String body,
+                                   Boolean usingFilepicker,
```
Comment (trishaanand) [inline app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java:181]:
```suggestion
                                   Boolean usingFilePicker,
```

File: app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java [hunk 3]
```diff
@@ -164,40 +171,85 @@ public AmazonS3Plugin(PluginWrapper wrapper) {
...
             S3ObjectInputStream content = fullObject.getObjectContent();
+            byte[] bytes = IOUtils.toByteArray(content);
 
-            String result = "";
-            String line = null;
-            BufferedReader reader = new BufferedReader(new InputStreamReader(content));
-            while ((line = reader.readLine()) != null) {
-                result += line + "\n";
+            String result = null;
+            if(encodeContent == true) {
```
Comment (trishaanand) [inline app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java:248]: Same as before. This way of check ensures null values are handled as well.
```suggestion
            if(Boolean.TRUE.equals(encodeContent)) {
```

File: app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java [hunk 4]
```diff
@@ -178,12 +178,12 @@ String uploadFileFromBody(AmazonS3 connection,
...
                                    String path,
                                    String body,
-                                   Boolean usingFilepicker,
+                                   Boolean usingFilePicker,
                                    int durationInMillis)
                 throws InterruptedException, AppsmithPluginException {
 
             byte[] payload = null;
-            if(usingFilepicker == true) {
+            if(Boolean.TRUE.equals(usingFilepicker)) {
```
Comment (trishaanand) [inline app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java:186]:
```suggestion
            if(Boolean.TRUE.equals(usingFilePicker)) {
```

**Review by trishaanand — APPROVED** [review]
