### PR TITLE
fix: empty error toast message in CI issue fixed

### LINKED ISSUE #27489: [Task]: Debug editor going to loading state with an empty toast message on cypress CI
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Original issue where this was reported https://github.com/appsmithorg/appsmith/issues/24174

Seems to be more frequent on EE. 

editor

Failed test: https://internal.appsmith.com/app/cypressdashboard/specdetails-64ec3df0c632e24c00764939?branch=master&specID=937535&testsstatus=failed

### PR DESCRIPTION
**Pull request by sneha122**
## Description

In CI, we observed that in a couple of cases, when we open application in edit mode, we get a blank toast message or sometimes error toast message which is caused while fetching plugin form configs. This PR identifies and fixes the potential cause of the issue.

#### PR fixes following issue(s)
Fixes #27489 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/sagas/PluginSagas.ts [hunk 1]
```diff
@@ -124,32 +124,35 @@ function* fetchPluginFormConfigsSaga() {
...
-          dependencies[pluginId] = pluginFormData[index].dependencies;
-        }
-        // Datasource form buttons config if not available use default
-        if (plugin && !pluginFormData[index].formButton) {
-          datasourceFormButtonConfigs[pluginId] =
-            defaultDatasourceFormButtonConfig[plugin.type];
-        } else {
-          datasourceFormButtonConfigs[pluginId] =
-            pluginFormData[index].formButton;
+        if (!!pluginFormData[index]) {
```
Comment (AmanAgarwal041) [inline app/client/src/sagas/PluginSagas.ts:127]: Shouldn't there be an else condition? As earlier also if the `pluginFormData[index]` was `undefined` or `null` then the error would still be empty. Any suggestions ?

Comment (sneha122) [reply app/client/src/sagas/PluginSagas.ts:132]: @AmanAgarwal041 I dont think we require else condition here because, if pluginFormData[index] itself is undefined, then what would we even add in else, moreover over here we are simply setting a couple of objects, it should not be set in case of pluginFormData[index] being undefined.

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by sneha122** [comment]
This PR does not require manual testing, it simply adds more logs to understand the issue in CI. Hence adding test plan approved label CC: @rohan-arthur @btsgh @chandannkumar
