### PR TITLE
fix: Reduce RTS calls in the updateLayout flow

### LINKED ISSUE #37055: [Task]: Resolve the delay due to RTS for the updateLayout
### SubTasks

Post adding instrumentation around the JS object updation request, we observed from the metrics that the RTS call is taking about 3 seconds for every request. 
[This newrelic trace](https://one.newrelic.com/distributed-tracing?account=4209548&duration=259200000&filters=%28name%20LIKE%20%27rishabh%27%20OR%20id%20%3D%20%27rishabh%27%20OR%20domainId%20%3D%20%27rishabh%27%29&state=63e87a65-6da5-d58d-f38b-ec78c6a38780) verifies this information.

image

This task is to further debug and understand the reason for this large time taken.

### PR DESCRIPTION
**Pull request by rishabhrathod01**
## Description

In this PR, we update the code to send all the bindings to RTS together instead of calling it for each property binding. It was observed that the calls were earlier around 40k for the test application. 

This change leads to optimisation of performance for 
- updateLayout call ( when updating anything in the DSL ) 
- query/API action update 
- JS action update

Fixes #37055

## Tests on DP 

Deploy-Preview-URL: https://ce-37127.dp.appsmith.com/

- [x] Multiple widgets with the same bindings impacting the sequence of onPageLoadActions
- onPageLoadActions update as expected when
   - [x] DSL is updated
   - [x] Query is updated
   - [x] JS Object is updated

EE PR - https://github.com/appsmithorg/appsmith-ee/pull/5642 

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12082854290>
> Commit: 07b68d4f0663ff336807223c93feceb1264741df
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12082854290&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Fri, 29 Nov 2024 11:44:31 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced retrieval of possible entity references and their relationships with a new method.
	- Added new test cases to validate action execution on page load and dynamic binding handling.

- **Bug Fixes**
	- Improved error handling and validation for executable references.
	- Enhanced assertions to ensure correct execution of layout actions.

- **Tests**
	- Added a test to validate layout actions with multiple widgets referencing the same action.
	- Refactored existing tests for better readability and maintainability.
	- Expanded test coverage for layout updates and dynamic binding scenarios.

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java [hunk 1]
```diff
@@ -35,6 +36,8 @@
 @Slf4j
 public class MustacheHelper {
 
+    private static ObservationRegistry observationRegistry;
+
```
[the remark this answers is not in the document]
Comment (sneha122) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java:40]: @rishabhrathod01 Can you please check this comment?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java [hunk 2]
```diff
@@ -71,6 +74,10 @@ public class MustacheHelper {
     public static final int EXECUTABLE_ENTITY_REFERENCES = 0b01;
     public static final int WIDGET_ENTITY_REFERENCES = 0b10;
 
+    public MustacheHelper(ObservationRegistry observationRegistry) {
```
Comment (sneha122) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java:77]: Is this required here? I don't see it being used anywhere in this file

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 3]
```diff
@@ -501,9 +504,18 @@ private Mono<List<Set<DslExecutableDTO>>> filterAndTransformSchedulingOrderToDTO
      * @param evalVersion                       : Depending on the evaluated version, the way the AST parsing logic picks entities in the dynamic binding will change
      * @return A set of any possible reference found in the binding that qualifies as a global entity reference
      */
+    private Mono<Map<String, Set<EntityDependencyNode>>> getPossibleEntityReferencesMap(
+            Mono<Map<String, Executable>> executableNameToExecutableMapMono, List<String> bindings, int evalVersion) {
+        return getPossibleEntityReferencesMap(executableNameToExecutableMapMono, bindings, evalVersion, null)
+                .name(GET_POSSIBLE_ENTITY_REFERENCES)
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:510]: Should we change the trace name here to map instead? GET_POSSIBLE_ENTITY_REFERENCES_MAP as the function name suggests

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 4]
```diff
@@ -526,7 +538,9 @@ private Mono<Set<EntityDependencyNode>> getPossibleEntityReferences(
         final int entityTypes = EXECUTABLE_ENTITY_REFERENCES | WIDGET_ENTITY_REFERENCES;
 
         return executableNameToExecutableMono
-                .zipWith(getPossibleEntityParentsMap(bindings, entityTypes, evalVersion))
+                .zipWith(getPossibleEntityParentsMap(new ArrayList<>(bindings), entityTypes, evalVersion)
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:541]: @rishabhrathod01 Do we need these spans here? Asking because it will be logged multiple times everytime this function is called

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 5]
```diff
@@ -501,9 +504,18 @@ private Mono<List<Set<DslExecutableDTO>>> filterAndTransformSchedulingOrderToDTO
...
+    private Mono<Map<String, Set<EntityDependencyNode>>> getPossibleEntityReferencesMap(
+            Mono<Map<String, Executable>> executableNameToExecutableMapMono, List<String> bindings, int evalVersion) {
+        return getPossibleEntityReferencesMap(executableNameToExecutableMapMono, bindings, evalVersion, null)
+                .name(GET_POSSIBLE_ENTITY_REFERENCES)
+                .tap(Micrometer.observation(observationRegistry));
+    }
+
     private Mono<Set<EntityDependencyNode>> getPossibleEntityReferences(
             Mono<Map<String, Executable>> executableNameToExecutableMapMono, Set<String> bindings, int evalVersion) {
-        return getPossibleEntityReferences(executableNameToExecutableMapMono, bindings, evalVersion, null);
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:506]: Same question here. Do we need these traces to be logged into new relic for production data as these will be logged multiple times, flooding the traces? I was under the impression that we had added these only for the dev environment to debug the problem

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 6]
```diff
@@ -584,6 +598,92 @@ private Mono<Set<EntityDependencyNode>> getPossibleEntityReferences(
                 });
     }
 
+    /**
+     * Similar to the overridden method, this method is used to find all possible global entity references in the given set of bindings.
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:602]: Should we change the comment here to indicate how this method is different from getPossibleEntityReferences?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 4 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:541]: I will remove this. It was kept with the assumption that after this change the call for getPossibleEntityParentsMap will be reduced to 2-3 calls but that is not the case anymore.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 5 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:506]: https://github.com/appsmithorg/appsmith/pull/37127#discussion_r1851456122

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 6 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:602]: Yes, let me modify it.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 7]
```diff
@@ -584,6 +598,92 @@ private Mono<Set<EntityDependencyNode>> getPossibleEntityReferences(
...
+     * However, here we are assuming that the call came from when we were trying to analyze the DSL.
+     * For such cases, we also want to capture entity references that would be qualified to run on page load first.
+     *
+     * @param executableNameToExecutableMono : This map is used to filter only valid executable references in bindings
+     * @param bindings                       : The set of bindings to find references from
+     * @param evalVersion                    : Depending on the evaluated version, the way the AST parsing logic picks entities in the dynamic binding will change
+     * @param bindingsInDsl                  : All references are also added to this set if they should be qualified to run on page load first.
+     * @return A set of any possible reference found in the binding that qualifies as a global entity reference
+     */
+    private Mono<Map<String, Set<EntityDependencyNode>>> getPossibleEntityReferencesMap(
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:612]: @rishabhrathod01 Instead of creating a new method here, can we create a single method that caters to both i.e. when it's a single binding and when it's multiple bindings that we need to evaluate? Asking this because in both methods getPossibleEntityReferencesMap and getPossibleEntityReferences, many code pieces are same and it's a lot of redundant code being repeated, instead if we could combine both these methods, it will be better

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 8]
```diff
@@ -594,10 +694,14 @@ private Mono<Set<EntityDependencyNode>> getPossibleEntityReferences(
...
-        Flux<Tuple2<String, Set<String>>> findingToReferencesFlux =
-                astService.getPossibleReferencesFromDynamicBinding(new ArrayList<>(bindings), evalVersion);
-        return MustacheHelper.getPossibleEntityParentsMap(findingToReferencesFlux, types);
+            List<String> bindings, int types, int evalVersion) {
+        Flux<Tuple2<String, Set<String>>> findingToReferencesFlux = astService
+                .getPossibleReferencesFromDynamicBinding(bindings, evalVersion)
+                .name(GET_POSSIBLE_REFERENCES_FROM_DYNAMIC_BINDING)
+                .tap(Micrometer.observation(observationRegistry));
+        return MustacheHelper.getPossibleEntityParentsMap(findingToReferencesFlux, types)
+                .name(GET_POSSIBLE_ENTITY_PARENTS_MAP)
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:703]: I believe these are also local traces that we don't need to push to production, if that's the case, can we please remove it?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 9]
```diff
@@ -627,31 +731,43 @@ private Mono<Set<ExecutableDependencyEdge>> addDirectlyReferencedExecutablesToGr
...
+        List<String> allBindings = new ArrayList<>();
+
+        widgetDynamicBindingsMap.forEach((widgetName, bindingsInWidget) -> {
+            EntityDependencyNode widgetDependencyNode =
+                    new EntityDependencyNode(EntityReferenceType.WIDGET, widgetName, widgetName, null, null);
+
+            bindingsInWidget.forEach(binding -> {
+                bindingToWidgetNodesMap
+                        .computeIfAbsent(binding, k -> new HashSet<>())
+                        .add(widgetDependencyNode);
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:745]: Why is this a one to many mapping that we have created here for widgetName and widgetDependencyNode? In the old code, I see that widgetDependency node is created for each widgetName i.e. widgetProperty and not for each binding in that widget. Can you please give an example of this scenario?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 10]
```diff
@@ -931,6 +1047,8 @@ private Mono<Set<ExecutableDependencyEdge>> recursivelyAddExecutablesAndTheirDep
         // First fetch all the executables in the page whose name matches the words found in all the dynamic bindings
         Mono<List<EntityDependencyNode>> findAndAddExecutablesInBindingsMono = getPossibleEntityReferences(
                         executableNameToExecutableMapMono, dynamicBindings, evalVersion)
+                .name(GET_POSSIBLE_ENTITY_REFERENCES)
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:1050]: Please check if this trace is required here or not

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java [hunk 11]
```diff
@@ -127,7 +129,10 @@ public Flux<Tuple2<String, Set<String>>> getPossibleReferencesFromDynamicBinding
                     long currentIndex = tuple2.getT1();
                     Set<String> references = tuple2.getT2().getReferences();
                     return Mono.zip(Mono.just(bindingValues.get((int) currentIndex)), Mono.just(references));
-                });
+                })
+                .name("appsmith.rts.multiple-script-data")
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java:133]: Is this trace required to be pushed to production? If not, let' remove it

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java [hunk 12]
```diff
@@ -926,4 +928,120 @@ public void testDeleteActionCollection_afterApplicationPublish_clearsActionColle
...
+
+        // Create Js object
+        ActionCollectionDTO createdActionCollectionDTO =
+                layoutCollectionService.createCollection(actionCollectionDTO).block();
+        assert createdActionCollectionDTO != null;
+        assert createdActionCollectionDTO.getId() != null;
+        String createdActionCollectionId = createdActionCollectionDTO.getId();
+
+        // Update JS object body to simulate action collection
+        actionCollectionDTO.getActions().stream()
```
Comment (sneha122) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java:1011]: Is this needed in the test case? As we already have the same body in action when it was created, we are not updating anything in the action body here

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java [hunk 13]
```diff
@@ -926,4 +928,120 @@ public void testDeleteActionCollection_afterApplicationPublish_clearsActionColle
             assertEquals(expectedMessage, error.getMessage());
         });
     }
+
+    @Test
+    @WithUserDetails(value = "api_user")
+    public void testLayoutOnLoadActions_withTwoWidgetsAndSameBinding_callsCorrectActions() {
```
Comment (sneha122) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java:934]: Can we modify this test case to have two bindings in two widgets? table and text can have bindings of myFunction.data + testAction2.data, this will cover even multiple bindings scenario for us

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java (hunk 11 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java:133]: This was a miss. I will remove it.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java (hunk 12 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java:1011]: Yes, this is not required. I will remove it.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 10 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:1020]: removed

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 14]
```diff
@@ -627,31 +731,43 @@ private Mono<Set<ExecutableDependencyEdge>> addDirectlyReferencedExecutablesToGr
...
+        Map<String, Set<EntityDependencyNode>> bindingToWidgetNodesMap = new HashMap<>();
+        List<String> allBindings = new ArrayList<>();
+
+        widgetDynamicBindingsMap.forEach((widgetName, bindingsInWidget) -> {
+            EntityDependencyNode widgetDependencyNode =
+                    new EntityDependencyNode(EntityReferenceType.WIDGET, widgetName, widgetName, null, null);
+
+            bindingsInWidget.forEach(binding -> {
+                bindingToWidgetNodesMap
+                        .computeIfAbsent(binding, k -> new HashSet<>())
```
[the remark this answers is not in the document]
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:714]: done

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 8 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:673]: removed

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 7 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:582]: @sneha122 return types of both the methods are different and changing the return type would also mean changing the code where the  `getPossibleEntityReferences` was consumed. I wanted to avoid that. I can move the common code to another function.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java (hunk 13 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java:934]: Sure

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 3 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java]: removed the trace as it is not required.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 9 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:653]: We are sending all the bindings now instead of for each property path. We need to store each binding relation with the widgetDependencyNode.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java [hunk 15]
```diff
@@ -71,6 +71,8 @@ public class MustacheHelper {
     public static final int EXECUTABLE_ENTITY_REFERENCES = 0b01;
     public static final int WIDGET_ENTITY_REFERENCES = 0b10;
 
+    public MustacheHelper() {}
```
Comment (rishabhrathod01) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java:74]: remove this code

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 16]
```diff
@@ -491,16 +491,6 @@ private Mono<List<Set<DslExecutableDTO>>> filterAndTransformSchedulingOrderToDTO
...
-    /**
-     * This method is used to find all possible global entity references in the given set of bindings.
-     * We'll be able to find valid executable references only at this point. For widgets, we just assume that all
-     * references are possible candidates
-     *
-     * @param executableNameToExecutableMapMono : This map is used to filter only valid executable references in bindings
-     * @param bindings                          : The set of bindings to find references from
-     * @param evalVersion                       : Depending on the evaluated version, the way the AST parsing logic picks entities in the dynamic binding will change
-     * @return A set of any possible reference found in the binding that qualifies as a global entity reference
-     */
```
Comment (rishabhrathod01) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:503]: Add comment to explain what the method does.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 17]
```diff
@@ -533,55 +545,55 @@ private Mono<Set<EntityDependencyNode>> getPossibleEntityReferences(
...
-                            } else {
-                                // If the reference node was identified as a widget, directly add it as a possible
-                                // reference
-                                // Because we are not doing any validations for widget references at this point
-                                if (EntityReferenceType.WIDGET.equals(binding.getEntityReferenceType())) {
-                                    possibleEntitiesReferences.add(binding);
-                                }
-                            }
-                        });
+    private <T> T processBindingToParentMap(
```
Comment (rishabhrathod01) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:557]: Add comment to explain what processBindingToParentMap does

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java [hunk 18]
```diff
@@ -926,4 +928,109 @@ public void testDeleteActionCollection_afterApplicationPublish_clearsActionColle
...
+        JSONObject textDsl = new JSONObject();
+        textDsl.put("widgetName", "Text1");
+        textDsl.put("type", "TEXT_WIDGET");
+        textDsl.put("text", "{{testCollection1.myFunction.data}} + {{testCollection1.myFunction2.data}}");
+        JSONArray textDslTemp2 = new JSONArray();
+        textDslTemp2.add(new JSONObject(Map.of("key", "text")));
+        textDsl.put("dynamicBindingPathList", textDslTemp2);
+        JSONArray textDslTemp3 = new JSONArray();
+        textDslTemp3.add(new JSONObject(Map.of("key", "text")));
+        textDsl.put("dynamicPropertyPathList", textDslTemp3);
```
Comment (rishabhrathod01) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java:986]: Reduce the code redundancy here

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 19]
```diff
@@ -525,6 +515,28 @@ private Mono<Set<EntityDependencyNode>> getPossibleEntityReferences(
         // We want to be finding both type of references
         final int entityTypes = EXECUTABLE_ENTITY_REFERENCES | WIDGET_ENTITY_REFERENCES;
 
+        return executableNameToExecutableMono
+                .zipWith(getPossibleEntityParentsMap(new ArrayList<>(bindings), entityTypes, evalVersion))
+                .map(tuple -> {
+                    Map<String, Executable> executableMap = tuple.getT1();
+                    Map<String, Set<EntityDependencyNode>> bindingToPossibleParentMap = tuple.getT2();
+                    return processBindingToParentMap(
```
Comment (sneha122) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:523]: @rishabhrathod01 How are we sending the type here which processBindingToParentMap expects?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:557]: @sneha122 could you elaborate? types are inferred here.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java (hunk 19 above)
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:523]: the type is inferred from the `aggregateToSet` value inside the processBindingToParentMap  method.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 20]
```diff
@@ -533,55 +555,68 @@ private Mono<Set<EntityDependencyNode>> getPossibleEntityReferences(
...
+     * - the parent is added to the set of possibleEntitiesReferencesToBindingMap with the binding as the key
+     *
+     * @param bindingToPossibleParentMap
+     * @param executableMap
+     * @param bindingsInDsl
+     * @param aggregateToSet
+     * @param <T>
+     * @return
+     */
+    private <T> T processBindingToParentMap(
```
Comment (rishabhrathod01) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:580]: @NilanshBansal we would like your review of this method definition. Mainly for the usage of generics here.

Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:580]: @rishabhrathod01 I don't see a very solid use case of implementing generics here as we already have information about when to return a `Map` and when to return a `Set` from this function based on the `aggregateToSet` parameter.
In this case, can we please split the code into two functions and add a parent method if there is any common code. 
The two new functions can be:
```
private Set<EntityDependencyNode> processBindingToParentSet(
        Map<String, Set<EntityDependencyNode>> bindingToPossibleParentMap,
        Map<String, Executable> executableMap,
        Set<EntityDependencyNode> bindingsInDsl) {} 
```
and 
```
private Map<String, Set<EntityDependencyNode>> processBindingToParentMap(
        Map<String, Set<EntityDependencyNode>> bindingToPossibleParentMap,
        Map<String, Executable> executableMap,
        Set<EntityDependencyNode> bindingsInDsl) {}
```

By dividing the code into two different methods, we have the following advantages as opposed to using generics here:
- Enhanced code readability and clarity 
- Defined return type
- More scalable as newer code can be added to different functions easily

cc: @sneha122

File: app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java [hunk 21]
```diff
@@ -627,31 +699,43 @@ private Mono<Set<ExecutableDependencyEdge>> addDirectlyReferencedExecutablesToGr
...
+                    Set<EntityDependencyNode> widgetDependencyNodes =
+                            bindingToWidgetNodesMap.getOrDefault(binding, Set.of());
+
+                    // Process each possibleEntity for the current binding
+                    return Flux.fromIterable(possibleEntities).flatMap(possibleEntity -> Flux.fromIterable(
+                                    widgetDependencyNodes) // Iterate all associated widgets
+                            .flatMap(widgetDependencyNode -> {
                                 if (getExecutableTypes().contains(possibleEntity.getEntityReferenceType())) {
                                     edgesRef.add(new ExecutableDependencyEdge(possibleEntity, widgetDependencyNode));
-                                    // This executable is directly referenced in the DSL. This executable is an ideal
```
[the remark this answers is not in the document]
Comment (rishabhrathod01) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java:651]: added the comment back it was a miss.

**Review by sneha122 — APPROVED** [review]
