### PR TITLE
fix: Add support to generate ssh keys of type RSA

### LINKED ISSUE #13353: [Bug]-[656]:Unable to connect apps to azure devops
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to connect apps to azure devops 
image

### Steps To Reproduce

1. add new app
2. Click on connect git 
3. add a remote url 
4. now try to add ssh in the azure devops 
5. the error is displayed as in the attached screenshot

### Public Sample App

_No response_

### Version

production

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> Unable to connect apps to azure devops as we do not support generating keys based on RSA algorithm. This PR adds support for the same. Now the user can choose the key type while regenerating the keys.

Fixes #13353

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally
- Unit Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AnaghHegde** [comment]
Tests are on the way

File: app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+
+import lombok.Getter;
+import lombok.Setter;
+
+@Getter
+@Setter
+public class GitDeployKeyDTO {
+    String protocolName;
+
+    String platFormSupported;
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java:11]:
```suggestion
    String platformSupported;
```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCE.java [hunk 2]
```diff
@@ -45,7 +45,7 @@ public interface ApplicationServiceCE extends CrudService<Application, String> {
 
     Mono<Application> setTransientFields(Application application);
 
-    Mono<GitAuth> createOrUpdateSshKeyPair(String applicationId);
+    Mono<GitAuth> createOrUpdateSshKeyPair(String applicationId, String keyType);
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCE.java:48]: Should we share the supported keys array in the response itself so as to avoid another API call?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitDeployKeyGenerator.java [hunk 3]
```diff
@@ -3,24 +3,59 @@
...
         KeyPair kpair;
+        int key;
+        int keySize;
+        if(StringUtils.isEmpty(keyType)) {
+            key = KeyPair.ECDSA;
+            keySize = supportedProtocols.ECDSA.key_size;
+        } else {
+            key = KeyPair.RSA;
+            keySize = supportedProtocols.RSA.key_size;
+        }
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitDeployKeyGenerator.java:55]: Please invert the condition so that, we will generate RSA key only when requested for other scenarios we will always generate the key with ECDSA.

**Review by abhvsn — CHANGES_REQUESTED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCE.java (hunk 2 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCE.java:48]: Are you referring to get SSH Key response? I guess we can do that.

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCE.java:48]: Yes

File: app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java (hunk 1 above)
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java:11]: Should it be List<String> as many platforms can support particular protocol along with the size

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java:11]: I was thinking of keeping it as a comma separated value.

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitDeployKeyDTO.java:11]: I think keeping this as a List will give more flexibility on client-side.

**Review by abhvsn — APPROVED** [review]
LGTM
Just a minor comment

**Comment by AnaghHegde** [comment]
Let's not merge this change as it is a breaking change. Once the client  changes are in we can merge this to release.

**Comment by IAmAnubhavSaini** [comment]
@AnaghHegde What are the breaking changes? Are we not defaulting to earlier keyType?

**Review by abhvsn — DISMISSED** [review]

**Review by abhvsn — APPROVED** [review]
