### PR TITLE
fix: Skip create application when root application is present

### LINKED ISSUE #24614: [Bug]: "Null" application in workspace
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A null application was created in my workspace. The application literally shows "null" as the name, but I didn't create it. However, the audit logs say It was created by my account. 

### Steps To Reproduce

...

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud & Self - Hosted > 1.9.19

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
During git checkout to a remote branch, if the underlying application is present in DB, the operation creates an extra application with name "null". This PR fixes the issue.

#### PR fixes following issue(s)
Fixes #24614

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 1]
```diff
@@ -1455,24 +1455,34 @@ private Mono<Application> checkoutRemoteBranch(String defaultApplicationId, Stri
...
-                    srcApplication.setPublishedPages(null);
-                    srcApplication.setGitApplicationMetadata(srcBranchGitData);
-                    srcApplication.setEditModeThemeId(null);
-                    srcApplication.setPublishedModeThemeId(null);
+                    if (branchName.equals(srcBranchGitData.getBranchName())) {
+                        /*
+                         in this case, user deleted the initial default branch and now wants to check out to that branch.
+                         as we didn't delete the application object but only the branch from git repo,
+                         we can just use this existing application without creating a new one.
+                        */
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1467]: Are we sure that this condition is valid for all the cases? For example - If i change default branch from master --> dev --> feature, then i delete dev branch. In this case the `dev` branch resources are soft deleted. Then this condition does not hold good right?

**Review by AnaghHegde — COMMENTED** [review]
Minor comment, rest looks good to me.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 1 above)
Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1467]: Yeah, you're right on this. This will only happen if you've deleted the initial branch and trying to checkout to that branch again.

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1467]: In that case, can we modify the if condition to reflect this scenario?

Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1467]: Sorry, didn't get it. This condition will only be true if you are checking out to the initial branch i.e. the application that has `id=defaultApplicationId`. The scenario you mentioned - in that case the `srcApplication` will have `branchname=master` and it'll never change. The condition will only be true if you've changed the default branch from master to something else and then trying to checkout to `origin/master`.

**Comment by Parthvi12** [comment]
Verified the issue and it works fine now.

**Review by Parthvi12 — APPROVED** [review]
