### PR TITLE
fix: trigger fields linting issue

### LINKED ISSUE #11943: [Bug]-[24000]:JSObejct/Query/API shows as "not defined"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After reloading an application, the connected data source shows as "not defined" in the code editor.
Screenshot 2022-03-17 at 6 17 25 PM

### Steps To Reproduce

1. Create a new JSObject or Query or API
2. Bind the created object to a button or any widget
3. Turn on the JS editable option if you bound the query to the widget using action selector UI
4. Refresh the page and check the same code where you bound the query and widget to see the error

### Public Sample App

https://app.appsmith.com/applications/6233205d0c166d1757961b3f/pages/6233205d0c166d1757961b42

### Version

Cloud v1.6.16 (released on 17th March 2022)

### PR DESCRIPTION
**Pull request by eco-monk**
Fixes #11943

## Description
- DataTreeEvaluator - Include trigger fields(onClick etc...) in dependency map to keep them in sync with linting. #10941

- Added `loadingProperties` in table widget config (can be configured for other widgets in future)
  - this is a list of regex that is used to determine, which properties of a widget can trigger it's loading state
  - when undefined, any path bound to a API/Query can trigger the loadingState (same as existing behaviour)

- [performance logs](https://github.com/appsmithorg/appsmith/pull/11875/commits/63acf2ba421d18069cf00e409b17f6ac1972bf7d) checked with A-force app (current branch vs release)
  - increase in time per update, ranged between 30ms - 70ms 

## Notes
Brings back changes from #10941
Which was reverted (here #11163) to address #11136

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Create a button and an API.
- Bind `{{Api1.run()}}` to onClick event of the button.
- Refresh the page and notice `Api1 is undefined` error doesn't show up anymore.
- Delete `Api1` and notice the error is shown on onClick field.
- Create `Api1` again and notice the error goes away.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/onclick-linting-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.67 **(0)** | 37.07 **(0.02)** | 35.26 **(0)** | 55.93 **(0)**
 :red_circle: | app/client/src/utils/WidgetFactory.tsx | 74.49 **(0.02)** | 73.68 **(1.46)** | 61.11 **(-3.6)** | 74.49 **(0.02)**
 :green_circle: | app/client/src/utils/WidgetLoadingStateUtils.ts | 96.83 **(0.16)** | 92 **(2)** | 100 **(0)** | 98.08 **(0.12)**
 :red_circle: | app/client/src/widgets/BaseWidget.tsx | 79.07 **(-0.46)** | 44.44 **(0)** | 73.53 **(-2.23)** | 78.23 **(-0.46)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 30.07 **(0.33)** | 9.43 **(0)** | 30.19 **(1.34)** | 29.77 **(0.37)**
 :red_circle: | app/client/src/workers/DataTreeEvaluator.ts | 75.93 **(-0.4)** | 57.47 **(-0.2)** | 73.86 **(-0.85)** | 75.5 **(-0.55)**</details>

### CODE REVIEW

File: app/client/src/widgets/BaseWidget.tsx [hunk 1]
```diff
@@ -75,6 +75,10 @@ abstract class BaseWidget<
     return {};
   }
 
+  static getLoadingProperties(): Array<RegExp> | undefined {
```
Comment (sbalaji1192) [inline app/client/src/widgets/BaseWidget.tsx:78]: Could you add comment about the purpose of this `getLoadingProperties` ?

File: app/client/src/utils/WidgetLoadingStateUtils.test.ts [hunk 2]
```diff
@@ -116,6 +164,22 @@ describe("Widget loading state utils", () => {
...
 
+    beforeAll(() => {
+      // mock WidgetFactory.getLoadingProperties
+      const loadingPropertiesMap = new Map<string, RegExp[]>();
+      loadingPropertiesMap.set("TABLE_WIDGET", [/.tableData$/]);
+
+      jest
+        .spyOn(WidgetFactory, "getLoadingProperties")
+        .mockImplementation((widgetType) =>
+          loadingPropertiesMap.get(widgetType),
```
Comment (sbalaji1192) [inline app/client/src/utils/WidgetLoadingStateUtils.test.ts:175]: can we simply return `[/.tableData$/]` ?

**Review by sbalaji1192 — COMMENTED** [review]
@riodeuno Could you have a look once?

File: app/client/src/widgets/TableWidget/widget/index.tsx [hunk 3]
```diff
@@ -109,6 +109,10 @@ class TableWidget extends BaseWidget<TableWidgetProps, WidgetState> {
     };
   }
 
+  static getLoadingProperties(): Array<RegExp> | undefined {
+    return [/.tableData$/];
```
[the remark this answers is not in the document]
Comment (eco-monk) [reply app/client/src/widgets/TableWidget/widget/index.tsx:113]: Discussing in the above thread.

File: app/client/src/utils/WidgetLoadingStateUtils.test.ts (hunk 2 above)
Comment (eco-monk) [reply app/client/src/utils/WidgetLoadingStateUtils.test.ts:175]: This has to be returned only when called for a TABLE_WIDGET. 
Other test cases (e.g. SELECT_WIDGET cases) would fail, if we return tableData by default

Comment (sbalaji1192) [reply app/client/src/utils/WidgetLoadingStateUtils.test.ts:175]: oh yeah.  you're correct.

File: app/client/src/widgets/BaseWidget.tsx (hunk 1 above)
Comment (eco-monk) [reply app/client/src/widgets/BaseWidget.tsx:88]: @sbalaji1192 
updated with comments, please check if it is appropriate.

File: app/client/src/workers/DataTreeEvaluator.ts [hunk 4]
```diff
@@ -519,12 +519,22 @@ export default class DataTreeEvaluator {
...
       // Adding the dynamic triggers in the dependency list as they need linting whenever updated
-      // we don't make it dependent on anything else
-      if (entity.dynamicTriggerPathList) {
-        Object.values(entity.dynamicTriggerPathList).forEach(({ key }) => {
-          dependencies[`${entityName}.${key}`] = [];
+      // To keep linting in trigger fields in sync, nodes they depend on need to be added to their dependencies
+      const dynamicTriggerPathlist = entity.dynamicTriggerPathList;
+
+      if (dynamicTriggerPathlist && dynamicTriggerPathlist.length) {
+        dynamicTriggerPathlist.forEach((dynamicPath) => {
```
Comment (ohansFavour) [inline app/client/src/workers/DataTreeEvaluator.ts:526]: This logic (lines 525 - 534) seems to be repeated in two other places (see 569 - 580 and 584-599). can we compose this into a helper function?  and add a test?

**Review by ohansFavour — CHANGES_REQUESTED** [review]

**Review by sbalaji1192 — APPROVED** [review]

**Review by ohansFavour — APPROVED** [review]

File: app/client/src/workers/DataTreeEvaluator.ts (hunk 4 above)
Comment (eco-monk) [reply app/client/src/workers/DataTreeEvaluator.ts:526]: Discussed, the functions behave slightly differently.
