### PR TITLE
fix: added regex 

### LINKED ISSUE #19881: [Feature]: Add support for the custom ssh URL that does not begin with git@
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Why should this be worked on?

A self hosted or a private github organization can have ssh urls that does not begin with the keyword `git`. Hence such urls are not supported with Appsmith. We should support such use cases. 

Link to conversation - https://theappsmith.slack.com/archives/C0341RERY4R/p1674049012093039?thread_ts=1673636062.767679&cid=C0341RERY4R

Front logo [Front conversations](https://app.frontapp.com/open/top_6vccs)

### PR DESCRIPTION
**Pull request by sondermanish**
Fixes #19881
## Automation

/ok-to-test tags="@tag.Git"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9090239144>
> Commit: 05f2b6f8e6bbbbd6f05e70d9fa9194a07c89d86d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9090239144&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java [hunk 1]
```diff
@@ -26,6 +26,9 @@ public class GitUtils {
     public static final Pattern URL_PATTERN_WITHOUT_SCHEME =
             Pattern.compile("^git@(?<host>.+?):/*(?<path>.+?)(\\.git)?$");
 
+    public static final Pattern URL_PATTERN_WITHOUT_GIT_PREFIX =
+            Pattern.compile("^[a-zA-Z0-9]+@(?<host>.+?):/*(?<path>.+?)(\\.git)?$");
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java:30]: What if they use ssh prefix with custom username?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java [hunk 2]
```diff
@@ -26,6 +26,9 @@ public class GitUtils {
     public static final Pattern URL_PATTERN_WITHOUT_SCHEME =
             Pattern.compile("^git@(?<host>.+?):/*(?<path>.+?)(\\.git)?$");
 
+    public static final Pattern URL_PATTERN_WITHOUT_GIT_PREFIX =
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java:29]: Nit, can we rename this to indicate exactly what we're accepting here, that is, custom username.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java [hunk 3]
```diff
@@ -60,6 +60,10 @@ public void convertSshUrlToBrowserSupportedUrl() {
         assertThat(GitUtils.convertSshUrlToBrowserSupportedUrl(
                         "ssh://git@tim.tam.example.com:9876/v3/sladeping/pyhe/SpaceJunk"))
                 .isEqualTo("https://tim.tam.example.com/v3/sladeping/pyhe/SpaceJunk");
+
+        // custom ssh username:
+        assertThat(GitUtils.convertSshUrlToBrowserSupportedUrl("custom@vs-ssh.visualstudio.com:v3/newJet/ai/zilla"))
+                .isEqualTo("https://vs-ssh.visualstudio.com/v3/newJet/ai/zilla");
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java:66]: There should be another check somewhere for repo names. Does that pattern comply with this input already? If it does, can you add a test case there as well to make sure that it does not break in the future?

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Needs a few more inclusions.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java (hunk 3 above)
Comment (sondermanish) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java:66]: it does comply, adding test cases

**Review by nidhi-nair — APPROVED** [review]
