### PR TITLE
fix: Added iFrame to load Base64 PDF data in document viewer widget

### LINKED ISSUE #10756: [Bug]: Unable to view pdf document on Document viewer widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we map a filepicker widget to document viewer widget to display the .pdf document, it says "The content is blocked.Contact the site owner to fix the issue."

Sharing video:
[LOOM DEMO](https://www.loom.com/share/7ac19196d6fb4507a0381cb58ee2c6bd)

### Steps To Reproduce

1. Add Document viewer widget
2. Add File Picker widget and bind it with Document viewer {{FilePicker1.files[0].data}}
3. Upload .pdf file using file picker to display file on Document viewer
4. Observe the error on Document viewer widget

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

Added Iframe for load Base64 PDF in document viewer widget

Fixes #10756 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/pdf-document-viewer 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55 **(0)** | 36.49 **(0.01)** | 34.71 **(0)** | 55.4 **(0)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/DocumentViewerWidget/component/index.tsx | 41.53 **(1.16)** | 40.82 **(-4.83)** | 16.67 **(0)** | 43.27 **(1.16)**</details>

### CODE REVIEW

File: app/client/src/widgets/DocumentViewerWidget/component/index.tsx [hunk 1]
```diff
@@ -172,7 +174,13 @@ export const getDocViewerConfigs = (docUrl: string): ConfigResponse => {
   const { extension, hasExtension, validExtension } = checkUrlExtension(url);
   if (hasExtension) {
     if (validExtension) {
-      if (!(extension === "txt" || extension === "pdf")) {
+      if (extension === "pdf") {
```
Comment (sbalaji1192) [inline app/client/src/widgets/DocumentViewerWidget/component/index.tsx:177]: make this a switch case and move `renderer = Renderers.DOCUMENT_VIEWER;` outside the switch case.

File: app/client/src/widgets/DocumentViewerWidget/component/index.tsx [hunk 2]
```diff
@@ -206,6 +214,18 @@ function DocumentViewerComponent(props: DocumentViewerComponentProps) {
...
+            frameBorder="0"
+            height="100%"
+            id="pdfiframe"
+            src={url}
+            title="pdfiframe"
+            width="100%"
+          />
+        );
+      }
       return <DocumentViewer url={url} viewer={viewer} />;
```
Comment (sbalaji1192) [inline app/client/src/widgets/DocumentViewerWidget/component/index.tsx:229]: enclose this on a else {}

**Review by sbalaji1192 — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this PR and it is working fine
