### PR TITLE
Fix spacing of fields in org settings: fixes (#3612)

### LINKED ISSUE #3612: [Bug] Mis-Alignment of Organisation Logo
Steps to reproduce:
1) Navigate to organisation setting 
2) Observe the logo section

Screenshot 2021-03-18 at 4 35 48 PM

### PR DESCRIPTION
**Pull request by kaushik94**
## Description
Fixes the misalignment of fields in organisation settings.

Fixes #3612 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Go to Org settings and check that the css for fields has "display: flex"

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by rishabhsaxena — DISMISSED** [review]
@kaushik94 Minor change: though the spacing looks consistent, we have increased the spacings from what they were before, think we should keep the original spacing here

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/OrgSettings_validation_spec.js [hunk 1]
```diff
@@ -23,6 +23,26 @@ describe("Org Settings validation spec", function() {
...
+      // checking parent's(<a></a>) since the child(<span>) inherits css from it
+      cy.get(".react-tabs li")
+        .first()
+        .click({ force: true });
+      cy.get(homePage.orgSettingsFilePickerCol).should(
+        "have.css",
+        "display",
+        "flex",
+      );
+    });
```
Comment (hetunandu) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/OrgSettings_validation_spec.js:45]: Let's avoid doing a cypress test for style checks. Instead, do a jest test

File: app/client/src/pages/organization/General.tsx [hunk 2]
```diff
@@ -54,6 +54,15 @@ const FilePickerLoader = styled.div`
   border-radius: 0;
 `;
 
+// testing
+export const Row = styled.div`
+  display: flex;
+`;
+
+export const Col = styled.div`
+  margin-right: -3em;
```
Comment (kaushik94) [inline app/client/src/pages/organization/General.tsx:63]: @hetunandu please check if this line is ok.

Comment (hetunandu) [inline app/client/src/pages/organization/General.tsx:63]: Instead of minus margins, we should see which child component adds some margin/padding you are trying to negate and then handle that there. As a rule, I like to make each component's padding and margin be zero, and the container rendering the component should instead place it where it wants to. That ensures some separation of concerns in styling components.

File: app/client/src/components/ads/FilePicker.tsx [hunk 3]
```diff
@@ -196,6 +196,8 @@ const FilePickerComponent = (props: FilePickerProps) => {
       const files = monitor.getItem().files;
       if (files) {
         handleFileUpload(files);
+      } else {
+        return;
```
Comment (hetunandu) [inline app/client/src/components/ads/FilePicker.tsx:200]:
```suggestion
      if (!files) {
        return;
      }
      handleFileUpload(files);
```

File: app/client/src/components/ads/FilePicker.tsx [hunk 4]
```diff
@@ -224,6 +226,8 @@ const FilePickerComponent = (props: FilePickerProps) => {
     if (file) {
       fileSize = Math.floor(file.size / 1024);
       setFileInfo({ name: file.name, size: fileSize });
+    } else {
+      return;
```
Comment (hetunandu) [inline app/client/src/components/ads/FilePicker.tsx:230]:
```suggestion
    if (!file) {
      return
    }
    fileSize = Math.floor(file.size / 1024);
    setFileInfo({ name: file.name, size: fileSize });
```

**Review by hetunandu — CHANGES_REQUESTED** [review]
Minor refacor suggestions

File: app/client/src/pages/Applications/__tests__/OrganizationSettingsForm.test.tsx [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+describe("Applications", () => {
+  beforeEach(async () => {
+    // setup a DOM element as a render target
+    container = document.createElement("div");
+    document.body.appendChild(container);
+  });
+  it("checks that organization settings have correct styling", async (done) => {
+    const { getByText } = render(<GeneralSettings />);
+
+    const orgNameField = await getByText("Organization Name");
```
Comment (rishabhsaxena) [inline app/client/src/pages/Applications/__tests__/OrganizationSettingsForm.test.tsx:17]: NIT: think `getByText` is a sync method, `findBy` queries are async

File: app/client/src/pages/Applications/__tests__/OrganizationSettingsForm.test.tsx [hunk 6]
```diff
@@ -0,0 +1,28 @@
+import React from "react";
+import { unmountComponentAtNode } from "react-dom";
+import { render } from "test/testUtils";
+import "@testing-library/jest-dom";
+import { GeneralSettings } from "../../organization/General";
+
+let container: any = null;
+describe("Applications", () => {
```
Comment (rishabhsaxena) [inline app/client/src/pages/Applications/__tests__/OrganizationSettingsForm.test.tsx:8]: NIT: Should update the desc to `Application Settings`?

**Review by rishabhsaxena — COMMENTED** [review]
Couple of nitpicks

**Comment by rishabhsaxena** [comment]
IMHO not sure if this test helps us a lot. What do you guys think about jest snapshots with jest-styled-components 
as a practise. We could merge this and take it separately.

 @kaushik94 @hetunandu

**Comment by hetunandu** [comment]
> IMHO not sure if this test helps us a lot. What do you guys think about jest snapshots with jest-styled-components
> as a practise. We could merge this and take it separately.
> 
> @kaushik94 @hetunandu

Makes sense. Lets start snapshot testing

**Comment by kaushik94** [comment]
@hetunandu @rishabhsaxena Snapshoting sounds good to me.

**Review by hetunandu — DISMISSED** [review]

**Review by hetunandu — APPROVED** [review]

**Comment by kaushik94** [comment]
@hetunandu @rishabhsaxena merging this. Thanks.
