### PR TITLE
fix: updated logic to retain the files on page change

### LINKED ISSUE #11660: [Bug]-[800]:Filepicker doesn't show files in it's pop-up when the user goes to a query page and comes back
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i upload a file in filepicker and go to the query/api page and come back, I can see the number of files uploaded in the button but don't see the files in the pop-up. 

Either reset the filepicker or show the files uploaded, the current state is weird.

### Steps To Reproduce

1. Upload a file to filepicker
2. Navigate to query page
3. Come back to the widget
4. Open the pop-up
5. See that the file is not shown 

Loom -
[LOOM DEMO](https://www.loom.com/share/48f6107d76f7445c938bef1ecf0509e2)

### Environment

Production

### Version

Cloud

### LINKED ISSUE #15002: [Bug]: Filepicker not retaining the data when i move to a query page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i upload a file to filepicker and bind a data to query, i am unable to see the uploaded file values

### Steps To Reproduce

1. Add a new filepicker widget
2. Upload a file
3. Change page to a query page
4. Reference filepicker.files[0]
5. Observe that the reference shows undefined

### Public Sample App

_No response_

### Version

Production

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

**PR Changes context:**
- To retain the files when the user returns to the canvas from query page or any page, we initialize the uppy's instance with the files that are present in the `selectedFiles` meta property. 
- During this process, we also add a flag inside the file's meta called: `isInitializing`. This helps us to prevent adding same files with different `file.id`. Note: during initialization `addFile` function will generate a different `file.id` for the files present in the `selectedFiles` meta property.
- We initialze the files returned by the `getFiles` function whenever a file is removed by a user.

Fixes #15002
Fixes #11660

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Updated the cypress test: `FilePickerV2_spec.js` to check the following scenario:
* Upload a file to the file picker.
* Check if the uploaded file's name reflects in the text widget.
* Goes to the query page, and checks if the binding `{{FilePicker1.files}}` evaluates to the file picker's file content. Here we check if the file name appears in the Evaluation pop-up.
* Goes back to the canvas, checks if the uploaded file is retained by checking if the file picker button contains: `1 files selected`.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 1]
```diff
@@ -611,22 +836,36 @@ class FilePickerWidget extends BaseWidget<
...
-        updatedFiles = [];
+        const fileCount = this.props.selectedFiles?.length || 0;
+
+        /**
+         * Once the file is removed we update the selectedFiles
+         * with the current files present in the uppy's internal state
+         */
+        const updatedFiles = this.state.uppy
+          .getFiles()
+          .map((currentFile: any, index: number) => ({
```
Comment (ashit-rath) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:848]: Try to use appropriate typings instead of `any`.

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 2]
```diff
@@ -611,22 +836,36 @@ class FilePickerWidget extends BaseWidget<
...
        * Refer to the following issue to know about reason prop: https://github.com/transloadit/uppy/pull/2323
        */
-      let updatedFiles = [];
       if (reason === "removed-by-user") {
-        updatedFiles = this.props.selectedFiles
-          ? this.props.selectedFiles.filter((dslFile) => {
-              return file.id !== dslFile.id;
-            })
-          : [];
-      } else if (reason === "cancel-all") {
```
Comment (ashit-rath) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:621]: Don't we need the "cancell-all" event for reset?

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 3]
```diff
@@ -746,6 +994,22 @@ class FilePickerWidget extends BaseWidget<
...
+        this.state.uppy.addFile({
+          name: fileItem.name,
+          type: fileItem.type,
+          data: new Blob([fileItem.data]),
+          meta: {
+            // Adding this flag to distinguish a file in the files-added event
+            isInitializing: true,
+          },
+        });
+      });
```
Comment (ashit-rath) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:1012]: Put this block in a function.

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 4]
```diff
@@ -611,22 +836,36 @@ class FilePickerWidget extends BaseWidget<
...
-          : [];
-      } else if (reason === "cancel-all") {
-        updatedFiles = [];
+        const fileCount = this.props.selectedFiles?.length || 0;
+
+        /**
+         * Once the file is removed we update the selectedFiles
+         * with the current files present in the uppy's internal state
+         */
+        const updatedFiles = this.state.uppy
```
Comment (ashit-rath) [inline app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:846]: What happens when a user intentionally removes a file present in the uppy's modal?

**Review by ashit-rath — COMMENTED** [review]
Good PR description!

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx [hunk 5]
```diff
@@ -211,6 +212,230 @@ class FilePickerWidget extends BaseWidget<
...
+            isJSConvertible: true,
+            isBindProperty: true,
+            isTriggerProperty: false,
+            validation: { type: ValidationTypes.TEXT },
+          },
+        ],
+      },
+    ];
+  }
+
```
[the remark this answers is not in the document]
Comment (keyurparalkar) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:438]: Merged the latest release. Removed the `propertyPaneConfig`

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx (hunk 4 above)
Comment (keyurparalkar) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:846]: If a user intentionally removes the file from the modal then the following will occur:

- `file-removed` event will be emitted along with a reason argument. Reason will be `removed-by-user`.
- Once the file is removed from the uppy's instance, we get the current files present in uppy's instance with `getFiles`
- Finally, we update `selectedFiles` with updatedFiles

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx (hunk 2 above)
Comment (keyurparalkar) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:621]: `cancel-all` will get called by uppy and it will reset the uppy's instance. We don't need to do anything at this event from our end. 
Here on `cancel-all` we set the `selectedFiles` to `[]` which led to files not getting retained when coming back to the canvas from query page

File: app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx (hunk 4 above)
Comment (ashit-rath) [reply app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx:623]: Got it! Very well explained!
Now I notice the comment you added 😅

**Review by ashit-rath — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and working as expected.
This PR fixes:
 #15002
#11660

**Review by ashit-rath — APPROVED** [review]
