### PR TITLE
fix: hide explorer toggle icon in preview mode

### LINKED ISSUE #13869: [Bug]: Open and close side bar (Hamburger menu)- not working in first page of Welcome tour
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we click on Welcome tour in Main page and click on the ☰ (Hamburger menu) in top left corner, we are not seeing opening or closing of side bar. But we are able to see the hover or click message but no action noted.

### Steps To Reproduce

1. Click on "Welcome tour"
2. Observe page loads to first page of "Welcome tour"
3. Click on ☰ (Hamburger menu) in top left corner
4. Observe "Lock side bar open ctrl+/" is displayed
5. Click again observe "Close side bar ctrl+/" is displayed
6. But Side bar is not Locked open or closed 

https://user-images.githubusercontent.com/104895602/168588646-062094ba-cadf-47f9-8aca-5ddb12390eb8.mp4

### Public Sample App

_No response_

### Version

release and production

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Hides explorer toggle icon in preview mode

Fixes #13869

https://user-images.githubusercontent.com/67054171/172160658-5c06db5d-8ea0-40f8-ad37-a848b1207bea.mov

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/pages/Editor/EditorHeader.tsx [hunk 1]
```diff
@@ -345,7 +345,13 @@ export function EditorHeader(props: EditorHeaderProps) {
     <ThemeProvider theme={theme}>
       <HeaderWrapper className="pr-3" data-testid="t--appsmith-editor-header">
         <HeaderSection className="space-x-3">
-          <HamburgerContainer className="relative flex items-center justify-center p-0 text-gray-800 transition-all transform duration-400">
+          <HamburgerContainer
+            className={classNames({
+              "relative flex items-center justify-center p-0 text-gray-800 transition-all transform duration-400": true,
+              "-translate-y-full opacity-0": isPreviewMode,
+              "translate-y-0 opacity-100": !isPreviewMode,
```
Comment (jsartisan) [inline app/client/src/pages/Editor/EditorHeader.tsx:352]: @akash-codemonk can you try translate x instead? I think that would look good animation. Take the call. If it looks okay, then lets go with it.

Comment (akash-codemonk) [reply app/client/src/pages/Editor/EditorHeader.tsx]: Horizontal seems to look better. Have updated the same.

**Review by jsartisan — APPROVED** [review]
