### PR TITLE
fix: add keywords to the validation list

### LINKED ISSUE #10402: [Bug]: App crashes on renaming input widget and adding another input widget to the canvas
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that each and every time when an input widget is added to canvas and renamed as Number and the data type is set to number and on adding another input or any other widgets to the canvas the widgets doesn't load and on refreshing the page the app crashes 

[LOOM DEMO](https://www.loom.com/share/2c025c81dcf646c58b23ed0d3039710a)

### Steps To Reproduce

1.Launch appmsith app in release
2.Drag and drop input widget 
3.Rename the input widget as Number
4.Change the datatype to number 
5.Drag and drop another input widgets and other widgets 
6.Refresh the page and observe

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description

Fixes #10402 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/js-keywords 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.05 **(0)** | 36.62 **(-0.01)** | 34.76 **(0)** | 55.45 **(0)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**</details>

### CODE REVIEW

File: app/client/src/constants/WidgetValidation.ts [hunk 1]
```diff
@@ -80,6 +80,25 @@ export const JAVASCRIPT_KEYWORDS = {
...
+  NaN: "NaN",
+  name: "name",
+  Number: "Number",
+  Object: "Object",
+  prototype: "prototype",
+  String: "String",
+  toString: "toString",
+  undefined: "undefined",
+  valueOf: "valueOf",
 };
```
Comment (sbalaji1192) [inline app/client/src/constants/WidgetValidation.ts:102]: 1. prototype is not defined by js in the global namespace, we can remove.
2. Boolean is missing.

Comment (sbalaji1192) [reply app/client/src/constants/WidgetValidation.ts:102]: 2. Function is missing
3. JSON is missing

Comment (sbalaji1192) [reply app/client/src/constants/WidgetValidation.ts:102]: Could you arrange this alphabetically, it will be easy to search for a particular word.

File: app/client/src/constants/WidgetValidation.ts [hunk 2]
```diff
@@ -34,71 +34,72 @@ export type Validator = (
 export const ISO_DATE_FORMAT = "YYYY-MM-DDTHH:mm:ss.sssZ";
 
 export const JAVASCRIPT_KEYWORDS = {
-  true: "true",
+  Array: "Array",
   await: "await",
+  boolean: "boolean",
```
Comment (sbalaji1192) [inline app/client/src/constants/WidgetValidation.ts:39]: boolean - > Boolean

File: app/client/src/constants/WidgetValidation.ts [hunk 3]
```diff
@@ -34,71 +34,72 @@ export type Validator = (
...
   do: "do",
   else: "else",
   enum: "enum",
+  eval: "eval",
   export: "export",
   extends: "extends",
   false: "false",
   finally: "finally",
   for: "for",
   function: "function",
```
Comment (sbalaji1192) [inline app/client/src/constants/WidgetValidation.ts:59]: Function is missing, 
function is a keyword, while Function is a native function. we need to add both

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Verified this and it is working fine now
