### PR TITLE
Fix brackets mismatch

### LINKED ISSUE #1915: [Bug] Bracket matching does not work properly with binding brackets
Binding brackets interfere and throw a user off causing errors

### PR DESCRIPTION
**Pull request by ofpiyush**
## Description
Disable matching brackets if we're outside of javascript `mode`

Fixes #1915

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/editorComponents/CodeEditor/index.tsx [hunk 1]
```diff
@@ -216,17 +218,25 @@ class CodeEditor extends Component<Props, State> {
...
   };
 
+  handleCursorMovement = (cm: CodeMirror.Editor) => {
+    // ignore if disabled
+    if (!this.props.input.onChange || this.props.disabled) {
+      return;
+    }
+    const mode = cm.getModeAt(cm.getCursor());
+    if (mode && ["javascript", "application/json"].includes(mode.name)) {
+      this.editor.setOption("matchBrackets", true);
```
Comment (ofpiyush) [inline app/client/src/components/editorComponents/CodeEditor/index.tsx:228]: Fix memory leak in the codemirror library.

**Comment by ofpiyush** [comment]
I've opened a PR with CodeMirror to fix the memory leak. https://github.com/codemirror/CodeMirror/pull/6509

We'll update our dep once they merge and release a new version.
This PR can get merged independently.

**Review by hetunandu — APPROVED** [review]
