### PR TITLE
fix: Refactor entities with specific rules

### LINKED ISSUE #6760: [Bug] Error on table : "Binding path in the widget not found. Please reach out to Appsmith customer support to resolve this"
` Error: {  "widgetType" : "TABLE_WIDGET",  "bindingPath" : "primaryColumns.Sr_No..computedValue",  "message" : "Binding path in the widget not found. Please reach out to Appsmith customer support to resolve this.",  "widgetName" : "Table7",  "widgetId" : "v78pamwmft",  "pageId" : "610cdc95f00abe4fc53d8bef",  "layoutId" : "610cdc95f00abe4fc53d8bee",  "dynamicBinding" : null}`

Screenshot 2021-08-20 at 12 58 13 PM

Observation: Data is not showing on table sr_no column.
### Important Details

- Version: Cloud 
- OS: MacOSX
- Environment production

### LINKED ISSUE #17755: [Task]: Handle refactoring of JSObjects in AST-based entity refactor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Appsmith JSObjects starts with export default {} which is not a valid syntax as per acornjs parsing.
Sample input 
```
{ 
    "script":  "export default {\n\tmyVar1: [],\n\tmyVar2: {},\n\t\tsearch: () => {\n\t\tif(Input1Copy.text.length==0){\n\t\t\treturn select_repair_db.data\n\t\t}\n\t\telse{\n\t\t\treturn(select_repair_db.data.filter(word => word.cust_name.toLowerCase().includes(Input1Copy.text.toLowerCase())))\n\t\t}\n\t},\n}",
    "oldName": "select_repair_db", 
    "newName": "ApiForever", 
    "evalVersion": 2 
}
```

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description

This PR introduces more intelligence in the way we parse the DSL, actions and JS Objects during the refactor flow. Earlier, we used to treat each of these objects as plain maps that needed to be walked and performed a string replacement at any location where we found a match with the old name that was being refactored. However, this caused a few problems like ending up refactoring texts in the DSL that was not a binding but just happened to share the same keyword. Examples of these are when table names happened to have the same name as a widget name that is being refactored.

In this PR, we now only look at very specific paths in each type of object:
1. For DSL:
    - Only look at widgets
    - Specifically look at widget names
    - Parse through paths identified to contain dynamic bindings or dynamic triggers
    - In case of list, also look at templates
2. For actions:
    - Parse through paths identified to contain dynamic bindings or dynamic triggers
4. For JS Objects:
    - For an JS function that has been refactored, also update the complete body string for that action collection

Fixes #6760 
Fixes #17755 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual testing
- JUnit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/shared/ast/src/index.ts [hunk 1]
```diff
@@ -262,12 +266,18 @@ export const entityRefactorFromCode = (
   script: string,
   oldName: string,
   newName: string,
+  isJSObject: boolean,
   evaluationVersion: number,
   invalidIdentifiers?: Record<string, unknown>
-): Record<string, string | number> | string => {
+): EntityRefactorResponse => {
+  //If script is a JSObject then replace export default to decalartion.
+  if(isJSObject) script = script.replace(/export default/g, "let chandanbalajibp =");
```
Comment (ohansFavour) [inline app/shared/ast/src/index.ts:274]: Take a look at parseJSObjectWithAST function located [here](https://github.com/appsmithorg/appsmith/blob/bd95ae4ef0a4687e05d33e4257c54ecea7aa7ba7/app/shared/ast/src/jsObject/index.ts#L21). There is a similar logic to refactor js object string. Could we create an helper function that does this?.

File: app/shared/ast/src/index.ts [hunk 2]
```diff
@@ -262,12 +266,18 @@ export const entityRefactorFromCode = (
...
   let ast: Node = { end: 0, start: 0, type: "" };
   //Copy of script to refactor
   let refactorScript = script;
+  //Handle if a different datatypes is sent by server
+  oldName = typeof oldName === "string" ? oldName : String(oldName);
```
Comment (ohansFavour) [inline app/shared/ast/src/index.ts:279]: A very rare case though, but if an object is sent instead of a string, String() won't convert it to a useful string.

See [getInputValue function](https://github.com/appsmithorg/appsmith/blob/bd95ae4ef0a4687e05d33e4257c54ecea7aa7ba7/app/client/src/components/editorComponents/CodeEditor/codeEditorUtils.ts#L13) for inspiration to convert any type to string.

Comment (ohansFavour) [reply app/shared/ast/src/index.ts:279]: We should create an helper function that does this, so we don't duplicate logic for both oldName and newName

File: app/shared/ast/src/index.ts [hunk 3]
```diff
@@ -308,13 +318,17 @@ export const entityRefactorFromCode = (
         refactorOffset += nameLengthDiff;
         ++refactorCount;
       }
-      return shouldUpdateNode;
     });
-    return { script: refactorScript, count: refactorCount };
+    //If script is a JSObject then revert decalartion to export default.
+    if(isJSObject) refactorScript = refactorScript.replace("let chandanbalajibp =", "export default");
```
Comment (ohansFavour) [inline app/shared/ast/src/index.ts:323]: Duplicated logic

**Review by ohansFavour — COMMENTED** [review]
The client-side changes look good. Few suggestions.

File: app/shared/ast/src/index.ts (hunk 2 above)
Comment (ChandanBalajiBP) [reply app/shared/ast/src/index.ts]: Have handled this in validators. Hence removed this check itself.

File: app/shared/ast/src/index.ts (hunk 1 above)
Comment (ChandanBalajiBP) [reply app/shared/ast/src/index.ts]: parseJSObjectWithAST receives input without export default, hence couldn't reuse the whole of it. But have created helper functions along with the refactoring of common code.

File: app/shared/ast/src/index.ts (hunk 3 above)
Comment (ChandanBalajiBP) [reply app/shared/ast/src/index.ts]: Same as above

**Review by ohansFavour — APPROVED** [review]
Client-side changes look good.

**Review by subrata71 — APPROVED** [review]
Please take care of the comments that I made through a separate PR if seemed to be valid. Otherwise, it looks good to me.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java [hunk 4]
```diff
@@ -90,4 +151,32 @@ static class GetIdentifiersResponseDetails {
         Set<String> functionalParams;
         Set<String> variables;
     }
+
+    @NoArgsConstructor
```
[the remark this answers is not in the document]
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java:155]: I was facing some issues with the WebClient response parsing without it

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/RefactoringSolutionCEImpl.java [hunk 5]
```diff
@@ -264,59 +341,248 @@ public Mono<LayoutDTO> refactorName(String pageId, String layoutId, String oldNa
...
+                    return tuple.getT1();
+                });
+    }
+
+    Mono<Set<String>> refactorNameInWidget(JsonNode widgetDsl, String oldName, String newName, int evalVersion, Pattern oldNamePattern) {
+        boolean isRefactoredWidget = false;
+        boolean isRefactoredTemplate = false;
+        String widgetName = "";
+        // If the name of this widget matches the old name, replace the name
+        if (widgetDsl.has(FieldName.WIDGET_NAME)) {
```
[the remark this answers is not in the document]
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/RefactoringSolutionCEImpl.java:380]: We've done the check on widget id, the check here is to make sure that this flow does not fail even in case of a malformed DSL

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/RefactoringSolutionCEImpl.java [hunk 6]
```diff
@@ -264,59 +341,248 @@ public Mono<LayoutDTO> refactorName(String pageId, String layoutId, String oldNa
...
-                next.setValue(newArrayNode);
-            } else {
-                // This is either directly a text node or another json node
-                // In either case, recurse over the entire value to get the replaced value
-                next.setValue(replaceStringInJsonNode(value, oldNamePattern, newName));
+        Mono<Set<String>> refactorDynamicBindingsMono = Mono.just(new HashSet<>());
+        Mono<Set<String>> refactorTriggerBindingsMono = Mono.just(new HashSet<>());
+
+        // If there are dynamic bindings in this action configuration, inspect them
+        if (widgetDsl.has(FieldName.DYNAMIC_BINDING_PATH_LIST) && !widgetDsl.get(FieldName.DYNAMIC_BINDING_PATH_LIST).isEmpty()) {
```
[the remark this answers is not in the document]
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/RefactoringSolutionCEImpl.java:422]: I did not understand this comment @subrata71 .. could you please help with an example?
