### PR TITLE
Collab minor fixes

### LINKED ISSUE #5097: Show tooltip for comments feature discovery

### LINKED ISSUE #5436: [Bug] Collab issues

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
Collab minor fixes

Fixes #5436
Fixes #5097

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: collab-fixes 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.14 **(0.01)** | 36.1 **(-0.02)** | 32.83 **(0.04)** | 54.63 **(0)**
 :red_circle: | app/client/src/comments/CommentCard/CommentCard.tsx | 73.94 **(-1.37)** | 66.67 **(-2.49)** | 43.9 **(0)** | 74.51 **(-1.49)**
 :red_circle: | app/client/src/components/ads/EmojiReactions.tsx | 41.82 **(-4.85)** | 30 **(-10.63)** | 11.76 **(-0.74)** | 41.67 **(-3.33)**
 :red_circle: | app/client/src/constants/messages.ts | 71.92 **(-0.02)** | 100 **(0)** | 15.09 **(-0.08)** | 76.19 **(0.08)**
 :green_circle: | app/client/src/pages/Applications/permissionHelpers.tsx | 92.31 **(0.64)** | 100 **(0)** | 50 **(0)** | 91.67 **(0.76)**
 :green_circle: | app/client/src/pages/Editor/EditableAppName.tsx | 72.73 **(31.82)** | 37.5 **(4.17)** | 66.67 **(66.67)** | 73.68 **(26.31)**
 :green_circle: | app/client/src/pages/Editor/EditorHeader.tsx | 87.5 **(0)** | 55.81 **(9.47)** | 73.91 **(0)** | 87.21 **(0)**
 :red_circle: | app/client/src/pages/Editor/ToggleModeButton.tsx | 72.22 **(-4.79)** | 46.88 **(-3.12)** | 43.48 **(-3.89)** | 70.41 **(-3.95)**</details>

### CODE REVIEW

File: app/client/src/comments/CommentsShowcaseCarousel/index.tsx [hunk 1]
```diff
@@ -26,37 +21,40 @@ import { setCommentsIntroSeen } from "utils/storage";
 
 import { updateUserDetails } from "actions/userActions";
 
+const getBanner = (step: number) =>
+  `https://s3.us-east-2.amazonaws.com/assets.appsmith.com/comments/step-${step}.png`;
```
Comment (jsartisan) [inline app/client/src/comments/CommentsShowcaseCarousel/index.tsx:25]: I think we should save the base url in some constant.

**Review by jsartisan — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Review by akash-codemonk — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]
