### PR TITLE
fix: back btn navigation problems

### LINKED ISSUE #6813: [Bug]-[250]:Back button navigation problems
We need to fix how the back button works in our pages. I constantly land at odd places when I use the back button. It’s a minor annoyance that repeats frequently. An example:

- I see a list of datasources in the right hand side bar of the API pane
- I click to edit a datasource so I land up on the datasource page
- I click on the back button and it just takes me to the canvas instead of the API I was editing

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
The back button across for all the editors now will perform true go back action. This simplifies a lots of scenarios including going back to generate page vs going back to empty canvas.

Fixes #6813

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/back-btn-bug 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.62 **(0.01)** | 36.4 **(0.01)** | 33.83 **(0)** | 55.21 **(0.01)**
 :green_circle: | app/client/src/components/editorComponents/CloseEditor.tsx | 53.33 **(11.39)** | 100 **(75)** | 0 **(0)** | 53.33 **(11.39)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/Explorer/Actions/helpers.tsx [hunk 1]
```diff
@@ -65,11 +65,11 @@ export const ACTION_PLUGIN_MAP: Array<ActionGroupConfig | undefined> = [
       pluginType: PluginType,
       plugin?: Plugin,
     ) => {
-      if (!!plugin && pluginType === PluginType.SAAS) {
+      if (pluginType === PluginType.SAAS) {
         return `${SAAS_EDITOR_API_ID_URL(
           applicationId,
           pageId,
-          plugin.packageName,
+          !!plugin ? plugin.packageName : "",
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/Explorer/Actions/helpers.tsx:72]: image
I had come across this route, it has a missing `/`

**Review by rishabhsaxena — APPROVED** [review]
LGTM

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM!

Generate Page feature works as is 😁

File: app/client/src/pages/Editor/Explorer/Actions/helpers.tsx (hunk 1 above)
Comment (pranavkanade) [reply app/client/src/pages/Editor/Explorer/Actions/helpers.tsx:72]: Yes, although it works even without the `pluginPackageName`. I've looked into the Component corresponding to the route and found out that the package name is never being used. The redirection works without any hiccup.

**Comment by pranavkanade** [comment]
@RakshaKShetty could you please have a look at this. @Nikhil-Nandagopal could you please also take a look when you can and check if this behaviour is desirable or needs tweaking.

File: app/client/src/pages/Editor/Explorer/Actions/helpers.tsx (hunk 1 above)
Comment (rishabhsaxena) [reply app/client/src/pages/Editor/Explorer/Actions/helpers.tsx:72]: Yeah I guess it might still be working, think we should try passing the `plugin` param while using `getURL` at the `ActionsGroup.tsx`?

**Review by rishabhsaxena — APPROVED** [review]
