### PR TITLE
fix: datasource discard popup issue fixed

### LINKED ISSUE #18664: [Bug]: datasource unsaved changes popup shows even without changes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open a datasource for editing, and hit `Back` without making any changes, I should not see the popup to save/discard changes. As you can see in the video, on release there is popup being shown

https://user-images.githubusercontent.com/94514895/205579385-d80d4306-03e2-47cb-902a-bbe14b8c95bc.mov

### Steps To Reproduce

1. select existing datasource (I used a postgres datasource)
2. open it for editing
3. make no changes, hit `Back`

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by sneha122**
## Description
When I open a datasource for editing, and hit Back without making any changes, I should not see the popup to save/discard changes. 

Fixes #18664 

Media
https://user-images.githubusercontent.com/30018882/206202137-63bf45fb-8aa9-4867-86e6-68ee8d093b00.mov

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18664_spec.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+describe("Bug 18664: datasource unsaved changes popup shows even without changes", function() {
+  it("1. Create postgres datasource, save it and edit it and go back, now unsaved changes popup should not be shown", () => {
+    dataSources.NavigateToDSCreateNew();
+    agHelper.GenerateUUID();
+    cy.get("@guid").then((uid) => {
+      dataSources.CreatePlugIn("PostgreSQL");
+      dsName = "Postgres" + uid;
+      agHelper.RenameWithInPane(dsName, false);
+      dataSources.SaveDatasource();
+      cy.wait(1000);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18664_spec.ts:17]: Can we please use - ` dataSources.CreateDataSource("Postgres");` instead of these lines?
And read created dsName with 
`cy.get("@dsName").then(($dsName) => {
      dsName = $dsName;
    });` to use in deleteDS method

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18664_spec.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+      dataSources.EditDatasource();
+      agHelper.GoBack();
+      cy.get(dataSources._activeDS).should("be.visible");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18664_spec.ts:20]: Use  `agHelper.AssertElementVisible(dataSources._activeDS);` instead.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18664_spec.ts (hunk 1 above)
Comment (sneha122) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18664_spec.ts:17]: Actually createdatasource, will create the ds with all filled information, I wanted to create empty postgres datasource without filling any form, hence i used create plugin instead.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18664_spec.ts (hunk 2 above)
Comment (sneha122) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18664_spec.ts]: Suggested changes are made. Please check @Aishwarya-U-R

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good!

**Review by AmanAgarwal041 — APPROVED** [review]
