### PR TITLE
fix: Excluded hyphen substitution in branch name validation

### LINKED ISSUE #9758: Don't substitute hyphens with `_` in branch names

### PR DESCRIPTION
**Pull request by ankitakinger**
Added exception for hyphen while updating branch names containing special characters.

## Description
Branch names are validated to check if it contains special characters. If any special character is present then it gets replaced with an underscore.
Earlier, only / was excluded for the above validation process.
Now, / and - are excluded for the validation process.

Fixes #9758

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

* Tested by passing a random string value to the function containing special characters: */-_
* Tested by creating a new branch name

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: hotfix/hyphen_branchnames 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.23 **(0)** | 37.09 **(0)** | 34.09 **(0.01)** | 55.74 **(0)**
 :green_circle: | app/client/src/pages/Editor/gitSync/components/BranchList.tsx | 23.6 **(1.24)** | 10.67 **(0)** | 2.5 **(2.5)** | 25.52 **(1.38)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/gitSync/components/BranchList.tsx [hunk 1]
```diff
@@ -245,7 +245,7 @@ function BranchesLoading() {
 }
 
 export const removeSpecialChars = (value: string) => {
-  const separatorRegex = /(?!\/)\W+/;
+  const separatorRegex = /(?![/-])\W+/;
```
Comment (mohanarpit) [inline app/client/src/pages/Editor/gitSync/components/BranchList.tsx:248]: Is there a test case for this?

Comment (ankitakinger) [reply app/client/src/pages/Editor/gitSync/components/BranchList.tsx:248]: Added the Jest test case for this one and updated the PR.

**Review by mohanarpit — APPROVED** [review]
