### PR TITLE
FIX #4731: update condition for selectedRowIndices when table widget drag and drop

### LINKED ISSUE #4731: [Bug]Dragging and Dropping table widget 'The value at selected-row is invalid' error occurs in the debugger
## Description
Release Environment - Table Widget - It is observed that by dragging and dropping Table widget 'The Value at the selected row is invalid' error occurs in the debugger

**Expected Result:**
Error should not occur by Dragging and Dropping any widgets

**Actual Result:**
Dragging and Dropping table widget error 'The value at selected row is invalid' occurs in the debugger

### Steps to reproduce the behaviour:
1.Launch Appsmith app in the release Environment 
2.Expand Widgets
3.Drag and Drop table widget and observe

**Video Link:**
https://www.loom.com/share/e741880350784267bd70b6e07121d22d

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS Big sur 11.3]
- Browser [Safari]
- Environment [Release]

### PR DESCRIPTION
**Pull request by vibhandikyash**
Fixes #4731 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested Locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

File: app/client/src/widgets/TableWidget/derived.js [hunk 1]
```diff
@@ -20,7 +20,9 @@ export default {
   },
   //
   getSelectedRows: (props, moment, _) => {
-    const selectedRowIndices = props.selectedRowIndices || [];
+    const selectedRowIndices = Array.isArray(props.selectedRowIndices)
+      ? props.selectedRowIndices
+      : [props.selectedRowIndices];
```
Comment (riodeuno) [inline app/client/src/widgets/TableWidget/derived.js:25]: If `props.selectedRowIndices` is `undefined` or `null`, this will result in `[undefined]`  or `[null]`. Can we verify if this will cause issues?

Comment (riodeuno) [reply app/client/src/widgets/TableWidget/derived.js:25]: @somangshu @vibhandikyash any updates on this?

Comment (vibhandikyash) [reply app/client/src/widgets/TableWidget/derived.js:25]: I've verified this one on my local and this doesn't cause any issues.

**Comment by somangshu** [comment]
re-running, tests are failing

**Comment by YogeshJayaseelan** [comment]
Tested this issue in https://deploy-preview-4864--appsmith-editor-ce.netlify.app/applications and it is working as expected

**Review by somangshu — APPROVED** [review]
Approving to run tests

@riodeuno we have confirmed that this fixes the linked issues!

**Review by riodeuno — APPROVED** [review]

**Comment by somangshu** [comment]
Rerunning jobs as a flaky test failed

**Comment by somangshu** [comment]
@vibhandikyash need to merge the latest release here.

**Comment by somangshu** [comment]
@vibhandikyash latest merge required here for fix failing tests.

**Review by somangshu — APPROVED** [review]
