### PR TITLE
fix: Execute api pagination fix

### LINKED ISSUE #16202: [Bug]-[4000]:Response url not encoded in Previous URL & Next URL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

API call run fine but when I enter the same url in Next url, throws

java.net.URISyntaxException: Illegal character in query at index 78: https://api.github.com/orgs/appsmithorg/issues?filter=all&state=open&labels=UI Builders Pod&pulls=true&per_page=100&page=2

### Steps To Reproduce

Loom recording
https://www.loom.com/share/9956f599b4764e738790424ff72d8038

### Public Sample App

_No response_

### Version

Cloud 1.7.13

### PR DESCRIPTION
**Pull request by vaibh1297**
## Description

> Url encoding added for pagination cases.

Fixes #16202 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Unit Testing

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 1]
```diff
@@ -196,14 +197,49 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
                 if (actionConfiguration.getNext() == null) {
                     datasourceConfiguration.setUrl(null);
                 } else {
-                    datasourceConfiguration.setUrl(URLDecoder.decode(actionConfiguration.getNext(), StandardCharsets.UTF_8));
+//                    datasourceConfiguration.setUrl(URLDecoder.decode(actionConfiguration.getNext(), StandardCharsets.UTF_8));
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:200]: Please don't leave commented code in the code base. Makes it much harder for future developers to read & understand the code base.

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 2]
```diff
@@ -196,14 +197,49 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
...
+
+        private String encodeQueryParameters(String queryParams) {
+
+            StringBuilder responseBuilder = new StringBuilder();
+
+            String[] queryParamArray = queryParams.split("&");
+
+            for (String queryParam : queryParamArray) {
+
+                String[] a = queryParam.split("=");
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:229]: Suggestion to use a better variable name. As a rule of thumb, please use minimum 4 characters to define a variable name. At any point, if you find yourself using a variable name less than 4 characters, please reconsider. 

At this point in the code, I don't know what `a` is or what it represents.

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 3]
```diff
@@ -124,6 +111,154 @@ public void testValidJsonApiExecution() {
...
+        executeActionDTO.setViewMode(Boolean.FALSE);
+        executeActionDTO.setParamProperties(Collections.singletonMap("k0","string"));
+        executeActionDTO.setParameterMap(Collections.singletonMap(url,"k0"));
+        executeActionDTO.setInvertParameterMap(Collections.singletonMap("k0",url));
+
+        DatasourceConfiguration dsConfig = new DatasourceConfiguration();
+        dsConfig.setUrl("https://api.github.com");
+
+        final List<Property> headers = List.of(
+                new Property("Authorization","Basic TmlraGlsLU5hbmRhZ29wYWw6ODJjY2ZlMDljN2M4MDU5M2VkOTRjZTI1OTA0OTEyYmQ1OTA0NWJmNA=="),
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:142]: What API key is this? I hope this is not your API key for Github. If yes, please remove it & immediately change the key because this is a security issue.

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 4]
```diff
@@ -124,6 +111,154 @@ public void testValidJsonApiExecution() {
                 .verifyComplete();
     }
 
+    @Test
+    public void testExecuteWithPaginationForPreviousUrlApi() {
+
+        String url = "https://api.github.com/orgs/appsmithorg/issues?filter=all&state=open&labels=UI Builders Pod&pulls=true&per_page=100&page=2";
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:117]: Nit: Is it necessary for us to use a Github endpoint? Can we not hit our mock-api endpoint for testing purposes?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 5]
```diff
@@ -124,6 +111,154 @@ public void testValidJsonApiExecution() {
...
+        String previousUrl = "https://api.github.com/orgs/appsmithorg/issues?filter=all&state=open&labels=UI Builders Pod&pulls=true&page=1&per_page=100";
+        String nextUrl = "https://api.github.com/orgs/appsmithorg/issues?filter=all&state=open&labels=UI Builders Pod&pulls=true&per_page=100&page=2";
+
+        String actionId = "634f0dcee577f13a234483a2";
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:121]: Can you help me understand what `actionId` is this? Are we sure that this will NEVER change?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 6]
```diff
@@ -124,6 +127,137 @@ public void testValidJsonApiExecution() {
...
+        actionConfig.setFormData(Collections.singletonMap("apiContentType","none"));
+
+        Mono<ActionExecutionResult> resultMono = pluginExecutor.executeParameterized(null, executeActionDTO, dsConfig, actionConfig);
+
+        StepVerifier.create(resultMono)
+                .assertNext(result -> {
+                    assertTrue(result.getIsExecutionSuccess());
+                    assertNotNull(result.getBody());
+                    JsonNode body = (JsonNode) result.getBody();
+                    assertEquals(3,body.size());
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:188]: Can you please add a check here to see that we have hit the correct URL with the correct query params ?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 7]
```diff
@@ -124,6 +127,137 @@ public void testValidJsonApiExecution() {
...
+    @Test
+    public void testExecuteApiWithPaginationForPreviousUrl() {
+
+        String url = "https://mock-api.appsmith.com/users?pageSize=1&page=3&mock_filter=abc 11";
+        String previousUrl = "https://mock-api.appsmith.com/users?pageSize=1&page=2&mock_filter=abc 11";
+        String nextUrl = "https://mock-api.appsmith.com/users?pageSize=1&page=4&mock_filter=abc 11";
+
+        String actionId = "6363b463274d262e00edc1c5";
+
+        Param param = new Param();
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:140]: Can we remove this since we don't seem to be using the `param` variable anywhere ? Please mention here in case it is being used anywhere.

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 8]
```diff
@@ -124,6 +127,137 @@ public void testValidJsonApiExecution() {
...
 
+
+    @Test
+    public void testExecuteApiWithPaginationForPreviousUrl() {
+
+        String url = "https://mock-api.appsmith.com/users?pageSize=1&page=3&mock_filter=abc 11";
+        String previousUrl = "https://mock-api.appsmith.com/users?pageSize=1&page=2&mock_filter=abc 11";
+        String nextUrl = "https://mock-api.appsmith.com/users?pageSize=1&page=4&mock_filter=abc 11";
+
+        String actionId = "6363b463274d262e00edc1c5";
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:138]: APMU, we don't need to set or use the `actionId` for this test case. Can you please check if remvoing the `actionId` is ok for this test case ?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 9]
```diff
@@ -124,6 +127,137 @@ public void testValidJsonApiExecution() {
...
+                    assertEquals(3,body.size());
+                    final ActionExecutionRequest request = result.getRequest();
+                    assertEquals(HttpMethod.GET, request.getHttpMethod());
+                })
+                .verifyComplete();
+
+    }
+
+    @Test
+    public void testExecuteApiWithPaginationForNextUrl() {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:197]: Please check once if the points mentioned above apply for this test case as well.

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 1 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 2 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 10]
```diff
@@ -196,14 +197,49 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
...
+        }
+
+        private String encodeQueryParameters(String queryParams) {
+
+            StringBuilder responseBuilder = new StringBuilder();
+
+            String[] queryParamArray = queryParams.split("&");
+
+            for (String queryParam : queryParamArray) {
+
```
[the remark this answers is not in the document]
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 11]
```diff
@@ -5,15 +5,7 @@
...
-import com.appsmith.external.models.ActionConfiguration;
-import com.appsmith.external.models.ActionExecutionRequest;
-import com.appsmith.external.models.ActionExecutionResult;
-import com.appsmith.external.models.ApiKeyAuth;
-import com.appsmith.external.models.AuthenticationDTO;
-import com.appsmith.external.models.DatasourceConfiguration;
-import com.appsmith.external.models.OAuth2;
-import com.appsmith.external.models.Param;
-import com.appsmith.external.models.Property;
+import com.appsmith.external.models.*;
```
[the remark this answers is not in the document]
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 3 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 4 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 8 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java]: actionId is removed.

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 7 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java]: removed.

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 12]
```diff
@@ -196,14 +197,43 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
...
+            StringBuilder responseBuilder = new StringBuilder();
+            String[] queryParamArray = queryParams.split("&");
+
+            for (String queryParam : queryParamArray) {
+                String[] keyValue = queryParam.split("=");
+                if (keyValue.length == 2) {
+                    if (responseBuilder.length() != 0) {
+                        responseBuilder.append("&");
+                    }
+                    responseBuilder.append(keyValue[0]).append("=").append(URLEncoder.encode(keyValue[1], StandardCharsets.UTF_8));
```
[the remark this answers is not in the document]
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 13]
```diff
@@ -196,14 +197,43 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
...
-                datasourceConfiguration.setUrl(actionConfiguration.getPrev());
+                datasourceConfiguration.setUrl(encodeUrl(actionConfiguration.getPrev()));
             }
+
             return datasourceConfiguration;
         }
 
+        private String encodeUrl(String inputUrl) {
+
+            String[] urlParts = inputUrl.split("\\?");
```
[the remark this answers is not in the document]
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 14]
```diff
@@ -196,14 +197,43 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
...
                 }
             } else if (PaginationField.PREV.equals(paginationField)) {
-                datasourceConfiguration.setUrl(actionConfiguration.getPrev());
+                datasourceConfiguration.setUrl(encodeUrl(actionConfiguration.getPrev()));
             }
+
             return datasourceConfiguration;
         }
 
+        private String encodeUrl(String inputUrl) {
```
[the remark this answers is not in the document]
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 15]
```diff
@@ -124,6 +127,137 @@ public void testValidJsonApiExecution() {
                 .verifyComplete();
     }
 
+
+    @Test
+    public void testExecuteApiWithPaginationForPreviousUrl() {
+
+        String url = "https://mock-api.appsmith.com/users?pageSize=1&page=3&mock_filter=abc 11";
+        String previousUrl = "https://mock-api.appsmith.com/users?pageSize=1&page=2&mock_filter=abc 11";
+        String nextUrl = "https://mock-api.appsmith.com/users?pageSize=1&page=4&mock_filter=abc 11";
```
[the remark this answers is not in the document]
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:137]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 6 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:237]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 9 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:248]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 5 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java]: This is not required.

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 16]
```diff
@@ -196,14 +197,48 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
...
             }
+
             return datasourceConfiguration;
         }
 
+        private String decodeUrlAndEncodeQueryParams(String inputUrl) {
+
+            String decodedUrl = URLDecoder.decode(inputUrl,StandardCharsets.UTF_8);
+
+            String[] urlParts = decodedUrl.split("\\?");
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:213]: QQ: Have we added a check anywhere to make sure that we encode query params only when the `encode query params` toggle is switched on in the settings tab ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 16 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:217]: done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 17]
```diff
@@ -106,8 +107,9 @@ public Mono<ActionExecutionResult> executeParameterized(APIConnection connection
             if (actionConfiguration.getPaginationType() != null &&
                     PaginationType.URL.equals(actionConfiguration.getPaginationType()) &&
                     executeActionDTO.getPaginationField() != null) {
-                updateDatasourceConfigurationForPagination(actionConfiguration, datasourceConfiguration, executeActionDTO.getPaginationField());
-                updateActionConfigurationForPagination(actionConfiguration, executeActionDTO.getPaginationField());
+                List<Property> queryParamsList = new ArrayList<>();
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:110]: Can you please rename this to `paginationQueryParams` ?

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 18]
```diff
@@ -181,29 +183,78 @@ public Mono<ActionExecutionResult> executeCommon(APIConnection apiConnection,
...
                                                                                    DatasourceConfiguration datasourceConfiguration,
+                                                                                   List<Property> queryParamsList,
                                                                                    PaginationField paginationField) {
+
             if (PaginationField.NEXT.equals(paginationField)) {
                 if (actionConfiguration.getNext() == null) {
                     datasourceConfiguration.setUrl(null);
                 } else {
-                    datasourceConfiguration.setUrl(URLDecoder.decode(actionConfiguration.getNext(), StandardCharsets.UTF_8));
+                    queryParamsList.addAll(decodeUrlAndEncodeQueryParams(datasourceConfiguration,actionConfiguration.getNext()));
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:204]: Please change the function name `decodeUrlAndEncodeQueryParams` to something since we are not encoding the query params in this function now I think ? Something like `decodeUrlAndGetAllQueryParams` ?

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 19]
```diff
@@ -181,29 +183,78 @@ public Mono<ActionExecutionResult> executeCommon(APIConnection apiConnection,
...
+            return new ArrayList<>();
+        }
+
+    private List<Property> getQueryParamList(String queryParams) {
+
+            String[] queryParamArray = queryParams.split("&");
+
+            List<Property> queryParamList = new ArrayList<>();
+
+            for (String queryParam : queryParamArray) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:245]: Can you please check if this case is handled here: https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 20]
```diff
@@ -181,29 +183,78 @@ public Mono<ActionExecutionResult> executeCommon(APIConnection apiConnection,
...
+                String[] keyValue = queryParam.split("=");
+
+                String key = keyValue.length > 0 ? keyValue[0] : "";
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:248]: Can you please check what happens when key evaluates to empty ? i.e. whether the API server runs into any error during further processing ?

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 21]
```diff
@@ -181,29 +183,78 @@ public Mono<ActionExecutionResult> executeCommon(APIConnection apiConnection,
...
+                    queryParamBuilder.append(urlParts[i]);
+                }
+
+                return getQueryParamList(queryParamBuilder.toString());
+            }
+
+            return new ArrayList<>();
+        }
+
+    private List<Property> getQueryParamList(String queryParams) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:239]: Can you please rename this to `getQueryParamListFromUrlSuffix` ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 21 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 18 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 17 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: done

**Review by sumitsum — APPROVED** [review]

**Comment by btsgh** [comment]
Tested the fix with following Apis - 
1. https://mock-api.appsmith.com/users?pageSize=1&page=3&mock_filter=abc 11
2. https://637f8e5a2f8f56e28e8fd6ef.mockapi.io/api/v1/articles?page=3&mock filter=abc 11&pagesize=1

In both the cases, the api runs successfully
In the Pagination tab, on the next and previous url, test works fine - no errors. 
On disabling the Encode Query Params toggle, the run as well as test fails .. this is as expected. 

One concern - the Performance results have many values showing up in red in the SD (Variation%) column. @vaibh1297  - please can you connect with the performance team to check if this is acceptable.

**Comment by sumitsum** [comment]
@SatishGandham can you please check out the performance metrics mentioned by Aparna.

**Comment by btsgh** [comment]
Found an issue with logging into this branch using my appsmith id. It gave internal server error and the docker logs had the following errors - 
 
Logging into localhost of other branches using the same appsmith id does not give any errors. 
Discussed the same with @vaibh1297  - he tried it on his local with my appsmith id and he did not face any issues.

Just bringing this up here as wanted to take a call if this is something that needs to be looked at?

**Comment by sumitsum** [comment]
@btsgh can you please share steps to reproduce the error ?

**Comment by btsgh** [comment]
> @btsgh can you please share steps to reproduce the error ?

Bring up the local environment for this branch
Try to login using my appsmith credentials - aparna@appsmith.com and corresponding password
