### PR TITLE
fix: QA callouts on List V2

### LINKED ISSUE #19941: TAsk: QA Callout-2
https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

1. Issue with SSP when Primary key is not selected(My datasource here was a google sheet) https://www.loom.com/share/d4f7f799ec0c473f88015110b441fc9a
2. Listv2 and the canvas crashes when we refresh the data from the QUERIES/JS  section and then come back to the widget and do item selection on pagination https://www.loom.com/share/fed18e8f9aed4300a3ffa1d0a7b18502
3. Canvas crashes when we click on List item after resetting the List widget(List widget should NOT be on page 1 during resetting) https://www.loom.com/share/511d3ec8988742878867507bc7fd61a8
4. We are not showing any of the Child widgets (widgets inside a nested List) view properties on calling triggrerdViewItems
5. remove the paste operation when copied from Listv2 container item https://www.loom.com/share/90c42a98c4194beabc4f89e26bbe5d54
6. remove the cut operation from Listv2 container item https://www.loom.com/share/90c42a98c4194beabc4f89e26bbe5d54

https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0

Fixes #19941

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Jest
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 1]
```diff
@@ -210,6 +210,7 @@ class ListWidget extends BaseWidget<
     if (this.props.infiniteScroll) {
       this.generateMetaWidgets();
     }
+    this.updateCacheKey();
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:213]: Add a new line above this.

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 2]
```diff
@@ -621,33 +619,33 @@ class ListWidget extends BaseWidget<
   };
 
   updateCacheKey = () => {
-    const { selectedItemIndex = -1, triggeredItemIndex = -1 } = this.props;
+    const { selectedItemKey, triggeredItemKey } = this.props;
     const cachedKeys: Record<string, number> = {};
 
-    if (selectedItemIndex === -1 && triggeredItemIndex === -1) return;
+    if (!selectedItemKey && !triggeredItemKey) return;
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:625]: Keys can be `0` as well right? I think we should check for `null/undefined`?

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 3]
```diff
@@ -621,33 +619,33 @@ class ListWidget extends BaseWidget<
...
 
-    [selectedItemIndex, triggeredItemIndex].forEach((index) => {
-      if (index === -1) return;
+    [selectedItemKey, triggeredItemKey].forEach((key) => {
+      if (!key) return;
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:628]: Check for null/undefined here as well?

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 4]
```diff
@@ -723,18 +722,17 @@ class ListWidget extends BaseWidget<
...
 
-    if (selectedItemIndex !== -1) {
+    if (selectedItemKey) {
       if (this.props.serverSidePagination) {
-        const key =
-          Object.keys(this.cachedKeys).find(
-            (key) => this.cachedKeys[key] === selectedItemIndex,
-          ) ?? this.metaWidgetGenerator.getPrimaryKey(selectedItemIndex);
-        data = this.metaWidgetGenerator.getRowDataCache()[key];
+        data = this.metaWidgetGenerator.getRowDataCache()[selectedItemKey];
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:730]: Can we have another method in `metaWidgetGenerator` like `getDataByPrimaryKey`?
Let's not expose any `cache` related API as the user of metaWidgetGenerator should not be aware of that much info

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 5]
```diff
@@ -621,33 +619,33 @@ class ListWidget extends BaseWidget<
...
+        const index = this.metaWidgetGenerator.getRowIndexFromPrimaryKey(key);
         if (key) cachedKeys[key] = index;
         return;
       }
 
-      const key = this.metaWidgetGenerator.getPrimaryKey(index);
-      cachedKeys[key] = index;
+      if (this.getWidgetCache()?.[key]) {
+        const index = this.metaWidgetGenerator.getRowIndexFromPrimaryKey(key);
+        cachedKeys[key] = index;
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:638]: What is the use of `cachedKeys` now?

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx (hunk 3 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:628]: Keys are either strings or null/undefined.

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:625]: Keys are either strings or null/undefined.

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 6]
```diff
@@ -656,24 +632,32 @@ class ListWidget extends BaseWidget<
   };
 
   updateRowCacheWithNewData = () => {
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:634]: Remove

File: app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts [hunk 7]
```diff
@@ -65,21 +65,64 @@ export const primaryColumnValidation = (
...
+  try {
+    return JSON.parse(value);
+  } catch (error) {
+    return "";
+  }
+};
+
 export const primaryKeyOptions = (props: ListWidgetProps) => {
-  const { widgetName } = props;
+  const { primaryKeys, widgetName } = props;
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts:89]: // Since this is uneval value, coercing it to primitive type 
const primaryKeys = props.primaryKeys as unknown as string | number

File: app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts [hunk 8]
```diff
@@ -65,21 +65,64 @@ export const primaryColumnValidation = (
...
+  const updatedPrefix = `${prefixTemplate} currentItem[`;
+  const updatedSuffix = `] ${suffixTemplate}`;
+  const suffixLength = dynamicValue.length - updatedSuffix.length;
+
+  const value = dynamicValue.substring(updatedPrefix.length, suffixLength);
+
+  try {
+    return JSON.parse(value);
+  } catch (error) {
+    return "";
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts:84]: log error

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 9]
```diff
@@ -586,90 +579,34 @@ class ListWidget extends BaseWidget<
...
-      cachedKeys[key] = index;
-    });
-
-    this.cachedKeys = cachedKeys;
-  };
-
+  /**
+   * Only Initiate Cache if
+   * 1. Triggered or Selected Key changes (i.e a  new row was triggered or selected)
+   * 2. If Server-side Pagination is just turned on. (The is mainly to cache any row previously selected)
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:585]: Typo -> `This is mainly ...`

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 10]
```diff
@@ -586,90 +579,34 @@ class ListWidget extends BaseWidget<
...
-        const viewIndex = rowIndex - startIndex;
-
-        rowDataCache = {
-          ...rowDataCache,
-          [key]: this.props.listData?.[viewIndex] ?? rowDataCache[key],
-        };
-      }
-    });
-    this.updateMetaGeneratorRowDataCache(rowDataCache);
+    this.metaWidgetGenerator.handleCache(keys);
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:605]: `handleCachedKeys`

**Review by ashit-rath — APPROVED** [review]
