### PR TITLE
fix: response tab open by default in case of page load query

### LINKED ISSUE #28428: [Task]: Show query response tab open by default when query runs on page load
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

As per [thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1697720357230469) we want to keep response tab open by default when we visit a query that loads on page refresh

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes second part of the issue #28287 . First part, where data was not getting shown in response tab even if data is present, was fixed in PR #28296 . Second part is where we want to keep the debugger tab open, when query response is present. Its fixed in this PR.

https://github.com/appsmithorg/appsmith/assets/30018882/09e390a7-a311-4200-9e3f-71a0cd241a4f

#### PR fixes following issue(s)
Fixes #28428 
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx [hunk 1]
```diff
@@ -503,6 +503,13 @@ export function EditorJSONtoForm(props: Props) {
     }
   }
 
+  useEffect(() => {
+    if (responseDisplayFormat && !!responseDisplayFormat?.title && output) {
+      dispatch(showDebugger(true));
+      dispatch(setDebuggerSelectedTab(DEBUGGER_TAB_KEYS.RESPONSE_TAB));
+    }
+  }, [responseDisplayFormat]);
```
Comment (AmanAgarwal041) [inline app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx:511]: Should output not also be in the dependency array ?

Comment (sneha122) [reply app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx]: Yes its needed, nice catch!! Fixed it. Please check

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested on different set of Datasources and API
