### PR TITLE
fix: table ISO 8061 format bug for v1 and v2 version

### LINKED ISSUE #20799: [Bug]: Error when setting date field to ISO 8601 for perfectly acceptable date value
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try and set the original date format to "ISO 8601" I get the error "The value at primaryColumns.created.inputFormat is invalid" for the value `2023-02-02T13:39:38.367857Z`.

CleanShot 2023-02-03 at 12 35 55@2x

CleanShot 2023-02-03 at 12 35 06@2x

CleanShot 2023-02-03 at 16 34 22@2x

CleanShot 2023-02-03 at 12 41 48@2x

### Steps To Reproduce

1. Provide value `2023-02-02T13:39:38.367857Z` to table date field.
2. Set "Original Date Format" to "ISO 8601"
3. See error.

### Public Sample App

https://app.appsmith.com/app/o-m/1-customers-6022c2575437724e9c2c06a0/edit?branch=main

### Issue video log

https://drive.google.com/file/d/1Qylu8tnuqQh2vkr0JTysCYqYxE4m3Spw/view?usp=sharing

### Version

Cloud 1.9.8

### PR DESCRIPTION
**Pull request by vsvamsi1**
## Description

This pr fixes the ISO-8061 format issue with table v1 and v2. We see a validation errors in both when ISO-8061 format is selected. 

Fixes #20799

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/TableWidget/widget/propertyConfig.ts [hunk 1]
```diff
@@ -372,6 +372,7 @@ export default [
                       type: ValidationTypes.TEXT,
                       params: {
                         allowedValues: [
+                          "YYYY-MM-DDTHH:mm:ss.SSSZ",
```
Comment (aswathkk) [inline app/client/src/widgets/TableWidget/widget/propertyConfig.ts:375]: I think we need to replace the value `YYYY-MM-DDTHH:mm:ss.sssZ` (line number 380) to `YYYY-MM-DDTHH:mm:ss.SSSZ` instead of adding `YYYY-MM-DDTHH:mm:ss.SSSZ` to this array.

**Review by aswathkk — CHANGES_REQUESTED** [review]
@vsvamsi1 The changes looks good to me.

I have a minor suggestion.
Also, I could see that this validation is wrong for `outputFormat` property too. Can you fix that too?

File: app/client/src/widgets/TableWidget/widget/propertyConfig.ts (hunk 1 above)
Comment (vsvamsi1) [reply app/client/src/widgets/TableWidget/widget/propertyConfig.ts:375]: I was thinking of the same, but will it break existing validations if someone has add in the JS expression `YYYY-MM-DDTHH:mm:ss.sssZ`?

**Comment by vsvamsi1** [comment]
> @vsvamsi1 The changes looks good to me.
> 
> I have a minor suggestion. Also, I could see that this validation is wrong for `outputFormat` property too. Can you fix that too?

@aswathkk with regards to this comment I have fixed it over here ....are these changes okay?
`https://github.com/appsmithorg/appsmith/blob/0c39a72b2402c798bb725ce4c85f49d40878946a/app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/Data.ts#L275
https://github.com/appsmithorg/appsmith/blob/0c39a72b2402c798bb725ce4c85f49d40878946a/app/client/src/widgets/TableWidget/widget/propertyConfig.ts#L513
`

**Comment by aswathkk** [comment]
@vsvamsi1 Yeah. But, there also I can see that you added the valid format (`YYYY-MM-DDTHH:mm:ss.SSSZ`) into the beginning of the array rather than fixing the invalid one (`YYYY-MM-DDTHH:mm:ss.sssZ`) inside the array

**Review by aswathkk — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested date format issue on Table v2
- Tested for validation error - fixed

P.S- Testing of table v1 fix will be verified after merge. Since above DP doesn't have older apps
