### PR TITLE
fix: widget card filter

### LINKED ISSUE #32408: [Bug] Observed this bug while building an app, not sure why widget cards filter is lost when hovered on a widget.
The widget search filter gets reset every time the search input is unfocused

https://github.com/appsmithorg/appsmith/assets/12022471/133c936c-3ba4-4f5b-b133-ae89ebf4184b

### PR DESCRIPTION
**Pull request by jacquesikot**
When user starts to search for a widget, and hovers over the canvas area, the search filter resets. This issues is caused by the resetting of the widget cards state whenever user hovers

**Fix**
I have changed the trigger for the useEffect, to only set the widget cards state only when the building blocks are loaded.

Fixes #32408  

## Automation

/ok-to-test tags="@tag.Templates, @tag.Visual, @tag.Widget"

### :mag: Cypress test results

> [!IMPORTANT]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8610964331>
> Commit: `c5f3b657d91278a4ee841bc05db3ae4cab4b34c6`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8610964331&attempt=1" target="_blank">Click here!</a>
> All cypress tests have passed 🎉🎉🎉

## Summary by CodeRabbit

- **Bug Fixes**
    - Improved the update mechanism for the widgets list in the UI Editor sidebar to ensure it refreshes correctly after fetching new building blocks.

### CODE REVIEW

File: app/client/src/pages/Editor/widgetSidebar/hooks.ts [hunk 1]
```diff
@@ -40,7 +40,7 @@ export const useUIExplorerItems = () => {
     } else {
       setEntityLoading((prev) => ({ ...prev, "Building Blocks": false }));
     }
-  }, [dispatch, isBuildingBlocksLoaded]);
+  }, [isBuildingBlocksLoaded]);
```
Comment (hetunandu) [inline app/client/src/pages/Editor/widgetSidebar/hooks.ts:43]: Missing: `releaseDragDropBuildingBlocks` here

Comment (jacquesikot) [reply app/client/src/pages/Editor/widgetSidebar/hooks.ts:43]: done

**Review by hetunandu — DISMISSED** [review]

**Review by hetunandu — APPROVED** [review]
