### PR TITLE
fix: Removed applicationDetail empty object initialisation

### LINKED ISSUE #21727: [Bug]: For migration changes in git connected apps, after committing changes git sync modal shows option to commit and push again.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/227171633-566e00bb-91dd-4234-8313-d44a5bf4bac1.mov

### Steps To Reproduce

1. Go to an old app which has migration change like page modified.
2. Try to commit changes and observe.

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description

> This PR removes applicationDetail initialisation for empty object from the publish application method. 
> Due to the initialisation while publishing, git was detecting some changes in the application json and only these two fields were getting set in a separate commit. 
> With this fix, these fields will be set only when a user explicitly sets these properties.

Fixes #21727 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java [hunk 1]
```diff
@@ -1007,16 +1007,11 @@ public Mono<Application> publish(String applicationId, boolean isPublishedManual
 
                     application.setPublishedAppLayout(application.getUnpublishedAppLayout());
 
-                    if (application.getUnpublishedApplicationDetail() == null){
-                        application.setUnpublishedApplicationDetail(new ApplicationDetail());
-                    }
 
-                    if (application.getPublishedApplicationDetail() == null){
-                        application.setPublishedApplicationDetail(new ApplicationDetail());
+                    if (application.getUnpublishedApplicationDetail() != null){
```
Comment (nayan-rafiq) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java:1011]: This check is not required. If edit mode version is null, then published version should have null as well. Otherwise published mode version should have same value as edit mode version.

**Review by nayan-rafiq — CHANGES_REQUESTED** [review]
Looks good, just a minor change request.

**Review by nayan-rafiq — APPROVED** [review]
