### PR TITLE
fix: Open state of bottom bar

### LINKED ISSUE #22810: [Bug]: Debugger opens up during on-boarding causing important information to be hidden
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Debugger opens up in a blank state during on-boarding and stays open blocking important information a new user is trying to read. This shouldn't be the case, debugger should only open up when user chooses to view errors/logs.

### Steps To Reproduce

image

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
Added conditions to prevent unnecessary rendering when selecting RESPONSE_TAB or HEADER_TAB, improving performance.

>**Responsive ActionExecutionResizerHeight**
Adjusted the height calculation to be 30% of the window height, making it adaptable to different screen sizes.

>**Applied tab handling improvements to DataSourceEditor/Debugger**
Enhanced the performance of the DataSourceEditor/Debugger component by implementing similar tab handling conditions.

#### PR fixes following issue(s)
Fixes #22810 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts [hunk 1]
```diff
@@ -15,7 +16,26 @@ describe("Entity bottom bar", () => {
     _.debuggerHelper.AssertClosed();
   });
 
-  it("2. Api bottom pane should be collapsable", () => {
+  it("2. Jseditor bottom bar should be collapsable", () => {
+    _.jsEditor.CreateJSObject(` return "hello world";`);
+    //Verify if bottom bar open status is retained on changing from api to JSEditor.
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts:21]: Where are we checking if bottom bar is open when navigating to api page?
Where is api page navigation here?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts [hunk 2]
```diff
@@ -15,7 +16,26 @@ describe("Entity bottom bar", () => {
...
+    //Verify if bottom bar is closed on clicking close icon in JSEditor.
+    _.debuggerHelper.CloseBottomBar();
+    _.debuggerHelper.AssertClosed();
+    //Verify if bottom bar is open on executing JSFunction.
+    _.jsEditor.RunJSObj();
+    _.debuggerHelper.AssertOpen(PageType.JsEditor);
+    //verify if response tab is selected on execution JSFunction.
+    _.debuggerHelper.AssertSelectedTab("Response");
+    //verify if bottom bar is closed on switching to canvas page.
+    cy.get(OnboardingLocator.widgetPaneTrigger).click();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts:34]: Use agHelper.GetNClick()

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts (hunk 1 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts:21]: If not applicable - please correct the comments.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Onboarding/GuidedTour_spec.js [hunk 3]
```diff
@@ -30,7 +30,6 @@ describe("Guided Tour", function () {
     _.dataSources.SetQueryTimeout();
     // Step 1: Run query
     _.dataSources.RunQuery();
-    _.debuggerHelper.ClickDebuggerIcon();
```
[the remark this answers is not in the document]
Comment (ChandanBalajiBP) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Onboarding/GuidedTour_spec.js:33]: Yep, we will open response tab. But in this PR when user navigates from query page to canvas with response tab open -> we are closing bottom bar as response tab is part of canvas. 
We will keep the bottom bar open only if the selected tab is present in the navigate page.

[the remark this answers is not in the document]
Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Onboarding/GuidedTour_spec.js:33]: Where is user navigating to canvas here? They are clicking on successButton as next step.
No, either which ways question still is open - when RUnQuery is triggered - will the bottom bar open or not? Why is this statement removed?

[the remark this answers is not in the document]
Comment (ChandanBalajiBP) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Onboarding/GuidedTour_spec.js:33]: The click above was suppose to close debugger after the query run so when we navigate to canvas in further steps cypress is able to drag and drop widgets.

[the remark this answers is not in the document]
Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Onboarding/GuidedTour_spec.js:33]: Ok, now since canvas does not have any response - moving to canvas wil automatically close the bottom bar & this explicit closing is not needed.
Is the understanding right?

[the remark this answers is not in the document]
Comment (ChandanBalajiBP) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Onboarding/GuidedTour_spec.js:33]: Yes

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts (hunk 1 above)
Comment (ChandanBalajiBP) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts]: Updated

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts (hunk 2 above)
Comment (ChandanBalajiBP) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts]: Updated, will run tests tomorrow as most of them are timed out in previous run

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts [hunk 4]
```diff
@@ -15,7 +16,26 @@ describe("Entity bottom bar", () => {
     _.debuggerHelper.AssertClosed();
   });
 
-  it("2. Api bottom pane should be collapsable", () => {
+  it("2. Jseditor bottom bar should be collapsable", () => {
+    _.jsEditor.CreateJSObject(` return "hello world";`);
+    //Verify if bottom bar opens JSEditor.
+    _.debuggerHelper.AssertOpen(PageType.JsEditor);
+    // Verify if selected tab is response.
+    _.debuggerHelper.AssertSelectedTab("Response");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts:24]: Why is Response default here? Bcs its JSEditor-run?

Comment (ChandanBalajiBP) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts:24]: Yep, upon running JSFunc we open Response tab. This is existing behaviour.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts [hunk 5]
```diff
@@ -15,7 +16,26 @@ describe("Entity bottom bar", () => {
...
+    //Verify if bottom bar is closed on clicking close icon in JSEditor.
+    _.debuggerHelper.CloseBottomBar();
+    _.debuggerHelper.AssertClosed();
+    //Verify if bottom bar is open on executing JSFunction.
+    _.jsEditor.RunJSObj();
+    _.debuggerHelper.AssertOpen(PageType.JsEditor);
+    //verify if response tab is selected on execution JSFunction.
+    _.debuggerHelper.AssertSelectedTab("Response");
+    //verify if bottom bar is closed on switching to canvas page.
+    _.agHelper.GetNClick(OnboardingLocator.widgetPaneTrigger).click();
```
[the remark this answers is not in the document]
Comment (ChandanBalajiBP) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/EntityBottomBar_spec.ts]: Updated

File: app/client/src/components/editorComponents/Debugger/DebuggerTabs.tsx [hunk 6]
```diff
@@ -97,34 +97,43 @@ function DebuggerTabs() {
...
-      />
-      <Icon
-        className="close-debugger t--close-debugger"
-        name="close-modal"
-        onClick={onClose}
-        size={IconSize.XL}
-      />
-    </Container>
-  );
+  if (
```
Comment (ayushpahwa) [inline app/client/src/components/editorComponents/Debugger/DebuggerTabs.tsx:100]: Nit: can these conditions be moved to a single place in a function? And can you also add a comment on this regarding the use case of this condition. The code otherwise looks good to me.

Comment (ChandanBalajiBP) [reply app/client/src/components/editorComponents/Debugger/DebuggerTabs.tsx]: Updated

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress changes looks OK.

**Review by ayushpahwa — APPROVED** [review]
