### PR TITLE
fix: Add window object methods and properties as invalid entity name

### LINKED ISSUE #7898: [Bug] Entity names that are same as common window objects causes error in evaluation
## Description
Entity names get added to global scope while evaluation and if the entity name is some critical global object, it will crash the evaluation.

Screenshot 2021-09-28 at 4 35 53 PM

### Steps to reproduce the behaviour:

1. Rename a widget or action as "location"
2. Refresh
3. Add binding in any widget property and see this error

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

When entity name is a critical global object, it crashes the evaluation. This PR renders all the Window object property and method names as invalid for an entity name.

Fixes #7898

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Added Cypress tests to check that window object property and method names are invalid as entity names

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/do-not-support-window-object-properties-and-methods-as-valid-names 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/helpers.tsx | 64.93 **(0)** | 36.19 **(-0.7)** | 42.86 **(0)** | 62.05 **(0)**</details>

### CODE REVIEW

File: app/client/src/constants/WidgetValidation.ts [hunk 1]
```diff
@@ -87,3 +87,64 @@ export const DATA_TREE_KEYWORDS = {
...
+  requestAnimationFrame: "requestAnimationFrame",
+  resizeBy: "resizeBy",
+  resizeTo: "resizeTo",
+  scroll: "scroll",
+  scrollBy: "scrollBy",
+  scrollTo: "scrollBy",
+  setInterval: "setInterval",
+  setTimeout: "setTimeout",
+  stop: "stop",
+};
```
Comment (ohansFavour) [inline app/client/src/constants/WidgetValidation.ts:150]: For consistency in invalid entity names, I have added all methods and properties of the window object. Although, not all of these would crash the evaluation if not included.
I suggest that this should also be included in the documentation so that users know what names cannot be used as entity names.

Comment (hetunandu) [reply app/client/src/constants/WidgetValidation.ts:150]: Along with documentation can we create a custom error toast explaining this ?

**Review by hetunandu — APPROVED** [review]

File: app/client/src/constants/WidgetValidation.ts (hunk 1 above)
Comment (ohansFavour) [reply app/client/src/constants/WidgetValidation.ts:150]: All right

**Review by hetunandu — APPROVED** [review]
