### PR TITLE
fix: Incorrect error handling when incorrect sheet name is used in Google Sheets query

### LINKED ISSUE #9463: [Bug]: Incorrect error handling when incorrect sheet name is used in Google Sheets query
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Incorrect error for range parsing is displayed when incorrect sheet name is used in Google Sheets query

[LOOM DEMO](https://www.loom.com/share/b36dce31d86b471cb4d1a5f560e5451f)

### Steps To Reproduce

1. Go to Google Sheets query page and enter an incorrect sheet name and observe the error displayed to user

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by leotom2000**
## Description

> Incorrect error handling when incorrect sheet name is used in Google Sheets query

Fixes #9463

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> The already generated error from Response is parsed and displayed.
> Earlier as soon as an error is identified generic error message are thrown.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/AppendMethod.java [hunk 1]
```diff
@@ -121,12 +126,12 @@ public boolean validateMethodRequest(MethodConfig methodConfig) {
                                 "Expected to receive a response of existing headers."));
                     }
 
-                    if (jsonNodeBody.get("error") != null && jsonNodeBody.get("error").get("message") !=null) {
-                        throw Exceptions.propagate(new AppsmithPluginException(
-                                AppsmithPluginError.PLUGIN_ERROR,   jsonNodeBody.get("error").get("message").toString()));
-                    }
+                    if (response.getStatusCode() != null && !response.getStatusCode().is2xxSuccessful()) {
+                        if (jsonNodeBody.get("error") != null && jsonNodeBody.get("error").get("message") != null) {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/AppendMethod.java:130]: Can you also handle the else for this condition? That is, in case Google sheets comes back with a non-200 response, but does not have an error message of its own.

**Review by nidhi-nair — APPROVED** [review]
