### PR TITLE
[Fix] Support Videos in omnibar

### LINKED ISSUE #4887: Support videos within omnibar documentations details

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
Added a parsing logic to replace the gitbook embeddings with iframe to support youtube videos

Fixes #4887 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feature/video-in-ominibar 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.71 **(-0.02)** | 35.68 **(-0.02)** | 32.32 **(0.01)** | 54.29 **(-0.02)**
 :red_circle: | app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts | 78.79 **(-0.33)** | 43.02 **(0)** | 92.86 **(0.55)** | 79.17 **(-0.38)**
 :red_circle: | app/client/src/sagas/ErrorSagas.tsx | 64.6 **(-3.54)** | 47.62 **(-4.76)** | 50 **(0)** | 64.71 **(-3.92)**
 :red_circle: | app/client/src/sagas/CommentSagas/index.ts | 42.42 **(-3.03)** | 17.86 **(0)** | 50 **(0)** | 42.16 **(-1.96)**</details>

### CODE REVIEW

**Review by rishabhsaxena — DISMISSED** [review]

File: app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts [hunk 1]
```diff
@@ -20,6 +20,22 @@ export const htmlToElement = (html: string) => {
  */
 const strip = (text: string) => text.replace(/{% .*?%}/gm, "");
 
+const updateVideoEmbedingsWithIframe = (text: string) => {
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts:23]: nitpick: we could call it youtube embeddings instead

**Review by rishabhsaxena — DISMISSED** [review]

File: app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts [hunk 2]
```diff
@@ -20,6 +20,22 @@ export const htmlToElement = (html: string) => {
  */
 const strip = (text: string) => text.replace(/{% .*?%}/gm, "");
 
+const updateYoutubeEmbedingsWithIframe = (text: string) => {
+  let docString = text;
+  const ytIdSelectionRegex = /{% embed url="<a href="https:\/\/www.youtube.com\/watch\?v=(.*?)\&.*? %}/m;
```
Comment (Rishabh-Rathod) [inline app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts:25]: just a suggestion, Contansts (Regex) can be defined outside the functions avoiding reinitialisation of it on every call. Also allowing it to be used somewhere else if needed. (doesn't make much difference)

**Review by Rishabh-Rathod — APPROVED** [review]

**Review by Rishabh-Rathod — APPROVED** [review]
