### PR TITLE
fix: retained refresh token when auth token refresh request is executed

### LINKED ISSUE #24767: [Bug]: Data Source Reauthorization Required to Authenticate API After Update
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After one of the updates, some users are experiencing the need to reauthorize their data sources in the AHutenticate API after a certain period of time. I have investigated and successfully replicated this issue.

image

### Steps To Reproduce

1. Create a new data source for Authenticate API.

2. Configure it for Google Drive as shown in these images.
image
image
image
image

3. Execute the GET request, and you will receive a `200` response. However, after 3 hours, the token will expire, and despite having the parameters to refresh the token, it will not be refreshed.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Appsmith v1.9.23-SNAPSHOT

Front logo [Front conversations](https://app.frontapp.com/open/top_lt898)

### PR DESCRIPTION
**Pull request by tkAppsmith**
#### PR fixes following issue(s)
Fixes #24767
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by nidhi-nair — APPROVED** [review]

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java [hunk 1]
```diff
@@ -157,6 +157,11 @@ private Mono<OAuth2> generateOAuth2Token(DatasourceConfiguration datasourceConfi
                     if (mappedResponse.containsKey(Authentication.REFRESH_TOKEN)) {
                         authenticationResponse.setRefreshToken(
                                 String.valueOf(mappedResponse.get(Authentication.REFRESH_TOKEN)));
+                    } else {
+                        authenticationResponse.setRefreshToken(datasourceConfiguration
```
Comment (sumitsum) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java:161]: @tkAppsmith can you please add a null check here for `datasourceConfiguration.getAuthentication()`, `datasourceConfiguration.getAuthentication().getAuthenticationResponse()` ?

Comment (tkAppsmith) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java:161]: There are other places in the same flow before this line is executed where the refresh token property is accessed and if it was null if would've failed there and hence as per the design it seems this property is never expected to be null.

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java:161]: Hi @tkAppsmith , sorry, I am not able to find any usage / check for `datasourceConfiguration.getAuthentication().getAuthenticationResponse()` - can you please mention where I can find it in the code ?

Comment (tkAppsmith) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java:161]: https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java#L208

Here its being used to initiate the refresh token flow

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java:161]: @tkAppsmith in the line that you have referenced, it is accessing the objects in the new `OAuth` object that is received as a response from the remote server instead of the object in the datasourceConfiguration object: `oAuth2.getAuthenticationResponse().getRefreshToken()`

Comment (tkAppsmith) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java:161]: No no. oAuth2 object is caster from the datasourceConfuguration only.

https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java#L107

And that has to be no null since refresh token is needed to initiate the flow.

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java:161]: Apologies, seems like a misunderstanding on my part.

**Review by sumitsum — APPROVED** [review]
