### PR TITLE
Fixes error on failed github docs fetch : fixes #3551

### LINKED ISSUE #3551: [Bug] TypeError: Failed to fetch
Sentry Issue: [APPSMITH-M1](https://sentry.io/organizations/appsmith/issues/2266588809/?referrer=github_integration)

```
TypeError: Failed to fetch
```

### PR DESCRIPTION
**Pull request by kaushik94**
## Description
The application seems to report on Sentry when it fails to fetch raw GitHub content.

Fixes #3551 
Make sure we catch that error and retry fetching until a certain number of retries.

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Added a test to make sure the `fetchDefaultDocs`. But this is not a complete test in itself, as it doesn't test the useEffect hook.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mohanarpit** [comment]
@kaushik94 Can we prioritize merging this PR? There are quite a few errors that we are seeing in this flow. Merging this & promoting the fix to prod will do a world of good for our users.

File: app/client/src/components/editorComponents/GlobalSearch/utils.tsx [hunk 1]
```diff
@@ -103,33 +103,77 @@ const defaultDocsConfig = [
...
-            ...doc,
-          } as DocSearchItem;
-        }),
+const fetchDefaultDocs = (
+  updateIsFetching: (b: boolean) => void,
+  setDefaultDocs: (t: DocSearchItem[]) => void,
+  retries: number,
+  maxRetries: number,
+) => {
+  if (maxRetries >= retries) {
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/GlobalSearch/utils.tsx:138]: Looks like a typo,  should be `maxRetries <= retries`?

File: app/client/src/components/editorComponents/GlobalSearch/utils.tsx [hunk 2]
```diff
@@ -103,33 +103,77 @@ const defaultDocsConfig = [
...
+    return;
+  }
+  (async () => {
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/GlobalSearch/utils.tsx:141]: We can do without an `iife` here

File: app/client/src/components/editorComponents/GlobalSearch/utils.tsx [hunk 3]
```diff
@@ -103,33 +103,77 @@ const defaultDocsConfig = [
...
+        setDefaultDocs(data);
+        updateIsFetching(false);
+      } else {
+        fetchDefaultDocs(
+          updateIsFetching,
+          setDefaultDocs,
+          retries + 1,
+          maxRetries,
+        );
+      }
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/GlobalSearch/utils.tsx:155]: This seems a bit redundant, unless there's a failure to fetch the content due to network issues, we should always have data, otherwise retrying won't help much I suppose.

This should suffice?
```
setDefaultDocs(data);
updateIsFetching(false);
```

File: app/client/src/components/editorComponents/GlobalSearch/utils.tsx [hunk 4]
```diff
@@ -103,33 +103,77 @@ const defaultDocsConfig = [
...
+    } catch (e) {
+      fetchDefaultDocs(
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/GlobalSearch/utils.tsx:157]: We should add some delay here before retrying.
Also should reset `isFetching` flag

```
updateIsFetching(false);
setTimeout(() => fetchDefaultDocs(), 500 * (retries));
```

File: app/client/src/components/editorComponents/GlobalSearch/utils.tsx [hunk 5]
```diff
@@ -103,33 +103,77 @@ const defaultDocsConfig = [
...
-    })();
-  }, []);
+    }
+  })();
+};
+
+export const useDefaultDocumentationResults = (modalOpen: boolean) => {
+  const [defaultDocs, setDefaultDocs] = useState<DocSearchItem[]>([]);
+  const [isFetching, updateIsFetching] = useState(false);
+  // usestate
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/GlobalSearch/utils.tsx:170]: Not sure if this is still needed?

**Review by rishabhsaxena — CHANGES_REQUESTED** [review]

File: app/client/src/components/editorComponents/GlobalSearch/utils.tsx (hunk 4 above)
Comment (rishabhsaxena) [reply app/client/src/components/editorComponents/GlobalSearch/utils.tsx:157]: Hey @kaushik94 it just occurred to me, we should not reset `isFetching` flag here, instead we should reset when we're out of retry attempts, ie. within `if (maxRetries >= retries) {}`

Comment (kaushik94) [reply app/client/src/components/editorComponents/GlobalSearch/utils.tsx]: I think you are right, we should set isFetching flag there since we are using setTimeout. When the function is run from the start again, it automatically sets isFetching to true.

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/components/editorComponents/GlobalSearch/utils.test.ts [hunk 6]
```diff
@@ -0,0 +1,20 @@
+import { fetchDefaultDocs } from "./utils";
+
+describe("globalsearch utils", () => {
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/GlobalSearch/utils.test.ts:3]: Should mock `fetchRawGithubContentList` to return the docs results instead of making actual api calls.

**Review by rishabhsaxena — CHANGES_REQUESTED** [review]

File: app/client/src/components/editorComponents/GlobalSearch/utils.test.ts [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+    let documents = [];
+    await fetchDefaultDocs(
+      (truthy: boolean) => {
+        // do nothing for now
+        // to turn off errors
+        expect(truthy === null || typeof truthy === "boolean").toBeTruthy();
+      },
+      (docs: DocSearchItem[]) => {
+        documents = docs;
+        expect(documents.length).toEqual(4);
```
Comment (rishabhsaxena) [inline app/client/src/components/editorComponents/GlobalSearch/utils.test.ts:22]: something looks off, since the mocked fn doesn't run the callback with the documents array, this should always fail?

**Review by rishabhsaxena — CHANGES_REQUESTED** [review]

File: app/client/src/components/editorComponents/GlobalSearch/utils.test.ts (hunk 7 above)
Comment (kaushik94) [reply app/client/src/components/editorComponents/GlobalSearch/utils.test.ts:26]: Yes, the tests pass which means the success callback was never called. Hmm.

**Review by rishabhsaxena — APPROVED** [review]

**Review by rishabhsaxena — APPROVED** [review]

**Review by jsartisan — APPROVED** [review]
