### PR TITLE
Fix/table widget pagination changes

### LINKED ISSUE #731: [BUG] onPageChange is not triggering for client side pagination
## Description
Alert isn't triggering for tableWidget on `onPageChange` action

[Video In Action](https://drive.google.com/file/d/1DU7e1FwxU56sVuKTCvP1cZV_5Cy-CszT/view?usp=sharing).

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

### PR DESCRIPTION
**Pull request by vicky-primathon**
Fixes #731 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

-Workflow is tested manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/TableWidget.tsx [hunk 1]
```diff
@@ -638,6 +636,23 @@ class TableWidget extends BaseWidget<TableWidgetProps, WidgetState> {
     }
   };
 
+  updatePageNumber = (pageNo: number) => {
+    const oldPageNo: number = this.props.pageNo || 1;
+    let event = EventType.ON_NEXT_PAGE;
```
Comment (riodeuno) [inline app/client/src/widgets/TableWidget.tsx:641]: @vicky-primathon  This seems like it will trigger when the user manually enters the same page number. Please check this scenario.

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon @riodeuno is this PR ready to be merged?

**Review by riodeuno — APPROVED** [review]
LGTM
