### PR TITLE
fix: Update success message for reset password link sent

### LINKED ISSUE #11672: [Bug]: Successful Reset password message appears to non registered user id
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user who has not signed up but directly tries to sign with his credentials is redirected to "It looks like you may have entered incorrect/invalid credentials. Please try again or reset password using the button below.
 " When the user clicks on  "Reset Password" and gives non registered email id credentials, it shows a successful message "A password reset link has been sent to abc@c.com". 

https://loom.com/share/386d0679574b42f49fd014f776726266

Expected behavior : The user should be displayed "This emailid/user is not registered with appsmith"

### Steps To Reproduce

1. Go to login page https://release.app.appsmith.com/user/login
2. Give unregistered email and password credentials (abctesting@abctesting.com)
3. A unsuccessful message appears  "It looks like you may have entered incorrect/invalid credentials. Please try again or reset password using the button below."
4. Click on Reset password button.
5. Observe successful message appears.
6. Now edit the email id in the Reset password field and observe the message

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

> If a user who has not signed up, directly tries to sign with his credentials, then the message "It looks like you may have entered incorrect/invalid credentials. Please try again or reset the password using the button below." appears on the login screen.

> If the user clicks on "Reset Password" and gives a non-registered email id, it shows a successful message "A password reset link has been sent to [abc@c.com](mailto:abc@c.com)".

> This PR fixes this issue by updating the successful message to "A password reset link has been sent to your email address  [abc@c.com](mailto:abc@c.com) registered with Appsmith." This had to be done instead of showing error message for nog registered account due to security concerns.

> Another issue fixed under this PR is that if the user tries to change the email address after submitting the reset password form, then the form should be reset instead of just updating the email id in the field as well as successful message.

Fixes #11672 [#185](https://github.com/appsmithorg/appsmith-ee/issues/185)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested if the form gets reset every time we try to change the email id field after the reset password form has already been submitted.
- Tested if the new successful message gets displayed instead of the old one.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: hotfix/reset-pwd-message 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**</details>

### CODE REVIEW

File: app/client/src/pages/UserAuth/ForgotPassword.tsx [hunk 1]
```diff
@@ -64,6 +64,12 @@ export const ForgotPassword = withTheme(
       submitting,
     } = props;
 
+    useEffect(() => {
+      if (submitSucceeded) {
+        props.reset();
```
Comment (sharat87) [inline app/client/src/pages/UserAuth/ForgotPassword.tsx:69]: Ignorant question: This `reset` call will reset the `emailValue` to empty string right? So, if we are emptying the `emailValue` right after a success response from the server, does that mean we won't be able to show the email in the success massage `FORGOT_PASSWORD_SUCCESS_TEXT`? Since that is also using the value of `emailValue` only no?

File: app/client/src/ce/constants/messages.ts [hunk 2]
```diff
@@ -97,8 +97,8 @@ export const FORGOT_PASSWORD_PAGE_TITLE = () => `Reset password`;
 export const FORGOT_PASSWORD_PAGE_SUBTITLE = () =>
   `We will send a reset link to the email below`;
 export const FORGOT_PASSWORD_PAGE_SUBMIT_BUTTON_TEXT = () => `Reset`;
-export const FORGOT_PASSWORD_SUCCESS_TEXT = () =>
-  `A password reset link has been sent to`;
+export const FORGOT_PASSWORD_SUCCESS_TEXT = (email: string) =>
+  `A password reset link has been sent to your email address ${email} registered with Appsmith.`;
```
Comment (sharat87) [inline app/client/src/ce/constants/messages.ts:101]: This sounds as if we are implying that that email is already registered. I'm not sure if that's okay. 🤔

How about a message like on https://github.com/appsmithorg/appsmith/issues/11672#issuecomment-1072271495 cc @hiteshjoshi

Comment (ankitakinger) [reply app/client/src/ce/constants/messages.ts:101]: I checked that message earlier. That can be read like "if the email id exists". What if the user's email id exists, but they are have not registered on Appsmith using the same.

I'd asked @Pranay105 to reframe it for me and he shared the below options:
`We have shared a password reset link to your email address (<aaa@aaa.com>) that exists on Appsmith
OR
We have shared a password reset link to the email address (<aaa@aaa.com>) registered with Appsmith
OR
A password reset link has been sent to your email address (aaa@aaa.com) registered with Appsmith`

**Comment by ankitakinger** [comment]
@RakshaKShetty could you please test this out before I merge it?

**Comment by RakshaKShetty** [comment]
Point 1. The text message has been changed as mentioned above i e "A password reset link has been sent to your email address [abc@c.com](mailto:abc@c.com) registered with Appsmith"
Point 2. When the user tries to re-edit the email id after submitting, the success message won't get edited instead the success message is removed and the user should reenter the email id
Point 3. In Local I couldn't verify the email this part i will be verifying in the release instance

Tested above points LGTM

File: app/client/src/pages/UserAuth/ForgotPassword.tsx (hunk 1 above)
Comment (ankitakinger) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:69]: Nope, it's not right after the success response. This will be reset only when a user tries to change the email value after submit success response is received from the server. `props.emailValue` dependency has been added in this useEffect.

Comment (sharat87) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:69]: Ah I see. Then in that case, say I input `abc@test.com` and click on the Reset button, then I see the green success message, then I try changing the email to `abcd@test.com`, by just inserting a `d`, then the success message goes away, but the email is still `abc@test.com`. The `d` is not inserted. Could it be because of this? It's acting a little weird, I'm not sure what's happening.

https://user-images.githubusercontent.com/120119/159893103-70969af1-1f2e-4f8a-8b31-156d048d799e.mov

Comment (ankitakinger) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:69]: Ohh interesting. When I and Raksha both tested on our end, we both didn't face this. Let me have a look again. Thanks for this.

Comment (ankitakinger) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:75]: this should be fixed now. @RakshaKShetty could you confirm?

**Review by sharat87 — APPROVED** [review]

File: app/client/src/ce/constants/messages.ts (hunk 2 above)
Comment (IAmAnubhavSaini) [inline app/client/src/ce/constants/messages.ts:101]: This message should be `A password reset link has been sent to ${email}, if it is registered with Appsmith.` Or the if part can come first. 

You can get product input on it.

I really hope that we send email only when it is registered with Appsmith.

**Review by albinAppsmith — APPROVED** [review]

**Review by IAmAnubhavSaini — CHANGES_REQUESTED** [review]
The email label and input, and reset button should be hidden on the success screen.

User has submitted their email for password reset, we are not expecting them to send another reset email. There is no use case for email and reset button to be there.

**Review by IAmAnubhavSaini — APPROVED** [review]
It can go as it is ATM.

File: app/client/src/pages/UserAuth/ForgotPassword.tsx (hunk 1 above)
Comment (RakshaKShetty) [reply app/client/src/pages/UserAuth/ForgotPassword.tsx:75]: yes LGTM
