### PR TITLE
fix: radio group widget options

### LINKED ISSUE #6967: [Bug] TypeError: Cannot read property 'map' of undefined
Sentry Issue: [APPSMITH-12K](https://sentry.io/organizations/appsmith/issues/2610821653/?referrer=github_integration)

```
TypeError: Cannot read property 'map' of undefined
  at render (components/designSystems/blueprint/RadioGroupComponent.tsx:55:31)
  at apply (utils/WorkerUtil.ts:176:10)
  at Worker.r (../../src/helpers.ts:87:17)
...
(44 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Fix undefined options of Radio group widget

Fixes #6967  (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix--Radio-group-options-undefined 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.89 **(0.01)** | 36.74 **(0.03)** | 34.2 **(0)** | 55.42 **(0)**
 :green_circle: | app/client/src/widgets/RadioGroupWidget/widget/index.tsx | 84.62 **(0.62)** | 0 **(0)** | 75 **(0)** | 87.5 **(0.54)**
 :green_circle: | app/client/src/workers/validations.ts | 79.65 **(0.5)** | 69.42 **(0.46)** | 73.08 **(0)** | 81.3 **(0.53)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@Tooluloope please add the reproducible steps here for any one to verify

File: app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx [hunk 1]
```diff
@@ -52,16 +52,17 @@ class RadioGroupComponent extends React.Component<RadioGroupComponentProps> {
...
-            return (
-              <Radio
-                className={this.props.isLoading ? "bp3-skeleton" : ""}
-                key={option.value}
-                label={option.label}
-                value={option.value}
-              />
-            );
-          })}
+          {this.props.options &&
```
Comment (riodeuno) [inline app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx:55]: I believe the validations should automatically send in a default `[]` instead of us having to handle this here.

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx (hunk 1 above)
Comment (Tooluloope) [reply app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx:55]: Yeah, I'd remove that

Comment (Tooluloope) [reply app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx:55]: @somangshu We could just delete the PR, I believe the issue has been fixed already

Comment (riodeuno) [reply app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx:55]: Let's update the validations configuration and try to resolve it there. Let's bind the `options` to something which results in `false` or `undefined` and test with the updated validation configurations.

File: app/client/src/workers/validations.ts [hunk 2]
```diff
@@ -522,11 +522,21 @@ export const VALIDATORS: Record<ValidationTypes, Validator> = {
       message: `${WIDGET_TYPE_VALIDATION_ERROR} ${getExpectedType(config)}`,
     };
     if (value === undefined || value === null || value === "") {
-      if (config.params && config.params.required) {
+      if (
+        config.params &&
+        config.params.required &&
+        !isArray(config.params.default)
```
Comment (riodeuno) [inline app/client/src/workers/validations.ts:544]: This will effect the whole application. So we should test this using strings as well. For example if we get `'[]'` instead of `[]`, what would happen?

We should also add this to the unit tests if it isn't already there.

Comment (Tooluloope) [reply app/client/src/workers/validations.ts:544]: Added unit test

**Review by riodeuno — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@Tooluloope Not able to repro the issue did a round of sanity as per the smartlook video and is working fine.

**Comment by somangshu** [comment]
@Tooluloope why didnt we add a test around this?

File: app/client/src/workers/validations.test.ts [hunk 3]
```diff
@@ -855,6 +861,25 @@ describe("Validate Validators", () => {
       expect(result).toStrictEqual(expected[index]);
     });
   });
+  it("correctly validates array when default is given", () => {
```
Comment (Tooluloope) [inline app/client/src/workers/validations.test.ts:864]: @somangshu Added Validation test here

Comment (somangshu) [reply app/client/src/workers/validations.test.ts:864]: Perfect, Apologies for missing this
