### PR TITLE
fix: Paddings and scrolls in Plugin Action Editor

### LINKED ISSUE #31573: [Bug]: Unnecessary scroll in a couple of areas in split panes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We have come across areas that have an unnecessary scroll. It doe not add value.

https://github.com/appsmithorg/appsmith/assets/39921438/df9a0c03-dbb0-40b8-8f17-74867bd5a323

### Steps To Reproduce

1. Login with the below credentials in release:
-username: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
-password: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
2. Add some queries.

You'll notice we get to see scroll that are not needed in a couple of places

### Public Sample App

_No response_

### Environment

Release

### Severity

Low (Inconsistent UI/UX)

### Issue video log

_No response_

### Version

Cloud

### LINKED ISSUE #37214: [Task]: Fix Paddings at various places
Fix the paddings to be as designed. Listed bellow

https://www.notion.so/appsmith/Paddings-margins-and-sizes-are-wrong-12dfe271b0e280ffa8c8cb1a28d4427a?pvs=4

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Updates the padding and fixes the unnecessary scrolls renders in the new Plugin Action Editor flow

Fixes #31573
Fixes #37214

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!IMPORTANT]
> 🟣 🟣 🟣 Your tests are running.
> Tests running at: <https://github.com/appsmithorg/appsmith/actions/runs/11683203062>
> Commit: 73474fd93022c9eabd272225b15c1352b2b88145
> Workflow: `PR Automation test suite`
> Tags: `@tag.Datasource`
> Spec: ``
> <hr>Tue, 05 Nov 2024 11:28:08 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `TabbedViewContainer` for improved layout in the `CommonEditorForm`.
	- Added support for binary file uploads in the `PostBodyData` component.

- **Improvements**
	- Enhanced padding and border behavior in the `Section` component based on the new `withoutPadding` attribute.
	- Adjusted minimum height for the `.CodeMirror` class in the `PostBodyData` component.
	- Improved layout and styling in the `InfoFields` component with new styled components.
	- Updated tooltip content handling in the `DatasourceConfig` component for better clarity on invalid entries.
	- Refined layout behavior in the `CommonEditorForm` with the addition of the `TabbedViewContainer`.
	- Enhanced layout in the `EmbeddedDatasourcePathField` component with updated styling.

- **Bug Fixes**
	- No new bug fixes reported.

- **Refactor**
	- Streamlined the `RequestTabs` component by integrating styles directly into the `Tabs` component.
	- Refined handling of datasource URLs in the `EmbeddedDatasourcePathField` component.
	- Updated styling and structure in the `KeyValueFieldArray` component for improved layout.

### CODE REVIEW

**Review by albinAppsmith — DISMISSED** [review]

File: app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx [hunk 1]
```diff
@@ -52,7 +52,7 @@ const Flex = styled.div<{ size: number }>`
   ${(props) =>
     props.size === 3
       ? `
-    margin-left: 5px;
+    margin-left: 8px;
```
Comment (albinAppsmith) [inline app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx:55]: Can you update using ads token here as well? `var(--ads-v2-spaces-2)`

**Review by albinAppsmith — DISMISSED** [review]
