### PR TITLE
fix: fixed failing queries using aggregation pipeline

### LINKED ISSUE #26090: [Bug]: Deploying applications when using DocumentDB as the DB fails.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The code changes adding via [chore: Improve time to publish application](https://github.com/appsmithorg/appsmith/pull/25516) are not supported by DocumentDB.

Impact of the code change: When creating a new application, it errors out with an Internal Server Error toast message, and also when deploying an application, it errors out with an Internal Server Error toast message.

This is happening because, in order to to improve the publishing time for an application, we set the values of unpublished documents (actions & pages) to the published documents. It uses aggregation update and as mentioned in the [Notion Document](https://www.notion.so/appsmith/Document-DB-aggregates-521b6c3f5cb448079557753900696b05#2686bd1d5e564248b4a67f1134493376), these are not supported by DocumentDB.

### PR DESCRIPTION
**Pull request by tkAppsmith**
#### PR fixes following issue(s)
Fixes #26090
Fixes https://github.com/appsmithorg/appsmith-ee/issues/1659

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/ServerApplication.java [hunk 1]
```diff
@@ -4,12 +4,16 @@
...
 import org.springframework.scheduling.annotation.EnableScheduling;
+import reactor.core.publisher.Hooks;
 
 @SpringBootApplication
 @EnableScheduling
 public class ServerApplication {
 
     public static void main(String[] args) {
+
+        Hooks.onOperatorDebug();
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/ServerApplication.java:15]: Please don't leave this on, there is an IDE configuration that allows you to do this without inserting it in code.

Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/ServerApplication.java:15]: This pr is for evaluation of correctness. Hence a lot of things will be changed as per code style and unit tests. But it seems this will not work as the method used here is getting duplicateKeyException. @nidhi-nair

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java [hunk 2]
```diff
@@ -251,14 +267,55 @@ public Mono<NewPage> findByGitSyncIdAndDefaultApplicationId(
...
+                    mongoOperations.getConverter().write(newPage, document);
+                    document.remove("_id");
+                    return (WriteModel<Document>) new UpdateOneModel<Document>(
+                            new Document("_id", new ObjectId(newPage.getId())), new Document("$set", document));
+                })
+                .collect(Collectors.toList());
+
+        return mongoOperations
+                .getCollection(mongoOperations.getCollectionName(NewPage.class))
+                .flatMapMany(documentMongoCollection -> documentMongoCollection.bulkWrite(dbObjects))
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: Can you please help me understand why the result of a bulk write is split into a list of different `BulkWriteResult` objects?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java [hunk 3]
```diff
@@ -199,9 +200,8 @@ public void testMissingPluginIdAndTypeFixForJSPluginType() {
     @Test
     public void testPublishActionArchivesAndPublishesActions() {
         String applicationId = "dummy-application-id";
-        UpdateResult updateResult = Mockito.mock(UpdateResult.class);
-        Mockito.when(updateResult.getModifiedCount()).thenReturn(10L);
-        Mockito.when(updateResult.getMatchedCount()).thenReturn(5L);
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java:204]: My previous question is because we are losing this insight as a result of this change now. Or is there a way to retain a sense of matched versus modified count?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java [hunk 4]
```diff
@@ -570,16 +577,33 @@ public Flux<NewAction> findByDefaultApplicationId(String defaultApplicationId, O
...
         Criteria applicationIdCriteria =
                 where(fieldName(QNewAction.newAction.applicationId)).is(applicationId);
-        // using aggregation update instead of regular update here
-        // it's required to set a field to a value of another field from the same domain
-        AggregationUpdate aggregationUpdate = AggregationUpdate.update()
-                .set(fieldName(QNewAction.newAction.publishedAction))
-                .toValue("$" + fieldName(QNewAction.newAction.unpublishedAction));
 
-        return updateByCriteria(List.of(applicationIdCriteria), aggregationUpdate, permission);
+        Mono<Set<String>> permissionGroupsMono =
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: Are we not routing these queries based on type of DB?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java [hunk 5]
```diff
@@ -161,7 +161,9 @@ public Flux<T> findAll() {
                 .flatMapMany(principal -> {
                     Query query = new Query(notDeleted());
                     return mongoOperations.find(
-                            query, entityInformation.getJavaType(), entityInformation.getCollectionName());
+                            query.cursorBatchSize(10000),
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java:164]: Does it make sense to either rename this method, or overload it at least?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java (hunk 4 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: Detection of db type is not yet reliable as discussed in last engineering meet.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java (hunk 3 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java:204]: Yes. I agree. I need to think how to incorporate this. I guess we cant get the matched count in the new approach.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java (hunk 2 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: I used an existing method hence Im not sure what the author's use case was. We can modify both the implementations as to retain the existing method interfaces so that the unit test is not affected.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java (hunk 5 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java:164]: Ok. We can accept a cursor size and then pass that argument and in that manner we will be able to override this method.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java (hunk 2 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: I think the bulk write operation return a flux which then requires us to use subscription in caller as well as in unit tests hence it will still need code change. With this list setup I guess the results are getting updated and the above used matched and updated count is irrelevant in this case as all records that we are passing will be overwritten by matching _id.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java (hunk 3 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java:204]: I do see that the new type you are returning has a method defined in its interface for both. This is a minor point, I'm just curious as to why that is not possible here.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java (hunk 4 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: I thought we were going the environment variable route till we found a solution? This would affect larger instances, especially our own cloud instance right?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java (hunk 2 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: Hmm .. Is that because with the aggregation pipeline it is possible to have multiple sets of updates? 🤔 Even in that case, I suppose we'd be interested only in the first entry in this list.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java (hunk 4 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: You mean an env variable set by user?? we thought that approach will be unreliable as users might configure the instance wrongly then things will fail at some point later on in the usage life cycle of app.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java (hunk 2 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: This bulkUpdate method is not run using an aggregation pipeline. I think the usage of reactive mongo interface to do bulk write dictates the return of flux of bulkWriteResult which basically might mean that this stream of objects each might correspond to batches of updates being done to collection.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java (hunk 4 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: We should at least have infrastructure created in code to distinguish between two types of database calls. That is why the environment variable is useful. As of today, the only instance that suffers really badly as a result of these performance problems is cloud. We could choose to not publish information about the environment variable, but we should at least have the provision to use this variable in our own production instance and switch between code paths.

This then also becomes an exercise in making sure that our code structure is designed to support alternate queries as and when required.

Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: The idea here is that whenever we find the reliable identifier for figuring out if an instance is hosting DocDB or Mongo, we can immediately implement that conditional in our code, and switch out of the environment variable way of doing things. One criteria that definitely cannot be overlooked for this effort is that the cloud instance should be able to continue to use the most performant queries all the time.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java (hunk 2 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: Can you please confirm this so we can resolve this thread?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java (hunk 4 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: You mean we should have stubs that read and populate the environment variable and for now they shall be defaulting to mongo only. Im asking this since we are not yet really certain how to detect document db instance with 100% accuracy. The host name in server build confg command can also be proxied.

Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: Let's do it the other way around, unless mentioned in the environment variable, we can use DocDb. And then in our own cloud instances we can set the variable up.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java [hunk 6]
```diff
@@ -251,14 +267,55 @@ public Mono<NewPage> findByGitSyncIdAndDefaultApplicationId(
...
-        AggregationUpdate aggregationUpdate = AggregationUpdate.update()
-                .set(fieldName(QNewPage.newPage.publishedPage))
-                .toValue("$" + fieldName(QNewPage.newPage.unpublishedPage));
 
-        return updateByCriteria(List.of(applicationIdCriteria), aggregationUpdate, permission);
+        Mono<Set<String>> permissionGroupsMono =
+                getCurrentUserPermissionGroupsIfRequired(Optional.ofNullable(permission));
+
+        return permissionGroupsMono.flatMap(permissionGroups -> {
+            AggregationOperation matchAggregationWithPermission = null;
```
[the remark this answers is not in the document]
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:277]: I have done the necessary instrumentation for the changed queries on local. First I compared the application creation flow between release and this branch changes. I have selected application creation flow because it was the flow that invokes these queries. There is x10 difference in comparison in some apis (get pages and get actions) ie this branch is x10 slower. But workspace create application api call (applications?workspaceId={workspace}) is faster on this branch (x5 - x10). Hence I deduced that there are recent changes on release that have bought these optimisations on the unrelated get api calls. I then proceeded to revert all these changes in the current branch and retried to application creation flow and the numbers still stand at x10 for the get pages and get actions calls which means the faster api calls are due to optimisations made on the release branch and hence we can safely merge in these changes and they won’t have performance implications as such.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java (hunk 2 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: I ran some logs on the current approach. It seems the flux is returned because of batch based updates, where each element has its own matched and updated count. The current implemetation seems to be blocking because it converts the flux to list and returns a mono of that. We can change that to make it return a flux of write result but it will need to change both the methods and then corresponsing changes in service caller layer. We can take this up as refactoring work afterwards since this will need some amount of code changes and re review and performance metrics.

Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: And for the total number of matched and updated counts, we will have to finally convert the flux to list and then sum up the counts of each element to get the total counts due to async nature of this operation.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java (hunk 4 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:584]: Can we take this up as a separate initiate, We have some bugs still left to fix for doc db and we can club this initiative with them in next sprint. Right now the performance instrumentation shows no great effect of these query changes on api call response times.

**Comment by tkAppsmith** [comment]
Open items issues:
Async bulk update: https://github.com/appsmithorg/appsmith/issues/27138
Overload or different name method with cursorbatchsize: https://github.com/appsmithorg/appsmith/issues/27139
Code toggle/routing for document db connected instances: https://github.com/appsmithorg/appsmith/issues/27140

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java (hunk 5 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java:164]: https://github.com/appsmithorg/appsmith/issues/27139

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java (hunk 4 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java:585]: https://github.com/appsmithorg/appsmith/issues/27140

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java (hunk 2 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java:318]: https://github.com/appsmithorg/appsmith/issues/27138

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java (hunk 3 above)
Comment (tkAppsmith) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java:204]: https://github.com/appsmithorg/appsmith/issues/27138

**Review by nidhi-nair — APPROVED** [review]
LGTM, is there anything from @nayan-rafiq 's comments that needs changing @tkAppsmith ?

**Comment by tkAppsmith** [comment]
Hey nidhi. I have done as requested by @nayan-rafiq . He also has a comment if we can scope out moving bulk update to the base repository. I can add this in one of the issues we have taken up as part of next iteration of enhancements on this part of work.

**Comment by btsgh** [comment]
Since, this same code change was regression tested on EE DP raised for Doc DB, and the issues for which this one was targeted are working, adding TestPlanApproved label. cc: @tkAppsmith
