### PR TITLE
fix: Passsing dataTreePath to CodeEditor for AI events

### LINKED ISSUE #26690: Params missing in AI events - Passsing dataTreePath to CodeEditor for AI events

### PR DESCRIPTION
**Pull request by Druthi**
## Description
Fixed issue where the propertyPath, widgetType was not being passed to the AI events. 

##PR fixes following issue(s)
Fixes #26690 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/components/propertyControls/ColumnActionSelectorControl.tsx [hunk 1]
```diff
@@ -60,6 +60,7 @@ class ColumnActionSelectorControl extends BaseControl<ColumnActionSelectorContro
                   <ActionCreator
                     action={this.props.label}
                     additionalControlData={{}}
+                    dataTreePath={""}
```
Comment (Rishabh-Rathod) [inline app/client/src/components/propertyControls/ColumnActionSelectorControl.tsx:63]:
```suggestion
                    dataTreePath=""
```

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM.

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM
