### PR TITLE
fix: Snowflake error msg fix on test datasource timeout

### LINKED ISSUE #16140: [Bug]-[116]:On trying to configure snowflake db - no error is thrown if incorrect details are entered.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Snowflake DB -
If I enter any random values in the DB details screen (for account name, warehouse, etc) , and click test - no error is thrown.
The circular progress on Test button just goes on and on, and after 30.1s it just stops on the same screen. It is not clear to the user if the DB connection has been made/ has been tested successfully or if there is an issue.

### Steps To Reproduce

1. Click on new data source and select snowflake.
2. Enter random values in the db details screen. Click Test.

The circular progress on Test button just goes on and on, and after 30.1s it just stops on the same screen. It is not clear to the user if the DB connection has been made/ has been tested successfully or if there is an issue.

Expected behavior - Some information should be given to user on the status of the connection.

### Public Sample App

_No response_

### Version

Release

### LINKED ISSUE #22035: [Bug]: Error message missing in case of wrong account name.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user enters a wrong account number, there is no error message shown.

### Steps To Reproduce

1. Create a snowflake datasource with the valid credentials except the Account name
2. Click on test

Observe - There is no error message shown

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/BfkSaKyWb6Bg3p2Z

### Version

1.9.12

### PR DESCRIPTION
**Pull request by PiyushPushkar02**
## Description

- Set a flag called InitializationFailTimeout to -1 to create the connection pool asynchronously.
- Set the **connectionTimeout** value to timeout to handle any issue with the connection as the pool is getting created asynchronously now.
- Changed the error message returned to the user for an invalid Snowflake URL.

Fixes #16140 
Fixes #22035 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Junit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java [hunk 1]
```diff
@@ -174,6 +174,13 @@ private static HikariDataSource createConnectionPool(DatasourceConfiguration dat
 
             config.setMinimumIdle(MINIMUM_POOL_SIZE);
             config.setMaximumPoolSize(MAXIMUM_POOL_SIZE);
+            /**
+             * Setting the value for setInitializationFailTimeout to -1 to
+             * bypass any connection attempt and validation during startup
+             * @see https://www.javadoc.io/doc/com.zaxxer/HikariCP/latest/com/zaxxer/hikari/HikariConfig.html
+             */
+            config.setInitializationFailTimeout(-1);
+            config.setConnectionTimeout(25000);
```
Comment (sumitsum) [inline app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java:183]: Hi Piyush, can you please create a macro for the value `25000`, but leave -1 as it is because it is an unusual value and should be better to keep it more visible ?

File: app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java [hunk 2]
```diff
@@ -174,6 +175,13 @@ private static HikariDataSource createConnectionPool(DatasourceConfiguration dat
 
             config.setMinimumIdle(MINIMUM_POOL_SIZE);
             config.setMaximumPoolSize(MAXIMUM_POOL_SIZE);
+            /**
+             * Setting the value for setInitializationFailTimeout to -1 to
```
Comment (sumitsum) [inline app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java:179]: Nice to add comment here :)

**Review by sumitsum — APPROVED** [review]
