### PR TITLE
chore: fix menu widget bugs

### LINKED ISSUE #38202: Menu Widget bugs
- [ ]  Menu Doesn’t open
- [ ]  Hide Dynamic Option

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #38202 

/ok-to-test tags="@tag.Anvil"

## Summary by CodeRabbit

- **New Features**
	- Introduced a new configuration for widget sizing and characteristics.
	- Enhanced menu functionality with clearer item rendering and interaction.

- **Bug Fixes**
	- Improved type safety and compatibility in menu item processing.

- **Refactor**
	- Updated configuration handling for menu items, transitioning to a more generic structure.
	- Rearranged export statements for better organization.

- **Documentation**
	- Updated method signatures and interface definitions for better clarity and usability.

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12392606404>
> Commit: ade8c87e56c003a3d5c733f9c66a2ac4345f7158
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12392606404&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Anvil`
> Spec:
> <hr>Wed, 18 Dec 2024 12:33:31 UTC

### CODE REVIEW

File: app/client/src/modules/ui-builder/ui/wds/WDSMenuButtonWidget/config/propertyPaneConfig/contentConfig.ts [hunk 1]
```diff
@@ -43,6 +43,7 @@ export const propertyPaneContentConfig = [
         isTriggerProperty: false,
         validation: { type: ValidationTypes.TEXT },
         updateHook: updateMenuItemsSource,
+        hidden: () => true,
```
Comment (KelvinOm) [inline app/client/src/modules/ui-builder/ui/wds/WDSMenuButtonWidget/config/propertyPaneConfig/contentConfig.ts:46]: Why are we doing this again? Could you leave a comment about this?

**Review by KelvinOm — APPROVED** [review]

File: app/client/src/modules/ui-builder/ui/wds/WDSMenuButtonWidget/config/propertyPaneConfig/contentConfig.ts (hunk 1 above)
Comment (jsartisan) [reply app/client/src/modules/ui-builder/ui/wds/WDSMenuButtonWidget/config/propertyPaneConfig/contentConfig.ts:46]: We are just hiding the option of creating dynamic menu items.

This one.
CleanShot 2024-12-19 at 11 11 40
