### PR TITLE
fix: build error due to fn name change, copy node_modules on mac error

### LINKED ISSUE #16875: [Bug]: RTS build error due to import wrong exported AST function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Tsc Alias was not working as there was a wrong import of function which was exported from AST shared module which resulted in the below error 

> appsmith    | backend stdout | [2022-09-19 05:45:20,111]  - Multiple Spring Data modules found, entering strict repository configuration mode!
appsmith    | backend stdout | [2022-09-19 05:45:20,112]  - Bootstrapping Spring Data Reactive MongoDB repositories in DEFAULT mode.
appsmith    | backend stdout |
appsmith    | rts stdout | internal/modules/cjs/loader.js:905
appsmith    | rts stdout |   throw err;
appsmith    | rts stdout |   ^
appsmith    | rts stdout |
appsmith    | rts stdout | Error: Cannot find module '@controllers/socket'
appsmith    | rts stdout | Require stack:
appsmith    | rts stdout | - /opt/appsmith/rts/sockets/mongo.js
appsmith    | rts stdout | - /opt/appsmith/rts/sockets/index.js
appsmith    | rts stdout | - /opt/appsmith/rts/server.js
appsmith    | rts stdout |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
appsmith    | rts stdout |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
appsmith    | rts stdout |     at Module.require (internal/modules/cjs/loader.js:974:19)
appsmith    | rts stdout |     at require (internal/modules/cjs/helpers.js:101:18)
appsmith    | rts stdout |     at Object.<anonymous> (/opt/appsmith/rts/sockets/mongo.js:18:18)
appsmith    | rts stdout |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
appsmith    | rts stdout |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
appsmith    | rts stdout |     at Module.load (internal/modules/cjs/loader.js:950:32)
appsmith    | rts stdout |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
appsmith    | rts stdout |     at Module.require (internal/modules/cjs/loader.js:974:19) {
appsmith    | rts stdout |   code: 'MODULE_NOT_FOUND',
appsmith    | rts stdout |   requireStack: [
appsmith    | rts stdout |     '/opt/appsmith/rts/sockets/mongo.js',
appsmith    | rts stdout |     '/opt/appsmith/rts/sockets/index.js',
appsmith    | rts stdout |     '/opt/appsmith/rts/server.js'
appsmith    | rts stdout |   ]
appsmith    | rts stdout | }
appsmith    | rts stdout |

### Steps To Reproduce

1. Try building RTS server
2. You will see the error on the console

### Public Sample App

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description

- Due to change in the function name in the AST shared module, rts build was not getting completed successfully which was giving errors for the file aliasing.
- Copy of node_modules was not working on the mac machine due to `-L` flag, so added a `Or` condition to run the same command with `-r` only.

Fixes #16875

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/rts/build.sh [hunk 1]
```diff
@@ -8,4 +8,4 @@ npx tsc && npx tsc-alias
 # Copying node_modules directory into dist as rts server requires node_modules to run server build properly. 
 # This was previously being done in dockerfile which was copying the symlinks to image rather than the whole directory of shared modules (e.g. AST)
 # Also, we copy node_modules with -L flag in order to follow the symlinks for @shared folder and copy the contents instead of just the symlink
-cp -rL node_modules ./dist
+cp -rL node_modules ./dist || cp -r node_modules ./dist
```
Comment (mohanarpit) [inline app/rts/build.sh:11]: Can we please add a comment here explaining why we have the `||` condition?

Comment (AmanAgarwal041) [reply app/rts/build.sh:11]: Yeah adding comments.

Comment (sharat87) [reply app/rts/build.sh:12]: We can check this later, but I think just a `cp -RL node_modules ./dist` would work on both macOS and Linux.

Comment (AmanAgarwal041) [reply app/rts/build.sh]: Updated the command.

**Review by mohanarpit — APPROVED** [review]
