### PR TITLE
fix: Reset app, page and widget details when switching between apps

### LINKED ISSUE #12871: [Docs] #11986 [Bug]: Navigate CTA in omnibar shows widgets and pages of the other apps with label undefined, on clicking one of these undefined widgets, it clones the other app’s page.
> TODO 

 - [ ] Evaluate if this task is needed. If not add the "Skip Docs" label on the parent ticket 
- [ ] Fill these fields 
- [ ] Prepare first draft 
- [ ] Add label: "Ready for Docs Team" 

Field | Details 
-----|----- 
**POD** | New Developers Pod 
**Parent Ticket** | #11986
Engineer | 
Release Date | 
Live Date | 
First Draft | 
Auto Assign | 
Priority | 
Environment |

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
When switching between apps, we do not reset the widgets state in the reducer causing the widgets from other apps to show up in the omnibar. 
This was working fine earlier because used to do a full reload while launching an app in edit mode.

Fixes #12871 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/11986-entities-from-other-apps-omnibar 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.49 **(0)** | 37.99 **(0)** | 36.28 **(-0.01)** | 56.71 **(0)**
 :red_circle: | app/client/src/actions/pageActions.tsx | 67.92 **(-0.08)** | 25 **(0)** | 25 **(-1.67)** | 59.15 **(1.18)**
 :red_circle: | app/client/src/reducers/entityReducers/pageListReducer.tsx | 26.92 **(-0.53)** | 30 **(0)** | 23.81 **(-1.19)** | 29.79 **(-0.64)**
 :red_circle: | app/client/src/reducers/uiReducers/pageCanvasStructureReducer.ts | 71.43 **(-11.9)** | 50 **(0)** | 50 **(-25)** | 76.92 **(-6.41)**
 :green_circle: | app/client/src/sagas/ApplicationSagas.tsx | 20.81 **(0.27)** | 4.08 **(0)** | 9.09 **(0)** | 23.89 **(0.31)**
 :red_circle: | app/client/src/sagas/InitSagas.ts | 50.56 **(-0.87)** | 36.67 **(0)** | 58.33 **(0)** | 54 **(-1.1)**</details>

### CODE REVIEW

File: app/client/src/reducers/uiReducers/applicationsReducer.tsx [hunk 1]
```diff
@@ -126,6 +126,7 @@ const applicationsReducer = createReducer(initialState, {
     currentApplication: action.payload,
     isFetchingApplication: false,
   }),
+  [ReduxActionTypes.RESET_APPLICATION]: () => initialState,
```
Comment (akash-codemonk) [inline app/client/src/reducers/uiReducers/applicationsReducer.tsx:129]: Do we want to reset the whole reducer to it's initial state? This also resets the application list stored here.

**Review by akash-codemonk — CHANGES_REQUESTED** [review]

File: app/client/src/reducers/uiReducers/applicationsReducer.tsx (hunk 1 above)
Comment (arunvjn) [reply app/client/src/reducers/uiReducers/applicationsReducer.tsx]: Not sure if we need the application list when were are in edit/view mode. 
We fetch application list every time we visit the dashboard as well. 
I have remove it for now since we do not need it to fix this particular issue. Will add that change in a different PR.

**Review by akash-codemonk — DISMISSED** [review]

**Review by akash-codemonk — APPROVED** [review]
