### PR TITLE
fix: empty form data in API pane

### LINKED ISSUE #5756: [Bug] Do not send empty key-value pairs from the API pane to the backend
## Description

We are currently sending empty key-value pairs from the API pane to the backend. 

apiempty1

When they are sent, the server returns an error

`"'name' must not be empty"`

apierror2

The empty rows/pairs are difficult to spot on and cause errors which is difficult to spot on.   I just spend an hour debugging this error just to find that there was an empty row left. And the [user](https://discord.com/channels/725602949748752515/760761686549463060/862754799568027698) also spent a lot of time figuring this out.

### Steps to reproduce the behaviour:

1. Add empty row to the API pane
2. Send the request
3. See error

### Important Details

- Version: Cloud
- Environment: Production

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Removes empty key value pair from headers, query parameters and form data thereby avoid execution failures from this.

Fixes #5756 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/empty-form-data 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55 **(0.01)** | 36.9 **(0.02)** | 33.87 **(0.02)** | 55.55 **(0.01)**
 :green_circle: | app/client/src/transformers/RestActionTransformer.ts | 95.83 **(1.71)** | 81.82 **(0.57)** | 100 **(0)** | 100 **(0)**</details>

### CODE REVIEW

File: app/client/src/transformers/RestActionTransformer.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { HTTP_METHODS } from "constants/ApiEditorConstants";
 import { ApiAction } from "entities/Action";
-import _ from "lodash";
+import _, { isEmpty } from "lodash";
```
Comment (ApekshaBhosale) [inline app/client/src/transformers/RestActionTransformer.ts:3]: remove _ or remove isEmpty, _ has already isEmpty

**Review by ApekshaBhosale — CHANGES_REQUESTED** [review]

File: app/client/src/transformers/RestActionTransformer.ts (hunk 1 above)
Comment (arunvjn) [reply app/client/src/transformers/RestActionTransformer.ts]: Done

File: app/client/src/transformers/RestActionTransformer.ts [hunk 2]
```diff
@@ -41,5 +41,22 @@ export const transformRestAction = (data: ApiAction): ApiAction => {
...
+    action.actionConfiguration.queryParameters,
+  );
+
   return action;
 };
+
+function removeEmptyPairs(keyValueArray: any) {
+  if (!keyValueArray || !keyValueArray.length) return keyValueArray;
+  return keyValueArray.filter(
+    (data: any) => !_.isEmpty(data.key) || !_.isEmpty(data.value),
```
[the remark this answers is not in the document]
Comment (arunvjn) [reply app/client/src/transformers/RestActionTransformer.ts:60]: In a scenario where the user fills in the 'key' and navigates away from the page to look up a widget from where needs the data, he might loose the entry he has made against the key property.

**Review by hetunandu — APPROVED** [review]

**Review by ApekshaBhosale — APPROVED** [review]
