### PR TITLE
fix: add binding paths for new UQI components

### LINKED ISSUE #11160: [Bug]: UQI form control components not setting evaluation order
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

evaluation order is not getting set for form inputs in the new components. Likely cause is that some of these paths are created on the fly within these component definitions.

### Steps To Reproduce

https://theappsmith.slack.com/archives/C02KTH6EHUG/p1644904919405449?thread_ts=1644833232.546069&cid=C02KTH6EHUG

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by rashmi-rai**
## Description

This PR adds logic to create binding paths for new UQI compoents i.e. Sorting, Pagination and EntitySelector.
Form components that uses FormControl to render other components also requires handling of binding paths. 

Fixes #11160

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?
Tested with following components:
- Sorting
- Pagination

Tested with mock data:
- Entity selector

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/create-binding-path 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.72 **(-0.01)** | 37.05 **(0)** | 35.79 **(-0.01)** | 56.08 **(-0.02)**
 :red_circle: | app/client/src/components/formControls/EntitySelectorControl.tsx | 56 **(-0.52)** | 35.29 **(0)** | 0 **(0)** | 56 **(-0.52)**
 :red_circle: | app/client/src/components/formControls/PaginationControl.tsx | 58.82 **(-1.18)** | 50 **(0)** | 25 **(0)** | 57.58 **(-1.04)**
 :red_circle: | app/client/src/components/formControls/SortingControl.tsx | 55 **(-0.56)** | 59.26 **(0)** | 11.11 **(0)** | 55 **(-0.56)**
 :green_circle: | app/client/src/components/formControls/WhereClauseControl.tsx | 32.86 **(0.05)** | 35.9 **(0)** | 0 **(0)** | 32.86 **(0.05)**
 :green_circle: | app/client/src/components/formControls/utils.ts | 93.62 **(0.94)** | 79.1 **(2.05)** | 100 **(0)** | 94.12 **(0.97)**
 :red_circle: | app/client/src/entities/Action/actionProperties.ts | 55.79 **(-21.57)** | 40 **(-15.26)** | 40 **(-26.67)** | 51.16 **(-23.84)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

File: app/client/src/entities/Action/actionProperties.ts [hunk 1]
```diff
@@ -110,12 +110,51 @@ export const getBindingPathsOfAction = (
...
+            bindingPaths[
+              `${configPath}[${index}].order`
+            ] = getCorrectEvaluationSubstitutionType(
+              formConfig.evaluationSubstitutionType,
+            );
+          });
+        }
+      } else if (formConfig.controlType === "ENTITY_SELECTOR") {
+        if (Array.isArray(formConfig.schema)) {
+          const allowedControlTypes = ["DROP_DOWN", "QUERY_DYNAMIC_INPUT_TEXT"];
```
Comment (AmanAgarwal041) [inline app/client/src/entities/Action/actionProperties.ts:142]: Try using the allowedTypes from the entitySelector control, so that if any other control type is added in future, then chance of forgetting to add the control type here would not be an option.

Comment (rashmi-rai) [reply app/client/src/entities/Action/actionProperties.ts]: Done

**Review by AmanAgarwal041 — APPROVED** [review]
LGTM

**Review by Irongade — APPROVED** [review]
Code looks good, but seems client build is failing, please review that.

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by Irongade — APPROVED** [review]
