### PR TITLE
Fixes related to the comments feature

### LINKED ISSUE #5677: [Enhancement] Comment Tab should be hidden behind Invite User Modal overlay
When clicking on the share button to invite users comment tab ideally should be hidden behind the modal.
  
Screenshot 2021-07-07 at 7 55 14 PM

### LINKED ISSUE #5697: [Bug] Reset comment mode on navigating away from the canvas
- Also check if the option for setting comment modes within `NavigationMenu` at edit app name is hidden

### LINKED ISSUE #5813: [Bug] Comments added on the empty canvas get repositioned after new elements are added
## Description
Comments added on the empty canvas get repositioned after new elements are added since the container height is changed

### Steps to reproduce the behaviour:

1. Create a new app
2. Add some comments on the empty canvas
3. Drag a widget to the canvas
4. Notice the position of the pin is updated

### LINKED ISSUE #5879: [Task] Typing @appsmith should prompt the user to invite support@appsmith.com to their app

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
Show modal when clicking on the comment card from the sidebar if comment is left on a modal

- Fixes #5677
- Fixes #5813
- Fixes #5697 
- Fixes #5879
- Mentions list related fixes:
  - Trigger invite on selecting appsmith from the list
  - Overflow: ellipses
- Permissions fix
    - `useOrgUsers`: any app user (invited) can fetch org users
    - fix error while opening share modal as a non-app user on a public app

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: collab-fixes-1-cherry-picked 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.85 **(-1.75)** | 33.53 **(-1.82)** | 29.9 **(-2.24)** | 52.52 **(-1.64)**
 :red_circle: | app/client/src/actions/commentActions.ts | 73.77 **(-6.56)** | 100 **(0)** | 25.64 **(-20.51)** | 72.58 **(-4.84)**
 :red_circle: | app/client/src/actions/initActions.ts | 80 **(-10)** | 100 **(0)** | 33.33 **(-33.34)** | 100 **(0)**
 :red_circle: | app/client/src/api/Api.ts | 77.78 **(-7.41)** | 20 **(-20)** | 50 **(-16.67)** | 77.78 **(-7.41)**
 :red_circle: | app/client/src/api/CommentsAPI.tsx | 64.29 **(-14.28)** | 100 **(0)** | 9.09 **(-36.36)** | 62.96 **(-14.82)**
 :red_circle: | app/client/src/comments/utils.ts | 34 **(-58.31)** | 0 **(-25)** | 0 **(-66.67)** | 24.39 **(-66.24)**
 :red_circle: | app/client/src/comments/CommentCard/CommentCard.tsx | 32.78 **(-39.89)** | 23.14 **(-40.11)** | 7.14 **(-35.72)** | 34.52 **(-38.61)**
 :red_circle: | app/client/src/comments/CommentCard/CommentContextMenu.tsx | 24.49 **(-55.1)** | 45.45 **(-36.37)** | 0 **(-33.33)** | 26.09 **(-54.34)**
 :red_circle: | app/client/src/comments/CommentCard/ResolveCommentButton.tsx | 26.92 **(-65.39)** | 40 **(-30)** | 0 **(-80)** | 29.17 **(-62.5)**
 :red_circle: | app/client/src/comments/CommentThread/CommentThread.tsx | 28.3 **(-64.15)** | 6.45 **(-55.92)** | 0 **(-81.82)** | 30.61 **(-65.31)**
 :red_circle: | app/client/src/comments/CommentThread/ScrollToLatest.tsx | 57.14 **(-42.86)** | 100 **(0)** | 0 **(-100)** | 61.54 **(-38.46)**
 :red_circle: | app/client/src/comments/inlineComments/AddCommentInput.tsx | 24.64 **(-49.7)** | 8.42 **(-34.08)** | 0 **(-65)** | 27.64 **(-47.11)**
 :red_circle: | app/client/src/comments/inlineComments/Comments.tsx | 30.3 **(-66.67)** | 0 **(-87.5)** | 0 **(-100)** | 33.33 **(-66.67)**
 :red_circle: | app/client/src/comments/inlineComments/InlineCommentPin.tsx | 30.16 **(-54.84)** | 9.52 **(-50)** | 0 **(-85.71)** | 33.33 **(-52.38)**
 :red_circle: | app/client/src/comments/inlineComments/OverlayCommentsWrapper.tsx | 74.19 **(-22.58)** | 37.5 **(-37.5)** | 50 **(-50)** | 74.07 **(-25.93)**
 :red_circle: | app/client/src/comments/inlineComments/UnpublishedCommentThread.tsx | 43.75 **(-45.14)** | 50 **(0)** | 0 **(-71.43)** | 50 **(-38)**
 :red_circle: | app/client/src/comments/inlineComments/useOrgUsers.tsx | 44.44 **(-51.01)** | 0 **(-77.78)** | 0 **(-100)** | 44.44 **(-51.01)**
 :red_circle: | app/client/src/components/ads/Button.tsx | 91.41 **(-0.78)** | 74.19 **(-5.38)** | 90.7 **(-2.32)** | 92.06 **(-0.8)**
 :red_circle: | app/client/src/components/ads/EmojiPicker.tsx | 42.86 **(-42.85)** | 0 **(-100)** | 0 **(-33.33)** | 47.37 **(-36.84)**
 :red_circle: | app/client/src/components/ads/EmojiReactions.tsx | 24.14 **(-15.52)** | 18.52 **(-9.26)** | 5.88 **(-5.88)** | 28 **(-12)**
 :red_circle: | app/client/src/components/ads/Icon.tsx | 48.94 **(-7.05)** | 32.5 **(-8.33)** | 100 **(0)** | 48.76 **(-7.07)**
 :red_circle: | app/client/src/components/ads/MentionsInput.tsx | 30.12 **(-35.67)** | 29.63 **(-9.95)** | 4.35 **(-22.92)** | 32.89 **(-30.88)**
 :red_circle: | app/client/src/components/ads/tour/TourTooltipWrapper.tsx | 48.48 **(-48.29)** | 15.79 **(-53.65)** | 0 **(-80)** | 50 **(-46.77)**
 :green_circle: | app/client/src/configs/index.ts | 95.56 **(0)** | 84 **(0.33)** | 100 **(0)** | 97.56 **(0)**
 :red_circle: | app/client/src/constants/messages.ts | 69.38 **(-1.41)** | 100 **(0)** | 7.44 **(-4.24)** | 76.43 **(0.08)**
 :red_circle: | app/client/src/constants/routes.ts | 81.95 **(-2.26)** | 38.04 **(-5.44)** | 61.11 **(-5.56)** | 80 **(-2.61)**
 :red_circle: | app/client/src/pages/Applications/permissionHelpers.tsx | 92.31 **(-7.69)** | 100 **(0)** | 50 **(-50)** | 91.67 **(-8.33)**
 :red_circle: | app/client/src/pages/common/ProfileImage.tsx | 30 **(-60)** | 12.5 **(-50)** | 0 **(-71.43)** | 33.33 **(-55.56)**
 :red_circle: | app/client/src/pages/organization/AppInviteUsersForm.tsx | 48.57 **(0)** | 15 **(-0.79)** | 0 **(0)** | 48.57 **(0)**
 :red_circle: | app/client/src/reducers/entityReducers/pageListReducer.tsx | 22.22 **(0)** | 22.22 **(-5.56)** | 23.08 **(0)** | 25 **(0)**
 :red_circle: | app/client/src/reducers/uiReducers/editorReducer.tsx | 19.12 **(-2.94)** | 0 **(0)** | 13.04 **(-8.7)** | 19.12 **(-2.94)**
 :red_circle: | app/client/src/reducers/uiReducers/commentsReducer/commentsReducer.ts | 39.19 **(-6.76)** | 14.29 **(-21.42)** | 37.04 **(-18.52)** | 44.62 **(-7.69)**
 :red_circle: | app/client/src/sagas/ErrorSagas.tsx | 53.98 **(-14.16)** | 28.57 **(-23.81)** | 38.89 **(-11.11)** | 52.94 **(-15.69)**
 :red_circle: | app/client/src/sagas/InitSagas.ts | 45.45 **(-5.46)** | 8.57 **(-11.43)** | 50 **(-16.67)** | 48.39 **(-4.3)**
 :red_circle: | app/client/src/sagas/CommentSagas/index.ts | 16.31 **(-29.14)** | 14.71 **(-3.15)** | 15.79 **(-34.21)** | 20 **(-24.12)**
 :red_circle: | app/client/src/sagas/WebsocketSagas/WebsocketSagas.ts | 18.75 **(-10.94)** | 10.53 **(-5.26)** | 13.33 **(-13.34)** | 22.22 **(-11.11)**
 :red_circle: | app/client/src/selectors/appViewSelectors.tsx | 56.25 **(-12.5)** | 0 **(0)** | 0 **(-28.57)** | 60 **(-6.67)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 37.25 **(-5.17)** | 15.63 **(3.96)** | 12 **(-28)** | 31.51 **(-3.27)**
 :red_circle: | app/client/src/selectors/organizationSelectors.tsx | 65.12 **(-4.65)** | 0 **(0)** | 21.05 **(-10.53)** | 62.96 **(-3.71)**
 :red_circle: | app/client/src/utils/AppsmithUtils.tsx | 46.37 **(-7.82)** | 23.26 **(-3.48)** | 29.73 **(-8.11)** | 41.94 **(-7.74)**
 :red_circle: | app/client/src/utils/helpers.tsx | 53.46 **(-0.13)** | 26.03 **(-0.73)** | 22.22 **(-0.86)** | 47.2 **(-0.3)**
 :red_circle: | app/client/src/utils/hooks/useIsScrolledToBottom.tsx | 14.29 **(-80.95)** | 0 **(-70.83)** | 0 **(-100)** | 20 **(-80)**
 :red_circle: | app/client/src/utils/hooks/useOrg.tsx | 47.06 **(-41.18)** | 0 **(-27.27)** | 0 **(-100)** | 50 **(-37.5)**
 :red_circle: | app/client/src/utils/hooks/useProceedToNextTourStep.tsx | 93.75 **(-6.25)** | 20 **(-20)** | 75 **(-25)** | 100 **(0)**
 :red_circle: | app/client/test/customQueries.js | 90 **(-5)** | 100 **(0)** | 33.33 **(-33.34)** | 89.47 **(-5.27)**
 :x: | ~~app/client/src/comments/tests/setMockPages.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~</details>

### CODE REVIEW

File: app/client/src/comments/inlineComments/InlineCommentPin.tsx [hunk 1]
```diff
@@ -164,12 +181,17 @@ function InlineCommentPin({
...
+      leftPercent={leftPercent}
       onClick={(e: any) => {
         // capture clicks so that create new thread is not triggered
         e.preventDefault();
         e.stopPropagation();
       }}
+      positionAbsolutely={positionAbsolutely}
       top={top}
+      topPercent={topPercent}
+      xOffset={"- 1"}
```
Comment (Rishabh-Rathod) [inline app/client/src/comments/inlineComments/InlineCommentPin.tsx:193]: why is there a space between `-` (minus) and number? for eg:- `xOffset={"- 1"}`

Comment (rishabhsaxena) [reply app/client/src/comments/inlineComments/InlineCommentPin.tsx:193]: actually offset can be -ve or +ve
should I add a comment here?

File: app/client/src/components/ads/tour/TourTooltipWrapper.tsx [hunk 2]
```diff
@@ -74,6 +74,9 @@ function TourTooltipWrapper(props: Props) {
     };
   }, [isOpen, dotRef?.current]);
 
+  // eslint-disable-next-line
+  if (!isOpen) return <>{children}</>;
```
Comment (Rishabh-Rathod) [inline app/client/src/components/ads/tour/TourTooltipWrapper.tsx:78]: `return children;` directly should work here.

Comment (rishabhsaxena) [reply app/client/src/components/ads/tour/TourTooltipWrapper.tsx:78]: I was getting a TS error here, would check

File: app/client/src/comments/inlineComments/InlineCommentPin.tsx (hunk 1 above)
Comment (Rishabh-Rathod) [inline app/client/src/comments/inlineComments/InlineCommentPin.tsx:193]: wouldn't it be better to accept `xOffset` and `yOffset` as number and then convert them to string. Avoid invalid string values for xOffset like instead of "- 1" if someone enters "-1 px"

File: app/client/src/comments/inlineComments/UnpublishedCommentThread.tsx [hunk 3]
```diff
@@ -46,6 +62,10 @@ function UnpublishedCommentThread({
     dispatch(createCommentThreadAction({ commentBody: text, commentThread }));
   };
 
+  const positionAbsolutely = getShouldPositionAbsolutely(commentThread);
+
+  console.log(commentThread, "commentThread");
```
Comment (Rishabh-Rathod) [inline app/client/src/comments/inlineComments/UnpublishedCommentThread.tsx:67]: Maybe you missed removing the log from here.

File: app/client/src/comments/utils.ts [hunk 4]
```diff
@@ -121,3 +127,40 @@ export const getCommentThreadURL = ({
...
+ * main container canvas since the height
+ * can change dynamically
+ */
+export const getPosition = (props: {
+  top: number;
+  left: number;
+  leftPercent: number;
+  topPercent: number;
+  positionAbsolutely: boolean;
+  xOffset?: string;
```
Comment (Rishabh-Rathod) [inline app/client/src/comments/utils.ts:142]: `xOffset` and `yOffset` here can be numbers and then are converted to a string.

File: app/client/src/components/ads/tour/TourTooltipWrapper.tsx (hunk 2 above)
Comment (rishabhsaxena) [reply app/client/src/components/ads/tour/TourTooltipWrapper.tsx]: Updated the type def for children here, based on:
https://stackoverflow.com/questions/54905376/type-error-jsx-element-type-null-undefined-is-not-a-constructor-functi

**Review by Rishabh-Rathod — APPROVED** [review]

**Review by Rishabh-Rathod — DISMISSED** [review]

**Review by Rishabh-Rathod — DISMISSED** [review]
LGTM

**Review by Rishabh-Rathod — APPROVED** [review]
