### PR TITLE
fix: Unwanted width calculation in Dropdown

### LINKED ISSUE #15018: [Bug]: Dropdown used for property pane connections causes expensive style recalculations
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there is a evaluation cycle, dropdown used in property pane connections triggers an expensive style recalculation, costing about 40-80ms per cycle. 

Since it's dimensions don't change, there is no need for calling this property which triggers these calculations.
Screenshot 2022-07-05 at 12 26 56 PM

Note: The above profile is with 4x throttling.

### Steps To Reproduce

Create a simple app with couple of widgets with one of them having some incoming and outgoing connections.

### Public Sample App

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

Makes the options width calculation to be done only when required

Fixes #15018

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/ads/Dropdown.tsx [hunk 1]
```diff
@@ -1149,12 +1149,31 @@ export default function Dropdown(props: DropdownProps) {
...
-  }
+  const onParentResize = useCallback(
+    debounce(() => {
+      requestAnimationFrame(() => {
+        if (dropdownWrapperRef.current) {
+          const { width } = dropdownWrapperRef.current.getBoundingClientRect();
+          setDropdownWrapperWidth(`${width}px`);
+        }
+      });
+    }, 1000),
```
Comment (SatishGandham) [inline app/client/src/components/ads/Dropdown.tsx:1164]: 1000 is too long, set it under 300.

File: app/client/src/components/ads/Dropdown.tsx [hunk 2]
```diff
@@ -1149,12 +1149,31 @@ export default function Dropdown(props: DropdownProps) {
...
+    [dropdownWrapperRef.current],
+  );
+
+  useEffect(() => {
+    const resizeObserver = new ResizeObserver(onParentResize);
+    if (dropdownWrapperRef.current && props.fillOptions)
+      resizeObserver.observe(dropdownWrapperRef.current);
+
+    return () => {
```
Comment (SatishGandham) [inline app/client/src/components/ads/Dropdown.tsx:1173]: 🍕 for cleaning up :)

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/src/components/ads/Dropdown.tsx [hunk 3]
```diff
@@ -1149,12 +1149,31 @@ export default function Dropdown(props: DropdownProps) {
...
+          const { width } = dropdownWrapperRef.current.getBoundingClientRect();
+          setDropdownWrapperWidth(`${width}px`);
+        }
+      });
+    }, 1000),
+    [dropdownWrapperRef.current],
+  );
+
+  useEffect(() => {
+    const resizeObserver = new ResizeObserver(onParentResize);
```
Comment (SatishGandham) [inline app/client/src/components/ads/Dropdown.tsx:1169]: Where are we specifying the element which needs to be observed?
Does it check only width or both? we need to check only width.

File: app/client/src/components/ads/Dropdown.tsx (hunk 1 above)
Comment (aswathkk) [reply app/client/src/components/ads/Dropdown.tsx:1164]: @SatishGandham 
We need to recalculate the width only before the user opens the options dropdown.
IMO, 1000 is acceptable.
Because after resizing, it will take at least a second for the user to click and open the dropdown.

Comment (SatishGandham) [reply app/client/src/components/ads/Dropdown.tsx:1164]: 1second is a long time and there is no downside to reducing the duration. It will ensure we do not degrade experience of users who are fast.

Comment (aswathkk) [reply app/client/src/components/ads/Dropdown.tsx:1164]: The downside is that we will be doing this geBoundingClientRect calculation. Yeah I agree that we should not degrade experience of users who are fast

File: app/client/src/components/ads/Dropdown.tsx (hunk 3 above)
Comment (aswathkk) [reply app/client/src/components/ads/Dropdown.tsx:1174]: Element is specified in line number 1176 `dropdownWrapperRef.current`

File: app/client/src/components/ads/Dropdown.tsx (hunk 1 above)
Comment (aswathkk) [reply app/client/src/components/ads/Dropdown.tsx]: Updated to 300ms since I also faced issue being a fast user 😄

**Review by SatishGandham — APPROVED** [review]
LGTM.
@aswathkk , keep an eye out for other forced reflows where we can use resizeObserver.

**Review by SatishGandham — APPROVED** [review]
