### PR TITLE
fix: missing number of queries in active datasource

### LINKED ISSUE #7645: [Bug] number of query associated with datasource are not displayed in Active Tab
Steps to reproduce:
1) Add a google API
2) Click on Run
3) Associate it to a widget

Observation:
number of query associated are not listed under Active datasource

Expectation:
number of query associated must be displayed under Active datasource
Screenshot 2021-09-20 at 7 08 30 PM
 listed under Active datasource

### PR DESCRIPTION
**Pull request by rashmi-rai**
## Description

Changed selector for queryActions in DatasourceCard.
Added Test case for plugintype.SAAS.

Fixes #7645 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested Manually with google sheets and API datasource.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/7645-missing-no-of-queries 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/selectors/entitiesSelector.ts | 54.14 **(0.2)** | 10.47 **(0)** | 32.79 **(0.53)** | 51.5 **(0.23)**</details>

### CODE REVIEW

**Comment by mohanarpit** [comment]
@rashmi-rai Is it possible to add a check in Cypress test case to assert that the number of queries is always showing up for all SaaS datasources?

File: app/client/src/selectors/entitiesSelector.ts [hunk 1]
```diff
@@ -310,7 +310,10 @@ export const getQueryActionsForCurrentPage = createSelector(
   getActionsForCurrentPage,
   (actions) => {
     return actions.filter((action) => {
-      return action.config.pluginType === PluginType.DB;
+      return (
+        action.config.pluginType === PluginType.DB ||
```
Comment (trishaanand) [inline app/client/src/selectors/entitiesSelector.ts:314]: Would we have to handle separately for any new type of plugin we introduce? Is this because rest api is handled separately? If that is the case, could we instead filter on the basis of NOT rest?

Comment (trishaanand) [reply app/client/src/selectors/entitiesSelector.ts:314]: Actually just checked. This is broken for REST API datasource as well.

**Comment by trishaanand** [comment]
@rashmi-rai : Since you are not actively working on fixing this and we keep getting notified every day for this, I am marking this as draft.

**Comment by rashmi-rai** [comment]
> @rashmi-rai Is it possible to add a check in Cypress test case to assert that the number of queries is always showing up for all SaaS datasources?

Done

File: app/client/src/selectors/entitiesSelector.ts (hunk 1 above)
Comment (rashmi-rai) [reply app/client/src/selectors/entitiesSelector.ts]: Fixed for both. 
Changed selector here which works like Not `PluginType.JS`

File: app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx [hunk 2]
```diff
@@ -9,7 +9,7 @@ import { useParams } from "react-router";
 import CollapseComponent from "components/utils/CollapseComponent";
 import {
   getPluginImages,
-  getQueryActionsForCurrentPage,
```
Comment (ApekshaBhosale) [inline app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx:12]: getQueryActionsForCurrentPage only used here. If we are not using this anymore please remove the code

**Review by ApekshaBhosale — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx (hunk 2 above)
Comment (rashmi-rai) [reply app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx:12]: done

**Review by ApekshaBhosale — APPROVED** [review]
