### PR TITLE
fix: Showing mock datasource on onboarding start with data screen

### LINKED ISSUE #28965: [Bug]: Mock datasources not visible on onboarding flow start with data 1st step
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Mock datasources section is not visible
Screenshot 2023-11-20 at 4 17 14 PM

### Steps To Reproduce

- Create a new user 
- Click on `Start with data` option on new onboarding flow for creating new apps
- Observe the datasources screen, mock datasources section is not visible 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
This pr has :
- mock datasource fetching call on onboarding start with data step
- shows mock datasource on the above mentioned screen
- Redirect the user to mock preview data screen on selecting mock datasource

#### PR fixes following issue(s)
Fixes #28965 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by jsartisan** [comment]
@AmanAgarwal041 ignore my comment. I am just looking for a DP to test something.

File: app/client/src/pages/Editor/IntegrationEditor/CreateNewDatasourceTab.tsx [hunk 1]
```diff
@@ -304,12 +307,13 @@ class CreateNewDatasourceTab extends React.Component<
           pageId={pageId}
           showUnsupportedPluginDialog={this.showUnsupportedPluginDialog}
         />
-        {dataSources.length > 0 && this.props.mockDatasources.length > 0 && (
-          <StyledDivider />
-        )}
-        {dataSources.length > 0 &&
-          this.props.mockDatasources.length > 0 &&
-          mockDataSection}
+        {(this.props.isOnboarding || dataSources.length > 0) &&
```
Comment (sneha122) [inline app/client/src/pages/Editor/IntegrationEditor/CreateNewDatasourceTab.tsx:310]: @AmanAgarwal041 Please checkout this [comment](https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu?node-id=2365:20296&mode=design#599821274) once, I thought we wanted to keep mock datasources section's behaviour as is i.e initially they will be shown at the top only when no datasources exist. Also I feel since its an onboarding step we should keep it at top so if users do not want to create any datasources, sample datasources options is obvious, can you please check this once?

Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/IntegrationEditor/CreateNewDatasourceTab.tsx]: Checked with @carinanfonseca

**Comment by sneha122** [comment]
@AmanAgarwal041 Tested the DP, everything looks good and working as expected

File: app/client/src/pages/Editor/IntegrationEditor/CreateNewDatasourceTab.tsx [hunk 2]
```diff
@@ -203,6 +204,7 @@ interface CreateNewDatasourceScreenProps {
   pageId: string;
   isAppSidebarEnabled: boolean;
   isEnabledForStartWithData: boolean;
+  currentApplicationIdForCreateNewApp?: string;
```
[the remark this answers is not in the document]
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/IntegrationEditor/CreateNewDatasourceTab.tsx]: Done

**Review by sneha122 — APPROVED** [review]
