### PR TITLE
fix: widget crashing

### LINKED ISSUE #6965: [Bug] Crash on writing JS query on table widget
Screenshot 2021-08-30 at 4 59 41 PM

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: Release

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description
JS query crashes table widget

Fixes #6965  (issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-widget-crash-on-js-query 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.89 **(0)** | 36.76 **(0)** | 33.61 **(-0.01)** | 55.44 **(0)**
 :red_circle: | app/client/src/widgets/TableWidget/index.tsx | 27.52 **(0.11)** | 6.08 **(0)** | 25 **(-0.49)** | 27.69 **(0.12)**</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
Approving to run tests

File: app/client/src/widgets/TableWidget/index.tsx [hunk 1]
```diff
@@ -93,13 +93,17 @@ class TableWidget extends BaseWidget<TableWidgetProps, WidgetState> {
...
 
-  getPropertyValue = (value: any, index: number, preserveCase = false) => {
+  getBooleanPropertyValue = (value: any, index: number) => {
     if (isBoolean(value)) {
       return value;
     }
     if (Array.isArray(value) && isBoolean(value[index])) {
       return value[index];
     }
+    return value;
```
Comment (marks0351) [inline app/client/src/widgets/TableWidget/index.tsx:103]: should we add a double negation? to allow evaluated value?

**Review by marks0351 — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@Tooluloope Tested on Deploy Preview and working fine.
