### PR TITLE
Fix api settings page not getting updated

### LINKED ISSUE #3191: [Bug] API settings page is not getting updated on selecting a different API
## Description
API settings page is not getting updated on selecting a different API. The correct page shows up after selecting a different page and then coming back to the settings page.

https://user-images.githubusercontent.com/1757421/108990504-f7e76b80-76bc-11eb-8b21-98bc1f7ace10.mov

### Steps to reproduce the behaviour:
1. Go to Api1 settings.
2. Click on execute on load.
3. Select Api2.
4. See that settings page has not changed to reflect Api2 settings. 

### Important Details
 - Version: Cloud
 - OS: Linux
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by ram-primathon**
## Description
fix API settings page is not getting updated

Fixes #3191

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/ads/Checkbox.tsx [hunk 1]
```diff
@@ -95,9 +95,14 @@ const LabelContainer = styled.div<{ info?: string }>`
...
 const Checkbox = (props: CheckboxProps) => {
   const [checked, setChecked] = useState<boolean>(
-    props.isDefaultChecked || false,
+    props.isDefaultChecked as boolean,
   );
 
+  useEffect(() => {
+    const isChecked = !!props.isDefaultChecked;
+    setChecked(isChecked);
+  }, [props.isDefaultChecked]);
```
Comment (hetunandu) [inline app/client/src/components/ads/Checkbox.tsx:104]: Combine into a single custom hook

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/components/ads/Checkbox.tsx (hunk 1 above)
Comment (ram-primathon) [reply app/client/src/components/ads/Checkbox.tsx]: done

**Review by hetunandu — APPROVED** [review]
