### PR TITLE
fix: gsheet continuous re authorisation required issue fixed

### LINKED ISSUE #24236: [Bug]: User is asked for reAuthorise On gsheet
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to older app it is observed that the it needs reauthorisation and asks for Authorisation every 2-3 hr 

### Steps To Reproduce

1) Navigate to older apps with Gsheet 
2) Observe  Datasource  review asking for re-auth
3) Navigate to Queries and observe the sheet list is missing 

However this was observed only in 1 app out of 5 apps that I investigated 

### Public Sample App

https://app.appsmith.com/applications/613868bedd7786286ddd4a6a/pages/63ec710e8e503f763651791a (

### Environment

Production

### Issue video log

_No response_

### Version

cloud

Front logo [Front conversations](https://app.frontapp.com/open/top_b61ak)

### PR DESCRIPTION
**Pull request by sneha122**
## Description

After upgrade to v1.9.21, google sheets datasource would lose authentication after every couple of hours, causing all queries to fail. This PR fixes that issue. 

The issue started occurring after v1.9.21 because of the changes made as a part of multiple environments. Once the access token expires, we make an API call to google to refresh the access token. This API call does not return refresh token and hence we were setting refresh token as null. On subsequent refresh calls, this refresh token would be passed as null, hence causing failure in refresh. 

#### PR fixes following issue(s)
Fixes #24236 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 1]
```diff
@@ -608,13 +608,14 @@ public Mono<DatasourceStorage> refreshAuthentication(DatasourceStorage datasourc
                                 }
                             })
                             .flatMap(authenticationResponse -> {
+                                authenticationResponse.setRefreshToken(integrationDTO.getAuthenticationResponse().getRefreshToken());
                                 oAuth2.setAuthenticationResponse(authenticationResponse);
                                 datasourceStorage.getDatasourceConfiguration().setAuthentication(oAuth2);
-                                // We return the same object instead of the update value because the updates value
-                                // will be in the encrypted form
+
                                 return datasourceStorageService
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:615]: Can you please add a comment here explaining why we need to fetch the datasourceStorage value from DB again ?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 2]
```diff
@@ -608,13 +608,14 @@ public Mono<DatasourceStorage> refreshAuthentication(DatasourceStorage datasourc
                                 }
                             })
                             .flatMap(authenticationResponse -> {
+                                authenticationResponse.setRefreshToken(integrationDTO.getAuthenticationResponse().getRefreshToken());
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:611]: Can you please add a comment here why we need to explicitly set the refresh token ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 1 above)
Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:615]: yes will do that, thanks @sumitsum

**Review by sumitsum — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 3]
```diff
@@ -608,13 +608,18 @@ public Mono<DatasourceStorage> refreshAuthentication(DatasourceStorage datasourc
                                 }
                             })
                             .flatMap(authenticationResponse -> {
+                                // We need to set refresh token here, because refresh token API call made to google, does not return refresh token in the response
+                                // hence it was resulting in refresh token being set as null, that would break the authentication. 
+                                authenticationResponse.setRefreshToken(integrationDTO.getAuthenticationResponse().getRefreshToken());
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:613]: Curious, did this line exist before and get removed along the way?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 4]
```diff
@@ -608,13 +608,18 @@ public Mono<DatasourceStorage> refreshAuthentication(DatasourceStorage datasourc
...
                                 datasourceStorage.getDatasourceConfiguration().setAuthentication(oAuth2);
-                                // We return the same object instead of the update value because the updates value
-                                // will be in the encrypted form
+
+                                // We need to return datasourceStorage object from the database so as to get decrypted token values,
+                                // if we dont then, encrypted token values would be returned and subsequently those encrypted values would be used to call google apis
                                 return datasourceStorageService
                                         .save(datasourceStorage)
-                                        .thenReturn(datasourceStorage);
+                                        .flatMap(ignore -> datasourceService.findByIdWithStorages(datasourceStorage.getDatasourceId())
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:621]: Do we need to use the `withStorages` call here and then find storage again in the next line?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 3 above)
Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:613]: Hi @nidhi-nair earlier we used to make `update` call instead of `save` call - APMU, the update call only updated the non null values, which made sure that even if the refresh token was set to null by the cloud services, it didn't get set as null in the API server DB.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 4 above)
Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:621]: As discussed, will address this. I have created [this](https://github.com/appsmithorg/appsmith/issues/24282) issue to track it.

Comment (sondermanish) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:621]: Since this is small change, I'll take this up in My cleanup PR, given it's merged by then
