### PR TITLE
fix: Issues and Enhancements in the camera widget

### LINKED ISSUE #10077: [Bug]: Issues and Enhancements in the camera widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Couple of bugs noticed with the camera widget
1. Stretching of images after click. 
2. Camera controls not visible when placed on a white background
3. Action should be updated to onImageSave than onImageCapture. We will retain the onImageCapture functionality in our code so that if users need it we can enable it.
4. For video also we need an action for onVideoSave so that user can confirm the video they want to send. We CAN retain the onVideoStart and onVideoStop functionality but let's not expose the controls right now.
5. When you drag the camera widget for the first time and grant access, it doesn't show the devices 
list in the dropdown. It works after you delete and add it again.
6. Change the mode name to "Image" instead of "Camera" in the dropdown.
[LOOM DEMO](https://www.loom.com/share/0043f40cca5f4b9aa53b73e78f0b78f6)

Issue 5
[LOOM DEMO](https://www.loom.com/share/6c992a2688024a248f336a7febefd7b8)

### Steps To Reproduce

Stretching of images
1. Drag a new camera widget onto the canvas
2. Resize the camera widget
3. Take a picture
4. Observe how the picture taken is stretched

Camera controls are hidden
1. Drag a new camera widget onto the canvas
2. Increase the widget height so that camera controls come out of the picture area. (See video)
3. Observe how the color is close to the container color and hard to differentiate.

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
1): Fix on various issues on a camera widget 
- Stretching of images after click.
- Camera controls not visible when placed on a white background
- When you drag the camera widget for the first time and grant access, it doesn't show the devices
list in the dropdown. It works after you delete and add it again.

2): Enhance UX/Feature
- Action should be updated to onImageSave than onImageCapture. We will retain the onImageCapture functionality in our code so that if users need it we can enable it.
- For video also we need an action for onVideoSave so that user can confirm the video they want to send. We CAN retain the onVideoStart and onVideoStop functionality but let's not expose the controls right now.
- Change the mode name to "Image" instead of "Camera" in the dropdown.
- Always keep the camera dimensions intact on resize
- @dilippitchika , @Pranay105 , You guys can find the PR for documentation change here : https://github.com/appsmithorg/appsmith-docs/pull/335

Fixes #10077 #10126 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/10077-camera-issue-enhance 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.54 **(0.01)** | 37 **(0.01)** | 35.74 **(-0.01)** | 55.87 **(0.01)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :green_circle: | app/client/src/widgets/CameraWidget/component/index.tsx | 11.01 **(0.24)** | 15.09 **(0.37)** | 0 **(0)** | 12.87 **(0.19)**
 :red_circle: | app/client/src/widgets/CameraWidget/widget/index.tsx | 28.92 **(-3.08)** | 0 **(0)** | 33.33 **(-9.53)** | 28.4 **(-3.11)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@wmdev0808 please make some efforts towards making the PR description better along with the title, Making it descriptive for the reviewer is important

**Review by somangshu — COMMENTED** [review]
Please state all the changes and then re-request for the review

**Comment by somangshu** [comment]
@wmdev0808 have you made the changes in the documentation? Can you link it here and tag @dilippitchika & @Pranay105

File: app/client/src/widgets/CameraWidget/component/index.tsx [hunk 1]
```diff
@@ -193,7 +193,8 @@ export interface ControlPanelProps {
   status: MediaCaptureStatus;
   appLayoutType?: SupportedLayouts;
   fullScreenHandle: FullScreenHandle;
-  onCaptureImage: () => void;
+  onImageCapture: () => void;
```
Comment (somangshu) [inline app/client/src/widgets/CameraWidget/component/index.tsx:196]: why do we need to change the event name? also this is unused, Is this really required @wmdev0808 @dilippitchika

File: app/client/src/widgets/CameraWidget/component/index.tsx [hunk 2]
```diff
@@ -982,6 +967,19 @@ function CameraComponent(props: CameraComponentProps) {
     [setAudioInputs, setVideoInputs],
   );
 
+  const updateDeviceInputs = useCallback(() => {
```
Comment (somangshu) [inline app/client/src/widgets/CameraWidget/component/index.tsx:970]: Can we assert this using JEST?

**Comment by wmdev0808** [comment]
> @wmdev0808 have you made the changes in the documentation? Can you link it here and tag @dilippitchika & @Pranay105

done

File: app/client/src/widgets/CameraWidget/widget/index.tsx [hunk 3]
```diff
@@ -215,6 +238,18 @@ class CameraWidget extends BaseWidget<CameraWidgetProps, WidgetState> {
     });
   };
 
+  handleImageSave = () => {
```
Comment (somangshu) [inline app/client/src/widgets/CameraWidget/widget/index.tsx:241]: Cover these functions with test, If JEST is possible great otherwise use Cypress.

We could probably compare before / after DSL

**Review by somangshu — APPROVED** [review]
Implementation LGTM, Tested the deploy preview too. 

Left a couple of comments to look at

**Comment by somangshu** [comment]
@wmdev0808 great work with the PR description. ❤️

File: app/client/src/widgets/CameraWidget/component/index.tsx (hunk 1 above)
Comment (wmdev0808) [reply app/client/src/widgets/CameraWidget/component/index.tsx:196]: It is just for easy maintenance.
It means: 
- we are just expose two events: onImageSave and onVideoSave in this PR
- If users are also requiring the original ones, we can easily expose them, either.

**Comment by YogeshJayaseelan** [comment]
@wmdev0808 Tested this PR and the issue #10126 and #10077 are working as expected

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Camera_spec.js [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+    // Take photo
+    cy.get(mainControlSelector).click();
+    cy.wait(200);
+    // Save photo
+    cy.get(mainControlSelector)
+      .first()
+      .click();
+
+    // Assert: should trigger onImageSave action - modal popup
+    cy.get(modalWidgetPage.modelTextField).should("have.text", modalName);
```
Comment (somangshu) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Camera_spec.js:32]: @wmdev0808 how are you checking that the event did not fire after the photo was taken?

**Review by somangshu — COMMENTED** [review]
Left a comment. @yatinappsmith can you checkout the cypress test case.

@wmdev0808 please update with the latest release and run test again, Lot of failures seen here

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Camera_spec.js (hunk 4 above)
Comment (wmdev0808) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Camera_spec.js:32]: > @wmdev0808 how are you checking that the event did not fire after the photo was taken?

I don't think we have to check such a case because we don't expose any other action handlers except for onImageSave and this property is bound to save button only.

**Review by yatinappsmith — APPROVED** [review]

**Comment by somangshu** [comment]
@wmdev0808 related test is failing. Please check.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Camera_spec.js (hunk 4 above)
Comment (somangshu) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Camera_spec.js:32]: I thought its worth checking so that we dont regress. 

cc @yatinappsmith

**Comment by wmdev0808** [comment]
> @wmdev0808 related test is failing. Please check.

It is not specific to this test case
