### PR TITLE
fix: changed validation to FUNCTION for the default selected value RadioGroupWidget

### LINKED ISSUE #9834: [Bug]: Radiogroup not working for Id->String values
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Default selected value is only pre-selected if the Options values are specified as strings. 
image

Notably, the select widget does allows int to string mapping and behaves as expected, so it can effectively be used as a workaround if string mapping is not possible

image

### Steps To Reproduce

Set the radio group items as a label-value as a string->integer map  as follows:
image

You'll notice that the radio group has no pre-selected item

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

**Summary of changes**

- Changed the validation to function type for `defaultOptionValue`.
- Added custom validator function for options property
    - This also checks that all the data types of the `value` property inside options is similar. 
- Changed the logic for onRadioSelectionChange function. 
    - Checking the data type of `value` property of the first object inside options property to be number. If true, parsing it to float.
    - Else keeping value as is.

**Motivation**

- Evaluated value for the defaultOptionValue is always the string irrespective of the mustasch syntax i.e. {{}}. This caused issue when the value is integer in the `value` property of the `options` property. Now with changes included in this PR -> value inside mustach is treated as integer if passed integer e.g. {{1}} <-> int. And normal value is treated as string e.g. 1 is string. 
-  Whenever the `value` property inside the `options` property has integer values then, clicking on radio button does not change the state to checked. This issue also got fixed in this PR.

Fixes #9834 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Added the following tests:

- Cypress test: `RadioGroup_Int_Value_spec.js`,
    - This spec file checks the following
        - If the data type of the value in the `value` property is integer or string, do the following checks:
        - Check if the default selected value is changing the radio but as expected.
        - Check if the radio buttons can be clicked normally.
        - Checks if all the data types of the value property in the options property is the same.
- Unit test: `propertyPaneConfig.test.ts`
    - This test checks the defaultOptionValue custom validator. It checks if number passed to the validator returns parsed value as an integer. Same the case with string. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix-radio_group_value_to_integer_map 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.06 **(-0.05)** | 36.84 **(-0.03)** | 34.99 **(0)** | 55.55 **(-0.05)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/widgets/RadioGroupWidget/widget/index.tsx | 33.77 **(-50.85)** | 6.06 **(6.06)** | 63.64 **(-11.36)** | 34.72 **(-52.78)**</details>

### CODE REVIEW

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 1]
```diff
@@ -4,9 +4,32 @@ import { WidgetType } from "constants/WidgetConstants";
...
 import { compact, isArray } from "lodash";
+import { AutocompleteDataType } from "utils/autocomplete/TernServer";
+
+function defaultOptionValueValidation(value: unknown): ValidationResponse {
+  /**
+   * Check if the data type of the value
+   * If it's number send return as a number
+   * Other than that returns as it is.
+   */
+  if (typeof value === "number") {
```
Comment (sbalaji1192) [inline app/client/src/widgets/RadioGroupWidget/widget/index.tsx:21]: use _.isNumber() here. Its more readeable.

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 2]
```diff
@@ -4,9 +4,32 @@ import { WidgetType } from "constants/WidgetConstants";
...
-import { ValidationTypes } from "constants/WidgetValidation";
+import {
+  ValidationResponse,
+  ValidationTypes,
+} from "constants/WidgetValidation";
 import { EvaluationSubstitutionType } from "entities/DataTree/dataTreeFactory";
 import { compact, isArray } from "lodash";
+import { AutocompleteDataType } from "utils/autocomplete/TernServer";
+
+function defaultOptionValueValidation(value: unknown): ValidationResponse {
```
Comment (sbalaji1192) [inline app/client/src/widgets/RadioGroupWidget/widget/index.tsx:15]: suggestion: `defaultOptionValidation` is more appropriate.

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx (hunk 1 above)
Comment (sbalaji1192) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx:21]: Why do we need this condition. it seems in all cases we're returning 
`return {
    isValid: true,
    parsed: value,
  };`

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 3]
```diff
@@ -163,7 +201,13 @@ class RadioGroupWidget extends BaseWidget<RadioGroupWidgetProps, WidgetState> {
   }
 
   onRadioSelectionChange = (updatedValue: string) => {
-    this.props.updateWidgetMetaProperty("selectedOptionValue", updatedValue, {
+    let newVal;
+    if (typeof this.props.options[0].value === "number") {
```
Comment (sbalaji1192) [inline app/client/src/widgets/RadioGroupWidget/widget/index.tsx:205]: use _.isNumber here

Comment (sbalaji1192) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx:205]: if typeof `this.props.options[0].value` is already a number, why do we need to parseFloat it ?

Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx:205]: @sbalaji1192 the this.props.options[0].value is not number it depends on the value that is passed to it.

Comment (sbalaji1192) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx:205]: understood

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx (hunk 2 above)
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx]: Yes, I have changed the name of the functions as suggested

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx (hunk 1 above)
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx]: Removed the condition, now directly returning the object

**Review by sbalaji1192 — APPROVED** [review]
LGTM. Good work!

**Comment by YogeshJayaseelan** [comment]
@keyurparalkar Verified this PR and now user will be able to pass integer in the default value of radio group with the following format {{1}}

Observed one issue 

Issue 1 - Since the default value structure is Sting | Number - The expected example should be abc | {{1}} instead of 1 | {{1}}

Screenshot 2021-12-30 at 11 17 16 AM

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js [hunk 4]
```diff
@@ -0,0 +1,202 @@
...
+      "{{1}}",
+    );
+    checkSelectedRadioValue(formWidgetsPage.radioWidget, "1");
+
+    //Change the DSV to {{2}}
+    cy.updateCodeInput(".t--property-control-defaultselectedvalue", "{{2}}");
+    cy.wait(200);
+
+    //Check the DSV if {{2}} and radio with value=2 is selected
+    cy.validateCodeEditorContent(
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js:33]: remove validateCodeEditorContent

File: app/client/src/widgets/RadioGroupWidget/widget/propertyPaneConfig.test.ts [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+      (child: any) => child.propertyName === "defaultOptionValue",
+    )[0];
+
+    const dsvValidationFunc = dsv.validation.params.fn;
+
+    expect(dsvValidationFunc(1)).toEqual({ isValid: true, parsed: 1 });
+    expect(dsvValidationFunc("1")).toEqual({ isValid: true, parsed: "1" });
+  });
+
+  // it("case: check the value returned by options property", () => {
```
Comment (sbalaji1192) [inline app/client/src/widgets/RadioGroupWidget/widget/propertyPaneConfig.test.ts:19]: Do we need this commented case?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js [hunk 6]
```diff
@@ -0,0 +1,202 @@
...
+          }
+        ]`,
+        message: `This value does not evaluate to type Array<{ "label": "string", "value": "string" | number }>`,
+      },
+    ];
+
+    inputOutputValues.map((useCase) => {
+      cy.updateCodeInput(".t--property-control-options", useCase.input);
+      cy.evaluateErrorMessage(useCase.message);
+    });
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js:200]: add a test case where default option and option value type don't match

Comment (keyurparalkar) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js:183]: For this, we have added a helper message in the expected section of the default selected value. So whenever the user needs default selected value as an integer they should bind it with `{{}}` or if its a string the they can type normally. This will make sure that the data type in the default selected value and the options value is similar. 
To satisfy this scenario we have the first test case.

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 7]
```diff
@@ -4,9 +4,137 @@ import { WidgetType } from "constants/WidgetConstants";
...
+      const { label, value } = options[i];
+      if (!valueType) {
+        valueType = typeof value;
+      }
+      //Checks the uniqueness all the values in the options
+      if (!uniqueLabels.hasOwnProperty(value)) {
+        uniqueLabels[value] = "";
+      } else {
+        _isValid = false;
+        message = "path:value must be unique. Duplicate values found";
```
[the remark this answers is not in the document]
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx:44]: Done

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 8]
```diff
@@ -4,9 +4,137 @@ import { WidgetType } from "constants/WidgetConstants";
...
+import {
+  ValidationResponse,
+  ValidationTypes,
+} from "constants/WidgetValidation";
 import { EvaluationSubstitutionType } from "entities/DataTree/dataTreeFactory";
-import { compact, isArray } from "lodash";
+import { AutocompleteDataType } from "utils/autocomplete/TernServer";
+import { isArray, compact, isNumber } from "lodash";
+/**
+ * Validation requirement for the options property of this widget:
```
[the remark this answers is not in the document]
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx]: Done

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 9]
```diff
@@ -4,9 +4,137 @@ import { WidgetType } from "constants/WidgetConstants";
...
+ * 1. This property will take the value in the following format: Array<{ "label": "string", "value": "string" | number}>
+ * 2. The `value` property should consists of unique values only.
+ * 3. The `value` property can accept strings or numbers.
```
[the remark this answers is not in the document]
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx]: 3, 4, 6 removed. Validation rules updated.

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 10]
```diff
@@ -4,9 +4,137 @@ import { WidgetType } from "constants/WidgetConstants";
...
+        _isValid = false;
+        message =
+          "Invalid entry at index: " + i + ". Missing required key: label";
+        break;
+      }
+
+      //Validation checks for the the label.
+      if (
+        label === undefined ||
+        label === null ||
```
[the remark this answers is not in the document]
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx]: Replaced with `_.isNil()`

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 11]
```diff
@@ -4,9 +4,137 @@ import { WidgetType } from "constants/WidgetConstants";
...
+
+      //Check if all the data types for the value prop is the same.
+      if (typeof value !== valueType) {
+        _isValid = false;
+        message = "All value properties in options must have the same type";
+        break;
+      }
+
+      //Check if the each object has value property.
+      if (!value && value !== "") {
```
[the remark this answers is not in the document]
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx]: Replaced with _.isNil()

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js (hunk 4 above)
Comment (keyurparalkar) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RadioGroup_Int_Value_spec.js]: Removed

File: app/client/src/widgets/RadioGroupWidget/widget/propertyPaneConfig.test.ts (hunk 5 above)
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/propertyPaneConfig.test.ts]: Removed this case

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 12]
```diff
@@ -4,9 +4,123 @@ import { WidgetType } from "constants/WidgetConstants";
...
+      if (!label) {
+        _isValid = false;
+        message =
+          "Invalid entry at index: " + i + ". Missing required key: label";
+        break;
+      }
+
+      //Validation checks for the the label.
+      if (
+        _.isNil(value) ||
```
Comment (sbalaji1192) [inline app/client/src/widgets/RadioGroupWidget/widget/index.tsx:58]: was this supposed to be _.isNil(label)?

File: app/client/yarn.lock [hunk 13]
```diff
@@ -2764,11 +2764,6 @@
   dependencies:
```
Comment (sbalaji1192) [inline app/client/yarn.lock:2764]: do we need these changes?

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx (hunk 12 above)
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx]: Done

File: app/client/yarn.lock (hunk 13 above)
Comment (keyurparalkar) [reply app/client/yarn.lock]: These changes were present in the previous release branch. Merging the new release branch resolved this

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 14]
```diff
@@ -4,9 +4,132 @@ import { WidgetType } from "constants/WidgetConstants";
...
+): ValidationResponse {
+  //Checks if the value is not of object type in {{}}
+  if (_.isObject(value)) {
+    return {
+      isValid: false,
+      parsed: JSON.stringify(value, null, 2),
+      messages: ["This value does not evaluate to type: string or number"],
+    };
+  }
+
```
Comment (sbalaji1192) [inline app/client/src/widgets/RadioGroupWidget/widget/index.tsx:127]: we should write a block for `{{true}}` as well

**Review by sbalaji1192 — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx (hunk 14 above)
Comment (keyurparalkar) [reply app/client/src/widgets/RadioGroupWidget/widget/index.tsx:127]: Added the boolean block

File: app/client/src/widgets/RadioGroupWidget/widget/index.tsx [hunk 15]
```diff
@@ -125,6 +125,14 @@ function defaultOptionValidation(
     };
   }
 
+  if (_.isBoolean(value)) {
+    return {
+      isValid: false,
+      parsed: JSON.stringify(value, null, 2),
```
Comment (sbalaji1192) [inline app/client/src/widgets/RadioGroupWidget/widget/index.tsx:131]: we don't need to stringify it.

**Review by sbalaji1192 — CHANGES_REQUESTED** [review]

**Review by sbalaji1192 — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@keyurparalkar Tested this PR. DP looks good.
Moving to Done
