### PR TITLE
fix: updating trigger meta to get the source of console logs

### LINKED ISSUE #16483: [Bug]: Console fails to read parent function details if statement is present in a function nested in a setInterval
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When console statement is triggered from inside a function defined in an interval, then the console is unable to read parent function name. This needs to be supported.

### Steps To Reproduce

1. Use following code on the editor
```
IntervalCheck: () => {
		setInterval(() => {
			return storeValue('name', appsmith.user.name)
			.then(() => {
				return Api1.run()
				.then(() => {
					console.log('Api has been executed')
					console.log('from user obj ' ,appsmith.user.name)
					console.log('from store ', appsmith.store.name)
				})
			})
		}, 1000, 'testConsole')
	}
```
2. Run the function and observe that **Logs** on the **Debugger** does not display any result if there's a filter on search field. If Filter is not present then the console logs are printed without origin details present for that entry.

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #16514: [Bug]: First console statement in a code snippet does not get executed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Console statement in a code snippet does not get executed as expected

image

### Steps To Reproduce

1. Use following snippet and run the function or any consecutive console statements 
```
myFun2: async () => {
		return storeValue('animal', 'https://dog-api.kinduff.com/api/facts')
			.then(() => {
			console.warn('Attempting to find new dog pics')
			return Api1.run()
				.then(() => {
				console.log(Api1.data)
			})
		})
	},
```
2. Observe the first console statement is not executed on the debugger

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #16515: [Bug]: Source of console statement trigger does not get logged correctly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Source of console statement trigger does not get logged correctly

### Steps To Reproduce

1. Use following snippet in code and run function. Observe the source is not set as function name but picks the code itself as the source
```

funcType2: function() {
	console.log('this is from parent')
	Api1.run(async () => {console.log('this is from child')})
}
```

image

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ayushpahwa**
## Description

For nested functions, the trigger meta is not available for subsequent functions. So in cases where the dynamic trigger has the relevant info, we can use that to update the trigger meta and then use that meta to display the source of the logs.

Fixes #16515 
Fixes #16483
Fixes #16514

## Type of change

- New feature (non-breaking change which adds functionality)

## Test plan

- [ ] https://github.com/appsmithorg/TestSmith/issues/2058

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/workers/evaluate.ts [hunk 1]
```diff
@@ -337,6 +343,7 @@ export async function evaluateAsync(
         originalBinding: userScript,
       });
       logs = userLogs.flushLogs();
+      console.log("Ayush test", logs.length);
```
Comment (arunvjn) [inline app/client/src/workers/evaluate.ts:346]: Unintentional logs ?

File: app/client/src/workers/evaluate.ts [hunk 2]
```diff
@@ -304,6 +308,7 @@ export async function evaluateAsync(
     let result;
     let logs;
     /**** Setting the eval context ****/
+    console.log("Ayush is resetting");
```
Comment (arunvjn) [inline app/client/src/workers/evaluate.ts:311]: Unintentional logs ?

**Review by arunvjn — APPROVED** [review]

**Comment by ramsaptami** [comment]
Verified all fixes on DP. Gtg to release CC: @ayushpahwa

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 3]
```diff
@@ -196,13 +218,17 @@ describe("Debugger logs", function() {
...
+      `${logString} Started`,
+    );
     agHelper.GetNAssertContains(
       locator._debuggerLogMessage,
       `${logString} Success`,
     );
   });
 
-  it("11. Console log after API execution fails", function() {
+  it("12. Console log after API execution fails", function() {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:231]: Can we add Started & Failed for catch block also please?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 4]
```diff
@@ -168,18 +187,21 @@ describe("Debugger logs", function() {
     agHelper.GetNAssertContains(locator._debuggerLogMessage, logString);
   });
 
-  it("10. Console log after API succedes", function() {
+  it("11. Console log after API succedes", function() {
     ee.NavigateToSwitcher("explorer");
     apiPage.CreateAndFillApi(dataSet.baseUrl + dataSet.methods, "Test1");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:192]: nit: Can we leave the query name as such instead of renaming here? Since Api1 is more readable & this case is also for API.

File: app/client/src/workers/DataTreeEvaluator/index.ts [hunk 5]
```diff
@@ -882,12 +882,19 @@ export default class DataTreeEvaluator {
             !!entity && isJSAction(entity),
             contextData,
             callBackData,
+            fullPropertyPath?.includes("body") ||
+              !toBeSentForEval.includes("console."),
```
Comment (arunvjn) [inline app/client/src/workers/DataTreeEvaluator/index.ts:886]: Seems little hacky. Just for my understanding, why are we adding this check ?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 6]
```diff
@@ -118,7 +118,26 @@ describe("Debugger logs", function() {
...
+      `{{(function(){
+  	const temp = "Hello!"
+
+  	console.log("${logString}");
+  	return temp;
+  })()}}`,
+    );
+    cy.reload();
+    // Wait for the debugger icon to be visible
+    cy.get(".t--debugger").should("be.visible");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:135]: Use ts helper methods instead of these.

**Comment by Aishwarya-U-R** [comment]
Is this expected - myfun1 not returning the API data? Should I do something else for it to return?

https://user-images.githubusercontent.com/91450662/188624970-9fde7032-bad1-49c4-b450-85f9dd3b920e.mov

**Comment by ayushpahwa** [comment]
@Aishwarya-U-R you need to return Api1.data in the .then() after the run.

```
return Api1.run()
				.then(() => {
				console.log(Api1.data)
				return 1;
			})
```

File: app/client/src/workers/DataTreeEvaluator/index.ts (hunk 5 above)
Comment (ayushpahwa) [reply app/client/src/workers/DataTreeEvaluator/index.ts:886]: Hey @arunvjn , there are times when the js object is being validated/checked without the function being explicitly run. For eg when you make any changes to a function, the whole JSobject is run once using the evaluateSync function. The evaluation causes logs to pop up and this particular code creates a flag which skips the log parsing and resetting when such actions are being called. For the second part, the logs are being reset even if non console evals are done, like if `{{appmsith.store.name}}` is used anywhere, it will reset the logs object and cause logs to go missing from between the function runs.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 7]
```diff
@@ -168,18 +187,21 @@ describe("Debugger logs", function() {
...
-            console.log("${logString} Success");
-            return "success";
-          }).catch(()=>{
-            console.log("${logString} Failed");
-            return "fail";
+          return storeValue("test", "test").then(() => {
+            console.log("${logString} Started");
+            return Test1.run().then(()=>{
+              console.log("${logString} Success");
+              return "success";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:200]: Please also map to a text widget & validate the return statement after console is executed fine.

Comment (ayushpahwa) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:199]: Added

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js (hunk 6 above)
Comment (ayushpahwa) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js]: Done

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js (hunk 4 above)
Comment (ayushpahwa) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js]: Done

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js (hunk 3 above)
Comment (ayushpahwa) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:236]: Done

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 8]
```diff
@@ -196,22 +217,30 @@ describe("Debugger logs", function() {
...
+    agHelper.GetNAssertContains(
+      locator._debuggerLogMessage,
+      `${logString} Started`,
+    );
     agHelper.GetNAssertContains(
       locator._debuggerLogMessage,
       `${logString} Success`,
     );
+    ee.DragDropWidgetNVerify("textwidget", 200, 600);
+    propPane.UpdatePropertyFieldValue("Text", `{{JSObject2.myFun1.data}}`);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:229]: Is it always JSObject2? Better to read the name dynamically from next time or incase this case fails.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 9]
```diff
@@ -118,7 +118,25 @@ describe("Debugger logs", function() {
...
+    propPane.UpdatePropertyFieldValue(
+      "Text",
+      `{{(function(){
+  	const temp = "Hello!"
+
+  	console.log("${logString}");
+  	return temp;
+  })()}}`,
+    );
+    cy.reload();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:132]: User agHelper.RefreshPage() from next time.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 10]
```diff
@@ -118,7 +118,25 @@ describe("Debugger logs", function() {
...
+    // Wait for the debugger icon to be visible
+    cy.get(".t--debugger").should("be.visible");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:134]: Use agHelper.AssertElementVisible() from next time.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 11]
```diff
@@ -196,22 +217,30 @@ describe("Debugger logs", function() {
...
+      locator._debuggerLogMessage,
+      `${logString} Started`,
+    );
     agHelper.GetNAssertContains(
       locator._debuggerLogMessage,
       `${logString} Success`,
     );
+    ee.DragDropWidgetNVerify("textwidget", 200, 600);
+    propPane.UpdatePropertyFieldValue("Text", `{{JSObject2.myFun1.data}}`);
+    cy.get(commonlocators.textWidgetContainer).should(
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:230]: Use agHelper.GetNAssertElementText() from next time.

**Review by Aishwarya-U-R — COMMENTED** [review]
Enhancements mentioned, otherwise cypress looks good!

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js (hunk 8 above)
Comment (ayushpahwa) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js]: Yes, it's better to update it. I have done the changes here.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js (hunk 9 above)
Comment (ayushpahwa) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js]: Updated

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js (hunk 10 above)
Comment (ayushpahwa) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js]: Updated here, will keep in mind for future also

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js (hunk 11 above)
Comment (ayushpahwa) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js]: Updated here, will keep in mind for future also

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js [hunk 12]
```diff
@@ -118,7 +118,25 @@ describe("Debugger logs", function() {
...
+      `{{(function(){
+  	const temp = "Hello!"
+
+  	console.log("${logString}");
+  	return temp;
+  })()}}`,
+    );
+    agHelper.RefreshPage();
+    // Wait for the debugger icon to be visible
+    agHelper.AssertElementVisible(".t--debugger");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.js:134]: No direct locators in spec. Since debugger could be common - should take it from Common locators.ts.

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good!

**Review by arunvjn — APPROVED** [review]
