### PR TITLE
fix: edit ds button was disabled due to no user perm in ds object

### LINKED ISSUE #25148: [Bug]: OAuth - Edit DS on Authentication page is disabled.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create an OAuth DS , save it and create an api query, in the authentication tab, the edit datasource button is missing

### Steps To Reproduce

1. Create a new Auth API DS with a url as say - https://api.dropboxapi.com/
2. Save and click on new api
3. Now click on Authentication tab and note that the edit datasource button is disabled here.
Screenshot 2023-07-06 at 1 39 01 PM

Works fine on Production

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Due to absence of `userPermissions` in Datasource object being sent to the Api authentication component, the `edit datasource` button was being disabled. Now the `userPermissions` with regard to datasource, is being added to its object to enable disable the `edit ds` button.

#### PR fixes following issue(s)
Fixes #25148 

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx [hunk 1]
```diff
@@ -149,6 +149,10 @@ const mapStateToProps = (state: AppState, ownProps: any): ReduxStateProps => {
         datasourceFromDataSourceList.datasourceStorages[
           currentEnvironment
         ].datasourceId;
+
+      // Adding user permissions for datasource from datasourceFromDataSourceList
+      datasourceMerged.userPermissions =
```
Comment (sneha122) [inline app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx:154]: @AmanAgarwal041 Do we know why its marked as release blocker? If the issue occurred because of permissions, shouldn't it be present before as well?

File: app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx [hunk 2]
```diff
@@ -149,6 +149,10 @@ const mapStateToProps = (state: AppState, ownProps: any): ReduxStateProps => {
...
+        datasourceFromDataSourceList.userPermissions || [];
```
Comment (sneha122) [inline app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx:155]: @AmanAgarwal041 Should we add a cypress test for this fix?

File: app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx:154]: This got introduced because of the multiple environments. ref : https://github.com/appsmithorg/appsmith/blob/261c6c169b9d1d160c5822d0822ca90736d89e9c/app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx#L142

File: app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx (hunk 2 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx:155]: Surely. Will add the same

Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx:155]: Done

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25148_Spec.ts [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+    agHelper.GenerateUUID();
+    cy.get("@guid").then((uid) => {
+      dsName = "AuthAPI " + uid;
+      dataSources.CreatePlugIn("Authenticated API");
+      agHelper.RenameWithInPane(dsName, false);
+      dataSources.FillAuthAPIUrl();
+      dataSources.SaveDatasource();
+      apiPage.CreateApi("API" + uid, "GET", true);
+      apiPage.SelectPaneTab("Authentication");
+      cy.get(apiPage._saveAsDS).should("be.enabled");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25148_Spec.ts:18]: There are 2 Edit data source buttons. Can you check state of both please?

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25148_Spec.ts:18]: One in Authentication, one to the right of URL input.

Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25148_Spec.ts]: Done

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25148_Spec.ts [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+    cy.get("@guid").then((uid) => {
+      dsName = "AuthAPI " + uid;
+      dataSources.CreatePlugIn("Authenticated API");
+      agHelper.RenameWithInPane(dsName, false);
+      dataSources.FillAuthAPIUrl();
+      dataSources.SaveDatasource();
+      apiPage.CreateApi("API" + uid, "GET", true);
+      apiPage.SelectPaneTab("Authentication");
+      // Last one if present on the authentication tab.
+      cy.get(apiPage._saveAsDS).last().should("be.enabled");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25148_Spec.ts:19]: @AmanAgarwal041 - Use `AssertElementEnabledDisabled` method to assert both` Edit datasource `buttons are `enabled`.

Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25148_Spec.ts]: Done

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes.
