### PR TITLE
fix: Header tags are not styled correctly in the Text widget

### LINKED ISSUE #10936: [Bug]: Header tags are not styled correctly in the Text widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use header tags like `h1`, `h2`, etc. inside the Text widget, these used to get the standard header styling applied to them in the past. But now, text inside these tags look like normal text. The problem seems to be that Tailwind resets the styles for these tags with the following CSS:

```css
h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
}
```

But then that kinda hints that perhaps, Tailwind styles could be used for styling my text, so if I try `<h1 class="text-6xl">Header</h1>`, that still doesn't show large text, it's still body sized.

### Steps To Reproduce

Drop a new text widget and use the following as the text:

```html
<h1>Header here</h1>
<p>Paragraph text here.</p>
```

Notice that the header and the paragraph have the same font size and look the same.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by jsartisan**
When we introduced tailwind to the project, the default heading styles on text widget got ruined. This PR fixes that.

Fixes #10936 

## Type of change
- Bug fix

## How Has This Been Tested?

- Manually tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/text-widget-default-styles 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.01 **(-0.01)** | 36.35 **(0)** | 34.69 **(0)** | 55.39 **(-0.01)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**</details>

### CODE REVIEW

File: app/client/src/widgets/TextWidget/component/index.tsx [hunk 1]
```diff
@@ -45,6 +45,42 @@ export const TextContainer = styled.div`
...
+    font-size: 0.75em;
+    margin: 1.67em 0;
+  }
+  h1,
+  h2,
+  h3,
+  h4,
+  h5,
+  h6 {
+    font-weight: bold;
```
Comment (somangshu) [inline app/client/src/widgets/TextWidget/component/index.tsx:74]: Should'nt we allow the tags to fallback browser defaults (I am assuming different weights from the browser for these tags), If someone if using the tags we should not make it unpredictable for the user.

**Review by somangshu — APPROVED** [review]
Changes looks good, Left one comment for discussion

**Comment by shwetha-ramesh** [comment]
@jsartisan Tested this PR. DP looks good.
image

Moving to Done.
