### PR TITLE
fix: Add logic to change default branch for git connected application

### LINKED ISSUE #11541: [Feature]: For git connected application always open the default branch application in edit mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We are opening the appsmith default application when the user clicks on edit. But when the app is connected to git we should always bring up the default application of the default branch.

### Why should this be worked on?

We are opening the appsmith default application when the user clicks on edit. But when the app is connected to git we should always bring up the default application of the default branch.

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description
We are opening the appsmith default application when the user clicks on edit. But when the app is connected to git we should always bring up the default application of the default branch.

Fixes #11541 #11223 #11651 #12931 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Locally
- Junit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: feat/fetch-app-by-default-branch 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.49 **(0)** | 37.98 **(0)** | 36.27 **(0)** | 56.7 **(-0.01)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(3.92)** | 100 **(0)** | 93.33 **(0.95)**</details>

### CODE REVIEW

**Comment by abhvsn** [comment]
I did not follow this can you please elaborate on this further.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java [hunk 1]
```diff
@@ -190,6 +196,24 @@ protected Criteria getIdCriteria(Object id) {
         return queryAll(List.of(organizationIdCriteria, repoCriteria, gitAuthCriteria), AclPermission.MANAGE_APPLICATIONS);
     }
 
+    @Override
+    public Mono<Application> getApplicationByDefaultApplicationIdAndDefaultBranch(String defaultApplicationId) {
+        String gitApplicationMetadata = fieldName(QApplication.application.gitApplicationMetadata);
+
+        Criteria applicationIdCriteria = where(gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.defaultApplicationId)).is(defaultApplicationId);
+        Criteria deletionCriteria = where(fieldName(QApplication.application.deleted)).ne(true);
+        boolean branchCriteria = where("this." + gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.branchName))
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java:205]: What is the use of `this.`, can you please point me to the right documentation as I'm not aware of this yet

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java [hunk 2]
```diff
@@ -190,6 +196,24 @@ protected Criteria getIdCriteria(Object id) {
...
+                .equals("this." +gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.defaultBranchName));
+
+        Query query = new Query();
+        query.addCriteria(where(gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.defaultApplicationId)).is(defaultApplicationId));
+        query.addCriteria(where(fieldName(QApplication.application.deleted)).ne(true));
+        query.equals(where("this." + gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.branchName))
+                .equals("this." +gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.defaultBranchName)));
+
+        return mongoOperations.findOne(query,Application.class);
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java:214]: Whay are we not using the `queryOne` method here?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java [hunk 3]
```diff
@@ -111,9 +112,21 @@ public ApplicationServiceCEImpl(Scheduler scheduler,
...
+    public Mono<Application> findByIdAndBranchName(String defaultApplicationId, String branchName) {
+            return findByBranchNameAndDefaultApplicationId(branchName, defaultApplicationId, READ_APPLICATIONS)
+                    // Check if the Appsmith application and the default branch are same
+                    .flatMap(application -> {
+                        if (StringUtils.isEmpty(branchName)) {
+                            if(Optional.ofNullable(application.getGitApplicationMetadata()).isEmpty()
+                                    || application.getGitApplicationMetadata().getBranchName().equals(application.getGitApplicationMetadata().getDefaultBranchName())) {
+                                return Mono.just(application);
+                            }
+                            return repository.getApplicationByGitBranchAndDefaultApplicationId(defaultApplicationId, application.getGitApplicationMetadata().getDefaultBranchName(), READ_APPLICATIONS)
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:124]: Do we want to query here for `getApplicationByDefaultApplicationIdAndDefaultBranch`? Also why are we looking for application with defaultBranch when `branchName` is empty? Can you please elaborate what is going on here?

**Review by abhvsn — COMMENTED** [review]
Some questions:
1. Have we tested the flow for already available applications where defaultBranch in remote is different than what we have in DB? Asking this because there are certain fields that we only store in the `defaultApplication` but with this implementation, we are requesting the `remoteDefaultBranchedApplication` always
2. Should we apply migration so that applications where defaultApplication and remote default branch are not same and insert the fields which are present in the gitApplicationMetadata of DB default application like gitAuth etc?
3. When we are running the sync flow are we creating the `remoteDefaultBranchedApplication` if the default branch is altered from remote?
4. Are we maintaining the `gitApplicationMetadata` for both `DBDefaultApplication` and `remoteBranchedDefaultApplication` henceforth? Is there any need for this, asking this because we have `findApplicationByDefaultApplicationIdAndBranchName` method present in quite a lot of places which needs to be addressed

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java (hunk 1 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java:205]: This is to compare two fields in the same collection where the query is being run. There are two ways to do this from v3.6+ one is to use aggregate with $expr inside the pipeline. Other one is to use this in the find query. Since this was a simple check on branchName and defaultBranchName i didn't feel the need to add a aggregate query here. 
https://docs.mongodb.com/v4.0/reference/operator/query/expr/
https://stackoverflow.com/questions/4442453/mongodb-query-condition-on-comparing-2-fields

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java (hunk 2 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java:214]: Query one internally calls the findOne. And the reason is i cannot achieve the expected output via queryOne as the way it forms the query object via List of criteria.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java (hunk 3 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:124]: This is because the client does not send the branchName on the first call in edit mode. This is to determine that condition and fetch the defaultBranchName application on the load.

**Comment by AnaghHegde** [comment]
> Some questions:
> 
> 1. Have we tested the flow for already available applications where defaultBranch in remote is different than what we have in DB? Asking this because there are certain fields that we only store in the `defaultApplication` but with this implementation, we are requesting the `remoteDefaultBranchedApplication` always
> 2. Should we apply migration so that applications where defaultApplication and remote default branch are not same and insert the fields which are present in the gitApplicationMetadata of DB default application like gitAuth etc?
> 3. When we are running the sync flow are we creating the `remoteDefaultBranchedApplication` if the default branch is altered from remote?
> 4. Are we maintaining the `gitApplicationMetadata` for both `DBDefaultApplication` and `remoteBranchedDefaultApplication` henceforth? Is there any need for this, asking this because we have `findApplicationByDefaultApplicationIdAndBranchName` method present in quite a lot of places which needs to be addressed

1. Yes this tested on the scenarios you are referring to.
2. No we do not need migration here, as the logic takes care of updating the these fields on refresh/sync workflow. On the change in defaultBranch all the details needed are copied to the respective application.
3. Yes we are doing that. There is oneError handler at L.1574 which is doing the same
4. I am not fully confident on removing the gitApplicationMetadata from the defaultBranch app yet, for the same reason you mentioned. But i don't see any harm in doing so as the majority cases are in GitService class and that is handled already via the newly created method in ApplicationService to handle this scenario.

**Comment by AnaghHegde** [comment]
@abhvsn 
1. Yes this tested on the scenarios you are referring to.
2. No we do not need migration here, as the logic takes care of updating the these fields on refresh/sync workflow. On the change in defaultBranch all the details needed are copied to the respective application.
3. Yes we are doing that. There is oneError handler at L.1574 which is doing the same
4. I am not fully confident on removing the gitApplicationMetadata from the defaultBranch app yet, for the same reason you mentioned. But i don't see any harm in doing so as the majority cases are in GitService class and that is handled already via the newly created method in ApplicationService to handle this scenario.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java (hunk 3 above)
Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:124]: IMO we should update the client-side implementation for this instead of doing this hack. This might confuse folks working on this feature in the future.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 4]
```diff
@@ -1295,7 +1295,7 @@ private String getReason() {
     }
 
     Mono<Application> getApplicationById(String applicationId) {
-        return applicationService.findById(applicationId, MANAGE_APPLICATIONS)
+        return applicationService.getApplicationByDefaultApplicationIdAndDefaultBranch(applicationId)
```
[the remark this answers is not in the document]
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java]: This would make sense if we go with older approach. I have updated logic per latest approach.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java [hunk 5]
```diff
@@ -190,6 +196,24 @@ protected Criteria getIdCriteria(Object id) {
...
+        Criteria deletionCriteria = where(fieldName(QApplication.application.deleted)).ne(true);
+        boolean branchCriteria = where("this." + gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.branchName))
+                .equals("this." +gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.defaultBranchName));
+
+        Query query = new Query();
+        query.addCriteria(where(gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.defaultApplicationId)).is(defaultApplicationId));
+        query.addCriteria(where(fieldName(QApplication.application.deleted)).ne(true));
+        query.equals(where("this." + gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.branchName))
+                .equals("this." +gitApplicationMetadata + "." + fieldName(QApplication.application.gitApplicationMetadata.defaultBranchName)));
+
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java:213]: Why are we duplicating the criteria here?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 6]
```diff
@@ -1407,46 +1407,28 @@ private String getReason() {
...
-                                        .onErrorResume(throwable -> {
-                                            log.warn(" No application exists in DB for the local branch of file system", throwable);
-                                            return Mono.empty();
-                                        })
-                                        .then(gitExecutor.deleteBranch(repoPath, gitBranch)))
-                                .then(Mono.just(gitBranchListDTOS));
-
                         if(defaultBranchRemote.equals(dbDefaultBranch)) {
-                            return monoBranchList.zipWith(Mono.just(application));
+                            return Mono.just(gitBranchListDTOS).zipWith(Mono.just(application));
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1411]: Are we not pruning the branches in DB if both DB and local repo have the same default branch?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 7]
```diff
@@ -1407,46 +1407,28 @@ private String getReason() {
...
+                                    .onErrorResume(throwable -> checkoutRemoteBranch(defaultApplicationId, defaultBranchRemote))
+                                    // Copy the gitApplicationMetadata to the app
+                                    .flatMap(application1 -> {
+                                        application1.setGitApplicationMetadata(gitApplicationMetadata);
+                                        application1.getGitApplicationMetadata().setBranchName(defaultBranchRemote);
+                                        application1.getGitApplicationMetadata().setDefaultBranchName(defaultBranchRemote);
+                                        return applicationService.save(application1);
+                                    })
+                                    // Update the default branch name in all the branched applications
+                                    .flatMap(application1 -> applicationService.findAllApplicationsByDefaultApplicationId(defaultApplicationId)
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1425]: I don't think that we are storing the default branch in each application. Just the default application's gitApplicationMetadata has this info so no need to update this

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java (hunk 5 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java:213]: I was testing and forgot to remove the unused part. My bad

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 6 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1411]: No with the delete branchs, it does not make sense to delete branch's in the sync flow. To keep it simple lets just delete the branch in the new delete branch API.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 7 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1425]: I will add a migration for this

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1425]: That makes sense. I had added this logic in the past where the idea was to delete the Appsmith default Application as well.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 6 above)
Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1411]: I still think this can be useful in scenarios where user has lot of stale branches, but let us present this change in a bigger forum as I'm not aware if we are making this change from product point of view.

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1411]: @AnaghHegde this PR is pending as we have made changes in the sync branch flows. Can we please add this change as a separate PR and let's merge this one? Asking this because both these changes are independent of each other and we are blocked on frontend to roll out delete branch feature

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 8]
```diff
@@ -1409,46 +1409,22 @@ public Mono<List<GitBranchDTO>> listBranchForApplication(String defaultApplicati
...
-                            return monoBranchList.zipWith(applicationService.save(application));
+                            // Get the application from DB by new defaultBranch name
+                            return applicationService.findByBranchNameAndDefaultApplicationId(defaultBranchRemote, defaultApplicationId, MANAGE_APPLICATIONS)
+                                    // Check if the branch is already present, If not follow checkout remote flow
+                                    .onErrorResume(throwable -> checkoutRemoteBranch(defaultApplicationId, defaultBranchRemote))
+                                    // Copy the gitApplicationMetadata to the app
+                                    .flatMap(application1 -> {
+                                        application1.setGitApplicationMetadata(gitApplicationMetadata);
+                                        application1.getGitApplicationMetadata().setBranchName(defaultBranchRemote);
+                                        application1.getGitApplicationMetadata().setDefaultBranchName(defaultBranchRemote);
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1423]: Are we storing the default branchName whenever user updates the default branch? Should we keep the defaultBranch is the defaultApplicationMetadata only, otherwise we will have to update previous defaultBranched application gitMetadata.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 9]
```diff
@@ -2071,7 +2047,7 @@ public Mono<Application> deleteBranch(String defaultApplicationId, String branch
                     GitApplicationMetadata gitApplicationMetadata = application.getGitApplicationMetadata();
                     Path repoPath = Paths.get(application.getOrganizationId(), defaultApplicationId, gitApplicationMetadata.getRepoName());
                     if(branchName.equals(gitApplicationMetadata.getDefaultBranchName())) {
-                        return Mono.error(new AppsmithException(AppsmithError.GIT_ACTION_FAILED, " delete branch", "Cannot delete default branch"));
+                        return Mono.error(new AppsmithException(AppsmithError.GIT_ACTION_FAILED, " delete branch.", " Cannot delete default branch"));
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2050]:
```suggestion
                        return Mono.error(new AppsmithException(AppsmithError.GIT_ACTION_FAILED, "delete branch", " Cannot delete default branch"));
```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationFetcherCEImpl.java [hunk 10]
```diff
@@ -113,8 +113,12 @@ public Mono<UserHomepageDTO> getAllApplications() {
                     Flux<Application> applicationFlux = applicationRepository
                             .findByMultipleOrganizationIds(orgIds, READ_APPLICATIONS)
                             .filter(application -> application.getGitApplicationMetadata() == null
-                                    || (StringUtils.equals(application.getId(), application.getGitApplicationMetadata().getDefaultApplicationId()))
+                                    || (!Optional.ofNullable(application.getGitApplicationMetadata().getDefaultBranchName()).isEmpty()
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationFetcherCEImpl.java:116]:
```suggestion
                                    || (!StringUtils.isEmpty(application.getGitApplicationMetadata().getDefaultBranchName()))
```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationFetcherCEImpl.java [hunk 11]
```diff
@@ -113,8 +113,12 @@ public Mono<UserHomepageDTO> getAllApplications() {
...
+                                    && application.getGitApplicationMetadata().getBranchName().equals(application.getGitApplicationMetadata().getDefaultBranchName()))
                             )
+                            /*.filter(application -> application.getGitApplicationMetadata() == null
+                                    || (StringUtils.equals(application.getId(), application.getGitApplicationMetadata().getDefaultApplicationId()))
+                            )*/
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationFetcherCEImpl.java:121]: Can we please remove the commented code here if not needed

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 8 above)
Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1423]: I wanted to keep the data confined to `defaultApplicationMetadata` because there are certain other fields except `defaultBranchName` like `isRepoPrivate` which is currently stored only in defaultApplicationGitMetadata object so that whenever we receive the changes from remote we only update the defaultApplicationMetadata

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java [hunk 12]
```diff
@@ -2546,4 +2547,37 @@ public void cloneApplication_WithCustomSavedTheme_ThemesAlsoCopied() {
...
+
+
+        Mono<Application> getApplication = applicationService.findByIdAndBranchName(gitConnectedApp.getId(), "release");
+        StepVerifier.create(getApplication)
+                .assertNext(application1 -> {
+                    assertThat(application1).isNotNull();
+                    assertThat(application1.getGitApplicationMetadata().getBranchName()).isNotEqualTo(gitConnectedApp.getGitApplicationMetadata().getBranchName());
+                    assertThat(application1.getGitApplicationMetadata().getBranchName()).isEqualTo(application.getGitApplicationMetadata().getBranchName());
+                    assertThat(application1.getId()).isEqualTo(gitConnectedApp.getId());
+                    assertThat(application1.getName()).isEqualTo(application.getName());
```
Comment (abhvsn) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java:2578]: Should we test this flow with listBranch API as that is the place where we are altering the defaultBranchName 🤔

**Comment by abhvsn** [comment]
If possible can you also add a testcase for getAllApplications `/new` API?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java (hunk 12 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java:2578]: Checking this here would be enough.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 13]
```diff
@@ -1266,7 +1267,15 @@ private Mono<Application> checkoutRemoteBranch(String defaultApplicationId, Stri
...
                                             .zipWith(Mono.just(application1))
-                            );
+                            )
+                            .onErrorResume(throwable -> {
+                                if (throwable instanceof DuplicateKeyException) {
+                                    return fileUtils.reconstructApplicationJsonFromGitRepo(srcApplication.getOrganizationId(), defaultApplicationId, srcApplication.getGitApplicationMetadata().getRepoName(), branchName)
+                                            .zipWith(Mono.just(tuple.getT2()));
+                                }
+                                log.error(" Git checkout remote branch failed", throwable.getMessage());
+                                return Mono.error(new AppsmithException(AppsmithError.INTERNAL_SERVER_ERROR));
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1277]: Internal server error is too generic can we use git error so that it will be easy to detect the root cause

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 14]
```diff
@@ -1266,7 +1267,15 @@ private Mono<Application> checkoutRemoteBranch(String defaultApplicationId, Stri
                             .flatMap(application1 ->
                                     fileUtils.reconstructApplicationJsonFromGitRepo(srcApplication.getOrganizationId(), defaultApplicationId, srcApplication.getGitApplicationMetadata().getRepoName(), branchName)
                                             .zipWith(Mono.just(application1))
-                            );
+                            )
+                            .onErrorResume(throwable -> {
+                                if (throwable instanceof DuplicateKeyException) {
+                                    return fileUtils.reconstructApplicationJsonFromGitRepo(srcApplication.getOrganizationId(), defaultApplicationId, srcApplication.getGitApplicationMetadata().getRepoName(), branchName)
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1273]: Let's add a comment on why the handling is different for duplicate key exceptions than in the other scenarios.

**Review by abhvsn — APPROVED** [review]
LGTM

**Review by abhvsn — APPROVED** [review]
