### PR TITLE
fix: changed the editing to false on onFocus in PrimaryColumnsControl

### LINKED ISSUE #9188: [Bug]: Column name on property pane changes on changing the order
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[LOOM DEMO](https://www.loom.com/share/54029a63fe7143f6a86a5ccddf04993d)

### Steps To Reproduce

1. Drag and drop a table widget
2. Open the property pane
3. Click on any column name in property pane and drag to change the order
4. Observe that previous column name on property pane changes to same name

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

Column name in the property of the table widget duplicates when dragging the columns from top to bottom or from bottom to top.

By setting the state `setEditing` to false on `onFocus` solved the issue, since it will stop the editing of the input while dragging.

Fixes #9188 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I have tested this manually. 

Instructions to test:

1. Click one of the rows of the column property in the property pane of the table widget
2. With mouse still being pressed down, drag the row down.
3. Once the row is dragged to the desired position release the mouse button.
4. Observe now that the column sequence is changed correctly both in the table and the column property in the property pane.

Please find below the video for the reference:
[LOOM DEMO](https://www.loom.com/share/766f8a2d7e2246eab6558d27ee1c754f)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix-column_name_order_change_table 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

File: app/client/src/components/propertyControls/PrimaryColumnsControl.tsx [hunk 1]
```diff
@@ -140,7 +140,7 @@ function ColumnControlComponent(props: RenderComponentProps) {
   );
 
   const onFocus = () => {
-    setEditing(true);
+    setEditing(false);
```
Comment (SatishGandham) [inline app/client/src/components/propertyControls/PrimaryColumnsControl.tsx:143]: @keyurparalkar Won't this impact the editing of column name?
I think you should set editing to false when dragging starts.

Comment (keyurparalkar) [reply app/client/src/components/propertyControls/PrimaryColumnsControl.tsx:143]: @SatishGandham I tested after making this change and editing of column name was working fine. 

The issue is: whenever we drag the columns from top to bottom the focused state of the cell continues until the mouse button is released. Overehere the expected behaviour is once the mouse button is released then the focused state should persists on that dragged row, but instead the focus still remains on the previous row due to `focusedIndex` value not changed on the drag end. Due to this reason the column name was appearing twice due to `setEditing(true)` on drag complete.  That is why the `setEditing` is set to false to avoid that behaviour

**Review by SatishGandham — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@keyurparalkar Verified this PR and working as expected now
