### PR TITLE
fix: List Widget shows cyclic dependency error when children widgets with bindings in action are deleted

### LINKED ISSUE #8862: [Bug]: List Widget shows cyclic dependency error when children widgets with bindings in action are deleted
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever we add binding to the action of the list widget's children and later delete it, the list widget shows cyclic dependencies every time we load the app.

### Steps To Reproduce

1. Drop a list widget
2. Drop an icon button into the list
3. Bind the onClick action of the icon button to `{{List1.backgroundColor}}` and after that delete the icon button.
4. Refresh the page and notice the cyclic dependency error.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #8862 

## Type of change
- Bug fix

## How Has This Been Tested?
- Added jest test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/list-widget-trigger-path-bug 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.84 **(0.03)** | 36.59 **(0.05)** | 33.48 **(0.03)** | 55.37 **(0.02)**
 :green_circle: | app/client/src/sagas/WidgetDeletionSagas.ts | 40.94 **(2.43)** | 25 **(4.76)** | 42.11 **(4.01)** | 42.42 **(2.56)**
 :green_circle: | app/client/src/sagas/WidgetEnhancementHelpers.ts | 38.36 **(1.37)** | 27.45 **(1.96)** | 14.29 **(0)** | 40.91 **(1.52)**
 :green_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 60.78 **(1.3)** | 41.94 **(2.97)** | 57.14 **(2.79)** | 60 **(1.56)**</details>

### CODE REVIEW

File: app/client/src/sagas/WidgetOperationUtils.ts [hunk 1]
```diff
@@ -817,3 +818,45 @@ export function* getParentWidgetIdForGrouping(
 
   return pastingIntoWidgetId;
 }
+
+/**
+ * this saga clears out the enhancementMap, template and dynamicBindingPathList when a child
```
Comment (hetunandu) [inline app/client/src/sagas/WidgetOperationUtils.ts:823]:
```suggestion
 * this saga clears out the enhancementMap, template, dynamicBindingPathList and dynamicTriggerPathList when a child
```

File: app/client/src/sagas/WidgetOperationUtils.ts [hunk 2]
```diff
@@ -817,3 +818,45 @@ export function* getParentWidgetIdForGrouping(
...
+ * is deleted in list widget
+ *
+ * @param widgets
+ * @param widgetId
+ * @param widgetName
+ * @param parentId
+ */
+export function updateListWidgetPropertiesOnChildDelete(
```
Comment (mohanarpit) [inline app/client/src/sagas/WidgetOperationUtils.ts:831]: Quick question: Is it not possible to define this function in `BaseWidget` and allow widget classes to override this base function & perform custom post processing whenever the widget is deleted? I'm asking because we have some special handling for tab widget, list widget and in some places chart widget. This make code maintenance very hard for a widget developer.

Comment (jsartisan) [reply app/client/src/sagas/WidgetOperationUtils.ts:831]: @riodeuno Can we do this?

**Comment by jsartisan** [comment]
action: https://github.com/appsmithorg/appsmith/runs/4138072323?check_suite_focus=true

**Comment by Rishabh-Rathod** [comment]
@jsartisan Just to confirm will this change also fix the already present dependency error due to incorrect `dynamicBindingPathList` and `dynamicTriggerPathList`

**Comment by jsartisan** [comment]
No no. That fix will be done by a Trisha.
