### PR TITLE
fix: Login Redirection fixed for Authentication failure

### LINKED ISSUE #18670: [Bug]: Slug path looses redirection param when user login fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On a private app where a user has to login to access app, the redirection path gets lost when user login fails so user is redirected to the home page and not the app link
- [x] #21750

### Steps To Reproduce

1. Use a private shared link to access an app on incognito
2. Cause a failed login attempt and notice the URL slug looses the `redirection` query param
3. Logging in correctly now causes the user to land on the Appsmith homepage and not the shared app link. User needs to reenter the shared URL to land on the correct page

image

image

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by NilanshBansal**
Fixes #18670 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
https://github.com/appsmithorg/TestSmith/issues/2203

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java [hunk 1]
```diff
@@ -33,7 +36,13 @@ public Mono<Void> onAuthenticationFailure(WebFilterExchange webFilterExchange, A
         // On authentication failure, we send a redirect to the client's login error page. The browser will re-load the
         // login page again with an error message shown to the user.
         String state = exchange.getRequest().getQueryParams().getFirst(Security.QUERY_PARAMETER_STATE);
+        MultiValueMap<String, String> queryParams = exchange.getRequest().getQueryParams();
```
Comment (nayan-rafiq) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java:39]: Is there any chance that `exchange.getRequest().getQueryParams()` will return null?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java [hunk 2]
```diff
@@ -33,7 +36,13 @@ public Mono<Void> onAuthenticationFailure(WebFilterExchange webFilterExchange, A
...
         String originHeader = "/";
+        String redirectUrl = null;
+        if (queryParams.getFirst(REDIRECT_URL_QUERY_PARAM) != null) {
```
Comment (nayan-rafiq) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java:42]: Shouldn't we check empty values as well?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java [hunk 3]
```diff
@@ -68,18 +77,21 @@ public Mono<Void> onAuthenticationFailure(WebFilterExchange webFilterExchange, A
...
-                defaultRedirectLocation = URI.create(originHeader + "/user/login?error=true&message=" +
-                    URLEncoder.encode(exception.getMessage(), StandardCharsets.UTF_8));
+                url = originHeader + "/user/login?error=true&message=" + URLEncoder.encode(exception.getMessage(), StandardCharsets.UTF_8);
             } else {
-                defaultRedirectLocation = URI.create(originHeader + "/user/login?error=true");
+                url = originHeader + "/user/login?error=true";
             }
         }
-
+        if (redirectUrl != null){
```
Comment (nayan-rafiq) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java:91]: Same as above. What should we do if redirectUrl is empty?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java (hunk 1 above)
Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java:39]: No chance. Check one line above for fetching `state`, if that was the case, it would have failed long ago.

Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationFailureHandlerCE.java:39]: I think that's not required.

**Review by nayan-rafiq — APPROVED** [review]

**Comment by NilanshBansal** [comment]
/build-deploy-preview sha= b2ac007347ae89083d255b820ec952b43dd10802

**Comment by NilanshBansal** [comment]
@ramsaptami @eco-monk can you please verify the change on the DP generated.
https://ce-21495.dp.appsmith.com/

**Comment by ramsaptami** [comment]
Works fine for edit and view modes of a private app.
@NilanshBansal please add test cases so we don't regress on this flow

**Comment by eco-monk** [comment]
DP looks good to me.

**Comment by NilanshBansal** [comment]
We can merge this once the test cases are completed. Ref: https://github.com/appsmithorg/TestSmith/issues/2203
CC: @ginilpg @kocharrahul7 @eco-monk

File: app/client/cypress/integration/Regression_TestSuite/ServerSideTests/LoginTests/LoginFailure_spec.js [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+      })
+      .then(() => cy.GetUrlQueryParams())
+      .then((queryParams) => {
+        expect(decodeURIComponent(queryParams.redirectUrl)).to.eq(appUrl);
+        cy.LoginUser("user@error.com", "pwd_error", false);
+      })
+      .then(() => cy.GetUrlQueryParams())
+      .then((queryParams) => {
+        expect(decodeURIComponent(queryParams.error)).to.eq("true");
+        expect(decodeURIComponent(queryParams.redirectUrl)).to.eq(appUrl);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ServerSideTests/LoginTests/LoginFailure_spec.js:23]: This is when login fails, how about the next step mentioned in bug? 
When login is successful - then?

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good!

File: app/client/cypress/integration/Regression_TestSuite/ServerSideTests/LoginTests/LoginFailure_spec.js (hunk 4 above)
Comment (eco-monk) [reply app/client/cypress/integration/Regression_TestSuite/ServerSideTests/LoginTests/LoginFailure_spec.js:23]: Yep, that's a good idea.
I stuck to just verifying whether redirectUrl is persisted, because that's what is technically fixed here.
Better to cover the whole scenario as suggested.

**Review by nayan-rafiq — APPROVED** [review]
