### PR TITLE
fix: Truncate title in tooltips in table cell if it exceeds 200 characters

### LINKED ISSUE #23156: [Bug]: The table tooltip covers the entire data and doesn't disappear
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When hovering on a column of the Table widget where the text is longer, it gets displayed in a tooltip. If the text is very long, it covers the whole table, resulting in a bad user experience. Turning on Cell Wrapping is also not an option, as it is not desired to show the whole content in the cell. Therefore, we need to allow users to disable/enable the tooltip as needed.
image

[Front thread](https://app.frontapp.com/open/msg_1s0so098?key=R3a1p1q_bn0FUJRWAjhWmhm6P1BtJGYc)

### Steps To Reproduce

1. Add a Table widget to the canvas.
2. Ensure one of the cells contains a very long text.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/Self Hosted

Front logo [Front conversations](https://app.frontapp.com/open/top_a1pak)

### PR DESCRIPTION
**Pull request by rahulbarwal**
## Description
Truncate the title in tooltips if it exceeds 1000 characters to improve readability.

Fixes #23156
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Widget"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9697818492>
> Commit: a4007cb6372e7872b1c6472efdabee1a4932a83c
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9697818492&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Widget`

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Improved tooltip functionality to automatically truncate text that exceeds a set character limit, enhancing readability.

### CODE REVIEW

File: app/client/src/widgets/TableWidgetV2/component/cellComponents/AutoToolTipComponent.tsx [hunk 1]
```diff
@@ -43,6 +44,13 @@ function useToolTip(
   const ref = createRef<HTMLDivElement>();
   const [requiresTooltip, setRequiresTooltip] = useState(false);
 
+  const titleToDisplay = useMemo(() => {
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/cellComponents/AutoToolTipComponent.tsx:47]: Why do we need to use `useMemo` here?

Comment (rahulbarwal) [reply app/client/src/widgets/TableWidgetV2/component/cellComponents/AutoToolTipComponent.tsx:47]: Coming to think of it, I could have avoided it. Out of habit I put it, do you see any -ve implications of this?

Comment (ashit-rath) [reply app/client/src/widgets/TableWidgetV2/component/cellComponents/AutoToolTipComponent.tsx:47]: Nothing significant but it's a bit unnecessary to add pre-optimisation to something where not required since such optimizations always comes with a cost

Comment (rahulbarwal) [reply app/client/src/widgets/TableWidgetV2/component/cellComponents/AutoToolTipComponent.tsx:47]: ok, let me do this without `useMemo`

Comment (rahulbarwal) [reply app/client/src/widgets/TableWidgetV2/component/cellComponents/AutoToolTipComponent.tsx]: done.

**Review by ashit-rath — APPROVED** [review]
