### PR TITLE
fix: converted sniping test cases to support suggested widgets, api binding bug

### LINKED ISSUE #26897: [Bug]: Invalid binding of table data when used suggested widgets for an action returning object
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you bind a data response to a table using suggested widget, it throws an error as the response bound to it is `{{Api1.data}}` which is not an array, instead it should have `{{Api1.data.users}}` (for mock-api example).
Screenshot 2023-09-03 at 5 51 53 PM

### Steps To Reproduce

1. Drag a table on the canvas
2. Create an action that returns an object
3. Click on run, add an existing suggested widget
4. Observe the error

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
This PR fixes : 
- the issue of binding suggested widget to already bound table widget when the action response returns an object instead of an array
- the number of test cases which were earlier for sniping mode are not supported for suggested widgets present in the new binding UI

#### PR fixes following issue(s)
Fixes #26897 

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/support/Pages/DataSources.ts [hunk 1]
```diff
@@ -1674,32 +1684,53 @@ export class DataSources {
...
+    widget: Widgets,
+    force = false,
+    index = 0,
+    parentClass?: string,
+  ) {
     switch (widget) {
       case Widgets.Dropdown:
-        this.agHelper.GetNClick(this._suggestedWidget("SELECT_WIDGET"));
+        this.agHelper.GetNClick(
+          this._suggestedWidget("SELECT_WIDGET", parentClass),
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1696]: What is parent class? Why is user now forced to send this parent class?

File: app/client/cypress/support/Pages/DataSources.ts [hunk 2]
```diff
@@ -1674,32 +1684,53 @@ export class DataSources {
     );
   }
 
-  public AddSuggestedWidget(widget: Widgets, force = false, index = 0) {
+  public AddSuggestedWidget(
+    widget: Widgets,
+    force = false,
+    index = 0,
+    parentClass?: string,
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1691]: Make NewWidget addition default & remove methods sending. If its existing - let it be sent.

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+  dataSources,
+  propPane,
+  table,
+  apiPage,
+} from "../../../../support/Objects/ObjectsCore";
+import { Widgets } from "../../../../support/Pages/DataSources";
+
+describe("Test Create Api and Bind to Table widget", function () {
+  before(() => {
+    agHelper.AddDsl("tableWidgetDsl");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: DragDrop table instead of Dsl.

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts [hunk 4]
```diff
@@ -37,7 +42,12 @@ describe("API Bugs", function () {
       dataManager.dsValues[dataManager.defaultEnviorment].mockApiObjectUrl,
     );
     apiPage.RunAPI();
-    dataSources.AddSuggestedWidget(Widgets.Table, false, -1);
+    dataSources.AddSuggestedWidget(
+      Widgets.Table,
+      false,
+      0,
+      dataSources._addSuggestedExisting,
+    );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts:50]: If issue exists for Existing widget, how is this passing here?

File: app/client/cypress/support/Pages/DataSources.ts [hunk 5]
```diff
@@ -1674,32 +1684,53 @@ export class DataSources {
     );
   }
 
-  public AddSuggestedWidget(widget: Widgets, force = false, index = 0) {
+  public AddSuggestedWidget(
+    widget: Widgets,
+    force = false,
+    index = 0,
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1690]: Move these to last, after parentClass parameter, since the default is used most of the time.

File: app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_2_spec.ts [hunk 6]
```diff
@@ -433,7 +433,32 @@ describe("Validate CRUD queries for Amazon S3 along with UI flow verifications",
     });
   });
 
-  // Removed the Select Widget snipping mode test case as we have removed the `Connect widget` element from the new bindings UI - 6th test case
+  it("6. Verify Adding Suggested widget with specific name functionality - S3 ", () => {
+    datasourceName = "";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_2_spec.ts:437]: Why is datasourceName set to ""?

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts (hunk 4 above)
Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts:50]: Because this PR also has a fix for the existing widget in suggested list with the object response.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts:50]: Add a test validation for new widget also. As part of bug - to make sure both existing & new does not reoccur.

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts (hunk 3 above)
Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: This table widget dsl adds a `Older version of Table` but if we drag and drop the table then it will add a New version of table widget. I added a support for `Older version of Table` in the existing suggested widget in the binding UI to connect the data to it.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: I added a support for Older version of Table in the existing suggested widget in the binding UI to connect the data to it - dint get.
You mean existing widget - adds a T1 widget & hence dsl is needed here?
Exiting widget - for me is a drag dropped widget & then binding to it
New Widget - Running an action & mapping to a widget from query editor page itself.
Please correct if my understanding is incorrect here.

File: app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_2_spec.ts (hunk 6 above)
Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_2_spec.ts:437]: Will remove this.

File: app/client/cypress/support/Pages/DataSources.ts (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/cypress/support/Pages/DataSources.ts:1696]: Its not mandatory. If you don't send any parent class then it behaves like the earlier add suggested widget logic. ref : https://github.com/appsmithorg/appsmith/pull/26911/files#diff-745de5dfe12de5fe01a6700879bb359863e5becc8dd641f984252ed4385a27afR193

File: app/client/cypress/support/Pages/DataSources.ts (hunk 5 above)
Comment (AmanAgarwal041) [reply app/client/cypress/support/Pages/DataSources.ts:1690]: parentclass parameter is also optional. Should we move this parameter before the default variables ?

Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/DataSources.ts:1690]: Yes. And please assign default value in method. Right now it seems like its undefined unless I go into the locator to understand

File: app/client/cypress/support/Pages/DataSources.ts [hunk 7]
```diff
@@ -185,8 +188,15 @@ export class DataSources {
...
-    ".t--suggested-widget-" + widgetType + "";
+
+  private _suggestedWidget = (widgetType: string, parentClass?: string) =>
+    parentClass
+      ? "//div[contains(@class, '" +
+        parentClass +
+        "')]//div[contains(@class, 't--suggested-widget-" +
+        widgetType +
+        "')]"
+      : ".t--suggested-widget-" + widgetType + "";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:199]: If parent is not sent, does it take existing or new widget from right pane?

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts (hunk 3 above)
Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: Earlier the logic of existing suggested widgets had a check for displaying only `Table widget v2` but now added a support for `Table widget` (older version of table) to include in the existing list of widgets.
The dsl adds an older version of table on the canvas which now with the above updated logic can be connect from the existing suggested widgets list.
But if we drag a table widget from the widget explorer to the canvas, it adds table widget v2 which will becomes irrelevant for the above test case.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: Why is older version support needed here when Users cannot drag drop it from UI?

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: Exiting widget - for me is a drag dropped widget & then binding to it
New Widget - Running an action & mapping to a widget from query editor page itself.

Need confirmation for this.

File: app/client/cypress/support/Pages/DataSources.ts (hunk 7 above)
Comment (AmanAgarwal041) [reply app/client/cypress/support/Pages/DataSources.ts]: fixed. By default the parent class will be selecting from Add new widget list.

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts [hunk 8]
```diff
@@ -86,4 +86,36 @@ describe("API Bugs", function () {
...
+
+    // Create another API so that it returns object response
+    apiPage.CreateAndFillApi(
+      dataManager.dsValues[dataManager.defaultEnviorment].mockApiObjectUrl,
+      "OBJECT_RESPONSE",
+    );
+    apiPage.RunAPI();
+    dataSources.AddSuggestedWidget(
+      Widgets.Table,
+      dataSources._addSuggestedExisting,
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts:113]: Where is Table DragDrop for using Existing widget here?

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts (hunk 3 above)
Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: This test case that I removed earlier was having old version of table being imported by the dsl.
Now since the sniping mode feature (i.e. to bind the data to a widget by selecting the widget from the canvas) is removed. 
There will now be a list of suggested widgets in the binding UI present on the Action Right pane (which for now supports only Table version 2 widget). So, to fix this older version table test case, we need to enable the older version of table in existing suggested widgets list : https://github.com/appsmithorg/appsmith/pull/26911/files#diff-be2f52c7c46a01aaebb81fbe4a1913f0cb3d7bdb14deaf331028dded3a06243aR345
For the new version of table : https://github.com/appsmithorg/appsmith/pull/26911/files#diff-768b435f0af4aadef3496ebbaf35296ed25e28c846054bf4525fbf09d0f3e02c

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: I understand you have added support now, but asking if its needed. We can replace the DSL with dragdrop & take action in the the spec.

Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: I updated the table version v2 test case with dragdrop table action in the spec. But it can't be done for table version v1. In that case, should we remove the test case for old table or should we continue with the dsl implementations?

If we want to remove the particular test case : In that case giving support for table version v1 in the existing suggested widgets list doesn't make sense thus it shall be removed as well.

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts [hunk 9]
```diff
@@ -86,4 +86,36 @@ describe("API Bugs", function () {
...
   });
+
+  it("5. Bug 26897, Invalid binding of table data when used existing suggested widgets for an action returning object", function () {
+    // Case where api returns array response
+    apiPage.CreateAndFillApi(
+      dataManager.dsValues[dataManager.defaultEnviorment].mockApiUrl,
+      "ARRAY_RESPONSE",
+    );
+    apiPage.RunAPI();
+    dataSources.AddSuggestedWidget(Widgets.Table);
```
[the remark this answers is not in the document]
Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts]: Updated the test case

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts (hunk 8 above)
Comment (AmanAgarwal041) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/ApiBugs_Spec.ts:104]: Updated the test case. Now it drags and drop the table before binding.

File: app/client/cypress/support/Pages/DataSources.ts (hunk 2 above)
Comment (AmanAgarwal041) [reply app/client/cypress/support/Pages/DataSources.ts]: Done. Update the logic

File: app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts (hunk 3 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/Binding/TableWithSnipingMode_spec.ts:13]: Yes Table v1 support can be removed. Since its not going to impact the users.
For TableV2 - do we have existing & new widget covered in other specs? If yes - this spec can be entirely removed.

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress changes looks fine

**Review by Aishwarya-U-R — APPROVED** [review]

**Review by rajatagrawal — DISMISSED** [review]

**Review by rajatagrawal — APPROVED** [review]
