### PR TITLE
fix: 8956 connection and deploy v2

### LINKED ISSUE #8956: [Task] [GitSync] Progress bar and error states on the connection and deploy tabs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Show progress bar on clicking connect. Should mock the progress: (@haoin111) https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=3%3A6076
- [x] Show connection error:(@haojin111) https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=3%3A6611
- [x] Show progress bar on during commit and push: (@haojin111)  https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=3%3A7707
- [x] Show errors during commit and push: (@haojin111) https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A8238, https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A9285
- [x] Display help message on top along with the doc link on the generate key step: https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=1%3A47586
- [x] Update deploy key section UI: https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=3%3A5544. (  @Rishabh-Rathod  )
- [x] Validate ssh url, should still continue on failing validation since it's difficult to validate all cases, regex:  `/^(ssh|.+@).*/`, i.e. url should either start with `ssh://` or `user@` (  @Rishabh-Rathod  )

Other tasks
- [x] Show Positive reinforcement in deploy preview (  @Rishabh-Rathod  )
- [x] Show Loader for git status  ( @Rishabh-Rathod  )
- [x] Show Loader for merge status  (  @Rishabh-Rathod  )
- [x] Success, and Failure states for merge status ( @Rishabh-Rathod  )
https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A9837 
- [x] Show changes being pushed ( like n widgets modified, m queries modified )(@haojin111)
https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A8238
- [x] Show Last Deployed time ( @Rishabh-Rathod  )
Screenshot 2021-11-09 at 3 45 19 PM

### Not yet ready
- [ ] Using Default config and application config test ( backend dependency )

### PR DESCRIPTION
**Pull request by haojin111**
## Description

> Added status bar of progressing to connect to git url with information.
> Added Error message displaying part
> Implemented 1st sub task

Related to: #8956 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Please refer attached task.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8956-connection-and-deploy-v2 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.76 **(-0.02)** | 36.61 **(0)** | 33.47 **(-0.05)** | 55.3 **(-0.02)**
 :green_circle: | app/client/src/actions/gitSyncActions.ts | 63.64 **(0.37)** | 100 **(0)** | 0 **(0)** | 76.6 **(2.18)**
 :red_circle: | app/client/src/api/GitSyncAPI.tsx | 41.67 **(-2.52)** | 100 **(0)** | 6.67 **(-0.47)** | 42.22 **(-2.78)**
 :red_circle: | app/client/src/components/ads/TextInput.tsx | 75.21 **(0.42)** | 47.66 **(-0.88)** | 84.21 **(0)** | 74.31 **(0.24)**
 :green_circle: | app/client/src/constants/messages.ts | 74.07 **(0)** | 100 **(0)** | 23.29 **(0)** | 79.73 **(0.11)**
 :red_circle: | app/client/src/pages/Editor/GeneratePage/components/CrudInfoModal.tsx | 80.77 **(-0.36)** | 82.14 **(0)** | 40 **(0)** | 79.17 **(-0.42)**
 :sparkles: :new: | **app/client/src/pages/common/SuccessTick.tsx** | **45.45** | **100** | **0** | **45.45**
 :red_circle: | app/client/src/reducers/uiReducers/gitSyncReducer.ts | 14.63 **(-1.59)** | 100 **(0)** | 0 **(0)** | 14.63 **(-1.59)**
 :red_circle: | app/client/src/sagas/GitSyncSagas.ts | 11.43 **(-0.69)** | 1.43 **(-0.04)** | 6.67 **(-0.47)** | 15.15 **(-0.85)**
 :red_circle: | app/client/src/selectors/gitSyncSelectors.tsx | 67.95 **(-0.05)** | 50 **(0)** | 7.69 **(-0.31)** | 57.69 **(-0.31)**
 :x: | ~~app/client/src/pages/Editor/GeneratePage/components/styles.ts~~ | ~~66.67~~ | ~~100~~ | ~~0~~ | ~~66.67~~</details>

### CODE REVIEW

File: app/client/src/pages/Editor/gitSync/components/Statusbar.tsx [hunk 1]
```diff
@@ -0,0 +1,111 @@
+import React, { useEffect, useState } from "react";
```
Comment (Rishabh-Rathod) [inline app/client/src/pages/Editor/gitSync/components/Statusbar.tsx:1]: As the Status Bar component will be consumed in other features also, maybe we could move it to `ads/components`?

File: app/client/src/pages/Editor/gitSync/GitSyncModal.tsx [hunk 2]
```diff
@@ -33,10 +33,12 @@ const Container = styled.div`
...
 const BodyContainer = styled.div`
   flex: 3;
-  height: 100%;
+  height: calc(100% - 47px);
 `;
 
-const MenuContainer = styled.div``;
+const MenuContainer = styled.div`
+  height: 47px;
+`;
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/GitSyncModal.tsx:41]: nitpick: It might make if more readable if we assign a variable to offset values:
```suggestion
const MENU_HEIGHT = "47px";
const MenuContainer = styled.div`
  height: ${MENU_HEIGHT};
`;
```

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx [hunk 3]
```diff
@@ -188,6 +222,7 @@ function GitConnection({ isImport }: Props) {
     useSelector(getCurrentAppGitMetaData) || ({} as any);
 
   const [remoteUrl, setRemoteUrl] = useState(remoteUrlInStore);
+  const [processingGit, setProcessingGit] = useState(false);
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:225]: Should we re-use `isConnectingToGit` here instead?

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx [hunk 4]
```diff
@@ -415,8 +451,19 @@ function GitConnection({ isImport }: Props) {
...
+      scrollWrapperRef.current?.scrollTo({ top: top, behavior: "smooth" });
+    }
+  }, [failedConnectingToGit]);
+
   return (
-    <Container>
+    <Container ref={scrollWrapperRef}>
       <Section>
         <Title>{createMessage(CONNECT_TO_GIT)}</Title>
         <Subtitle>{createMessage(CONNECT_TO_GIT_SUBTITLE)}</Subtitle>
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:469]: Nitpick: The title and subtitle here shouldn't scroll and should stick on top, when we scroll to show the error

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx [hunk 5]
```diff
@@ -527,23 +574,65 @@ function GitConnection({ isImport }: Props) {
...
+                    color={Colors.CHARCOAL}
+                    type={TextType.P3}
+                    weight={FontWeight.BOLD}
+                  >
+                    {createMessage(READ_DOCUMENTATION)}
+                    <AdsIcon name="right-arrow" size={IconSize.SMALL} />
+                  </Text>
+                </LintText>
+              </ErrorWrapper>
+            )}
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:631]: This would be based on the API response, since there could be multiple errors, for example:
- Key not found
- Key doesn't have right access
- Repo not found or invalid repo
we could modify the component a bit so later we could just replace the params from the api response

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx [hunk 6]
```diff
@@ -527,23 +574,65 @@ function GitConnection({ isImport }: Props) {
...
+                onClick={onSubmit}
+                size={Size.large}
+                tag="button"
+                text={
+                  isGitConnected
+                    ? createMessage(UPDATE_CONFIG)
+                    : createMessage(CONNECT_BTN_LABEL)
+                }
+              />
+            )}
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:604]: nitpick: on error, the button appears after a slight delay after the error is displayed

**Review by rishabhsaxena — COMMENTED** [review]
LGTM, few nitpicks:

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx (hunk 3 above)
Comment (haojin111) [reply app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:225]: No, we can't use isConnectingToGit for it.
Because when fetching a git config, isConnectingTogit is alwo true.
but progress bar is only for connecting to git by clicking "Connect" button

File: app/client/src/reducers/uiReducers/gitSyncReducer.ts [hunk 7]
```diff
@@ -233,6 +233,12 @@ const gitSyncReducer = createReducer(initialState, {
     ...state,
     isDisconnectingGit: false,
   }),
+  [ReduxActionErrorTypes.CONNECT_TO_GIT_ERROR]: (
+    state: GitSyncReducerState,
+  ) => ({
+    ...state,
+    isConnectingToGit: false,
+  }),
```
Comment (rishabhsaxena) [inline app/client/src/reducers/uiReducers/gitSyncReducer.ts:241]: nitpick: Just confirming if we're using this store variable?

File: app/client/src/pages/Editor/gitSync/hooks.ts [hunk 8]
```diff
@@ -82,15 +82,21 @@ export const useGitConnect = () => {
...
     setIsConnectingToGit(false);
   }, [setIsConnectingToGit]);
 
-  const onGitConnectFailure = useCallback(() => {
-    setIsConnectingToGit(false);
-    setFailedConnectingToGit(true);
-  }, [setIsConnectingToGit]);
+  const onGitConnectFailure = useCallback(
+    (error: any) => {
+      setGitError({ message: error.message });
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/hooks.ts:94]: nit: we could check if connection to git failed using the `gitError` variable itself and remove `failedConnectingToGit`, on success we could set it to null?

**Review by rishabhsaxena — APPROVED** [review]
Couple nitpicks, LGTM!

**Review by rishabhsaxena — APPROVED** [review]
Just one minor issue, the title scrolls a bit, when the error is visible

**Review by rishabhsaxena — APPROVED** [review]
