### PR TITLE
fix theme breaking with a slash in url

### LINKED ISSUE #1386: [Bug] Opening applications/ breaks the theme
## Description

Opening the home page with the trailing slash `/applications/` breaks the theme and displays the page weirdly

### Steps to reproduce the behaviour:

1. Go to https://app.appsmith.com/applications/

Screenshot 2020-10-24 at 11 48 59 AM

### Important Details
 - Version: Cloud / Self-Hosted v1.2.10
 - OS: MacOSX
 - Browser: Firefox

### PR DESCRIPTION
**Pull request by ThakurKarthik**
## Description
Fixes the issue of theme not properly loading in /applications/ route

Fixes #1386

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A tested with loading `/applications`, `/applications/`, `/settings`, `/settings/` routes theme was loading properly

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Hey @trishaanand @mohanarpit can you review the code for the fix?

### CODE REVIEW

File: app/client/src/AppRouter.tsx [hunk 1]
```diff
@@ -42,8 +42,8 @@ const loadingIndicator = <PageLoadingBar />;
 
 function changeAppBackground(currentTheme: any) {
   if (
-    window.location.pathname === "/applications" ||
-    window.location.pathname.indexOf("/settings/") !== -1
+    window.location.pathname.indexOf("/applications") !== -1 ||
```
Comment (mohanarpit) [inline app/client/src/AppRouter.tsx:45]: I'm sorry, this change won't work because it breaks the experience when you open the editor for a given application; which is of the form: `/applications/<applicationId>/pages/<pageId>`. 

Would suggest you to trim any trailing slashes and then do the comparison. It'll ensure that we don't run into such issues in the future.

Comment (ThakurKarthik) [reply app/client/src/AppRouter.tsx]: hey @mohanarpit thanks for the suggestion,i have updated the code,can you review ?

**Review by mohanarpit — APPROVED** [review]

**Comment by mohanarpit** [comment]
@ThakurKarthik Thank you for this PR! This has been merged 🎉
