### PR TITLE
fix: set max-height for Dropdown component

### LINKED ISSUE #12572: [Bug]: Dropdown popover in the property pane needs a max height after which content scrolls
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Today all the dropdowns used in the property pane don't have a max height property. This hides data when the screen is a bit small and the user doesn't know that more data exists.

### Steps To Reproduce

1. Add a JSON form widget or a datepicker widget
2. Click on the JSON form -> Field type or datepicker -> date format
3. Observe the number of items visible without scroll in the popover
image

### Public Sample App

_No response_

### Version

Production

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

- Set a max height for dropdown inside the property pane so that content won't go outside the window
- Removed MultiSelectControl and started using DropdownControl with isMultiSelect prop instead
- Made the Dropdown component with isMultiSelect to be keyboard accessible

Fixes #12572

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/dropdown-height 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.49 **(-0.03)** | 38.01 **(0.02)** | 35.78 **(-0.08)** | 56.73 **(-0.02)**
 :green_circle: | app/client/src/components/ads/Dropdown.tsx | 90.1 **(5.25)** | 71.97 **(8.86)** | 81.48 **(7.51)** | 89.67 **(5.79)**
 :green_circle: | app/client/src/components/ads/index.ts | 100 **(0)** | 100 **(0)** | 11.32 **(0.21)** | 100 **(0)**
 :red_circle: | app/client/src/components/propertyControls/DropDownControl.tsx | 51.67 **(-38.33)** | 41.46 **(-25.21)** | 50 **(-21.43)** | 49.09 **(-39.8)**
 :green_circle: | app/client/src/components/propertyControls/StyledControls.tsx | 67.14 **(0.02)** | 75 **(-0.76)** | 45.24 **(1.05)** | 67.14 **(0.02)**
 :red_circle: | app/client/src/components/propertyControls/index.ts | 86.84 **(-0.34)** | 100 **(0)** | 0 **(0)** | 86.49 **(-0.35)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :x: | ~~app/client/src/components/ads/MultiselectDropdown.tsx~~ | ~~83.87~~ | ~~70.83~~ | ~~85.37~~ | ~~82.14~~
 :x: | ~~app/client/src/components/propertyControls/MultiSelectControl.tsx~~ | ~~47.83~~ | ~~0~~ | ~~33.33~~ | ~~52.63~~</details>

### CODE REVIEW

File: app/client/src/components/ads/Dropdown.tsx [hunk 1]
```diff
@@ -277,39 +272,47 @@ export const DropdownWrapper = styled.div<{
...
+      border: 1.2px solid ${Colors.GRAY_200};
+
+      &:hover {
+        background: ${Colors.GRAY_50};
+      }
 
       &:focus {
-        border: 1.2px solid ${Colors.GREEN_1};
-        box-shadow: 0px 0px 0px 2px ${Colors.GREEN_2};
+        border-color: ${Colors.GRAY_900}!important;
```
Comment (riodeuno) [inline app/client/src/components/ads/Dropdown.tsx:298]: We can increase specificity by using multiple `&`. This should help us remove the need for `!important`
```suggestion
       &&&:focus { 
             border-color: ${Colors.GRAY_900}`,
```

File: app/client/src/components/ads/Dropdown.tsx [hunk 2]
```diff
@@ -24,6 +24,7 @@ import { useTheme } from "styled-components";
 import { findIndex, isArray } from "lodash";
 
 export type DropdownOnSelect = (value?: string, dropdownOption?: any) => void;
+type SubTextPosition = "BOTTOM" | "LEFT";
```
Comment (riodeuno) [inline app/client/src/components/ads/Dropdown.tsx:27]: We can use an `enum` instead of string literals here.

File: app/client/src/components/ads/Dropdown.tsx [hunk 3]
```diff
@@ -436,14 +450,18 @@ const HeaderWrapper = styled.div`
   padding: 0px 7px 7px 7px;
 `;
 
-const SelectedDropDownHolder = styled.div`
+const SelectedDropDownHolder = styled.div<{ enableScroll?: boolean }>`
```
Comment (riodeuno) [inline app/client/src/components/ads/Dropdown.tsx:453]: `enableScroll` might cause a warning in the browser's console. This is a new attribute added to the `div` element. React might complain, please verify this.

File: app/client/src/components/ads/Dropdown.tsx [hunk 4]
```diff
@@ -436,14 +450,18 @@ const HeaderWrapper = styled.div`
...
   display: flex;
   align-items: center;
   min-width: 0;
   max-width: 100%;
-  overflow: hidden;
+  overflow: ${(props) => (props.enableScroll ? "auto" : "hidden")};
   width: 100%;
 
+  &::-webkit-scrollbar {
```
Comment (riodeuno) [inline app/client/src/components/ads/Dropdown.tsx:461]: Are we removing scrollbars in the dropdown? 
I was wondering if this has been reviewed by someone from the design team? I am concerned because this effects all dropdowns in Appsmith's platform UI.

File: app/client/src/components/ads/Dropdown.tsx [hunk 5]
```diff
@@ -821,7 +850,11 @@ export default function Dropdown(props: DropdownProps) {
         // Multi select -> typeof selected is array of objects
         if (isArray(selected) && selected.length < 1) {
           setSelected([option]);
-        } else {
+        } else if (
+          !(selected as DropdownOption[])
```
Comment (riodeuno) [inline app/client/src/components/ads/Dropdown.tsx:854]: Would `findIndex` make for a more performant mechanism?

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/src/components/ads/Dropdown.tsx (hunk 1 above)
Comment (aswathkk) [reply app/client/src/components/ads/Dropdown.tsx:298]: It doesn't work. That's why I added `!important`

File: app/client/src/components/ads/Dropdown.tsx (hunk 4 above)
Comment (aswathkk) [reply app/client/src/components/ads/Dropdown.tsx:461]: This is not to remove scrollbar in dropdown. This is to remove scrollbar in multi select value display.

https://user-images.githubusercontent.com/10436935/165256665-afa66c01-90c4-421a-892b-88714d685aae.mov

Comment (aswathkk) [reply app/client/src/components/ads/Dropdown.tsx:461]: I will get this reviewed by @vasanth-appsmith

File: app/client/src/components/ads/Dropdown.tsx (hunk 3 above)
Comment (aswathkk) [reply app/client/src/components/ads/Dropdown.tsx:453]: I checked this. React is not complaining about this.

**Comment by vivekverma2312** [comment]
@aswathkk 
1. The drop down option do not scroll using keyboard
https://www.loom.com/share/16817daa61a44e3d904a0e71b2d7a6f2

2. Are we not setting max height for these drop-downs?
Screenshot 2022-04-26 at 2 02 07 PM

3. On table widget Primary key property also do not have max height
Screenshot 2022-04-26 at 2 16 26 PM

**Comment by aswathkk** [comment]
@vivekverma2312 
1. Great finding. I will try to implement it.
2. That's not a dropdown. That's technically an Action Selector. Designs are not available for this. I will discuss with @vasanth-appsmith and pick up that in a separate PR
3. I will fix this too.

**Comment by aswathkk** [comment]
Thanks, @rahulramesha. That was a regression that came as a part of merging the code. Fixed it.

@vivekverma2312, as Rahul pointed out, this Dropdown is being used in other parts of Appsmith as well. I've taken a look at those and found no issues. You can also take a look at those.
The other places where we use the same Dropdown component are Dropdown inside JSObjects, Query Editor, Data Source pages, Generate pages, Debugger Filter, Git connect, Currency and Phone input widget.

**Comment by vivekverma2312** [comment]
@aswathkk Can you check the keyboard scroll is not looking smooth.
https://www.loom.com/share/926756a3b726400199594fe9d8480a2b

**Comment by vivekverma2312** [comment]
@aswathkk On JS Object screen dropdown
Screenshot 2022-05-03 at 1 53 18 PM

**Comment by vivekverma2312** [comment]
@aswathkk Drop-down on git
Screenshot 2022-05-03 at 2 00 33 PM

**Comment by aswathkk** [comment]
@vivekverma2312 For dropdown in Git and JSObject, if you are talking about the height, then that is not under the scope of this issue. You can create a separate issue for that and assign it to the respective team.

**Comment by aswathkk** [comment]
> @aswathkk Can you check the keyboard scroll is not looking smooth.

This is fixed. @vivekverma2312 Can you check?

**Comment by vivekverma2312** [comment]
@aswathkk Tested and working fine.

**Review by riodeuno — APPROVED** [review]

**Review by rahulramesha — APPROVED** [review]
