### PR TITLE
fix: Auth datasource new api button not working fixed

### LINKED ISSUE #32064: [Bug]: New API button doesn't work from REST API datasource review page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is only on https://release-ee.appsmith.com/

The `+ New API` doesn't respond

https://github.com/appsmithorg/appsmith/assets/94514895/72275de9-0af2-4622-aab8-5860159e912f

### Steps To Reproduce

1. create a new REST API datasource - enter any URL and click save
2. Add config details for any one of the environments
3. Try switching to a different environment.
4. Go to the created datasource
5. click button `+ New API` and see that nothing happens

### Public Sample App

_No response_

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by sneha122**
## Description
This PR fixes the issue:
New API button does not work from REST API datasource from review page. This issue is only observed in enterprise version as it has connections to multiple environments:

https://github.com/appsmithorg/appsmith/assets/30018882/1f1f3a75-fa4c-4f0a-a463-541299ad8f15

Fixes #32064 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!IMPORTANT]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8449817023>
> Commit: `70549d166af84a9484439ce966a5e26a1e71f909`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8449817023&attempt=1" target="_blank">Click here!</a>
> All cypress tests have passed 🎉🎉🎉

## Summary by CodeRabbit

- **New Features**
	- Enhanced error detection by introducing a validation mechanism for API plugin URLs during query action creation in the Editor, based on environment, plugin type, and datasource configuration.
- **Tests**
	- Added tests to validate the new API plugin URL validation functionality in the Editor.

### CODE REVIEW

File: app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx [hunk 1]
```diff
@@ -36,6 +36,22 @@ interface NewActionButtonProps {
...
+) => {
+  return (
+    pluginType === PluginType.API &&
+    (!datasource ||
+      !datasource.datasourceStorages[currentEnvironment]
+        ?.datasourceConfiguration ||
+      !datasource.datasourceStorages[currentEnvironment]
+        ?.datasourceConfiguration?.url)
+  );
+};
```
Comment (rishabhrathod01) [inline app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx:53]: Code we make this code more readable?

```suggestion
   if(pluginType !== PluginType.API) return false; 
   if(!datasource) return false 
   return !datasource?.datasourceStorages[currentEnvironment]
        ?.datasourceConfiguration?.url
  
};
```

File: app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx [hunk 2]
```diff
@@ -59,14 +75,7 @@ function NewActionButton(props: NewActionButtonProps) {
...
     (pageId: string) => {
-      if (
-        pluginType === PluginType.API &&
-        (!datasource ||
-          !datasource.datasourceStorages[currentEnvironment]
-            .datasourceConfiguration ||
-          !datasource.datasourceStorages[currentEnvironment]
-            .datasourceConfiguration.url)
-      ) {
+      if (isApiPluginInvalidUrl(currentEnvironment, pluginType, datasource)) {
```
Comment (rishabhrathod01) [inline app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx:78]: As we check for presence of URL here, could we name the method accordingly? 
```suggestion
      if (apiPluginHasUrl(currentEnvironment, pluginType, datasource)) {
```

Comment (rishabhrathod01) [inline app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx:78]: I do not notice any logic change here, am I missing something? 
I noticed that we moved the logic to a method but the logic remains the same. Could you help me understand, how the change fixes the issue?

Comment (sneha122) [reply app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx:78]: I have added ?. which will add an extra check and we wont get any console errors ```
datasource.datasourceStorages[currentEnvironment]
        ?.datasourceConfiguration
```

**Review by rishabhrathod01 — APPROVED** [review]
looks good to me.
