### PR TITLE
fix: Current branch delete exception in delete branch API

### LINKED ISSUE #12674: [Bug]: Fix NPE for delete branch API when user tries to delete the checked out branch
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The server should throw the relevant error message in case of an unsuccessful transaction.

### Steps To Reproduce

1. Connect application to git
2. Create a new branch
3. Try to delete the current checked out branch
4. Internal server error is thrown

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> When the user tried to delete the current checked out branch, we should throw the relevant error message and handle it properly without affecting the other resources and state.

Fixes #12674 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 1]
```diff
@@ -2070,6 +2071,13 @@ private String getReason() {
                         return Mono.error(new AppsmithException(AppsmithError.GIT_ACTION_FAILED, " delete branch", "Cannot delete default branch"));
                     }
                     return gitExecutor.deleteBranch(repoPath, branchName)
+                            .onErrorResume(throwable -> {
+                                log.error(" Delete branch failed ", throwable.getMessage());
+                                if(throwable instanceof CannotDeleteCurrentBranchException) {
+                                    return Mono.error(new AppsmithException(AppsmithError.GIT_ACTION_FAILED, " delete branch", throwable.getMessage()));
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2077]: We don't need the space prefix "` `delete branch" as this has been already handled in AppsmithError

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 2]
```diff
@@ -2070,6 +2071,13 @@ private String getReason() {
...
+                                }
+                                return Mono.error(new AppsmithException(AppsmithError.GIT_ACTION_FAILED, " delete branch"));
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2079]: Can we please use second parameter to throw the error given by JGIT here?
```
return Mono.error(new AppsmithException(AppsmithError.GIT_ACTION_FAILED, "delete branch", throwable.getMessage()));
```

**Review by abhvsn — CHANGES_REQUESTED** [review]
Let's put up a constraint that user can't delete the branch where she has checked out in UI

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 2 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2079]: If the exception is not because of current branch delete exception, we do not want to show it to user. Hence i am not sending the exception message here.

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2079]: Any specific reason for this?

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2079]: IIUC, we are following this across all the git errors.

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java]: Nope we are sending the user friendly error message if we are already aware of the root cause just like you are checking the `CannotDeleteCurrentBranchException` in the above implementation, if not we are throwing the error from JGit as is

**Review by abhvsn — APPROVED** [review]
Please make sure client side code handles the scenario where delete icon will not be shown for the current checked out branch on UI
