### PR TITLE
fix: cypress test added for onboarding start with data

### LINKED ISSUE #30554: [Task]: Write automated cypress test cases for onboarding revamp experiment (rolled out to 100% users)
### SubTasks

This task is to write automated cypress test cases for onboarding revamp experiment

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR adds cypress test for issue https://github.com/appsmithorg/appsmith/issues/30620

#### PR fixes following issue(s)
Fixes #30554 
#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Tests**
	- Added automated tests for the "Start with data" user flow in the onboarding process.
- **New Features**
	- Enhanced the UI interaction in the Data Sources page by introducing an index-based element selection feature.

### CODE REVIEW

File: app/client/cypress/support/Pages/DataSources.ts [hunk 1]
```diff
@@ -430,9 +430,14 @@ export class DataSources {
     }).as("testDatasource");
   }
 
-  public CreatePlugIn(pluginName: string, waitForToastDisappear = false) {
+  public CreatePlugIn(
+    pluginName: string,
+    waitForToastDisappear = false,
+    index = 0,
```
Comment (AmanAgarwal041) [inline app/client/cypress/support/Pages/DataSources.ts:436]: Any reason, why this change was made ?

Comment (sneha122) [reply app/client/cypress/support/Pages/DataSources.ts:436]: So in the new changes that we have made for the onboarding flag, we have also added most popular section with postgres in it. Now when we create postgres db it finds two elements having text "Postgres", so I am always picking up first index.

**Review by AmanAgarwal041 — APPROVED** [review]
