### PR TITLE
chore: fix js object flaky tests

### LINKED ISSUE #20023: [Task]: Fix JSFunctionExecution flaky test
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
The test fails due to running a function that is no longer present.

https://cloud.cypress.io/projects/eyxvp8/runs/28353/test-results/904ce875-9704-4f76-9fb2-88f09fd14e3e/video

_No response_

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

- Introduces a new way of filling JS content in cypress tests
- Adds tests to handle invalid export of JS Objects
- Removes redundant "toast wait" function
- Refactors selection of JSAction from state

Fixes #20023 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/selectors/entitiesSelector.ts [hunk 1]
```diff
@@ -417,21 +416,6 @@ export const getJSCollection = (
   return jsaction ? jsaction.config : undefined;
 };
 
-export const getJSFunctionFromName = (state: AppState, name: string) => {
```
Comment (ohansFavour) [inline app/client/src/selectors/entitiesSelector.ts:420]: @Rishabh-Rathod this selector has been removed because it could introduce potential bugs. Since JSObject names/ js function names are not unique across pages, selecting by name poses a problem.

**Review by Rishabh-Rathod — DISMISSED** [review]
LGTM

File: app/client/cypress/support/Pages/JSEditor.ts [hunk 2]
```diff
@@ -103,6 +101,19 @@ export class JSEditor {
   private selectAllJSObjectContentShortcut = `${
     this.isMac ? "{cmd}{a}" : "{ctrl}{a}"
   }`;
+
+  private handleJSContentFilling(toPaste: boolean, JSCode: string, el: any) {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/JSEditor.ts:105]: nit: Method names are PascalCase :) Otherwise Cypress changes looks good!

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress updates looks good.

**Comment by ohansFavour** [comment]
@Aishwarya-U-R can you please approve the request and add the test plan label?

**Comment by Aishwarya-U-R** [comment]
@ohansFavour - I see you have made some src file changes. Do this PR hence requires a functional test or we are good?

**Comment by ohansFavour** [comment]
> @ohansFavour - I see you have made some src file changes. Do this PR hence requires a functional test or we are good?

It is a refactor. There is already a test for the implementation

**Review by Aishwarya-U-R — APPROVED** [review]
