### PR TITLE
fix: Auto-generated header Refactor

### LINKED ISSUE #18473: [Bug]: REST API content type is auto setting and removing user set content type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1669537528438219 

### Steps To Reproduce

Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1669537528438219

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

cloud, self hosted

### PR DESCRIPTION
**Pull request by Irongade**
API content type refactor flow. More information can be found [here](https://www.notion.so/appsmith/API-Content-type-Header-Refactor-07f2f944e13f43148210c2461cf3fcda?d=339958cf1d374fefadfa437f86d95627)

Fixes #18473

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx [hunk 1]
```diff
@@ -353,40 +361,54 @@ const Flex = styled.div<{ size: number }>`
...
   width: calc(100% - 30px);
 
-  &.header {
-    margin-bottom: 8px;
-  }
-
   .key-value {
     .${Classes.TEXT} {
-      color: ${(props) => props.theme.colors.apiPane.text};
+      color: #4b4848;
```
Comment (sneha122) [inline app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx:380]: is it possible to change the color in the theme object itself? instead of hardcoding here?

**Review by sneha122 — APPROVED** [review]

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java [hunk 2]
```diff
@@ -61,9 +63,24 @@ public String getRequestContentType(ActionConfiguration actionConfiguration,
             reqContentType = getRequestContentTypeFromHeaders(actionConfiguration.getHeaders());
         }
 
+        if(reqContentType.isEmpty() && actionConfiguration.getAutoGeneratedHeaders() != null){
```
Comment (sumitsum) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java:66]: Can you please change `reqContenType.isEmpty()` to `StringUtils.isEmpty(reqContentType)` just in case `reqContentType` could become null ? Also, please import the static function `StringUtils.isEmpty` so that it can be written as `isEmpty(reqContentType)`.

Comment (sumitsum) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java:66]: Could we instead use the `getRequestContentType(ActionConfig ...)` defined below ?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java [hunk 3]
```diff
@@ -130,4 +147,17 @@ public String getSignatureKey(DatasourceConfiguration datasourceConfiguration) t
...
 
+    public void setContentTypeHeader(ActionConfiguration actionConfiguration){
+        if(actionConfiguration.getAutoGeneratedHeaders() == null){
+            return;
+        }
+        if(actionConfiguration.getHeaders() == null){
+            actionConfiguration.setHeaders(Arrays.asList(new Property(HttpHeaders.CONTENT_TYPE,
+                    getRequestContentTypeFromHeaders(actionConfiguration.getAutoGeneratedHeaders()))));
+        } else if(!actionConfiguration.getHeaders().stream().filter(s -> s.getKey().
+                equals(HttpHeaders.CONTENT_TYPE)).toList().isEmpty()){
```
Comment (sumitsum) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java:158]: Can you please re-write the `if` condition here to make it easier to read ? e.g. if (isContentTypeHeaderPresent(...)) {...} ? The if condition is a little difficult to read at the moment.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RequestCaptureFilter.java [hunk 4]
```diff
@@ -58,16 +59,29 @@ public ActionExecutionRequest populateRequestFields(ActionExecutionRequest exist
         actionExecutionRequest.setHttpMethod(request.method());
         MultiValueMap<String, String> headers = CollectionUtils.toMultiValueMap(new LinkedCaseInsensitiveMap<>(8, Locale.ENGLISH));
         AtomicBoolean isMultipart = new AtomicBoolean(false);
+        AtomicBoolean isMultipartUserDefined = new AtomicBoolean(false);
```
Comment (sumitsum) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RequestCaptureFilter.java:62]: Nit: can we rename this to `isMultipartContentTypeDefinedByUser` ?

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 5]
```diff
@@ -30,11 +31,7 @@
 import java.net.URISyntaxException;
 import java.net.URLDecoder;
 import java.nio.charset.StandardCharsets;
-import java.util.ArrayList;
-import java.util.HashSet;
-import java.util.List;
-import java.util.Map;
-import java.util.Set;
+import java.util.*;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:34]: Nit: please replace wild imports with specific imports i.e. please replace `import xyz.*` with `import xyz.foo`.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java (hunk 3 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java:158]: done

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RequestCaptureFilter.java (hunk 4 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RequestCaptureFilter.java:62]: done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 5 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:34]: done

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java (hunk 2 above)
Comment (PiyushPushkar02) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java:66]: I have removed this as it's not required since we are already setting the value of headers from the auto-generated header. There is no point in checking it again here.

File: app/client/cypress/support/Pages/ApiPage.ts [hunk 6]
```diff
@@ -256,6 +263,76 @@ export class ApiPage {
...
+      this._importedValue(index, keyValueName),
+      header.value,
+    );
+  }
+
+  public ValidateImportedKeyValueContent(
+    selector: string,
+    contentToValidate: any,
+  ) {
+    cy.get(selector).should("have.text", contentToValidate);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/ApiPage.ts:291]: Lets call agHelper.GetNAssertElementText() here.

File: app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+    apiPage.SelectSubTab("FORM_URLENCODED");
+    apiPage.ValidateImportedHeaderParams(true, {
+      key: "content-type",
+      value: "application/x-www-form-urlencoded",
+    });
+    apiPage.EnterHeader("content-type", "application/json");
+    apiPage.ValidateImportedKeyValueOverride(0);
+    apiPage.EnterHeader("", "");
+    apiPage.ValidateImportedKeyValueOverride(0, false);
+    cy.get(apiPage._autoGeneratedHeaderInfoIcon("content-type")).should(
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts:18]: agHeleper.AssertElementVisible()

File: app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+      "be.visible",
+    );
+    cy.get(apiPage._autoGeneratedHeaderInfoIcon("content-type")).realHover({
+      pointer: "mouse",
+    });
+
+    cy.contains(
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts:25]: agHelper.GetNAssertContains() will suffice?

File: app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts [hunk 9]
```diff
@@ -0,0 +1,29 @@
+import { ObjectsRegistry } from "../../../../support/Objects/Registry";
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts:1]: Can use import from ObjectsCore.
`import * as _ from "../../../../support/Objects/ObjectsCore";`

Use it like :
`_.apiPage.CreateApi("FirstAPI");`

Comment (Irongade) [reply app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts:1]: This is usually not a best practice, as this significantly increases the import size of the file rather than just importing what we need.

File: app/client/cypress/support/Pages/ApiPage.ts (hunk 6 above)
Comment (Irongade) [reply app/client/cypress/support/Pages/ApiPage.ts]: Done

File: app/client/cypress/support/Pages/ApiPage.ts [hunk 10]
```diff
@@ -256,6 +263,76 @@ export class ApiPage {
...
+    this.ValidateImportedKeyValueAbsence(
+      this._importedKey(index, keyValueName),
+    );
+    this.ValidateImportedKeyValueAbsence(
+      this._importedValue(index, keyValueName),
+    );
+  }
+
+  public ValidateImportedKeyValueAbsence(selector: string) {
+    cy.get(selector).should("not.exist");
```
[the remark this answers is not in the document]
Comment (Irongade) [reply app/client/cypress/support/Pages/ApiPage.ts]: Done

File: app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts (hunk 7 above)
Comment (Irongade) [reply app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts]: Done

File: app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts (hunk 8 above)
Comment (Irongade) [reply app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Auto_Generated_Header_spec.ts]: Done

**Review by sumitsum — APPROVED** [review]

**Comment by sumitsum** [comment]
Backend changes LGTM.

**Review by sumitsum — APPROVED** [review]

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java (hunk 3 above)
Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java:160]: Hi @PiyushPushkar02 seems like this has not been fixed yet, can you please check ?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java [hunk 11]
```diff
@@ -130,4 +141,39 @@ public String getSignatureKey(DatasourceConfiguration datasourceConfiguration) t
...
+
+            String autoGeneratedContentTypeHeader = getRequestContentTypeFromHeaders(
+                    actionConfiguration.getAutoGeneratedHeaders());
+
+            actionConfiguration.getHeaders().add(new Property(HttpHeaders.CONTENT_TYPE
+                    ,autoGeneratedContentTypeHeader));
+        }
+    }
+
+    private boolean isHeaderPresent(List<Property> headers,String headerName){
```
Comment (sumitsum) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java:170]: QQ: Are we using it anywhere ?

**Review by Aishwarya-U-R — DISMISSED** [review]

**Review by sumitsum — APPROVED** [review]

**Comment by sumitsum** [comment]
Server side changes LGTM.

**Review by sneha122 — APPROVED** [review]
