### PR TITLE
fix: multiple storeValue action completion track

### LINKED ISSUE #14653: [Bug]: Consecutive storeValue calls don't work and only the first call is executed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Consecutive `storeValue()` does not work anymore - regressed issue. Only the first call goes through

### Steps To Reproduce

1. Use consecutive `storeValue()` bound either in a widget JS or in a `promise.all()` and observe that the code fails and saves only the first `storeValue()` call

https://release.app.appsmith.com/app/scratch-pad/iframe-629d9ca4b1677a11502ab3e2/edit

### Public Sample App

https://release.app.appsmith.com/app/scratch-pad/iframe-629d9ca4b1677a11502ab3e2/edit

### Version

Cloud

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
### Problem 

`yield take(ReduxActionTypes.UPDATE_APP_STORE_EVALUATED)` inside storeValueLocally saga can catch previous storeValue action and complete the latest call too.
This was not expected behaviour with promisified storeValue as we need to track completion of each storeValue action separately.

Fixes #14653

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual & Cypress

- [x] https://github.com/appsmithorg/TestSmith/issues/1893

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/sagas/ActionExecution/StoreActionSaga.ts [hunk 1]
```diff
@@ -34,10 +34,22 @@ export default function* storeValueLocally(
...
       text: `store('${action.key}', '${action.value}', false)`,
     });
   }
-  yield take(ReduxActionTypes.UPDATE_APP_STORE_EVALUATED);
+  /* It is possible that user calls multiple storeValue function together, in such case we need to track completion of each action separately
+  We use uniqueRequestId to differentiate each storeValueAction here.
+  */
+  while (true) {
+    const returnedAction: StoreValueActionDescription = yield take(
+      updateAppStoreEvaluated().type,
```
Comment (ohansFavour) [inline app/client/src/sagas/ActionExecution/StoreActionSaga.ts:47]: Can we use `ReduxActionTypes.UPDATE_APP_STORE_EVALUATED` instead of updateAppStoreEvaluated().type?.

Reasons: 

1. Most times during code inspection, we do a string search of the `redux action type` to see how it is used within the codebase.

2. For consistency across the codebase.

Comment (ohansFavour) [reply app/client/src/sagas/ActionExecution/StoreActionSaga.ts:47]: This looks good. Few more points

1. Can we add a cypress test too?

2. Can we also in this PR use the same pattern for other actions? e.g `resetWidget`

**Review by ohansFavour — COMMENTED** [review]
This looks good. Few more points

1. Can we add a cypress test too?

2. Can we also in this PR use the same pattern for other actions? e.g `resetWidget`

File: app/client/src/sagas/ActionExecution/StoreActionSaga.ts (hunk 1 above)
Comment (Rishabh-Rathod) [reply app/client/src/sagas/ActionExecution/StoreActionSaga.ts:47]: sure, i will revert this. 

Intention was to slowly adopt usage of action creators everywhere but i realise that for `take` it is not at all intuitive. 

Problem, i have seen with directly using `ReduxActionTypes.UPDATE_APP_STORE_EVALUATED` are mainly when we do `put` or `dispatch` directly without actionCreator and avoid the type check of payload. ( we had bugs in past due to this practice. )

Hopefully, we will come up with better solution for this in future.

**Comment by Rishabh-Rathod** [comment]
> 2\. Can we also in this PR use the same pattern for other actions? e.g `resetWidget`

I will also fix this for `resetWidget`. That was the only action i found which has similar implementation and issue but that will go in as separate PR so that we could ship `storeValue` fix ASAP. 

- `resetWidget` will again need more testing 
( there is a core change in resetWidget functionality in this PR https://github.com/appsmithorg/appsmith/pull/14468 )

According to new test plan of it, i would decide how to add resetWidget fix. ( merging the testing effort for reset )

Also, problem is less severe for `resetWidget`. hence, we could separately ship them.
@ohansFavour

File: app/client/src/sagas/ActionExecution/StoreActionSaga.ts (hunk 1 above)
Comment (Rishabh-Rathod) [reply app/client/src/sagas/ActionExecution/StoreActionSaga.ts]: done

**Review by ramsaptami — APPROVED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/StoreValue_spec.ts [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+      toRun: false,
+      shouldCreateNewJSObj: true,
+    });
+
+    agHelper.AssertAutoSave();
+
+    jsEditor.EditJSObj(jsObjectBody);
+
+    agHelper.AssertAutoSave();
+
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/StoreValue_spec.ts:42]: Firstly - please move this case into ClientSidetests/Binding/Promises - which already has promise related tests. (by appending right tc number)
And - CreateJSObj has AssertAuotSave - so this can be removed from line 37.
And why are we editing JSOBj here?

**Review by ramsaptami — APPROVED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/StoreValue_spec.ts (hunk 2 above)
Comment (Rishabh-Rathod) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/StoreValue_spec.ts:42]: > Firstly - please move this case into ClientSidetests/Binding/Promises - which already has promise related tests. (by appending right tc number)

@Aishwarya-U-R  we will need to test each action like `storeValue`, `resetWidget` separately.

This issue was related to storeValue particularly not handling promise well. ( not a general promise issue )

We will be add more test cases here in future specific to storeValue ( which maybe not be related to promise ) hence a separate file.

> And - CreateJSObj has AssertAuotSave - so this can be removed from line 37.
And why are we editing JSOBj here?

Editing JSObject is not required here, there is a bug in JSObject https://github.com/appsmithorg/appsmith/issues/14503 which i was trying to bypass. 

Current test code, is able to reliably bypass it. I will add modify this test case once we fix above issue.
