### PR TITLE
fix(mysqlPlugin): MySQL allow empty password if user is not empty

### LINKED ISSUE #9221: [Bug]: Database connection does not allow empty password
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I configure a MySQL database with an empty password, the form does not allow me to proceed with the "Test" button.

image

However, I can save and continue.

### Steps To Reproduce

1. Create Datasource
2. Fill database host, port, username
3. Click "Test"

### Environment

Production

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by mojtab23**
## Description

mysqlPlugin will ignore and validate the empty password if the user field is not empty.

Fixes #9221

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

-  With unit tests against the MySQL `root` user and also with another user.
-  Test file `MySqlWithEmptyPasswordTest` is added to `mysqlPlugin`
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java [hunk 1]
```diff
@@ -7,32 +7,13 @@
...
-import com.appsmith.external.models.DBAuth;
-import com.appsmith.external.models.DatasourceConfiguration;
-import com.appsmith.external.models.DatasourceStructure;
-import com.appsmith.external.models.DatasourceTestResult;
-import com.appsmith.external.models.Endpoint;
-import com.appsmith.external.models.Property;
-import com.appsmith.external.models.PsParameterDTO;
-import com.appsmith.external.models.RequestParamDTO;
-import com.appsmith.external.models.SSLDetails;
+import com.appsmith.external.models.*;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java:10]: Hi Mojtaba, please replace the `*` import everywhere with specific imports since we don't want to import the libraries that we are not using.

File: app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java [hunk 2]
```diff
@@ -636,8 +605,11 @@ public void datasourceDestroy(Connection connection) {
                     invalids.add("Missing username for authentication.");
                 }
 
-                if (StringUtils.isEmpty(authentication.getPassword())) {
+                if (StringUtils.isEmpty(authentication.getPassword()) && StringUtils.isEmpty(authentication.getUsername())) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java:608]: Can we replace the `if else` by :
```
if (StringUtils.isEmpty(authentication.getPassword())) { 
    authentication.setPassword("");
}
```
Since we are already adding an error statement in case of missing `username` we only have to handle the case when the username is provided.

File: app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlWithEmptyPasswordTest.java [hunk 3]
```diff
@@ -0,0 +1,194 @@
+package com.external.plugins;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlWithEmptyPasswordTest.java:1]: Can you please move the tests to `MySqlPluginTest.java` ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlWithEmptyPasswordTest.java (hunk 3 above)
Comment (mojtab23) [reply app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlWithEmptyPasswordTest.java]: Sure, I did that.

File: app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java (hunk 1 above)
Comment (mojtab23) [reply app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java]: I fixed the imports.

**Review by sumitsum — APPROVED** [review]
