### PR TITLE
fix: cyclic dependency in renaming js objects

### LINKED ISSUE #13283: [Bug]-[92]:Cyclic dependency error thrown when renaming JS functions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cyclic dependency error is displayed when JS function is being renamed and clears when page is refreshed

### Steps To Reproduce

1. Take any existing app with JS objects or go to app at [this link ](https://release.app.appsmith.com/app/git-connected-app-with-js-objects/page1-62668caa01f360366e25e4d2/edit/jsObjects/62668cc801f360366e25e4d9)
2. Try to rename any function - observe the cyclic dependency error as seen in the video

[LOOM DEMO](https://www.loom.com/share/19137f50abf6485aaa7e0919b7ad0fc7)

### Public Sample App

https://release.app.appsmith.com/app/git-connected-app-with-js-objects/page1-62668caa01f360366e25e4d2/edit/jsObjects/62668cc801f360366e25e4d9

### Version

Cloud

### LINKED ISSUE #13755: [Bug]: cyclic dependency error is displayed in the view mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Getting cyclic dependency error in one of my app
Facing the issue only in the view mode not in the edit mode
image

facing it in this app->made this app public
https://release.app.appsmith.com/applications/626a7f2e7e182b2589133461/pages/626a7f327e182b258913346e?branch=master

### Steps To Reproduce

1. go to git-template-3-foodtruck app
2. Launch the app 
3. Now go to the dish tab
4. the cyclic dependency error will be displayed

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by ohansFavour**
### Cause of issue

A mismatch between JS Object in `currentJSCollectionState` and that of the `unevalDataTree`

`myFunc.data` was not listed as a part of the differences array.
Hence it never got removed from the `dependencyMap` even though the function was renamed.

Screenshot 2022-05-17 at 15 23 27

---

### Approach

Added logic in `EvaluationUtils.ts` to identify when `myFunc.data` is removed and to list in the differences array.
So, it will be removed from the `dependencyMap` properly.

---

Fixes #13283 
Fixes #13755 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Test Plan**
- [x] https://github.com/appsmithorg/TestSmith/issues/1735
- [ ] https://github.com/appsmithorg/TestSmith/issues/1736

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/cyclic-dependency-in-renaming-js-objects 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.71 **(0)** | 38.66 **(-0.01)** | 36.23 **(0)** | 56.96 **(0)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**
 :red_circle: | app/client/src/workers/DataTreeEvaluator/DataTreeEvaluator.ts | 80.42 **(-0.37)** | 59.56 **(-0.38)** | 78.65 **(0)** | 80.26 **(-0.4)**</details>

### CODE REVIEW

File: app/client/cypress/support/Pages/JSEditor.ts [hunk 1]
```diff
@@ -171,15 +172,15 @@ export class JSEditor {
...
-    this.agHelper.AssertAutoSave(); //Ample wait due to open bug # 10284
+  //Edit the name of a JSObject's property (variable or function)
+  public EditJSObj(newContent: string) {
+    cy.get(this.locator._codeMirrorTextArea)
+      .first()
+      .focus()
+      .type(this.selectAllJSObjectContentShortcut, { force: true })
+      .then((el: any) => {
+        this.agHelper.Paste(el, newContent);
+      });
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/JSEditor.ts:183]: I see you are doing a complete replace... does this account for renaming function?

Comment (ohansFavour) [reply app/client/cypress/support/Pages/JSEditor.ts:183]: @Aishwarya-U-R Yes. Say for example we had
```
export default {
myVar : []
}
```
and we completely replace it with new content (without first clearing out the content of the JS Object) 

 ```
export default {
myVar2 : []
}
```

The editor sees this as a change in the variable name.

NB: We don't clear out the content of the Editor (no backspace after highlighting all).

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts [hunk 2]
```diff
@@ -166,4 +166,67 @@ describe("JS Function Execution", function() {
       expect($cellData).to.eq("1"); //validating id column value - row 0
     });
   });
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:168]: I see the case is failing in CI - coz this testcase has navigated to Deploy page, so navigate back to Editor via `agHelper.NavigateBacktoEditor();
` in this case itself & run CI again! Otherwise cyclic dependency test looks good to me!

**Review by Aishwarya-U-R — APPROVED** [review]

**Review by Aishwarya-U-R — DISMISSED** [review]

File: app/client/src/workers/DataTreeEvaluator/DataTreeEvaluator.ts [hunk 3]
```diff
@@ -193,14 +192,18 @@ export default class DataTreeEvaluator {
...
+      if (!!entity) {
         Object.keys(updates).forEach((key) => {
-          const data = _.get(dataTree, `${update}.${key}.data`, undefined);
-          if (this.isJSObjectFunction(dataTree, update, key)) {
-            _.set(dataTree, `${update}.${key}`, new String(updates[key]));
-            _.set(dataTree, `${update}.${key}.data`, data);
-          } else {
-            _.set(dataTree, `${update}.${key}`, updates[key]);
+          const updatePath = `${update}.${key}`;
+          if (_.has(dataTree, updatePath)) {
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/DataTreeEvaluator/DataTreeEvaluator.ts:199]: Can you please add a comment here explaining why we should have the above check?
```
if (_.has(dataTree, updatePath)) 
```

**Review by Rishabh-Rathod — APPROVED** [review]
Looks good to me.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts [hunk 4]
```diff
@@ -164,6 +164,80 @@ describe("JS Function Execution", function() {
...
+      completeReplace: true,
+      toRun: false,
+      shouldCreateNewJSObj: true,
+    });
+
+    // change sync function name and test that cyclic dependency is not created
+    jsEditor.EditJSObj(syncJSCodeWithRenamedFunction1);
+    cy.contains(locator._toastMsg, cyclicDependencyToastMessage).should(
+      "not.exist",
+    );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:221]: Hey @ohansFavour - instead of these lines.. can you try replacing with below combination?
```
    agHelper.WaitUntilToastDisappear('created successfully');
    agHelper.AssertElementAbsence(locator._toastMsg);
```

File: app/client/src/workers/evaluationUtils.ts [hunk 5]
```diff
@@ -156,7 +156,32 @@ export const translateDiffEventToDataTreeDiffEvent = (
           typeof difference.lhs === "string" && isDynamicValue(difference.lhs);
       }
 
-      if (rhsChange || lhsChange) {
+      // JsObject function renaming
+      // remove .data from a String instance manually
+      // since it won't be identified when calculating diffs
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/evaluationUtils.ts:161]: Can you please elaborate here on what won't be identified when calculating diffs?

**Review by Aishwarya-U-R — APPROVED** [review]
Cypress test LGTM!

File: app/client/src/workers/evaluationUtils.ts (hunk 5 above)
Comment (ohansFavour) [reply app/client/src/workers/evaluationUtils.ts:161]: > Can you please elaborate here on what won't be identified when calculating diffs?


When updating the localUnEvalTree, 

Screenshot 2022-06-06 at 09 45 30

We set a `.data` property to the String class, this is not identified when we calculate diffs.

**Review by Rishabh-Rathod — APPROVED** [review]
Changes. Looks good to me.

Let's create an issue to understand why we have `updateLocalUnEvalTree` and the possibility to remove it.
