### PR TITLE
fix: Table and JSON Widgets columns max height adjusted

### LINKED ISSUE #31833: [Task]: Reduce the number of columns to 4 shown by default
### SubTasks

https://www.notion.so/appsmith/Reduce-the-number-of-columns-to-4-shown-by-default-f597eb225517449c9419ba49df5d33f6
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by NilanshBansal**
image

Fixes #31833  

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!IMPORTANT]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8355362590>
> Commit: `576e01175a9427bbe8e2a463ad31881fc2875123`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8355362590&attempt=2" target="_blank">Click here!</a>
> All cypress tests have passed 🎉🎉🎉

## Summary by CodeRabbit

- **New Features**
	- Introduced a new property to enhance the layout consistency of draggable list controls.
- **Refactor**
	- Updated the layout configuration for improved user interface consistency in list controls.

### CODE REVIEW

File: app/client/src/components/propertyControls/FieldConfigurationControl.tsx [hunk 1]
```diff
@@ -264,6 +264,7 @@ class FieldConfigurationControl extends BaseControl<ControlProps, State> {
       <div className="flex flex-col w-full gap-1">
         <DraggableListControl
           deleteOption={this.onDeleteOption}
+          fixedHeight={197}
```
Comment (sneha122) [inline app/client/src/components/propertyControls/FieldConfigurationControl.tsx:267]: @NilanshBansal Can we please store this 197 value somewhere in a global constant? And use that constant everywhere? This way if we decided to expand this feature for all widgets tomorrow it will be easier and if we ever need to modify this column sizing, it will be easier to change in one place rather 10 places

**Comment by sneha122** [comment]
@NilanshBansal Tested the PR for table and json widgets with adding bindings manually, one click binding and generate crud, all looks except for following case with one click binding, the columns are getting scrolled to bottom:

https://github.com/appsmithorg/appsmith/assets/30018882/0ebe2945-82a9-426b-a108-b27944b0f4be

File: app/client/src/components/propertyControls/FieldConfigurationControl.tsx (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/src/components/propertyControls/FieldConfigurationControl.tsx:267]: And it will be better to write a logic to calculate the fixedHeight instead of hardcoding for better readability and understanding. eg. 3 * height of the element + space between two element etc.

**Comment by NilanshBansal** [comment]
> @NilanshBansal Tested the PR for table and json widgets with adding bindings manually, one click binding and generate crud, all looks good except for following case with one click binding, the columns are getting scrolled to bottom:
> 
>  Screen.Recording.2024-03-18.at.5.40.52.PM.mov

@sneha122 thanks for highlighting this! This same behavior of columns getting scrolled to bottom is also reproducible in production.
The scope of this PR is only to limit the height of the columns to 4. 
I am not sure whether this scrolling was intentional or a bug. Nonetheless, there can be a separate issue logged for the scrolling functionality. 


https://github.com/appsmithorg/appsmith/assets/25542733/f684ba87-49f5-40f8-8c53-53ff5df47103

**Comment by rishabhrathod01** [comment]
> except for following case with one click binding, the columns are getting scrolled to bottom:

The scroll behaviour of columns is expected, that is how user would see the rest of the columns of the table.

**Comment by sneha122** [comment]
Thanks @NilanshBansal @rishabhrathod01 Rest of the stuff looks good from testing standpoint!

**Review by sneha122 — APPROVED** [review]
