### PR TITLE
fix: handle editor value update

### LINKED ISSUE #11624: [Bug]-[600]:RichTextEditor not loading at start
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently i have a RichTextEditor.
The "default text" is filled by a database.
In widget edit mode (where you can place the appsmith widgets) it works fine.
Now I deploy the app and open it it does not work. The editor remains empty.
If I change the page in the same app via the navigation bar of Appsmith and change back again it works.
It can be a disaster if the editor is empty and when changing the data then the current data is completely deleted from the database (onChange).

### Steps To Reproduce

1. Place a RichTextEditor Widget
2. Use a database query (postgres) `{{RichTextData.data[0].data}}` (`SELECT data FROM RichTextData;`)
3. Deploy
4. Open the deployed app

### Environment

Release

### Version

Self-Hosted

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

RichTextEditor isn’t loading at the start to fix that issue `textChange` event prevents while initializations of RichTextEditor.

Fixes #11624 

## Type of change

- Bugfix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/issue-11624 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.46 **(0)** | 37.91 **(-0.01)** | 36.17 **(0)** | 56.68 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Comment by lublak** [comment]
@techbhavin there is something like this:

```js
editor.on('init', function (e) {
  editor.setContent(content);
});
```

**Review by SatishGandham — COMMENTED** [review]
Why is it not changing?
We pass the value prop, why is it not changing when the value prop changes?

**Comment by techbhavin** [comment]
As per my observation, in the initial render when props are changing, `editorRef.current` is not there, but when `editorRef.current` changes, `props.value` is stable and that will not effect on `useEffect`

image

**Review by SatishGandham — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@techbhavin tested this on Windows machine on Chrome browser. This issue is still partially reproducible. 
https://loom.com/share/cbacf59b9c204c00abab01cfbad0277f

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx [hunk 1]
```diff
@@ -77,33 +82,38 @@ export function RichtextEditorComponent(props: RichtextEditorComponentProps) {
...
     "insertfile undo redo | formatselect | bold italic backcolor forecolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | removeformat | table | print preview media | forecolor backcolor emoticons' | help";
 
   useEffect(() => {
-    if (!value && !props.value) return;
+    if (!value.text && !props.value) return;
     // This Prevents calling onTextChange when initialized
-    if (!isInit.current) return;
-    const timeOutId = setTimeout(() => props.onValueChange(value), 1000);
+    if (!value.isUserEdit) return;
+    const timeOutId = setTimeout(() => props.onValueChange(value.text), 1000);
```
Comment (SatishGandham) [inline app/client/src/widgets/RichTextEditorWidget/component/index.tsx:99]: Why are you waiting a second to trigger the update?

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx (hunk 1 above)
Comment (SatishGandham) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:99]: @Tooluloope 
Why did we add a one second debounce. Update meta property is already debounced.

Comment (techbhavin) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:99]: to prevent triggering onValueChange method when the user typing. it will call when the user takes a pause while typing

**Review by SatishGandham — APPROVED** [review]

**Comment by shwetha-ramesh** [comment]
@techbhavin re-tested this on Windows machine on Chrome browser. Working as expected now.
https://loom.com/share/ee17b306517b436888d307aaada35273

Moving to Done.

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx (hunk 1 above)
Comment (Rishabh-Rathod) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:99]: Why do we want to prevent calling `onValueChange` when the user is typing? 
I believe that will cause the local state to update unexpectedly as per current logic.

@techbhavin I would like to understand why we need the local state for the RTE component and how is it different from the input widget?

Comment (Tooluloope) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:99]: - If we leave it solely to the meta property to provide the value, once a new value is provided, the cursor would shift to the beginning, which is bad UX.
