### PR TITLE
fix: JS option missing for some style items in table widget v2

### LINKED ISSUE #2906: [Bug]-[160]:JS option missing for the following style items in table
Steps to reproduce:
1) Add a table 
2) Click on the property pane 
3) Scroll and observe

Table styles
    1. Font Style
    2. Text Align
    3. Vertical Alignment

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

The JS toggle option was missing in Text formatting section of table widget v2 for:

1. Emphasis
2. Text Align
3. Vertical Alignment

Enabled the options in styleConfig

Fixes #2906

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts [hunk 1]
```diff
@@ -106,8 +108,18 @@ export default [
           },
         ],
         defaultValue: "LEFT",
-        isBindProperty: false,
+        isJSConvertible: true,
+        isBindProperty: true,
         isTriggerProperty: false,
+        validation: {
+          type: ValidationTypes.TABLE_PROPERTY,
```
Comment (aswathkk) [inline app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts:115]: You don't need to make use of `ValidationTypes.TABLE_PROPERTY` since this configuration is not for the column but for the Table itself.

Just the following is enough:
```js
validation: {
   type: ValidationTypes.TEXT,
   params: {
     allowedValues: ["LEFT", "CENTER", "RIGHT"],
   },
}
```

File: app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts [hunk 2]
```diff
@@ -129,9 +141,19 @@ export default [
             value: "BOTTOM",
           },
         ],
-        defaultValue: "LEFT",
+        defaultValue: "CENTER",
+        isJSConvertible: true,
         isBindProperty: false,
         isTriggerProperty: false,
+        validation: {
```
Comment (aswathkk) [inline app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts:148]: Same as above

**Review by aswathkk — CHANGES_REQUESTED** [review]
@souma-ghosh We don't need to make use of `ValidationTypes.TABLE_PROPERTY`. Otherwise PR looks good to me.

**Review by aswathkk — APPROVED** [review]

File: app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts [hunk 3]
```diff
@@ -82,8 +82,10 @@ export default [
             value: "ITALIC",
           },
         ],
-        isBindProperty: false,
+        isJSConvertible: true,
+        isBindProperty: true,
         isTriggerProperty: false,
+        validation: { type: ValidationTypes.TEXT },
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts:88]: we need to provide the expected value as well.

**Comment by laveena-en** [comment]
Tested and verified.

File: app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts (hunk 3 above)
Comment (souma-ghosh) [reply app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts:88]: We can select multiple values for BUTTON_TABS control type.
It is accepting any string where it can find "bold" or "italic" somewhere in the string.
So valid values can be any of the following

- bolditalic
- bold,italic
- ["bold", "italic"]
- somethingboldsomething - bold gets activated
- randomitalicrandomboldrandom - both bold and italic gets activated

So what should we provide as expected value?
@sbalaji1192

Comment (souma-ghosh) [reply app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts:88]: Consulted @aswathkk  on this. Seems like the expected validation for BUTTON_TABS control type has been discussed before. Hence opening a new issue here https://github.com/appsmithorg/appsmith/issues/17018. Moving ahead with this one @sbalaji1192 @aswathkk
