### PR TITLE
fix: skipped unnecessary code for js object updates

### LINKED ISSUE #37114: [Task]: Add metrics for uninstrumented time during action update
### SubTasks

If we observe the Js object update call on new relic, for every existing action, we update in DB. During this process, on new relic we are observing uninstrumented time getting allocated when updating each action. This task is to add metrics around that uninstrumented time and also analyse the cause of it to see if it can be optimised.

Screenshot 2024-10-28 at 1 07 00 PM

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR is in continuation to [PR](https://github.com/appsmithorg/appsmith/pull/37062) which we had merged earlier, In previous, we skipped the redundant calls to update page layout when updating each js object action, as we already have a call for [updating the page layout for actionCollection](https://github.com/appsmithorg/appsmith/blob/27bdeb92b6a0b27e6afcbfe80a5cb0705c0812ac/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java#L411)

Since we have skipped the update page layout for each js action, we no longer need the code part after this, which basically fetches page data from DB and updates the `errorReports` in actionDTO based on layout `layoutOnLoadActionErrors`. This PR skips this unnecessary part too for each js action as we do [set the errorReport for actionCollection in the end](https://github.com/appsmithorg/appsmith/blob/27bdeb92b6a0b27e6afcbfe80a5cb0705c0812ac/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java#L430)

### Will this have any impact on error messages shown to user?
In order to understand this, checked out the frontend code to see if errorReports from individual js action is getting consumed on updating js object, looks like [it is not](https://github.com/appsmithorg/appsmith/blob/e7e3d5e00290919c1df0767fdefed67458ec3cc9/app/client/src/sagas/JSPaneSagas.ts#L316), so we can safely remove this piece of code.
However this points to existing bug in the code (as errorReports is not even getting consumed from actionCollection), which is, when there is cyclic dependency created for js object with a widget, we don't get any toast message. Since this is existing issue which is not caused by any of the above PR implementations, creating separate issue for it and tracking it [here](https://github.com/appsmithorg/appsmith/issues/37129)

Fixes #37114 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.JS, @tag.JS"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11698258739>
> Commit: 9fbde996545451c1a12736e0b8a9252ad4ab69bd
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11698258739&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.JS, @tag.JS`
> Spec:
> <hr>Wed, 06 Nov 2024 06:50:05 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Streamlined layout update process for actions, enhancing performance and clarity.

- **Bug Fixes**
	- Improved test reliability by monitoring interactions with the layout service and handling cyclic dependencies.

- **Documentation**
	- Updated comments to clarify the logic behind layout updates for JS actions.

- **Tests**
	- Enhanced test descriptions and assertions for better clarity and validation of method interactions, including cyclic dependency scenarios.

### CODE REVIEW

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java [hunk 1]
```diff
@@ -766,6 +766,14 @@ public void testUpdateUnpublishedActionCollection_withValidCollection_callsPageL
...
                     Mockito.verify(updateLayoutService, Mockito.times(2))
                             .updatePageLayoutsByPageId(Mockito.anyString());
+
+                    // This gets called 4 times:
+                    // 2 times during createCollection -> a. getExistingEntityNames and b. updatePageLayoutsByPageId
+                    // 1 time during setup of this test case
+                    // 1 time during update action collection -> As expected as find page by id should be called only
+                    // once in updatePageLayoutsByPageId
+                    Mockito.verify(newPageService, Mockito.times(4))
+                            .findPageById(Mockito.anyString(), Mockito.any(), Mockito.anyBoolean());
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java:776]: Can we assert for on load action errors please?

Comment (sneha122) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java]: Done, updated the test cases

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java [hunk 2]
```diff
@@ -249,36 +249,40 @@ protected Mono<ActionDTO> updateActionBasedOnContextType(NewAction newAction, Ac
...
-                });
+
+        // Update page layout is skipped for JS actions here because when JSobject is updated, we first
+        // update all actions, action
+        // collection and then we update the page layout, hence updating page layout with each action update
+        // is not required here
+        if (action.getPluginType() == PluginType.JS) {
+            return updateSingleAction(newAction.getId(), action)
+                    .name(UPDATE_SINGLE_ACTION)
+                    .tap(Micrometer.observation(observationRegistry));
```
Comment (NilanshBansal) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java:260]: @sneha122 just to confirm, earlier actionDTO that is getting returned from this function for JS actions contained the errorReports as well but after this change it will be null. Can we please assert that in a test case.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java [hunk 3]
```diff
@@ -766,6 +788,11 @@ public void testUpdateUnpublishedActionCollection_withValidCollection_callsPageL
                     // collection as expected
                     Mockito.verify(updateLayoutService, Mockito.times(2))
                             .updatePageLayoutsByPageId(Mockito.anyString());
+
+                    assertEquals(1, actionCollectionDTO1.getErrorReports().size());
+                    assertEquals(
+                            AppsmithError.CYCLICAL_DEPENDENCY_ERROR.getAppErrorCode(),
+                            actionCollectionDTO1.getErrorReports().get(0).getCode());
```
Comment (NilanshBansal) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java:795]: @sneha122 here we are asserting `errorReports` from the `actionCollectionDTO` but from the above function changes from `updateActionBasedOnContextType()` we have removed it from the returned `actionDTO`. Can we please assert a condition from the `actionDTO` for a `JS` type action that `errorReports` is null.

**Review by NilanshBansal — CHANGES_REQUESTED** [review]
Added comments.

**Review by NilanshBansal — APPROVED** [review]
LGTM
