### PR TITLE
FIX #4676 : added onclick handler and update property pane config to table widget for column type image

### LINKED ISSUE #4676: [Bug] Clicking on the image in Table widget takes the user to the URL of the image
## Description
A user on discord reported this bug. He felt this is an unintended behaviour. The image in the table widget takes the user to the URL of the image.

### Steps to reproduce the behaviour:

1. Drag and drop table widget
2. Change column type to `image`
3. Click on the image displayed in the table widget
4. A new tab is opened with the image URL

### Important Details
 - Version: [Cloud]
 - OS: [MacOSX]
 - Browser [chrome, safari]
 - Environment - [Production]

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Added onclick handler and update property pane config to table widget for column type image

Fixes #4676 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: FIX/4676-table-widget-onclick-for-columntype-image 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.82 **(-0.01)** | 35.79 **(-0.01)** | 32.44 **(0.01)** | 54.41 **(0)**
 :green_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx | 38.98 **(0.38)** | 19.48 **(0.3)** | 9.38 **(0)** | 37.04 **(0.5)**
 :green_circle: | app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts | 41.03 **(2.36)** | 13.73 **(0)** | 57.14 **(3.29)** | 43.24 **(2.39)**
 :red_circle: | app/client/src/widgets/TableWidget/index.tsx | 9.09 **(-0.12)** | 0 **(0)** | 10 **(-0.2)** | 9.71 **(-0.15)**</details>

### CODE REVIEW

**Comment by SatishGandham** [comment]
@techbhavin , What is the purpose of isSelected? Why we don't want click on a selected row?

**Comment by vibhandikyash** [comment]
@SatishGandham When the row is selected and user clicks on the image at that time onRowSelected handler was getting called unnecessarily and used stoppropogation to handle that.

File: app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx [hunk 1]
```diff
@@ -60,19 +62,21 @@ export const renderCell = (
...
-                    href={item}
                     key={index}
-                    onClick={(e) => e.stopPropagation()}
-                    rel="noopener noreferrer"
-                    target="_blank"
+                    onClick={(e) => {
+                      if (isSelected) {
+                        e.stopPropagation();
+                      }
+                      !!onClick && onClick();
```
Comment (SatishGandham) [inline app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx:72]: We don't need this check here as we have set a default for onclick.
Looks good otherwise.

**Review by SatishGandham — CHANGES_REQUESTED** [review]

**Comment by YogeshJayaseelan** [comment]
@vibhandikyash Tested this feature and it is working as expected

**Review by SatishGandham — APPROVED** [review]

**Comment by somangshu** [comment]
@vibhandikyash related jest tests are failing. Kindly look into this

**Review by somangshu — APPROVED** [review]
Approving to rerun the tests now

**Review by somangshu — APPROVED** [review]
