### PR TITLE
Fix-Native scrollbar UX with custom scrollbars

### LINKED ISSUE #2895: [Bug] Table has a vertical scrollbar even if content fits
## Description

A table always has a vertical scrollbar, whether or not the content of the table fits within the page. 

### Expected Behavior

The table should never need a vertical scrollbar, because it should load just as many rows as it can display on a single page. 

### Steps to reproduce the behaviour:

1. Open any table
2. Try scrolling in the table

Here's a loom recording showing what I mean:
[LOOM DEMO](https://www.loom.com/share/9c895fb2a2124d479ae4f72cafb444f6)

### Important Details
 - Version: Self-Hosted v1.3.3
 - OS: MacOSX (client), Ubuntu (server)
 - Browser: Chrome, Firefox (probably others too)

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Native scrollbar UX with custom scrollbars

Fixes #2895 #3249 #3966 #4035

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/native-scrollbars-experience 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 48.69 **(-0.01)** | 29.65 **(-0.02)** | 27.2 **(-0.07)** | 49.15 **(-0.01)**
 :green_circle: | app/client/src/components/ads/ScrollIndicator.tsx | 82.61 **(0.79)** | 52.78 **(-0.35)** | 86.67 **(0)** | 80.95 **(2.57)**
 :red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx | 35.37 **(-1.12)** | 16.81 **(0.71)** | 0 **(0)** | 35.37 **(-1.12)**
 :red_circle: | app/client/src/pages/Applications/ForkApplicationModal.tsx | 87.27 **(-7.28)** | 76 **(-20)** | 50 **(-20)** | 86.79 **(-7.55)**</details>

### CODE REVIEW

File: app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx [hunk 1]
```diff
@@ -148,125 +154,166 @@ export const Table = (props: TableProps) => {
...
+        ref={tableHeaderWrapperRef}
+        width={props.width}
+      >
+        <Scrollbars
+          style={{ width: props.width, height: 38 }}
+          renderThumbHorizontal={(props) => (
+            <div {...props} className="thumb-horizontal" />
+          )}
+          renderThumbVertical={(props) => (
+            <div {...props} className="thumb-vertical" />
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx:171]: Does this property need all the props?
Also, if this is a component, let's abstract it out and put it outside this component. Otherwise, this component will be created every time. Best case scenario is to make sure we only pass the props which are necessary.
Also, let's wrap the component in `React.memo`

File: app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx [hunk 2]
```diff
@@ -148,125 +154,166 @@ export const Table = (props: TableProps) => {
...
+              nextPageClick={props.nextPageClick}
+              prevPageClick={props.prevPageClick}
+              pageNo={props.pageNo}
+              pageCount={pageCount}
+              currentPageIndex={currentPageIndex}
+              pageOptions={pageOptions}
+              widgetName={props.widgetName}
+              serverSidePaginationEnabled={props.serverSidePaginationEnabled}
+              columns={props.columns.filter((column: ReactTableColumnProps) => {
+                return column.accessor !== "actions";
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx:195]: Let's put this in a `useMemo` so that this is not computed on every render and only renders when the columns change.

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Comment by riodeuno** [comment]
There are merge conflicts. Let's resolve those.

**Review by riodeuno — APPROVED** [review]
Approving for tests to run

**Review by riodeuno — DISMISSED** [review]

**Review by somangshu — APPROVED** [review]

**Comment by areyabhishek** [comment]
@vicky-primathon There's a weird case where there's a scrollbar visible. Could you fix this?
https://www.loom.com/share/a3f9926e9a8a487caea097d40317dae6
