### PR TITLE
Fix docker-compose installation

### LINKED ISSUE #318: [BUG]
## Description
Got an error while setting up appsmith using `install.sh`.

### Steps to reproduce the behaviour:
Followed steps outlined in https://docs.appsmith.com/quick-start#docker. Failed on 3rd step mentioned.

On running `./install.sh`, got the following logs,
```sh
👋  Thank you for trying out Appsmith!

🕵  Detecting your OS

[sudo] password for apoorv:
Installation Directory [appsmith]:
Is this a fresh installation? [Y/n]

Appsmith needs to create a mongo db
Set the mongo root user: root
Set the mongo password:

Do you have a custom domain that you would like to link? (Only for cloud installations) [N/y]: N
Generating the configuration files from the templates

No domain found. Skipping generation of SSL certificate.
Pulling the latest container images
sudo: docker-compose: command not found
```

### What you expected to happen
Fresh local installation of appsmith as expected after following  https://docs.appsmith.com/quick-start#docker.

### Important Details

How are you running appsmith?

On-Premise w/ Docker, version 19.03.9

Which browser / OS are you using?
 - OS: Ubuntu 18.04
 - Browser: NA

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Fixes #318

The issue occurred because code assumes that if `docker` is already installed, `docker-compose` would have been installed too. This PR is an attempt to fix it.

### CODE REVIEW

File: deploy/install.sh [hunk 1]
```diff
@@ -36,14 +36,23 @@ install_docker() {
...
+    if [ $package_manager == "apt-get" -o $package_manager == "yum" ];then
+        if [ ! -f /usr/bin/docker-compose ];then
+            echo "Installing docker-compose..."
+            sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+            sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
+            echo "docker-compose installed!"
+        fi
+    else
+        echo "docker-compose not found! Please install docker-compose first and then continue with this installation."
```
Comment (mohanarpit) [inline deploy/install.sh:51]:
```suggestion
        echo "+++++++++++ IMPORTANT READ ++++++++++++++++++++++"
        echo "docker-compose not found! Please install docker-compose first and then continue with this installation."
```

Suggest adding a section in order to help the user pin-point the error quickly.

File: deploy/install.sh [hunk 2]
```diff
@@ -36,14 +36,23 @@ install_docker() {
...
+        echo "Refer https://docs.docker.com/compose/install/ for installing docker-compose."
+        echo -e "Exiting for now. Bye! \U1F44B"
```
Comment (mohanarpit) [inline deploy/install.sh:53]:
```suggestion
        echo -e "Exiting for now. Bye! \U1F44B"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++"
```

**Comment by mohanarpit** [comment]
@apoorv-mishra Thanks a lot for raising this PR. Have added a couple of minor suggestions. It'll be great if you can incorporate them into your PR.
