### PR TITLE
fix: gs authorisation status updates

### LINKED ISSUE #23877: [Bug]: Gsheets even when permissions are denied authentication status remains as IN_PROGRESS, it should be updated to FAILURE
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

During google sheet authorisation, if we do not give any permissions, authentication status in datasource object still remains as in progress, it should be set to Failure.

### Steps To Reproduce

1. Create google sheet datasource
2. Do not grant permissions during authorisation
3. Check the `datasource.datasourceConfiguration.authentication.authenticationStatus` it should be failure, but it still says in progress

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/ Self-Hosted - 1.8.4

### PR DESCRIPTION
**Pull request by sneha122**
## Description
This PR fixes inconsistencies in the authenticationStatus property for google sheets:
- In case of google sheets datasource, when we authorise the datasource, but do not grant permissions, the authenticationStatus is being saved as `IN_PROGRESS`, instead it should be `FAILURE` as user failed to give permissions.
- This PR adds 3 new statuses in AuthenticationStatus Enum, `IN_PROGRESS_PERMISSIONS_GRANTED`, `FAILURE_ACCESS_DENIED` and `FAILURE_NO_FILES_SELECTED`.
- `IN_PROGRESS_PERMISSIONS_GRANTED` is used in case of specific sheets scope, so that we would know that users have granted permissions and selection of files is pending
- `FAILURE_ACCESS_DENIED` denotes, for any of the scope, if user does not grant permissions.
- `FAILURE_NO_FILES_SELECTED` denotes, for specific scope, if user grants permissions but files have not been selected yet.

#### PR fixes following issue(s)
Fixes #23877 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java [hunk 1]
```diff
@@ -37,7 +37,10 @@ public enum AuthenticationStatus {
         NONE,
         IN_PROGRESS,
         SUCCESS,
-        FAILURE
+        FAILURE,
```
Comment (Irongade) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java:40]: The same thing here as well

**Comment by tanvibhakta** [comment]
No ads review necessary

File: app/client/src/entities/Datasource/index.ts [hunk 2]
```diff
@@ -12,6 +12,9 @@ export enum AuthenticationStatus {
   IN_PROGRESS = "IN_PROGRESS",
   SUCCESS = "SUCCESS",
   FAILURE = "FAILURE",
```
[the remark this answers is not in the document]
Comment (sumitsum) [reply app/client/src/entities/Datasource/index.ts:14]: Hi @Irongade we need the default `FAILURE` event for these reasons: (1) So that older persisted events don't cause API server crash - otherwise we would need to run a migration to update the `FAILURE` state to one of the new states which would not be accurate because we don't know why it failed (2) In case we reach a failure state that cannot be mapped to any of of the other failure states reliably, then we can assign them the default failure state.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java (hunk 1 above)
Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java:40]: Responded in the previous comment.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java [hunk 3]
```diff
@@ -509,11 +510,19 @@ public Mono<OAuth2ResponseDTO> getAccessTokenFromCloud(String datasourceId, Stri
                                 // for specific sheets, it needs to remain in as in progress until files are selected
                                 // Once files are selected, client sets authentication status as SUCCESS, we can find this code in
                                 // /app/client/src/sagas/DatasourcesSagas.ts, line 1195
-                                if (oAuth2.getScope() != null && !oAuth2.getScope().contains(FILE_SPECIFIC_DRIVE_SCOPE)) {
-                                    datasource
+                                Set<String> oauth2Scopes = oAuth2.getScope();
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:513]: Hi @sneha122 can you please create a GitHub task to track refactor for this code block. This code block is GSheet plugin specific and hence should not reside in a generic handler like this file - we should ideally move this functionality to GSheet plugin module. We can take it up later.

**Review by sumitsum — APPROVED** [review]

**Comment by sumitsum** [comment]
server side changes LGTM.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java (hunk 3 above)
Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java:513]: https://github.com/appsmithorg/appsmith/issues/23940 Created the issue here

**Comment by prapullc** [comment]
Hi @sneha 
Regression is completed and I have identified only one issue which was reproducible only once. 
Attaching screenshot for referance 
Screenshot 2023-06-01 at 7 29 04 PM
