### PR TITLE
fix: Application created when the repo is empty in git import flow

### LINKED ISSUE #13446: [Bug]: On importing app from an empty repo, the app gets created with no pages.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On importing an app from empty git repository , gives error on gitImport modal but on hard refresh it creates an empty app with repository's name.

Screenshot 2022-04-29 at 3 21 44 PM

### Steps To Reproduce

1. Go to Import from a git repo
2. In gitImport modal give empty repo.
3. Error will be shown "git import failed. Details: Cannot import app from an empty repo"
4. Refresh the Page and observe
5. An app gets created with no pages

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> During the git import if we give the empty repo url, we just throw the error and inform the user. But we missed out is not creating the application in such scenarios. This PR fixes the app getting created when the repo is empty. 

Fixes #13446 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- JUnit test
- Locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by abhvsn — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 1]
```diff
@@ -1937,6 +1937,12 @@ public Mono<ApplicationImportDTO> importApplicationFromGit(String organizationId
                                 List<Datasource> datasourceList = data.getT2();
                                 List<Plugin> pluginList = data.getT3();
 
+                                if(Optional.ofNullable(applicationJson.getExportedApplication()).isEmpty()
+                                        || applicationJson.getPageList().isEmpty()) {
+                                    return deleteApplicationCreatedFromGitImport(application.getId(), application.getOrganizationId(), gitApplicationMetadata.getRepoName())
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1942]: For my understanding, why are we even creating the application in the first place and then deleting it from the DB? Is it possible to do these checks before we proceed with application creation in the first place?

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1942]: We need to clone the repo in the import flow and when we clone the repo we usually clone them to the file system with the path `orgId/appId/repoName` and then store the repoName in the gitApplicationMetadata object so that we can construct the path to the repo dynamically. This is one of the main reason why we create a empty application object with no other resources.

Comment (sharat87) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1942]: Hey, is this resolved? Should we merge this PR? @mohanarpit

Comment (mohanarpit) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1942]: Sure. Please go ahead.
