### PR TITLE
fix: Issue with evaluations when level_1 property is used

### LINKED ISSUE #19940: Task: QA Callout - 1
https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description
Fixes issue 2 in [QA tracker](https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0)

Note to Reviewer - Changes
1. When the siblings array ways updated using `modifyMetaWidget` `addorUpdate`, a stale meta widget was passed and was overriding the latest one in the reducer. Now modified to only update the particular property.
2. Removed the whole callback logic and used a simple approach where the property update is calculated and passed whenever meta widgets are generated.
3. The `deleteWidget` was not getting called in view mode as it was not added in the `EditorContextProvider`

Fixes #19940

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/BaseWidget.tsx [hunk 1]
```diff
@@ -240,21 +240,9 @@ abstract class BaseWidget<
...
-    const { propertyUpdates } = modifications;
-    const updatedPropertyUpdates: ModifyMetaWidgetPayload["propertyUpdates"] = [];
-
-    (propertyUpdates || []).forEach(({ path, value }) => {
-      updatedPropertyUpdates.push({
-        path: `${widgetId}.${path}`,
-        value,
-      });
-    });
-
```
Comment (Tooluloope) [inline app/client/src/widgets/BaseWidget.tsx:253]: @ashit-rath, I didn't get why we are removing this?

**Review by Tooluloope — APPROVED** [review]

File: app/client/src/widgets/BaseWidget.tsx (hunk 1 above)
Comment (Tooluloope) [reply app/client/src/widgets/BaseWidget.tsx:253]: Oh, I later understood why.
