### PR TITLE
fix: Reset of isPublic flag during git merge operation

### LINKED ISSUE #12595: [Bug]: The app visibility toggle is not set to public after git merge operation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The app visibility toggle is not set to the public after the git merge operation
#11682

### Steps To Reproduce

1. Connect an app to git repo
2. Create branch from the main branch
3. Make the app public
4. Add a widget or page or make any changes and then do commit + push
5. Now merge the branch back to main branch
6. Now click on share button
7. Now see the public toggle its not enabled even when app is public

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> The app visibility toggle is reset to the false after the git merge operation even though the app is public.

Fixes #12595 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java [hunk 1]
```diff
@@ -766,6 +766,10 @@
                                                 )
                                                 .flatMap(existingApplication -> {
                                                     importedApplication.setId(existingApplication.getId());
+                                                    // For the existing application we don't need to default value of the flag
+                                                    // The isPulbic flag has a default value as false and this would be confusing to user
+                                                    // when it is reset to false during git merge
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:771]: Instead of git-merge can we use import for already available application in DB, this way if we introduce a new feature in future to partially update the application with the JSON file like adding a page to the available application etc can come under same umbrella

Typo `isPulbic` in above statement

**Review by abhvsn — COMMENTED** [review]
Let's add the testcase to be future proof

**Review by abhvsn — APPROVED** [review]
LGTM
