### PR TITLE
fix: Clear cache when switching pages

### LINKED ISSUE #17097: [Bug]-[1340]:Same widget names in different pages causes widget to show stale value
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there is a Table widget with the same name on two pages in an application, Navigating from one page to another shows the widget with tableData from the previous page.

https://user-images.githubusercontent.com/5328605/192513123-8ad30580-76d3-47ae-8cf9-cce74a440f4f.mov

### Steps To Reproduce

1 . Drag a table widget and bind it to a sample user data source query
2. Create a new page
3. Drag a table widget on page 3 as well.
4. Observe that while navigating from one page to another shows the table widget with data from the previous page.
5. Renaming the table widget in any one of the pages fixes this issue.

### Public Sample App

https://app.appsmith.com/app/untitled-application-26/page1-6332dfa22384d5623d9a03d1

### Version

cloud

### PR DESCRIPTION
**Pull request by rimildeyjsr**
## Description

We noticed stale data from the previous page when having widgets with the same name on different pages. This PR fixes this by changing the data tree in the state when clearing the cache.

Fixes #17097 

PS - This task does not have tests, since we could not come up with an approach to test this scenario 

## Media

https://www.loom.com/share/14b88d57237d4a1097aa82185e9606cd

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Test Plan
tested with table, list and chart widgets

### Issues raised during DP testing
none

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer-reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reviewing all Cypress test

### CODE REVIEW

File: app/client/src/reducers/evaluationReducers/treeReducer.ts [hunk 1]
```diff
@@ -41,6 +41,13 @@ const evaluatedTreeReducer = createImmerReducer(initialState, {
     }
   },
   [ReduxActionTypes.FETCH_PAGE_INIT]: () => initialState,
+  [ReduxActionTypes.RESET_DATA_TREE]: () => {
+    const state = { ...initialState };
+    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+    // @ts-ignore
+    state.dataTree = undefined;
```
Comment (ohansFavour) [inline app/client/src/reducers/evaluationReducers/treeReducer.ts:48]: Is there a reason why we are setting this to *undefined*, instead of an empty object (the initial state)

Comment (rimildeyjsr) [reply app/client/src/reducers/evaluationReducers/treeReducer.ts]: youre right, no good reason, made the change!

**Review by ohansFavour — APPROVED** [review]

**Review by ohansFavour — CHANGES_REQUESTED** [review]
Set state as initial state in RESET_DATATREE handler

**Review by ohansFavour — APPROVED** [review]

**Comment by ramsaptami** [comment]
lgtm
cc: @rimildeyjsr
