### PR TITLE
fix: Remove default values for error message in analytics

### LINKED ISSUE #11096: [Bug]: Git syncs analytics
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are not sending gitHosting provider to the analytics
Error data points should be null for success states

### Steps To Reproduce

We are not sending gitHosting provider to the analytics
Error data points should be null for success states

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> Git-sync analytics we were sending empty string for error data points. This was causing issues in filtering out the data between error events and success events. This change set removes the default values for the error data points in case of success events and pass the null value to the analytics.

Fixes #11096

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 1]
```diff
@@ -2245,8 +2245,8 @@ private boolean isInvalidDefaultApplicationGitMetadata(GitApplicationMetadata gi
                             "applicationId", defaultApplicationId,
                             "organizationId", defaultIfNull(application.getOrganizationId(), ""),
                             "branchApplicationId", defaultIfNull(application.getId(), ""),
-                            "errorMessage", defaultIfNull(errorMessage, ""),
-                            "errorType", defaultIfNull(errorType, ""),
+                            "errorMessage", errorMessage,
+                            "errorType", errorType,
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2249]: This will still get registered can we remove these from the Map itself?
Check implementation in AnalyticsService
```
// Segment throws an NPE if any value in `properties` is null.
        for (final Map.Entry<String, Object> entry : analyticsProperties.entrySet()) {
            if (entry.getValue() == null) {
                analyticsProperties.put(entry.getKey(), "");
            }
        }
```

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:2249]: good point i was not aware of this.

**Review by abhvsn — APPROVED** [review]
