### PR TITLE
fix: update rts logic to use updated shared AST logic

### LINKED ISSUE #16848: [Bug]: AST logic used in the RTS folder not up to date.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The RTS APIs that exposes AST to the server are failing because code used in the RTS code has been modified due to changes in the AST logic as a result of this [PR](https://github.com/appsmithorg/appsmith/pull/16171)

### Steps To Reproduce

1. Call The endpoint `/rts-api/v1/ast/multiple-script-identifiers` in postman.
2. Observe the endpoint failing.

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #17100: [Task]: Add Integration tests for RTS API and Rename AST Functions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Add Jest Test cases
Add running integration test to Github workflow.

### PR DESCRIPTION
**Pull request by Irongade**
This PR does these things:

-  Ensures the RTS code makes use of the updated AST logic. The changes made can be found in this [PR](https://github.com/appsmithorg/appsmith/pull/16171).
- Writes Jest test cases to assert the results of the Calling the AST RTS endpoints
- Includes running the jest test cases in the github RTS workflows.

Fixes #17100 

- Bug fix (non-breaking change which fixes an issue)

Manual Tests

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/rts/src/routes/ast_routes.ts [hunk 1]
```diff
@@ -8,17 +8,17 @@ const astController = new AstController();
...
+  "/single-script-info",
   AstRules.getScriptValidator(),
   validator.validateRequest,
-  astController.getDependentIdentifiers
+  astController.getInfoFromScript
 );
 
 router.post(
-  "/multiple-script-identifiers",
+  "/multiple-script-infos",
```
Comment (AmanAgarwal041) [inline app/rts/src/routes/ast_routes.ts:18]: We already have `multiple` attached in the route. Can we remove `s` from info?

File: app/rts/src/controllers/Ast/AstController.ts [hunk 2]
```diff
@@ -46,7 +43,7 @@ export default class AstController extends BaseController {
       Promise.all(
         scripts.map(
           async (script) =>
-            await AstService.getIdentifiersFromScript(script, evalVersion)
+            await AstService.extractInfoFromScript(script, evalVersion)
```
Comment (ohansFavour) [inline app/rts/src/controllers/Ast/AstController.ts:46]: There should be a third argument here too

File: app/rts/src/controllers/Ast/AstController.ts [hunk 3]
```diff
@@ -18,14 +18,11 @@ export default class AstController extends BaseController {
     super();
   }
 
-  async getDependentIdentifiers(req: Request, res: Response) {
```
Comment (nidhi-nair) [inline app/rts/src/controllers/Ast/AstController.ts:21]: Can we rename this method to something more descriptive? I am unable to understand what `info` indicates here.

File: app/rts/src/controllers/BaseController.ts [hunk 4]
```diff
@@ -1,6 +1,9 @@
 import { Response } from "express";
 import { ValidationError } from "express-validator";
 import { StatusCodes } from "http-status-codes";
+import { ExtractInfoFromCode } from "@shared/ast";
+
+type Extractions = ExtractInfoFromCode;
```
Comment (ohansFavour) [inline app/rts/src/controllers/BaseController.ts:6]: is there any reason for the re-assignment here?. If "Extractions" is a better name then we could change it in the @shared/ast file itself.

File: app/rts/src/services/AstService.ts [hunk 5]
```diff
@@ -1,16 +1,10 @@
...
-    evalVersion
-  ): Promise<any> {
+  static async extractInfoFromScript(script, evalVersion): Promise<any> {
     return new Promise((resolve, reject) => {
       try {
-        const extractions = extractIdentifiersFromCode(
-          script,
-          evalVersion
-        );
+        const extractions = extractInfoFromCode(script, evalVersion);
```
Comment (ohansFavour) [inline app/rts/src/services/AstService.ts:7]: Third argument needed here too

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Could we please add integration test cases here to make sure that CI fails if any PR tries to change the structure of how this library returns data in the future?

Also, does this change affect the API response in any way? If yes, could you please share the expected response structure in the PR description?

File: app/rts/src/controllers/Ast/AstController.ts (hunk 3 above)
Comment (Irongade) [reply app/rts/src/controllers/Ast/AstController.ts:21]: We are returning a bunch of Information from the function, hence why we used Info, However on a second thought, we can make use of the word "Data". Data will be a good enough generic name.

**Comment by Irongade** [comment]
> Also, does this change affect the API response in any way? If yes, could you please share the expected response structure in the PR description?

Expected change in the API response will follow the schema below.
 
```
 interface Extractions {
  references: string[];
  functionalParams: string[];
  variables: string[];
}
```

**Comment by AmanAgarwal041** [comment]
> Could we please add integration test cases here to make sure that CI fails if any PR tries to change the structure of how this library returns data in the future?
> 
> Also, does this change affect the API response in any way? If yes, could you please share the expected response structure in the PR description?

The API routes also change.

File: app/rts/src/services/AstService.ts [hunk 6]
```diff
@@ -1,15 +1,17 @@
-import { extractIdentifiersFromCode } from "@shared/ast";
```
Comment (nidhi-nair) [inline app/rts/src/services/AstService.ts:1]: Hey I'm sorry to nitpick, but this is still not informative. Info and data are quite generic and do not glean insight into what kind of data we expect to get here. Could we either revert to identifiers or use something more informative here?

I am guessing we will need to make this change to the ast library as well.

**Review by nidhi-nair — COMMENTED** [review]
QQ, @Irongade could you please explain to me why we need to version control the yarn lock file?

**Comment by Irongade** [comment]
> QQ, @Irongade could you please explain to me why we need to version control the yarn lock file?

@nidhi-nair, I'm not sure why yarn.lock file was version controlled as well, but my guess would be that there might be certain dependencies that we don't want changing.

File: .github/workflows/rts-build.yml [hunk 7]
```diff
@@ -119,6 +119,16 @@ jobs:
           echo ::set-output name=version::$next_version-SNAPSHOT
           echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
 
+      # Install all the dependencies
+      - name: Install dependencies
```
Comment (AmanAgarwal041) [inline .github/workflows/rts-build.yml:123]: Build step already installs dependencies. Why do we need to install dependencies here? Can we not move this step after the build process ?

File: app/shared/ast/src/index.test.ts [hunk 8]
```diff
@@ -1,85 +1,85 @@
...
-        script: 'Table5.data.map(c => ({ name: c.name }))',
-        expectedResults: ['Table5.data.map'],
+        script: "Table5.data.map(c => ({ name: c.name }))",
+        expectedResults: ["Table5.data.map"],
       },
       {
         // Literal property search
         script: "Table6['data']",
-        expectedResults: ['Table6'],
+        expectedResults: ["Table6"],
```
[the remark this answers is not in the document]
Comment (Irongade) [reply app/shared/ast/src/index.test.ts:57]: Good, then there will be no merge conflicts. It was automatically done by Prettier.

File: .github/workflows/rts-build.yml (hunk 7 above)
Comment (Irongade) [reply .github/workflows/rts-build.yml:123]: 1. We need to install all dependencies in order to be able to run the Jest test cases, as Jest, Supertest and other dependencies are required for this step.
2. Ideally we should run jest test cases before commencing a build as this is the best practice. So I think we have to remove the extra yarn install in the build.sh file (as long as it does not break the docker deployment for RTS - I did not remove it for this reason).

Comment (AmanAgarwal041) [reply .github/workflows/rts-build.yml:123]: Since both jest test cases and build are independent on each other here, we can move the running of jest test cases after build as both steps are important. We cannot remove the `yarn install` step in build.sh file as this is the file being called when the build is created.

**Comment by nidhi-nair** [comment]
> I'm not sure why yarn.lock file was version controlled as well, but my guess would be that there might be certain dependencies that we don't want changing.

@Irongade I thought yarn allowed you to specify particular versions in the definition itself, no? Is that understanding incorrect? 🤔

**Comment by Irongade** [comment]
> > I'm not sure why yarn.lock file was version controlled as well, but my guess would be that there might be certain dependencies that we don't want changing.
> 
> @Irongade I thought yarn allowed you to specify particular versions in the definition itself, no? Is that understanding incorrect? 🤔

Yes, but we would be hardcoding the versions in the package.json file for example `moment: 4.5.2`. It is often better to use the yarn.lock file instead to maintain versions. We make use of this pattern in the client folder as well.

**Review by AmanAgarwal041 — APPROVED** [review]

**Review by nidhi-nair — APPROVED** [review]
