### PR TITLE
fix: code to UI breaking by disabling JS toggle

### LINKED ISSUE #22180: [Bug]: Code to UI breaking for  Action selector
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below code snippet is not working while doing toggle JS-NON JS, expected was to disable it when not able to translate 

```
`{{["UI Building", "Actions", "JS", "Autocomplete", "Widgets", "Pages", "Property Pane", "API Pane", "Query Editor", "Datasources", "ACL", "Login / Signup", "Telemetry", "Deployment"].forEach((label, index) => {
  Api1.run((res, param) => {
    let CritLen = 0;
    let HighLen = 0;
    let LowLen = 0;
    let NoPriLen = 0;
    res.map(issue => {
      let noPriVal = 1;
      issue.labels.map(label => {
        if (label.name === "Critical") {
          CritLen++;
          noPriVal = 0;
        } else if (label.name === "High") {
          HighLen++;
          noPriVal = 0;
        } else if (label.name === "Low") {
          LowLen++;
          noPriVal = 0;
        }
      });
      NoPriLen += noPriVal;
    });
    storeValue("Bug-" + param.index + "", {
      x: param.label,
      critY: CritLen,
      highY: HighLen,
      lowY: LowLen,
      noPriY: NoPriLen
    });
  }, undefined, {
    label: label,
    index: index
  });
  Query1.run((res, param) => {
    let CritLen = 0;
    let HighLen = 0;
    let LowLen = 0;
    let NoPriLen = 0;
    res.map(issue => {
      let noPriVal = 1;
      issue.labels.map(label => {
        if (label.name === "Critical") {
          CritLen++;
          noPriVal = 0;
        } else if (label.name === "High") {
          HighLen++;
          noPriVal = 0;
        } else if (label.name === "Low") {
          LowLen++;
          noPriVal = 0;
        }
      });
      NoPriLen += noPriVal;
    });
    storeValue("Feature-" + param.index, {
      x: param.label,
      critY: CritLen,
      highY: HighLen,
      lowY: LowLen,
      noPriY: NoPriLen
    });
  }, undefined, {
    label: label,
    index: index
  });
});}}`
```

code`{{
(function(){
    return  Promise.race([
            Api1.run({ name: 1 }),
            Api1.run({ name: 2 })
    ]).then((res) => {
        showAlert(`Winner: ${res.args.name}`)
    });
})()
}}`

Screenshot - 
Screenshot 2023-04-07 at 4 18 09 PM

Working in DP - https://appsmith-ejs3m15tj-get-appsmith.vercel.app/app/actionrefactor/page1-63a074cf8ee2c20625765e14/edit/widgets/v88nz2t05x

### Steps To Reproduce

1. Add above code snippet and toggle between the Non JS mode and verify the the code in UI

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by ravikp7**
## Description
In some cases, while converting code to UI, the actions were being rendered incorrectly. This PR addresses the issue by disabling the JS toggle in such cases.

#### PR fixes following issue(s)
Fixes #22180 #22505

## Media
Screenshot 2023-05-12 at 12 02 04 AM
Screenshot 2023-05-12 at 12 02 11 AM

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] Jest
- [x] Cypress

#### Test Plan
- snippets present on the issue
- snippets with spaces formated on the editor
- function declaration like `function() {}`

#### Issues raised during DP testing
none

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [x] Cypress test cases have been added and approved by SDET/manual QA
- [x] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts [hunk 1]
```diff
@@ -0,0 +1,109 @@
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { agHelper, apiPage, entityExplorer, jsEditor, locators, propPane } = _;
+
+describe("Disable JS toggle when Action selector code is not parsable", () => {
+  before(() => {
+    cy.fixture("buttondsl").then((val: any) => {
+      agHelper.AddDsl(val);
+    });
+    apiPage.CreateApi("Api1", "GET");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:10]: Is API needed?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts [hunk 2]
```diff
@@ -0,0 +1,109 @@
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { agHelper, apiPage, entityExplorer, jsEditor, locators, propPane } = _;
+
+describe("Disable JS toggle when Action selector code is not parsable", () => {
+  before(() => {
+    cy.fixture("buttondsl").then((val: any) => {
+      agHelper.AddDsl(val);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:8]: Since its only one button that is needed, can we please prefer drag drop - instead of relying in dsl load?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+    });
+    apiPage.CreateApi("Api1", "GET");
+    entityExplorer.SelectEntityByName("Button1", "Widgets");
+  });
+
+  it("1. Bug 22180", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:14]: So - all of the below cases are only verifying for `AssertJSToggleDisabled`?
And all can be into single `it`
Can we add one valid snippet & verify `AssertJSToggleEnabled` too?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts (hunk 1 above)
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:10]: Yes, it's needed. It's being used in the code snippet.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts (hunk 3 above)
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:14]: They all are different code snippets, so added in separate `it` blocks. We don't need the `AssertJSToggleEnabled` as it's already covered in other action selector related tests. There we have all valid snippets and we're doing toggling there.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts (hunk 2 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:8]: `    _.entityExplorer.DragDropWidgetNVerify(WIDGET.BUTTON, 200, 200);
`

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts (hunk 3 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:14]: Example please?
I know we add many JS snippets via js toggle - but not sure if we check if the toggle is enabled back?

Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:14]: check `uiToCode_spec.ts`. In that spec we're using `propPane.EnterJSContext` and `propPane.DisableJSContext` at multiple places to switch back and forth with valid JS snippet. If the toggle was disabled, we couldn't do so.

File: app/client/src/components/propertyControls/ActionSelectorControl.tsx [hunk 4]
```diff
@@ -129,8 +131,22 @@ class ActionSelectorControl extends BaseControl<ControlProps> {
...
+        // If converting the code block to action tree and then back to code block
+        // results in the same code block, then the code block can be displayed in UI
+        const actionTree = codeToAction(codeBlock, fieldOptions, true, true);
+        const codeFromActionTree = actionToCode(actionTree);
+
+        const isSame = compareCodeBlockASTs(
+          codeBlock,
+          codeFromActionTree,
+          evaluationVersion,
+        );
```
Comment (arunvjn) [inline app/client/src/components/propertyControls/ActionSelectorControl.tsx:145]: Would this account for spaces and comments ?
We could avoid these additional checks by returning the root call expressions names from `canTranslateToUI` and and comparing to check if they are valid.

File: app/client/src/components/editorComponents/ActionCreator/utils.ts [hunk 5]
```diff
@@ -292,6 +293,15 @@ export function codeToAction(
     if (mainActionType === AppsmithFunction.none) {
       throw new Error("Invalid action detected");
     }
+
+    // In the action selector field, if we can't find the selected option,
+    // it means, we can't render that action correctly in the UI
+    const fieldConfig = FIELD_CONFIG[FieldType.ACTION_SELECTOR_FIELD];
+    const selectedOptionValue = fieldConfig.getter(jsCode);
```
Comment (arunvjn) [inline app/client/src/components/editorComponents/ActionCreator/utils.ts:300]: Would this not default to `AppsmithFunction.none` ?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts (hunk 2 above)
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts]: Done

File: app/client/src/components/editorComponents/ActionCreator/utils.ts (hunk 5 above)
Comment (ravikp7) [reply app/client/src/components/editorComponents/ActionCreator/utils.ts:300]: Check the [last screenshot in this issue](https://github.com/appsmithorg/appsmith/issues/22505) It address that

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts [hunk 6]
```diff
@@ -1,12 +1,11 @@
...
 
-const { agHelper, apiPage, entityExplorer, jsEditor, locators, propPane } = _;
+const { agHelper, apiPage, entityExplorer, propPane } = _;
 
 describe("Disable JS toggle when Action selector code is not parsable", () => {
   before(() => {
-    cy.fixture("buttondsl").then((val: any) => {
-      agHelper.AddDsl(val);
-    });
+    entityExplorer.DragDropWidgetNVerify(WIDGET.BUTTON, 200, 200);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:8]: Is this run locally? I think after dragdrop - you need to switch to explorer tab to Create Api:
`    _.entityExplorer.NavigateToSwitcher("explorer");
`

File: app/client/src/components/propertyControls/ActionSelectorControl.tsx (hunk 4 above)
Comment (ravikp7) [reply app/client/src/components/propertyControls/ActionSelectorControl.tsx:145]: The whole idea of using AST to compare was to make sure that it accounts for spaces, but after giving it a second look, I don't think it's handled right now. For comments, yes that's also a miss. Let me check and add the comment support and remove the `locations` and `ranges` option. I think that will take care of spaces.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts (hunk 6 above)
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:8]: Yes, it ran locally

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts [hunk 7]
```diff
@@ -0,0 +1,128 @@
...
+  });
+
+  it("5. Test case", () => {
+    const codeSnippet = `{{Api1.run().then(() => {
+      return Api1.data;
+    })}}`;
+
+    propPane.EnterJSContext("onClick", codeSnippet);
+    agHelper.Sleep(200);
+    propPane.AssertJSToggleDisabled("onClick");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts:126]: Since these are extremely small validations, please move to single  `it` & give proper description to `it`. Not `Testcase`.
2, 3, 4, 5 - all can be in single `it` block please.

Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/disableJSToggle_spec.ts]: done

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/ActionSelector_JsToNonJSMode_spec.ts [hunk 8]
```diff
@@ -188,7 +188,7 @@ describe("JS to non-JS mode in Action Selector", () => {
     _.entityExplorer.SelectEntityByName("Button1", "Widgets");
     _.propPane.EnterJSContext(
       "onClick",
-      "{{Api1.run().catch(() => copyToClipboard('hi'))}}",
+      "{{Api1.run().catch(() => { copyToClipboard('hi'); })}}",
```
[the remark this answers is not in the document]
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/ActionSelector_JsToNonJSMode_spec.ts]: reverted

**Review by arunvjn — APPROVED** [review]

**Comment by ramsaptami** [comment]
lgtm cc: @ravikp7

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good.

File: app/client/cypress/e2e/Regression/ClientSide/ActionExecution/disableJSToggle_spec.ts [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+        index: index
+      });
+    });}}`;
+
+    propPane.EnterJSContext("onClick", codeSnippet);
+    agHelper.Sleep(200);
+    propPane.AssertJSToggleDisabled("onClick");
+  });
+
+  it("should disable JS toggle when the code can't be parsed into UI", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/ActionExecution/disableJSToggle_spec.ts:87]: Index this case too. Approving for now.

**Review by Aishwarya-U-R — APPROVED** [review]
