### PR TITLE
fix: Do not show empty array as an error for tableData field

### LINKED ISSUE #6893: [Bug] Table widget: allow empty data object
## Description

Today the table widget requires the data to be of the format `[{}]`, where as the user usually tries to set `[]` for the empty data. The table widget also shows an error when the API has not finished loading. We need to allow empty data sets in the table data and also not show the error where the data has not finished loading

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [production]

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

This fix does not mark empty array as an error. For e.g tableData field of TableWidget

Fixes #6893 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Jest test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/empty-arrays 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.61 **(0)** | 36.41 **(0.02)** | 33.83 **(0)** | 55.21 **(0.01)**
 :green_circle: | app/client/src/workers/validations.ts | 73.95 **(0.16)** | 66.36 **(0.17)** | 63.33 **(0)** | 76.14 **(0.25)**</details>

### CODE REVIEW

**Review by rishabhsaxena — DISMISSED** [review]

File: app/client/src/workers/validations.ts [hunk 1]
```diff
@@ -580,7 +580,16 @@ export const VALIDATORS: Record<ValidationTypes, Validator> = {
...
 
     if (Array.isArray(parsed)) {
-      if (parsed.length === 0) return invalidResponse;
+      if (parsed.length === 0) {
+        if (config.params?.required) {
+          return invalidResponse;
+        } else {
+          return {
+            isValid: true,
+            parsed: config.params?.default || [{}],
```
Comment (rishabhsaxena) [inline app/client/src/workers/validations.ts:589]: as an enhancement we could create a config for all default values vs `ValidationTypes`?
```
const defaultValuesByValidationTypes = {
  [ValidationType]: [{}]
}
```

Comment (akash-codemonk) [reply app/client/src/workers/validations.ts:589]: I don't think we can do this currently, because looking at the file, for each type we might be returning a different parsed value based on further validations. For e.g https://github.com/appsmithorg/appsmith/blob/fix/empty-arrays/app/client/src/workers/validations.ts#L476 and https://github.com/appsmithorg/appsmith/blob/fix/empty-arrays/app/client/src/workers/validations.ts#L484

**Review by jsartisan — APPROVED** [review]
