### PR TITLE
fix: set eval version for workflows artefact 

### LINKED ISSUE #34171: [Bug]: adding `"\n"` to the workflow code causes the evaluation to fail
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add `\n` to my workflow code, the evaluation fails.
Side effect: When the PUT call to update the actions in JS object happens, it removes the function which has errors in it.

### Steps To Reproduce

Create a workflow and use `\n` in it.

### Public Sample App

_No response_

### Environment

Production

### Severity

Critical (Broken Production apps)

### Issue video log

_No response_

### Version

1.28_SNAPSHOT

### PR DESCRIPTION
**Pull request by ayushpahwa**
## Description
Eval version 2 is used to properly handle the escape characters like `\n` etc in the eval flow. If not set, it is defaulting to behaviour for eval version 1. This PR introduces the type fixes to allow for eval version to be set via the API. The main change is in the EE PR and this PR is to update the type. 

Fixes #34171 

## Automation

/test sanity

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9478023950>
> Commit: c5edfb33f93802d2a025a064ddaa4593ea7932a4
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9478023950&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Refactor**
  - Consolidated `EvaluationVersion` type imports to a single source for improved maintainability.
  - Promoted `DEFAULT_EVALUATION_VERSION` to be exportable for broader use across the application.

### CODE REVIEW

**Review by rajatagrawal — APPROVED** [review]

File: app/client/src/ce/constants/WorkflowConstants.ts [hunk 1]
```diff
@@ -14,6 +16,9 @@ export interface Workflow {
   slug: string; // Slug of the workflow (Not in use currently).
   mainJsObjectId: string; // ID of the main JS object.
   tokenGenerated: boolean;
+  // Evaluation version of the application. Used to ensure the escape characters are properly evaluated.
+  // PR for reference: https://github.com/appsmithorg/appsmith/pull/8796
+  evaluationVersion?: EvaluationVersion;
```
Comment (rajatagrawal) [inline app/client/src/ce/constants/WorkflowConstants.ts:21]: Is it required to have evaluationVersion as optional ? Can it be non optional ?

Comment (ayushpahwa) [reply app/client/src/ce/constants/WorkflowConstants.ts:21]: It is going to be optional till server starts sending it in. In EE PR, I am setting a default value. Once server starts sending, it will be enforced.

Comment (rajatagrawal) [reply app/client/src/ce/constants/WorkflowConstants.ts:21]: If there is a default value provided, then it can be assumed that evaluation version would always be present. Would that be the case ? From client's perspective, evaluation version is always present, either server value or default value.

Comment (ayushpahwa) [reply app/client/src/ce/constants/WorkflowConstants.ts]: Updated

**Review by rajatagrawal — APPROVED** [review]
