### PR TITLE
fix: ssh to http url conversion

### LINKED ISSUE #10216: Url conversion is wrong for bitbucket clients

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> This fixes the issue with the bitbucket url. In the git connected apps when there is a conflict error we show the browser supported(https) git client urls so that the user can go to the git repo and resolve the conflicts. But for the bitbucket this conversion is wrong and this PR fixes the conversion issue.  

Fixes #10216 #10217

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java [hunk 1]
```diff
@@ -28,6 +28,7 @@ public static String convertSshUrlToHttpsCurlSupportedUrl(String sshUrl) {
         return sshUrl
                 .replaceFirst("git@", "https://")
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java:29]: Hey we have to update the regex here to cover other cases as well https://git-scm.com/docs/git-clone#_git_urls.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java [hunk 2]
```diff
@@ -28,6 +28,7 @@ public static String convertSshUrlToHttpsCurlSupportedUrl(String sshUrl) {
...
                 .replaceFirst("\\.com:", ".com/")
+                .replaceFirst("\\.org", ".org/")
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java:31]: Here **\\.org`:`** is missing. But I started to think should we address other placeholders as well?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 3]
```diff
@@ -1576,12 +1576,18 @@ private String getReason() {
 
                         localBranch.removeAll(remoteBranches);
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1577]: Can we filter the `defaultBranch` in DB from the list so as not to delete this even the same is deleted from remote? We will come up with a better approach in future though

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java (hunk 2 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java:31]: Do git clients have extensions such as .in, .io kind ? There are not many git clients. We can use regex to support them but is it really required ?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 3 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1577]: Yep this would lead to bad state. Good catch.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 4]
```diff
@@ -1575,15 +1571,29 @@ private String getReason() {
                                 .collect(Collectors.toList());
 
                         localBranch.removeAll(remoteBranches);
+                        localBranch.remove(gitApplicationMetadata.getBranchName());
+
+                        // Remove the branches which are not in remote from the list before sending
+                        gitBranchListDTOS = gitBranchListDTOS.stream()
+                                .filter(gitBranchDTO -> !localBranch.contains(gitBranchDTO.getBranchName()))
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1578]: Sorry I should have reported this earlier but why are we checking with contains, so consider there are 2 branches `feature/f1` and `feature/f10`.

**Review by abhvsn — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java (hunk 4 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1578]: I am using `.contains` on list of strings and it looks for exact match.

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1582]: `.equals` looks for the exact match

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1582]: `list.contains()` looks for the exact match. `String.contains()` looks for partial match.

**Review by abhvsn — APPROVED** [review]
