### PR TITLE
fix:  Improper formatting for Input Widget for DataType currency

### LINKED ISSUE #8832: [Bug]: Input Widget for DataType currency seems broken
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Issues 

1. why do we need to erase the decimal and type again to see the updated comma?
2. the comma for a currency doesn’t work without a decimal point
[LOOM DEMO](https://www.loom.com/share/b5b45b509a0a4f209ac64599c46021fb)

3. Random numbers getting generated in between

https://user-images.githubusercontent.com/23132741/138881284-b0f4c2a6-a3df-435b-ac46-01a6688fa34b.mov

### Steps To Reproduce

1. Add Input Widget
2. Change type to currency
3. Try typing `535,316.00` and then removing `6`
4. See the error
5. Again try removing `1` and see the error

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description

Number to be formatted on blur event and deformed when the input is focused. This solves the problem of formatting while user is editing the input.

Fixes #8832

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Unit tests are added

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/currency-formating 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.06 **(0.03)** | 36.54 **(0.09)** | 34.51 **(0.07)** | 55.59 **(0.03)**
 :red_circle: | app/client/src/widgets/InputWidget/component/index.tsx | 57.86 **(-0.47)** | 44.68 **(0.72)** | 59.18 **(-1.29)** | 56.77 **(-0.26)**
 :green_circle: | app/client/src/widgets/InputWidget/component/utilities.ts | 95.92 **(-4.08)** | 76.79 **(26.79)** | 100 **(0)** | 97.5 **(-2.5)**
 :red_circle: | app/client/src/widgets/InputWidget/widget/index.tsx | 60.87 **(-1.99)** | 41.25 **(-1.99)** | 70.83 **(1.26)** | 63.3 **(-1.7)**</details>

### CODE REVIEW

**Comment by vicky-primathon** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1439134853

**Review by jsartisan — DISMISSED** [review]

**Comment by vicky-primathon** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1448005682

**Comment by vicky-primathon** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1452179605

File: app/client/src/widgets/InputWidget/component/utilities.ts [hunk 1]
```diff
@@ -7,3 +7,40 @@ export const countryToFlag = (isoCode: string) => {
         )
     : isoCode;
 };
+
```
Comment (jsartisan) [inline app/client/src/widgets/InputWidget/component/utilities.ts:10]: can we also add some comments to get a brief info what this function is doing like this:

image

File: app/client/src/widgets/InputWidget/component/utilities.ts [hunk 2]
```diff
@@ -7,3 +7,40 @@ export const countryToFlag = (isoCode: string) => {
...
+    value.includes(".") && currentIndexOfDecimal <= indexOfDecimal;
+  const locale = navigator.languages?.[0] || "en-US";
+  const formatter = new Intl.NumberFormat(locale, {
+    style: "decimal",
+    minimumFractionDigits: isDecimal ? fractionDigits : 0,
+  });
+  return formatter.format(parseFloat(value));
+};
+
+export const limitDecimalValue = (
```
Comment (jsartisan) [inline app/client/src/widgets/InputWidget/component/utilities.ts:25]: same here. some brief info would be great.

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Tested this PR and fixes for issue 1 , 2, 3 and 4 are working as expected.

New issue:

Issue 5 - when the user enter value to the currency field and clicking on up or down arrow removes the value which are entered

https://www.loom.com/share/1c9290561c6849cc898055da42abbb54

**Comment by vicky-primathon** [comment]
> @vicky-primathon Tested this PR and fixes for issue 1 , 2, 3 and 4 are working as expected.
> 
> New issue:
> 
> Issue 5 - when the user enter value to the currency field and clicking on up or down arrow removes the value which are entered
> 
> [LOOM DEMO](https://www.loom.com/share/1c9290561c6849cc898055da42abbb54)

@vivekverma2312  above issue (5) is fixed.

File: app/client/cypress.json [hunk 3]
```diff
@@ -18,5 +18,13 @@
   "retries": {
     "runMode": 2,
     "openMode": 0
+  },
+  "env": {
+    "USERNAME": "vicky.bansal@primathon.in",
```
[the remark this answers is not in the document]
Comment (jsartisan) [reply app/client/cypress.json:23]: @vicky-primathon just one doubt about exporting credentials like this. can you confirm with nandan on this?

**Review by jsartisan — APPROVED** [review]

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Verified this PR and issues are fixed and working as expected

File: app/client/src/widgets/InputWidget/component/index.tsx [hunk 4]
```diff
@@ -326,40 +351,41 @@ class InputComponent extends React.Component<
     this.props.onValueChange(event.target.value);
   };
 
-  onNumberChange = (valueAsNum: number, valueAsString: string) => {
+  onButtonClick = (type: number) => {
+    let deFormattedValue: string | number = this.props.value
+      .split(",")
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/index.tsx:356]: We use Intl.NumberFormat to format the string. so based on the locale, decimal seperator could be `,` or `.` and Thousands seperator could be `.` or `,`. Could we figure out the decimal and Thousands separator in runtime?
Reference:
https://en.wikipedia.org/wiki/Decimal_separator#Usage_worldwide
https://stackoverflow.com/questions/1074660/with-a-browser-how-do-i-know-which-decimal-separator-does-the-operating-system

File: app/client/src/widgets/InputWidget/component/index.tsx [hunk 5]
```diff
@@ -436,6 +462,24 @@ class InputComponent extends React.Component<
...
+        this.props.value,
+      );
+      this.props.onValueChange(formattedValue);
+    }
+
+    this.setFocusState(false);
+  };
+
+  onNumberInputFocus = () => {
+    const deFormattedValue = ("" + this.props.value).split(",").join("");
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/index.tsx:478]: here too

File: app/client/src/widgets/InputWidget/component/utilities.ts [hunk 6]
```diff
@@ -7,3 +7,64 @@ export const countryToFlag = (isoCode: string) => {
...
+ Returns number in string format with maximum number of decimals based on decimalsInCurrency value
+  for eg:
+  a) (2, 1235.456) will return 1234.56 
+  b) (1, 1234.456) will return 1234.5
+*/
+export const limitDecimalValue = (
+  decimalsInCurrency = 0,
+  valueAsString: string,
+) => {
+  let value = valueAsString.split(",").join("");
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/utilities.ts:53]: here too

File: app/client/src/widgets/InputWidget/component/utilities.ts [hunk 7]
```diff
@@ -7,3 +7,64 @@ export const countryToFlag = (isoCode: string) => {
...
+ and add commas based on user's local browser
+  for eg:
+  a) (2, 1235.456) will return 1,234.56 
+  b) (1, 1234.456) will return 1,234.5
+*/
+export const formatCurrencyNumber = (decimalsInCurrency = 0, value: string) => {
+  if (value === "") return "";
+  let valueToFormat = value;
+  const fractionDigits = decimalsInCurrency || 0;
+  const currentIndexOfDecimal = value.indexOf(".");
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/utilities.ts:22]: here too

File: app/client/src/widgets/InputWidget/component/index.tsx [hunk 8]
```diff
@@ -309,11 +314,62 @@ class InputComponent extends React.Component<
...
 
+  updateValueOnButtonClick = (type: number) => {
+    let deFormattedValue: string | number = this.props.value
+      .split(this.groupSeparator)
+      .join("");
+    const stepSize = this.props.stepSize || 1;
+    deFormattedValue = +deFormattedValue + stepSize * type;
+    const formattedValue = formatCurrencyNumber(
+      this.props.decimalsInCurrency,
+      "" + deFormattedValue,
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/index.tsx:359]: Use `String(deFormattedValue)`

File: app/client/src/widgets/InputWidget/component/index.tsx [hunk 9]
```diff
@@ -309,11 +314,62 @@ class InputComponent extends React.Component<
...
+      }
+    }
   }
 
+  updateValueOnButtonClick = (type: number) => {
+    let deFormattedValue: string | number = this.props.value
+      .split(this.groupSeparator)
+      .join("");
+    const stepSize = this.props.stepSize || 1;
+    deFormattedValue = +deFormattedValue + stepSize * type;
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/index.tsx:356]: use `Number(deFormattedValue)`

File: app/client/src/widgets/InputWidget/component/index.tsx [hunk 10]
```diff
@@ -436,6 +485,29 @@ class InputComponent extends React.Component<
...
+      );
+      this.props.onValueChange(formattedValue);
+    }
+
+    this.setFocusState(false);
+  };
+
+  onNumberInputFocus = () => {
+    if (this.props.value) {
+      const deFormattedValue = ("" + this.props.value)
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/index.tsx:503]: use `String(this.props.value)`

File: app/client/src/widgets/InputWidget/component/utilities.ts [hunk 11]
```diff
@@ -7,3 +7,107 @@ export const countryToFlag = (isoCode: string) => {
...
+const getGroupSeparator = (locale: string) => {
+  const numberWithDecimalSeparator = 1000.1;
+  const formatter = new Intl.NumberFormat(locale);
+  return formatter
+    ?.formatToParts(numberWithDecimalSeparator)
+    ?.find((part) => part.type === "group")?.value;
+};
+
+export const getSeparators = () => {
+  const locale = navigator.languages?.[0] || "en-US";
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/utilities.ts:108]: Create a function to get the locale and use it in this and above functions.

File: app/client/src/widgets/InputWidget/component/utilities.ts [hunk 12]
```diff
@@ -7,3 +7,107 @@ export const countryToFlag = (isoCode: string) => {
...
+  eg: 
+  getDecimalSeparator("en-US") will return "."
+  getDecimalSeparator("fr-FR") will return "."
+*/
+const getDecimalSeparator = (locale: string) => {
+  const numberWithDecimalSeparator = 1.1;
+  const formatter = new Intl.NumberFormat(locale);
+  return formatter
+    ?.formatToParts(numberWithDecimalSeparator)
+    ?.find((part) => part.type === "decimal")?.value;
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/utilities.ts:90]: lets add a fallback value.

File: app/client/src/widgets/InputWidget/component/index.tsx [hunk 13]
```diff
@@ -309,11 +314,62 @@ class InputComponent extends React.Component<
...
+    const formattedValue = formatCurrencyNumber(
+      this.props.decimalsInCurrency,
+      "" + deFormattedValue,
+      this.decimalSeparator,
+    );
+    this.props.onValueChange(formattedValue);
+  };
+
+  onIncrementButtonClick = () => {
+    this.updateValueOnButtonClick(1);
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/index.tsx:366]: we need to call preventDefault. Clicking on blueprint numeric input buttons fires onValueChange handler. so we need to prevent that.

File: app/client/src/widgets/InputWidget/component/utilities.test.ts [hunk 14]
```diff
@@ -0,0 +1,31 @@
...
+describe("Limiting decimal Numbers ", () => {
+  it("Without Decimal", () => {
+    const response = limitDecimalValue(undefined, "1234560", ".", ",");
+    expect(response).toStrictEqual("1234560");
+  });
+  it("With Decimal more than the limit", () => {
+    const response = limitDecimalValue(2, "3456789.35444", ".", ",");
+    expect(response).toStrictEqual("3456789.35");
+  });
+});
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/utilities.test.ts:31]: Lets add tests for getGroupSeparator and getDecimalSeperator

**Review by sbalaji1192 — DISMISSED** [review]

File: app/client/src/widgets/InputWidget/widget/index.tsx [hunk 15]
```diff
@@ -694,8 +699,24 @@ class InputWidget extends BaseWidget<InputWidgetProps, WidgetState> {
     }
   };
 
+  getFormattedText = () => {
+    if (this.props.isFocused || this.props.inputType !== InputTypes.CURRENCY) {
+      return this.props.text ? this.props.text : "";
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/widget/index.tsx:704]: return `this.props.text || ""`

File: app/client/src/widgets/InputWidget/widget/index.tsx [hunk 16]
```diff
@@ -694,8 +699,24 @@ class InputWidget extends BaseWidget<InputWidgetProps, WidgetState> {
...
+    }
+    if (this.props.text === "") return "";
+    const valueToFormat = "" + this.props.text;
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/widget/index.tsx:707]: use String(this.props.text)

File: app/client/src/widgets/InputWidget/component/utilities.ts [hunk 17]
```diff
@@ -7,3 +7,113 @@ export const countryToFlag = (isoCode: string) => {
...
+  const missingFractDigitsCount =
+    fractionDigits - (value.length - currentIndexOfDecimal - 1);
+  if (missingFractDigitsCount > 0) {
+    valueToFormat =
+      value +
+      Array(missingFractDigitsCount)
+        .fill("0")
+        .join("");
+  }
+  const locale = navigator.languages?.[0] || "en-US";
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidget/component/utilities.ts:40]: use getLocale function

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Re-tested this feature and please find the status below,

Issue 1 - Fixed
Issue 2 - Fixed 
Issue 3 - **Reopen** - Random numbers are generated by choosing currency type and typing 1322222222222 or 143333333333 - with some repetitive numbers

https://loom.com/share/c8cab1e8d3884992a39ff2a4da32fcae

Issue 4 -Fixed 

Issue 5 - **Reopen** - Clicking on up and down in the currency type does not work - users needs to click on the input field each and every time to either reduce or add the numbers by clicking on up and down button 

https://www.loom.com/share/d2440fe0a3d7442c98b65af1209618a8

New issue:

Issue 6 - NaN is displayed in all the existing old apps which has input type set to currency 

https://www.loom.com/share/011589724a544c9290c8f0b2f9c26bd4

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Re-tested the fixes and please find the status below,

Issue 1 - **Fixed**
Issue 2 - **Fixed**
Issue 3 - **Reopen - Random numbers are generated by choosing currency type and typing 1322222222222 or 143333333333 - with some repetitive numbers**
https://loom.com/share/c8cab1e8d3884992a39ff2a4da32fcae

Issue 4 - **Fixed**
Issue 5 - **Fixed**
Issue 6 - **Fixed**


**New issue** 

Issue 7 - The decimal points are not visible on the widget after 17 digits. Also, it is observed that only on clicking on the widget the decimal points are visible

**Comment by vicky-primathon** [comment]
> @vicky-primathon Re-tested the fixes and please find the status below,
> 
> Issue 1 - **Fixed** Issue 2 - **Fixed** Issue 3 - **Reopen - Random numbers are generated by choosing currency type and typing 1322222222222 or 143333333333 - with some repetitive numbers** https://loom.com/share/c8cab1e8d3884992a39ff2a4da32fcae
> 
> Issue 4 - **Fixed** Issue 5 - **Fixed** Issue 6 - **Fixed**
> 
> **New issue**
> 
> Issue 7 - The decimal points are not visible on the widget after 17 digits. Also, it is observed that only on clicking on the widget the decimal points are visible

@YogeshJayaseelan regarding issue 3 & 7, maximum value for number type in JavaScript is 9007199254740991 (16 digits) 
Any value above that will have issues.

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon Verified this PR and please find the status below,

Issue 1 - Fixed
Issue 2 - Fixed
Issue 3 - Expected behaviour - Random numbers will be generated after 16 digits - because maximum value for number type in JavaScript is 9007199254740991 (16 digits)
Any value above that will have issues.

Issue 4 - Fixed
Issue 5 - Fixed
Issue 6 - Fixed
Issue 7 - Expected behaviour - maximum value for number type in JavaScript is 9007199254740991 (16 digits)

**Review by sbalaji1192 — APPROVED** [review]
LGTM
