### PR TITLE
fix: select widget accept string and object in the defaultOption property

### LINKED ISSUE #11074: [Bug][DX] Use both string and Object values for the default values in select and Multiselect widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is difficult to bind the default value in a select and multi-select widget when we need to provide both label and value.

### Steps To Reproduce

The default value property in the Select Widget.

### Environment

Production

### Version

Cloud

### LINKED ISSUE #11081: [Bug]: Select Widget does not clear after submit or reset but is actually empty
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Apologies if this is a dup. I did a search for "is:Bug select widget" and got 9+ pages of results. The select widget does not visually clear after submit or reset but the state does clear.

### Steps To Reproduce

Following the "Building a Store Catalog Manager" tutorial.
1. Using forms
2. Using a "Select" widget in place of the dropdown widget.
3. Complete the form and select something.
4. After submitting the form the dropdown widget does not visually clear/reset.
5. Fill out the form again but do not select anything just leave the select widget on what it was.
6. Submit the form.
7. Check the DB. You will see the first submit recorded data for the select but not the second.

### Environment

Deploy Preview

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

- Accept both string and object for defaultOption in MultiSelect and Select to improve existing DX
- Reset Select Widget onSubmit or onReset
- Add `value` property to be able to get Select value in a form widget

Fixes #11074
Fixes #11081 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update

## How Has This Been Tested?

- Unit test to check validate defaultOption
- Unit test for Evaluations 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/SelectV2-default-options-type 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.58 **(0.04)** | 37.06 **(0.06)** | 35.79 **(0.04)** | 55.91 **(0.04)**
 :green_circle: | app/client/src/entities/DataTree/dataTreeWidget.ts | 98.08 **(0)** | 83.33 **(8.33)** | 100 **(0)** | 97.83 **(0)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :green_circle: | app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx | 80.95 **(14.28)** | 53.06 **(53.06)** | 70.59 **(10.59)** | 81.01 **(13.36)**
 :green_circle: | app/client/src/widgets/SelectWidget/component/index.styled.tsx | 45.45 **(1.7)** | 21.88 **(0)** | 0 **(0)** | 50 **(1.72)**
 :green_circle: | app/client/src/widgets/SelectWidget/component/index.tsx | 27.78 **(2.78)** | 0 **(0)** | 6.67 **(-0.47)** | 27.27 **(1.87)**
 :green_circle: | app/client/src/widgets/SelectWidget/widget/index.tsx | 54.93 **(5.91)** | 22.22 **(22.22)** | 50 **(3.85)** | 55.88 **(4.82)**
 :green_circle: | app/client/src/workers/evaluationUtils.ts | 58.37 **(0)** | 57.14 **(0.53)** | 64.52 **(0)** | 57.7 **(0)**</details>

### CODE REVIEW

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 1]
```diff
@@ -12,6 +15,106 @@ import {
...
+    });
+
+    if (_valid) {
+      return {
+        isValid: true,
+        parsed: values,
+      };
+    }
+  }
+  return {
```
Comment (sbalaji1192) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:112]: This validation allows all object values.

File: app/client/src/widgets/SelectWidget/widget/index.tsx [hunk 2]
```diff
@@ -5,9 +5,87 @@ import { EventType } from "constants/AppsmithActionConstants/ActionConstants";
...
+  let values: Record<string, unknown> = {};
+  if (value === undefined || value === null) {
+    return {
+      isValid: false,
+      parsed: "",
+      messages: ["This value does not evaluate to type: string"],
+    };
+  }
+  // if JSON, parse data and Check if it's an Object
+  try {
```
Comment (sbalaji1192) [inline app/client/src/widgets/SelectWidget/widget/index.tsx:41]: need to check if its a string before JSON.parse

**Review by sbalaji1192 — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 3]
```diff
@@ -12,6 +15,115 @@ import {
 } from "rc-select/lib/interface/generator";
 import { Layers } from "constants/Layers";
 import { MinimumPopupRows, GRID_DENSITY_MIGRATION_V1 } from "widgets/constants";
+import { AutocompleteDataType } from "utils/autocomplete/TernServer";
+import _ from "lodash";
```
Comment (riodeuno) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:19]: Let us tree shake this import. We can potentially reduce the build size by making sure we tree shake where-ever possible. I realise that lodash is being used in the application where the root import is necessary. However, I think it will help us in the long run if we use this approach as a practice.

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 4]
```diff
@@ -12,6 +15,115 @@ import {
...
+      obj.hasOwnProperty("value") &&
+      _.isString(obj.label) &&
+      (_.isString(obj.value) || _.isFinite(obj.value))
+    );
+  };
+
+  /*
+   * Function to check for duplicate values in array
+   */
+  const hasUniqueValues = (arr: []) => {
```
Comment (riodeuno) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:46]: Two things I would suggest here:
1. We move this function out of this validation function and put it in workers/utils. Not sure if this will work, but we can try and see.
2. We don't need to do an `Array.from`. We can probably check this using `set.size < arr.length`

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 5]
```diff
@@ -12,6 +15,115 @@ import {
...
+    const uniqueValues = Array.from(new Set(arr));
+
+    return uniqueValues.length === arr.length;
+  };
+
+  /*
+   * When value is "['green', 'red']", "[{label: 'green', value: 'green'}]" and "green, red"
+   */
+  if (_.isString(value) && value !== "") {
```
Comment (riodeuno) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:55]: This will probably pass strings like `"   "` as `true`. Let's make sure to trim the value, and them check for length.

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 6]
```diff
@@ -12,6 +15,115 @@ import {
...
+      /*
+       * when value is "green, red", JSON.parse throws error
+       */
+      const splitByComma = (value as string).split(",") || [];
+
+      value = splitByComma.map((s) => s.trim());
+    }
+  }
+
+  if (value === "") {
```
Comment (riodeuno) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:71]: Do we want to trim here and check for this condition?

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx (hunk 4 above)
Comment (riodeuno) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:46]: Also, shall we type this as `arr: Array<string>`

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 7]
```diff
@@ -328,7 +421,13 @@ class MultiSelectWidget extends BaseWidget<
     const options = isArray(this.props.options) ? this.props.options : [];
     const dropDownWidth = MinimumPopupRows * this.props.parentColumnSpace;
     const { componentWidth } = this.getComponentDimensions();
-
+    const values = this.props.selectedOptions
+      ? this.props.selectedOptions.map((o) =>
+          _.isNil(o.value)
+            ? { laebl: o, value: o }
```
Comment (riodeuno) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:427]: There is a typo here. `label`. Let's fix this and see if there is any input we could have added to the test cases to have caught this.

File: app/client/src/widgets/SelectWidget/component/index.styled.tsx [hunk 8]
```diff
@@ -12,6 +12,7 @@ import {
   BlueprintCSSTransform,
   createGlobalStyle,
 } from "constants/DefaultTheme";
+import _ from "lodash";
```
Comment (riodeuno) [inline app/client/src/widgets/SelectWidget/component/index.styled.tsx:15]: Same suggestion as above regarding tree-shaking.

File: app/client/src/widgets/SelectWidget/widget/index.tsx [hunk 9]
```diff
@@ -300,6 +349,18 @@ class SelectWidget extends BaseWidget<SelectWidgetProps, WidgetState> {
   }
   componentDidUpdate(prevProps: SelectWidgetProps): void {
     // removing selectedOptionValue if defaultValueChanges
+    if (
```
Comment (riodeuno) [inline app/client/src/widgets/SelectWidget/widget/index.tsx:352]: Let's look at a solution in a separate PR for this:
I am curious if this can be caught in the `derviedProperty`? Instead of using componentDidUpdate and componentDidMount.

**Review by riodeuno — CHANGES_REQUESTED** [review]
A few notes and suggestions.

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx (hunk 6 above)
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:71]: We currently allow empty values,
Since the values are Unique, You can only have one option with an Empty string and most users use this as a placeholder

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx (hunk 7 above)
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:427]: I think just adding types to Values would have caught this

File: app/client/src/widgets/SelectWidget/widget/index.tsx (hunk 9 above)
Comment (Tooluloope) [reply app/client/src/widgets/SelectWidget/widget/index.tsx:352]: I'll add that to the list of task here
https://github.com/appsmithorg/appsmith/issues/10575

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx (hunk 6 above)
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:71]: We currently allow empty values,
Since the values are Unique, You can only have one option with an Empty string and most users use this as a placeholder

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx (hunk 4 above)
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:46]: Didn't work in utils.
is there any reason why you advise I put this in utils?

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.test.tsx [hunk 10]
```diff
@@ -0,0 +1,249 @@
...
+      defaultOptionValueValidation(input, {} as MultiSelectWidgetProps, _),
+    ).toEqual({
+      isValid: true,
+      parsed: ["green"],
+      messages: [""],
+    });
+  });
+
+  it("should get tested with simple string", () => {
+    const input = `{"green"`;
```
Comment (riodeuno) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.test.tsx:96]: I'm not sure if this is a typo or do we pass through any string values in default values? Or does this match one of the values in the options?

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx (hunk 4 above)
Comment (riodeuno) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx]: Yes, I believe as we're defining a function within another function -- so each time the parent function runs JS has to deal with defining the child function, this should come with a performance expense. 

If we can't move it out, it's ok, let's move on with this.

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.test.tsx (hunk 10 above)
Comment (sbalaji1192) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.test.tsx:96]: @riodeuno We pass string values in defaultValues, if there is no binding. This test case tests that invalid json strings don't throw error.

**Review by riodeuno — APPROVED** [review]
Looks good to me.

**Comment by riodeuno** [comment]
@sbalaji1192 @Tooluloope Although we have added jest tests to validate our updates to the validation function -- I can see that we've made a few updates to the components to handle certain values and use-cases. We should look into adding/updating cypress tests for these scenarios, if we don't already have them in place.

**Comment by sbalaji1192** [comment]
> @sbalaji1192 @Tooluloope Although we have added jest tests to validate our updates to the validation function -- I can see that we've made a few updates to the components to handle certain values and use-cases. We should look into adding/updating cypress tests for these scenarios, if we don't already have them in place.

+1

File: app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx [hunk 11]
```diff
@@ -12,6 +15,114 @@ import {
...
+    try {
+      /*
+       * when value is "['green', 'red']", "[{label: 'green', value: 'green'}]"
+       */
+      value = JSON.parse(value as string);
+    } catch (e) {
+      /*
+       * when value is "green, red", JSON.parse throws error
+       */
+      const splitByComma = (value as string).split(",") || [];
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:64]: @riodeuno @Tooluloope  Should this check be enough for checking if it is a `CSV`?
ex - If I pass the value `"['green', 'red]"`, (notice `red` does not have closing single quotes). It would go to the catch clause and the value would come out to be `["['green', "'red]"]`.
This would a mistake by the Appsmith developer (missing quotes) but we are not informing the developer and treating it as a CSV.

Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:64]: @ashit-rath, So when the user sees that in the Popup, they would be able to correct the value they inputted.

It's like having `'Green` in the PropertyPane for any width that accepts sting, it would still render as a string `"'Green". The developer can then correct  and add the extra quote

Comment (riodeuno) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:64]: @ashit-rath I see your point. Nice catch! @Tooluloope could you look into the logic here to catch this case?

Comment (sbalaji1192) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:64]: @riodeuno @ashit-rath There could be many such cases involving invalid JSON strings. For eg. the user forgetting to close the square bracket or curly bracket. Are we gonna cover that case as well? 
I guess as @Tooluloope  pointed out, the user can see the evaluated value popup and debug the issue. rather than us trying to catch all invalid cases and throw an error.

Comment (ashit-rath) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:64]: @sbalaji1192 You are right Balaji, we should have a limit as to how far we should validate. IMO we should only check for valid CSV.

Found this well-explained answer in [stack overflow](https://stackoverflow.com/questions/8493195/how-can-i-parse-a-csv-string-with-javascript-which-contains-comma-in-data). It does not fully comply with [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180#page-2) but is a good enough case for us.

Comment (ashit-rath) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:64]: BTW what was the original reason to have comma-separated strings? Are we trying to support values coming from google sheets?

Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:64]: We were supporting such values earlier when Select and Multiselect were 1 widget, and continue it support till now

Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx:64]: Also, the value you dropped in the First comment wasn't a CSV

File: app/client/src/widgets/SelectWidget/widget/index.tsx [hunk 12]
```diff
@@ -3,11 +3,83 @@ import BaseWidget, { WidgetProps, WidgetState } from "../../BaseWidget";
...
+  } else if (hasLabelValue(value)) {
+    /*
+     * When value is {label: "green", value: "green"}
+     */
+    isValid = true;
+    parsed = value;
+  } else {
+    isValid = false;
+    parsed = {};
+    message = `value does not evaluate to type: string | { "label": "label1", "value": "value1" }'`;
```
Comment (ashit-rath) [inline app/client/src/widgets/SelectWidget/widget/index.tsx:63]: @Tooluloope There is an extra `'` at the end of this line.

**Review by riodeuno — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@Tooluloope Object value is not working when I use sniping mode.
https://www.loom.com/share/6d5872d293fe43929beb1ee097dc5b67

**Comment by shwetha-ramesh** [comment]
@Tooluloope Co tested this PR with @YogeshJayaseelan. DP working fine for issues  #11081 & #11074. 
Moving to Done.
