### PR TITLE
fix: widget icon in debugger

### LINKED ISSUE #29144: CE [Task] Add Debugger Icon for Module Inputs

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

- Fix the widget icon in debugger 
- Makes the LogEntityLink component extendable 

#### PR fixes following issue(s)
Fixes #29144

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/ce/utils/getEntityPayloadInfo.ts [hunk 1]
```diff
@@ -14,14 +14,15 @@ export const getEntityPayloadInfo: Record<
   (entityConfig: EntityConfig) => {
     iconId: string;
     id: string;
-    pluginType?: PluginType;
+    pluginType?: PluginType | string;
```
Comment (ApekshaBhosale) [inline app/client/src/ce/utils/getEntityPayloadInfo.ts:17]: what is this for? @Rishabh-Rathod

**Review by ApekshaBhosale — CHANGES_REQUESTED** [review]

**Review by ApekshaBhosale — APPROVED** [review]
