### PR TITLE
fix: prevent cyclic dependency when switching to js mode

### LINKED ISSUE #14669: [Bug]: Cyclic Dependency Errors with Google sheets Form Controls
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A cyclic dependency error is shown when switching from Component mode to JSON mode for any Form control that contains dynamic bindings, This is due to the dynamic binding pathlist not being updated when we make a switch. This incorrect binding path list results in an issue with the evaluations flow.

### Steps To Reproduce

1. Go to new Google sheets.
2. Switch to Fetch many, populate the sheet url and sheet name
3. Go to the sorting component and add dynamic bindings within it e.g. {{""}}
4. Then switch to JSON mode
5. You'll observe a cyclic dependency error message being displayed.

### Public Sample App

_No response_

### Version

UQI branch version.

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

When translating diffs, if an array value changes to a string, all `MemberExpressions` of the array should be removed from the dependency map.

For example.

- Previous

```
ENTITY.options = [
{
label: "name",
value: {{name}}
},
{
label: "name",
value: {{name2}}
}
]
```

- Current (after switching to js mode)

```
ENTITY.options = "[
{
label: "name",
value: {{name}}
},
{
label: "name",
value: {{name2}}
}
]"
```

ENTITY.options[0] and ENTITY.options[1] (and their child nodes eg, ENTITY.options[0].value) should be removed from the dependencyMap

Fixes #14669 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Jest

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ApekshaBhosale — COMMENTED** [review]
won't this create a problem in the case where we are trying to add a dependency for Api1.data[0]? just wondering @ohansFavour

File: app/client/src/workers/evaluationUtils.ts [hunk 1]
```diff
@@ -182,11 +182,41 @@ export const translateDiffEventToDataTreeDiffEvent = (
...
+              propertyPath,
+              value: difference.rhs,
+            },
+          },
+        ];
+        /**
+         * If lhs is an array/object
+         * Add delete events for all memberExpressions
+         */
+        if (Array.isArray(difference.lhs)) {
```
Comment (ohansFavour) [inline app/client/src/workers/evaluationUtils.ts:198]: @ApekshaBhosale, here if the left-hand side is an array/object definitely, the rhs is a string (because of the check in line 184)

**Review by ApekshaBhosale — APPROVED** [review]

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM, Let's create a task to ideally detect such changes using `dynamicBindingPathList` as discussed.

**Review by ApekshaBhosale — APPROVED** [review]
