### PR TITLE
fix: Autocompletion issues

### LINKED ISSUE #2174: [Enhancement] Autocomplete should work with local variables
## Summary

In JS, when we create new objects which are references to data within entities. Autocomplete does not work.

https://media.discordapp.net/attachments/760761686549463060/787294091758272591/autocompleteNotShowing.gif

Additional information 
- Demo of codemirror and tern supporting local variable autocomplete https://codemirror.net/5/demo/tern.html
Code - https://github.com/codemirror/codemirror5/blob/master/demo/tern.html

### LINKED ISSUE #9692: [Bug] Autocomplete doesn't work to access this object inside JSObjects
`this.` currently shows un-necessary autocomplete suggestions.

image

This needs to be changed so it lists variables and functions within the current object only.

Note: 
`this` keyword ideally would work with just functions `function() {}` within an object. Not arrow functions `() => {}`.
It is currently handled by appsmith, so it works with arrow functions too.

### LINKED ISSUE #11310: [Bug]: filter un-necessary global autocomplete items
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

e.g. latLong, dropdownOption, chartData etc...

image

### Steps To Reproduce

1. Open a JS binding {{}}
2. type `latLong`, `chartData` etc...
3. These are not entities that should be listed as suggestions.

They are internal types used within widgets. And should be filtered.

### Environment

Production

### Version

Cloud

### LINKED ISSUE #12188: [Bug]-[360]:No Autocompletion hints for ButtonGroup widgets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I don't get autocompletion hints for ButtonGroup widgets present on the canvas.

### Steps To Reproduce

1. Drag a `Buttongroup` widget to the canvas
2. Drag an input  widget to the canvas
3. Try to bind a property of the buttongroup widget to the input widget
4.  You don't get any suggestions

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #12730: [Task]: Remove eval from autocomplete menu.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We throw an error when a user tries to use `eval`. We should remove this from the autocomplete menu, too.

- [ ] Remove `eval` from the autocomplete menu.

image

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Fixes #9692
Fixes #2174
Fixes #12730
Fixes #12188
Fixes #11310

## Type of change

- Bug fix (non-breaking change which fixes an issue)

#### Cypress test

- [x] [JSObject `this.` showing autocomplete suggestions for variables and functions](https://github.com/appsmithorg/TestSmith/issues/1998)
- [x] Local variable autocomplete suggestion
- [x] No eval autocomplete suggestion
- [x] ButtonGroup widget autocomplete suggestion
- [ ]  https://github.com/appsmithorg/TestSmith/issues/1982

#### Jest test
- [x] Add tests for `getFunctionsArgsType`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts [hunk 1]
```diff
@@ -28,12 +31,27 @@ export const bindingHint: HintHelper = (editor, dataTree, customDataTree) => {
...
+        // If focused/modified JSEditor has changed
+        if (dataTreeForAutoComplete && entityInformation.entityName) {
+          const JSObject = getJSObjectProperty({
+            dataTreeForAutoComplete,
+            JSObjectName: entityInformation.entityName,
+          });
+          const JSObjectFocusedDef = generateTypeDef(JSObject) as Def;
+
+          TernServer.updateDef("JSOBJECT_GLOBAL", JSObjectFocusedDef);
+        }
```
Comment (Rishabh-Rathod) [inline app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts:54]: `updateDef` on every character is very bad for performance. 
- [ ] Do it only when JSEditor is in focused
- [ ] Once added as def we don't need to modify it until JSObject property is modified.
- [ ] Add arguments support for JS functions

File: app/client/src/components/editorComponents/CodeEditor/index.tsx [hunk 2]
```diff
@@ -636,6 +640,7 @@ class CodeEditor extends Component<Props, State> {
     let hinterOpen = false;
     for (let i = 0; i < this.hinters.length; i++) {
       hinterOpen = this.hinters[i].showHint(cm, entityInformation, {
+        dataTreeForAutoComplete: this.props.dynamicData,
```
Comment (Rishabh-Rathod) [inline app/client/src/components/editorComponents/CodeEditor/index.tsx:643]: Explore possibility of moving `dynamicData` out of codeEditor to avoid re-rendering on evaluated value change and instead direct update hinters.

File: app/client/src/components/editorComponents/CodeEditor/utils.ts [hunk 3]
```diff
@@ -0,0 +1,30 @@
+import { DataTree } from "entities/DataTree/dataTreeFactory";
+import { EVALUATION_PATH } from "utils/DynamicBindingUtils";
+import { isJSAction } from "workers/evaluationUtils";
+
+export const getJSObjectProperty = ({
```
Comment (Rishabh-Rathod) [inline app/client/src/components/editorComponents/CodeEditor/utils.ts:5]: Move this function into any other file.

File: app/client/src/selectors/dataTreeSelectors.ts [hunk 4]
```diff
@@ -71,6 +72,7 @@ export const getDataTreeForAutocomplete = createSelector(
   getActionsForCurrentPage,
   getJSCollectionsForCurrentPage,
   (tree: DataTree, actions: ActionDataState) => {
+    const dataTreeWithoutPrivateWidget = getDataTreeWithoutPrivateWidgets(tree);
```
Comment (Rishabh-Rathod) [inline app/client/src/selectors/dataTreeSelectors.ts:75]: As `cachedResponses` are not used either complete the implementation or create an issue for it if not already present.

**Review by Rishabh-Rathod — COMMENTED** [review]
Initial review

File: app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts [hunk 5]
```diff
@@ -28,12 +31,27 @@ export const bindingHint: HintHelper = (editor, dataTree, customDataTree) => {
...
+
+        // If focused/modified JSEditor has changed
+        if (dataTreeForAutoComplete && entityInformation.entityName) {
+          const JSObject = getJSObjectProperty({
+            dataTreeForAutoComplete,
+            JSObjectName: entityInformation.entityName,
+          });
+          const JSObjectFocusedDef = generateTypeDef(JSObject) as Def;
+
+          TernServer.updateDef("JSOBJECT_GLOBAL", JSObjectFocusedDef);
```
Comment (arunvjn) [inline app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts]: I don't think we need these line. Tern server does this out of the box. Can you tweak the TernServer class to get the behaviour right ?

Comment (Rishabh-Rathod) [reply app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts]: Can you please check if you are looking at older commits in review. This code is already removed.

File: app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts [hunk 6]
```diff
@@ -62,20 +60,20 @@ export const dataTreeTypeDefCreator = (
...
     } else if (isJSAction(entity) && isJSEditorEnabled) {
-      const metaObj: Record<string, MetaArgs> = entity.meta;
-      const jsOptions: Record<string, unknown> = {};
+      const metaObj = entity.meta;
+      const jsProperty: Def = {};
       for (const key in metaObj) {
-        jsOptions[key] =
+        jsProperty[key] =
           "fn(onSuccess: fn() -> void, onError: fn() -> void) -> void";
       }
```
Comment (Rishabh-Rathod) [inline app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts:68]: Fix JSObject function type definition.

File: app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts [hunk 7]
```diff
@@ -62,20 +60,20 @@ export const dataTreeTypeDefCreator = (
...
 
       for (let i = 0; i < entity.variables.length; i++) {
         const varKey = entity.variables[i];
         const varValue = entity[varKey];
-        jsOptions[varKey] = generateTypeDef(varValue);
+        jsProperty[varKey] = generateTypeDef(varValue);
```
Comment (Rishabh-Rathod) [inline app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts:73]: verify variable typeDef as we have issue for it. https://github.com/appsmithorg/appsmith/issues/14989

**Review by Rishabh-Rathod — COMMENTED** [review]
Next tasks

File: app/client/src/components/editorComponents/CodeEditor/index.tsx (hunk 2 above)
Comment (Rishabh-Rathod) [reply app/client/src/components/editorComponents/CodeEditor/index.tsx:630]: there is already a performance issue for this hence closing it here.

File: app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts (hunk 6 above)
Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts]: done

File: app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts (hunk 7 above)
Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts:78]: Variables are not getting updates in dataTree. Need to fix this issue separately. 
A potential PR to fix it https://github.com/appsmithorg/appsmith/pull/15111

File: app/client/src/components/editorComponents/CodeEditor/index.tsx [hunk 8]
```diff
@@ -651,10 +642,11 @@ class CodeEditor extends Component<Props, State> {
 
   handleAutocompleteVisibility = (cm: CodeMirror.Editor) => {
     if (!this.state.isFocused) return;
-    const entityInformation: FieldEntityInformation = this.getEntityInformation();
+    const entityInformation = this.getEntityInformation();
     let hinterOpen = false;
     for (let i = 0; i < this.hinters.length; i++) {
       hinterOpen = this.hinters[i].showHint(cm, entityInformation, {
+        dataTreeForAutoComplete: this.props.dynamicData,
```
Comment (Rishabh-Rathod) [inline app/client/src/components/editorComponents/CodeEditor/index.tsx:649]: remove this `dataTreeForAutoComplete: this.props.dynamicData,` as it is not required anymore

File: app/client/src/components/propertyControls/PrimaryColumnsControlV2.tsx [hunk 9]
```diff
@@ -541,7 +541,7 @@ class EvaluatedValuePopupWrapperClass extends Component<
   };
 }
 const mapStateToProps = (state: AppState): ReduxStateProps => ({
-  dynamicData: getDataTreeForAutocomplete(state),
+  dynamicData: getDataTree(state),
```
Comment (Rishabh-Rathod) [inline app/client/src/components/propertyControls/PrimaryColumnsControlV2.tsx:544]: seems like this has performance implications, please check once.

File: app/client/src/selectors/dataTreeSelectors.ts [hunk 10]
```diff
@@ -86,6 +88,6 @@ export const getDataTreeForAutocomplete = createSelector(
         }
       });
     }
-    return tree;
+    return dataTreeWithoutPrivateWidget;
```
Comment (Rishabh-Rathod) [inline app/client/src/selectors/dataTreeSelectors.ts:91]: Undo this change until not required to fix issue and add comment.

File: app/client/src/utils/autocomplete/EntityDefinitions.ts [hunk 11]
```diff
@@ -264,6 +278,23 @@ export const entityDefinitions = {
     isDisabled: "bool",
     recaptchaToken: "string",
   },
+  BUTTON_GROUP_WIDGET: (widget: ButtonGroupWidgetProps) => {
+    const groupButtons: Record<string, PartialGroupButton> = {};
+    Object.entries(widget.groupButtons).forEach(([buttonLabel, button]) => {
```
Comment (Rishabh-Rathod) [inline app/client/src/utils/autocomplete/EntityDefinitions.ts:283]: As only 1st option matters for type generation, avoid going through all `groupButtons`

File: app/client/src/components/editorComponents/CodeEditor/index.tsx (hunk 8 above)
Comment (Rishabh-Rathod) [reply app/client/src/components/editorComponents/CodeEditor/index.tsx]: removed.

File: app/client/src/components/propertyControls/PrimaryColumnsControlV2.tsx (hunk 9 above)
Comment (Rishabh-Rathod) [reply app/client/src/components/propertyControls/PrimaryColumnsControlV2.tsx:544]: As `getDataTreeForAutocomplete` internally used `getDataTree` it shouldn't have any performance issues

File: app/client/src/utils/autocomplete/EntityDefinitions.ts (hunk 11 above)
Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/EntityDefinitions.ts]: removed logic to pick few keys from object and let it show all the fields.

File: app/client/src/selectors/dataTreeSelectors.ts (hunk 10 above)
Comment (Rishabh-Rathod) [reply app/client/src/selectors/dataTreeSelectors.ts]: undone

File: app/client/src/workers/DataTreeEvaluator/index.ts [hunk 12]
```diff
@@ -803,11 +804,16 @@ export default class DataTreeEvaluator {
 
       let entityType = "UNKNOWN";
       const entityName = node.split(".")[0];
-      const entity = _.get(this.oldUnEvalTree, entityName);
+      const entity = _.get(
+        this.oldUnEvalTree,
+        entityName,
+      ) as DataTreeObjectEntity;
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/DataTreeEvaluator/index.ts:810]: remove `DataTreeObjectEntity` as type here

Comment (Rishabh-Rathod) [reply app/client/src/workers/DataTreeEvaluator/index.ts]: done

File: app/client/src/selectors/dataTreeSelectors.ts (hunk 4 above)
Comment (Rishabh-Rathod) [reply app/client/src/selectors/dataTreeSelectors.ts]: left it untouched for now.

File: app/client/src/utils/autocomplete/EntityDefinitions.ts [hunk 13]
```diff
@@ -346,26 +358,35 @@ export const entityDefinitions = {
     isDisabled: "bool",
     recaptchaToken: "string",
   },
-  MAP_WIDGET: {
+  MAP_WIDGET: () => ({
```
Comment (arunvjn) [inline app/client/src/utils/autocomplete/EntityDefinitions.ts:361]: The config looks static. Does it have to be a function ?

Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/EntityDefinitions.ts:361]: Forgot to change it back. Thanks for catching this. I will change it back.

File: app/client/src/utils/autocomplete/TernServer.ts [hunk 14]
```diff
@@ -538,67 +545,40 @@ class TernServer {
...
-      inLiteral?: boolean;
-    },
+    query: Partial<RequestQuery>,
     pos?: CodeMirror.Position,
   ) {
     const files = [];
     let offsetLines = 0;
     const allowFragments = !query.fullDocs;
     if (!allowFragments) delete query.fullDocs;
+    if (typeof query == "string") query = { type: query };
```
Comment (arunvjn) [inline app/client/src/utils/autocomplete/TernServer.ts:555]: When will this condition be true since there is no overlap between Partial<RequestQuery> and string ?

File: app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts [hunk 15]
```diff
@@ -62,20 +61,27 @@ export const dataTreeTypeDefCreator = (
...
       for (const key in metaObj) {
-        jsOptions[key] =
-          "fn(onSuccess: fn() -> void, onError: fn() -> void) -> void";
+        // const jsFunctionObj = metaObj[key];
+        // const { arguments: args } = jsFunctionObj;
+        // const argsTypeString = getFunctionsArgsType(args);
+        // As we don't show args we avoid to get args def of function
+        // we will also need to check performance implications here
+
+        const argsTypeString = getFunctionsArgsType([]);
```
Comment (arunvjn) [inline app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts:74]: Shouldn't we be passing argument names here ?

File: app/client/src/utils/autocomplete/TernServer.ts (hunk 14 above)
Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/TernServer.ts:555]: I am not sure about the cases when `query` could be a string. This changes in `buildRequest` is inspired  from  https://github.com/codemirror/codemirror5/blob/master/addon/tern/tern.js#L510

File: app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts (hunk 15 above)
Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts:74]: Currently we haven't added `showArgsHints` in TernServer. 
reference code : https://github.com/codemirror/codemirror5/blob/master/addon/tern/tern.js#L318

- Without `showArgsHints` determining the function definition with args is not useful.
- JSObject on argument modification doesn’t reflect the changes in the dataTree which means only on refresh we will see latest args definition. 
As fixing both of above issues were out of scope for current PR hence i went ahead with only implementing what all will be needed for args definition generation.

**Review by arunvjn — DISMISSED** [review]

File: app/client/src/utils/autocomplete/TernServer.ts (hunk 14 above)
Comment (Rishabh-Rathod) [reply app/client/src/utils/autocomplete/TernServer.ts]: Added type as string to `query`

**Review by arunvjn — APPROVED** [review]

**Review by arunvjn — DISMISSED** [review]
LGTM!

**Comment by ramsaptami** [comment]
- [ ] Button group widget autocomplete issues
- New buttons don't show the correct name
- When a button is deleted, the binding does not show an error
- Autocomplete completely covers up the code
- When a button is deleted and user tries to amend then we see a momentary tern message
https://www.loom.com/share/afbdca0b7f664967a74088ec920975fa

**Comment by Rishabh-Rathod** [comment]
> * [ ]  Button group widget autocomplete issues
> * New buttons added don't show the correct name
> * When a button is deleted and since the autocomplete shows indexed button names, (`groupButtton1`, `groupButton2`....) the index does not change if `groupButton2` is deleted

Above issue is being addressed here https://github.com/appsmithorg/appsmith/pull/15490 we have similar issue with table widget column name updation.

> * When a button is deleted, the binding does not show an error

Seems like a linting issue.


> * Autocomplete completely covers up the code

This might be happening for other cases too. We could create a separate issue for this.

> * When a button is deleted and user tries to amend then we see a momentary tern message

Could you please share more details for this.

**Comment by ramsaptami** [comment]
@Rishabh-Rathod The video attached in my previous comment shows tern message seen about 5 seconds before the video ends

**Review by arunvjn — APPROVED** [review]

**Review by ramsaptami — DISMISSED** [review]

**Comment by ramsaptami** [comment]
Edge case where `this.` suggests own function
image

**Review by Aishwarya-U-R — APPROVED** [review]
Approving PR as it was already reviewed and approved.
