### PR TITLE
fix: App crashes when a modal has a filepicker?

### LINKED ISSUE #10283: [Bug] App crashes when a modal has a filepicker?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
Reported by A-Cityzen#3550 on discord.

The user added a filepicker - which calls a multipart POST api - into a modal. The modal crashes the application on `showModal`
Logs from the crash:

Screenshot 2022-01-10 at 5 41 49 PM
.

### Steps To Reproduce

Not clear at the moment. We can attempt to do the following

- Create a multipart POST API
- Create a modal
- Add a file picker into the modal, and configure it to call the multipart POST API.
- We can further try selecting a video/PDF/Excel to try and recreate this issue.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by jsartisan**
## Description
- Due to our recent changes, filepicker started crashing on the self-hosted instances that don't have an SSL certificate. The filepicker was making a call to a function (due to webam plugin of @uppy) `enumerateDevice` that is only available on websites that has an SSL certificate. 
- This PR adds a try-catch and only adds the webcam plugin of @uppy only when the site is loaded over https.

Fixes #10283 

## Type of change
- Bug fix 

## How Has This Been Tested?
- Manully tested

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/http-issue-with-filepicker-v1 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**
 :red_circle: | app/client/src/widgets/FilepickerWidget/widget/index.tsx | 37.36 **(-1.01)** | 0 **(0)** | 21.43 **(0)** | 36.67 **(-0.98)**</details>

### CODE REVIEW

File: app/client/src/widgets/FilepickerWidget/widget/index.tsx [hunk 1]
```diff
@@ -440,7 +444,11 @@ class FilePickerWidget extends BaseWidget<
   }
 
   componentDidMount() {
-    this.initializeUppyEventListeners();
+    try {
+      this.initializeUppyEventListeners();
+    } catch (e) {
+      log.debug("Error in initializing uppy");
```
Comment (somangshu) [inline app/client/src/widgets/FilepickerWidget/widget/index.tsx:450]: Would this be helpful logging? if not we could probably remove.

**Review by somangshu — APPROVED** [review]
Change LGTM

File: app/client/src/widgets/FilepickerWidget/widget/index.tsx (hunk 1 above)
Comment (jsartisan) [reply app/client/src/widgets/FilepickerWidget/widget/index.tsx:450]: Shri asked me to add it. may be required for debugging.

**Comment by somangshu** [comment]
@jsartisan please take a call if we need to unfreeze and merge this in

**Comment by jsartisan** [comment]
@somangshu Unfreezing this PR. Also, not passing this PR to QA as it's hard to qa this because it only happens on instances with SSL certificate.

**Comment by somangshu** [comment]
@jsartisan just one thing, we should inform QA just so that they are aware

**Comment by jsartisan** [comment]
Yes. Yatin knows about it.
