### PR TITLE
fix: Reskinning Radio + Toggle + Checkbox

### LINKED ISSUE #10975: [Enhancement] : Checkbox widget reskinning
https://www.notion.so/appsmith/Checkbox-b8a235faf3b74fa2aff59f68cafc0c05

### LINKED ISSUE #10985: [Enhancement]: Radio group reskinning
https://www.notion.so/appsmith/Radio-group-a82e799a8e254bf9a2ed16704c484d1b

### LINKED ISSUE #10987: [Enhancement]: Switch reskinning
https://www.notion.so/appsmith/Switch-51f47213ed53455eb4fe035b64b5dc0b

### LINKED ISSUE #11022: [Enhancement] : Switch group widget reskinning
https://www.notion.so/appsmith/Switch-group-39b21f09ed2042e5955194d42b46866a

### LINKED ISSUE #11027: [Enhancement] : Checkbox group widget reskinning
https://www.notion.so/appsmith/Checkbox-group-659541492f7d47bb9e2a0e6e46361580

### PR DESCRIPTION
**Pull request by jsartisan**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes #11027
Fixes #10975
Fixes #11022
Fixes #10987
Fixes #10985

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/ads/LabelWithTooltip.tsx [hunk 1]
```diff
@@ -97,7 +97,7 @@ export const labelLayoutStyles = css<{
 
   align-items: ${({ compactMode, labelPosition }) => {
     if (labelPosition === LabelPosition.Top) return "flex-start";
-    if (compactMode || labelPosition === LabelPosition.Left) return "center";
```
Comment (keyurparalkar) [inline app/client/src/components/ads/LabelWithTooltip.tsx:100]: Why are we removing this condition?

File: app/client/src/components/wds/Checkbox/index.tsx [hunk 2]
```diff
@@ -1,115 +1,143 @@
...
-      background: ${Colors.GREY_5} !important;
-      color: ${Colors.GREY_8};
-
-      &::before {
-        background-image: url("${DISABLED_ICON_SVG}") !important;
-      }
+    // hover on checked
+    &.bp3-control.bp3-checkbox:hover input:checked ~ .bp3-control-indicator,  &.bp3-control.bp3-checkbox:hover input:indeterminate ~ .bp3-control-indicator {
+      box-shadow: none;
+      background: ${darkenColor(accentColor)} !important;
```
Comment (keyurparalkar) [inline app/client/src/components/wds/Checkbox/index.tsx:69]: Can we use css variable for accentColor?

File: app/client/src/components/wds/Checkbox/index.tsx [hunk 3]
```diff
@@ -1,115 +1,143 @@
...
+      box-shadow: 0px 0px 0px 1px var(--wds-color-border-disabled);
+      background-color: var(--wds-color-disabled) !important;
     }
 
-    // HOVER WHEN CHECKED
-    &.bp3-control.bp3-checkbox:hover input:checked ~ .bp3-control-indicator {
+    // checked
+    &.bp3-control.bp3-checkbox input:checked ~ .bp3-control-indicator,
+    &.bp3-control.bp3-checkbox input:indeterminate ~ .bp3-control-indicator {
+      background-color: ${accentColor} !important;
```
Comment (keyurparalkar) [inline app/client/src/components/wds/Checkbox/index.tsx:86]: Can we make use of css variable here?

File: app/client/src/components/wds/Checkbox/index.tsx [hunk 4]
```diff
@@ -1,115 +1,143 @@
...
+    }
+
+    // blueprint specific issues
     &.bp3-control:not(.bp3-align-right) {
       padding-left: 0;
     }
+
+    // checked + disabled icon
+    &.bp3-control.bp3-checkbox input:checked:disabled ~ .bp3-control-indicator::before {
+      background-image: url(/widgets/disabledcheck-icon.svg);
```
Comment (keyurparalkar) [inline app/client/src/components/wds/Checkbox/index.tsx:123]: Can we import this svg as an ES import rather than hard coding it here in css?

Can we do this for all the below imports?

File: app/client/src/theme/wds.css [hunk 5]
```diff
@@ -0,0 +1,18 @@
+:root {
```
Comment (keyurparalkar) [inline app/client/src/theme/wds.css:1]: Is is possible to use the approach in this PR for storing css variables?  https://github.com/appsmithorg/appsmith/pull/15183/files#diff-2d7db458ec9c671d341dd63f05054a41201d03e5ff582d174e74d81ae922362d

File: app/client/src/widgets/SwitchWidget/component/index.tsx [hunk 6]
```diff
@@ -66,6 +67,13 @@ export const StyledSwitch = styled(Switch)<{
       background: ${({ accentColor }) => `${accentColor}`} !important;
       border: 1px solid ${({ accentColor }) => `${accentColor}`} !important;
     }
+
+    &:hover input:checked:not(:disabled) ~ .bp3-control-indicator {
+      background: ${({ accentColor }) =>
+        `${darkenColor(accentColor)}`} !important;
```
Comment (keyurparalkar) [inline app/client/src/widgets/SwitchWidget/component/index.tsx:73]: Can we use css variable for accentColor?

**Review by keyurparalkar — CHANGES_REQUESTED** [review]

File: app/client/src/theme/wds.css (hunk 5 above)
Comment (jsartisan) [reply app/client/src/theme/wds.css:1]: These are CSS variables that will be used by every widget. So these ones will be static. So using static CSS file is better here.

File: app/client/src/components/wds/Checkbox/index.tsx (hunk 4 above)
Comment (jsartisan) [reply app/client/src/components/wds/Checkbox/index.tsx:123]: Actually, we can't because es import will convert it into react component and we don't want react component here.

File: app/client/src/widgets/SwitchWidget/component/index.tsx (hunk 6 above)
Comment (jsartisan) [reply app/client/src/widgets/SwitchWidget/component/index.tsx:73]: We can use it but it won't benefit us much right now. I was using CSS variables at other places because the variables were the same. But here variables value needs to change according to props. I can send the variables with props like you did for filepicker but it won't help us much because we are anyway using styled-components that will take care of these dynamic styles.
Check out this file - I will be exactly what you suggested with wds - https://github.com/appsmithorg/appsmith/blob/wds/checkbox/app/client/src/components/wds/Checkbox/styles.module.css

File: app/client/src/components/wds/Checkbox/index.tsx (hunk 3 above)
Comment (jsartisan) [reply app/client/src/components/wds/Checkbox/index.tsx:86]: Replied below.

File: app/client/src/components/wds/Checkbox/index.tsx (hunk 2 above)
Comment (jsartisan) [reply app/client/src/components/wds/Checkbox/index.tsx:69]: Replied below.

File: app/client/src/components/ads/LabelWithTooltip.tsx (hunk 1 above)
Comment (jsartisan) [reply app/client/src/components/ads/LabelWithTooltip.tsx:100]: Yes. This is something we changed with reskinning. We want label to be shown at flex-start when the label is on left.

**Review by keyurparalkar — APPROVED** [review]
LGTM!

**Comment by chandannkumar** [comment]
Tested this PR for:
- Switch widget reskinning
- Switch Group widget reskinning
- Radio Group reskinning
- Checkbox widget reskinning
- Checkbox Group widget reskinning

All reskinning widgets here are working as expected

**Review by keyurparalkar — APPROVED** [review]
LGTM!

File: app/client/src/widgets/SwitchGroupWidget/index.ts [hunk 7]
```diff
@@ -11,7 +11,7 @@ export const CONFIG = {
   isCanvas: false, // Defines if this widget has a canvas within in which we can drop other widgets
   defaults: {
     widgetName: "SwitchGroup",
-    rows: 6,
+    rows: 4,
```
Comment (keyurparalkar) [inline app/client/src/widgets/SwitchGroupWidget/index.ts:14]: @jsartisan Wouldn't changing this value cause UI inconsistencies between the existing users?

Comment (jsartisan) [reply app/client/src/widgets/SwitchGroupWidget/index.ts:14]: 6 rows were not actually required for default drop. so changed it according to what we needed.
