### PR TITLE
fix: fixed the default value of zero not present in parent form data on pageload

### LINKED ISSUE #9117: [Bug]: Number input with default value as 0 not showing up in parent form data on pageload
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An input widget set to the Number type and with a Default text of 0 is not included in Form1.data on page load. You have to change its value to include it. This also happens if the Default is changed back to 0 by setting it from a store value.

### Steps To Reproduce

1. Add a form to canvas
2. Add a Number input  to form
3. Set default value to 0.
4. Observe that form.data doesn't have this value on pageload.
5. Change the input value.
6. observe that form.data now has this value

Additional context: 
Issue is result of L51 from `Forwidget/widget/index.tsx` file. `widgetData.value` evaluates to false when value is 0. Should use _.isNill function.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
This PR includes the following changes:
* Addition of `isNil` function from lodash in the import statement
* Changed the condition to use `isNil` function to check for `null` or `undefined` values in the widget.

Fixes #9117 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

* Cypress test cases are already present for checking the default value to 0 for input with number type. 
* Manually tested, by creating a text field with value as `{{Form1.data}}` and checking the value of input appearing in this textfield.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Comment by sbalaji1192** [comment]
@keyurparalkar Could you have this tested by QA once?

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by keyurparalkar** [comment]
> @keyurparalkar Could you have this tested by QA once?

Sure @sbalaji1192 will have this tested with QA.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_With_Input_Number.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+    cy.get(widgetsPage.formButtonWidget)
+      .contains("Submit")
+      .click();
+
+    //Check if on submission if the notifition toast appears with text containing input1: 0
+    cy.get(widgetsPage.toastActionText)
+      .last()
+      .invoke("text")
+      .then((text) => {
+        const someText = text;
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_With_Input_Number.js:29]: do we need this proxy variable?

Comment (keyurparalkar) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_With_Input_Number.js:29]: Let me change it. So that we can directly consume the `text` variable

Comment (keyurparalkar) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_With_Input_Number.js]: Added the changes

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_With_Input_Number.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+      .contains("Submit")
+      .scrollIntoView()
+      .should("be.visible");
+
+    //Do Submission
+    cy.get(widgetsPage.formButtonWidget)
+      .contains("Submit")
+      .click();
+
+    //Check if on submission if the notifition toast appears with text containing input1: 0
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_With_Input_Number.js:24]: typo - `notification`

**Review by sbalaji1192 — APPROVED** [review]
LGTM

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_With_Input_Number.js (hunk 2 above)
Comment (keyurparalkar) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_With_Input_Number.js]: Typo fixed.

**Comment by vivekverma2312** [comment]
@keyurparalkar Tested on deploy preview and it's working fine.

**Review by sbalaji1192 — APPROVED** [review]
LGTM
