### PR TITLE
fix: Upgrade map widget library to support react 17

### LINKED ISSUE #16946: Upgrade map widget library to support react 17
map widget library react-google-maps doesn't seem to support react 17 its SearchBox widget that we use fails to render in react 17, the library last gave an update for react 16 for the [same problem](https://github.com/tomchentw/react-google-maps/pull/680). its best if we ditch this library and use a new one its 5 years old and is not active.

_Originally posted by @marks0351 in https://github.com/appsmithorg/appsmith/issues/16257#issuecomment-1236882805_

### PR DESCRIPTION
**Pull request by jsartisan**
This PR:
 - updates the react 16 to react 17
 - replaces the underlying library for the map widget
 - adds clustering of markers
 - refactor code for map widget's component
 
## Description

Fixes #16946

## Type of change
- Breaking change

## How Has This Been Tested?
- Manually

### Test Plan
https://github.com/appsmithorg/TestSmith/issues/2149

### Issues raised during DP testing
1. https://github.com/appsmithorg/appsmith/pull/19315#issuecomment-1378495845

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/MapWidget/component/Map.tsx [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+          return React.cloneElement(child as React.ReactElement<any>, {
+            map,
+          });
+        }
+      })}
+    </Wrapper>
+  );
+};
+
+Map.PickMyLocation = PickMyLocation;
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Map.tsx:125]: Nice use of compound component pattern!

File: app/client/src/widgets/MapWidget/component/Map.tsx [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+   * on click map, add marker
+   *
+   * @param e
+   * @returns
+   */
+  const onClickOnMap = (e: google.maps.MapMouseEvent) => {
+    if (!enableCreateMarker || !saveMarker) return;
+
+    // create marker
+    saveMarker(Number(e.latLng?.lat()), Number(e.latLng?.lng()));
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Map.tsx:90]: Wouldn't this `Number(e.latLng?.lat())` would be `NaN` when `e.latLng` is undefined. Maybe in such scenario  we should not execute `saveMarker`

File: app/client/src/widgets/MapWidget/component/Map.tsx [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+
+  return (
+    <Wrapper>
+      <StyledMap
+        borderRadius={borderRadius}
+        boxShadow={boxShadow}
+        id="map"
+        ref={mapRef}
+      />
+      <Clusterer map={map} markers={markers} {...rest} />
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Map.tsx:113]: Do we require the clustering feature in this PR?

File: app/client/src/widgets/MapWidget/component/Map.tsx [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+      {React.Children.map(children, (child) => {
+        if (React.isValidElement(child)) {
+          return React.cloneElement(child as React.ReactElement<any>, {
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Map.tsx:116]: Are we using `cloneElement` to pass down `map` object to all children?

File: app/client/src/widgets/MapWidget/component/SearchBox.tsx [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+const SearchBox = (props: SearchBoxProps) => {
+  const { isEnabled, updateCenter } = props;
+  const searchBoxRef = useRef<HTMLInputElement>(null);
+  const searchBoxObjRef = useRef<google.maps.places.SearchBox>();
+
+  // initialize search box
+  useEffect(() => {
+    if (!searchBoxRef.current) return;
+
+    searchBoxObjRef.current = new window.google.maps.places.SearchBox(
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/SearchBox.tsx:41]: We should check that `window` has `google` and `map` object

File: app/client/src/widgets/MapWidget/widget/index.tsx [hunk 6]
```diff
@@ -304,7 +304,7 @@ class MapWidget extends BaseWidget<MapWidgetProps, WidgetState> {
     };
   }
 
-  updateCenter = (lat: number, long: number, title?: string) => {
+  updateCenter = (lat?: number, long?: number, title?: string) => {
     this.props.updateWidgetMetaProperty("center", { lat, long, title });
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/widget/index.tsx:308]: Did we save `lng` or `long` in the DSL?

File: app/client/src/components/propertyControls/LocationSearchControl.tsx [hunk 7]
```diff
@@ -21,37 +28,47 @@ class LocationSearchControl extends BaseControl<ControlProps> {
...
       else {
         log.debug("Error selecting location - searchBox not found");
       }
     }
   };
 
-  onSearchBoxMounted = (ref: SearchBox) => {
-    this.searchBox = ref;
+  onSearchBoxMounted = (ref: any) => {
+    if (window) {
```
Comment (keyurparalkar) [inline app/client/src/components/propertyControls/LocationSearchControl.tsx:51]: Also check if `map` object exists?

File: app/client/src/widgets/MapWidget/component/index.tsx [hunk 8]
```diff
@@ -20,219 +23,72 @@ interface MapComponentProps {
...
+ * @returns
+ */
+const renderMapStatus = (status: Status) => {
+  switch (status) {
+    case Status.LOADING:
+      return <span>Loading...</span>;
+    case Status.FAILURE:
+      return <span>Error in the component</span>;
+    case Status.SUCCESS:
+      return <span>Component loaded....</span>;
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/index.tsx:57]: When there is a FAILURE or LOADING state are we should these span elements or appsmith defaults?

File: app/client/src/widgets/MapWidget/component/Clusterer.tsx [hunk 9]
```diff
@@ -0,0 +1,88 @@
+import React, { useEffect, useState } from "react";
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Clusterer.tsx:1]: Do we require this feature in this PR?
CC: @dilippitchika

**Review by keyurparalkar — COMMENTED** [review]
Is this issue occuring: `Component re-renders on change in zoom level`?

File: app/client/src/widgets/MapWidget/component/Clusterer.tsx (hunk 9 above)
Comment (dilippitchika) [reply app/client/src/widgets/MapWidget/component/Clusterer.tsx:1]: @keyurparalkar i am assuming you are talking about clustering, reviewed this with @jsartisan and it seems good to go for me.

**Comment by laveena-en** [comment]
@jsartisan A loading state is seen in place of the text box under Initial location.

And the corresponding location isn’t showing up on the map, on searching for a particular city.
Can you please check? https://ivp6ez0ljb.vmaker.com/record/8XtxRhdwQYClpbub

File: app/client/src/widgets/MapWidget/component/Map.tsx [hunk 10]
```diff
@@ -100,17 +109,23 @@ const Map = (props: MapProps) => {
 
       map.addListener("click", onClickOnMap);
     }
-  }, [map]);
+  }, [map, onClickOnMap]);
 
   return (
-    <Wrapper>
+    <Wrapper onMouseLeave={enableDrag}>
```
Comment (keyurparalkar) [inline app/client/src/widgets/MapWidget/component/Map.tsx:115]: Since Wrapper is a styled component with no props being passed to it? is `onMouseLeave` being pass intentionally?

**Review by keyurparalkar — DISMISSED** [review]

**Comment by yaldram** [comment]
Q/A Problem Areas : - 
- `All Select Widgets`, need to be tested thoroughly please check this comment - https://github.com/appsmithorg/appsmith/pull/14000#issuecomment-1160387162
- `Not able to drag the select widget inside the Modal widget` - https://www.loom.com/share/e579ba0bb9d94692ba4ab2043da7efd6
- Map Widget (Already Done).

**Comment by yaldram** [comment]
QA - The drag to select multiple widgets inside the Modal widget is fixed by Ashok, and is working as expected.

**Comment by kamakshibhat-appsmith** [comment]
Issues and observations:Issue with footer remix icons and the clickable action on it .
