### PR TITLE
fix: updated Box shadow UI

### LINKED ISSUE #23760: [Task]: In property pane, replace box-shadow property icon with text
Replace the icon with small, medium & large text.

### PR DESCRIPTION
**Pull request by harshitpandey0426**
#### PR fixes following issue(s)
Fixes #23760

#### Media (Screenshots to justify change)
image

image

>
image

>
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx [hunk 1]
```diff
@@ -14,22 +14,22 @@ export interface BoxShadowOptionsControlProps extends ControlProps {
...
+        <div>
           <Icon name="close-line" size="md" />
         </div>
       ) : (
-        <div
-          className="flex items-center justify-center w-5 h-5 bg-white"
-          style={{ boxShadow: boxShadowOptions[optionKey] }}
-        />
+        <div>
+          {optionKey === "S" && "Small"}
```
Comment (sheoranabhishek) [inline app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx:26]: I suggest that we keep a mapping of these size literals to their full form. We might need to reuse it along various components. We can define this mapping within ThemeConstants. What do you say ?
`{
S : "Small",
M: "Medium",
L : "Large",
}`

**Review by aswathkk — CHANGES_REQUESTED** [review]
@harshitpandey0426 Thank you for the contribution.

Please take a look at the review comments.
Also, I could see that you made this change only for the widget's property pane.

We also need to change the UI in App theme settings pane too.
The file we need to make the change would be ThemeShadowControl.tsx

File: app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx [hunk 2]
```diff
@@ -14,22 +14,22 @@ export interface BoxShadowOptionsControlProps extends ControlProps {
   propertyValue: string | undefined;
 }
 
-const options = Object.keys(boxShadowOptions).map((optionKey) => ({
+const options = Object.keys(boxShadowOptions).map((optionKey, index) => ({
   label: (
-    <Tooltip content={optionKey} key={optionKey}>
+    <React.Fragment key={index}>
```
[the remark this answers is not in the document]
Comment (harshitpandey0426) [reply app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx:19]: @aswathkk Since we removed Tooltip here fragment was needed to group multiple elements together. Can be changed to <> .. </>. Will this work? or I should think of something else like creating an array here?

[the remark this answers is not in the document]
Comment (harshitpandey0426) [reply app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx:19]: I will create the mapping as suggested.

**Comment by harshitpandey0426** [comment]
@aswathkk 
> We also need to change the UI in App theme settings pane too. The file we need to make the change would be ThemeShadowControl.tsx

Thanks for the input, I will make these changes

File: app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (aswathkk) [reply app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx:19]: @harshitpandey0426 There is only one div element available there. Right?
Fragments need to be used only when there are multiple elements are there.

[the remark this answers is not in the document]
Comment (harshitpandey0426) [reply app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx:19]: @aswathkk There are 2 div elements with ternary operator on optionKey.

File: app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx [hunk 3]
```diff
@@ -14,22 +14,18 @@ export interface BoxShadowOptionsControlProps extends ControlProps {
   propertyValue: string | undefined;
 }
 
-const options = Object.keys(boxShadowOptions).map((optionKey) => ({
+const options = Object.keys(boxShadowOptions).map((optionKey, index) => ({
   label: (
-    <Tooltip content={optionKey} key={optionKey}>
+    <div key={index}>
```
Comment (aswathkk) [inline app/client/src/components/propertyControls/BoxShadowOptionsControl.tsx:19]: These divs are unnecessary and the label and value could just be as follows:
```javascript
label: optionKey === "none" ? (<Icon name="close-line" size="md" />) : (sizeMappings[optionKey]),
value: boxShadowOptions[optionKey],
```

File: app/client/src/pages/Editor/ThemePropertyPane/controls/ThemeShadowControl.tsx [hunk 4]
```diff
@@ -40,20 +43,17 @@ function ThemeBoxShadowControl(props: ThemeBoxShadowControlProps) {
     ? invertedBoxShadowOptions[selectedOption]
     : "";
 
-  const buttonGroupOptions = Object.keys(options).map((optionKey) => ({
+  const buttonGroupOptions = Object.keys(options).map((optionKey, index) => ({
     label: (
-      <Tooltip content={optionKey} key={optionKey}>
+      <div key={index}>
```
Comment (aswathkk) [inline app/client/src/pages/Editor/ThemePropertyPane/controls/ThemeShadowControl.tsx:48]: Same as mentioned above

**Review by aswathkk — CHANGES_REQUESTED** [review]
@harshitpandey0426 Seems like we can remove some unwanted DOM elements here.
Can you take a look at it?

**Comment by harshitpandey0426** [comment]
@aswathkk Made the suggested changes. Please have a look.

**Review by aswathkk — DISMISSED** [review]
LGTM

**Comment by harshitpandey0426** [comment]
@aswathkk 
Updated Theme_Default_spec.js, Theme_Default_spec.js, Theme_MultiSelectWidget_spec.js tests
I could not get what exactly is wrong with Basic_spec.js. I get that .ads-v2-segmented-control-value class is no longer present for box shadow. Should I remove that part of the test? Any input will be helpful.

**Comment by harshitpandey0426** [comment]
@aswathkk I could not get what exactly is wrong in basic_spec.js. I have updated the css class but still it is failing for the code I commented. Any input would be appreciable.

File: app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js [hunk 5]
```diff
@@ -777,16 +777,15 @@ describe("App Theming funtionality", function () {
...
-    cy.get(".ads-v2-segmented-control-value-0 div")
-      .eq(2)
+    cy.contains(".ads-v2-segmented-control-value-0", "Large").click();
+    cy.contains(".ads-v2-segmented-control-value-0", "Large")
       .invoke("css", "box-shadow")
       .then((boxshadow) => {
-        cy.get(".t--widget-button2 button").should(
-          "have.css",
-          "box-shadow",
-          boxshadow, //rgba(0, 0, 0, 0.1) 0px 10px 15px -3px, rgba(0, 0, 0, 0.05) 0px 4px 6px -2px
```
Comment (harshitpandey0426) [inline app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js:788]: Cypress is expecting "none" here

File: app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js [hunk 6]
```diff
@@ -777,16 +777,10 @@ describe("App Theming funtionality", function () {
       });
 
     //Change Shadow & verify
-    cy.get(".ads-v2-segmented-control-value-0").eq(2).click({ force: true });
-    cy.get(".ads-v2-segmented-control-value-0 div")
-      .eq(2)
+    cy.contains(".ads-v2-segmented-control-value-0", "Large").click();
+    cy.contains(".ads-v2-segmented-control-value-0", "Large")
       .invoke("css", "box-shadow")
-      .then((boxshadow) => {
```
Comment (harshitpandey0426) [inline app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js:784]: This is because box-shadow was passed in a div element from boxShadowOptionsElement.tsx and that is removed now

**Comment by harshitpandey0426** [comment]
@aswathkk Updated the tests, please have a look.

File: app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Theme_Default_spec.js [hunk 7]
```diff
@@ -40,10 +40,6 @@ describe("Theme validation for default data", function () {
     //Shadow validation
     //cy.contains("Shadow").click({ force: true });
     cy.wait(2000);
-    cy.shadowMouseover("none");
-    cy.shadowMouseover("S");
```
Comment (harshitpandey0426) [inline app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Theme_Default_spec.js:44]: Because tooltip is removed

File: app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js (hunk 6 above)
Comment (aswathkk) [reply app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js:784]: ok. Got it.
In that case, we don't need to do ` cy.contains(".ads-v2-segmented-control-value-0", "Large").invoke("css", "box-shadow")` and then verify the box-shadow of iconButton and button widgets.
Rather, we could just verify them immediately.

File: app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js [hunk 8]
```diff
@@ -1004,16 +998,10 @@ describe("App Theming funtionality", function () {
...
+    cy.contains(".ads-v2-segmented-control-value-0", "Small")
       .invoke("css", "box-shadow")
-      .then((boxshadow) => {
-        cy.get(".t--widget-button1 button").should(
-          "have.css",
-          "box-shadow",
-          boxshadow, //rgba(0, 0, 0, 0.1) 0px 1px 3px 0px, rgba(0, 0, 0, 0.06) 0px 1px 2px 0px
-        );
+      .then(() => {
         cy.get(widgetsPage.iconWidgetBtn).should(
```
Comment (aswathkk) [inline app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js:1005]: Same as above.
We can put this out of then block and remove the invoke of box-shadow on the segmented control value

**Review by aswathkk — CHANGES_REQUESTED** [review]
Minor nit-pick on the Cypress tests

**Comment by harshitpandey0426** [comment]
@aswathkk made the changes please review.

**Review by aswathkk — APPROVED** [review]
LGTM

**Comment by harshitpandey0426** [comment]
I checked these failing cypress tests are not related to this change and they are failing in release too.
@aswathkk @rohitagarwal88 Please lmk if anything else is pending from my end.

**Comment by aswathkk** [comment]
Hi @harshitpandey0426, Can you merge the latest release branch with this branch?

**Comment by harshitpandey0426** [comment]
@aswathkk done

**Comment by harshitpandey0426** [comment]
@aswathkk any update on this?
