### PR TITLE
fix: App card is created even when app import fails and no action can be performed on this app card

### LINKED ISSUE #10490: [Bug]-[224]:App card is created even when app import fails and no action can be performed on this app card
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App card is created with no timestamp details when app import fails. This app card is a placeholder and performing any action like edit or launch throws a resource not found error.

[LOOM DEMO](https://www.loom.com/share/71cebf292b384a6293f0767805417ae3)

### Steps To Reproduce

1. Try to import a corrupt app and observe an `internal server error` displayed when import fails
2. Refresh the page and observe an app card created for this app and have no timestamp details.
3. Clicking on `Edit` or `Launch` does not yield expected behaviour instead shows resource not found

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> App card is created with no timestamp details when app import fails. This app card is a placeholder and performing any action like edit or launch throws a resource not found error.

Fixes #10490

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- JUnit

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java [hunk 1]
```diff
@@ -729,6 +729,7 @@ private Mono<Application> importApplicationInWorkspace(String workspaceId,
                     // Check if the destination org have all the required plugins installed
                     for (Datasource datasource : importedDatasourceList) {
                         if (StringUtils.isEmpty(pluginMap.get(datasource.getPluginId()))) {
+                            log.error("Unable to find the plugin ", datasource.getPluginId());
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:732]: Do you know when this happens? On the same instance, the plugin ids should remain the same no?

Also, instead of logging this error here, do you know why Mono.error is not logging it? If it is not, I suggest that you check out the Global Exception Handler?

**Review by trishaanand — APPROVED** [review]
Minor question added.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java (hunk 1 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:732]: Hey, the error is logged but because the onErrorResume is catching this error hence I had to add this condition.
