### PR TITLE
fix: Use populated actionDTO for json path keys in JS during refactor

### LINKED ISSUE #7583: [Bug] Trying to refactor a widget name twice does not refactor references in JS objects
1. Create a widget Input1
2. Create a JSObject1
3. Refer to Input1 in JSObject1.Action1
4. Refactor Input1 to Input2, update and refactor both succeed
5. Refactor Input2 to Input3, update succeeds but refactor fails

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #7583

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java [hunk 1]
```diff
@@ -306,43 +306,48 @@
...
-                        // Since json path keys actually contain the entire inline js function instead of just the widget/action
-                        // name, we can not simply use the set.contains(obj) function. We need to iterate over all the keys
-                        // in the set and see if the old name is a substring of the json path key.
-                        for (String key : jsonPathKeys) {
-                            if (key.contains(oldName)) {
-                                actionUpdateRequired = true;
-                                break;
+                .flatMap(newAction1 -> {
+                    final NewAction newAction = newAction1;
+                    Mono<ActionDTO> actionMono = newActionService.generateActionByViewMode(newAction, false);
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java:311]: Why are we doing this? Could you write a small comment for this line?

**Review by trishaanand — APPROVED** [review]

**Review by trishaanand — APPROVED** [review]
