### PR TITLE
Fix issue while deleting a tab from explorer 

### LINKED ISSUE #2885: [Bug]Deletion of Tab from entity explorer is not working
Steps:

1.Delete one of the 2 default tabs in the tab widget from entity explorer.
2.Tab deleted message is seen but it's not reflecting in the widget and also in the property pane.

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description
Deleting from the explorer doesn't update the widgets `tab` property. So doing the same as a special case for tabs in a tab widget in the delete widget saga.

Fixes #2885 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 1]
```diff
@@ -431,6 +432,23 @@ export function* deleteSaga(deleteAction: ReduxAction<WidgetDelete>) {
       // SPECIAL HANDLING FOR TABS IN A TABS WIDGET
       if (parent.type === WidgetTypes.TABS_WIDGET && widget.tabName) {
         widgetName = widget.tabName;
+        // Deleting a tab from the explorer doesn't remove the same
```
Comment (mohanarpit) [inline app/client/src/sagas/WidgetOperationSagas.tsx:435]: Can we ensure that we don't leak abstractions here? Technically, the WidgetOperationSaga should be agnostic to the widget being deleted. Since the tab widget has special handling, we should have a function called `deleteWidget` in the `BaseWidget` class with an empty implementation. If any widget requires a special handling, the specific widget should override it's implementation of the `delete` function to fire the specific event.

Comment (akash-codemonk) [reply app/client/src/sagas/WidgetOperationSagas.tsx:435]: I am not sure how would that work for deleting a widget from outside the widget context, in this case from the entity explorer.

Comment (Nikhil-Nandagopal) [reply app/client/src/sagas/WidgetOperationSagas.tsx:435]: @riodeuno is there a good solution here?

Comment (Nikhil-Nandagopal) [reply app/client/src/sagas/WidgetOperationSagas.tsx:435]: @mohanarpit spoke to @riodeuno and since there is no good solution here and it needs some fundamental rearchitecting, we're merging this in

**Review by Nikhil-Nandagopal — APPROVED** [review]
