### PR TITLE
fix: [Perf Improvement] removed unnecessary individual DB calls to plugin and fetched al…

### LINKED ISSUE #33678: [Task]: Improve performance of datasources in consolidated API (Remove unnecessary call to DB for plugins)
### SubTasks

As per discussion in thread, after adding [instrumentation](https://theappsmith.slack.com/archives/CPQNLFHTN/p1716358302105049?thread_ts=1715761934.675989&cid=CPQNLFHTN) and checking this instrumentation from local, we have decided on following areas of improvements:
In order to solve identified bottlenecks, we can:

- Remove unnecessary individual calls to fetch plugin info from DB everytime, instead we can fetch all plugins at once and send this data populateHintMessages

### LINKED ISSUE #33711: [Task]: Introduce additional perf instrumentation for datasources section of consolidated APIs
### SubTasks

Consolidated API is responsible for fetch all application resources at once, as part of this API we also fetch list of datasources. In this task we need to add additional perf instrumentation to see how much time it takes to fetch all datasources, their datasource storages and collect them.

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR adds:
- Additional instrumentation around `datasources` section of consolidated API

Datasources fetch process looks as below:
1. It first fetches all datasources belonging to a workspace
2. For each datasources, fetches its datasourceStorages
     a. Calls populateHintMessages to populate messages property in datasourceStorage
     b. Fetches plugin from DB
     c. Gets pluginExecutor from plugin
     d. calls getHintMessages on pluginExecutorMono
3. Marks recently used datasources (sorts all datasources based on createdAt in desc order and marks top 3 as recent)

This PR adds improvements around point 2.b so that we fetch all plugins at once in one DB call and then use that to process hint messages for all datasourceStorages, this avoiding multiple calls to DB

Fixes #33711 
Fixes #33678
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9347912473>
> Commit: 15643310489a52ae4067bde8ce4d5b48fa73567f
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9347912473&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java [hunk 1]
```diff
@@ -261,7 +260,7 @@ public Mono<DatasourceStorage> populateHintMessages(DatasourceStorage datasource
             return Mono.just(datasourceStorage);
         }
 
-        final Mono<Plugin> pluginMono = pluginService.findById(datasourceStorage.getPluginId());
```
Comment (NilanshBansal) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java:264]: @sneha122 Nit: Is there any specific need to remove the final keyword?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java [hunk 2]
```diff
@@ -281,6 +280,44 @@ public Mono<DatasourceStorage> populateHintMessages(DatasourceStorage datasource
...
+        return pluginExecutorMono
+                .flatMap(pluginExecutor -> ((PluginExecutor<Object>) pluginExecutor)
+                        .getHintMessages(null, datasourceStorage.getDatasourceConfiguration()))
+                .flatMap(tuple -> {
+                    Set<String> datasourceHintMessages = tuple.getT1();
+                    datasourceStorage.getMessages().addAll(datasourceHintMessages);
+                    return Mono.just(datasourceStorage);
+                });
+    }
+
```
Comment (NilanshBansal) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java:320]: @sneha122 Can we please reduce the code duplication in the overloaded method populateHintMessages(). 
One way of doing this could be to invoke the `populateHintMessages(
            DatasourceStorage datasourceStorage, Map<String, Plugin> pluginsMap)` from `populateHintMessages(DatasourceStorage datasourceStorage)` with pluginsMap as null.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java [hunk 3]
```diff
@@ -150,6 +150,7 @@ public void verifyStorageCreationErrorsOutWhenStorageAlreadyExists() {
         datasourceStorage.setEnvironmentId(environmentIdOne);
         datasourceStorage.setPluginId(pluginId);
         datasourceStorage.setDatasourceConfiguration(datasourceConfiguration);
+        datasourceStorage.setWorkspaceId(workspace.getId());
```
Comment (NilanshBansal) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java:153]: Nit: @sneha122 why is this new LOC addition required for an existing test case?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java [hunk 4]
```diff
@@ -186,6 +187,7 @@ public void verifyStorageCreationSucceedsWithDifferentEnvironmentId() {
...
```
Comment (NilanshBansal) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java:190]: Same as L153.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java [hunk 5]
```diff
@@ -214,6 +216,7 @@ public void verifyFindByDatasourceAndStorageIdGivesErrorWhenNoConfigurationIsPre
         datasourceStorage.setDatasourceId(datasourceId);
         datasourceStorage.setEnvironmentId(environmentIdOne);
         datasourceStorage.setPluginId(pluginId);
+        datasourceStorage.setWorkspaceId(workspace.getId());
```
Comment (NilanshBansal) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java:219]: Same as L153.

**Review by NilanshBansal — CHANGES_REQUESTED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java (hunk 1 above)
Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java:264]: Thanks @NilanshBansal will add it back

File: app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java (hunk 2 above)
Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java:320]: @NilanshBansal Yes will do this, thanks for the suggestion!

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java (hunk 3 above)
Comment (sneha122) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java:153]: @NilanshBansal This is not required at all, will remove it

**Review by NilanshBansal — APPROVED** [review]
LGTM
