### PR TITLE
fix: removed success toast message for onload js functions

### LINKED ISSUE #32695: [Task]: Remove success toast message for when query is run
### SubTasks

When you have created JSObjects functions which are set to execute on page load, when you reload such page and these functions are executed, we get toast messages that these functions have ran successfuly. These toast messages end up cluttering the UI, hence we should remove them.

https://github.com/appsmithorg/appsmith/assets/30018882/44472503-d3c7-4bf8-861f-437284a4996c

### PR DESCRIPTION
**Pull request by sneha122**
## Description

Whenever we have js object functions set to execute on page load, and we reload such page, all these functions are execute and we get lots of success message popups indicating the execution of js object functions was successful, These toasts clutter the UI and unnecessary since action execution has been successful, this PR removes those toast messages

https://github.com/appsmithorg/appsmith/assets/30018882/44472503-d3c7-4bf8-861f-437284a4996c

Fixes #32695
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8734047332>
> Commit: fb22e7445618c592dee1066991d668082afc5642
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8734047332&attempt=2" target="_blank">Click here!</a>

## Summary by CodeRabbit

- **Refactor**
	- Simplified JavaScript execution flow by removing unused imports and functions.
	- Removed success toast notification after JavaScript function execution.
	- Updated test scenarios in Cypress related to JavaScript execution and navigation back to the editor.
	- Removed test cases verifying the number and sequence of JS objects on page load in ServerSide/OnLoadTests.
	- Added functionality to interact with the debugger in the test scenario in ClientSide/BugTests.

### CODE REVIEW

File: app/client/src/sagas/JSPaneSagas.ts [hunk 1]
```diff
@@ -68,7 +68,6 @@ import {
   JS_EXECUTION_FAILURE,
   JS_FUNCTION_CREATE_SUCCESS,
   JS_FUNCTION_DELETE_SUCCESS,
-  JS_EXECUTION_SUCCESS_TOASTER,
```
Comment (rishabhrathod01) [inline app/client/src/sagas/JSPaneSagas.ts:71]: Could we also remove the `JS_EXECUTION_SUCCESS_TOASTER`, this is not being used anywhere else in CE codebase.

**Review by rishabhrathod01 — COMMENTED** [review]
Could we verify once, that this change doesn't break any code/tests in EE?

File: app/client/src/sagas/JSPaneSagas.ts (hunk 1 above)
Comment (sneha122) [reply app/client/src/sagas/JSPaneSagas.ts:71]: Yes will do this, also I am running tests with tag.All on both CE and EE PR, so in case of any failures we will get to know!

**Review by rishabhrathod01 — APPROVED** [review]
Changes look good to me. Tested on the DP.

**Comment by sneha122** [comment]
Failing tests are unrelated and discussion happening [here](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1713299032136189), moving into blocked state till then

File: app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad2_Spec.ts [hunk 2]
```diff
@@ -70,108 +70,6 @@ describe(
...
-      jsEditor.EnableDisableAsyncFuncSettings("cat", true);
-      jsEditor.EnableDisableAsyncFuncSettings("hogwartsstudents", true);
-      EditorNavigation.SelectEntityByName("JSObject3", EntityType.JSObject);
-      jsEditor.EnableDisableAsyncFuncSettings("film", true);
-
-      EditorNavigation.SelectEntityByName("Page1", EntityType.Page);
-      agHelper.RefreshPage();
-
-      agHelper.ValidateToastMessage("ran successfully", 0, 5);
-    });
```
Comment (rishabhrathod01) [inline app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad2_Spec.ts:173]: Instead of removing the test case here, shouldn’t we change the verification logic here? 
We could check for logs to verify the function execution?

Comment (sneha122) [reply app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad2_Spec.ts:173]: Yeah even I thought about it, I will see if we have any debugger tests written and will try to add that logic here

**Review by rishabhrathod01 — APPROVED** [review]
LGTM
