### PR TITLE
fix: for api-redirection

### LINKED ISSUE #25408: [Bug]: Appsmith API Error `java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "o" is null`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user encounters the error `java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "o" is null `when making a `GET` request to an `API`. It also happens with `POST` requests.

### Steps To Reproduce

API Endpoint: `https://mock-api.appsmith.com/users`
Body: `{"a":1}`
HTTP Method: `POST`
image

For more details about this issue, you can refer to the [Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1689005370629189) and the conversation with the [user](https://app.frontapp.com/open/cnv_11zxo570?key=PigvRTBY6rExgYlM_JhlcCFGXwqBOl9Z).

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud: Appsmith v1.9.27-SNAPSHOT

Front logo [Front conversations](https://app.frontapp.com/open/top_wr32k)

### PR DESCRIPTION
**Pull request by sondermanish**
This Pr adds null pointer checks for host address, adds stack trace in logging, and fixes the problem of erroring out when the  called endpoint redirection headers don't have full formed forwarding location

#### PR fixes following issue(s)
Fixes #25408 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit

#### Test Plan
1. Tried out with the  endpoint of the API hosted on Manish's ngrok, GET and POST requests fail with the java null pointer exception. However, on this DP, both GET and POST requests work. 
2. Tried out Sanity tests with other end points on Rest API
3. Did Sanity checks on GraphQL
4. Saved Rest API and GraphQL as datasource and ensured that works fine too
5. Exported this app, imported the same and ran the API to check for functionality

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [x] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by nidhi-nair — DISMISSED** [review]

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java [hunk 1]
```diff
@@ -213,6 +226,20 @@ protected Mono<ClientResponse> httpCall(
...
+                StringUtils.hasText(redirectUri.getScheme()) ? redirectUri.getScheme() : originalUrl.getScheme();
+        String authority = StringUtils.hasText(redirectUri.getAuthority())
+                ? redirectUri.getAuthority()
+                : originalUrl.getAuthority();
+        String path = redirectUri.getPath();
+        String query = redirectUri.getQuery();
+        String fragment = redirectUri.getFragment();
+
+        return new URI(scheme, authority, path, query, fragment);
+    }
```
Comment (sharat87) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java:241]: Can we use the [`URI.resolve`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URI.html#resolve(java.lang.String)) method to do the resolution here instead of manually doing it please? It'll handle few other cases correctly, like `../redirect-path` etc.

```suggestion
    public URI createRedirectUrl(String redirectUrl, URI originalUrl) {
        return originalUrl.resolve(redirectUrl);
    }
```

**Review by sharat87 — CHANGES_REQUESTED** [review]

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java (hunk 1 above)
Comment (sondermanish) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java:241]: got it, making the change

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java [hunk 2]
```diff
@@ -213,6 +225,10 @@ protected Mono<ClientResponse> httpCall(
                 });
     }
 
+    public URI createRedirectUrl(String redirectUrl, URI originalUrl) throws URISyntaxException {
```
Comment (sharat87) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java:228]: I don't think this exception is being thrown in here.

```suggestion
    public URI createRedirectUrl(String redirectUrl, URI originalUrl) {
```

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java [hunk 3]
```diff
@@ -202,7 +213,8 @@ protected Mono<ClientResponse> httpCall(
                          */
                         final URI redirectUri;
                         try {
-                            redirectUri = new URI(redirectUrl);
+                            redirectUri = createRedirectUrl(redirectUrl, uri);
+                            //                            redirectUri = new URI(redirectUrl);
```
Comment (sharat87) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java:217]: Can we remove this instead of commenting please?


```suggestion
```

**Review by sharat87 — CHANGES_REQUESTED** [review]
Minor, but otherwise looks good. Thanks.

**Review by sharat87 — APPROVED** [review]

**Comment by btsgh** [comment]
Completed Manual testing of this PR. Works fine. @sondermanish  do let me know once your automation cases are added for this

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 4]
```diff
@@ -208,6 +208,11 @@ public Mono<ActionExecutionResult> executeCommon(
                         errorResult.setRequest(requestCaptureFilter.populateRequestFields(
                                 actionExecutionRequest, isBodySentWithApiRequest));
                         errorResult.setIsExecutionSuccess(false);
+                        log.debug(
+                                "An error has occurred while trying to run the API query for url: {}, path : {}",
+                                datasourceConfiguration.getUrl(),
+                                actionConfiguration.getPath());
+                        error.printStackTrace();
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:215]: Hey why are we printing stack trace like this?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java [hunk 5]
```diff
@@ -29,10 +32,16 @@ public class WebClientUtils {
 
     public static final String HOST_NOT_ALLOWED = "Host not allowed.";
 
-    public static final ExchangeFilterFunction IP_CHECK_FILTER = ExchangeFilterFunction.ofRequestProcessor(
-            request -> DISALLOWED_HOSTS.contains(request.url().getHost())
-                    ? Mono.error(new UnknownHostException(HOST_NOT_ALLOWED))
-                    : Mono.just(request));
+    public static final ExchangeFilterFunction IP_CHECK_FILTER = ExchangeFilterFunction.ofRequestProcessor(request -> {
+        request.url();
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java:36]: What does this line do?

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 4 above)
Comment (sondermanish) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:215]: this is explicitly for debugging purpose, since this error is handled, it gets difficult to debug.

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java (hunk 5 above)
Comment (sondermanish) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java]: was a typo, fixed that.

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 4 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:215]: Should we not log it using sl4j in that case?

Comment (sondermanish) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:215]: we don't get the complete trace on the error using, `error.getStackTrace()`

**Review by nidhi-nair — APPROVED** [review]

**Comment by btsgh** [comment]
As per discussion with @sondermanish  - since junit tests are added, adding the test plan approved label.
