### PR TITLE
fix: S3 formData path for bucket name

### LINKED ISSUE #12033: [Bug]: Generate page doesn't work for S3 and mongo datasource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Generate page doesn't work for S3 and mongo datasource
image

### Steps To Reproduce

1. Add the s3 datasource 
2. now click on generate page
3. Select  the Datasource as s3
4. now select the bucket as assert.test.appsmith.com
5. Now click on generate button 
6. The internal server error is displayed instead of generating the page

### Public Sample App

_No response_

### Version

release

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #12033

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/nn-patch-6 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.63 **(0)** | 36.86 **(-0.01)** | 34.94 **(0)** | 55.94 **(0)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**</details>

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java [hunk 1]
```diff
@@ -323,8 +323,9 @@
                     // index 1 in plugin specified templates
 
                     if (Entity.S3_PLUGIN_PACKAGE_NAME.equals(plugin.getPackageName()) && !CollectionUtils.isEmpty(templateActionList)) {
+                        final Map<String, Object> formData = templateActionList.get(0).getUnpublishedAction().getActionConfiguration().getFormData();
                         mappedColumnsAndTableName.put(
-                                (String) templateActionList.get(0).getUnpublishedAction().getActionConfiguration().getFormData().get("bucket"),
+                                (String) ((Map<?,?>)formData.get("bucket")).get("data"),
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java:328]: @nidhi-nair can you please explain what have we changed recently to affect the CRUD template page?

**Review by abhvsn — APPROVED** [review]
