### PR TITLE
Fix/select widget placeholder

### LINKED ISSUE #6610: [Feature] Placeholder for the select widget
## Summary

As a Dev, I should be able to set a placeholder for the select widget, Where nothing is selected, The placeholder is visible

## Additional Context

Support [query](https://discord.com/channels/725602949748752515/760761686549463060/876061940089233458) from our discord server

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

Add Placeholder to Select widget
Fixes #6610 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/select-widget-placeholder 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.62 **(0)** | 36.69 **(0)** | 33.05 **(-0.01)** | 55.23 **(0)**
 :red_circle: | app/client/src/components/designSystems/blueprint/DropdownComponent.tsx | 44.23 **(-0.87)** | 19.51 **(-4.02)** | 5 **(-0.26)** | 44 **(-0.9)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**</details>

### CODE REVIEW

File: app/client/src/widgets/DropdownWidget.tsx [hunk 1]
```diff
@@ -95,6 +95,16 @@ class DropdownWidget extends BaseWidget<DropdownWidgetProps, WidgetState> {
             },
             dependencies: ["selectionType"],
           },
+          {
+            helpText: "Input Place Holder",
```
Comment (somangshu) [inline app/client/src/widgets/DropdownWidget.tsx:99]: Does not need help text

**Review by somangshu — DISMISSED** [review]
Code looks good to me, Approving to run tests

**Comment by somangshu** [comment]
Feedback from he deploy preview:

0. There are consistency issues
1. We need to change the select placeholder colour with what we use for the multiselect placeholder
2. We need to change the multiselect arrow colour with what we use in the select widget

Screenshot 2021-08-20 at 3 17 45 PM

**Review by somangshu — APPROVED** [review]
LGTM
