### PR TITLE
fix: Added single quotes on hint query containing mustache substitution fo…

### LINKED ISSUE #22132: [Bug]: single quote required in the hint text for create query.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The current hint text is:
INSERT INTO users
  (name, gender, email)
VALUES
  (
    {{ nameInput.text }},
    {{ genderDropdown.selectedOptionValue }},
    {{ nameInput.text }}
  );

it should be 
The current hint text is:
INSERT INTO users
  (name, gender, email)
VALUES
  (
    '{{ nameInput.text }}',
   ' {{ genderDropdown.selectedOptionValue }}',
   ' {{ nameInput.text }}'
  );

### Steps To Reproduce

1. Create a snowflake datasource
2. Create a create query

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

1.9.13

### PR DESCRIPTION
**Pull request by tkAppsmith**
## Description

> In this PR, single quotes have been added around substitution expression in hint query of Snowflake DB.
> This fixes the issue: https://github.com/appsmithorg/appsmith/issues/22132
> Single quotes is necessary in hint text because Snowflake DB don't have prepared statements mode yet and with single quotes, the substituted values appear in query without quotes leading to query execution error.

Fixes #22132 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by nidhi-nair — DISMISSED** [review]

**Comment by nidhi-nair** [comment]
Is it possible for us to write tests around this query generation flow so that we never regress on it?

**Comment by tkAppsmith** [comment]
> Is it possible for us to write tests around this query generation flow so that we never regress on it?

Yes. Tests can be added on the method that loads these templates from resource files. I will add new tests in this pr. Thanks.

File: app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java [hunk 1]
```diff
@@ -10,20 +10,31 @@
...
 import reactor.test.StepVerifier;
 
+import java.io.BufferedReader;
+import java.io.IOException;
+import java.io.InputStream;
+import java.io.InputStreamReader;
 import java.sql.Connection;
 import java.sql.SQLException;
 import java.sql.Statement;
 import java.util.*;
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java:35]: Not a change in your PR but could you please get rid of this generic import? We try to keep specific import statements to ensure readability.

File: app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java [hunk 2]
```diff
@@ -147,4 +160,57 @@ public void verifyUniquenessOfSnowflakePluginErrorCode() {
...
+
+        result.get("templates").forEach(entry -> {
+            for (Map.Entry<String, String> mapEntry : entry.entrySet()) {
+                try {
+                    InputStream template = new ClassPathResource("templates/" + mapEntry.getValue()).getInputStream();
+                    BufferedReader templateReader = new BufferedReader(new InputStreamReader(template));
+                    String file = templateReader.lines().collect(Collectors.joining(System.lineSeparator()));
+                    templates.add(file);
+                } catch(IOException ioe) {
+                    log.error("error while reading the template file:", ioe);
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java:189]: We should fail the test if this happens

File: app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java [hunk 3]
```diff
@@ -147,4 +160,57 @@ public void verifyUniquenessOfSnowflakePluginErrorCode() {
...
+        mapper  = new ObjectMapper();
+        result  = mapper.readValue(meta, type);
+
+        List<String> templates = new ArrayList<>();
+
+        result.get("templates").forEach(entry -> {
+            for (Map.Entry<String, String> mapEntry : entry.entrySet()) {
+                try {
+                    InputStream template = new ClassPathResource("templates/" + mapEntry.getValue()).getInputStream();
+                    BufferedReader templateReader = new BufferedReader(new InputStreamReader(template));
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java:185]: Do you want to use try with resources here to ensure optimal memory usage?

File: app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java [hunk 4]
```diff
@@ -147,4 +160,57 @@ public void verifyUniquenessOfSnowflakePluginErrorCode() {
...
+
+            int mustacheMatchCount = 0;
+            int enclosedMustacheMatchCount = 0;
+            while( mustacheMatcher.find() ) {
+                mustacheMatchCount++;
+            }
+            while( enclosedMustacheMatcher.find() ) {
+                enclosedMustacheMatchCount++;
+            }
+            assertEquals(mustacheMatchCount, enclosedMustacheMatchCount);
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java:213]: So we're essentially testing for whether every mustache is enclosed in quotes here, but this might not be the use case in the future (think of numeric fields). We should put in a comment here along the same lines so that the red on the test in the future is easily understandable.

**Comment by AnandShahs123** [comment]
@tkAppsmith - This is tested. Looks fine. can be closed
