### PR TITLE
fix: js object functions were retained after clearing

### LINKED ISSUE #9585: [Bug]-[200]:Default functions are retained on the run dropdown even after deleting the JSObject code
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JS object does not recognize incorrect structure when code is copy-pasted and hence the default functions `myFun1` and `myFun2` are retained. No error is displayed either on the response or error tab of Debugger and only shows one when the function `myFun1` or `myFun2` are run.

### Steps To Reproduce

1. Go to app at [link](https://release.app.appsmith.com/applications/612332edfe755a38b6e6a9c2/pages/61aa020312c2470ed74e584a/edit/jsObjects/61aa035012c2470ed74e584f) or copy paste a chunk of code that does not follow our JS structure of `export {}...`
2. Observe the default functions retained even after the toast message informing of expected structure
image
3. Run any default function present in debugger and observe the error.

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by ravikp7**
## Description
After deleting all the JS code, the older functions were getting retained. This PR fixes that issue by clearing the functions when the js object body is empty.

#### PR fixes following issue(s)
fixes #9585

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing
- [x] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSObject/Bug9585_spec.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { jsEditor, locators } = _;
+
+describe("List no functions on empty collection", () => {
+  it("should not show functions when whole code is deleted", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSObject/Bug9585_spec.ts:6]: Index `it` block

File: app/client/cypress/support/Pages/JSEditor.ts [hunk 2]
```diff
@@ -212,6 +212,16 @@ export class JSEditor {
...
+  public ClearJSObj() {
+    cy.get(this.locator._codeMirrorTextArea)
+      .first()
+      .focus()
+      .type(this.selectAllJSObjectContentShortcut, { force: true })
+      .type("{backspace}", { force: true });
+    this.agHelper.Sleep(2000); //Settling time for edited js code
+    this.agHelper.AssertAutoSave();
+  }
+
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/JSEditor.ts:224]: Can we try calling `_.jsEditor.EditJSObj("",false, true);` - to see if it works?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSObject/Bug9585_spec.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+    jsEditor.CreateJSObject(
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSObject/Bug9585_spec.ts:7]: nit: Since we are going to delete the js editor content & not really use it, simple JsObject also should do right?  ` _.jsEditor.CreateJSObject('return "Hello World";');`

File: app/client/cypress/support/Pages/JSEditor.ts [hunk 4]
```diff
@@ -355,5 +365,9 @@ export class JSEditor {
     this.agHelper.GetNClickByContains(this.locator._dropdownText, funName);
   }
 
+  public AssertFunctionDropdownValue(funName: string) {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/JSEditor.ts:368]: Can method be `AssertSelectedFunction()`

File: app/client/cypress/support/Pages/JSEditor.ts (hunk 2 above)
Comment (ravikp7) [reply app/client/cypress/support/Pages/JSEditor.ts:224]: I tried that first, but it didn't work.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSObject/Bug9585_spec.ts (hunk 3 above)
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSObject/Bug9585_spec.ts:7]: We want the functions to be populated first and then make sure that after deleting the code, the functions go away from the top selector dropdown. Hence, created that whole js object with functions.

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSObject/Bug9585_spec.ts:7]: No - by passing passing above syntax also - there are still 2 methods in JSObject. 
I meant we can reduce the parameters & length of the Js Object sent from spec, by creating above simple JS object which suffices this case still.

File: app/client/src/workers/Evaluation/JSObject/index.ts [hunk 5]
```diff
@@ -188,7 +189,9 @@ export function saveResolvedFunctionsAndJSUpdates(
     } catch (e) {
       //if we need to push error as popup in case
     }
-  } else {
+  }
+
+  if (!correctFormat) {
```
Comment (ohansFavour) [inline app/client/src/workers/Evaluation/JSObject/index.ts:194]: We might not need this change. If the body is empty, then the format is not correct. So the else block should work.

File: app/client/src/workers/Evaluation/JSObject/index.ts [hunk 6]
```diff
@@ -87,8 +87,9 @@ export function saveResolvedFunctionsAndJSUpdates(
 ) {
   jsPropertiesState.delete(entityName);
   const correctFormat = regex.test(entity.body);
+  const isEmptyBody = entity.body.trim() === "";
 
-  if (correctFormat) {
+  if (correctFormat || isEmptyBody) {
```
Comment (ohansFavour) [inline app/client/src/workers/Evaluation/JSObject/index.ts:92]: When the body is empty, I guess we only want to delete the functions right?, we don't need to do any additional AST parsing.

File: app/client/src/workers/Evaluation/JSObject/index.ts (hunk 5 above)
Comment (ravikp7) [reply app/client/src/workers/Evaluation/JSObject/index.ts:194]: When the body is empty, `correctFormat` is `false`, and we show the error in that case as well.

File: app/client/src/workers/Evaluation/JSObject/index.ts (hunk 6 above)
Comment (ravikp7) [reply app/client/src/workers/Evaluation/JSObject/index.ts:92]: We want the functions state to be cleared, running through this, it clears the state and the earlier functions don't show up anymore.

File: app/client/src/workers/Evaluation/JSObject/index.ts (hunk 5 above)
Comment (ohansFavour) [reply app/client/src/workers/Evaluation/JSObject/index.ts:194]: Got it

File: app/client/src/workers/Evaluation/JSObject/index.ts (hunk 6 above)
Comment (ohansFavour) [reply app/client/src/workers/Evaluation/JSObject/index.ts:92]: Yeah, I am suggesting that we move the "function clearing" bit out of the if statement. With the current implementation, when the body is empty, we still attempt to parse the function using AST.

Comment (ravikp7) [reply app/client/src/workers/Evaluation/JSObject/index.ts:92]: I understand your concern. But I'm usually not in favour of writing unnecessary `if/else` conditions if it doesn't have much impact on readability or performance.

In this case, since the body is empty string, even if we do the AST parsing, it'll have negligible/no effect on performance. If one pathway of code can serve the purpose, why write another one? I don't see any benefits here as per my knowledge. Please let me know your thoughts on this or if I'm missing something.

Comment (ohansFavour) [reply app/client/src/workers/Evaluation/JSObject/index.ts:92]: Yes, I think your concerns are valid. It makes sense.

**Review by ohansFavour — APPROVED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/JSObject/Bug9585_spec.ts [hunk 7]
```diff
@@ -0,0 +1,32 @@
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { jsEditor } = _;
+
+describe("List no functions on empty collection", () => {
+  it("1. should not show functions when whole code is deleted", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/JSObject/Bug9585_spec.ts:6]: Add Bug id to `it` also - which returns when this text is searched in vs code.

File: app/client/cypress/support/Pages/JSEditor.ts [hunk 8]
```diff
@@ -359,5 +369,9 @@ export class JSEditor {
     this.agHelper.GetNClickByContains(this._funcDropdownOptions, funName);
   }
 
+  public AssertSelectedFunction(funName: string) {
+    cy.get(`${this._funcDropdown} p`).contains(funName).should("exist");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/JSEditor.ts:373]: No direct locator. Move to a variable & call here.

File: app/client/cypress/e2e/Regression/ClientSide/JSObject/Bug9585_spec.ts (hunk 7 above)
Comment (ravikp7) [reply app/client/cypress/e2e/Regression/ClientSide/JSObject/Bug9585_spec.ts]: done

File: app/client/cypress/support/Pages/JSEditor.ts (hunk 8 above)
Comment (ravikp7) [reply app/client/cypress/support/Pages/JSEditor.ts]: done

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good.

**Review by Aishwarya-U-R — APPROVED** [review]
