### PR TITLE
fix: Unable to group widgets

### LINKED ISSUE #9032: [Bug]: Cmd G or grouping widget into container is not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user tires to draw and select widget to form as a container or drawing and selecting few widgets and pressing cmd+G is not working as expected.

[LOOM DEMO](https://www.loom.com/share/6721aba46fb84b428b74e9267dc7c23b)

### Steps To Reproduce

1.Launch appmsith app in release environment 
2.Drag and drop few widgets 
3.Try to draw and select few widget and press cmd+G or click on grouping icon and observe

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

While working on #8954, I didn't realise `pasteWidgetSaga` is being used for widget grouping also. That caused this issue.
The issue is fixed and a test is added to avoid regression.

Fixes #9032

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Open editor on an incognito window. Make sure you didn't copied any widget.
Try grouping a couple of widgets

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/unable-to-group 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 53.97 **(0.02)** | 42.7 **(0.54)** | 53.19 **(0)** | 55.56 **(-0.27)**</details>

### CODE REVIEW

**Comment by aswathkk** [comment]
test run: https://github.com/appsmithorg/appsmith/actions/runs/1435824246

**Comment by vivekverma2312** [comment]
@aswathkk Tested the DP and it's working fine now.

**Comment by aswathkk** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1438152875

**Comment by aswathkk** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1438268907

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 1]
```diff
@@ -754,7 +753,7 @@ function* pasteWidgetSaga(action: ReduxAction<{ groupWidgets: boolean }>) {
   }
 
   // to avoid invoking old copied widgets
-  if (!Array.isArray(copiedWidgetGroups)) return;
```
Comment (marks0351) [inline app/client/src/sagas/WidgetOperationSagas.tsx:757]: this code was to avoid using old copied widgets which were an array of objects, cud you add the new condition with an OR and retain the older condition as well.

Comment (marks0351) [reply app/client/src/sagas/WidgetOperationSagas.tsx:757]: old as in old way of implementation...used be an array and now its an object.

**Review by marks0351 — CHANGES_REQUESTED** [review]

**Comment by aswathkk** [comment]
test run: https://github.com/appsmithorg/appsmith/actions/runs/1438509334

**Review by marks0351 — APPROVED** [review]
