### PR TITLE
fix: Wrap JSON.stringify for text widget binding(suggested widgets)

### LINKED ISSUE #6568: [Bug]The bindings fails for Text widget when the user selects it from suggested widgets section
## Description

[What happened]The bindings fails for the Text widget when the user selects it from the suggested widgets section

### Steps to reproduce the behaviour:
1.connect to the any of the datasource 
2.run the query 
3.from the suggested widget section
4.select the Text widget

Actual Result: The binding fails for the text widget as in the screenshot
image

### Important Details

- Version: [Cloud]
- OS: [MacOS]
- Browser [chrome,]
- Environment [release]

### PR DESCRIPTION
**Pull request by akash-codemonk**
Wrap JSON.stringify for text widget binding while adding from suggested widgets.

## Description

To not show the widget as an error the binding is wrapped with JSON.stringify.

Fixes #6568 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/text-widget 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.85 **(0)** | 36.79 **(0)** | 33.54 **(0)** | 55.43 **(-0.01)**
 :red_circle: | app/client/src/components/editorComponents/ActionRightPane/SuggestedWidgets.tsx | 42.55 **(-0.93)** | 26.67 **(-1.9)** | 0 **(0)** | 43.48 **(-0.96)**
 :red_circle: | app/client/src/sagas/DebuggerSagas.ts | 17.18 **(-0.21)** | 5.07 **(-0.08)** | 17.65 **(0)** | 19.05 **(-0.13)**</details>

### CODE REVIEW

File: app/client/src/sagas/DebuggerSagas.ts [hunk 1]
```diff
@@ -373,6 +373,9 @@ function* deleteDebuggerErrorLogSaga(
   action: ReduxAction<{ id: string; analytics: Log["analytics"] }>,
 ) {
   const errors: Record<string, Log> = yield select(getDebuggerErrors);
+  // If no error exists with this id
```
Comment (rishabhsaxena) [inline app/client/src/sagas/DebuggerSagas.ts:376]: nitpick: can we add a comment here, saying why this was needed? In case it was something else apart from a null check

**Review by rishabhsaxena — DISMISSED** [review]

File: app/client/src/sagas/DebuggerSagas.ts (hunk 1 above)
Comment (akash-codemonk) [reply app/client/src/sagas/DebuggerSagas.ts:376]: It is a null check.

**Review by rishabhsaxena — APPROVED** [review]
