### PR TITLE
fix: misc git sync fixes / ui polish

### LINKED ISSUE #9196: [Task]: Move git request error handling away from the common api validation handler
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### LINKED ISSUE #9209: [Task]: Git sync issues
Summary (can ignore other comments on the thread)
- [x] #9751
- [x] #9758
- [x] #9831
- [x] Disconnect git flow (in progress)
- [x] When the user edits the application name in sub-branch other than master that particular application name will not be updated (@abhvsn), repro steps: create a child branch; rename app; refresh the page; the name is reset
- [x] When user delete a page and try to merge it with a master the internal server error is displayed (@abhvsn)
- [x] When the branch is deleted from the Git the branch should be deleted from the application (@AnaghHegde)
- [x] Throw an error while trying to switch to a remote branch when the local tracking branch exists (@AnaghHegde)
 - [x] Under Merge tab the conflict error is displayed with The branch committed change which is contradicting error (@RakshaKShetty could not repro this)
 - [x] Show merge success state, similar to commit and push success: https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=754%3A8621
- [x] Remove border for branch dropdown within the merge tab
- [x] Remove remote branches from the branch dropdown on the merge tab
- [x] Show count of uncommitted changes on the commit (+) button at the buttom bar similar to how we show it for pull button
- [x] Bottom bar icons (@rishabhsaxena)
  - [x] improve spacing between the icons
  - [x] the number badge looks a bit odd along with the icons
  - [x] update tooltip text (append changes): `commit and push changes`, `push changes`, `pull changes`
- [x] Remove redundant error and success toasts, if the success or the error state is already indicated on the UI or the success toast is distracting we should remove those (@rishabhsaxena)
- [x] Append (*) to the branch button, if we have uncommitted changes (@rishabhsaxena)
- [x] Display remote and local branches within the branch list:
  - [x] bottom bar (@rishabhsaxena)
  - [x] merge tab branch dropdown (@Debsourabh)
- [x] An icon on the application card to indicate the application is connected to git (@rishabhsaxena)
- [x] The view application and edit application link doesn't work in the readme file (@AnaghHegde)
- [x] Add a check for existing files within the repo, repos with files apart from common templates such as: `README.md`, `.gitignore`, `llicence` should be invalid (@AnaghHegde)
- [x] Update socket rooms to include branch for maintaining realtime cursors and concurrent editor warning (@rishabhsaxena )
- [x] Separate feature flag for git import (@rishabhsaxena )
- [x] Update generate key step UI: https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=1%3A47090 (@haojin111 )
- [x] `0 page updated` should say `0 pages updated`, similarly for queries(@haojin111 )
- [x] Remove push button(@haojin111 )
- [x] After signing up as a new user, on opening the git sync modal we get an error toast, (update error handling to hide the error toast for `/profile/default` api), related to #9196(@haojin111 )
- [x] Add option to use global config
- [x] Add latest deploy preview time: didn't appear until the duration was in minutes(@haojin111 )
- [x] Link `open repo` button with repo link(@haojin111 )
- [x] Git connection tab: on error the window doesn't scroll all the way to the bottom(@haojin111 )
- [x] Hide latest deploy preview until the app is published for the first time(@haojin111 )
- [x] Update banner styles for error and warning: https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A9285, https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=684%3A8619(@haojin111 )
- [x] Use large buttons as CTAs(@haojin111 )
- [x] Use `_` as the branch name separator, instead of `-`(@haojin111 )
- [x] Merge form: remove icon(@haojin111 )
- [x] Merge CTA moves down when the status is rendered, add offset to prevent that(@haojin111 )
- [x] Remove the % from the progress bar(@haojin111 )
- [x] Fix alignment for the skeletons on the deploy tab(@haojin111 )
- [x] Merge tab: add max height to the branch list(@haojin111 )
- [x] Fetch `merge status` message from the API, instead of a hardcoded message for error and success states (@rishabhsaxena )
- [x] Show progress bar after clicking on `Merge` CTA as the loading state(@haojin111 )
- [x] Edge case issues for the git user config in the connect tab (both before connection and post connection)(@haojin111 )
- [x] Generate key button should be disabled until a valid URL in entered, also the button shifts when the error is rendered below the URL input(@haojin111 )
- [x] The error alignment in the merge tab needs to be fixed(@haojin111 )
- [x] The generate Key button should be displayed only after the Remote URL has been (@haojin111 )
- [x] when the user clicks on the push icon the deploy tab should open(@haojin111 )
- [x] when branch name is too big and user hover on it the tooltip is not displayed(@haojin111 )
- [x] The dropdown alignment displayed for the git connect should be polished(@haojin111 )
- [x] after generating the deploy key before clicking on connect close the pop-up and open it again the Remote URL is not visible in the input box(@haojin111 )
- [x] Under the merge tab when the user searches for the branch name which is not present the pop up closes all of a sudden(@haojin111 )
- [x] under merge tab when the branch name is too big the complete name is not displayed in the dropdown (@haojin111 )
- [x] When the new user gets added to the old repo when the other users were working the New user can do his first push this causes the conflict in the Other user's app (expected)
- [x] The merge button should be disabled when the User merge the changes from the github (not in scope for v1)
- [x] User should not be allowed to add 2 different application in the same git repo (duplicate)
- [x] when the user switches between the tab in the pop the loader is displayed in the Deployed tab (expected, fetches status)
- [x] There is a delay in displaying the  changes update (is it due to the loading state?) loading state for the fetch status call

### PR DESCRIPTION
**Pull request by haojin111**
## Description

> Move to git sync error action from validateResponse on errorSaga to proper function inside of GitySyncSaga
> ConflictingInfo component is added on GitSync components

Fixes #9196, #9000
Related to #9209

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/9209-git-sync-issues 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.14 **(0.01)** | 37.05 **(-0.12)** | 33.9 **(-0.07)** | 55.64 **(0)**
 :green_circle: | app/client/src/actions/gitSyncActions.ts | 63.87 **(0.08)** | 100 **(0)** | 0 **(0)** | 75 **(0.49)**
 :red_circle: | app/client/src/api/GitSyncAPI.tsx | 38.46 **(-2.36)** | 0 **(-100)** | 6.67 **(0)** | 40.43 **(-1.79)**
 :red_circle: | app/client/src/components/ads/Dropdown.tsx | 64.67 **(-0.49)** | 50.84 **(-1.39)** | 40.68 **(-0.7)** | 64.47 **(-0.07)**
 :red_circle: | app/client/src/components/ads/Icon.tsx | 52.13 **(-0.14)** | 35.37 **(-0.21)** | 100 **(0)** | 52.01 **(-0.14)**
 :sparkles: :new: | **app/client/src/components/ads/ListSegmentHeader.tsx** | **63.64** | **100** | **0** | **63.64**
 :red_circle: | app/client/src/constants/messages.ts | 73.96 **(-0.07)** | 100 **(0)** | 22.96 **(-0.18)** | 79.72 **(0)**
 :green_circle: | app/client/src/pages/Editor/Canvas.tsx | 72.55 **(1.72)** | 35.71 **(0)** | 57.14 **(0)** | 72 **(1.79)**
 :red_circle: | app/client/src/pages/Editor/GlobalHotKeys.tsx | 62.4 **(-0.41)** | 28.57 **(0)** | 51.11 **(-2.38)** | 61.67 **(-0.4)**
 :sparkles: :new: | **app/client/src/pages/Editor/gitSync/utils.ts** | **50** | **0** | **0** | **33.33**
 :red_circle: | app/client/src/pages/Editor/gitSync/QuickGitActions/BranchButton.tsx | 50 **(3.57)** | 14.29 **(-19.04)** | 0 **(0)** | 54.84 **(2.84)**
 :red_circle: | app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx | 71.43 **(-0.61)** | 46.15 **(-3.85)** | 34.78 **(0)** | 73.12 **(-1.32)**
 :green_circle: | app/client/src/pages/Editor/gitSync/components/BranchList.tsx | 22.36 **(2.23)** | 10.67 **(-0.6)** | 0 **(0)** | 24.14 **(2.24)**
 :green_circle: | app/client/src/pages/common/CanvasMultiPointerArena.tsx | 25.61 **(1.56)** | 5.88 **(0)** | 0 **(0)** | 26.58 **(1.58)**
 :red_circle: | app/client/src/reducers/uiReducers/gitSyncReducer.ts | 12.24 **(-1.09)** | 100 **(0)** | 0 **(0)** | 12.24 **(-1.09)**
 :green_circle: | app/client/src/sagas/ErrorSagas.tsx | 57.76 **(1.46)** | 41.18 **(3.85)** | 38.89 **(0)** | 57.14 **(1.07)**
 :red_circle: | app/client/src/sagas/GitSyncSagas.ts | 10.66 **(-0.51)** | 0.74 **(-0.58)** | 6.67 **(0)** | 14 **(-0.79)**
 :sparkles: :new: | **app/client/src/sagas/WebsocketSagas/utils.ts** | **66.67** | **0** | **0** | **50**
 :red_circle: | app/client/src/selectors/gitSyncSelectors.tsx | 72.03 **(1.82)** | 23.81 **(-6.19)** | 17.95 **(-0.23)** | 64.38 **(3.09)**</details>

### CODE REVIEW

**Review by rishabhsaxena — COMMENTED** [review]
Hey @haojin111 , I think we should refactor the errors a bit:
- Instead of a common git sync error, let's maintain `connection` and `commit and push` errors separately
- Also instead of using the error state, for showing the pull button in the deploy tab we could use, `behindCount` and `isClean`, if there are no changes and `behindCount > 0` we could show the pull warning

File: app/client/src/pages/Editor/gitSync/components/ConflictInfo.tsx [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+    // bitbucket repo
+    if (new RegExp("bitbucket.org").test(originUrl)) {
+      const match = remoteUrl?.match(/\/\w+/g);
+      if (match && match.length > 2) {
+        remoteUrl = remoteUrl?.replace(
+          /bitbucket.org/,
+          match[1].substr(1) + "@bitbucket.org",
+        );
+      }
+    }
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/components/ConflictInfo.tsx:64]: Please add a comment or a test here to explain the use-case
Also, I think we should show the `open repo` button only for the hosts for whom we know how to construct the repo url. At the least, `github`, `gitlab` and `bitbucket` should be supported.

File: app/client/src/pages/Editor/gitSync/components/UserGitProfileSettings/index.tsx [hunk 2]
```diff
@@ -26,9 +26,17 @@ const LabelContainer = styled.div`
...
+const InputContainer = styled.div<{ isValid: boolean }>`
   display: flex;
   align-items: center;
+  margin-bottom: ${(props) => props.theme.spaces[props.isValid ? 7 : 12]}px;
+  & > div {
+    ${(props) =>
+      !props.isValid ? `border: 1px solid ${Colors.ERROR_RED};` : ""}
+    input {
+      ${(props) => (!props.isValid ? `color: ${Colors.ERROR_RED};` : "")}
+    }
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/components/UserGitProfileSettings/index.tsx:38]: QQ: error styles should already be a part of the `TextInput` component?

File: app/client/src/pages/Editor/gitSync/components/UserGitProfileSettings/index.tsx [hunk 3]
```diff
@@ -194,16 +203,12 @@ function UserGitProfileSettings({
...
           <TextInput
             dataType="text"
             defaultValue={authorInfo.authorName}
             disabled={disableInput}
-            errorMsg={
-              !authorInfo.authorName && !nameInputFocused && triedSubmit
-                ? "Author name cannot be empty"
-                : ""
-            }
+            errorMsg={nameInvalid ? "Author name cannot be empty" : ""}
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/components/UserGitProfileSettings/index.tsx:211]: We should move the string to `constants/messages`, it would be useful later for i18n

File: app/client/src/sagas/GitSyncSagas.ts [hunk 4]
```diff
@@ -75,13 +79,30 @@ function* commitToGitRepoSaga(
...
       applicationId,
     });
-    const isValidResponse: boolean = yield validateResponse({
-      ...response,
-      gitRequest: true,
-    });
+
+    if (!response?.responseMeta?.success) {
+      yield put({
+        type: ReduxActionErrorTypes.GIT_SYNC_ERROR,
```
Comment (rishabhsaxena) [inline app/client/src/sagas/GitSyncSagas.ts:85]: Not sure if we need a common `GIT_SYNC_ERROR`, I feel we should have separate errors for connect, commit and push and other operations

File: app/client/src/reducers/uiReducers/applicationsReducer.tsx [hunk 5]
```diff
@@ -411,6 +411,18 @@ const applicationsReducer = createReducer(initialState, {
...
   },
+  [ReduxActionTypes.TEMP_REMOTE_URL_INIT]: (
+    state: ApplicationsReduxState,
+    action: ReduxAction<string>,
+  ) => {
+    return {
+      ...state,
+      currentApplication: {
+        ...state.currentApplication,
+        tempRemoteUrl: action.payload,
```
Comment (rishabhsaxena) [inline app/client/src/reducers/uiReducers/applicationsReducer.tsx:422]: We should keep this key in the `gitSyncReducer` instead of the `applicationsReducer`

**Review by rishabhsaxena — COMMENTED** [review]
Hey @haojin111 have added a few minor comments

File: app/client/src/components/ads/Dropdown.tsx [hunk 6]
```diff
@@ -580,9 +652,21 @@ export function RenderDropdownOptions(props: DropdownOptionsProps) {
...
+            className="t--dropdown-option"
+            key={-1}
+            onClick={noop}
+            selected
+          >
+            <Text color={`${Colors.ERROR_RED} !important`} type={TextType.P1}>
+              {createMessage(NOT_OPTIONS)}
+            </Text>
+          </OptionWrapper>
+        )}
```
[the remark this answers is not in the document]
Comment (haojin111) [reply app/client/src/components/ads/Dropdown.tsx:666]: currently I removed that part

File: app/client/yarn.lock [hunk 7]
```diff
@@ -4116,7 +4116,7 @@ arg@^5.0.1:
   resolved "https://registry.yarnpkg.com/arg/-/arg-5.0.1.tgz#eb0c9a8f77786cad2af8ff2b862899842d7b6adb"
```
Comment (rishabhsaxena) [inline app/client/yarn.lock:4116]: nit: think we're not adding any new package here, so we could uncheck the changes in `yarn.lock`?

**Review by rishabhsaxena — COMMENTED** [review]
Couple of minor points, else LGTM!

File: app/client/src/constants/ReduxActionConstants.tsx [hunk 8]
```diff
@@ -916,6 +916,7 @@ export interface ApplicationPayload {
 export interface CurrentApplicationData extends ApplicationPayload {
   SSHKeyPair?: string;
   deployKeyDocUrl?: string;
+  tempRemoteUrl?: string; // for temperary git remote url
```
[the remark this answers is not in the document]
Comment (haojin111) [reply app/client/src/constants/ReduxActionConstants.tsx]: https://github.com/appsmithorg/appsmith/pull/9229/commits/75cb75f6a845913c7c6e23b73fc22fa8cf93b01e

File: app/client/src/components/ads/Dropdown.tsx [hunk 9]
```diff
@@ -425,8 +442,35 @@ const ErrorLabel = styled.span`
   color: ${Colors.POMEGRANATE2};
 `;
 
+const TextWrapper = styled.div`
+  overflow: hidden;
+  text-overflow: ellipsis;
+  white-space: nowrap;
+`;
+
+function TooltipWrappedText(
```
[the remark this answers is not in the document]
Comment (haojin111) [reply app/client/src/components/ads/Dropdown.tsx:453]: updated on this [commit](https://github.com/appsmithorg/appsmith/pull/9229/commits/de5f97ecfdb3024278007b01cd5460d571044c8f)

File: app/client/yarn.lock (hunk 7 above)
Comment (haojin111) [reply app/client/yarn.lock:4116]: I removed use-text-width yarn module, because we're using `isEllipsisActive` now

File: app/client/src/components/ads/Dropdown.tsx [hunk 10]
```diff
@@ -425,8 +444,35 @@ const ErrorLabel = styled.span`
...
+  return (
+    <Tooltip
+      boundary="window"
+      content={label}
+      disabled={!isEllipsisActive(targetRef.current)}
+      position={Position.TOP}
+    >
+      <StyledText ref={targetRef} {...textProps}>
+        {label}
+      </StyledText>
```
Comment (rishabhsaxena) [inline app/client/src/components/ads/Dropdown.tsx:469]:
```suggestion
      isEllipsisActive(targetRef.current) ? (
        <StyledText ref={targetRef} {...textProps}>
          {label}
        </StyledText>
      ): <Text type={TextType.P1}>{option.label}</Text>
```
Actually I meant adding ellipsis only if the tooltip is active

File: app/client/yarn.lock (hunk 7 above)
Comment (rishabhsaxena) [reply app/client/yarn.lock:4116]: got it, yeah I guess in that case we should remove the `yarn.lock` changes?

**Review by rishabhsaxena — COMMENTED** [review]
Hey @haojin111  just a couple minor comments

**Review by rishabhsaxena — APPROVED** [review]
