### PR TITLE
fix: RestApiPlugin get request raw body fix

### LINKED ISSUE #12343: [Bug]-[5600]:Evaluate Value not included in Body of GET Request.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user uses dynamic bindings in raw body of a GET request it does not get sent in the body of the request when it is ran despite it showing up in the evaluated pop up.

Screen Shot 2022-03-28 at 9 40 26 AM

### Steps To Reproduce

1. Create a GET request
2. Add a key-value in the raw body of the request, with the value being a dynamic binding.
3. Run the query and observe that the object is not included in the request.

### Public Sample App

_No response_

### Version

1.6.16

### PR DESCRIPTION
**Pull request by vaibh1297**
## Description

> RestApiPlugin fix for accepting raw body in get request.

Fixes #12343

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Unit Tests

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 1]
```diff
@@ -213,6 +218,67 @@ public void testValidSignature() {
...
+        final List<Property> queryParameters = List.of();
+
+        ActionConfiguration actionConfiguration = new ActionConfiguration();
+        actionConfiguration.setHeaders(headers);
+        actionConfiguration.setQueryParameters(queryParameters);
+        actionConfiguration.setHttpMethod(HttpMethod.GET);
+
+        actionConfiguration.setTimeoutInMillisecond("10000");
+
+        actionConfiguration.setPaginationType(PaginationType.URL);
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:252]: Should we should keep it as PaginationType.NONE, since we don't intend to use pagination ?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 2]
```diff
@@ -213,6 +218,67 @@ public void testValidSignature() {
...
+
+        actionConfiguration.setEncodeParamsToggle(true);
+
+        actionConfiguration.setPluginSpecifiedTemplates(List.of(new Property(null,true)));
+
+        actionConfiguration.setFormData(Collections.singletonMap("apiContentType", MediaType.TEXT_PLAIN_VALUE));
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:258]: Can you please check once if we do required this, since we are already setting the content type on line 240 as well ?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 3]
```diff
@@ -213,6 +218,67 @@ public void testValidSignature() {
...
+        String[] requestBodyList = {"abc is equals to {{Input1.text}}","{ \"abc\": {{Input1.text}} }",""};
+
+        String[] finalRequestBodyList = {"abc is equals to \"123\"","{ \"abc\": \"123\" }",""};
+
+        for (int i = 0; i < requestBodyList.length; i++) {
+
+            actionConfiguration.setBody(requestBodyList[i]);
+            Mono<ActionExecutionResult> resultMono = pluginExecutor.executeParameterized(null, executeActionDTO, datasourceConfiguration, actionConfiguration);
+
+            int currentIndex = i;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:269]: Instead of renaming the variable here, could we instead rename `i` to `requestBodyIndex` on line 264 itself ?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 4]
```diff
@@ -213,6 +218,67 @@ public void testValidSignature() {
...
+            StepVerifier.create(resultMono)
+                    .assertNext(result -> {
+                        assertTrue(result.getIsExecutionSuccess());
+                        assertNotNull(result.getBody());
+                        final ActionExecutionRequest request = result.getRequest();
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:274]: Instead of using `result.getRequest()` can you please check if `result.getBody()` can be used ? - reason being that APMU, the `request` object in `result` may actually be set by us as opposed to the remote service setting it.

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 4 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:274]: But request and response body will be different, how can we validate if response is correct ?

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 1 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 2 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:258]: Yes, this is required.

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 3 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java]: done

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 4 above)
Comment (vaibh1297) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:274]: Also executed this test on release branch as well but it was not passed.

**Review by sumitsum — APPROVED** [review]

**Review by sumitsum — CHANGES_REQUESTED** [review]
Some un-intended client side changes have crept in the PR. Can you please check once ?

**Review by sumitsum — APPROVED** [review]
