### PR TITLE
fix: workspace email website validation

### LINKED ISSUE #8970: [Bug]: Email and website format is not validated on Org settings page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User can type in an incorrect email or website address of any format on Org settings page and this is not currently validated by the system. But on refreshing the page this invalid value is not saved (field is empty on page refresh) for email but incorrect website value is saved.

On prod, if there was a valid email format before the invalid email was entered then on refresh the valid format replaces r recent change.

### Steps To Reproduce

1. Go to Org settings from home page
2. Enter an incorrect format for email/website (with spaces for example) and observe the no validation error displayed to a user
3. Refresh page and observe behavior as mentioned above

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by nsarupr**
## Description

Adding Validation on the Workspace's Email and Website on Backend APIs

Fixes #8970

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- testValidateIncomingWorkspaceValidEmail
- testValidateIncomingWorkspaceInvalidEmail
- testValidateIncomingWorkspaceValidWebsite
- testValidateIncomingWorkspaceInvalidWebsite

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java [hunk 1]
```diff
@@ -580,6 +586,16 @@ public Mono<Workspace> archiveById(String workspaceId) {
         });
     }
 
+    @Override
+    public void validateIncomingWorkspace(Workspace workspace){
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java:590]: Why do we need this to expose this? If it is just used in this service class can we make it private?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/constants/PatternConstants.java [hunk 2]
```diff
@@ -0,0 +1,7 @@
+package com.appsmith.server.constants;
+
+public class PatternConstants {
+    public final static String WEBSITE_PATTERN = "^(http://|https://)?(www.)?(([a-z0-9\\-]+)\\.)+([a-z]+)$";
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/constants/PatternConstants.java:4]: Can we please add a comment here with valid and invalid cases? it would be hard to understand the use case just by looking at the regex.

**Review by AnaghHegde — COMMENTED** [review]
Minor comments. Rest looks good to me.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/constants/PatternConstants.java (hunk 2 above)
Comment (nsarupr) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/constants/PatternConstants.java:4]: I have added the test cases for users to look at.
I have covered all the valid and invalid use cases.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java (hunk 1 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java:590]: IMO, we can do that change when required. For now, I would say let's keep it private.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/constants/PatternConstants.java (hunk 2 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/constants/PatternConstants.java:4]: IMO, Test cases are to ensure that we covered all the cases. But comments are usually added in the actual implementation. Adding test cases would not justify not adding comments.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java (hunk 1 above)
Comment (nsarupr) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java:590]: Although, won't be able to invoke it from the test case then.
In that case, we'll have to test the Update function of the repository directly.

**Review by AnaghHegde — DISMISSED** [review]

**Review by AnaghHegde — APPROVED** [review]

**Review by AnaghHegde — DISMISSED** [review]

**Review by AnaghHegde — APPROVED** [review]
