### PR TITLE
fix: Tooltip for long names in Entity Explorer

### LINKED ISSUE #6524: [Bug]-[100]:Long name of an entity in the entity explorer must be able to display a name on hover
Steps to reproduce:
1) Add a JS function
2) Click on the edit icon 
3) Add a long name 
and observe the entity explorer

Observation:
When a long name is added the name of the JS function gets truncated in the entity explorer and the user would not be able to view the entire name 

Expectation:
Since the user is unable to view the entire name of the function, when the user hovers on the name of the function in the entity explorer we can display the name as a tooltip

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Long names were not getting tooltips on the Entity explorer. This change will fix this by ensuring that the check for tooltips disabled is ran correctly and not with wrong values.

Screenshot 2022-07-07 at 1 43 40 PM

Fixes #6524 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Cypress Test:

- Add a short name and a long name entity
- Short name should not get a tooltip on hover
- Long name should get a tooltip on hover
- Renaming long name to a shorter name should not get a tooltip on hover

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/pages/Editor/Explorer/Entity/Name.tsx [hunk 1]
```diff
@@ -99,15 +99,20 @@ export const EntityName = React.memo(
...
     useEffect(() => {
       setUpdatedName(name);
     }, [name, setUpdatedName]);
 
+    // Check to show tooltip on hover
+    const nameWrapperRef = useRef<HTMLDivElement | null>(null);
+    const [showTooltip, setShowTooltip] = useState(false);
+    useEffect(() => {
+      setShowTooltip(!!isEllipsisActive(nameWrapperRef.current));
+    }, [updatedName, name]);
```
Comment (akash-codemonk) [inline app/client/src/pages/Editor/Explorer/Entity/Name.tsx:114]: There is a scenario where the user can resize the width of the explorer from large to small. Can we handle that as well?

**Review by akash-codemonk — CHANGES_REQUESTED** [review]

**Review by akash-codemonk — DISMISSED** [review]

**Review by akash-codemonk — APPROVED** [review]
