### PR TITLE
fix: Remove datasource connection from cache when datasource is deleted

### LINKED ISSUE #17352: [Bug]: Destroy datasource context and connection on deleting datasource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, we're not going through the cache and removing the connection entry, or closing any ongoing connection(s) when a datasource is deleted. This can bloat the number of connections that Appsmith creates to an given datasource.

### Steps To Reproduce

1. Create a new datasource
2. Run a query against it
3. Check the database for existing connection
4. Delete the query and datasource on Appsmith
5. Check the database for existing connection. It will still exist

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description

This PR makes sure that every time we delete a datasource, any possible connections created for that datasource are destroyed, both in the cache and in the connection pool.

Along with that, the PR also refactors the test datasource flow to bring more consistency in the way all plugins perform this action. The method is now only delegated the core testing flow, while the original method takes care of datasource creation, destruction, and result aggregation. In case testing only involves creation and destruction of the connection, plugins need not implement this method at all, for instance SQL plugins.

TODO:
1. Test each plugins' testDatasource flow manually:
- [x] Postgres
- [x] MySQL
- [x] MSSQL - Same as other SQL
- [x] Redshift - Same as other SQL in terms of code flow
- [x] S3
- [x] Redis
- [x] Mongo
- [ ] Arango
- [ ] DynamoDB
- [ ] ElasticSearch
- [ ] Firestore
- [x] GoogleSheets - N/A
- [x] JS - N/A
- [ ] Snowflake
- [ ] SMTP
Skipping manual tests for a few since they're automated and non-trivial to test ✅ 

2. Test delete datasource kills connection in DB ✅ 
3. Create test cases for testDatasource flows ✅ 
- [x] Postgres
- [x] MySQL - Already exists, passes
- [x] MSSQL
- [ ] Redshift - Cannot mock
- [ ] S3 - Cannot mock
- [x] Redis - Already exists, passes
- [x] Mongo
- [x] Arango - Already exists, passes
- [x] DynamoDB
- [x] ElasticSearch - Already exists, passes
- [x] Firestore 
- [x] GoogleSheets - N/A
- [x] JS - N/A
- [ ] Snowflake - Cannot mock
- [x] SMTP

4. Create test case for delete datasource flow ✅ 

Fixes #17352 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit tests
- Manual testing

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java [hunk 1]
```diff
@@ -3,13 +3,14 @@
...
+import org.springframework.context.annotation.Lazy;
 import org.springframework.stereotype.Service;
 
 @Service
 @Slf4j
 public class DatasourceContextServiceImpl extends DatasourceContextServiceCEImpl implements DatasourceContextService {
 
-    public DatasourceContextServiceImpl(DatasourceService datasourceService,
+    public DatasourceContextServiceImpl(@Lazy DatasourceService datasourceService,
                                         PluginService pluginService,
```
Comment (subrata71) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java:14]: Can you please state your reasoning for adding a lazy initializer on `DatasourceService` while others are eagerly initialized?

File: app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java [hunk 2]
```diff
@@ -330,32 +330,15 @@ public Set<String> validateDatasource(@NonNull DatasourceConfiguration datasourc
...
-                    )
-                    .onErrorResume(error -> Mono.just(new DatasourceTestResult(error.getMessage())))
-                    .subscribeOn(scheduler);
+        public Mono<DatasourceTestResult> testDatasource(DynamoDbClient connection) {
+            return Mono.fromCallable(() -> {
+                /*
+                 * - Creating a connection with false credentials does not throw an error. Hence,
+                 *   calling listTables() method to check validity.
+                 */
+                connection.listTables();
```
Comment (subrata71) [inline app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java:339]: Aren't we going to close that connection?

File: app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java [hunk 3]
```diff
@@ -975,28 +976,17 @@ public Set<String> validateDatasource(DatasourceConfiguration datasourceConfigur
...
-                            log.debug("Error closing S3 connection that was made for testing.", e);
-                            return new DatasourceTestResult(e.getMessage());
-                        }
-
                         return new DatasourceTestResult();
                     })
-                    .onErrorResume(error -> Mono.just(new DatasourceTestResult(amazonS3ErrorUtils.getReadableError(error))))
-                    .subscribeOn(scheduler);
+                    .onErrorResume(error -> Mono.just(new DatasourceTestResult(amazonS3ErrorUtils.getReadableError(error))));
         }
```
Comment (subrata71) [inline app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java:990]: Removing the `subscribeOn` part for some good reason maybe. What's that?

File: app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java (hunk 2 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java:339]: This is handled in the common code for the overridden testDatasource method now

File: app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java (hunk 3 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java:990]: This is handled in the common code for the overridden testDatasource method now

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java (hunk 1 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java:14]: We're ending up with a cyclic dependency between the two services. Had to lazy initialize so that the cycle does not make server error out on boot

File: app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java (hunk 2 above)
Comment (nidhi-nair) [reply app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java:339]: There are two versions of testDatasource now. The default implementation of the one that accepts a datasource configuration object takes care of opening and closing the connections. The other overridden method then only operates on the connection object to perform the actual test. This plugin uses the connection object method only.

**Review by subrata71 — APPROVED** [review]
