### PR TITLE
fix: Add pane issues

### LINKED ISSUE #33583: [Bug]: `N/A` displayed after creating a new query instead of an appropriate heading
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to create a new API query, we see `N/A` displayed instead of `APIs` for a quick moment.

### Steps To Reproduce

1. Click on `New query/API`
2. Click on `Rest API`.

**Expected:** The subheading in the entity pane should read `APIs`.
**Actual:** We see `N/A` displayed for a second before the appropriate heading gets displayed.

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

https://jam.dev/c/337385f4-5940-43e7-9a26-6577cb7e917c

### Version

Cloud

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Fixes issues in add pane 

Fixes #33583

## Automation

/ok-to-test tags="@tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9178183004>
> Commit: eeb8f4067fd18779380c0918ba9c4bd294b5134d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9178183004&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: app/client/src/ce/selectors/entitiesSelector.ts [hunk 1]
```diff
@@ -1499,30 +1499,33 @@ export const getQuerySegmentItems = createSelector(
...
-    });
+    const items: EntityItem[] = actions
+      .map((action) => {
+        let group;
+        const iconUrl = getAssetUrl(
+          pluginGroups[action.config.pluginId]?.iconLocation,
+        );
+        if (action.config.pluginType === PluginType.API) {
+          group = isEmbeddedRestDatasource(action.config.datasource)
+            ? "APIs"
```
Comment (sneha122) [inline app/client/src/ce/selectors/entitiesSelector.ts:1510]: Nit: can we please avoid these magic strings?

File: app/client/src/ce/selectors/entitiesSelector.ts [hunk 2]
```diff
@@ -1499,30 +1499,33 @@ export const getQuerySegmentItems = createSelector(
...
+            : datasourceIdToNameMap[action.config.datasource.id] ?? "APIs";
+        } else if (action.config.pluginType === PluginType.AI) {
+          group = isEmbeddedAIDataSource(action.config.datasource)
+            ? "AI Queries"
```
Comment (sneha122) [inline app/client/src/ce/selectors/entitiesSelector.ts:1514]: Same here for AI Queries

**Review by sneha122 — APPROVED** [review]
