### PR TITLE
Fix to enable scroll in sql query results.

### LINKED ISSUE #5042: [Bug] Scrolling doesn't work in the response for SQL queries
When the result of an SQL Query has more rows that can be displayed at once, it should allow the user to scroll to see more rows. But scrolling is disabled/not-working.

https://user-images.githubusercontent.com/120119/121625554-4add0700-ca91-11eb-8ba4-00c5bfeec1b6.mov

### Important Details

- Version: Cloud
- OS: macOS
- Browser: Firefox
- Environment: Production, <https://app.appsmith.com>

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fix to enable scroll in sql query results and disappearing scroll bar.
Dynamically adjust table virtualiser's height according to re-sizer's.

Fixes #5042 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/scroll_sql_query 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.34 **(-0.01)** | 35.31 **(-0.01)** | 31.92 **(-0.01)** | 53.85 **(-0.01)**
 :red_circle: | app/client/src/components/editorComponents/Debugger/Resizer/index.tsx | 15 **(-1.22)** | 28.57 **(-4.76)** | 0 **(0)** | 16.67 **(-1.51)**
 :red_circle: | app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx | 48.51 **(-1.49)** | 48.48 **(0)** | 0 **(0)** | 50.78 **(-0.81)**
 :red_circle: | app/client/src/pages/Editor/QueryEditor/Table.tsx | 24.56 **(-0.44)** | 8.33 **(-1.67)** | 0 **(0)** | 25.93 **(-0.49)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx [hunk 1]
```diff
@@ -688,7 +691,12 @@ export function EditorJSONtoForm(props: Props) {
         </TabContainerView>
 
         <TabbedViewContainer ref={panelRef}>
-          <Resizable panelRef={panelRef} />
+          <Resizable
+            panelRef={panelRef}
+            setContainerDimensions={
+              (height: number) => setTableBodyHeightHeight(height - 115) //accounts for the tab containers height and the table header.
```
Comment (hetunandu) [inline app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx:697]: Let's not hard code the height of the tabs here. If you cant derive it dynamically here, you can declare it as a variable and use that in the styles for the tab as well. Avoids confusion when this number changes for some reason

File: app/client/src/pages/Editor/QueryEditor/Table.tsx [hunk 2]
```diff
@@ -44,13 +45,13 @@ export const TableWrapper = styled.div`
...
     width: 100%;
+    height: 100%;
     .thead,
     .tbody {
       overflow: hidden;
     }
     .tbody {
-      overflow-y: scroll;
-      height: 100%;
+      height: calc(100% - 38px);
```
Comment (hetunandu) [inline app/client/src/pages/Editor/QueryEditor/Table.tsx:54]: Don't hard code the 38px.

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx (hunk 1 above)
Comment (arunvjn) [reply app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx]: Removed hardcoding here. Table component will now compute the height it needs to set to the virtualised list it contains.

**Review by hetunandu — APPROVED** [review]
