### PR TITLE
fix: URL replace issue in JS editor cmd click

### LINKED ISSUE #20217: [Bug]: Command click to JS functions reloads app when git is connected
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app is connected via git, the cmd click to a particular JS function will reload the whole app instead of just loading the function. 

### Steps To Reproduce

1. Have a git connected app
2. Have a JS Object with functions
3. In a widget add a binding to a particular JS function
4. CMD click to the JS function
5. Notice the loading sign for the whole app

### Public Sample App

_No response_

### Issue video log

https://user-images.githubusercontent.com/12022471/215469956-d15decbd-e526-49ed-be70-607d54fa8596.mov

### Version

Cloud

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

When an app is connected via git, it adds an extra query param to the URL. This messes up with the cmd click url changes when navigating to a particular JS function. This change will maintain such query params to avoid any reload because of url changes

> Fixes page load when navigating to a JS function via cmd click with git

Fixes #20217 

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by akash-codemonk — APPROVED** [review]

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/Command_Click_Navigation_spec.js [hunk 1]
```diff
@@ -1,10 +1,12 @@
 import reconnectDatasourceModal from "../../../../locators/ReconnectLocators";
 import { ObjectsRegistry } from "../../../../support/Objects/Registry";
 import { PROPERTY_SELECTOR } from "../../../../locators/WidgetLocators";
+import * as _ from "../../../../support/Objects/ObjectsCore";
 
 const homePage = ObjectsRegistry.HomePage;
 const agHelper = ObjectsRegistry.AggregateHelper;
 const commonLocators = ObjectsRegistry.CommonLocators;
+const ee = ObjectsRegistry.EntityExplorer;
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/Command_Click_Navigation_spec.js:9]: Local spec level objects are not needed when importing from 'ObjectsCore'

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/Command_Click_Navigation_spec.js [hunk 2]
```diff
@@ -136,18 +135,40 @@ describe("1. CommandClickNavigation", function() {
...
+    cy.wait(1000);
+
     cy.get(`[${NAVIGATION_ATTRIBUTE}="JSObject1.myFun1"]`).click({
       ctrlKey: true,
     });
 
     cy.assertCursorOnCodeInput(".js-editor", { ch: 1, line: 3 });
+
+    // Assert context switching works when going back to canvas
+    ee.SelectEntityByName("Page1", "Pages");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/Command_Click_Navigation_spec.js:158]: This can also be replaced with `_.ee.SelectEntityByName("Page1", "Pages");`
