### PR TITLE
fix: Avoid pasting list widget inside another list widget

### LINKED ISSUE #13609: [Bug]: App crash on List widget when try copy/paste
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[LOOM DEMO](https://www.loom.com/share/eda77e0771234aa992198df3c73406ed)

### Steps To Reproduce

1. Drag and drop a List widget
2. Copy list widget (CMD +C)
3. Move the cursor on the container
4. Pate it (CMZ+V)
5. Observe the app crash

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rahulramesha**
## Description

Verify that the widget selected is list widget or inside list widget when one of the copied widget is a list widget.

Fixes #13609 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Manual testing, cypress and jest

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: copyPasteListWidgetFix 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.57 **(-0.02)** | 38.35 **(-0.04)** | 35.84 **(0)** | 56.82 **(-0.01)**
 :red_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 68.93 **(-2.47)** | 45.16 **(-5.94)** | 68.49 **(0.43)** | 68.52 **(-2.66)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

File: app/client/src/sagas/WidgetOperationUtils.ts [hunk 1]
```diff
@@ -384,26 +384,71 @@ export const getSelectedWidgetIfPastingIntoListWidget = function(
...
+
+  //if the selected widget is a list widgets the return isListWidgetPastingOnItself as true
+  if (selectedWidgets.length === 1 && selectedWidgets[0].type === "LIST_WIDGET")
+    return { selectedWidgets, isListWidgetPastingOnItself: true };
+
+  //get list widget ancestor of selected widget if it has a list widget ancestor
+  const parentListWidgetId = document
+    .querySelector(
+      `.${POSITIONED_WIDGET}.${getBaseWidgetClassName(
+        selectedWidgets[0].widgetId,
```
Comment (sbalaji1192) [inline app/client/src/sagas/WidgetOperationUtils.ts:417]: We don't need to check the reset of the widget?

**Review by sbalaji1192 — APPROVED** [review]

File: app/client/src/sagas/WidgetOperationUtils.ts (hunk 1 above)
Comment (rahulramesha) [reply app/client/src/sagas/WidgetOperationUtils.ts:417]: Not sure I understand the question, could you please elaborate?

Comment (sbalaji1192) [reply app/client/src/sagas/WidgetOperationUtils.ts:417]: My bad. I thought selectedWidgets referred to widgets that are getting copied.But It's actually the widget we're pasting into, right?. Ignore the comment.

Comment (rahulramesha) [reply app/client/src/sagas/WidgetOperationUtils.ts:417]: Selected widgets are the widgets that are currently selected, if they are layout widgets like container or list widget we paste into it, but if it is a non-layout widget then we paste below it in the same canvas. Here we are checking if any parent is a list widget to avoid pasting a list widget on another list widget

Comment (sbalaji1192) [reply app/client/src/sagas/WidgetOperationUtils.ts:417]: Got it
