### PR TITLE
Fix map method being called on undefined variable  in MapComponent #3843

### LINKED ISSUE #3843: [Bug] TypeError: Cannot read property 'map' of undefined
Sentry Issue: [APPSMITH-N5](https://sentry.io/organizations/appsmith/issues/2311808869/?referrer=github_integration)

```
TypeError: Cannot read property 'map' of undefined
  at c (components/designSystems/appsmith/MapComponent.tsx:143:22)
  at apply (utils/hooks/useScript.tsx:83:9)
  at HTMLScriptElement.r (../../src/helpers.ts:87:17)
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by SatishGandham**
## Description
MapComponent markers prop can be empty, but it tries to access the map method on the prop without checking if its defined or it is an array.

Fixes #3843

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/designSystems/appsmith/MapComponent.tsx [hunk 1]
```diff
@@ -140,29 +140,30 @@ const MyMapComponent = withGoogleMap((props: any) => {
...
-              lng: marker.long,
-            });
-            props.selectMarker(marker.lat, marker.long, marker.title);
-          }}
-          onDragEnd={(de) => {
-            props.updateMarker(de.latLng.lat(), de.latLng.lng(), index);
-          }}
-        />
-      ))}
+      {Array.isArray(props.markers) &&
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/MapComponent.tsx:143]: I believe marker has a type here. Can we add that type?
`{ lat: number, lng: number, title: string }`

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]
