### PR TITLE
fix: modal autofocus fix issue #19957

### LINKED ISSUE #19957: [Bug]: Auto focus not working anymore in modal view
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have v1.8.14.1 running on my server. When I add a input field with Auto Focus within a modal view the field is focused when I open the modal.
I tried updating to v1.9.3.2 and this doesn't work any more. Same for the cloud hosting in the sample app I created it doesn't work any more.

### Steps To Reproduce

1. Click on Submit, the modal will open but the field is not focused

### Public Sample App

https://app.appsmith.com/app/untitled-application-1/page1-635160d1e15bd110fc705f51

### Issue video log

_No response_

### Version

both cloud and self-hosted v1.9.3.2

Front logo [Front conversations](https://app.frontapp.com/open/top_715e4)

### PR DESCRIPTION
**Pull request by vsvamsi1**
## Description

This fix checks the modal's content and check if any of the input widgets state has autofocused enabled. If it does it allows the html autoofocus attribute to resolve the focus state and if not the focus is shifted to the modal.

Fixes #19957 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/ModalWidget/widget/index.tsx [hunk 1]
```diff
@@ -318,9 +322,23 @@ const mapDispatchToProps = (dispatch: any) => ({
     });
   },
 });
-
-const mapStateToProps = (state: AppState) => {
+const isAutoFocusEnabled = (state: AppState, modalChildren: any) => {
+  if (!modalChildren) return false;
+  return modalChildren.some(({ widgetId }: { widgetId: string }) => {
+    const matchingWidget = Object.values(getDataTree(state)).find(
```
Comment (riodeuno) [inline app/client/src/widgets/ModalWidget/widget/index.tsx:328]: Instead of calling `find` on `getDataTree(state)`, can we instead get the data tree once, and use the `widgetName` index to find if it has `autoFocus`.

File: app/client/src/widgets/ModalWidget/widget/index.tsx [hunk 2]
```diff
@@ -311,9 +316,29 @@ const mapDispatchToProps = (dispatch: any) => ({
...
+const isAutoFocusEnabled = (
+  state: AppState,
+  modalChildrenWidget: WidgetProps[] | undefined,
+) => {
+  if (!modalChildrenWidget) return false;
+  return modalChildrenWidget.some((widget: WidgetProps) => {
+    const widgetState = getDataTree(state)[widget.widgetName] as DataTree;
+    return !!widgetState?.autoFocus;
+  });
+};
```
Comment (jsartisan) [inline app/client/src/widgets/ModalWidget/widget/index.tsx:328]:
```
if (!modalChildrenWidget) return false;
 const dataTree =  getDataTree(state);
  return modalChildrenWidget.some((widget: WidgetProps) => {
    const widgetState = dataTree[widget.widgetName] as DataTree;
    return !!widgetState?.autoFocus;
  });
```

**Comment by laveena-en** [comment]
@vsvamsi1 Modal background is not seen in the deployed version. Can you please check? https://www.loom.com/share/bad8c5dcc78a4e49add36a6b24a14907

**Comment by laveena-en** [comment]
Raised a separate bug report for the above callout since it's on release as well: https://github.com/appsmithorg/appsmith/issues/20405

**Comment by vsvamsi1** [comment]
> @vsvamsi1 Modal background is not seen in the deployed version. Can you please check? https://www.loom.com/share/bad8c5dcc78a4e49add36a6b24a14907

Hi @laveena-en this seems to be an existing issue in release. We can test this PR separately from that.

**Review by jsartisan — DISMISSED** [review]

**Comment by chandannkumar** [comment]
@vsvamsi1 Auto focus is not working in when modal, when Input widget is added inside Container widget
https://bthrujcsw8.vmaker.com/record/HxtlgMkfXG1CoInN

**Comment by chandannkumar** [comment]
Tested this and LGTM
- Tested Modal with auto focus enabled and disabled
- Tested Auto focus property on widgets added inside container types
- Tested on older apps

**Review by jsartisan — APPROVED** [review]
