### PR TITLE
fix: Combine app navigation tests where possible to reduce Cypress cloud costs

### LINKED ISSUE #21847: [Task]: Combine app navigation's cypress `it` blocks wherever possible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Combine cypress' `it` block wherever possible in app navigation to reduce cypress cloud costs

### PR DESCRIPTION
**Pull request by dhruvikn**
## Description
Reducing the number of `it` blocks in Cypress test cases helps us save costs on Cypress cloud. This PR does a refactor on Cypress tests written for App Navigation.

Fixes #21847 

## Type of change
- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?
- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AppNavigation/TopInline_spec.js [hunk 1]
```diff
@@ -130,33 +130,34 @@ describe("Test Top + Inline navigation style", function () {
     );
   });
 
-  it("8. Application name, share button, edit button, and user dropdown should be available in the app header", () => {
+  it("6. Application name, share button, edit button, and user dropdown should be available in the app header", () => {
     cy.get(appNavigationLocators.applicationName).should("exist");
     cy.get(appNavigationLocators.shareButton).should("exist");
     cy.get(appNavigationLocators.editButton).should("exist");
     cy.get(appNavigationLocators.userProfileDropdownButton).should("exist");
   });
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AppNavigation/TopInline_spec.js:138]: This can still go as part of next case :)

**Review by Aishwarya-U-R — APPROVED** [review]
