### PR TITLE
fix: Support evaluated value in nested property paths

### LINKED ISSUE #11913: [Bug]: evaluatedValue in property controls are undefined for nested property paths.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Property controls that have nested paths don't get the `evaluatedValue`. And this is because in  `getNestedEvalPath `function we are wrapping the path with square brackets
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/utils/DynamicBindingUtils.ts#L339

For a path that should come out as
`"__evaluation__.evaluatedValues.schema.__root_schema__.children.name.fieldType"`
is now coming out as
`"__evaluation__.evaluatedValues.['schema.__root_schema__.children.name.fieldType']"`

This would be fine for when we have "__evaluation__.evaluatedValue.['propertyA']" and used in conjunction with lodash's get function but not with a longer nested path.

### Steps To Reproduce

Check the `evaluatedValue` for a widget that has nested property control like the Button Group widget menu items.

### Public Sample App

_No response_

### Version

Cloud and Self hosted

### PR DESCRIPTION
**Pull request by ohansFavour**
Cause of issue

The `widgetProperties` object in the property control has its evaluated values in a populated structure.  Hence, the path for retrieving values needs to change accordingly.

Populated Structure

Screenshot 2022-03-29 at 16 31 25

Unpopulated Structure

Screenshot 2022-03-29 at 16 32 11

## Description

Fixes #11913 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Jest

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/evaluated-value-is-undefined-for-nested-property-paths 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.69 **(0)** | 37.09 **(0.01)** | 35.25 **(0)** | 55.95 **(0.01)**
 :green_circle: | app/client/src/utils/DynamicBindingUtils.ts | 83.98 **(0.09)** | 70.69 **(0.15)** | 75.86 **(0)** | 83.54 **(0.31)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 **(-0.95)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx [hunk 1]
```diff
@@ -329,7 +329,7 @@ const PropertyControl = memo((props: Props) => {
 
     const evaluatedValue = _.get(
       widgetProperties,
-      getEvalValuePath(dataTreePath, false),
+      getEvalValuePath(dataTreePath, false, true),
```
Comment (ashit-rath) [inline app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:332]: Suggestion: As we are adding a new param here which is another boolean, it is becoming a bit hard to understand what the first `false` is and the 2nd `true` in a quick glance. Instead, should we have just an `options` param which would have `fullPath` and `isPopulated`? It would give more context to the reader.

```js
getEvalValuePath(dataTreePath, { fullPath: false, isPopulated: true })
```

**Review by ashit-rath — APPROVED** [review]

File: app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx (hunk 1 above)
Comment (ohansFavour) [reply app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:332]: > Suggestion: As we are adding a new param here which is another boolean, it is becoming a bit hard to understand what the first `false` is and the 2nd `true` in a quick glance. Instead, should we have just an `options` param which would have `fullPath` and `isPopulated`? It would give more context to the reader.
> 
> ```js
> getEvalValuePath(dataTreePath, { fullPath: false, isPopulated: true })
> ```

This makes sense, I will update this.

Comment (ohansFavour) [reply app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:332]: This makes sense. I will update this.

**Review by ashit-rath — APPROVED** [review]

File: app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx [hunk 2]
```diff
@@ -329,7 +329,10 @@ const PropertyControl = memo((props: Props) => {
 
     const evaluatedValue = _.get(
       widgetProperties,
-      getEvalValuePath(dataTreePath, false),
+      getEvalValuePath(dataTreePath, {
+        isPopulated: true,
```
Comment (Rishabh-Rathod) [inline app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:333]: As I am not familiar with the term `isPopulated` referring to dot property accessor. Just wanted to confirm, if the term is common for developers?

Comment (ohansFavour) [reply app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx:333]: I wouldn't say it is. That is why I have added a description of the term "populated" in dynamicBindingsUtils as a comment.
