### PR TITLE
fix: Anvil fixes and enhancements post R0

### LINKED ISSUE #28577: [Task]: Handle widget visibility related cases in Anvil
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by marks0351**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
## Description
In this PR we are fixing
- suggested widgets feature in Anvil
- implementing isVisible prop based rendering in Anvil
- remove main canvas resizer in edit mode of Anvil
- cleaning up sniping mode based changes for anvil since its only used via sign posting flow which is a fixed layout only feature right now.
- adding buffer for main canvas DnD
- fixing glitches in first time DnD
#### PR fixes following issue(s)
Fixes #28577

> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [ ] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Comment by shadabbuchh** [comment]
DnD feels glitchy (similar to the previous DP): https://www.loom.com/share/da9b42a1a33c4379a5b366a7c444848e

**Comment by marks0351** [comment]
> DnD feels glitchy (similar to the previous DP): https://www.loom.com/share/da9b42a1a33c4379a5b366a7c444848e

Thanks for the inputs @shadabbuchh , we have this recorded as a needed performance enhancement. As discussed, I was mentioning about placement indicators glitches during the process of DnD.

**Comment by marks0351** [comment]
@shadabbuchh @Sripriya93 can we test for DnD in fixed and auto
- especially fixed layout containers that are not auto height enabled and have scroll enabled.
- similarly widgets where we can DnD like form, stats, modal, etc

**Comment by Sripriya93** [comment]
@marks0351 We are able to see horizontal scroll, double vertical scrolls and a zero at the left bottom corner in deploy mode for fixed layout, in review mode it as expected, we are seeing this issue only in deploy mode

image

**Comment by shadabbuchh** [comment]
> @marks0351 We are able to see horizontal scroll, double vertical scrolls and a zero at the left bottom corner in deploy mode for fixed layout, in review mode it as expected, we are seeing this issue only in deploy mode

We can see this in Auto layout mode as well.

**Comment by marks0351** [comment]
> > @marks0351 We are able to see horizontal scroll, double vertical scrolls and a zero at the left bottom corner in deploy mode for fixed layout, in review mode it as expected, we are seeing this issue only in deploy mode
> 
> We can see this in Auto layout mode as well.

@shadabbuchh @Sripriya93 this is a release branch bug, you can see this in promotional dp as well.
it seems to have been introduced in this [pr](https://github.com/appsmithorg/appsmith/pull/27043)

**Comment by Sripriya93** [comment]
QA completed. Working fine CC @shadabbuchh. If there is any more issues please comment.

File: app/client/src/layoutSystems/anvil/common/widgetComponent/AnvilWidgetComponent.tsx [hunk 1]
```diff
@@ -1,9 +1,15 @@
 import ErrorBoundary from "components/editorComponents/ErrorBoundry";
+import { invisible } from "constants/DefaultTheme";
 import WidgetComponentBoundary from "layoutSystems/common/widgetComponent/WidgetComponentBoundary";
 import React from "react";
+import styled from "styled-components";
 import type { BaseWidgetProps } from "widgets/BaseWidgetHOC/withBaseWidgetHOC";
 import Skeleton from "widgets/Skeleton";
-
+const WidgetVisibilityWrapper = styled.div<{
```
Comment (riodeuno) [inline app/client/src/layoutSystems/anvil/common/widgetComponent/AnvilWidgetComponent.tsx:8]: I was wondering if there is a need to add another DOM wrapper here? Basically, if we can identify an existing DOM wrapper, and use the `isVisible` prop to apply the styles for visibility. Wouldn't that work?

Also, this seems to be something that is added for both Editor and viewer. Is it possible that we are not concerned as this component will not be rendered in the viewer at all?

File: app/client/src/layoutSystems/anvil/integrations/sagas/draggingSagas.ts [hunk 2]
```diff
@@ -9,14 +9,151 @@ import type { CanvasWidgetsReduxState } from "reducers/entityReducers/canvasWidg
...
+    yield put(updateAndSaveLayout(updatedWidgets));
+    yield put(
+      selectWidgetInitAction(SelectionRequestType.One, [
+        newWidgetParams.newWidgetId,
+      ]),
+    );
+  }
+}
+
+function* addNewChildToDSL(
```
Comment (riodeuno) [inline app/client/src/layoutSystems/anvil/integrations/sagas/draggingSagas.ts:95]: Is this saga also something we reuse for the add widget operations? If so, that's a better design, as it decouples the existing add child sagas from the one in Anvil. Making sure that updates don't cause us to regress.

File: app/client/src/layoutSystems/common/canvasArenas/StickyCanvasArena.tsx [hunk 3]
```diff
@@ -24,6 +24,49 @@ interface StickyCanvasArenaRef {
   slidingArenaRef: RefObject<HTMLDivElement>;
 }
 
+const shouldUpdateCanvas = (
```
Comment (riodeuno) [inline app/client/src/layoutSystems/common/canvasArenas/StickyCanvasArena.tsx:27]: Please add a description of this function. I'm not fully sure what this function does.

File: app/client/src/widgets/withWidgetProps.tsx [hunk 4]
```diff
@@ -242,7 +242,11 @@ function withWidgetProps(WrappedWidget: typeof BaseWidget) {
       !isPreviewMode;
 
     widgetProps.mainCanvasWidth = mainCanvasWidth;
-    if (layoutSystemType !== LayoutSystemTypes.ANVIL) {
+    if (layoutSystemType === LayoutSystemTypes.ANVIL) {
```
Comment (riodeuno) [inline app/client/src/widgets/withWidgetProps.tsx:245]: Is this a bug fix? Seems like should not be calling any of the auto height functions at all. @marks0351 could you ideate on a wholistic fix here?

File: app/client/src/layoutSystems/anvil/common/widgetComponent/AnvilWidgetComponent.tsx (hunk 1 above)
Comment (marks0351) [reply app/client/src/layoutSystems/anvil/common/widgetComponent/AnvilWidgetComponent.tsx:8]: makes sense, let me move this to the AnvilFlexComponent

File: app/client/src/widgets/withWidgetProps.tsx (hunk 4 above)
Comment (marks0351) [reply app/client/src/widgets/withWidgetProps.tsx:245]: this is not auto height functionality but its the isVisible functionality that was written mixed together with Auto Height, I am going to leave fixed and auto heights code paths as is, since we will be restructuring this HOC in #27615. the widget and layout system based cleanup would be done in it.

File: app/client/src/layoutSystems/anvil/integrations/sagas/draggingSagas.ts (hunk 2 above)
Comment (marks0351) [reply app/client/src/layoutSystems/anvil/integrations/sagas/draggingSagas.ts:95]: This utility is something extracted out of add widget saga written for anvil. so that the same can be used for suggested widget addition coz its mostly the same flow with a few tweaks.

**Review by riodeuno — APPROVED** [review]
