### PR TITLE
fix: analytic events and binding UI issue fixed

### LINKED ISSUE #24810: [Feature]: New binding pane
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Design: https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=43-19957&mode=design&t=2qZMFmvPTKakZTEu-0

Notion: https://www.notion.so/appsmith/Activation-60c64894f42d4cdcb92220c1dbc73802?p=7c9a22fa873c4ab9a1a3df7921150398&pm=s

1. The suggested widgets should be shown along with their icons
    1. When I have a successful query, I should see the `Bindings` section as shown in the design (ignore the tooltip/tutorial for this story)
2. Connect to existing widget:
    1. if there are no existing widgets on the canvas, I should see message ‘No existing widgets’ like in the design above
    2. if there are connecting widgets:
        1. we need design for this
        2. [[Open question](https://theappsmith.slack.com/archives/C056PSE5X0E/p1687522136381749?thread_ts=1687520736.508259&cid=C056PSE5X0E)](https://theappsmith.slack.com/archives/C056PSE5X0E/p1687522136381749?thread_ts=1687520736.508259&cid=C056PSE5X0E), please create a new issue if the solution isn’t trivial. For now, leave the existing `Select widget` button as it is. On clicking this, the existing flow should continue, i.e., I should be taken to the canvas and I can snipe to an existing widget.
        
        
        
3. Connect to new widget:
    1. Upon clicking on one of the widgets, the existing snipe flow should kick in, i.e., I should be taken to the canvas and a new widget should be created with the proper data binding from the query response.
4. I should not see the `Relationships` section anymore

### Data

1. Snipe mode used by user
2. Which widget is used in snipe mode
3. A/B test: roughly 50% of users should see this new flow, the remaining should see the old flow
    1. I should be able to see on mixpanel the users who saw the new and old flows

### Why should this be worked on?

for activation project

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR adds analytical required in order to measure success of activation project.

The details of events can be found on [link](https://miro.com/app/board/uXjVM--NcEY=/?moveToWidget=3458764558687776936&cot=14&messenger=slack&utm_source=slack&utm_medium=messenger&utm_campaign=notifications&utm_content=unfurled_chat_link&utm_term=messenger_analytics)

**This PR adds following:**

_frontend events:_
WALKTHROUGH_SHOWN
WALKTHROUGH_DISMISSED
DATASOURCE_SCHEMA_SEARCH
DATASOURCE_SCHEMA_TABLE_SELECT

**This PR removes following:**

_frontend events:_
DATASOURCE_SCHEMA_FETCH_FAILURE
DATASOURCE_SCHEMA_FETCH_SUCCESS

_backend events:_
Datasource_Schema_Fetch_Failed
Datasource_Schema_Fetch_Success

**This PR updates following existing:**

_frontend events:_
DATASOURCE_SCHEMA_FETCH
CREATE_ACTION

_backend events:_
Datasource_Schema_Fetch

#### PR fixes following issue(s)
Fixes #24810 #24811 #24812 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java [hunk 1]
```diff
@@ -78,7 +78,7 @@ public Mono<DatasourceStructure> getStructure(DatasourceStorage datasourceStorag
         if (Boolean.FALSE.equals(datasourceStorage.getIsValid())) {
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java:78]: Should we remove the entire `if` block here ?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java [hunk 2]
```diff
@@ -128,7 +128,7 @@ public Mono<DatasourceStructure> getStructure(DatasourceStorage datasourceStorag
                 })
                 .onErrorResume(error -> analyticsService
                         .sendObjectEvent(
-                                AnalyticsEvents.DS_SCHEMA_FETCH_EVENT_FAILED,
+                                AnalyticsEvents.DS_SCHEMA_FETCH_EVENT,
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java:131]: Should we remove the entire `.onErrorResume` part ?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java [hunk 3]
```diff
@@ -138,7 +138,7 @@ public Mono<DatasourceStructure> getStructure(DatasourceStorage datasourceStorag
 
                     return analyticsService
                             .sendObjectEvent(
-                                    AnalyticsEvents.DS_SCHEMA_FETCH_EVENT_SUCCESS,
+                                    AnalyticsEvents.DS_SCHEMA_FETCH_EVENT,
```
Comment (sumitsum) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java:141]: Should we remove the entire `sendObjectEvent` part ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java (hunk 2 above)
Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java:131]: No @sumitsum Over here, I am simply renaming the event, and in the DS_SCHEMA_FETCH_EVENT, we are sending info like isSuccess and errors along with the event. If we remove the complete block, event wont be triggered at all

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java (hunk 3 above)
Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java:141]: Same here as well, if we remove the entire sendObjectEvent, no event will be triggered but we want generic Datasource_Schema_Fetch event to be there

**Review by sumitsum — APPROVED** [review]

**Comment by sumitsum** [comment]
Server side changes LGTM.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java (hunk 1 above)
Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java:78]: No the if block is required here, because getAnalyticsPropertiesForTestEventStatus in this function, second param is about success/failure.

**Review by Irongade — APPROVED** [review]
