### PR TITLE
fix: Improve cell overflow check logic when switching between table page

### LINKED ISSUE #13336: [Bug]-[450]:Table widget is not center aligned according to setting and alignment changes when page/table is refreshed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When table column values are center aligned and either page or table is refreshed then some of the values default to left-alignment. A page refresh reverts column back to user-defined center alignment though.

### Steps To Reproduce

1. Center align table data on any app with multiple pages or go to app at [this](https://release.app.appsmith.com/app/earworm/spotify-and-youtube-61ea4a44361846772cfb1180) location
2. Navigate between pages of the table widget as seen in the video and observe some column entries not center alinged as per user setting
3. Change selection from dropdown widget and observe that table refresh corrects the alignment as seen in the video
4. Observe that a page refresh also corrects alignment as per settings

[LOOM DEMO](https://www.loom.com/share/bb5ecc680be94b7cbd8799964fff2b4b)

Note: Steps to populate data on the table on this app incase you don't see any values:
Go to the [home page](https://release.app.appsmith.com/app/earworm/home-6219207a0276eb01d22fec5e) and click on the Spotify logo to go through the authorization.

### Public Sample App

https://release.app.appsmith.com/app/earworm/spotify-and-youtube-61ea4a44361846772cfb1180

### Version

Cloud

### PR DESCRIPTION
**Pull request by sbalaji1192**
Fixes #13336 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-autocomplete-alignment 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx | 58.33 **(1.19)** | 34.21 **(3.65)** | 28.57 **(0)** | 59.38 **(1.32)**</details>

### CODE REVIEW

**Comment by sbalaji1192** [comment]
@Bhavin789 CC

**Comment by Bhavin789** [comment]
> @Bhavin789 CC

@sbalaji1192 I think it is @techbhavin, not me 🙂

**Comment by sbalaji1192** [comment]
@Bhavin789 Oops. apologies :)

File: app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx [hunk 1]
```diff
@@ -39,7 +44,7 @@ function LinkWrapper(props: Props) {
     } else {
       updateToolTip(false);
     }
-  }, [ref]);
+  }, [props.children, ref.current]);
```
Comment (Tooluloope) [inline app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx:47]: I don't think `ref.current` is needed as a dependency

**Review by Tooluloope — DISMISSED** [review]

File: app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx (hunk 1 above)
Comment (sbalaji1192) [reply app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx:47]: We need to run the effect when the underlying element gets changed, right?

Comment (Tooluloope) [reply app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx:47]: This was what i meant https://stackoverflow.com/a/60476525

Comment (sbalaji1192) [reply app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx:47]: @Tooluloope Thanks for sharing. The issue on the StackOverflow seems different. Here when the auto tooltip component gets re-rendered, we want to run the effect if the underlying dom element itself gets changed.

Comment (sbalaji1192) [reply app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx:47]: This issue happened because we were not running the effect when the children element was getting changed when the user was switching between the page.

**Comment by chandannkumar** [comment]
Tested this PR by @ramsaptami  and it is working as expected

**Review by Tooluloope — APPROVED** [review]
