### PR TITLE
fix: Makes the auto dimension update to work on mobile view

### LINKED ISSUE #21587: [Bug]: Auto dimension updates are not working in mobile breakpoint
Automatic height/width updation isn't working if we are in mobile layout.

https://user-images.githubusercontent.com/10436935/226307253-07e3d30a-2a2a-4151-941d-f169422a01a5.mov

### LINKED ISSUE #21651: [Bug] [Widget Responsiveness][Auto layout]The textbox overflowing the designated borders in mobile viewport
https://www.loom.com/share/12798c9901954a42b315876004b08c5a

### PR DESCRIPTION
**Pull request by aswathkk**
Updates mobileBottomRow & mobileRightColumn while processing auto dimension updates.

Fixes #21587
Fixes #21651

### CODE REVIEW

File: app/client/src/sagas/AutoLayoutUpdateSagas.tsx [hunk 1]
```diff
@@ -254,13 +254,24 @@ function* processAutoLayoutDimensionUpdatesSaga() {
       ? 1
       : GridDefaults.DEFAULT_GRID_ROW_HEIGHT;
 
+    const widgetToBeUpdated = { ...widget };
+    if (isMobile) {
+      if (widgetToBeUpdated.mobileTopRow !== undefined)
```
Comment (prsidhu) [inline app/client/src/sagas/AutoLayoutUpdateSagas.tsx:259]: @aswathkk  flexWidgetUtils methods like getTopRow, setBottomRow will help improve readability of this block.
