### PR TITLE
fix: handleSubmit issue with redux form

### LINKED ISSUE #22946: [Bug]: Sentry exception from QueryEditorForm APPSMITH-5WA
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/3877084266

### Steps To Reproduce

NA

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

ignore

### PR DESCRIPTION
**Pull request by Irongade**
Redux form was causing apps to crash due to absence of handleSubmit being called on the forms.

Fixes #22946

- Bug fix (non-breaking change which fixes an issue)

- [ ] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx [hunk 1]
```diff
@@ -722,7 +723,7 @@ function CommonEditorForm(props: CommonFormPropsWithExtraParams) {
   return (
     <>
       <CloseEditor />
-      <Form onSubmit={props.handleSubmit}>
+      <Form onSubmit={handleSubmit(props.handleSubmit)}>
```
Comment (AmanAgarwal041) [inline app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx:726]: Why are we calling handleSubmit with handleSubmit as a param ?

Comment (Irongade) [reply app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx]: Good catch.

**Review by AmanAgarwal041 — APPROVED** [review]
