### PR TITLE
fix: postgres plugin blocking call

### LINKED ISSUE #36008: [Task]: Debugging Initial Blockhound Errors on /actions/execute API
### SubTasks

Post configuring the Blockhound locally and triggering it for /actions/execute API, I am getting the following error for a blocking call. 
**Blocking call! java.io.FileInputStream#readBytes**
https://drive.google.com/file/d/1DDeatHZlUYqK_r3V6LDKk2LnvpE54lul/view?usp=sharing

### PR DESCRIPTION
**Pull request by NilanshBansal**
## Description
This PR resolves the blockhound callout `Blocking call! java.io.FileInputStream#readBytes` in the /v1/actions/execute (POST) API call when used with Postgres Plugin. 
This blocking call was present in the PostgresPlugin.java

Fixes #36008   

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10666128697>
> Commit: 9224297c20722ebd5b2891e9e2f306f75e78ed1b
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10666128697&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Sanity`
> Spec:
> <hr>Mon, 02 Sep 2024 11:40:16 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **Chores**
	- Improved the readability and conciseness of the connection pool creation logic in the Postgres plugin, enhancing maintainability without affecting functionality.
	- Updated logging level from debug to info for better clarity on log messages.

### CODE REVIEW

File: app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java [hunk 1]
```diff
@@ -654,15 +654,11 @@ public Mono<HikariDataSource> datasourceCreate(DatasourceConfiguration datasourc
...
-                        return Mono.fromCallable(() -> {
-                            log.debug("Connecting to Postgres db");
-                            return createConnectionPool(datasourceConfiguration, maxPoolSize);
-                        });
+            return connectionPoolConfig.getMaxConnectionPoolSize().flatMap(maxPoolSize -> Mono.fromCallable(() -> {
+                        log.debug("Connecting to Postgres db");
+                        return createConnectionPool(datasourceConfiguration, maxPoolSize);
                     })
-                    .subscribeOn(scheduler);
+                    .subscribeOn(scheduler));
```
Comment (NilanshBansal) [inline app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java:661]: @nsarupr can you please review this? Also, can you check if it makes sense to call this on parallel scheduler or elastic scheduler also serves the purpose?

PS. I was not able to use the LoadShifter module in the appsmith-plugins directory.

**Review by sondermanish — APPROVED** [review]
