### PR TITLE
fix: Reset sync function fields on each update

### LINKED ISSUE #13197: [Bug]: Async functions turned into sync code is still executed on page load even though the option to do so is unavailable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a function containing async code is made into sync function - then any on page action that was previously set is retained and the sync is run on page load

### Steps To Reproduce

1. Add a JS object and mark an async function to run on page load
2. Remove async code in the function and refresh the page - observe that the previously marked async function is run again

[LOOM DEMO](https://www.loom.com/share/a74a18aa5c5940b3a51cc9f5eb4eb05b)

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description

Sync JS functions are not meant to ever run on page load automatically, since we have disabled the ability for users to set them to run on page load. This fix resets the relevant props on each update, so that the fields are not reused from when the function used to be recognized as async.

[Slack thread](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1658734579510539)

Fixes #13197 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually tested
- JUnit tested
- Cypress tested

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sondermanish — DISMISSED** [review]
The implementation is quite straight forward and tested.

File: app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts [hunk 1]
```diff
@@ -478,4 +478,44 @@ describe("JS Function Execution", function() {
...
+      jsObj = jsObjName;
+    });
+
+    // Switch to settings tab
+    agHelper.GetNClick(jsEditor._settingsTab);
+    // Enable all settings
+    jsEditor.EnableDisableAsyncFuncSettings("myFun1", true, true);
+
+    // Modify js object
+    jsEditor.CreateJSObject(syncJSCode, {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:512]: When you want to modify, you use 'jsEditor.EditJSObj()' method & not CreateJSObject()

Comment (nidhi-nair) [reply app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:512]: Oh I see, what is this property meant for in that case?

```
shouldCreateNewJSObj: false 
```

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:512]: OK, so there is a slight difference. Setting this to 'false' - will act like removing the contents of the JSObj & replacing with new body. Because of which it's not considered as edit to same function.
But EditObj - will also replace the content - **but without removing the previous content unlike previous** - hence by which its considered edit to same JSObj body.

Comment (nidhi-nair) [reply app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:512]: Oh I see, they both actually function in exactly the same way for my test. 😅 I'm not sure if that's by accident? I've switched to edit though. :)

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:512]: Haha lucky you! but editing same function body - we prefer EditObj

File: app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts [hunk 2]
```diff
@@ -478,4 +478,44 @@ describe("JS Function Execution", function() {
     agHelper.GetNClick(jsEditor._settingsTab);
     assertAsyncFunctionsOrder(FUNCTIONS_SETTINGS_RENAMED_DATA);
   });
+
+  it("10. Verify converting async functions to sync resets all settings", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:482]: Add Bug title to "it" -` it("10. Bug 13197 - Verify converting async functions to sync resets all settings", () => {`

**Review by Aishwarya-U-R — APPROVED** [review]
Approving Cypress test!

**Comment by Aishwarya-U-R** [comment]
@ramsaptami - Kindly test this & add the TestPlanApproved as applicable. Cypress stands verified.
