### PR TITLE
Throw a stale connection exception when authentication token expires in Snowflake

### LINKED ISSUE #6607: [Bug] Snowflake - Authentication token has expired. The user must authenticate again.
## Description

After leaving the application overnight and coming back to it the next day, the authentication token for the Snowflake connection expired and I cannot find a way to re-authenticate the connection.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create a new data source with a connection to Snowflake
2. Use connection in a table
3. Wait until the authentication token expires
4. Refresh the application
4. See error when the table tries to connect to Snowflake to refresh

### Important Details

- Version: Cloud
- Windows
- Chrome
- Production

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #6607

### CODE REVIEW

File: app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java [hunk 1]
```diff
@@ -88,6 +89,9 @@ public SnowflakePlugin(PluginWrapper wrapper) {
                                 rowsList.add(row);
                             }
                         } catch (SQLException e) {
+                            if (e instanceof SnowflakeReauthenticationRequest) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java:92]: Can you please add a JUnit TC for this ? So that we may be safe against any regression in future.

**Review by sumitsum — APPROVED** [review]
