### PR TITLE
fix: Fixed Icon Button onClick in disabled state and disabled style fixes for widgets.

### LINKED ISSUE #11957: [Bug]: Able to press a button and onclick of that button is executing when the button is in disabled state.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Able to press a button and onclick of that button is executing when the button is in disabled state. This issue started after recent update.

### Steps To Reproduce

1.Create a button
2.Add a function in Onclick of that button
3.Click on the button after disabling it

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #12030: [Bug]: Pagination previous/next is not proper
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2022-03-21 at 6 00 57 PM

### Steps To Reproduce

Drag and drop a table widget on canvas and observe

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by yaldram**
## Description

- Icon Button `onClick` was working when `isDisable: true`.
- Button Disabled textstyles were breaking in release, fixed it.
- Disabled styles were breaking for some widgets due to a color change in the themes file. Following widgets got affected
  - `Button Widget Disabled`, `Menu Button Widget Disabled`, `Icon Button Widget Disabled`, `Button Group Widget Disabled`.
  - `AudioRecorder Widget` Time color.
  - `Table Widget`, pagination and `Button Disabled styles` in the Table column

Fixes #11957
Fixes #12030

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested Manually on the Canvas.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/icon-button-disabled-click 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.6 **(0)** | 36.79 **(-0.01)** | 34.91 **(-0.01)** | 55.91 **(0)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :green_circle: | app/client/src/widgets/ButtonGroupWidget/component/index.tsx | 25 **(0.79)** | 11.2 **(0)** | 4.17 **(-0.18)** | 26.74 **(0.86)**
 :red_circle: | app/client/src/widgets/ButtonWidget/component/DragContainer.tsx | 66.67 **(-24.24)** | 40 **(-26.67)** | 66.67 **(-33.33)** | 69.23 **(-20.77)**
 :red_circle: | app/client/src/widgets/ButtonWidget/component/index.tsx | 49.49 **(-2.09)** | 28.72 **(-1.28)** | 45.45 **(0)** | 50 **(-1.19)**
 :red_circle: | app/client/src/widgets/IconButtonWidget/component/index.tsx | 22.22 **(-1.59)** | 5.71 **(-0.17)** | 0 **(0)** | 34.48 **(-2.56)**
 :red_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 29.74 **(0)** | 9.43 **(-0.05)** | 28.85 **(0)** | 29.4 **(0)**</details>

### CODE REVIEW

**Review by dilippitchika — APPROVED** [review]

**Comment by dilippitchika** [comment]
@yaldram can you also add some test-cases to prevent this from happening again?

**Comment by yaldram** [comment]
Hey @ashit-rath for more context on the `ButtonContainer` please check this Pull Request - https://github.com/appsmithorg/appsmith/pull/11627

**Comment by yaldram** [comment]
Hey @ashit-rath for more context on the `ButtonContainer` please check this Pull Request - https://github.com/appsmithorg/appsmith/pull/11627

**Review by ashit-rath — CHANGES_REQUESTED** [review]
Few callouts:

1. Can you add some cypress test for the icon button disabled state?

2. Please do make a list of places the QA should expect the color to get fixed (I think it's 5 places)

3. Can you please update the title of this PR to include the color change and also improve the description of this PR. Please do add more information as to why we are changing the color and mention the PR where this got changed.
The reason for doing the above exercise is to provide as much context as possible to anyone looking at this (like during release notes preparation or any dev for reference) and also leave breadcrumbs to how we came to conclusion to change this.

File: app/client/src/widgets/IconButtonWidget/component/index.tsx [hunk 1]
```diff
@@ -254,7 +254,10 @@ function IconButtonComponent(props: IconButtonComponentProps) {
       buttonVariant={buttonVariant}
       disabled={isDisabled}
       hasOnClickAction={hasOnClickAction}
-      onClick={onClick}
```
Comment (ashit-rath) [inline app/client/src/widgets/IconButtonWidget/component/index.tsx:257]: Any idea why the `onClick` is on this div rather than on the `StyledButton`?

File: app/client/src/widgets/ButtonWidget/component/DragContainer.tsx [hunk 2]
```diff
@@ -68,7 +68,12 @@ export function DragContainer(props: DragContainerProps) {
         buttonVariant={props.buttonVariant}
         disabled={props.disabled}
         loading={props.loading}
-        onClick={props.onClick}
+        onClick={(event) => {
```
Comment (ashit-rath) [inline app/client/src/widgets/ButtonWidget/component/DragContainer.tsx:71]: I don't understand this, IMO the `DragContainer` as the name implies should not have the `onClick` action. Also, in the places where this container is used, a button is placed as its child and that also has the same `onClick` function as its prop. Why are we need to do this?

File: app/client/src/widgets/IconButtonWidget/component/index.tsx (hunk 1 above)
Comment (yaldram) [reply app/client/src/widgets/IconButtonWidget/component/index.tsx:257]: Well the `StyledButton` is wrapped by the `div`, all the clicks will be registered on the `div` and not the `StyledButton`.

File: app/client/src/widgets/ButtonWidget/component/DragContainer.tsx (hunk 2 above)
Comment (yaldram) [reply app/client/src/widgets/ButtonWidget/component/DragContainer.tsx:71]: Yes we had to do this, you can refer to this Pull Request - https://github.com/appsmithorg/appsmith/pull/11627

**Comment by yaldram** [comment]
The color changes done in this Pull Request - 
1. Check `TimerContainer` for `AudioRecorderWidget`.
2. Check `Pagination` component for `TableWidget`.
3. Check `Buttons Disabled` for the `TableWidget`.

**Comment by yaldram** [comment]
Some Tests for the Q/A for `Button`, `IconButton`, `MenuButton`, `ButtonGroup` widgets  : - 
- Please check for the button Styles in both canvas and deploy mode they should work.
- Enable and Disabled states should function as expected.
- Please check if the Button Captcha is working as expected both in Enable and Disable mode.

**Comment by somangshu** [comment]
@yaldram from the internal conversation I found out that this change was made by @IAmAnubhavSaini / @albinAppsmith, Are the aware of the change we are doing here? Why was this change made in the first place?

Lets act quickly on this informing all the people and getting it merged to release

**Comment by vivekverma2312** [comment]
@yaldram Tested and it's working fine but I see the PR has conflicting files.

**Comment by IAmAnubhavSaini** [comment]
@yaldram change to `GREY_8` is not required in app/client/src/pages/Editor/gitSync/DisconnectGitModal.tsx

You can take release changes for resolving conflict.

**Comment by YogeshJayaseelan** [comment]
@yaldram Tested this PR and please find the status below,

* Original issue - Icon button OnClick on the disabled state is working fine

Observed an issue with button captcha 

Issue 1 - Clicking on the disabled Button widget generates the google Recaptcha token 

https://www.loom.com/share/73e1127b06fc45e6a1cebf33d4e7f632

**Comment by yaldram** [comment]
@YogeshJayaseelan both the above issues have been fixed.

**Review by ashit-rath — DISMISSED** [review]

**Comment by YogeshJayaseelan** [comment]
@yaldram Tested the fixes and did a round of sanity on button styles on the button widget family. They are working as expected

**Review by ashit-rath — COMMENTED** [review]
Good job!

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/IconButton_spec.js [hunk 3]
```diff
@@ -1,23 +1,26 @@
...
+const widgetsPage = require("../../../../locators/Widgets.json");
+const publishPage = require("../../../../locators/publishWidgetspage.json");
 
 describe("Icon Button Widget Functionality", function() {
   before(() => {
     cy.addDsl(dsl);
   });
 
-  it("check default buttonVariant with isJSConvertible", function() {
+  it.only("1. check default buttonVariant with isJSConvertible", function() {
```
[the remark this answers is not in the document]
Comment (yaldram) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/IconButton_spec.js:12]: Ah so sorry will push a fix.

**Review by ashit-rath — APPROVED** [review]
LGTM!
