### PR TITLE
fix: table search is not working properly for url colums

### LINKED ISSUE #23636: [Bug]: Search and filter functions in the table widget do not work as expected when the column is formatted as URL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change the `Column Type` to URL and then search for a string or use the filters (e.g. column, contains `XYZ`) string is not found.

Seems like it is searching a combination of display text and url and only works partially. 

### Steps To Reproduce

1. Insert a table widget with random data
2. Change one of the Columns to URL type
3. Add any URL to the fields in the column
4. Search for one of the string or use the filters to find the text in that column. It might work with the first few charcters.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Self hosted v1.9.19

### PR DESCRIPTION
**Pull request by berzerkeer**
## Description
- If we have a column type of `url` in table, the search considers the computed value and filters data based on that. But the search should take the display text as the search value to filter data.

#### PR fixes following issue(s)
Fixes #23636 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [x] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_FilteredTableData_spec.js [hunk 1]
```diff
@@ -43,4 +44,47 @@ describe("Table Widget V2 Filtered Table data in autocomplete", function () {
       );
     });
   });
+
+  it("3. Table Widget V2 Functionality to validate filtered table data for URL columntype", function () {
+    _.entityExplorer.SelectEntityByName("Table1");
```
Comment (sbalaji1192) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_FilteredTableData_spec.js:49]: 1. We need to validate search, filter and sorting with display text.

File: app/client/src/widgets/TableWidgetV2/widget/derived.test.js [hunk 2]
```diff
@@ -1083,6 +1083,118 @@ describe("Validates getFilteredTableData Properties", () => {
...
+          textSize: "PARAGRAPH",
+          fontStyle: "REGULAR",
+          enableFilter: true,
+          enableSort: true,
+          isVisible: true,
+          isDerived: false,
+          label: "awesome",
+          isAscOrder: undefined,
+          computedValue: ["W", "X", "Y", "Z"],
+          displayText: ["D.COM", "C.COM", "B.COM", "A.COM"],
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/widget/derived.test.js:1138]: switch this

Comment (sbalaji1192) [reply app/client/src/widgets/TableWidgetV2/widget/derived.test.js:1138]: add cases for search and filter

**Review by NandanAnantharamu — CHANGES_REQUESTED** [review]
As discussed please update the test in .ts and then send for review.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+    name: "B.COM",
+  },
+  {
+    name: "A.COM",
+  },
+];
+
+describe("Table V2 sort & filter using display text functionality", () => {
+  before(() => {
+    _.entityExplorer.DragDropWidgetNVerify("tablewidgetv2", 650, 250);
```
Comment (NandanAnantharamu) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:18]: import the relevant things from Objects Core like u have done for table, import entityExplorer/propPane and others on the same manner.
Eg: import {
  entityExplorer,
  agHelper,
  deployMode,
} from "../../../../support/Objects/ObjectsCore";

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+    _.entityExplorer.SelectEntityByName("Table1", "Widgets");
+    _.table.AddSampleTableData();
+    _.propPane.UpdatePropertyFieldValue("Table data", JSON.stringify(data));
+    cy.wait("@updateLayout");
+    cy.wait(1000);
```
Comment (NandanAnantharamu) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:23]: is this wait needed ? agHelper.Sleep() can be used if its really needed. since u r waiting for @updateLayout it should be fine and i suppose this hard wait is not needed

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+    _.propPane.TogglePropertyState("clientsidesearch", "On");
+    cy.wait(2000);
+    table.ChangeColumnType("name", "URL", "v2");
+    const colSettings = table._columnSettingsV2("name");
+    _.agHelper.GetNClick(colSettings);
+    _.propPane.UpdatePropertyFieldValue(
+      "Display text",
+      "{{['X','Y','Z'][currentIndex]}}",
+    );
+    cy.get(table._searchInput).type("X");
```
Comment (NandanAnantharamu) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:40]: please refer to relevant common helpers from agHelper.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+    table.ReadTableRowColumnData(0, 0, "v2").then(($cellData) => {
+      expect($cellData).to.eq("X");
+    });
+    cy.get(table._searchInput).clear();
```
Comment (NandanAnantharamu) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:44]: please refer to relevant common helpers from agHelper.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+    _.propPane.NavigateBackToPropertyPane();
+  });
+
+  it("2. should filter column using display text when filters are applied", () => {
+    const colSettings = table._columnSettingsV2("name");
+    _.agHelper.GetNClick(colSettings);
+    let columnType;
+    cy.get(".t--property-control-columntype span.rc-select-selection-item span")
```
Comment (NandanAnantharamu) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:52]: Dont use direct locators move to appropriate Helper Class, in this case it looks like propPane related one and hence move this to that support file and also look for relevant helper method to use invoke()

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+    });
+    table.RemoveFilter();
+    _.propPane.NavigateBackToPropertyPane();
+  });
+
+  it("3. should sort column using display text", () => {
+    const colSettings = table._columnSettingsV2("name");
+    _.agHelper.GetNClick(colSettings);
+    let columnType;
+    cy.get(".t--property-control-columntype span.rc-select-selection-item span")
```
Comment (NandanAnantharamu) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:78]: same as above

File: app/client/cypress/support/Pages/Table.ts [hunk 9]
```diff
@@ -602,4 +602,15 @@ export class Table {
     this.propPane.EnterJSContext("Table data", JSON.stringify(sampleTableData));
     this.ChangeColumnType("action", "Button", "v2");
   }
+
+  public sortColumn(columnName: string, direction: string) {
+    cy.get(
+      ` ${this._columnHeaderDiv(columnName)} .header-menu .bp3-popover2-target`,
```
Comment (NandanAnantharamu) [inline app/client/cypress/support/Pages/Table.ts:608]: use agHelper method for cy.get().click() , there are many common helper methods that u can use

File: app/client/cypress/support/Pages/Table.ts [hunk 10]
```diff
@@ -602,4 +602,15 @@ export class Table {
...
+    ).click({ force: true });
+    cy.get(".bp3-menu")
```
Comment (NandanAnantharamu) [inline app/client/cypress/support/Pages/Table.ts:610]: direct locator cannot be used, create a locator and then use. There is a wait for 500ms is it needed ? use agHlper.sleep() if its really neeeded

**Review by NandanAnantharamu — CHANGES_REQUESTED** [review]
added some review comments please address those.

**Review by sbalaji1192 — DISMISSED** [review]
Please go ahead after addressing nandan's callouts.

**Comment by NandanAnantharamu** [comment]
@Aishwarya-U-R i had reviewed the tests and @berzerkeer did resolve. Please cross check if you want.

**Review by NandanAnantharamu — DISMISSED** [review]
LGTM

File: app/client/cypress/support/Pages/PropertyPane.ts [hunk 11]
```diff
@@ -99,7 +99,8 @@ export class PropertyPane {
     "')]//input[@class='rc-select-selection-search-input']/parent::span/following-sibling::span//span";
   private _createModalButton = ".t--create-modal-btn";
   _pageName = (option: string) => "//a/div[text()='" + option + "']";
-
+  private _propPaneSelectedItem = (option: string) =>
+    `.t--property-control-${option} span.rc-select-selection-item span`;
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/PropertyPane.ts:103]: Can we add new locators at end?

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+  },
+  {
+    name: "A.COM",
+  },
+];
+
+describe("Table V2 sort & filter using display text functionality", () => {
+  before(() => {
+    entityExplorer.DragDropWidgetNVerify("tablewidgetv2", 650, 250);
+    entityExplorer.SelectEntityByName("Table1", "Widgets");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:23]: `DragDropWidgetNVerify` - will already open Widget's prop pane as done manually. Dont need this `SelectEntityByName` again.

**Review by Aishwarya-U-R — COMMENTED** [review]
@berzerkeer - Good work with Cypress tests 👍 , over-all nits to be corrected but no merging till they are corrected :)

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 13]
```diff
@@ -0,0 +1,102 @@
...
+    propPane.UpdatePropertyFieldValue("Table data", JSON.stringify(data));
+    cy.wait("@updateLayout");
+  });
+
+  beforeEach(() => {
+    entityExplorer.SelectEntityByName("Table1", "Widgets");
+  });
+
+  it("1. should search against display text when on client search", () => {
+    propPane.TogglePropertyState("clientsidesearch", "On");
```
[the remark this answers is not in the document]
Comment (berzerkeer) [reply app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:34]: Sorry, I don't get this one 😕

**Comment by berzerkeer** [comment]
> @berzerkeer - Good work with Cypress tests 👍 , over-all nits to be corrected but no merging till they are corrected :)

Haha alright, will fix those and update :D

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts [hunk 14]
```diff
@@ -0,0 +1,102 @@
...
+    agHelper.Sleep(1000);
+    table.ChangeColumnType("name", "URL", "v2");
+    const colSettings = table._columnSettingsV2("name");
+    agHelper.GetNClick(colSettings);
```
[the remark this answers is not in the document]
Comment (berzerkeer) [reply app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_DisplayText_spec.ts:38]: I am using the same selector in one other place within the same method.

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress code changes 👍🏻

**Review by sbalaji1192 — APPROVED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
