### PR TITLE
[Bug Fix] : Clone Application creates corrupted clone when interrupted.

### LINKED ISSUE #1707: [Bug] Cloned an app and the original one isn't available.
### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]

### PR DESCRIPTION
**Pull request by trishaanand**
## Description
The cloned application process, when interrupted by client cancellation (due to request timeout) leads to the flow getting cancelled mid way. This leads to a clone getting created (and can be viewed by the user) which wasn't created completely and is in a corrupted state. To solve this, two changes have been made :
1. When creating the clone, start with a deep copy of the original application without the pages being copied. This ensures that even if the cloning process stops midway, the cloned application does not point to the original application's pages.
2. Ensuring that if the client cancels the request, the server still finishes the entire request, whether or not the client is interested. This ensures that once triggered, the clone of the application would be available on the user's home screen in a sane state on home page refresh.
Fixes #1707 

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java [hunk 1]
```diff
@@ -613,6 +614,11 @@ public void createCloneApplication() {
                     assertThat(application.getName().equals("ApplicationServiceTest Clone Source TestApp Copy"));
                     assertThat(application.getPolicies()).containsAll(Set.of(manageAppPolicy, readAppPolicy));
                     assertThat(application.getOrganizationId().equals(orgId));
+                    List<ApplicationPage> pages = application.getPages();
+                    Set<String> pageIdsFromApplication = pages.stream().map(page -> page.getId()).collect(Collectors.toSet());
+                    Set<String> pageIdsFromDb = pageList.stream().map(page -> page.getId()).collect(Collectors.toSet());
+
+                    assertThat(pageIdsFromApplication.containsAll(pageIdsFromDb));
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java:621]: @trishaanand Should we have another test to ensure that pageIDs from testApplication and clonedApplication are not equal?

Comment (trishaanand) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java:621]: Fair. Let me add that.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java [hunk 2]
```diff
@@ -431,43 +430,58 @@ private void generateAndSetPagePolicies(Application application, PageDTO page) {
...
                 .flatMap(tuple -> {
                     Application sourceApplication = tuple.getT1();
                     String newName = tuple.getT2();
 
-                    sourceApplication.setId(null);
-                    sourceApplication.setIsPublic(false);
-                    sourceApplication.setName(newName);
-
+                    // Create a new application object and copy the essential fields which would remain the same over cloning
+                    Application newApplication = new Application();
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java:439]: Would you consider putting this object deep copy as a constructor in `Application` class? Will ensure that it's a re-usable construct that is easy to modify whenever we add new fields into the object.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java (hunk 1 above)
Comment (trishaanand) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java:621]: @nidhi-nair : Just checked. This is already happening in the following code section :
```StepVerifier
                .create(Mono.zip(pageIdListMono, testPageIdListMono))
                .assertNext(tuple -> {
                    List<String> pageIdList = tuple.getT1();
                    List<String> testPageIdList = tuple.getT2();

                    assertThat(pageIdList).doesNotContainAnyElementsOf(testPageIdList);
                })
                .verifyComplete();```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java [hunk 3]
```diff
@@ -431,43 +430,58 @@ private void generateAndSetPagePolicies(Application application, PageDTO page) {
...
+                                    })
+                            );
                 });
+
+        // Clone Application is currently a slow API because it needs to create application, clone all the pages, and then
+        // clone all the actions. This process may take time and the client may cancel the request. This leads to the flow
+        // getting stopped mid way producing corrupted clones. The following ensures that even though the client may have
+        // cancelled the flow, the cloning of the application should proceed uninterrupted and whenever the user refreshes
+        // the page, the cloned application is available and is in sane state.
+        // To achieve this, we use a synchronous sink which does not take subscription cancellations into account. This
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java:480]: Long shot: Is there a way to assert this behaviour in a test case? Basically, in the test case, we use Mockito to induce a delay during which the client closes it thread? We then fetch the applications again to check if the cloned app is still available. 

This is not a blocker comment. I'm just wondering if we can assert this behaviour to prevent such a bug from happening again.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java [hunk 4]
```diff
@@ -49,6 +50,25 @@
 
     String icon;
 
+    public Application(String name,
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java:53]: Suggested signature for a copy constructor:
```suggestion
    public Application(Application originalApp) 
```
Inside this function, you then decide what values you want to copy and which you don't want to copy. Makes it cleaner to invoke.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java [hunk 5]
```diff
@@ -431,43 +430,59 @@ private void generateAndSetPagePolicies(Application application, PageDTO page) {
...
                 .flatMap(tuple -> {
                     Application sourceApplication = tuple.getT1();
                     String newName = tuple.getT2();
 
-                    sourceApplication.setId(null);
-                    sourceApplication.setIsPublic(false);
-                    sourceApplication.setName(newName);
-
+                    // Create a new clone application object without the pages using the parametrized Application constructor
+                    Application newApplication = new Application(
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java:439]:
```suggestion
                    Application newApplication = new Application(originalApp);
                    newApplication.setPages(new ArrayList<>());
                    newApplication.setPublishedPages(new ArrayList<>());
```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java (hunk 3 above)
Comment (trishaanand) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java:474]: Added a test case but without using Mockito. Please review.

**Review by mohanarpit — APPROVED** [review]
