### PR TITLE
fix: update JS options

### LINKED ISSUE #2907: [Bug] Widget wise list of field that does not have JS option
Property Pane:

1. Button
    1. ButtonStyle
2. Chart
    1. ~~Allow horizontal scroll~~
    2. ~~Chart Data~~
3. Container
    1. Background Color
    2. ~~Scroll Contents~~
4. Dropdown
    1. ~~Selection Type~~
    2. ~~Option~~
    3. ~~Default Option~~
5. Radiobutton
    1. ~~Default Selected Value~~
6. Rich Text Editor
    1. ~~Default text~~
8. Text 
    1.  Text Align
    2.  Text Style
    3. ~~Enable Scroll~~
9. Forms
    1.  ~~Scroll Contents~~
    2. Background Color
10. Table 
    1. ~~Server Side Pagination~~
    2.~~Enable multi row selection~~

### PR DESCRIPTION
**Pull request by Tooluloope**
Fixes #2907 

## Type of change

- Update (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@vivekverma2312 kindly test this deploy preview

File: app/client/src/widgets/DropdownWidget.tsx [hunk 1]
```diff
@@ -42,6 +42,7 @@ class DropdownWidget extends BaseWidget<DropdownWidgetProps, WidgetState> {
             label: "Options",
             controlType: "INPUT_TEXT",
             placeholderText: 'Enter [{label: "label1", value: "value2"}]',
+            isJSConvertible: true,
```
Comment (riodeuno) [inline app/client/src/widgets/DropdownWidget.tsx:45]: I believe we can already add bindings here so  `isJSconvertible` may not be needed. Same goes for `Default Option`. Sorry, I did not take into account the fact the `input_text` control type by default supports bindings. Please make changes accordingly. Whenever, we see `isBindProperty` as `true`, it usually means that we don't need to add `isJSConvertible` as it would either already be added or may not be needed.

File: app/client/src/widgets/TextWidget.tsx [hunk 2]
```diff
@@ -112,8 +112,10 @@ class TextWidget extends BaseWidget<TextWidgetProps, WidgetState> {
                 value: "ITALIC",
               },
             ],
+            isJSConvertible: true,
             isBindProperty: false,
```
Comment (riodeuno) [inline app/client/src/widgets/TextWidget.tsx:116]: Here when we added `isJSConvertible` to `true`, `isBindProperty` should also become `true`, as we should now be able to add bindings to this property.

File: app/client/src/widgets/TextWidget.tsx [hunk 3]
```diff
@@ -134,8 +136,10 @@ class TextWidget extends BaseWidget<TextWidgetProps, WidgetState> {
               },
             ],
             defaultValue: "LEFT",
+            isJSConvertible: true,
```
Comment (riodeuno) [inline app/client/src/widgets/TextWidget.tsx:139]: Here when we added isJSConvertible to true, isBindProperty should also become true, as we should now be able to add bindings to this property.

**Review by riodeuno — CHANGES_REQUESTED** [review]
Please update the properties based on the comments.

File: app/client/src/widgets/DropdownWidget.tsx (hunk 1 above)
Comment (Tooluloope) [reply app/client/src/widgets/DropdownWidget.tsx:45]: Noted 👍

**Review by riodeuno — APPROVED** [review]
Looks good to me!

**Review by riodeuno — APPROVED** [review]

**Comment by somangshu** [comment]
@Tooluloope please checkout the failing tests

**Review by somangshu — DISMISSED** [review]
Approving to run tests

**Comment by somangshu** [comment]
@Tooluloope please check the failing test!

**Comment by Tooluloope** [comment]
> @Tooluloope please check the failing test!

Passes Locally and its unrelated
Screenshot 2021-06-08 at 14 34 56

**Comment by somangshu** [comment]
@yatinappsmith @NandanAnantharamu need you to respond here, Why are these tests failing?

**Comment by NandanAnantharamu** [comment]
> @yatinappsmith @NandanAnantharamu need you to respond here, Why are these tests failing?

@Tooluloope can pull the latest release and check if it's still failing

**Review by riodeuno — APPROVED** [review]

**Comment by somangshu** [comment]
@Tooluloope latest release merge required for failing tests

**Comment by somangshu** [comment]
Re-running jobs dont work, all tests failing. @Tooluloope merge the latest release once again. I dont see this failing anywhere else

**Review by mohanarpit — DISMISSED** [review]

**Comment by mohanarpit** [comment]
The earlier failures seen were related to Netlify. I've merged the latest release & re-ran the build on Netlify as well.

**Comment by mohanarpit** [comment]
@Tooluloope @somangshu All the tests are passing now. Please merge this if all looks good to you.

**Comment by Tooluloope** [comment]
> @Tooluloope @somangshu All the tests are passing now. Please merge this if all looks good to you.

Thanks @mohanarpit

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified this feature and Js option is available for all the above mentioned widgets except 'Container' and 'Form' - Background colour

Screenshot 2021-07-06 at 3 14 28 PM

**Comment by Tooluloope** [comment]
> @Tooluloope Verified this feature and Js option is available for all the above mentioned widgets except 'Container' and 'Form' - Background colour
> 
> Screenshot 2021-07-06 at 3 14 28 PM

@YogeshJayaseelan Fixed the issue

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
Rerunning all jobs, tests are failing
