### PR TITLE
Fix: List Widget issues

### LINKED ISSUE #5107: [Bug] List widgets overlap on copy paste
### Steps to reproduce the behaviour:

1. Drag and drop list widget
2. Copy list widget and paste on canvas
3. Observe that another list widget is overlaps the previous list widget
4. Also observed that  new list widget is pasted inside the list

### Important Details
- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: production

https://www.loom.com/share/21f8445e91434d7e81c885fe255eb350

### LINKED ISSUE #5730: [Bug] List Widgets issues
- [x] The list item container is getting an inner scroll when a widget is placed inside it
- [x] Multiple bindings inside the list widget don't work.
- [ ] #6455
- [x] Cannot select a list item once the list widget has been selected
- [x] Resizing a card is difficult once the entire widget is selected
- [ ] User struggled with populating list cards using currentItem
- [x] When the list widget width is low, the cards are difficult to resize
- [x] Need a way to unselect a card

### LINKED ISSUE #5868: [Bug] MappingException: Map key Sq.Yds. Per Carton contains dots but no replacement was configured! Make sure map keys do...
Sentry Issue: [APPSMITH-VA](https://sentry.io/organizations/appsmith/issues/2424076937/?referrer=github_integration)

```
MappingException: Map key Sq.Yds. Per Carton contains dots but no replacement was configured! Make sure map keys don't contain dots in the first place or configure an appropriate replacement!
    at org.springframework.data.mongodb.core.convert.MappingMongoConverter.potentiallyEscapeMapKey(MappingMongoConverter.java:873)
```

### LINKED ISSUE #6178: [Bug] User is not able to expand the item
Steps to reproduce:
1) Add a list widget
2) Add spacing between the list widget
3) Try to expand the list widget item

Observation:
It is observed that the list widget item does not expand and make it difficult to add a widget into the list item

Expectation:
It is expected that the item inside the widget must gets expanded

Video
https://www.loom.com/share/86d2c4f6aa3849b5b6637609e67e551f

### LINKED ISSUE #6319: [Bug] TypeError: can't convert undefined to object
Sentry Issue: [APPSMITH-10A](https://sentry.io/organizations/appsmith/issues/2548531031/?referrer=github_integration)

```
TypeError: can't convert undefined to object
  at componentDidUpdate (widgets/ListWidget/ListWidget.tsx:165:18)
  at apply (utils/WorkerUtil.ts:176:10)
  at r (../../src/helpers.ts:87:17)
...
(44 additional frame(s) were not displayed)
```

### LINKED ISSUE #6377: TypeError: Cannot read property 'type' of undefined
Sentry Issue: [APPSMITH-10E](https://sentry.io/organizations/appsmith/issues/2551124993/?referrer=github_integration)

```
TypeError: Cannot read property 'type' of undefined
  at checkIfPastingIntoListWidget (sagas/WidgetOperationUtils.ts:326:24)
  at call (sagas/WidgetOperationSagas.tsx:1517:26)
...
(17 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #5730
Fixes #5868
Fixes #5107
Fixes #6178
Fixes #6377
Fixes #6319 

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/list-widget-issues 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.4 **(-0.01)** | 34.92 **(-0.07)** | 31.5 **(-0.04)** | 53.94 **(-0.02)**
 :green_circle: | app/client/src/components/designSystems/appsmith/ContainerComponent.tsx | 93.1 **(-0.23)** | 60 **(0.91)** | 100 **(0)** | 93.1 **(-0.23)**
 :red_circle: | app/client/src/components/designSystems/appsmith/PositionedContainer.tsx | 100 **(0)** | 75 **(-6.25)** | 100 **(0)** | 100 **(0)**
 :green_circle: | app/client/src/components/editorComponents/DraggableComponent.tsx | 82.81 **(0.27)** | 60.47 **(0.95)** | 73.33 **(0)** | 82.76 **(0.3)**
 :red_circle: | app/client/src/components/editorComponents/ResizableComponent.tsx | 58.1 **(-1.47)** | 13.51 **(-3.44)** | 63.64 **(0)** | 58.65 **(-0.92)**
 :green_circle: | app/client/src/mockResponses/WidgetConfigResponse.tsx | 12.38 **(-0.24)** | 0 **(0)** | 0 **(0)** | 13.27 **(0.27)**
 :red_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 53.39 **(0.4)** | 31.18 **(-1.4)** | 66.67 **(-2.56)** | 51.89 **(-0.45)**
 :green_circle: | app/client/src/selectors/propertyPaneSelectors.tsx | 80.6 **(0.3)** | 67.35 **(0)** | 100 **(0)** | 85.96 **(0)**
 :green_circle: | app/client/src/utils/DynamicBindingUtils.ts | 89.78 **(-0.3)** | 80 **(-0.28)** | 78.26 **(2.07)** | 88.24 **(-0.36)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**
 :green_circle: | app/client/src/utils/hooks/useClickOpenPropPane.tsx | 83.02 **(1.2)** | 55.81 **(2.32)** | 100 **(0)** | 82 **(1.23)**
 :red_circle: | app/client/src/widgets/BaseWidget.tsx | 76.23 **(-3.28)** | 37.21 **(-4.65)** | 71.88 **(-6.25)** | 75.21 **(-3.42)**
 :green_circle: | app/client/src/widgets/ListWidget/ListWidget.tsx | 35.45 **(1.02)** | 23.7 **(-1.51)** | 28.26 **(0.35)** | 34.65 **(1.17)**
 :red_circle: | app/client/src/widgets/ListWidget/derived.js | 66 **(3.78)** | 41.67 **(0)** | 62.5 **(-7.5)** | 63.83 **(2.47)**</details>

### CODE REVIEW

**Review by marks0351 — APPROVED** [review]

**Review by marks0351 — APPROVED** [review]

File: app/client/src/sagas/WidgetOperationUtils.ts [hunk 1]
```diff
@@ -76,16 +76,19 @@ export const handleIfParentIsListWidgetWhilePasting = (
...
-          const { jsSnippets } = getDynamicBindings(value);
+          const { jsSnippets, stringSegments } = getDynamicBindings(value);
 
-          const modifiedAction = jsSnippets.reduce(
-            (prev: string, next: string) => {
-              return prev + `${next}`;
-            },
-            "",
-          );
+          const js = stringSegments
```
Comment (marks0351) [inline app/client/src/sagas/WidgetOperationUtils.ts:81]: can we extract these utils

File: app/client/src/widgets/DropdownWidget.tsx [hunk 2]
```diff
@@ -205,7 +205,7 @@ class DropdownWidget extends BaseWidget<DropdownWidgetProps, WidgetState> {
     // Check if the value has changed. If no option
     // selected till now, there is a change
     if (this.props.selectedOption) {
-      isChanged = !(this.props.selectedOption.value === selectedOption.value);
+      isChanged = !(this.props.selectedOptionValue === selectedOption.value);
```
Comment (marks0351) [inline app/client/src/widgets/DropdownWidget.tsx:208]: issue: not able to select same option in all items of list widget.

File: app/client/src/widgets/ListWidget/ListWidget.tsx [hunk 3]
```diff
@@ -222,21 +262,19 @@ class ListWidget extends BaseWidget<ListWidgetProps<WidgetProps>, WidgetState> {
...
-        : this.props.shouldScrollContents;
+    childWidgetData.canExtend = undefined;
     childWidgetData.isVisible = this.props.isVisible;
     childWidgetData.minHeight = componentHeight;
     childWidgetData.rightColumn = componentWidth;
     childWidgetData.noPad = true;
-    childWidgetData.bottomRow =
-      this.props.bottomRow * this.props.parentRowSpace - 45;
-    childWidgetData.shouldScrollContents = false;
+    childWidgetData.bottomRow = shouldPaginate
```
Comment (marks0351) [inline app/client/src/widgets/ListWidget/ListWidget.tsx:275]: lets have a constant for 34

**Review by marks0351 — CHANGES_REQUESTED** [review]

File: app/client/src/components/designSystems/appsmith/PositionedContainer.tsx [hunk 4]
```diff
@@ -48,10 +48,11 @@ export function PositionedContainer(props: PositionedContainerProps) {
       height: props.style.componentHeight + (props.style.heightUnit || "px"),
       width: props.style.componentWidth + (props.style.widthUnit || "px"),
       padding: padding + "px",
-      zIndex:
-        props.selected || props.focused
-          ? Layers.selectedWidget
-          : Layers.positionedWidget,
+      zIndex: props.focused
```
[the remark this answers is not in the document]
Comment (jsartisan) [reply app/client/src/components/designSystems/appsmith/PositionedContainer.tsx:51]: This was needed because when resizing the template widget, I wanted to show it over the other container

File: app/client/src/components/editorComponents/ResizableComponent.tsx [hunk 5]
```diff
@@ -234,7 +246,22 @@ export const ResizableComponent = memo(function ResizableComponent(
     // By setting the focus, we enable the control buttons on the widget
     selectWidget &&
       selectedWidget !== props.widgetId &&
-      selectWidget(props.widgetId);
+      parentWidgetToSelect?.widgetId !== props.widgetId &&
```
[the remark this answers is not in the document]
Comment (jsartisan) [reply app/client/src/components/editorComponents/ResizableComponent.tsx:249]: Not needed. Reverted this as we will be doing this as a separate feature.

File: app/client/src/widgets/ListWidget/ListWidget.tsx (hunk 3 above)
Comment (jsartisan) [reply app/client/src/widgets/ListWidget/ListWidget.tsx:276]: Done.

File: app/client/src/sagas/WidgetOperationUtils.ts (hunk 1 above)
Comment (jsartisan) [reply app/client/src/sagas/WidgetOperationUtils.ts]: Done.

File: app/client/src/components/editorComponents/DraggableComponent.tsx [hunk 6]
```diff
@@ -169,9 +179,16 @@ function DraggableComponent(props: DraggableComponentProps) {
 
   // When mouse is over this draggable
   const handleMouseOver = (e: any) => {
+    if (parentWidgetToOpen && !propertyPaneState.isVisible) {
```
[the remark this answers is not in the document]
Comment (jsartisan) [reply app/client/src/components/editorComponents/DraggableComponent.tsx]: Reverted this.

**Review by marks0351 — APPROVED** [review]
