### PR TITLE
fix: handles premium integrations based on release and license flags

### LINKED ISSUE #39738: Plan for the integrations usage if the business downgrade their plan (What will happen in such case?)

### PR DESCRIPTION
**Pull request by sneha122**
## Description
This Pr ensures that both release_external_saas_plugins_enabled and license_external_saas_plugins_enabled flags are being used for the frontend code as well where we show upcoming sections and premium tags

Fixes #39738   
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/14191640435>
> Commit: e35e9437b0ce13a7918202a0786034aaec2edf57
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=14191640435&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Tue, 01 Apr 2025 09:53:12 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a configurable flag that manages premium integration options for external SaaS plugins, set to off by default.
	- Added checks for premium integrations based on the new feature flag in relevant components.

- **Refactor**
	- Streamlined naming and logic for integration controls to enhance clarity in displaying premium plugins and data sources.
	- Improved error handling when accessing plugin icons to prevent runtime errors.

### CODE REVIEW

File: app/client/src/pages/Editor/IntegrationEditor/PremiumDatasources/index.tsx [hunk 1]
```diff
@@ -27,11 +27,11 @@ const PremiumTag = styled(Tag)`
 
 export default function PremiumDatasources(props: {
   plugins: PremiumIntegration[];
-  isGACEnabled?: boolean;
+  isIntegrationsEnabledForPaid?: boolean;
 }) {
   const [selectedIntegration, setSelectedIntegration] = useState<string>("");
   const handleOnClick = (name: string) => {
-    handlePremiumDatasourceClick(name, props.isGACEnabled);
+    handlePremiumDatasourceClick(name, props.isIntegrationsEnabledForPaid);
```
Comment (AmanAgarwal041) [inline app/client/src/pages/Editor/IntegrationEditor/PremiumDatasources/index.tsx:34]: Shouldn't here `isExternalSaasEnabled` flag be included ? @sneha122

Comment (sneha122) [reply app/client/src/pages/Editor/IntegrationEditor/PremiumDatasources/index.tsx:34]: @AmanAgarwal041 Not needed here because that flag is only for production instance, which means if we revoke access to paragon integrations for any user, they will simply see premium tag similar to normal user, they don't need to see soon tag

**Review by AmanAgarwal041 — DISMISSED** [review]

**Review by AmanAgarwal041 — APPROVED** [review]
