### PR TITLE
fix: added all js object functions as part of global data while checking isAsync

### LINKED ISSUE #10150: [Bug]: Success or error call for promises in a JS object does not work unless return keyword is used for the function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Success or error alert from a JS object inside a `promise` does not work until `return` keyword is used on the function.
For e.g., following code works only when the return keyword is present:
```
return myFunc1()
.then(() => showAlert("onSuccess call"))
.catch(() => showAlert("onError call"))
```

Similarly, when chaining JS, return needs to be included to execute onSuccess and onError code. For example:
```
Api1.run()
.then(() => { 
    Api2.run()
    return myFunc1()
```

[LOOM DEMO](https://www.loom.com/share/3250b3db55e642648d62e7ca21faf880)

### Steps To Reproduce

1. Use `promise` and display a showAlert on success and error
2. Observe all functions within `promise` call have been executed but success/error code is not executed.
3. Use return keyword before executing the promise and you'll see onSuccess and onError calls executed as expected

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by ApekshaBhosale**
## Description
When any js object function was referred to in any other js object function. it was throwing an error that `function does not exist`
The problem was while checking is a function asych, we were not adding existing functions which are stored as part of resolvedFunctions hence it was not getting the reference. I have added all resolvedFunctions as part of global data to avoid reference errors

Fixes #10150 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: critical-10150 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.96 **(-0.01)** | 36.64 **(-0.01)** | 34.67 **(-0.01)** | 55.47 **(-0.01)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/workers/DataTreeEvaluator.ts | 77.58 **(-0.25)** | 61.15 **(0)** | 75 **(-0.86)** | 77.32 **(-0.27)**
 :red_circle: | app/client/src/workers/evaluate.ts | 89.34 **(-4.57)** | 72.22 **(-5.91)** | 82.61 **(-7.87)** | 88.79 **(-4.79)**</details>

### CODE REVIEW

File: app/client/src/workers/evaluate.ts [hunk 1]
```diff
@@ -323,6 +327,17 @@ export function isFunctionAsync(userFunction: unknown, dataTree: DataTree) {
     Object.keys(dataTreeWithFunctions).forEach((datum) => {
       GLOBAL_DATA[datum] = dataTreeWithFunctions[datum];
     });
+    if (!isEmpty(resolvedFunctions)) {
+      Object.keys(resolvedFunctions).forEach((datum: any) => {
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/evaluate.ts:331]: nitpick:-

`datum` type is known to be string, here we could avoid use of any for it.

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM
