### PR TITLE
Fix explorer entity icon alignment

### LINKED ISSUE #2354: [Bug] Entity explorer icons are not aligned properly

### PR DESCRIPTION
**Pull request by akash-codemonk**
Fixes #2354

### CODE REVIEW

File: app/client/src/pages/Editor/Explorer/Entity/index.tsx [hunk 1]
```diff
@@ -156,7 +156,9 @@ export const Entity = forwardRef(
             disabled={!!props.disabled}
             className={`${EntityClassNames.COLLAPSE_TOGGLE}`}
           />
-          <span onClick={handleClick}>{props.icon}</span>
+          <span style={{ lineHeight: "0px" }} onClick={handleClick}>
```
Comment (riodeuno) [inline app/client/src/pages/Editor/Explorer/Entity/index.tsx:159]: Please use styled-components for this style.

**Review by riodeuno — APPROVED** [review]
