### PR TITLE
FIX #4813 : display filter count and highlighted filter button

### LINKED ISSUE #4813: [Bug] Numbering for Table filtering  is not displayed
Steps to reproduce:
1) Add a Table
2) Add a filter 
and observe

Observation
It is observed that the number of filters added are not displayed to the user 

Expectation:
It is expected that the numbering must be displayed to user which would help them to understand that filter is added into the table

### PR DESCRIPTION
**Pull request by vibhandikyash**
Fixes #4813 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/4813-displayed-count-for-table-filtering 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.69 **(-1.6)** | 32.93 **(-2.34)** | 29.64 **(-2.24)** | 52.17 **(-1.63)**
 :red_circle: | app/client/src/actions/widgetActions.tsx | 74.58 **(-1.42)** | 0 **(0)** | 27.78 **(1.11)** | 65 **(-2.65)**
 :red_circle: | app/client/src/api/Api.ts | 85.19 **(0)** | 30 **(-10)** | 66.67 **(0)** | 85.19 **(0)**
 :red_circle: | app/client/src/api/ApiUtils.ts | 65.38 **(-2.54)** | 45.71 **(-2.86)** | 80 **(0)** | 62.5 **(-2.81)**
 :red_circle: | app/client/src/api/PageApi.tsx | 55 **(-15)** | 0 **(-50)** | 7.14 **(-14.29)** | 55.26 **(-15.79)**
 :red_circle: | app/client/src/comments/utils.ts | 91.43 **(-0.88)** | 12.5 **(-12.5)** | 66.67 **(0)** | 89.66 **(-0.97)**
 :red_circle: | app/client/src/comments/CommentCard/CommentCard.tsx | 75.16 **(-0.15)** | 68.93 **(-0.23)** | 43.9 **(0)** | 75.84 **(-0.16)**
 :red_circle: | app/client/src/comments/inlineComments/AddCommentInput.tsx | 71.84 **(-0.28)** | 41.67 **(-0.83)** | 63.16 **(0)** | 72.73 **(0.51)**
 :green_circle: | app/client/src/comments/inlineComments/useOrgUsers.tsx | 100 **(0)** | 100 **(25)** | 100 **(0)** | 100 **(0)**
 :red_circle: | app/client/src/components/ads/MentionsInput.tsx | 65.79 **(0)** | 36.54 **(-3.04)** | 27.27 **(0)** | 63.77 **(0)**
 :red_circle: | app/client/src/components/editorComponents/ActionCreator.tsx | 34.42 **(-0.25)** | 23.22 **(0)** | 21.11 **(-1.11)** | 33.68 **(0)**
 :red_circle: | app/client/src/components/editorComponents/ApiResponseView.tsx | 50 **(-2.86)** | 32.79 **(-2.69)** | 0 **(0)** | 52.86 **(-1.55)**
 :green_circle: | app/client/src/components/editorComponents/DragLayerComponent.tsx | 81.82 **(0.34)** | 38 **(0)** | 100 **(0)** | 80.39 **(0.39)**
 :red_circle: | app/client/src/components/editorComponents/DraggableComponent.tsx | 82.76 **(-0.29)** | 61.54 **(0)** | 73.33 **(0)** | 82.69 **(-0.33)**
 :red_circle: | app/client/src/components/editorComponents/DropTargetComponent.tsx | 62.89 **(-0.38)** | 38.36 **(0)** | 43.75 **(0)** | 58.14 **(-0.48)**
 :red_circle: | app/client/src/components/editorComponents/ResizableComponent.tsx | 56.98 **(-0.49)** | 22.95 **(0)** | 60 **(0)** | 55.95 **(-0.52)**
 :red_circle: | app/client/src/components/editorComponents/Debugger/DebuggerTabs.tsx | 55.17 **(-1.5)** | 100 **(0)** | 0 **(0)** | 61.54 **(-1.42)**
 :green_circle: | app/client/src/components/editorComponents/Debugger/index.tsx | 90.91 **(2.34)** | 50 **(0)** | 91.67 **(0)** | 90.91 **(2.34)**
 :red_circle: | app/client/src/components/editorComponents/GlobalSearch/index.tsx | 62.7 **(0)** | 14.84 **(-2.32)** | 42.5 **(0)** | 62.13 **(-0.22)**
 :red_circle: | app/client/src/components/editorComponents/WidgetNameComponent/index.tsx | 81.25 **(-0.38)** | 68.42 **(0)** | 90 **(0)** | 80.43 **(-0.42)**
 :red_circle: | app/client/src/constants/IconConstants.tsx | 100 **(0)** | 92.86 **(-7.14)** | 100 **(0)** | 100 **(0)**
 :green_circle: | app/client/src/constants/messages.ts | 71.75 **(0.02)** | 100 **(0)** | 14.56 **(0.07)** | 75.69 **(-0.09)**
 :red_circle: | app/client/src/constants/routes.ts | 80.99 **(-1.94)** | 34.15 **(-8.53)** | 58.82 **(-5.89)** | 77.88 **(-3.25)**
 :red_circle: | app/client/src/icons/ControlIcons.tsx | 55.42 **(-1.21)** | 100 **(0)** | 7.5 **(-2.5)** | 55.42 **(-1.21)**
 :red_circle: | app/client/src/icons/MenuIcons.tsx | 54.05 **(-10.81)** | 100 **(0)** | 0 **(-23.53)** | 54.05 **(-10.81)**
 :red_circle: | app/client/src/icons/WidgetIcons.tsx | 54.17 **(-12.5)** | 100 **(0)** | 4.35 **(-26.08)** | 54.17 **(-12.5)**
 :red_circle: | app/client/src/normalizers/CanvasWidgetsNormalizer.tsx | 90 **(-10)** | 100 **(0)** | 66.67 **(-33.33)** | 90 **(-10)**
 :red_circle: | app/client/src/pages/Editor/GlobalHotKeys.tsx | 52.44 **(-0.57)** | 0 **(0)** | 35.48 **(0)** | 50 **(-0.63)**
 :red_circle: | app/client/src/pages/Editor/ToggleModeButton.tsx | 74.29 **(-2.72)** | 45.45 **(-4.55)** | 46.67 **(-0.7)** | 72.31 **(-2.05)**
 :red_circle: | app/client/src/pages/Editor/WidgetCard.tsx | 36.11 **(-1.73)** | 50 **(0)** | 0 **(0)** | 40.63 **(-1.79)**
 :red_circle: | app/client/src/pages/Editor/WidgetsEditor.tsx | 88.89 **(-1.59)** | 59.38 **(-12.5)** | 100 **(0)** | 88.33 **(-1.67)**
 :red_circle: | app/client/src/pages/Editor/routes.tsx | 37.88 **(-0.93)** | 22.22 **(0)** | 6.67 **(0)** | 42.11 **(-0.99)**
 :red_circle: | app/client/src/pages/Editor/Explorer/ContextMenuTrigger.tsx | 72.73 **(-27.27)** | 100 **(0)** | 0 **(-100)** | 72.73 **(-27.27)**
 :red_circle: | app/client/src/pages/Editor/Explorer/ExplorerIcons.tsx | 81.13 **(-5.66)** | 50 **(-8.33)** | 0 **(-20)** | 80.39 **(-5.88)**
 :red_circle: | app/client/src/pages/Editor/Explorer/ExplorerStyledComponents.tsx | 75 **(-25)** | 100 **(0)** | 0 **(-100)** | 75 **(-25)**
 :red_circle: | app/client/src/pages/Editor/Explorer/TreeDropdown.tsx | 16.22 **(-48.64)** | 0 **(-53.85)** | 0 **(-44.44)** | 17.14 **(-45.72)**
 :red_circle: | app/client/src/pages/Editor/Explorer/hooks.ts | 45.28 **(-3.15)** | 29.23 **(0)** | 45.95 **(-13.51)** | 48.8 **(-3.2)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Actions/helpers.tsx | 33.85 **(-21.53)** | 6.12 **(-32.66)** | 4.55 **(-27.27)** | 33.33 **(-22.81)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Entity/AddButton.tsx | 53.85 **(-30.77)** | 33.33 **(-33.34)** | 0 **(-50)** | 54.55 **(-27.27)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Entity/Collapse.tsx | 53.33 **(-40)** | 33.33 **(-50)** | 0 **(-100)** | 57.14 **(-42.86)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Entity/CollapseToggle.tsx | 46.15 **(-46.16)** | 0 **(-66.67)** | 0 **(-100)** | 50 **(-50)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Entity/Loader.tsx | 55.56 **(-44.44)** | 50 **(-50)** | 0 **(-100)** | 62.5 **(-37.5)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Entity/Name.tsx | 18.29 **(-41.47)** | 4.76 **(-21.43)** | 0 **(-52.63)** | 19.23 **(-39.74)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Entity/index.tsx | 43.33 **(-51.83)** | 21.05 **(-59.38)** | 7.14 **(-86.61)** | 45.61 **(-49.31)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Pages/PageContextMenu.tsx | 42.86 **(-28.57)** | 20 **(-40)** | 0 **(-12.5)** | 44.12 **(-29.41)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Pages/PageEntity.tsx | 53.33 **(-33.34)** | 0 **(-37.5)** | 0 **(-40)** | 53.33 **(-33.34)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Pages/PageGroup.tsx | 64.71 **(-17.64)** | 5.88 **(-52.94)** | 33.33 **(-33.34)** | 63.64 **(-21.21)**
 :red_circle: | app/client/src/pages/Editor/Explorer/PluginGroup/PluginGroup.tsx | 48 **(-40)** | 0 **(-61.4)** | 0 **(-60)** | 50 **(-37.5)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Widgets/WidgetEntity.tsx | 44.29 **(-53.79)** | 0 **(-79.59)** | 9.09 **(-90.91)** | 47.54 **(-52.46)**
 :red_circle: | app/client/src/pages/Editor/Explorer/Widgets/WidgetGroup.tsx | 65.22 **(-26.78)** | 6.45 **(-58.67)** | 0 **(-60)** | 65.22 **(-26.45)**
 :red_circle: | app/client/src/pages/Editor/PropertyPane/index.tsx | 82.83 **(-0.17)** | 71.58 **(0)** | 68 **(0)** | 83.7 **(-0.17)**
 :red_circle: | app/client/src/pages/Editor/SaaSEditor/constants.ts | 100 **(0)** | 60 **(-3.33)** | 100 **(0)** | 100 **(0)**
 :green_circle: | app/client/src/pages/common/ProfileDropdown.tsx | 68 **(-1.23)** | 75 **(15)** | 0 **(0)** | 68 **(-1.23)**
 :red_circle: | app/client/src/pages/organization/OrgInviteUsersForm.tsx | 39.62 **(-0.57)** | 24.49 **(0.49)** | 0 **(0)** | 41.18 **(-0.57)**
 :red_circle: | app/client/src/reducers/uiReducers/dragResizeReducer.ts | 57.14 **(-25.36)** | 35 **(-22.69)** | 50 **(-13.64)** | 58.82 **(-25.8)**
 :red_circle: | app/client/src/reducers/uiReducers/editorReducer.tsx | 17.91 **(-4.48)** | 0 **(0)** | 18.18 **(-4.55)** | 17.91 **(-4.48)**
 :red_circle: | app/client/src/reducers/uiReducers/pageCanvasStructureReducer.ts | 50 **(-33.33)** | 0 **(-50)** | 0 **(-75)** | 50 **(-33.33)**
 :red_circle: | app/client/src/reducers/uiReducers/pageWidgetsReducer.ts | 58.33 **(-33.34)** | 0 **(-50)** | 25 **(-75)** | 58.33 **(-33.34)**
 :red_circle: | app/client/src/sagas/ErrorSagas.tsx | 65.09 **(-0.95)** | 42.11 **(-5.26)** | 50 **(0)** | 65.26 **(-1.06)**
 :red_circle: | app/client/src/sagas/ModalSagas.ts | 27.87 **(-18.03)** | 4.17 **(-16.66)** | 10 **(-10)** | 30.36 **(-16.07)**
 :red_circle: | app/client/src/sagas/PageSagas.tsx | 17.63 **(-6.11)** | 3.17 **(-3.18)** | 9.68 **(-6.45)** | 20.17 **(-5.46)**
 :green_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 11.95 **(1.4)** | 3.46 **(2.21)** | 9.33 **(2.39)** | 12.68 **(1.3)**
 :green_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 76.19 **(13.23)** | 65.63 **(18.96)** | 70 **(6.36)** | 74.58 **(11.91)**
 :red_circle: | app/client/src/sagas/index.tsx | 91.3 **(-0.19)** | 60 **(0)** | 100 **(0)** | 93.18 **(-0.15)**
 :red_circle: | app/client/src/sagas/selectors.tsx | 61.8 **(-8.99)** | 36.36 **(-18.19)** | 28 **(-16)** | 55.22 **(-8.96)**
 :red_circle: | app/client/src/sagas/CommentSagas/index.ts | 47.79 **(-1.35)** | 26.09 **(0)** | 50 **(-3.33)** | 47.78 **(-0.57)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 41.58 **(-0.84)** | 10.61 **(-1.06)** | 40 **(0)** | 34.29 **(-0.49)**
 :red_circle: | app/client/src/selectors/editorSelectors.tsx | 61.54 **(-0.77)** | 43.24 **(-2.71)** | 42.86 **(-2.38)** | 57.94 **(-0.94)**
 :red_circle: | app/client/src/selectors/entitiesSelector.ts | 44.75 **(-0.5)** | 2.86 **(-2.7)** | 14.81 **(-1.04)** | 41.61 **(-0.72)**
 :red_circle: | app/client/src/selectors/themeSelectors.tsx | 94.12 **(-0.32)** | 100 **(0)** | 80 **(0)** | 91.67 **(-0.64)**
 :red_circle: | app/client/src/utils/AppsmithUtils.tsx | 54.19 **(0)** | 21.95 **(-1.31)** | 40.54 **(0)** | 49.68 **(0)**
 :red_circle: | app/client/src/utils/PerformanceTracker.ts | 54.05 **(-7.49)** | 11.69 **(-11.09)** | 60 **(-12.73)** | 53.64 **(-8.64)**
 :red_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 64.2 **(-2.47)** | 52.31 **(-9.68)** | 54.17 **(-4.73)** | 63.58 **(-2.52)**
 :red_circle: | app/client/src/utils/canvasStructureHelpers.ts | 77.78 **(-22.22)** | 70 **(-25)** | 66.67 **(-33.33)** | 81.25 **(-18.75)**
 :red_circle: | app/client/src/utils/helpers.tsx | 47.62 **(-4.08)** | 18.84 **(-4.35)** | 12 **(-8)** | 40 **(-5.22)**
 :green_circle: | app/client/src/utils/hooks/dragResizeHooks.tsx | 83.02 **(3.02)** | 40 **(0)** | 70.59 **(9.05)** | 81.82 **(3.44)**
 :red_circle: | app/client/src/utils/hooks/useClick.tsx | 10 **(-70)** | 0 **(-64.29)** | 0 **(-100)** | 10 **(-70)**
 :red_circle: | app/client/src/utils/hooks/useClickOpenPropPane.tsx | 80.77 **(-0.36)** | 51.35 **(-1.28)** | 100 **(0)** | 79.59 **(-0.41)**
 :red_circle: | app/client/src/widgets/ContainerWidget.tsx | 67.35 **(-1.88)** | 25 **(-25)** | 70 **(0)** | 68.89 **(-2.54)**
 :red_circle: | app/client/src/widgets/ListWidget/ListComponent.tsx | 76.47 **(-3.53)** | 50 **(0)** | 42.86 **(-7.14)** | 76.47 **(-3.53)**
 :red_circle: | app/client/test/factories/Widgets/CanvasFactory.ts | 75 **(-25)** | 100 **(0)** | 0 **(-100)** | 75 **(-25)**
 :red_circle: | app/client/test/factories/Widgets/ChartFactory.ts | 75 **(-25)** | 100 **(0)** | 0 **(-100)** | 75 **(-25)**
 :x: | ~~app/client/src/actions/canvasSelectionActions.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~
 :x: | ~~app/client/src/actions/widgetSelectionActions.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~
 :x: | ~~app/client/src/pages/Editor/Explorer/Widgets/useNavigateToWidget.ts~~ | ~~90.24~~ | ~~75~~ | ~~100~~ | ~~92.31~~
 :x: | ~~app/client/src/pages/Editor/Explorer/Widgets/utils.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~
 :x: | ~~app/client/src/pages/common/CanvasSelectionArena.tsx~~ | ~~92.16~~ | ~~57.58~~ | ~~82.35~~ | ~~91.92~~
 :x: | ~~app/client/src/reducers/uiReducers/canvasSelectionReducer.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~
 :x: | ~~app/client/src/sagas/SelectionCanvasSagas.ts~~ | ~~95.45~~ | ~~56.25~~ | ~~71.43~~ | ~~94.87~~
 :x: | ~~app/client/src/sagas/WidgetSelectionSagas.ts~~ | ~~98.48~~ | ~~92.5~~ | ~~100~~ | ~~98.31~~
 :x: | ~~app/client/src/utils/hooks/useWidgetSelection.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@prapullac please test this out!
<details><summary>Browser metadata</summary>





```
Path:      /applications/60a4f4981f2eef5dc53d3754/pages/60a4f4981f2eef5dc53d3756/edit
Browser:   Chrome 91.0.4472.77 on Mac OS 10.15.7
Viewport:  1387 x 796 @2x
Language:  en-GB
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-4916--appsmith-editor-ce.netlify.app%2Fapplications%2F60a4f4981f2eef5dc53d3754%2Fpages%2F60a4f4981f2eef5dc53d3756%2Fedit&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=91.0&resolution=1387x796&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-4916--appsmith-editor-ce.netlify.app/applications/60a4f4981f2eef5dc53d3754/pages/60a4f4981f2eef5dc53d3756/edit) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60b8f232572b7f00088b6869&commentID=60b9c19b1861d3b129d8e898&resolution=resolved)

File: app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx [hunk 1]
```diff
@@ -175,6 +175,7 @@ function TableFilters(props: TableFilterProps) {
     >
       <TableAction
         className="t--table-filter-toggle-btn"
+        filterApplied={hasAnyFilters}
```
Comment (vicky-primathon) [inline app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx:178]: Instead of passing filterApplied to TableAction component, we can pass icon color since we are only changing color based on filterApplied property.

**Review by vicky-primathon — CHANGES_REQUESTED** [review]

File: app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx (hunk 1 above)
Comment (somangshu) [reply app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx:178]: @vicky-primathon Check the new design, We need a count of filters next to the icon.

Comment (vicky-primathon) [reply app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx:178]: Yes @somangshu , i have that figured. But since we are only changing icon color by passing filterApplied property we can instead pass the icon color property. That will keep our component generalised.

Comment (somangshu) [reply app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx:178]: @vibhandikyash ☝️

**Comment by vivekverma2312** [comment]
@vibhandikyash Tested and working fine on deploy preview. Good to be merged into release.

File: app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx (hunk 1 above)
Comment (vibhandikyash) [reply app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx:178]: Yes, this is a good suggestion. Implemented it.

**Review by somangshu — APPROVED** [review]
Approving to run tests

@vicky-primathon please check the changes requested

@vivekverma2312 some changes here, Please test them out again!

**Review by vicky-primathon — APPROVED** [review]
Looks good to me

**Comment by somangshu** [comment]
@vibhandikyash merge the latest release here. Failing test fixes are available!

**Review by somangshu — APPROVED** [review]
