### PR TITLE
fix: minor git sync fixes

### LINKED ISSUE #9904: [Bug]: Git Issues in release
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
- [x] Keep commit input empty by default instead add a placeholder, for the first commit post connection we might want to keep it as `Initial Commit` (@haojin111)
- [x] #10003
- [ ] #10536
- [x] Update message for contact message for intercom: (@haojin111)
  - `Hey there,
Thanks for getting in touch! We understand that you’d like to extend the number of private repos for your <Organisation Name>. Could you tell us how many private repos you’d require and why? We'll get back to you in a short while.` 
- [x] The update button should be similar to COnnect button for the consistence (@haojin111)->Fixed
- [x] The commit change tooltip retains when user click on + icon (@haojin111)->Fixed
- [x] #10517
- [x] The Appsmith server unavailable error is displayed instead of page not found when the user switch between the branch which has missing pages (@haojin111 )->Fixed
- [x] When the user creates a new branch in git in the appsmith application the new remote branch wont be displayed until the new branch is created in local->Fixed
- [x] When the user delete the branch from git and try to sync it the delete branch will still be displayed in the Application @AnaghHegde
- [x] The internal server error is displayed when the user checkout from the remote branch @AnaghHegde
- [x] when the user tries to click on local branch created from the remote branch the appsmith server is unavailable message is displayed @AnaghHegde
- [x] when the user select the local branch created from the remote branch for merging the change the null pointer error is displayed
- [x] The user configuration is not checked by default ->Fixed
- [ ] The user is able to connect 2different application same repo in bit bucket
- [x] The open repo link doesn't work for the bit bucket(in progress by @haojin111), (duplicated by #10216)
- [x] The disconnect flow doesn't work in release->fixed
- [x] #9989
- [x] #10004
  - [ ] ssh url input
  - [ ] ssh key box
  - [ ] conflicts found: (deploy / merge tabs and bottom bar popup)
  - [ ] disconnect popup
  - [ ] repo limit reached modal
  - [ ] error while connecting at the connection tab
  - [ ] push error: pending upstream changes at the deploy tab  
- [x]  When the user tries to add a new branch and clicks multiple times on the branch name the error is displayed and then the user is unable to switch on the new branch created(Disable the click action until we get the response from backend)(@haojin111 )
- [x] The Pull changes button shows infinite loading when there are a merge conflict(@haojin111)
- [ ] When the users are in the same branch the multiple Cursors are displayed
- [ ] The page count is wrong in the deploy tab 
- [ ] When Multiple users tries to merge the changes at the same time the error is displayed in the merge tab
- [x] When the merge is not successful the error message should be displayed(@haojin111 )
- [x] Some time user tries to merge the changes metadat.json error is displayed
- [x] If 2 users create a branch at the same time internal server error is displayed
- [x] Replace the ID with Readable slug  (this should be a part of clean URLs project)
- [x] The new Deploy key should autogenerated when user change the remote URL(@haojin111)
- [x] Invalid URL or page has no data error is displayed on the Canvas
- [x] The wrong error message is displayed when user tries to connect to git without adding a deploy key (@AnaghHegde)
- [x] #10216
- [x] #10217
- [x] #10333
- [x] #10354
- [x] User is unable to delete the imported curl api
- [x] #10537
- [x] The git Icon retains even after deleting the connection(@haojin111 )

The issue which came up after the new changes done

- [x] When the user creates a new branch Until we refresh the browser i won't be able to see the branch(local branch)
- [x] When we create a new remote branch Until we refresh the browser i won't be able to see the branch
- [ ] When we commit and push it take a lot of time  to complete the action (i am comparing it with the previous release) same goes with the merging
- [x] The user should not be allowed to click multiple times on the same Remote branch
- [ ]When user update the page name the count is displayed as “2page updated” instead of 1

### Steps To Reproduce

1. Connect your application to git and check for the above issues

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by haojin111**
## Description

> updated hard-coded document url links from store
> it'll be fetch from back-end side later

Related to #9904 

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please refer attached issue.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/9904-git-sync-ui-issues 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.07 **(0)** | 36.51 **(-0.06)** | 34.46 **(-0.03)** | 55.58 **(0)**
 :green_circle: | app/client/src/actions/applicationActions.ts | 66.1 **(0.03)** | 100 **(0)** | 12.5 **(-0.83)** | 53.66 **(1.16)**
 :red_circle: | app/client/src/constants/messages.ts | 74.02 **(-0.01)** | 100 **(0)** | 23.09 **(-0.04)** | 79.17 **(-0.08)**
 :red_circle: | app/client/src/reducers/uiReducers/applicationsReducer.tsx | 9.38 **(-0.09)** | 30 **(0)** | 6.25 **(-0.13)** | 9.68 **(-0.1)**
 :red_circle: | app/client/src/selectors/gitSyncSelectors.tsx | 70.95 **(-0.7)** | 13.41 **(-12.78)** | 14.29 **(-2.38)** | 62.64 **(-1.46)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx [hunk 1]
```diff
@@ -254,6 +256,11 @@ function GitConnection({ isImport }: Props) {
     setIsValidRemoteUrl(isInvalid);
     setRemoteUrl(value);
     dispatch(remoteUrlInputValue({ tempRemoteUrl: value }));
+
+    // if changed remote url, sshkey should be regenarated automatically
+    if (value !== remoteUrlInStore) {
+      generateSSHKey();
+    }
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:263]: hey, QQ what's the use-case here, I think it would trigger multiple generate calls?

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx [hunk 2]
```diff
@@ -381,10 +388,10 @@ function GitConnection({ isImport }: Props) {
             <Link
               color={Colors.PRIMARY_ORANGE}
               hasIcon={false}
-              link={DOCS_BASE_URL}
+              link={RepoUrlDocumentUrl as string}
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:391]: nit: I suppose we could do without the typecast here?

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx (hunk 1 above)
Comment (haojin111) [reply app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx]: updated this part

File: app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx [hunk 3]
```diff
@@ -220,9 +225,15 @@ function GitConnection({ isImport }: Props) {
     dispatch(fetchLocalGitConfigInit());
   }, []);
 
+  useEffect(() => {
+    if (!isModalOpen && !isGitConnected) {
+      dispatch(initSSHKeyPairWithNull());
+    }
+  }, [isModalOpen, isGitConnected]);
+
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:233]: @haojin111 On second thoughts I feel, we should skip this edge case for now. Since in some cases even if the modal is closed by default the state would be reset.

Comment (haojin111) [reply app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx:233]: OK, I'll comment that part now!

**Review by rishabhsaxena — APPROVED** [review]
