### PR TITLE
fix: Misc. fixes for anvil

### LINKED ISSUE #28203: [Task]: Fix Misc issues in Anvil
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- No borders show in Anvil around widgets
- Canvas jumps when we hover on the resizer of the Canvas
- MainContainer is getting zero height when applying `height:100%`
- Widgets get focus in preview mode
- Auto Height Sagas run in Anvil
- Auto Layout Sagas run in Anvil

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
Fixes #28203 
- Borders are added to widgets separately now, as there is no resizer in Anvil
- Fix main container jump when hovering over the main container resizer
- Add height 100% to themeprovider so that the layout preset for main canvas can render correctly
- Stop widgets from focusing in preview mode
- Prevent AutoHeight Sagas from running in Anvil
- Prevent Auto Layout sagas from running in Anvil

### CODE REVIEW

**Review by prsidhu — APPROVED** [review]

File: app/client/packages/design-system/theming/src/theme/src/ThemeProvider.tsx [hunk 1]
```diff
@@ -36,8 +36,8 @@ const providerCss = ({
 `;
 
 export const ThemeProvider = (props: ThemeProviderProps) => {
-  const { children, className, style, theme } = props;
-
+  const { children, className, style = {}, theme } = props;
```
Comment (riodeuno) [inline app/client/packages/design-system/theming/src/theme/src/ThemeProvider.tsx:39]: @KelvinOm Could you review this change?

File: app/client/src/sagas/AutoLayoutUpdateSagas.tsx [hunk 2]
```diff
@@ -492,19 +503,23 @@ export default function* layoutUpdateSagas() {
   yield all([
     takeLatest(
       ReduxActionTypes.RECALCULATE_COLUMNS,
+      preventForAnvil,
       updateLayoutForMobileCheckpoint,
     ),
     takeLatest(
       ReduxActionTypes.UPDATE_LAYOUT_SYSTEM_TYPE,
+      preventForAnvil,
```
Comment (riodeuno) [inline app/client/src/sagas/AutoLayoutUpdateSagas.tsx:511]: Remove this.

File: app/client/src/sagas/AutoLayoutUpdateSagas.tsx [hunk 3]
```diff
@@ -492,19 +503,23 @@ export default function* layoutUpdateSagas() {
...
       updateLayoutSystemTypeSaga,
     ),
     takeLatest(
       ReduxActionTypes.UPDATE_WIDGET_DIMENSIONS,
```
Comment (riodeuno) [inline app/client/src/sagas/AutoLayoutUpdateSagas.tsx:515]: Rename action to be more specific.
