### PR TITLE
Fix edit and fork buttons visible simultaneously on the viewer header

### LINKED ISSUE #3722: [Bug] Fork and edit buttons can both appear simultaneously
## Description
Fork and edit buttons can both appear simultaneously

## Steps to reproduce:
[TODO]

Screen Shot 2021-03-23 at 11 47 27 PM

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
Fix edit and fork buttons visible simultaneously on viewer header
Fixes #3722

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- TODO, on the deploy preview

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hetunandu — DISMISSED** [review]

**Review by hetunandu — DISMISSED** [review]

File: app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx [hunk 1]
```diff
@@ -175,17 +175,24 @@ export const AppViewerHeader = (props: AppViewerHeaderProps) => {
...
   ) {
-    CTA = (
-      <ForkButton
-        className="t--fork-app"
-        href={forkUrl}
-        text={createMessage(FORK_APP)}
-        icon="fork"
-      />
-    );
+    if (currentUser?.username === ANONYMOUS_USERNAME) {
```
Comment (hetunandu) [inline app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx:180]: Consider adding a unit test for this component

File: app/client/src/pages/AppViewer/viewer/getAppViewerHeaderCTA.tsx [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        <ForkButton
+          className="t--fork-app"
+          href={forkUrl}
+          text={createMessage(FORK_APP)}
+          icon="fork"
+        />
+      );
+    } else {
+      CTA = (
+        <div className="header__application-fork-btn-wrapper">
```
Comment (hetunandu) [inline app/client/src/pages/AppViewer/viewer/getAppViewerHeaderCTA.tsx:55]: Class names for testing should be prepended with `t--`

File: app/client/src/pages/AppViewer/viewer/getAppViewerHeaderCTA.test.tsx [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+};
+
+let container: any = null;
+describe("get app viewer header CTA", () => {
+  beforeEach(async () => {
+    // setup a DOM element as a render target
+    container = document.createElement("div");
+    document.body.appendChild(container);
+  });
+  it("renders the edit app button", async () => {
```
Comment (hetunandu) [inline app/client/src/pages/AppViewer/viewer/getAppViewerHeaderCTA.test.tsx:67]: We should also do a test to ensure both edit and fork buttons don't show simultaneously

**Review by hetunandu — APPROVED** [review]
