### PR TITLE
[ISSUE#4524]Fix: Added a check in else block too and assigned default…

### LINKED ISSUE #4524: [Bug] Toggling dynamic property field to a normal field does not reset the value to a boolean
### Steps to reproduce the behaviour:

1.  Add a button widget. Toggle a JS property field to edit it's value. Add some random text, toggle back to non-edit mode
2.  Reference this value in another widget. 
3. See that the value is not reset.

https://user-images.githubusercontent.com/67054171/118458387-53ebea00-b718-11eb-9ab6-37bd522ee161.mov

It is expected that the value should probably get reset to a default boolean value. 

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

### PR DESCRIPTION
**Pull request by vibhandikyash**
… config

## Description
Toggling dynamic property field to a normal field was not resetting the value to a boolean.

Fixes #4524 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 1]
```diff
@@ -1055,6 +1057,12 @@ function* setWidgetDynamicPropertySaga(
     }
     widget = set(widget, propertyPath, convertToString(propertyValue));
   } else {
+    const keyExists =
+      dynamicPropertyPathList.findIndex((path) => path.key === propertyPath) >
+      -1;
+    if (keyExists) {
+      propertyValue = defaultConfig[propertyPath];
```
Comment (hetunandu) [inline app/client/src/sagas/WidgetOperationSagas.tsx:1064]: This will reset the value to the default value of a widget but that seems like an incorrect solution. Instead, we should improve the validation function of BOOLEAN type to make sure it always returns a true or false. You can find that function [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/workers/validations.ts#L142-L163)

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Review by hetunandu — APPROVED** [review]
