### PR TITLE
fix: Tab navigation issue in multi page apps

### LINKED ISSUE #38216: [Bug]: Navigation between Jsobjects not working properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we have multiple pages with each having different jsobjects. If we try to navigate between jsobjects in one page its taking user to different page incorrectly

### Steps To Reproduce

1.Mantain 3 pages with 5 jsobjects in each with different name
2.Select a page and randomly click on different jsobjects.

Expected:
It should go to the clicked jsobject

Actual:
Its randomly navigating to different jsobject in different page.

https://github.com/user-attachments/assets/fa6f0592-4738-4af5-917c-999cad7d5862

### Public Sample App

_No response_

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

_No response_

### Version

v1.53

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Fixes the caching in useEventCallback for tabClickHandler that was getting the old pageId 

Fixes #38216

## Automation

/ok-to-test tags="@tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12429634967>
> Commit: 3715ac2cec6918060ac1d6ff8b8c440d9c279bc0
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12429634967&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.IDE`
> Spec:
> <hr>Fri, 20 Dec 2024 10:53:24 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [x] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Introduced Cypress end-to-end tests for tab navigation within the IDE, ensuring seamless switching between JavaScript and query tabs.
	- Added a new function `editorTabSelector` for generating string selectors for IDE tabs.

- **Bug Fixes**
	- Optimized tab click handling in the editor for improved performance.

- **Chores**
	- Updated imports to include necessary hooks for better functionality.

### CODE REVIEW

**Review by alex-golovanov — APPROVED** [review]

**Review by ankitakinger — DISMISSED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/IDE/Tabs_Navigation_spec.ts [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+  it("should create and switch between JS files", () => {
+    // Create first JS file
+    jsEditor.CreateJSObject("", { prettify: false, toRun: false });
+    jsEditor.RenameJSObjFromPane("Page1_JS1");
+
+    // Create second JS file
+    jsEditor.CreateJSObject("", { prettify: false, toRun: false });
+    jsEditor.RenameJSObjFromPane("Page1_JS2");
+
+    cy.get("[data-testid='t--ide-tab-page1_js1']").click();
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/Regression/ClientSide/IDE/Tabs_Navigation_spec.ts:34]: Please  agHelper.GetNClick(reconnectDatasourceModal.SkipToAppBtn,0,true, ); here for click function. And do follow for all.
 
 Kindly add locator as variable.

**Review by sagar-qa007 — CHANGES_REQUESTED** [review]
