### PR TITLE
fix: gsheets import headers fix

### LINKED ISSUE #27172: [Bug]: The user is logged out of the instance when we try to authenticate app level imported Gsheet
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user is logged out of the instance when we try to authenticate app level imported Gsheet
image
https://www.loom.com/share/70584f0b7c644b988f9ac7809c704a89?sid=e3b68b70-9a74-4619-8b9a-41267cbbbb3e

### Steps To Reproduce

1. Go to https://ee-2281.dp.appsmith.com/
2. create a new workspace and a app
3. Not in edit mode
4. click on app setting then on Import 
5. Now import any one of your json app which has gsheet datasource
6. once the reconnect modal is up try to authenticate the gsheet datasource 
7. Noe the user is redirected to login page

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

v1.9.38

### PR DESCRIPTION
**Pull request by ayushpahwa**
## Description
For /token call during import process, the env API is not fetched so the envId passed was wrong. Earlier, we used to fetch from localstorage. This PR adds the wait call in the saga so that the envs are always fetched before we can use the token call.

#### PR fixes following issue(s)
Fixes #27172 

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
Tested the following on CE DP:

1. Tested import from home page with all Datasources - including OAuth and GSheets
2. Tested fork of the above app into another workspace
3. Tested import from inside the application with Gsheets DS
4. Tested import from inside the application with OAuth DS
5. Tested fork of a GSheets application into a new workspace
6. Tested import from inside the application with multiple Datasources including OAuth and Gsheets

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by ankitakinger — DISMISSED** [review]

File: app/client/src/ce/api/ApiUtils.ts [hunk 1]
```diff
@@ -105,7 +106,11 @@ export const apiRequestInterceptor = (config: AxiosRequestConfig) => {
 
   if (ENV_ENABLED_ROUTES_REGEX.test(config.url?.split("?")[0] || "")) {
     // Add header for environment name
-    const activeEnv = getCurrentEnvironmentId(state);
+    let activeEnv = getCurrentEnvironmentId(state);
+
+    if (config.url?.indexOf("/token") !== -1) {
```
Comment (sneha122) [inline app/client/src/ce/api/ApiUtils.ts:111]: @ayushpahwa Why are we adding this condition for token API explicitly? By doing this we are fixing the problem for gsheet but do we know any other APIs where such problem could still be there? Also in PR description you have mentioned that now it gets the env from indexedDB, I hope the indexedDB has correct information about the environments.

Comment (ayushpahwa) [reply app/client/src/ce/api/ApiUtils.ts]: Makes sense, I updated it to correct implementation, please check again

**Review by sneha122 — APPROVED** [review]
