### PR TITLE
fix: Sort/Freeze control existing after they are disabled

### LINKED ISSUE #23200: [Bug]: Sort/Freeze controls still exist in the Table header after sorting and freezing have both been disabled.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The sort/freeze controls still exist in the DOM if sorting and freezing are disabled for a column. This causes unnecessary squeeze on the column headers.

I expect the DOM element to disappear and give way to the header text if both behaviors are disabled.

Here is an example of this squeeze. If the user makes one of the columns any smaller, the header text is truncated.

image

### Steps To Reproduce

1. D&D a table onto the canvas.
2. Disable sorting and freezing for the table.
3. Observe that the dropdown arrow still exists in the header.
4. Reduce the width of one of the columns.
5. Observe that this control takes up space and causes premature truncation of the header text.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud v1.9.18-SNAPSHOT

### PR DESCRIPTION
**Pull request by Sheikh-JamirAlam**
## Description
Sort and Freeze controls where visible even after disabling them. This caused unwanted premature truncation of the header text.
Now, when both the controls are disabled, we don't see the freeze/sort drop-down.
#### PR fixes following issue(s)
Fixes #23200 
#### Media
[Screencast from 02-06-23 11:59:25 AM IST.webm](https://github.com/appsmithorg/appsmith/assets/48979376/b0381f6a-f596-4931-bf45-e7b397097091)

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
- [X] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx [hunk 1]
```diff
@@ -266,7 +266,11 @@ const HeaderCellComponent = (props: HeaderProps) => {
           </Title>
         </ColumnNameContainer>
       </div>
-      <div className={`header-menu${!isMenuOpen ? " hide" : ""}`}>
+      <div
+        className={`header-menu ${
+          !isSortable && !props.canFreezeColumn && "hide-menu"
```
Comment (keyurparalkar) [inline app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx:271]: @Sheikh-JamirAlam Can you please use `disableSort` instead of `!isSortable` here?

Comment (Sheikh-JamirAlam) [reply app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx]: @keyurparalkar Done. So like disabling Sorting should be visible only for when its in deployed state ig?

Comment (keyurparalkar) [reply app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx]: @Sheikh-JamirAlam Apologies, but can we revert back to `!isSortable`? It is required that in both the deployed and the edit state this menu should be hidden.

Comment (Sheikh-JamirAlam) [reply app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx]: @keyurparalkar Sure. I also think it makes more sense to see sorting disabled during edit state.

**Review by keyurparalkar — APPROVED** [review]

**Comment by laveena-en** [comment]
Hey @Sheikh-JamirAlam , a couple of QA callouts here:
1. The columns are sortable even when they are disabled in edit mode
2. The options for sort are seen when `Column freeze` has been enabled

Adding a loom for ref: https://www.loom.com/share/b8c64329d55b4d3597da845d1d2e8f3b
cc: @keyurparalkar

**Comment by laveena-en** [comment]
@Sheikh-JamirAlam Please use these credentials to access the DP:
Email: test.appsmith@gmail.com
PW: test.appsmith

**Comment by Sheikh-JamirAlam** [comment]
Hey @laveena-en , the reason for these 
> 1. The columns are sortable even when they are disabled in edit mode
> 2. The options for sort are seen when `Column freeze` has been enabled

is that the code uses [disableSort](https://github.com/appsmithorg/appsmith/blob/79ede3f1ca177cc087c338150af56ef44d0e4d33/app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx#L183) that checks if the user is on edit mode.
If we want to make the columns not sortable in edit mode then we need to remove `disableSort` completely.

**Comment by laveena-en** [comment]
> Hey @laveena-en , the reason for these
> 
> > 1. The columns are sortable even when they are disabled in edit mode
> > 2. The options for sort are seen when `Column freeze` has been enabled
> 
> is that the code uses [disableSort](https://github.com/appsmithorg/appsmith/blob/79ede3f1ca177cc087c338150af56ef44d0e4d33/app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx#L183) that checks if the user is on edit mode. If we want to make the columns not sortable in edit mode then we need to remove `disableSort` completely.

@keyurparalkar Can we have your thoughts on this? Looks like the first callout's behaviour is similar on prod, was this intentional? If yes, we can ignore it and just get the fix in for the second issue.

**Comment by keyurparalkar** [comment]
> @keyurparalkar Both the issues mentioned by @laveena-en are actually same and if I just replace all the `disableSort` with `!isSortable` then it should be fixed. My question is, was this intentional that the user won't be able to turn off sorting while on edit mode? or this was a bug?

@Sheikh-JamirAlam No this is not intentional and it is a bug. The QA callouts mentioned in this PR will also be addressed in the above mentioned [issue](https://github.com/appsmithorg/appsmith/issues/24375).

CC: @laveena-en @dilippitchika

**Review by keyurparalkar — APPROVED** [review]

**Comment by Sheikh-JamirAlam** [comment]
@keyurparalkar Alright then I am working on the changes.

**Comment by Sheikh-JamirAlam** [comment]
@keyurparalkar Alright I am working on that issue then 👍

**Comment by keyurparalkar** [comment]
@Sheikh-JamirAlam the other issue requires triaging, team will analyse it and check if it fits as a Good first issue.

Meanwhile this PR LGTM! and we can go ahead with it.

**Review by albinAppsmith — APPROVED** [review]
