### PR TITLE
fix: TreeWidgets issues

### LINKED ISSUE #15466: [Bug]: TreeSelect | Unable to capture right Label data OnPageLoad (first load)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2022-07-26 at 8 46 28 PM
Screenshot 2022-08-29 at 5 07 07 PM

### Steps To Reproduce

1. Dragdrop Tree select widget/MultiTree & map for the selected options display
2. Observe the selected option value & label data
3. **While the label data is Blue - the data captured is only "B" - can be seen in screenshot - TreeSelect**
4. **While the label data is Green - the data captured is "GREEN" - which is option value - MultiTreeSelect**
5. Now change the selected valued in Tree Select & observe right data is captured
6. **Expected - The right Label (and Value) data should be available (at all times and) during first load also**

### Public Sample App

_No response_

### Version

Prod/Release v1.7.10

### LINKED ISSUE #16365: [Bug]: "selectedOptionValue" in TreeSelect widget does not work as expected
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even when we clear the selected option in a TreeSelect widget, the value of the same is still stored.

**Note:** 

1. This happens when there is a `Default Value` mentioned for the TreeSelect widget.
2. This is happening only in release and not in Prod.

https://www.loom.com/share/efbfe26332a948f5b9d63917229b8e25

### Steps To Reproduce

1. D&D TreeSelect & Text widgets.
3. Bind the Text widget to the TreeSelect widget such that the `Text` property of the Text widget is `{{TreeSelect1.selectedOptionValue}}`.
4. Now clear the selected option in the TreeSelect widget.

**Expected:** The text in the Text widget should also disappear. 

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #16367: [Bug]: Issues in MultiTreeSelct widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two issues are happening with the MultiTreeSelect widget in release:

1. The `selectedOptionLabels` displays the values of the selected options instead of the labels.
2. On binding it with a Text widget using: `{{MultiTreeSelect1.selectedOptionLabels}}` when we clear all the selected options, the Text widget still displays the labels.

**Note:**

This happens when there is a Default Value mentioned for the TreeSelect widget.
This is happening only in release and not in Prod.

https://www.loom.com/share/8e6e11471fe2409fb786d556db0292e9

### Steps To Reproduce

1. D&D MultiTreeSelect & Text widgets.
2. Bind the Text widget to the MultiTreeSelect widget such that the Text property of the Text widget is {{MultiTreeSelect1.selectedOptionLabels}}.
4. Now clear the selected option in the TreeSelect widget.

**Expected:** The text in the Text widget should also disappear.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

This Fixes issues with Both Single Tree Select and Multi Tree Select.

- Clearing Values
- `SelectedOptionLabels` for both widgets

Fixes #16367
Fixes #16365
Fixes #15466

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Unit Test

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx [hunk 1]
```diff
@@ -872,20 +880,15 @@ class MultiSelectTreeWidget extends BaseWidget<
     ) {
       this.props.updateWidgetMetaProperty("isDirty", false);
     }
+
+    if (!equal(prevProps.options, this.props.options)) {
+      const flattenedOptions = flat(this.props.options ?? []);
+      this.props.updateWidgetMetaProperty("flattenedOptions", flattenedOptions);
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx:886]: Can we make `flattenedOptions` as derived property?

File: app/client/src/widgets/WidgetUtils.ts [hunk 2]
```diff
@@ -589,3 +589,27 @@ export function composePropertyUpdateHook(
...
+  children?: DropdownOption[];
+}
+
+/*
+ * Helps flatten nested Array of objects
+ *  Array -> Object { value, label,  children : Array -> Object { value, label } }
+ * This would be flattened to Array -> { value, label } , { value, label }
+ */
+
+export const flat = (array: DropdownOption[]) => {
```
Comment (ashit-rath) [inline app/client/src/widgets/WidgetUtils.ts:606]: I think there is a lodash function to flatten which you can use in the derived properties.

File: app/client/src/widgets/SingleSelectTreeWidget/widget/derived.js [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+      options,
+      (option) =>
+        option.label === label && option.value === props.selectedOptionValue,
+    );
+    if (labelIndex === -1) {
+      if (
+        !_.isNil(props.selectedOptionValue) &&
+        props.selectedOptionValue !== ""
+      ) {
+        const selectedOption = _.find(
```
Comment (ashit-rath) [inline app/client/src/widgets/SingleSelectTreeWidget/widget/derived.js:34]: Why are we not directly finding the option which has the `value` same as `pops.selectedOptionValue` and return the label?

File: app/client/src/widgets/WidgetUtils.ts (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/widgets/WidgetUtils.ts:606]: Not sure it would work for this use case. What youre refering to is that `Flatten` or `flattenDeep`

File: app/client/src/widgets/SingleSelectTreeWidget/widget/derived.test.ts [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+        _,
+      );
+
+      expect(isValid).toBeTruthy();
+    });
+
+    it("return true when isRequired true and selectedOptionValue is not empty", () => {
+      const isValid = derivedProperty.getIsValid(
+        {
+          selectedOptionValue: "GREEN",
```
Comment (ashit-rath) [inline app/client/src/widgets/SingleSelectTreeWidget/widget/derived.test.ts:49]: This can also be a number right? If yes, then can we add cases for 0 and 1 as they sort of represent falsey and truthy values

**Review by ashit-rath — APPROVED** [review]

**Comment by shadabbuchh** [comment]
All the reported issues pertaining to `TreeSelect` & `MultiTreeSelect` widgets are fixed and working fine.
https://www.loom.com/share/72b543e08d984647a758e168da972c0e

**Review by ashit-rath — APPROVED** [review]
