### PR TITLE
fix: firefox file picker not showing up issue fixed

### LINKED ISSUE #22753: GSheet Firefox Blank UI Bug
**Steps to reproduce:**

1. Create an application with a Google sheet data source.
2. Import the application and change the scope to Selected google sheets.
3. Complete the authorization.
4. Once the redirection happens the page comes as blank. Even after leaving it to load it doesn't loads.
5. If a hard refresh is done for the page it loads but in the data source section, it shows the data source is not authorized.

**Note:**
1. The issue is not consistently reproducible.
2. The issue is reproducible only for the FireFox browser.

### PR DESCRIPTION
**Pull request by sneha122**
## Description

This PR fixes a bug:
- Google sheet file picker is not visible in firefox browser.

> Add a TL;DR when description is extra long (helps content team)

Fixes #22753 

Media
> A video or a GIF is preferred. when using Loom, don’t embed because it looks like it’s a GIF. instead, just link to the video

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/pages/Editor/SaaSEditor/GoogleSheetFilePicker.tsx [hunk 1]
```diff
@@ -80,6 +80,18 @@ function GoogleSheetFilePicker({
...
   }, [gsheetToken, scriptLoadedFlag, pickerInitiated, gsheetProjectID]);
 
+  // This is added in useEffect instead of file picker callback,
+  // because in case when browser has blocked third party cookies
+  // The file picker needs to be displayed with allow cookies option
+  // hence as soon as file picker is visible we should remove the overlay
+  // Ref: https://github.com/appsmithorg/appsmith/issues/22753
+  useEffect(() => {
+    if (!!pickerVisible) {
+      const className = "overlay";
```
Comment (AmanAgarwal041) [inline app/client/src/pages/Editor/SaaSEditor/GoogleSheetFilePicker.tsx:90]: Any reason of creating a new variable ? It can be passed directly to the function.

Comment (sneha122) [reply app/client/src/pages/Editor/SaaSEditor/GoogleSheetFilePicker.tsx:90]: No reason actually I was also using this same constant in one more file, ill create a global constant instead

**Review by AmanAgarwal041 — APPROVED** [review]
