### PR TITLE
fix: 12603 - git import modal message of remote url inputbox

### LINKED ISSUE #12603: [Bug]: Git import modal shows the wrong text
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2022-04-05 at 9 29 40 PM

It says "Create an empty git repository and paste the remote URL here."  Although for git import we are using repository which already has commits for the app.

### Steps To Reproduce

1. Click on NEW.
2. Click on import
3. Click on Import from github repo
4. Git import modal will open

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by haojin111**
## Description

> Update a label of remote URL input box when importing application from git
Fixes #12603 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> refer linked issue

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/12603-git-import-modal-message 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/ce/constants/messages.ts | 77.83 **(-0.01)** | 100 **(0)** | 34.42 **(-0.05)** | 81.78 **(0.02)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

File: app/client/src/ce/constants/messages.ts [hunk 1]
```diff
@@ -607,6 +607,7 @@ export const CONNECT_TO_GIT_SUBTITLE = () =>
 export const REMOTE_URL = () => "Remote URL";
 export const REMOTE_URL_INFO = () =>
   `Create an empty git repository and paste the remote URL here.`;
+export const IMPORT_URL_INFO = () => `Paste the remote url here:`;
```
Comment (IAmAnubhavSaini) [inline app/client/src/ce/constants/messages.ts:610]: `url` should be capital like in the string above.

**Review by IAmAnubhavSaini — CHANGES_REQUESTED** [review]

**Review by IAmAnubhavSaini — APPROVED** [review]
