### PR TITLE
Fix: New widget and action name conflicts

### LINKED ISSUE #2773: [Bug] Widget get next entity name does not handle conflicts with Action names
While getting the name of a new widget, we do not check if an action with that name exists

### PR DESCRIPTION
**Pull request by riodeuno**
Fix widget add scenarios to make sure there are not conflicts between widget names and action names

## Description
When adding a new widget, the new widget's name should not conflict with an existing action name

Fixes #2773 
## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by riodeuno** [comment]
We should use the `evalTree` and `pageNames` for checking for conflicts as well.

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 1]
```diff
@@ -280,15 +285,17 @@ export function* addChildrenSaga(
...
       // Create only if it doesn't already exist
       if (!widgets[child.widgetId]) {
         const defaultConfig: any = WidgetConfigResponse.config[child.type];
-        const newWidgetName = getNextEntityName(
-          defaultConfig.widgetName,
-          widgetNames,
-        );
+        const newWidgetName = getNextEntityName(defaultConfig.widgetName, [
+          ...widgetNames,
+          ...entityNames,
```
Comment (hetunandu) [inline app/client/src/sagas/WidgetOperationSagas.tsx:297]: Will the function be able to handle duplicate names in the array? `entityNames` here will also include most of `widgetNames`

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 2]
```diff
@@ -1311,7 +1334,8 @@ function* addTableWidgetFromQuerySaga(action: ReduxAction<string>) {
     const rows = 7;
     const queryName = action.payload;
     const widgets = yield select(getWidgets);
-    const widgetName = getNextWidgetName(widgets, "TABLE_WIDGET");
+    const evalTree = yield select(getDataTree);
+    const widgetName = getNextWidgetName(widgets, "TABLE_WIDGET", evalTree);
```
Comment (hetunandu) [inline app/client/src/sagas/WidgetOperationSagas.tsx:1338]: Different way of getting a name here. Lets make a common function for this

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 3]
```diff
@@ -1063,11 +1070,25 @@ function calculateNewWidgetPosition(
...
+function getNextWidgetName(
+  widgets: CanvasWidgetsReduxState,
+  type: WidgetType,
+  evalTree: Record<string, unknown>,
+) {
   // Compute the new widget's name
   const defaultConfig: any = WidgetConfigResponse.config[type];
   const widgetNames = Object.keys(widgets).map((w) => widgets[w].widgetName);
-  return getNextEntityName(defaultConfig.widgetName, widgetNames);
+  const entityNames = Object.keys(evalTree);
```
Comment (ofpiyush) [inline app/client/src/sagas/WidgetOperationSagas.tsx:1086]: Do we need `widgetNames` anymore?

can use `getEntityNames` at the caller.

File: app/client/src/sagas/WidgetOperationSagas.tsx (hunk 1 above)
Comment (riodeuno) [reply app/client/src/sagas/WidgetOperationSagas.tsx:297]: There will be redundant entries. But, this is faster than looping through the arrays to find uniq names.
The other approach is to keep track of the new widgets introduced so far in the loop. Which increases the complexity of the function. 
So, this should work out fine.

File: app/client/src/sagas/WidgetOperationSagas.tsx (hunk 3 above)
Comment (riodeuno) [reply app/client/src/sagas/WidgetOperationSagas.tsx:1086]: These are being used in a loop where new widgets have been added. We need to make sure there are no conflicts with these new names as well.

Comment (riodeuno) [reply app/client/src/sagas/WidgetOperationSagas.tsx:1086]: I'll update the code by using `getEntityNames`

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 4]
```diff
@@ -280,15 +285,17 @@ export function* addChildrenSaga(
     const stateWidgets = yield select(getWidgets);
     const widgets = { ...stateWidgets };
     const widgetNames = Object.keys(widgets).map((w) => widgets[w].widgetName);
+    const evalTree = yield select(getDataTree);
+    const entityNames = Object.keys(evalTree);
```
[the remark this answers is not in the document]
Comment (riodeuno) [reply app/client/src/sagas/WidgetOperationSagas.tsx:289]: `getEntityNames` is a generator function. I can't use it a normal function inside a loop. Hence, the lack of re-use.

File: app/client/src/sagas/WidgetOperationSagas.tsx (hunk 3 above)
Comment (riodeuno) [reply app/client/src/sagas/WidgetOperationSagas.tsx:1086]: Just realized, `getEntityNames` is a generator function, so I can't use that in loops. `getNextEntityName` is a function which can. I'll update this above where @hetunandu  mentioned it.

File: app/client/src/sagas/WidgetOperationSagas.tsx (hunk 2 above)
Comment (riodeuno) [reply app/client/src/sagas/WidgetOperationSagas.tsx:1338]: This is the common function `getNextWidgetName` which I've used in this file. It gets called within map functions, so I have to keep it as a `non-generator` function.

**Review by hetunandu — APPROVED** [review]
