### PR TITLE
fix: column dragging and column reordering

### LINKED ISSUE #20858: [Bug]: Unable to reorder column positions through column headers in edit mode on the table when the first column is frozen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
Unable to reorder column positions through column headers in edit mode on the table when the first column is frozen

### Steps To Reproduce

1. DnD a table
2. Turn on Server-side pagination
3. freeze the first column 
4. try reordering the unfreezed column positions

### Public Sample App

_No response_

### Issue video log

https://www.loom.com/share/b2e2b6001486406aabbe123cffa511be

### Version

Release

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

This PR implements the following changes:
- Move the drag events from the Parent component's useEffect to the `HeaderCell` component.
- Refactored the code. Inside the table component, we refactored the code such that when SSP is disabled the component uses `StaticTable` and when SSP enabled then we use `VirtualTable`.
- It also includes the fix for the following issue. Whenever the user has a scroll to the bottom of the page, on clicking of add new button it is expected that the scroll should move to the top but it wasn't happening.

> Add a TL;DR when description is extra long (helps content team)

Fixes #20858
> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
    - Test cases:
        - Column name should appear on update from the property pane
        - reorder whenever SSP is enabled
        - On column re-size
        - When a col is frozen
        - When a col is unfrozen
        - When all the headers or one of them is removed
        - When sorted also should work
        - Enable multi-row selection
        - When in preview mode and back and forth(Check the above cases)
        - When in Deployed mode
        - Dragging of columns from the column header should work as expected both in Deploy and Published mode.
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx [hunk 1]
```diff
@@ -174,7 +191,33 @@ export function HeaderCell(props: {
...
+        onDragOver={(e) => {
+          // Below condition will disable the ability to drop a column on a frozen column
+          if (props.column.sticky === StickyType.NONE && !props.isHidden) {
+            props.onDragOver(e, props.columnIndex);
+          }
+        }}
+        onDragStart={(e) => props.onDragStart(e, props.columnIndex)}
+        onDrop={(e) => {
+          props.onDrop(e, props.columnIndex);
+        }}
```
Comment (keyurparalkar) [inline app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx:220]: @vsvamsi1 please review to the above section. This is the code that replaces the `useEffect` that is present in the `component/Table.tsx`

File: app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx [hunk 2]
```diff
@@ -174,7 +191,33 @@ export function HeaderCell(props: {
...
       <div
         className={!props.isHidden ? `draggable-header` : "hidden-header"}
+        draggable={
+          (props.column.sticky === StickyType.NONE && !props.isHidden) ||
+          undefined
+        }
         onClick={!disableSort && props ? handleSortColumn : undefined}
+        onDrag={props.onDrag}
+        onDragEnd={props.onDragEnd}
+        onDragEnter={(e) => {
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx:201]: Can we avoid defining functions inline? 
```
const onDragEnter = useCallback((e) => {
 ...
}, [<deps>]
}

....
....

onDragEnter={onDragEnter}
```

File: app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+  columns: ReactTableColumnProps[];
+  width: number;
+  subPage: ReactTableRowType<Record<string, unknown>>[];
+  prepareRow: any;
+  headerWidth?: number;
+  rowSelectionState: 0 | 1 | 2 | null;
+  widgetId: string;
+};
+
+export const HeaderComponent = (props: HeaderComponentProps) => {
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx:36]: 1. Why export instead of export default?
2. Can the file name be `TableHeader`? We know it's a component so no need to add the word `Component` as suffix

File: app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+      className="thead"
+      onMouseLeave={props.enableDrag}
+      onMouseOver={props.disableDrag}
+    >
+      {props.headerGroups.map((headerGroup: any, index: number) => {
+        const headerRowProps = {
+          ...headerGroup.getHeaderGroupProps(),
+          style: { display: "flex", width: props.headerWidth },
+        };
+        return (
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx:64]: Add a new line before this. Please think about logic separation and add appropriate new lines for better visibility

File: app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+  return (
+    <div
+      className="thead"
+      onMouseLeave={props.enableDrag}
+      onMouseOver={props.disableDrag}
+    >
+      {props.headerGroups.map((headerGroup: any, index: number) => {
+        const headerRowProps = {
+          ...headerGroup.getHeaderGroupProps(),
+          style: { display: "flex", width: props.headerWidth },
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx:62]: Why are we passing styles like this? Can't we use styled components for this?

File: app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx [hunk 6]
```diff
@@ -0,0 +1,128 @@
...
+              )}
+            {headerGroup.headers.map((column: any, columnIndex: number) => {
+              const stickyRightModifier = !column.isHidden
+                ? columnIndex !== 0 &&
+                  props.columns[columnIndex - 1].sticky === StickyType.RIGHT &&
+                  props.columns[columnIndex - 1].isHidden
+                  ? "sticky-right-modifier"
+                  : ""
+                : "";
+              return (
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx:81]: Add a new line above this

File: app/client/src/widgets/TableWidgetV2/component/header/VirtualTableInnerElement.tsx [hunk 7]
```diff
@@ -0,0 +1,46 @@
...
+  multiRowSelection?: boolean;
+  totalColumnsWidth: number;
+}>`
+  width: ${(props) =>
+    props.multiRowSelection
+      ? MULTISELECT_CHECKBOX_WIDTH + props.totalColumnsWidth
+      : props.totalColumnsWidth}px !important;
+`;
+
+export const VirtualTableInnerElement = ({
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/header/VirtualTableInnerElement.tsx:18]: Why export instead of export default?

File: app/client/src/widgets/TableWidgetV2/widget/utilities.ts [hunk 8]
```diff
@@ -954,3 +956,156 @@ export const getAllStickyColumnsCount = (columns: TableColumnProps[]) => {
...
   );
 };
+
+/**
+ *
+ * @param currentIndex: current dragging item index
+ * @param targetIndex: Index poistion of of header that is being hovered
+ * @returns
+ */
+export const getHeaderClassNameOnDragDirection = (
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/widget/utilities.ts:966]: Do we have jest tests for all of these functions?

File: app/client/src/widgets/TableWidgetV2/component/VirtualTable.tsx [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+  primaryColumnId?: string;
+  isAddRowInProgress: boolean;
+  totalColumnsWidth?: number;
+  scrollContainerStyles: any;
+  useVirtual: boolean;
+  tableBodyRef: React.MutableRefObject<HTMLDivElement | null>;
+};
+
+const VirtualTable = (props: VirtualTableProps) => {
+  const headerProps = {
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/VirtualTable.tsx:46]: This object is being passed to a context. We need to make sure that this is memoized as this object would be re-created on every render even if the object might not have a change. Due to this the context will update and whichever component uses the context will re-render.

1. Memoize this
2. Run react profiler and check for un-necessary re-renders. 

Go through this article to better understand
https://kentcdodds.com/blog/usememo-and-usecallback

File: app/client/src/widgets/TableWidgetV2/component/VirtualTable.tsx [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+    isSortable: props.isSortable,
+    multiRowSelection: props.multiRowSelection,
+    prepareRow: props.prepareRow,
+    rowSelectionState: props.rowSelectionState,
+    sortTableColumn: props.sortTableColumn,
+    subPage: props.subPage,
+    widgetId: props.widgetId,
+    width: props.width,
+  };
+  return (
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/VirtualTable.tsx:69]: Please add a new line before this!

File: app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx (hunk 1 above)
Comment (vsvamsi1) [reply app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx:220]: @keyurparalkar Its much better that it is moved to the HeaderCell and the useEffect code has been removed.

File: app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx (hunk 3 above)
Comment (keyurparalkar) [reply app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx:36]: Naming this file as `TableColumnHeader` since we are already using another component called `TableHeader` that renders the options such as dowload, search box etc

Comment (ashit-rath) [reply app/client/src/widgets/TableWidgetV2/component/header/TableHeaderComponent.tsx:36]: Okay

File: app/client/src/widgets/TableWidgetV2/component/Table.tsx [hunk 11]
```diff
@@ -368,56 +297,11 @@ export function Table(props: TableProps) {
     );
 
   useEffect(() => {
-    if (props.isAddRowInProgress && tableBodyRef) {
-      tableBodyRef.current?.scrollTo({ top: 0 });
+    if (props.isAddRowInProgress && scrollBarRef && scrollBarRef?.current) {
+      scrollBarRef.current.getScrollElement().scrollTop = 0;
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/Table.tsx:301]: put this in `fastDom.mutate` as this will cause layout thrashing. Check other places where we have done this to get more idea

File: app/client/src/widgets/TableWidgetV2/component/TableBody/index.tsx [hunk 12]
```diff
@@ -104,40 +111,51 @@ const TableVirtualBodyComponent = React.forwardRef(
...
-        {props.pageSize > props.rows.length && (
-          <EmptyRows rowCount={props.pageSize - props.rows.length} />
-        )}
-      </div>
-    );
-  },
-);
+const TableBodyComponent = (props: BodyPropsType) => {
+  return (
+    <div {...props.getTableBodyProps()} className="tbody body">
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/TableBody/index.tsx:116]: We don't need the ref anymore?

File: app/client/src/widgets/TableWidgetV2/component/header/TableColumnHeader.tsx [hunk 13]
```diff
@@ -0,0 +1,145 @@
...
+  widgetId: string;
+};
+
+const StyledHeaderGroup = styled.div<{
+  headerWidth: number;
+}>`
+  display: flex;
+  width: ${(props) => props.headerWidth}px !important;
+`;
+const HeaderComponent = (props: HeaderComponentProps) => {
```
Comment (ashit-rath) [inline app/client/src/widgets/TableWidgetV2/component/header/TableColumnHeader.tsx:42]: Name of the file does not match with the component name

File: app/client/src/widgets/TableWidgetV2/component/TableBody/index.tsx (hunk 12 above)
Comment (keyurparalkar) [reply app/client/src/widgets/TableWidgetV2/component/TableBody/index.tsx:116]: No, we don't need this ref here. We moved it [here](https://github.com/appsmithorg/appsmith/blob/30476f44bedd8f18a81f103e48d4385b1ba0bdf7/app/client/src/widgets/TableWidgetV2/component/StaticTable.tsx#L52) so that we can scroll the custom scroll bar to top which happens [here](https://github.com/appsmithorg/appsmith/blob/30476f44bedd8f18a81f103e48d4385b1ba0bdf7/app/client/src/widgets/TableWidgetV2/component/Table.tsx#L301)

**Review by ashit-rath — DISMISSED** [review]

**Review by ashit-rath — APPROVED** [review]

**Review by ashit-rath — APPROVED** [review]
