### PR TITLE
fix: serverside selected and triggered row issues

### LINKED ISSUE #18730: [BUG]: List widget V2 SelectedItemView and TriggeredItemView in Serverside Pagination

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

1. Fixed SelectedItemView and TriggeredItemView
2. Further improved metaWidget Error Suppression

Thought Process for the solution https://miro.com/app/board/uXjVP1rCNHM=/

Fixes #18730

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts [hunk 1]
```diff
@@ -334,11 +340,13 @@ class MetaWidgetGenerator {
...
 
-    this.cacheRowIndices(this.cacheIndexArr);
-
     const removedMetaWidgetIds = this.getRemovedMetaWidgetIds();
 
-    this.cachedRows.prev = new Set(this.cachedRows.curr);
+    if (this.modificationsQueue.has(MODIFICATION_TYPE.GENERATE_CACHE_WIDGETS)) {
+      this.cachedRows.prev = new Set(this.cachedRows.curr);
+      const cachedTemplateMetaWidgets = this.getCachedTemplateMetaWidgets();
+      metaWidgets = { ...metaWidgets, ...cachedTemplateMetaWidgets };
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:348]: add a new line above.

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 2]
```diff
@@ -500,6 +510,75 @@ class ListWidget extends BaseWidget<
...
+      const viewIndex = rowIndex - startIndex;
+      const rowData = this.props.listData?.[viewIndex] ?? {};
+      rowDataCache[key] = rowData;
+    });
+
+    if (!isEmpty(rowDataCache)) {
+      this.rowDataCache = rowDataCache;
+      this.updateGeneratorCacheRowKeys(Object.keys(this.rowDataCache));
+    }
+  };
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:531]: Shouldn't these be done in the MetaWidgetGenerator?

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 3]
```diff
@@ -500,6 +510,75 @@ class ListWidget extends BaseWidget<
...
+  updateGeneratorCacheRowKeys = (keys: string[]) => {
+    this.metaWidgetGenerator.updateCurrCachedRows(keys);
+  };
+
+  updateRowDataCacheWidgetProp = () => {
+    if (
+      !isEqual(this.rowDataCache, this.props.rowDataCache) &&
+      this.props.serverSidePagination
+    ) {
+      super.updateWidgetProperty("rowDataCache", this.rowDataCache);
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:542]: Why are we updating the widget property?

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:531]: By setting RowDataCache, 
we are getting the required Data and sending the cachedRows to MetaWidgetGenerator.

The rowData are cached as a Listwidget property

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx (hunk 3 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:542]: Oh, that's the data being cached.

Do you propose we just pass in the data to currentItem from MetaWidgetGenerator, rather than passing it this way?

Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:542]: This would persist the data in DSL which is not required. Also I remember us discussing the scenario of live data vs cached data, where in one case the currentItem's data can change due to the binding but in server side case where the page changes and we store the data. Are we doing that here?

Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:542]: Hi @ashit-rath, is this a scenario you're referring to?

https://user-images.githubusercontent.com/31691737/210411431-a048c73c-cef4-4368-82e6-34cbf5202ef0.mov

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts [hunk 4]
```diff
@@ -661,7 +706,11 @@ class MetaWidgetGenerator {
     const currentIndex = this.serverSidePagination
       ? this.getViewIndex(rowIndex)
       : rowIndex;
-    const currentItem = `{{${this.widgetName}.listData[${currentIndex}]}}`;
+    const dataBinding =
+      this.serverSidePagination && this.cachedRows.curr.has(key)
+        ? `${this.widgetName}.rowDataCache["${key}"]`
+        : `${this.widgetName}.listData[${currentIndex}]`;
+    const currentItem = `{{${dataBinding}}}`;
```
Comment (Tooluloope) [inline app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:716]: @ashit-rath over here, Would it be okay to inject the data itself rather than using the string `rowDataCache["${key}"]` since we already have the data?

The cost of using the string is that we'd need to update the RowDataCache on the widget property.
The cost of this other method is we might need to run a Generate cycle if the data updates.

Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:716]: Here's the PR using the MetaGenerator to hold the cache and injecting the data into currentItem, rather than using evals to get it from List widget

https://github.com/appsmithorg/appsmith/pull/19467

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 5]
```diff
@@ -500,6 +510,89 @@ class ListWidget extends BaseWidget<
...
+    const rowDataCache: RowDataCache = {};
+
+    Object.entries(this.cachedKeys).forEach(([key, rowIndex]) => {
+      if (Object.keys(prevDataCache).includes(key)) {
+        rowDataCache[key] = prevDataCache[key];
+        return;
+      }
+      const startIndex = this.metaWidgetGenerator.getStartIndex();
+      const viewIndex = rowIndex - startIndex;
+      const rowData = this.props.listData?.[viewIndex] ?? {};
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:526]: Use `getViewIndex` here.

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts [hunk 6]
```diff
@@ -997,6 +1068,38 @@ class MetaWidgetGenerator {
...
+   * Only generate cache widget when template widget property changes
+   * or new template widgets are added
+   * or new cached row is added (further conditions are done in getCachedTemplateMetaWidgets to ensure
+   * its only generated for the template row, the usual filtering of metaWidgetIds is used to cache rows)
+   *
+   */
+  private shouldGenerateCacheWidgets = (nextOptions: GeneratorOptions) => {
+    return (
+      !isEqual(this.currTemplateWidgets, nextOptions.currTemplateWidgets) ||
+      !isEqual(this.cachedRows.curr, this.cachedRows.prev)
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:1086]: Aren't we checking for renderMode to be Canvas here?

**Review by ashit-rath — APPROVED** [review]
