### PR TITLE
fix: Updated the copy text if plugin not installed, disabled new query and edit for unavailable plugin ds

### LINKED ISSUE #40015: [Task]: Edit datasource shouldn't work for downgraded integration
### SubTasks

When editing downgraded datasource, it allows me to update provider data, that should not happen

https://github.com/user-attachments/assets/d8daccb2-5cb5-4efd-8ea5-ead94a8a8ab5

### LINKED ISSUE #40019: [Task]: Update copy of Error messaging on downgrade
### SubTasks

Image

Copy: Upgrade your plan to unlock access to these integrations. 
CTA (small primary CTA): Upgrade

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
This PR addresses couple of issues:
- Disabling Edit button in the datasources whose plugins are not available
- Disabling New Query/Api button in the datasources whose plugins are not available
- Filtering the datasources to create api/query whose plugins are not available from global search and IDE 
- Updating the copy text for plugin not installed in the API/query editor and show upgrade button to admin users

Fixes #40015
Fixes #40019 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/14640968412>
> Commit: bfa889061344ab899b8fd7e1ef9aba843f999172
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=14640968412&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Thu, 24 Apr 2025 13:12:40 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Added a prompt and upgrade option when a required plugin is not installed, with improved messaging and layout.

- **Bug Fixes**
  - Disabled editing and creation actions for datasources when the associated plugin is missing or invalid.
  - Improved filtering in search and selection interfaces to exclude datasources linked to unavailable plugins, ensuring only valid options are shown.

### CODE REVIEW

File: app/client/src/PluginActionEditor/PluginActionEditor.tsx [hunk 1]
```diff
@@ -54,10 +56,11 @@ const PluginActionEditor = (props: ChildrenProps) => {
 
   if (!plugin) {
     return (
-      <CenteredWrapper>
+      <CenteredWrapper className="flex flex-col items-center justify-center">
```
Comment (ankitakinger) [inline app/client/src/PluginActionEditor/PluginActionEditor.tsx:59]: CenteredWrapper itself is just a styled component already handling these styles. Only `flex-col` is new here. 

Any reason we're maintaining it in 2 places?

File: app/client/src/ce/constants/messages.ts [hunk 2]
```diff
@@ -2691,3 +2691,6 @@ export const GOOGLE_RECAPTCHA_FAILED = () =>
   "Google reCAPTCHA verification failed";
 export const PASSWORD_INSUFFICIENT_STRENGTH = () =>
   "Insufficient password strength";
+
+export const PLUGIN_NOT_INSTALLED = () =>
```
Comment (ankitakinger) [inline app/client/src/ce/constants/messages.ts:2695]: Will this be the only seen for paragon integrations? Can this not show up for any other use-cases where user may not need an upgrade?

Comment (AmanAgarwal041) [reply app/client/src/ce/constants/messages.ts:2695]: This message is shown when the plugin is not available for any particular action -> datasource. Hence, I don't think other than paragon integration there would exist any scenarios where the plugin is not available.

**Review by ankitakinger — APPROVED** [review]
