### PR TITLE
fix: asymmetric padding for sections and zones

### LINKED ISSUE #32209: [Bug]: Avoid reducing paddings in a background-free zone when at least one zone in a section has a background on
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With conditional paddings depending on visual separation it might make sense to reintroduce another constraint: we don’t reduce/remove paddings in a background-free zone as long as at least one zone in a section has background on. This will prevent situations when a content of bordering zones is misaligned.

### Steps To Reproduce

1. add multiple zones to a section
2. Turn off the background on one of the zones and observe the shift in the UI

image

### Public Sample App

_No response_

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://theappsmith.slack.com/files/U03JBF3Q8JE/F06RQK11TNY/cleanshot_2024-03-27_at_20.46.02.mp4

### Version

cloud

### PR DESCRIPTION
**Pull request by KelvinOm**
## Description
Added asymmetric paddings for sections and zones.

https://github.com/appsmithorg/appsmith/assets/11555074/1959c6f2-5e26-4fdd-98e3-ea1bb5e09dae

Fixes #32209   

## Automation

/ok-to-test tags="@tag.Anvil"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8999510824>
> Commit: b714426d3185c9a75523fe98ae4ca75e26f0b249
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8999510824&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: app/client/packages/design-system/widgets/src/components/Flex/src/Flex.tsx [hunk 1]
```diff
@@ -19,6 +21,8 @@ const _Flex = (props: FlexProps, ref: Ref<HTMLDivElement>) => {
     ...rest
   } = props;
 
+  const domProps = filterDOMProps(rest as DOMProps);
```
Comment (KelvinOm) [inline app/client/packages/design-system/widgets/src/components/Flex/src/Flex.tsx:24]: Filtering the data attributes

File: app/client/packages/design-system/widgets/src/index.ts [hunk 2]
```diff
@@ -22,7 +22,6 @@ export * from "./components/ButtonGroup";
 export * from "./components/Select";
 export * from "./components/ContextualHelp";
 
-export * from "./utils";
```
Comment (KelvinOm) [inline app/client/packages/design-system/widgets/src/index.ts:25]: Don't use it

File: app/client/src/layoutSystems/anvil/sectionSpaceDistributor/constants.ts [hunk 3]
```diff
@@ -1,6 +1,6 @@
 export const SpaceDistributorHandleDimensions = {
-  width: 6,
-  offsetTop: 10,
```
Comment (KelvinOm) [inline app/client/src/layoutSystems/anvil/sectionSpaceDistributor/constants.ts:3]: I discussed these changes with Taras. cc @marks0351

File: app/client/packages/design-system/widgets/src/utils/filterDataProps.ts [hunk 4]
```diff
@@ -0,0 +1,12 @@
...
+export const filterDataProps = (props: Record<string, unknown>) => {
+  const result: Record<string, unknown> = {};
+  Object.keys(props).forEach((key) => {
+    if (key.startsWith("data-")) {
+      result[key] = props[key];
+      delete props[key];
+    }
+  });
+
+  return result;
```
[the remark this answers is not in the document]
Comment (marks0351) [reply app/client/packages/design-system/widgets/src/utils/filterDataProps.ts:11]: sounds like a valid comment.

File: app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx [hunk 5]
```diff
@@ -108,6 +106,8 @@ export const AnvilFlexComponent = forwardRef(
         isInner
         {...flexProps}
         className={_className}
+        data-testid="t--anvil-widget-wrapper"
```
Comment (marks0351) [inline app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx:109]: we set a few data attributes in useAnvilWidgetStyles, lets use the same if we don't want these attributes showing up in deploy/preview mode

File: app/client/packages/design-system/widgets/src/utils/filterDataProps.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (KelvinOm) [reply app/client/packages/design-system/widgets/src/utils/filterDataProps.ts:11]: This is expected and consciously done. I need to split the object into two. The object inside the component is obtained by rest operator, so that it affects only the internal state of the component.

File: app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx (hunk 5 above)
Comment (KelvinOm) [reply app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx:109]: I don't think that's necessary. We can also use this attribute for testing in  deploy/preview mode as well. This only for testing purpose. [The behavior in useAnvilWidgetStyles has also been changed](https://github.com/appsmithorg/appsmith/pull/33204/files#diff-bb17b83358a23f0cb4c7d5baf06ef5f5470ff1d76468c053266c493f9b92c1d6R37).

**Comment by ramsaptami** [comment]
@KelvinOm everything lgtm

one feedback: 
section background on, zone background off causes a slight shift to the bottom
https://www.loom.com/share/24f684dacd624d8faee909b005fea02f

**Comment by KelvinOm** [comment]
> @KelvinOm everything lgtm
> 
> one feedback: section background on, zone background off causes a slight shift to the bottom https://www.loom.com/share/24f684dacd624d8faee909b005fea02f

This should already be fixed. Check the latest DP please.

**Comment by ramsaptami** [comment]
@KelvinOm trying it out on the fresh DP, the shift is less chunky but still noticeable

File: app/client/src/layoutSystems/anvil/editor/canvas/styles/anvilEditorVariables.css [hunk 6]
```diff
@@ -50,5 +50,5 @@
   --on-canvas-ui-border-width-1: 1px;
   --on-canvas-ui-border-width-2: 2px;
 
-  --on-canvas-ui-outline-offset: 3px;
+  --on-canvas-ui-outline-offset: 4px;
```
Comment (KelvinOm) [inline app/client/src/layoutSystems/anvil/editor/canvas/styles/anvilEditorVariables.css:53]: I changed this because now we use outline instead of border in sections and zones. 
cc @riodeuno

**Comment by KelvinOm** [comment]
> @KelvinOm trying it out on the fresh DP, the shift is less chunky but still noticeable

Should be fixed.

**Review by riodeuno — APPROVED** [review]

**Review by ramsaptami — APPROVED** [review]
