### PR TITLE
fix: added virtualization to schema structure list for large number of tables in db

### LINKED ISSUE #26361: [Bug]: Page unresponsive due to large number of tables in ds for schema on action change
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Page becomes unresponsive due to large number of tables in postgres db which gets rendered for schema structure.
Slack thread : https://theappsmith.slack.com/archives/C0341RERY4R/p1692014095222679

### Steps To Reproduce

1. Create a postgres datasource having large number of tables
2. Create multiple action for the above datasource
3. Observe on switching between actions the page becomes unresponsive

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
- Added new package for virtualization of list in case of displaying schema structure on the Action Editor right pane and the editor explorer datasource section.
- Due to large number of tables the page was being unresponsive which is now handled by virtualization with random height of accordions in case of schema tables expanded or collapsed.

#### PR fixes following issue(s)
Fixes #26361

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
1. Created a PostGreSQL ds with many tables [101], and checked for the UI of the entity explorer as well as the right side activation schema, to check for scrolling and functionalities.
2. Took a look at developer tools inspect element and noted the virtualization implementation difference, which will fix the issue in case of large number of tables. What ever is visible in the UI, only those many `entity datasourcestructure` lines are seen on the DP [around 6 to 10], as against the entire list in prod [101].
3. Minor UI issues of padding, how the view looks with DS having lesser number of tables etc will be logged and handled separately. 

>
>
#### Issues raised during DP testing
https://github.com/appsmithorg/appsmith/pull/26483#issuecomment-1693235444
>
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by KelvinOm — DISMISSED** [review]

**Comment by btsgh** [comment]
Tested the fix on the above DP and as per Aman's implementation, it seems to be working as per expectation. Do not have as such a huge DS with all the tables like the customer has. But the concept and implementation could be tested with the biggest test DS structure that we have, and that seems to be working fine

There are few UI issues that we spotted, adding the screenshots here. These will be raised as separate bugs if it is agreed upon by all:

virtualization_extrapadding_lessdbs
virtualization_extrapadding
virtualization_twoscrolls

**Comment by btsgh** [comment]
Moving to QA done. Will add TestPlan Approved based on Aman's feedback on whether or not automation is needed/will be handled in a separate PR.

**Review by ChandanBalajiBP — APPROVED** [review]

**Comment by AmanAgarwal041** [comment]
> Tested the fix on the above DP and as per Aman's implementation, it seems to be working as per expectation. Do not have as such a huge DS with all the tables like the customer has. But the concept and implementation could be tested with the biggest test DS structure that we have, and that seems to be working fine
> 
> There are few UI issues that we spotted, adding the screenshots here. These will be raised as separate bugs if it is agreed upon by all:
> 
> virtualization_extrapadding_lessdbs virtualization_extrapadding virtualization_twoscrolls

Created an issue to address the multiple scrollbar issue https://github.com/appsmithorg/appsmith/issues/26714

File: app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructure.tsx [hunk 1]
```diff
@@ -155,6 +172,52 @@ export function DatasourceStructure(props: DatasourceStructureProps) {
...
+  step: number;
+  datasourceId: string;
+  context: DatasourceStructureContext;
+  isDefaultOpen?: boolean;
+  forceExpand?: boolean;
+  currentActionId: string;
+};
+
+const DatasourceStructure = (props: DatasourceStructureProps) => {
+  const [containerHeight, setContainerHeight] = useState<number>();
```
Comment (ayushpahwa) [inline app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructure.tsx:188]: Why do we need to maintain the height in a state?

**Review by ayushpahwa — COMMENTED** [review]
Looks good, just a small question

File: app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructure.tsx (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructure.tsx:188]: Because we need to render the virtualized list only when we have container height fixed. As it is the only required property needed to implement virtualization.

**Comment by sunil8627** [comment]
Hi Team,

This issue was raised when one of my teammates had reached out to appsmith support.

By when can we expect this PR to be merged please? A few of our reports on appsmith are really slow/ unresponsive right now. It would be great to have a fix asap.

Thanks, 
Sunil Pai
sunil@aisle.co

**Comment by AmanAgarwal041** [comment]
@sunil8627 This is on priority and will be merged by the end of this week.

File: app/client/cypress/support/Pages/DataSources.ts [hunk 2]
```diff
@@ -1898,4 +1901,65 @@ export class DataSources {
...
     });
   }
+
+  public AssertTableInVirtuosoList(
+    dsName: string,
+    targetTableName: string,
+    absence = false,
+  ) {
+    this.entityExplorer.ExpandCollapseEntity("Datasources");
+    this.entityExplorer.ExpandCollapseEntity(dsName);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1911]: Can be     `entityExplorer.SelectEntityByName(dsName, "Datasources");`

File: app/client/cypress/support/Pages/DataSources.ts [hunk 3]
```diff
@@ -1898,4 +1901,65 @@ export class DataSources {
...
+    cy.intercept("GET", "/api/v1/datasources/*/structure?ignoreCache=*").as(
+      "getDatasourceStructureUpdated",
+    );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1914]: Why cant existing alias `getDatasourceStructure` be used?

File: app/client/cypress/support/Pages/DataSources.ts [hunk 4]
```diff
@@ -1898,4 +1901,65 @@ export class DataSources {
       );
     });
   }
+
+  public AssertTableInVirtuosoList(
+    dsName: string,
+    targetTableName: string,
+    absence = false,
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1908]: Can it be `presence=true`. `Absence = false` is confusing to read.

File: app/client/cypress/support/Pages/DataSources.ts [hunk 5]
```diff
@@ -1898,4 +1901,65 @@ export class DataSources {
...
+                this.agHelper.ScrollToXY(
+                  this._dsVirtuosoElement(dsName),
+                  0,
+                  `${scrollPercent}%`,
+                );
+              }
+
+              this.agHelper.AssertElementExist(
+                `.t--entity-item[data-testid='t--entity-item-${targetTableName}']`,
+              );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1960]: Can we continue to use  :
```
agHelper.AssertElementAbsence(
      entityExplorer._entityNameInExplorer(targetTableName),
    ); 
Or AssertElementVisibility

File: app/client/cypress/support/Pages/DataSources.ts (hunk 3 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/DataSources.ts:1914]: Ok, this is only an alias. You can use `getDatasourceStructure` also, but you should wait properly to get the latest api call. In this case - let `getDatasourceStructureUpdated` be there.

File: app/client/cypress/support/Pages/DataSources.ts (hunk 2 above)
Comment (AmanAgarwal041) [reply app/client/cypress/support/Pages/DataSources.ts:1911]: We are expanding the sections over here, but `entityExplorer.SelectEntityByName(dsName, "Datasources");` selects the entity and navigates to that entity.

Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/DataSources.ts:1911]: `SelectEntityByName` will expand the section that is sent in 2nd parameter. So this  `entityExplorer.SelectEntityByName(dsName, "Datasources");` will expand '`Datasources`' while also selecting `dsName` after expanding. In this case do you also want to expand `dsName`?

File: app/client/cypress/support/Pages/DataSources.ts (hunk 5 above)
Comment (AmanAgarwal041) [reply app/client/cypress/support/Pages/DataSources.ts:1960]: `AssertElementExist` is also an aghelper function. Any reason why should we use `AssertElementAbsence` or `AssertElementVisibility` in specific ?

Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/DataSources.ts:1960]: `AssertElementExist` will check if element is in DOM - which can be invisible also. But here I hope the goal is to check if the table is visible or not under respective datasources & suggested methods does that.

File: app/client/cypress/support/Pages/DataSources.ts (hunk 2 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/DataSources.ts:1910]: Ok, let `dsName` also be expanded. It will help to see if table is visible or not in UI for debug

File: app/client/cypress/support/Pages/DataSources.ts (hunk 5 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/DataSources.ts:1957]: @AmanAgarwal041 - any update here?

Comment (AmanAgarwal041) [reply app/client/cypress/support/Pages/DataSources.ts]: Done

File: app/client/cypress/support/Pages/DataSources.ts [hunk 6]
```diff
@@ -1897,4 +1900,65 @@ export class DataSources {
...
+                this.agHelper.ScrollToXY(
+                  this._dsVirtuosoElement(dsName),
+                  0,
+                  `${scrollPercent}%`,
+                );
+              }
+
+              this.agHelper.AssertElementVisibility(
+                `.t--entity-item[data-testid='t--entity-item-${targetTableName}']`,
+              );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1957]: No direct locator please. Try to check feasibility of 
```agHelper.AssertElementVisibility(
      entityExplorer._entityNameInExplorer(targetTableName),
    );
```

Comment (AmanAgarwal041) [reply app/client/cypress/support/Pages/DataSources.ts]: Done

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes.

**Comment by Aishwarya-U-R** [comment]
> Workflow run: https://github.com/appsmithorg/appsmith/actions/runs/6197843638. Commit: `a3d1681`. Cypress dashboard url: [Click here!](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6197843638&attempt=1) All cypress tests have passed 🎉🎉🎉

@AmanAgarwal041 - Ignore this all pass. Please merge latest & trigger run again.. This is due to bug that is [fixed now in this](https://github.com/appsmithorg/appsmith/pull/27354)

**Review by sneha122 — APPROVED** [review]

**Comment by AmanAgarwal041** [comment]
Adding `Test Plan Approved` label as Cypress tests approved by Aishwarya and tested by Prapulla and Aparna.
