### PR TITLE
fix: added empty stack in sppThemingReducer

### LINKED ISSUE #13836: [Bug]: "Change theme" property pane persists between the apps
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Change theme property pane persists between the apps. 

Environment  = RELEASE

https://user-images.githubusercontent.com/14138515/168325295-63345dec-6b84-494f-960f-387abd1650ba.mov

### Steps To Reproduce

1. Create a new app.
2. Click on the change theme in the property pane.
3. Now click on the appsmith icon in the top left corner to open all the applications.
4. Now open a new app, and observe that the "Change theme property pane" still persists.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by keyurparalkar**
## Description

**Summary of Changes**

Emptied the theming stack when REDUX Action FETCH_APP_THEMES_SUCCESS is executed.

Fixes #13836 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/fix-reset-theme-stack 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.62 **(0.01)** | 38.56 **(0.01)** | 35.9 **(0)** | 56.86 **(0)**
 :red_circle: | app/client/src/reducers/uiReducers/appThemingReducer.ts | 28 **(-1.17)** | 100 **(0)** | 13.33 **(0)** | 28 **(-1.17)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 **(0.25)**</details>

### CODE REVIEW

File: app/client/src/reducers/uiReducers/appThemingReducer.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ const themeReducer = createImmerReducer(initialState, {
   ) => {
     state.themesLoading = false;
     state.themes = action.payload;
+    state.stack = [];
```
Comment (jsartisan) [inline app/client/src/reducers/uiReducers/appThemingReducer.ts:74]: @keyurparalkar Why is required? 🤔

Comment (jsartisan) [reply app/client/src/reducers/uiReducers/appThemingReducer.ts:74]: nvm. got it.

**Review by jsartisan — APPROVED** [review]
