### PR TITLE
fix: correct placeholder text for graphql action editor

### LINKED ISSUE #41422: [Bug]: Placeholder text for GraphQL Actions is incorrect
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When creating a new Custom GraphQL Action, for any SaaS datasource that uses it, it gives the following incorrect placeholder text:

```js
{{
  query {
    name: inputName.property
  }
}}
```

This query fails and sends a blank query as shown below.

Image

Instead it needs to be formatted like so:

```graphql
query myQuery($name: String!) {
  team(name: $name) {
    id
    name
    description
  }
}
```

With an appropriate variables placeholder text:

```js
{
  "name": {{inputName.text}}
}
```

### Steps To Reproduce

1. Create a new app.
2. Create and Auth a Linear datasource.
3. Create a new query.
4. Select Custom GraphQL Action from the dropdown.
5. Set the method to POST
6. Set the endpoint to `/`
7. Populate the variables field with this value:
  a. You can run an empty Search Teams query to get a teamId, but it should also run fine with an empty string.
  b. Label name is any human readable label on an issue. Bug should work for us.

```json
{
  "teamId": "your_team_id",
  "labelName": "Bug"
}
```

8. Populate the Query field with this value:

```graphql
{{
query IssuesByLabel($teamId: String!, $labelName: String!) {
  team(id: $teamId) {
    id
    name
    issues(filter: { labels: { some: { name: { eq: $labelName } } } }) {
      nodes {
        id
        identifier
        title
        description
        labels {
          nodes {
            id
            name
          }
        }
        createdAt
        updatedAt
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
}}
```

9. Run the query.
10. Observe the following error:

Image

11. Remove the `{{ }}` from the query like so:

```graphql
query IssuesByLabel($teamId: String!, $labelName: String!) {
  team(id: $teamId) {
    id
    name
    issues(filter: { labels: { some: { name: { eq: $labelName } } } }) {
      nodes {
        id
        identifier
        title
        description
        labels {
          nodes {
            id
            name
          }
        }
        createdAt
        updatedAt
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
```

12. Run the query again.
13. Observe the successful response.

### Public Sample App

_No response_

### Environment

Release

### Severity

Medium (Frustrating UX)

### Issue video log

_No response_

### Version

v1.93.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by LagunaElectric**
## Description
This PR replaces the placeholder text for custom graphql actions with a valid example.

Fixes #41422 

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/19724407878>
> Commit: ac5f41c3cb884c8c44708f730abe2495be0f0762
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=19724407878&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Thu, 27 Nov 2025 04:22:34 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

* **Documentation**
  * Simplified the example payload shown in the GraphQL variables editor and updated the GraphQL query template placeholder to a clearer, concrete example for improved clarity in the configuration UI.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by LagunaElectric** [comment]
This will also fix https://github.com/appsmithorg/appsmith/issues/23335

File: app/client/src/components/formControls/CustomActionControls/CustomGraphQLActionsConfigControl.tsx [hunk 1]
```diff
@@ -46,8 +46,7 @@ const StyledFormLabel = styled(FormLabel)`
 
 const EXPECTED_VARIABLE = {
   type: "object",
-  example:
-    '{\n  "name":"{{ inputName.property }}",\n  "preference":"{{ dropdownName.property }}"\n}',
+  example: '{\n  "name": "{{ inputName.property }}"\n}',
```
Comment (tomjose92) [inline app/client/src/components/formControls/CustomActionControls/CustomGraphQLActionsConfigControl.tsx]: Instead of inputName.property can we use something like inputName.text. As none of our widgets has a attribute called property that is exposed

File: app/client/src/PluginActionEditor/components/PluginActionForm/components/GraphQLEditor/PostBodyData.tsx [hunk 2]
```diff
@@ -53,7 +52,7 @@ function PostBodyData(props: Props) {
               evaluatedPopUpLabel={"Query"}
               mode={EditorModes.GRAPHQL_WITH_BINDING}
               name="actionConfiguration.body"
-              placeholder={`{{\n\t{name: inputName.property, preference: dropdownName.property}\n}}`}
+              placeholder={`query myQuery($name: String!) {\n  team(name: $name) {\n\tid\n\tname\n  }\n}`}
```
Comment (tomjose92) [inline app/client/src/PluginActionEditor/components/PluginActionForm/components/GraphQLEditor/PostBodyData.tsx:55]: The other file where this change needs to be made is app/client/src/PluginActionEditor/components/PluginActionForm/components/GraphQLEditor/PostBodyData.tsx

File: app/client/src/components/formControls/CustomActionControls/CustomGraphQLActionsConfigControl.tsx (hunk 1 above)
Comment (LagunaElectric) [reply app/client/src/components/formControls/CustomActionControls/CustomGraphQLActionsConfigControl.tsx]: Done
