### PR TITLE
fix: current item in widget that uses current item internally

### LINKED ISSUE #19155: [BUG]: CurrentItem is not updated in Table Widget and JSONForm Widget
Add a Table widget or JSONForm and change the Table Data or source data respectively to 

TableData
```
{{[
	currentItem
]}}
```
or Source Data
```
{{currentItem}}
```

The table or JSON Form doesn't receive the correct value when you switch pages

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

1. Added new Meta Widget action to update properties from Batch Update Properties
2. Find and replace meta widget name in Meta generator Bindings

Fixes #19155

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts [hunk 1]
```diff
@@ -798,13 +798,27 @@ class MetaWidgetGenerator {
...
+  private updateWidgetNameInDynamicBinding = (
+    binding: string,
+    metaWidgetName: string,
+    templateWidgetName: string,
+  ) => {
+    if (metaWidgetName === templateWidgetName) return binding;
+
+    const pattern = new RegExp(`${templateWidgetName}.`, "g");
+
+    const output = binding.replace(pattern, `${metaWidgetName}.`);
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:810]: return directly

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts [hunk 2]
```diff
@@ -798,13 +798,27 @@ class MetaWidgetGenerator {
     metaWidget.level = this.level + 1;
   };
 
+  private updateWidgetNameInDynamicBinding = (
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:801]: I think this is going to enable something greater than fixing Table/JSONform.
If in a template widget we do in the property pane `Input1.isValid` in defaultValue of that Input1 then we are going to replace the `Input1` to the correct metaWidgetName.

Can we verify this add cypress tests for this.

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 3]
```diff
@@ -818,9 +818,20 @@ class ListWidget extends BaseWidget<
     const templateWidgetId = this.metaWidgetGenerator.getTemplateWidgetIdByMetaWidgetId(
       metaWidgetId,
     );
-    const widgetId = templateWidgetId || metaWidgetId;
-
-    this.context?.batchUpdateWidgetProperty?.(widgetId, updates, shouldReplay);
+    const widgetId = metaWidgetId || templateWidgetId;
+    if (!templateWidgetId) {
```
[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:822]: I've added comments in the code.

The template widget/Canvas widgets don't have templateWidgetId so `batchUpdateWidgetProperty` is called to update them.

For the MetaWidgets, we update their properties using the MetaWidgetReducer.

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts]: Having this would cause Cyclic Dependency.

Also, the Ideal way would be to use `currentView.Input1.isValid`

Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts]: But the logic the you have in place would rename right? And would it also rename if I have `currentView.Input1.isValid`?

Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts]: This also wont be possible, Only if is in another widget `currentView.Input1.isValid`

Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts]: https://user-images.githubusercontent.com/31691737/212059830-b15a76dd-899e-450f-a5d6-86c8b59a439b.mov

Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts]: So even if we don't show `Input1` in `currentView` it still gets added and causes cyclic dependency error. I think we can easily avoid this.

Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts]: No it doesn't get added.

I might not be understanding the previous comment though.

Screenshot 2023-01-12 at 11 58 57
Screenshot 2023-01-12 at 11 59 12

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:824]: So if `templateWidgetId` is present then it is a meta widget then we are calling `updateMetaWidgetProperty` with the `templateWidgetId`? due to line 821?

[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:824]: Exactly

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts (hunk 2 above)
Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts]: It's not showing in autocomplete but it seems to be getting added and that is why we are getting cyclic dependencies. I tried in my local as well.

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:824]: Are we suppose to call `updateMetaWidgetProperty` with the metaWidgetId rather than the `templateWidgetId`?

[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:824]: We're to call it with the metaWidgetId.
Since, we want to update the MetaWidgets and not the Template widget.

Also this enables us to store the updates from this metaWidgets in the MetaWidgetState

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts]: Oh, got it

**Review by ashit-rath — COMMENTED** [review]
Review feedback discussed sync.

**Review by ashit-rath — APPROVED** [review]
