### PR TITLE
fix: incorrect icon being used for chevron-right

### LINKED ISSUE #8886: [Bug]:Inconsistent arrow displayed in the deploy mode when there are more number of pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inconsistent arrow displayed in the deploy mode when there are more number of pages

### Steps To Reproduce

1. Go to canvas 
2. Add at least 10 pages 
3. Now deploy the application 
4. There is an inconsistent arrow displayed in the Page name header

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by akash-codemonk**
Fixes #8886 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/page-names-arrow 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | app/client/src/components/ads/Icon.tsx | 50.53 **(-0.28)** | 33.33 **(-0.44)** | 100 **(0)** | 50.4 **(-0.28)**</details>

### CODE REVIEW

File: app/client/src/components/ads/Icon.tsx [hunk 1]
```diff
@@ -26,6 +26,7 @@ import { ReactComponent as ManageIcon } from "assets/icons/ads/manage.svg";
 import { ReactComponent as ArrowLeft } from "assets/icons/ads/arrow-left.svg";
 // import { ReactComponent as Fork } from "assets/icons/ads/fork.svg";
 import { ReactComponent as ChevronLeft } from "assets/icons/ads/chevron_left.svg";
+import { ReactComponent as ChevronRight } from "assets/icons/ads/chevron_right.svg";
```
Comment (albinAppsmith) [inline app/client/src/components/ads/Icon.tsx:29]: This should not be svg file. All icons should come from remix icon package

**Review by albinAppsmith — CHANGES_REQUESTED** [review]

File: app/client/src/pages/AppViewer/viewer/PageTabsContainer.tsx [hunk 2]
```diff
@@ -16,7 +17,7 @@ const Container = styled.div`
   & {
     svg path,
     svg:hover path {
-      fill: transparent;
+      fill: ${Colors.BLACK};
```
Comment (albinAppsmith) [inline app/client/src/pages/AppViewer/viewer/PageTabsContainer.tsx:20]: This may affect somewhere else

**Review by albinAppsmith — CHANGES_REQUESTED** [review]

**Review by albinAppsmith — APPROVED** [review]
