### PR TITLE
fix: run validateLicense in case we are at /license after login

### LINKED ISSUE #29166: [Task] Fix Cypress Test cases related to License flow in case the Instance does not start with a License
[Task] Fix Cypress Test cases related to License flow in case the Instance does not start with a License

### PR DESCRIPTION
**Pull request by dipyamanbiswas07**
## Description

Fix Cypress Test cases related to License flow in case the Instance does not start with a License

#### PR fixes following issue(s)
Fixes #29166

- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/support/commands.js [hunk 1]
```diff
@@ -364,6 +364,15 @@ Cypress.Commands.add("LoginFromAPI", (uname, pword) => {
...
 
+    if (CURRENT_REPO === REPO.EE) {
+      cy.wait(2000);
+      cy.url().then((url) => {
+        if (url.indexOf("/license") > -1) {
+          cy.validateLicense();
+        }
+      });
+    }
+
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/commands.js:375]: Since we added it here, can we please remove from e2e.js?
