### PR TITLE
fix: fix page load action execution order

### LINKED ISSUE #10049: [Bug]: Dependency not executed in expected order in layoutOnLoadActions when dependency added via URL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
"layoutOnLoadActions": [
					[
						{
							"id": "61cc1e5cd87e61534bb1e705",
							"name": "CatImage",
							"pluginType": "API",
							"jsonPathKeys": [

							],
							"timeoutInMillisecond": 10000
						},
						{
							"id": "61cc2563d87e61534bb1e709",
							"name": "Genderize",
							"pluginType": "API",
							"jsonPathKeys": [
								"Suggestions.data.type"
							],
							"timeoutInMillisecond": 10000
						}
					],
					[
						{
							"id": "61cc1bd6d87e61534bb1e703",
							"name": "CatFacts",
							"pluginType": "API",
							"jsonPathKeys": [
								"CatImage.data"
							],
							"timeoutInMillisecond": 10000
						}
					],
					[
						{
							"id": "61cc23edd87e61534bb1e707",
							"name": "Suggestions",
							"pluginType": "API",
							"jsonPathKeys": [
								"CatFacts.data"
							],
							"timeoutInMillisecond": 10000
						}
					]
				]
```

### Steps To Reproduce

1. Create Api1 - 'CatImage'
2. Create Api2 - 'CatFacts' - Dependent on Api1 - added via Header
3. Create Api3 - 'Suggestions' - Dependent on Api2 - added via Header
4. Create Api4 - 'Genderize' - Dependent on Api3 - added via url & not params
5. Map all of the results to widgets
6. Refresh page & observe

### Environment

Release

### Version

Self-Hosted

### LINKED ISSUE #10242: [Bug]: on page load computation order fails when all actions are only user set page load actions.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Create `action1` and `action2`. Don't bind them to any widgets.
- Make `action2` dependent on `action1` by binding `{{action1.data}}` in `action2`. 
- Set both actions to run on page load via settings. 
- Check page load actions order in `dsl`. Ideally, `action1` is expected to run first then `action2` - however both actions are set to load at the same time. 

### Steps To Reproduce

- explained above.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- This PR fixes the page load action execution order when the actions have been set to run on page load explicitly via the settings tab by the user and its data has not been referenced in any other widget or action. e.g.
  - create `action1` and `action2`.
  - make `action2` dependent on `action1` by adding `{{action1.data}}` in `action2`'s body.
  - set both `action1` and `action2` to run on page load via settings tab. Do not reference `action1` and `action2` data in any other widget or action.

Fixes #10242 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit TC
- Manual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java [hunk 1]
```diff
@@ -927,13 +927,21 @@ private boolean hasUserSetActionToNotRunOnPageLoad(ActionDTO unpublishedAction)
...
+                 * Add action for page load if:
+                 *  o it has been explicitly set to run on page load by the user (even if its data is not
                  *  referenced in any widget or action)
+                 *  o or, it is not a function call i.e. the data of this call is being referred to in the binding.
                  */
-                String validBinding = entity + "." + "data";
-                if (!vertex.contains(validBinding) && !explicitUserSetOnLoadActions.contains(entity)) {
+
+                String validBinding;
+                if (explicitUserSetOnLoadActions.contains(entity)) {
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java:937]: How would the following scenario be handled : 
Action1 has been explicitly set to run on page load and text1.text has the binding : {{Action1.data}}. Also note that Action1 has no bindings in its configuration.

Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java:937]: @trishaanand IMO, we would have the following relationship in our `DAG` : `Action1.actionConfiguration` `-->` `Action1` and hence it would get added since the `validBinding` in the `if` branch would match.

Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java:937]: @trishaanand I have added a TC to capture this scenario.

**Review by trishaanand — APPROVED** [review]
