### PR TITLE
FIX #5287 : updated isLoading state when event action completed

### LINKED ISSUE #5287: [Bug] File picker keeps in loading state when File select property is set
### Steps to reproduce the behaviour:

1. Drag and drop file picker widget
2. Set "On file selected property"
3. Now try uploading the file
4. Observe that after upload the loader on the widget keeps in loading state

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: production

https://www.loom.com/share/dcc6387e38e24a80a243de0439e798c2

### LINKED ISSUE #5312: [Bug] Filepicker button gets stuck in a loading state if we set the action to `copyToClipboard`
## Description
Filepicker button gets stuck in a loading state if we set the action to `copyToClipboard`

### Steps to reproduce the behaviour:
1. Drag a filepicker to the canvas
2. Set the `onFilesSelected` action as `copyToClipboard`
3. Upload a file
4. The filepicker gets stuck in a loading state

image

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Picking a file in filepicker keeps on loading. The loading state was not stopped by default fixed it. 

Fixes #5287 
Fixes #5312 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: FIX/5287-filepicker-keep-loading-state 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.24 **(-0.01)** | 35.22 **(0)** | 31.93 **(-0.01)** | 53.76 **(0)**
 :red_circle: | app/client/src/widgets/FilepickerWidget.tsx | 38.46 **(-0.87)** | 0 **(0)** | 17.86 **(-0.66)** | 37.78 **(-0.86)**</details>

### CODE REVIEW

File: app/client/src/widgets/FilepickerWidget.tsx [hunk 1]
```diff
@@ -384,13 +384,18 @@ class FilePickerWidget extends BaseWidget<
         dynamicString: this.props.onFilesSelected,
         event: {
           type: EventType.ON_FILES_SELECTED,
+          callback: this.handleActionComplete,
```
Comment (somangshu) [inline app/client/src/widgets/FilepickerWidget.tsx:387]: @SatishGandham does this look fine?

**Review by somangshu — APPROVED** [review]
Approving to run tests

**Comment by somangshu** [comment]
@vivekverma2312 need your sign off here

**Comment by YogeshJayaseelan** [comment]
@vibhandikyash @somangshu 

Tested issues 5287 and 5312 in-which 5287 is fixed and 5312 still exists, please find the below video for 5312

https://www.loom.com/share/3a3492fe63664d3a8f770b2170edb90c

**Review by SatishGandham — APPROVED** [review]

**Comment by somangshu** [comment]
@YogeshJayaseelan is the issue fixed, @vibhandikyash can you confirm that both cases work in the deploy preview.

**Comment by YogeshJayaseelan** [comment]
@vibhandikyash @somangshu Tested issue #5312 and is working as expected
