### PR TITLE
Fix binding query for the nested data responses

### LINKED ISSUE #6103: [Bug]When the user select the suggested widgets the Bindings Fails for Select, Chart and Text widget
## Description When the user select the suggested widgets the Bindings Fails for Select, Chart and Text widget 

[What happened]

https://loom.com/share/0e57b88b831c45ae9a36344414a5f353
https://loom.com/share/9f93de4bba2948ac8663af5fac95f123

### Important Details

- Version: [Cloud ]
- Browser Chrome
- Environment [deploy preview]

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

> For nested data structures, after suggesting the widget the binding query doesnt work properly. This change address that issue.
Fixes #6103 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> 
- Unit Tests
- Manually in local environment

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java [hunk 1]
```diff
@@ -2073,4 +2068,13 @@ private WidgetSuggestionDTO getWidget(WidgetType widgetType, Object... args) {
         return  widgetSuggestionDTO;
     }
 
+    private static WidgetSuggestionDTO getWidgetNestedData(WidgetType widgetType, String nestedFieldName, Object... args) {
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java:2071]: Any reason we are duplicating this function in the source code & the test? 

Also, can you please format the code? I think the formatting is off in a couple of places.

Comment (AnaghHegde) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java:2071]: The reason is when we have the nested data, the binding query changes from `data.map()` -> `data.fieldName.map()`. I can add this check in the same function with an if condition and i would be doing that check on every time. So to avoid that i added a new function.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/WidgetSuggestionHelper.java [hunk 2]
```diff
@@ -150,12 +168,39 @@ private static void collectFieldsFromData(Iterator<Map.Entry<String, JsonNode>>
         return widgetTypeList;
     }
 
+    private static List<WidgetSuggestionDTO> getWidgetsForTypeNestedObject(String nestedFieldName) {
+        List<WidgetSuggestionDTO> widgetTypeList = new ArrayList<>();
+        if(!fields.isEmpty()) {
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/WidgetSuggestionHelper.java:173]: Can you please add some comments explaining what is happening in these if-clauses? For eg, what data structure leads to what resultant widget etc?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java (hunk 1 above)
Comment (mohanarpit) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java:2071]: I meant, why do we have the same function `getWidgetNestedData(...)` in `ActionServiceTest` & `WidgetSuggestionHelper` classes? Can we not just use the function available in `WidgetSuggestionHelper` here?

Comment (AnaghHegde) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java]: @mohanarpit ready for review

**Review by mohanarpit — APPROVED** [review]
