### PR TITLE
fix: show correct dependency list for widgets even if one's name is substring of other widget 

### LINKED ISSUE #7714: [Bug] Incorrect dependency list is shown if name of one widget is substring of some other widget
## Description
New Input widget added to the canvas is automatically binding to table data that was generate using CRUD

### Steps to reproduce the behaviour:
1. Generate a page using CRUD operation
2. Drag and drop **input widget** on to the canvas and observe the **input widget** automatically binding itself to the table data but not appear in the **outgoing entities** of table data

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[LOOM DEMO](https://www.loom.com/share/7ebaddb8c1794de2b05db0d2f7317dde)

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
Removed the use of `includes`

Fixes #7714 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Added jest test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/dependency-issues-on-widget-name-overlap 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | app/client/src/components/editorComponents/Debugger/helpers.tsx | 80 **(0.31)** | 79.17 **(0)** | 37.5 **(0)** | 80 **(0.37)**</details>

### CODE REVIEW

File: app/client/src/components/editorComponents/Debugger/helpers.tsx [hunk 1]
```diff
@@ -70,24 +70,19 @@ export function getDependenciesFromInverseDependencies(
   const inverseDependencies = new Set<string>();
 
   Object.entries(deps).forEach(([dependant, dependencies]) => {
+    const entity = dependant
+      .split(".")
+      .slice(0, 1)
+      .join("");
```
Comment (akash-codemonk) [inline app/client/src/components/editorComponents/Debugger/helpers.tsx:76]: To get the entityName can we use [getEntityName](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/workers/evaluationUtils.ts#L72)?

**Review by akash-codemonk — CHANGES_REQUESTED** [review]

**Comment by akash-codemonk** [comment]
Also can we add a test [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/editorComponents/Debugger/helpers.test.ts#L8)

**Review by akash-codemonk — APPROVED** [review]

**Review by akash-codemonk — APPROVED** [review]
