### PR TITLE
[Issue #2689][Bug] Duplicate Accounts with Same Email - Field is Case…

### LINKED ISSUE #2689: [Bug] Duplicate Accounts with Same Email - Field is Case Sensitive
## Description

[What happened]
I couldn't remember the email associated with my account and tried everything. Next step was to go into Mongo and view the user records, realized I used a capitol letter in the email. No problem, went back to login using the case sensitive string and was in. 

So for testing reasons, I decided to create another account with the same email using all lowercase letters. I was successfully able to create two accounts tied to the same email. 

### Steps to reproduce the behavior:
Add steps to reproduce this behavior, include console / network logs & screenshots
1. Go to ' Sign up page'
2. Create an account with an email such as 'test@domain.com'
3. Enter password and create account
4. Sign out of that account
5. Go to sign up again
6. Create another account  with an email 'TesT@domain.com
7. enter password and create account.
4. You should now have two separate accounts with the same email. 

### Important Details
 - Version: [Self-Hosted v1.3.1]
 - OS: [Synology NAS DSM 6.2.3]
 - Browser [Chrome]

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
Currently, the signup by email treats case sensitive emails as different ones. So it's possible to create two accounts with `rafiqnayan@gmail.com` and `rafiqNayan@gmail.com`. This PR fixes this issue for the new signups.

Fixes #2689 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Unit test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java [hunk 1]
```diff
@@ -432,6 +432,9 @@ public UserServiceImpl(Scheduler scheduler,
                 return Mono.error(new AppsmithException(AppsmithError.INVALID_CREDENTIALS));
             }
             user.setPassword(passwordEncoder.encode(user.getPassword()));
+
+            // convert the email to lowercase if it's form signup so that abc@gmail and aBc@gmail are treated as same
+            user.setEmail(user.getEmail().toLowerCase());
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java:437]: I'm curious about whether we intend to handle existing duplicates as well?

**Comment by nidhi-nair** [comment]
LGTM @nayan-appsmith, you might want to change to description of the PR where it references the issue to the format:
Fixes #2689 
^(removed extra space to allow linking) This allows Github to automatically attach the issue to this PR and close the issue when this PR gets merged. Our QA team may miss out on testing this fix if the issue remains open.

**Comment by sharat87** [comment]
Hey @nayan-appsmith, if I understand this correctly, we are automatically converting the user's email address to lower case when they sign up. So, if I sign up with `SHRIKANT@appsmith.com`, the system is _actually_ signing me up as `shrikant@appsmith.com`. But I, as a user, am unaware of this. So when I try to login now with `SHRIKANT@appsmith.com`, it would fail, right? Since we are not converting emails to lower case when logging in? Please correct me if I'm missing something. Thanks!

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java (hunk 1 above)
Comment (nayan-appsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java:437]: @nidhi-nair As per our discussion, we'll not fix the existing duplicates now as it is a huge migration operation.

**Comment by nayan-appsmith** [comment]
> Hey @nayan-appsmith, if I understand this correctly, we are automatically converting the user's email address to lower case when they sign up. So, if I sign up with `SHRIKANT@appsmith.com`, the system is _actually_ signing me up as `shrikant@appsmith.com`. But I, as a user, am unaware of this. So when I try to login now with `SHRIKANT@appsmith.com`, it would fail, right? Since we are not converting emails to lower case when logging in? Please correct me if I'm missing something. Thanks!

@sharat87 That's a very good point, I missed it. Do you have any suggestion on that? What I'm thinking is - fail the validation if there is an uppercase letter in email. Does that make sense?

**Comment by sharat87** [comment]
I'd prefer something like the second. Where the case of the email doesn't matter for both signup and login. So, if we automatically apply `.toLowerCase()` on emails for login as well, this problem should go away.

But that would bring up another problem. If emails are going to be lowe-cased for login, that means whoever is logging in with upper case emails today, won't be able to login anymore. We'll need a migration path as part of this PR itself in that case.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserRepositoryImpl.java [hunk 2]
```diff
@@ -25,8 +26,15 @@ public CustomUserRepositoryImpl(ReactiveMongoOperations mongoOperations, MongoCo
...
     public Mono<User> findByEmail(String email, AclPermission aclPermission) {
         Criteria emailCriteria = where(fieldName(QUser.user.email)).is(email);
-
         return queryOne(List.of(emailCriteria), aclPermission);
     }
 
+    @Override
+    public Mono<User> findByCaseInsensitiveEmail(String email) {
+        String findEmailRegex = String.format("^%s$", email);
+        Criteria emailCriteria = where(fieldName(QUser.user.email)).regex(findEmailRegex, "i");
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserRepositoryImpl.java:35]: I think we need to escape regex special characters in the email before using it as the pattern. Otherwise, if the email is `a.c@gmail.com`, it will match both `a.c@gmail.com` and `abc@gmail.com`. Something like this might do:

```suggestion
        String findEmailRegex = String.format("^%s$", email.replaceAll("[.+*?\\[\\]|]", "\\$0"));
        Criteria emailCriteria = where(fieldName(QUser.user.email)).regex(findEmailRegex, "i");
```

File: app/server/appsmith-server/src/main/resources/application.properties [hunk 3]
```diff
@@ -91,4 +91,4 @@ signup.allowed-domains=${APPSMITH_SIGNUP_ALLOWED_DOMAINS:}
 
 # Google recaptcha config
 google.recaptcha.key.site = ${APPSMITH_RECAPTCHA_SITE_KEY:}
-google.recaptcha.key.secret= ${APPSMITH_RECAPTCHA_SECRET_KEY:}
+google.recaptcha.key.secret= ${APPSMITH_RECAPTCHA_SECRET_KEY:}
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/resources/application.properties:94]: There doesn't seem to be any change in this right? Just the blank line at the end of the file. Can we revert it?

```suggestion
google.recaptcha.key.secret= ${APPSMITH_RECAPTCHA_SECRET_KEY:}

```

**Comment by sharat87** [comment]
@nayan-appsmith, for login, we want to check if there is a _case-sensitive_ email match first, if that fails, then we want to do a _case-insensitive_ match, correct? Can you elaborate a bit on where this is happening as I couldn't find the code doing this? Thanks!

**Comment by nayan-appsmith** [comment]
@sharat87 I didn't implement that way. I was able to do the query `findUserByCaseInsensitiveEmail` which also uses index. This makes sure we're not creating duplicate emails anymore during signup. I also removed the code that converts the email to lowercase during signup. Do you think we need to do any additional check during login now?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserRepositoryImpl.java (hunk 2 above)
Comment (nayan-appsmith) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserRepositoryImpl.java]: @sharat87 Great finding. There was a bug. I've fixed it using the `Pattern.quote` method. Also added a test for it.

Comment (sharat87) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserRepositoryImpl.java]: Ah nice! I didn't realize MongoDB's regex engine supported the `\Q` and `\E` directives that `Pattern.quote` adds.

**Review by sharat87 — APPROVED** [review]
