### PR TITLE
fix: PhoneInputWidget crash on switching environment

### LINKED ISSUE #26693: [Bug]: page breaks down during environment switch if Phone input widget  is present with inputs inside it
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/a7f72d3bb13e4be6bb6ac54a9e923267

### Steps To Reproduce

1. DnD a phone input widget
2. Deploy
3. add some input in the phone widget and switch the environment, The page breaks

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud/Self-Hosted

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
#### PR fixes following issue(s)
Fixes #26693 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan

1. Dragged and dropped phone input widget on canvas and deployed the app - Entered value and switched environments. 
2. Set a default value for phone input widget, and deployed the app - switched environments. 
3. Dragged and dropped  other input widgets [Currency / Input] - and deployed, switched environments

>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/widgets/PhoneInputWidget/widget/index.tsx [hunk 1]
```diff
@@ -276,11 +276,13 @@ class PhoneInputWidget extends BaseInputWidget<
     ) {
       const formattedValue = this.getFormattedPhoneNumber(this.props.text);
 
-      this.props.updateWidgetMetaProperty(
-        "value",
-        parseIncompletePhoneNumber(formattedValue),
-      );
-      this.props.updateWidgetMetaProperty("text", formattedValue);
+      formattedValue &&
```
Comment (sbalaji1192) [inline app/client/src/widgets/PhoneInputWidget/widget/index.tsx:279]: can we move this two statements into an if block?

Comment (ChandanBalajiBP) [reply app/client/src/widgets/PhoneInputWidget/widget/index.tsx]: Updated

**Review by sbalaji1192 — APPROVED** [review]
