### PR TITLE
fix: cursor position not between parenthesis for function autocomplete

### LINKED ISSUE #20449: [Bug]-[680]:Cursor not between parenthesis when function is autocompleted
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a function is "autocompleted", the cursor is expected to be in between the parenthesis 

### Steps To Reproduce

1. Create a JS Object
2. In any of the functions, type {{show}}
3. Select showAlert() hint
4. See cursor position

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ravikp7**
## Description
When using autocomplete suggestion, earlier on selecting a function the cursor was placed at the end of the parenthesis forcing the user to press one more key (left arrow) before filling the arguments. Now the cursor is placed right between the parenthesis.

Fixes #20449 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts [hunk 1]
```diff
@@ -109,4 +109,16 @@ describe("Autocomplete bug fixes", function () {
...
+    ee.SelectEntityByName("Text1");
+    propPane.TypeTextIntoField("Text", "{{console.l");
+
+    agHelper.GetNClickByContains(locator._hints, "log");
+
+    propPane.TypeTextIntoField("Text", '"hello"', false);
+
+    // If the cursor was not between parenthesis, the following command will fail
+    propPane.ValidatePropertyFieldValue("Text", '{{console.log("hello")}}');
+  });
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts:123]: Can we include cypress for one JS object also. For which bug as raised originally.
This case looks good otherwise.

**Review by Aishwarya-U-R — COMMENTED** [review]
CAn

**Review by Rishabh-Rathod — DISMISSED** [review]
Code LGTM.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts (hunk 1 above)
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts:124]: @Aishwarya-U-R I've added test case for JS object also, please review.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts [hunk 2]
```diff
@@ -121,4 +122,35 @@ describe("Autocomplete bug fixes", function () {
...
+        completeReplace: true,
+        toRun: false,
+        shouldCreateNewJSObj: true,
+        prettify: false,
+      },
+    );
+
+    agHelper.GetNClick(jsEditor._lineinJsEditor(3));
+
+    cy.get(jsEditor._lineinJsEditor(3)).type("console.l");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts:144]: ` _.agHelper.TypeText(_.locators._codeMirrorTextArea, "console.l");` - can be used.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts [hunk 3]
```diff
@@ -121,4 +122,35 @@ describe("Autocomplete bug fixes", function () {
...
+
+    agHelper.GetNClickByContains(locator._hints, "log");
+
+    cy.get("body").type("'hello'");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts:148]: Try same as above.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts (hunk 2 above)
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts]: Done

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts (hunk 3 above)
Comment (ravikp7) [reply app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts]: Done. Thanks!

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good.

**Comment by shwetha-ramesh** [comment]
@ravikp7 Tested on this [DP](https://appsmith-gcib2dky3-get-appsmith.vercel.app/applications). Working as expected, moving to done
