### PR TITLE
fix: load main container without waiting for evaluations to complete.

### LINKED ISSUE #3825: [Bug] Canvas breaks for new users
## Description

A few users on smartlook have a broken canvas that cannot be used
https://app.smartlook.com/org/9b6c5c859e85745d01196fa4/project/e373e3a21d27278fd281d8b0/recordings?filter=e072f0526cba4d894bf7765c0d2f52c94f3950db86a7c623e39fc359c88dc938&playSession=J9j2VR8AOkh&playVisitor=YsZlYJHwx-U

### PR DESCRIPTION
**Pull request by marks0351**
## Description

Load main container without waiting for evaluations to complete.
today main container is also in loading state and no widget is shown in loading state unless evaluations are complete.

Fixes #3825 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/canvas-loading-state 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.04 **(-0.01)** | 36.97 **(-0.01)** | 33.71 **(-0.01)** | 55.64 **(0)**
 :red_circle: | app/client/src/selectors/editorSelectors.tsx | 71.9 **(-1.75)** | 61.54 **(0)** | 58 **(-2.42)** | 68.8 **(-2.03)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

File: app/client/src/selectors/editorSelectors.tsx [hunk 1]
```diff
@@ -157,7 +160,7 @@ export const getCanvasWidgetDsl = createSelector(
       const evaluatedWidget = _.find(evaluatedDataTree, {
         widgetId: widgetKey,
       }) as DataTreeWidget;
-      if (evaluatedWidget) {
+      if (evaluatedWidget || widgetKey === MAIN_CONTAINER_WIDGET_ID) {
```
Comment (hetunandu) [inline app/client/src/selectors/editorSelectors.tsx:163]: Instead of manipulating this if statement. Always add this widget by default before looping through other evaluated widgets

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/selectors/editorSelectors.tsx (hunk 1 above)
Comment (marks0351) [reply app/client/src/selectors/editorSelectors.tsx:163]: if we do that we have to add if else statement to not add loading state for maincontainer or filter maincontainer from canvasWidgets before iterating. thoughts?

Comment (riodeuno) [reply app/client/src/selectors/editorSelectors.tsx:163]: If we have to have this check in either case, then let's just go with this approach. @hetunandu Let us know if there is reason for the approach you suggested.

Comment (hetunandu) [reply app/client/src/selectors/editorSelectors.tsx:163]: We should then add it by default and filter it from the list before looping.

**Review by hetunandu — APPROVED** [review]
