### PR TITLE
fix: Archived pages are getting copied in forked application

### LINKED ISSUE #11793: [Bug]: Forking apps add the deleted page from the Original app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Forking apps add the deleted page from the Original app
[LOOM DEMO](https://www.loom.com/share/af8a968361034774b6228b3d11ec1040)

### Steps To Reproduce

1. Generate a new app
2. Add 2 pages Page 1 and page 2 
3. Now delete the Page 1
4. Now fork the application to the new org
5. Open the application and check the user can see the deleted page in the application

### Public Sample App

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> When we try to fork the application with an archived unpublished page, the forked application contains the archived page as we don't filter the pages from the source application. Also, we are safe to assume that we can ignore the pages which are still not deleted in the view mode because we have publish event after the forking is done.   

Fixes #11793 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> JUnit testcase
> Manual test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java [hunk 1]
```diff
@@ -430,15 +430,15 @@ private boolean updateOnLoadActionsWithNewActionAndCollectionIds(Map<String, Str
...
+    private Flux<NewPage> doOnlyCloneApplicationObjectWithoutItsDependenciesAndReturnNonDeletedPages(Application application, List<String> applicationIds) {
         final String templateApplicationId = application.getId();
         return cloneApplicationDocument(application)
                 .flatMapMany(
                         savedApplication -> {
                             applicationIds.add(savedApplication.getId());
                             return forkThemes(application, savedApplication).thenMany(
                                     newPageRepository
-                                            .findByApplicationId(templateApplicationId)
+                                            .findByApplicationIdAndNonDeletedEditMode(templateApplicationId, AclPermission.READ_PAGES)
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java:441]: Looks like we are changing the permission requirement as well here. Will the user who is forking have this permission on the page objects for sure?

**Review by sharat87 — COMMENTED** [review]
Looks good. Just a minor question.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java (hunk 1 above)
Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java:441]: AFAIK if user have the read_application permission on source application object, by the hierarchical structure of ACL user will have read_page permission on page object. Also we are checking for this permission while fetching the source application.
```
final Mono<Application> sourceApplicationMono = applicationService.findById(srcApplicationId, AclPermission.READ_APPLICATIONS)
                .switchIfEmpty(Mono.error(new AppsmithException(AppsmithError.NO_RESOURCE_FOUND, FieldName.APPLICATION, srcApplicationId)));

```
But let me double confirm on this 🙂

Comment (sharat87) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java:441]: Yeah, we likely do, just that we weren't doing this before so was wondering if this would break in some edge cases. Just me being paranoid. 😄

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java:441]: Hey checked the following flow, and I think we are safe here:
1. Created a sample app 
2. Made app public and forkable _(forkingEnabled: true)_
3. Opened the same app in an incognito window
4. Try to fork the application
5. Application is successfully forked after the new signup

**Review by sharat87 — APPROVED** [review]
