### PR TITLE
Fix-Table cell tooltip should show inside table widget

### LINKED ISSUE #1830: [Bug] Table cell hover message should resize according to resolution
## Description
Drag and drop a table with each cell filled with a lot of text. Hover on a cell and you'll find that some of the hover text is cut off. 

### Important Details
- OS: MacOSX
- Browser: Safari 
Screen Shot 2020-11-20 at 11 28 24 AM

### PR DESCRIPTION
**Pull request by vicky-primathon**
Using table width as max width for table cell hover tooltip content

Fixes #1830

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/designSystems/appsmith/AutoToolTipComponent.tsx [hunk 1]
```diff
@@ -17,13 +19,26 @@ const AutoToolTipComponent = (props: {
       updateToolTip(false);
     }
   }, [ref]);
+  const boundariesElement = props.widgetId
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/AutoToolTipComponent.tsx:22]: Let's remove this.

File: app/client/src/components/designSystems/appsmith/AutoToolTipComponent.tsx [hunk 2]
```diff
@@ -17,13 +19,26 @@ const AutoToolTipComponent = (props: {
...
+  console.log({ boundariesElement });
   return (
     <CellWrapper ref={ref} isHidden={props.isHidden}>
       {useToolTip && props.children ? (
         <Tooltip
           autoFocus={false}
           hoverOpenDelay={1000}
-          content={props.title}
+          content={
+            <div
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/AutoToolTipComponent.tsx:33]: Let's make this a styledComponent.

**Review by riodeuno — APPROVED** [review]
