### PR TITLE
Fix: Fix redis plugin db authentication

### LINKED ISSUE #4862: [Bug] Redis datasource displays AUTH error
Steps to reproduce:
1) Navigate to the data source
2) Select Redis
3) Add appropriate credentials 
4) Click on Test
and observe

Observation:
It is observed that an  error for Auth is being displayed to the user  
error: "NOAUTH Authentication required"

Expectation:
The error must be displayed to the user only when it is expected

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- remove DB Auth type check, since the type is not getting set and the check does not seem to be required in any way. 

Fixes #4862 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java [hunk 1]
```diff
@@ -150,7 +150,7 @@ public RedisPlugin(PluginWrapper wrapper) {
                 Jedis jedis = new Jedis(endpoint.getHost(), port);
 
                 DBAuth auth = (DBAuth) datasourceConfiguration.getAuthentication();
-                if (auth != null && DBAuth.Type.USERNAME_PASSWORD.equals(auth.getAuthType())) {
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java:153]: What was the purpose of having the authType check here? Do we want to add the ability to use that specific authType in our flow instead?

Comment (sumitsum) [reply app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java:153]: Not sure why it was added, it had existed here for a long time, but didn't I am not able to see any reason why this check should exist. Irrespective of the type attribute, username and password fields exist. Redis does not use any other kind of auth as well.

**Review by nidhi-nair — APPROVED** [review]
