### PR TITLE
Suggest List of possible widgets and add exception handling 

### LINKED ISSUE #5785: [Bug] Mongo DB - Internal server error occurs for distinct operation
## Description
Release Frozen - It is observed that when passing valid query in the distinct operation - Internal server error occurs

Expected Result:
For valid input queries error should not be displayed

### Steps to reproduce the behaviour:
1.Launch appsmith app in the release frozen environment
2.Click on Datasoure 
3.Choose Mongo DB
4.Choose option with uri and pass the following MongoDB url
5.Click on new query 
6.Choose comand type as - Insert a document 
7.Enter the collection name and pass the following query - 
```
[{ "_id": 1, "user": "Niralya", "status": "Active" } ,
{"_id": 2, "user": "Yogesh", "status": "Active" } ,
{"_id": 3, "user": "Prapulla", "status": "Active" } ,
{"_id": 4, "user": "Vivek", "status": "Active" } ,
{"_id": 5, "user": "Raksha", "status": "Active" }]
```
8.Choose the command type as Distinct and pass the above 
collection name - RCJuly9 , 
Query - {} and 
Key - status
9.Click on run and observe

VideoLink:
https://loom.com/share/5fdf54fc90364c6b8006b7dd7c5b34ae

### Important Details

- Version: [ 14.1 (16611.1.21.161.3)]
- OS: [MacOS big sur 11.3]
- Browser [Chrome,safari]
- Environment [release frozen]

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description
While suggesting the widget for the executed query/action we are converting the data in order to look for the best possible widget which fits the data. While converting the data we are not handling it properly. This change-set adds the exception handling that could generate while converting the data

Fixes #5785 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Unit Tests
- Locally via postman

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java [hunk 1]
```diff
@@ -709,21 +709,27 @@ private WidgetType getSuggestedWidget(Object data) {
...
+                }
+                if(fieldsCount <= 2) {
+                    return WidgetType.DROP_DOWN_WIDGET;
+                }
+                if(length <= 20 && fieldsCount <= 5) {
+                    return WidgetType.LIST_WIDGET;
+                }
+                return WidgetType.TABLE_WIDGET;
+
+            } catch(Exception e) {
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:729]: Couple of suggestions:
1. Instead of catching generic Exception, is it possible to catch a specific exception here?
2. Is there a way to check if the JsonNode object itself is a String or Object? I'm asking because while catching the Exception is fine, we shouldn't use it as a control flow. That's an anti-pattern.

Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:729]: I will add a specific exception. 
I don't know if i got your point fully. There is a method called `getNodeType` which i can use, but this will be again of the type TextNode or ValueNode etc. The other way to check specifically is by casting the JsonNode to respective classes.  Are you suggesting that i should further break this piece of code rather than using the JsonNode ?

Comment (mohanarpit) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:729]: Won't `node.getNodeType()` return an enum of `JsonNodeType` ? This enum has different types of fields right? Can we check if the nodeType is String, do X; for objects, do Y; for everything else, do Z ?

**Comment by AnaghHegde** [comment]
@mohanarpit Ready for review 😀

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionResult.java [hunk 2]
```diff
@@ -33,7 +33,7 @@
 
     List<ParsedDataType> dataTypes;
 
-    WidgetType suggestedWidget;
+    List<WidgetType> suggestedWidget;
```
Comment (mohanarpit) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionResult.java:36]:
```suggestion
    List<WidgetType> suggestedWidgets;
```

If this is a list, we should rename the variable to reflect that it's plural.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java [hunk 3]
```diff
@@ -683,12 +683,14 @@ private void transformRequestParams(ActionExecutionResult result, Map<String, St
...
-    private ActionExecutionResult addDataTypesAndSetSuggestedWidget(ActionExecutionResult result) {
+    private ActionExecutionResult addDataTypesAndSetSuggestedWidget(ActionExecutionResult result, Boolean viewMode) {
         /*
          * - Do not process if data types are already present.
          * - It means that data types have been added by specific plugin.
          */
-        result.setSuggestedWidget(getSuggestedWidget(result.getBody()));
+        if(FALSE.equals(viewMode)) {
+            result.setSuggestedWidget(getSuggestedWidget(result.getBody()));
+        }
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:693]: Can we move this code blow above the comment? It seems like the comment is for this statement, which it is not. I was confused for 5 secs before I realized that that comment belongs to the code snippet below.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java [hunk 4]
```diff
@@ -702,31 +704,48 @@ private ActionExecutionResult addDataTypesAndSetSuggestedWidget(ActionExecutionR
...
-                return WidgetType.LIST_WIDGET;
+        if(data instanceof ArrayNode && ((ArrayNode) data).isArray()) {
+            if(!((ArrayNode) data).isEmpty()) {
+                try {
+                    ArrayNode array = (ArrayNode) data;
+                    int length = array.size();
+                    JsonNode node = array.get(0);
+                    JsonNodeType nodeType = node.getNodeType();
+
+                    if(nodeType.equals(JsonNodeType.STRING)) {
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:719]: Nit: Always have the constant value first in an if condition. This ensures that we are protected against NPEs. Goes a long way in ensuring small bugs don't arise across the code base. This should be done across all if condition comparisons in this file.

```suggestion
                    if(JsonNodeType.STRING.equals(nodeType)) {
```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java [hunk 5]
```diff
@@ -702,31 +704,48 @@ private ActionExecutionResult addDataTypesAndSetSuggestedWidget(ActionExecutionR
...
+                        widgetTypeList.add(WidgetType.TABLE_WIDGET);
+                    }
+
+                    if(nodeType.equals(JsonNodeType.NUMBER)) {
+                        widgetTypeList.add(WidgetType.INPUT_WIDGET);
+                        widgetTypeList.add(WidgetType.TEXT_WIDGET);
+                    }
+
+                } catch(ClassCastException e) {
+                    log.warn("Error while casting data to suggest widget "+ e);
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:741]:
```suggestion
                    log.warn("Error while casting data to suggest widget.", e);
```
Nit: Having `,e` instead of `+e` ensures that the stack trace is also printed in the logs.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java (hunk 4 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:719]: Good point, Never thought of this. I will follow this in future :)

**Comment by AnaghHegde** [comment]
@mohanarpit Ready for review 😀

**Review by mohanarpit — APPROVED** [review]
