### PR TITLE
fix: 8878 - To handle Comma delimited float values

### LINKED ISSUE #8878: [Bug]: Data not being parsed into Float
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user navigates into Google API and sets the Query row into 1-100 which has the combination of both empty decimal and integers. The API displays an error
Screenshot 2021-10-28 at 12 22 06 PM

### Steps To Reproduce

1) Navigate to Google sheet
2) Authorise the sheets 
3) Click on the new API 
4) Select fetch as the method
5) Add the where clause 
6) Click on Run 
and observe

Ensure the user data has a combination of integer and decimal in the google sheet 

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by leotom2000**
## Google Sheet Data processing issue with comma

- Fix for Comma delimited Number with or without decimal places

Fixes #8878 

## Type of change
- Bug fix (non-breaking change which fixes an issue) 

## How Has This Been Tested?
- Manually tested
- Existing @Tests were checked to work fine
- Added new @Tests to test new implementation

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/DataTypeStringUtilsTest.java [hunk 1]
```diff
@@ -57,6 +57,30 @@ public void checkFloatDataType() {
         assertThat(dataType).isEqualByComparingTo(DataType.FLOAT);
     }
 
+    @Test
+    public void checkCommaDelimitedNumbers() {
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/DataTypeStringUtilsTest.java:61]: Nitpick: Could you please rename the tests so that it is clear what we are testing here?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java [hunk 2]
```diff
@@ -65,7 +65,7 @@ public static DataType stringToKnownDataTypeConverter(String input) {
             return DataType.NULL;
         }
 
-        input = input.trim();
+        String strNumericValue = input.trim().replaceAll(",","");
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java:68]: Does this change the value that is displayed in the end result?

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
A few tiny comments, please also format the files you have edited. I was pretty confused when I read `.replaceAll(",","")`. I got lost in those quotes and commas for a second because there were no spaces. :)

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java (hunk 2 above)
Comment (leotom2000) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java:68]: No, it enables to decide the DataType

File: app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/DataTypeStringUtilsTest.java (hunk 1 above)
Comment (leotom2000) [reply app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/DataTypeStringUtilsTest.java:61]: Updated

**Comment by leotom2000** [comment]
> A few tiny comments, please also format the files you have edited. I was pretty confused when I read `.replaceAll(",","")`. I got lost in those quotes and commas for a second because there were no spaces. :)



> A few tiny comments, please also format the files you have edited. I was pretty confused when I read `.replaceAll(",","")`. I got lost in those quotes and commas for a second because there were no spaces. :)

Renamed the Test methods

**Review by nidhi-nair — APPROVED** [review]

**Comment by nidhi-nair** [comment]
Merging in because failing tests are flaky and unrelated.
