### PR TITLE
Fix organization ordering

### LINKED ISSUE #1036: [Bug] Orgs should be ordered in the order in a user was invited to them on the home page
## Steps
1. Create 2 accounts
2. Create an organization in the second account with a name starting with A
3. Invite the user from the first account
4. The organization that the user was invited to should show up at the bottom of the list but instead shows up at a random location

### PR DESCRIPTION
**Pull request by shinnlok**
## Description

- Organizations are now sorted by name. We can drop the last commit if create date makes more sense to you.

## Type of change

- Bug fix

## How Has This Been Tested?

- Added a bunch of organizations/applications and sorting was predictable

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationFetcher.java [hunk 1]
```diff
@@ -70,33 +70,28 @@ public ApplicationFetcher(
...
-                            .zipWith(organizationsMapMono)
+                    return organizationService
+                            .findByIdsIn(orgIds, READ_ORGANIZATIONS)
+                            .collectList()
+                            .zipWith(applicationsMapMono)
                             .map(tuple -> {
-                                Map<String, Collection<Application>> applicationsCollectionByOrgId = tuple.getT1();
-                                Map<String, Organization> organizationsMap = tuple.getT2();
+                                List<Organization> organizations = tuple.getT1();
+                                Map<Object, Collection<Application>> applicationsCollectionByOrgId = tuple.getT2();
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationFetcher.java:89]: One minor review comment : As the key of the Map, could we use String for organization id instead of generic Object? Thanks!

Comment (shinnlok) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationFetcher.java]: Done!

**Comment by manchicken** [comment]
Is it probable that you’d have enough data in any of these queries to need pagination? If not, might it be more efficient to perform the sorts on the client-side?

**Comment by shinnlok** [comment]
How is it more efficient?

**Comment by manchicken** [comment]
From a server-side perspective, it's more efficient to hand small sorting tasks like this to the UI. For a reasonably small set, JavaScript on the client side will barely be able to measure the performance difference, when a server processing a number of these requests would likely be able to notice the difference in sorting versus not sorting. 

The only wild card would be whether or not pagination were a concern, which it doesn't seem to be here. 

That said, if both traffic and set size are low, then this is a wash and there likely isn't any difference.

**Review by mohanarpit — APPROVED** [review]

**Comment by mohanarpit** [comment]
@shinnlok Thank you for the PR! This has been merged 🎉 

The reason I edited your original message and removed the linking to the bug is because even though this PR is a step forward from our current state, it doesn't address what the Github issue had asked for. 

In order to address the Github issue of ordering organizations by invitation date for the user is more involved and requires datapoints that aren't being tracked by the platform right now. Hence, we'll tackle that Github issue later. But for now, this is a good implementation for the short term. Thanks!
