### PR TITLE
fix: The case of the missing tabs

### LINKED ISSUE #33032: [Bug]: IDE Tabs go missing in a few cases
### Description

Tabs are going missing and not being saved correctly

### Steps To Reproduce

- [ ] Tabs go missing while switching pages
- [ ] #33045

### LINKED ISSUE #33045: [Bug]: JS Object displayed in editor even when moved to a different page.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we move a JS Object to a different page, we are still able to see it in the editor of the page from where it was moved.

### Steps To Reproduce

1. Create an app and add a JS Object to Page1.
2. Now create a new page Page2.
3. Move the JS Object from Page1 to Page2.

**Expected:** The JS Object should not be visible in the editor of Page1 anymore.
**Actual:** JS Object is still visible.

### Public Sample App

_No response_

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/6a6c9c9ab02149eea3ae8d514f3eca27

### Version

Cloud

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Fixes #33032
Change the data structure of the tabs to now keep account different tabs for each page instead of just one page at a time. Also removed tabs state for focus retention.

Fixes #33045
Handles removing and navigating post move of js and queries to avoid being in a bad state

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9000257489>
> Commit: b39c8d7cca16ea739457f277290c29317317cef3
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9000257489&attempt=2" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: app/client/src/ce/sagas/JSActionSagas.ts [hunk 1]
```diff
@@ -254,8 +255,19 @@ export function* moveJSCollectionSaga(
...
-    const currentURL = window.location.pathname;
-    yield call(FocusRetention.handleRemoveFocusHistory, currentURL);
+    yield call(
+      closeJSActionTabSaga,
+      closeJSActionTab({
+        id: action.payload.id,
+        parentId: actionObject.pageId,
+      }),
+    );
+    // yield put(
```
Comment (albinAppsmith) [inline app/client/src/ce/sagas/JSActionSagas.ts:265]: remove this if not needed

**Review by albinAppsmith — DISMISSED** [review]

**Review by albinAppsmith — APPROVED** [review]
