### PR TITLE
fix: ds structure issue fixed for zendesk integration

### LINKED ISSUE #38736: [Bug]: Show correct error message for when datasource structure is not supported for zendesk
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description
Ref: https://www.notion.so/appsmith/No-bottom-spacing-in-the-empty-state-datasource-schema-Also-why-do-we-get-this-error-17afe271b0e280aa9520ddfbc64107ab
Datasource structure is not valid for zendesk as it's not relational DB, Show appropriate message in response tab, currently it shows:

Image
Image

### Steps To Reproduce

1. Create zendesk datasource
2. Create query
3. check the response tab for ds structure

### Public Sample App

_No response_

### Environment

Deploy Preview

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

NA

### PR DESCRIPTION
**Pull request by sneha122**
## Description
This PR fixes the issue where for Saas integrations like zendesk, we do not have a structure to be displayed, in that case we should show appropriate error message. 

Fixes #38736 
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12907027118>
> Commit: 5a9ef72ef41275bcd6303e311313758f0c24789d
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12907027118&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Wed, 22 Jan 2025 12:24:10 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **Refactor**
	- Deprecated the previous method for retrieving datasource context.
	- Updated the datasource context retrieval process to include plugin information.

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java [hunk 1]
```diff
@@ -452,9 +452,12 @@ public Mono<DatasourceContext<?>> getDatasourceContext(DatasourceStorage datasou
 
     @Override
     public <T> Mono<T> retryOnce(DatasourceStorage datasourceStorage, Function<DatasourceContext<?>, Mono<T>> task) {
-
         final Mono<T> taskRunnerMono = Mono.justOrEmpty(datasourceStorage)
-                .flatMap(this::getDatasourceContext)
+                .flatMap(ds -> {
+                    return pluginService
+                            .findById(datasourceStorage.getPluginId())
+                            .flatMap(plugin -> getDatasourceContext(datasourceStorage, plugin));
```
Comment (NilanshBansal) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java:459]: @sneha122 can we please add @Deprecated annotation for the CE method with one parameter to avoid people using this again.

Comment (sneha122) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java:462]: Done

**Review by NilanshBansal — APPROVED** [review]

**Review by NilanshBansal — APPROVED** [review]
