### PR TITLE
Fix: FilePicker widget was not setting loading state to true on calling action

### LINKED ISSUE #949: [Bug] File upload is not putting picker in loading state
## Steps to Reproduce
1. Drag a file picker
2. Create an API
3. Bind the onFileSelected to the API
4. Pick a file
5. The File picker does not go into loading state

### PR DESCRIPTION
**Pull request by jsartisan**
## Description
Filepicker widget was not setting isLoading to true on calling action whenever files were selected. 
Fixes #949 

## Type of change
- Bugfix

## How Has This Been Tested?
- Manually tested
- Added cypress tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/FilepickerWidget.tsx [hunk 1]
```diff
@@ -167,15 +172,24 @@ class FilePickerWidget extends BaseWidget<
           callback: this.handleFileUploaded,
         },
       });
+
+      this.props.updateWidgetMetaProperty("isLoading", true);
```
Comment (hetunandu) [inline app/client/src/widgets/FilepickerWidget.tsx:176]: We should use the state here instead of WidgetMetaProperty

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/FilepickerWidget.tsx (hunk 1 above)
Comment (hetunandu) [reply app/client/src/widgets/FilepickerWidget.tsx:176]: You can check Button Widget for implementation details

**Comment by jsartisan** [comment]
@hetunandu added the isLoading in state.

**Review by hetunandu — APPROVED** [review]
