### PR TITLE
fix: removed default value for API DS, updated conditions for headers and apiformattype

### LINKED ISSUE #11822: [Bug]: Set default content type to application/json instead of raw when creating API
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Currently when we create an API, the default content type which is set to be raw while we want it to be set to json 
- The body tab has group of tabs which by default should selected as json instead of raw.

Screenshot 2022-03-10 at 1 38 15 PM

### Steps To Reproduce

1. Go to datasource page and Create an API
2. When you go to API creation Page, you will see the default content type to be raw instead of json in the body tab, which should be fixed.

### Public Sample App

_No response_

### Version

Cloud and Self Hosted

### LINKED ISSUE #14132: [Test Case]: Validating content type of Api and when the method type changes but body remains empty
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the API is created : 
- The `content-type` header is not present in the first place
- When the `method` type is changed from `GET` to `POST` considering body to be empty, the `content-type` header should become `application/json`
- When the `method` type is switched back to `GET`, the `content-type` header should become `none`.

### Steps To Reproduce

Create an API and follow the above steps

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description

Added changes :
- Removed the default values for API datasource and made it to be empty.
- Added conditions to update the content type of API when the method type is changed from one to another.
- Updated the apiformattype to `None` when the method type is changed to `GET` and the content-type is not specifically defined and the body is also empty.

Fixes #11822 
Fixes #14132

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/11822-default-content-type 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.7 **(-0.01)** | 38.64 **(-0.02)** | 36.22 **(0)** | 56.95 **(-0.01)**
 :red_circle: | app/client/src/components/ads/MultiSwitch.tsx | 40 **(0)** | 50 **(-7.14)** | 0 **(0)** | 40 **(0)**
 :red_circle: | app/client/src/sagas/ApiPaneSagas.ts | 16.36 **(-0.23)** | 1.12 **(-0.12)** | 8.7 **(0)** | 17.89 **(-0.34)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 70.59 **(0)** | 100 **(0)** | 93.33 **(0.95)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by rashmi-rai — APPROVED** [review]

File: app/client/src/sagas/ApiPaneSagas.ts [hunk 1]
```diff
@@ -65,6 +65,7 @@ import {
   datasourcesEditorIdURL,
   integrationEditorURL,
 } from "RouteBuilder";
+import _ from "lodash";
```
Comment (Irongade) [inline app/client/src/sagas/ApiPaneSagas.ts:68]: Why not import {isEmpty} directly from lodash, instead of the whole package, this will help to reduce import size.

Comment (AmanAgarwal041) [reply app/client/src/sagas/ApiPaneSagas.ts]: done

**Review by Irongade — APPROVED** [review]

**Comment by yatinappsmith** [comment]
- [ ] [1732 [TestCase] REST api behaviour for get and post for content-type](https://github.com/appsmithorg/TestSmith/issues/1732)
