### PR TITLE
fix: App title drop down close on interaction with other components.

### LINKED ISSUE #28114: [Bug]: App title drop down pop up is not getting closed automatically when user opens up omnibar using hotkeys
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

screen shot : 
image

### Steps To Reproduce

1. Expand app title drop down 
2. then from keyboard press ctrl+k to open omnibar pop up 

Work around : Expands app title drop down then click on omnibar without using hot keys

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Appsmith v1.9.40-SNAPSHOT

### PR DESCRIPTION
**Pull request by saicharan-zemoso**
Fixes #28114 

fixed the app title drop down and it closes on interaction with other components

Before fixing the bug the omni bar and title dropdown overlap over each other:
image

after the fix the app title drop down closes on opening omni bar or any other component.

added the cypress test to visually confirm that the fix was working and did not add unit test as to test this we need to interact with other components or open omni bar while testing.

## Summary by CodeRabbit

- **New Features**
	- Enhanced the Navigation Menu to automatically close when users interact outside of it, improving user experience.
	- Introduced a test suite for validating application dropdown interactions with the omnibar using keyboard shortcuts.

- **Bug Fixes**
	- Resolved an issue where the dropdown menu would remain open after interactions outside its boundaries.

### CODE REVIEW

File: app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ApplicationDropdownClose_spec.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+import homePage from "../../../../locators/HomePage";
+const omnibar = require("../../../../locators/Omnibar.json");
+
+describe("application dropdown interaction test", () => {
+  it("application dropdown closes when interacting with omni bar using hotkeys", () => {
+    cy.get(homePage.applicationName).click();
+    cy.get(homePage.applicationEditMenu).should("be.visible");
+    cy.wait(1000);
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ApplicationDropdownClose_spec.ts:8]: Kindly tell us for need of cypress test case here? I feel logic can be tested with unit test.

**Review by sagar-qa007 — CHANGES_REQUESTED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ApplicationDropdownClose_spec.ts (hunk 1 above)
Comment (alex-golovanov) [reply app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ApplicationDropdownClose_spec.ts:8]: @saicharan-zemoso since @sagar-qa007 is against this cypress test, could you simply omit it? You do not have to add a unit test for this fix.

Comment (saicharan-zemoso) [reply app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ApplicationDropdownClose_spec.ts:8]: Ok, sure @alex-golovanov . I will remove this cypress test. Thank you.

File: app/client/src/pages/Editor/EditorName/NavigationMenu.tsx [hunk 2]
```diff
@@ -13,9 +13,13 @@ interface NavigationMenuProps {
 
 export function NavigationMenu(props: NavigationMenuProps) {
   const { menuItems, setIsPopoverOpen } = props;
-
   return (
-    <MenuContent width="214px">
+    <MenuContent
+      width="214px"
+      onInteractOutside={() => {
```
Comment (alex-golovanov) [inline app/client/src/pages/Editor/EditorName/NavigationMenu.tsx:19]: This will create a new function on every re-render, possibly invalidating cache inside MenuContent. I believe, for that purpose, we have a lint rule for this. As a rule of thumb, if we pass an object to a component, that object should have a stable ref.

Could you please wrap this in a callback? 

```
const handleInteractionOutside = useCallback(() => {
  setIsPopoverOpen(false);
}, [setIsPopoverOpen]);

return (
    <MenuContent
      width="214px"
      onInteractOutside={handleInteractionOutside}
```

Comment (saicharan-zemoso) [reply app/client/src/pages/Editor/EditorName/NavigationMenu.tsx:19]: Ok,sure.

**Comment by alex-golovanov** [comment]
All tests are passing in [shadow PR](https://github.com/appsmithorg/appsmith/pull/36778).

**Review by alex-golovanov — APPROVED** [review]
