### PR TITLE
fix: Context menu auto close issue in page settings

### LINKED ISSUE #9193: [Bug]: Visible toggle on page properties animates from off to on when pages are set to visible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Visible toggle animates from off to on position when settings button is clicked. Ideally, it should be in the on position when the page is set to visible and not toggle when user navigates to page settings.

[LOOM DEMO](https://www.loom.com/share/5a82a3280a1f4fc1a2422f023313fd67)

### Steps To Reproduce

1. Go to page properties and click on settings icon and observe the toggle move from off state to on.

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description
   
     Fix for the issue of context menu auto closing after changing the settings.

Fixes #9193

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: bugfix/9193-page-setting-re-render 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.12 **(0)** | 37.04 **(-0.01)** | 34 **(0)** | 55.63 **(0)**
 :red_circle: | app/client/src/pages/Editor/PagesEditor/index.tsx | 46.81 **(-2.08)** | 60 **(0)** | 0 **(0)** | 47.83 **(-2.17)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/PagesEditor/index.tsx [hunk 1]
```diff
@@ -116,6 +116,20 @@ function PagesEditor() {
...
+   *
+   * @return JSX.Element
+   */
+  const draggableListRenderItem = useMemo(
+    () =>
+      function renderer({ item }: any) {
+        return <PageListItem item={item} />;
+      },
+    [],
+  );
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/PagesEditor/index.tsx:131]: nit: instead of `useMemo` we could define the component outside the `PagesEditor` component?

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/pages/Editor/PagesEditor/index.tsx (hunk 1 above)
Comment (albinAppsmith) [reply app/client/src/pages/Editor/PagesEditor/index.tsx:131]: Added useMemo because, the component was keep re-rendering every-time when a value inside item getting changed

Comment (rishabhsaxena) [reply app/client/src/pages/Editor/PagesEditor/index.tsx:131]: Actually moving the component definition outside the component should do the same thing, it won't get created on each render?

Comment (albinAppsmith) [reply app/client/src/pages/Editor/PagesEditor/index.tsx:131]: Okay I'll try this
