### PR TITLE
fix: MongoPlugin smart substitution for regex arguments

### LINKED ISSUE #11880: [Bug]-[1408]:Mongo plugin- smart substitution fails with $regex keyword when input is number
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

From community:
```
{$match: {
  $or:[
  {OrderNumber:{$regex:"{{orders_table.searchText}}"}}
  ]
}} 

Error: error $regex has to be a string. 

can you please share what evaluated value is being substituted for {{orders_table.searchText}}
If there is something in the search box will be “69” other wise “”
```

This issue was resolved upon turning off smart BSON substitution.

### Steps To Reproduce

.

### Public Sample App

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by sondermanish**
## Description

Fixes #11880 

Server side smart substitution parses js bounded (numbers/string representation of number arguments) as  **whole numbers**, and **decimal numbers** regardless if they are placed in quotes **" "**. This feature creates a bug for mongo regex substitution as **mongo regex attributes** only takes string arguments.  This PR fixes before mentioned characteristic.

## Type of change

> Bug Fix: Now, digit/ number arguments could be provided to the $regex with smart substitution turned on. 

## How Has This Been Tested?

The backend changes has been tested:
- Junit test cases
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 1]
```diff
@@ -574,9 +582,96 @@ private String smartSubstituteBSON(String rawQuery,
...
+                valueSB.insert(0, quote );
+                // adds quote at the end of the line
+                valueSB.append(quote);
+            }
+
+            return valueSB;
+        }
+
+        private static StringBuilder trimAndBuildStringBuilderFromString(String input) {
+
```
Comment (subrata71) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:608]: There are a lot of instances where `String.trim` function is used. And looking at the implementation of trim function I found that there are two different trim functions used based on the coder e.g. `Latin1/UTF16`. I would vote for using the `String.trim` function. What do you think?

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java [hunk 2]
```diff
@@ -2848,5 +2848,84 @@ public void testValidateDatasource_withoutDefaultDBInURIString_returnsInvalid()
...
+        Mono<ActionExecutionResult> actionExecutionResultMono = dsConnectionMono.flatMap(clientConnection -> pluginExecutor.executeParameterized(clientConnection,
+                executeActionDTO,
+                dsConfig,
+                actionConfiguration));
+
+        StepVerifier.create(actionExecutionResultMono)
+                .assertNext(actionExecutionResult -> {
+                    assertNotNull(actionExecutionResult);
+                    assertTrue(actionExecutionResult.getIsExecutionSuccess());
+                    assertEquals(0, ((ArrayNode) actionExecutionResult.getBody()).size());
```
Comment (subrata71) [inline app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:2922]: You are asserting size with 0. This doesn't essentially prove that regex with Number as value works. Can you populate some data first and apply the number regex? Please make sure that at least one document is returned by matching with that regex. This will also verify that the implementation is correct.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 3]
```diff
@@ -574,9 +582,96 @@ private String smartSubstituteBSON(String rawQuery,
...
+
+
+            int startIndex = 0;
+            StringBuilder inputQuerySB = new StringBuilder();
+
+            Pattern mongo$regexIdentifierPattern = Pattern.compile(mongo$regexWithNumberIdentifier);
+            Matcher mongo$regexIdentifierMatcher = mongo$regexIdentifierPattern.matcher(inputQuery);
+
+            while (mongo$regexIdentifierMatcher.find()) {
```
Comment (subrata71) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:645]: Can you please state the reason behind calling `mongo$regexIdentifierMatcher.find()` multiple times? Could there be multiple occurrences of regex in a single query?

Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:645]: There could be multiple occurrences of `$regex` in different part of the same query. i.e `{"attribute":{$regex: /value/ }, "attribute": {$regex}:/value/}`, hence we require to match every such occurrences possible.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 1 above)
Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:608]: String.trim() gives us another object of string and then we are using it to build `StringBuilder` object, hence it will take tiny amount of extra memory for same computation, however the function I've used reduces that extra string object.
This however is very minor. Let me know if you want me to use `new StringBuilder(string.trim())`.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 4]
```diff
@@ -574,9 +582,96 @@ private String smartSubstituteBSON(String rawQuery,
                     params,
                     parameters);
 
+            updatedQuery = mongoRegexSmartSubstitutionHelper (updatedQuery);
```
[the remark this answers is not in the document]
Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:585]: Changing as suggested.

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java (hunk 2 above)
Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:2922]: changing as suggested.

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java [hunk 5]
```diff
@@ -2848,5 +2848,84 @@ public void testValidateDatasource_withoutDefaultDBInURIString_returnsInvalid()
...
+                    assertNotNull(actionExecutionResult);
+                    assertTrue(actionExecutionResult.getIsExecutionSuccess());
+                    assertEquals(1, ((ArrayNode) actionExecutionResult.getBody()).size());
+                    assertEquals(List.of(new ParsedDataType(JSON), new ParsedDataType(RAW)).toString(), actionExecutionResult.getDataTypes().toString());
+                })
+                .verifyComplete();
+
+
+
+
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:2889]: Nit: Why do we have so many empty lines here? Can we please format the entire code to ensure that we are all following the same code guidelines?

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 1 above)
Comment (subrata71) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:608]: Yes, I understand your concern. But it would have an impact if the string size is much larger. And also the Latin1/UTF16 coder being used in the implementation of the trim function may have some other cases that we might miss if we go with our own implementation.
@sondermanish

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java (hunk 5 above)
Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:2889]: removing the empty lines and formatting the code.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 1 above)
Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:608]: changing as suggested.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java [hunk 6]
```diff
@@ -156,6 +156,14 @@ public class MongoPlugin extends BasePlugin {
      */
     private static final String MONGO_URI_REGEX = "^(mongodb(?:\\+srv)?://)(?:(.+):(.+)@)?([^/?]+)/?([^?]+)?\\??(.+)?$";
 
+    /**
+     * We use this regex to identify the $regex attribute and the respective argument provided:
+     * e.g. {"code" : {$regex: value, $options: value}} / {"code" : {$regex: value}}
+     * capturing the value group for regex.
+     * e.g {"code" : {$regex: 8777}}, this whole substring will be matched and 8777 is captured for further processing.
+     */
+    private static final String mongo$regexWithNumberIdentifier = ".*\\{[\\s\\n]*\\$regex[\\s\\n]*:([\\s\\n]*(?:(?:\\\"[/]*)|(?:/[\\\"]*)|)[\\d]*(?:(?:[/]*\\\")|(?:[\\\"]*/)|)[\\s\\n]*)(?:,|\\})";
```
Comment (subrata71) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:165]: By this regex we are trying to match with an integer number only, right? Couldn't there be cases where non-integer numbers can also be part of the regex?

Comment (subrata71) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:165]: Also, negative integers are not matched by this regex.

Comment (subrata71) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:165]: Can you add this in the comment above it regarding what kind of values it can cover through this regex? @sondermanish

Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:165]: In that case the Smart substitution already sends those as strings as when the data type is being decided in `DataTypeStringUtils.jsonSmartReplacementPlaceholderWithValue().`

Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:165]: I can write test case to verify the same, or modify the existing test case for the same.

Comment (subrata71) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java:165]: Yes, but it removes the quotes around it. So you are left with a value like "{\"code\" : {$regex: -4, $options: value}}"; which is not matched by the number regex. Please correct me if I am wrong.

@sondermanish

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java]: @subrata71 changed as suggested

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java (hunk 1 above)
Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java]: modified as suggested

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java (hunk 2 above)
Comment (sondermanish) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java]: modified as suggested

**Review by subrata71 — APPROVED** [review]
Looks good to me.
