### PR TITLE
Handle exception where prepared statements viewer does not get a value

### LINKED ISSUE #5342: [Bug] TypeError: Cannot read property 'split' of undefined
Sentry Issue: [APPSMITH-X2](https://sentry.io/organizations/appsmith/issues/2470198851/?referrer=github_integration)

```
TypeError: Cannot read property 'split' of undefined
  at PreparedStatementViewer (components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx:156:32)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
Handle exception and log additional info on sentry

Fixes #5342

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
No valid reproduction found

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/critical-evaluated-value-split 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.07 **(0)** | 36.09 **(0)** | 32.57 **(0)** | 54.61 **(-0.01)**
 :red_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 63.33 **(-1.38)** | 59.38 **(-1.91)** | 42.86 **(0)** | 65.48 **(-1.61)**</details>

### CODE REVIEW

**Review by ayushpahwa — APPROVED** [review]

File: app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx [hunk 1]
```diff
@@ -15,6 +15,8 @@ import {
   EvaluationError,
   PropertyEvaluationErrorType,
 } from "utils/DynamicBindingUtils";
+import * as Sentry from "@sentry/react";
```
Comment (mohanarpit) [inline app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx:18]: QQ: Is it better to import just the specific functions like `captureException` instead of the whole library? Will it give us any benefits w.r.t chunk sizes?

Comment (hetunandu) [reply app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx:18]: Not unless we do it all over the codebase.
