### PR TITLE
Fix selectedTab binding issue

### LINKED ISSUE #1889: [Bug] Tabs selected tab is not working
### Steps to reproduce the behaviour:
1. Drag a tab widget
2. Drag a text widget
3. Bind the text widget to the selected tab {{Tabs1.selectedTab}}
4. Change the selected tab by clicking on it
5. The value of the text does not change

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
Fixes issue where binding `selectedTab` of a tabs widget wasn't updating when tabs were switched.

Fixes #1889 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Tested manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/TabsWidget.tsx [hunk 1]
```diff
@@ -39,9 +39,7 @@ class TabsWidget extends BaseWidget<
   }
 
   static getDefaultPropertiesMap(): Record<string, string> {
-    return {
-      selectedTab: "defaultTab",
-    };
+    return {};
```
Comment (mohanarpit) [inline app/client/src/widgets/TabsWidget.tsx:42]: If I may ask, but is there a Jest test that could have caught this issue from occurring in the first place? This is a simple fix but caused a critical bug. That's why I'm asking how can we prevent this from happening again.

**Review by Nikhil-Nandagopal — APPROVED** [review]

File: app/client/src/widgets/TabsWidget.tsx (hunk 1 above)
Comment (Nikhil-Nandagopal) [reply app/client/src/widgets/TabsWidget.tsx:42]: +1 please atleast add a cypress test here

Comment (riodeuno) [reply app/client/src/widgets/TabsWidget.tsx:42]: This related to the bindings. So, we need an integration test in cypress. This was a code design error. I'll add the cypress test.
