### PR TITLE
Fix - tests don't run on an M1 Silicon Mac

### LINKED ISSUE #4860: [Bug] MySQL tests don't run on an M1 Silicon Mac
The MySQL tests in the server codebase use the `mysql:5.7` image. But this image is only available for `linux/amd64` architecture and not for `arm64`. Running this on M1 Silicon Mac needs the image to be available for the `arm64` architecture as well.

Alternatives include the [mysql/mysql-server](https://hub.docker.com/r/mysql/mysql-server/tags) images that are maintained by the Oracle team, or to use the mariadb image instead, which is reasonably compatible MySQL server.

@AnaghHegde, can you test out both the options above to see if they resolve the problem on your system and we can take a call based on the results?

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description
The MySQL, MSSQL and Elasticsearch tests in the server codebase use the image which is only available for linux/amd64 architecture and not for arm64. Running this on M1 Silicon Mac needs the image to be available for the arm64 architecture as well.

Fixes #4860 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

- [ ] This change requires a documentation update

## How Has This Been Tested?

- Ran the tests on M1 mac and verified
- Need to run this on a intel chip machine and make sure that things are not breaking

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java [hunk 1]
```diff
@@ -54,14 +55,16 @@
 
     @SuppressWarnings("rawtypes") // The type parameter for the container type is just itself and is pseudo-optional.
     @ClassRule
-    public static MySQLContainer mySQLContainer = new MySQLContainer("mysql:5.7")
+    public static MySQLContainer mySQLContainer = new MySQLContainer(
+            DockerImageName.parse("mysql/mysql-server:latest-aarch64").asCompatibleSubstituteFor("mysql"))
```
Comment (sharat87) [inline app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java:59]: I think the test is failing in CI because we are forcing the arm64 architecture here. Can we use `latest` tag or `8.0.25` instead? This will peg our tests to a single version and make them more predictable and it also has both architectures available.

Screenshot 2021-06-04 at 12 01 46

```suggestion
            DockerImageName.parse("mysql/mysql-server:8.0.25").asCompatibleSubstituteFor("mysql"))
```

**Comment by sharat87** [comment]
@AnaghHegde, the `latest` tag is usually not a fixed tag. Newer versions will get pushed to that tag constantly, that might inadvertently break our tests. In an effort to keep tests repeatable, so that a failure in tests most definitely means a lapse in our code and not because some other product released a new version, can we use fixed version tags like `8.0.25` etc.? What say?

File: app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java (hunk 1 above)
Comment (AnaghHegde) [reply app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java:59]: Yes. This makes sense. I agree with you. I will make this change. For the SQL Server edge i couldn't find any release notes on the docker hub page.  They just have one Repo tag **latest**. 

Is there any way to get the past release version ? I tried checking the history of the image locally but no luck either.

Comment (sharat87) [reply app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java]: Looks like they have a few versions, as seen from <https://mcr.microsoft.com/v2/azure-sql-edge/tags/list>. Try with the `1.0.3`, if it works, we'll keep it, otherwise we'll continue with `latest`. Not much we can do if the version tags aren't provided by Microsoft.

File: app/server/appsmith-plugins/mssqlPlugin/src/test/java/com/external/plugins/MssqlPluginTest.java [hunk 2]
```diff
@@ -57,7 +58,8 @@
     @SuppressWarnings("rawtypes") // The type parameter for the container type is just itself and is pseudo-optional.
     @ClassRule
     public static final MSSQLServerContainer container =
-            new MSSQLServerContainer<>("mcr.microsoft.com/mssql/server:2017-latest")
+            new MSSQLServerContainer<>(
+                    DockerImageName.parse("mcr.microsoft.com/azure-sql-edge:latest").asCompatibleSubstituteFor("mcr.microsoft.com/mssql/server:2017-latest"))
                     .acceptLicense()
```
Comment (AnaghHegde) [inline app/server/appsmith-plugins/mssqlPlugin/src/test/java/com/external/plugins/MssqlPluginTest.java:63]: @sharat87 We are already using `latest` for mssql. Should i keep it as it is ? Or does this also needs a change?

Comment (sharat87) [reply app/server/appsmith-plugins/mssqlPlugin/src/test/java/com/external/plugins/MssqlPluginTest.java:63]: Hey yeah this is fine, there's not a whole lot of choice from MS here anyway.

**Review by sharat87 — APPROVED** [review]

**Comment by sharat87** [comment]
@AnaghHegde, I've approved the changes. Please merge it in after the CI is done and is green :)
