### PR TITLE
fix: bump storybook version and move stories to storybook package

### LINKED ISSUE #25534: Move all the stories to the Storybrook package

### PR DESCRIPTION
**Pull request by KelvinOm**
## Description
- bump storybook version
- move stories to storybook package
- add dimensions for testing viewports
- improve some stories and types for argTable

#### PR fixes following issue(s)
Fixes #25534

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### CODE REVIEW

File: app/client/packages/design-system/widgets/src/components/Button/Button.tsx [hunk 1]
```diff
@@ -5,28 +5,32 @@ import type {
...
-   *
-   * @default "filled"
+   * @default filled
    */
-  variant?: ButtonVariant;
-  /** Color tone of the button */
-  color?: ButtonColor;
-  /** When true, makes the button occupy all the space available */
-  isFitContainer?: boolean;
+  variant?: (typeof BUTTON_VARIANTS)[keyof typeof BUTTON_VARIANTS];
```
Comment (jsartisan) [inline app/client/packages/design-system/widgets/src/components/Button/Button.tsx:21]: any reason for moving these types?

**Review by jsartisan — APPROVED** [review]
LGTM! left one minor comment

File: app/client/packages/design-system/widgets/src/components/Button/Button.tsx (hunk 1 above)
Comment (KelvinOm) [reply app/client/packages/design-system/widgets/src/components/Button/Button.tsx:21]: Yes, it bit improves the docs
Снимок экрана 2023-07-31 в 10 47 48

File: app/client/package.json [hunk 2]
```diff
@@ -354,6 +354,7 @@
     "@blueprintjs/core@^3.43.0": "patch:@blueprintjs/core@npm%3A3.47.0#./.yarn/patches/@blueprintjs-core-npm-3.47.0-a5bc1ea927.patch",
     "@blueprintjs/core@^3.33.0": "patch:@blueprintjs/core@npm%3A3.47.0#./.yarn/patches/@blueprintjs-core-npm-3.47.0-a5bc1ea927.patch",
     "@blueprintjs/core@^3.47.0": "patch:@blueprintjs/core@npm%3A3.47.0#./.yarn/patches/@blueprintjs-core-npm-3.47.0-a5bc1ea927.patch",
-    "@blueprintjs/icons": "3.22.0"
+    "@blueprintjs/icons": "3.22.0",
+    "@types/react": "^17.0.2"
```
Comment (KelvinOm) [inline app/client/package.json:358]: For history. `addon-docs` with some dependency updated `@types/react` version, which leads to type errors in the main app. 

cc @jsartisan

File: app/client/packages/storybook/package.json [hunk 3]
```diff
@@ -5,38 +5,40 @@
...
-    "@storybook/builder-webpack5": "^6.5.16",
-    "@storybook/manager-webpack5": "^6.5.16",
-    "@storybook/node-logger": "^6.5.16",
-    "@storybook/preset-create-react-app": "^4.1.2",
-    "@storybook/react": "^6.5.16",
-    "@storybook/testing-library": "^0.0.13",
-    "@types/react": "^17.0.2",
-    "@types/react-dom": "^17.0.2",
-    "autoprefixer": "^9.0.0",
+    "@storybook/addon-actions": "^7.1.1",
```
Comment (KelvinOm) [inline app/client/packages/storybook/package.json:17]: `addon-essentials` is already has a basic set of packages(docs, links, actions and so on), but we have duplicated them. I have removed this addon and installed the necessary addons explicitly so that there is no duplication.

cc @jsartisan

**Review by jsartisan — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — DISMISSED** [review]
