### PR TITLE
fix: handle 413 errors on the client

### LINKED ISSUE #20641: [Bug]: Log 413 error in plugin execution
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the payload size is more than 100MB, 413 response is thrown.
This error is not logged, Add an entry to error log 

### Steps To Reproduce

Upload any file > 100MB to any plugin

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Irongade**
This PR introduces client side error handling. Certain errors cannot be handled by the server for example, 413 errors (Content Too Large), this is because they get rejected by NGINX before it reaches the server code. Hence why they have to be handled on the client side.

Fixes #20641

## Type of change

- Bug fix (non-breaking change which fixes an issue)

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/api/ApiUtils.ts [hunk 1]
```diff
@@ -95,6 +96,25 @@ export const apiSuccessResponseInterceptor = (
...
+      ...error,
+      clientDefinedError: true,
+      statusCode: "AE-APP-4013",
+      message: createMessage(ERROR_413, 100),
+      pluginErrorDetails: {
+        appsmithErrorCode: "AE-APP-4013",
+        appsmithErrorMessage: createMessage(ERROR_413, 100),
+        downstreamErrorCode: "413 CONTENT_TOO_LARGE",
+        downstreamErrorMessage: "",
+        errorType: "INTERNAL_ERROR",
```
Comment (sneha122) [inline app/client/src/api/ApiUtils.ts:112]: Should we create enum for errorType?

**Review by sneha122 — APPROVED** [review]

File: app/client/src/api/ApiUtils.ts [hunk 2]
```diff
@@ -95,6 +98,25 @@ export const apiSuccessResponseInterceptor = (
...
+  if (error && error?.response && error?.response.status === 413) {
+    return Promise.reject({
+      ...error,
+      clientDefinedError: true,
+      statusCode: "AE-APP-4013",
+      message: createMessage(ERROR_413, 100),
+      pluginErrorDetails: {
+        appsmithErrorCode: "AE-APP-4013",
+        appsmithErrorMessage: createMessage(ERROR_413, 100),
+        downstreamErrorCode: createMessage(APPSMITH_HTTP_ERROR_413),
```
Comment (ChandanBalajiBP) [inline app/client/src/api/ApiUtils.ts:112]: Can we remove downstreamErrorCode and downstreamErrorMessage parameter as it is optional and this might mislead users as we are not connected downstream.

**Review by ChandanBalajiBP — CHANGES_REQUESTED** [review]
Sorry for the late review

**Comment by btsgh** [comment]
@Irongade - Would it be possible for you to  create a deploy preview for this issue so we could test it?

File: app/client/src/api/ApiUtils.ts (hunk 2 above)
Comment (Irongade) [reply app/client/src/api/ApiUtils.ts]: Resolved.

**Comment by Irongade** [comment]
> Deploy-Preview-URL: https://appsmith-kb286luoc-get-appsmith.vercel.app

@btsgh @prapullac Kindly find the DP above.

**Review by ChandanBalajiBP — DISMISSED** [review]
LGTM

**Review by ChandanBalajiBP — APPROVED** [review]
LGTM!
