### PR TITLE
fix: Fixed mustache binding highlight

### LINKED ISSUE #25894: [Bug]: Broken highlighting on binding brackets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Bracket highlighting for binding syntax is buggy and doesn't work in certain scenarios. A sample scenario is listed in the __Steps to Reproduce__ section. 
Also observe the image below to see that the same css classes `binding-brackets` & `binding-highlight` keeps getting added on every edits
Screenshot 2023-08-01 at 14 19 09

### Steps To Reproduce

1. Drag and drop a text widget
2. Paste this snippet into the text field 
```
Hello {{
(function() {
return appsmith.user.name
})()
}}
```

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Changes
- Removed custom bindingMarkers function that manually iterates each line and highlights brackets
- Added a delimStyle property to multiplex modes (where bindings are expected)
- Replaced binding-brackets, binding-highlight CSS classes with cm-binding-brackets

#### PR fixes following issue(s)
Fixes #25894 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
#### How Has This Been Tested?
- [x] Manual
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by hetunandu — DISMISSED** [review]

**Review by Rishabh-Rathod — DISMISSED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25894_spec.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import { WIDGET } from "../../../../locators/WidgetLocators";
+import * as _ from "../../../../support/Objects/ObjectsCore";
+
+const { entityExplorer, propPane } = _;
+
+describe("Bug 25894 - Moustache brackets should be highlighted", () => {
+  it("1. should show {{ }} in bold", () => {
+    entityExplorer.DragDropWidgetNVerify(WIDGET.BUTTON, 200, 200);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25894_spec.ts:8]: nit: Use `draggableWidgets.BUTTON` - to avoid separate import of WIDGET from locators.

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes.

**Review by Aishwarya-U-R — APPROVED** [review]
