### PR TITLE
fix: canvas resizing issues

### LINKED ISSUE #34741: [Bug]: Regression in Fluid Width Behaviour in View Mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have created an App in fluid width mode. When I change the resolution of the browser, or move it between monitors, the App should occupy the full space available in width. Whether its lesser space or more space.

With the current regression, the App occupies the same space when i change the resolutions. So from larger to small resolution, I see a scroll bar on the page
And from a smaller resolution to wider resolution, the App widgets do not occupy the full space.

I need to refresh the App for it to work correctly. This happens only in deployed mode

### Steps To Reproduce

1. Create an Application
2. Drag and Drop widgets onto it
3. Ensure that the App Canvas mode is using Fluid Width
4. Deploy the App
5. Reize the browser to a small width, or move the browser to a different sized screen

You will see that the App has not resized itself to occupy the width available in the browser

https://github.com/appsmithorg/appsmith/assets/5265702/f0a8d7cb-abcb-438f-964b-83ffc015c758

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by alex-golovanov**
## Description
Fixes canvas resizing issue and introduces performance improvements.

Fixes #34741

## Automation

/ok-to-test tags="@tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9976888930>
> Commit: 89ccd69466efaf6ea6a55c2b3b3fb20175024dbd
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9976888930&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.IDE`
> Spec:
> <hr>Wed, 17 Jul 2024 15:42:40 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
  - Introduced auto-resize functionality for canvas elements based on container width.
  - Added debouncing for resize events to improve performance.

- **Refactor**
  - Reorganized imports and constants for better modularity and maintainability. 
  - Updated component and hook references to use new `useCanvasWidthAutoResize`.

- **Tests**
  - Added tests for canvas width resolution logic to ensure correct behavior across different layout types.

### CODE REVIEW

File: app/client/src/pages/Editor/WidgetsEditor/components/MainContainerWrapper/hooks/useCanvasWidthAutoResize.ts [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+export const useCanvasWidthAutoResize = (ref: React.RefObject<HTMLElement>) => {
+  const dispatch = useDispatch();
+
+  const isCanvasInitialized = useSelector(getIsCanvasInitialized);
+  const { type: appLayoutType = DefaultLayoutType } = useSelector(
+    getCurrentApplicationLayout,
+  );
+
+  useEffect(() => {
+    if (!isCanvasInitialized && ref.current) {
```
Comment (riodeuno) [inline app/client/src/pages/Editor/WidgetsEditor/components/MainContainerWrapper/hooks/useCanvasWidthAutoResize.ts:22]: @alex-golovanov The `!isCanvasInitialized` is confusing me. I was wondering if calling this in line 52 would suffice?

File: app/client/src/utils/hooks/useDynamicAppLayout.tsx [hunk 2]
```diff
@@ -1,292 +0,0 @@
...
-    }
-
-    // if explorer is closed or its preview mode, we don't need to subtract the EE width
-    if (!isPreviewing && appMode === APP_MODE.EDIT) {
-      calculatedWidth -= explorerWidth;
-    }
-
-    if (appMode === APP_MODE.EDIT) {
-      calculatedWidth -= APP_SIDEBAR_WIDTH;
-    }
```
Comment (hetunandu) [inline app/client/src/utils/hooks/useDynamicAppLayout.tsx:128]: How did we avoid doing all of these calculations anymore? Is it because we are not looking at the ref of the container?

**Comment by shadabbuchh** [comment]
The issue is fixed in the above DP. However there seems to be a slight lag when the widgets inside the app resize itself to occupy the width available in the browser.
https://jam.dev/c/a4e76956-c179-4782-84fd-39992ea1151a

**Review by hetunandu — APPROVED** [review]

**Comment by alex-golovanov** [comment]
> The issue is fixed in the above DP. However there seems to be a slight lag when the widgets inside the app resize itself to occupy the width available in the browser. https://jam.dev/c/a4e76956-c179-4782-84fd-39992ea1151a

Thanks for testing it @shadabbuchh, the lag you've noticed is due to debouncing aspect, there is not much that can be done about it, given current approach.

File: app/client/src/pages/Editor/WidgetsEditor/components/MainContainerWrapper/hooks/useCanvasWidthAutoResize.ts (hunk 1 above)
Comment (alex-golovanov) [reply app/client/src/pages/Editor/WidgetsEditor/components/MainContainerWrapper/hooks/useCanvasWidthAutoResize.ts:22]: Was the question why we there are two effects?  First one fires on mount and it initializes canvas based on current container width, second effect attaches ResizeObserver, which in turn watches for changes. ResizeObserver may not always fire on mount. @riodeuno
