### PR TITLE
fix: prioritize parse errors in debugger callout

### LINKED ISSUE #13764: [Bug]: Prioritize parse error callouts in JS Editor debugger
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[See video](
[LOOM DEMO](https://www.loom.com/share/9ef82d9984064d8ba303d44b4b7e921d)

### Steps To Reproduce

1. Run a function in JS Editor with parse errors within it . Eg Run func1 in 

```
export default {
  myVar1: [],
  func1:async ()=>{	
	return f
	}
 }
```
Observe error callout (message is particular to `jsobject.func1`)

2. Now replace code with invalid js object

```
export default {
  myVar1: [] tetete
  func1:async ()=>{	
	return f
	}
 }
 
 Expected Callout Message: `JS object could not be parsed`
 Current Behaviour: Callout message doesn't change


### Public Sample App

_No response_

### Version

Cloud/ Release

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description 

Fixes #13764

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Cypress

- [x] Assert presence of function 'execution parse error' callout when function with error is executed
Screenshot 2022-05-14 at 20 51 29

- [x] Assert parse error callout when JS Object is invalid
Screenshot 2022-05-14 at 20 50 54

- [x] Assert that when JS Object becomes invalid after function with error is executed, parse error callout is shown

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: chore/prioritize-parse-errors-in-debugger-callout 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.64 **(0)** | 38.6 **(-0.01)** | 35.96 **(0)** | 56.89 **(0)**
 :red_circle: | app/client/src/components/editorComponents/JSResponseView.tsx | 50 **(-1.22)** | 25.88 **(-0.63)** | 8.33 **(0)** | 51.85 **(-1.31)**
 :red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**</details>

### CODE REVIEW

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts [hunk 1]
```diff
@@ -16,40 +17,98 @@ describe("JS Function Execution", function() {
...
+      .type(
+        "{shift}{uparrow}{uparrow}{uparrow}{uparrow}{uparrow}{uparrow}{uparrow}{uparrow}{uparrow}",
+        { force: true },
+      )
+      .type("{backspace}", { force: true });
+
+    // Add parse error that renders JS Object invalid in code
+    cy.get(locator._codeMirrorTextArea)
+      .first()
+      .then((el: any) => {
```
Comment (Rishabh-Rathod) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:102]: nit: Will `el: HTMLElement` not work here? 
If we are not aware of the type in the worst case we could use `unknown` instead of `any`.

**Review by Rishabh-Rathod — DISMISSED** [review]
LGTM

**Review by Aishwarya-U-R — CHANGES_REQUESTED** [review]
@ohansFavour - Testcase 4, line 87 to 103 - can we please update the existing CreateJSObj method in JSEditor.ts to use the same method instead of hardcoded lines in the spec?

@Aishwarya-U-R this is done. I have also cleaned up the CreateJSObject util, it had too many function parameters(ideally, parameters should be 3 or less).

Screenshot 2022-05-19 at 00 03 23
Screenshot 2022-05-19 at 00 02 55

**Review by Aishwarya-U-R — DISMISSED** [review]
CypressTests enhancements looks good!

**Review by Aishwarya-U-R — APPROVED** [review]
Approving cypress changes!
