### PR TITLE
fix: remove the duplicate and rename the actions to events in property panel

### LINKED ISSUE #14620: [Bug]-[166]:User gets "Actions" & "Events" (duplicate) sections in the Property Pane which save the same purpose
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are two issues:

1. A user is able to see both `Actions` & `Events` sections in the `Property Pane` for `TreeSelect` & `MultiTreeSelect` widgets which save the same purpose of providing the user with `onOptionChange` property. This can be confusing for the user as both have the same usage.
2. There is a naming inconsistency in the above section. For some widgets like `Button` widget we see the section named as `Events` and for `Button Group` widget it is named as `Actions`. 

Please have a look at the below video for clarity:
https://www.loom.com/share/feb9262bb7f343bb88a4bed2bf0c24b8

### Steps To Reproduce

1. D&D a `TreeSelect` or a `MultiTreeSelect` widget.
2. Go to the Property Pane and observe.

The user sees both `Actions` & `Events` sections in the `Property Pane`. 

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by techbhavin**
## Description

> Fix the issue of the User getting "Actions" & "Events" (duplicate) sections in the tree-select and multi-tree-select widget in the property Panel.

Fixes #14620 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/widgets/ButtonGroupWidget/widget/index.tsx [hunk 1]
```diff
@@ -344,7 +344,7 @@ class ButtonGroupWidget extends BaseWidget<
                             ],
                           },
                           {
-                            sectionName: "Actions",
+                            sectionName: "Events",
```
Comment (Tooluloope) [inline app/client/src/widgets/ButtonGroupWidget/widget/index.tsx:347]: Button Group.
Camera
Currency Input
Input
JSONForm and All Field Types
MapChart
All Selects
Phone Input
Switch Group

These are all the Widgets that uses Actions instead of Events

**Review by Tooluloope — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/ButtonGroupWidget/widget/index.tsx (hunk 1 above)
Comment (Tooluloope) [reply app/client/src/widgets/ButtonGroupWidget/widget/index.tsx:347]: This would be handled in another PR

**Review by Tooluloope — DISMISSED** [review]

**Comment by chandannkumar** [comment]
@techbhavin The DP link seems broken here

**Comment by vivekverma2312** [comment]
@techbhavin Duplicate properties are removed the issue is now all the drop-down widget is not consistent.

- `Select` widget has `Action` at bottom of property pane
- `Multiselect` has `Action` at bottom of property pane
- `Treeselect` has `Events` in center of property pane
- `Multitreeselect` has `Event` in center of property pane

**Comment by techbhavin** [comment]
@dilippitchika  can we want to rename 'Actions' to 'Events' in the Select and MultiSelect widget in a current PR?

**Comment by dilippitchika** [comment]
@techbhavin yes please rename

**Comment by Athayde3586** [comment]
Ok to what test

**Review by Tooluloope — DISMISSED** [review]

**Comment by vivekverma2312** [comment]
@techbhavin Thanks for the fix it's working fine now.

**Review by Tooluloope — APPROVED** [review]
