### PR TITLE
fix: Table Widget property to specify if prev or next buttons were pressed

### LINKED ISSUE #10522: [Feature]: Id based pagination or Cursors based pagination (or both) for performance issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A way to access the last id (before the page change).
So that in theory can make `id > Table1.lastId Limit 10`.
Or for postgres: https://www.postgresql.org/docs/9.2/plpgsql-cursors.html with `Table1.lastPageNo` so you can move the cursor with a condition: `Table1.lastPageNo > Table1.pageNo`

### Why should this be worked on?

https://use-the-index-luke.com/no-offset
Performance if you need to go back allot.

### PR DESCRIPTION
**Pull request by rajatagrawal**
… (#10522)

Fixes #10522

We have added two new boolean meta properties, previousPageVisited and nextPageVisited, that are set whenever respective pagination button is clicked. This property is updated for server side pagination mode as well as non server side pagination mode.

By default, both properties are set to false.

When the user clicks on previous page button or tries to enter a page number which is less than current page number, `previousPageVisited` is set to `true` and `nextPageVisited` is set to `false`.

The users can use these property as follows in their code : 

```
myFun1: () => {
		if (Table1.nextPageVisited == true){
			NextQuery.run()
		}
		else if (Table1.prevPageVisited == true){
			PrevQuery.run()
		}
		else {
			BaseQuery.run()
		}
	}
```

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/ce/utils/autocomplete/EntityDefinitions.ts [hunk 1]
```diff
@@ -154,6 +154,10 @@ export const entityDefinitions = {
     tableHeaders: generateTypeDef(widget.tableHeaders),
     newRow: generateTypeDef(widget.newRow),
     isAddRowInProgress: "bool",
+    previousPageButtonClicked: generateTypeDef(
```
Comment (riodeuno) [inline app/client/src/ce/utils/autocomplete/EntityDefinitions.ts:157]: Architecture note: These need to be either auto generated from the widget properties or defined in the widget configuration. This is because we need to make sure that all widget related configurations exist in the widget folder (these folders are the ones in `widgets` directory). That way, we can make sure widgets are pluggable components and don't have any dependency on platform code like this.

Comment (riodeuno) [reply app/client/src/ce/utils/autocomplete/EntityDefinitions.ts:157]: The above note is for a separate PR. I've created an issue https://github.com/appsmithorg/appsmith/issues/21718

**Comment by riodeuno** [comment]
@rajatagrawal This adds an API for table widget, adding a new feature that did not exist earlier. 
This means that we need to do two things:
1. Add this to the Table Widget PRD with the help of @dilippitchika and @sbalaji1192 
2. Update the documentation of Table widget on docs.appsmith.com
3. Write a cypress test, testing this new API
4. We need a test plan for this which the @appsmithorg/qa can help create for your review and approval. Once created we can link to the test plan in the description.
5. Update the PR description answering the following questions (This will be necessary for our release notes)
    - What was the use-case? (I guess the original issue describes this, a TL;DR will be helpful)
    - What did we do to satisfy the use-case?
    - Was there anything else we considered but went with this approach?

File: app/client/src/ce/utils/autocomplete/EntityDefinitions.ts (hunk 1 above)
Comment (sbalaji1192) [reply app/client/src/ce/utils/autocomplete/EntityDefinitions.ts:157]: @riodeuno A while back I asked souma to do a POC to move this definition to the widget config and it will get registered to the entity definition registry while the widget gets registered. We were able to do this with minimal code changes to widget factory.

File: app/client/src/widgets/TableWidgetV2/widget/index.tsx [hunk 2]
```diff
@@ -1361,8 +1365,36 @@ class TableWidgetV2 extends BaseWidget<TableWidgetProps, WidgetState> {
...
+    }
+
+    this.props.updateWidgetMetaProperty(
+      "previousPageButtonClicked",
+      previousButtonFlag,
+    );
+    this.props.updateWidgetMetaProperty(
+      "nextPageButtonClicked",
+      nextButtonFlag,
+    );
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/widget/index.tsx:1392]: @vsvamsi1 There is a conflict here related to your batch update in table performance changes. Please coordinate with Rajat on who is going to merge first and resolve the conflict.

File: app/client/src/ce/utils/autocomplete/EntityDefinitions.ts (hunk 1 above)
Comment (sbalaji1192) [reply app/client/src/ce/utils/autocomplete/EntityDefinitions.ts:157]: @rajatagrawal Please reach out to me when you work on this. Will give you the context.

Comment (rajatagrawal) [reply app/client/src/ce/utils/autocomplete/EntityDefinitions.ts:157]: cool

File: app/client/src/widgets/TableWidgetV2/widget/index.tsx [hunk 3]
```diff
@@ -1361,8 +1365,36 @@ class TableWidgetV2 extends BaseWidget<TableWidgetProps, WidgetState> {
     }
   };
 
+  updatePaginationButtonMetaProperties = (direction?: EventType) => {
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/TableWidgetV2/widget/index.tsx:1368]: done

File: app/client/src/widgets/TableWidgetV2/widget/index.tsx [hunk 4]
```diff
@@ -142,6 +142,8 @@ class TableWidgetV2 extends BaseWidget<TableWidgetProps, WidgetState> {
       isAddRowInProgress: false,
       newRowContent: undefined,
       newRow: undefined,
+      previousPageButtonClicked: false,
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/TableWidgetV2/widget/index.tsx:145]: okay. changing the property name to `previousPageVisited` and `nextPageVisited` for now.

File: app/client/src/widgets/TableWidgetV2/widget/index.tsx [hunk 5]
```diff
@@ -1361,8 +1365,36 @@ class TableWidgetV2 extends BaseWidget<TableWidgetProps, WidgetState> {
...
+    );
+    this.props.updateWidgetMetaProperty(
+      "nextPageButtonClicked",
+      nextButtonFlag,
+    );
+  };
+
   handleNextPageClick = () => {
     const pageNo = (this.props.pageNo || 1) + 1;
+    this.updatePaginationButtonMetaProperties(EventType.ON_NEXT_PAGE);
```
[the remark this answers is not in the document]
Comment (rajatagrawal) [reply app/client/src/widgets/TableWidgetV2/widget/index.tsx:1397]: done

**Comment by rajatagrawal** [comment]
@kamakshibhat-appsmith

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_pagination_spec.js [hunk 6]
```diff
@@ -17,6 +17,54 @@ describe("Table Widget property pane feature validation", function () {
...
+    cy.get(commonlocators.bodyTextStyle).should("have.text", "false true");
+
+    // Type and go to previous page
+    cy.get(".t--table-widget-page-input .bp3-input").clear().type("1{enter}");
+    cy.get(commonlocators.bodyTextStyle).should("have.text", "true false");
+
+    cy.closePropertyPane();
+  });
+
+  it("3. updates previous and next pagination propeties properly in server side pagination mode", function () {
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_pagination_spec.js:50]: Can we combine this into one it block? There is a discussion going on to merge it blocks that are asserting similar things. for cost reduction.

File: app/client/src/widgets/TableWidgetV2/widget/index.tsx [hunk 7]
```diff
@@ -111,6 +111,11 @@ const ReactTableComponent = lazy(() =>
   retryPromise(() => import("../component")),
 );
 
+enum PaginationDirection {
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/widget/index.tsx:114]: Please move this to constants file. we will also need to use this on the table header tsx file as well.

**Review by sbalaji1192 — APPROVED** [review]
