### PR TITLE
fix: configurable item in edit mode

### LINKED ISSUE #19043: Task: List v2 Prevent duplicated template widget id generation for meta widgets

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

1. Makes the first item of each page configurable
2. Retains changes in the first item when data changes
3. Regenerates appropriate no of items when data changes.

### Steps to reproduce
Issue 2
1. Drop an input widget
2. Type something in the input widget of first item
3. Go to page 2
4. Type something different in the input widget of the first item
5. Go to page 1 and observe the input value from Step 2 is retained
6. Go to page 2 and observe the input value from Step 4 is retained

Issue 3
For this first check in the base widget the behavior and then check here for comparison
1. Drop a List v2 widget
2. Make the widget taller
3. Drop the following data
```
[  { "id": 1, "name": "Blue" },
  { "id": 2, "name": "Pink" },
  { "id": 3, "name": "Black" }]
```
4. Then update the data to
```
[{ "id": 0, "name": "Green" },
      { "id": 1, "name": "Blue" },
      { "id": 2, "name": "Pink" },
      { "id": 3, "name": "Black" }]
```
5. Observe in the base branch DP that there are now only 3 items instead for 4

Fixes #19043

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Jest

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by Tooluloope — CHANGES_REQUESTED** [review]
Hi @ashit-rath 

Found some issues with other widgets not responding to inputs or clicks

https://user-images.githubusercontent.com/31691737/209026307-8b8d5308-c860-495b-836c-2ca39b40adce.mov

File: app/client/src/widgets/MetaHOC.tsx [hunk 1]
```diff
@@ -146,7 +146,16 @@ function withMeta(WrappedWidget: typeof BaseWidget) {
...
       const { syncUpdateWidgetMetaProperty } = this.context;
-      const { widgetId } = this.props;
+      /**
+       * Some meta widget will have the actual widget's widgetId as it's widgetId.
+       * Eg - these are the widgets that are present in the first row of the List widget.
+       * For these widgets, it's expected for the meta updates to not go into the actual widgetId
+       * but a different internal id as over page changes the first row widgets should reflect distinct
+       * values entered in that particular page.
+       *
+       * Note: metaWidgetId would be undefined for almost all the widgets.
```
Comment (Tooluloope) [inline app/client/src/widgets/MetaHOC.tsx:156]: Shouldn't this be `Note: metaWidgetId would be undefined for all non metaWidgets.`

File: app/client/src/sagas/ModalSagas.ts [hunk 2]
```diff
@@ -142,9 +143,12 @@ export function* showModalSaga(
 
   yield put(focusWidget(action.payload.modalId));
 
+  const modalWidget = {
```
Comment (Tooluloope) [inline app/client/src/sagas/ModalSagas.ts:146]: should we go for `widgetLikeProps` or `modalWidget`

**Review by Tooluloope — CHANGES_REQUESTED** [review]

**Review by Tooluloope — APPROVED** [review]
