### PR TITLE
fix: Reconnect failure error after fork application

### LINKED ISSUE #24566: [Bug]: Unable to Re-Authorize Google Sheets Datasource After Forking App to New Workspace
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After forking an app that is connected to a Google Sheets datasource to a new workspace, users get an error when trying to re-authorize the datasource. 
[Front thread](https://app.frontapp.com/open/cnv_116n09e4?key=iI2Mr-RePsIhbhb09vxQqNDQ-jloEqUS)

image

image

image

The workaround is to create a new GS datasource from scratch and connect the queries to it.

### Steps To Reproduce

1. Create an app with **Google Sheets** as datasource.
2. Fork it to another workspace.
3. When opening the app, Appsmith will ask us to re-authorize.
4. If trying to re-authorize, errors are displayed.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud v1,9,23

Front logo [Front conversations](https://app.frontapp.com/open/top_fijik)

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
After forking an application, the reconnect modal appears. In the reconnect modal, it's not possible to reauthorize the google sheets plugin. This PR fixes the problem.

#### PR fixes following issue(s)
Fixes #24566
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing

- [x] Manual
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStorageDTO.java [hunk 1]
```diff
@@ -69,12 +69,7 @@ public DatasourceStorageDTO fork(Boolean forkWithConfiguration, String toWorkspa
         }
 
         if (!Boolean.TRUE.equals(forkWithConfiguration)) {
-            DatasourceConfiguration dsConfig = new DatasourceConfiguration();
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStorageDTO.java:72]: Hey were we able to figure out why this piece of code existed before?

Comment (nayan-rafiq) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStorageDTO.java:72]: No. I think it was there to avoid null pointer exception.

**Review by nidhi-nair — APPROVED** [review]

**Comment by btsgh** [comment]
Also tested the [Mongo](https://github.com/appsmithorg/appsmith/issues/24702), [S3](https://github.com/appsmithorg/appsmith/issues/24655), [Dynamo](https://github.com/appsmithorg/appsmith/issues/24669) issues on this DP.

**Comment by NilanshBansal** [comment]
@nayan-rafiq @nidhi-nair I see, we are setting the entire datasourceConfiguration object as null if the forkWithConfiguration is False but we only need the authentication to be set as null ideally.
Setting the entire datasourceConfiguration object as null will also remove the other fields as well for the new workspace and the user will have to enter all the details again from the datasource reconnection modal.

image
 
 
image

**Comment by NilanshBansal** [comment]
converted the PR to draft as Sneha is working on this from the frontend, if it is fixed then no backend change required. 
Discussion Thread: https://theappsmith.slack.com/archives/C0341RERY4R/p1686935585764669

**Comment by NilanshBansal** [comment]
Approved, pls go ahead @nayan-rafiq @nidhi-nair

**Review by NilanshBansal — APPROVED** [review]

**Comment by NilanshBansal** [comment]
@btsgh can you pls merge this, ci already passed earlier
