### PR TITLE
fix: Error log on a widget property not clearing out when the widget property is deleted

### LINKED ISSUE #12894: [Bug]-[2760]:JSON form shows error in debugger on first bind
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JSON form shows that the date of birth field's default value is invalid, even after updating the data

[LOOM DEMO](https://www.loom.com/share/ac7417a1751046aba81b7eb285cef370)

### Steps To Reproduce

1. Add a new json form
2. Bind a query
3. Open debugger and see error
4. Refresh page and notice error goes away

### Public Sample App

_No response_

### Version

Production

### PR DESCRIPTION
**Pull request by Druthi**
## Description
fix: Error log on a widget property not clearing out when the widget property is deleted

Fixes #12894 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/workers/common/DependencyMap/index.ts [hunk 1]
```diff
@@ -379,6 +383,15 @@ export const updateDependencyMap = ({
...
           removedPaths.push(dataTreeDiff.payload.propertyPath);
           // If an existing entity was deleted, remove all the bindings from the global dependency map
+
+          const propertyPath = dataTreeDiff.payload.propertyPath;
+          const dependencyPath = dataTreeEvalRef.dependencyMap[propertyPath];
+          pathsToClearErrorsFor.push(propertyPath);
+
+          if (dependencyPath) {
+            pathsToClearErrorsFor.push(...dependencyPath);
+          }
```
Comment (arunvjn) [inline app/client/src/workers/common/DependencyMap/index.ts:393]: Can you create an widget with an error state, bind it to the computedValue property in a custom column and see what happens when you delete the column ?

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Widget_Error_spec.ts [hunk 2]
```diff
@@ -3,14 +3,18 @@ import { ObjectsRegistry } from "../../../../support/Objects/Registry";
 const dsl = require("../../../../fixtures/buttondsl.json");
 const widgetLocators = require("../../../../locators/Widgets.json");
 
-const { DebuggerHelper: debuggerHelper } = ObjectsRegistry;
+const {
+  DebuggerHelper: debuggerHelper,
+  PropertyPane: propPane,
+} = ObjectsRegistry;
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Widget_Error_spec.ts:9]: Use Import from Objects Core:
`import * as _ from "../../../../support/Objects/ObjectsCore";`
And use it like:
`_.ee.DragDropWidgetNVerify()`

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Widget_Error_spec.ts [hunk 3]
```diff
@@ -64,4 +68,26 @@ describe("Widget error state", function() {
...
   });
+
+  it("Bug-2760: Error log on a widget property not clearing out when the widget property is deleted", function() {
+    cy.dragAndDropToCanvas("tablewidgetv2", {
+      x: 150,
+      y: 300,
+    });
+    cy.openPropertyPane("tablewidgetv2");
+    cy.addColumnV2("customColumn1");
+    cy.editColumn("customColumn1");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Widget_Error_spec.ts:79]: Use ts helpers only. No direct cy statements in spec files.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Widget_Error_spec.ts [hunk 4]
```diff
@@ -3,14 +3,18 @@ import { ObjectsRegistry } from "../../../../support/Objects/Registry";
...
+} = ObjectsRegistry;
 
 describe("Widget error state", function() {
   const modifierKey = Cypress.platform === "darwin" ? "meta" : "ctrl";
 
   before(() => {
     cy.addDsl(dsl);
   });
+
   it("Check widget error state", function() {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Widget_Error_spec.ts:18]: Index the `it` functions.

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Widget_Error_spec.ts [hunk 5]
```diff
@@ -64,4 +68,26 @@ describe("Widget error state", function() {
     cy.get("body").type(`{${modifierKey}}z`);
     debuggerHelper.AssertVisibleErrorMessagesCount(2);
   });
+
+  it("Bug-2760: Error log on a widget property not clearing out when the widget property is deleted", function() {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Widget_Error_spec.ts:72]: Index the `it` functions.

**Comment by ramsaptami** [comment]
LGTM cc: @Druthi

File: app/client/cypress/support/Pages/PropertyPane.ts [hunk 6]
```diff
@@ -377,4 +377,16 @@ export class PropertyPane {
     if (property)
       this.agHelper.AssertElementExist(this._propertyControl(property));
   }
+
+  public BackFromPropertyPanel() {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/PropertyPane.ts:381]: Can we use the already existing NavigateBackToPropertyPane() method?

File: app/client/src/workers/common/DependencyMap/index.ts (hunk 1 above)
Comment (Druthi) [reply app/client/src/workers/common/DependencyMap/index.ts]: Tried this and it worked fine.

File: app/client/cypress/support/Pages/TableV2.ts [hunk 7]
```diff
@@ -175,7 +181,7 @@ export class TableV2 {
     if (pageNo == 1) cy.get(this._previousPage).should("have.attr", "disabled");
   }
 
-  public AssertSelectedRow(rowNum: number = 0) {
+  public AssertSelectedRow(rowNum = 0) {
```
Comment (ApekshaBhosale) [inline app/client/cypress/support/Pages/TableV2.ts:184]: why did you remove type here?

**Review by ApekshaBhosale — APPROVED** [review]

File: app/client/cypress/support/Pages/TableV2.ts (hunk 7 above)
Comment (Druthi) [reply app/client/cypress/support/Pages/TableV2.ts:184]: Weird, autosave is removing it.

Comment (Druthi) [reply app/client/cypress/support/Pages/TableV2.ts:184]: Checked with @Aishwarya-U-R 

"Since it has default value assigned - 0 - which is number - its being removed". This is expected
