### PR TITLE
Fix/api editor enhancement

### LINKED ISSUE #5094: [Feature] Move headers from action to datasource on save
**Save all the headers in the action to the datasource when "Save as datasource" is triggered.**

- Copy only the key-value pairs which doesn't have dynamic binding in it.

- All the copied headers should be removed from the action and now be a part of datasource.

- Keep the datasources tab on the right open by default. This will help remind the users  of the already configured datasources.

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Minor enhancement to copy action headers to datasources on save. 
Keeping the datasource tab on the right open by default.

Fixes #5094 

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/api_editor_enhancement 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.66 **(-0.01)** | 32.89 **(-0.01)** | 29.59 **(0)** | 52.14 **(-0.01)**
 :red_circle: | app/client/src/sagas/DatasourcesSagas.ts | 13.91 **(-0.04)** | 2.11 **(-0.04)** | 9.52 **(-0.48)** | 16.36 **(-0.07)**</details>

### CODE REVIEW

File: app/client/src/sagas/DatasourcesSagas.ts [hunk 1]
```diff
@@ -573,7 +573,23 @@ function* storeAsDatasourceSaga() {
   const pageId = yield select(getCurrentPageId);
   let datasource = _.get(values, "datasource");
   datasource = _.omit(datasource, ["name"]);
-
+  const originalHeaders = _.get(values, "actionConfiguration.headers", []);
+  const datasourceHeaders = originalHeaders.filter(
+    ({ value }: { key: string; value: string }) => {
+      const bindOpen = value.indexOf("{{");
+      const bindClose = value.indexOf("}}");
+      return !(bindOpen > -1 && bindClose > -1 && bindOpen < bindClose);
```
Comment (hetunandu) [inline app/client/src/sagas/DatasourcesSagas.ts:581]: We have a regex to check for this. 
https://github.com/appsmithorg/appsmith/blob/179d5ae8a95f998c00aee5bd375f73d807fa17be/app/client/src/utils/DynamicBindingUtils.ts#L19

Both key and value could have bindings so we should check for bindings in both

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/sagas/DatasourcesSagas.ts [hunk 2]
```diff
@@ -573,7 +574,23 @@ function* storeAsDatasourceSaga() {
   const pageId = yield select(getCurrentPageId);
   let datasource = _.get(values, "datasource");
   datasource = _.omit(datasource, ["name"]);
-
+  const originalHeaders = _.get(values, "actionConfiguration.headers", []);
+  const datasourceHeaders = originalHeaders.filter(
+    ({ key, value }: { key: string; value: string }) => {
+      return !(
+        DATA_BIND_REGEX_GLOBAL.test(key) || DATA_BIND_REGEX_GLOBAL.test(value)
```
Comment (hetunandu) [inline app/client/src/sagas/DatasourcesSagas.ts:581]: Just use the function `isDynamic`

File: app/client/src/sagas/DatasourcesSagas.ts [hunk 3]
```diff
@@ -573,7 +574,21 @@ function* storeAsDatasourceSaga() {
...
   let datasource = _.get(values, "datasource");
   datasource = _.omit(datasource, ["name"]);
-
+  const originalHeaders = _.get(values, "actionConfiguration.headers", []);
+  const datasourceHeaders = originalHeaders.filter(
+    ({ key, value }: { key: string; value: string }) => {
+      return !(isDynamicValue(key) || isDynamicValue(value));
+    },
+  );
+  const actionHeaders = _.difference(originalHeaders, datasourceHeaders);
```
Comment (hetunandu) [inline app/client/src/sagas/DatasourcesSagas.ts:583]: Perf improvement:
If you use a function like https://lodash.com/docs/4.17.15#partition you will have to loop through the list only once

**Review by hetunandu — APPROVED** [review]
