### PR TITLE
fix: show lint when unused variable is present in code

### LINKED ISSUE #10589: Linter doesn't show an error for unused variables
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Screenshot 2022-01-24 at 12 02 45

I don't get warned for unused variables

### Steps To Reproduce

On any code editor, write a valid JavaScript function with unused variable(s). Notice that you do not get warned.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description
This PR introduces warnings in linting. Users get warned when an unused variable is present in the code.

Screenshot 2022-01-27 at 22 03 12

Fixes #10589 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/show-lint-error-for-unused-variables 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.01 **(0.01)** | 36.57 **(0.01)** | 34.93 **(0)** | 55.41 **(0.01)**
 :sparkles: :new: | **app/client/src/components/editorComponents/CodeEditor/constants.ts** | **100** | **100** | **100** | **100**
 :green_circle: | app/client/src/components/editorComponents/CodeEditor/lintHelpers.ts | 97.33 **(0.23)** | 77.78 **(1.31)** | 100 **(0)** | 96.67 **(0.31)**</details>

### CODE REVIEW

File: app/client/src/components/editorComponents/CodeEditor/lintHelpers.ts [hunk 1]
```diff
@@ -125,3 +126,25 @@ export const getLintAnnotations = (
...
+    message: "'{a}' is defined but never used.",
+  },
+];
+
+export const getLintSeverity = (
+  code: string,
+): Severity.WARNING | Severity.ERROR => {
+  let severity = Severity.ERROR;
+
+  WARNING_LINT_ERRORS.forEach((warningError) => {
```
Comment (Rishabh-Rathod) [inline app/client/src/components/editorComponents/CodeEditor/lintHelpers.ts:144]: If we need to match code then why not make `WARNING_LINT_ERRORS` as an object with key as code and message as value?
 ```
 const WARNING_LINT_ERRORS = {
   "W098" : "'{a}' is defined but never used.",
  };
  ```

**Review by Rishabh-Rathod — APPROVED** [review]
Looks good.

mentioned nit pick in above comment
