### PR TITLE
fix: import issue with workspace id fixed

### LINKED ISSUE #27594: [Bug]: On importing an application and testing DS, I get unable to find environment production - on GAC DP intermittently.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to import an application, on clicking Test config, I see an error which reads unable to find env prod. This does not happen on release. Also, this happens the first time, and then intermittently.

### Steps To Reproduce

Login to the 1-click DP. Try to import the attached application [convert json to txt]. An error pops up. 
[OldApp_DSTesting1.9.24 (1).txt](https://github.com/appsmithorg/appsmith/files/12714097/OldApp_DSTesting1.9.24.1.txt)

Screenshot 2023-09-25 at 3 55 06 PM

https://github.com/appsmithorg/appsmith/assets/101863839/b6cb6096-2e20-4d72-ad5a-384951959987

### Public Sample App

_No response_

### Environment

Deploy Preview

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by sneha122**
## Description

In a case where we are inside an application, then we come back to home page and add a new workspace and try importing application in that newly created workspace, the workspace Id that is being sent along with test API is workspaceId of previous workspace and not the new one. This PR fixes that issue.

Issue occurs because for test API we are sending workspaceId which we get from redux state. Whenever we enter inside any application, we set the currentWorkspace object inside state, this object contains data about current workspace, but when we leave the application and come back to home page, we are not resetting this currentWorkspace object, it still contains stale data, hence when we create new workspace and import application, it gets workspace id from this stale object.

#### PR fixes following issue(s)
Fixes #27594 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
1. Login to appsmith, create a new app in a new workspace. Now come back to home page, and create a new workspace and then import an application. The reported error should no longer appear
2. Tried with new workspace, new app created and app level import. Here also the error does not appear. 
3. Tried forking an app into a new workspace. Here also error does not occur
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by ankitakinger — APPROVED** [review]
LGTM

**Review by dipyamanbiswas07 — APPROVED** [review]
LGTM

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug27594_spec.ts [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+      agHelper.GetNClick(homePageLocatores.optionsIcon, 1);
+      agHelper.GetNClick(homePageLocatores.workspaceImportAppOption, 0, true);
+
+      agHelper.AssertElementVisibility(
+        homePageLocatores.workspaceImportAppModal,
+      );
+      cy.xpath(homePageLocatores.uploadLogo).selectFile(
+        "cypress/fixtures/forkedApp.json",
+        { force: true },
+      );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug27594_spec.ts:29]: Can `homePage.ImportApp("forkedApp.json");` be used?

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug27594_spec.ts [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+        if (isPartialImport) {
+          // should reconnect button
+          dataSources.ReconnectSingleDSNAssert("mockdata", "PostgreSQL", true);
+          homePage.AssertNCloseImport();
+          agHelper.Sleep(2000);
+        } else {
+          cy.get(homePageLocatores.toastMessage).should(
+            "contain",
+            "Application imported successfully",
+          );
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug27594_spec.ts:48]: Can `homePage.AssertImportToast();` be used?

File: app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug27594_spec.ts [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+        cy.wait("@getPagesForCreateApp").then((interception) => {
+          const pages = interception?.response?.body.data.pages;
+          let defaultPage = pages.find((eachPage) => !!eachPage.isDefault);
+          // validating data binding for imported application
+          agHelper.AssertElementVisibility("//input[@value='Submit']");
+          agHelper.AssertElementVisibility("//span[text()='schema_name']");
+          agHelper.AssertElementVisibility("//span[text()='id']");
+          agHelper.AssertElementVisibility("//span[text()='title']']");
+          agHelper.AssertElementVisibility("//span[text()='due");
+
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug27594_spec.ts:61]: No direct locators in spec. Use `locators._visibleTextSpan`

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug27594_spec.ts:61]: And what are these elements, After app is imported - table columns?

File: app/client/cypress/support/Pages/DataSources.ts [hunk 4]
```diff
@@ -1091,12 +1091,16 @@ export class DataSources {
...
     dbName: string,
     dsName: "PostgreSQL" | "MySQL" | "MongoDB",
+    shouldTestDatasource = false,
   ) {
     this.ReconnectModalValidation(dbName, dsName);
     this.ValidateNSelectDropdown("Connection mode", "Read / Write");
     if (dsName == "PostgreSQL") this.FillPostgresDSForm();
     else if (dsName == "MySQL") this.FillMySqlDSForm();
     else if (dsName == "MongoDB") this.FillMongoDSForm();
+    if (shouldTestDatasource) {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/support/Pages/DataSources.ts:1101]: Is Testing ds going to add value?

Comment (sneha122) [reply app/client/cypress/support/Pages/DataSources.ts:1101]: Yes test ds is the case where the issue is, As discussed, will be updating ServerSide -> OnLoadTests -> JSoNload_spec 2 for covering above scenario

**Comment by sneha122** [comment]
@Aishwarya-U-R Please review again, as discussed I have removed new test case and modified existing one

File: app/client/cypress/support/Pages/DataSources.ts (hunk 4 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/DataSources.ts:1101]: Can we by default test for all `ReconnectSingleDSNAssert` calls - instead of parameter? And in that case can use `dataSources.TestSaveDatasource`

Comment (sneha122) [reply app/client/cypress/support/Pages/DataSources.ts:1101]: @Aishwarya-U-R I think this is good have to have for now, to have it configurable through parameter, because sometimes you would just want to save the datasource without test, then again we would have to add a flag to skip test. Also by making it test implicitly, we may end up breaking a couple of tests which are using this generic function

Comment (Aishwarya-U-R) [reply app/client/cypress/support/Pages/DataSources.ts:1101]: because sometimes you would just want to save the datasource without test - do we have a scenrioa for this?

Comment (sneha122) [reply app/client/cypress/support/Pages/DataSources.ts:1101]: I do not know of any such scenario yet, but I am sure if we make test implicit, there will be a couple of test case failures.

Comment (sneha122) [reply app/client/cypress/support/Pages/DataSources.ts:1101]: We can maybe create another issue to make it implicit, that way if at all there are any failures we can handle it separately and let this PR go in

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes.

**Review by Aishwarya-U-R — DISMISSED** [review]

**Comment by btsgh** [comment]
Tested this on the above DP and the issue is not reproducible any more. Has been fixed.

**Review by dipyamanbiswas07 — APPROVED** [review]
LGTM
