### PR TITLE
fix: check if smartlook, sentry and analytics are inited before the init call

### LINKED ISSUE #9575: [Bug]: Profile Page is inaccessible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Users cannot access the profile page

### Steps To Reproduce

1. login
2. navigate to https://app.appsmith.com/profile
3. you will be logged out

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
Checks if smartlook, sentry and analytics exist on the `window` object before initing
Fixes #9575

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually: this would need smartlook enabled to verify 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: reinit-smartlook-error 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 55.13 **(-0.01)** | 37.16 **(-0.02)** | 33.97 **(0)** | 55.63 **(-0.02)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 **(-2.35)**
 :red_circle: | app/client/src/utils/AppsmithUtils.tsx | 55.19 **(-1.33)** | 28.85 **(-1.76)** | 33.33 **(0)** | 50 **(-1.41)**</details>

### CODE REVIEW

File: app/client/src/utils/AppsmithUtils.tsx [hunk 1]
```diff
@@ -57,45 +57,53 @@ export const appInitializer = () => {
...
-          return null;
-        }
-        if (breadcrumb.category === "sentry.transaction") {
-          return null;
-        }
-        if (breadcrumb.category === "redux.action") {
+  try {
+    const appsmithConfigs = getAppsmithConfigs();
+
+    if (appsmithConfigs.sentry.enabled) {
```
Comment (sbalaji1192) [inline app/client/src/utils/AppsmithUtils.tsx:63]: let's check for window.Sentry here.

File: app/client/src/utils/AppsmithUtils.tsx [hunk 2]
```diff
@@ -57,45 +57,53 @@ export const appInitializer = () => {
...
+    }
 
-  if (appsmithConfigs.segment.enabled) {
-    if (appsmithConfigs.segment.apiKey) {
-      // This value is only enabled for Appsmith's cloud hosted version. It is not set in self-hosted environments
-      AnalyticsUtil.initializeSegment(appsmithConfigs.segment.apiKey);
-    } else if (appsmithConfigs.segment.ceKey) {
-      // This value is set in self-hosted environments. But if the analytics are disabled, it's never used.
-      AnalyticsUtil.initializeSegment(appsmithConfigs.segment.ceKey);
+    if (appsmithConfigs.segment.enabled) {
```
Comment (sbalaji1192) [inline app/client/src/utils/AppsmithUtils.tsx:95]: lets check for window.analytics

**Review by sbalaji1192 — APPROVED** [review]
LGTM

File: app/client/src/utils/AppsmithUtils.tsx [hunk 3]
```diff
@@ -57,45 +57,53 @@ export const appInitializer = () => {
...
+      if (appsmithConfigs.segment.apiKey) {
+        // This value is only enabled for Appsmith's cloud hosted version. It is not set in self-hosted environments
+        AnalyticsUtil.initializeSegment(appsmithConfigs.segment.apiKey);
+      } else if (appsmithConfigs.segment.ceKey) {
+        // This value is set in self-hosted environments. But if the analytics are disabled, it's never used.
+        AnalyticsUtil.initializeSegment(appsmithConfigs.segment.ceKey);
+      }
     }
+  } catch (e) {
+    Sentry.captureException(e);
```
Comment (hetunandu) [inline app/client/src/utils/AppsmithUtils.tsx:105]: There might be an error in initializing sentry itself right? We cannot capture that exception in that case

Comment (rishabhsaxena) [reply app/client/src/utils/AppsmithUtils.tsx:105]: Yeah to be sure, we could add another try catch around the `captureException` statement, does that sound good?

Comment (rishabhsaxena) [reply app/client/src/utils/AppsmithUtils.tsx:109]: @hetunandu based on the tip, have added an additional try catch to the sentry code instead

File: app/client/src/utils/AppsmithUtils.tsx [hunk 4]
```diff
@@ -57,45 +57,57 @@ export const appInitializer = () => {
...
-        }
-        return breadcrumb;
-      },
-    });
-  }
+  try {
+    const appsmithConfigs = getAppsmithConfigs();
+
+    try {
+      if (appsmithConfigs.sentry.enabled && !window.Sentry) {
```
Comment (hetunandu) [inline app/client/src/utils/AppsmithUtils.tsx:64]: Do not nest your try / catch

**Review by hetunandu — APPROVED** [review]
