### PR TITLE
fix: autocommit ui issues

### LINKED ISSUE #30628: [Bug]: If the user has not done his first commit then this auto commit bar is displayed each time when user opens the app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user has not done his first commit then this auto commit bar is displayed each time when user opens the app

### Steps To Reproduce

1. take a local pull with " docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:v1.9.35"
2. Now import any bigger app
3. Now upgrade the instance keeping the old stack
4. docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:release
5. now open the git connected app te auto commit bar is displayed
6. go back to home page
7. open the same app
8. the auto commit bar is displayed again

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

v1.10

### LINKED ISSUE #30631: [Bug]: The auto commit bar is displayed even after users first commit
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The auto commit bar is displayed even after users first commit 

### Steps To Reproduce

1. take a local pull with " docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com/" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:v1.9.35"
2. Now import any bigger app
3. Now upgrade the instance keeping the old stack
4. docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com/" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:release
5. now open the git connected app to auto commit bar is displayed
7. after the auto commit please do your first commit may be by adding a new page
8. Now go back to home page and open the same app
9. The auto commit bar is displayed 

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

v1.10

### LINKED ISSUE #30704: [Bug]: The auto-commit bar is displayed even when the auto-commit feature is disabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The auto-commit bar is displayed even when the auto-commit feature is disabled
https://www.loom.com/share/195d942242fe42158c33e7ff700c666a?sid=1354be80-4c99-4f27-bfe9-57aab0aaafcf
image

### Steps To Reproduce

1. Pull docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:v1.9.58
2. connect the app to git and disable the auto commit on the application from setting tab
3. now upgarde the instance to latest release version
4. open the same app
5. The auto commit bar is displayed on the UI which seems little confusing to users
6. If we check in the Github there are no default commit displayed

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

v1.10

### LINKED ISSUE #30706: [Bug]: The auto-commit bar is displayed for a fraction of a second in the protected branches
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The auto-commit bar is displayed for a fraction of a second in the protected branches
https://www.loom.com/share/66cfd834560e4007a9fbb6511155ffba?sid=94340645-a543-46da-a761-68a4cfb58703

### Steps To Reproduce

1. Pull docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com/" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:v1.9.58
2. connect the app to git in setting tab make few of the branches as protected
3. now upgarde the instance to latest release version
4. open the same app
5. The auto commit bar is displayed on the UI for a sec 
6. If we check in the Github there are no default commit displayed

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

v1.10

### LINKED ISSUE #30737: [Bug]: When user has rbac access the branch and general tab looks kind of empty in setting modal
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user has rbac access the branch and general tab looks kind of empty in setting modal
image
the 

### Steps To Reproduce

1. pull docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com/" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:v1.9.58
2. connect few application to git and give edit and view access for application from RBAC role
3. and give this role access to user1
4. now login as user1
5. click on edit button
6. click on the setting icon
7. click on branch tab 
8. the tab looks empty

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

v1.10

### PR DESCRIPTION
**Pull request by brayn003**
## Description
- Adds initial checks in Sagas to avoid showing the auto-commit progress bar unnecessarily
- Adds component-level checks to avoid rendering progress when auto-commit is disabled
- Adds logic to remove branch tab from git settings modal when neither default branch nor protected branch permissions are present

#### PR fixes following issue(s)
Fixes #30628
Fixes #30631 
Fixes #30706 
Fixes #30704 
Fixes #30737

#### Media
image

- Bug fix (non-breaking change which fixes an issue)

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Enhanced autocommit functionality with improved progress polling, error handling, and branch tabs visibility based on permissions.
- **Refactor**
	- Adjusted autocommit progress polling logic and action types for better performance and reliability.

### CODE REVIEW

File: app/client/src/sagas/GitSyncSagas.ts [hunk 1]
```diff
@@ -1225,39 +1225,62 @@ function* getGitMetadataSaga() {
...
         }
-      } else {
-        yield put({
-          type: ReduxActionErrorTypes.GIT_AUTOCOMMIT_PROGRESS_POLLING_ERROR,
-          payload: {
-            error: response?.responseMeta?.error?.message,
-            show: true,
-          },
-        });
+        yield delay(1000);
```
Comment (sneha122) [inline app/client/src/sagas/GitSyncSagas.ts:1273]: Curious, why are we introducing a delay here? Asking because if we are waiting for any operation to get complete within 1000 ms and if it does not get complete, will it not cause issues?

Comment (brayn003) [reply app/client/src/sagas/GitSyncSagas.ts:1273]: Oh this delay is the delay b/w two polls
This saga is used for long polling using rest api

Comment (sneha122) [reply app/client/src/sagas/GitSyncSagas.ts:1273]: Got it

**Review by sneha122 — APPROVED** [review]
