### PR TITLE
fix: Fix annoying error with text input control

### LINKED ISSUE #19893: [Bug]-[3250]:GraphQL | Unable to re-write the Authenticated GraphQL API fields
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/213379350-69c69581-a295-4ed6-b12c-779cf1109232.mov

### Steps To Reproduce

1. Create a new Authenticated GraphQL datasource
2. Give a url value
3. Try to edit the field value
4. **Observe: The control is taken to end of line & user is not able to edit the field with ease (All fields in the datasource page has same behaviour - Headers, Query Parameters)**
5. **Expected: User should be able to edit fields with ease**

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud / v1.9.3.2

### PR DESCRIPTION
**Pull request by Irongade**
> Pull Request Template

For all API datasource forms (both Rest API and Graphql), the input text field was getting re-rendered on every change. This PR fixes that.

Fixes #19893

- Bug fix (non-breaking change which fixes an issue)

- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/pages/Editor/DataSourceEditor/index.tsx [hunk 1]
```diff
@@ -284,6 +210,8 @@ export interface DatasourcePaneFunctions {
   toggleSaveActionFromPopupFlag: (flag: boolean) => void;
   createTempDatasource: (data: any) => void;
   resetDefaultKeyValPairFlag: () => void;
+  toggleDatasourceViewMode: (newMode: boolean) => void;
```
Comment (sneha122) [inline app/client/src/pages/Editor/DataSourceEditor/index.tsx:213]: Are we using this action in the component? If not can we remove it?

File: app/client/src/sagas/DatasourcesSagas.ts [hunk 2]
```diff
@@ -1110,6 +1116,41 @@ function* executeDatasourceQuerySaga(
...
+  if (
+    defaultKeyValueArrayConfig &&
+    defaultKeyValueArrayConfig?.length > 0 &&
+    !!initialValue
+  ) {
+    const restAPIFormData: Datasource = yield select(
+      getFormValues(DATASOURCE_REST_API_FORM),
+    );
+    const formData: Datasource = yield select(
+      getFormValues(DATASOURCE_REST_API_FORM),
```
Comment (sneha122) [inline app/client/src/sagas/DatasourcesSagas.ts:1139]: it should be DATASOURCE_DB_FORM instead of DATASOURCE_REST_API_FORM as this object would represent form data for other datasources

Comment (Irongade) [reply app/client/src/sagas/DatasourcesSagas.ts:1139]: Good catch, Thanks Sneha

**Review by sneha122 — APPROVED** [review]
