### PR TITLE
fix: Entity props show evaluated value

### LINKED ISSUE #30648: [Bug]: undefined value in the bindings pane of explorer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.notion.so/appsmith/Fix-the-bindings-that-show-undefined-values-23d6e18c1ebf4bd2856279ad221f89cf

### Steps To Reproduce

1. Add a Table widget
2. Bind data to it
3. Open the explorer, click on more option for table widget and select show bindings
4. Notice that all the binding values are `undefined`. 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

1.9.61

### LINKED ISSUE #30670: [Bug]: bindings scroll is incorrect, overlaps with the heading
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/94514895/8ceb1246-486d-403f-be9b-acc26f19d26f

### Steps To Reproduce

1. Add a Table widget
2. Bind data to it
3. Open the explorer, click on more option for table widget and select show bindings
4. Scroll to see the problem

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rishabhrathod01**
## Description

- Header bg color white.
- Make the `entityProperties` generation code extendable so the module-related code can be moved to the EE repo. 
- Made the Binding text color similar to how it looks in code.
- Binding popup stays open on the widget select change and shows newly selected widget's binding.

#### PR fixes following issue(s)
Fixes #30670 
Fixes #30648 

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

<hr/>

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Steps to test the changes

1. Go to the application
2. Add widgets, query and JS function
3. Connect the widget with the query to show the data on canvas
4. Go to the entity explorer and click on more options to select "Show bindings"
5. Check the bindings for the respective entity. 

https://github.com/appsmithorg/appsmith/assets/23132741/0bf073d0-69f3-46f8-9107-c3fc48c7eb8f

### Issues raised during DP testing

- [x] Noticed that the `Query.data` doesn't show the evaluated values ( added by @rishabhrathod01 )
- [x] The binding popup doesn't close when clicked on any other widget. ( added by @rishabhrathod01 )

<hr/>

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

<hr/>

## Summary by CodeRabbit

- **New Features**
	- Introduced functions to fetch and organize properties for various entity types in the application.
- **Refactor**
	- Streamlined entity property extraction by removing redundant functions.
	- Optimized the `EntityProperties` component for better event handling and rendering based on entity type.
- **Style**
	- Adjusted layout and styling of the `EntityProperties` component for improved user interface.
- **Documentation**
	- Enhanced documentation for the `EntityProperty` component.

### CODE REVIEW

File: app/client/src/ce/pages/Editor/Explorer/Entity/getEntityProperties.ts [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+export const getPropsForJSActionEntity = (
+  jsActionEntity: JSActionEntity,
+  entityName: string,
+) => {
+  const properties: Record<string, unknown> = {};
+
+  const configTree = ConfigTreeActions.getConfigTree();
+  const jsActionEntityConfig = configTree[entityName] as JSActionEntityConfig;
+
+  const variablesProps = jsActionEntityConfig.variables;
```
Comment (sneha122) [inline app/client/src/ce/pages/Editor/Explorer/Entity/getEntityProperties.ts:33]: Could there be a case that jsActionEntityConfig is undefined? If yes we can run into error state because of that. Please check once

File: app/client/src/ce/pages/Editor/Explorer/Entity/getEntityProperties.ts [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+
+  if (config) {
+    entityProperties = Object.keys(config)
+      .filter((k) => k.indexOf("!") === -1)
+      .map((actionProperty: string) => {
+        let value = entity[actionProperty];
+        if (actionProperty === "isLoading") {
+          value = entity.isLoading;
+        }
+        if (actionProperty === "run") {
```
Comment (sneha122) [inline app/client/src/ce/pages/Editor/Explorer/Entity/getEntityProperties.ts:93]: The execution of "run" and "clear" is exactly same? Do we need two if blocks for it?

File: app/client/src/ce/pages/Editor/Explorer/Entity/getEntityProperties.ts (hunk 1 above)
Comment (rishabhrathod01) [reply app/client/src/ce/pages/Editor/Explorer/Entity/getEntityProperties.ts]: Can't think of any case where config would be undefined but to make sure code doesn’t break for an edge case added a check here.

File: app/client/src/components/editorComponents/HighlightedCode/index.tsx [hunk 3]
```diff
@@ -19,6 +19,14 @@ const StyledCode = styled.div<{ skin: Skin }>`
...
   padding: 0 0px;
 
+  code.language-appsmith-binding {
+    color: ${(props) => props.theme.colors.bindingText};
+  }
+  .token.punctuation {
+    color: hsl(222, 70%, 77%);
+  }
+  .token.property {
+    color: hsl(30, 77%, 40%);
```
[the remark this answers is not in the document]
Comment (rishabhrathod01) [reply app/client/src/components/editorComponents/HighlightedCode/index.tsx:29]: As the above colors are not part of the theme, it is hard coded for now.

File: app/client/src/ce/pages/Editor/Explorer/Entity/getEntityProperties.ts [hunk 4]
```diff
@@ -87,18 +96,17 @@ const getActionBindings = (
       .filter((k) => k.indexOf("!") === -1)
       .map((actionProperty: string) => {
         let value = entity[actionProperty];
-        if (actionProperty === "isLoading") {
+        if (actionProperty === ActionEntityPublicProperties.isLoading) {
```
Comment (sneha122) [inline app/client/src/ce/pages/Editor/Explorer/Entity/getEntityProperties.ts]: Nit: usually enum keys are in uppercase

**Comment by sneha122** [comment]
@rishabhrathod01 Tested the PR for following cases:
- Header bg color white => Looks good to me ✅
- Made the Binding text color similar to how it looks in code => Looks good to me ✅ 
- Overall the binding popup looks good => ✅

A couple of queries/feedback:
- For insert modal / show modal, the popup looks like this, should we just not show the popup when no bindings?
Screenshot 2024-02-07 at 12 34 16 PM
- First binding is shown as opened by default, I hope this is expected behaviour
Screenshot 2024-02-07 at 12 34 26 PM
- For refresh button, I see isVisible is the only thing shown in binding but it also has isDisabled state but it's not shown in bindings, Is there any reason for it? How do we determine what goes in show bindings and what does not? For select widget, I saw that isDisabled is also shown
Screenshot 2024-02-07 at 12 36 22 PM
- These values are in a input box, makes me think I can edit it [Just a feedback]
Screenshot 2024-02-07 at 12 37 38 PM
- Same question, why don't we show border radius or box shadow in bindings when they are clearly written in js mode?
Screenshot 2024-02-07 at 12 40 03 PM
- For select widget, filterText accordion is not opening, is this expected?
https://github.com/appsmithorg/appsmith/assets/30018882/a1d1ec51-5ae0-487f-bc6f-31206e917619

**Review by sneha122 — APPROVED** [review]

**Comment by rishabhrathod01** [comment]
> - First binding is shown as opened by default, I hope this is expected behaviour

@sneha122 This was added to make it easier for users to discover the value section. 

> - These values are in a input box, makes me think I can edit it [Just a feedback]
> - Same question, why don't we show border radius or box shadow in bindings when they are clearly written in js mode?

@sneha122 Yes, I agree and as we are redesigning the bindings section with IA-redesign I believe we could address these points. 
cc: @momcilo-appsmith @rohan-arthur 

> - For select widget, filterText accordion is not opening, is this expected?
> - For insert modal / show modal, the popup looks like this, should we just not show the popup when no bindings?

@sneha122 Yes, I did notice both of these issues while testing. For now, I avoided extending the scope of this PR. I will create separate tasks for these bugs. 

> - For refresh button, I see isVisible is the only thing shown in binding but it also has isDisabled state but it's not shown in bindings, Is there any reason for it? How do we determine what goes in show bindings and what does not? For select widget, I saw that isDisabled is also shown

@sneha122 we rely on what is exposed to the user in the autocomplete config of the widget. If a property is not shown then probably it is also not supported by autocomplete and we could fix the core issue.
