### PR TITLE
fix: revalidation logic 

### LINKED ISSUE #24905: [Bug]: Revalidation of widget properties not getting updated in the data tree
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the property pane configuration, we have a validation configuration called `dependentPaths` to list out the dependent properties that the current property is dependent on for validation. If any of the dependent properties change during evaluations we revalidate the current property. But this revalidation result is not getting updated on the data tree.

### Steps To Reproduce

For more info refer here - https://github.com/appsmithorg/appsmith/pull/17138

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Debugger logs were only updated according to the evaluation order earlier this led to an issue as after revalidation we need to update the debugger errors. 

#### PR fixes following issue(s)
Fixes #24905

#### Type of change

- Bug fix (non-breaking change which fixes an issue)

#### Test Plan

- Validation sanity test

#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/workers/common/DataTreeEvaluator/index.ts [hunk 1]
```diff
@@ -979,13 +987,23 @@ export default class DataTreeEvaluator {
...
+
+          switch (entityType) {
+            case ENTITY_TYPE.WIDGET: {
+              if (isATriggerPath) return currentTree;
+
+              const isNewWidget =
+                isFirstTree || isNewEntity(unevalUpdates, entityName);
+
+              const widgetEntity = entity as WidgetEntity;
+
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/common/DataTreeEvaluator/index.ts:1003]: code refactor to change if else to switch case

**Review by Rishabh-Rathod — COMMENTED** [review]
Self review: LGTM

File: app/client/src/workers/common/DataTreeEvaluator/index.ts [hunk 2]
```diff
@@ -752,22 +756,28 @@ export default class DataTreeEvaluator {
...
+    this.setEvalTree(newEvalTree);
+
     const reValidateStartTime = performance.now();
-    this.reValidateTree(
-      nonDynamicFieldValidationOrder,
+    const validationOrder = new Set([
+      ...evaluationOrder,
+      ...nonDynamicFieldValidationOrder,
+    ]);
+    const reValidatedPaths = this.reValidateTree(
```
Comment (arunvjn) [inline app/client/src/workers/common/DataTreeEvaluator/index.ts:774]: Is there no `skipRevalidation` condition anymore ?

**Review by arunvjn — APPROVED** [review]

**Comment by ramsaptami** [comment]
Sanity checked most used widget like input, table, checkbox, button and select and LGTM
cc: @Rishabh-Rathod
