### PR TITLE
fix: App visibility of git connected application is reset after git merge

### LINKED ISSUE #11682: [Bug]: App visibility is set to private after git merge operation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After merging the branches with in Appsmith if the app is public it is reset to private. 

### Steps To Reproduce

1. Connect an app to git repo
2. Create branch from the main branch 
3. Make the app public
4. Add a widget or page or make any changes and then do commit + push
5. Now merge the branch back to main branch
6. Try to access the app in view mode and notice that it is not public and user is redirected to login screen
### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description

For git connected application, app visibility is not working correctly. There are two parts
1. Visibility is reset after merging
2. When we change the visibility to Public/Private from the UI, it should be applied to all the branch applications.
This change set will fix both the cases. 

Fixes #11682 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Locally
- JUnit Tests

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java [hunk 1]
```diff
@@ -699,38 +700,48 @@
...
+                                                                                                existingApplication,
+                                                                                                existingApplication.getName(),
+                                                                                                0
+                                                                                        );
+                                                                            }
+                                                                            throw error;
+                                                                        });
                                                             });
                                                 });
+                                    } else {
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:722]: We can get away from the else as are returning from the if block

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java [hunk 2]
```diff
@@ -699,38 +700,48 @@
...
-                                                                                    0
-                                                                            );
-                                                                }
-                                                                throw error;
+                                                    return applicationService.findById(existingApplication.getGitApplicationMetadata().getDefaultApplicationId())
+                                                            .flatMap(application1 -> {
+                                                                // Set the policies from the defaultApplication
+                                                                existingApplication.setPolicies(application1.getPolicies());
+                                                                importedApplication.setPolicies(application1.getPolicies());
+                                                                return applicationService.save(existingApplication)
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:708]: Why are we not reutilizing the `changeViewAccess` with `isPublic` flag that we have and get rid away with if-else block?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java (hunk 1 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:722]: I added this so that we can easily differentiate between file and git operations.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java (hunk 2 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:708]: For to use `changeViewAccess` we need to know the value of `isPublic` flag which will not be part of git/app json. Just like how we are not committing policies we should not commit the flag as well. Since they depend on each other and should use DB as source of truth.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java (hunk 1 above)
Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:722]: Can we please remove this to be consistent with other implementation?

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java [hunk 3]
```diff
@@ -792,6 +792,16 @@ public void makeApplicationPublic_applicationWithGitMetadata_success() {
...
 
+        // Create a branch
+        Application testApplication = new Application();
+        testApplication.setName("branch1");
+        testApplication.setOrganizationId(orgId);
+        GitApplicationMetadata gitApplicationMetadata = new GitApplicationMetadata();
+        gitApplicationMetadata.setDefaultApplicationId(gitConnectedApp.getId());
+        gitApplicationMetadata.setBranchName("test");
+        testApplication.setGitApplicationMetadata(gitApplicationMetadata);
+        Application application = applicationPageService.createApplication(testApplication).block();
```
Comment (abhvsn) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java:803]: I'm not sure if I get this correctly, what are we trying to test with this testcase?

Comment (AnaghHegde) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java:803]: This is ti check if the app is made public, all the branched application policy also needs to be updated. I am testing the same scenario.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java (hunk 1 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:721]: This else block makes it easy to read and differentiate the flow for file and git import.  Since the method is huge it would be good to have the else block in this scenario.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java [hunk 4]
```diff
@@ -266,9 +266,12 @@ public ApplicationServiceCEImpl(Scheduler scheduler,
     public Mono<Application> changeViewAccess(String defaultApplicationId,
                                               String branchName,
                                               ApplicationAccessDTO applicationAccessDTO) {
-        return this.findByBranchNameAndDefaultApplicationId(branchName, defaultApplicationId, MAKE_PUBLIC_APPLICATIONS)
+        // For git connected application update the policy for all the branch's
+        return findAllApplicationsByDefaultApplicationId(defaultApplicationId)
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:270]: Should we include this in git-docs that visibility will be applicable at repo level and not the branch level?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java (hunk 1 above)
Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java:721]: I still feel this should be consistent with other places where if we are returning from the if block no need to include else part, but yes this is not a blocker though

**Review by abhvsn — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java (hunk 4 above)
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:270]: It is intuitive right? Most of the users complained that it is not working correctly across branches. But there is no harm in adding this to doc.

Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:270]: Reason I asked is because we are sharing branches in git corresponds to app in appsmith. Also today app visibility is at app level that's why confusion might arise in some situations

**Review by abhvsn — DISMISSED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:270]: @trishaanand No we are passing the permission in the repository implementation for this method. If you look at the implementation of the method `getApplicationByGitDefaultApplicationId`, we are passing the policy while querying the db.

[the remark this answers is not in the document]
Comment (trishaanand) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:270]: But the permission used by the method `getApplicationByGitDefaultApplicationId` is actually `MANAGE_APPLICATIONS` instead of `MAKE_PUBLIC_APPLICATIONS`.

[the remark this answers is not in the document]
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:270]: I thought `MANAGE_APPLICATION` is a super set and `MAKE_PUBLIC_APPLICATIONS` is part of that.

[the remark this answers is not in the document]
Comment (trishaanand) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:270]: Today it is, but tomorrow, this would be controlled via RBAC with more granular access controls and this flow would break. It is easier to stick to the correct permissions at the application logic level.

[the remark this answers is not in the document]
Comment (AnaghHegde) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java:270]: Got it, thanks for highlighting this. I will change this.

**Review by trishaanand — APPROVED** [review]

**Comment by AnaghHegde** [comment]
@trishaanand @abhvsn Can you guys please approve the PR again? Just merge release into my branch.

**Review by abhvsn — APPROVED** [review]
