### PR TITLE
fix: Bug in evaluated value for falsy value checks

### LINKED ISSUE #7646: [Bug] Evaluated value shows 2 values on Google Sheets row offset field
## Description
Google sheets evaluated row is displayed in 2 rows for query that's created using generate page feature

### Steps to reproduce the behaviour:
1. Click on Generate page for Google sheets data source
2. Go to the generated query 'SelectQuery' and navigate to the Row Offset field
3. Observe the evaluated value for the field

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

image

### PR DESCRIPTION
**Pull request by hetunandu**
## Description

Falsy evaluated value would fail the if check and not render the copy button

fixes #7646

Screenshot 2021-10-05 at 1 44 03 PM

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>

    // Code coverage diff between base branch:release and head branch: fix/evaluated-value-bug 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.82 **(0)** | 36.82 **(-0.01)** | 33.9 **(0.01)** | 55.41 **(0)**
 :green_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 65.87 **(0.79)** | 57.5 **(1.25)** | 38.89 **(2.78)** | 66.36 **(0.91)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**</details>

### CODE REVIEW

**Review by arunvjn — APPROVED** [review]

File: app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx [hunk 1]
```diff
@@ -327,7 +327,7 @@ export const CurrentValueViewer = memo(
         <Collapse isOpen={openEvaluatedValue}>
           <CurrentValueWrapper colorTheme={props.theme}>
             {content}
-            {props.evaluatedValue && (
+            {"evaluatedValue" in props && (
```
Comment (arunvjn) [inline app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx:330]: Nit: "hasOwnProperty" is faster than "in" since it doesn't look into the prototype chain

**Review by arunvjn — APPROVED** [review]
