### PR TITLE
[Fix] create new api not working from saved google sheet state

### LINKED ISSUE #5680: [Bug] Google Sheet query creation is not working from saved state
## Description
From saved state of Google Sheet Datasource, user is unable to create a query. It fails with error - `Unable to create API. Try adding a URL to the datasource`

### Steps to reproduce the behaviour:
1. Create New Google Sheet Datasource
2. Create New Query and save it
3. Go to canvas
4. Click on Your Google Sheet Datasource
5. Click on `new api`

### Important Details
- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [release]

### LINKED ISSUE #5686: [Bug]-The API Icon is displayed instead of the respective database icon for the database query in the entity pane
## Description

[What happened]The API Icon is displayed instead of the respective database icon for the database query in the entity pane (happens mostly for old app)

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to the application page
2. open any of the old application which have the data sources connected
3. Now expand the entity page 
4. for few of the tables in the datasources are displayed with API icon instead of Database icon
image

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment release

### PR DESCRIPTION
**Pull request by pranavkanade**
## Description
Fixed the bug, by using action creator which does not require URL to be provided at start. For datasources of pluginType `API` added a fix to properly set action config.

Fixes #5680 
Fixes #5686 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: bug/new-api-not-working-google-sheet 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.89 **(-0.02)** | 35.79 **(-0.06)** | 32.55 **(0.01)** | 54.48 **(-0.01)**
 :green_circle: | app/client/src/pages/Editor/DataSourceEditor/Connected.tsx | 49.02 **(2.35)** | 11.11 **(0.58)** | 0 **(0)** | 50 **(2.54)**
 :red_circle: | app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx | 25.77 **(-0.14)** | 19.64 **(0)** | 2.94 **(0)** | 28.99 **(-0.18)**
 :red_circle: | app/client/src/pages/Editor/IntegrationEditor/ActiveDataSources.tsx | 44 **(-2.81)** | 17.14 **(-29.92)** | 9.09 **(0)** | 51.22 **(-4.04)**
 :red_circle: | app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx | 47.27 **(-5.79)** | 47.62 **(-2.38)** | 0 **(0)** | 50 **(-4.17)**
 :green_circle: | app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx | 34.34 **(0.32)** | 17.14 **(1.14)** | 6.25 **(0)** | 36.26 **(0.3)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/DataSourceEditor/Connected.tsx [hunk 1]
```diff
@@ -4,24 +4,18 @@ import { useParams } from "react-router";
 import { AppState } from "reducers";
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/DataSourceEditor/Connected.tsx:4]: Just checking if we're removing the handling for api actions here, since we've disabled the view mode for `api datasources`?

File: app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx [hunk 2]
```diff
@@ -146,7 +148,13 @@ function DatasourceCard(props: DatasourceCardProps) {
...
       );
     }
-  };
+  }, [datasource.id, params]);
+
+  const onCreateNewQuery = useCallback(() => {
+    setIsSelected(true);
+    const plugin = pluginGroups[datasource.pluginId];
+    props.onCreateQuery(datasource, plugin.type);
+  }, []);
```
Comment (rishabhsaxena) [inline app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx:157]: Just checking, should we add the dependencies here?

**Review by rishabhsaxena — CHANGES_REQUESTED** [review]
image
I think the `New Api` button is now missing?
Also should we redirect away from this page on save?

File: app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx (hunk 2 above)
Comment (pranavkanade) [reply app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx:157]: plugins are fetched once and do not change throughout the use. Moreover, datasources also don't change their plugins in their lifecycle. So, no dependencies needed.

File: app/client/src/pages/Editor/DataSourceEditor/Connected.tsx (hunk 1 above)
Comment (pranavkanade) [reply app/client/src/pages/Editor/DataSourceEditor/Connected.tsx]: modified the function to handle generic action creation, so that if in future we add new SAAS/API solutions, it'll work as it is

**Comment by pranavkanade** [comment]
> image
> I think the `New Api` button is now missing?
> Also should we redirect away from this page on save?

Re introduced the `New API` btn. (With text change to `New Query`)

**Review by rishabhsaxena — APPROVED** [review]

**Comment by pranavkanade** [comment]
unrelated test case failing.
