### PR TITLE
fix: 9824 Google Sheet to filter empty condition ver.2

### LINKED ISSUE #9824: [Bug]: Unable to filter by empty conditions in Google sheets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On trying to apply a where condition on Google sheets to search for an empty value, the plugin responds with an error.

### Steps To Reproduce

Create a `Fetch sheet rows` request with a condition like `"columnName" == [empty_value]`

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by leotom2000**
## Description
To fetch data from Google Sheet with empty where condition, ie with no entry in Where Conditions, value field
For example, user needs this implementation as he want to search a member with no emailId from the googlesheet database.

**Features/Scenarios implemented and Tested regarding the values in the condition:**
1. When Value is Empty ""    - Pass
2. When Value is Null     null  -  Pass
3. When Value is Space  " "   - Pass
4. When Two conditions are  "" -  Pass
5. When Two conditions are null - Pass
6. When one Condition is Null and other empty - Pass
7. When both has value    - Pass
8. When both condition are empty  - Pass
9. Test for EQ  with empty / Null /  with_value   - Pass
10. Test for 'IN' for with  empty / Null     - Pass
11. Test for 'NOT_IN'  with  empty / Null     - Pass
12. Test for combination of  EQ  /   IN   /  NOT_IN    - Pass

Note : The UI will sent null, when we do not touch the field (ie Mouse down/Click), at present it is handled in the backend by capturing the nulls.
We may need to fix that in the front end, for which I will create a ticket later.

Fixes #9824

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested with Single and Multiple conditions
- Unit Test Added

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java [hunk 1]
```diff
@@ -154,6 +154,59 @@ public void testFilterMultipleConditions() {
...
+
+            List<Condition> whereConditionList = new ArrayList<>();
+
+            Condition condition = new Condition("productName", "EQ", "");
+            whereConditionList.add(condition);
+
+            //Precondition for whereConditionList implemented in GetValuesMethod.isWhereConditionConfigured(..)
+            whereConditionList.stream()
+                    .filter(val -> val.getValue().equals("") && val.getOperator().name().equals("EQ"))
+                    .forEach(val -> val.setValue(" ")); // Setting null fails in null validation
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java:197]: Should this not be an empty string?

Comment (leotom2000) [reply app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java:197]: In appsmith-Interfaces module, Condition.java has a method isValid(Condition condition),
This evaluates for StringUtills.isEmpty and throws error.

So we are adding a Space to bypass that 
updated to StringUtills.Space  instead of " " now

Comment (nidhi-nair) [reply app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java:197]: Then the fix needs to be made for the empty check right? The end user would always have an empty string that they pass.

Comment (leotom2000) [reply app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java]: Resolved this issue as discussed with you

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java [hunk 2]
```diff
@@ -448,20 +447,32 @@ private String generateWhereClauseOldFormat(List<Condition> conditions, LinkedLi
...
+                }
+                isEmptyConditionValue = true;
+            } else {
+                sb.append(sqlOp);
+            }
             sb.append(" ");
 
             // These are array operations. Convert value into appropriate format and then append
-            if (operator == ConditionalOperator.IN || operator == ConditionalOperator.NOT_IN) {
+            if ((value != null || (value != null && !value.equals(StringUtils.EMPTY))) &&
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java:474]: There seems to be a redundant check here? Could you please confirm?

File: app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java [hunk 3]
```diff
@@ -154,6 +154,105 @@ public void testFilterMultipleConditions() {
...
+
+        try {
+            ArrayNode items = (ArrayNode) objectMapper.readTree(data);
+
+            List<Condition> whereConditionList = new ArrayList<>();
+
+            Condition condition1 = new Condition("orderStatus", "EQ", "READY");
+            whereConditionList.add(condition1);
+
+            Condition condition2 = new Condition("productName", "EQ", null); //The UI sends null when that field is untouched
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java:242]: Good job on this test case

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
@leotom2000 Please check the condition to add brackets for `IN` and `NOT IN`

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java (hunk 2 above)
Comment (leotom2000) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java:474]: Simplified the line of code
Anyhow the objective is, value should not be EMPTY or null

**Comment by leotom2000** [comment]
> @leotom2000 Please check the condition to add brackets for `IN` and `NOT IN`

The functionality taking array as inputs for IN and NOT IN remains unmodified and works fine except that it is validated for Empty and null which is taken care by the current implementation. All non null values remains the same and handled as earlier.


image
