### PR TITLE
fix: Remove Gsheets unauth method

### LINKED ISSUE #35523: [Bug]: cannot create gsheets datasource, blocked by google
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2024-08-07 at 18 06 53

### Steps To Reproduce

1. Add a new gsheets datasource
2. Select scope that is anything other than `Selected google sheets`
3. Save and authorise
4. Authorise a non-appsmith email domain
See the error.

### Public Sample App

_No response_

### Environment

Production

### Severity

Critical (Broken Production apps)

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rishabhrathod01**
## Description

This PR temporarily removes the unauthorised Google Sheets method to ensure users are only shown methods that would work and avoid causing confusion. 
- The feature flag wasn't used here as the form JSON config's method field does not support hidden fields using feature flag and we avoided writing a logic specifically to remove the field from JSON before sending it as once the other methods get authorised again, we won't need the feature flag again

Fixes #35523

## Automation

/test gsheet

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10789501829>
> Commit: 040643a4d4ed4f2467a0af5733f4015a92d74e26
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10789501829&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.GSheet`
> Spec:
> <hr>Tue, 10 Sep 2024 09:37:24 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Simplified authorization options for Google Sheets integration, now limited to read and write access for selected sheets only.

- **Bug Fixes**
	- Updated integration tests to reflect the removal of outdated Google Sheets permission options, ensuring tests align with current authorization constraints.

- **Tests**
	- Temporarily skipped multiple test suites related to Google Sheets functionality to streamline testing and focus on relevant tests.

### CODE REVIEW

**Review by sneha122 — APPROVED** [review]

File: app/client/cypress/e2e/Regression/ServerSide/QueryPane/GoogleSheets_spec.ts [hunk 1]
```diff
@@ -20,9 +20,10 @@ describe(
       dataSources.CreatePlugIn("Google Sheets");
       VerifyFunctionDropdown([
         "Read / Write / Delete | Selected google sheets",
-        "Read / Write / Delete | All google sheets",
-        "Read / Write | All google sheets",
-        "Read | All google sheets",
+        // Hiding below methods as they are not authorized at this state
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/Regression/ServerSide/QueryPane/GoogleSheets_spec.ts:23]: Why do we need this code?

**Review by sagar-qa007 — CHANGES_REQUESTED** [review]

File: app/client/cypress/e2e/Regression/ServerSide/QueryPane/GoogleSheets_spec.ts (hunk 1 above)
Comment (rishabhrathod01) [reply app/client/cypress/e2e/Regression/ServerSide/QueryPane/GoogleSheets_spec.ts:23]: @sagar-qa007 Once Google has authorised the methods currently blocked by it, we will restore them and test them. Currently, Google has unauthorized commented methods, so we are removing them to reduce user confusion.

Comment (rishabhrathod01) [reply app/client/cypress/e2e/Regression/ServerSide/QueryPane/GoogleSheets_spec.ts:23]: @sagar-qa007 Also, I request to use `requested-changes` only for cases when there is an actual change that is required instead of doubts like above as it blocks the PR until approved again by the same person.

Comment (sagar-qa007) [reply app/client/cypress/e2e/Regression/ServerSide/QueryPane/GoogleSheets_spec.ts:23]: Cool. Please run the test and update workflow result in comments.

File: app/client/cypress/e2e/GSheet/AllAccess_Spec.ts [hunk 2]
```diff
@@ -15,7 +15,7 @@ const workspaceName = "gsheet apps";
 const dataSourceName = "gsheet-all";
 let appName = "gsheet-app";
 let spreadSheetName = "test-sheet";
-describe(
+describe.skip(
```
Comment (sagar-qa007) [inline app/client/cypress/e2e/GSheet/AllAccess_Spec.ts:18]: @rishabhrathod01 Just for clarification, why we have skipped this test cases and did we given same information to QA team about it?

If we are adding this cases back in Cypress code base then please share details for it.

**Review by sagar-qa007 — CHANGES_REQUESTED** [review]

File: app/client/cypress/e2e/GSheet/AllAccess_Spec.ts (hunk 2 above)
Comment (rishabhrathod01) [reply app/client/cypress/e2e/GSheet/AllAccess_Spec.ts:18]: [link](https://theappsmith.slack.com/archives/C0134BAVDB4/p1725968553976509?thread_ts=1725967329.578669&cid=C0134BAVDB4) to message to inform QA team and explanation of why we skipped the test case.

**Review by NilanshBansal — APPROVED** [review]

**Review by sagar-qa007 — APPROVED** [review]
