### PR TITLE
chore: add mousemove listener to konva and bug fixes.

### LINKED ISSUE #28380: [Bug]: Unable to select widgets.
Issue:

1. MouseMove event listener on MainCanvas enables pointerEvents on WidgetName Canvas if mouse is hovering over a widget name component.
2. When pointerEvents are enabled, WidgetName canvas (Konva) consumes all subsequent mouse events and the original event listener on MainCanvas is never triggered.
3. This prevents selection of any widget.

### LINKED ISSUE #28415: [Task]: Remove unobserved position elements from redux store.
Presently, elements are being unobserved but not removed from the store. This is resulting enormous bloating of data and presence of ghost positions is causing issues with highlight calculations.

### PR DESCRIPTION
**Pull request by prsidhu**
## Description

Add ``mousemove`` event listener to WidgetName canvas. This allows the canvas to toggle its own pointerEvents back to ``none`` when the mouse is not hovering over a widget name component.

Additionally:
1. Removes highlights for empty ``AlignedWidgetRow``.
2. Fix layout preset for container widget. New layoutIDs are generated for every instance.
3. Add an action to remove unobserved elements from layout positions redux store.
4. Bottom padding of MainCanvas layout.

#### PR fixes following issue(s)
Fixes #28380 
Fixes #28415 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

## Testing

- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/layoutSystems/common/WidgetNamesCanvas/index.tsx [hunk 1]
```diff
@@ -157,6 +157,33 @@ const OverlayCanvasContainer = (props: { canvasWidth: number }) => {
...
+     */
+    if (pointerEvents === "auto") {
+      /**
+       * Add the same listener to the wrapper when pointerEvents are enabled.
+       */
+      wrapper.addEventListener("mousemove", mouseMoveHandler);
+    } else {
+      wrapper.removeEventListener("mousemove", mouseMoveHandler);
+    }
+  }, [wrapperRef?.current?.style?.pointerEvents]);
```
Comment (marks0351) [inline app/client/src/layoutSystems/common/WidgetNamesCanvas/index.tsx:185]: does setting ref as dependency work?

Comment (riodeuno) [reply app/client/src/layoutSystems/common/WidgetNamesCanvas/index.tsx:185]: @prsidhu This is the patch fix I added yesterday. Sorry, I didn't mention why I added this: 
https://github.com/appsmithorg/appsmith/pull/28238/commits/6f63881bd787fab5f9fc8b7cd62cd2474759db0c#r1371259016

I'll work on your PR, and update the branch.

Comment (riodeuno) [reply app/client/src/layoutSystems/common/WidgetNamesCanvas/index.tsx:185]: @prsidhu Is it better to keep adding and removing the listeners or to have the listener available for the lifecycle of the WidgetNameCanvas?

Basically, we do this: https://github.com/appsmithorg/appsmith/commit/6f63881bd787fab5f9fc8b7cd62cd2474759db0c#r1371259016
Or what you have in this PR?

Can I ask you to take a call and merge this PR?

Comment (prsidhu) [reply app/client/src/layoutSystems/common/WidgetNamesCanvas/index.tsx:185]: @riodeuno It would be better to have the listener always available. We can use your fix. Is it already available on the DP?

Comment (prsidhu) [reply app/client/src/layoutSystems/common/WidgetNamesCanvas/index.tsx:185]: okay, will do it.

Comment (riodeuno) [reply app/client/src/layoutSystems/common/WidgetNamesCanvas/index.tsx]: Thank you!

**Review by riodeuno — APPROVED** [review]
