### PR TITLE
fix: List v2 - First row not editable for page > 1 when server side rendered

### LINKED ISSUE #18621: Task: List v2 - First row not editable for page > 1 when server side rendered.
For a server side enabled List widget, the first item of each page is editable i.e the property pane can be accessed to edit the properties of the widgets.
This is not true for client side enabled where List where only the page 1 first item is enabled for editing.

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

- Makes the first row non-editable for pages > 1 in server side pagination
- Fixes the container widget not syncing with List widget widget on resize

Fixes #18621

## Type of change

> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts [hunk 1]
```diff
@@ -1194,15 +1195,21 @@ class MetaWidgetGenerator {
...
     if (typeof key === "number" || typeof key === "string") {
       return key.toString();
     }
-    const startIndex = this.getStartIndex();
-    const viewIndex = rowIndex - startIndex;
-    const data = this.getData()[viewIndex];
 
-    return hash(data, { algorithm: "md5" });
+    const data = this.getData()[dataIndex];
+    const dataToHash = data ?? rowIndex;
```
Comment (Tooluloope) [inline app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:1210]: Why are we hashing by rowIndex?

**Review by Tooluloope — CHANGES_REQUESTED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicServerSideData_spec.js [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+    id: "002",
+    name: "Green",
+    img: "https://assets.appsmith.com/widgets/default.png",
+  },
+  {
+    id: "003",
+    name: "Red",
+    img: "https://assets.appsmith.com/widgets/default.png",
+  },
+];
```
[the remark this answers is not in the document]
Comment (ashit-rath) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicServerSideData_spec.js:22]: I tried a bunch of things yesterday to mimic container resize in cypress but was unable to. I'll try out a few more things today and if it doesn't work then we'll to skip it.

File: app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts (hunk 1 above)
Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:1210]: I have seen instances where the data is `undefined` and it crashes the whole application. This will act as a safety net.

Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:1210]: @Tooluloope I tried a bunch of things and it seems there is a problem with the react-spring used internally and the mouse up event is not triggering with correct coordinates. Let's not explore more right now on adding cypress test as it may cause flakiness even if we somehow do it.

Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts:1209]: Got it,

**Review by Tooluloope — APPROVED** [review]
