### PR TITLE
fix: mongo uri lowercasing removed

### LINKED ISSUE #32145: [Bug]: Mongo Plugin: don't lowercase params in URI
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
MongoPlugin automatically lowercases the URI added by the user. 

https://github.com/appsmithorg/appsmith/assets/25542733/a717afb3-ff58-4a88-b182-f8289b9c42ef

[Slack Thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1711547237735119)

### Steps To Reproduce

[Slack Thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1711547237735119)

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

cloud, self hosted

### PR DESCRIPTION
**Pull request by NilanshBansal**
Fixes #32145

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!IMPORTANT]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8593895715>
> Commit: `aa366fdcfdcdbdcdddeebec4d14e0ca01b739014`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8593895715&attempt=1" target="_blank">Click here!</a>
> All cypress tests have passed 🎉🎉🎉

## Summary by CodeRabbit

- **Bug Fixes**
	- Fixed an issue with option processing by retaining the original case of keys, ensuring accurate data handling.

### CODE REVIEW

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/DatasourceUtils.java [hunk 1]
```diff
@@ -131,23 +132,34 @@ public static String buildURIFromExtractedInfo(Map extractedInfo, String passwor
     }
 
     private static String buildURITail(String tailInfo) {
-        Map<String, String> optionsMap = new HashMap<>();
+        // preserves order of keys, and hence the params ordering in the url remains unchanged
+        // here Treemap with case-insensitive order could not be used because that also changes the ordering of params
+        Map<String, String> optionsMap = new LinkedHashMap<>();
+        Map<String, String> lowercasedOptionsMap = new HashMap<>();
```
Comment (sharat87) [inline app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/DatasourceUtils.java:138]: Would the `LinkedCaseInsensitiveMap` serve better here instead of two maps? Sounds like exactly what we need here I think: https://www.baeldung.com/java-map-with-case-insensitive-keys#spring

shot-2024-04-08-02-31-14

**Review by sharat87 — COMMENTED** [review]
Minor suggestion for improvement, but solution looks good.

File: app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/DatasourceUtils.java (hunk 1 above)
Comment (NilanshBansal) [reply app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/DatasourceUtils.java:138]: Thanks for the suggestion @sharat87 !

**Review by sharat87 — APPROVED** [review]
