### PR TITLE
fix: Add migrations for all google sheet actions to turn off smart substitution for existing actions

### LINKED ISSUE #7513: [Bug] GSheets is returning a 500 on query run
## Description
GSheets is returning a 500 on query run due to NPE. More details on the link below
https://theappsmith.slack.com/archives/CGBPVEJ5C/p1631778191413700

### Steps to reproduce the behaviour:
1. Go to Google sheets data source and add a new query
2. Enter all details and click Run
3. Observe an "undefined" error on query run

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

### PR DESCRIPTION
**Pull request by trishaanand**
Fixes #7513

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java [hunk 1]
```diff
@@ -2993,4 +2993,55 @@ public void addJSPlugin(MongockTemplate mongoTemplate) {
...
+                toMigratePublishedActions.add(action.getId());
+            }
+        }
+
+        Property smartSubProperty = new Property("smartSubstitution", false);
+
+        // Migrate unpublished actions
+        mongoTemplate.updateMulti(
+                query(where("_id").in(toMigrateUnPublishedActions)),
+                new Update().set("unpublishedAction.actionConfiguration.pluginSpecifiedTemplates.13", smartSubProperty),
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java:3036]: Interesting, does Mongo also understand array indices as object references? Thought that was just a JS thing.

**Review by nidhi-nair — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java (hunk 1 above)
Comment (trishaanand) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java:3036]: Yup! And works perfectly! I was doing this in java for empty arrays and it seemed like too much handling. This is super :)

**Review by nidhi-nair — APPROVED** [review]

**Review by mohanarpit — APPROVED** [review]
