### PR TITLE
fix: 9648 The Update query fails to update for all matching Document in mongo 

### LINKED ISSUE #9648: [Bug]: The Update query fails to update for all matching Document in mongo
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user try to update all the matching document at once the update happens only for 1 data in the mongo database
[LOOM DEMO](https://www.loom.com/share/ad32bd8ae7484ac3aeeed9ca7f052eef)

### Steps To Reproduce

1. go to the database
2. add the mongo database
3.  Select the update query 
4. add the query in such a way that the user is trying to update 2 records with the same name
5. Now select the All matching documents in the limit dropdown 
6. Run the query 
7. The update happens for only 1 data

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by leotom2000**
## Description

The Update query fails to update for all matching Document in mongo 
 It works fine for single and fails for multiple records.
The issue is related to the Mongo version change syntax of handling multi records update.
Implemented the updates to fix the issue

Fixes #9648 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

> Manually verified by verifying the data in DB during development
> Unit Test cases was modified to take up the new change

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java [hunk 1]
```diff
@@ -1235,7 +1235,7 @@ public void testUpdateManyFormCommand() {
         setValueSafelyInFormData(configMap, COLLECTION, "users");
         // Query for all the documents in the collection
         setValueSafelyInFormData(configMap, UPDATE_QUERY, "{}");
-        setValueSafelyInFormData(configMap, UPDATE_OPERATION, "{ $set: { updatedByCommand: true }}}");
+        setValueSafelyInFormData(configMap, UPDATE_OPERATION, "{ updatedByCommand: true }}");
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:1238]: Are we changing how users need to enter data into the query here @leotom2000 ?

Comment (leotom2000) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:1238]: Yes, the syntax of update command needs $set attribute, this has been handled in the unit test earlier,
since we have implemented in the main code now, this became a duplicate in the generated query, so we have removed from here.

Comment (nidhi-nair) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:1238]: Will this not require users to change the way they write their actions? Could you please give an example of what the end user would end up using?

Comment (leotom2000) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:1238]: The below syntax will work, as $set is added in code,
 but if we need to consider other update options, we need to decide,
 I tested with the existing $inc, it is not working in this scenario even for single document.
 Will discuss before closing this issue


image

Comment (leotom2000) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java:1238]: If we may need to utilise other update operators also, we need to follow the below syntax.
update operators : ($currentDate, $inc, $min, $max, $mul, $rename, $set, $setOnInsert, $unset)


image

Comment (leotom2000) [reply app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java]: A change to one constants fixed this issue, the issue was it was not able to resolve whether the update is going to be multi or single. After the change to the constant it worked comparing the dynamic input.
The unit tests for single and multi updates were already handled. The new change did not affect Tests is because, the same variable was used in both places like the simulated input and in the place where it is used to evaluate if it is multi or single. so even after the code change (constant) it continues to work.

**Review by nidhi-nair — APPROVED** [review]
