### PR TITLE
fix: remove debounce from RTE component

### LINKED ISSUE #14045: [Bug]: RTE Widget's values are not getting reflected in the google sheet
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I am facing an issue with the feedback form that I created. The feedback form is simple, there are `3 RTEs inside a FORM widget`. The form is connect to a google sheet query. Please find attached the `json` export for the application.
 
**Expected behaviour is:** On click of the submit button, the data should get inserted into the google sheet.
**Observed behaviour is:** Sporadically, the data is not getting reflected into some columns of the google sheet on click of the submit button. Below is the screenshot of the google sheet for this behaviour.

Screenshot 2022-05-24 at 11 07 37 AM

Video:
[LOOM DEMO](https://www.loom.com/share/0409115e8a43488682242b1b9341c875)

Application JSON:
[application-json.txt](https://github.com/appsmithorg/appsmith/files/8973663/application-json.txt)

### Steps To Reproduce

1. Import the app via json given in the description.
2. Make sure to update the google sheet query with your own google sheet link.
3. Now try to enter the data into the RTE quickly and click on the `send feedback` button.
4. Observe that for some columns the value is not getting reflected.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Rishabh-Rathod**
## Description

Remove debounce from RTE component

It was noticed that `onEditorChange` was called also when RTE component was focused, unfocused ( cases where value was not changed, instead editor's value changes. ) in such cases, we don't want to call `onValueChange`. 
Hence, we added logic to only update value when we have an actual change in value.

Fixes following issues:
#14045
#7231 
#10419 
https://github.com/appsmithorg/appsmith/issues/14708
#14922 

This PR also fixes the issues that were caught during the development process:

* If Input type is markdown or html and when you cut the text inside the RTE widget then text re-appears (in this case default text is none). Here is the video that demonstrates this behaviour: 

https://user-images.githubusercontent.com/14138515/174781044-4ce4f760-1e3c-4f1b-a195-c876a0ddd797.mov

* The isDirty property of the widget was not working as expected. isDirty property was not getting set to false when the default text is changed. 
* ResetWidget functionality of the widget was not working properly. It was observed that for resetting the widget, `resetWidget` function was needed to be called twice. 
* isDirty was not setting to false for the last step in the following scenario: Update normal text(isDirt true) -> Update Default Text(isDirt false) -> Reset widget(isDirt false) ->. Update default Text(isDirt true)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

This PR adds the following cypress test cases into the file `RichTextEditor_spec.js`:

* Updated the`Check isDirty meta property` test case to check for the following scenario - `Update normal text -> isDirty True -> Update Default Text -> isDirty false -> Reset widget ->. Update default Text -> isDirty false`
* Check if the binding is getting removed from the text and the RTE widget Once the default text is cleared.
* Check if text does not re-appear when cut, inside the RTE widget
* Check if the cursor position is at the end for the RTE widget
* Check if different font size texts are supported inside the RTE widget

Following scenario needs to be tested manually: 
* When Input Type is Markdown - cursor jumps(Additional scenario for #7231 )
* The google sheet issue mentioned in the github issue #14045 needs to be tested manually.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/RTE-remove-debounce 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.71 **(0)** | 38.66 **(-0.01)** | 36.22 **(0)** | 56.96 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx [hunk 1]
```diff
@@ -91,41 +86,30 @@ export function RichtextEditorComponent(props: RichtextEditorComponentProps) {
...
-      setValue({ text: initValue, isUserEdit: true });
+    if (!initialRender.current && valueRef.current !== props.value) {
+      valueRef.current = props.value;
     } else {
-      /**
-       * due to lazy data load, props.value can trigger after initialization
-       * in that case this method called, so handle by comparing newValue and props.value
-       */
-      setValue({ text: newValue, isUserEdit: newValue !== props.value });
+      initialRender.current = false;
```
[the remark this answers is not in the document]
Comment (Rishabh-Rathod) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:112]: Added comment.

**Review by keyurparalkar — APPROVED** [review]
LGTM!

**Review by Tooluloope — CHANGES_REQUESTED** [review]
Some issues I noticed
https://user-images.githubusercontent.com/31691737/171059905-0f64b804-7ec5-4447-a8e2-f54c83c0e990.mov

**Comment by Rishabh-Rathod** [comment]
> Some issues I noticed https://user-images.githubusercontent.com/31691737/171059905-0f64b804-7ec5-4447-a8e2-f54c83c0e990.mov

Thanks for reviewing it @Tooluloope. Seems like checking for `props.value` is not correct approach here.

**Review by Rishabh-Rathod — COMMENTED** [review]
Changes look good to me. Can we add a test for Rich Text Editor for the issues we faced? 

Suggestion: We could add RichTextEditor in `AllInputsWidgets_spec.js` to easily add a cypress test for it.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RichTextEditor_spec.js [hunk 2]
```diff
@@ -140,14 +140,120 @@ describe("RichTextEditor Widget Functionality", function() {
     // Check if isDirty has been changed into false
     cy.get(".t--widget-textwidget").should("contain", "false");
     // Interact with UI
-    cy.setTinyMceContent("rte-6h8j08u7ea", "abc");
+    // cy.setTinyMceContent("rte-6h8j08u7ea", "abc");
```
Comment (Tooluloope) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RichTextEditor_spec.js:143]: Any reason why this was commented out.
If it's not needed we can remove it

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx [hunk 3]
```diff
@@ -73,14 +74,10 @@ export interface RichtextEditorComponentProps {
   labelTextSize?: TextSize;
   labelStyle?: string;
   isValid?: boolean;
+  isDirty: boolean;
```
Comment (Tooluloope) [inline app/client/src/widgets/RichTextEditorWidget/component/index.tsx:77]: Are you using this property in this component?

**Review by Tooluloope — CHANGES_REQUESTED** [review]

**Review by techbhavin — DISMISSED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RichTextEditor_spec.js (hunk 2 above)
Comment (keyurparalkar) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RichTextEditor_spec.js:143]: I have added a new way to update the text inside the RTE widget. Therefore, removing this comment.

File: app/client/src/widgets/RichTextEditorWidget/component/index.tsx (hunk 3 above)
Comment (keyurparalkar) [reply app/client/src/widgets/RichTextEditorWidget/component/index.tsx:77]: No, I have removed the `isDirty` and `defaultText` properties at the component level since they were not required

**Review by Tooluloope — APPROVED** [review]

**Review by Tooluloope — APPROVED** [review]

**Review by Rishabh-Rathod — COMMENTED** [review]
Changes won't be conflicting with https://github.com/appsmithorg/appsmith/pull/14468

**Comment by shadabbuchh** [comment]
Validated https://github.com/appsmithorg/appsmith/issues/14922 and moved it to `Done`.

**Comment by vivekverma2312** [comment]
@keyurparalkar Tested the RTE widget and looks good.
