### PR TITLE
fix: Removed on page load edges from layout model

### LINKED ISSUE #20680: [Bug]: Internal Server Error When Deploying App
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A cloud user gets an internal server error when trying to click the Deploy button for an app. Even if they try to fork it, they are not able to deploy the forked app.

Status 500:
`{"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Internal server error while processing request"}}}`

Furthermore the following errors can be seen in the console:
```
POST https://app.appsmith.com/api/v1/applications/publish/.....................................? 500 (Internal Server Error)
main.87faf633.js:2 Error: Internal server error while processing request
at main.87faf633.js:2:1040527
at d (main.87faf633.js:2:9046090)
at Generator._invoke (main.87faf633.js:2:9045843)
at [Generator.next](http://generator.next/) (main.87faf633.js:2:9046453)
at d (main.87faf633.js:2:1274405)
at c (main.87faf633.js:2:1274740)
at main.87faf633.js:2:1269349
at Mr (main.87faf633.js:2:1266908)
at zr (main.87faf633.js:2:1267114)
at Dr (main.87faf633.js:2:1266962)
at Jr.<computed> (main.87faf633.js:2:1269245)
at main.87faf633.js:2:1273998
at p (main.87faf633.js:2:1274959)
at d (main.87faf633.js:2:1274465)
at di (main.87faf633.js:2:1274198)
at main.87faf633.js:2:1273936
at p (main.87faf633.js:2:1274959)
at d (main.87faf633.js:2:1274465)
at c (main.87faf633.js:2:1274740)
```

### Steps To Reproduce

https://app.frontapp.com/open/cnv_wcyqpu4?key=Fzrrn5ZtStYcdXYJuFs8XGLn3t26klSU

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

Front logo [Front conversations](https://app.frontapp.com/open/top_7i0gc)

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description

Since an Appsmith application is not limited by the number of interconnections it can make, it is possible for users to create graphs so complex that we end up having MBs of data in a relatively simple page as well. This was causing failures in a user's app since they were now unable to update their app any further. We do not really use this property anywhere in our logic today, and this is essentially redundant information. This PR gets rid of the edges property from the layout and runs a migrations to clean up all existing pages as well. 

If we do find a need for this property in the future, a simple update layout on each of these pages would do the trick.

Fixes #20680 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Comment by sondermanish** [comment]
LGTM

**Review by sondermanish — DISMISSED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration004ResetOnPageLoadEdgesInLayouts.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+import io.mongock.api.annotations.Execution;
+import io.mongock.api.annotations.RollbackExecution;
+import org.springframework.data.mongodb.core.MongoTemplate;
+import org.springframework.data.mongodb.core.query.Query;
+import org.springframework.data.mongodb.core.query.Update;
+import org.springframework.data.mongodb.core.query.UpdateDefinition;
+
+
+@ChangeUnit(order = "004", id = "reset-on-page-load-edges-in-layouts")
+public class Migration004ResetOnPageLoadEdgesInLayouts {
```
Comment (subrata71) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration004ResetOnPageLoadEdgesInLayouts.java:14]: Can you please add a comment describing the need for writing this specific migration? This will help others understand the story behind it. @nidhi-nair
