### PR TITLE
Fix #1597: Add a signed issuer token to proxied requests, if configured

### LINKED ISSUE #1597: [Bug] Enhancement : The truncated page name must be displayed to user on hover
Steps to reproduce
1) Add a page 
2) Edit the page name to lengthy name 
and observe the entity explorer
3) Deploy the application 
and observe the page name tabs 

Observation:
It is observed that the user is unable to read the truncated page name when the name of the page is lengthy

Expectation:
truncated page name can be displayed to user on hover

### PR DESCRIPTION
**Pull request by sharat87**

### CODE REVIEW

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 1]
```diff
@@ -128,6 +133,38 @@ public RestApiPlugin(PluginWrapper wrapper) {
                 requestBodyAsString = convertPropertyListToReqBody(actionConfiguration.getBodyFormData());
             }
 
+            if (!CollectionUtils.isEmpty(datasourceConfiguration.getProperties())) {
+                boolean isSendSessionEnabled = false;
+                String secretKey = null;
+
+                for (Property property : datasourceConfiguration.getProperties()) {
+                    if ("isSendSessionEnabled".equals(property.getKey())) {
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:141]: Can we move this to a class level constant? Makes it easier to quickly scan the class and ensure there aren't typos.

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 2]
```diff
@@ -128,6 +133,38 @@ public RestApiPlugin(PluginWrapper wrapper) {
...
+
+                    final SecretKey key = Keys.hmacShaKeyFor(secretKey.getBytes(StandardCharsets.UTF_8));
+                    final Instant now = Instant.now();
+                    final String token = Jwts.builder()
+                            .setIssuer("Appsmith")
+                            .setIssuedAt(new Date(now.toEpochMilli()))
+                            .setExpiration(new Date(now.plusSeconds(600).toEpochMilli()))
+                            .signWith(key)
+                            .compact();
+                    webClientBuilder.defaultHeader("X-APPSMITH-AUTH", token);
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:165]: Suggestion: Can we rename the header key to `X-APPSMITH-SIGNATURE`? I'm asking this because we are no longer sending any auth information in the JSON body. This key makes it apparent that it's just a signature.

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java [hunk 3]
```diff
@@ -334,6 +373,24 @@ public void datasourceDestroy(Void connection) {
                 invalids.add("Invalid Content-Type: " + contentTypeError);
             }
 
+            if (!CollectionUtils.isEmpty(datasourceConfiguration.getProperties())) {
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:376]: This seems to be repeated between the execute & validateDatasource function. Can we move this to a private function so that it can be re-used?

File: app/server/appsmith-plugins/restApiPlugin/src/main/resources/form.json [hunk 4]
```diff
@@ -14,6 +14,47 @@
...
+        },
+        {
+          "label": "Send Authentication Information Key (Do not edit)",
+          "configProperty": "datasourceConfiguration.properties[0].key",
+          "controlType": "INPUT_TEXT",
+          "hidden": true,
+          "initialValue": "isSendSessionEnabled"
+        },
+        {
+          "label": "Send Authentication Information",
```
Comment (mohanarpit) [inline app/server/appsmith-plugins/restApiPlugin/src/main/resources/form.json:26]: Here as well. I suggest calling it a signature instead of authentication information
```suggestion
          "label": "Send Appsmith signature header (X-APPSMITH-SIGNATURE)",
```

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 2 above)
Comment (sharat87) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:165]: Yes, I intended to confirm this with you. Thank you. :)

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 3 above)
Comment (sharat87) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java:395]: Done

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java (hunk 1 above)
Comment (sharat87) [reply app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java]: Done

**Review by mohanarpit — APPROVED** [review]
