### PR TITLE
fix: order async functions in settings tab alphabetically

### LINKED ISSUE #13732: [Bug]: Async functions don't maintain any order in JS Editor settings tab
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Async functions don't maintain any order in JS Editor settings tab

### Steps To Reproduce

1. Create multiple Async functions in a JS Object
2. Run them
3. Observe that order is random in the settings tab for each run

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

This PR orders async functions alphabetically in the settings tab

Fixes #13732 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
**TestPlan**

- [ ] [[Test Case] : verify that multiple async functions can be added in JS object’s editor](https://github.com/appsmithorg/TestSmith/issues/1875) 
- [ ] [[Test Case] : Verify the order of async functions in Setting Tab of Js editor](https://github.com/appsmithorg/TestSmith/issues/1876)
- [ ] [[Test Case] : Verify that async functions can be execute](https://github.com/appsmithorg/TestSmith/issues/1877)

Cypress

- [x] Assert that number of async functions in settings tab corresponds to number of async function in js object
- [x] Assert that function settings remain in alphabetical order after running a function
- [x] Assert that function settings remain in alphabetical order after running multiple functions on pageload
- [x] https://github.com/appsmithorg/TestSmith/issues/1742
- [x] https://github.com/appsmithorg/TestSmith/issues/1743

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/order-async-settings-alphabetically 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.71 **(0)** | 38.65 **(-0.01)** | 36.22 **(0)** | 56.96 **(0)**
 :red_circle: | app/client/src/selectors/entitiesSelector.ts | 48.37 **(0)** | 11.3 **(-0.13)** | 23.95 **(0)** | 44.1 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

**Review by eco-monk — DISMISSED** [review]

File: app/client/src/selectors/entitiesSelector.ts [hunk 1]
```diff
@@ -792,7 +792,9 @@ export const getJSActions = (
     (jsCollectionData) => jsCollectionData.config.id === JSCollectionId,
   );
 
-  return jsCollection?.config.actions ?? [];
+  return jsCollection?.config.actions
```
Comment (rimildeyjsr) [inline app/client/src/selectors/entitiesSelector.ts:795]: Do we need to provide a fallback here for when `jsCollection` is not defined? or returning undefined is enough?

Comment (ohansFavour) [reply app/client/src/selectors/entitiesSelector.ts:795]: In line 797, we already have a fallback.   `jsCollection?.config.actions` is a conditional here.

Comment (rimildeyjsr) [reply app/client/src/selectors/entitiesSelector.ts:795]: Cool, approving!

**Review by rimildeyjsr — APPROVED** [review]
LGTM

**Review by Aishwarya-U-R — CHANGES_REQUESTED** [review]
Can the locators please be moved to JSEditor.ts as they are JSEditor specific locators? And there is already '_settingsTab' locator in the file that can be reused here also.

**Review by Aishwarya-U-R — CHANGES_REQUESTED** [review]
@ohansFavour - I see - in the test case - you are running only the last method once. But the issue can be seen only if more than one functions are invoked at a time. Hence please add scenarios for random methods with set OnPageLoad & Confirm before calling & then check if the order persists after running them on a page reload.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts [hunk 2]
```diff
@@ -75,4 +76,72 @@ describe("JS Function Execution", function() {
...
+    jsEditor.EnableDisableAsyncFuncSettings("getId", true, false);
+    jsEditor.EnableDisableAsyncFuncSettings("zip", true, false);
+    jsEditor.EnableDisableAsyncFuncSettings("base", true, false);
+
+    cy.reload();
+
+    // Switch to settings tab
+    agHelper.GetNClick(jsEditor._settingsTab);
+    // Assert that order remains the same
+    assertAsyncFunctionsOrder();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:145]: Can we repeat this section by enabling Confirmbefore run for different method combinations [eg, assert & zip], reload & confirm order once again?

Comment (ohansFavour) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:145]: @Aishwarya-U-R Does confirming before running functions in any way affect the order of function settings?. This seems like a redundant assertion.

Comment (ohansFavour) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:145]: @Aishwarya-U-R , I misunderstood your initial comment. Yes, this makes sense. Now done :white_check_mark:

**Review by Rishabh-Rathod — DISMISSED** [review]
Approving according to the previous review done.

**Comment by Rishabh-Rathod** [comment]
@ohansFavour  seems like we updated the cypress test. Does @Aishwarya-U-R  needs to re-review this?

**Comment by ohansFavour** [comment]
> @ohansFavour seems like we updated the cypress test. Does @Aishwarya-U-R need to re-review this?

Without her endorsement, the `test plan approved` label won't be added.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts [hunk 3]
```diff
@@ -166,4 +167,80 @@ describe("JS Function Execution", function() {
...
+
+    jsEditor.EnableDisableAsyncFuncSettings("assert", false, true);
+    jsEditor.EnableDisableAsyncFuncSettings("base", true, false);
+    jsEditor.EnableDisableAsyncFuncSettings("zip", false, true);
+    jsEditor.EnableDisableAsyncFuncSettings("getId", false, false);
+    cy.reload();
+
+    agHelper.GetNClick(jsEditor._settingsTab);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:243]: @ohansFavour - Hey sorry I missed to mention it clearly in my previous comment.. Can you please make a few methods - both true - OnpPageLoad + ConfirmBeforeRunning - then reload - handle the confirm popup's then navigate to settings tab & verify order..

I put a comment to handle the Confirm pop's after reload - but the  EnableDisableAsyncFuncSettings() method i gave wasn't complying to both setting to true.

So I expect ideally something like below:
jsEditor.EnableDisableAsyncFuncSettings("assert", **true**, true);
    jsEditor.EnableDisableAsyncFuncSettings("base", true, false);
    jsEditor.EnableDisableAsyncFuncSettings("zip", **true**, true);
    jsEditor.EnableDisableAsyncFuncSettings("getId", false, false);

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts:243]: Also instead of cy.reload - please use agHelper.RefreshPage() which waits a bit before proceeding since we have seen failures with cy.load, coz of it having a flickering effect & this method gives it some time to settle.

**Review by rimildeyjsr — DISMISSED** [review]

**Review by Aishwarya-U-R — DISMISSED** [review]

**Review by Aishwarya-U-R — APPROVED** [review]
