### PR TITLE
fix: update placeholder text for port numbers in datasource form 

### LINKED ISSUE #24960: [Bug]: Update faulty placeholder texts for port number in datasource forms
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Update faulty placeholder texts for port number in datasource forms.

### Steps To Reproduce

1. Create new datasource for MsSQL, Oracle, SMTP plugin and check that the placeholder text for port number is incorrect. 

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

cloud, self hosted

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Fix placeholder text for port numbers in datasource form for Oracle, MsSQL and SMTP plugins. 
- This PR has added Cypress test cases for the integrations that are being updated by this PR only (in the interest of time). Adding similar test cases for all other integrations is being tracked via [this](https://github.com/appsmithorg/appsmith/issues/25066) issue and will be taken up separately. 

#### PR fixes following issue(s)
Fixes #24960 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit 

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sneha122 — DISMISSED** [review]

File: app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+  let dsName: any;
+  it("1. Test MsSQL datasource port number placeholder", () => {
+    dataSources.NavigateToDSCreateNew();
+    agHelper.GenerateUUID();
+    cy.get("@guid").then((uid) => {
+      // using CreatePlugIn function instead of CreateDatasource,
+      // because I do not need to fill the datasource form and use the same default data
+      dataSources.CreatePlugIn("Microsoft SQL Server");
+      dsName = "MsSql" + uid;
+      agHelper.RenameWithInPane(dsName, false);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts:13]: Do we need to rename the DS - while we are only going to validate the port?

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts:13]: All renames can be removed.

File: app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+    });
+
+    const expectedPlaceholderValue = "1521";
+    agHelper.AssertAttribute(
+      dataSources._port,
+      "placeholder",
+      expectedPlaceholderValue,
+    );
+    dataSources.SaveDSFromDialog(false);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts:42]: Since only opening DS, asserting Port# & navigating back, all can be a single `it` too.

Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts:42]: Hi @Aishwarya-U-R IMO, keeping them in separate `it` would be helpful because if any of them fails then it would be easier to find which datasource has failed.

File: app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts (hunk 1 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts]: Hi Aishwarya, thanks for pointing this out. I have removed the renaming part.

File: app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts (hunk 2 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts:27]: Haha , we can still see from Cypress video.

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes!

File: app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts (hunk 2 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts]: Done.
