### PR TITLE
fix: file upload fixed when using Base64 type in FilePicker and multipart/form-data in REST API

### LINKED ISSUE #39227: [Bug]: [A-force] Can't upload pdf file using MULTIPART_FORM_DATA when the File Picker is set to return Base64
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When I have filepicker format selected as Base64, I cannot upload PDF file using Content type `multipart/form-data`

Image

### Steps To Reproduce

1. Drag a file picker to canvas, set file format to Base64
2. Create a new API with BaseRow upload file as URI, set all required headers and set body to MULTIPART_FORM_DATA with the following config.

Image

3. Run the API
4. Observe the REST API fails with the following error.

Image

### Public Sample App

_No response_

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

_No response_

### Version

Cloud - v1.50

### PR DESCRIPTION
**Pull request by NilanshBansal**
From the table [here](https://github.com/appsmithorg/appsmith/issues/39109#issuecomment-2655659006), this issue points to the 3rd one in the list. 

Fixes #39227 

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13392351852>
> Commit: c731c6515d4bba00ca3232b5309401d76471f184
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13392351852&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Sanity`
> Spec:
> <hr>Tue, 18 Feb 2025 14:36:12 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Enhanced multipart form data handling for file uploads, now supporting robust processing of base64-encoded content with options for custom filenames and MIME types.
  - Introduced specific error messages for invalid multipart data and base64 format issues.

- **Refactor**
  - Streamlined the data processing workflow with clearer error messages and simplified logic for improved reliability during file upload operations.

### CODE REVIEW

**Comment by NilanshBansal** [comment]
@sneha122 @appsmithorg/query-widgets-pod I have tested the file upload with the following types of files and it works fine. 
pdf [both large (>5MB) and small (<5MB) pdfs], mp3, jpeg, mp4, pptx, json, txt

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java [hunk 1]
```diff
@@ -300,37 +300,118 @@ public String parseFormData(List<Property> bodyFormData, Boolean encodeParamsTog
...
-                    outputMessage.bufferFactory(),
-                    4096);
-
-            bodyBuilder
-                    .asyncPart(key, data, DataBuffer.class)
-                    .filename(multipartFormDataDTO.getName())
-                    .contentType(MediaType.valueOf(multipartFormDataDTO.getType()));
-        });
+    // Helper method to map MIME types to file extensions
+    private String mimeTypeToExtension(String mimeType) {
```
Comment (sneha122) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java:404]: Is this getting used anywhere?

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java [hunk 2]
```diff
@@ -300,37 +300,118 @@ public String parseFormData(List<Property> bodyFormData, Boolean encodeParamsTog
...
+            ClientHttpRequest outputMessage,
+            String filename,
+            String mimeType) {
+        byte[] bytes = data.getBytes(StandardCharsets.ISO_8859_1);
+        addPartToBody(bodyBuilder, key, bytes, outputMessage, filename, mimeType);
+    }
+
+    // Extract MIME type from metadata
+    private String extractMimeType(String metadataPart, String defaultMimeType) {
+        if (metadataPart.startsWith("data:")) {
```
Comment (sneha122) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java:366]: Can we add a comment here explaining how the metadataPart looks like?

**Review by sneha122 — APPROVED** [review]

**Comment by sneha122** [comment]
@NilanshBansal Let's create a separate task and add test cases for this functionality as discussed

**Comment by nurd-os** [comment]
I have this error appearing recently may be 1-2 weeks ago. It was working fine before. I am using self hosted appsmith-ce:latest docker image. Somehow on my Mac works fine, however on remote server, it is giving error related to base64 encoding.

Steps to reproduce:
1. File picker choose any file, Base64 dataformat
2. Trigger upload to  REST API datasource
3. Error

Screenshot 2025-03-18 at 22 49 01

Screenshot 2025-03-18 at 22 51 02

**Comment by NilanshBansal** [comment]
Hey @nurd-os , when using `Base64` data format in the filepicker, you have to use `{{file.files[0].data}}` property in the REST API. Can you check if that works by updating the REST API to use `.data`?
