### PR TITLE
chore: consolidated API: update variable names, fix error propagation, handle defaults in case error

### LINKED ISSUE #29994: [Task]: Rename variables in ConsolidatedAPIResponseDTO.java
### SubTasks

- [ref](https://theappsmith.slack.com/archives/C024GUDM0LT/p1703658107495969?thread_ts=1703592506.794199&cid=C024GUDM0LT)

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Update variable names to make them more understandable
- Fix an error handling clause wherein the error was not caught at the right place. 
- Replace with defaults:
  - when workspace Id is not found then don't supply workspace Id to downstream sub-APIs (effectively passing null value which is handled via validation check in the sub-APIs).
  - when feature flag API errors out, then assign false value to migrate DSL flag
- This PR is targeted to be merged in development branch `oneApiChanges` instead of `release`  

#### PR fixes following issue(s)
Fixes #29994 #29995

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
- Chore (housekeeping or task changes that don't impact user perception)

- [x] Manual

>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java [hunk 1]
```diff
@@ -247,7 +247,14 @@ public Mono<ConsolidatedAPIResponseDTO> getConsolidatedInfoForPageLoad(
 
         /* Check if release_server_dsl_migrations_enabled flag is true for the user */
         Mono<Boolean> migrateDslMonoCache = featureFlagsForCurrentUserResponseDTOMonoCache
-                .map(ResponseDTO::getData)
+                .map(responseDTO -> {
+                    if (INTERNAL_SERVER_ERROR_STATUS
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java:251]: We seem to be silently consuming errors. Is that the expectation? How would we debug this state?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java [hunk 2]
```diff
@@ -61,6 +61,7 @@ public class ConsolidatedAPIServiceImpl implements ConsolidatedAPIService {
             "release_server_dsl_migrations_enabled";
     public static final int INTERNAL_SERVER_ERROR_STATUS = AppsmithError.INTERNAL_SERVER_ERROR.getHttpErrorCode();
     public static final String INTERNAL_SERVER_ERROR_CODE = AppsmithError.INTERNAL_SERVER_ERROR.getAppErrorCode();
+    public static final String EMPTY_WORKSPACE_ID_ON_ERROR = "";
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java:64]: @sumitsum For my knowledge, why did we have to introduce this error? In what scenario would the workspace ID be empty?

**Review by trishaanand — COMMENTED** [review]
Unsure of whats the expectation of error handling here. Otherwise refactor looks ok

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java (hunk 2 above)
Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java:64]: Hi @mohanarpit this is a value that is used to identify whether the code flow to fetch workspace id has failed (for any reason). This value is not supplied to the downstream APIs. It is instead used as an indicator of failure to fetch workspace id and hence not supplying the workspace id to downstream APIs. Example:
```
MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
if (!EMPTY_WORKSPACE_ID_ON_ERROR.equals(workspaceId)) {
    params.add(WORKSPACE_ID, workspaceId);
}
return datasourceService.getAllWithStorages(params).collectList();
```

The idea here is that the downstream Mono should return a validation error instead of the error that is returned from workspace id Mono. ([Slack thread](https://theappsmith.slack.com/archives/C024GUDM0LT/p1704355122219259?thread_ts=1703074675.245879&cid=C024GUDM0LT))

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java (hunk 1 above)
Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java:251]: Hi @trishaanand yes, this is done intentionally. This is discusse [here](https://theappsmith.slack.com/archives/C024GUDM0LT/p1704354835672119?thread_ts=1703074675.245879&cid=C024GUDM0LT).

**Review by rajatagrawal — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java (hunk 1 above)
Comment (rajatagrawal) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java:251]: As per my understanding,

This logic was present on client earlier. The logic was that if the migrateDSL feature flag was missing on client, the client wouldn't send the value of that feature flag. This logic has now moved to backend and the logic has been tried to be replicated here.

i.e if fetching the value of migrateDSL feature flag fails for some reason, empty value is passed to subsequent code flow, just like it would have happened earlier when client wouldn't have passed the value of this feature flag.
