### PR TITLE
fix: provide analytics data for graphql plugin

### LINKED ISSUE #12394: [Feature]: Graphql Tracking usage metric
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

_As a product manager, I should be able to see the percantage and number of apps that use GraphQL datasource, so that I can understand the success of this feature_

t[here](https://mixpanel.com/project/2032485/view/178891/app/insights#report/13034407/datasource-used-by-developers/~(columnWidths~(bar~())~description~%27~displayOptions~(chartType~%27pie~plotStyle~%27standard~analysis~%27linear~value~%27absolute)~sorting~(bar~(sortBy~%27column~colSortAttrs~(~(sortBy~%27value~sortOrder~%27desc)~(sortBy~%27value~sortOrder~%27desc)))~line~(sortBy~%27value~sortOrder~%27desc~valueField~%27averageValue~colSortAttrs~(~(sortBy~%27value~sortOrder~%27desc~valueField~%27averageValue)))~table~(sortBy~%27column~colSortAttrs~(~(sortBy~%27label~sortOrder~%27asc)~(sortBy~%27label~sortOrder~%27asc)))~insights-metric~(sortBy~%27value~sortOrder~%27desc~valueField~%27totalValue~colSortAttrs~(~))~pie~(sortBy~%27value~sortOrder~%27desc~valueField~%27totalValue~colSortAttrs~(~(sortBy~%27value~sortOrder~%27desc~valueField~%27totalValue))))~timeComparison~null~querySamplingEnabled~false~dashboard~(id~1160693~title~%27BE*20Coders*20Pod~creator_name~%27Nikhil*20Nandagopal~can_update_basic~true~can_share~true~allow_staff_override~false~is_superadmin~false)~title~%27Datasource*20used*20by*20developers~sections~(show~(~(dataset~%27!mixpanel~value~(name~%27execute_ACTION_TRIGGERED~resourceType~%27events)~resourceType~%27events~profileType~null~search~%27~dataGroupId~null~filter~(~(dataset~%27!mixpanel~value~%27datasource~resourceType~%27events~profileType~null~search~%27~dataGroupId~null~filterType~%27string~defaultType~%27string~filterOperator~%27does*20not*20equal~filterValue~(~%27*7b*22name*22*3a*22Fake*20Database*22*7d~%27*7b*22name*22*3a*22fakeApi*22*7d~%27*7b*22name*22*3a*22Mock*20API*22*7d~%27*7b*22name*22*3a*22Mock*20Database*22*7d~%27*7b*22name*22*3a*22Mock*20Db*22*7d~%27*7b*22name*22*3a*22Mock_Appsmith*22*7d~%27*7b*22name*22*3a*22Mock_Db*22*7d~%27*7b*22name*22*3a*22Mock*22*7d~%27*7b*22name*22*3a*22https*3a*2f*2fmock-api.appsmith.com*22*7d~%27*7b*22name*22*3a*22Appsmith*20Example*20Apps*22*7d~%27*7b*22name*22*3a*22https*3a*2f*2fappsmithhelp.freshdesk.com*22*7d~%27*7b*22name*22*3a*22https*3a*2f*2fapp.appsmith.com*22*7d~%27*7b*22name*22*3a*22Mock*20Mongo*22*7d~%27*7b*22name*22*3a*22MOVIES*20-*20Mock*22*7d~%27*7b*22name*22*3a*22USERS*20-*20Mock*22*7d~%27*7b*22name*22*3a*22Posgress*20Mock*20DB*22*7d~%27*7b*22name*22*3a*22Postgres*20Mock*20DB*22*7d~%27*7b*22name*22*3a*22Postgres*20mock*20db*22*7d~%27*7b*22name*22*3a*22Postgres_Mock_DB*22*7d~%27*7b*22name*22*3a*22Postgress*20Mock*20DB*22*7d~%27*7b*22name*22*3a*22Post*20Gres*20MOCK*20DB*22*7d~%27*7b*22name*22*3a*22Mock*20database*22*7d~%27*7b*22name*22*3a*22users*20*282*29*22*7d~%27*7b*22name*22*3a*22users*22*7d~%27*7b*22name*22*3a*22movies*22*7d~%27*7b*22name*22*3a*22Movies*22*7d)~propertyObjectKey~null~determiner~%27all)~(dataset~%27!mixpanel~value~%27appMode~resourceType~%27events~profileType~null~search~%27~dataGroupId~null~filterType~%27string~defaultType~%27string~filterOperator~%27equals~filterValue~(~%27edit)~propertyObjectKey~null))~math~%27unique~perUserAggregation~null~property~null~filterDeterminer~%27all))~group~(~(dataset~%27!mixpanel~value~%27pluginName~resourceType~%27events~profileType~null~search~%27~dataGroupId~null~propertyType~%27string~typeCast~null~unit~null))~filter~(clauses~(~(dataset~%27!mixpanel~value~%27!cohorts~resourceType~%27events~profileType~null~search~%27~dataGroupId~null~filterType~%27list~filterOperator~%27contains~filterValue~(~(cohort~(id~839025~name~%27Non*20Appsmith*20Cloud~negated~false))~(cohort~(id~972685~name~%27Non*20Appsmith*20CE~negated~false)))~propertyObjectKey~null))~determiner~%27all)~time~(~(dateRangeType~%27in*20the*20last~unit~%27day~window~(unit~%27day~value~30))))~legend~(individualSelectedSegments~(selected~(~(key~%27REST*20API)~(key~%27PostgreSQL)~(key~%27MongoDB)~(key~%27Mysql)~(key~%27Google*20Sheets)~(key~%27S3)~(key~%27MsSQL)~(key~%27Firestore)~(key~%27DynamoDB)~(key~%27Redshift)~(key~%27ElasticSearch)~(key~%27Snowflake))))~originDashboard~(id~1160693~title~%27BE*2520Coders*2520Pod))) should be an entry for GraphQL here

_As a product manager, I should be able to see the number of bugs reported on GraphQL feature, so that I can track the quality of the project_

### Why should this be worked on?

this is part of graphql v1 https://www.notion.so/appsmith/PRD-Native-GraphQL-Support-8b67d6c768a04be0a65597ecf79c5cfd

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Currently all the required data is already being sent. This PR introduces a minor change to rename the plugin name along the same lines as the REST API plugin since the current plugin name could be a bit misleading. 

Fixes #12394 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual via setting up a test segment account
- Automated test for this seems not possible at the moment.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java [hunk 1]
```diff
@@ -721,7 +721,7 @@ public void setDefaultApplicationVersion(MongockTemplate mongockTemplate) {
     @ChangeSet(order = "023", id = "add-graphql-plugin", author = "")
     public void addGraphQLPlugin(MongockTemplate mongoTemplate) {
         Plugin plugin = new Plugin();
-        plugin.setName("Authenticated GraphQL API");
+        plugin.setName("GraphQL API");
         plugin.setType(PluginType.API);
         plugin.setPackageName("graphql-plugin");
         plugin.setUiComponent("GraphQLEditorForm"); // TODO: make it ApiEditorForm -> GraphQLEditorForm
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java:727]: Nit: this todo is complete now, yes?

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Requested a small unrelated change

File: app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java (hunk 1 above)
Comment (sumitsum) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java]: Thanks for pointing this out. I have removed the comment.

**Review by nidhi-nair — APPROVED** [review]
