### PR TITLE
fix: catch block not working in firefox and safari for async functions

### LINKED ISSUE #15372: [Bug]: Catch block not executing in async function in Firefox/Safari
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The catch block was only getting triggered in chrome, not safari/firefox

### Steps To Reproduce

https://discord.com/channels/725602949748752515/760761686549463060/999336741326569554

### Public Sample App

_No response_

### Version

1.6.6

### PR DESCRIPTION
**Pull request by rimildeyjsr**
## Description

The catch block was not working for an async function in safari/firefox. On further debugging we found that different browsers were sending different call stacks to the response payload, making it fail on firefox and safari. We are only extracting the error message now to keep it consistent across browsers.

Screen recording (firefox) - 

https://user-images.githubusercontent.com/10229595/180390210-bb578a5a-f930-4dbe-aaff-6fafbd536dd9.mov

Fixes #15372 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- [ ] https://github.com/appsmithorg/TestSmith/issues/2011

- Cypress tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import { ObjectsRegistry } from "../../../../support/Objects/Registry";
+
+let jsEditor = ObjectsRegistry.JSEditor;
+
+describe("[Bug]: Catch block was not triggering in Safari/firefox", () => {
+  it("1. Triggers the catch block when the API hits a 404", () => {
+    cy.NavigateToAPI_Panel();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.js:7]: @rimildeyjsr Consider writing test scripts in Ts. Approving cypress script now.

**Review by Rishabh-Rathod — COMMENTED** [review]
Can we please check cypress test failures here, doesn’t seem like a flaky test failures.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.js (hunk 1 above)
Comment (rimildeyjsr) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.js]: done

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts [hunk 2]
```diff
@@ -21,8 +24,6 @@ describe("[Bug]: Catch block was not triggering in Safari/firefox", () => {
         shouldCreateNewJSObj: true,
       },
     );
-
-    cy.validateToastMessage("fun ran successfully");
-    cy.validateToastMessage("404 hit");
+    agHelper.WaitUntilToastDisappear("404 hit");
```
Comment (Aishwarya-U-R) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts:27]: I think this line should be "    agHelper.WaitUntilToastDisappear("404 hit", 1, 2);" -1 is the index of 404 hit toast & 2 is total length of toasts.. since I assume here 'fun ran successfully' toast also will appear.

Comment (Aishwarya-U-R) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts:27]: Oh, I see this case has passed. Above comment can be ignored.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+describe("[Bug]: Catch block was not triggering in Safari/firefox", () => {
+  it("1. Triggers the catch block when the API hits a 404", () => {
+    apiPage.CreateAndFillApi("https://swapi.dev/api/people/18261826", "Api1");
+    cy.wait(3000);
+
+    jsEditor.CreateJSObject(
+      `export default {
+      fun: async () => {
+        return await Api1.run().catch(() => showAlert("404 hit"));
```
Comment (Rishabh-Rathod) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts:17]: nit: Can we please add usage of `error.message` in the cypress test to make sure this works as expected.

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress looks good!

**Review by ApekshaBhosale — APPROVED** [review]

File: app/client/src/sagas/EvaluationsSaga.ts [hunk 4]
```diff
@@ -336,7 +336,7 @@ function* executeTriggerRequestSaga(
     // a success: false is sent to reject the promise
 
     // @ts-expect-error: reason is of type string
-    responsePayload.data.reason = error;
+    responsePayload.data.reason = new Error(error.message);
```
Comment (Rishabh-Rathod) [inline app/client/src/sagas/EvaluationsSaga.ts:339]: nit: Can we fix the type of ResponsePayload too? 
`reason?: string;`

Maybe below article might help: https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript

**Review by Rishabh-Rathod — DISMISSED** [review]
LGTM. 

few nitpicks mentioned below

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts (hunk 3 above)
Comment (rimildeyjsr) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts:17]: @Rishabh-Rathod - any suggestions on how to do this? this bug was just that in firefox/safari catch block did not execute, so that's what I covered in the tests

File: app/client/src/sagas/EvaluationsSaga.ts (hunk 4 above)
Comment (rimildeyjsr) [reply app/client/src/sagas/EvaluationsSaga.ts:339]: done

Comment (Rishabh-Rathod) [reply app/client/src/sagas/EvaluationsSaga.ts]: Ideally `if(error instanceof Error)` should always be `true` but still for sanity can we add else case with `responsePayload.data.reason = new Error("unknown error");` and let's move `responsePayload.success = false;` above if else to always make it false.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts (hunk 3 above)
Comment (Rishabh-Rathod) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts:17]: I meant that we can modify above test js code to `.catch((e) => showAlert("404 hit:"+e.message))` to verify if `e.message` is working as expected with this change too.

File: app/client/src/sagas/EvaluationsSaga.ts (hunk 4 above)
Comment (rimildeyjsr) [reply app/client/src/sagas/EvaluationsSaga.ts]: done

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts (hunk 3 above)
Comment (rimildeyjsr) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts]: makes sense, done

**Review by Rishabh-Rathod — DISMISSED** [review]
Code LGTM

**Review by Rishabh-Rathod — APPROVED** [review]
Code Looks good.

All test are passing in CI.

**Comment by AnandiKulkarni** [comment]
Catch block is not working for Safari browser
- Recoding 
- chrome -

https://user-images.githubusercontent.com/80756091/184296504-8210cf03-ee12-4d26-a725-f4d427afec2c.mov

Safari -

https://user-images.githubusercontent.com/80756091/184296534-8ec51cc9-fd46-4c89-9950-c72a6b876c09.mov

**Comment by AnandiKulkarni** [comment]
@rimildeyjsr 
Firefox is not working

https://user-images.githubusercontent.com/80756091/185040699-716b9e2d-c34c-4845-b90a-2e0d6a0c72a3.mov

**Comment by AnandiKulkarni** [comment]
@rimildeyjsr verified on safari and Firefox -
working fine

https://user-images.githubusercontent.com/80756091/185364606-abe45e07-30d6-464a-8cc2-76292c987e83.mov


https://user-images.githubusercontent.com/80756091/185364753-863a1bd7-a102-4366-beda-e7601c54df71.mov

**Review by Rishabh-Rathod — APPROVED** [review]
LGTM
