### PR TITLE
fix: Add current index property to min max fields

### LINKED ISSUE #20231: [Feature]: currentRow accessible in Min/Max/RegExpression fields of table column
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

currentRow should be accessible everywhere on a table.  It is not accessible in the min, max, and regex fields of an editable column.  It accessible in the valid field, so this is not an urgent issue, but it is confusing for new users to see a field on a table and not be able to use currentRow on it.

### Why should this be worked on?

Improve consistency.

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #20231 

- It is a new feature (non-breaking change which adds functionality)

This pull request adds support for currentIndex/currentRow properties for editable columns in a table widget. This property has been specifically added for min/max/regex/Error Message/Required properties of a column.

This change has been made to achieve consistency in the implementation and API of a table widget column for various properties that it has.

This pull request has a migration which has been unit tested by me. Cypress tests for the feature have also been added.

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [x] Test plan has been approved by relevant developers
- [x] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

Testing Plan - by developer

1. Make a column editable.
2. Check `currentIndex` and `currentRow` are available for checking validations in min/max/errorMessage/regex/required fields.
3. Since this PR also involves a migration, please check existing values in min/max/errorMessage/regex/required fields don't break after migration. Existing values in validations can include validations values of type string, boolean and other data type possible, like `{currentIndex == 1}`

### CODE REVIEW

File: app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx [hunk 1]
```diff
@@ -77,14 +81,23 @@ export function InputText(props: InputTextProp) {
...
+      ${tableId}.isAddRowInProgress,
+      ${tableId}.isAddRowInProgress ? -1 : ${tableId}.editableCell.index,
+      ${tableId}.isAddRowInProgress ? ${tableId}.newRow : (${tableId}.processedTableData[${tableId}.editableCell.index] ||
+        Object.keys(${tableId}.processedTableData[0])
+          .filter(key => ["${ORIGINAL_INDEX_KEY}", "${PRIMARY_COLUMN_KEY_VALUE}"].indexOf(key) === -1)
+          .reduce((prev, curr) => {
+            prev[curr] = "";
+            return prev;
+          }, {})),
+      ${tableId}.isAddRowInProgress ? -1 : ${tableId}.editableCell.index
```
Comment (sbalaji1192) [inline app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx:100]: we don't need this argument. IIFE receives only three params.

File: app/client/src/utils/migrations/TableWidget.ts [hunk 2]
```diff
@@ -738,3 +742,65 @@ export const migrateTableSelectOptionAttributesForNewRow = (
...
+
+      const oldBindingSuffix = `))(${tableId}.isAddRowInProgress)}}`;
+      const newBindingSuffix = `
+      ))
+      (
+        ${tableId}.isAddRowInProgress,
+        ${tableId}.isAddRowInProgress ? -1 : ${tableId}.editableCell.index,
+        ${tableId}.isAddRowInProgress ? ${tableId}.newRow : (${tableId}.processedTableData[${tableId}.editableCell.index] ||
+          Object.keys(${tableId}.processedTableData[0])
+            .filter(key => ["${ORIGINAL_INDEX_KEY}", "${PRIMARY_COLUMN_KEY_VALUE}"].indexOf(key) === -1)
```
Comment (sbalaji1192) [inline app/client/src/utils/migrations/TableWidget.ts:767]: Never use exported const in the migration code (ORIGINAL_INDEX_KEY and PRIMARY_COLUMN_KEY_VALUE). These exported values tend to change over time and it will affect the migrations. Always use literal values.

File: app/client/src/utils/migrations/TableWidget.ts [hunk 3]
```diff
@@ -738,3 +742,65 @@ export const migrateTableSelectOptionAttributesForNewRow = (
     }
   });
 };
+
+export const migrateBindingPrefixSuffixForInlineEditValidationControl = (
+  currentDSL: DSLWidget,
+) => {
+  return traverseDSLAndMigrate(currentDSL, (widget: WidgetProps) => {
+    if (widget.type == "TABLE_WIDGET_V2") {
```
Comment (sbalaji1192) [inline app/client/src/utils/migrations/TableWidget.ts:750]: prefer strict equal over equality operator.

File: app/client/src/utils/migrations/TableWidget.ts [hunk 4]
```diff
@@ -738,3 +742,65 @@ export const migrateTableSelectOptionAttributesForNewRow = (
...
+    `;
+      const applicableValidationNames = [
+        "min",
+        "max",
+        "regex",
+        "errorMessage",
+        "isColumnEditableCellRequired",
+      ];
+      const primaryColumns = widget?.primaryColumns as ColumnPropertiesV2;
+      Object.values(primaryColumns).forEach((column) => {
```
Comment (sbalaji1192) [inline app/client/src/utils/migrations/TableWidget.ts:783]: leave a line of space here.

File: app/client/src/utils/migrations/TableWidget.ts [hunk 5]
```diff
@@ -738,3 +742,65 @@ export const migrateTableSelectOptionAttributesForNewRow = (
...
+        if (column.hasOwnProperty("validation")) {
+          const validations = column.validation;
+          for (const validationName in validations) {
+            if (applicableValidationNames.indexOf(validationName) == -1) {
+              continue;
+            }
+            const validationValue = validations[validationName];
+            let compressedValidationValue = validationValue.replace(/\s/g, "");
+            compressedValidationValue = compressedValidationValue.replaceAll(
```
Comment (sbalaji1192) [inline app/client/src/utils/migrations/TableWidget.ts:792]: replace should be fine.

File: app/client/src/utils/migrations/TableWidget.ts [hunk 6]
```diff
@@ -738,3 +742,65 @@ export const migrateTableSelectOptionAttributesForNewRow = (
...
+              oldBindingPrefix,
+              newBindingPrefix,
+            );
+            compressedValidationValue = compressedValidationValue.replaceAll(
+              oldBindingSuffix,
+              newBindingSuffix,
+            );
+            validations[validationName] = compressedValidationValue;
```
Comment (sbalaji1192) [inline app/client/src/utils/migrations/TableWidget.ts:800]: Please ask QA to test this migration

File: app/client/src/utils/DSLMigrationsUtils.test.ts [hunk 7]
```diff
@@ -3095,4 +3096,115 @@ describe("correctly migrate dsl", () => {
...
+            },
+          },
+        },
+      ],
+    };
+    const nextDSL = transformDSL(currentDSL);
+
+    const validations = (nextDSL.children || [])[0].primaryColumns.column1
+      .validation;
+    console.log("new validations are ", validations);
```
Comment (sbalaji1192) [inline app/client/src/utils/DSLMigrationsUtils.test.ts:3179]: remove console.log

File: app/client/src/utils/DSLMigrationsUtils.test.ts [hunk 8]
```diff
@@ -3095,4 +3096,115 @@ describe("correctly migrate dsl", () => {
...
+
+    for (const validationName in validations) {
```
Comment (sbalaji1192) [inline app/client/src/utils/DSLMigrationsUtils.test.ts:3181]: we don't need to expect this. Just create a updated `currentDSL` with the expected value and check if that gets returned from the migration

File: app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_PropertyPane_spec.js [hunk 9]
```diff
@@ -372,4 +372,38 @@ describe("Table Widget V2 property pane feature validation", function () {
...
+    cy.get(".t--evaluatedPopup-error").should("not.exist");
+
+    // Update cell with row : 0, column : orderAmount. The min is set to 231224 (i.e value of cell in id column)
+    cy.editTableCell(4, 0);
+    cy.enterTableCellValue(4, 0, 231225);
+    cy.get(".t--evaluatedPopup-error").should("not.exist");
+    cy.enterTableCellValue(4, 0, 231223);
+    cy.get(".bp3-popover-content").contains("Invalid input");
+    cy.enterTableCellValue(4, 0, 231225);
+    cy.get(".t--evaluatedPopup-error").should("not.exist");
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_PropertyPane_spec.js:407]: we should also test the regex, isColumnEdtiableCellValid as well

File: app/client/src/utils/DSLMigrationsUtils.test.ts (hunk 7 above)
Comment (rajatagrawal) [reply app/client/src/utils/DSLMigrationsUtils.test.ts:3179]: Done

File: app/client/src/utils/migrations/TableWidget.ts (hunk 5 above)
Comment (rajatagrawal) [reply app/client/src/utils/migrations/TableWidget.ts:796]: Done

File: app/client/src/utils/migrations/TableWidget.ts (hunk 4 above)
Comment (rajatagrawal) [reply app/client/src/utils/migrations/TableWidget.ts:783]: Done

File: app/client/src/utils/migrations/TableWidget.ts (hunk 3 above)
Comment (rajatagrawal) [reply app/client/src/utils/migrations/TableWidget.ts:750]: Done

File: app/client/src/utils/DSLMigrationsUtils.test.ts (hunk 8 above)
Comment (rajatagrawal) [reply app/client/src/utils/DSLMigrationsUtils.test.ts:3181]: It might be hard to replicate the exact whitespaces(tabs, spaces) in the new suffix substiution in the new DSL, so I came up with this approach.

File: app/client/src/utils/migrations/TableWidget.ts (hunk 6 above)
Comment (rajatagrawal) [reply app/client/src/utils/migrations/TableWidget.ts:804]: @chandannkumar

File: app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx (hunk 1 above)
Comment (rajatagrawal) [reply app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx:100]: Done

**Review by sbalaji1192 — APPROVED** [review]

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested all js fields
- Sanity on Table widget all columns
- Tested migration scenarios
- Tested with older apps

**Review by sbalaji1192 — APPROVED** [review]

**Review by sbalaji1192 — APPROVED** [review]
