### PR TITLE
Fix action field evaluation for editor

### LINKED ISSUE #3279: Evaluated value doesn't update when switching prepared statements on/off

### PR DESCRIPTION
**Pull request by hetunandu**
## Description
After adding `bindingPaths` concept in the evaluation, we had patched fix the action editor evaluation by some default `bindingPaths` but that was replacing some evaluations because of parent evals.

This PR introduces the `bindingPaths` of actions by reading the editor Configs the plugin provides. Incase there is not config, we will default to some local configs.

As part of this, did some cleanup:
- Moved existing config code by ensuring they all get fetched during initialization
- Moved action settings config in a constants file and store them with other configs instead of injecting directly in a form
- Abstracted and tested parts of DataTreeFactory
- Deleted any unused mock responses

Fixes #3279

### CODE REVIEW

**Comment by trishaanand** [comment]
Approving to get the cypress tests running.

**Review by trishaanand — DISMISSED** [review]

**Review by trishaanand — APPROVED** [review]

**Comment by trishaanand** [comment]
Approved for running cy tests.

**Comment by trishaanand** [comment]
Approving for cy tests.

**Review by trishaanand — DISMISSED** [review]

**Review by trishaanand — APPROVED** [review]

File: app/client/src/sagas/ActionSagas.ts [hunk 1]
```diff
@@ -90,30 +89,11 @@ export function* createActionSaga(
   try {
     let payload = actionPayload.payload;
     if (actionPayload.payload.pluginId) {
-      let editorConfig;
-      editorConfig = yield select(
+      const editorConfig = yield select(
```
Comment (rishabhsaxena) [inline app/client/src/sagas/ActionSagas.ts:92]: Just checking we don't need to call `checkAndGetPluginFormConfigsSaga ` here?

File: app/client/src/entities/DataTree/dataTreeWidget.ts [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+    const propertyValue = _.get(widget, propertyPath);
+    if (_.isObject(propertyValue)) {
+      // Stringify this because composite controls may have bindings in the sub controls
+      _.set(widget, propertyPath, JSON.stringify(propertyValue));
+    }
+  });
+  Object.keys(derivedPropertyMap).forEach((propertyName) => {
+    // TODO regex is too greedy
+    derivedProps[propertyName] = derivedPropertyMap[propertyName].replace(
+      /this./g,
```
Comment (rishabhsaxena) [inline app/client/src/entities/DataTree/dataTreeWidget.ts:47]: Should this be`/^this./g`? not perfect with regexes or this specific case

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/sagas/ActionSagas.ts (hunk 1 above)
Comment (hetunandu) [reply app/client/src/sagas/ActionSagas.ts:92]: We don't need to do that here because we are already calling it when creating a new datasource. Only place where new datasource would not be called before new action is API and I call that over there

File: app/client/src/entities/DataTree/dataTreeWidget.ts (hunk 2 above)
Comment (hetunandu) [reply app/client/src/entities/DataTree/dataTreeWidget.ts:47]: We do need to work on this. Today I am just abstracting this into a new function but will tackle this at a later date. It works as expected today.

File: app/client/src/entities/DataTree/dataTreeWidget.ts [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+      `${widget.widgetName}.`,
+    );
+    dynamicBindingPathList.push({
+      key: propertyName,
+    });
```
Comment (rishabhrathod01) [inline app/client/src/entities/DataTree/dataTreeWidget.ts:52]: Why was a derived property added to `dynamicBindingPathList`?  

By the definition, dynamic binding is a binding that changes whereas derived property binding remains constant throughout all the flows.
