### PR TITLE
fix: make the row click event trigger when table button is clicked

### LINKED ISSUE #7838: [Bug]In the table widget the first row data is deleted by default if the user performs delete action without selecting the row
## Description In the table widget the first row data is deleted by default if the user performs delete action without selecting the row 

[What happened]In the crud page the user should select the row before performing the delete functionality else the first row is deleted by default

### Steps to reproduce the behavior:

[LOOM DEMO](https://www.loom.com/share/319156d2968b49d097286f431f91cc74)

### Important Details

- Version: [Cloud ]
- OS: macOS
- Browser chrome
- Environment release

### PR DESCRIPTION
**Pull request by aswathkk**
## Description

makes the click event on the button propagate to the row so that the event handler for the row gets triggered.

Fixes #7838 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

tested manually.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/table-widget-button-issue 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.83 **(0)** | 36.98 **(0)** | 33.81 **(-0.01)** | 55.44 **(-0.01)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**
 :red_circle: | app/client/src/widgets/TableWidget/component/TableUtilities.tsx | 40.56 **(-0.57)** | 23.3 **(-0.46)** | 16.22 **(-0.45)** | 39.23 **(-0.61)**
 :red_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 26.6 **(-0.27)** | 5.79 **(-0.07)** | 26.92 **(0)** | 26.34 **(-0.29)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@riodeuno @aswathkk vicky is now looking at the change to be made here, He will continue on the same branch and let us know as soon as he is done. Kindly review this once ready

**Review by riodeuno — DISMISSED** [review]

**Comment by riodeuno** [comment]
@vicky-primathon Converting to multi select table crashes the widge
Screenshot 2021-09-28 at 11 26 10 AM
t.

**Review by riodeuno — APPROVED** [review]

**Comment by RakshaKShetty** [comment]
@vicky-primathon @riodeuno The delete button issue is fixed.
issue 1:  the table crash when I enable multi-row select toggle
issue 2:  the delete button appears first then it moves at the end of the table. there is a flicker in table

File: app/client/src/widgets/TableWidget/widget/index.tsx [hunk 1]
```diff
@@ -240,10 +240,13 @@ class TableWidget extends BaseWidget<TableWidgetProps, WidgetState> {
             columnProperties,
             originalIndex,
           );
-
           if (columnProperties.columnType === "button") {
+            const isSelected = this.props.multiRowSelection
+              ? this.props.selectedRowIndices &&
```
Comment (riodeuno) [inline app/client/src/widgets/TableWidget/widget/index.tsx:245]: Can we just do this.
`if(this.props.multiRowSelection) { return Array.isArray(this.props.selectedRowIndices) && this.props.selectedRowIndices.includes(rowIndex) } else { return this.props.selectedRowIndex === rowIndex }`

**Review by riodeuno — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/TableWidget/widget/index.tsx (hunk 1 above)
Comment (riodeuno) [reply app/client/src/widgets/TableWidget/widget/index.tsx:245]: The problem is that we're getting `undefined` instead of `true|false` in a particular scenario here. Let's fix this.

**Comment by vicky-primathon** [comment]
> the delete button appears first then it moves at the end of the table. there is a flicker in table

@RakshaKShetty,  I am not able to understand 2nd issue. Can you please share a loom video for the 2nd issue.

**Review by riodeuno — APPROVED** [review]

**Comment by RakshaKShetty** [comment]
[Bug] onRowSelected getting triggered onRowAction #2313 we see this issue introduced again

**Comment by riodeuno** [comment]
> [Bug] onRowSelected getting triggered onRowAction #2313 we see this issue introduced again

@RakshaKShetty This is intentional. We're reverting this feature, where onRowAction and onRowSelection fire at the same time, when clicking a button on a particular row.

**Comment by RakshaKShetty** [comment]
@riodeuno, when the user enables a multi-select toggle and tries to delete the delete query fails. this issue is present in Prod as well

**Comment by riodeuno** [comment]
> @riodeuno, when the user enables a multi-select toggle and tries to delete the delete query fails. this issue is present in Prod as well

@RakshaKShetty What is the binding we've used in the delete query? Are we using `selectedRow` or `selectedRows`? If it is `selectedRows` then it should work with multi-select on. If it is `selectedRow`, then that would not be available in multiselect table today.

**Comment by RakshaKShetty** [comment]
@riodeuno i tried with both still facing the issue https://www.loom.com/share/95bff4dcbf0e41cbadd83424ae182ec4

**Comment by RakshaKShetty** [comment]
> > the delete button appears first then it moves at the end of the table. there is a flicker in table
> 
> @RakshaKShetty, I am not able to understand 2nd issue. Can you please share a loom video for the 2nd issue.

@vicky-primathon sharing a loom video https://www.loom.com/share/4072279070024d7fb02141aa9f0c02b1

**Comment by riodeuno** [comment]
@RakshaKShetty Both issues shared are non-issues. The Delete button flicker is due to the table widget recomputing the data. The other issue is, as we discussed, `selectedRows` is being used incorrectly.

Please confirm if there are any other issues. If not, we can move ahead with the merge.

**Comment by RakshaKShetty** [comment]
> @RakshaKShetty Both issues shared are non-issues. The Delete button flicker is due to the table widget recomputing the data. The other issue is, as we discussed, `selectedRows` is being used incorrectly.
> 
> Please confirm if there are any other issues. If not, we can move ahead with the merge.

@riodeuno there are no other bugs, fix looks good to me
