### PR TITLE
fix: Add ability to set the number of rows(page size) for WDS table widget

### LINKED ISSUE #30561: Add ability to set the number of rows(page size) for WDS table widget
In the property pane, we need to add control to set the number of rows of tables, based on this value we will calculate the height of the table.

It is also necessary to remove the control responsible for the rows height.

Снимок экрана 2024-01-23 в 16 13 58

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #30561 

## Summary by CodeRabbit

- **New Features**
  - Enhanced feature flag functionality for improved widget deployment control.
  - Added a configurable `pageSize` property to WDSTableWidget for customizing displayed rows.

- **Refactor**
  - Streamlined table scrolling by removing `SimpleBar` and adjusting container styles.
  - Improved table structure and styling for enhanced performance and user experience.
  - Updated height calculation logic for better data display.

- **Bug Fixes**
  - Resolved issue with inaccurate evaluation of feature flags to ensure all users access latest features.

### CODE REVIEW

File: app/client/src/widgets/wds/WDSTableWidget/component/TableBody/index.tsx [hunk 1]
```diff
@@ -81,36 +78,53 @@ interface BodyPropsType {
...
+        horizontalScrollbarHeight
+      }
+      innerElementType={props.innerElementType}
+      itemCount={Math.max(props.rows.length, props.pageSize)}
+      itemData={props.rows}
+      itemSize={props.tableSizes.ROW_HEIGHT}
+      outerRef={ref}
+      style={{
+        overflow: "auto",
+        scrollbarColor: "initial",
```
Comment (jsartisan) [inline app/client/src/widgets/wds/WDSTableWidget/component/TableBody/index.tsx:112]: This is just to revert the platform scrollbar style.

File: app/client/src/widgets/wds/WDSTableWidget/component/TableBody/index.tsx [hunk 2]
```diff
@@ -81,36 +78,53 @@ interface BodyPropsType {
...
-      </div>
-    );
-  },
-);
+const TableVirtualBodyComponent = React.forwardRef((props: BodyPropsType) => {
+  const ref = React.useRef<HTMLDivElement>(null);
+  const [horizontalScrollbarHeight, setHorizontalScrollbarHeight] =
+    React.useState(0);
+
+  useLayoutEffect(() => {
```
Comment (jsartisan) [inline app/client/src/widgets/wds/WDSTableWidget/component/TableBody/index.tsx:86]: this is done so that the scrollbar does not come on the top of the last row.

File: app/client/src/widgets/wds/WDSTableWidget/component/TableBody/index.tsx [hunk 3]
```diff
@@ -81,36 +78,53 @@ interface BodyPropsType {
...
-          width={`calc(100% + ${2 * WIDGET_PADDING}px)`}
-        >
-          {rowRenderer}
-        </FixedSizeList>
-      </div>
-    );
-  },
-);
+const TableVirtualBodyComponent = React.forwardRef((props: BodyPropsType) => {
+  const ref = React.useRef<HTMLDivElement>(null);
```
Comment (sbalaji1192) [inline app/client/src/widgets/wds/WDSTableWidget/component/TableBody/index.tsx:82]: Can we also remove the React.forwardRed?

File: app/client/src/widgets/wds/WDSTableWidget/component/TableBody/index.tsx [hunk 4]
```diff
@@ -122,10 +136,7 @@ const TableBodyComponent = (props: BodyPropsType) => {
 };
 
 export const TableBody = React.forwardRef(
```
Comment (sbalaji1192) [inline app/client/src/widgets/wds/WDSTableWidget/component/TableBody/index.tsx:138]: here too

**Review by sbalaji1192 — APPROVED** [review]

**Review by KelvinOm — APPROVED** [review]
