### PR TITLE
Fix Local setup changes to accommodate M1 chip Macbooks.

### LINKED ISSUE #2957: [Bug] Local setup fails in M1 Chip Macbooks
## Description

[What happened]

Client fails to start nginx docker when trying to do a local setup in M1 chip Macbook.

./start-https runs without error but the docker fails to start.

### PR DESCRIPTION
**Pull request by marks0351**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
host.docker.internal seems to have a problem in M1 chip macbooks, added changes by @rishabhsaxena to start-https.sh and added documentation and new start-m1 script in package.json.

Fixes #2957 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update

## How Has This Been Tested?

Try setting up the appsmith client in a M1 chip macbook.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/start-https.sh [hunk 1]
```diff
@@ -87,6 +87,15 @@ case "${uname_out}" in
...
                 ;;
     Darwin*)    machine=Mac
+            # workaround for apple silicon until host.docker.interal works as expected
+        if [[ "$(uname -m)" = "arm64" ]]
+        then
+            # if no server was passed
+            if [[ -z $1 ]]; then
+                server_proxy_pass='http://"$(ipconfig getifaddr en0)":8080'
+            fi
+            client_proxy_pass='http://"$(ipconfig getifaddr en0)":3000'
```
Comment (mohanarpit) [inline app/client/start-https.sh:97]: Please format this section correctly.

**Review by mohanarpit — APPROVED** [review]
