### PR TITLE
fix: Popover in Multi select widget inside modals breaks away from the widget

### LINKED ISSUE #11485: [Bug]: Clicking on Multi-select dropdown inside tab widget the focus jumps to the top area on the canvas
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that placing tab widget below few of the widgets on the canvas and placing multi-select widget inside tab widget and on clicking on the multi-select drop down the focus jumps tp the top area on the canvas

[LOOM DEMO](https://www.loom.com/share/24f9e476b420475fb626bf19887f5c6a)

### Steps To Reproduce

1.Launch appsmith app in release/Production Environment 
2. Drag and drop a few widgets on the canvas one below one
3.Place Tab widget at the bottom 
4.Place an Multi-select widget inside Tab widget 
5.Click on the drop-down option of Multi-select and observe the focus jumps to the top area on the canvas

### Environment

Production

### Version

Cloud

### LINKED ISSUE #12161: [Bug]: Popover in Multi select widget inside modals breaks away from the widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i add a multi-select inside a modal with options exceeding the height to see a scroll. After reaching the end of the scroll the multi-select popover breaks away from the modal.

https://www.loom.com/share/91731e936021422db79eb97602f52bbc

### Steps To Reproduce

1. Create an app and make sure it's height exceeds that of the viewport
2. Add a new modal and a multi select widget inside the modal
3. Make sure the number of options in the multi select are high
4. Scroll after reaching the end of the list to see the pop-over break away

### Public Sample App

_No response_

### Version

Production

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
When I add a multi-select inside a modal with options exceeding the height to see a scroll. After reaching the end of the scroll the multi-select popover breaks away from the modal.

Fixes #12161 
Fixes #11485

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/12161-multiselects-broken-in-modal 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.72 **(0.01)** | 38.68 **(0.01)** | 36.22 **(0)** | 56.97 **(0.01)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :red_circle: | app/client/src/widgets/WidgetUtils.ts | 82.56 **(-0.25)** | 59.66 **(-2.08)** | 64.52 **(-2.15)** | 78.75 **(-0.36)**
 :red_circle: | app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx | 15.12 **(-0.61)** | 0 **(0)** | 0 **(0)** | 16.88 **(-0.62)**
 :red_circle: | app/client/src/widgets/MultiSelectWidget/component/index.tsx | 18.84 **(-0.6)** | 0 **(0)** | 0 **(0)** | 20 **(-0.59)**
 :red_circle: | app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx | 9.7 **(-0.52)** | 0 **(0)** | 0 **(0)** | 10.92 **(-0.56)**
 :red_circle: | app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx | 14.77 **(-0.61)** | 0 **(0)** | 0 **(0)** | 16.46 **(-0.61)**</details>

### CODE REVIEW

File: app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx [hunk 1]
```diff
@@ -148,12 +147,9 @@ function MultiTreeSelectComponent({
...
-    if (Boolean(node?.closest(`.${MODAL_PORTAL_CLASSNAME}`))) {
-      return document.querySelector(
-        `.${MODAL_PORTAL_CLASSNAME}`,
-      ) as HTMLElement;
-    }
-    return document.querySelector(`.${CANVAS_CLASSNAME}`) as HTMLElement;
+    return node?.closest(
+      `${SELECT_DROPDOWN_CONTAINER_SELECTOR}`,
+    ) as HTMLElement;
   }, []);
```
Comment (Tooluloope) [inline app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx:153]: Can we make getting the Closest canvas widget into a utility function rather than repeating this across

**Review by Tooluloope — CHANGES_REQUESTED** [review]

**Review by Tooluloope — DISMISSED** [review]

**Comment by Tooluloope** [comment]
@wmdev0808 
Moving to QA but please dont merge till Theming is merged.
There's a conflict
Screenshot 2022-04-21 at 12 55 37

**Comment by chandannkumar** [comment]
Tested this PR and working as expected
- scrolling the multi-select popover breaks away from the modal - fixed

**Review by Tooluloope — APPROVED** [review]

**Comment by dilippitchika** [comment]
@vivekverma2312 can you please #11485 here, the treeselect issue where it navigates to the top once opened?

**Review by ashit-rath — COMMENTED** [review]
I think there is a scroll function in cypress that we can use to verify the fix. Can you check if that's useful and add a cypress test if possible?

File: app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx [hunk 2]
```diff
@@ -152,14 +148,9 @@ function MultiTreeSelectComponent({
...
-  const getDropdownPosition = useCallback(() => {
+  const getPopupContainer = useCallback(() => {
     const node = _menu.current;
-    if (Boolean(node?.closest(`.${MODAL_PORTAL_CLASSNAME}`))) {
-      return document.querySelector(
-        `.${MODAL_PORTAL_CLASSNAME}`,
-      ) as HTMLElement;
-    }
-    return document.querySelector(`.${CANVAS_CLASSNAME}`) as HTMLElement;
+    return node as HTMLElement;
```
[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx:153]: @ashit-rath 
using `const _menu = useRef<HTMLElement>();` wont help as _menu could then be HTMLElement or Undefined

[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx]: Oh no, the reason I'm asserting is because the needed return type for the function is HTMLElement, so either way, I'll still need to assert

[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx]: It cant throw an error since `getPopupContainer` can only be called after the dropdown has been rendered.

[the remark this answers is not in the document]
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx]: As for the scrolling, the scroll commands in cypress are just to help simulate scrolling and not to assert if it scrolled

**Review by ashit-rath — DISMISSED** [review]

**Comment by chandannkumar** [comment]
@Tooluloope  
Observation:
- Since the size of the pop-over dropdown is now fixed which actually hides few list at the bottom, if the size of the modal is compact.
- It is also observed that pop-over list is now transparent as we can see background buttons when we move the cursor away from the pop-over. refer video
https://www.loom.com/share/79fd60ae6a014c92b94aac9af77ad0dd

File: app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx [hunk 3]
```diff
@@ -187,7 +182,6 @@ function MultiTreeSelectComponent({
       <>
         {isFilterable ? (
           <InputGroup
-            autoFocus
```
Comment (Tooluloope) [inline app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx:190]: @ashit-rath this was the major reason for the jumps/scrolling when the dropdown is rendered

**Review by ashit-rath — DISMISSED** [review]
@Tooluloope Minor callout.

**Review by Tooluloope — APPROVED** [review]

**Comment by chandannkumar** [comment]
@Tooluloope @dilippitchika 
1st point on my last callout is still not fixed where few list items in bottom of dropdown is hidden since the modal size is compact
https://www.loom.com/share/552e452105a54a9fabbf997c2a12c19e

or else this is an expected behavior here?

**Comment by Tooluloope** [comment]
Could you confirm this also happens in release or Production?
If it does I can handle that in another PR @chandannkumar

**Comment by chandannkumar** [comment]
@Tooluloope Since on release/Production we didn't have fixed size of the dropdown and hence the dropdown list can be seen beyond the modal size

**Comment by chandannkumar** [comment]
Moving it to in Progress again.
@Tooluloope Please let me know if we are going to track this separately

**Comment by Tooluloope** [comment]
@chandannkumar Please do test for the Multiselect, MultiTreeSelect and TreeSelect  positioning issues, scrolling issues,

**Comment by chandannkumar** [comment]
@Tooluloope 
Observation: When we try to scroll the dropdown list after reaching to the bottom of the list, the list went to the top of the canvas and cuts the view of dropdown.
This behavior occurs to all the select family in this DP and only when widget added on Modal
https://www.loom.com/share/76608810c457433baa5d7acaca0695f8

**Comment by chandannkumar** [comment]
Tested this PR and it is working as expected

File: app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx [hunk 4]
```diff
@@ -208,50 +233,6 @@ function MultiSelectComponent({
     return filteredOptions.map((x) => value.some((y) => y.value === x.value));
   };
 
-  // SelectAll if all options are in Value
-  useEffect(() => {
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx:212]: Are we relocating these somewhere else?

File: app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx [hunk 5]
```diff
@@ -15,20 +15,22 @@ import {
...
+import {
+  getMainCanvas,
+  labelMargin,
+  WidgetContainerDiff,
+} from "widgets/WidgetUtils";
 import Icon from "components/ads/Icon";
 import { Colors } from "constants/Colors";
 import { LabelPosition } from "components/constants";
 import LabelWithTooltip from "components/ads/LabelWithTooltip";
+import { BackDrop } from "widgets/MultiSelectWidgetV2/component";
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx:32]: It seems a bit odd to import such components from Multiselect.
Is there any other place we can keep this?

File: app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx [hunk 6]
```diff
@@ -195,9 +212,17 @@ function MultiSelectComponent({
     return onChange([]);
   };
 
+  // When Dropdown is opened disable scrolling within the app except the list of options
   const onOpen = useCallback((open: boolean) => {
     if (open) {
       setTimeout(() => inputRef.current?.focus(), FOCUS_TIMEOUT);
+      if (popupContainer.current && renderMode === RenderModes.CANVAS) {
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx:219]: I see a lot of code getting repeated across the select family. 
Let's create a hook and have the hook do the following
1. Create `popupContainer` and manage to add the canvas to it.
2. Create `selectRef` and return it to add it to the Select component
3. Return a function that toggles the overflow of the container which you can use here.
4. Returns `getPopupContainer` function
5. Returns `closeBackDrop` function
6. Return the Backdrop component as well

File: app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx [hunk 7]
```diff
@@ -34,6 +34,13 @@ import LabelWithTooltip from "components/ads/LabelWithTooltip";
 const menuItemSelectedIcon = (props: { isSelected: boolean }) => {
   return <MenuItemCheckBox checked={props.isSelected} />;
 };
+
+type BackDropProps = {
+  onClick: () => void;
+};
+export function BackDrop({ onClick }: BackDropProps) {
+  return <div className="select-backdrop" onClick={onClick} />;
```
Comment (ashit-rath) [inline app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx:42]: Can this not be a Styled component? With this we are including the same style everywhere.

**Review by ashit-rath — COMMENTED** [review]
@Tooluloope It seems that we have now implemented a different logic than before. Why didn't the old one work and what are we doing with this new logic?

**Comment by Tooluloope** [comment]
> It seems that we have now implemented a different logic than before. Why didn't the old one work and what are we doing with this new logic?
@ashit-rath , We decided to disable scrolling when the Dropdown is opened, That's why I'm using a backDrop.

File: app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx (hunk 4 above)
Comment (Tooluloope) [reply app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx:212]: I think this was duplicated

File: app/client/src/widgets/useDropdown.tsx [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+    return <BackDropContainer onClick={closeBackDrop} />;
+  }
+  // Get PopupContainer on main Canvas
+  const getPopupContainer = useCallback(() => popupContainer.current, []);
+
+  // When Dropdown is opened disable scrolling within the app except the list of options
+  const onOpen = useCallback((open: boolean) => {
+    if (open) {
+      setTimeout(() => inputRef.current?.focus(), FOCUS_TIMEOUT);
+      console.log(popupContainer.current);
```
Comment (ashit-rath) [inline app/client/src/widgets/useDropdown.tsx:45]: Remove `console.log`

File: app/client/src/widgets/useDropdown.tsx [hunk 9]
```diff
@@ -0,0 +1,63 @@
...
+      if (popupContainer.current && renderMode === RenderModes.CANVAS) {
+        popupContainer.current.style.overflowY = "hidden";
+      }
+    } else {
+      if (popupContainer.current && renderMode === RenderModes.CANVAS) {
```
Comment (ashit-rath) [inline app/client/src/widgets/useDropdown.tsx:50]: Don't we need to do this in the View mode as well?

Comment (Tooluloope) [reply app/client/src/widgets/useDropdown.tsx]: Not needed for view mode

**Review by ashit-rath — APPROVED** [review]

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by somangshu** [comment]
Seems like related tests are failing, Please check @Tooluloope
