### PR TITLE
fix: Add message prompt on min field

### LINKED ISSUE #20235: [Bug]-[8000]:In table widget , Unable to see the Helper text for properties that come under Editable section in all column types
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 In table widget , Unable to see the Helper text for properties that come under Editable section in all column types 

### Steps To Reproduce

1. DND tablele widget
2. goto column type Plain text
3. switch property to editable
4. check the dependent properties . eg- regex
5. The "type / to access command " is missing in the input box

This can be replicated with Plain text, Number
Screen Shot 2023-01-31 at 12 53 56 AM

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by rajatagrawal**
Fixes #20235

This pull requests adds a prompt message to min/max/regex/errorMessage/required input validation fields. Also fixed css styling on the prompt message for these fields as well as additionally on Valid/ComputedValue fields.

The design shared by @vasanthappsmith is attached below : 

image (1)

### Dev activity
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx [hunk 1]
```diff
@@ -123,6 +127,13 @@ class TableInlineEditValidationControl extends BaseControl<TableInlineEditValida
         expected={expected}
         label={label}
         onChange={this.onTextChange}
+        promptMessage={
+          <PromptMessage>
+            Access the current cell using <CurlyBraces>{"{{"}</CurlyBraces>
```
Comment (mohanarpit) [inline app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx:132]: Nit: Please move all strings to `messages.ts` file. This ensures that we can internationalize it and/or modify it from a single location.

File: app/client/cypress/support/index.js [hunk 2]
```diff
@@ -32,6 +32,17 @@ import "./themeCommands";
 import "./AdminSettingsCommands";
 /// <reference types="cypress-xpath" />
 
+let rapidMode = {
```
Comment (sbalaji1192) [inline app/client/cypress/support/index.js:35]: I think this should be part of a env file. @Aishwarya-U-R

Comment (Aishwarya-U-R) [reply app/client/cypress/support/index.js:35]: @rajatagrawal - is this not already merged to release?

Comment (rajatagrawal) [reply app/client/cypress/support/index.js:35]: yes sorry, it got accidentally pushed in this PR

Comment (Aishwarya-U-R) [reply app/client/cypress/support/index.js:35]: And @sbalaji1192 - Rishabh has also given a suggestion to keep this variable in cypress.json to avoid accident pushes & Rajat confirmed he will be working on it. @rajatagrawal - can give more updates.

Comment (rajatagrawal) [reply app/client/cypress/support/index.js]: yes, I will be working on it in a separate PR.

File: app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx (hunk 1 above)
Comment (rajatagrawal) [reply app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx]: This is fixed now.

File: app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx [hunk 3]
```diff
@@ -15,13 +15,22 @@ import styled from "styled-components";
...
 import { JSToString, stringToJS } from "./utils";
 import type { AdditionalDynamicDataTree } from "utils/autocomplete/customTreeTypeDefCreator";
+import { Colors } from "constants/Colors";
+import {
+  createMessage,
+  TABLE_WIDGET_VALIDATION_ASSIST_PROMPT,
+} from "@appsmith/constants/messages";
 
-const PromptMessage = styled.span`
+export const PromptMessage = styled.span`
```
Comment (aswathkk) [inline app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx:24]: I can see that `PromptMessage` got defined in multiple files.
example: TableComputeValue.tsx, ListComputeControl.tsx, JSONFormComputeControl.tsx etc.
Just search for it in the codebase.
Can we de-duplicate them?

File: app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx [hunk 4]
```diff
@@ -15,13 +15,22 @@ import styled from "styled-components";
...
 `;
+
+export const StyledCode = styled.span`
+  color: ${Colors.PRIMARY_ORANGE};
+`;
+
 export const CurlyBraces = styled.span`
-  color: ${(props) => props.theme.colors.codeMirror.background.hoverState};
-  background-color: #ffffff;
+  color: ${Colors.PRIMARY_ORANGE};
```
Comment (aswathkk) [inline app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx:33]: This style is only applied to this component.
I think we need to make it consistent across the product.

Screenshot 2023-05-05 at 12 32 26 PM
Screenshot 2023-05-05 at 12 32 34 PM

**Review by aswathkk — CHANGES_REQUESTED** [review]
@rajatagrawal The changes are not applied in all the fields.
I think we need to make this style consistent across the product.

The components like `PromptMessage`, `StyledCode` and `CurlyBraces` are locally defined in multiple files causes the inconsistency.

We need to define all these in a central location, make the style changes in that central location and import it

**Review by aswathkk — DISMISSED** [review]
Changes looks good to me.
The deduplication/inconsistency issues will be picked up in ADS2.0 it seems.

@rohitagarwal88 Can you attach the relevant task in this PR?
