### PR TITLE
fix: Changes for JS actions in the import/export feature

### LINKED ISSUE #7008: [Bug] Implement import/export for js collections

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #7008

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java [hunk 1]
```diff
@@ -97,187 +103,212 @@
...
+                    application.setOrganizationId(null);
+                    application.setPages(null);
+                    application.setPublishedPages(null);
+                    application.setModifiedBy(null);
+                    application.setUpdatedAt(null);
+                    application.setLastDeployedAt(null);
+                    application.setGitApplicationMetadata(null);
+                    examplesOrganizationCloner.makePristine(application);
+                    applicationJson.setExportedApplication(application);
+                    // TODO @Abhijeet please take a look at the ACL permissions
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:165]: @nidhi-nair : Does MANAGE_PAGES does not look like the correct permission to use here?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java [hunk 2]
```diff
@@ -97,187 +103,212 @@
...
-                    })
-                    .collectList()
-                    .map(newActionList -> {
-                        Set<String> concernedDBNames = new HashSet<>();
-                        newActionList.forEach(newAction -> {
-                            newAction.setPluginId(pluginMap.get(newAction.getPluginId()));
-                            newAction.setOrganizationId(null);
-                            newAction.setPolicies(null);
-                            newAction.setApplicationId(null);
-                            //Collect Datasource names to filter only required datasources
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:233]: @abhvsn : QQ : What was the reason this check was added?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java [hunk 3]
```diff
@@ -97,187 +103,212 @@
...
+                                    if (newAction.getUnpublishedAction() != null) {
+                                        ActionDTO actionDTO = newAction.getUnpublishedAction();
+                                        actionDTO.setPageId(pageIdToNameMap.get(actionDTO.getPageId() + PublishType.UNPUBLISHED));
+                                    }
+                                    if (newAction.getPublishedAction() != null) {
+                                        ActionDTO actionDTO = newAction.getPublishedAction();
+                                        actionDTO.setPageId(pageIdToNameMap.get(actionDTO.getPageId() + PublishType.PUBLISHED));
+                                    }
+                                });
+                                // This is where we're removing global datasources that are unused in this application
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:257]: Thanks for writing the comment @nidhi-nair ! ❤️

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java [hunk 4]
```diff
@@ -378,275 +418,358 @@
...
+                                        .flatMap(actionId -> newActionRepository.findById(actionId, AclPermission.MANAGE_ACTIONS))
+                                        .map(newAction -> {
+                                            newAction.getUnpublishedAction().setCollectionId(
+                                                    unpublishedActionIdToCollectionIdMap.getOrDefault(newAction.getId(), null));
+                                            newAction.getPublishedAction().setCollectionId(
+                                                    publishedActionIdToCollectionIdMap.getOrDefault(newAction.getId(), null));
+                                            return newAction;
+                                        })
+                                        .flatMap(newAction -> newActionService.update(newAction.getId(), newAction))
+                                        .then()
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:732]: Any reason for adding a then() considering you are calling a thenReturn right after?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java (hunk 2 above)
Comment (abhvsn) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:233]: I was not sure if `PluginType.JS` will break the flow in some scenario that's why put that check here. But we can safely remove this

Comment (trishaanand) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:233]: Thanks!

**Review by abhvsn — APPROVED** [review]
LGTM

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java (hunk 4 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:732]: Mysterious webflux behaviour, it was failing without it

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java (hunk 1 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:165]: We seem to have a separate role for `export`, but we're using different kinds of permissions throughout this flow. We should stick to one ACL type so that any changes in that graph in the future does not break this flow.

Comment (trishaanand) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:165]: Role is used to programmatically give permissions (which are of types manage, read, execute, etc.) on top of the domain object. So the export role would give manage page permissions to the user for all the apps the user can export. Hence, this would be the correct permission to use.

**Review by trishaanand — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java (hunk 1 above)
Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java:165]: Oh I see. We should map these expected roles visually some place. I thought we'd have export at various levels as well. But yeah, @abhvsn you can ignore my comment I'll delete it in some other PR :P
