### PR TITLE
fix: The value is always empty object in AudioRecorder Widget

### LINKED ISSUE #8855: [Bug]: The value is always empty object in AudioRecorder Widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The evaluated value of `value` prop always shows an empty object whenever we record audio with the audio recorder widget.

### Steps To Reproduce

1. Drag and drop audio recorder widget.
2. Record a audio.
3. Bind the `AudioRecorder1.value` on a text widget.
4. Notice that value will show empty object.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
The evaluated value of value prop always shows an empty object whenever we record audio with the audio recorder widget.

Fixes #8855 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/8855-audiorecorder-value-empty 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.56 **(-0.01)** | 36.43 **(-0.01)** | 33.17 **(0)** | 55.08 **(-0.01)**
 :red_circle: | app/client/src/widgets/AudioRecorderWidget/component/index.tsx | 13.98 **(0)** | 13.46 **(-0.13)** | 6.25 **(0)** | 16.18 **(0)**
 :red_circle: | app/client/src/widgets/AudioRecorderWidget/widget/index.tsx | 38.46 **(-6.54)** | 0 **(0)** | 62.5 **(0)** | 38 **(-6.74)**</details>

### CODE REVIEW

File: app/client/src/widgets/AudioRecorderWidget/widget/index.tsx [hunk 1]
```diff
@@ -121,21 +132,37 @@ class AudioRecorderWidget extends BaseWidget<
...
     }
-    this.props.updateWidgetMetaProperty("value", blob, {
-      triggerPropertyName: "onRecordingComplete",
-      dynamicString: this.props.onRecordingComplete,
-      event: {
-        type: EventType.ON_RECORDING_COMPLETE,
-      },
-    });
+    this.props.updateWidgetMetaProperty("blobUrl", blobUrl);
+    if (blob) {
```
Comment (SatishGandham) [inline app/client/src/widgets/AudioRecorderWidget/widget/index.tsx:141]: You already have a blob URL. Why are you creating it again?
You can use code form `createBlobUrl` directly here instead of making another blob url.

File: app/client/src/widgets/AudioRecorderWidget/widget/index.tsx [hunk 2]
```diff
@@ -121,21 +132,37 @@ class AudioRecorderWidget extends BaseWidget<
 
   handleRecordingComplete = (blobUrl?: string, blob?: Blob) => {
     if (!blobUrl) {
-      this.props.updateWidgetMetaProperty("value", undefined);
+      this.props.updateWidgetMetaProperty("blobUrl", undefined);
+      this.props.updateWidgetMetaProperty("dataAsDataURL", undefined);
```
Comment (SatishGandham) [inline app/client/src/widgets/AudioRecorderWidget/widget/index.tsx:136]: @somangshu Names `dataAsDataURL` and `dataAsRawBinary` doesn't feel right to me. Any suggestions?

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/AudioRecorderWidget/widget/index.tsx (hunk 2 above)
Comment (somangshu) [reply app/client/src/widgets/AudioRecorderWidget/widget/index.tsx:136]: @SatishGandham you are right, thanks for bringing this up. We could use:
- just `dataURL` : This is a very common term generically used
- `rawBinary` / `rawData` : Are the most commonly used 

Let me know what you think.

cc @Nikhil-Nandagopal

**Comment by somangshu** [comment]
@wmdev0808 are the above comments resolved?

**Comment by wmdev0808** [comment]
> @wmdev0808 are the above comments resolved?

Not yet, I will make changes

**Comment by somangshu** [comment]
Also @SatishGandham @wmdev0808 please see if we need tests here.

@YogeshJayaseelan this is a critical issue and should have bee tested by now, Please look into this.

**Comment by vivekverma2312** [comment]
@wmdev0808 Tested on deploy preview, Now we are able to store the recording files to S3.

File: app/client/src/widgets/AudioRecorderWidget/constants.ts [hunk 3]
```diff
@@ -1 +1,7 @@
-export const MY_AUDIORECORDER_WIDGET_CONSTANT = "";
+export enum BlobContentTypes {
+  RAW_BINARY = "RAW_BINARY",
+  DATA_URL = "DATA_URL",
+  TEXT = "TEXT",
```
Comment (SatishGandham) [inline app/client/src/widgets/AudioRecorderWidget/constants.ts:4]: Audio is never going to be text.

**Review by SatishGandham — CHANGES_REQUESTED** [review]

**Comment by wmdev0808** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1439521092

**Review by SatishGandham — APPROVED** [review]

**Comment by somangshu** [comment]
@wmdev0808 this PR is failing the server build repeatedly, Let try running the CI after updating the branch with the latest release

**Comment by wmdev0808** [comment]
https://github.com/appsmithorg/appsmith/actions/runs/1448997667
