### PR TITLE
fix: Calling form eval init on form change

### LINKED ISSUE #7370: [Bug][UQI] When changing from one query to another from the query pane, the evaluations are not updating
## Description

This is not going to show unless the form type is of UQI. When we switch from one form type to another, the evaluation state is not updating.

### Important Details

- Version: All
- OS: MacOSX
- Browser all
- Environment deploy preview for UQI

### PR DESCRIPTION
**Pull request by ayushpahwa**
## Description

Minor fix to update evals when the query is changed from the query pane. Issue is related to the new UQI changes and won't be visible if the changes from the backend are not made.

Fixes #7370 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/7370-update-evals-on-query-change 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.88 **(-0.01)** | 36.85 **(-0.01)** | 34.39 **(0)** | 55.4 **(-0.01)**
 :red_circle: | app/client/src/pages/Editor/QueryEditor/index.tsx | 31.37 **(-0.31)** | 9.3 **(0)** | 6.25 **(0)** | 32.98 **(-0.35)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/QueryEditor/index.tsx [hunk 1]
```diff
@@ -125,8 +126,14 @@ class QueryEditor extends React.Component<Props> {
         PerformanceTransactionName.RUN_QUERY_CLICK,
       );
     }
+    // Update the page and evaluations when the queryID is changed
```
Comment (trishaanand) [inline app/client/src/pages/Editor/QueryEditor/index.tsx:129]: Could you add the context here as to why the query id changes? Would be easy for a new person to understand

**Review by trishaanand — COMMENTED** [review]
Super minor nitpick

File: app/client/src/pages/Editor/QueryEditor/index.tsx (hunk 1 above)
Comment (ayushpahwa) [reply app/client/src/pages/Editor/QueryEditor/index.tsx]: Done

**Review by trishaanand — APPROVED** [review]

**Review by ApekshaBhosale — APPROVED** [review]

**Review by rashmi-rai — APPROVED** [review]
