### PR TITLE
fix: Show trigger errors in the debugger with widget and property name

### LINKED ISSUE #6339: [Feature] Debugger: Log trigger errors in the debugger
## Summary
It seems that currently trigger errors are not logged in the debugger, hence even though the user sees a trigger error, they cannot find it the debugger. 

More context:
https://theappsmith.slack.com/archives/CGBPVEJ5C/p1627900733030300

### LINKED ISSUE #6340: [Bug] Error reporting: Make errors more pointed
## Summary
If the onRowClick field is causing the error, then it should clearly say that the Table1 's onRowClick field has error. This would help the user look into the right place when debugging. 

More context:
https://theappsmith.slack.com/archives/CGBPVEJ5C/p1627900733030300

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description 

Fixes #6340
Fixes #6339

Errors are shown are in the errors tab of the debugger when there is an error on trigger. The error in the debugger gets cleared once the same is triggered succesfully.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Cypress test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/pointed-trigger-errors 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.86 **(-0.02)** | 36.81 **(-0.08)** | 34.23 **(0)** | 55.38 **(-0.02)**
 :green_circle: | app/client/src/components/ads/Toast.tsx | 78.72 **(0.46)** | 62.5 **(1.39)** | 88.24 **(0)** | 78.72 **(0.46)**
 :red_circle: | app/client/src/constants/messages.ts | 75.04 **(-0.03)** | 100 **(0)** | 25.59 **(-0.07)** | 81.23 **(-0.12)**
 :red_circle: | app/client/src/sagas/DebuggerSagas.ts | 14.58 **(-1.06)** | 4.17 **(-0.35)** | 16.67 **(-0.98)** | 16.28 **(-1.11)**
 :green_circle: | app/client/src/sagas/PostEvaluationSagas.ts | 17.73 **(0.25)** | 0 **(0)** | 0 **(0)** | 21.74 **(0.37)**
 :green_circle: | app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts | 32.97 **(4.22)** | 1.56 **(-1.22)** | 28.57 **(0)** | 32.18 **(4.55)**
 :red_circle: | app/client/src/sagas/ActionExecution/PromiseActionSaga.ts | 29.27 **(-3.29)** | 0 **(0)** | 33.33 **(0)** | 23.53 **(-4.25)**
 :red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

File: app/client/src/sagas/PostEvaluationSagas.ts [hunk 1]
```diff
@@ -244,9 +244,6 @@ export function* evalErrorHandler(
           variant: Variant.danger,
           showDebugButton: true,
         });
-        AppsmithConsole.error({
-          text: message,
-        });
```
Comment (rishabhsaxena) [inline app/client/src/sagas/PostEvaluationSagas.ts:249]: Should we log at both places: logs and errors tabs?

File: app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts [hunk 2]
```diff
@@ -107,18 +116,37 @@ export function* executeAppAction(payload: ExecuteTriggerPayload) {
...
+        id: source?.id ?? "",
+        name: source?.name ?? "",
+        propertyPath: triggerPropertyName,
+      },
+      messages: [
+        {
+          message: e.message,
+        },
+      ],
+    });
```
Comment (rishabhsaxena) [inline app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts:149]: QQ: is there any case where the error is not caught during evaluation, as in within `evaluateDynamicTrigger`?

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts (hunk 2 above)
Comment (akash-codemonk) [reply app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts:147]: Actually all errors including [eval trigger errors](https://github.com/appsmithorg/appsmith/blob/fix/pointed-trigger-errors/app/client/src/sagas/PostEvaluationSagas.ts#L247) are caught here. 

There are other [errors](https://github.com/appsmithorg/appsmith/blob/fix/pointed-trigger-errors/app/client/src/sagas/ActionExecution/CopyActionSaga.ts#L10) which are thrown after eval as well.

File: app/client/src/sagas/DebuggerSagas.ts [hunk 3]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable no-console */
```
Comment (rishabhsaxena) [inline app/client/src/sagas/DebuggerSagas.ts:1]: I guess this was meant for dev

File: app/client/src/sagas/ActionExecution/PluginActionSaga.ts [hunk 4]
```diff
@@ -315,7 +315,6 @@ export default function* executePluginActionTriggerSaga(
     Toaster.show({
       text: createMessage(ERROR_PLUGIN_ACTION_EXECUTE, action.name),
       variant: Variant.danger,
-      showDebugButton: true,
```
Comment (rishabhsaxena) [inline app/client/src/sagas/ActionExecution/PluginActionSaga.ts:318]: QQ: we do add an error here, so ideally we could show the debug cta?

File: app/client/src/sagas/ActionExecution/PromiseActionSaga.ts [hunk 5]
```diff
@@ -48,7 +48,6 @@ export default function* executePromiseSaga(
       Toaster.show({
         text: "There was an error while executing",
         variant: Variant.danger,
-        showDebugButton: true,
```
Comment (rishabhsaxena) [inline app/client/src/sagas/ActionExecution/PromiseActionSaga.ts:51]: QQ: should we show the toast only when we don't have a catch block here, and we could then log it and show the debug cta

**Review by rishabhsaxena — APPROVED** [review]

File: app/client/src/sagas/ActionExecution/PluginActionSaga.ts (hunk 4 above)
Comment (akash-codemonk) [reply app/client/src/sagas/ActionExecution/PluginActionSaga.ts]: The toast was removed on release

File: app/client/src/sagas/ActionExecution/PromiseActionSaga.ts [hunk 6]
```diff
@@ -55,7 +56,9 @@ export default function* executePromiseSaga(
     }
   } catch (e) {
     log.error(e);
-    if (!trigger.catch) {
+    // TriggerEvaluationError toasts are already shown in
+    // evalErrorHandler saga
+    if (!trigger.catch && !(e instanceof TriggerEvaluationError)) {
       Toaster.show({
```
Comment (rishabhsaxena) [inline app/client/src/sagas/ActionExecution/PromiseActionSaga.ts:62]: should we add the toaster at `initiateActionTriggerExecution` as well, since we're anyway throwing the error, so we'd handle the errors at one place?

File: app/client/src/sagas/ActionExecution/PromiseActionSaga.ts [hunk 7]
```diff
@@ -79,9 +82,10 @@ export default function* executePromiseSaga(
         },
         responseData: catchArguments,
       });
-    } else {
-      throw new TriggerFailureError("Uncaught promise rejection", e);
     }
+    // This error could be a TriggerEvaluationError as well so
+    // throwing these errors as it is
+    throw e;
```
Comment (rishabhsaxena) [inline app/client/src/sagas/ActionExecution/PromiseActionSaga.ts:88]: should we throw an error only when there's no `catch` block?

**Review by rishabhsaxena — APPROVED** [review]
a couple of queries, rest LGTM

**Comment by rishabhsaxena** [comment]
Also a minor point: should we show the value along with the error in the errors tab? This could be an enhancement

File: app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts [hunk 8]
```diff
@@ -95,37 +100,65 @@ export function* executeAppAction(payload: ExecuteTriggerPayload) {
...
+    log.debug({ triggers });
+    if (triggers && triggers.length) {
+      yield all(
+        triggers.map((trigger: ActionDescription) =>
+          call(executeActionTriggers, trigger, type),
+        ),
+      );
+    }
+  } catch (e) {
+    throw e;
```
[the remark this answers is not in the document]
Comment (akash-codemonk) [reply app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts:120]: Yes these errors are required to be thrown so that all errors eventually endup in initiateActionTriggerExecution. This was not happening.

File: app/client/src/sagas/ActionExecution/PromiseActionSaga.ts (hunk 7 above)
Comment (akash-codemonk) [reply app/client/src/sagas/ActionExecution/PromiseActionSaga.ts]: For e.g here we do have a catch(the showAlert call), but there is an error in then( assuming no query named Query1s exists). So in this case we were showing a toast but this error wasn't thrown back to `initiateActionTriggerExecution` saga. To show this error in the debugger the error needs to be accessible there so I am throwing it at the end of the saga if there are any errors.
```
{{Query1.run(() => Query1s.run(), () => showAlert("Test"))}}
```

**Comment by akash-codemonk** [comment]
> Also a minor point: should we show the value along with the error in the errors tab? This could be an enhancement

Not sure this would be helpful as these are for trigger fields and these have function calls, so there is no resulting evaluated value of the field. So what could be shown is the code in the field itself.

File: app/client/src/sagas/ActionExecution/PromiseActionSaga.ts (hunk 7 above)
Comment (rishabhsaxena) [reply app/client/src/sagas/ActionExecution/PromiseActionSaga.ts]: Just checking: would it be displaying an error toast even when there's an explicit catch block added by the user?

Comment (akash-codemonk) [reply app/client/src/sagas/ActionExecution/PromiseActionSaga.ts]: Yes it is shown. This happens on release as well.

**Review by rishabhsaxena — DISMISSED** [review]

**Review by rishabhsaxena — APPROVED** [review]
