### PR TITLE
fix: Added support for multiple files in multipart REST

### LINKED ISSUE #8985: [Feature]: Add support for multiple files in the same key for multipart REST APIs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Users would like to attach multiple files to the same key in multipart file uploads

### Why should this be worked on?

We're currently only accepting one file per key and the spec is not limited to such behaviour.

### PR DESCRIPTION
**Pull request by nidhi-nair**
## Description
This fix retains support for single uploads as well as adds support for an array of files. This means that existing actions do not have to be migrated and future actions continue to have the option of using an array of files or just a single file.

Fixes #8985 

## Type of change
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Tested manually
- JUnit case

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java [hunk 1]
```diff
@@ -150,26 +152,11 @@ public String parseFormData(List<Property> bodyFormData, Boolean encodeParamsTog
...
                         } else if (MultipartFormDataType.FILE.equals(multipartFormDataType)) {
-
-                            MultipartFormDataDTO multipartFormDataDTO = null;
                             try {
-                                multipartFormDataDTO = objectMapper.readValue(
-                                        String.valueOf(property.getValue()),
-                                        MultipartFormDataDTO.class);
+                                populateFileTypeBodyBuilder(bodyBuilder, property, outputMessage);
                             } catch (JsonProcessingException e) {
                                 e.printStackTrace();
```
Comment (sumitsum) [inline app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java:158]: Hey sorry for this, I know this is not a part of this change, still since it is related I wanted to bring this up - the try catch here silently suppresses the exception from reading file data. Can we do something else here ? - like maybe return an `AppsmithExeception` or a warning message to the client that the file upload has failed ?

**Review by sumitsum — APPROVED** [review]
