### PR TITLE
fix: File lock issue with git status and fetch

### LINKED ISSUE #29260: [Bug]: Internal Server error seen on navigating between branches in a git connected app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I navigate between branches in a git connected application, after making some changes in one branch, I see an internal server error popping up

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/a9368941-0f77-48e6-b8ac-bce4ae649ad2

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
File lock was not handled properly in In git status and fetch API. As a result, when the get status and fetch APIs are called in parallel, the lock file error is thrown. This PR fixes the issue.

#### PR fixes following issue(s)
Fixes #29260

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
  - Enhanced the Git integration to support file locking during branch checkout operations, ensuring better concurrency management.

- **Bug Fixes**
  - Resolved issues related to branch checkout by introducing additional checks and operations to maintain consistency and prevent conflicts.

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java [hunk 1]
```diff
@@ -1448,21 +1451,35 @@ public Mono<Application> checkoutBranch(String defaultApplicationId, String bran
...
+                    return Mono.just(result);
                 })
-                .flatMap(application -> addAnalyticsForGitOperation(
-                        AnalyticsEvents.GIT_CHECKOUT_BRANCH.getEventName(),
-                        application,
-                        application.getGitApplicationMetadata().getIsRepoPrivate()))
-                .map(responseUtils::updateApplicationWithDefaultResources);
+                .onErrorResume(throwable -> {
+                    if (addFileLock) {
+                        return releaseFileLock(defaultApplicationId).then(Mono.error(throwable));
```
Comment (AnaghHegde) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java:1479]: Why is this still present?
