### PR TITLE
[Bugfix] - Allow login with case insensitive emails

### LINKED ISSUE #5998: [Bug] Username during signuup/login are case sensitive
## Description

The username during signup/login should not be case sensitive. 

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to the sign up page
2. Sign up with email ID: abc@example.com
3. Log out
4. Sign up with another email ID: ABC@example.com
5. You should be informed that a user already exists with this username & that the user should login. 
6. Login with ABC@example.com. 

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
This PR checks for case insensitive email when no user found with a provided email address.

Fixes #5998 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Unit test
- Tested on local machine

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomFormLoginServiceImpl.java [hunk 1]
```diff
@@ -33,6 +33,7 @@ public CustomFormLoginServiceImpl(UserRepository repository) {
     @Override
     public Mono<UserDetails> findByUsername(String username) {
         return repository.findByEmail(username)
+                .switchIfEmpty(repository.findByCaseInsensitiveEmail(username))
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomFormLoginServiceImpl.java:36]: Is there a way for us to find the number of users with the same email ID but different casing? I’m asking to see if we can solve this via a migration instead of 2 DB queries.

Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomFormLoginServiceImpl.java:36]: @mohanarpit we thought about that approach but did not do it because there might be duplicates in self hosted instances also.

**Review by mohanarpit — APPROVED** [review]

**Comment by nayan-rafiq** [comment]
@mohanarpit I've Rebased from release to fix the failing cypress tests. Would you please review once again?

**Review by mohanarpit — APPROVED** [review]
