### PR TITLE
fix: Fix annoying issue with Entity form control in google sheets

### LINKED ISSUE #21700: [Feature]: In Gsheet datasource, The entity dropdown in query creation should default to a single enabled option if all other options are disabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In google sheet query creation, when I select operation as `insert many`, `update one`, and `update many`, in the entity dropdown only sheet rows option is enabled by default, other options of spreadsheet and sheet are disabled, Since a single option is enabled for these operations we can default the dropdown to this option for above three operations. 

### Why should this be worked on?

When I create gsheet query, for some operations, only single value is enabled in entity dropdown, for such operations I should be able to see that single option value by default in the dropdown, so that I do not have to waste my time into opening the dropdown and looking at other option values which are disabled and I can move ahead with query creation faster

### PR DESCRIPTION
**Pull request by Irongade**
In google sheet query creation, when I select operation as insert many, update one, and update many, in the entity dropdown only sheet rows option is enabled by default, other options of spreadsheet and sheet are disabled, Since a single option is enabled for these operations we can default the dropdown to this option for above three operations. This PR fixes that.

Fixes #21700 
> if no issue exists, please create an issue and ask the maintainers about this first

- Bug fix (non-breaking change which fixes an issue)

- Manual

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/components/formControls/DropDownControl.tsx [hunk 1]
```diff
@@ -209,6 +209,22 @@ function renderDropdown(
         selectedValue = tempValues;
         props.input?.onChange(tempValues);
       }
+
+      const isOptionDynamic = options.some((opt) => "disabled" in opt);
+      if (isOptionDynamic) {
+        const isCurrentOptionDisabled = options.some(
```
Comment (sneha122) [inline app/client/src/components/formControls/DropDownControl.tsx:215]: @Irongade Since this code is added in dropdowncontrol component, which is common form control and this change will be applicable to wherever we use dropdown control and if they have disabled property, In google sheets case, since entity field is mandatory it makes sense, but what if the field is optional, in that case we would still be setting it to some default value, we should not do that right?

Comment (sneha122) [reply app/client/src/components/formControls/DropDownControl.tsx:215]: Please check conversation: https://theappsmith.slack.com/archives/CNQ9Q91C0/p1679642422610159

**Review by sneha122 — APPROVED** [review]
