### PR TITLE
Fix manage users link not visible in the share modal when triggered from the editor or viewer

### LINKED ISSUE #2592: [Feature] Manage users link is missing in 'share' flow from inside the app
## Summary
Users should be able to access the user management page from within an app. The current share modal inside the app doesn't show a manage users button.

This is how it should be:
Screen Shot 2021-01-15 at 9 40 27 PM

Current state:
Screen Shot 2021-01-15 at 9 40 50 PM

Notice the missing 'manage users' button.

### LINKED ISSUE #2794: TypeError: Cannot read property 'name' of undefined
Sentry Issue: [APPSMITH-HD](https://sentry.io/organizations/appsmith/issues/2191397342/?referrer=github_integration)

```
TypeError: Cannot read property 'name' of undefined
  at c (pages/organization/AppInviteUsersForm.tsx:71:49)
  at HTMLDocument.r (../../src/helpers.ts:87:17)
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by rishabhsaxena**
## Description
Fetch the `currentOrg` from the `orgs` reducer, since the list of organizations is not fetched for pages within the app viewer/editor
Null check for `currentUser`

Fixes #2592
Fixes #2794

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- manually
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by riodeuno — DISMISSED** [review]
Nice clean code!

**Comment by rishabhsaxena** [comment]
@riodeuno have updated it to use the `currentOrg` instead of looking up the list of user orgs. Since the list of user orgs is not fetched within editor/viewer.
Also we're updating the current org within the modal when opened through `/applications` or other pages where the current org context might not be set

File: app/client/src/pages/organization/AppInviteUsersForm.tsx [hunk 1]
```diff
@@ -110,7 +105,6 @@ const AppInviteUsersForm = (props: any) => {
       {canInviteToOrg && (
         <OrgInviteUsersForm orgId={props.orgId} isApplicationInvite={true} />
       )}
-      {canManage && <ManageUsers orgId={props.orgId} />}
```
Comment (riodeuno) [inline app/client/src/pages/organization/AppInviteUsersForm.tsx]: Since we're removing this, we should also remove the `ManageUsers` import above

**Review by riodeuno — DISMISSED** [review]

**Review by riodeuno — APPROVED** [review]
