### PR TITLE
fix: Feature Flag User Based Caching

### LINKED ISSUE #24941: [Task]: Flagsmith Update Caching to store in Redis and set a user based cache
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_No response_

### PR DESCRIPTION
**Pull request by NilanshBansal**
Fixes #24941 

#### Type of change
- Chore (housekeeping or task changes that don't impact user perception)

#### How Has This Been Tested?
- [x] Manual
- [x] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AnaghHegde — DISMISSED** [review]
Redis cache chages LGTM

File: app/server/appsmith-server/src/main/resources/application.properties [hunk 1]
```diff
@@ -110,3 +110,6 @@ appsmith.admin.envfile=${APPSMITH_ENVFILE_PATH:/appsmith-stacks/configuration/do
 
 # RTS port
 appsmith.rts.port=${APPSMITH_RTS_PORT:8091}
+
+# Feature Flagging Cache Refresh Rate
+appsmith.feature-flag.cache.in.minutes=${APPSMITH_FF_CACHE_TIME_MIN:120}
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/resources/application.properties:115]: Should this be configurable at all? Would we not risk excessive requests if this has been set to a different value?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java [hunk 2]
```diff
@@ -149,36 +186,19 @@ private Mono<Map<String, Boolean>> forceAllRemoteFeatureFlagsForUser(User user)
...
-                    return this.getRemoteFeatureFlagsByIdentity(
-                            new FeatureFlagIdentities(
-                                    tuple.getT1(),
-                                    tuple.getT2(),
-                                    this.featureFlagCache.keySet()));
-                })
-                .map(newCache -> {
-                    this.featureFlagCache.putAll(newCache);
-                    return newCache;
+                    return Mono.just(newValue.get(userIdentifier))
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java:194]: We need not return with a tuple here, please consider using a thenReturn

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java [hunk 3]
```diff
@@ -45,26 +49,43 @@ public class FeatureFlagServiceCEImpl implements FeatureFlagServiceCE {
...
-                                    UserIdentifierService userIdentifierService) {
+                                    UserIdentifierService userIdentifierService,
+                                    ReactiveRedisTemplate<String, Object> reactiveRedisTemplate) {
         this.sessionUserService = sessionUserService;
         this.ff4j = ff4j;
         this.tenantService = tenantService;
         this.configService = configService;
         this.cloudServicesConfig = cloudServicesConfig;
-        this.featureFlagCache = new ConcurrentHashMap<>();
+        this.reactiveRedisTemplate = reactiveRedisTemplate;
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java:72]: Please consider using a utility service like the one being used in reactive-caching as a wrapper here. We should use a common prefix to all feature flag related entries so we have an easy to manage those values. The repository layer ops would also get isolated in another class that way.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java [hunk 4]
```diff
@@ -45,26 +49,43 @@ public class FeatureFlagServiceCEImpl implements FeatureFlagServiceCE {
 
     private final CloudServicesConfig cloudServicesConfig;
 
-    private final Map<String, Map<String, Boolean>> featureFlagCache;
+    @Value("${appsmith.feature-flag.cache.in.minutes}")
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java:52]: What do you think about configuring this in a config bean and using the value from there? That's the norm we have been following so far to avoid littering the code base with property references.

**Review by nidhi-nair — CHANGES_REQUESTED** [review]
Please write tests

File: app/server/appsmith-server/src/main/resources/application.properties (hunk 1 above)
Comment (NilanshBansal) [reply app/server/appsmith-server/src/main/resources/application.properties:115]: Valid point, for self-hosted, this can be configured to a shorter time by the user, which can lead to excessive requests. 
@hetunandu @ginilpg @kocharrahul7 shall we consider keeping the cache time per user to a fixed value?

Comment (hetunandu) [reply app/server/appsmith-server/src/main/resources/application.properties:115]: We can set it as a fixed value for now. Lets see if it needs shorter time in dev/release in the future

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+
+@Slf4j
+public class CacheableFeatureFlagHelperCEImpl implements CacheableFeatureFlagHelperCE{
+    private final TenantService tenantService;
+
+    private final ConfigService configService;
+
+    private final CloudServicesConfig cloudServicesConfig;
+
+    public CacheableFeatureFlagHelperCEImpl(TenantService tenantService, ConfigService configService,
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java:31]: Nit, please use a formatter in your files before committing. Let's do this in whatever PR you work on next since this PR is a blocker for release.

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/FeatureFlagServiceTest.java [hunk 6]
```diff
@@ -81,6 +90,30 @@ public void testFeatureCheckForEmailStrategy() {
                 .verifyComplete();
     }
 
+    @Test
+    public void getFeatureFlags_withUserIdentifier_redisKeyExists(){
+        String userIdentifier = "testIdentifier";
+        Mono<CachedFlags> cachedFlagsMono = cacheableFeatureFlagHelper.fetchUserCachedFlags(userIdentifier);
+        Mono<Boolean> hasKeyMono = reactiveRedisTemplate.hasKey("featureFlag:" + userIdentifier);
+        StepVerifier.create(cachedFlagsMono.then(Mono.defer(()-> hasKeyMono)))
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/FeatureFlagServiceTest.java:98]: Does this not work as expected without the deferring? Also in the main code? Could you please check?

Comment (NilanshBansal) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/services/FeatureFlagServiceTest.java:98]: Yes, @nidhi-nair without Mono.defer() as well tests and main code both work as expected

**Review by nidhi-nair — APPROVED** [review]
