### PR TITLE
fix: evalTrigger mutation fix

### LINKED ISSUE #33823: [Bug]: Table Widget's TriggeredRow showing up as empty intermittently
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user reported facing an issue in his App which has a Table widget, and a column with a menu button.
He is using the Table.triggeredRow property to show some value in the Text widget and even run a query with it, whenever the a button in the menu is clicked.
He mentioned facing an issue intermittently where on clicking the button, sometimes the triggeredRow still shows up as empty and other times it shows up with the correct value.

This became frustrating for the user, so we debugged the issue and verified that it happens randomly.
So we came to a workaround where we are assigned a JSObject variable the triggeredRow's value whenever the menu's button is clicked. And that seems to have solved it. 

We even kept two text widgets side by side. One having the Table.triggeredRow value and the other having the JSObject variable assigned with the triggeredRow's value. 
 The text widget with the direct reference of triggeredRow showed up empty, but the widget with the reference of the variable was always showing the correct value when a row was triggered.
 
 Slack thread with recording here: https://theappsmith.slack.com/archives/C02JV8G1MP0/p1716975411759369

### Steps To Reproduce

1. Introduce a table widget and connect it to some data.
2.  Add a custom column having the type Menu button and configure some action for its onClick event.
3. Add a text widget which directly references the tables triggeredRow.<columnName>
4. Now click on the Menu button of any Row.

Sometimes you will see the text widget having the triggeredRow's value, and other times it will still be empty.
The issue is not persistent but can creep up both in editor and deployed mode.

### Public Sample App

_No response_

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://theappsmith.slack.com/archives/C02JV8G1MP0/p1716975411759369

### Version

Self Hosted 1.26

### PR DESCRIPTION
**Pull request by vsvamsi1**
## Description
This fixes a gap in our evaluation flow where we were not sending evaluation updates during an evaluation in the evalTrigger. We have resolved that by sending updates in the evalTrigger, also we have created a separate function called evaluateAndGenerateWebWorkerResponse which unifies the logic between sending updates in evalTrigger as well as evalTreeWithChanges. We have added several unit test cases in this PR to test the evaluation flow.

Fixes #33823  

> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.All"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9558723818>
> Commit: 8b7bc93e3d1a8ce93c722a94c8846f9359d40686
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9558723818&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: ``

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **Refactor**
  - Improved the evaluation and update process for data tree structures with new helper functions and interfaces.
  - Enhanced error handling with optional chaining in `setPrevState` function.

- **New Features**
  - Introduced `evaluateAndPushResponse`, `evaluateAndGenerateResponse`, and `getAffectedNodesInTheDataTree` functions for better data tree evaluation and updates.
  - Added `UpdateTreeResponse` interface for structured update responses.

- **Bug Fixes**
  - Adjusted error handling in the evaluation process to ensure robustness.

### CODE REVIEW

File: app/client/src/workers/Evaluation/handlers/evalTrigger.ts [hunk 1]
```diff
@@ -26,14 +27,13 @@ export default async function (request: EvalWorkerASyncRequest) {
       //TODO: the evalTrigger can be optimised to not diff all JS actions
       { isAllAffected: true, ids: [] },
     );
-
-    dataTreeEvaluator.evalAndValidateSubTree(
-      evalOrder,
-      unEvalTree.configTree,
-      unEvalUpdates,
+    evaluateAndPushUpdatesToMainThread(
```
Comment (rishabhrathod01) [inline app/client/src/workers/Evaluation/handlers/evalTrigger.ts:30]: We should also use this method in evalTree to make it consistent all over the place.

File: app/client/src/workers/Evaluation/evalTreeWithChanges.ts [hunk 2]
```diff
@@ -1,110 +1,165 @@
...
   const allUnevalUpdates = unEvalUpdates.map(
     (update) => update.payload.propertyPath,
   );
-  const completeEvalOrder = uniqueOrderUpdatePaths([
-    ...allUnevalUpdates,
-    ...evalOrder,
-  ]);
+  return uniqueOrderUpdatePaths([...allUnevalUpdates, ...evalOrder]);
+};
+export interface UpdateTreeResponse {
```
Comment (rishabhrathod01) [inline app/client/src/workers/Evaluation/evalTreeWithChanges.ts:75]: Move types either above the code or in separate file.

File: app/client/src/workers/Evaluation/handlers/evalTrigger.ts (hunk 1 above)
Comment (vsvamsi1) [reply app/client/src/workers/Evaluation/handlers/evalTrigger.ts:30]: Sure can we do this in a follow up PR since the evalTree code flow is slightly different? We can initially limit any possible issue to the evalTrigger and evalTreeWithChanges flow.

File: app/client/src/workers/Evaluation/evalTreeWithChanges.ts (hunk 2 above)
Comment (vsvamsi1) [reply app/client/src/workers/Evaluation/evalTreeWithChanges.ts:75]: Sure moved the type into the types file

File: app/client/src/workers/Evaluation/evalTreeWithChanges.ts [hunk 3]
```diff
@@ -1,110 +1,160 @@
...
-      unEvalUpdates,
-    );
+  const setterAndLocalStorageUpdatePaths = uniqueOrderUpdatePaths(
+    updatedValuePaths.map((val) => val.join(".")),
+  );
 
-    dataTree = makeEntityConfigsAsObjProperties(dataTreeEvaluator.evalTree, {
-      evalProps: dataTreeEvaluator.evalProps,
-    });
+  evaluateAndPushUpdatesToMainThread(
```
Comment (rishabhrathod01) [inline app/client/src/workers/Evaluation/evalTreeWithChanges.ts:47]: We plan to make evaluation code platform agnostic ( browser / nodejs ) and hence we avoid naming functions or variables with browser terms like mainThread or worker, could we follow the same practice here too?

File: app/client/src/workers/Evaluation/handlers/evalTrigger.ts [hunk 4]
```diff
@@ -1,6 +1,7 @@
 import { dataTreeEvaluator } from "./evalTree";
 import type { EvalWorkerASyncRequest } from "../types";
 import ExecutionMetaData from "../fns/utils/ExecutionMetaData";
+import { evaluateAndPushResponse } from "../evalTreeWithChanges";
```
Comment (rishabhrathod01) [inline app/client/src/workers/Evaluation/handlers/evalTrigger.ts:4]: In the next PR, could we move the evaluateAndPushResponse to separate file itself.

**Review by rishabhrathod01 — APPROVED** [review]
LGTM

File: app/client/src/workers/Evaluation/helpers.ts [hunk 5]
```diff
@@ -383,13 +383,13 @@ export const generateOptimisedUpdatesAndSetPrevState = (
   mergeAdditionalUpdates?: any,
 ) => {
   const { error, serialisedUpdates } = generateSerialisedUpdates(
-    dataTreeEvaluator.getPrevState(),
+    dataTreeEvaluator?.getPrevState() || {},
```
Comment (rajatagrawal) [inline app/client/src/workers/Evaluation/helpers.ts:386]: why is `dataTreeEvaluator` optional ?

**Review by rajatagrawal — APPROVED** [review]

File: app/client/src/workers/Evaluation/handlers/evalTrigger.ts (hunk 4 above)
Comment (vsvamsi1) [reply app/client/src/workers/Evaluation/handlers/evalTrigger.ts:4]: Sure
