### PR TITLE
fix: Update render logic of switch environment component

### LINKED ISSUE #26880: [Feature]: Hide env dropdown in view mode if there's only one env enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Proposed changes for visibility of env switch dropdown

- for edit mode, we’ll show dropdown if user has access to one or more envs.
     - In case of one env access, the dropdown will be disabled
- In view mode
     - Dropdown is visible and enabled only if user has access to two or more envs
     - If the user has access to only one env and that env is production, the dropdown will be hidden
     - If the user has access to only one env and that env is the default env(in this case production), the dropdown will be hidden
     - If the user has access to only one env and that env is not the default env(in this case staging), the dropdown will be shown but disabled

### Why should this be worked on?

The env dropdown in view mode is not helpful in cases when only one env is there so we need to hide it.

### PR DESCRIPTION
**Pull request by ChandanBalajiBP**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.
>
#### PR fixes following issue(s)
Fixes #26880 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)
- This change requires a documentation update
>
>
>
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress
>
>
#### Test Plan
EEDP

1. Test the Switch Env dropdown by logging in with a user with only Production access on an application - in Edit mode
2. Test the Switch Env dropdown by logging in with a user with only Production access on an application - in Preview mode
3. Test the Switch Env dropdown by logging in with a user with only Production access on an application - Deploy mode
4. Test the Switch Env dropdown by logging in with a user with only Staging access on an application - in Edit mode
5. Test the Switch Env dropdown by logging in with a user with only Staging access on an application - in Preview mode
6. Test the Switch Env dropdown by logging in with a user with only Staging access on an application - in Deploy mode
7. Above scenarios by clicking Launch - same behaviour should exist as Deploy mode.
8. Make application public - and ensure no bottom bar or dropdown is seen 
9. Signup with a non appsmith user and ensure we can see the dropdown and the Ramps properly

>
>
#### Issues raised during DP testing
https://github.com/appsmithorg/appsmith/pull/27043#issuecomment-1717495254
>
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/ce/reducers/environmentReducer.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// Type for one environment
+export interface EnvironmentType {
+  id: string;
+  name: string;
+  workspaceId: string;
+  isDefault?: boolean;
+  userPermissions?: string[];
+}
```
Comment (ankitakinger) [inline app/client/src/ce/reducers/environmentReducer.ts:8]: can we not add a type file instead of adding simply this in a reducer? We could re-use that type on EE as well.

Comment (ChandanBalajiBP) [reply app/client/src/ce/reducers/environmentReducer.ts:8]: Yep this will be better implementation. I will update.

File: app/client/src/components/BottomBar/index.tsx [hunk 2]
```diff
@@ -25,7 +29,23 @@ const Wrapper = styled.div`
...
 
-export default function BottomBar({ viewMode }: { viewMode: boolean }) {
+function BottomBar({
+  environmentList,
+  viewMode,
+}: {
+  environmentList: Array<EnvironmentType>;
+  viewMode: boolean;
+}) {
+  // skip the render if no environments are present in view mode
```
Comment (ayushpahwa) [inline app/client/src/components/BottomBar/index.tsx:39]: The render logic is also handled in the appviewer file. We also need to account for the ramps visibility in case the feature is disabled. Will it make sense to collate everything in one place only. Since bottom bar is called in 2 places, it would be better to include that logic to this file only

**Review by ayushpahwa — CHANGES_REQUESTED** [review]

File: app/client/src/ee/reducers/environmentReducer.ts [hunk 3]
```diff
@@ -0,0 +1 @@
+export * from "ce/reducers/environmentReducer";
```
Comment (ankitakinger) [inline app/client/src/ee/reducers/environmentReducer.ts:1]: Why is this file not part of your CE PR? Your import will not work correctly on CE if this is not added there.

**Review by ankitakinger — CHANGES_REQUESTED** [review]
Comment added on one file

File: app/client/src/ee/reducers/environmentReducer.ts (hunk 3 above)
Comment (ChandanBalajiBP) [reply app/client/src/ee/reducers/environmentReducer.ts]: Updated

File: app/client/src/components/BottomBar/index.tsx (hunk 2 above)
Comment (ChandanBalajiBP) [reply app/client/src/components/BottomBar/index.tsx]: Updated

**Comment by btsgh** [comment]
1. When a non appsmith user logs in - this is what is observed. This behavior is incorrect
https://github.com/appsmithorg/appsmith/assets/101863839/24a91705-8acf-4e50-8f82-2b2d04875b17

**Review by ankitakinger — APPROVED** [review]

**Review by ayushpahwa — APPROVED** [review]

**Review by jsartisan — DISMISSED** [review]

**Review by ayushpahwa — APPROVED** [review]
Re-approving since last change was release merge

**Comment by ayushpahwa** [comment]
Adding test plan label post testing by @riteshkew and me. cc: @btsgh
