### PR TITLE
fix: props is now required in type Validator

### LINKED ISSUE #10850: [Task]: Revert changes in validation function typescript signature.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The typing of the validator function was modified in this [PR](https://github.com/appsmithorg/appsmith/pull/10457/files) where the `props` parameter was made optional.
https://github.com/appsmithorg/appsmith/blob/9d1a5ba92b69ffc58e6211d16def863026592553/app/client/src/constants/WidgetValidation.ts#L31

This needs to be reverted to make it a required parameter to the function as we need to make sure `props` are always available for the validator functions.

### PR DESCRIPTION
**Pull request by rashmi-rai**
## Description
This PR updates typescript interface `Validator`, makes `props` required from optional. We are doing so in order ensure that props is passed for `ValidationTypes.FUNCTION`. 

Fixes #10850 

## How Has This Been Tested?

Not required.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/10850-make-props-required 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.95 **(0.01)** | 36.4 **(0.01)** | 34.61 **(0)** | 55.36 **(0.01)**
 :green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**</details>

### CODE REVIEW

File: app/client/src/workers/validations.ts [hunk 1]
```diff
@@ -589,7 +589,7 @@ export const VALIDATORS: Record<ValidationTypes, Validator> = {
   [ValidationTypes.ARRAY]: (
     config: ValidationConfig,
     value: unknown,
-    props?: Record<string, unknown>,
+    props: Record<string, unknown>,
   ): ValidationResponse => {
     const invalidResponse = {
       isValid: false,
```
Comment (ashit-rath) [inline app/client/src/workers/validations.ts:595]: Can we remove `as Record<string, unknown>` from [line 636](https://github.com/appsmithorg/appsmith/pull/10854/files#diff-e7e2b5776f9525df854356addbab33804e25601da70d2e77697b22ba8f1e1016L636) and [line 646](https://github.com/appsmithorg/appsmith/pull/10854/files#diff-e7e2b5776f9525df854356addbab33804e25601da70d2e77697b22ba8f1e1016L646)?

**Review by ashit-rath — CHANGES_REQUESTED** [review]

File: app/client/src/workers/validations.ts (hunk 1 above)
Comment (rashmi-rai) [reply app/client/src/workers/validations.ts:595]: Done

**Review by ashit-rath — APPROVED** [review]
