### PR TITLE
fix: fix modal position and styles

### LINKED ISSUE #30788: Fix modal widget issues

### PR DESCRIPTION
**Pull request by KelvinOm**
## Description
Fixes for the modal widget:
1. Added support for clickOutside. The modal is closed only by clicking on the backdrop overlay. A click on the widget name has been added to the exceptions for close event.
2. Fixed the positioning of the modal. Now it is located in the center of the provider. 
3. For the correct positioning of the modal, it was necessary to make fixes for canvas height. The fixes also affect fixed and autolayout.

#### PR fixes following issue(s)
Fixes #30788

Also fixed this https://www.notion.so/appsmith/Canvas-gets-cut-off-on-preview-mode-525b95f26c6e4644bf5ab7389c02e434

#### Media

https://github.com/appsmithorg/appsmith/assets/11555074/6db9ecde-595b-4fa4-a21b-9ed08930d58f

- Bug fix (non-breaking change which fixes an issue)
- Chore (housekeeping or task changes that don't impact user perception)
>
>
>
- [x] Manual
- [ ] JUnit
- [x] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **New Features**
	- Popover and Modal components now support dismissing by clicking outside. Custom logic and selectors can be specified to control this behavior.
- **Enhancements**
	- Simplified logic for closing Modals by directly setting open state.
	- Enhanced Modal styling options, allowing for better customization of width and height.
	- ErrorBoundary component now supports custom styles.
- **Refactor**
	- Removed redundant code and unused properties across various components and layout systems.
	- Simplified state management and styling adjustments in editor components.
- **Style**
	- Updated Modal component styles for improved layout and responsiveness.
- **Chores**
	- Codebase cleanup including removal of unused classes, variables, and adjustments for more efficient layout rendering.

### CODE REVIEW

File: app/client/src/layoutSystems/common/mainContainerResizer/MainContainerResizer.tsx [hunk 1]
```diff
@@ -174,8 +170,8 @@ export function MainContainerResizer({
       }}
       ref={ref}
       style={{
-        top: "100%",
-        height: shouldHaveTopMargin ? heightWithTopMargin : "100vh",
+        top: isPreview ? "48px" : "0",
```
Comment (marks0351) [inline app/client/src/layoutSystems/common/mainContainerResizer/MainContainerResizer.tsx:173]: if 48px has some meaning, lets add it as a constant that explains that.

File: app/client/src/pages/Editor/Canvas.tsx [hunk 2]
```diff
@@ -98,21 +94,20 @@ const Canvas = (props: CanvasProps) => {
...
+          renderAppsmithCanvas(props.widgetsStructure as WidgetProps)}
       </Wrapper>
     );
   };
 
   try {
     if (isWDSEnabled) {
       return (
-        <WDSThemeProvider theme={theme}>{renderChildren()}</WDSThemeProvider>
+        <WDSThemeProvider
```
Comment (marks0351) [inline app/client/src/pages/Editor/Canvas.tsx:105]: lets move the styles obj outside as a constant to makes sure new obj is not supplied to WDSThemeProvider on every render.

File: app/client/src/pages/Editor/WidgetsEditor/MainContainerWrapper.tsx [hunk 3]
```diff
@@ -236,7 +209,7 @@ function MainContainerWrapper(props: MainCanvasWrapperProps) {
         isPreviewingNavigation={isPreviewingNavigation}
         navigationHeight={navigationHeight}
         style={{
```
Comment (marks0351) [inline app/client/src/pages/Editor/WidgetsEditor/MainContainerWrapper.tsx:211]: lets add a constant for 40px explaining it.

File: app/client/src/pages/Editor/WidgetsEditor/index.tsx [hunk 4]
```diff
@@ -218,9 +223,20 @@ function WidgetsEditor() {
               isPreview={isPreviewMode || isProtectedMode}
               isPublished={isPublished}
               sidebarWidth={isPreviewingNavigation ? sidebarWidth : 0}
+              style={
```
Comment (marks0351) [inline app/client/src/pages/Editor/WidgetsEditor/index.tsx:226]: lets add these objects as constants to avoid rendering while parent renders.

**Review by marks0351 — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Editor/WidgetsEditor/MainContainerWrapper.tsx (hunk 3 above)
Comment (KelvinOm) [reply app/client/src/pages/Editor/WidgetsEditor/MainContainerWrapper.tsx:212]: Fixed

File: app/client/src/layoutSystems/common/mainContainerResizer/MainContainerResizer.tsx (hunk 1 above)
Comment (KelvinOm) [reply app/client/src/layoutSystems/common/mainContainerResizer/MainContainerResizer.tsx]: Fixed

File: app/client/src/pages/Editor/WidgetsEditor/index.tsx (hunk 4 above)
Comment (KelvinOm) [reply app/client/src/pages/Editor/WidgetsEditor/index.tsx:226]: Wrapped styles in styled-components.

File: app/client/src/pages/Editor/Canvas.tsx (hunk 2 above)
Comment (KelvinOm) [reply app/client/src/pages/Editor/Canvas.tsx]: Creating a constant for an object will not do anything, since an object is a reference type. Wrapped styles in styled-components.

Comment (marks0351) [reply app/client/src/pages/Editor/Canvas.tsx]: This works too 👍🏽. just to understand why wont creating an object outside of the component work?

**Review by marks0351 — DISMISSED** [review]

File: app/client/src/pages/Editor/Canvas.tsx (hunk 2 above)
Comment (KelvinOm) [reply app/client/src/pages/Editor/Canvas.tsx]: Because for a component, it will always be a new object anyway. React compares only primitives. To compare objects, you need a deep comparison of what the React does not do. Such an expression `a = {} ; a === {}` will return `false`.

File: app/client/src/pages/Editor/WidgetsEditor/index.tsx [hunk 5]
```diff
@@ -218,9 +223,20 @@ function WidgetsEditor() {
...
+                isAnvilLayout
+                  ? {
+                      //This is necessary in order to place WDS modal with position: fixed; relatively to the canvas.
+                      transform: "scale(1)",
```
[the remark this answers is not in the document]
Comment (jsartisan) [reply app/client/src/pages/Editor/WidgetsEditor/index.tsx:230]: what scale(1)  do? 🤔

[the remark this answers is not in the document]
Comment (KelvinOm) [reply app/client/src/pages/Editor/WidgetsEditor/index.tsx:230]: The element with a fixed position begins to be positioned relative to the element with this style. I hoped that this would be clear from the comment.

File: app/client/src/pages/Editor/Canvas.tsx (hunk 2 above)
Comment (KelvinOm) [reply app/client/src/pages/Editor/Canvas.tsx]: In this way we are trying to avoid rendering the component that these styles receive, nothing will change for it, it will still compare the objects. But styled components, will simply not change the class name(hash), it will be the same.

**Comment by riodeuno** [comment]
@KelvinOm The changes look fine to me. The areas which are effected and need to be tested:

- Canvas scrolling When banners like the following show up (Editor, Preview and Deployed)
Screenshot 2024-02-05 at 4 53 23 PM
Screenshot 2024-02-05 at 4 55 49 PM

- The Main canvas resizer in AutoLayout.
 
I tested this briefly and found an issue:


https://github.com/appsmithorg/appsmith/assets/103687/94256735-1811-4f38-82a9-7847f0b5e2ae

**Review by jsartisan — DISMISSED** [review]

**Comment by KelvinOm** [comment]
> @KelvinOm The changes look fine to me. The areas which are effected and need to be tested:
> 
> * Canvas scrolling When banners like the following show up (Editor, Preview and Deployed)
>   Screenshot 2024-02-05 at 4 53 23 PM
>   Screenshot 2024-02-05 at 4 55 49 PM
> * The Main canvas resizer in AutoLayout.
> 
> I tested this briefly and found an issue:
> 
>  Screen.Recording.2024-02-05.at.4.58.59.PM.mov

Checked and fixed the behavior you mentioned.

https://github.com/appsmithorg/appsmith/assets/11555074/ab99d5f3-4613-4ebb-9460-4fb2ffc96da6

**Review by riodeuno — APPROVED** [review]
