### PR TITLE
fix: disable sorting in view mode

### LINKED ISSUE #5640: Disable sorting for end-user view mode(required when sorting will mess up the row order)

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

disable sorting in view mode

Fixes #5640

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/disable-sorting-in-view-mode 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.9 **(0.01)** | 36.6 **(0.02)** | 33.62 **(0.01)** | 55.44 **(0.01)**
 :green_circle: | app/client/src/utils/DSLMigrations.ts | 73.62 **(0.11)** | 65.14 **(-0.06)** | 70.21 **(0)** | 73.43 **(0.12)**
 :green_circle: | app/client/src/utils/migrations/TableWidget.ts | 84.43 **(0.69)** | 76.32 **(1.04)** | 92.59 **(0.59)** | 86.49 **(0.61)**
 :red_circle: | app/client/src/widgets/TableWidget/component/TableUtilities.tsx | 37.95 **(-0.23)** | 21.62 **(-1.24)** | 16.22 **(0)** | 36.18 **(-0.24)**
 :red_circle: | app/client/src/widgets/TableWidget/component/index.tsx | 27.27 **(0)** | 2.6 **(-0.03)** | 15.79 **(0)** | 25.68 **(0)**
 :green_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 26.49 **(0)** | 6.09 **(0.81)** | 28 **(0)** | 26.36 **(0)**</details>

### CODE REVIEW

File: app/client/src/widgets/TableWidget/component/TableUtilities.tsx [hunk 1]
```diff
@@ -526,7 +527,7 @@ export function TableHeaderCell(props: {
     <div
       {...column.getHeaderProps()}
       className="th header-reorder"
-      onClick={handleSortColumn}
+      onClick={props.editMode !== false ? handleSortColumn : undefined}
```
Comment (SatishGandham) [inline app/client/src/widgets/TableWidget/component/TableUtilities.tsx:530]: Can we not write this as       `onClick={props.editMode ? handleSortColumn : undefined}`

Also, won't this disable sorting in view mode completely?

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/TableWidget/component/TableUtilities.tsx (hunk 1 above)
Comment (Tooluloope) [reply app/client/src/widgets/TableWidget/component/TableUtilities.tsx:530]: @SatishGandham , I think the issue is to disable sorting in view mode.

Comment (SatishGandham) [reply app/client/src/widgets/TableWidget/component/TableUtilities.tsx:530]: Issue says when it can break the table, so there should be an option to disable sorting.
Do we store sorting state in the edit mode when we sort columns?

Comment (Tooluloope) [reply app/client/src/widgets/TableWidget/component/TableUtilities.tsx:530]: Oh, So just a switch in the property pane.
Shouldn't we just tackle why the table breaks, cos users might not know the real reason for disabling sorting

**Comment by somangshu** [comment]
@Tooluloope the sorting disabled needs to be a configurable option, The dev can choose to do so for the end user. Hence, we need to provide the option to do so from the property pane

File: app/client/src/widgets/TableWidget/component/TableUtilities.tsx [hunk 2]
```diff
@@ -517,12 +519,15 @@ export function TableHeaderCell(props: {
       props.isAscOrder === undefined ? false : !props.isAscOrder;
     props.sortTableColumn(columnIndex, sortOrder);
   };
+  const disableSort = useMemo(() => {
```
Comment (SatishGandham) [inline app/client/src/widgets/TableWidget/component/TableUtilities.tsx:522]: We don't need a memo here. It is only required it is going to return a new object with same value or if we are doing expensive calculations. 
Here it is a primitive value.

Comment (SatishGandham) [reply app/client/src/widgets/TableWidget/component/TableUtilities.tsx]: I don't see any changes?

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/src/widgets/TableWidget/component/TableUtilities.tsx (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/widgets/TableWidget/component/TableUtilities.tsx]: @SatishGandham I have removed it.
Not sure why github still showing this on your end
Screenshot 2021-10-01 at 07 49 50

**Review by SatishGandham — DISMISSED** [review]

**Comment by Tooluloope** [comment]
@YogeshJayaseelan Fixed

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified the fix and the sorting toggle is working as expected

**Review by SatishGandham — DISMISSED** [review]

File: app/client/src/utils/DSLMigrations.ts [hunk 3]
```diff
@@ -975,6 +976,10 @@ export const transformDSL = (
     currentDSL = mapAllowHorizontalScrollMigration(currentDSL);
     currentDSL.version = LATEST_PAGE_VERSION;
```
Comment (riodeuno) [inline app/client/src/utils/DSLMigrations.ts:977]: This needs to change to 44 from `LATEST_PAGE_VERSION`

**Review by riodeuno — CHANGES_REQUESTED** [review]

**Comment by riodeuno** [comment]
@Tooluloope I have one change requested. I believe @SatishGandham has already reviewed, this so I'll remove myself from the reviewers list.

File: app/client/src/utils/DSLMigrations.ts [hunk 4]
```diff
@@ -975,6 +976,10 @@ export const transformDSL = (
...
   }
+  if (currentDSL.version === 44) {
```
Comment (Tooluloope) [inline app/client/src/utils/DSLMigrations.ts:979]: @riodeuno we're using 44 here already

**Review by SatishGandham — APPROVED** [review]
