### PR TITLE
fix: curl import empty headers issue fixed

### LINKED ISSUE #19214: [Bug]: On creating api using curl command, Key and Value fields are not present under headers tab
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating api using curl command, Key and Value fields do not show up
Screenshot 2022-12-26 at 3 22 53 PM

 

### Steps To Reproduce

1.Import from curl for this command curl -X GET https://mock-api.appsmith.com/users
2. Observe on api editor, Key and Value options are not present

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by sneha122**
## Description
This PR fixes:
- When we import api request using curl and if api request does not have any header values, the imported request looks like below, empty key value headers are missing.
Screenshot 2023-06-02 at 1 30 34 PM

#### PR fixes following issue(s)
Fixes #19214 
> if no issue exists, please create an issue and ask the maintainers about this first
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Test-plan-implementation#speedbreaker-features-to-consider-for-every-change) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans/_edit#areas-of-interest)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by sumitsum — APPROVED** [review]

**Comment by sumitsum** [comment]
Server side changes LGTM.

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/CurlImportFlow_spec.js [hunk 1]
```diff
@@ -63,4 +63,22 @@ describe("Test curl import flow", function () {
...
+          force: true,
+          parseSpecialCharSequences: false,
+        },
+      );
+      cy.importCurl();
+      _.apiPage.AssertEmptyHeaderKeyValuePairsPresent(0);
+      _.apiPage.AssertEmptyHeaderKeyValuePairsPresent(1);
+    });
+  });
 });
```
Comment (Parthvi12) [inline app/client/cypress/e2e/Regression/ServerSide/ApiTests/CurlImportFlow_spec.js:84]: @sneha122 Going forward we are writing all tests in .ts, can you please change this test also from js to ts?

Comment (Parthvi12) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/CurlImportFlow_spec.js:84]: Had a chat with Sneha and we are planning to convert this test to ts later. 
CC @Aishwarya-U-R  Can this be merged?

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/CurlImportFlow_spec.js:84]: @sneha122 Why later? I see test is small. Convert this to TS now, run locally & let me know. We can merge it. No need of CI run.

Comment (sneha122) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/CurlImportFlow_spec.js:84]: @Aishwarya-U-R The spec file was created before, I have simply added 3rd test block in it, Since the code changes done in PR are small, do not want to cause any issues in other 2 tests which have been there from before.

Comment (sneha122) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/CurlImportFlow_spec.js:84]: okay sure thanks I thought would need to change whole spec file, thanks will make the updates

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/CurlImportFlow_spec.js:84]: Yes, previously when I mentioned test being small - I referred only to new test :) Please do!
