### PR TITLE
chore: fix table with and without connected data have different heights

### LINKED ISSUE #33758: [Bug]: Table with and without connected data have different heights
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Table with and without connected data have different heights

### Steps To Reproduce

image

### Public Sample App

_No response_

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

_No response_

### Version

cloud

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #33758

/ok-to-test tags="@tag.Anvil"
> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9267730971>
> Commit: 5305b21086cc8965be0f9159d11ebeadf2503878
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9267730971&attempt=1" target="_blank">Click here!</a>

### CODE REVIEW

File: app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/EmptyCell.tsx [hunk 1]
```diff
@@ -153,13 +158,16 @@ export const renderEmptyRows = (
                     ? "td hidden-cell"
                     : `td${addStickyModifierClass(columns, colIndex)}`
                 }
-                role="cell"
+                role={isHeaderRow ? "columnheader" : "cell"}
```
Comment (jsartisan) [inline app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/EmptyCell.tsx:161]: Need to add `role="columnheader"` in case of header cell so that our CSS properly selects thead's cells.

File: app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/EmptyCell.tsx [hunk 2]
```diff
@@ -153,13 +158,16 @@ export const renderEmptyRows = (
...
                 {...stickyAttributes}
+                data-column-type="text"
                 key={colIndex}
                 sticky={column?.sticky ?? StickyType.NONE}
                 style={{ ...distanceFromEdge }}
                 width={column.width}
-              />
+              >
+                <Text data-empty-text="">&#8203;</Text>
```
Comment (jsartisan) [inline app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/EmptyCell.tsx:169]: Need to Text component so that height of the empty cell is same as the filled one.

File: app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/EmptyCell.tsx [hunk 3]
```diff
@@ -74,13 +76,16 @@ export const renderEmptyRows = (
                       ? "td hidden-cell"
                       : `td${addStickyModifierClass(columns, cellIndex)}`
                   }
+                  data-column-type="text"
```
Comment (jsartisan) [inline app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/EmptyCell.tsx:79]: need to add this attribute so that our css picks this element to style.

**Review by KelvinOm — COMMENTED** [review]
@jsartisan Why do we need all these changes if we plan to add the default data into the table? All this code for an empty table should go away, right?

**Comment by jsartisan** [comment]
> @jsartisan Why do we need all these changes if we plan to add the default data into the table? All this code for an empty table should go away, right?

@KelvinOm Right but this changes also makes sense for deploy mode so that empty table is of same height. It's not just for edit mode.

**Comment by KelvinOm** [comment]
> > @jsartisan Why do we need all these changes if we plan to add the default data into the table? All this code for an empty table should go away, right?
> 
> @KelvinOm Right but this changes also makes sense for deploy mode so that empty table is of same height. It's not just for edit mode.

So if we have default data, they will also displayed in deploy mode, we should not have a case with an empty table. Or am I missing something?

**Comment by jsartisan** [comment]
> > > @jsartisan Why do we need all these changes if we plan to add the default data into the table? All this code for an empty table should go away, right?
> > 
> > @KelvinOm Right but this changes also makes sense for deploy mode so that empty table is of same height. It's not just for edit mode.
> 
> So if we have default data, they will also displayed in deploy mode, we should not have a case with an empty table. Or am I missing something? 

Consider a table that is binded with a data source and and data is empty from it.

**Review by KelvinOm — APPROVED** [review]
