### PR TITLE
fix: Analytics events not fired during export application

### LINKED ISSUE #28369: Fix failing tests in audit log service
One unit tests is failing in the audit log service for export application

### PR DESCRIPTION
**Pull request by nayan-rafiq**
#### PR fixes following issue(s)
Fixes #28369

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [ ] JUnit

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by nidhi-nair — APPROVED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/ExportApplicationServiceCEImpl.java [hunk 1]
```diff
@@ -312,25 +307,25 @@ public Mono<ExportFileDTO> getApplicationFile(String applicationId, String branc
...
-                final Map<String, Object> data = Map.of(
-                        FieldName.APPLICATION_ID, application.getId(),
-                        FieldName.WORKSPACE_ID, workspace.getId(),
-                        FieldName.EVENT_DATA, eventData);
-
-                return analyticsService.sendObjectEvent(event, application, data);
-            });
-        });
+            Mono<String> applicationIdMono, AnalyticsEvents event) {
+        return applicationIdMono.flatMap(applicationService::findById).flatMap(application -> workspaceService
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/ExportApplicationServiceCEImpl.java:316]: @nayan-rafiq Why are we having to call the DB again? Could you please help understand?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/ExportApplicationServiceCEImpl.java [hunk 2]
```diff
@@ -120,11 +121,20 @@ public Mono<ApplicationJson> exportApplicationById(
                         })
                         .cache();
 
+        /*
+         * We need to cache the applicationMono because the application object inside the applicationMono will be
+         * updated in the subsequent steps. We need to use the original application object for analytics.
+         */
+        Mono<String> cachedApplicationIdMono =
+                applicationMono.map(BaseDomain::getId).cache();
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/ExportApplicationServiceCEImpl.java:129]: We already have a method level variable `applicationId`, can we use the same instead of wrapping this inside Mono?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/ExportApplicationServiceCEImpl.java [hunk 3]
```diff
@@ -174,12 +184,12 @@ public Mono<ApplicationJson> exportApplicationById(
...
-                    analyticsService.sendEvent(
-                            AnalyticsEvents.UNIT_EXECUTION_TIME.getEventName(), user.getUsername(), data);
-                    return applicationJson;
+                    return analyticsService
+                            .sendEvent(AnalyticsEvents.UNIT_EXECUTION_TIME.getEventName(), user.getUsername(), data)
+                            .thenReturn(applicationJson);
                 })
-                .then(applicationMono)
-                .map(application -> sendImportExportApplicationAnalyticsEvent(application, AnalyticsEvents.EXPORT))
+                .flatMap(unused ->
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/ExportApplicationServiceCEImpl.java:191]: Should we move this call after the `sendEvent` to merge the analytics events within a single flatmap?

**Review by abhvsn — COMMENTED** [review]
Minor comments on code structure, from functionality POV LGTM.
