### PR TITLE
fix: hide explorer menu on scroll

### LINKED ISSUE #15474: [Bug]-[5000]:Entity explorer pop-up behaviour is incorrect when scrolling through on the explorer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the hamburger icon is clicked next to a query/widget and a datasource is expanded to display all it's tables as seen in the video then scrolling on the entity explorer causes the pop-up to scroll with the explorer and sometimes add an unnecessary scroll on the canvas

### Steps To Reproduce

1. Click on the hamburger icon next to a mongo query
2. Expand it's datasource so you can see all it's tables
3. Now scroll in both directions on the entity explorer and observe that the pop-over persists on screen and it's behaviour is incorrect in both directions as seen in the video (moving upward causes pop-over to colliade with pages and other irrelevant entities on the explorer and moving downward causes an extra scroll to appear)

https://www.loom.com/share/81ae4909ad304ec4a5928ad837e298af

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by akash-codemonk**
## Description

Hides the explorer menu on scroll

Fixes #15474

Release

https://user-images.githubusercontent.com/67054171/182078934-823e8f0a-1b31-4bb0-b5ae-2315bad4cb9d.mov

Post fix

https://user-images.githubusercontent.com/67054171/182078989-d1ee0942-bdcd-4b0b-9b86-7ca556b33bd0.mov

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/pages/Editor/Explorer/hooks.ts [hunk 1]
```diff
@@ -396,3 +397,17 @@ export function useActiveAction() {
     return saasMatch.params.apiId;
   }
 }
+
+export const useCloseMenuOnScroll = (open: boolean, onClose: () => void) => {
+  const sidebar = document.getElementById(SIDEBAR_ID);
```
Comment (hetunandu) [inline app/client/src/pages/Editor/Explorer/hooks.ts:402]: This id could be passed as an argument and then the hook could be used for other elements as well

**Review by hetunandu — APPROVED** [review]
