### PR TITLE
FIX #6193 : bind enter and tab key on color picker input to close color board

### LINKED ISSUE #6193: [Bug] Colour selector must exit after pressing on the Enter or Tab key
## Description
Colour selector on widgets to be more keyboard friendly and should exit when user hits **Enter** or **Tab** key. Currently user needs to move cursor to exit the default colour selection panel. In the meanwhile if user users **Tab** to move control then information is overlapped and input fields are blocked

### Steps to reproduce the behaviour:
1. Enter colour name/code into input field
2. Hit **Enter** - colour selction panel should exit but remains on screen
3. Press **Tab** - colour selection panel should exit but causes information text to overlap and input fields being blocked

### Important Details

- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: RC and Production

[LOOM DEMO](https://www.loom.com/share/bec2756012f349b4b3ecf382ffe47052)

### PR DESCRIPTION
**Pull request by vibhandikyash**
## Description

> Binding Enter and Tab Key on color picker and close color popup.

Fixes #6193 

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

> Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: FEATURE/6193-binding-key-events-color-picker 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 54.6 **(-0.02)** | 36.68 **(-0.01)** | 33.03 **(-0.02)** | 55.21 **(-0.01)**
 :red_circle: | app/client/src/components/ads/ColorPickerComponent.tsx | 28.57 **(-9.27)** | 58.33 **(-5.31)** | 0 **(0)** | 31.82 **(-8.18)**</details>

### CODE REVIEW

**Comment by somangshu** [comment]
@ramsaptami can you test this deploy preview and give us a signoff

File: app/client/src/components/ads/ColorPickerComponent.tsx [hunk 1]
```diff
@@ -186,6 +189,11 @@ function ColorPickerComponent(props: ColorPickerProps) {
           )
         }
         onChange={handleChangeColor}
+        onKeyDown={(e) => {
+          if ((e.key === "Enter" || e.key === "Tab") && isPopoverOpen) {
```
Comment (SatishGandham) [inline app/client/src/components/ads/ColorPickerComponent.tsx:193]: isPopoverOpen check in the if is not required. Since it is a primitive value change from false -> false doesn't trigger a render as well.

**Review by SatishGandham — CHANGES_REQUESTED** [review]

**Comment by ramsaptami** [comment]
Tested and ok on deploy preview

**Review by SatishGandham — DISMISSED** [review]

**Comment by somangshu** [comment]
@vibhandikyash please merge latest release here, Failing test fix is available here.

Also do request for a review as /ok-to-test is not fully functional right now

**Review by somangshu — APPROVED** [review]

**Comment by somangshu** [comment]
There is an issue in the DP
- Focus on the colour picker field
- type a colour ex: red
- Press tab

It is observed that the colour picker of the previous input/field opens, and then if we press shift + tab another colour picker opens.


https://user-images.githubusercontent.com/11089579/128358463-5437baf8-4b0d-4363-b030-351363f4634e.mov

**Review by somangshu — APPROVED** [review]
LGTM, Deploy preview also works well now

File: app/client/src/components/ads/ColorPickerComponent.tsx [hunk 2]
```diff
@@ -176,22 +178,36 @@ function ColorPickerComponent(props: ColorPickerProps) {
...
-            <NoColorIconWrapper>
+            <NoColorIconWrapper onClick={() => setOpen(true)}>
               <NoColorIcon>
                 <div className="line" />
               </NoColorIcon>
             </NoColorIconWrapper>
           )
         }
+        onBlur={() => {
+          // if user clicks on ColorBoard blur is called first and color is not updated
```
Comment (SatishGandham) [inline app/client/src/components/ads/ColorPickerComponent.tsx:191]: I don't see why this is required. Looks like a hacky solution to whatever problem we are solving.

File: app/client/src/components/ads/ColorPickerComponent.tsx [hunk 3]
```diff
@@ -176,22 +178,36 @@ function ColorPickerComponent(props: ColorPickerProps) {
...
+          // to prevent that make sure to wait for color update before onBlur
+          setTimeout(() => {
+            setOpen(false);
+          }, 100);
+        }}
         onChange={handleChangeColor}
+        onFocus={() => setOpen(true)}
+        onKeyUp={(e) => {
+          if (e.key === "Enter") {
```
Comment (SatishGandham) [inline app/client/src/components/ads/ColorPickerComponent.tsx:200]: @somangshu  Should we also include tab here?
If I focus a color picker input and use tab to navigate to next input, the picker is not closed.

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/src/components/ads/ColorPickerComponent.tsx (hunk 2 above)
Comment (vibhandikyash) [reply app/client/src/components/ads/ColorPickerComponent.tsx:191]: @SatishGandham This is because when we click on the popover to pick a color the blur function is called first and then the click event which prevents it from setting the color. That's why I had to put this setTimeout which allows the click event to set it first and then close.

**Comment by vibhandikyash** [comment]
@SatishGandham As discussed yesterday on the call. Can you pl. update here?

File: app/client/src/components/ads/ColorPickerComponent.tsx (hunk 3 above)
Comment (somangshu) [reply app/client/src/components/ads/ColorPickerComponent.tsx:205]: @SatishGandham that sounds right. As far as the deploy preview is concerned the color picker closes where the next input is focused using tab, Do you see some other behaviour? I am not sure if i am getting this correctly

Comment (vibhandikyash) [reply app/client/src/components/ads/ColorPickerComponent.tsx:205]: @somangshu I had a word with @SatishGandham about the same. The Keyup will not detect tab because its not happening no its focus. That's why we have to use the onBlur event.

**Review by SatishGandham — APPROVED** [review]

**Comment by somangshu** [comment]
@SatishGandham what is pending here? I have missed the trail

**Review by somangshu — APPROVED** [review]

**Comment by vivekverma2312** [comment]
@vibhandikyash Tested the DP and working fine
