### PR TITLE
BUG : Iframe widget: wrong placeholder `Title`

### LINKED ISSUE #5975: [Bug] iFrame widget: wrong placeholder `Title`
## Description

The title field in the iframe property pane is not correct `Enter the title for the` should be `Enter the title for iFrame element`

Screenshot 2021-07-19 at 7 14 12 PM

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- Fix typo on the placeholder text of the title property

Fixes #5975 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:white_circle: Total coverage has not changed</summary>
No changes to code coverage between the base branch and the head branch</details>

### CODE REVIEW

File: app/client/src/widgets/IframeWidget.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ class IframeWidget extends BaseWidget<IframeWidgetProps, WidgetState> {
             helpText: "Label the content of the page to embed",
             label: "Title",
             controlType: "INPUT_TEXT",
-            placeholderText: "Enter the title of the page to embed",
+            placeholderText: "Enter the title for iframe element",
```
Comment (somangshu) [inline app/client/src/widgets/IframeWidget.tsx:31]: This will still overflow, Lets change it to > `Title for iframe element`

**Review by somangshu — CHANGES_REQUESTED** [review]

**Review by somangshu — APPROVED** [review]
LGTM
