### PR TITLE
fix: disable main js rename from entity pane

### LINKED ISSUE #32275: [Task - Client]: Renaming of JS objects isn't happening properly from all the places.

### PR DESCRIPTION
**Pull request by ayushpahwa**
## Description
Updated the condition to prevent main JS function rename from entity list

Fixes #32275 

## Automation

/ok-to-test tags="@tag.Sanity, @tag.IDE"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8967754921>
> Commit: 9c3f85291a40460a4e7566ae7591308634c4048c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8967754921&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by ankitakinger — DISMISSED** [review]
LGTM

File: app/client/src/pages/Editor/Explorer/Entity/index.tsx [hunk 1]
```diff
@@ -363,7 +363,7 @@ export const Entity = forwardRef(
           alwaysShowRightIcon={props.alwaysShowRightIcon}
           className={`${props.highlight ? "highlighted" : ""} ${
             props.active ? "active" : ""
-          } t--entity-item`}
+          } ${canEditEntityName ? "editable" : ""} t--entity-item`}
```
Comment (hetunandu) [inline app/client/src/pages/Editor/Explorer/Entity/index.tsx:366]: Please use the `classNames` utility function here

File: app/client/src/pages/Editor/Explorer/JSActions/JSActionEntity.tsx [hunk 2]
```diff
@@ -92,7 +92,9 @@ export const ExplorerJSCollectionEntity = memo(
       <Entity
         action={navigateToJSCollection}
         active={props.isActive}
-        canEditEntityName={canManageJSAction}
+        canEditEntityName={
+          canManageJSAction && !Boolean(jsAction?.isMainJSCollection)
```
Comment (hetunandu) [inline app/client/src/pages/Editor/Explorer/JSActions/JSActionEntity.tsx:96]: `isMainJSCollection` is a EE concept right? Do we want to expose it out here?

Comment (ayushpahwa) [reply app/client/src/pages/Editor/Explorer/JSActions/JSActionEntity.tsx:96]: isMainJSCollection is currently used only for workflows (only set by server during workflows creation) but doesn't seem to be an issue to include it in CE also. This is in case it might be re-used for a CE use case.

File: app/client/src/pages/Editor/Explorer/Entity/index.tsx (hunk 1 above)
Comment (ayushpahwa) [reply app/client/src/pages/Editor/Explorer/Entity/index.tsx]: Updated

File: app/client/src/pages/Editor/Explorer/Entity/index.tsx [hunk 3]
```diff
@@ -361,9 +362,12 @@ export const Entity = forwardRef(
...
           alwaysShowRightIcon={props.alwaysShowRightIcon}
-          className={`${props.highlight ? "highlighted" : ""} ${
-            props.active ? "active" : ""
-          } t--entity-item`}
+          className={classNames(
+            props.highlight && "highlighted",
+            props.active && "active",
+            canEditEntityName && "editable",
+            "t--entity-item",
+          )}
```
Comment (hetunandu) [inline app/client/src/pages/Editor/Explorer/Entity/index.tsx:370]:
```suggestion
          className={classNames({
            highlighted: props.highlight,
            active: props.active,
            editable: props.editable,
            t--entity-item: true, 
          })}
```

Comment (hetunandu) [reply app/client/src/pages/Editor/Explorer/Entity/index.tsx:370]: This makes it more readable

**Review by hetunandu — APPROVED** [review]
