### PR TITLE
fix: handle empty column name in UQI sort component

### LINKED ISSUE #10896: [Bug]: handle empty column name in UQI sort component
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sort component introduced as part of UQI currently fails if any of the column names are empty. This is a problem because if a sort component is added to a query editor form then at least one sort component with an empty column gets added by default, which can make the query fail.

### Steps To Reproduce

On release:
- create S3 list query
- don't edit sort component
- execute query will show failure

### Environment

Release

### Version

Cloud

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- The sort component introduced as part of UQI currently fails if any of the column names are empty. This is a problem because if a sort component is added to a query editor form then at least one sort component with an empty column gets added by default, which can make the query fail.
- This PR adds changes to ignore all the empty column names (or ignore the sort conditon if all column names are empty). 

Fixes #10896

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit TC
- Manual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java [hunk 1]
```diff
@@ -310,12 +310,19 @@ private void addProjectionCondition(StringBuilder sb, List<String> projectionCol
...
+         *  o `sortBy` condition list is null or empty
+         *  o all column names in the sortBy list are empty
+         */
+        if (isSortConditionEmpty(sortBy)) {
             return;
         }
 
         sb.append(" ORDER BY");
         sortBy.stream()
+                .filter(sortCondition -> !isBlank(sortCondition.get(SORT_BY_COLUMN_NAME_KEY)))
```
Comment (nidhi-nair) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java:325]: Is this not redundant? If we get to this point we'll already have appended the `ORDER BY` clause.

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java:325]: @nidhi-nair , this is not redundant because at this point we are assured that at least one of the sort component is non-empty so we will process that sort componet while skipping all the other ones.

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java:325]: @nidhi-nair , this is not redundant because at this point we are assured that at least one of the sort component is non-empty so we will process that sort componet while skipping all the other ones.

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java:325]: @nidhi-nair , this is not redundant because at this point we are assured that at least one of the sort component is non-empty so we will process that sort componet while skipping all the other ones.

Comment (sumitsum) [reply app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java:325]: @nidhi-nair , this is not redundant because at this point we are assured that at least one of the sort component is non-empty so we will process that sort componet while skipping all the other ones.

**Review by nidhi-nair — APPROVED** [review]
