### PR TITLE
fix: Fixed corrupt validation error on page reload

### LINKED ISSUE #24664: [Bug]: Evaluation errors don't show up when a page with existing evaluation errors is reloaded
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`__evaluations__` property doesn't have evaluation errors populated in it if a page with existing evaluation errors is reloaded.

### Steps To Reproduce

1. Go to this DP https://appsmith-rl2cnfsls-get-appsmith.vercel.app/applications and DnD chart widget v2
3. In the Chart Dataset field, remove any comma from the json values and introduce a syntax error in that property.
4. Put a debugger in componentDidUpdate and check the props for __evaluation__ key and notice that errors are present.
5. Refresh the page with the syntax errors and check the props again when the breakpoint is hit.
6. Observed behavior : Validation errors are not present in `__evaluations__` field.
7. They are actually present in `'__evaluations__` key.
8. Expected behavior : The evaluation errors should be present in `__evaluations__` key

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
`getValidatedTree` method which gets called during first tree setup sets errors into an invalid location causing the validation error to not show up on page reload. This PR fixes the error location.
>
>
#### PR fixes following issue(s)
Fixes #24664
>
>
>
#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [x] Manual
- [ ] Jest
- [ ] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/workers/common/DataTreeEvaluator/validationUtils.ts [hunk 1]
```diff
@@ -169,10 +168,7 @@ export function getValidatedTree(
           addErrorToEntityProperty({
             errors: evalErrors,
             evalProps,
-            fullPropertyPath: getEvalErrorPath(`${entityKey}.${property}`, {
-              isPopulated: false,
-              fullPath: true,
-            }),
```
Comment (Rishabh-Rathod) [inline app/client/src/workers/common/DataTreeEvaluator/validationUtils.ts:175]: Isn't the default value of the option the same as the one passed here? 
image

Comment (arunvjn) [reply app/client/src/workers/common/DataTreeEvaluator/validationUtils.ts:175]: Not sure if I understand this. Could you please elaborate ? 
I have deleted that code because `addErrorToEntityProperty` expects the property path and not the `evalError` path
