### PR TITLE
fix: Add validation for Git URLs on server

### LINKED ISSUE #12054: [Bug]: Add check for ssh url validation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Current validation for ssh get url is not sufficient for all the edgecases, more discussion can be found https://theappsmith.slack.com/archives/CGALMH6MT/p1647846338879989

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/pull/12004

### Public Sample App

_No response_

### Version

v1.6.17

### PR DESCRIPTION
**Pull request by vishnu-gp**
## Description

This PR adds a backend validation for git URLs on the backend side. Plus added some more test cases for URLs

Fixes #12054

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual via local version of app as well as via Postman API

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java [hunk 1]
```diff
@@ -139,6 +139,7 @@ public enum AppsmithError {
     GENERIC_JSON_IMPORT_ERROR(400, 4049, "Unable to import application in organization {0} with error {1}", AppsmithErrorAction.DEFAULT, null, ErrorType.BAD_REQUEST, null),
     FILE_PART_DATA_BUFFER_ERROR(500, 5017, "Failed to upload file with error: {0}", AppsmithErrorAction.DEFAULT, null, ErrorType.BAD_REQUEST, null),
     MIGRATION_ERROR(500, 5018, "This action is already migrated", AppsmithErrorAction.DEFAULT, null, ErrorType.INTERNAL_ERROR, null),
+    INVALID_GIT_SSH_URL(400, 5019, "Please enter valid SSH URL of your repository", AppsmithErrorAction.DEFAULT, null, ErrorType.GIT_CONFIGURATION_ERROR, null),
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java:142]:
```suggestion
    INVALID_GIT_SSH_URL(400, 4050, "Please enter valid SSH URL of your repository", AppsmithErrorAction.DEFAULT, null, ErrorType.GIT_CONFIGURATION_ERROR, null),
```

**Review by abhvsn — APPROVED** [review]
