### PR TITLE
fix: Optimize reflows on the applications list page

### LINKED ISSUE #16012: [Task]: Optimize reflows on applications list page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We have these two function in utils/helpers.tsx which trigger reflows.

- `isVerticalEllipsisActive`
- `isEllipsisActive`

They are used to decide if we have to show tooltips are not. I don't see the tooltips though.

**Possible solutions**

1. Always show the tooltips.
2. Since these are fixed width divs, make an approximation based on the length of the text.
3. Use the native browser tooltips by providing a title attribute.
4. If we can not remove these functions, make them async and wrap the calculation in `requestAnimationFrame` callback.
5. Figure if a tooltip needs to be shown on demand, that is on hover.?

This saves about 5-8ms per application card. If a user has 40 applications, thats about 300ms saved.

Screenshot 2022-08-15 at 3 45 41 PM

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

> Optimize reflows on the applications list page which is happening due to `isVerticalEllipsisActive` helper function.

Fixes #16012 

## Type of change

- Performance improvement

## How Has This Been Tested?

> Took a performance profile before and after making this change. Could see a difference in rendering time.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SatishGandham — DISMISSED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/UpdateApplication_spec.js [hunk 1]
```diff
@@ -111,6 +111,6 @@ describe("Update Application", () => {
       .first()
       .find(homePage.applicationCardName)
       .trigger("mouseover");
-    cy.get(".bp3-popover-target.bp3-popover-open").should("have.length", 1);
+    cy.get(".bp3-popover-target.bp3-popover-open").should("not.exist");
```
Comment (SatishGandham) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/UpdateApplication_spec.js:114]: Where are we checking that the application name has updated?

**Review by SatishGandham — CHANGES_REQUESTED** [review]

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/UpdateApplication_spec.js (hunk 1 above)
Comment (ankitakinger) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/UpdateApplication_spec.js:114]: I discussed this with @Parthvi12 and since we have removed the tooltip now, she asked me to add the check of it not existing.

**Review by SatishGandham — APPROVED** [review]
