### PR TITLE
Fix/4362 recaptcha field unexpected data types

### LINKED ISSUE #4362: Unexpected data types in the Recaptcha field for buttons breaks the widget
Sentry Issue: [APPSMITH-RR](https://sentry.io/organizations/appsmith/issues/2386220794/?referrer=github_integration)

```
Error: SyntaxError: Failed to execute 'querySelector' on 'Document': 'script[src="https://www.google.com/recaptcha/api.js?render={
  "actionId": "6087b745cc507f406e581b76",
  "name": "Api3",
  "pluginType": "API",
  "config": {
    "timeoutInMillisecond": 1...

SyntaxError: Failed to execute 'querySelector' on 'Document': 'script[src="https://www.google.com/recaptcha/api.js?render={
  "actionId": "6087b745cc507f406e581b76",
  "name": "Api3",
  "pluginType": "API",
  "config": {
    "timeoutInMillisecond": 1...
```

### PR DESCRIPTION
**Pull request by wmdev0808**
## Description
- Add a guard for invalid google recaptcha key

Fixes #4362 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/4362-recaptcha-field-unexpected-data-types 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.6 **(-0.01)** | 32.46 **(-0.01)** | 29.84 **(0)** | 52.08 **(-0.01)**
 :red_circle: | app/client/src/components/designSystems/blueprint/ButtonComponent.tsx | 59.21 **(-6.97)** | 52.73 **(-4.13)** | 66.67 **(-3.33)** | 61.43 **(-7.92)**</details>

### CODE REVIEW

File: app/client/src/components/designSystems/blueprint/ButtonComponent.tsx [hunk 1]
```diff
@@ -180,8 +180,25 @@ function RecaptchaComponent(
...
+      return true;
+    } catch (err) {
+      return false;
+    }
+  };
+
+  let validGoogleRecaptchaKey = props.googleRecaptchaKey;
+
+  if (validGoogleRecaptchaKey && checkValidJson(validGoogleRecaptchaKey)) {
+    validGoogleRecaptchaKey = undefined;
```
Comment (somangshu) [inline app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:197]: @wmdev0808 Why are we setting the `validGoogleRecaptchaKey=undefined` if it's valid. Should this be the other way round?

Comment (somangshu) [reply app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:197]: Also, does a unit test exist for this?

**Review by somangshu — APPROVED** [review]
LGTM

File: app/client/src/components/designSystems/blueprint/ButtonComponent.tsx (hunk 1 above)
Comment (somangshu) [reply app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:197]: > @wmdev0808 Why are we setting the `validGoogleRecaptchaKey=undefined` if it's valid. Should this be the other way round?

This is because the captcha always needs to be a valid string and not an object

Comment (wmdev0808) [reply app/client/src/components/designSystems/blueprint/ButtonComponent.tsx:197]: > Also, does a unit test exist for this?

We don't have any test file for ButtonWidget
