### PR TITLE
Fix: Tabs widget refactor with new nested property validation

### LINKED ISSUE #2037: [Bug] Tab widget's tab name updates are not getting saved properly
### Steps to reproduce the behaviour:
1. Drop a tabs widget
2. Open the explorer with tab names showing
3. Rename the tabs
4. The old names still remain in the explorer
Screenshot 2020-12-06 at 11 50 51 PM

### LINKED ISSUE #2545: [Bug] JS bound tabs allow more operations than required
## Description

Individual tabs can be removed from the `TabsWidget` by using JS and removing elements from the array.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create a `TabsWidget`
2. Bind tabs to a js variable.
3. Use a button to change the number of elements in the tabs array.
4. The tab removed from the array gets deleted in editor mode.

### Important Details
 - Version: Cloud
 - OS: All
 - Browser: All

### LINKED ISSUE #3696: [Bug] Changing JS in the tabs deletes all widgets in the tab
Srijan lost all his work with this issue
### Steps to reproduce the behaviour:

1. Drag a tab widget
2. add widgets in the tabs
3. convert it to js
4. edit the js and make an error
5. All the tabs and widgets are lost forever

## Solution
Disallow dynamic creation of tabs and allow dynamically setting tabs as visible or not

### LINKED ISSUE #3727: [Bug] User is unable to edit the Tabs name of the tabs widget
Steps to reproduce:
1) Add a Tab widget
2) Ensure default Tabs are available
3) Now click on Tab 1 
4) Try to edit the name of the tab
and observe

Observation:
by clicking on the tab 1 trying to change the tab name the  widget itself gets deleted

Expectation:
User must be able to edit the name of the Tab of tab widget 

Video:
https://www.loom.com/share/48b14ba560f44e199df74f114a1f641f

### LINKED ISSUE #3735: [Bug]Tabs :  Default tab is not getting identified in the Tab after renaming the Tab
Steps to reproduce:
1) Add a Tab widget
2) Rename a Tab
3) Add renamed Tab as Default tab
and observe

Observation:
It is observed that the Default tab is selected in edit mode and deploy mode

Expectation:
It is expected to identify the default mode

Screenshot 2021-03-29 at 12 24 59 PM
Screenshot 2021-03-29 at 12 25 30 PM

### LINKED ISSUE #3929: [Bug] Property Pane stays open while dragging / resizing
Noticed this today when I was trying to build UI. The property pane remains open during the drag and blocks my view as well as drag location.

### LINKED ISSUE #4107: [Bug]Undo functionality is not functional on the tabs
Steps to reproduce:
1) Add a tab widget
2) Add multiple Tabs
3) Now click on delete option
4) Along with Information message there isUndo option
5) Click on "Undo" option

Observation:
It is observed that the undo action is not functional 

Expectation:
When user click on "Undo" action the Tabs must get replaced 

Scenario:
1) When the user clicks on delete option the message is not displayed 
2) When Undo is clicked the tab does not get retained

Video:
https://www.loom.com/share/2c0ba5b09a7247f6b3334d51e15f9d82

Environment:
Deploy-Preview-4014

### LINKED ISSUE #4111: [Bug] User is unable to add other widget on the Tab widget
Steps to reproduce:
1) Add a Tab widget 
2) Drag and drop widget
and observe

Observation:
It is observed that user is not allowed to add the widget into the tab widget

Expectation:
It is expected to add other widget into the Tab widget

Video:
https://www.loom.com/share/887b6f81f52e46dc948468369bad5256

Environment:
Deploy-Preview-4041

### LINKED ISSUE #4112: [Bug] Visible "False" for the First tab after deleting the entire tab
Steps to reproduce:
1) Add a tab widget
2) Delete the default tab
3) first tab gets added automatically
4) Add multiple tabs 
5) Click on Control Pane of tab 1
and observe

Observation:
It is observed that Visible is false on the tab that is automatically added 

Expectation:
It is expected that the Visible is True for the automatically added tab 

Video:
https://www.loom.com/share/f0f5e6e19ad84a46965b0b6686722c02

Environment:
deploy-preview-4014

### LINKED ISSUE #4113: [Bug] Additional information message is displayed to user
Steps to reproduce:
1) Add a new Tab Widget
2) delete the default widget 
ensure new Tab is added 
3) Click on "add tab"
and observe

Observation:
It is observed that the information message is displayed to user which is leading to confusion 

Expectation:
information message must be displayed only when the the action has been held

Video :
https://www.loom.com/share/eb62c1f1dfb84032af47c75429d4cb40

Environment:
Deploy-Preview-4041

### LINKED ISSUE #4148: [Bug]Image Widget inside the tab widget flickers in both edit and deploy mode upon binding an api with default tab
## Description
It is observed that the image widget which is placed inside tab widget flickers in both edit and deploy mode when an api is binded to the default tab

**Expected Result:**
Image widget placed inside tab widget should not flicker 

**Actual Result:**
Image widget placed inside tab widget flickers upon binding an api to the default tab

### Steps to reproduce the behaviour:
1.Launch App Smith app in the deploy environment - 
2.Expand API and click on new api 
3.Choose the method as GET
4.Pass the following header url - https://enmbt55ts7rbb96.m.pipedream.net/
5. Click on Run button and name the API
6. Expand Widget and Drag and drop tab widget 
7. Drag and Drop image widget inside tab widget 
8. Click edit on the tab 
9. On the Property pane of Tab widget bind the existing API to the Default tab and observe

**VideoLink:**
https://www.loom.com/share/6eecc3cab2df42b4a2d824d4b78d3b0e

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [MacOS Big Sur 11.2.3]
 - Browser [safari]

### PR DESCRIPTION
**Pull request by marks0351**
## Description
Tabs widget refactor
- removing the dynamic nature of number of tabs.
- will be able to bind to the visibility of the tab.

Fixes #3696 
Fixes #2545 
Fixes #3735
Fixes #3727
Fixes #4107 
Fixes #4111 
Fixes #4112 
Fixes #4113 
Fixes #2037 
Fixes #3929 
Fixes #4148 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce. 
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/nester-prop-validate 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 49.07 **(-0.19)** | 29.76 **(-0.9)** | 27.25 **(0.01)** | 49.45 **(-0.08)**
 :green_circle: | app/client/src/actions/debuggerActions.ts | 78.95 **(10.53)** | 100 **(0)** | 33.33 **(33.33)** | 100 **(0)**
 :green_circle: | app/client/src/actions/pageActions.tsx | 67.16 **(1.49)** | 0 **(0)** | 4.76 **(4.76)** | 55.81 **(2.32)**
 :sparkles: :new: | **app/client/src/components/ads/ButtonTabComponent.tsx** | **46.67** | **50** | **0** | **46.67**
 :sparkles: :new: | **app/client/src/components/ads/ColorPickerComponent.tsx** | **41.03** | **63.64** | **0** | **43.24**
 :sparkles: :new: | **app/client/src/components/ads/DatePickerComponent.tsx** | **50** | **100** | **0** | **50**
 :sparkles: :new: | **app/client/src/components/ads/DraggableList.tsx** | **20.63** | **14.29** | **0** | **27.66**
 :sparkles: :new: | **app/client/src/components/ads/DraggableListComponent.tsx** | **31.03** | **0** | **11.11** | **30.43**
 :sparkles: :new: | **app/client/src/components/ads/GifPlayerComponent.tsx** | **50** | **75** | **0** | **55.56**
 :sparkles: :new: | **app/client/src/components/ads/IconTabsComponent.tsx** | **46.67** | **50** | **0** | **46.67**
 :sparkles: :new: | **app/client/src/components/ads/MultiSwitch.tsx** | **46.67** | **60** | **0** | **46.67**
 :sparkles: :new: | **app/client/src/components/ads/StepComponent.tsx** | **43.48** | **66.67** | **0** | **40.91**
 :sparkles: :new: | **app/client/src/components/ads/Switch.tsx** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/src/components/ads/TreeDropdown.tsx** | **14.29** | **11.76** | **0** | **14.81**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/ContainerComponent.tsx** | **91.67** | **57.14** | **100** | **91.67**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/FilePickerComponent.tsx** | **55** | **0** | **20** | **52.63**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/IconComponent.tsx** | **88.89** | **0** | **50** | **87.5**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/ImageComponent.tsx** | **27.08** | **15.38** | **13.33** | **27.27**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/MapComponent.tsx** | **31.82** | **24.24** | **0** | **33.33**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/PickMyLocation.tsx** | **37.5** | **25** | **16.67** | **38.1**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/PopoverVideo.tsx** | **83.33** | **100** | **0** | **83.33**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/TabsComponent.tsx** | **100** | **85.29** | **100** | **100**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/VideoComponent.tsx** | **77.78** | **50** | **0** | **77.78**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/TableComponent/AutoToolTipComponent.tsx** | **31.43** | **15.38** | **0** | **35.48**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/TableComponent/TableStyledWrappers.tsx** | **35.21** | **18.81** | **0** | **35.21**
 :sparkles: :new: | **app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx** | **29.52** | **10.71** | **0** | **26.8**
 :green_circle: | app/client/src/components/designSystems/blueprint/ButtonComponent.tsx | 68.06 **(33.34)** | 56.86 **(45.1)** | 70 **(65)** | 70.77 **(33.85)**
 :sparkles: :new: | **app/client/src/components/designSystems/blueprint/CheckboxComponent.tsx** | **94.12** | **66.67** | **80** | **93.33**
 :sparkles: :new: | **app/client/src/components/designSystems/blueprint/DatePickerComponent.tsx** | **28.17** | **3.17** | **6.25** | **27.54**
 :sparkles: :new: | **app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx** | **29.41** | **3.51** | **5.88** | **28.79**
 :sparkles: :new: | **app/client/src/components/designSystems/blueprint/DropdownComponent.tsx** | **32.89** | **24** | **3.45** | **33.33**
 :sparkles: :new: | **app/client/src/components/designSystems/blueprint/InputComponent.tsx** | **61.64** | **37.1** | **48.28** | **62.32**
 :sparkles: :new: | **app/client/src/components/designSystems/blueprint/RadioGroupComponent.tsx** | **66.67** | **30.77** | **25** | **73.33**
 :sparkles: :new: | **app/client/src/components/designSystems/blueprint/SwitchComponent.tsx** | **93.75** | **62.5** | **50** | **93.33**
 :sparkles: :new: | **app/client/src/components/editorComponents/ActionCreator.tsx** | **12.06** | **0** | **0** | **11.57**
 :sparkles: :new: | **app/client/src/components/editorComponents/ActionNameEditor.tsx** | **28.36** | **3.39** | **0** | **28.57**
 :sparkles: :new: | **app/client/src/components/editorComponents/CloseEditor.tsx** | **58.33** | **100** | **0** | **58.33**
 :green_circle: | app/client/src/components/editorComponents/DragLayerComponent.tsx | 82.14 **(10.71)** | 38 **(8)** | 100 **(15.38)** | 80.77 **(11.54)**
 :green_circle: | app/client/src/components/editorComponents/DraggableComponent.tsx | 74.58 **(1.7)** | 41.03 **(0)** | 60 **(6.67)** | 73.58 **(1.88)**
 :green_circle: | app/client/src/components/editorComponents/DropTargetComponent.tsx | 62 **(44)** | 32.91 **(30.38)** | 43.75 **(43.75)** | 57.3 **(38.2)**
 :sparkles: :new: | **app/client/src/components/editorComponents/FormRow.tsx** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/components/editorComponents/PaneWrapper.tsx** | **40** | **100** | **0** | **40**
 :green_circle: | app/client/src/components/editorComponents/ResizableComponent.tsx | 55.56 **(0)** | 23.73 **(8.48)** | 55.56 **(0)** | 54.43 **(0)**
 :green_circle: | app/client/src/components/editorComponents/ResizeStyledComponents.tsx | 100 **(0)** | 100 **(3.57)** | 100 **(0)** | 100 **(0)**
 :sparkles: :new: | **app/client/src/components/editorComponents/StoreAsDatasource.tsx** | **64.71** | **66.67** | **0** | **64.71**
 :sparkles: :new: | **app/client/src/components/editorComponents/form/fields/DropdownFieldWrapper.tsx** | **21.05** | **0** | **0** | **23.53**
 :sparkles: :new: | **app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx** | **25.66** | **3.23** | **4.35** | **27.45**
 :sparkles: :new: | **app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx** | **45.65** | **26.67** | **0** | **46.67**
 :sparkles: :new: | **app/client/src/components/editorComponents/form/fields/RadioGroupField.tsx** | **63.64** | **0** | **0** | **63.64**
 :sparkles: :new: | **app/client/src/components/editorComponents/form/fields/RadioGroupWrapper.tsx** | **20** | **0** | **0** | **22.22**
 :sparkles: :new: | **app/client/src/components/editorComponents/form/fields/RequestDropdownField.tsx** | **63.64** | **0** | **0** | **63.64**
 :sparkles: :new: | **app/client/src/components/propertyControls/ActionSelectorControl.tsx** | **62.5** | **0** | **50** | **64.29**
 :sparkles: :new: | **app/client/src/components/propertyControls/BaseControl.tsx** | **66.67** | **0** | **33.33** | **63.64**
 :sparkles: :new: | **app/client/src/components/propertyControls/ButtonTabControl.tsx** | **40.74** | **0** | **40** | **47.62**
 :sparkles: :new: | **app/client/src/components/propertyControls/ChartDataControl.tsx** | **38.71** | **35.9** | **11.11** | **38.98**
 :sparkles: :new: | **app/client/src/components/propertyControls/CodeEditorControl.tsx** | **36.67** | **0** | **50** | **40**
 :sparkles: :new: | **app/client/src/components/propertyControls/ColorPickerControl.tsx** | **71.43** | **0** | **50** | **75**
 :sparkles: :new: | **app/client/src/components/propertyControls/ColumnActionSelectorControl.tsx** | **40.43** | **31.58** | **16.67** | **42.86**
 :sparkles: :new: | **app/client/src/components/propertyControls/ComputeTablePropertyControl.tsx** | **32.73** | **19.05** | **22.22** | **32.08**
 :sparkles: :new: | **app/client/src/components/propertyControls/CustomFusionChartControl.tsx** | **50** | **100** | **66.67** | **47.06**
 :sparkles: :new: | **app/client/src/components/propertyControls/DatePickerControl.tsx** | **27.27** | **4.76** | **13.33** | **26.92**
 :sparkles: :new: | **app/client/src/components/propertyControls/DropDownControl.tsx** | **43.48** | **0** | **33.33** | **45**
 :sparkles: :new: | **app/client/src/components/propertyControls/IconTabControl.tsx** | **45.45** | **0** | **50** | **56.25**
 :sparkles: :new: | **app/client/src/components/propertyControls/InputTextControl.tsx** | **36.84** | **0** | **33.33** | **36.11**
 :sparkles: :new: | **app/client/src/components/propertyControls/KeyValueComponent.tsx** | **17.74** | **29.63** | **0** | **18.97**
 :sparkles: :new: | **app/client/src/components/propertyControls/LocationSearchControl.tsx** | **35.56** | **0** | **22.22** | **36.59**
 :sparkles: :new: | **app/client/src/components/propertyControls/MultiSelectControl.tsx** | **47.83** | **0** | **33.33** | **52.63**
 :sparkles: :new: | **app/client/src/components/propertyControls/MultiSwitchControl.tsx** | **66.67** | **0** | **40** | **68.75**
 :sparkles: :new: | **app/client/src/components/propertyControls/OptionControl.tsx** | **71.43** | **0** | **50** | **75**
 :sparkles: :new: | **app/client/src/components/propertyControls/PrimaryColumnsControl.tsx** | **22.33** | **14.55** | **8** | **22.92**
 :sparkles: :new: | **app/client/src/components/propertyControls/StepControl.tsx** | **38.46** | **0** | **28.57** | **47.37**
 :sparkles: :new: | **app/client/src/components/propertyControls/SwitchControl.tsx** | **71.43** | **0** | **50** | **75**
 :sparkles: :new: | **app/client/src/components/propertyControls/TabControl.tsx** | **26.74** | **32** | **8.33** | **26.83**
 :sparkles: :new: | **app/client/src/components/propertyControls/index.ts** | **82.14** | **100** | **0** | **81.48**
 :sparkles: :new: | **app/client/src/components/utils/EmptyDataState.tsx** | **85.71** | **100** | **0** | **85.71**
 :sparkles: :new: | **app/client/src/components/utils/Skeleton.tsx** | **87.5** | **100** | **0** | **85.71**
 :sparkles: :new: | **app/client/src/components/utils/TreeStructure.tsx** | **83.33** | **100** | **0** | **83.33**
 :green_circle: | app/client/src/constants/DefaultTheme.tsx | 92.86 **(4.08)** | 88.89 **(0)** | 75 **(14.29)** | 91.46 **(4.87)**
 :sparkles: :new: | **app/client/src/constants/FieldExpectedValue.ts** | **100** | **100** | **100** | **100**
 :green_circle: | app/client/src/constants/messages.ts | 70.04 **(0.19)** | 100 **(0)** | 9.25 **(0.58)** | 73.31 **(0)**
 :sparkles: :new: | **app/client/src/entities/Datasource/index.ts** | **31.25** | **0** | **0** | **30**
 :green_circle: | app/client/src/entities/Widget/utils.ts | 93.75 **(1.56)** | 72.58 **(1.61)** | 81.82 **(0)** | 93.55 **(1.61)**
 :red_circle: | app/client/src/mockResponses/WidgetConfigResponse.tsx | 27.63 **(-0.37)** | 9.38 **(0)** | 28.57 **(0)** | 27.4 **(-0.38)**
 :green_circle: | app/client/src/normalizers/CanvasWidgetsNormalizer.tsx | 90 **(10)** | 100 **(0)** | 66.67 **(33.34)** | 90 **(10)**
 :sparkles: :new: | **app/client/src/pages/Editor/ActionSettings.tsx** | **42.11** | **50** | **0** | **42.11**
 :sparkles: :new: | **app/client/src/pages/Editor/Canvas.tsx** | **83.33** | **100** | **100** | **83.33**
 :sparkles: :new: | **app/client/src/pages/Editor/FormControl.tsx** | **53.85** | **0** | **0** | **58.33**
 :sparkles: :new: | **app/client/src/pages/Editor/PropertyPaneHelpButton.tsx** | **50** | **0** | **0** | **52.63**
 :sparkles: :new: | **app/client/src/pages/Editor/PropertyPaneTitle.tsx** | **32.69** | **18.18** | **0** | **35.42**
 :sparkles: :new: | **app/client/src/pages/Editor/APIEditor/Form.tsx** | **42.98** | **53.85** | **0** | **44.55**
 :sparkles: :new: | **app/client/src/pages/Editor/APIEditor/Pagination.tsx** | **50.98** | **62.5** | **0** | **50.98**
 :sparkles: :new: | **app/client/src/pages/Editor/APIEditor/PostBodyData.tsx** | **52.94** | **33.33** | **0** | **54.55**
 :sparkles: :new: | **app/client/src/pages/Editor/Explorer/Actions/MoreActionsMenu.tsx** | **33.33** | **33.33** | **0** | **34.29**
 :red_circle: | app/client/src/pages/Editor/Explorer/Widgets/WidgetContextMenu.tsx | 37.14 **(-1.1)** | 0 **(0)** | 0 **(0)** | 36.36 **(-1.14)**
 :sparkles: :new: | **app/client/src/pages/Editor/PropertyPane/Generator.tsx** | **45** | **0** | **0** | **41.18**
 :sparkles: :new: | **app/client/src/pages/Editor/PropertyPane/PanelPropertiesEditor.tsx** | **20.51** | **0** | **0** | **20**
 :sparkles: :new: | **app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx** | **20.33** | **0** | **0** | **21.74**
 :sparkles: :new: | **app/client/src/pages/Editor/PropertyPane/PropertyHelpLabel.tsx** | **55.56** | **0** | **0** | **55.56**
 :sparkles: :new: | **app/client/src/pages/Editor/PropertyPane/PropertySection.tsx** | **50** | **28.57** | **0** | **53.85**
 :sparkles: :new: | **app/client/src/pages/Editor/PropertyPane/index.tsx** | **49.49** | **11.83** | **20** | **50**
 :sparkles: :new: | **app/client/src/pages/common/ArtBoard.tsx** | **100** | **100** | **100** | **100**
 :green_circle: | app/client/src/reducers/entityReducers/canvasWidgetsReducer.tsx | 72.73 **(9.09)** | 100 **(0)** | 33.33 **(33.33)** | 72.73 **(9.09)**
 :green_circle: | app/client/src/reducers/uiReducers/debuggerReducer.ts | 37.04 **(7.41)** | 7.14 **(7.14)** | 16.67 **(16.67)** | 40 **(8)**
 :green_circle: | app/client/src/reducers/uiReducers/editorReducer.tsx | 23.88 **(14.92)** | 0 **(0)** | 4.55 **(4.55)** | 23.88 **(14.92)**
 :green_circle: | app/client/src/sagas/DebuggerSagas.ts | 15.96 **(3.19)** | 3.77 **(1.88)** | 28.57 **(14.28)** | 17.44 **(3.49)**
 :green_circle: | app/client/src/sagas/PageSagas.tsx | 17.52 **(0.98)** | 3.51 **(1.82)** | 6.45 **(3.22)** | 20.09 **(0.78)**
 :sparkles: :new: | **app/client/src/sagas/WidgetEnhancementHelpers.ts** | **26.76** | **4.26** | **7.14** | **28.57**
 :red_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 7.99 **(-0.06)** | 1.02 **(0)** | 3.17 **(-0.06)** | 9.12 **(-0.09)**
 :green_circle: | app/client/src/selectors/editorSelectors.tsx | 58.46 **(6.92)** | 27.03 **(16.22)** | 33.33 **(14.28)** | 56.07 **(8.41)**
 :green_circle: | app/client/src/selectors/entitiesSelector.ts | 44.29 **(0.45)** | 1.43 **(0)** | 14.81 **(1.23)** | 40.99 **(0.62)**
 :green_circle: | app/client/src/selectors/propertyPaneSelectors.tsx | 62.96 **(14.96)** | 46.15 **(26.15)** | 100 **(40)** | 61.54 **(11.54)**
 :green_circle: | app/client/src/selectors/themeSelectors.tsx | 94.12 **(5.88)** | 100 **(0)** | 80 **(20)** | 91.67 **(0)**
 :green_circle: | app/client/src/selectors/usersSelectors.tsx | 83.33 **(8.33)** | 100 **(0)** | 50 **(25)** | 85.71 **(14.28)**
 :sparkles: :new: | **app/client/src/selectors/widgetSelectors.ts** | **47.06** | **0** | **0** | **57.14**
 :green_circle: | app/client/src/utils/AppsmithConsole.ts | 80 **(30)** | 100 **(0)** | 60 **(60)** | 80 **(30)**
 :green_circle: | app/client/src/utils/AppsmithUtils.tsx | 53.98 **(0.57)** | 15.85 **(0)** | 41.67 **(2.78)** | 49.02 **(0.65)**
 :sparkles: :new: | **app/client/src/utils/EditorUtils.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/src/utils/PropertyControlFactory.tsx** | **40** | **0** | **50** | **42.11**
 :sparkles: :new: | **app/client/src/utils/PropertyControlRegistry.tsx** | **90.91** | **100** | **75** | **90.91**
 :green_circle: | app/client/src/utils/WidgetFactory.tsx | 62.12 **(33.33)** | 57.89 **(57.89)** | 50 **(41.67)** | 62.12 **(33.33)**
 :green_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 57.62 **(36.15)** | 45.28 **(40.65)** | 48.15 **(39.26)** | 56.73 **(37.96)**
 :sparkles: :new: | **app/client/src/utils/WidgetRegistry.tsx** | **75.86** | **100** | **27.59** | **75.86**
 :green_circle: | app/client/src/utils/generators.tsx | 95.24 **(19.05)** | 50 **(16.67)** | 100 **(50)** | 100 **(23.08)**
 :green_circle: | app/client/src/utils/hooks/dragResizeHooks.tsx | 52.08 **(6.25)** | 0 **(0)** | 25 **(6.25)** | 47.5 **(7.5)**
 :green_circle: | app/client/src/utils/hooks/useClickOpenPropPane.tsx | 88 **(8)** | 40 **(40)** | 100 **(20)** | 86.96 **(4.35)**
 :green_circle: | app/client/src/utils/migrations/IncorrectDynamicBindingPathLists.ts | 94.74 **(63.16)** | 87.5 **(87.5)** | 100 **(100)** | 94.44 **(66.66)**
 :green_circle: | app/client/src/utils/migrations/TableWidget.ts | 72.62 **(9.52)** | 57.5 **(16.25)** | 70 **(20)** | 75.64 **(10.26)**
 :green_circle: | app/client/src/utils/migrations/TextWidgetReplaceTextStyle.ts | 95.83 **(8.33)** | 85.71 **(35.71)** | 100 **(0)** | 95.65 **(8.69)**
 :green_circle: | app/client/src/widgets/BaseWidget.tsx | 79.61 **(5.82)** | 39.02 **(7.31)** | 76.92 **(23.07)** | 78.57 **(6.12)**
 :sparkles: :new: | **app/client/src/widgets/ButtonWidget.tsx** | **74.29** | **50** | **55.56** | **73.53**
 :sparkles: :new: | **app/client/src/widgets/CanvasWidget.tsx** | **77.78** | **53.33** | **75** | **82.5**
 :sparkles: :new: | **app/client/src/widgets/CheckboxWidget.tsx** | **92.59** | **66.67** | **75** | **92**
 :sparkles: :new: | **app/client/src/widgets/ContainerWidget.tsx** | **67.35** | **25** | **70** | **68.89**
 :sparkles: :new: | **app/client/src/widgets/DatePickerWidget.tsx** | **57.14** | **0** | **55.56** | **57.5**
 :sparkles: :new: | **app/client/src/widgets/DatePickerWidget2.tsx** | **82.14** | **0** | **62.5** | **84.62**
 :sparkles: :new: | **app/client/src/widgets/DropdownWidget.tsx** | **42.11** | **0** | **35.71** | **44.23**
 :sparkles: :new: | **app/client/src/widgets/FilepickerWidget.tsx** | **35.56** | **0** | **14.81** | **34.83**
 :sparkles: :new: | **app/client/src/widgets/FormButtonWidget.tsx** | **50** | **0** | **33.33** | **48.72**
 :sparkles: :new: | **app/client/src/widgets/FormWidget.tsx** | **35.29** | **0** | **15.38** | **36.17**
 :sparkles: :new: | **app/client/src/widgets/IconWidget.tsx** | **72** | **28.57** | **33.33** | **73.91**
 :sparkles: :new: | **app/client/src/widgets/ImageWidget.tsx** | **65.38** | **0** | **28.57** | **66.67**
 :sparkles: :new: | **app/client/src/widgets/InputWidget.tsx** | **69.64** | **34.38** | **58.33** | **76**
 :sparkles: :new: | **app/client/src/widgets/MapWidget.tsx** | **46.77** | **9.09** | **23.53** | **47.46**
 :green_circle: | app/client/src/widgets/MetaHOC.tsx | 76.56 **(54.68)** | 52.94 **(52.94)** | 92.31 **(76.93)** | 76.36 **(52.72)**
 :sparkles: :new: | **app/client/src/widgets/ModalWidget.tsx** | **46.03** | **0** | **15.38** | **45.76**
 :sparkles: :new: | **app/client/src/widgets/RadioGroupWidget.tsx** | **81.48** | **0** | **62.5** | **84**
 :sparkles: :new: | **app/client/src/widgets/RichTextEditorWidget.tsx** | **71.79** | **22.22** | **50** | **72.97**
 :sparkles: :new: | **app/client/src/widgets/SkeletonWidget.tsx** | **87.5** | **100** | **50** | **86.67**
 :sparkles: :new: | **app/client/src/widgets/SwitchWidget.tsx** | **92.59** | **60** | **75** | **92**
 :sparkles: :new: | **app/client/src/widgets/TextWidget.tsx** | **88.89** | **0** | **60** | **88.24**
 :sparkles: :new: | **app/client/src/widgets/VideoWidget.tsx** | **62.22** | **40** | **35.71** | **72.97**
 :sparkles: :new: | **app/client/src/widgets/ChartWidget/index.tsx** | **74.07** | **0** | **33.33** | **76**
 :green_circle: | app/client/src/widgets/ListWidget/ListWidget.tsx | 37.95 **(1.54)** | 21.18 **(0)** | 27.27 **(9.09)** | 37.02 **(1.66)**
 :sparkles: :new: | **app/client/src/widgets/TableWidget/index.tsx** | **9.49** | **0** | **10.64** | **10.27**
 :sparkles: :new: | **app/client/src/widgets/TableWidget/parseDerivedProperties.ts** | **38.46** | **0** | **0** | **38.46**
 :sparkles: :new: | **app/client/src/widgets/Tabs/TabsMigrator.tsx** | **75** | **0** | **40** | **73.91**
 :sparkles: :new: | **app/client/src/widgets/Tabs/TabsWidget.tsx** | **66.17** | **36.56** | **60.71** | **65.08**
 :green_circle: | app/client/src/workers/validations.ts | 34.97 **(0)** | 29.96 **(0.22)** | 38.64 **(0)** | 35.44 **(0)**
 :sparkles: :new: | **app/client/test/factories/WidgetFactoryUtils.ts** | **92.86** | **50** | **100** | **92.31**
 :sparkles: :new: | **app/client/test/factories/Widgets/ButtonFactory.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/test/factories/Widgets/CanvasFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/ChartFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/CheckboxFactory.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/test/factories/Widgets/ContainerFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/DatepickerFactory.ts** | **66.67** | **100** | **0** | **66.67**
 :sparkles: :new: | **app/client/test/factories/Widgets/DropdownFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/FilepickerFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/FormButtonFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/FormFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/IconFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/ImageFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/InputFactory.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/test/factories/Widgets/ListFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/MapFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/ModalFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/RadiogroupFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/RichTextFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/SkeletonFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/SwitchFactory.ts** | **100** | **100** | **100** | **100**
 :sparkles: :new: | **app/client/test/factories/Widgets/TableFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/TabsFactory.ts** | **83.33** | **100** | **50** | **83.33**
 :sparkles: :new: | **app/client/test/factories/Widgets/TextFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/VideoFactory.ts** | **75** | **100** | **0** | **75**
 :sparkles: :new: | **app/client/test/factories/Widgets/WidgetTypeFactories.ts** | **100** | **100** | **100** | **100**</details>

### CODE REVIEW

**Review by riodeuno — APPROVED** [review]
Approving for CI tests

File: app/client/src/widgets/Tabs/TabsMigrator.tsx [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+import { migrateTabsData } from "utils/WidgetPropsUtils";
+import { cloneDeep } from "lodash";
+import { VALIDATION_TYPES } from "constants/WidgetValidation";
+
+class TabsMigratorWidget extends BaseWidget<
+  TabsWidgetProps<TabContainerWidgetProps>,
+  WidgetState
+> {
+  getPageView() {
+    console.log(this.props);
```
Comment (riodeuno) [inline app/client/src/widgets/Tabs/TabsMigrator.tsx:16]: Missed console.log

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — DISMISSED** [review]

**Review by jsartisan — APPROVED** [review]

**Review by jsartisan — DISMISSED** [review]

**Review by riodeuno — APPROVED** [review]

**Review by riodeuno — APPROVED** [review]
