### PR TITLE
fix: rts fat container docker image

### LINKED ISSUE #16091: [Bug]: RTS docker container image for new revamped code
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fix the docker commands for the rts docker image

### Steps To Reproduce

Create RTS docker image using Fat Container Dockerfile on root directory and direct rts image using Dockerfile inside `app/rts` directory

### Public Sample App

_No response_

### Version

Both

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description

- Added the removal of rts previous build before building new image
- Fixed Fat container copying of dist folder to rts image directory path in docker container

Fixes #16091

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Irongade — APPROVED** [review]

File: app/rts/build.sh [hunk 1]
```diff
@@ -3,5 +3,6 @@
 set -o errexit
 
 cd "$(dirname "$0")"
+rm -rf dist
```
Comment (sharat87) [inline app/rts/build.sh:6]: I don't think this is needed here right? Can we undo changes in this file and just keep the fix in the Dockerfile? Otherwise it looks ready to be merged.

**Review by sharat87 — CHANGES_REQUESTED** [review]

**Review by mohanarpit — APPROVED** [review]

File: app/rts/build.sh (hunk 1 above)
Comment (AmanAgarwal041) [reply app/rts/build.sh]: Removed the line to delete the dist directory.

**Review by mohanarpit — APPROVED** [review]
