### PR TITLE
fix: Mongo plugin: fix test datasource with URI

### LINKED ISSUE #24660: [Bug]: Mongo DB - Connection string URI - Empty key error on DS page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On choosing yes from the use connection string uri option of Mongo DS, enter the connection string from the doc: https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79?pvs=4#548f42ade97d403892d47a85ba59ec36

Note that user gets an error "Empty Key"

### Steps To Reproduce

1. Go to Create new DS, choose mongo, choose use connection string uri as yes and add the details from the above notion doc. 
2. Click on Test config, and note the error Empty Key

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/5EoOxXFcYk41en3x

### Version

Cloud

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Mongo test datasource flow relies on validate datasource flow which in turn relies on a check to find if a datasource is embedded or not. Because the check was incorrectly coded, test datasource flow was failing. This PR fixes the check to find if a datasource is an embedded datasource or not. 
  - JFYI, embedded datasource is a datasource which is not explicitly persisted i.e. has no entry in the respective collection in Mongo. Currently only the REST API plugin and the GraphQL API plugin use embedded datasource. 
- Update regex for Mongo URI to match URI strings which don't have username and password so that users can now connect with Mongo accounts that don't have username and password via their URI.  

#### PR fixes following issue(s)
Fixes #24660 #24897 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [x] JUnit
- [x] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+import { agHelper, dataSources } from "../../../support/Objects/ObjectsCore";
+import datasourceFormData from "../../../fixtures/datasources.json";
+
+let dsName: any;
+
+describe("Create, test, save then delete a mongo datasource using URI", function () {
+  it("1. Create, test, save then delete a mongo datasource using URI", function () {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:7]: Add Bug id to `it` description.

File: app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+      dataSources.CreatePlugIn("MongoDB");
+      dsName = "Mongo" + uid;
+      agHelper.RenameWithInPane(dsName, false);
+
+      dataSources.FillMongoDatasourceFormWithURI(
+        datasourceFormData["mongo-uri"],
+      );
+      // TODO: update this to `true` when the following issue is fixed:
+      //  https://github.com/appsmithorg/TestEventDriver/issues/40
+      dataSources.TestSaveDatasource(false);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: @sneha122 - has a working method from this [PR](https://github.com/appsmithorg/appsmith/pull/24845/files#diff-745de5dfe12de5fe01a6700879bb359863e5becc8dd641f984252ed4385a27af) mongodb://host.docker.internal:28017/mongo_samples - for TED mongo which connects fine.
Can you please update this test accordingly & have the TestSaveDatasource done - instead of false?

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: Because I think testing fine will be the proper completion of the bug verification too.

Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: Hi @Aishwarya-U-R , even if we use the URI that you have provided it would not test bug for this PR because (1) it needs password to test the issue (2) currently we don't support URI without username and password, tracking it here: https://github.com/appsmithorg/appsmith/issues/24897

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: Oh ok, need more clarification here. 
So right now we are able to connect to mongo URI with above mentioned via Appsmith.
Now you mean the Empty key error bug occurs only if password is also supplied to mongo uri? And anything more to it?

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: Also can we add the application bug also to the spec along with one mentioned for TED?
`Bug # 24897`

**Review by tkAppsmith — DISMISSED** [review]

File: app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts (hunk 2 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: Once https://github.com/appsmithorg/appsmith/issues/24897 is fixed, we can add another cypress test case to test for it.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: No Sumit, it connects fine & we are able to use the TED mongo collections to query also:
What am I missing here? 🤔
Screenshot 2023-06-28 at 6 59 05 PM

Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: @Aishwarya-U-R as I have mentioned earlier, it will still connect fine but when we press on `test datasource` it will fail (not now because the flow is broken, but will start doing it once this PR is merged).

File: app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts (hunk 1 above)
Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts]: Done.

File: app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts (hunk 2 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: So we are going to break something which is working now?

Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:22]: Hi @Aishwarya-U-R yes, it will look like breaking but its actually fixing it. Right now there is effectively no validation running on the URI strings.

Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts]: Hi @Aishwarya-U-R I have now added the fix for https://github.com/appsmithorg/appsmith/issues/24897 as well, so this change is now fully backwards compatible.

File: app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+    dataSources.NavigateToDSCreateNew();
+    agHelper.GenerateUUID();
+    cy.get("@guid").then((uid) => {
+      // using CreatePlugIn function instead of CreateDatasource,
+      // because I do not need to fill the datasource form and use the same default data
+      dataSources.CreatePlugIn("MongoDB");
+      dsName = "Mongo" + uid;
+      agHelper.RenameWithInPane(dsName, false);
+
+      dataSources.FillMongoDatasourceFormWithURI();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:18]: This method does not take value from dataSources.json anymore. There is a new HostPort.ts file from which values are read. So can you please verify if the current mongo_uri value given suffices this test? or it needs added '@' infront of hostname?
If yes - create a new variable for this test & make that argument & pass it from caller.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:18]: And is the bug still not validated fully then? I see bug is for when un & pswd are used in uri.

Comment (sumitsum) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:18]: Hi @Aishwarya-U-R 
(1) URI doesn't need to have `@` before the host address. Its not recommeded as per the URI rules described [here](https://www.mongodb.com/docs/manual/reference/connection-string/). Also, I had noticed that the URI is coming from Hostports.ts now, but I have still updated the `datasources.json` because that URI was incorrect. 
(2) Yes, this cypress will not be able to fully validate the bug - we need URI with username and password for it which we don't have at the moment, hence I have added a comment for the same.

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts:18]: Got it!

File: app/client/cypress/fixtures/datasources.json [hunk 4]
```diff
@@ -3,7 +3,7 @@
   "mongo-host": "host.docker.internal",
   "mongo-port": 28017,
   "mongo-databaseName": "mongo_samples",
-  "mongo-uri": "mongodb+srv://localhost:localhost@mockdb.net/mock?retryWrites=true&w=majority",
+  "mongo-uri": "mongodb://@host.docker.internal:28017/mongo_samples?retryWrites=true&w=majority",
```
Comment (Aishwarya-U-R) [inline app/client/cypress/fixtures/datasources.json:6]: Can `@` then be removed from here?

**Review by Aishwarya-U-R — COMMENTED** [review]
Approving Cypress changes.

File: app/client/cypress/fixtures/datasources.json (hunk 4 above)
Comment (sumitsum) [reply app/client/cypress/fixtures/datasources.json]: Thanks for pointing this out. I have updated it.

**Review by Aishwarya-U-R — DISMISSED** [review]

**Review by tkAppsmith — APPROVED** [review]

**Review by tkAppsmith — APPROVED** [review]
Approving as approval was revoked due to a merge conflict.
