### PR TITLE
fix: Switch to preview mode performance issue

### LINKED ISSUE #18458: [Bug]: Limit handles deselects widget when the mouse down happen on the canvas.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Limit handles deselects widget when the mouse down happen on the canvas.

https://user-images.githubusercontent.com/113327629/203992348-11ab52ee-c1a9-4e3e-991e-293aa3bf4e9d.mov

### Steps To Reproduce

1. Dnd a widget
2. change it to Auto height with Limit
3. try to resize using signifier
you'll notice that the widget gets deselected

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Release

### LINKED ISSUE #18475: [Bug]: Switching to preview mode is slow
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Due to the recent auto height changes, when we switch to preview mode in a complex application, we find the switch really slow, and in some cases, it freezes the browser tab

### Steps To Reproduce

1. Create a complex application with many multiselect widgets, tree select widgets and JSONForm widgets
2. Switch to preview mode from view mode
3. Measure the time taken to switch and render the page in preview mode.

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

Release

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
- Reverts the RenderModes.PREVIEW logic.
- This helps resolve the edit -> preview -> edit switch performance.

Fixes #18475
Fixes #18458 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- [Cypress tests pending](https://www.notion.so/appsmith/Cypress-Test-scenarios-50557ff33f2745498396a4215b9a77ed)

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [PENDING] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [NA] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/withWidgetProps.tsx [hunk 1]
```diff
@@ -33,6 +34,7 @@ function withWidgetProps(WrappedWidget: typeof BaseWidget) {
     props: WidgetProps & { skipWidgetPropsHydration?: boolean },
   ) {
     const { children, skipWidgetPropsHydration, type, widgetId } = props;
+    const isPreviewMode = useSelector(previewModeSelector);
```
Comment (rahulramesha) [inline app/client/src/widgets/withWidgetProps.tsx:37]: This will still re-render all the widgets, let me see if i can write a selector for this.

File: app/client/src/widgets/BaseWidget.tsx [hunk 2]
```diff
@@ -455,18 +455,12 @@ abstract class BaseWidget<
 
       // return this.getCanvasView();
       case RenderModes.PAGE:
-      case RenderModes.PREVIEW:
```
Comment (rahulramesha) [inline app/client/src/widgets/BaseWidget.tsx:458]: I remember there being a Preview container, is that not required anymore?

**Review by rahulramesha — CHANGES_REQUESTED** [review]
Have few comments, but other than that what exactly was the issue with select|multiselect type widgets?

File: app/client/src/reducers/entityReducers/canvasWidgetsReducer.ts [hunk 3]
```diff
@@ -101,6 +102,7 @@ const canvasWidgetsReducer = createImmerReducer(initialState, {
           set(state, path, propertyValue);
       });
     }
+    console.log("Setting redux state: Time taken:", performance.now() - start);
```
[the remark this answers is not in the document]
Comment (riodeuno) [reply app/client/src/reducers/entityReducers/canvasWidgetsReducer.ts:105]: Yep, build failed due to this. Removing it.

**Comment by riodeuno** [comment]
In conjunction with RenderModes.PREVIEW (when all widgets used to re-render), we used to get `(Committing Changes) Warning: Lifecycle hook scheduled a cascading update`

Basically, for reasons I couldn't figure out, widgets like MultiSelect widget which has a lot of internal renders, used to block the thread for seconds. The cause of this was that we were somehow sending updates rapidly, even before React had a chance to commit it to the DOM. This resulted in a UI freeze.

**Review by rahulramesha — APPROVED** [review]
