### PR TITLE
fix: Correcting the duplication of headers from datasource to newer APIs

### LINKED ISSUE #6278: [Bug] Multiple header are displayed to user when the header is added from the datasource
Steps to reproduce :
1) Add an API
2) Save as data source
3) Add Header in the Datasource
4)Save the data source
5) Create an API from the data source
observe the header section

Observation:
It is observed that the data source header is being displayed to the user twice. 

Video:
[LOOM DEMO](https://www.loom.com/share/7e23846f5cd7444bb201abbe10a45392)

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description

When an API was created from the datasource having some headers attached to it, then the created API used to get duplicated headers one from datasource (derived headers) and the other from its own headers. 

Fixes #6278

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Steps to reproduce :

1.  Add an API
2.  Save as data source
3.  Add Header in the Datasource
4.  Save the data source
5.  Create an API from the data source observe the header section
6. In the previous version the headers were duplicated but now the datasource headers are present only in the derived headers section.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/multiple-headers-api 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.15 **(0)** | 37.06 **(0.01)** | 34.03 **(0)** | 55.67 **(0)**
 :green_circle: | app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx | 38.46 **(0.96)** | 4.55 **(1.1)** | 0 **(0)** | 41.67 **(1.13)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx [hunk 1]
```diff
@@ -67,10 +67,12 @@ function NewActionButton(props: NewActionButtonProps) {
             ? createNewQueryName(actions, currentPageId || "")
             : createNewApiName(actions, currentPageId || "");
 
-        const headers = datasource?.datasourceConfiguration?.headers ?? [];
+        /* Removed Datasource Headers because they already exists in inherited headers so should not be duplicated to Newer APIs creation as datasource is already attached to it. While for older APIs we can start showing message on the UI from the API from messages key in Actions object. */
+        // const headers = datasource?.datasourceConfiguration?.headers ?? [];
         const defaultApiActionConfig: ApiActionConfig = {
           ...DEFAULT_API_ACTION_CONFIG,
-          headers: headers.length ? headers : DEFAULT_API_ACTION_CONFIG.headers,
+          // headers: headers.length ? headers : DEFAULT_API_ACTION_CONFIG.headers,
```
Comment (mohanarpit) [inline app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx:74]: Nit: Can we please remove commented code? Keeps the code more readable for the future.

Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx]: removed the commented code.

**Review by rashmi-rai — APPROVED** [review]

**Review by Irongade — APPROVED** [review]

**Review by rashmi-rai — APPROVED** [review]
