### PR TITLE
Fix: Dynamodb Plugin: remove data type info keys from raw values. 

### LINKED ISSUE #6581: [Feature] Dynamo DB: Automatic mapped values
A user on discord reports and suggests the following:

BTW - one thing that would make working with dynamodb results much better is if you automatically mapped the values after they are returned. DynamoDB returns this object for each column that has properties "S", "N", "M", etc that depend on the datatype. You then need to edit each column in the table to refer to returnedvalue,.S or returned value.N, It is very annoying. I tried the same thing in retool and they map it for you. The AWS dynamodb API comes with something called the documentclient that does all the mapping for you: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- A fix had been introduced earlier (I had introduced it a few months back) to remove data type info keys from the raw response. However, the transformation was not getting applied to the `Query` action as the transformation was explicitly limited to few actions. This PR removes that check and allows the transformation for all actions as there does not seem to be any reason to withhold this transformation for other actions.
- The earlier fix also restricted this transformation to results that had specific keys. This PR removes this check as well as it does not seem to be required and further may lead to similar issues if any particular key gets missed. 
- Some other redundant checks have been removed from the flow as the transformation function itself takes care of it as edge/base case. 

Fixes #6581 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- JUnit TC

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java [hunk 1]
```diff
@@ -180,98 +170,17 @@ public Object getTransformedResponse(Map<String, Object> rawResponse,
...
-                case SCAN_ACTION_VALUE:
-                    topLevelKey = ITEMS_KEY;
-                    break;
-                case GET_ITEM_ACTION_VALUE:
-                    topLevelKey = ITEM_KEY;
-                    break;
-                case PUT_ITEM_ACTION_VALUE:
-                case UPDATE_ITEM_ACTION_VALUE:
-                case DELETE_ITEM_ACTION_VALUE:
-                    topLevelKey = ATTRIBUTES_KEY;
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java:218]: @sumitsum could you please explain to me why this is not required anymore? I can't seem to figure what types of responses we are handling with these.

**Review by nidhi-nair — APPROVED** [review]
