### PR TITLE
fix: Signposting when user signs up with oauth is not working

### LINKED ISSUE #7417: [Bug] Signposting does not work when user signs up using OAuth
## Description
Google and GitHub sign up does not trigger Sign Posting feature

### Steps to reproduce the behaviour:
1. Sign up using Google/Github account and observe that sign posting flow is not triggered.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

### PR DESCRIPTION
**Pull request by nayan-rafiq**
> Pull Request Template
>
> Use this template to quickly create a well written pull request. Delete all quotes before creating the pull request.

## Description
In the signposting feature, we create a default application when someone signs up. Currently, it works for form based signups only. This PR adds oauth for signposting also. 

Fixes #7417

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- Manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java [hunk 1]
```diff
@@ -154,8 +181,14 @@
...
 
+        boolean addFirstTimeExperienceParam = false;
         if (isFromSignup) {
-            redirectUrl = buildSignupSuccessUrl(redirectUrl, false);
+            if(redirectUrl.endsWith(RedirectHelper.DEFAULT_REDIRECT_URL) && defaultApplication != null) {
+                addFirstTimeExperienceParam = true;
+                HttpHeaders headers = exchange.getRequest().getHeaders();
+                redirectUrl = redirectHelper.buildApplicationUrl(defaultApplication, headers);
+            }
+            redirectUrl = buildSignupSuccessUrl(redirectUrl, addFirstTimeExperienceParam);
```
Comment (sharat87) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java:191]: Can you elaborate a little on this please? If the user is coming from signup (checked by the `if (isFromSignup)` line, shouldn't we always take them to the first time experience? Shouldn't `addFirstTimeExperienceParam` here be always `true`? Can you add a comment on when we want it to be `false`, even though they came from signup?

**Review by sharat87 — COMMENTED** [review]
Looks good. Wanted a small comment on something.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java (hunk 1 above)
Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java:191]: @sharat87 As per discussion with @sbalaji1192 we only redirect to default application if the default redirect url is empty. For example, user is trying to access an application using an URL `/applications/abcd` and they are taken to signup page with url `/signup?redirectUrl=/applications/abc`. In this case, we don't want to take user to newly created application. That's why we are checking if user has any redirect url other than default url.

Comment (sharat87) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java:191]: I see. So what's the idea behind using `.endsWith` here? Looks like we want to check if the redirect URL is _equal_ to the default redirect URL, that's when we want to do this no?

Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java:191]: I've used `endsWith` so that `https://app.appsmith.com/applications` and `/applications` both are matched.

**Review by sharat87 — APPROVED** [review]
Looks good to be merged. Please:

1. Edit the merge commit's detail to the PR description, or otherwise more details about the change.
1. Squash merge once the CI is finished. Thanks!
