### PR TITLE
Fixes refresh token flow

### LINKED ISSUE #4398: [Bug] - Google Datasource token expires and needs configuration
## Description
Release - For an existing application the already configured datasource needs to be configured again to perform API actions. 

Actual Result:
API does not fetch results from API as it needs Authorisation

Expected Result:
User needs to Authorise everytime he tends to use the Google API 

### Steps to reproduce the behaviour:
Steps to Reproduce:
Navigate to existing application with Google API
Click on the Google sheet API Datasource from the Entity explorer
Click on “Add New API” button
Add add simply method “List ”
Click on Run
and observe

VideoLink:
https://www.loom.com/share/20fe0045cb9c4dd391c7217536a94cd3

Note:
If the datasource is not configured properly the below error occurs 

Screenshot 2021-05-10 at 1 39 49 PM

### Important Details
 - Version: [14.1 (16611.1.21.161.3)]
 - OS: [MacOS Big Sur 11.3]
 - Browser [Safari]

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixes #4398

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java [hunk 1]
```diff
@@ -422,7 +422,9 @@
                                 oAuth2.setAuthenticationResponse(authenticationResponse);
                                 oAuth2.setIsEncrypted(null);
                                 datasource.getDatasourceConfiguration().setAuthentication(oAuth2);
-                                return datasourceService.update(datasource.getId(), datasource);
+                                return datasourceService
+                                        .update(datasource.getId(), datasource)
+                                        .thenReturn(datasource);
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java:427]: Please add a comment here explaining we are not returning the saved datasource returned from the repository at this point but the datasource which was sent to the repo ( I am guessing this is because of the annotated encryption).

**Review by trishaanand — APPROVED** [review]

**Review by trishaanand — APPROVED** [review]

**Review by trishaanand — APPROVED** [review]
