### PR TITLE
fix: Validation issue in select widget on page reload

### LINKED ISSUE #28224: [Bug]: Select widget value field shows error by default
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i connect a select field to label and value and refresh the page, i see the widget showing an error and value property showing an error

https://www.loom.com/share/5ed9b122fd13450b84324fcf0fefa1ac

### Steps To Reproduce

1. Add a new select widget
2. Configure static data in any format, select the label and value key
3. Refresh the page
4. Observe the error in the select widget

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://www.loom.com/share/5ed9b122fd13450b84324fcf0fefa1ac

### Version

Cloud

### LINKED ISSUE #28368: [Bug]: Incorrect validation error on select widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Validation error is shown on `Default Selected Value` field of a select widget on page reload.

### Steps To Reproduce

1. Create a new application.
2. Drag & Drop select widget.
3. Force a validation error by providing an incorrect value and then undo this change.
4. Refresh the app

Observe that there is an incorrect validation errors logged against the Default Selected Value field.

### Public Sample App

_No response_

### Environment

Production

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fixes the regression in select widget validation caused by https://github.com/appsmithorg/appsmith/issues/27408
This PR remove most of the re-validation related logic written in evaluations code base. Going forward we'll maintain an internal dependencyMap for widgets. This can help avoid IIFE hacks to introduce dependency between fields.

###### Changes
- Removes the concept of dependentPaths in validation config.
- Remove validationDependencyMap from eval code base.
- Added internal dependency map to base widget.
- Added dependency map config for select, multi-select & Tabs widget.

#### PR fixes following issue(s)
Fixes #28368 
Fixes #28224

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [x] Jest
- [x] Cypress
>
>
#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [x] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [x] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [x] Cypress test cases have been added and approved by SDET/manual QA
- [x] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

File: app/client/src/sagas/EvaluationsSaga.ts [hunk 1]
```diff
@@ -375,8 +373,13 @@ export function* executeTriggerRequestSaga(
...
 
 export function* clearEvalCache() {
-  yield put({ type: ReduxActionTypes.RESET_DATA_TREE });
+  /**
+   * Reset cache in worker before resetting the dataTree
+   * This order is important because there could be pending evaluation requests that are being processed by the worker
+   * The diffs generated by the already queued eval request when applied to a reset data tree will cause unexpected crash.
+   */
   yield call(evalWorker.request, EVAL_WORKER_ACTIONS.CLEAR_CACHE);
+  yield put({ type: ReduxActionTypes.RESET_DATA_TREE });
```
Comment (ohansFavour) [inline app/client/src/sagas/EvaluationsSaga.ts:382]: This makes sense!

Nice catch :+1:

Comment (vsvamsi1) [reply app/client/src/sagas/EvaluationsSaga.ts:382]: Okay this is the part you are referring to @arunvjn, this makes sense.

File: app/client/src/sagas/PostEvaluationSagas.ts [hunk 2]
```diff
@@ -225,18 +225,14 @@ export function* evalErrorHandler(
...
-  if (dataTree && evaluationOrder && configTree && reValidatedPaths) {
+  if (dataTree && evaluationOrder && configTree) {
     const currentDebuggerErrors: Record<string, Log> =
       yield select(getDebuggerErrors);
 
-    const evalAndValidationOrder = new Set([
-      ...reValidatedPaths,
-      ...evaluationOrder,
-    ]);
+    const evalAndValidationOrder = new Set([...evaluationOrder]);
```
Comment (vsvamsi1) [inline app/client/src/sagas/PostEvaluationSagas.ts:235]: This should be fine 
Set(evaluationOrder)

File: app/client/src/workers/common/DataTreeEvaluator/index.ts [hunk 3]
```diff
@@ -352,32 +427,29 @@ export default class DataTreeEvaluator {
...
 
-    const evaluationEndTime = performance.now();
-    const validationStartTime = performance.now();
-
-    const validatedEvalTree = getValidatedTree(
+    /**
+     * We need to re-validate all widgets only in case of first tree
+     * Widget fields with custom validation functions can depend on other properties of the widget,
+     * which aren't evaluated/validated yet, thereby store incorrect validation errors in the previous step
+     */
```
[the remark this answers is not in the document]
Comment (arunvjn) [reply app/client/src/workers/common/DataTreeEvaluator/index.ts:434]: 1. We were doing something similar earlier. These micro optimisations gives us no advantage in terms of performance and often leads to hard-to-maintain code. Also, validation cannot be omitted since validation functions can transform values(questionable design choice here) and subsequent paths in the eval order might depend on this transformed value.
2. Can you give me an example here ? This might be a case that is missed out.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/Multiselect/MultiSelect5_spec.ts [hunk 4]
```diff
@@ -296,4 +296,74 @@ describe("Multi Select widget Tests", function () {
       "rgba(0, 0, 0, 0.1) 0px 10px 15px -3px, rgba(0, 0, 0, 0.05) 0px 4px 6px -2px",
     );
   });
+
+  it("8. Verify validation error in default selected values", () => {
+    entityExplorer.SelectEntityByName("NewMultiSelect", "Widgets");
+
+    propPane.MoveToTab("Content");
+
+    propPane.TypeTextIntoField(
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/Multiselect/MultiSelect5_spec.ts:305]: Type is ok, but it may fail to type it properly in cases of large string. So use 
    `propPane.UpdatePropertyFieldValue("Default selected values", '["GREEN1", "RED1"]');`
TypeTextIntoField can be used for small words.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/Multiselect/MultiSelect5_spec.ts [hunk 5]
```diff
@@ -296,4 +296,74 @@ describe("Multi Select widget Tests", function () {
...
+    agHelper.FocusElement(
+      locators._propertyInputField("Default selected values"),
+    );
+
+    agHelper.VerifyEvaluatedErrorMessage(
+      "Some or all default values are missing from options. Please update the values.",
+    );
+
+    // Reload to check if the error persists
+    cy.reload();
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/Multiselect/MultiSelect5_spec.ts:347]: Use `agHelper.Refresh()` that will also verify if the page loaded fine.

File: app/client/cypress/e2e/Regression/ClientSide/Widgets/Select/Select_Validation_spec.js [hunk 6]
```diff
@@ -29,5 +29,74 @@ describe("Select Widget Functionality", function () {
...
     );
+    _.deployMode.NavigateBacktoEditor();
+  });
+
+  it("2. Shows validation error for invalid defaultSelectedValue", () => {
+    const { agHelper, entityExplorer, locators, propPane } = _;
+
+    entityExplorer.SelectEntityByName("SelectRenamed", "Widgets");
+
+    propPane.TypeTextIntoField("Default selected value", "GREEN1", true);
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/Widgets/Select/Select_Validation_spec.js:40]: Same as above, consider using `propPane.UpdatePropertyFieldValue("Default selected value", "GREEN1");`

**Comment by Aishwarya-U-R** [comment]
> Workflow run: https://github.com/appsmithorg/appsmith/actions/runs/6652633947. Commit: ``. Cypress dashboard: [ Click here!](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6652633947&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) The following are new failures, please fix them before merging the PR:
> 
> 1. cypress/e2e/Regression/ClientSide/Widgets/Select/Select_Validation_spec.js
> 
> 
> To know the list of identified flaky tests - [Refer here](https://app.appsmith.com/applications/613868bedd7786286ddd4a6a/pages/63ec710e8e503f763651791a)

In this case, consider using `/ci-test-limit runId=` for the newly added specs & once they clean pass, you can run entire suite.

**Review by ohansFavour — APPROVED** [review]

**Comment by ramsaptami** [comment]
lgtm cc: @arunvjn

File: app/client/src/workers/common/DataTreeEvaluator/index.ts [hunk 7]
```diff
@@ -325,15 +316,99 @@ export default class DataTreeEvaluator {
...
+        );
+        // Pass it through parse
+        const { isValid, messages, parsed, transformed } =
+          validateWidgetProperty(validationConfig, value, entity, propertyPath);
+
+        set(entity, propertyPath, parsed);
+
+        const evaluatedValue = isValid
+          ? parsed
+          : isUndefined(transformed)
```
[the remark this answers is not in the document]
Comment (arunvjn) [reply app/client/src/workers/common/DataTreeEvaluator/index.ts:367]: I don't think this is used. Let's remove it across all places in an another PR
