### PR TITLE
fix: Redirection after login does not work for Google and Github

### LINKED ISSUE #9819: [Bug]: Redirection after login does not work for Google and Github
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/5298848/146347391-dfd00370-1e97-43b9-b25e-5816f82ad52b.mov

### Steps To Reproduce

1. Use direct link to an app in incognito mode.
2. After being redirected to login, use Google authentication to login

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by anvaravind**
Security.STATE_PARAMETER_ORIGIN is already set to "origin="

## Description

When we open a private application url in incognito window ( where appsmith is not logged in) and log in via any Ouath (github/google)  mechanism, after successful authentication we will be redirected to Default "/applications" page instead of actual application 
## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

   Manually 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by anvaravind** [comment]
@AnaghHegde @trishaanand can you help me in  resolving the failing checks

File: app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java [hunk 1]
```diff
@@ -181,7 +181,7 @@ private Mono<Void> handleOAuth2Redirect(WebFilterExchange webFilterExchange, App
         ServerWebExchange exchange = webFilterExchange.getExchange();
         String state = exchange.getRequest().getQueryParams().getFirst(Security.QUERY_PARAMETER_STATE);
         String redirectUrl = RedirectHelper.DEFAULT_REDIRECT_URL;
-        String prefix = Security.STATE_PARAMETER_ORIGIN + "=";
+        String prefix = Security.STATE_PARAMETER_ORIGIN;
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java:184]: Hey @anvaravind! The changes in this PR are logically sound. But do you mind getting rid of the variable entirely so that we directly reference the String value in the condition? This a very particular nitpick, only to make sure that we always use the reference directly in all usages.

Comment (anvaravind) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java]: @nidhi-nair agree with you comments, I have made changes to remove local variable, kindly check the updated files

**Comment by nidhi-nair** [comment]
Force merging since all tests have passed.
