### PR TITLE
Hotfix/trailing white spaces in mysql datasource configuration

### LINKED ISSUE #6066: [Bug] Trim trailing whitespace in MySQL datasource configuration
## Description

Trailing whitespaces in the URL, DB Name or username cause errors when testing or connecting to a MySQL datasource. 

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create a new MySQL datasource
2. Fill in the datasource settings. Ensure that the DB Name field has a trailing whitespace
3. Test the DB connection
4. User will see "Internal Server Error"

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

### PR DESCRIPTION
**Pull request by ohansFavour**
## Changes made

- Added a new method for trimming input values on the JSONtoForm class
- Triggered the method when saving and testing the datasource connection
- Added cypress tests 

Fixes #6066 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I ran all datasources tests and added a new test (app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/MySQLDatasource_spec.js)

New configuration details were added

Screenshot 2021-07-28 at 13 54 59

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: hotfix/trailing-white-spaces-in-mysql-datasource-configuration 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 53.27 **(-0.03)** | 34.74 **(-0.03)** | 31.33 **(-0.01)** | 53.83 **(-0.03)**
 :red_circle: | app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx | 46.67 **(-1.28)** | 29.63 **(0)** | 7.69 **(0)** | 46.58 **(-1.31)**
 :red_circle: | app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx | 15.48 **(-0.72)** | 18.18 **(-2.11)** | 3.85 **(-0.5)** | 16.43 **(-0.89)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

### CODE REVIEW

File: app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx [hunk 1]
```diff
@@ -208,6 +209,19 @@ export class JSONtoForm<
     return formData;
   };
 
+  getTrimmedData = (formData: any) => {
+    if (formData && typeof formData === "object") {
```
Comment (hetunandu) [inline app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx:213]: use the [getType](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/utils/TypeHelpers.ts#L16) function here

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx (hunk 1 above)
Comment (ohansFavour) [reply app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx]: All right. Fixed in latest commit.

**Review by hetunandu — APPROVED** [review]

**Review by hetunandu — APPROVED** [review]

**Review by hetunandu — APPROVED** [review]
