### PR TITLE
fix: mixpanel publish event individual query counts added

### LINKED ISSUE #21536: [Task]: Fix publish_application_application event - Mixpanel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

**Issue Summary**
The `publish_application_application` event is currently counting JS functions. It should count only the number of queries and APIs.

### PR DESCRIPTION
**Pull request by NilanshBansal**
Fixes #21536 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java [hunk 1]
```diff
@@ -1088,7 +1090,19 @@ private Mono<Application> sendApplicationPublishedEvent(Mono<List<NewPage>> publ
                     Application application = objects.getT4();
                     Map<String, Object> extraProperties = new HashMap<>();
                     extraProperties.put("pageCount", objects.getT1().size());
-                    extraProperties.put("queryCount", objects.getT2().size());
+                    Map<PluginType, Collection<NewAction>> pluginTypeCollectionMap = objects.getT2();
```
Comment (nayan-rafiq) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java:1093]: I suggest to create a small private method for the repetitive tertiary if-else. The method may look like the following: 

```
private int getActionCount(Map<PluginType, Collection<NewAction>> pluginTypeCollectionMap, PluginType pluginType) {
    if (pluginTypeCollectionMap.containsKey(pluginType)) {
        return pluginTypeCollectionMap.get(pluginType).size();
    }
    return 0;
}
```

**Review by nayan-rafiq — APPROVED** [review]
Left a comment for a small suggestion, otherwise LGTM

**Review by nayan-rafiq — APPROVED** [review]
