### PR TITLE
fix: workspace context menu is not permission driven

### LINKED ISSUE #18030: [Bug]: RBAC Issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**FRONTEND ISSUES**
- [x] [[Bug]: The hover state looks broken in the firefox browser](https://github.com/appsmithorg/appsmith/issues/18038)
- [ ] unable to check the data in the Groups & roles tab until we refresh the page each time 
- [ ] Low Priority | On visiting roles, all the checkboxes checked should be expanded

**BACKEND ISSUES**
- [x] The user icons not displayed in the workspace level where we show the user icon who are the users that are part of workspace -->This is intended  we will not show the user icon 
image

- [x] When there are 4 pages in a app and in that if one page doesn't have edit permission then deploy doesn't work ->this is expected as per the discussion https://www.loom.com/share/791306fbb3b54a5d813dd233be835c1d

- [X] Even when we have create app access not able to create new apps 
https://40edv1d3xs.vmaker.com/record/9qJSTG4zheGPiA6n

- [x] In the user's tab The User email is displayed in the Roles column
image

- [x] [Trim should be done in Datasource & queries page when pages doesn’t have the queries associated with the pages](https://github.com/appsmithorg/appsmith/issues/18312)
image

- [x] #18763
image

- [X] Unable to create a data source. We see Resource Not Found error when we are trying to create a datasource
https://40edv1d3xs.vmaker.com/record/6olr7K7k3r870N2O

- [X]  Can't Create a new Queries from data source
https://40edv1d3xs.vmaker.com/record/rKqKFM42thHuwhCN

- [X] [When user check edit access from workspace level the view access is checked from application level instead of workspace level](https://github.com/appsmithorg/appsmith/issues/18232)
https://40edv1d3xs.vmaker.com/record/ra1IqvIVdQrPkxja

- [x] [[Task - EE]: delete workspace role doesn't work](https://github.com/appsmithorg/appsmith/issues/18216)
https://40edv1d3xs.vmaker.com/record/grqukEEce76a5Cyv

- [x] [[Task - EE]: Even when user doesn't have the edit access the user can edit the data sources and even having the delete access we can not delete the datasource](https://github.com/appsmithorg/appsmith/issues/18237)
https://40edv1d3xs.vmaker.com/record/K8vLq4P1jLzEzlaA

- [x] The role of a user is hidden is the members page login as test4@appsmith.com now invite test6@appsmith.com as a appviewer and assign the role as edit workspace to test user6, Now user can navigate to members tab here the Admin user role is hidden as in screenshot 
image

- [x] Able to give Export permissions for Workspace and Apps, even if no View permissions are selected. Ideally, without View permissions selected, Export permissions should be disabled

- [ ] Recently added groups/roles should be shown at the top in Groups/Roles page.

- [x] The Widgets will be in infinite loading state when page has only view access

- [x] when we try to add a deleted user (deleted from the ACL user listing screen) to a workspace via invite modal on the homepage, we get duplicate key error.
image

- [x] #18425

- [x] Deploy the app come back to edit mode try to add a widget the No access error is displayed https://www.loom.com/share/b6be1cc5e738448b90f20daf29bd347d

- [x] On clicking create new option from omnibar for user with edit only role, it shows No results found Join our Discord Server for more help

- [x] #18391
image

### Steps To Reproduce

1. Login to the instance
2. do the changes in the roles
3. assign it to user 
4. login as a assigned user
5. check the functinality works 

### Public Sample App

_No response_

### Version

http://65.0.99.89/settings/roles

### LINKED ISSUE #18551: [Bug]: In RBAC instance the users cant import the app through JSON or git
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In RBAC instance the users cant import the app through JSON or git 
image

### Steps To Reproduce

1. Go to the admin setting
2. Create a new role
3. check the edit access on workspace from others tab
4. click on edit access on workspace from application resources tab
5. give this role access to user 1
6. now login as user 1
7. Click on 3 dots icon
8. click on import menu
9. The resource not found error is displayed

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

localhost

### LINKED ISSUE #18643: [Bug]:  Workspace context menu is not permission driven
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With granular access control the workspace context menu should be permission driven. But it is not as of now.

_Cases to handle_

- > Import App:  requires create application permission on workspace.
- > Share, Members and Leave Workspace:  requires Invite users to workspace permission.
- > Delete Workspace: requires delete workspace permission on that workspace.

### Steps To Reproduce

1.Go to homepage
2.Click on more options of any workspace
3.User can import app even when they don't have create app permission for that workspace
4.User can share,view members and settings even they are not part of the workspace

### Public Sample App

_No response_

### Issue video log

_No response_

### Version

RBAC DP

### PR DESCRIPTION
**Pull request by berzerkeer**
## Description

- Now even more workspace context menu options are permission driven.

- Also now when the user doesn't have any Action Creation options in the omnibar, `Create New` option will be hidden.

Fixes #18643 
Fixes #18030 
Fixes #18551 

Media
1. https://www.loom.com/share/d20e0b22eb524c389565a60ef41a8196
2. https://www.loom.com/share/27cb577e321449588d0f697f2764ea2f

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] PR is being merged under a feature flag

### CODE REVIEW

File: app/client/src/ce/utils/permissionHelpers.tsx [hunk 1]
```diff
@@ -5,6 +5,7 @@ export enum PERMISSION_TYPE {
   MANAGE_WORKSPACE = "manage:workspaces",
   READ_WORKSPACE = "read:workspaces",
   INVITE_USER_TO_WORKSPACE = "inviteUsers:workspace",
+  DELETE_WORKSPACE = "delete:workspace",
```
Comment (ankitakinger) [inline app/client/src/ce/utils/permissionHelpers.tsx:8]: @berzerkeer please confirm with Trisha that this is not an EE only permission.

Comment (berzerkeer) [reply app/client/src/ce/utils/permissionHelpers.tsx:8]: Oh good point. I will check, if it is an EE only permission, I will explicitly return true on CE. Like we did for the create new app permission.

Comment (berzerkeer) [reply app/client/src/ce/utils/permissionHelpers.tsx:8]: Checked with her, its EE only , I will update my PR.

File: app/client/src/components/editorComponents/GlobalSearch/index.tsx [hunk 2]
```diff
@@ -300,7 +300,12 @@ function GlobalSearch() {
 
   const searchResults = useMemo(() => {
     if (isMenu(category) && !query) {
-      return filterCategoryList.filter((cat: SearchCategory) => !isMenu(cat));
+      const shouldRemoveActionCreation = !filteredFileOperations.length;
+      return filterCategoryList.filter(
+        (cat: SearchCategory) =>
+          !isMenu(cat) &&
+          (isActionOperation(cat) ? !shouldRemoveActionCreation : true),
+      );
```
Comment (arunvjn) [inline app/client/src/components/editorComponents/GlobalSearch/index.tsx:308]: @berzerkeer This looks good but could you instead write a selector that populates the search Results based on category and query ?

Comment (berzerkeer) [reply app/client/src/components/editorComponents/GlobalSearch/index.tsx:308]: @arunvjn if it's not a blocker now can I do it in a separate PR ?

Comment (arunvjn) [reply app/client/src/components/editorComponents/GlobalSearch/index.tsx:308]: Alright!

**Review by arunvjn — DISMISSED** [review]
Code changes for the omni-bar looks good.

File: app/client/src/pages/Applications/index.tsx [hunk 3]
```diff
@@ -777,121 +787,128 @@ function ApplicationsSection(props: any) {
...
+                                )
                               }
-                              underline
+                              text="Settings"
                             />
-                          </div>
+                          </>
+                        )}
+                        {hasCreateNewApplicationPermission && (
                           <MenuItem
```
Comment (ankitakinger) [inline app/client/src/pages/Applications/index.tsx:860]: I think you have removed `enableImportExport` check here. Is that intentional?

**Comment by ankitakinger** [comment]
@berzerkeer Just sharing a loom video here notifying about something I noticed that'll happen when this PR gets merged:
https://www.loom.com/share/d20bd7ab520b4d4a9fde44f5216b8e2a

File: app/client/src/pages/Applications/index.tsx (hunk 3 above)
Comment (berzerkeer) [reply app/client/src/pages/Applications/index.tsx:860]: Oh yes, so the `enableImportExport` is a const defined in this component with the value `true`. It is being passed to the `Application Card` component for `Export App` and also to enable the `Import App` option on `Workspace options`. But since we will show / hide `Import` based on whether the user create application permission on workspace. I simply removed that check and replaced it with this.

Comment (ankitakinger) [reply app/client/src/pages/Applications/index.tsx:860]: I think let the other condition remain just in case this needs to be reused sometime by the team who worked on this feature.

**Comment by ankitakinger** [comment]
@berzerkeer 
Developer access before:
image

Developer access after:
image

File: app/client/src/pages/Applications/index.tsx (hunk 3 above)
Comment (berzerkeer) [reply app/client/src/pages/Applications/index.tsx:860]: sure. I will add it.

**Comment by berzerkeer** [comment]
> @berzerkeer Just sharing a loom video here notifying about something I noticed that'll happen when this PR gets merged: https://www.loom.com/share/d20bd7ab520b4d4a9fde44f5216b8e2a

@trishaanand So before developer access and app viewer access users were only able to see `Leave workspace` option in the menu options. Now since I added a permission check to `Members` ,`Share` & `Leave workspace` options which is only visible if the user is a member of the workspace (`inviteUsers:workspace`) . These things are visible means , the server is sending the user with `App viewer` `Developer` who are also members of the workspace the said permission. Is this correct or should it be different ?

**Comment by berzerkeer** [comment]
> > > @berzerkeer Just sharing a loom video here notifying about something I noticed that'll happen when this PR gets merged: https://www.loom.com/share/d20bd7ab520b4d4a9fde44f5216b8e2a
> > 
> > 
> > @trishaanand So before developer access and app viewer access users were only able to see `Leave workspace` option in the menu options. Now since I added a permission check to `Members` ,`Share` & `Leave workspace` options which is only visible if the user is a member of the workspace (`inviteUsers:workspace`) . These things are visible means , the server is sending the user with `App viewer` `Developer` who are also members of the workspace the said permission. Is this correct or should it be different ?
> 
> No, we would have to revert to bring this back to the existing behaviour. I suggest the following : You must have manage:workspace to see Import (which is AS IS today, correct)? You must have manage:workspace + inviteUsers:workspace to see Members page You must have inviteUsers:workspace permission to leave the workspace
> 
> I do not understand why there is a Share option when we give the Share modal right above.

Actually, the other day on call we discussed that `Import` is basically a create new application. As of today the `+New` on workspace is behind `manage:workspaceApplications` hence I used the same permission for `Import`. Should this be `manage:workspace` then ? thanks.

File: app/client/src/ce/utils/permissionHelpers.tsx [hunk 4]
```diff
@@ -16,6 +16,7 @@ export enum PERMISSION_TYPE {
   MAKE_PUBLIC_APPLICATION = "makePublic:applications",
   MAKE_PUBLIC_WORKSPACE_APPLICATIONS = "makePublic:workspaceApplications",
   PUBLISH_APPLICATION = "publish:workspaceApplications",
+  CREATE_APPLICATION = "create:applications",
```
Comment (ankitakinger) [inline app/client/src/ce/utils/permissionHelpers.tsx:19]: AFAIK, this is EE-only permission. Please confirm with Trisha once.

Comment (berzerkeer) [reply app/client/src/ce/utils/permissionHelpers.tsx:19]: >  3.  Import - create:applications on both CE and EE

This is what I got from @trishaanand from our recent convo. I believe this implies `create:applications` permission is needed in both CE and EE. Hence the need to add it in CE.

**Review by ankitakinger — APPROVED** [review]
