### PR TITLE
fix: Number type input should honour required property when value is an empty string

### LINKED ISSUE #11438: [Bug]:  Required property is not honoured in Number type input widget for empty value
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Required is enabled for the number type input widget, empty values are considered valid. We should treat the empty value as inValid value in number type input widget.

### Steps To Reproduce

1. Add an Input widget
2. Change the type to Number
3. enable Required property
4. Observe that empty values are considered valid.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by sbalaji1192**
## Description
In Number type Input, when value is empty, it gets converted to `0`. As a result isValid check passes. as part of this commit we made sure that the empty string is handled properly in the isValid check.

Fixes #11438 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/number-type-input-required 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 55.74 **(0)** | 37.08 **(0.01)** | 35.82 **(0)** | 56.1 **(0)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 **(-0.25)**
 :green_circle: | app/client/src/widgets/InputWidgetV2/widget/derived.js | 78.72 **(0)** | 77.36 **(2.89)** | 100 **(0)** | 78.72 **(0)**</details>

### CODE REVIEW

File: app/client/src/widgets/InputWidgetV2/widget/index.tsx [hunk 1]
```diff
@@ -363,7 +363,7 @@ class InputWidget extends BaseInputWidget<InputWidgetProps, WidgetState> {
             parsedValue = Number(value);
 
             if (isNaN(parsedValue)) {
-              parsedValue = undefined;
+              parsedValue = null;
```
Comment (sbalaji1192) [inline app/client/src/widgets/InputWidgetV2/widget/index.tsx:366]: Not related to the issue. just made this change to be consistent with empty values in Number type.

**Review by jsartisan — APPROVED** [review]
