### PR TITLE
fix: fixed auto indent in fields that contains JSON inside binding

### LINKED ISSUE #25325: [Bug]: Incorrect formatting indent
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create the API, before I write the request parameters, which are formatted as JSON, when I press command s to save, an error occurs with the indentation of the default formatting

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/12797847/0a95f19b-aaf5-4d9e-a7d8-117a4ec766b4

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://github.com/appsmithorg/appsmith/assets/12797847/0a95f19b-aaf5-4d9e-a7d8-117a4ec766b4

### Version

Appsmith Community v1.9.22

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fixes auto indent on save in field that contains JS objects

#### PR fixes following issue(s)
Fixes #25325

#### Type of change
- Bug fix (non-breaking change which fixes an issue)
>
>
#### How Has This Been Tested?
- [x] Manual
- [x] Cypress
>
>
#### Test Plan
1. Verified query and api parameter for indentation after command +S 
2. Verified code editor for object and array indentation and cmd+s
3. Verified chrome and firefox browser for cmd+s

#### Dev activity
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [x] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by ohansFavour — DISMISSED** [review]

File: app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js [hunk 1]
```diff
@@ -341,4 +343,23 @@ myFun2: async () => {
     cy.get("div.CodeMirror").type("{cmd+leftArrow}");
     cy.get("div.CodeMirror").matchImageSnapshot("jsObjAfterGoLineStartSmart5");
   });
+
+  it.only("5. TC 1862 - JSEditor validation for goLineStartSmart with no errors, triggered by keyboard shortcut", () => {
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js:347]: Remove .only please.

File: app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js [hunk 2]
```diff
@@ -341,4 +343,23 @@ myFun2: async () => {
...
+        {
+          "title": this.params.title,
+              "due": this.params.due,
+                  assignee: this.params.assignee 
+                  }
+      }}`,
+    );
+    cy.get("body").type(agHelper.isMac ? "{meta}S" : "{ctrl}S");
+    cy.get(apiPage.jsonBody).matchImageSnapshot(
+      "formattedJSONBodyAfterSave",
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js:362]: Hope this snapshot was taken in headless mode. Else it will fail in CI runs.

File: app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js (hunk 1 above)
Comment (arunvjn) [reply app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js]: Done

**Review by Aishwarya-U-R — COMMENTED** [review]
Cypress changes looks fine.

**Review by Rishabh-Rathod — APPROVED** [review]
