### PR TITLE
[Fix] - Authentication after 404 not redirecting back to the original page

### LINKED ISSUE #2415: [Bug] Authentication after 404 not redirecting back to the original page
## Description
If you land on a private app without authentication, it is shown as 404. But after you sign in, you are redirected back to the homepage instead of the app

Steps
1) Create a private app
2) Logout and visit the app
3) On seeing the 404 error, sign in
4) After sign in, you will go to the home page

### PR DESCRIPTION
**Pull request by jsartisan**
If you land on a private app without authentication, it is shown as 404. But after you sign in, you are redirected back to the homepage instead of the app

Fixes #2415 

## Type of change
- Bugfix

## How Has This Been Tested?
- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/pages/common/PageNotFound.tsx [hunk 1]
```diff
@@ -23,9 +26,18 @@ const Wrapper = styled.div`
...
 }
+
 const PageNotFound: React.FC<Props> = (props: Props) => {
-  const { flushErrorsAndRedirect } = props;
+  const { flushErrorsAndRedirect, user } = props;
+
+  // if we have logged in user, append the current url in login url with `redirectTo` param
+  // logged in user here means email is not "anonymousUser"
+  const redirectURL =
+    get(user, "email") !== "anonymousUser"
```
Comment (hetunandu) [inline app/client/src/pages/common/PageNotFound.tsx:38]: This behaviour of appending the url should happen depending on the error and not on the auth user currently. Please confirm with backend the error code for an existing app but permission denied and decide the redirect url for that

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/pages/common/PageNotFound.tsx (hunk 1 above)
Comment (jsartisan) [reply app/client/src/pages/common/PageNotFound.tsx]: @hetunandu I just changed the logic. Nikhil asked to redirect "not logged in" directly to the login page with `redirectTo` param. For other users, on clicking the button, the user will be redirected to the applications page. 

> Please confirm with backend the error code for an existing app but permission denied and decide the redirect URL for that
We get a 404 status code for `existing app but permission denied`.  Currently, we are not differentiating between existing apps ( but permission denied ) and non-existing apps.

**Review by hetunandu — CHANGES_REQUESTED** [review]
This does not check for if the app exists or not. That means it will redirect even if the app or page does not really exist

**Comment by jsartisan** [comment]
> This does not check for if the app exists or not. That means it will redirect even if the app or page does not really exist

@hetunandu Seems like that is intentional for security reasons.

File: app/client/src/pages/common/PageNotFound.tsx [hunk 2]
```diff
@@ -23,9 +26,18 @@ const Wrapper = styled.div`
...
+  user?: any;
 }
+
 const PageNotFound: React.FC<Props> = (props: Props) => {
-  const { flushErrorsAndRedirect } = props;
+  const { flushErrorsAndRedirect, user } = props;
+
+  // if user is not logged, directly take him to the login page with `redirectTo` param
+  if (get(user, "email") === "anonymousUser") {
+    window.location.href = `${AUTH_LOGIN_URL}?redirectTo=${window.location.href}`;
```
Comment (hetunandu) [inline app/client/src/pages/common/PageNotFound.tsx:37]: This check can happen at the error level directly now since it is a redirect, dont render the PageNotFound page at all

**Comment by jsartisan** [comment]
@hetunandu replaced every occurrence of `redirectTo` to `redirectUrl`.

File: app/client/src/pages/common/PageNotFound.tsx [hunk 3]
```diff
@@ -56,6 +60,10 @@ const PageNotFound: React.FC<Props> = (props: Props) => {
   );
 };
 
-export default connect(null, {
+const mapStateToProps = (state: AppState) => ({
+  user: getCurrentUser(state),
+});
+
+export default connect(mapStateToProps, {
```
Comment (hetunandu) [inline app/client/src/pages/common/PageNotFound.tsx:67]: Not needed anymore right?

File: app/client/src/sagas/ErrorSagas.tsx [hunk 4]
```diff
@@ -154,6 +159,33 @@ function* crashAppSaga() {
   });
 }
 
+/**
+ * this saga do some logic before actually setting safeCrash to true
+ */
+function* preSafeCrashSaga(action: ReduxAction<{ code?: string }>) {
```
Comment (hetunandu) [inline app/client/src/sagas/ErrorSagas.tsx:165]:
```suggestion
function* safeCrashSagaRequest(action: ReduxAction<{ code?: string }>) {
```

File: app/client/src/sagas/ErrorSagas.tsx [hunk 5]
```diff
@@ -177,4 +209,8 @@ export default function* errorSagas() {
     ReduxActionTypes.FLUSH_AND_REDIRECT,
     flushErrorsAndRedirectSaga,
   );
+  yield takeLatest(
+    ReduxActionTypes.SAFE_CRASH_APPSMITH_REQUEST,
+    preSafeCrashSaga,
```
Comment (hetunandu) [inline app/client/src/sagas/ErrorSagas.tsx:214]:
```suggestion
    safeCrashSagaRequest,
```

**Review by hetunandu — CHANGES_REQUESTED** [review]

File: app/client/src/sagas/ErrorSagas.tsx (hunk 4 above)
Comment (jsartisan) [reply app/client/src/sagas/ErrorSagas.tsx]: Oh sorry. I forgot this name change. Updated now.

File: app/client/src/pages/common/PageNotFound.tsx (hunk 3 above)
Comment (jsartisan) [reply app/client/src/pages/common/PageNotFound.tsx]: Removed.

**Review by hetunandu — APPROVED** [review]
