### PR TITLE
fix: resetting audio and video widget

### LINKED ISSUE #14692: [Bug]-[64]:Resetting audio and video widget resets playState values but widget UI does not change play state
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When resetting audio and video widget, playState value resets to **NOT_STARTED** but the widget UI does not change play state

### Steps To Reproduce

1. Set an audio and video widget to reset using a button trigger field like so : `{{resetWidget('Audio1')}}`
2. Drop a text widget on the canvas and bind Audio/Video widget playState to this widget
3. Press play on the audio/video widget
4. Now trigger resetWidget reset using button widget
5. Observe the playState on the text widget changes from current state of **PLAYING/PAUSED** to **NOT_PLAYING** but UI does not change

https://www.loom.com/share/68026b0a41664d9eb8fbca37f8b2fa7a

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by iamrkcheers**
## Description

Resetting audio and video widget ui when playstate value resets

Fixes #14692 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manual
- Cypress

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/widgets/AudioWidget/widget/index.tsx [hunk 1]
```diff
@@ -130,6 +130,10 @@ class AudioWidget extends BaseWidget<AudioWidgetProps, WidgetState> {
     return {};
   }
 
+  componentDidUpdate(): void {
+    if (this.props.playState === "NOT_STARTED") this._player.current?.seekTo(0);
```
Comment (sbalaji1192) [inline app/client/src/widgets/AudioWidget/widget/index.tsx:134]: only call when playState changes

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js [hunk 2]
```diff
@@ -52,4 +52,43 @@ describe("Audio Widget Functionality", function() {
       200,
     );
   });
+
+  it("Resets audio widget when it is paused", function() {
+    cy.get(commonlocators.onPause).click();
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:57]: What is that we're testing in this test case?

Comment (sbalaji1192) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:57]: we can remove this

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js [hunk 3]
```diff
@@ -52,4 +52,43 @@ describe("Audio Widget Functionality", function() {
...
+      widgetsPage.buttonWidget,
+      commonlocators.buttonInner,
+    );
+    cy.get(commonlocators.onClick).click();
+    cy.selectResetWidget();
+    cy.selectWidgetForReset("Audio1");
+    cy.openPropertyPane("audiowidget");
+    cy.get(widgetsPage.autoPlay).click({ force: true });
+    cy.get(widgetsPage.widgetBtn).click({ force: true });
+    cy.wait("@updateLayout").should(
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:88]: we need to assert the play state of the audio dom element

File: app/client/cypress/support/widgetCommands.js [hunk 4]
```diff
@@ -892,6 +892,24 @@ Cypress.Commands.add("addSuccessMessage", (value) => {
...
+
+Cypress.Commands.add("selectWidgetForReset", (value) => {
+  cy.get(commonlocators.chooseWidget)
+    .last()
+    .click({ force: true });
+  cy.get(commonlocators.chooseAction)
+    .children()
+    .contains(value)
+    .click();
+  // cy.enterActionValue(value);
```
Comment (sbalaji1192) [inline app/client/cypress/support/widgetCommands.js:910]: remove

File: app/client/src/widgets/VideoWidget/component/index.tsx [hunk 5]
```diff
@@ -70,7 +70,7 @@ export default function VideoComponent(props: VideoComponentProps) {
       <ReactPlayer
         controls={controls || true}
         height="100%"
-        muted={autoplay}
+        muted={playing}
```
Comment (sbalaji1192) [inline app/client/src/widgets/VideoWidget/component/index.tsx:73]: This will mute video player any time it gets played.

File: app/client/src/widgets/VideoWidget/widget/index.tsx [hunk 6]
```diff
@@ -170,26 +170,59 @@ class VideoWidget extends BaseWidget<VideoWidgetProps, WidgetState> {
 
   static getMetaPropertiesMap(): Record<string, any> {
     return {
+      // Static property reflecting the state of the widget
```
Comment (sbalaji1192) [inline app/client/src/widgets/VideoWidget/widget/index.tsx:173]: What do you mean by static property?

File: app/client/src/widgets/VideoWidget/widget/index.tsx [hunk 7]
```diff
@@ -170,26 +170,59 @@ class VideoWidget extends BaseWidget<VideoWidgetProps, WidgetState> {
...
       playState: PlayState.NOT_STARTED,
+      // Static property passed onto the video player making it a controlled component
+      playing: false,
     };
   }
 
   static getDefaultPropertiesMap(): Record<string, string> {
-    return {};
+    return {
+      // Plays the video player by default and when reset, if autoPlay is on (and vice versa)
```
Comment (sbalaji1192) [inline app/client/src/widgets/VideoWidget/widget/index.tsx:182]: remove this comment.

File: app/client/src/widgets/VideoWidget/widget/index.tsx [hunk 8]
```diff
@@ -170,26 +170,59 @@ class VideoWidget extends BaseWidget<VideoWidgetProps, WidgetState> {
...
+  // TODO: (Balaji) Can we have dynamic default value that accepts current widget values and determines the default value.
+  componentDidUpdate(prevProps: VideoWidgetProps) {
+    // When the widget is reset
+    if (
+      prevProps.playState !== "NOT_STARTED" &&
+      this.props.playState === "NOT_STARTED"
+    ) {
+      this._player.current?.seekTo(0);
+
+      // When autoPlay & playing are true
```
Comment (sbalaji1192) [inline app/client/src/widgets/VideoWidget/widget/index.tsx:197]: remove this comment.

File: app/client/src/widgets/VideoWidget/widget/index.tsx [hunk 9]
```diff
@@ -170,26 +170,59 @@ class VideoWidget extends BaseWidget<VideoWidgetProps, WidgetState> {
...
+      if (this.props.playing) {
+        this.props.updateWidgetMetaProperty("playState", PlayState.PLAYING);
+      }
+    }
+
+    // When autoPlay changes
+    if (prevProps.autoPlay !== this.props.autoPlay) {
```
Comment (sbalaji1192) [inline app/client/src/widgets/VideoWidget/widget/index.tsx:204]: // When autoPlay changes changes from property pane

File: app/client/src/widgets/AudioWidget/widget/index.tsx [hunk 10]
```diff
@@ -122,22 +122,55 @@ class AudioWidget extends BaseWidget<AudioWidgetProps, WidgetState> {
 
   static getMetaPropertiesMap(): Record<string, any> {
     return {
+      // Static property reflecting the state of the widget
```
Comment (sbalaji1192) [inline app/client/src/widgets/AudioWidget/widget/index.tsx:125]: what do you mean by static property?

File: app/client/src/widgets/AudioWidget/widget/index.tsx [hunk 11]
```diff
@@ -122,22 +122,55 @@ class AudioWidget extends BaseWidget<AudioWidgetProps, WidgetState> {
...
       playState: PlayState.NOT_STARTED,
+      // Static property passed onto the audio player making it a controlled component
+      playing: false,
     };
   }
 
   static getDefaultPropertiesMap(): Record<string, string> {
-    return {};
+    return {
+      // Plays the audio player by default and when reset, if autoPlay is on (and vice versa)
```
Comment (sbalaji1192) [inline app/client/src/widgets/AudioWidget/widget/index.tsx:134]: remove this comment. Its self explainatory

File: app/client/src/widgets/AudioWidget/widget/index.tsx [hunk 12]
```diff
@@ -122,22 +122,55 @@ class AudioWidget extends BaseWidget<AudioWidgetProps, WidgetState> {
...
+  // TODO: (Balaji) Can we have dynamic default value that accepts current widget values and determines the default value.
+  componentDidUpdate(prevProps: AudioWidgetProps) {
+    // When the widget is reset
+    if (
+      prevProps.playState !== "NOT_STARTED" &&
+      this.props.playState === "NOT_STARTED"
+    ) {
+      this._player.current?.seekTo(0);
+
+      // When autoPlay & playing are true
```
Comment (sbalaji1192) [inline app/client/src/widgets/AudioWidget/widget/index.tsx:149]: Why do we mention that when autoplay is true but we are not checking that in the condition?
Remove the comment.

File: app/client/src/widgets/AudioWidget/widget/index.tsx [hunk 13]
```diff
@@ -122,22 +122,55 @@ class AudioWidget extends BaseWidget<AudioWidgetProps, WidgetState> {
...
+      if (this.props.playing) {
+        this.props.updateWidgetMetaProperty("playState", PlayState.PLAYING);
+      }
+    }
+
+    // When autoPlay changes
```
Comment (sbalaji1192) [inline app/client/src/widgets/AudioWidget/widget/index.tsx:155]: // When autoPlay changes from property pane

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js [hunk 14]
```diff
@@ -52,4 +52,27 @@ describe("Audio Widget Functionality", function() {
       200,
     );
   });
+
+  it("Resets audio widget on button click", function() {
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:56]: description should dictate what is being asserted. like "should check that playstate is getting reset when the widget gets reset."

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js [hunk 15]
```diff
@@ -52,4 +52,27 @@ describe("Audio Widget Functionality", function() {
...
+    );
+    cy.get(commonlocators.onClick).click();
+    cy.selectResetWidget();
+    cy.selectWidgetForReset("Audio1");
+    cy.openPropertyPane("audiowidget");
+    cy.get(widgetsPage.autoPlay).click({ force: true });
+    cy.wait(1000);
+    cy.get(widgetsPage.autoPlay).click({ force: true });
+    cy.get(widgetsPage.widgetBtn).click({ force: true });
+    cy.wait(1000);
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:72]: why do we need this wait times?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js [hunk 16]
```diff
@@ -52,4 +52,27 @@ describe("Audio Widget Functionality", function() {
...
+    cy.get(`${widgetsPage.audioWidget} audio`).then(($audio) => {
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:73]: we should also check whether playstate gets reset.

File: app/client/src/widgets/VideoWidget/widget/index.tsx (hunk 6 above)
Comment (iamrkcheers) [reply app/client/src/widgets/VideoWidget/widget/index.tsx]: Removed

File: app/client/src/widgets/AudioWidget/widget/index.tsx (hunk 10 above)
Comment (iamrkcheers) [reply app/client/src/widgets/AudioWidget/widget/index.tsx]: Removed

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js (hunk 16 above)
Comment (iamrkcheers) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:73]: Added additional test case for this

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js [hunk 17]
```diff
@@ -52,4 +52,40 @@ describe("Audio Widget Functionality", function() {
...
+      const audio = $audio.get(0);
+      expect(audio.currentTime).to.equal(0);
+    });
+  });
+
+  it("Checks if audio widget playstate is reset when the widget gets reset", function() {
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:79]: no need for a separate case you can club it with previous one

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js (hunk 15 above)
Comment (sbalaji1192) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:72]: Any update?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Others/Video_spec.js [hunk 18]
```diff
@@ -73,6 +75,43 @@ describe("Video Widget Functionality", function() {
...
+    cy.get(widgetsPage.widgetBtn).click({ force: true });
+    cy.wait(1000);
+    cy.get(`${widgetsPage.videoWidget} video`).then(($video) => {
+      const video = $video.get(0);
+      expect(video.currentTime).to.equal(0);
+    });
+  });
+
+  it("Checks if video widget playstate is reset when the widget gets reset", function() {
+    cy.dragAndDropToCanvas("textwidget", { x: 300, y: 500 });
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Others/Video_spec.js:103]: club it with previous case

File: app/client/src/widgets/VideoWidget/component/index.tsx [hunk 19]
```diff
@@ -70,7 +70,6 @@ export default function VideoComponent(props: VideoComponentProps) {
       <ReactPlayer
         controls={controls || true}
         height="100%"
-        muted={autoplay}
```
Comment (sbalaji1192) [inline app/client/src/widgets/VideoWidget/component/index.tsx:73]: we had this attribute just so the video is muted when it autoplay on the page load. Playing audio on load is generally bad UX. Reinstate this line.

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js (hunk 15 above)
Comment (iamrkcheers) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:72]: So the widget is being played and paused before being reset. Without the wait time, it is being reset at Zero itself. Just wanted a second to elapse before resetting.

Comment (sbalaji1192) [reply app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js:77]: Can you mention that as a comment here?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Others/Video_spec.js [hunk 20]
```diff
@@ -1,10 +1,12 @@
 const widgetsPage = require("../../../../../locators/Widgets.json");
 const commonlocators = require("../../../../../locators/commonlocators.json");
 const dsl = require("../../../../../fixtures/videoWidgetDsl.json");
+const buttondsl = require("../../../../../fixtures/buttondsl.json");
 const testdata = require("../../../../../fixtures/testdata.json");
 
 describe("Video Widget Functionality", function() {
   before(() => {
+    cy.addDsl(buttondsl);
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Others/Video_spec.js:9]: addDSL replaces existing DSL, so here buttondsl will get replaced with dsl. why are we calling it in succession?

File: app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Others/Video_spec.js [hunk 21]
```diff
@@ -1,6 +1,7 @@
 const widgetsPage = require("../../../../../locators/Widgets.json");
 const commonlocators = require("../../../../../locators/commonlocators.json");
 const dsl = require("../../../../../fixtures/videoWidgetDsl.json");
+const buttondsl = require("../../../../../fixtures/buttondsl.json");
```
Comment (sbalaji1192) [inline app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Others/Video_spec.js:4]: remove unused import

**Review by sbalaji1192 — APPROVED** [review]

**Comment by laveena-en** [comment]
@iamrkcheers @dilippitchika The fix for the camera widget mentioned in the same thread https://github.com/appsmithorg/appsmith/issues/14692#issuecomment-1160698296 hasn’t been covered in this PR. 
Shall I raise a separate issue for it or do we add this to the scope in the current PR itself?

cc: @sbalaji1192

**Comment by dilippitchika** [comment]
Thanks for pointing this @laveena-en, yes you can raise a separate issue for this

**Comment by laveena-en** [comment]
Raising a separate issue for the camera widget here: https://github.com/appsmithorg/appsmith/issues/18622

**Comment by laveena-en** [comment]
Tested and verified the PR. Internal properties and UI are being reset as expected.
