### PR TITLE
fix: listwidget in formwidget

### LINKED ISSUE #21113: [Bug]: List widget gets blank when added inside Form Widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On adding a List widget inside Form widget, the List widget gets blank along with some error on console.
On binding the same List widget with Datasources, the pagination appears but List widget's data remains blank

### Steps To Reproduce

1. Drag & Drop a Form Widget
2. Drag & Drop a List widget inside Form widget
3. Observe that List widget is blank

### Public Sample App

_No response_

### Environment

Production

### Issue video log

https://bthrujcsw8.vmaker.com/record/1ey8INkuMjb2XpiM

### Version

Cloud / Production

### LINKED ISSUE #21268: [Bug]: the page becomes unresponsive when the we increase the page size of the nested List
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the page becomes unresponsive when the we increase the page size of the nested List

### Steps To Reproduce

https://www.loom.com/share/271e75fc05364c2a8f6d4cc178dfdcc6

### Environment

**Release**

### Version

Cloud/Release

### PR DESCRIPTION
**Pull request by Tooluloope**
## Description

The list widget should be visible in the Form widget.
Also, updatePageNo shouldn't be called recursively when the List widget Height is adjusted.

Fixes #21113 
Fixes #21268 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual

### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/client/src/utils/widgetRenderUtils.tsx [hunk 1]
```diff
@@ -22,6 +22,7 @@ export const createCanvasWidget = (
   const widgetStaticProps = pick(canvasWidget, [
     ...Object.keys(WIDGET_STATIC_PROPS),
     ...(canvasWidget.additionalStaticProps || []),
+    ...["hasMetaWidgets", "requiresFlatWidgetChildren"],
```
Comment (ashit-rath) [inline app/client/src/utils/widgetRenderUtils.tsx:25]: Can we add these to `additionalStaticProps`? let's not have keys like this, it doesn't give any context

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx [hunk 2]
```diff
@@ -520,9 +520,20 @@ class ListWidget extends BaseWidget<
...
 
-  updatePageSize = () => {
-    super.updateWidgetProperty("pageSize", this.pageSize);
-  };
+  /**
+   * To prevent an infinite loop, this function is throttled to avoid recursively updating pageSize.
+   * The reason is that updateWidgetProperty doesn't immediately update the widget property, and when componentDidUpdate is called,
+   * it triggers another update, leading to an infinite loop.
+   */
+  updatePageSize = throttle(
```
Comment (ashit-rath) [inline app/client/src/widgets/ListWidgetV2/widget/index.tsx:528]: Is this the final solution we are proposing? Were you able to find out which PR caused this?

File: app/client/src/utils/widgetRenderUtils.tsx (hunk 1 above)
Comment (Tooluloope) [reply app/client/src/utils/widgetRenderUtils.tsx:25]: We could use DSL_STRUCTURE_PROPS.

File: app/client/src/widgets/ListWidgetV2/widget/index.tsx (hunk 2 above)
Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:528]: Yeah, I messaged @prsidhu concerning the issue, as I could pinpoint the problem only on this branch https://github.com/appsmithorg/appsmith/pull/21151. He's looking into it, but we can go with this for now.

Comment (ashit-rath) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:528]: So this is a temporary fix?
Is 2000 too much for this and should we have leading true than trailing true?

Comment (Tooluloope) [reply app/client/src/widgets/ListWidgetV2/widget/index.tsx:529]: I tried using 200. It was called four times, so I settled with 500ms. Also, read and tested out
1. Trailing and leading => true 
2. Trailing -> true, Leading -> false
3. leading -true, trailing -> false

They were all called twice. Since it would be called at the beginning of throttling, all subsequent calls would be merged into one after the 500ms.

**Comment by kamakshibhat-appsmith** [comment]
the page becomes unresponsive when we increase the size of list item container inside form with SSP on. [LOOM](https://www.loom.com/share/548530aaa0eb45bf9072f93b32890a67)

**Comment by kamakshibhat-appsmith** [comment]
https://github.com/appsmithorg/appsmith/pull/21234#issuecomment-1461520291
EDIT :the page becomes unresponsive when we increase the size of list item container inside form/Modal/Tab/List with SSP on. [LOOM](https://www.loom.com/share/548530aaa0eb45bf9072f93b32890a67)
@Tooluloope

**Comment by kamakshibhat-appsmith** [comment]
LGTM !!

File: app/client/src/utils/widgetRenderUtils.tsx [hunk 3]
```diff
@@ -20,7 +23,7 @@ export const createCanvasWidget = (
   specificChildProps?: string[],
 ) => {
   const widgetStaticProps = pick(canvasWidget, [
-    ...Object.keys(WIDGET_STATIC_PROPS),
+    ...Object.keys({ ...WIDGET_STATIC_PROPS, ...WIDGET_DSL_STRUCTURE_PROPS }),
```
Comment (marks0351) [inline app/client/src/utils/widgetRenderUtils.tsx:26]: Why do we need this change?

**Review by marks0351 — CHANGES_REQUESTED** [review]

File: app/client/src/utils/widgetRenderUtils.tsx (hunk 3 above)
Comment (Tooluloope) [reply app/client/src/utils/widgetRenderUtils.tsx:26]: Yeah, it's for the Form Widget.
I think I need to add some code comments there.
