### PR TITLE
Fix-Hide table filters delete icon when there is no filters

### LINKED ISSUE #2135: [Bug] The disabled delete icon shouldn't appear when there's no filter
## Description
I assumed that the delete icon was meant to close the filter window. The delete action only makes sense once there has been an edit on the filter options, or maybe have a separate clear action for that.

image

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

### PR DESCRIPTION
**Pull request by vicky-primathon**
## Description
Hide table filters delete icon when there is no filters

Fixes #2135 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/components/designSystems/appsmith/CascadeFields.tsx [hunk 1]
```diff
@@ -28,6 +28,9 @@ const StyledRemoveIcon = styled(
   padding: 0;
   position: relative;
   cursor: pointer;
+  &.hide-icon {
+    opacity: 0;
```
Comment (riodeuno) [inline app/client/src/components/designSystems/appsmith/CascadeFields.tsx:32]: Let's make this display:none instead.

**Review by riodeuno — APPROVED** [review]
