### PR TITLE
Scheduling of parallel tasks implementation for on-page load actions

### LINKED ISSUE #2562: [Bug] OnPageLoad execution order is incorrect
## Description

A single query fails intermittently on page load. This query fetch_monthly_dead_apps depends on another query and should run once it's execution is complete
https://app.appsmith.com/applications/5ffeeadc5b452f525458d4d5/pages/5ffeeadc5b452f525458d4e1/edit

### Steps to reproduce the behaviour:
1. Refresh the page multiple times till you see an error in the 4th table for dead apps

The layout action response is incorrect in this case. There are 2 problems
1. fetch_monthly_active_apps is repeated twice in this call stack
2. all the parallel actions are in the second array position which will delay all other action calls. Instead only the dead apps should be in the second position

```[
  [
    {
      "id": "5ffeeadd5b452f525458d4e9",
      "name": "fetch_monthly_active_apps",
      "pluginType": "DB",
      "jsonPathKeys": [
        "moment().add(-1,'months').format(\"YYYY-MM\")"
      ],
      "timeoutInMillisecond": 10000
    }
  ],
  [
    {
      "id": "5ffeeadd5b452f525458d4ed",
      "name": "fetch_monthly_dead_apps",
      "pluginType": "DB",
      "jsonPathKeys": [
        "moment().add(-2,'months').format(\"YYYY-MM\")",
        "fetch_monthly_active_apps.data.map((app) => \"'\" + app.active_app + \"'\").join(\",\")"
      ],
      "timeoutInMillisecond": 10000
    },
    {
      "id": "5ffeeadd5b452f525458d4e9",
      "name": "fetch_monthly_active_apps",
      "pluginType": "DB",
      "jsonPathKeys": [
        "moment().add(-1,'months').format(\"YYYY-MM\")"
      ],
      "timeoutInMillisecond": 10000
    },
    {
      "id": "5ffeeadd5b452f525458d50f",
      "name": "fetch_weekly_active_apps",
      "pluginType": "DB",
      "jsonPathKeys": [
        "moment().add(-30,'days').format(\"YYYY-WW\")"
      ],
      "timeoutInMillisecond": 10000
    }
  ]
]```

### PR DESCRIPTION
**Pull request by trishaanand**
Fixes #2562

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java [hunk 1]
```diff
@@ -639,4 +465,88 @@ private void extractAllWidgetNamesAndDynamicBindingsFromDSL(JSONObject dsl, Set<
...
+            // There is no DSL here. No need to process anything. Return as is.
+            return Mono.just(layout);
+        }
+
+        Set<String> widgetNames = new HashSet<>();
+        Set<String> dynamicBindings = new HashSet<>();
+        try {
+            extractAllWidgetNamesAndDynamicBindingsFromDSL(dsl, widgetNames, dynamicBindings);
+        } catch (Throwable t) {
+            throw Exceptions.propagate(t);
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java:482]: Return a Mono.error from here.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java [hunk 2]
```diff
@@ -862,6 +862,30 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
...
+        if (actions == null) {
+            return Mono.just(Boolean.FALSE);
+        }
+
+        List<ActionDTO> toUpdateActions = new ArrayList<>();
+
+        for (ActionDTO action : actions) {
+            // If a user has ever set execute on load, this field can not be changed automatically. It has to be
+            // explicitly changed by the user again. Add the action to update only if this condition is false.
+            if (!TRUE.equals(action.getUserSetOnLoad())) {
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:876]: Since `userSetOnLoad` has a default value of `false`, suggest simplifying this condition to `FALSE.equals()`

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java [hunk 3]
```diff
@@ -862,6 +862,30 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
...
+                action.setExecuteOnLoad(TRUE);
+                toUpdateActions.add(action);
+            }
+        }
+
+        return Mono.just(toUpdateActions)
+                .flatMapMany(Flux::fromIterable)
+                .flatMap(actionDTO -> updateUnpublishedAction(actionDTO.getId(), actionDTO))
+                .collectList()
+                .thenReturn(TRUE);
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:886]: I think we can simplify this code.

```suggestion
return Flux.fromIterable(toUpdateActions)
                .flatMap(actionDTO -> updateUnpublishedAction(actionDTO.getId(), actionDTO))
                .then(Mono.just(TRUE));```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java [hunk 4]
```diff
@@ -0,0 +1,266 @@
...
+import static com.appsmith.server.helpers.MustacheHelper.extractWordsAndAddToSet;
+
+@Slf4j
+@Component
+@RequiredArgsConstructor
+public class PageLoadActionsUtil {
+
+    private final NewActionService newActionService;
+
+    public Mono<List<HashSet<DslActionDTO>>> findAllOnLoadActions(Set<String> bindings,
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java:32]: Since parameters are being passed by reference, suggest adding a function doc explaining what this function does and warning future devs that values will be manipulated.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java [hunk 5]
```diff
@@ -0,0 +1,266 @@
...
+
+                    // Return the sequenced page load actions
+                    return onPageLoadActions;
+
+                });
+    }
+
+    private DslActionDTO getDslAction (String name, Map<String, ActionDTO> onLoadActionsMap) {
+        ActionDTO action = onLoadActionsMap.get(name);
+        DslActionDTO actionDTO = new DslActionDTO();
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java:98]:
```suggestion
        DslActionDTO dslActionDTO = new DslActionDTO();
```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java [hunk 6]
```diff
@@ -0,0 +1,266 @@
...
+                    flatPageLoadActions.addAll(updatedMap.values());
+
+                    // Return the sequenced page load actions
+                    return onPageLoadActions;
+
+                });
+    }
+
+    private DslActionDTO getDslAction (String name, Map<String, ActionDTO> onLoadActionsMap) {
+        ActionDTO action = onLoadActionsMap.get(name);
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java:97]:
```suggestion
        ActionDTO actionDTO = onLoadActionsMap.get(name);
```

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java [hunk 7]
```diff
@@ -0,0 +1,266 @@
...
+        List<String> rootNodes = dag.vertexSet().stream()
+                .filter(key -> dag.incomingEdgesOf(key).size() == 0)
+                .collect(Collectors.toList());
+
+        BreadthFirstIterator<String, DefaultEdge> bfsIterator = new BreadthFirstIterator<>(dag, rootNodes);
+
+        // Implementation of offline scheduler by using level by level traversal. Level i+1 actions would be dependent
+        // on Level i actions. All actions in a level can run independently and hence would get added to the same set.
+        while(bfsIterator.hasNext()) {
+            String vertex=bfsIterator.next();
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java:254]: Please format all the files

File: app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java [hunk 8]
```diff
@@ -293,7 +294,7 @@ public void getActionsExecuteOnLoad() {
                     action.getActionConfiguration().setHttpMethod(HttpMethod.POST);
                     action.getActionConfiguration().setBody(
                             "this won't be auto-executed: {{aPostSecondaryAction.data}}, but this one will be: {{aPostTertiaryAction.data}}.");
-                    action.setJsonPathKeys(Set.of("aPostSecondaryAction.data", "aPostTertiaryAction.data"));
+                        action.setJsonPathKeys(Set.of("aPostSecondaryAction.data", "aPostTertiaryAction.data"));
```
Comment (mohanarpit) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java:297]: Suggest adding a doc on this test to explain what is happening. Will be much easier for future "us" to glean what is being tested here.

**Review by mohanarpit — DISMISSED** [review]

File: app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java [hunk 9]
```diff
@@ -0,0 +1,283 @@
...
+                            return action;
+                        }
+                )
+                .map(newActionsMap -> {
+                    onLoadActionsInMap.putAll(newActionsMap);
+                    return onLoadActionsInMap;
+                });
+    }
+
+    private Mono<Map<String, ActionDTO>> recursivelyFindActionsAndTheirDependents(Set<String> dynamicBindingNames,
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java:190]: @trishaanand Could you please add a few comments here as well? I am having a hard time figuring out whether the recursive calls will eliminate actions that have already been calculated.

Comment (trishaanand) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java:154]: Added a note to explain the role of the function. This simply calculates the global set of actions which eventually would be put in a proper sequence.

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java [hunk 10]
```diff
@@ -862,6 +862,30 @@ private DatasourceConfiguration updateDatasourceConfigurationForPagination(Actio
         return repository.findByPageId(pageId);
     }
 
+    @Override
+    public Mono<Boolean> setOnLoad(List<ActionDTO> actions) {
```
[the remark this answers is not in the document]
Comment (trishaanand) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:873]: Since the return of this does not impact the calling function, I am simply returning a value and not using it.

**Review by nidhi-nair — APPROVED** [review]
