### PR TITLE
fix: premium and soon datasource display condition changed

### LINKED ISSUE #38802: [Bug]: Show premium tag datasources to community users instead of community instance
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Right now the premium tag datasources are visible to all users on ce edition and soon tag datasources to all ee edition users. But we want to show premium tag to users that don't have access to ee edition features on both ce or ee edition instances and soon tag datasources to only users who have ee edition features.

Notion doc : https://www.notion.so/appsmith/Condition-for-showing-Premium-Soon-tag-datasources-184fe271b0e2802cb55bd63f468df60d

### Steps To Reproduce

1. Go to datasource homepage
2. Observe premium or soon tag datasources
3. Soon tag datasources should only be visible to users have access to ee features.

### Public Sample App

_No response_

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

_No response_

### Version

Cloud & Self Hosted

### PR DESCRIPTION
**Pull request by AmanAgarwal041**
## Description
Earlier the condition for showing premium and soon datasources were dependent on the tenant instance being enterprise/business or free instance. Now after this PR it depends on the feature flag `license_gac_enabled` to show the premium/soon datasources.

Fixes #38802
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datasource"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13005514213>
> Commit: e2f22a45cd29d924ca4729cb2fad19af9bdd44f2
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13005514213&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Tue, 28 Jan 2025 08:08:38 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new feature flag check `isGACEnabled` to control premium datasource functionality.
	- Updated premium datasource handling logic to use the new feature flag.

- **Refactor**
	- Replaced free plan instance checks with a more specific feature flag mechanism.
	- Removed `isFreePlanInstance` variable and associated logic.
	- Updated component logic to use `isGACEnabled` for rendering and interaction conditions.

### CODE REVIEW

File: app/client/src/pages/Editor/IntegrationEditor/PremiumDatasources/ContactForm.tsx [hunk 1]
```diff
@@ -41,7 +43,7 @@ const PremiumDatasourceContactForm = (
 ) => {
   const instanceId = useSelector(getInstanceId);
   const appsmithConfigs = getAppsmithConfigs();
-  const isFreePlanInstance = useSelector(isFreePlan);
+  const isGACEnabled = useFeatureFlag(FEATURE_FLAG.license_gac_enabled);
```
Comment (sneha122) [inline app/client/src/pages/Editor/IntegrationEditor/PremiumDatasources/ContactForm.tsx:46]: @AmanAgarwal041 Nit: Can we add a comment here as to why we are using this flag instead of isFreePlan?

**Review by sneha122 — DISMISSED** [review]

File: app/client/src/pages/Editor/IntegrationEditor/PremiumDatasources/ContactForm.tsx (hunk 1 above)
Comment (AmanAgarwal041) [reply app/client/src/pages/Editor/IntegrationEditor/PremiumDatasources/ContactForm.tsx:46]: Sure

**Review by sneha122 — APPROVED** [review]
