### PR TITLE
Fixed overlapping dropdown

### LINKED ISSUE #4890: [Bug] SSL Mode dropdown is unusable in MySQL Plugin
## Description

https://user-images.githubusercontent.com/120119/120603629-ddfeb700-c469-11eb-9f4b-5c5c085883cd.mov

- Version: Cloud
- OS: macOS
- Browser: Firefox
- Environment: <https://app.appsmith.com>

### PR DESCRIPTION
**Pull request by arunvjn**
## Description
Fixed overlapping dropdown in mysql datasource form

Fixes #4890 
## Type of change

> Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: bug/overlapping_dropdown_mysql_form 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 51.58 **(0)** | 32.65 **(0)** | 29.74 **(-0.01)** | 52.1 **(0)**
 :red_circle: | app/client/src/components/designSystems/appsmith/Dropdown.tsx | 33.33 **(-4.17)** | 0 **(0)** | 0 **(0)** | 33.33 **(-4.17)**</details>

### CODE REVIEW

File: app/client/src/components/designSystems/appsmith/Dropdown.tsx [hunk 1]
```diff
@@ -50,12 +50,15 @@ const selectStyles = {
     padding: "5px",
   }),
   indicatorSeparator: () => ({}),
+  menu: (provided: any) => ({ ...provided, zIndex: 99 }),
```
Comment (hetunandu) [inline app/client/src/components/designSystems/appsmith/Dropdown.tsx:53]: That is a huge z-index for no reason. Try to keep it as low as possible

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Review by hetunandu — APPROVED** [review]
