### PR TITLE
fix: Theming issue when application has multiple git branches

### LINKED ISSUE #13860: [Bug]: Theming is not getting applied on view mode when the app is connected to Git
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[LOOM DEMO](https://www.loom.com/share/fbc973f635294af4bc2d88d27d30e6e9)

### Steps To Reproduce

1. Connect your app with git
2. Create a new branch
3. Change theme
4. Commit and deploy
5. Observe the default theme selected in master branch is showing.

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by nayan-rafiq**
## Description
Theming API was not considering branches. This PR fixes the issue.

Fixes #13860

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually
- JUnit tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java [hunk 1]
```diff
@@ -407,4 +410,12 @@ public Mono<Application> archiveApplicationThemes(Application application) {
                 .then(repository.archiveDraftThemesById(application.getEditModeThemeId(), application.getPublishedModeThemeId()))
                 .thenReturn(application);
     }
+
+    private Mono<Application> getApplication(String applicationId, String branchName, AclPermission permission) {
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java:414]: We should `applicationService.findByBranchNameAndDefaultApplicationId` this will handle the exact same thing that we are trying to in the following block.

Comment (nayan-rafiq) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java]: Done

**Review by abhvsn — COMMENTED** [review]
LGTM

**Review by abhvsn — APPROVED** [review]
