### PR TITLE
fix:prevent execution of js function when jscollection is saving

### LINKED ISSUE #13512: [Bug]: Function that is still being parsed can be run causing old code to run but incorrectly show current code and toast message
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A parsing issue consistently reproducible by keyboard shortcut usage (**Ctrl+Enter/Cmd+Enter**) making it quicker to run functions. In that intermediate time when a function is parsing we see old code being run when UI shows new code and success message.

### Steps To Reproduce

1. Create a new JS object and type in `return "hi"` in myFun1() of a new function and execute using keyboard shortcut
2. Observe the saving icon, success message and UI displaying new code on the function is run successfully but there's response is seen in the watch window because function hadn't parsed completely when function was run
3. Change the above snippet to `return false` and run the function
4. Observe that function returns `hi` in the watch window and not the current code
5. Re-run the function and observe that correct response is now seen on the console because it's now the updated code

### Public Sample App

_No response_

### Version

Cloud

### LINKED ISSUE #13960: [Bug]: Unreliable returns in JS function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a simple js function that returns a value:

`
myFun1: () => {
			return 1;
	}
`
When I try to run the function, in the first try, there is no return value. In the second try it works. If I try to change "1" to "2", sometimes the run works and sometimes not. 

https://www.loom.com/share/8afe4b057aef457dbf2bb9c720a2cc8c

conversation here: https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1652951480887279

### Steps To Reproduce

explained above

### Public Sample App

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by ohansFavour**
## Description

This PR prevents execution of JS functions with stale values. execution only starts after editors values are saved.

While still saving

Screenshot 2022-05-12 at 09 58 28

After saving
Screenshot 2022-05-12 at 10 10 56

Fixes #13512 
Fixes #13960 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Unit tests
- [x] getJSResponseViewState

- Manual

- [x] Tested by throttling the internet speed and ensuring that recent values are used for execution even when application is still in the saving state when execution is triggered. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/prevent-running-js-function-when-jsobject-is-loading 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 56.66 **(0.02)** | 38.66 **(0.06)** | 35.96 **(0)** | 56.91 **(0.02)**
 :red_circle: | app/client/src/ce/constants/messages.ts | 77.78 **(-0.02)** | 100 **(0)** | 34.26 **(-0.05)** | 81.74 **(0.02)**
 :green_circle: | app/client/src/components/editorComponents/JSResponseView.tsx | 58.44 **(8.44)** | 31.88 **(6)** | 8.33 **(0)** | 60.81 **(8.96)**
 :green_circle: | app/client/src/components/editorComponents/utils.ts | 82.61 **(49.28)** | 91.67 **(91.67)** | 33.33 **(33.33)** | 80 **(60)**
 :red_circle: | app/client/src/sagas/JSPaneSagas.ts | 16.39 **(-0.28)** | 1 **(-0.02)** | 4.55 **(0)** | 19.02 **(-0.29)**
 :green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**</details>

### CODE REVIEW

File: app/client/src/sagas/JSPaneSagas.ts [hunk 1]
```diff
@@ -322,6 +324,14 @@ export function* handleExecuteJSFunctionSaga(data: {
       collectionId,
     }),
   );
+
+  /**
+   * Only start executing when not saving
+   * This ensures that execution doesn't get carried out on stale values
+   * */
+
+  yield call(waitFor, (state: AppState) => !getIsSavingEntity(state));
```
Comment (eco-monk) [inline app/client/src/sagas/JSPaneSagas.ts:333]: I'm inclined to think listening to a specific event is better than, listening to all events and checking the state.

This (right now) is the equivalent of
`yield take(ReduxActionTypes.ENTITY_UPDATE_SUCCESS);`
Since, `ENTITY_UPDATE_SUCCESS` is the only action where savingEntity is set to `false`.

File: app/client/src/components/editorComponents/JSResponseView.tsx [hunk 2]
```diff
@@ -183,7 +186,7 @@ function JSResponseView(props: Props) {
     currentFunction && currentFunction.id && currentFunction.id in responses
       ? responses[currentFunction.id]
       : "";
-
+  const isSaving = useSelector(getIsSavingEntity);
```
Comment (eco-monk) [inline app/client/src/components/editorComponents/JSResponseView.tsx:189]: Something to watch out for. Noticed `savingEntity` prop is not entity specific.
Perhaps can be made entity specific later on.

**Review by eco-monk — COMMENTED** [review]
Any unit or cypress tests around this?

File: app/client/src/components/editorComponents/JSResponseView.tsx (hunk 2 above)
Comment (ohansFavour) [reply app/client/src/components/editorComponents/JSResponseView.tsx:189]: That is precisely the point here, we don't want to execute when an entity in the application is still saving, the reason being that there is a possibility that the entity being saved is used in the JS Object's function to be executed.

**Comment by ohansFavour** [comment]
> Any unit or cypress tests around this?

@eco-monk this is an edge case that can only be tested on throttled internet speed, it's currently tested manually.

File: app/client/src/components/editorComponents/JSResponseView.tsx (hunk 2 above)
Comment (eco-monk) [reply app/client/src/components/editorComponents/JSResponseView.tsx:190]: You're right, that makes sense.!

**Review by eco-monk — APPROVED** [review]

**Comment by ramsaptami** [comment]
Test p : https://github.com/appsmithorg/TestSmith/issues/1711

**Review by eco-monk — APPROVED** [review]
Merge conflicts resolved.
