### PR TITLE
fix: Options in WDS radio group widget get distorted in a Section with > 1 Zone

### LINKED ISSUE #29365: [Bug]: Options in WDS radio group widget get distorted in a Section with > 1 Zone
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The options of a Radio group widget get distorted when `Orientation` is set to `Horizontal`.
Screenshot_2023-11-28_at_4 38 47_PM

### Steps To Reproduce

1. Go to the latest Anvil instance.
2. DnD a Radio group widget.
3. Add some more options & set the `Orientation` to `Horizontal`.

**Expected:** The options should be displayed appropriately.
**Actual:** The options get distorted.

### Public Sample App

_No response_

### Environment

Deploy Preview

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #29365 

## Summary by CodeRabbit

- **New Features**
    - Enhanced label positioning for Checkbox, Radio, and Switch components with "start" and "end" options.
    - Introduced dynamic orientation for Checkbox and Radio groups based on container size.
    - Added new story for RadioGroup component to demonstrate vertical orientation.
- **Style Updates**
    - Updated CSS for Switch, Checkbox, and Radio components to align with the new label positioning options.
    - Improved field group styles with `flex-wrap` to accommodate various layouts.
- **Refactor**
    - Modified handling of `labelPosition` across components for consistency and flexibility.
    - Implemented `useGroupOrientation` hook for dynamic orientation management.
- **Chores**
    - Adjusted default configurations and property pane options for widgets to align with new label positioning and orientation features.
    - Added feature flag checks for specific functionalities to always return `true`.

### CODE REVIEW

File: app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ import { Icon as HeadlessIcon } from "../../Icon";
 import type { CheckboxGroupContextType } from "./context";
 
 export interface InlineLabelProps {
-  labelPosition?: "left" | "right";
+  labelPosition?: "start" | "end";
```
Comment (jsartisan) [inline app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx:19]: As discussed, changing values to same as logical properties.

File: app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx [hunk 2]
```diff
@@ -36,7 +36,7 @@ const _Checkbox = (props: CheckboxProps, ref: CheckboxRef) => {
     icon: Icon = CheckIcon,
     isDisabled: isDisabledProp = false,
     isIndeterminate = false,
-    labelPosition = "right",
+    labelPosition: labelPositionProp,
```
Comment (jsartisan) [inline app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx:39]: Removing default value here. This is required cause we want to have logic like if there is labelPosition on the checkbox, use that otherwise use the one we defined the checkbox group ( we now define optionsLabelPosition on checkbox group level too, same as isDisabled property.)

So had to remove default as it would mean `if there is labelPosition on the checkbox` is always true.

File: app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx [hunk 3]
```diff
@@ -50,6 +50,7 @@ const _Checkbox = (props: CheckboxProps, ref: CheckboxRef) => {
   // it should be safe in this case since the checkbox is not expected to be added or removed from the group.
   const context = useContext(CheckboxGroupContext) as CheckboxGroupContextType;
   const isDisabled = isDisabledProp || context?.isDisabled;
+  const labelPosition = labelPositionProp ?? context?.optionsLabelPosition;
```
Comment (jsartisan) [inline app/client/packages/design-system/headless/src/components/Checkbox/src/Checkbox.tsx:53]: This is saying if there  is checkbox's labelPosition, use it otherwise use the one we get from checkbox group.

File: app/client/packages/design-system/headless/src/components/Checkbox/src/CheckboxGroup.tsx [hunk 4]
```diff
@@ -15,12 +16,20 @@ const _CheckboxGroup = (props: CheckboxGroupProps, ref: CheckboxGroupRef) => {
...
   } = props;
   const domRef = useDOMRef(ref);
   const state = useCheckboxGroupState(props);
   const { descriptionProps, errorMessageProps, groupProps, labelProps } =
     useCheckboxGroup(props, state);
+  const containerRef = useRef<HTMLDivElement>(null);
+  const { orientation } = useGroupOrientation(
+    {
+      orientation: props.orientation,
+      optionsLabelPosition: optionsLabelPosition,
```
Comment (jsartisan) [inline app/client/packages/design-system/headless/src/components/Checkbox/src/CheckboxGroup.tsx:29]: We want to trigger calculation of "auto-orientation" when we change `optionsLabelPosition`. So passing it to the hook.

File: app/client/packages/design-system/headless/src/hooks/useGroupOrientation.ts [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+        orientation: "horizontal",
+      };
+
+      const orientation = computeOrientation();
+
+      yield {
+        orientation: orientation,
+      };
+    });
+  }, [ref, setOrientation, props.orientation, props.optionsLabelPosition]);
```
Comment (jsartisan) [inline app/client/packages/design-system/headless/src/hooks/useGroupOrientation.ts:65]: Note we pass optionsLabelPosition in the dependencies because we want the calculate to re-trigger whenever it changes.

File: app/client/packages/design-system/headless/src/hooks/useGroupOrientation.ts [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+            return "vertical";
+          }
+        }
+      }
+
+      return "horizontal";
+    };
+
+    setOrientation(function* () {
+      yield {
```
Comment (KelvinOm) [inline app/client/packages/design-system/headless/src/hooks/useGroupOrientation.ts:55]: Why are we using `yield` here?

**Review by KelvinOm — COMMENTED** [review]
Could you please fix this behavior as well. Let there always be only 1 line
Снимок экрана 2024-03-15 в 16 58 14

File: app/client/packages/design-system/headless/src/hooks/useGroupOrientation.ts (hunk 6 above)
Comment (jsartisan) [reply app/client/packages/design-system/headless/src/hooks/useGroupOrientation.ts:55]: it is required by`useValueEffect` hook. It is same hook we used in action group. More info here - https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/useValueEffect.ts

**Review by KelvinOm — APPROVED** [review]
