### PR TITLE
Fix: TypeError: e is undefined

### LINKED ISSUE #3287: [Bug] TypeError: e is undefined
Sentry Issue: [APPSMITH-KG](https://sentry.io/organizations/appsmith/issues/2242302574/?referrer=github_integration)

```
TypeError: e is undefined
  at isPropertyATriggerPath (sagas/WidgetOperationSagas.tsx:747:24)
  at forEach (sagas/WidgetOperationSagas.tsx:850:31)
  at call (sagas/WidgetOperationSagas.tsx:842:28)
  at batchUpdateWidgetProperty (components/editorComponents/EditorContextProvider.tsx:124:7)
  at batchUpdateWidgetProperty (widgets/BaseWidget.tsx:118:7)
...
(29 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jsartisan**
Fixes #3287 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/client/src/sagas/WidgetOperationSagas.tsx [hunk 1]
```diff
@@ -743,7 +743,7 @@ const isPropertyATriggerPath = (
   widget: WidgetProps,
   propertyPath: string,
 ): boolean => {
-  const widgetConfig = WidgetFactory.getWidgetPropertyPaneConfig(widget.type);
+  const widgetConfig = WidgetFactory.getWidgetPropertyPaneConfig(widget?.type);
```
Comment (hetunandu) [inline app/client/src/sagas/WidgetOperationSagas.tsx:746]: This will cause an issue down the line. We should check for a widget before calling this function and send an appropriate return value

**Review by hetunandu — CHANGES_REQUESTED** [review]

**Review by riodeuno — APPROVED** [review]
