### PR TITLE
test: fix hung tests in CI

### LINKED ISSUE #34026: bug: fix failing server tests related to templates caching.
Second reported [Slack Conversation](https://theappsmith.slack.com/archives/C02GAUE9P5H/p1717664846647609?thread_ts=1717654359.337849&cid=C02GAUE9P5H)

### PR DESCRIPTION
**Pull request by AnaghHegde**
## Description
Fix hung tests on the CI

Fixes #34026 

## Automation

/ok-to-test tags="@tag.Templates"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9399386015>
> Commit: c3c9ab9db85850d7323658b364e65a095d769e9c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9399386015&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **Refactor**
  - Improved test setup and scenarios in caching-related tests.
  - Replaced `cloudServicesConfig` with `baseUrl` for better clarity and maintainability in test methods.

### CODE REVIEW

File: app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/CacheableTemplateHelperTemplateMetadataTest.java [hunk 1]
```diff
@@ -99,7 +91,7 @@ public void getTemplateData_cacheIsEmpty_VerifyDataSavedInCache() throws JsonPro
                 .addHeader("Content-Type", "application/json"));
 
         Mono<CacheableApplicationTemplate> templateListMono =
-                cacheableTemplateHelper.getTemplates("recently-used", cloudServicesConfig.getBaseUrl());
+                cacheableTemplateHelper.getTemplates("recently-used", baseUrl);
```
Comment (nidhi-nair) [inline app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/CacheableTemplateHelperTemplateMetadataTest.java:94]: QQ, why is the cloud services url being passed as a param to this method?

Comment (AnaghHegde) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/CacheableTemplateHelperTemplateMetadataTest.java:94]: This is a helper class and the cloud service url is passed from the TemplateService.

Comment (nidhi-nair) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/CacheableTemplateHelperTemplateMetadataTest.java:94]: Yes, but why is that the case, why can the helper not use the URL directly? I see that the helper is already a component so injection should not be a problem? 🤔

Comment (AnaghHegde) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/CacheableTemplateHelperTemplateMetadataTest.java:94]: I agree with you that there is no good reason for this. Can i take this up in a different PR please?

Comment (nidhi-nair) [reply app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/CacheableTemplateHelperTemplateMetadataTest.java:94]: That's going to need a change in the test, but sure :)

**Review by nidhi-nair — APPROVED** [review]
