### PR TITLE
fix: Table Widget shows scrollbar when not in focus

### LINKED ISSUE #3744: [Bug]-[8000]:Table widget should not show scroll bars when it's not focused or being hovered on
Today the table widget shows scroll bars even when we don't hover over it. Hovering or interacting with the table widget should reveal the scroll bars. 

Screen Shot 2021-03-29 at 6 17 35 PM

### PR DESCRIPTION
**Pull request by souma-ghosh**
## Description

1. Fixes issue where Table widget was showing scrollbar even when not in focus.
2. Verified on a windows system that this was a problem only for horizontal scroll bar for table body
3. `autoHide` property was missing for table body horizontal scroll bar; added in the fix

Fixes #3744 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Manually tested

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by dilippitchika** [comment]
@sbalaji1192 @souma-ghosh can we also make the change in v1?

**Comment by sbalaji1192** [comment]
@dilippitchika Yes. The change required is really small. 
@souma-ghosh Could you fix it in V1 as well?

**Comment by souma-ghosh** [comment]
Pushed the fix @sbalaji1192 @dilippitchika

**Review by sbalaji1192 — DISMISSED** [review]

**Comment by laveena-en** [comment]
Tested and verified (on Windows and Mac)

**Comment by dilippitchika** [comment]
@sbalaji1192 @souma-ghosh this is hard to grok if the table is scrollable when my cursor is on the table. Is there some way where we show the scroll bars when user is hovering on the table?

**Comment by sbalaji1192** [comment]
@dilippitchika Yeah. we can selectively hide the scrollbar when the cursor is not on the table.
@souma-ghosh We need to ditch react custom scrolls config and achieve the functionality with CSS.

**Comment by souma-ghosh** [comment]
@sbalaji1192 Got it. Will rework this

**Comment by sbalaji1192** [comment]
Thanks @souma-ghosh

**Review by albinAppsmith — APPROVED** [review]

File: app/client/src/components/ads/ScrollIndicator.tsx [hunk 1]
```diff
@@ -49,13 +49,15 @@ interface Props {
   bottom?: string;
   right?: string;
   alwaysShowScrollbar?: boolean;
+  showScrollbarOnHover?: boolean;
```
Comment (sbalaji1192) [inline app/client/src/components/ads/ScrollIndicator.tsx:52]: `showScrollbarOnlyOnHover`

File: app/client/src/components/ads/ScrollIndicator.tsx [hunk 2]
```diff
@@ -106,6 +108,11 @@ function ScrollIndicator({
   }, []);
 
   useEffect(() => {
+    // showScrollbarOnHover prop if true will bypass hideScrollbar functionality
+    // as hideScrollbar behaviour conflicts with "hover to show scrollbar" functionality
+    if (showScrollbarOnHover) {
```
Comment (sbalaji1192) [inline app/client/src/components/ads/ScrollIndicator.tsx:113]: add `showScrollbarOnHover` to dependency

File: app/client/src/components/ads/ScrollIndicator.tsx [hunk 3]
```diff
@@ -114,6 +121,30 @@ function ScrollIndicator({
   const hideScrollbar = _.debounce(() => {
     setIsScrollVisible(alwaysShowScrollbar || false);
   }, 1500);
+
+  useEffect(() => {
+    // This useEffect adds events to show/hide scrollbar when showScrollBarOnHover prop is true
+    if (showScrollbarOnHover) {
```
Comment (sbalaji1192) [inline app/client/src/components/ads/ScrollIndicator.tsx:127]: create a handler functions seperately using useCallback

File: app/client/src/components/ads/ScrollIndicator.tsx [hunk 4]
```diff
@@ -114,6 +121,30 @@ function ScrollIndicator({
...
+      if (containerRef.current?.getAttribute("hoverListeners")) {
+        containerRef.current?.removeEventListener("mouseenter", () =>
+          setIsScrollVisible(true),
+        );
+        containerRef.current?.removeEventListener("mouseleave", () =>
+          setIsScrollVisible(false),
+        );
+      }
+    };
+  }, []);
```
Comment (sbalaji1192) [inline app/client/src/components/ads/ScrollIndicator.tsx:146]: containerRef, showScrollbarOnHover to dependency

File: app/client/src/widgets/TableWidget/component/Table.tsx [hunk 5]
```diff
@@ -288,6 +288,7 @@ export function Table(props: TableProps) {
         ref={tableWrapperRef}
       >
         <Scrollbars
+          autoHide
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidget/component/Table.tsx:291]: remove it

File: app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx [hunk 6]
```diff
@@ -52,13 +52,31 @@ export const TableWrapper = styled.div<{
     width: ${(props) => props.width}px;
     overflow-x: auto;
     ${hideScrollbar};
+    .track-horizontal {
+      height: 6px;
+      bottom: 1px;
+      width: 100%;
+      opacity: 0;
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx:59]: display none/block

File: app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx [hunk 7]
```diff
@@ -52,13 +52,31 @@ export const TableWrapper = styled.div<{
...
+      }
+    }
     .thumb-horizontal {
       height: 4px !important;
       border-radius: ${(props) => props.theme.radii[3]}px;
       background: ${(props) => props.theme.colors.scrollbarLight} !important;
       &:hover {
         height: 6px !important;
       }
+      &:active {
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx:77]: remove

File: app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx [hunk 8]
```diff
@@ -489,13 +507,31 @@ export const TableHeaderWrapper = styled.div<{
   min-height: ${(props) => props.tableSizes.TABLE_HEADER_HEIGHT}px;
   overflow-x: auto;
   ${hideScrollbar};
+  .track-horizontal {
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx:510]: extract this into separate string.

**Comment by dilippitchika** [comment]
Do we have a latest dp for this @souma-ghosh ?

**Comment by souma-ghosh** [comment]
> Do we have a latest dp for this @souma-ghosh ?

Should be in this thread. Cannot find it. Retriggering the tests.

File: app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx (hunk 7 above)
Comment (souma-ghosh) [reply app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx:77]: When we hover on the scroll bar its width changes from 4 to 6px. So for active state also the width needs to stay at 6px. Hence this is required

File: app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx (hunk 6 above)
Comment (souma-ghosh) [reply app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx:59]: Display none to hide scrollbar is causing a bug here. When page is rendered for the first time and we hover over the table the scroll bars don't appear. They only appear after the first time we try to scroll. Once they appear the subsequent "show scrollbar on hover" behaviour is fine. In ScrollIndicator component as well we are using opacity to hide the scrollbar. So sticking to opacity here.

**Comment by souma-ghosh** [comment]
@dilippitchika Latest DP is up
https://appsmith-elv0e643f-get-appsmith.vercel.app/applications

**Comment by dilippitchika** [comment]
Verified this, good to go from my end

File: app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx (hunk 6 above)
Comment (sbalaji1192) [reply app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx]: Lets go with opacity since we're already using opacity in scrollIndicator as you mentioned

File: app/client/cypress/support/index.js [hunk 9]
```diff
@@ -97,10 +97,10 @@ before(function() {
 });
 
 beforeEach(function() {
-  //cy.window().then((win) => (win.onbeforeunload = undefined));
-  if (!navigator.userAgent.includes("Cypress")) {
-    window.addEventListener("beforeunload", this.beforeunloadFunction);
-  }
+  cy.window().then((win) => (win.onbeforeunload = undefined));
+  // if (!navigator.userAgent.includes("Cypress")) {
```
Comment (sbalaji1192) [inline app/client/cypress/support/index.js:101]: Do we need this ?

File: app/client/src/components/ads/ScrollIndicator.tsx [hunk 10]
```diff
@@ -106,6 +108,13 @@ function ScrollIndicator({
...
 
   useEffect(() => {
+    /*
+      showScrollbarOnlyOnHover prop if true will bypass hideScrollbar functionality
+      as hideScrollbar behaviour conflicts with showScrollbarOnlyOnHover functionality
+    */
+    if (showScrollbarOnlyOnHover) {
+      return;
+    }
     if (isScrollVisible) {
```
Comment (sbalaji1192) [inline app/client/src/components/ads/ScrollIndicator.tsx:118]: change the condition to `isScrollVisible && !showScrollbarOnlyOnHover` and remove the first if

File: app/client/src/components/ads/ScrollIndicator.tsx [hunk 11]
```diff
@@ -114,6 +123,39 @@ function ScrollIndicator({
...
+        setScrollVisibilityOnHover,
+      );
+      containerRef.current?.addEventListener(
+        "mouseleave",
+        setScrollVisibilityOnHover,
+      );
+    }
+    return () => {
+      if (showScrollbarOnlyOnHover) {
+        containerRef.current?.removeEventListener("mouseenter", () =>
```
Comment (sbalaji1192) [inline app/client/src/components/ads/ScrollIndicator.tsx:149]: you need to pass the same handler reference you passed to `addEventListener` function

File: app/client/src/widgets/TableWidgetV2/component/Constants.ts [hunk 12]
```diff
@@ -372,3 +372,21 @@ export enum CheckboxState {
   CHECKED = 1,
   PARTIAL = 2,
 }
+
+export const showScrollbarOnHover = `
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/component/Constants.ts:376]: use an appropriate name. something like scrollbarOnHoverCSS

File: app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx [hunk 13]
```diff
@@ -52,13 +53,17 @@ export const TableWrapper = styled.div<{
...
     ${hideScrollbar};
+    ${showScrollbarOnHover};
     .thumb-horizontal {
       height: 4px !important;
       border-radius: ${(props) => props.theme.radii[3]}px;
       background: ${(props) => props.theme.colors.scrollbarLight} !important;
       &:hover {
         height: 6px !important;
       }
+      &:active {
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx:64]: club this selector with `&:hover` to above

File: app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx [hunk 14]
```diff
@@ -489,13 +494,17 @@ export const TableHeaderWrapper = styled.div<{
...
   ${hideScrollbar};
+  ${showScrollbarOnHover};
   .thumb-horizontal {
     height: 4px !important;
     border-radius: ${(props) => props.theme.radii[3]}px;
     background: ${(props) => props.theme.colors.scrollbarLight};
     &:hover {
       height: 6px !important;
     }
+    &:active {
```
Comment (sbalaji1192) [inline app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx:505]: here too

File: app/client/cypress/support/index.js (hunk 9 above)
Comment (Aishwarya-U-R) [reply app/client/cypress/support/index.js]: Reverted!

**Comment by tanvibhakta** [comment]
Hey folks - just before you merge this in, can you also make sure the functional changes from here are reflected on the design system component [here](https://github.com/appsmithorg/design-system/tree/release/packages/design-system/src/ScrollIndicator)? Sorry about having to duplicate the effort.

**Review by sbalaji1192 — DISMISSED** [review]

File: app/client/src/components/ads/ScrollIndicator.tsx [hunk 15]
```diff
@@ -49,13 +49,15 @@ interface Props {
   bottom?: string;
   right?: string;
   alwaysShowScrollbar?: boolean;
+  showScrollbarOnlyOnHover?: boolean;
```
Comment (tanvibhakta) [inline app/client/src/components/ads/ScrollIndicator.tsx:52]: Hey folks, can you please raise a PR making these updates in the design system repo as well? 
Sorry about the duplication. 
https://github.com/appsmithorg/design-system/blob/release/packages/design-system/src/ScrollIndicator/index.tsx

**Review by tanvibhakta — CHANGES_REQUESTED** [review]

File: app/client/src/components/ads/ScrollIndicator.tsx (hunk 15 above)
Comment (souma-ghosh) [reply app/client/src/components/ads/ScrollIndicator.tsx:52]: Sure will do @tanvibhakta .

**Comment by laveena-en** [comment]
@souma-ghosh I noticed that the scrollbars don’t seem to be seen on hover consistently. Can you please have a look?

1. On hovering over the table for the first time, the bottom scrollbar is seen. But the one on the right is seen very faintly.
2. However on scrolling down, the scrollbar on the right is seen.
3. From the second time onwards, on hovering over the table, both the scrollbars are seen. https://www.loom.com/share/bd7eff3332024a5ca533e96b33754304

File: app/client/src/components/ads/ScrollIndicator.tsx [hunk 16]
```diff
@@ -124,6 +128,15 @@ function ScrollIndicator({
   const setScrollVisibilityOnHover = useCallback((e) => {
     if (e?.type === "mouseenter") {
       setIsScrollVisible(true);
+      /*
+        Scroll Thumb by default has height 0.
+        Since we have to rely on hover event instead of scroll event when showScrollbarOnlyOnHover is true,
+        we have to set scroll thumb height and position one first hover(mouseenter)
+        or the scroll thumb won't be visible until scroll the first scroll event happens
```
Comment (tanvibhakta) [inline app/client/src/components/ads/ScrollIndicator.tsx:135]:
```suggestion
        or the scroll thumb won't be visible until the first scroll event happens
```

**Review by tanvibhakta — DISMISSED** [review]

**Comment by laveena-en** [comment]
Tested and verified.

**Review by sbalaji1192 — APPROVED** [review]

**Comment by souma-ghosh** [comment]
@sbalaji1192 The ScrollIndicator file has been remove from this repo and is being used directly from the design-systems repo. Sent the latest ScrollIndicator code to @albinAppsmith . He is working on pushing the changes to design-systems.

**Review by sbalaji1192 — APPROVED** [review]
