### PR TITLE
fix: submit button not disabled in invalid json form on first load

### LINKED ISSUE #13139: [Bug]-[308]:JSON form submit button is not disabled when default data doesn't meet the validation criteria
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If a json form has default data as empty and a field is marked as required, the submit button is still enabled when "disable invalid forms" is true. Only after the user interacts with the field, the submit button is disabled.

### Steps To Reproduce

1. Add a new JSON form
2. Bind this data
{
  "name": "",
  "date_of_birth": "20/02/1990",
  "employee_id": 1001
}
3. Make sure name is set to required
4. Deploy the app
5. Observe the submit button is enabled

### Public Sample App

_No response_

### Version

1.6.20

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description

If a JSONForm is invalid when loaded for the first time (either in edit mode or view mode), the `isValid` property is `true` and the submit button is enabled.

Fixes #13139

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Cypress

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:red_circle: Total coverage has decreased</summary>

    // Code coverage diff between base branch:release and head branch: fix/13139-fix-jsonform-button-invalid 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :red_circle: | total | 56.41 **(0)** | 37.84 **(-0.01)** | 36.01 **(-0.01)** | 56.62 **(-0.01)**
 :green_circle: | app/client/src/widgets/JSONFormWidget/component/Form.tsx | 29.17 **(0.75)** | 20 **(0)** | 0 **(0)** | 30.43 **(0.76)**
 :red_circle: | app/client/src/widgets/JSONFormWidget/fields/useRegisterFieldValidity.ts | 86.96 **(-8.49)** | 0 **(-100)** | 75 **(-25)** | 85.71 **(-9.29)**
 :red_circle: | app/client/src/widgets/JSONFormWidget/widget/index.tsx | 29.25 **(-0.27)** | 0 **(0)** | 20.69 **(0)** | 29.7 **(-0.3)**</details>

### CODE REVIEW

File: app/client/src/widgets/JSONFormWidget/widget/index.tsx [hunk 1]
```diff
@@ -207,16 +206,19 @@ class JSONFormWidget extends BaseWidget<
...
-        fieldState,
-        afterUpdateAction,
-      );
+      /**
+       * Using syncUpdateWidgetMetaProperty to avoid race-condition when
+       * multiple properties are updating in quick succession. As sync fn
+       * does not support action execution as a callback, it has to be
+       * explicitly called.
+       */
+      this.props.syncUpdateWidgetMetaProperty("fieldState", fieldState);
```
Comment (sbalaji1192) [inline app/client/src/widgets/JSONFormWidget/widget/index.tsx:220]: @Rishabh-Rathod you have removed the syncUpdateWidgetMetaProperty from metaHOC is this [PR](https://github.com/appsmithorg/appsmith/pull/13269/files). You might wanna reinstate it.

**Review by sbalaji1192 — COMMENTED** [review]
LGTM

**Review by sbalaji1192 — APPROVED** [review]

**Comment by ashit-rath** [comment]
@chandannkumar It shouldn't be set to true. Nice catch!
I'll look into it

File: app/client/src/widgets/JSONFormWidget/widget/index.tsx (hunk 1 above)
Comment (Rishabh-Rathod) [reply app/client/src/widgets/JSONFormWidget/widget/index.tsx:220]: We will need to change this to `updateWidgetMetaProperty` as after my changes as `updateWidgetMetaProperty` works same as current `syncUpdateWidgetMetaProperty`. 

Let me know if I am missing something here. @sbalaji1192 

Also, as I have added types to each widget method, I will rely on types for such usage detection.

Comment (ashit-rath) [reply app/client/src/widgets/JSONFormWidget/widget/index.tsx:220]: @Rishabh-Rathod Do we have an open PR for this? or is this already on release?
The one Balaji mentioned seems to be closed

**Comment by chandannkumar** [comment]
Tested this PR and it is working as expected
- submit button not disabled in invalid JSON Form on first load - **Fixed**
- validation of JSON form sets 'true' when RESET button is pressed - **Fixed**

File: app/client/src/widgets/JSONFormWidget/widget/index.tsx (hunk 1 above)
Comment (Rishabh-Rathod) [reply app/client/src/widgets/JSONFormWidget/widget/index.tsx:220]: This is the PR - https://github.com/appsmithorg/appsmith/pull/13084 
I have added types in this PR with more changes that are causing test failures for now - https://github.com/appsmithorg/appsmith/pull/13426

Comment (ashit-rath) [reply app/client/src/widgets/JSONFormWidget/widget/index.tsx:220]: Got it!
Any timelines on this PR? If it's gonna take more time then we can merge this PR and you can update this in your PR to use the `updateWidgetMetaProperty` and remove the `executeAction`?

Comment (Rishabh-Rathod) [reply app/client/src/widgets/JSONFormWidget/widget/index.tsx:220]: You can go ahead with merging your PR. @ashit-rath and let me know once your PR is merged to release. I will merge it and do replace `syncUpdateWidgetMetaProperty` with  `updateWidgetMetaProperty`

What do mean by removing `executeAction`?

Comment (ashit-rath) [reply app/client/src/widgets/JSONFormWidget/widget/index.tsx:220]: > What do mean by removing executeAction?

Since `syncUpdateWidgetMetaProperty` does not take a third argument like `updateWidgetMetaProperty` to execute triggers as a callback. I had to explicitly call the `executeAction` here. So just modify as per your changes.

https://github.com/appsmithorg/appsmith/pull/13415/files#diff-30b408a5a213174dcf593de534ed5097e5c38076bcd1a299ea44df9661ddbbb6R221

Most likely the change would look like 
```jsx
this.props.updateWidgetMetaProperty("fieldState", fieldState, afterUpdateAction)
```

**Review by sbalaji1192 — APPROVED** [review]
