### PR TITLE
fix: Fix duplicate action collection getting updated instead of creating a new collection

### LINKED ISSUE #9372: [Bug]: JS Objects Don't Get Copied Over When An App Is Duplicated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JS objects are not copied over when an application is duplicated. But this issue does not exist when an app is forked or exported

### Steps To Reproduce

1. Create an app
2. Create a JS object file
3. Duplicate the app
4. In the duplicated app, the JS object file does not exist

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by abhvsn**
## Description

> When a user is trying to duplicate an application, the action collection was getting updated instead of creating a separate resource for the cloned application. This was resulting in a state where both original and duplicated application unable to access the collection. 

Fixes #9372 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

> Junit TC
> Manual Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java [hunk 1]
```diff
@@ -554,24 +553,58 @@ public void generateAndSetPagePolicies(Application application, PageDTO page) {
...
+
+                                            } else {
+                                                unpublishedCollection
+                                                        .getDefaultToBranchedActionIdsMap()
+                                                        .forEach((defaultId, oldActionId) ->
+                                                                updatedDefaultToBranchedActionId.put(defaultId, actionIdsMap.get(oldActionId)));
+                                            }
+                                            unpublishedCollection.setDefaultToBranchedActionIdsMap(updatedDefaultToBranchedActionId);
+
+                                            actionCollection.setId(null);
```
Comment (abhvsn) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java:588]: This is what is required to resolve this issue.

**Review by trishaanand — APPROVED** [review]
