### PR TITLE
fix: PostgreSQL Trust Authentication Login

### LINKED ISSUE #14003: [Bug]: Postgres plugin: allow connection without password
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently Postgres plugin does not allow connection without password. We need to check if the Postgres DB allows a user to connect without password and if so, then Postgres plugin should allow such a connection as well. 

### Steps To Reproduce

1. Create new postgres datasource. 
2. Click on `Test` button after entering all details except password.

### Public Sample App

_No response_

### Version

cloud, self hosted

### PR DESCRIPTION
**Pull request by PiyushPushkar02**
### **Description**

- The PR removes the empty password validation check for PostgreSQL while creating a new data source.
- The JUnit test case is added for the same. Implemented using a separate PostgreSQL container with Trust Authentication enabled for the Same.
- Please note for testing from UI perspective we have to create a user with Trust auth enabled to validate the above changes.

Fixes  #14003

### **Type of Change**

- Bug Fix(non-breaking change which adds functionality)

### **How Has This Been Tested?**
- Manual
- JUnit TC added 

### **Checklist**:

- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [ ]  I have commented my code, particularly in hard-to-understand areas
- [ ]  I have made corresponding changes to the documentation
- [ ]  My changes generate no new warnings
- [x]  I have added tests that prove my fix is effective or that my feature works
- [x]  New and existing unit tests pass locally with my changes
- [ ]  PR is being merged under a feature flag

### **QA activity:**

- [ ]  Test plan has been approved by relevant developers
- [ ]  Test plan has been peer reviewed by QA
- [ ]  Cypress test cases have been added and approved by either SDET or manual QA
- [ ]  Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ]  Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

File: app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java [hunk 1]
```diff
@@ -567,9 +567,13 @@ public Set<String> validateDatasource(DatasourceConfiguration datasourceConfigur
...
                 }
 
-                if (StringUtils.isEmpty(authentication.getPassword())) {
-                    invalids.add("Missing password for authentication.");
-                }
+                /*
+                    Commenting the below check to allow the user to connect to
+                    postgresql without password
+                 */
+//                if (StringUtils.isEmpty(authentication.getPassword())) {
```
Comment (sumitsum) [inline app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java:574]: Can you please remove this commented out section ?

File: app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java [hunk 2]
```diff
@@ -84,9 +84,17 @@ public String getRemoteExecutionUrl() {
             .withUsername("postgres")
             .withPassword("password");
 
+    @Container
+    public static final PostgreSQLContainer pgsqlContainerNoPwdAuth = new PostgreSQLContainer<>("postgres:alpine")
+            .withExposedPorts(5432)
+            .withUsername("postgres_no_pwd_auth").withEnv("POSTGRES_HOST_AUTH_METHOD","trust");
```
Comment (sumitsum) [inline app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java:90]: Can we split it up into multiple lines ?

File: app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java [hunk 3]
```diff
@@ -84,9 +84,17 @@ public String getRemoteExecutionUrl() {
...
+
     private static String address;
     private static Integer port;
     private static String username, password;
+    private static String address_no_pwd_auth;
```
Comment (sumitsum) [inline app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java:95]: Can you please change the variable names to follow camel case - since this is the convention that we follow everywhere ?

**Review by sumitsum — CHANGES_REQUESTED** [review]

**Comment by sumitsum** [comment]
@PiyushPushkar02  Can you please follow the `Description` and title format used [here](https://github.com/appsmithorg/appsmith/pull/18904) for this PR as well ? However, instead of `feat` we would have to use `fix` here. 
Also, when raising PR, the branch name should be either `fix/something....` or `feature/something...` or `task/something....` or `chore/something....` - please take care of this in future.

**Review by sumitsum — DISMISSED** [review]

**Review by sumitsum — APPROVED** [review]
