### PR TITLE
fix: Prevent Errors in Debugger When Deleting List Widget

### LINKED ISSUE #35628: [Bug]: Debugger shows multiple errors when dropping or deleting the list widget
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We encounter multiple errors in the debugger section when dropping or deleting the list widget. These errors disappear after a hard refresh.

### Steps To Reproduce

1. D&d a List widget.
2. Now delete the widget.

**Expected:** No error should pop up in the debugger on dropping or deleting the widget.
**Actual:** We see errors both while dropping as well as deleting the widget.

### Public Sample App

_No response_

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/6cf50f71-aeea-472b-a8d7-2e4aceef06be

### Version

Cloud

### PR DESCRIPTION
**Pull request by jacquesikot**
## Description
**Problem**
When deleting a List widget in the EE environment, the widget is successfully removed, but errors are displayed in the in-app debugger. These errors disappear upon refreshing the page, leaving users confused as to why the errors appeared in the first place, despite the widget being deleted correctly.

**Root Cause**
- The issue arises from the sequence in which widgets and their associated meta widgets are deleted.

- When deleting a widget with meta widgets (e.g., a List widget):

  - The main widget is removed first via the deleteWidget saga.

  - Meta widgets are then deleted later during the componentWillUnmount lifecycle method.

- The lint evaluation runs between these two processes, detecting meta widgets still present in the state without a parent widget.

- This mismatch triggers errors in the in-app debugger, which disappear once the page is refreshed, as the meta widgets have already been deleted by then.

**Solution**
- We have modified the deletion process to ensure that both the main widget and its associated meta widgets are removed within the same action.

- Instead of handling meta widget deletion in the general deleteSaga:

  - We now check for widgets with the hasMetaWidgets flag within the deleteWidget saga.

  - If such widgets are found, their meta widgets are deleted before the main widget is removed from the layout.

- This adjustment ensures that the lint evaluation occurs after both the main widget and its meta widgets have been removed, preventing errors in the debugger.

Fixes #35628

## Automation

/ok-to-test tags="@tag.Widget, @tag.List, @tag.IDE, @tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10629216245>
> Commit: 56a4c85076d574cc2ebfef12d3b9f998ee1a4ece
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10629216245&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Widget, @tag.List, @tag.IDE, @tag.Sanity`
> Spec:
> <hr>Fri, 30 Aug 2024 09:25:02 UTC

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Enhanced testing for the list widget to include verification of the drag, drop, and delete functionalities.
  - Improved widget deletion process by ensuring related meta widgets are also addressed during deletion.
  - Updated test descriptions for better clarity and scope, specifically focusing on deletion functionality.
  - Introduced a factory for creating instances of version 2 list widgets, streamlining widget generation.

- **Bug Fixes**
  - Expanded test coverage for potential issues in widget behavior, particularly concerning deletion.

### CODE REVIEW

**Comment by sagar-qa007** [comment]
@jacquesikot there is test case failure. Please check.

File: app/client/src/sagas/WidgetDeletionSagas.ts [hunk 1]
```diff
@@ -253,6 +253,15 @@ function* deleteSaga(deleteAction: ReduxAction<WidgetDelete>) {
         parentId,
       );
 
+      if (widget.hasMetaWidgets) {
```
Comment (znamenskii-ilia) [inline app/client/src/sagas/WidgetDeletionSagas.ts:256]: May I ask to add comment why meta widgets should be removed here (the same you wrote in PR desc)?

**Review by rishabhrathod01 — APPROVED** [review]
LGTM

File: app/client/src/sagas/WidgetDeletionSagas.ts [hunk 2]
```diff
@@ -253,6 +253,24 @@ function* deleteSaga(deleteAction: ReduxAction<WidgetDelete>) {
...
+      /**
+       * This change ensures that meta widgets are deleted before the main widget.
+       * By handling meta widget deletion within the deleteWidget saga, we prevent
+       * lint evaluation from detecting orphaned meta widgets, which previously
+       * caused errors in the in-app debugger. This resolves the issue of transient
+       * errors appearing after widget deletion.
+       *
+       * For more details, refer to the PR: https://github.com/appsmithorg/appsmith/pull/35820
+       */
+      if (widget.hasMetaWidgets) {
```
Comment (ashit-rath) [inline app/client/src/sagas/WidgetDeletionSagas.ts:265]: when we have a list widget inside another list widget and we delete the outer most list widget; is the inner list widget recursively called and their meta widgets are deleted?

File: app/client/src/sagas/WidgetDeletionSagas.ts [hunk 3]
```diff
@@ -253,6 +253,24 @@ function* deleteSaga(deleteAction: ReduxAction<WidgetDelete>) {
...
+        yield put({
+          type: ReduxActionTypes.DELETE_META_WIDGETS,
+          payload: {
+            creatorIds: [widgetId],
+          },
+        });
```
Comment (ashit-rath) [inline app/client/src/sagas/WidgetDeletionSagas.ts:271]: @jacquesikot Can you add a unit test for this saga that ensures the metawidgets are actually removed from the reducers once the saga is completed?. 
The cypress tests that you have added checks the debugger to have error but that's just the verifies the side-effect of the change but not the actual outcome.

File: app/client/src/sagas/WidgetDeletionSagas.ts (hunk 2 above)
Comment (jacquesikot) [reply app/client/src/sagas/WidgetDeletionSagas.ts:265]: @ashit-rath Yes, I have tested this scenario with 3 levels of nesting for list widgets, i.e List widget inside list widget, inside another list widget. Deleting the top most widget removes all other list widgets and corresponding meta widgets. I have also tested deleting from the inner most list widget and working my way out.

Comment (ashit-rath) [reply app/client/src/sagas/WidgetDeletionSagas.ts:265]: @jacquesikot Amazing!

File: app/client/src/sagas/WidgetDeletionSagas.ts (hunk 3 above)
Comment (jacquesikot) [reply app/client/src/sagas/WidgetDeletionSagas.ts:274]: @ashit-rath test has been added, please review

**Review by znamenskii-ilia — APPROVED** [review]

File: app/client/src/sagas/WidgetDeletionSaga.test.ts [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+      type: ReduxActionTypes.WIDGET_DELETE,
+      payload: {
+        widgetId: undefined,
+        parentId: undefined,
+        disallowUndo: false,
+      },
+    });
+
+    // Step 1: Check if widgetId is not provided, select the currently selected widget
+    result = generator.next();
```
Comment (ashit-rath) [inline app/client/src/sagas/WidgetDeletionSaga.test.ts:51]: @jacquesikot It's great that you add the test in such fine detail but testing a saga in this way make it very brittle to change so in practise its always best to run the saga completely and then assert. Otherwise any small change in the test like moving one yield above another will break the test but in actuality it's just some refactoring and no logical change.

For more context -> https://redux-saga.js.org/docs/advanced/Testing/#testing-the-full-saga

Search for `runSaga` in our codebase and you'll find a lot of examples. You can search in the ee code as well; there you may find much more examples than ce

**Review by ashit-rath — CHANGES_REQUESTED** [review]

**Review by ashit-rath — APPROVED** [review]
Amazing job @jacquesikot!
