### PR TITLE
fix: add query params from datasource to URI

### LINKED ISSUE #9962: [Bug]: REST API plugin: query params in datasource is not taking effect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Query params in datasource is not taking effect.

### Steps To Reproduce

1. Create REST API datasource.
2. Add a query query param to the datasource.
3. Execute an API action with the datasource and check that the query param is not passed over to the endpoint.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Add query params from datasource to final URI used for REST API query.

Fixes #9962 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit TC
- Manual

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java [hunk 1]
```diff
@@ -929,4 +929,34 @@ public void testHintMessageForDuplicateParamWithOneInstanceEachInActionAndDsConf
...
+        dsConfig.setQueryParameters(queryParams);
+
+        Mono<ActionExecutionResult> resultMono = pluginExecutor.executeParameterized(null, new ExecuteActionDTO(), dsConfig, actionConfig);
+
+        StepVerifier.create(resultMono)
+                .assertNext(result -> {
+                    assertTrue(result.getIsExecutionSuccess());
+                    assertNotNull(result.getBody());
+
+                    String expected_url = "\"https://postman-echo.com/post?query_key=query+val\"";
```
Comment (nidhi-nair) [inline app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:956]: Shouldn't this be encoded to %20? There's this whole set of opinions on how Java handles this but I think we handle this as %20 some other place. At least, especially when we do the url encoding from client side. Could you please check this?

**Review by nidhi-nair — CHANGES_REQUESTED** [review]

File: app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java (hunk 1 above)
Comment (sumitsum) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:956]: @nidhi-nair thanks for pointing this out. It seems that it could be either based on the use case (came as a surprise to me). Please check out this link: https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20 

Quoting from w3schools:
```
URLs cannot contain spaces. URL encoding normally replaces a space with a plus (+) sign or with %20.
```
Ref: https://www.w3schools.com/tags/ref_urlencode.ASP

Comment (nidhi-nair) [reply app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java:956]: TIL! :) Nice clarification of expectations.

**Review by nidhi-nair — APPROVED** [review]
