### PR TITLE
Fixed timeout error message, added new type of error for plugin timeout

### LINKED ISSUE #1422: [Bug] Improve Query / API Timeout error
## Description

When a query / API times out, the message is to check your internet connection

### Steps to reproduce the behaviour:
1. create a query
2. set the timeout to 10 ms
3. execute the query
4. See the error

The error should say "`QueryName` took longer than 10ms to execute"

### PR DESCRIPTION
**Pull request by nidhi-nair**
Fixed timeout error message, added new type of error for plugin timeout

Fixes #1422 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- JUnit test mocks timeout at 10ms (ActionServiceTest.testActionExecuteTimeout)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-interfaces/src/main/java/com/appsmith/external/pluginExceptions/AppsmithPluginError.java [hunk 1]
```diff
@@ -9,6 +9,7 @@
 
     PLUGIN_ERROR(500, 5000, "PluginExecution failed with error {0}"),
     PLUGIN_STRUCTURE_ERROR(500, 5001, "Plugin failed to get structure with error {0}"),
+    PLUGIN_TIMEOUT_ERROR(500, 5002, "Plugin execution for query \"{0}\" timed out in {1}ms. Please increase timeout duration in your action settings or check your backend action endpoint."),
```
Comment (trishaanand) [inline app/server/appsmith-interfaces/src/main/java/com/appsmith/external/pluginExceptions/AppsmithPluginError.java:12]: Could we throw a 504 error here?

File: app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java [hunk 2]
```diff
@@ -547,6 +548,12 @@ public NewAction extractAndSetJsonPathKeys(NewAction newAction) {
                                         .then(executionMono);
                             })
                             .timeout(Duration.ofMillis(timeoutDuration))
+                            .onErrorMap(TimeoutException.class,
```
Comment (trishaanand) [inline app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:551]: Could you try to reproduce stale connection error on your localhost to ensure that both timeouts and stale connection errors are being mapped correctly?

Comment (nidhi-nair) [reply app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java:551]: Added another test for this (testActionExecuteSecondaryStaleConnection)

**Review by trishaanand — APPROVED** [review]
