### PR TITLE
fix: Fix API url path stringification

### LINKED ISSUE #24696: [Bug]: API Path field string value getting JSON.stringified
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screenshot 2023-06-21 at 07 02 01

### Steps To Reproduce

Create new API, Type in URL as shared in the image above.

### Public Sample App

_No response_

### Environment

Release

### Issue video log

_No response_

### Version

Cloud

### PR DESCRIPTION
**Pull request by Irongade**
API Url Path field string were being further JSON Stringified showing a wrong output in the evaluatedvalue. This PR fixes that.

Fixes #24696

- Bug fix (non-breaking change which fixes an issue)
>
>
>
- [ ] Manual
- [ ] Jest
- [x] Cypress
>
>
#### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

### CODE REVIEW

**Review by AmanAgarwal041 — APPROVED** [review]

File: app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_EvaluatedValue_spec.ts [hunk 1]
```diff
@@ -7,4 +7,14 @@ describe("Validate API URL Evaluated value", () => {
...
     apiPage.EnterURL(`{{{"key": "value"}}}`, true, `{"key":"value"}`);
   });
+
+  // https://github.com/appsmithorg/appsmith/issues/24696
+  it("2. Check if path field strings have not been JSON.stringified - #24696", () => {
+    apiPage.CreateApi("SecondAPI");
+    apiPage.EnterURL(
+      `https://jsonplaceholder.typicode/{{SecondAPI.isLoading}}`,
+      true,
+      `https://jsonplaceholder.typicode/false`,
```
Comment (Aishwarya-U-R) [inline app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_EvaluatedValue_spec.ts:17]: Ade, can we try to use an api from TED instead of an external API here?

Comment (Aishwarya-U-R) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_EvaluatedValue_spec.ts:17]: Oh got it, so still TED url can be used still right? 
We are adding validation to stop usage any external apis during commits itself. So in future even if this is not run & simply used - will be prohibited. So better to start practicing to use TED api's for any need.

Comment (Irongade) [reply app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_EvaluatedValue_spec.ts:17]: Okay I understand, Can i fix this in another PR next week? This PR needs to really go in if possible.
