### PR TITLE
fix: Peek overlay overflowing in side by side

### LINKED ISSUE #33370: [Bug] - Peak overlay is getting cutoff in split view

### PR DESCRIPTION
**Pull request by albinAppsmith**
## Description

Peek overlay popover was getting cut off in the left side. This PR fix this issue.

Fixes #33370

## Automation

/ok-to-test tags="@tag.Sanity"

### :mag: Cypress test results

> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9059955985>
> Commit: a7a9a10ba4e2f0a9918f6ca8898fb9e9b321f0d1
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9059955985&attempt=1" target="_blank">Click here!</a>

## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: app/client/src/components/editorComponents/CodeEditor/PeekOverlayPopup/PeekOverlayPopup.tsx [hunk 1]
```diff
@@ -96,6 +96,11 @@ export function PeekOverlayPopUpContent(
     PEEK_OVERLAY_DELAY,
   );
 
+  const getLeftPosition = (position: DOMRect) => {
```
Comment (hetunandu) [inline app/client/src/components/editorComponents/CodeEditor/PeekOverlayPopup/PeekOverlayPopup.tsx:99]: Why are we not using the Popover here and its ability to avoid / contain within certain HTML elements. The absolute positioning feels like we would need to handle it whenever dimensions change

Comment (albinAppsmith) [reply app/client/src/components/editorComponents/CodeEditor/PeekOverlayPopup/PeekOverlayPopup.tsx:99]: This change requires a design overlook cause popover comes with it's on padding shadow and all... Will create a task and assign to Design team.

**Review by hetunandu — APPROVED** [review]
