### PR TITLE
fix: Updating page sagas for fixing the scroll position issue on page

### LINKED ISSUE #30481: [Bug]: Scroll Position Not Resetting When Navigating Between Pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user is on one page and has scrolled down, then navigates to another page either by clicking the respective page in the Navigation bar or by clicking a button where the NavigateTo method was used, the user is not directed to the top of the second page, but to a scrolled down position. It seems that the scroll position does not get reset when navigating between pages.

### Steps To Reproduce

1. Create 2 pages and add some widgets so that the content is longer and you need to scroll to get to the bottom of the pages.
2. Deploy the app.
3. Go to the first page and scroll to the bottom, then click on the second page in the navigation bar (or use a button placed at the bottom of the page with the `navigateTo` method).
4. Note that you will be directed lower on the second page and have to scroll up to reach the top.

### Public Sample App

https://app.appsmith.com/app/navigateto-scroll-issue/page1-65aa86044ffa034b7c300ccd

### Environment

Production

### Issue video log

https://www.loom.com/share/df64b68189ef4128a600e0896525a05b

### Version

v1.9.62

### PR DESCRIPTION
**Pull request by ankitakinger**
## Description

Updating `setupPageSaga` and `setupPublishedPageSaga` for fixing the scroll position issue on page

#### PR fixes following issue(s)
Fixes #30481 

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

#### How Has This Been Tested?
- [x] Manual
- [ ] JUnit
- [ ] Jest
- [ ] Cypress

#### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

#### QA activity:
- [ ] [Speedbreak features](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#speedbreakers-) have been covered
- [ ] Test plan covers all impacted features and [areas of interest](https://github.com/appsmithorg/TestSmith/wiki/Guidelines-for-test-plans#areas-of-interest-)
- [ ] Test plan has been peer reviewed by project stakeholders and other QA members
- [ ] Manually tested functionality on DP
- [ ] We had an implementation alignment call with stakeholders post QA Round 2
- [ ] Cypress test cases have been added and approved by SDET/manual QA
- [ ] Added `Test Plan Approved` label after Cypress tests were reviewed
- [ ] Added `Test Plan Approved` label after JUnit tests were reviewed

## Summary by CodeRabbit

- **Refactor**
	- Updated action types for page initialization in the editor.
	- Renamed action types for setting up published pages.

### CODE REVIEW

File: app/client/src/ce/reducers/uiReducers/editorReducer.tsx [hunk 1]
```diff
@@ -69,21 +69,21 @@ export const handlers = {
     }
     return state;
   },
-  [ReduxActionTypes.FETCH_PAGE_INIT]: (state: EditorReduxState) => ({
```
Comment (marks0351) [inline app/client/src/ce/reducers/uiReducers/editorReducer.tsx:72]: This might break other parts of the code from where fetchPage(FETCH_PAGE_INIT) is being called.
I would suggest to make changes to setupPageSaga by changing fetchPageSaga `call` into a `put`(dispatch action). use `take` api and wait for FETCH_PAGE_SUCCESS and then dispatch SETUP_PAGE_SUCCESS. same for published.
Let me know what you think?

**Review by marks0351 — CHANGES_REQUESTED** [review]

File: app/client/src/ce/reducers/uiReducers/editorReducer.tsx (hunk 1 above)
Comment (ankitakinger) [reply app/client/src/ce/reducers/uiReducers/editorReducer.tsx]: Sounds good. Pushed the change.

File: app/client/src/ce/sagas/PageSagas.tsx [hunk 2]
```diff
@@ -13,7 +13,7 @@ import type {
   CreatePageActionPayload,
   FetchPageListPayload,
 } from "actions/pageActions";
-import { createPage } from "actions/pageActions";
+import { createPage, fetchPublishedPage } from "actions/pageActions";
```
[the remark this answers is not in the document]
Comment (ankitakinger) [reply app/client/src/ce/sagas/PageSagas.tsx:16]: it is being used.

**Review by marks0351 — APPROVED** [review]
