### PR TITLE
Fix: Use connection pool for Redis

### LINKED ISSUE #4924: [Bug] Redis plugin: some cmds are not working
## Description
Reported by community: 
```
Socket error disappeared after the latest release. Now most of redis commands are not working.

Not Working

KEYS *
LRANGE <KEY-NAME> 0 -1
GET <KEY-NAME>


Working

SELECT <INDEX>
CLIENT LIST
```

### PR DESCRIPTION
**Pull request by sumitsum**
## Description
- Replace single connection instance with a connection pool. This will ensure that simultaneous actions don't fail / break the connection. 

Fixes #4924 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual. Created six actions and set them to on page load. Earlier I could see actions failing, but with this change no such failure is seen. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java [hunk 1]
```diff
@@ -136,40 +154,56 @@ public RedisPlugin(PluginWrapper wrapper) {
...
 
+
+        /**
+         * - Config taken from https://www.baeldung.com/jedis-java-redis-client-library
+         * - To understand what these config mean:
+         * https://www.infoworld.com/article/2071834/pool-resources-using-apache-s-commons-pool-framework.html
+         */
+        private JedisPoolConfig buildPoolConfig() {
+            final JedisPoolConfig poolConfig = new JedisPoolConfig();
+            poolConfig.setMaxTotal(128);
```
Comment (trishaanand) [inline app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java:165]: These numbers are too high. If possible, we should have a minimum of 1 and maximum of ~5? This ensures that we don't bombard the redis db with too many connections in case multiple datasources exist for the same db.

**Review by trishaanand — APPROVED** [review]
