### PR TITLE
fix: Auto height breaks for fixed modal's children

### LINKED ISSUE #18681: [Bug]: TypeError: Cannot read properties of undefined (reading 'bottomRow')
Sentry Issue: [APPSMITH-5CS](https://sentry.io/organizations/appsmith/issues/3770898865/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'bottomRow')
  at getParentCurrentHeightInRows (sagas/autoHeightSagas/helpers.ts:63:43)
  at call (sagas/autoHeightSagas/widgets.ts:444:49)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by riodeuno**
## Description
Fix issue where auto height was throwing an error when a fixed modal widget's children were changing height automatically

Fixes #18681

Before:

https://user-images.githubusercontent.com/103687/205632585-9dc28071-7dbc-408e-9010-71cf5b2e2699.mov

After:

https://user-images.githubusercontent.com/103687/205632610-3b52e00e-f7cf-48dc-8bd4-4b316151a0c6.mov

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Manual
- Cypress: [PENDING](https://www.notion.so/appsmith/Cypress-Test-scenarios-50557ff33f2745498396a4215b9a77ed)

### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

### CODE REVIEW

**Review by ankurrsinghal — APPROVED** [review]

File: app/client/src/sagas/autoHeightSagas/widgets.ts [hunk 1]
```diff
@@ -441,8 +441,44 @@ export function* updateWidgetAutoHeightSaga() {
...
+                    .bottomRow;
+                parentTopRow =
+                  dynamicHeightLayoutTree[parentContainerLikeWidget.widgetId]
+                    .topRow;
+              }
+
+              // If this is a modal widget, then get the bottomRow in rows
+              // as the height and bottomRow could be in pixels.
+              if (
+                parentContainerLikeWidget.detachFromLayout &&
```
Comment (rahulramesha) [inline app/client/src/sagas/autoHeightSagas/widgets.ts:465]: @riodeuno just to clarify, does parentContainerLikeWidget also include CANVAS_WIDGET type or just Container widget etc. Would it be better to Just Check for type instead if it is specific to modal widget.

Comment (riodeuno) [reply app/client/src/sagas/autoHeightSagas/widgets.ts:465]: @rahulramesha Yes, we're certain. The current widget itself is a `CANVAS_WIDGET`, its parent is going to be a container like widget, based on the way the DSL is designed.
